#+TITLE: "main"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-07-16 15:37:28 +0900
FILE_NAME: 2019-07-16-153728_main.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: kk  金沢地方検察庁 石川県警察
記事タイトル名の文字数：4　保存ファイル名の文字数：26

* モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士（東京弁護士会）の刑事告訴（名誉毀損）について

** 名誉毀損で刑事処罰の必要性をあらためて考えたストーカー事件被害者の警視庁を所管する東京都を提訴のニュース

*** 吉本興業岡本昭彦社長会見の速報中継、に至る経緯
    :LOGBOOK:
    CLOCK: [2019-07-22 月 15:20]--[2019-07-22 月 16:40] =>  1:20
    :END:

＞＞＞2019-07-22（月曜日）15：20＿［これからの記述範囲の開始時刻］＞＞＞

　テレビのミヤネ屋をみています。番組が始まってからずっとこの中継です。番組の終わりの方までこのまま続きそうですが、だとするとTOKIOのメンバーの会見以来のことかと思いながらみています。今回さらに異様に映るのは、参院選があった翌日ということです。

　数日前から準備が万端整っていたのですが、なぜか作業を再開する気にはならず、昨日の午後になって自分で思い当たる理由に気が付きました。それは参院選と立憲民主党のことです。大勢に影響を与えたくないという思いと、距離をおき遮断した状況で見極めておきたい思いがありました。

　参院選の結果は、私個人の期待には反して立憲民主党が議席を８つ増やしたようですが、それも経過報告のようなもので、とくに強調されるような話題としてはみていません。投票率が歴代２位と低かったそうですが、ずいぶん静かな参院選だったという印象があります。

　参院選の投票があった昨日は九州の久留米市などで大雨による大きな冠水被害も出たようですが、人的被害が出ていないためか、それも大きな報道ではなく、今日のテレビではほとんど報道を見ていないように思います。

　土曜日ではなかったかと思いますが、宮迫博之さんと田村亮さんの電撃的な記者会見がありました。解雇や引退という話が出ていたお二人ですが、まるでクーデターのような反転攻勢で、吉本興業の崩壊という話が出るほどの大問題に発展しました。

　まずは、土曜日の夜の新・情報７daysニュースキャスターだったと思いますが、番組の始まりからたぶん５０分ほどそのことが取り上げられていました。トップニュースに予想されていた京都アニメーションの放火殺人事件は、後回しでしたが、それでも１０分は放送があったと思います。

　７月１８日だったと思います。放火事件があったのは午前１０時３０分頃とされていましたが、最初に報道でしったのは１３時４０分過ぎのことで、バイキングからグッディへの引き継ぎで、安藤優子アナが、大きなニュースが飛び込んできました、などと切り出したのです。

　３４人が亡くなったという大事件で、放火事件としては平成以降最大の被害者数とテレビに見出しが出ていましたが、ネットでは昭和の時代を含めても、３０人を殺害した津山事件を上回る情報も出ていました。

　ネットで調べて確認したところ津山事件は昭和１３年の事件でした。ガソリンを使った放火殺人事件は、「新宿バス放火事件」というような事件がありましたが、これも心神喪失や被告訴人木梨松嗣弁護士と絡めて書いておきたいことがあります。

　吉本興業の記者会見ですが、ミヤネ屋ではエンディングロールが流れる直前に、天気予報の大雨警戒の短いニュースがあるまで、吉本興業一色で、それもずいぶんと否定的な強いくすぶりを残す終わり方でした。

　その少し前にチャンネルを石川テレビのグッディにかえたのですが、そのタイミングで斉藤さんという薄毛をネタに人気者となった芸人が、吉本興業の所属と言いながら、まったく躊躇することなく、会見の内容や吉本興業の社長をこきおろしていました。

　私が個人的に注目するのは、弁護士の対応の社会性です。文字通り爆発的な注目を集めた問題ですが、弁護士同士のやりとりが起爆剤となった一面がありそうです。これまでとは違った展開となっており、インハウスの弁護士ということですが、会見の冒頭で経過の説明をしていました。

　本来の火災とは別のものですが、炎上という表現は世間の批判やバッシングの嵐によく使われるものです。芸能界における吉本興業の存在や影響をつかみどころもないほど大きなものだと思いますが、まさに激震が走り、吹き飛んでしまう危機的状況が、さらに高まったという印象です。

　マスコミの報道にも引きずられた一面があるかと思いますが、数年に一度で社会的影響も大きい参院選の結果を、まったくそっちのけにして報道がされていたことになります。

　１１時５５分頃から始まる情報番組バイキングでも、冒頭にいつもは２，３あるラインナップを１つに絞り、いつもは別の話題やニュースをいくつか紹介してから本題に移ることの多い進行を、いきなり宮迫・田村会見という本題に切り込みました。私はその時点でテレビを消しました。

　ふたたびテレビをつけたのは１３時３０分過ぎであったように思います。バイキングではそのまま吉本興業の話題を続けていましたが、このあと午後２時ころから吉本興業社長の記者会見があるということで、弁護士が出るようなことも書いてあったと思うので、みることにしたのです。

　宮迫博之さんと田村亮さんがつけたという弁護士は２人と聞いたように思いますが、名前はもちろん弁護士という以外に具体的な情報は、これまでのところ一切みておりません。いずれ表に出てくるのかもしれませんが、裏方で動き、事態を大きく動かしたようにも思えます。

　もともとは宮迫博之さんや田村亮さんらの不始末で謝罪もしていたようですが、処分が厳しすぎたことや対応に不手際があったにせよ、それにマスコミが京都アニメーションの放火殺人事件や参院選の選挙結果のニュースをそっちのけで飛びつき、燎原の火の如く、大問題にしたという気もします。

　吉本興業になにかの落ち度や不手際があったとは考えられますが、このマスコミの便乗感と言いますか、大々的な拡散方針は、森友学園問題や事務次官のセクハラ問題、それに日大アメフト部の危険タックル問題に共通したものを感じます。

＜＜＜2019-07-22（月曜日）16：40＿［これまでの記述範囲の終了時刻］＜＜＜

