#+TITLE: "２０１９年０７月２４日、ブロックされていることに気がついた樋詰哲朗弁護士（金沢弁護士会）のTwitterアカウント"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-07-26 11:15:35 +0900
FILE_NAME: 2019-07-26-111535_２０１９年０７月２４日、ブロックされていることに気がついた樋詰哲朗弁護士（金沢弁護士会）のTwitterアカウント.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 樋詰哲朗弁護士（金沢弁護士会） 
記事タイトル名の文字数：57　保存ファイル名の文字数：79

* ２０１９年０７月２４日、ブロックされていることに気がついた樋詰哲朗弁護士（金沢弁護士会）のTwitterアカウント
  :LOGBOOK:
  CLOCK: [2019-07-26 金 11:17]--[2019-07-26 金 14:42] =>  3:25
  :END:

＞＞＞2019-07-26（金曜日）11：17＿［これからの記述範囲の開始時刻］＞＞＞

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「ブロック」の検索結果 - Twilog https://t.co/MMGdETBPLv

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-07-26 11:19／2019-07-24 20:34 URL： https://twitter.com/kk_hirono/status/1154576896920715264 https://twitter.com/s_hirono/status/1153991947402354689
&twitter(1154576896920715264){theme:light}
> 2019-07-24-202912_ブロックされています　弁護士樋詰哲朗（@hizumelaw）さん　／　Twitter.jpg https://t.co/KCkN0i9vuI
◁◁◁
<hr />

　樋詰哲朗弁護士（金沢弁護士会）のTwitterアカウントの存在を知ったのは、比較的最近のことかと思います。法律事務所の住所が金沢市橋場となっていて、ちょうどその橋場に注目していたタイミングだったのでよく憶えています。あるいは２度目以降の発見時かもしれません。

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「橋場」の検索結果 - Twilog https://t.co/HRZmvVcWP6

<hr />

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「橋場」の検索結果 - Twilog https://t.co/I0xFU4BkoE

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-26 11:26／2018-11-26 08:17 URL： https://twitter.com/kk_hirono/status/1154578659476480000 https://twitter.com/hirono_hideki/status/1066833340940972032
&twitter(1154578659476480000){theme:light}
> 2443： ＃　金沢市橋場にあったパチンコ店と、昭和６３年当時の金沢市場輸送の運転手 https://t.co/0D61Zoq3s1
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-26 11:26／2013-11-20 19:12 URL： https://twitter.com/kk_hirono/status/1154578685577420800 https://twitter.com/hirono_hideki/status/403103562726932480
&twitter(1154578685577420800){theme:light}
> 東茶屋街 - Google マップ http://t.co/emhKMShOGl 初めて調べてみましたが思っていたより大通りから入り込んだ場所なので、たぶん行ったことはないと思います。テレビで見かけるようになったのもここ10年ぐらいからという気もします。橋場のバス停から徒歩5分。
◁◁◁
<hr />

　奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントで「橋場」を含むツイートが２件しかなかったのは意外でした。告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)の方が思いの外多い数でした。

　次に樋詰哲朗弁護士（金沢弁護士会）についてです。Twilogの検索結果は出ていますた。奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントで、最初に出てきたものが今年の３月２５日でした。昨年から存在をしっていたように思っていたので意外でした。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-26 11:30／2019-03-25 16:42 URL： https://twitter.com/kk_hirono/status/1154579793293139968 https://twitter.com/hirono_hideki/status/1110084564125270016
&twitter(1154579793293139968){theme:light}
> 石川県金沢市の弁護士　樋詰哲朗 | 交通事故、破産・民事再生、相続、離婚から、中小企業法務（労働問題、契約書作成、債権回収等）を扱っています。石川県・富山県・福井県を中心に対応しています。 https://t.co/I7oL9LfNv2
◁◁◁
<hr />

　ざっと数えたところ「樋詰哲朗」をキーワードに含むツイートは８つです。次にキーワードをTwitterアカウントの「@hizumelaw」にして検索をやってみます。これはメンションという通知にもなりうるので、ブロックされた原因とも推定されるものです。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「@hizumelaw」の検索結果 - Twilog https://t.co/4TuDQEScyQ

<hr />

　結果は同じく８件でした。「樋詰哲朗」をキーワードに含む最も古いツイートは今年の３月２５日でしたが、これも少々意外な結果で「@hizumelaw」を含むものは５月３０日が最初でした。

　ブロックされていたことで、改めて樋詰哲朗弁護士（金沢弁護士会）について調べてみたのですが、金沢市出身ということでかなり驚きました。勝手なイメージだったのかもしれないですが得た情報から、石川県外の都会の方から来た人というイメージを持っていたように思います。

　生年も確か１９７２年となっていたと思います。平成４年当時、２１歳だった被害者安藤文さんが昭和４５年の１９７０年生まれなので、その２つ年下と考えられます。これは同じ平成４年、１９歳だった被告発人多田敏明と同じ歳になるかと思われます。

　被告発人多田敏明の供述調書には生年月日の記載もありましたが、よくは憶えていません。ただ学年の違いにもなる１月から３月の生まれではなかったように思います。

```
１９７２年　石川県金沢市に生まれる
１９９１年　金沢二水高校　卒業
１９９６年　中央大学法学部法律学科　卒業
２００６年　中央大学法科大学院　卒業
２００８年　最高裁判所司法研修所
２００９年　金沢弁護士登録
２０１１年　弁護士法人あさひ法律事務所勤務

弁護士会所属委員会
刑事弁護センター委員会
犯罪被害者支援委員会
高齢者・障がい者支援センター委員

中央大学法学部通信教育課程インストラクター

［source：］プロフィール | 石川県金沢市の弁護士　樋詰哲朗 http://hizumelaw.com/profile/
```

　確認しましたが、生まれた月の記載はありませんでした。なお、落合洋司弁護士（東京弁護士会）は私と同じ１９６４年（昭和３９年）生まれですが、誕生日が１月から３月の間だったので、学年は１つ年長ということになります。

　次に、現在は記録用のスクリーンショット以外に投稿はしていない非常上告-最高検察庁御中_ツイッター（@s_hirono）のアカウントのTwilogを見ておきたいと思います。

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「樋詰哲朗」の検索結果 - Twilog https://t.co/SNoKfPsghZ

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-07-26 11:57／2019-03-25 16:16 URL： https://twitter.com/kk_hirono/status/1154586390031507457 https://twitter.com/s_hirono/status/1110077961489702912
&twitter(1154586390031507457){theme:light}
> 2019-03-25-155430_弁護士樋詰哲朗（@hizumelaw）さん　｜　Twitter.jpg https://t.co/QzuapoDTjG
◁◁◁
<hr />

　ざっと数えて１７件のツイートがありました。すべてスクリーンショットのツイートだと思います。少なくともここ２，３年、非常上告-最高検察庁御中_ツイッター（@s_hirono）のアカウントでスクリーンショット以外の投稿をした記憶はありません。

　こちらも今年３月２５日が最初のものです。意外と最近なのだとあらためて思いました。３月２５日頃といえば、性犯罪の４つの無罪判決で、法クラたちが盛り上がっていた時期です。

　最初に樋詰哲朗弁護士（金沢弁護士会）のTwitterアカウントのページをみたとき、まず目を引いたのが減っだ画像の写真の建物です。これは金沢地方裁判所の新庁舎ではないかと思いました。実際に見たことはない建物ですが、裁判のニュースではテレビでよく見かけています。

　実は、本日２０１９年０７月２６日、金沢地方裁判所で判決が出るという刑事事件があります。懲役８年の求刑が出たというニュースを見たのも、２，３日前のことです。あるいは樋詰哲朗弁護士（金沢弁護士会）にブロックされていると気がついたのと同じ日かもしれません。

　ネットでも全国ニュースにはなっていないようでしたが、かなり異例の刑事裁判かと思います。個人的に注目度が高いのは、平成４年の傷害・準強姦被告事件で被害者安藤文さんに大怪我を負わせてしまった現場にかなり近い場所での事件で、金沢港の大野埠頭になります。

　注目されていないのがとても不思議な事件でもあります。昨日かあるいは一昨日になると思いますが、北陸中日新聞の記事もかなり小さな扱いでした。北國新聞の記事はまだ確認していないですが、宇出津図書館での保存も一週間ぐらいと思うので、忘れないようにしたいとは考えています。

　時刻は１２時１２分です。ついさきほど気がついてパソコンの時計を見ると、１２時１０分でした。１１時３０分からテレビでニュース番組をみるつもりでいたのですが、すっかり忘れていてテレビは消したままの状態です。既に判決は出ていて、石川県内ニュースになっている可能性もあります。

[link:] » 金沢地裁 - Google 検索 https://t.co/cTv8iWapKb

<hr />

　まだ判決のニュースは出ていないようですが、検索結果のトップに意外なニュースが出ています。「エキサイトニュース　１時間前」とも表示されています。

```
約30年前に通っていた県内の小学校で当時の教頭からわいせつ行為を受けて精神的苦痛を被ったとして、金沢市の40代女性が元教頭で富山市の80代男性に約1100万円の損害賠償を求めた訴訟の判決で、金沢地裁（加島滋人裁判長）は25日、請求を棄却した。民法で賠償請求権が消滅すると規定された「除斥期間」（20年）を過ぎていると判断した。

［source：］「30年前に教頭わいせつ」元児童の請求棄却　「除斥期間」経過と判断　金沢地裁 (2019年7月26日) - エキサイトニュース https://www.excite.co.jp/news/article/Mainichi_20190726k0000m040052000c/
```

　次の部分が除斥期間に関する原告側の主張のようです。本人訴訟でこのようなニュースになるとも考えにくですが、代理人弁護士などの情報は、この記事に見当たりません。

```
原告側は、女性は心的外傷後ストレス障害（PTSD）を発症し、症状が最もひどかったのは2003年ごろだったため除斥期間には当たらないと主張していた。【岩壁峻】

［source：］「30年前に教頭わいせつ」元児童の請求棄却　「除斥期間」経過と判断　金沢地裁 (2019年7月26日) - エキサイトニュース https://www.excite.co.jp/news/article/Mainichi_20190726k0000m040052000c/
```

　この件に限らないですが、石川県の裁判のニュースや記事で、弁護士の名前を見たことは、もう何年も一度もないように思います。主張やコメントのようなものが出ても、名前がないので幽霊や亡霊のような得体の知れない存在感を受けることもありました。

　金沢弁護士会の弁護士で、Twitterアカウントというのは、この樋詰哲朗弁護士（金沢弁護士会）ともう一つ確認しています。ブックマークにもしていないのでここ最近はみていないですが、安藤という名前の弁護士です。

　樋詰哲朗弁護士（金沢弁護士会）と同じくプロフィールの写真が自身の顔写真になっていましたが、若くてひょうきんな感じの弁護士で、おどけたような表情の写真が掲載されていました。

　安藤という名前は、全国的にかなり多い名前かと思われます。はっきり確認はしていませんが、少なくとも多い名前の２０位以内には入っていそうに思えます。まあ、ネットで調べて確認はできそうです。

```
【全国順位】 69位 
【全国人数】 およそ231,000人

［source：］安藤さんの名字の由来や読み方、全国人数・順位｜名字検索No.1／名字由来net｜日本人の苗字・姓氏99%を掲載!! https://myoji-yurai.net/searchResult.htm?myojiKanji=%E5%AE%89%E8%97%A4
```

　６９位というのは意外に少ない結果でした。佐藤や斎藤となるとトップに近いように聞いた憶えがあり、その印象が強すぎたのかもしれません。「安藤さんの多い地域」という色分けの日本地図もありますが、石川県は全国的に少ないようです。

　ちょっと珍しい名前で近い地域だと親戚の可能性というのも考えますが、宇出津で同じ名前でもまったく無関係という話はけっこう聞いてきました。考えてみると、能登で安藤という名前は、自分のこれまでの生活で聞いたことはない気がします。

　私が金沢弁護士会で安藤という名前の弁護士にこだわるのは、それだけの理由があって、告発事件の大きなキーポイントの１つとも考えています。そのカギを握るのも被告発人多田敏明になります。

　２，３年前には、他にも２人ほど金沢弁護士会所属の実名弁護士アカウントをみていました。一人は法律事務所が金沢中央卸売市場の近くで、金石街道沿いになります。久しぶりに思い出したのですが、もう長い間、ツイートも見かけておらず、存在の確認もしていません。

　いけるかどうかわからないですが、「寛容な」をキーワードに捜し出すことが出来るかもしれません。

[link:] » 寛容な - Twitter検索 / Twitter https://t.co/GkvumlZuQU

<hr />

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「寛容な」の検索結果 - Twilog https://t.co/FBTKJ56Ddr

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-26 12:45／2017-10-07 13:32 URL： https://twitter.com/kk_hirono/status/1154598635050397696 https://twitter.com/hirono_hideki/status/916521699373285377
&twitter(1154598635050397696){theme:light}
> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: ＼寛容な鹿島啓一　@sunmi2017＼広弁いいね。金沢弁護士会でも面白いことやろうってやる気出てきた。 https://t.co/n5ZJ4E27lz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-26 12:45／2017-10-25 00:37 URL： https://twitter.com/kk_hirono/status/1154598672157425665 https://twitter.com/hirono_hideki/status/922849514385424384
&twitter(1154598672157425665){theme:light}
> ＼寛容な鹿島啓一　@sunmi2017＼ #松平浩一 さんは，本日の北陸中日新聞によると，石川県内に事務所を構えるかは未定との事。#立憲民主党 の候補者すらいないこの北陸の地に https://t.co/PmRd2hV6th
◁◁◁
<hr />

　もう３，４年前とも考えていたのですが、初出の記録が２０１７年１０月０７日でした。連続テレビ小説まれ、の放送があったのが２０１５年になるので、その頃のことかと思っていました。

　@sunmi2017の部分がリンクとなっているので、アカウント自体は現存しているように見えますが、Twilogなのであるいは、通常のツイートとは違っているのかも知れません。リンクを開けばすぐに確認できることではあります。

```
鹿島啓一
@sunmi2017
金沢弁護士会。60期。原発訴訟やってます。立憲民主党をフォローしたくてツイッター始めてみました。支持者だからこそ立憲民主党を監視 したい。（福山幹事長(link： https：//twitter.com/cdp2017/status/921667180449562624) twitter.com/cdp2017/status…）ヘッダー画像は福井県美浜町のめっちゃきれいな水晶浜と美浜原発。
石川 金沢市誕生年： 1978年2017年10月からTwitterを利用しています
59 フォロー中
73 フォロワー

［source：］鹿島啓一（@sunmi2017）さん / Twitter https://twitter.com/sunmi2017
```

　「寛容な」という部分が外れたままアカウントは残っているようですが、２０１８年１月１３日のツイートを最後に更新はないようです。１つリツイートをしておきます。その最後のツイートです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sunmi2017（鹿島啓一） 日時：2019-07-26 12:54／2018-01-13 10:21 URL： https://twitter.com/kk_hirono/status/1154600933923282944 https://twitter.com/sunmi2017/status/951987519347814400
&twitter(1154600933923282944){theme:light}
> 大阪地裁に申し立てた大飯原発3,4号機運転差止仮処分事件の裁判官が決まりました。大阪地裁民事第1部の森純子裁判官、谷口哲也裁判官、黒木宏太裁判官です。どの裁判官がどんな裁判をするのかということに多くの人が注目するようになれば日本は変わると思います。#原発裁判
◁◁◁
<hr />

　鹿島啓一弁護士のTwitterのアイコンは、女性のような漫画のアップですが、これは以前見たときと同じものと思います。ヘッダ画像の風景写真も、おそらく変わっていないように思いますが、今回、福井県の美浜原発の写真だと気が付きました。

　さきに写真を見ていて、石川県の風景写真としてはあり得ないと考えていたのですが、そのあと鹿島啓一弁護士のプロフィールを読むと、「ヘッダー画像は福井県美浜町のめっちゃきれいな水晶浜と美浜原発。」という説明がありました。

　海岸線にかなり大きな建造物が見えると、最初に思っていたのですが、何度見てもずいぶん大きく見えます。私は仕事の関係で石川県羽咋郡の志賀原子力発電所の敷地内に入ったことがあるのですが、特に大きな建造物だったという印象は残っていません。

　福井県は原発が多いことで有名ですが、その全ては若狭地方の海岸線に集中していたかと思います。敦賀市から京都府の舞鶴市まで国道２７号線で、ところどころ海岸線が見えるところもあったのですが、原発のような建物を見たという記憶はありません。長距離トラックでよく通行していました。

　以前は原発の訴訟のニュースというのもテレビでよく見かけていました。石川県にあるのは志賀原子力発電所だけですが、全国的にも集中していると聞く福井県の原発で、控訴審が名古屋高裁金沢支部の管轄だったので、なにかと目に触れる機会も多かったのだと思います。

　鹿島啓一弁護士についてGoogle検索で調べたのですが、人権や憲法について興味深い記事を発見しました。これも別のかたちで取り上げておきたいと思います。

　そういえば、一月ほど前に志賀原子力発電所でボヤのような火災があったというニュースを見たように思い出しましたが、原発の差し止め訴訟などとなると、もう長い間、ニュースも見かけていないように思います。数年前は活断層とかも問題にされていました。

[link:] » 金沢　弁護士 - Twitter検索 / Twitter https://t.co/RgeFpJLAKd

<hr />

　Twitterの短縮URLになっていますが、本来のURLの末尾は「&f=user」となっています。＆というのは複数の指定の連結だったと思いますが、これはリクエストパラメータと呼ばれるもので、ｆという変数の値にuserを入れているようです。

　具体的にはTwitter検索の「アカウント」というタブの指定になりますが、「金沢　弁護士」の検索結果は１つだけでした。全角スペースを使っていますが、半角数字にしても結果は同じと確認しました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜benuchida（内田清隆-金沢市の弁護士） 日時：2019-07-26 13:24／2014-09-21 16:06 URL： https://twitter.com/kk_hirono/status/1154608448769626112 https://twitter.com/benuchida/status/513585124135292928
&twitter(1154608448769626112){theme:light}
> あ
◁◁◁
<hr />

　投稿の数は３３２件と少なくないですが、上記の２０１４年９月２１日の投稿を最後に更新はなく、放置状態となっているようです。これらはプロフィールにホームページのURLのようなものが見えます。

[link:] » 内田清隆法律事務所（石川県金沢市の弁護士事務所） https://t.co/gw9iTK5jgg

<hr />

　なかなか本格的な商業用ホームページという感じですが、「ごあいさつ」として次の文章が掲載されています。

```
弁護士業は、「士」という文字からサムライ業とも呼ばれます。
私たちは、「新時代のサムライ魂」をモットーに、「裁判で勝つ」「交渉で勝つ」シンプルな強さ、「曲がったことは許さない」という素朴な正義感という伝統的な弁護士魂を大切にします。
一方で、スピードを重視し、「何もなくても行きたい」と思っていただく高品質なサービスを提供し、今までとは違う新時代にふさわしい法律事務所を目指します。

［source：］内田清隆法律事務所（石川県金沢市の弁護士事務所） http://www.uchida-houritsu.com/
```

　ホームページには左側のメニューのトップの目立つ場所に「2019/06/03　弁護士内田がカリフォルニア州司法試験に合格しました」という掲載があります。つい最近の近況のようですが、Twitterの方が２０１４年９月から放置状態となっているのも、なぜかと気になります。

　この内田清隆弁護士も鹿島啓一弁護士のTwitterアカウントと同じ頃に見ていたと記憶にあるのですが、２０１４年９月から更新がなかったとすると、ずいぶん前の投稿をそうとも意識せずに見ていたような気がします。

　弁護士の士業をサムライとするのは、最初に高野隆弁護士のブログで見ていました。２００８年頃のことかと思いますので、もうずいぶんと前になります。比較の上でも一緒に考えることが多かったのが、輪島市の海士町で、歴史的にも舳倉島での海女漁が中心だったようです。

　内田清隆弁護士については、数年前にもなにかコメントを読んで、ずいぶんと積極果敢な姿勢は感じていましたが、金沢弁護士会にサムライを意識する弁護士がいたというのも、身近に考えさせられるところです。

　内田清隆弁護士も個人事務所というイメージがあって、それを確認しようとホームページの「弁護士紹介」というメニューのようなリンクを開いたのですが、ここでも全く意外な発見がありました。

```
内田　清隆
生年月日
1973年10月18日
出生地
東京都品川区
学 歴
1992年	私立開成学園高等学校卒業
1999年	東京大学文学部社会学科卒業
　	　
経 歴･公 務
2001年～2004年	野田政仁法律事務所勤務
2004年～現在	内田清隆法律事務所長
2006年～2007年	金沢市包括外部監査補助者
2007年～現在	日本弁護士連合会・人権擁護委員会
2007年～現在	暴力追放相談委員
2009年～現在	弁護士知財ネット会員
2009年～2010年	金沢弁護士会副会長
2009年～現在	「ネットチェッカーズいしかわ」アドバイザー
2010年～現在	ITビジネスプラザ専門家相談員
2011年～現在	法とコンピュータ学会
2013年～現在	金沢市指定管理者選定委員
2014年～現在	内灘町情報公開審査委員会会長
2014年～現在	（一社）発明協会　窓口知財専門家

［source：］内田清隆法律事務所（石川県金沢市の弁護士事務所）：弁護士紹介 http://www.uchida-houritsu.com/lawyer.html
```

　出身地が東京都品川区となっていて、こちらは移住者の可能性もありそうですが、経歴公務として最初にあるのが「2001年～2004年	野田政仁法律事務所勤務」です。昨日、久しぶりに問題性を考えていた弁護士ですが、平成１１年の安藤健次郎さんの事件での一審国選弁護人です。

　あまり詳しいことは知らないですが、司法試験に合格した後の司法修習では、修習地というのがあるそうです。本人の希望も考慮されるようですが、修習を終えた後、その修習地で弁護士としてのスタートをきる人も少なからずいるようです。

　向原栄大朗弁護士は、大阪府の出身で、鹿児島が修習地になったことで縁が出来、同じ九州の福岡市で独立開業するに至ったという話をツイートで見たように思います。

　２００１年といえば、平成１３年ですが、司法制度改革が始まっていたのか微妙な端境期のように思われます。司法制度改革の目玉として見た憶えはないのですが、司法修習の期間がそれまでの２年から１年に短縮されたのも、それに近い時期であったような気がします。

```
修習期間［編集］
司法制度改革(法科大学院の設置等)の影響などにより、修習期間は短縮されてきている。

旧司法試験合格者対象の司法修習
第52期（1998年4月修習開始）まで - 2年
第53期（1999年4月修習開始）から第59期（2005年4月修習開始）まで - 1年6か月
第60期（2006年4月修習開始）から - 1年4か月
新司法試験合格者対象の司法修習
新60期（2006年11月修習開始）から - 1年

［source：］司法修習 - Wikipedia https://ja.wikipedia.org/wiki/%E5%8F%B8%E6%B3%95%E4%BF%AE%E7%BF%92
```

　初めて知ったと思うのですが、いきなり２年から１年に短縮されたわけではなく、１年６か月、１年４か月と段階的な経過があったようです。平成１１年４月から短縮が始まったようですが、すでに司法制度改革が実現の運びとなっていたとは、意外でした。

　その平成１１年の８月１２日に私は安藤健次郎さんに対する傷害事件で金沢中警察署に逮捕されていますが、金沢地方検察庁では司法修習生の集まった部屋で、司法修習生の一人に取り調べや調書の作成も受けています。その部屋というか教室で教官だったのが、下平豪検事になります。

　人数を数えたこともなかったので正確なことは言えないですが、教室はコの字のように向かい合って机が並び、７人ずつの１４人ぐらいだったように思います。それぞれの机の上に、当時はずいぶん高価でもあったノートパソコンが置かれていたのが壮観でした。

　修習２年目だったという可能性もありそうですが、その可能性を含め５２期か５３期が、そのときの金沢地方検察庁での司法修習生だったということになるようです。弁護士のTwitterでもこの修習の期というのはよく見かけるものですが、５３期というのもずいぶん古い人に感じていました。

　司法修習でのGoogle検索のトップに出てきたのですが、７２期というのが最新の司法修習なのかもしれません。私は現時点で最新の司法修習を受けているのが７３期ではないかと考え、その旨、記述したこともあるかと思います。

```
【第72期司法修習生の方】
牛島総合法律事務所では、第72期司法修習生の方も積極的に採用しております。企業法務にご興味をお持ちの方は、お気軽にお問い合わせ下さい（2019年6月27日更新）。

［source：］個別訪問 | 採用情報｜牛島総合法律事務所 https://www.ushijima-law.gr.jp/recruit/attorney/homon/
```

　牛島という名前の弁護士で知っているのは一人だけですが、大物感のある弁護士で、２，３か月前にもテレビのそこまで言って委員会NPで出演を見たように思います。すぐに確認は出来なかったですが、牛島総合法律事務所は弁護士が５０名とのことです。

　個人事務所のようなイメージが残っていた内田清隆弁護士の法律事務所ですが、弁護士紹介として全部で４名の顔写真付きプロフィールがありました。なかには経歴で弁護士ではないように思える人もいるのですが、写真には弁護士バッチをスーツにつけているように見えます。

```
永來　宏隆
生年月日
1987年8月16日
出生地
奈良県
学 歴
2006年	奈良学園高等学校卒業
2012年	慶應義塾大学総合政策学部卒業
2015年	一橋大学大学院法学研究科法務専攻修了
　	　
経 歴･公 務
2017年～	内田清隆法律事務所勤務
 	 
モットー
躓く石も縁の端

［source：］内田清隆法律事務所（石川県金沢市の弁護士事務所）：弁護士紹介 http://www.uchida-houritsu.com/lawyer.html
```

　上記に当該箇所を引用しましたが、見たこともない名前で、なんと読むのかわかりかねます。永來宏隆という名前ですが、読みのわからない二文字目は、鳥取県米子市に隣接した島根県の市町村名にあったような気がします。なにか民謡のような踊りの名前にもなったいたかと思います。

```
永來　宏隆　　えいらい　ひろたか
内田清隆法律事務所

［source：］弁護士を探す（弁護士名から探す）｜金沢弁護士会 http://www.kanazawa-bengo.com/search/list/
```

　金沢弁護士会のホームページで永來宏隆弁護士と、弁護士であることを確認しましたが、それにしては事務員なのかと間際らしいプロフィールでした。「えいらい」と読むようです。あるいは来の旧字体なのかもしれないですが、余り見かけることのない漢字だと思います。

　検索に取り掛かったところで思い出したのですが、島根県の地名は安来市ではなかったかと思います。「安来節」というのも思い出したのですが、これは近年、テレビで何度か群馬県の名物として見ているような気がします。

```
安来節（やすぎぶし）は島根県安来市の民謡である。「どじょう踊り」という滑稽なおどりを含み、総合的な民俗芸能として、大正期を中心に全国的人気を博した［1］。

［source：］安来節 - Wikipedia https://ja.wikipedia.org/wiki/%E5%AE%89%E6%9D%A5%E7%AF%80
```

　どうも群馬の方は「八木節」だったようですが、文字ではなく言葉として耳にすると「やすきぶし」と「やぎぶし」で混同をしていたようです。

　島根県の安来市は、国道９号線で九州方面に向かう時、夕方の早い時間に通過することが多かったのですが、国道沿いにちょっと変わった岩のような山があるのが印象的でした。大きさは余り記憶にないですが、似ていると思うのが能登町の恋路海岸にある道路沿いの岩でした。

＜＜＜2019-07-26（金曜日）14：42＿［これまでの記述範囲の終了時刻］＜＜＜


