#+TITLE: "参考資料／ジャーナリスト／ジャーナリストの江川紹子氏／【速報】わいせつ罪に問われた外科医に無罪判決（江川紹子）　-　Y！ニュース"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-02-20 15:16:27 +0900
FILE_NAME: 2019-02-20-151627_【速報】わいせつ罪に問われた外科医に無罪判決（江川紹子）　-　Y！ニュース.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  ジャーナリストの江川紹子氏 モトケンこと矢部善朗弁護士（京都弁護士会） 無罪判決 高野隆弁護士 医療問題
記事タイトル名の文字数：64　保存ファイル名の文字数：59

#contents

* モトケンこと矢部善朗弁護士（京都弁護士会）のTwitterの更新で発見した「【速報】わいせつ罪に問われた外科医に無罪判決（江川紹子）」という記事
  :LOGBOOK:
  CLOCK: [2019-02-20 水 15:21]--[2019-02-20 水 23:31] =>  8:10
  :END:

＞＞＞2019-02-20（水曜日）15：21＿［これからの記述範囲の開始時刻］＞＞＞

　テレビでミヤネ屋をみながら、モトケンこと矢部善朗弁護士（京都弁護士会）のTwitterタイムラインで、一番上の辺りのツイートを見ている時に、更新がありました。更新をクリックすると出てきたのがジャーナリストの江川紹子氏の記事紹介のツイートでした。

　以前ならスクープと呼ばれたものになるのか、文字通りの速報で、テレビでもネットでもまだジャーナリストの江川紹子氏の記事以外のものを見ていません。Twitterのトレンドにもありませんでした。

　もっとも今日あたりに判決があることは、私も知っていました。たぶん同じジャーナリストの江川紹子氏の同じ問題を取り上げた記事で、判決の期日が書いてあったと思います。半月ほど前に見ていたように思いますが、だいたい２月の１６日から２０日あたりだと思っていました。

　時刻は１５時４０分です。テレビのグッディで２件のニュースがあったところですが、１つはミヤネ屋が番組の冒頭で取り上げていた朝霞市の少女誘拐事件の控訴審判決で、もう２つは、不在票でクレジットカードをだまし取った夫婦というようなニュースでした。

［link：］ 女子中学生を2年監禁　寺内被告に懲役12年　東京高裁判決（毎日新聞） - Yahoo!ニュース https://headlines.yahoo.co.jp/hl?a=20190220-00000033-mai-soci

［link：］ 他人の不在連絡票を使いクレカを詐取した疑い 無職の夫婦を逮捕 - ライブドアニュース http://news.livedoor.com/article/detail/16047995/

　無職の夫婦とありますが、グッディの中のプライムニュースでは、暴力団の組長でグループとして同種の余罪があるようなことも報じていました。同じニュースでもずいぶん事件の印象が変わるものだと思いました。たまにあることです。

　懲役１２年と控訴審判決が出た事件は、見出しをみると監禁罪のようです。監禁罪の懲役刑の上限というのは高くなかったように思いますが、ミヤネ屋の放送によると検察の求刑が懲役１５年とのことでした。一審が懲役９年だったということですが、よく覚えていませんでした。

```
埼玉県朝霞市で2014年、当時中学1年だった少女を誘拐し約2年間自宅に監禁したとして未成年者誘拐などの罪に問われた寺内樺風被告（26）の控訴審判決で、東京高裁（若園敦雄裁判長）は20日、懲役9年とした1審判決を破棄し、懲役12年を言い渡した。

［source：］女子中学生を2年監禁　寺内被告に懲役12年　東京高裁判決（毎日新聞） - Yahoo!ニュース https://headlines.yahoo.co.jp/hl?a=20190220-00000033-mai-soci
```

　記事の本文には、「未成年者誘拐などの罪」とありますが、記事の見出しだけをみると、これも誤解を与えそうな気がしなくはありません。

```
逮捕・監禁罪（たいほ・かんきんざい）は、刑法220条に規定されている罪。 不法に人を逮捕し、または監禁する行為を内容とする。法定刑は3月以上7年以下の懲役（組織的な様態の場合は組織犯罪処罰法3条1項8号が適用され3月以上10年以下の懲役）。 逮捕・監禁の結果として傷害または死亡の結果が生じた場合には、逮捕・監禁致死傷罪（刑法221条）に該当する。

［source：］逮捕・監禁罪 - Wikipedia https://ja.wikipedia.org/wiki/%E9%80%AE%E6%8D%95%E3%83%BB%E7%9B%A3%E7%A6%81%E7%BD%AA
```

　調べると逮捕・監禁罪は３月以上７年以下の懲役とあります。以前の強制わいせつ罪が同じぐらいの量刑だったと思いますが、強制わいせつ罪の方は法定刑が引き上げられていたような気もします。

```
第176条
13歳以上の者に対し、暴行又は脅迫を用いてわいせつな行為をした者は、6月以上10年以下の懲役に処する。13歳未満の者に対し、わいせつな行為をした者も、同様とする。

［source：］刑法第176条 - Wikibooks https://ja.wikibooks.org/wiki/%E5%88%91%E6%B3%95%E7%AC%AC176%E6%9D%A1
```

　Googleの検索結果の上部には、６月以上７年以下の懲役と表記する情報が見られたのですが、やはり上限が１０年に引き上げられていたようです。また、ジャーナリストの江川紹子氏の記事もトップ扱いのような表示となっていました。スクリーンショットを記録しました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-20 16:11／2019-02-20 16:09 URL： https://twitter.com/kk_hirono/status/1098117863326441474 https://twitter.com/s_hirono/status/1098117402577985536
&twitter(1098117863326441474){theme:light}
> 2019-02-20-160409_強制わいせつ罪　-　Google　検索.jpg https://t.co/M5VbHW2SEi
◁◁◁
<hr />

　モトケンこと矢部善朗弁護士（京都弁護士会）のTwitterタイムラインの方もスクリーンショットで記録しています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-20 16:13／2019-02-20 15:09 URL： https://twitter.com/kk_hirono/status/1098118353703456768 https://twitter.com/s_hirono/status/1098102244891754496
&twitter(1098118353703456768){theme:light}
> 2019-02-20-144847_モトケンさんがリツイート＞　ShokoEgawa（@amneris84）：　【速報】わいせつ罪に問われた外科医に無罪判決（江川紹子）-Y!ニュース.jpg https://t.co/T6oACOMHB3
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-20 16:13／2019-02-20 15:09 URL： https://twitter.com/kk_hirono/status/1098118379376758784 https://twitter.com/s_hirono/status/1098102317667078145
&twitter(1098118379376758784){theme:light}
> 2019-02-20-145248_モトケンさんがリツイート＞　オタ小児科医（@otapediatrician）：　じゃあ何でさっきみたいなツイートわざわざするかって言うと、自分のツイート.jpg https://t.co/uR3AjjUYPG
◁◁◁
<hr />

　今日はテレビでずいぶん前に見たニュースの続報もありました。東京都の八王子市の近くだったと記憶しますが、生後１０が月ほどの女児が、祖父母宅の家で、家の中で放し飼いになっていた大型犬にかまれ亡くなったという事故でした。書類送検されたというニュースだったので事件になったようです。

```
南大沢署によると、祖父母は２０１７年３月９日午後４時３５分ごろ、八王子市の自宅で放し飼いにしていたゴールデンレトリバーが危害を加えないように注意する義務を怠った疑いがある。孫の乳児が頭をかまれ、失血死した。

［source：］犬にかまれ１０カ月の乳児死亡　容疑の祖父母を書類送検（朝日新聞デジタル） - Yahoo!ニュース https://headlines.yahoo.co.jp/hl?a=20190220-00000001-asahi-soci
```

　八王子市の近くで東京都の別の市と記憶していたのですが、八王子市内だったようです。他に大きなニュースが情報番組で取り上げられていた時期だったようにも思うのですが、注意喚起や公益性の高い事故だと思ったのに、ニュース報道以外の情報番組で全く見なかったのが印象的でした。

　２０１７年３月９日午後４時３５分ころ、とありますが、これは丁度、森友学園問題の報道が情報番組などで加熱していた時期になるように思います。１１日辺りに能登高校の女子高生殺害事件があったので、まだ森友問題で報道が加熱のピークを迎える前夜だったとも思われます。

　もっとも森友学園問題は２月の下旬辺りからテレビの報道でもくすぶりだしていたと記憶にあります。

　２０１７年３月９日というのは、中村元弥弁護士のリツイートとして衝撃を受けた淡路島の弁護士の画像付きツイートを見た頃だったとも思います。能登高校の殺害事件は事件の翌日の報道でした。飼い犬による乳児死亡事件とあわせ別に取り上げておきたいと思います。

　昨日、１９日の朝は、中村元弥弁護士のツイートをいろいろと調べたり、まとめ記事を作成していたと思うのですが、そのとき、中村元弥弁護士と落合洋司弁護士（東京弁護士会）が司法修習の同期だったということを知りました。これは初めて知ったように思います。

　同じように、櫻井光政弁護士のツイートで、櫻井光政弁護士と高野隆弁護士が司法修習の同期というツイートも余り事件をあけずに目にしたのですが、そちらはずっと前に見ていたような感じで思い出しました。そちらは同期だけではなく同クラスだったとのことです。

　そういえば、櫻井光政弁護士の年齢というのも以前調べて確認したように思うのですが、すっかり忘れています。櫻井光政弁護士の顔写真はネット上に数枚見かけてきましたが、年代が違う別人に見えるようなものもあったように思います。中にはずっと前の写真を使う人もいるようですが。

　１６時５０分です。テレビでプライムニュースが始まりました。yahooの番組表で確認すると、「石川さん　プライムニュース」という番組名で、１６時５０分から１９時００分までの放送となっています。

　これまでこの時間帯は、テレビ金沢で「となりのテレ金ちゃん」という番組をつけていることが多かったのですが、そちらは５時台を中心にeveryという全国ニュースの放送となっています。どうも石川テレビもそれに似ているようですが、今回初めて気が付きました。

　そのプライムニュースの番組開始の冒頭で、タイル状で１２枚のパネルがお伝えするニュースの項目となっていました。これも今回初めて気がついたように思うのですが、わいせつ罪に問われた外科医の無罪判決は見当たりませんでした。

　１６時５８分です。テレビを北陸朝日放送にかえると「横浜のサル」が出てきました。サルが東京を目指すのか、などという解説が聞こえていました。能登でサルを見たという話は聞かないのですが、猿山岬には昔、サルや鹿がいたという話になっています。どちらも羽咋市の辺りならいるのかもしれません。

　時刻は２２時４９分です。小項目を締めたものとばかり思っていました。中断後だと思いますが、とても大きな発見がありました。秋田の弁護士刺殺事件のことですが、２月１３日に控訴審で逆転判決が出ていたことです。それらしい情報は2,3日前、深澤諭史弁護士のTLで見かけていました。

　２月１３日は、目が霞んだこと、セラミックヒーターが壊れたこと、宇出津新港のアルプの食堂で十一面観音の検察審査会関係のポスターを見たことなどいろいろと特別なことがありましたが、他にも大きなニュースがあったと思いながら思い出せずにいました。

　Twilogで調べたところ、その２０１９年２月１３日の大きなニュースというのは、カルロス・ゴーン氏が大鶴基成弁護士を解任し、弘中惇一郎弁護士や高野隆弁護士を新たな弁護人として専任したというニュースでした。弁護士業界にとって特別な日だったようです。

　本項の「わいせつ罪に問われた外科医に無罪判決」というニュースですが、テレビでは見かけていない気がします。バタバタしていたのでよく思い出せないのですが、テレビで見ていればスマホで画面を撮影しているはずです。

　１つ確認しているのは、テレビ金沢のeveryで、それと思われるニュースの見出しだけが複数の項目の１つとしてピックアップされていたことですが、内容の放送はなかったと思います。項目のリストに気がついた時点で、監禁事件の控訴審判決の内容に移りました。

　そのあと再び項目のリストが出て、ピックアップされていた他の１つの内容に移りましたが、それが終わったあとは、昨日辺り、他の番組で見ていた滋賀県野洲町の廃墟の建物の取り壊しの問題でした。なぜそこまで建物が傷んだのか疑問でしたが、昨年の台風２１号が原因とのことでした。

　なお、今日は外に一度も出掛けておらず、午前１１時以降はほとんどの時間テレビをつけたままにしていたと思います。情報番組やニュース以外で見たのは、１６時台の「記憶」というドラマと、２０時過ぎ辺りからの林修先生の番組で、箱根の神社や芦ノ湖が紹介されていました。

　箱根というのは能都中学校の４泊５日の修学旅行で３日目で３泊目をした場所でもあったのですが、ほとんど記憶に残っておらず、イギリスのバイキングのような船に乗ったことは、記憶と数少ない写真に残っているのですが、それがたぶん芦ノ湖だと思ってきました。

　箱根の周辺だけで丸一日の観光があったとは考えにくく、伊豆の方にも行ったような気がして、大きな駅にいたような記憶もあるのですが、はっきりした記憶として残っていません。宿泊した場所も記憶にないのですが、これは２日目に宿泊したと思われる奈良も同じです。

　奈良県については、だいぶん前から取り上げておきたかった過去の病院の問題があるのですが、昨日辺り深澤諭史弁護士のタイムラインで、リツイートとして気になる写真付きのツイートを見かけていました。とりあえず、そちらのツイートをご紹介しておきます。

▷ リツイート→fukazawas（深澤諭史）＞hwtnv（渡邉英徳）｜2019/02/20 08:37／2019/02/20 06:00｜https://twitter.com/fukazawas/status/1098003699102711808 ／ https://twitter.com/hwtnv/status/1097964096480264192
&twitter(1098003699102711808){theme:light}
> RT @hwtnv: 86年前の今日。1933年2月20日，プロレタリア作家の小林多喜二が，特高警察の拷問により築地警察署で死亡。以来，この日は「多喜二忌」と呼ばれている。ニューラルネットワークによる自動色付け＋手動補正。 https://t.co/FAZnGxsQVQ  

　カラーの色付けとしては初めて見たかもしれないですが、この小林多喜二の写真というのは反権力やその弾圧の象徴として何度か目にしてきたのですが、この昔の写真を見ると、決まって秋田の弁護士刺殺事件のことを思い出していたようにも思います。

　私は長距離トラック運転手の仕事で秋田に行くこともけっこうあったので、町並みや風景が他のいろいろな知識や経験とも結びついています。

＜＜＜2019-02-20（水曜日）23：31＿［これまでの記述範囲の終了時刻］＜＜＜

