#+TITLE: "kk／告発に至る経緯／新聞社／弁護士と裁判官が共同で確定させた傷害・準強姦被告事件判決の再捜査要請に係る石川県警察珠洲警察署提出書面のご案内メール"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-03-31 11:18:31 +0900
FILE_NAME: 2019-03-31-111831_弁護士と裁判官が共同で確定させた傷害・準強姦被告事件判決の再捜査要請に係る石川県警察珠洲警察署提出書面のご案内メール.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  金沢地方検察庁 石川県警察 報道 ご連絡
記事タイトル名の文字数：73　保存ファイル名の文字数：80

#contents

* メール送信先各位に対するご挨拶と趣旨説明

** メール送信を決めたのは２０１９年３月２７日水曜日の昼過ぎ
   :LOGBOOK:
   CLOCK: [2019-03-31 日 11:27]--[2019-03-31 日 12:34] =>  1:07
   :END:

＞＞＞2019-03-31（日曜日）11：27＿［これからの記述範囲の開始時刻］＞＞＞

　当初は、木曜日の３月２８日に作成を始め金曜日の３月２９日に送信する予定でした。木曜日の午前中には送信先のメールアドレスの準備が終わっていたように思います。

　情報収集と記録が中心でしたが、けっこうばたばたとしていました。報道機関にメールを送信するという動機は、３月１２日毎日新聞のネットニュースがあった福岡地裁久留米支部の準強姦無罪判決に対する、一般と弁護士らの反応の違い格差が大きいです。

　今朝はなぜだか小康状態ですが、昨日は「神の目」というキーワードまで飛び出し活況を呈したTwitterにおける弁護士らの反応でした。

　メールの標題にある通り、明日で２７年となる再捜査要請の事件も、金沢西警察署において傷害・準強姦事件として捜査され、金沢地方検察庁で起訴され、平成６年の１月２０日過ぎに最高裁で懲役４年の判決が確定しています。

　このあと重点的に書いておきたいことですが、石川県警察に対する再捜査要請の手続きの前に、金沢地方検察庁に対する殺人未遂事件としての刑事告発がありました。処分通知書のようなものが届いたのが、ちょうど２年前の今頃だったと思います。

　その時も年度替わりでした。処分は不起訴となっていましたが、そのしばらく前には金沢地方検察庁の検事から受理する方向だと連絡を受けていました。私のスマホにも検事から電話連絡がありましたが、Twilogを見れば、その日付も確認できるかと思います。

　なお、年度変りに金沢地方検察庁から告訴や告発に対する処分が届いたのは、平成１９年にもあったことです。書面の日付が３月３１日となっていたように思いますが、それというのが当時における殺人未遂罪の１５年の公訴時効の満了日でした。あえてその日を選んできたことになります。

　なお、その平成１９年当時の告訴・告発と平成２９年の告訴・告発は内容がかなり違っています。告訴と告発の違いもややこしいですが、金沢地方検察庁の方で私の告訴状に対して、告発という文言を用いた書面を出しています。書面はネットで公開状態にあるはずです。

　久留米支部の準強姦無罪判決は私にとって未来予想のシミュレーションのような機会となりました。私自身、情報が整理できていない状態ですが、まともにやったらそれだけで膨大な作業となってしまいます。

　特異な弁護士の発言も数々目にしてきました。そのほとんどはツイートになります。木の芽時という言葉もありますが、その異様さは「春の弁護士まつり」の様相と感じられました。しかし、それを裏打ちにするの私の特異な経験によるところが大きく、共有を図るのも今回の目的です。

　私が経験した弁護士の実態、それを一言で表現するならば、それが「弁護士鉄道」です。

　報道の在り方についても、よくよく考えさせられたのが「福岡地裁久留米支部の準強姦無罪判決」でした。弁護士らは判決書を重きにして、毎日新聞の記事を短文記事として批判していました。短文と言われれば短文と思いましたが、これまでに見てきたネット記事の大半と同じに見えました。

　確認しないと正確な日付や経緯がわからないですが、水曜日の昼過ぎという時点では、同じ毎日新聞による詳報ともされる続報の記事が出ていたように思います。会員制の有料記事となっているようなので、私は一般に公開された部分の記事しか読んでいません。

　詳報が出されたことで、納得する向きが多いようにも感じました。間接的に部分的な内容をうかがう部分もありましたが、一定の納得や理解を得られた効果はあったように感じられました。

　同じ性犯罪の刑事裁判では、静岡でも２件の物議をかもす無罪判決が出ています。２件目は、数日前になると思いますが、国賠訴訟で比較的最近話題となった大阪の強姦再審無罪事件とよく似た構図です。

　共通したのは親族間における性犯罪事件ということです。性犯罪ではないですが、若い女性の殺人事件で父親に疑いが掛かり、噂が独り歩きしたという事件も身近の石川県でありました。未解決迷宮入りとなった殺人事件です。

　それも私が平成４年の傷害・準強姦被告事件で拘置所にいるときの事件でした。記憶が定かではないのですが、事件の情報源は個人で購読していた新聞紙のみ、そのなかでも父親の関与の疑いが塀の中の私に伝わってきたのであれば、相当の嫌疑が囁かれ、蔓延したと想像されます。

　そのような不安や不信、憶測を掻き立てるのも弁護士脳の泥棒根性の作為ではないかと私は考えることがあります。

　毎日新聞の福岡地裁久留米支部の準強姦無罪判決の記事は、「安部志帆子」という記者の名前が出ていました。女性差別や女性蔑視の暴虐性も少なからず感じた弁護士脳のお祭り的な反応でした。なお、続報の方には、その辺りも意識されたのか、男性記者の名前も併記されていました。

＜＜＜2019-03-31（日曜日）12：34＿［これまでの記述範囲の終了時刻］＜＜＜

** 年度替わりを決めたジャーナリストの江川紹子氏の再審請求で検察を批判するツイート
   :LOGBOOK:
   CLOCK: [2019-03-31 日 15:45]--[2019-03-31 日 16:24] =>  0:39
   :END:

＞＞＞2019-03-31（日曜日）15：45＿［これからの記述範囲の開始時刻］＞＞＞

▶ ツイート％amneris84（Shoko Egawa）％2019/03/28 16:03％ https://twitter.com/amneris84/status/1111161840250179589
&twitter(1111161840250179589){theme:light}
> 再審請求審は最高裁まで争って、宮田さん存命中の再審を阻止しようとがんばった検察ですが、何ミリかの良心が残っていたのか、あるいは再審が開かれた以上どうせ勝てないんだし、話を長引かせて批判が続くのは得策ではないと考えたのか、上訴権放棄… https://t.co/ggypUSNk4I  
▶

　とても重いものを感じると同時に、ジャーナリストの江川紹子氏に受けた影響力を噛み締めます。ジャーナリストの江川紹子氏は検察の何ミリかの良心と言っていますが、私も大きな局面のタイミングで、このツイートを得たことに感謝をしたい気持ちもあります。

　検察や裁判所に対しては厳しいご意見を発信してきたジャーナリストの江川紹子氏ですが、弁護士に対して何一つ問題の検証をせずに、再審制度を論じていることには、感情的なはるかにレベルを超えた危機感を感じています。別の視点に立てば問題そのものの刑事司法を歪める諸悪の根源の１つです。

　ジャーナリストの江川紹子氏の検察批判というのは、このところ見かける機会が減っていました。ツイートの数自体も更新が減っているように思います。

　これは、他の多くの刑事弁護の問題ともつながりがあるのですが、前回見た検察批判の記事というのが、柳原病院事件に関する記事です。無罪判決が出た後だったかもしれませんが、検察が控訴をするまでの間に、カルロスゴーン氏の弁護団の交代と、大きく報道された保釈の騒動がありました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-03-31 16:00／2019-02-20 22:42 URL： https://twitter.com/kk_hirono/status/1112248219784740864 https://twitter.com/amneris84/status/1098216249832595456
&twitter(1112248219784740864){theme:light}
> 判決の詳細と関係者の反応、そして本判決の意議など　→乳腺外科医への無罪判決が意味するもの(江川紹子) - Y!ニュース https://t.co/g4qXPWbe0I
◁◁◁
<hr />

[link:] » "乳腺" (from:amneris84) - Twitter検索 / Twitter https://t.co/98kIyApXTg

<hr />

　Twitterで検索をして記事を捜し出しました。Twitterのツイートでは記事の写真が表示されていますが、このあとテレビでさいさん名前と顔が報道され、刑事弁護のレジェンドとも紹介されることが多かった高野隆弁護士の姿があります。

　ここで気がついたのですが、私がもっと印象深かったのは、高野隆弁護士のことなど全く触れていないジャーナリストの江川紹子氏のネット記事でした。高野隆弁護士がその柳原病院の裁判に関与していることは、たまたま目にしたような小さな情報で、真偽も不確かに感じていたように思います。

　無罪判決の記者会見と思われる上記の写真には４人の男性の姿があります。向かって右から２人目が高野隆弁護士、その隣にいる３人目が、ネットの他の写真とは違う印象も受けますが、その他の情報と合わせ趙誠峰弁護士に間違いないと思います。端の２名はわからない人物です。

　向かって左端の人物は、胸に弁護士バッチと思われるものをつけています。それほど深堀りで追求はしていなかったとも思いますが、高野隆弁護士と趙誠峰弁護士以外に関与した弁護士名は見かけていなかったと思います。

　当日の可能性が高いと思いますが、２月２０日の時点で無罪判決が出ていたようです。考えてみると２月は２８日までだったので、翌月の日付に違いが出ていますが、私の記憶では３月６日が控訴の申し立ての期限で、その日に検察の控訴があったように思います。

　検察の控訴は大きなニュースになっておらず、Twitterの弁護士の反応もほとんど見かけていなかったように思います。注視したジャーナリストの江川紹子氏のTwitterにもそれと思われるツイートは確認しませんでした。

[link:] » 乳腺外科医への無罪判決が意味するもの(江川紹子) - 個人 - Yahoo!ニュース https://t.co/EAA0RwUrMv

<hr />

　上記のジャーナリストの江川紹子氏の記事にざっと目を通しました。以前読んでいる内容だと思いますし、時間も掛けたくはないので読み直しはしていません。高野隆弁護士の顔写真と名前が出ていました。別に被害者側の弁護士として、上谷さくら弁護士の名前と写真もあります。

　思い出したのですが、検察の控訴の後だったと思いますが、被害者側が弁護団を結成し記者会見を開いたようです。控訴審で被害者側の弁護士になるが出来るのかという疑問も、Twitterの弁護士の間に出ていました。若干の数名でしたが、刑裁サイ太のツイートもありました。

＜＜＜2019-03-31（日曜日）16：24＿［これまでの記述範囲の終了時刻］＜＜＜

*** 「検察側の主張に見るリアリティの欠如は、「合理的な疑い」と言えないだろうか。」と指摘する柳原病院事件におけるジャーナリストの江川紹子氏のネット記事
    :LOGBOOK:
    CLOCK: [2019-03-31 日 16:28]--[2019-03-31 日 18:33] =>  2:05
    :END:

＞＞＞2019-03-31（日曜日）16：28＿［これからの記述範囲の開始時刻］＞＞＞

　ジャーナリストの江川紹子氏の記事は次のように締めくくられています。

```
「合理的疑い」を超えた証明はなされているか
　だからと言って、100％やってないとは言い切れない、という意見もあろう。

　しかし刑事裁判は、被告人の側が100％無実であることを証明する場ではない。有罪とするには、事件があって、被告人が犯人であると、「合理的な疑いを差し挟む余地のない程度の立証」を検察側が立証しなければならない。

　「合理的な疑い」とは、つまり通常人なら誰もが抱くような疑問だ。

　検察側の主張に見るリアリティの欠如は、「合理的な疑い」と言えないだろうか。この疑問を封じるほどの説得力を、検察側が根拠にする鑑定が持っているのかが問われている。

　最後に発言の機会を与えられた被告人は、短く次のように述べた。

「患者さんの安全はもちろん、医療者側の安全も守られる必要があります。公明正大な判断を望みます」

　判決は、来月20日に言い渡される。

［source：］乳腺外科医のわいせつ事件はあったのか？～検察・弁護側の主張を整理する(江川紹子) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/egawashoko/20190119-00111366/
```

　ジャーナリストの江川紹子氏の検察に対する強い不信感が感じられる記事でもありますが、この記事を読んだ時の私の感想は、病院名が出ていない、ということが何より強く印象に残りました。

　「同年5月10日、東京都足立区内の病院で、右胸の腫瘍を切除する手術を受けた30代女性患者のA子さんが」とあります。少し前のところに２０１６年とありますので、２０１６年５月１０日に起きた事件。少し後ろには同年８月２５日に逮捕とあります。

　テレビでの報道というのは記憶にないのですが、それもあったので気になるニュースや報道のテレビは画面をスマホで撮影し、写真として記録する習慣が身につくようになりました。

　ネットで見た情報がほとんどだったとは思いますが、逮捕された医師の病院で警察に対して抗議の声明を出していたことが、印象的でした。柳原病院事件とあるのは、２月の無罪判決の前後にネットで調べて見た支援者の医師らのホームページに、使われていた事件名です。

　これは少し調べて確認をしておきたいと思います。まずはTwilogで調べます。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「柳原病院」の検索結果 - Twilog https://t.co/sUKWugSHuk

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 16:43／2016-09-20 21:48 URL： https://twitter.com/kk_hirono/status/1112259046663323648 https://twitter.com/hirono_hideki/status/778214189064216576
&twitter(1112259046663323648){theme:light}
> 当院非常勤医師の起訴について｜柳原病院［東京都足立区］ https://t.co/MW3tDq6smh
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nora_mike_mike（猫（ミケ）・固定ツイも読んでね） 日時：2019-03-31 16:43／2019-02-20 14:52 URL： https://twitter.com/kk_hirono/status/1112259197180084224 https://twitter.com/nora_mike_mike/status/1098098001841549314
&twitter(1112259197180084224){theme:light}
> @amneris84 この強引な訴訟を起こされた外科医の勤める柳原病院って、「脱原発宣言」とか掲げてるんですよね。 \n  政権に近い男の性犯罪はもみ消され、政権の方針に反するこの病院への扱いはどうでしょう。 \n  https://t.co/9EbuuxiQxi
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nora_mike_mike（猫（ミケ）・固定ツイも読んでね） 日時：2019-03-31 16:43／2019-02-20 15:21 URL： https://twitter.com/kk_hirono/status/1112259223662952449 https://twitter.com/nora_mike_mike/status/1098105434777382912
&twitter(1112259223662952449){theme:light}
> @amneris84 柳原病院、民医連だった。リベラル思想の強い病院群で、現政権とは真反対。 \n  安倍晋三のお友達の準強姦はもみ消す検察は、この事件ではどう動いたのでしょうね。
◁◁◁
<hr />

　上記２件のツイートは、私が奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントで、２０１９年２月２０日にリツイートしたものです。ここで気がついたのですが、ジャーナリストの江川紹子氏のアカウントのメンションが入っています。

　ツイートを個別に開いたところ、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントでは、ツイートのつながりが表示されませんでした。これはジャーナリストの江川紹子氏のアカウントにミュートされている可能性があるのかもしれません。

　ログインしたアカウントを切り替えるまでもなく、Twitterの従来の表示に切り替えたところ、ツイートの関連が表示されました。これは表示するツイートのルールの違いがあるようです。フォロー関係がないと表示されない、という可能性はあるかと思います。

　なお、私はTwitterのミュートという機能のついても、まだよくわかっていません。一つだけはっきりしていることは、小倉秀夫弁護士のアカウントにミュートされています、と表示されたことです。ミュートは他にも受けていそうですが、その表示を見たのはその１度だけです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-03-31 16:58／2019-03-31 16:56 URL： https://twitter.com/kk_hirono/status/1112262873860861952 https://twitter.com/s_hirono/status/1112262473254494209
&twitter(1112262873860861952){theme:light}
> 2019-03-31-165013_奉納＼さらば弁護士鉄道・泥棒神社の物語（@hirono_hideki）／「柳原病院」の検索結果　-　Twilog.jpg https://t.co/uUjYkoqETH
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-03-31 16:58／2019-03-31 16:57 URL： https://twitter.com/kk_hirono/status/1112262889010688000 https://twitter.com/s_hirono/status/1112262547107794944
&twitter(1112262889010688000){theme:light}
> 2019-03-31-165047_（1）　奉納＼さらば弁護士鉄道・泥棒神社の物語さんはTwitterを使っています：　「RT　@nora_mike_mike：　@amneris84　柳原病.jpg https://t.co/jg685OK7bl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-03-31 16:58／2019-03-31 16:57 URL： https://twitter.com/kk_hirono/status/1112262917833940993 https://twitter.com/s_hirono/status/1112262619195273216
&twitter(1112262917833940993){theme:light}
> 2019-03-31-165121_猫（ミケ）・固定ツイも読んでねさんのツイート：　”柳原病院、民医連だった。リベラル思想の強い病院群で、現政権とは真反対。　安倍晋三のお友達の準強姦はもみ消.jpg https://t.co/9OOmh8IHji
◁◁◁
<hr />

　言葉だけの説明は困難で手間も掛かるので、スクリーンショットを作成しました。気になったのはTwilogでの表示で、ツイートの先頭にジャーナリストの江川紹子氏のメンションがあります。＠amneris84がそれです。

　現在のTwitterでは、コピペのような非公式RTもほとんど見かけず、メンションは返信先としてツイートの内容とは別に表示されることが多いので、ツイートの人があえてメンションを記入したのかと思ったのですが、ツイートは２件の返信先となっていました。

　「返信先: @nora_mike_mikeさん、@amneris84さん」という部分がそれになるのですが、左の方は投稿者本人のメンションなので、Twilogには表示がないことになっていたのかもしれません。

　これまで他にもTwilogとTwitterのツイートに表示の違いを感じたことはありました。あらためて確認しましたが、ブログカードとも呼ばれる記事の要約と写真や画像のサムネイルがセットになった表示が、Twilogのツイートにはありません。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2016/09/20 21:48％ https://twitter.com/hirono_hideki/status/778214189064216576
&twitter(778214189064216576){theme:light}
> 当院非常勤医師の起訴について｜柳原病院［東京都足立区］ https://t.co/MW3tDq6smh  
▶

　上記のツイートにある記事はリンク切れとなっていました。上記の２件のリツイートにもありますが、伊藤詩織さんの準強姦事件に関連付けて、政権批判や政権不信として考え、論じる人も少なくはないようです。そういう意味でも、私は伊藤詩織さんの事件にも注目し、記録をしてきました。

　その伊藤詩織さんのことについても、数日前に意外な情報を見かけたのですが、余り話題にもなっていないようです。他の検索の過程でたまたま見かけたようにも思います。民事訴訟法の馴染みのない用語が使われていました。検索をしたいのですが、正確に思い出せません。

　「dp -p|grep 状」という大雑把な検索でやってみましたが、最近のことでもあり、手掛かりが見つかりました。まず目についてのは村松謙弁護士のツイートの記録記事です。

[link:] 2019年03月27日16時39分の登録： ＼村松 謙　@kmuramatsu＼ひょえー。反訴状を閲覧したひとがメモをあっぷしてるのか。。。 http://hirono2014sk.blogspot.com/2019/03/kmuramatsu_27.html

　「反訴状」というのが見慣れない用語でした。あらためてみても奇異に感じる言葉の組み合わせです。被控訴人などというややこしい用語がやたらと出てくるのも民事訴訟の特徴ですが、少なくともテレビでは見かけたことがなく、理解する人も多いはなさそうです。

```
ツイート数：5 リツイート数：11 トータル：1386
反訴状
ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "反訴状"
```

　まだ、ご説明をしていませんが、最近作成したコマンドで「twitterAPI-search-lawList-mydql-add.rb 反訴状」の実行結果になります。予め登録したアカウントののツイートをデータベースに登録します。TwitterAPIでの検索メソッドを使っています。

　トータルが１万を超えたこともありますが、エラーが出ることもあります。西崎健児だったと思いますが、途中でリミットのエラーが出ていました。福岡地裁久留米支部の準強姦無罪判決の裁判長の名前です。

　TwitterAPIでの検索は、通常のブラウザでのTwitterの高度な検索と異なり、制約が多くかなり最近のツイートとしか取得できません。「'from:imarockcaster42 since:2019-03-20 until:2019-03-21'」のような指定は出来ます。

　from:とあるのはツイートの投稿者のアカウントの指定です。そのあとツイートの投稿日時の範囲を指定していますが、この書式による指定は「Twitterの高度な検索」と同じです。

```
[9983]  % dp -p |grep 反訴状
[link:] 2019年03月27日16時35分の登録： ＼ystk　@lawkus＼話題の反訴状チラっと見たけど、性交が原告(反訴被告)の承諾のもと行われたことについて評価根拠事実を示すとか書いてあるな。それ規範的要件じゃない http://hirono2014sk.blogspot.com/2019/03/ystklawkus_93.html
[link:] 2019年03月27日16時39分の登録： ＼村松 謙　@kmuramatsu＼ひょえー。反訴状を閲覧したひとがメモをあっぷしてるのか。。。 http://hirono2014sk.blogspot.com/2019/03/kmuramatsu_27.html
```

　すでにまとめ記事を作成しているものと思っていたのですが、ツイートをデータベースに登録したあとの作業をし忘れていたようです。

　TwitterAPIでの検索は、処理時間も早く漏れもありそうなので、従来の方法を使ってテキストに保存済みのアカウントのツイートのURLを取得しました。

```
[9984]  % list-tweet-egrep.sh 反訴状
https://twitter.com/k_sawmen/status/966146078268579841
https://twitter.com/nabeteru1Q78/status/1111187883077959682
https://twitter.com/laparkadejapon/status/1101359287257817088
https://twitter.com/ISOKO_MOCHIZUKI/status/1111778676415172608
https://twitter.com/KazukoIto_Law/status/1111433383081472000
https://twitter.com/ohne_fleiss/status/912922913426202624
https://twitter.com/s_hirono/status/1110851723671683072
https://twitter.com/LiarLawyer800/status/1053141653999874049
https://twitter.com/hagirazors/status/987300825377652736
https://twitter.com/hagirazors/status/987300825377652736
https://twitter.com/ikatsuwo/status/974527352989368320
https://twitter.com/chopitarou/status/930997158316093440
https://twitter.com/kmuramatsu/status/1110464900902469633
https://twitter.com/ramenman365/status/750922250757419009
https://twitter.com/which0623/status/992262411536121858
https://twitter.com/hirono_hideki/status/1110809340707921921
https://twitter.com/hirono_hideki/status/1110809187519348737
https://twitter.com/hirono_hideki/status/1110809126488072192
https://twitter.com/hirono_hideki/status/1110808921873117186
https://twitter.com/hirono_hideki/status/1110808891925749762
https://twitter.com/hirono_hideki/status/1110808867519127553
https://twitter.com/hirono_hideki/status/1110808844635004930
https://twitter.com/sakanauranai/status/986914468444569600
https://twitter.com/sakanauranai/status/986613877008838657
https://twitter.com/un_co_the2nd/status/900295064244465664
https://twitter.com/un_co_the2nd/status/887263722518872064
https://twitter.com/un_co_the2nd/status/886994286192939008
https://twitter.com/un_co_the2nd/status/882626304876597251
https://twitter.com/un_co_the2nd/status/882267952178839554
https://twitter.com/siusiudon/status/750922250757419009
https://twitter.com/wata_nabekyo_ko/status/984612773886771200
https://twitter.com/wata_nabekyo_ko/status/973442569240592386
32 /home/a66/l



for i in `cat ~/l`; do k4-tweet-add-mysql-uniq-argv.rb $i; done
ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "反訴状"
```

　何度かご説明をしてきたと思いますが、「for i in `cat ~/l`; do k4-tweet-add-mysql-uniq-argv.rb $i; done」が検索結果のツイートを一括した処理としてデータベースに登録するコマンドです。

[link:] 2019年03月31日17時46分の登録： REGEXP：”反訴状”／データベース登録済みツイート：2019年03月31日17時45分の記録：ユーザ・投稿：23／36件 http://hirono2014sk.blogspot.com/2019/03/regexp2019033117452336.html

　意外な発見があるのもよくあることです。うの字という注目アカウントの一人ですが、なるほどと思われる内容のツイートです。裁判をゲームのような感覚で楽しむのは、ちょいちょい見られる弁護士ツイートですが、これだけリアルにストレートなものも珍しいとは思いました。

▶ ツイート％un_co_the2nd（うのじ）％2017/08/23 18:54％ https://twitter.com/un_co_the2nd/status/900295064244465664
&twitter(900295064244465664){theme:light}
> ワイが被告代理人だったら答弁書と一緒に反訴状出して、完勝した暁には本人に「原告代理人にたいする懲戒の請求したら？」って示唆するところだな  
▶

　現在も擬人化したウンコがアイコンですが、一年ほど前になりますか、それまでは巻糞がコンドームを口にくわえていました。弁護士のようですが匿名だし、それも自由かという思いはありましたが、鹿児島大学の教授から法政大学の教授になった坂本正幸弁護士がちょいちょいリツイートしていました。

　その坂本正幸弁護士も最近はツイートの頻度が減少しているようです。余り更新がないので、タイムラインを開く機会も減ってはいます。

　その坂本正幸弁護士のタイムラインを開くと、次の気になるツイートがありました。ツイートを個別に開いて会話を遡ると、足立啓太弁護士のツイートに「明日の自由を守る若手弁護士の会」というのが出てきました。

　「あすわか」などと略称された弁護士の会は、以前見かけていましたが、女性弁護士が中心になっていたように思います。それも見かけなくなってすっかり忘れていました。

　「list-tweet-egrep.sh "明日の自由を守る若手弁護士の会"」を実行すると、９３９１というツイートが結果に出てきました。余り見かけた覚えもないので、バグではないかとも思ったのですが１つ最後のものを開いてみましょう。URLだけだとリツイートかどうかもわかりません。

▶ ツイート％asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか）％2017/12/16 21:46％ https://twitter.com/asuno_jiyuu/status/942013106682601477
&twitter(942013106682601477){theme:light}
> 人を「大年増の厚化粧」と侮蔑するところ、女性蔑視の発露と感じられます。年齢を重ねれば「年増」とののしられ、化粧をすれば「厚化粧」と罵倒される。生きているだけで女性がどうとでも罵倒中傷されうる社会は、尊厳や“個人の尊重”とはほど遠い… https://t.co/sWWsG9bmCN  
▶

　やはりリツイートでしたが、リツイートのURLをブラウザで開いても、表示されるのはリツイートされた元のツイートになるので、まったく区別はできません。次がリツイートのURLです。処理の順序で時系列は無関係と思われます。

▷ リツイート→wata_nabekyo_ko（なべきょう＠過眠症）＞asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか）｜2017/12/17 04:46／2017/12/16 21:46｜https://twitter.com/wata_nabekyo_ko/status/942118806645702656 ／ https://twitter.com/asuno_jiyuu/status/942013106682601477
&twitter(942118806645702656){theme:light}
> RT @asuno_jiyuu: 人を「大年増の厚化粧」と侮蔑するところ、女性蔑視の発露と感じられます。年齢を重ねれば「年増」とののしられ、化粧をすれば「厚化粧」と罵倒される。生きているだけで女性がどうとでも罵倒中傷されうる社会は、尊厳や“個人の尊重”とはほど遠いところにありま…  

```
明日の自由を守る若手弁護士の会／あすわか
@asuno_jiyuu
自民党の日本国憲法改正草案の内容とその危険性を広く知らせることを目的とした、若手弁護士有志の会です（略称「あすわか」）。現在、約６００名が活動しています。リーフや立憲主義を題材にした紙芝居等を発行しています。 あすわか著「憲法カフェへようこそ！　意外と楽しく学べるイマドキの改憲」（かもがわ書店）おかげさまで大好評です♪

日本
asuno-jiyuu.com
2013年1月に登録

［source：］明日の自由を守る若手弁護士の会／あすわか(@asuno_jiyuu)さん | Twitter https://twitter.com/asuno_jiyuu
```

　１６０文字あったのでプロフィールを２分割して告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)にツイートしました。ページのデザインも女性っぽく、固定されたツイートの動画にも３人ほどの女性の姿がありました。

　すべて弁護士かどうかは不明ですが、約６００人が活動しているというのはけっこうな数です。これまでは女性限定の会というイメージで固定観念となっていたのですが、この数だと女性のみという可能性の方が低いような気がしてきました。

　テキストデータの記録まで登録済みのアカウントでしたが、これまでのまとめ記事では、ほとんど見かけることがなかったように思います。タイムラインのツイートをみると、数時間前のツイートが並んでいるので、けっこうな頻度で更新の投稿はされているようです。

▶ ツイート％asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか）％2019/03/29 12:17％ https://twitter.com/asuno_jiyuu/status/1111467418088435718
&twitter(1111467418088435718){theme:light}
> ４月６日（土）楾大樹弁護士の憲法カフェ「檻の中のライオン」in国立☆１０：００～１２：３０＠カンバーランド長老キリスト教会　国立のぞみ教会（国立市東３－１５－９）https://t.co/3Mz4UURBKL
> 参加費無料／申込み不… https://t.co/2vmYJ7fq4Y  
▶

　憲法問題を中心にしているようですが、福岡地裁久留米支部の準強姦無罪判決と静岡の２件の強制性交の無罪判決では、一般の不信感や反感を逆手に取って、性犯罪から暴行脅迫の要件を撤廃し、または過失による性犯罪の立法化を目指す動きもちらほらと見かけています。

＜＜＜2019-03-31（日曜日）18：33＿［これまでの記述範囲の終了時刻］＜＜＜

*** 明日の自由を守る若手弁護士の会／あすわか@asuno_jiyuuの(強制性交|わいせつ|強姦)を検索：201301291032-201903311200
    :LOGBOOK:
    CLOCK: [2019-03-31 日 18:37]--[2019-03-31 日 19:01] =>  0:24
    :END:

＞＞＞2019-03-31（日曜日）18：37＿［これからの記述範囲の開始時刻］＞＞＞

```
[9987]  % tac asuno_jiyuu_201301291032-201903311200.txt |egrep '(強制性交|わいせつ|強姦)'
▶TW asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか） 日時：2013-10-25 19:57 URL： https://twitter.com/asuno_jiyuu/status/393692781543030784 TWEET： 【２４条の会】島岡さん、強姦罪（刑法１７７条）は、女子しか被害者になれないように規定されている。こんな規定が残っているのは、先進国では日本くらいのもの。強姦罪の要件である暴行脅迫は、かなりひどいものでないと成立しない。貞操を守るために死ぬほど抵抗しないと、被害者が悪いとされる。  
▶TW asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか） 日時：2013-10-25 19:59 URL： https://twitter.com/asuno_jiyuu/status/393693346167656448 TWEET： 【２４条の会】約１００年前に刑法と一緒にできた民法では、女性は無能力者として規定されており、契約する能力もなかった。強姦罪は、夫の財産を犯した、という発想のもとに規定されている。その後、憲法２４条ができて、刑法や民法の発想も変わらなきゃいけなかったのに、変わっていない。  
▶TW asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか） 日時：2018-04-27 11:26 URL： https://twitter.com/asuno_jiyuu/status/989692344478744576 TWEET： TOKIO山口氏の強制わいせつの件、「そもそも被害者が（山口氏の）自宅に安易に行くのがいけない」という批判があります。性暴力は、もっぱら加害者の責任です。なぜ性犯罪に限って、ここまで「被害者側の落ち度」が語られるのか…。「男性の性… https://t.co/PH4GTXoDjh  
▶RT asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか）｜tasaki_kanagawa（田崎 基（神奈川新聞 記者）） 日時：2019-02-22 16:32／2019-02-22 00:16 URL： https://twitter.com/asuno_jiyuu/status/1098848074011631616 https://twitter.com/tasaki_kanagawa/status/1098602310924668929 TWEET： これは看過しがたい。 \n  \n 「問題にならないようにやらないと駄目だ。同じことをやるにしても」 伊吹氏、田畑議員巡り発言 https://t.co/xSLfnOFw04 \n  \n 準強制性交容疑（つまり強姦）で告訴された自民党議員についての発言です。
```

　ざっと見たところブロックされている可能性はなさそうのなので、URLからツイートを開いてリツイートをしたいと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか） 日時：2019-03-31 18:40／2013-10-25 19:57 URL： https://twitter.com/kk_hirono/status/1112288544041517056 https://twitter.com/asuno_jiyuu/status/393692781543030784
&twitter(1112288544041517056){theme:light}
> 【２４条の会】島岡さん、強姦罪（刑法１７７条）は、女子しか被害者になれないように規定されている。こんな規定が残っているのは、先進国では日本くらいのもの。強姦罪の要件である暴行脅迫は、かなりひどいものでないと成立しない。貞操を守るために死ぬほど抵抗しないと、被害者が悪いとされる。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか） 日時：2019-03-31 18:42／2013-10-25 19:59 URL： https://twitter.com/kk_hirono/status/1112289010137718784 https://twitter.com/asuno_jiyuu/status/393693346167656448
&twitter(1112289010137718784){theme:light}
> 【２４条の会】約１００年前に刑法と一緒にできた民法では、女性は無能力者として規定されており、契約する能力もなかった。強姦罪は、夫の財産を犯した、という発想のもとに規定されている。その後、憲法２４条ができて、刑法や民法の発想も変わらなきゃいけなかったのに、変わっていない。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜asuno_jiyuu（明日の自由を守る若手弁護士の会／あすわか） 日時：2019-03-31 18:42／2018-04-27 11:26 URL： https://twitter.com/kk_hirono/status/1112289177431760896 https://twitter.com/asuno_jiyuu/status/989692344478744576
&twitter(1112289177431760896){theme:light}
> TOKIO山口氏の強制わいせつの件、「そもそも被害者が（山口氏の）自宅に安易に行くのがいけない」という批判があります。性暴力は、もっぱら加害者の責任です。なぜ性犯罪に限って、ここまで「被害者側の落ち度」が語られるのか…。「男性の性… https://t.co/PH4GTXoDjh
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜tasaki_kanagawa（田崎 基（神奈川新聞 記者）） 日時：2019-03-31 18:43／2019-02-22 00:16 URL： https://twitter.com/kk_hirono/status/1112289383367925760 https://twitter.com/tasaki_kanagawa/status/1098602310924668929
&twitter(1112289383367925760){theme:light}
> これは看過しがたい。 \n   \n  「問題にならないようにやらないと駄目だ。同じことをやるにしても」 伊吹氏、田畑議員巡り発言 https://t.co/xSLfnOFw04 \n   \n  準強制性交容疑（つまり強姦）で告訴された自民党議員についての発言です。
◁◁◁
<hr />

　４件目はリツイートですが、神奈川新聞の記者で男性のようです。アイコンに身分証明書の写真のようなものが見えます。神奈川新聞といえば、ジャーナリストの江川紹子氏の経歴で見かけていました。カナコロというようなネットニュースがありましたが、もうずいぶん全く見かけていません。

［link：］ 【メディア掲載】「神奈川新聞」のニュースサイト「カナコロ」に神奈川大学のプログラムを掲載いただきました | スリール株式会社 https://sourire-heart.com/6666/

　カナコロのGoogle検索の結果を見たところ、上記の記事がもっとも新しいようですが、カナコロという名称自体、現在は使われていないようです。「カナロコ」というワードの方が優先して最初に表示され、いささか混乱しました。

　神奈川新聞で検索し直したところ、カナロコの方が上位に出てきました。カナが神奈川を意味することはわかりますが、「コロ」も「ロコ」も意味不明です。どちらが正しいのかもわからないですが、勘違いをする人は多そうな気がします。

　アクセスランキングが１位となっているのですが、意外な記事を発見しました。。それも「社会 神奈川新聞　 2019年02月05日 17:00」となっています。記事の配信時刻なのでしょう。

　全国的にはありがちな問題と思ったのですが、記事の内容を読むと、初めて目にする和解内容ではないかと思いました。地鎮祭や奉納の神事のようです。

＜＜＜2019-03-31（日曜日）19：01＿［これまでの記述範囲の終了時刻］＜＜＜

** ここ２，３日、やたらと目にするようになった弁護士の「神の目」というキーワード

*** 弁護士に忌避されたのか神奈川新聞のWebサイトでアクセス１位の「横浜中２死亡、両親と横浜市が和解　校外学習先で脳出血」という記事と、平成２１年９月、能登警察署での神様の目線
    :LOGBOOK:
    CLOCK: [2019-03-31 日 19:56]--[2019-03-31 日 21:17] =>  1:21
    :END:

＞＞＞2019-03-31（日曜日）19：56＿［これからの記述範囲の開始時刻］＞＞＞

```
5610： kk／告発に至る経緯／新聞社／弁護士と裁判官が共同で確定させた傷害・準強姦被告事件判決の再捜査要請に係る石川県警察珠洲警察署提出書面のご案内メール http://bit.ly/2YCOP3N
5611： メール送信を決めたのは２０１９年３月２７日水曜日の昼過ぎ http://bit.ly/2VeBI6E
5612： メール送信先各位に対するご挨拶と趣旨説明 http://bit.ly/2YDPDFG
5613： 年度替わりを決めたジャーナリストの江川紹子氏の再審請求で検察を批判するツイート http://bit.ly/2V9zhSS
5614： 「検察側の主張に見るリアリティの欠如は、「合理的な疑い」と言えないだろうか。」と指摘する柳原病院事件におけるジャーナリストの江川紹子氏のネット記事 http://bit.ly/2V8YYDk
5615： 明日の自由を守る若手弁護士の会／あすわか@asuno_jiyuuの(強制性交|わいせつ|強姦)を検索：201301291032-201903311200 http://bit.ly/2V9ziWW
```

　本日は上記の流れとなっています。「わらしべ長者」という日本昔ばなし、があったと思いますが、流れにまかせて記述を進めていたところ、 明日の自由を守る若手弁護士の会／あすわか@asuno_jiyuuから行き着いたのが次の記事になります。

［link：］ 横浜中２死亡、両親と横浜市が和解　校外学習先で脳出血 | 社会 | カナロコ https://www.kanaloco.jp/article/entry-148739.html

　あらためて記事をみると、女子生徒の死亡があったのが２０１３年５月、記事の配信時刻と思われる日時が２０１９年２月５日１７時００分となっています。

　「市によると、生徒は千葉県へ、２泊３日の校外学習に訪れた。２日目の朝食時に激しい頭痛を訴え、救急搬送されたが、間もなく死亡。死因は脳出血だった。」とありますが、思い出すのは２００９年８月３１日の朝のことです。母親がタオルを口にはさみ苦しんでいました。

　救急車は近くの宇出津病院ではなく、十八束から珠洲方面に向かいました。あとでわかったことですが、救急隊員はすぐに脳出血だと判断したようです。緊迫した状況の中、母親の人生もこれで最後かと思いました。

　当時の状況はもっと記憶の新しい段階で記述したものがあると思います。翌年の１月の２０日過ぎだったように思いますが、宇出津と同じ旧柳田村上町の病院に転院して、現在に至っておりますが、半身不随となり寝たきりの状態が続いています。

　９月の９日頃だったと思いますが、２，３日後に京都、兵庫、名古屋の母親の兄弟の親戚と会うため、能登警察署に行って今後の相談をしました。大家警部補です。そのとき言われた言葉が、「神様の目線でふざけたやつ」でした。

　これももっと記憶の新しい段階で記述したものがあると思います。現在は記憶が薄れていることも実感しておりますし、同じようなことを再度繰り返すのも、時間的の使い方として効率的ではありません。

　「供述調書にハンコをついたら、それで終わりや」などとふざけたようなことを大家警部補は言葉にしていましたが、それはジャーナリストの江川紹子氏が好きな演劇の舞台を演じるように、弁護士らが常套句とする台詞を語っているようでした。

　「両親は市に約８８９０万円の損害賠償を求めて横浜地裁に提訴したが、地裁は教諭側に安全配慮義務違反はなかったなどとして、請求を棄却した。」という部分を読んだときは、よくある話で、なぜアクセスランキングが１位になっていて、それもずいぶん経過していると思いました。

　「両親は東京高裁に控訴。昨年１２月１９日付で、市との和解が成立した。和解条項には市立学校で事故対応の指針を順守することや市が哀悼の意を表明することなどが盛り込まれた。和解金の支払いはない。」と続いてあります。

　「和解金の支払いはない」という和解はニュースとして過去に見た記憶がありません。和解金は非公表というのはちょいちょいと見かけてきたので、読みながら本当に驚きました。

　「市は「校外学習中に生徒が死亡した事実に真摯（しんし）に向き合い、深く哀悼の意を表す」としている。」と記事は締めくくられています。福岡地裁久留米支部の準強姦無罪判決の毎日新聞のような記者の名前はありません。

```
市によると、生徒は千葉県へ、２泊３日の校外学習に訪れた。２日目の朝食時に激しい頭痛を訴え、救急搬送されたが、間もなく死亡。死因は脳出血だった。


［source：］横浜中２死亡、両親と横浜市が和解　校外学習先で脳出血 | 社会 | カナロコ https://www.kanaloco.jp/article/entry-148739.html
```

　中学２年生で脳出血が死因だったというのも過去に聞いたことがありません。脳出血は高血圧が要因として多いとも聞きます。私も現在は血圧が高めだと思いますが、福井刑務所にいた３０歳の頃も血圧は低く、中高生の頃は、さらに血圧が低かったと思われ、寝起きが非常に悪かったです。

　上記にjavascriptを使ってコピペを行いました。カナロコをカナコロと勘違いしていた神奈川新聞のWebのニュースサイトですが、開いたのは１，２年ぶりと思います。その前回は右クリック禁止か、javascriptの実行が出来ず、不満に感じたことを記憶にしていました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「カナロコ」の検索結果 - Twilog https://t.co/h3hlKlVjMG

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:54／2010-06-02 19:11 URL： https://twitter.com/kk_hirono/status/1112322331009966081 https://twitter.com/hirono_hideki/status/15241726283
&twitter(1112322331009966081){theme:light}
> 発砲で立てこもりの男が自殺/横浜：ローカルニュース : ニュース : カナロコ -- 神奈川新聞社 | http://news.kanaloco.jp/localnews/article/0911060015/ 物騒な事件が増えているみたいです。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:55／2010-10-29 20:02 URL： https://twitter.com/kk_hirono/status/1112322519246069760 https://twitter.com/hirono_hideki/status/29076503581
&twitter(1112322519246069760){theme:light}
> [量刑]]弁護側によると、少女の証言には不自然な点が多々あるそうですが、無罪の主張とは出ていないみたいです。 / 強姦致傷事件で懲役８年求刑「反省の姿勢が全くない」/横浜地裁小田原支部：ローカルニュース : ニュース : カナロコ --… http://htn.to/y89GbG
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:55／2010-12-09 07:48 URL： https://twitter.com/kk_hirono/status/1112322610514157570 https://twitter.com/hirono_hideki/status/12639590636589056
&twitter(1112322610514157570){theme:light}
> [裁判所]業務妨害の故意はなかったように思えますが。客観的な要件が重視されたような。これも参考になる事例です。 / 書記官に「ぶっ殺してやる」、裁判所で暴れた容疑の男を逮捕/相模原 （カナロコ） - Yahoo!ニュース http://htn.to/vshka7
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:56／2011-01-28 22:46 URL： https://twitter.com/kk_hirono/status/1112322667149844486 https://twitter.com/hirono_hideki/status/30985113684672513
&twitter(1112322667149844486){theme:light}
> "死刑判決の裁判員らによる意見交換会、「当時を考えると今も泣いてしまう」/横浜地裁 （カナロコ） - Yahoo!ニュース" - http://j.mp/hXficJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:56／2011-03-10 04:38 URL： https://twitter.com/kk_hirono/status/1112322780563828736 https://twitter.com/hirono_hideki/status/45569123987628032
&twitter(1112322780563828736){theme:light}
> 「被害者証言に疑問」、傷害被告に無罪判決/横浜地裁：ローカルニュース : ニュース : カナロコ -- 神奈川新聞社 http://ow.ly/4b7bi （引用→）弁護人は「警察は一方の当事者の言い分のみを信用して捜査し、検察も公平中立な立場で起訴せず、その責任は重い」として
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:57／2012-10-22 18:22 URL： https://twitter.com/kk_hirono/status/1112322913145782272 https://twitter.com/hirono_hideki/status/260310265982230529
&twitter(1112322913145782272){theme:light}
> ＰＣ遠隔操作事件：横浜の襲撃予告で地検、「誘導疑い」の上申書基に疑問解消せず調書作成／神奈川：ローカルニュース : ニュース : カナロコ -- 神奈川新聞社 http://t.co/eUrk5FYy
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yinoue1975（井上雄樹） 日時：2019-03-31 20:57／2013-02-19 09:18 URL： https://twitter.com/kk_hirono/status/1112322979726123008 https://twitter.com/yinoue1975/status/303659677269520385
&twitter(1112322979726123008){theme:light}
> 痴漢証拠を「捏造」、冤罪被害者側が県警警部補告発へ／神奈川（カナロコ） - Y!ニュース http://t.co/XYTen44s 令状請求の際の報告書が盛ってあることは珍しくないよなあ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:57／2013-04-15 22:12 URL： https://twitter.com/kk_hirono/status/1112323123783729154 https://twitter.com/hirono_hideki/status/323785984045113344
&twitter(1112323123783729154){theme:light}
> "痴漢冤罪事件：元被告の妻、警察と司法に不信感／神奈川 （カナロコ） - Yahoo!ニュース" - http://t.co/HB0GZJhOuz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:58／2013-04-22 01:22 URL： https://twitter.com/kk_hirono/status/1112323176380289024 https://twitter.com/hirono_hideki/status/326007928895188992
&twitter(1112323176380289024){theme:light}
> "２ちゃんねるに前科の削除請求、被告の反論なく５月に地裁判決／横浜：ローカルニュース : ニュース : カナロコ -- 神奈川新聞社" http://t.co/yrhiIvIBTs
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:58／2014-02-06 19:04 URL： https://twitter.com/kk_hirono/status/1112323389002141696 https://twitter.com/hirono_hideki/status/431367732798713856
&twitter(1112323389002141696){theme:light}
> 「売春と慰安婦は違う」　関東学院大・林博史氏、ＮＨＫ会長の発言で：ローカルニュース : ニュース : カナロコ -- 神奈川新聞社 http://t.co/bUboWsoG7X
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 20:59／2014-03-30 08:55 URL： https://twitter.com/kk_hirono/status/1112323445335818240 https://twitter.com/hirono_hideki/status/450058765879246848
&twitter(1112323445335818240){theme:light}
> 公文書改ざん、小田原市前消防長ら不起訴に：ローカルニュース : ニュース : カナロコ -- 神奈川新聞社 http://t.co/zJtNfxketo \n  虚偽無印公文書作成・同行使の疑いで告発されていた前消防長ら４人を不起訴処分（起訴猶予）とした。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜imaedajin（弁護士今枝仁(イマジン広島3)） 日時：2019-03-31 20:59／2014-04-17 15:52 URL： https://twitter.com/kk_hirono/status/1112323503296929792 https://twitter.com/imaedajin/status/456686687477694464
&twitter(1112323503296929792){theme:light}
> 未成年の喫煙、飲酒黙認…　神奈川県警が保護者ら３３人書類送検（カナロコ by 神奈川新聞） - Y!ニュース http://t.co/lSyLmC2OxE
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:00／2014-05-02 09:47 URL： https://twitter.com/kk_hirono/status/1112323664093941761 https://twitter.com/hirono_hideki/status/462030533611249664
&twitter(1112323664093941761){theme:light}
> 元准教授「ネットで中傷」　横浜地裁が教え子に賠償命令 （カナロコ by 神奈川新聞） - Yahoo!ニュース http://t.co/PGyF1sPsq7 志村由貴裁判官は「元准教授の社会的評価を低下させた」として、約１８０万円の支払いを命じた。判決は４月２４日付。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:00／2014-06-27 13:51 URL： https://twitter.com/kk_hirono/status/1112323731253190657 https://twitter.com/hirono_hideki/status/482385669420232705
&twitter(1112323731253190657){theme:light}
> 料理に薬物混ぜ女性暴行　医師の被告に懲役１３年判決 | カナロコ http://t.co/IGQFil5Wok 被告は被害者に対し、損害賠償として計２３４０万円を支払った。今後、医師免許が取り消される見通し。判決を受け、同被告は「規範意識が欠落していた。一生をかけて罪を償っていき
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-03-31 21:01／2015-02-05 18:28 URL： https://twitter.com/kk_hirono/status/1112323924421828608 https://twitter.com/amneris84/status/563267906469765120
&twitter(1112323924421828608){theme:light}
> 裁判所は「謝罪にも来ない。どんなに誤った判断を下しても（裁判所の立場は）守られている」と。片山被告の態度については「非常に甘い」と　→ＰＣ遠隔操作事件、「早く忘れたい」　誤認逮捕された元少年の父（カナロコ by 神奈川新聞）  http://t.co/PM4xcXrmkz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yasumasa218（新谷泰真） 日時：2019-03-31 21:01／2015-05-25 09:56 URL： https://twitter.com/kk_hirono/status/1112324012665769984 https://twitter.com/yasumasa218/status/602639244696227840
&twitter(1112324012665769984){theme:light}
> 「横浜」か「神奈川」か　弁護士会改称議論できょう採決（カナロコ by 神奈川新聞） - Yahoo!ニュース http://t.co/uGkIB19NbL \n   \n  横浜弁護士会の人権感覚が問われる問題といっても差し支えあるまい。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:01／2015-05-25 14:03 URL： https://twitter.com/kk_hirono/status/1112324083700531201 https://twitter.com/hirono_hideki/status/602701492177477632
&twitter(1112324083700531201){theme:light}
> 「横浜」か「神奈川」か　弁護士会改称議論できょう採決 （カナロコ by 神奈川新聞） - Yahoo!ニュース http://t.co/CCUPrfiQVQ 日弁連によると、名称に都道府県名が入っていない弁護士会は、道内に四つの会がある北海道を除けば横浜、金沢、仙台のみとなって
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:02／2015-11-12 10:16 URL： https://twitter.com/kk_hirono/status/1112324231209979904 https://twitter.com/hirono_hideki/status/664612781551845381
&twitter(1112324231209979904){theme:light}
> 容疑者妻連れ検事総長と面会　横浜弁護士会、検察出身弁護士を懲戒（カナロコ by 神奈川新聞） - Yahoo!ニュース https://t.co/VX0YSAjMm8
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:02／2015-11-15 09:13 URL： https://twitter.com/kk_hirono/status/1112324268002426880 https://twitter.com/hirono_hideki/status/665683930830479360
&twitter(1112324268002426880){theme:light}
> 除霊と称しみだらな行為　占い師に一部無罪、横浜地裁（カナロコ by 神奈川新聞） - Yahoo!ニュース https://t.co/PjMvlgqBWl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:02／2016-02-10 15:39 URL： https://twitter.com/kk_hirono/status/1112324309626707968 https://twitter.com/hirono_hideki/status/697308845396201472
&twitter(1112324309626707968){theme:light}
> “【速報】少年に懲役９～１３年判決　川崎中1殺害で裁判員裁判｜カナロコ｜神奈川新聞ニュース” https://t.co/rymLoOVtBA
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:02／2016-03-23 09:48 URL： https://twitter.com/kk_hirono/status/1112324349686538243 https://twitter.com/hirono_hideki/status/712440864887296000
&twitter(1112324349686538243){theme:light}
> 感熱紙(エイハブリアクター搭載)さんはTwitterを使っています: “「議員控室で覚せい剤」　葉山町議、使用容疑でも追送検へ（カナロコ by 神奈川新聞） – Yahoo!ニュース https://t.co/Yc56xi6VKf… https://t.co/jntBPP54CW
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:02／2016-10-25 08:11 URL： https://twitter.com/kk_hirono/status/1112324400106213383 https://twitter.com/hirono_hideki/status/790692102699089920
&twitter(1112324400106213383){theme:light}
> 逗子ストーカー殺人　遺族が市提訴へ（カナロコ by 神奈川新聞） - Yahoo!ニュース https://t.co/ckfQEMAIuU
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:03／2017-11-07 18:13 URL： https://twitter.com/kk_hirono/status/1112324469178011648 https://twitter.com/hirono_hideki/status/927826363070812160
&twitter(1112324469178011648){theme:light}
> ＼モトケン　@motoken_tw＼議員というのは次の選挙までのことしか考えないなら無敵だな。＞山尾氏 顧問に弁護士倉持氏（カナロコ by 神奈川新聞）  https://t.co/tG6tmrBUzp
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:03／2018-01-11 22:55 URL： https://twitter.com/kk_hirono/status/1112324561293307904 https://twitter.com/hirono_hideki/status/951452553295867904
&twitter(1112324561293307904){theme:light}
> 野宿者私物を無断で廃棄　「命に関わる」と支援者（カナロコ by 神奈川新聞） - Yahoo!ニュース https://t.co/AQWFslkl8A
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:03／2018-07-20 14:18 URL： https://twitter.com/kk_hirono/status/1112324604951814145 https://twitter.com/hirono_hideki/status/1020176028814065664
&twitter(1112324604951814145){theme:light}
> 【速報】中国人姉妹殺害　被告の男に懲役２３年の判決｜カナロコ｜神奈川新聞ニュース https://t.co/EmCXcTGWCZ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kmuramatsu（村松 謙） 日時：2019-03-31 21:04／2014-05-02 08:31 URL： https://twitter.com/kk_hirono/status/1112324664108290048 https://twitter.com/kmuramatsu/status/462011355541688320
&twitter(1112324664108290048){theme:light}
> 元准教授「ネットで中傷」　横浜地裁が教え子に賠償命令（カナロコ by 神奈川新聞） - Y!ニュース http://t.co/LSSMdGM11Z
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-31 21:04／2018-07-30 18:13 URL： https://twitter.com/kk_hirono/status/1112324703811624960 https://twitter.com/hirono_hideki/status/1023858991124738048
&twitter(1112324703811624960){theme:light}
> 姉暴行の男性に無罪判決　地裁支部が正当防衛認める（カナロコ by 神奈川新聞） - Yahoo!ニュース https://t.co/X8Q5mhcNpj
◁◁◁
<hr />

　news.kanaloco.jpというドメインは消滅しているようで、リンク切れです。次のリンクはつながりました。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/07/20 14:18％ https://twitter.com/hirono_hideki/status/1020176028814065664
&twitter(1020176028814065664){theme:light}
> 【速報】中国人姉妹殺害　被告の男に懲役２３年の判決｜カナロコ｜神奈川新聞ニュース https://t.co/EmCXcTGWCZ  
▶

　Twitterの短縮URLに変換されましたが、「www.kanaloco.jp/article/347393」とURLにある記事です。kanaloco.jpというドメイン自体は消滅していないようです。

　私は以前DNSサーバも独自で動かしたことがあるのですが、news.という部分が無効化されたのかもしれません。サブドメインのような割当も実際にやったことがあったのですが、数年前からDNSサーバを意識することもありませんし、用語としても見かけることが全くなくなっています。

　http://headlines.yahoo.co.jp というネットニュースがリンク切れが際立って早いです。なにかの契約の関係ではと思われますが、リンクだけを張ってもタイトル以外はリンク切れで事実上無意味となります。これは数年前からずっと同じ状況です。

　Twilogでの「カナロコ」の検索結果は、割と少ない数でしたが、カナコロではなくカナロコであったことも確認できました。すっかり忘れていた記事や、ちょっと思い出せないような記事のリンクもありました。

＜＜＜2019-03-31（日曜日）21：17＿［これまでの記述範囲の終了時刻］＜＜＜


* 告発の事実（再捜査の必要性及び社会的意義）

** 被告発人岡田進弁護士

*** 国選弁護人としての岡田進弁護士の活動
    :LOGBOOK:
    CLOCK: [2019-04-23 火 10:43]--[2019-04-23 火 12:16] =>  1:33
    :END:

＞＞＞2019-04-23（火曜日）10：43＿［これからの記述範囲の開始時刻］＞＞＞

　偶然なのか、これからというタイミングで輪島の生活保護の担当者の訪問がありました。偶然以外には考えられないですが、いきなりのことでした。今回は、本来ならば職業安定所で求職中の記載が必要などと言われたので、内容的には偶然ではない訪問にも思えました。

　来月にも訪問すると言われたので、新聞社と石川県議会にメールを送信すると伝えました。事情は把握されていると感じましたが、説明を求められることもありませんでした。次回は、電話をしてから訪問をするというようなことも言われました。

　３月３１日から中断をしていました。この間いろいろとありましたが、自分なりに状況を見定め今後の方針を練り上げていました。書いておきたいこと、取り上げたいことは山のようにあるのですが、厳選していくという選択肢というのも非常に難しものだと実感しています。

　私はいくらか関心はあるものの囲碁のルールをしらないのですが、先手を打つという意味は聞いたことがあります。にわかに始めたことですが、しばらく考えて、最初に打った手が被告発人岡田進弁護士になります。

　平成４年の傷害・準強姦被告事件で、私が金沢西警察署から金沢刑務所の拘置所に移送されたのが５月２８日のことでした。この日の日付はとてもよく覚えていますが、本来、初公判の期日として指定されていたことも大きいかと思います。

　傷害罪のみの起訴で裁判官は川口泰司でした。単独審だったのだと思います。それが準強姦での追起訴があって、三宅俊一郎裁判長、川口泰司裁判官、山田徹裁判官の合議制となり、それにともなって期日の取り消しとなったのだと思います。

　初公判は６月１８日となり、６月３０日にも公判があって、その後半の終わりに判決期日の指定があったように記憶しています。三宅俊一郎裁判長から被告発人岡田進弁護士に対して口頭で、期日に支障がないのかという確認があった場面も記憶に残っています。判決公判は８月３日でした。

　記憶はずいぶん薄れていますが、初公判というのは顔合わせ程度のもので、判決公判も判決の言い渡しのみでした。判決の読み上げの後、不服があれば控訴が出来ますと、やや力強い感じで三宅俊一郎裁判長が語りかけていました。

```
[9978]  % cal 5 1992
      5月 1992         
日 月 火 水 木 金 土  
                1  2  
 3  4  5  6  7  8  9  
10 11 12 13 14 15 16  
17 18 19 20 21 22 23  
24 25 26 27 28 29 30  
31
```

　上記のcalコマンドで確認すると、平成４年５月２８日は木曜日です。被告発人岡田進弁護士の１回だけの接見があったのは、移送されて２，３日後だったと記憶していますが、土日は免業日となっていて接見はなかったはずなので、５月２９日の可能性が高く、次いで６月１日となります。

　被告発人岡田進弁護士の接見については、記憶が新しい段階で余すことなく記述したものがあると思うので、今曖昧になった記憶のまま書く必要もないように思いますが、短い時間の接見で、帰り際に半開きのドアに、たぶん手をかけたまま、私を睨みつけながら帰っていきました。

　「酒は飲んでいましたか？」「５，６年は言ってくるでしょう。」が、接見での被告発人岡田進弁護士の発言の全てだったとも思います。最初に、警察署での取り調べや供述調書の作成で間違ったことはありませんね、という言質を取るような質問があったとも思います。

　当時の金沢刑務所の弁護士との接見室というのは、昭和４０年代によく見た個人病院のような雰囲気がありました。一般の面会室の奥にあったと思いますが、一般の面会室とは内部の装飾が違って、チンチラと呼ばれた車の内装の絨毯模様のような内装であったように思います。

　６月３０日の第２回公判は、実質的な審理がありましたが、打ち合わせのようなものは皆無だったので、あれよという間に結審し、判決公判の期日指定になりました。

　５月２８日に予定されていた初公判が取り消しとなり、６月中に２回の公判があり、８月３日に判決があったことはよく憶えています。６月３０日の２回目の公判のときに間違いないですが、公判の最初に江村正之検察官が、被害者安藤文さんの意識が戻ったという話をしました。

　あらためて不思議に思うのは、意識不明で植物人間の可能性も高かった被害者の意識が回復したという報告があったのに、まるで何事もなかったように審理が進んだことです。

＜＜＜2019-04-23（火曜日）12：16＿［これまでの記述範囲の終了時刻］＜＜＜


