#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "弁護士業界の現状／弁護士に大量懲戒請求／小倉秀夫弁護士／余命三年時事日記という名前のブログの開設者の住所・氏名を小倉先生が把握"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-25 05:05:30 +0900
FILE_NAME: 2018-12-25-050530_余命三年時事日記という名前のブログの開設者の住所・氏名を小倉先生が把握.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  大西洋一弁護士 モトケンこと矢部善朗弁護士（京都弁護士会） 小倉秀夫弁護士 弁護士に大量懲戒請求
記事タイトル名の文字数：63　保存ファイル名の文字数：57

#contents

* 12月24日の夜、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインで見つけた、リツイートによる大西洋一弁護士のツイート
  :LOGBOOK:
  CLOCK: [2018-12-25 火 05:19]
  :END:

＞＞＞2018-12-25（火曜日）05：19＿［これからの記述範囲の開始時刻］＞＞＞

　24日の夜はテレビで最近リメイクされたらしい「犬神家の一族」を見ていて、マスクの男が最後どうなるだったかと気にしながらいつのまにか寝ていました。起きたのはちょうど2時頃で、4時ちょっと前には電気もパソコンも消して寝ようとしたのですが眠れず。

　昨日の24日は、旧柳田村上町にある母親のいる病院に行き、そこにある北國新聞のテレビ欄で夜の番組を確認したつもりだったのですが、「犬神家の一族」のことはすっかり見落としていたようです。

　テレビをつけてチャンネルを変えていると歌番組が出てきて、そこに久保田利伸という歌手が出てきて、ずいぶん久しぶりだと思いながら番組表で番組名を確認したところ、そこに「犬神家の一族」を見つけ、すぐにチャンネルを変えたのです。

　昭和の時代、古谷一行が金田一耕助を演じていたことは「八つ墓村」については、少し前に取り上げたことがありますが、「犬神家の一族」のことはずっと忘れていたように思います。湖から二本の足を出す場面が有名でバラエティ番組でも真似をされていたことがありました。

　もう30年ちょっと前になると思いますが、「犬神家の一族」はテレビ放送かレンタルビデオで観たように思います。推理小説のようなもので最後はマスクの男の正体も明らかになり、事件が解決したはずですが、その結末が思い出せず、どうなるのかと気になっていました。

　といっても、集中してテレビの「犬神家の一族」を観ていたわけではなく、パソコンの方に集中して作業をしていました。なぜクリスマスの夜に昭和の時代の「犬神家の一族」なのかという疑問もありましたが、衝撃的な写真も目にしていたので、それとも重なりました。

　それというのも小倉秀夫弁護士の訴訟手続で判明したらしい、余命三年というネットで有名な人の実名でGoogle検索をし、画像検索をクリックしていくつか出てきた写真でした。本人かどうかも不明ですが、加工した写真という可能性もあるのかもしれません。

　以上書いた経緯を、奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のツイートで確認しておこうと思います。時間的な流れもあります。

　その前にモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインのスクリーンショットから始めます。リツイートの記録とあわせて。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-25 05:49／2018-12-24 20:12 URL： https://twitter.com/kk_hirono/status/1077305182038372352 https://twitter.com/s_hirono/status/1077159969684783109
&twitter(1077305182038372352){theme:light}
> 2018-12-24-193525_モトケンのリツイート（弁護士大西洋一　@o2441）：余命三年時事日記という名前のブログの開設者の住所・氏名を小倉先生が把握した模様。.jpg https://t.co/vwaJuDue6l
◁◁◁
<hr />

▷ リツイート→motoken_tw（モトケン）＞o2441（弁護士大西洋一）｜2018/12/24 12:51／2018/12/24 07:17｜https://twitter.com/motoken_tw/status/1077049001034174466 ／ https://twitter.com/o2441/status/1076964980514271233
&twitter(1077049001034174466){theme:light}
> RT @o2441: 余命三年時事日記という名前のブログの開設者の住所・氏名を小倉先生が把握した模様。
> 
> https://t.co/dFzjbM0eFp  

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-25 06:01／2018-12-24 19:30 URL： https://twitter.com/kk_hirono/status/1077308364344909824 https://twitter.com/hirono_hideki/status/1077149392547635200
&twitter(1077308364344909824){theme:light}
> 美濃加茂 市長 from:yjochi - Twitter検索 https://t.co/tPFWaQiFAS
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-25 06:01／2018-12-24 19:51 URL： https://twitter.com/kk_hirono/status/1077308402080964608 https://twitter.com/hirono_hideki/status/1077154684366860288
&twitter(1077308402080964608){theme:light}
> 鯨一匹捕れば七浦潤う(くじらいっぴきとればななうらうるおう)とは - コトバンク https://t.co/l3QkjPqxLy
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-25 06:02／2018-12-24 20:42 URL： https://twitter.com/kk_hirono/status/1077308655022657536 https://twitter.com/hirono_hideki/status/1077167656887676928
&twitter(1077308655022657536){theme:light}
> 「余命」に天誅！余命三年時事日記の嘘とワナを暴く。 | 余命から 損害と寄付金、名誉を取り戻す、余命被害者の名誉回復プロジェクト。 https://t.co/ubBH0IuZLY
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-25 06:03／2018-12-24 20:57 URL： https://twitter.com/kk_hirono/status/1077308705266253824 https://twitter.com/hirono_hideki/status/1077171352384106496
&twitter(1077308705266253824){theme:light}
> Hideo Ogura - 新聞報道だと、佐々木・北グループは「違法な懲戒請求を触発したブログ運営者は（懲戒請求をした人の）共同不法行... https://t.co/zoHTOOzXRu
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-25 06:03／2018-12-24 21:02 URL： https://twitter.com/kk_hirono/status/1077308740922073088 https://twitter.com/hirono_hideki/status/1077172564839944192
&twitter(1077308740922073088){theme:light}
> 特集ドラマ　アシガールSP～超時空ラブコメ再び～ \n  2018年12月24日（月）  21時00分～22時30分  の放送内容 https://t.co/akIcumT08Q
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-25 06:03／2018-12-24 21:12 URL： https://twitter.com/kk_hirono/status/1077308904122417152 https://twitter.com/hirono_hideki/status/1077175172526821376
&twitter(1077308904122417152){theme:light}
> 説明会は現場のすぐそばにある１５階建てマンション「ファミール平岸」の住民が対象で約８０人が参加。報道陣には非公開だった。佐藤社長や同社代理人の中村隆弁護士の説明では、全４２世帯のほぼ全てで窓ガラスの破損やサッシのゆがみなど、何らか… https://t.co/4nBg3JAjPO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-25 06:04／2018-12-24 21:26 URL： https://twitter.com/kk_hirono/status/1077308971315130368 https://twitter.com/hirono_hideki/status/1077178584366641152
&twitter(1077308971315130368){theme:light}
> 三浦友和　妻・百恵さんへの告白「還暦迎えても、僕は一生守りぬく！」（女性自身） - Yahoo!ニュース https://t.co/P7Di81t3Tc
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-25 06:04／2018-12-24 21:35 URL： https://twitter.com/kk_hirono/status/1077309013925064704 https://twitter.com/hirono_hideki/status/1077180846069542912
&twitter(1077309013925064704){theme:light}
> スペシャルドラマ　犬神家の一族 \n  2018年12月24日（月）  21時30分～23時33分  の放送内容 https://t.co/PDzc2nHuji
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-25 06:04／2018-12-24 21:35 URL： https://twitter.com/kk_hirono/status/1077309047211081728 https://twitter.com/hirono_hideki/status/1077181064848715777
&twitter(1077309047211081728){theme:light}
> CDTVスペシャル！クリスマス音楽祭2018 \n  2018年12月24日（月）  19時00分～23時24分  の放送内容 https://t.co/hdFRfRlzM2
◁◁◁
<hr />

　NHKで21時から少女がタイムスリップした時代劇をやっていたのを思い出し、昭和の時代もそんな映画があったことを思い出していました。「戦国自衛隊」という映画だったと思いますし、少女が斬り込む場面では「セーラー服と機関銃」という映画のことも思い出しました。

　「戦国自衛隊」はどうかはっきりしませんが、「セーラー服と機関銃」も当時流行りだった角川映画だったと思います。「犬神家の一族」についてもあとでそれらしい情報を見かけたように思います。

　タイムラインを見るとリツイートがあとになっていますが、ジャーナリストの江川紹子氏のタイムラインのツイートで、久しぶりに三浦友和という俳優のことを久しぶりに思い出し、そういえばここ最近テレビで姿を見かけていないように思いました。

▷ リツイート→hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞amneris84（Shoko Egawa）｜2018/12/24 21:49／2018/12/24 18:29｜https://twitter.com/hirono_hideki/status/1077184546905309184 ／ https://twitter.com/amneris84/status/1077134099490304000
&twitter(1077184546905309184){theme:light}
> RT @amneris84: 1番大事なことが書かれていないゴマカシ記事。「女性自身」は記事を誤報と認め、謝罪と訂正はしたのだろうか…？　→三浦友和　妻・百恵さんへの告白「還暦迎えても、僕は一生守りぬく！」（女性自身） - Yahoo!ニュース https://t.co/pid…  

　タイムラインをみると「2018-12-24 19:30」というのが家に戻ってから最初のツイートのようです。あとで書きたいと思いますが、家に戻ってからクジラのことを考え、調べたりしていました。「なんでもいいから弁護士儲ける」という言葉が頭に浮かんできたのです。

　その私にとって鯨肉の思い出というのは昭和40年代で、ちょうど三浦友和と山口百恵が映画で共演した頃であったと思います。たぶん「伊豆の踊子」という映画で、その主題歌というのが私が初めて買ったレコード盤でした。陰気な曲だったので少し後悔しました。それを選びました。

　旧柳田村の「しんやスーパー」で久しぶりに鯨肉をみたのもきっかけでした。宇出津港産となっていましたが、その後に買い物をした宇出津のAコープ能都店には、鮮魚コーナーに鯨肉が見当たりませんでした。

　この鯨肉のことは、落合洋司弁護士（東京弁護士会）や郷原信郎弁護士とあわせて記述をしたいと思います。

▷ リツイート→hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞funakoshi65（弁護士船越雄一）｜2018/12/24 22:29／2017/11/22 18:35｜https://twitter.com/hirono_hideki/status/1077194679098105856 ／ https://twitter.com/funakoshi65/status/933267757096845313
&twitter(1077194679098105856){theme:light}
> RT @funakoshi65: 先日の講演の総括見ないな感じです。やってみた！子どもたちへのネットリテラシー教育の第一歩！ https://t.co/0lRNwigPz5  

　22時前に寝てしまったのかと思っていたのですが、上記のリツイートをみると22時29分にリツイートをしています。ツイートの内容にあまり意味はなくリツイートをしたのですが、初めて見る実名弁護士アカウントのように思ったので、ちょっと残しておきました。

* モトケンこと矢部善朗弁護士（京都弁護士会）がリツイートした大西洋一弁護士について

　たまにリツイートとして他のタイムラインで見かけるぐらいで、大西洋一弁護士のアカウントのタイムライン自体を開くことはほとんどないと思います。以前はブロックされていた時期もあったのですが、そのあと私の３つのアカウントに立て続けでフォローをくれたようです。

　ヘッダの写真などに小さな子どもの写真があったり、子煩悩な人という印象もあります。頭もよく経営者としても有能というイメージです。同業者の弁護士に対してどう考えているのか疑問に思うことはありましたが、社会汚染の有害性は感じず、余り注視もしていません。

　ただ向こうからフォローを入れてきて、その後ブロックをしてきた滋賀県高島市の野田隼人弁護士のようなケースもあります。日付が変わっているので昨日の24日になりますが、同じモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでリツイートを見たように思います。

［link：］ モトケン(@motoken_tw) - Twilog https://twilog.org/motoken_tw/asc

▷ リツイート→motoken_tw（モトケン）＞sakamotomasayuk（坂本正幸）｜2018/12/24 10:54／2018/12/24 10:17｜https://twitter.com/motoken_tw/status/1077019693376974849 ／ https://twitter.com/sakamotomasayuk/status/1077010407477325824
&twitter(1077019693376974849){theme:light}
> RT @sakamotomasayuk: 左右関係ないけど、「我々がこう考えている、みんなもそうだ、それを言えないのは何か圧力があるからだ」という発想がおかしいという事に気が付かないとダメだろう
> これって「私何とかちゃん嫌い、あなたも嫌いよね」って言ってそれに賛同しない人をいじ…  

　そういえば、坂本正幸弁護士のツイートもモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでリツイートとして見かけていました。ちょっと長めですが、内容は読んでいなかったように思います。たまに見かけています。

　「村社会の発想そのものだよね」と書いてありました。そういえば、大分弁護士会あるいは大分県弁護士会の村八分での人権侵害のことを思い出しました。テレビでも期間をはさんで何度か取り上げられていました。愛媛のアイドル自殺問題などは、一度報道がなくなるとそれっきりです。

▷ リツイート→motoken_tw（モトケン）＞nodahayato（弁護士　野田隼人）｜2018/12/24 16:37／2018/12/24 15:27｜https://twitter.com/motoken_tw/status/1077106096223862784 ／ https://twitter.com/nodahayato/status/1077088314811867136
&twitter(1077106096223862784){theme:light}
> RT @nodahayato: 弁護士視点では「国民の信頼を得るため」が行き過ぎて権利保障が過少になっているのではないかという懸念があるが、マスコミの問題が大きいと感じている。  

　このところ弁護士がマスコミの報道を問題視するツイートをちょくちょくと見かけていますが、いちいち取り合ってはいられないとも考えていました。弁護士による人権侵害にも少しは目を向けてはどうかと思うのですが、それでは商売も成り立たないのでしょう。オワコンだと思います。

* 「余命三年時事日記という名前のブログの開設者の住所・氏名を開示する書類がエックスサーバ社から届いていた。」という小倉秀夫弁護士のFacebook投稿

　再掲しますが、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでリツイートとして見かけた次の大西洋一弁護士のツイートですが、そこにあるリンクのURLを開かずに、昨夜は調べていました。

▷ リツイート→motoken_tw（モトケン）＞o2441（弁護士大西洋一）｜2018/12/24 12:51／2018/12/24 07:17｜https://twitter.com/motoken_tw/status/1077049001034174466 ／ https://twitter.com/o2441/status/1076964980514271233
&twitter(1077049001034174466){theme:light}
> RT @o2441: 余命三年時事日記という名前のブログの開設者の住所・氏名を小倉先生が把握した模様。
> 
> https://t.co/dFzjbM0eFp  

　気がついてリンクを開いたのは、夜中の2時に目が覚めたあとだったと思います。早い段階でツイートをしているはずと思いますし、暫くあとになるかとも思いますが、スクリーンショットも記録しています。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/12/25 03:56％ https://twitter.com/hirono_hideki/status/1077276910646747139
&twitter(1077276910646747139){theme:light}
> Hideo Ogura - 休日出勤完了。なお、余命三年時事日記という名前のブログの開設者の住所・氏名を開示する書類がエックスサーバ社... https://t.co/EjukhYCpi6  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-25 06:53／2018-12-25 05:02 URL： https://twitter.com/kk_hirono/status/1077321438133022720 https://twitter.com/s_hirono/status/1077293345351684096
&twitter(1077321438133022720){theme:light}
> 2018-12-25-045938_Hideo　Ogura12月23日　18：24　·休日出勤完了。なお、余命三年時事日記という名前のブログの開設者の住所・氏名を開示する書類が.jpg https://t.co/ZHvKuA1knD
◁◁◁
<hr />

　余命三年というネット上の人物については、以前調べたことがあり、なにか顔写真のようなものも見ていたように思うのですが、小倉秀夫弁護士のプロバイダーへの開示請求の成功がきっかけで実名をみつけ、そちらで検索をしたところ全く見たことのないような写真が出てきました。

```
Hideo Ogura
12月23日 18：24 · 
休日出勤完了。なお、余命三年時事日記という名前のブログの開設者の住所・氏名を開示する書類がエックスサーバ社から届いていた。
70奥村 徹、他69人
コメント5件
シェア15件

［source：］Hideo Ogura - 休日出勤完了。なお、余命三年時事日記という名前のブログの開設者の住所・氏名を開示する書類がエックスサーバ社... https://www.facebook.com/hideo.ogura/posts/10156949365859732
```

　上記に小倉秀夫弁護士のFacebook投稿の全文を引用しましたが、ここに実名は載っていないようです。そうすると、どこで実名を見たのかも思い出せないのですが、同じように比較的短く完結な文章でした。たぶんツイートだと思います。

　なお、この大量の弁護士懲戒請求問題については、先日NHKのクローズアップ現代プラスだったと思いますがテレビで取り上げていました。調べれば確認できることですが、私の感覚では半月ほど前ではなかったかと思います。

　それより2,3カ月前、いやどれぐらい前かはっきりとは思い出せないですが、平日の朝8時からの情報番組モーニングショーでも取り上げていました。テレビ朝日系です。私は見逃したのですが、すぐに放送のあったことを知り、YouTube動画で視聴をしました。

　視聴は期間をはさんで2回別の動画を観ましたが、初めに観た動画は午前9時辺りを境に録画が終わっていたように思います。2回目に視聴した動画というのも、最初から最後の放送を録画したものであったのか、はっきり確認できませんでした。

　テレビの放送はいずれも弁護士側が一方的に理不尽な被害を受けたような話になっていました。実際にそうなのかもしれないですが、内容に偏りや決めつけがあるようにも感じられました。

　名前をすぐに忘れてしまうのでGoogleで調べて確認しましたが、モーニングショーには玉川徹というコメンテーターがよく出ていて、弁護士に対して同情的な解説をしながら弁護士は「100件の案件」を抱えている、などと話していたのがなにより印象的でした。

　今は、ロックされて投稿をしていない小倉秀夫弁護士のTwitterアカウントですが、以前はそれこそ文字通りの四六時中のツイートが壊れたラジオのように放送されていました。文字入力も早く頭の回転も早いのでしょうが、それにしてもまともに他の案件をどれだけこなせるのか疑問でした。

　モトケンこと矢部善朗弁護士（京都弁護士会）も小倉秀夫弁護士とは負けず劣らずの投稿頻度であった時期がありますし、現在も似たような傾向性です。京都市内の経営する法律事務所のホームページもありますが、それはツイートとして一度も見かけたことがありません。

＜＜＜2018-12-25（火曜日）07：18＿［これまでの記述範囲の終了時刻］＜＜＜

