#+TITLE: "深澤諭史弁護士の固定されたツイートに記事に疑問のリプライしていたアカウント、調べると凍結されていた"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-13 11:34:09 +0900
FILE_NAME: 2019-08-13-113409_深澤諭史弁護士の固定されたツイートに記事に疑問のリプライしていたアカウント、調べると凍結されていた.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士（第二東京弁護士会） 
記事タイトル名の文字数：49　保存ファイル名の文字数：71

* 深澤諭史弁護士の固定されたツイートに記事に疑問のリプライしていたアカウント、調べると凍結されていた
  :LOGBOOK:
  CLOCK: [2019-08-13 火 11:34]--[2019-08-13 火 15:04] =>  3:30
  :END:

＞＞＞2019-08-13（火曜日）11：34＿［これからの記述範囲の開始時刻］＞＞＞

　今朝は深澤諭史弁護士のタイムラインに小菅信子山梨学院大学教授ののツイートがリツイートされていて、そちらを取り上げておこうと思ったのですが、小菅信子氏についてあれこれ思い出していると、深澤諭史弁護士の固定ツイートのリプライのことが気になりました。

　小菅信子氏のツイートは、昨夜ずいぶん久しぶりに検索結果か何かで１つ見かけていたのですが、他に調べたり、慌ただしくしていたこともあり、一瞥しただけで終わっていました。

　昨夜は、清泉亮氏のことを中心に山梨県のことについて記述をしていましたが、山梨というと決まって思い出すのも、この小菅信子山梨学院大学教授のことでした。文章も読みやすくて関心を持つ人物ですが、他に優先することがありすぎて、タイムラインを開くこともほとんどありませんでした。

　もう5年ほど前になると思いますが、NHKの連続テレビ小説で山梨を舞台にしたものがありました。「花子とアン」ではなかったかと思います。平均すると5回に1回も視聴していたかという程度だったのですが、明治か大将時代の女学校の様子とか印象的なドラマでした。

　小菅信子山梨学院大学のTwitterアカウントも、以前は袴姿の写真で入学式の桜並木のような風景があって、余り見てはいなかったですが「花子とアン」の小説というかドラマに重なるものを感じていました。

　小菅信子氏は近代史や戦争研究の専門家のような人なので、記事を読むと視野が広まって興味深いこともあったのですが、実質弁護士研究のことをやっている私には、時間の割り振りとして深入りすることはなく、一時期かいつまんでのぞいた程度でした。

　それでも断片的に、小菅信子氏がネットで脅迫のような目に遭い、あの神原元弁護士に救われたとか、深澤諭史弁護士に法的なアドバイスを受けて、とても感謝している様子を見かけたことがありました。それだけ痛い目にあっていて、救われた思いがあったのかと想像もしました。

　小菅信子氏についても、先ほどから書いているようにツイートを読む機会も少なかったので、断片的に少しの知識しかありません。それでもかなり個性的な人物と思いますし、同じ女性ということもありますが、銀座の街弁というブログをしていた人によく似ているとも感じていました。

　銀座の街弁のブログは、はてなダイアリーでしたが、2,3年か前にはてなダイアリーは完全にサービスが廃止になりました。その前に一度、ブログを見たと思うのですが、それが最後で、小菅信子氏のことも昨日辺り久しぶりに思い出していたのですが、それ以上にずっと忘れていたように思います。

　銀座の街弁のブログはとても個性が強く、几帳面で具体的でした。いま巷では戦艦大和の設計図の映画が話題となっており、その戦艦大和の整形をした人に関する本を少し読んだことがありました。拘置所の官本だったかもしれません。その設計図のような几帳面さを感じていました。

　遠藤キミというお名前ではなかったかと思います。その経歴にも興味の惹かれるところがあって、訟務検事というのがあったかと思います。

　確認はまだしていませんが、遠藤キミ弁護士は、最初にブログをみるようになって。それほど経っていない頃、遠方の案件に対する個人的な思いをそまま記事に綴り、それで弁護士会の懲戒処分を受けていたこともあったと記憶します。それだけ個性が強い人物でした。

[link:] » 銀座のマチ弁から勝どきの宅弁へ(弁護士遠藤きみのブログ) (新) https://t.co/roMpKuxRZk

<hr />

　「遠藤キミ」で検索するとすぐに情報が見つかり、開くと本日2019年8月13日付の記事が出てきたので驚きました。数年前に介護されていたご主人が亡くなったという投稿をされていたので、年齢の方は記憶になかったですが、ずっと見かけなかったこともあり、ご他界の可能性も考えていました。

　「遠藤キミ」ではなく「遠藤きみ」が正しかったようですが、昭和の初めの頃の女性にはカタカナの名前を見かけたことが多く、そちらのイメージが重なって先行していたようです。言い換えれば、昭和の時代の小説の登場人物と重なるようなところが感じられていました。

　実際にそのような昭和の時代に女性が描いた小説というのは、いくつか読むことがありました。拘置所や刑務所での官本です。官本ではなく母親に差し入れられた文庫本でも「私は忘れない」を読みました。平成5年9月のことです。

　数年ぶりに遠藤きみ弁護士の記事を読みましたが、たまたまなのか一つの記事として短くはあったものの、日誌と家計簿を掛け合わせたような小説風でもある独自のスタイルの記述でした。

```
はてなID
tamago2
ニックネーム
tamago
一行紹介
高卒後山一證券に７年余り勤務(その間に通教で大学卒業）した後，司法試験に合格，元訟務検事，裁判官，１７年４月弁護士登録，夫の事務所の片隅で独立開業，夫死亡後の２６年１月から勝どきの自宅での宅弁に

性別
女

職業
弁護士

学校
中央大学法学部通信教育課程

住んでいるところ
東京都中央区

生まれたところ
東京都北区

特技
珠算(中学２年の時，日本商工会議所珠算能力検定試験１級合格)

［source：］tamagoさんのプロフィール - はてな http://profile.hatena.ne.jp/tamago2/
```

```
遠藤　きみ
@endokimi
高卒後山一證券に７年余り勤務。中大法学部通信教育課程卒業後司法試験合格。２５期の司法修習後，訟務検事12年，裁判官２０年。平成17年4月１５日から弁護士。
中央区銀座二丁目銀座遠藤法律事務所d.hatena.ne.jp/tamago2/2013年3月からTwitterを利用しています
0 フォロー中
0 フォロワー

［source：］遠藤　きみ（@endokimi）さん / Twitter https://twitter.com/endokimi
```

　前に見かけたTwitterアカウントと思いましたが、フォロー、フォロワーがともに０というだけではなく、投稿数まで０のようです。これは初めて見たように思いますし、この並外れた個性の強さというのも、弁護士や法律家にはありがちなものなのかと考えてしまいます。

[link:] » 遠藤きみ弁護士の業務停止 | 福岡若手弁護士のblog https://t.co/H3iKgYhMVz \n 2009-02-08 09:09:13

<hr />

　ブログのデザインの色合いが変わっているように思いましたが、ずいぶん久しぶりに見た見覚えのあるブログでした。記事の一覧をみると２０１２年から更新が止まっているようです。

```
②　遠藤きみ　32516　　東京　業務停止1月　　2009年3月
弁護士のブログに依頼者のことを書いた
https：//jlfmt.com/2009/11/21/28340/

［source：］弁護士懲戒処分「守秘義務違反の処分例」 – 弁護士自治を考える会 https://jlfmt.com/2015/04/25/30164/
```

　不服の申立をされたようなので、その分長引いたとも考えられますが、業務停止１月は思っていたより重い処分という気がしました。２００９年３月とありますが、私はその３月１５日に羽咋市から宇出津に戻りました。同日一杯という車の車検切れにあわせた日付でした。

　「弁護士のブログに依頼者のことを書いた」というのは簡潔な処分内容ですが、不当な訴えで気の毒だ、というような趣旨の発言であったように記憶の片隅にあります。実質よりも守秘義務の形式的保護を優先されたという印象でしたが、実質で見ると深澤諭史弁護士には看過し難い発言があります。

　本題に入りますが、遡ると深澤諭史弁護士の記事に対する疑問を、無関係な深澤諭史弁護士が固定したツイートに返信したものでした。深澤諭史弁護士は、その返信に対して直接返信せず、別のかたちでツイートをしていました。これはスクリーンショットの記録を見つけています。

[link:] 2019-07-21-202740_深澤諭史@fukazawas·3m迷惑なので広報用にトップ固定しているツイートに，それと無関係のリプライをぶら下げるのは，止めて頂けませんか？.jpg http://hirono2014sk.blogspot.com/2019/07/2019072315202019-07-18-0833362019-07-23.html#20190721202740#20190721202740 

[link:] 2019年07月21日20時27分の登録： ＼深澤諭史　@fukazawas＼迷惑なので広報用にトップ固定しているツイートに，それと無関係のリプライをぶら下げるのは，止めて頂けませんか？ http://hirono2014sk.blogspot.com/2019/07/fukazawas_34.html

　深澤諭史弁護士が回答したツイートは見かけなかったですが、先の参院選で選挙当日のリツイートが違反となる、というような内容ではなかったかと思います。記憶もあやふやとなっていますが、こういうのもしっかり示しておく必要は感じます。

　深澤諭史弁護士がTwilogの登録でもしていてくれれば、余計な手間も省けるのですが、流し網漁のように情報を垂れ流しんながら、カモのような被害者を引っ掛けるのを目的としているようにも思えるので、それも弁護士の営業の形態としてありなのかもしれません。

　手間がかかりますが、日付から深澤諭史弁護士の記事を探してみたいと思います。個人のブログ記事ではなく、ニュースサイトのニュース記事のようなものであったと思います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年07月21日 - Twilog https://t.co/1AdOCzqKeX

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-13 13:07／2019-07-21 12:37 URL： https://twitter.com/kk_hirono/status/1161127020366987264 https://twitter.com/hirono_hideki/status/1152784688148172800
&twitter(1161127020366987264){theme:light}
> 2019年07月21日12時05分の登録： ＼深澤諭史　@fukazawas＼１．苦し紛れに自分の身を守るために適当な嘘をつくのは止めましょう。特に弁護士相手に。\n２．自分の望みの答えが出るまで，似たような問いを繰 https://t.co/mqRnSoO4fi
◁◁◁
<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 14:26／2019-08-13 14:24 URL： https://twitter.com/kk_hirono/status/1161146870762131457 https://twitter.com/s_hirono/status/1161146374471073794
&twitter(1161146870762131457){theme:light}
> 2019-08-13-131454_【参院選２０１９】うっかり選挙違反にご注意　出されたおにぎり／投票日にＳＮＳ／「デマ」拡散（2／3ページ）　-　産経ニュース.jpg https://t.co/botDe314nS
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 14:26／2019-08-13 14:23 URL： https://twitter.com/kk_hirono/status/1161146895252635648 https://twitter.com/s_hirono/status/1161146301725102080
&twitter(1161146895252635648){theme:light}
> 2019-08-13-130918_奉納＼さらば弁護士鉄道・泥棒神社の物語（@hirono_hideki）／2019年07月21日　-　Twilog.jpg https://t.co/zEbRIHhjHO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 14:26／2019-08-13 14:23 URL： https://twitter.com/kk_hirono/status/1161146911379750912 https://twitter.com/s_hirono/status/1161146228677079040
&twitter(1161146911379750912){theme:light}
> 2019-08-13-105333_undefined（@honkeumebosi）さん　／　Twitter.jpg https://t.co/LNIwRa3ztE
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 14:26／2019-08-13 14:23 URL： https://twitter.com/kk_hirono/status/1161146947698171904 https://twitter.com/s_hirono/status/1161146155486437376
&twitter(1161146947698171904){theme:light}
> 2019-08-13-103254_深澤諭史さんはTwitterを使っています：　「これって非弁提携？弁護士のための非弁対策Q＆A　　Twitter.jpg https://t.co/ad4AdugwrA
◁◁◁
<hr />

　Twilogに、深澤諭史弁護士の固定ツイートに返信をしていた凍結されたアカウントのツイートが、私のリツイートとして普通に表示されていました。

　「@fukazawas 深沢様、失礼いたします。こちらの産経新聞の記事の内容について質問があります。」という内容の深澤諭史弁護士に対する質問のツイートから始まっているようです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nobuhir92556533（後藤信廣） 日時：2019-08-13 14:30／2019-07-21 15:22 URL： https://twitter.com/kk_hirono/status/1161148085839355904 https://twitter.com/nobuhir92556533/status/1152826055788384256
&twitter(1161148085839355904){theme:light}
> 投票に行って来ました。 \n   \n  １枚目の地方選挙区は、立憲の野田くによし👍 \n   \n  ２枚目の比例代表は、『れいわ』の『山本太郎』🥰に、投票しました。 \n   \n  出口調査は、NHKと朝日が居ました。 \n   \n  入る時に、NHKに、こちらから声掛け、質問に答え、… https://t.co/dU17Z6QPmc
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Godu_tan（ゴッドうーたん❄） 日時：2019-08-13 14:31／2019-07-21 11:53 URL： https://twitter.com/kk_hirono/status/1161148188415283205 https://twitter.com/Godu_tan/status/1152773589315096577
&twitter(1161148188415283205){theme:light}
> @jun_oq うーんどれでしょう...一応産経新聞がこんな記事書かれてますが... \n  総務省のHP見てますがそれに関する詳しい記述は見当たらない、若しくは僕が理解できてないか、ですねｗｗ \n  https://t.co/3cfY1Saxz3
◁◁◁
<hr />

　次が質問の対象となった深澤諭史弁護士のニュース記事のコメントになります。やはり産経ニュースの記事でした。

```
また、ＳＮＳでの選挙運動も認められるのは、公示日の立候補から投票日前日まで。ネット選挙の法令に詳しい深沢諭史弁護士は「投票日前日の午後１１時５９分５９秒までなので、ＳＮＳのリツイート（転載）が投票日当日になってしまうと処罰の対象になることもある」と話す。


　投票日当日に「みんなで投票に行こう！」と呼びかけるのはよいが、「私は○○候補に投票してきました！」と投稿するのは違法となる可能性があるというから、注意が必要だ。

［source：］【参院選２０１９】うっかり選挙違反にご注意　出されたおにぎり／投票日にＳＮＳ／「デマ」拡散（2/3ページ） - 産経ニュース https://www.sankei.com/life/news/190718/lif1907180013-n2.html
```

```
もちろん、ネット上に悪質な誹謗（ひぼう）中傷を書き込めば、名誉毀損（きそん）や侮辱など罪に該当することもある。特定の候補を当選させない目的をもって、候補者に関する虚偽の事実、つまり「デマ」を記載するのも公選法の処罰対象となる。

　深沢弁護士は「デマのニュースを、そのままＳＮＳなどで拡散するのもＮＧ。情報を発信するときは、信用できるニュースサイトなどから引用する必要がある」と警鐘を鳴らす。１８歳未満の選挙運動は認められないから、期間中は子供のＳＮＳ、ネットの書き込みにも、保護者は注意を配ったほうがよさそうだ。

［source：］【参院選２０１９】うっかり選挙違反にご注意　出されたおにぎり／投票日にＳＮＳ／「デマ」拡散（3/3ページ） - 産経ニュース https://www.sankei.com/life/news/190718/lif1907180013-n3.html
```

　凍結されたアカウントの人は、「は、深沢先生の認識を、新聞記者の方がこのように書かれたもので宜しいでしょうか。」と深澤諭史弁護士に質問を投げかけています。

　さらに「しかし、この記事を見た多くの人は「違法だからツイートを消すべき」だと捉えているようなのです。」と別のツイートで、戸惑いや影響が出ていると呼びかけているようです。しかし、これに対する回答のようなものは、一切深澤諭史弁護士のツイートとして見ませんでした。

　再掲になるかもしれないですが、次が、質問を投げかけ、凍結されたことで深澤諭史弁護士の固定ツイートの関連ツイートからツイートが根こそぎ消えたアカウントに対して、私が見たところ一つだけ返した深澤諭史弁護士のツイートになります。迷惑ということだけを伝えています。

▶ ツイート％fukazawas（深澤諭史）％2019/07/21 20:24％ https://twitter.com/fukazawas/status/1152902175787327489
&twitter(1152902175787327489){theme:light}
> 迷惑なので広報用にトップ固定しているツイートに，それと無関係のリプライをぶら下げるのは，止めて頂けませんか？ https://t.co/MCsR5bqSZI  
▶

　あらためて深澤諭史弁護士のツイートをみると、２０１９年７月２１日２０時２４分の投稿です。Twilogに私がリツイートした元のツイートの投稿時刻の表示が見当たらないと思いました。さいわい私の記録済みの情報から次の情報を得ることが出来ました。

```
[5456]  % cat 2017_法務検察当局宛て注目参考資料弁護士のリスト化ツイート_m/hirono_hideki_201610181947-201908130956.txt |grep 'honkeumebosi'
▶RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜honkeumebosi（本家うめぼし） 日時：2019-07-21 20:59／2019-07-21 20:25 URL： https://twitter.com/hirono_hideki/status/1152910891848892417 https://twitter.com/honkeumebosi/status/1152902388065304576 TWEET： @fukazawas 業務妨害でしたかね！さーせん！  
▶RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜honkeumebosi（本家うめぼし） 日時：2019-07-21 20:30／2019-07-21 20:11 URL： https://twitter.com/hirono_hideki/status/1152903738543108096 https://twitter.com/honkeumebosi/status/1152898888384167936 TWEET： @fukazawas この方のツイートは違法となるのでしょうか？ \n  \n 有権者が、投票日に、自分がどう考え、誰に投票したかを表明する自由は制限されるものなのですか？  
▶RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜honkeumebosi（本家うめぼし） 日時：2019-07-21 20:30／2019-07-21 20:09 URL： https://twitter.com/hirono_hideki/status/1152903721249935360 https://twitter.com/honkeumebosi/status/1152898339953770497 TWEET： @fukazawas 内容によっては「違法となる可能性がある」ものですよね。 \n  \n しかし、この記事を見た多くの人は「違法だからツイートを消すべき」だと捉えているようなのです。 \n やり取りの例を示します。 \n https://t.co/IDc8DIDzek  
▶RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜honkeumebosi（本家うめぼし） 日時：2019-07-21 20:30／2019-07-21 20:01 URL： https://twitter.com/hirono_hideki/status/1152903657295249409 https://twitter.com/honkeumebosi/status/1152896250343116802 TWEET： @fukazawas 記事内の \n 「「私は○○候補に投票してきました！」と投稿するのは違法となる可能性があるという」 \n  \n は、深沢先生の認識を、新聞記者の方がこのように書かれたもので宜しいでしょうか。  
▶RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜honkeumebosi（本家うめぼし） 日時：2019-07-21 20:30／2019-07-21 19:57 URL： https://twitter.com/hirono_hideki/status/1152903571379064832 https://twitter.com/honkeumebosi/status/1152895479996280832 TWEET： @fukazawas 深沢様、失礼いたします。こちらの産経新聞の記事の内容について質問があります。 \n  \n https://t.co/VofEwBEnFq  
```

　私のリツイートの時刻と元のツイートの投稿時刻は別のものですが、元のツイートの投稿時刻は、１９時５７分、２０時０１分、２０時０９分、２０時１１分、２０時２５分と続いていることが確認できました。深澤諭史弁護士の返信ツイートは２０時２４分です。短時間に集中していました。

　このような深澤諭史弁護士に対する具体的に指摘をした質問ツイートというのは、私が見る限り初めてのことで、深澤諭史弁護士が相手をブロックすることで、ぶら下がりの関連ツイートを消すことも考えたのですが、その後数日経ってからもツイートはそのまま表示されていました。

　私の奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントは深澤諭史弁護士にブロックされているので、深澤諭史弁護士のツイートに返信をつけることはできません。同様にブロックされているアカウントはいるのかもしれないですが、確認する情報は見かけていません。

　法クラのTwitterアカウントには、誰それをブロックしたとツイートするのもときたま見かけますが、深澤諭史弁護士の場合そういうのは見かけていないと思いますし、取材などメディアの露出も比較的多いのが深澤諭史弁護士のアカウントの特徴でもあります。

＜＜＜2019-08-13（火曜日）15：04＿［これまでの記述範囲の終了時刻］＜＜＜

