#+TITLE: "「病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？」という深澤諭史弁護士のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-06-25 17:32:10 +0900
FILE_NAME: 2019-06-25-173210_「病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？」という深澤諭史弁護士のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士（第二東京弁護士会）  深澤諭史弁護士 病院
記事タイトル名の文字数：53　保存ファイル名の文字数：75

* 「病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？」という深澤諭史弁護士のツイート

** 繰り返される深澤諭史弁護士自身のリツイート「病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」」
   :LOGBOOK:
   CLOCK: [2019-06-25 火 17:38]--[2019-06-25 火 18:43] =>  1:05
   :END:

＞＞＞2019-06-25（火曜日）17：38＿［これからの記述範囲の開始時刻］＞＞＞

　自分のツイートのリツイートというのは、そう見かけないものですが、繰り返しリツイートをするには前のリツイートを取り消してからやる必要があるようです。取り消したリツイートといのは削除されたツイートと同じで記録は残らないのだと思いますが。

▶ ツイート％fukazawas（深澤諭史）％2016/05/23 11:32％ https://twitter.com/fukazawas/status/734572617651347459
&twitter(734572617651347459){theme:light}
> 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。  
▶

　普通にTwitterのＷｅｂサイトでリツイートのURLをコピーすると得られるのは上記のように元のツイートの情報になります。2016年5月23日の投稿となっているツイートです。

　TwitterにはツイートのURLとは別にリツイートのURLがあるのですが、リツイートのURLを取得してもリンクが元のツイートに飛びます。これは普通にTwitterを使っていると気が付かない仕組みだと思いますし、リツイートのURLを取得するのも普通には出来ません。

　URLを取得し、データベースに登録するタイミングで記録できなかったリツイートもあるかと思うのですが、すでにかなりの数、データベースに深澤諭史弁護士自身のリツイートが記録済みかと思います。それを含めて新たに、まとめ記事を作成します。

[link:] 2019年06月25日17時51分の登録： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？”／データベース登録済みツイート：2019年06月25日17時50分の記録：ユーザ・投稿：33／89件 http://hirono2014sk.blogspot.com/2019/06/regexp2019062517503389.html

　これから投稿された上記のページを開いて内訳を確認します。ツイートとリツイートの別、その数が表として確認できるようにプログラムを作り込んでいます。ただテキストコピペしただけでは、レイアウトが多少崩れ気味なので、多少見づらくはあります。

```
アカウント名	ツイート数	リツイート数
深澤諭史（fukazawas）	1	24
ワーキングプア弁護士（sokudokubengosi）	0	1
ワーキングプア弁護士（sokudoku_65）	0	1
Nobuhiro Funakushi（nobu2794）	0	1
弁護士ワック（mackckckck）	0	1
弁護士 中村憲昭（nakanori930）	0	1
モトケン（motoken_tw）	0	1
中村剛（take-five）（take___five）	0	1
まめ之助（mamenske）	0	1
赤ネコ＠弁護士兼マンガ家（Redips00）	0	1
sapporobengoshi.com（okinawabengoshi）	0	1
弁護士篠田奈保子（yorisoibengoshi）	0	1
おのりえ（norie_law）	0	1
ルート６６（元ルパン３世）（Route66_LP3）	0	1
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	6	3
みなみかずゆき（弁護士　南和行　大阪）（minami_kazuyuki）	0	1
山口貴士 aka無駄に感じが悪いヤマベン（otakulawyer）	0	1
弁護士大西洋一（o2441）	1	0
北白川（GUv4i6）	0	1
非常上告-最高検察庁御中_ツイッター（s_hirono）	24	0
ねこ好き（abcabcabc999666）	0	1
泥濘大魔王サイケ（k_sawmen）	0	2
中村元弥（1961kumachin）	0	1
藤岡孝司＠飯塚（fujiokabengoshi）	0	1
yuji kigami　木上雄二（39801）	0	1
微笑みのロイヤー（smile_spirits）	0	1
都 行志（Miyako_Koji）	0	1
ぽぽひと@死して屍動けばゾンビ（popohito）	0	1
浜ちゃん（lawer_hamachan）	0	1
弁護士 中原潤一（lawyernakahara）	0	1
けっす（keskil_）	0	1
中野 俊徳（kanonjilawfirm）	0	1
まゆこ（mayukotaniguchi）	0	1

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？”／データベース登録済みツイート：2019年06月25日17時50分の記録：ユーザ・投稿：33／89件 http://hirono2014sk.blogspot.com/2019/06/regexp2019062517503389.html
```

　深澤諭史弁護士のツイートの数が1件、同じくリツイートの数が24件となっており、私の非常上告-最高検察庁御中_ツイッター（@s_hirono）のツイートが24件となっていて、これは全てスクリーンショットの記録の可能性が高いと思います。

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？」の検索結果 - Twilog https://t.co/UPD4XZgEIb

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-25 18:05／2016-05-27 06:15 URL： https://twitter.com/kk_hirono/status/1143445011402387456 https://twitter.com/s_hirono/status/735942484451155969
&twitter(1143445011402387456){theme:light}
> 2016-05-27-061529_深澤諭史@fukazawas病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗.jpg https://t.co/2QpIPpBKL1
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-25 18:05／2016-10-12 20:32 URL： https://twitter.com/kk_hirono/status/1143445037151162369 https://twitter.com/s_hirono/status/786167741132582916
&twitter(1143445037151162369){theme:light}
> 2016-10-12-203245_深澤諭史さんがリツイート深澤諭史　@fukazawas　5月23日病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？.jpg https://t.co/wRMrwbNXCY
◁◁◁
<hr />

　ざっとみたところ、スクリーンキャストの動画が１つあって、ブラウザの画面ではない、仮想端末の画面も２つほど確認しました。すべてが深澤諭史弁護士のリツイートに対応した記録ではなかったようです。さきほど記録したものもまだアップロードしていませんでした。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-25 18:10／2019-06-25 18:08 URL： https://twitter.com/kk_hirono/status/1143446312504852481 https://twitter.com/s_hirono/status/1143445735456661504
&twitter(1143446312504852481){theme:light}
> 2019-06-25-144847_深澤諭史さんがリツイート＞　深澤諭史（@fukazawas）：　病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でや.jpg https://t.co/sCeLZQ2sUB
◁◁◁
<hr />

　ちょっとデータベースの方を直接操作して、深澤諭史弁護士自身のリツイートがいくつ記録されているのか、そのリツイートの時期をあわせて確認しておきたいと思います。弁護士としての不変で強固な意志も確認できるし、病理的な現象の1つだと私は見ています。

```
mysql -u root benngosi_twitter -e 'SELECT * FROM tw_user_tweet WHERE tweet LIKE "%俺，医療には詳しいんで，それで盲腸手術なんか%" AND user LIKE "fukazawas" \G'

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 1. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 55421
           name: 深澤諭史
        rt_name: 
         tw_url: https://twitter.com/fukazawas/status/734572617651347459
         rt_url: 
        tw_date: 2016-05-23 11:32:00
        rt_date: 0000-00-00 00:00:00
          tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 
        retweet: 0
           user: fukazawas
 statuses_count: 40594
        rt_user: 
    create_time: 2016-05-23 14:20:51
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter Web Client
       location: 東京
followers_count: 2315
  friends_count: 375
       rt_count: 770
      fav_count: 433
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 2. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 75135
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/786137103461560320
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2016-10-12 18:31:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 43105
        rt_user: fukazawas
    create_time: 2016-10-12 19:50:43
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 2637
  friends_count: 403
       rt_count: 4577
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 3. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 75234
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/786221235524866048
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2016-10-13 00:05:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 43124
        rt_user: fukazawas
    create_time: 2016-10-13 00:40:48
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter Web Client
       location: 東京
followers_count: 2639
  friends_count: 363
       rt_count: 4583
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 4. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 82958
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/804614456504262656
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2016-12-02 18:13:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 44423
        rt_user: fukazawas
    create_time: 2016-12-02 20:23:55
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Windows
       location: 東京
followers_count: 2727
  friends_count: 372
       rt_count: 4710
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 5. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 83031
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/804884400202625024
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2016-12-03 12:06:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 44424
        rt_user: fukazawas
    create_time: 2016-12-03 17:43:12
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Windows
       location: 東京
followers_count: 2734
  friends_count: 372
       rt_count: 4881
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 6. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 84202
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/807883920121282560
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2016-12-11 18:45:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 44587
        rt_user: fukazawas
    create_time: 2016-12-12 13:25:30
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 2745
  friends_count: 373
       rt_count: 4933
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 7. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 92693
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/823365397378310144
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-01-23 12:03:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 46723
        rt_user: fukazawas
    create_time: 2017-01-23 12:59:33
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 2835
  friends_count: 388
       rt_count: 4936
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 8. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 100894
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/838695905842745345
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-03-06 19:21:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 49020
        rt_user: fukazawas
    create_time: 2017-03-07 02:24:24
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 2942
  friends_count: 406
       rt_count: 5205
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 9. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 101213
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/839071378498170880
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-03-07 20:13:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 49118
        rt_user: fukazawas
    create_time: 2017-03-08 12:05:15
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 2946
  friends_count: 407
       rt_count: 5224
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 10. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 101442
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/839673217828573186
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-03-09 12:04:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 49217
        rt_user: fukazawas
    create_time: 2017-03-09 12:45:17
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 2946
  friends_count: 403
       rt_count: 5237
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 11. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 101857
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/840534451025145856
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-03-11 21:06:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 49382
        rt_user: fukazawas
    create_time: 2017-03-12 11:12:02
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 2966
  friends_count: 403
       rt_count: 5287
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 12. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 103965
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/845478713814757376
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-03-25 12:33:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 50187
        rt_user: fukazawas
    create_time: 2017-03-25 12:58:07
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 3038
  friends_count: 394
       rt_count: 5427
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 13. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 105172
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/848372968723955712
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-04-02 12:14:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 50549
        rt_user: fukazawas
    create_time: 2017-04-04 13:25:51
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 3054
  friends_count: 396
       rt_count: 5726
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 14. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 105798
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/850915962429648896
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-04-09 12:39:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 50770
        rt_user: fukazawas
    create_time: 2017-04-09 19:47:01
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 3134
  friends_count: 396
       rt_count: 5722
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 15. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 111126
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/863644176415469569
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-05-14 15:36:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 52195
        rt_user: fukazawas
    create_time: 2017-05-15 08:43:39
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter Web Client
       location: 東京
followers_count: 3188
  friends_count: 400
       rt_count: 5750
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 16. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 112813
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/869049959454097408
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-05-29 13:37:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 53193
        rt_user: fukazawas
    create_time: 2017-05-29 20:29:43
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter Web Client
       location: 東京
followers_count: 3201
  friends_count: 402
       rt_count: 5747
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 17. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 130266
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/896983608639934464
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-08-14 15:35:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 56010
        rt_user: fukazawas
    create_time: 2017-08-14 20:47:20
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Android
       location: 東京
followers_count: 3334
  friends_count: 417
       rt_count: 5718
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 18. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 133513
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/903871793227751425
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-09-02 15:46:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 56725
        rt_user: fukazawas
    create_time: 2017-09-02 16:35:52
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter Web Client
       location: 東京
followers_count: 3354
  friends_count: 422
       rt_count: 5735
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 19. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 145595
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/926271985306316800
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-11-03 11:17:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 58771
        rt_user: fukazawas
    create_time: 2017-11-04 09:33:48
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for Windows
       location: 東京
followers_count: 3411
  friends_count: 436
       rt_count: 5711
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 20. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 170048
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/936805158838665217
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-12-02 12:52:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 0
        rt_user: fukazawas
    create_time: 2018-01-30 12:45:49
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for iPhone
       location: 東京
followers_count: 3463
  friends_count: 438
       rt_count: 5722
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 21. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 181400
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/945096089769721856
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2017-12-25 09:57:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 0
        rt_user: fukazawas
    create_time: 2018-01-30 12:45:50
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for iPhone
       location: 東京
followers_count: 3492
  friends_count: 443
       rt_count: 5741
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 22. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 194046
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/959626370232983554
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2018-02-03 12:15:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 0
        rt_user: fukazawas
    create_time: 2018-02-03 19:37:02
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter for iPhone
       location: 東京
followers_count: 3596
  friends_count: 450
       rt_count: 5743
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 23. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 214131
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/975250282178232320
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2018-03-18 14:59:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 0
        rt_user: fukazawas
    create_time: 2018-03-18 20:40:39
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。
詳しくは、 IT法務.jp をご覧下さい
            app: Twitter Web Client
       location: 東京
followers_count: 3648
  friends_count: 461
       rt_count: 5727
      fav_count: 0
            tag: 
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 24. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 343937
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/1132448794925076480
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2019-05-26 09:50:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 87980
        rt_user: fukazawas
    create_time: 2019-05-26 10:55:03
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。 詳しくは、 IT法務.jp もご覧下さい。相談等ご依頼はTwitterでなく事務所あるいはブログ掲載のメールアドレスまで。
            app: Twitter for iPhone
       location: 東京
followers_count: 5545
  friends_count: 464
       rt_count: 5970
      fav_count: 0
            tag: nil
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊ 25. row ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
             id: 344513
           name: 深澤諭史
        rt_name: 深澤諭史
         tw_url: https://twitter.com/fukazawas/status/1132999079753990144
         rt_url: https://twitter.com/fukazawas/status/734572617651347459
        tw_date: 2019-05-27 22:16:00
        rt_date: 2016-05-23 11:32:00
          tweet: RT @fukazawas: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
      org_tweet: 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。
        retweet: 1
           user: fukazawas
 statuses_count: 88039
        rt_user: fukazawas
    create_time: 2019-05-27 22:25:28
        profile: 弁護士（第二東京弁護士会）。アイコンはフォロワーのロー生作。ＩＴ法務（システム開発紛争，ネットトラブル・誹謗中傷，ＩＴ企業の一般法務）を中心に，労働事件や刑事弁護を取り扱っています。 詳しくは、 IT法務.jp もご覧下さい。相談等ご依頼はTwitterでなく事務所あるいはブログ掲載のメールアドレスまで。
            app: Twitter for iPhone
       location: 東京
followers_count: 5551
  friends_count: 466
       rt_count: 6022
      fav_count: 0
            tag: nil

　上記に「create_time」とある項目が、データベースのフィールドになりますが、データベースへの記録の時点の日時になります。フォロワー数やリツイートの数なども、ほぼその時点で取得した情報になります。リツイートを繰り返すたびにリツイートの数も増えているようです。

　私は、大学の教育機関や弁護士会の製造物責任のようなものを深澤諭史弁護士にはとりわけ強く感じています。危険生物という表現も、その社会的に優位な立場や影響を考慮すれば、言い過ぎた表現とは思えないですし、的確な記録資料と考えています。

　深澤諭史弁護士の場合、具体的には東京大学大学院や第二東京弁護士会との関わりになります。深澤諭史弁護士の言動の特異性は、この「病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？」というツイートに限らないものです。

　挙げれば切りがないというのが現実でありますし、私の問題意識とは真逆に、深澤諭史弁護士の弁護士としての社会的活躍や評価には目覚ましいものがあると感じておりますし、まるでとんでもない漫画のような快進撃と言っても言い過ぎはないように思います。

　深澤諭史弁護士については、是が非にでも取り上げておきたかったツイートが２つあったのですが、今回はそのうちの１つを、これまでの予定を変えて１つ取り上げることとなりました。

＜＜＜2019-06-25（火曜日）18：43＿［これまでの記述範囲の終了時刻］＜＜＜

