#+TITLE: "吹田市の警察官刺傷拳銃強奪事件につき「実名報道で得られる利益よりも重大な利益が失われてるようにしか見えない」という深澤諭史弁護士のリツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-06-18 21:53:51 +0900
FILE_NAME: 2019-06-18-215351_吹田市の警察官刺傷拳銃強奪事件につき「実名報道で得られる利益よりも重大な利益が失われてるようにしか見えない」という深澤諭史弁護士のリツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士（第二東京弁護士会）  深澤諭史弁護士のリツイート 刑裁サイ太 実名報道 吹田市の警察官刺傷拳銃強奪事件
記事タイトル名の文字数：70　保存ファイル名の文字数：92

* 吹田市の警察官刺傷拳銃強奪事件につき「実名報道で得られる利益よりも重大な利益が失われてるようにしか見えない」という深澤諭史弁護士のリツイート
  :LOGBOOK:
  CLOCK: [2019-06-18 火 21:55]--[2019-06-19 水 00:28] =>  2:33
  :END:

＞＞＞2019-06-18（火曜日）21：55＿［これからの記述範囲の開始時刻］＞＞＞

▷ リツイート→fukazawas（深澤諭史）＞uwaaaa（サイ太）｜2019/06/18 10:36／2019/06/18 10:26｜https://twitter.com/fukazawas/status/1140795507851218944 ／ https://twitter.com/uwaaaa/status/1140792859857047552
&twitter(1140795507851218944){theme:light}
> RT @uwaaaa: 被害に遭った警察官の情報も出回っていて，顔写真や経歴はおろか，卒業した高校や大学の偏差値まで公開されてたんだけど，僕には実名報道で得られる利益よりも重大な利益が失われてるようにしか見えないよ  

　あらためて深澤諭史弁護士のリツイートの情報を仔細に見ると、刑裁サイ太のツイートが本日１０時２６分、深澤諭史弁護士のリツイートが同じく１０時３６分となっています。私が目撃したのもお昼の前後だったと思いますが、記録のスクリーンショットを作成しているはずです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-18 23:13／2019-06-18 11:13 URL： https://twitter.com/kk_hirono/status/1140986000665006080 https://twitter.com/s_hirono/status/1140804812809723904
&twitter(1140986000665006080){theme:light}
> 2019-06-18-110945_深澤諭史さんがリツイート＞　サイ太（@uwaaaa）：　責任能力に問題があるっぽい言動してるのに実名報道するのは，ガイドライン違反なんじゃないんですか？.jpg https://t.co/hFM2j47QyH
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-18 23:14／2019-06-18 11:14 URL： https://twitter.com/kk_hirono/status/1140986041089683456 https://twitter.com/s_hirono/status/1140804885354434560
&twitter(1140986041089683456){theme:light}
> 2019-06-18-111115_深澤諭史さんがリツイート＞　暇弁（暇とは言ってない）（@himaben1st）：　個人のプライバシーは「重大な利益」ではないんだよ，きっと。.jpg https://t.co/5KSF2xdKiX
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-18 23:14／2019-06-18 11:14 URL： https://twitter.com/kk_hirono/status/1140986079698276355 https://twitter.com/s_hirono/status/1140804957576155136
&twitter(1140986079698276355){theme:light}
> 2019-06-18-111154_深澤諭史さんがリツイート＞　サイ太（@uwaaaa）：　被害に遭った警察官の情報も出回っていて，顔写真や経歴はおろか，卒業した高校や大学の偏差値まで公開.jpg https://t.co/m7TnHgyXAM
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-18 23:14／2019-06-18 12:07 URL： https://twitter.com/kk_hirono/status/1140986108714471427 https://twitter.com/s_hirono/status/1140818193067335681
&twitter(1140986108714471427){theme:light}
> 2019-06-18-112038_サイ太さんのツイート：　”責任能力に問題があるっぽい言動してるのに実名報道するのは，ガイドライン違反なんじゃないんですか？”.jpg https://t.co/LCEZR8zAq4
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-18 23:14／2019-06-18 12:07 URL： https://twitter.com/kk_hirono/status/1140986131871195137 https://twitter.com/s_hirono/status/1140818265465188352
&twitter(1140986131871195137){theme:light}
> 2019-06-18-112127_サイ太さんのツイート：　”被害に遭った警察官の情報も出回っていて，顔写真や経歴はおろか，卒業した高校や大学の偏差値まで公開されてたんだけど，僕には実名報道.jpg https://t.co/t7V1pmW86P
◁◁◁
<hr />

　時刻は２３時１５分です。２２時２２分とテレビで情報があったと思いますが、新潟県の村上市で震度６強、山形県の鶴岡市で震度６弱という地震があり、すぐに津波注意報が出ています。ちょうどNHKで保釈をテーマとした番組をみている途中でした。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-18 23:20／2019-06-18 19:48 URL： https://twitter.com/kk_hirono/status/1140987671134605312 https://twitter.com/hirono_hideki/status/1140934332082614272
&twitter(1140987671134605312){theme:light}
> クローズアップ現代+ - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/U4ebebh5uU \n  もし、身近な人が逮捕されたら？長期勾留に批判もある日本の司法制度が揺れている。一方、保釈された被告が逃亡し、東京地検“トクシツ”が追跡。あなたはどう考えますか？
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-18 23:20／2019-06-18 19:48 URL： https://twitter.com/kk_hirono/status/1140987695465762816 https://twitter.com/hirono_hideki/status/1140934244882976770
&twitter(1140987695465762816){theme:light}
> クローズアップ現代＋「あなたが逮捕されたら検察内部にカメラ密着▽保釈が変わる」 \n   \n  2019年6月18日（火）  22時00分～22時30分  の放送内容 https://t.co/U4ebebh5uU
◁◁◁
<hr />

　番組の途中に緊急地震速報が出ましたが、テレビの画面の中央に大きく表示されたのは初めて見ました。最も被害の大きい可能性のある村上市付近の情報は入っておらず、警察や消防署、役所に電話がつながらない状況とのことでした。鶴岡市では大きな被害は確認していないとのこと。

　私の住む石川県の地方も１メートルの津波到達予想で津波注意報が出ていますが、日本海側で津波予想とはまったく予想外でした。新潟県でも中越地方は過去に地震の多い地域でしたが、山形県に近い村上市に大きな地震というのは、まったく専門家の予想も見たことがありませんでした。

　能登地方でも震度３という観測が情報が出ていますが、地震速報が確か秋田県から山形県と出ていたので、注意して身構えたのですが、揺れのようなものは感じませんでした。

　大きな地震で思い出すのは、熊本地震の後の深澤諭史弁護士のTwitterタイムラインです。現時点の深澤諭史弁護士のタイムラインは、普段と変わらず平常運航という感じです。このところ火山活動のような波立つ活性化を感じていた深澤諭史弁護士のタイムラインでもあります。

　時刻は２３時４１分です。テレビのチャンネルをテレビ金沢のzeroに変えたタイミングで、新潟県村上市の被害情報が読み上げられていました。ケガ人の情報だったようですが、大きなケガではないようでした。

　新潟県と山形県の国道７号線の境に鼠ヶ関という地名があるのですが、今回の地震と津波の報道で初めて「ねずがせき」と読むのだと知りました。入ってくる情報を読み上げていた女子アナも途中で「ねずみがせき」から読み替えていました。

　国道３４５号線で落石があり通行止めという情報がテレビにありましたが、金沢市場輸送の４t保冷車に乗務していた頃、海沿いの三百台の国道で、山形県から新潟県に通り抜けようとしたところ、途中で通行が無理だと判断して引き返したということがありました。昭和５９年です。

　今回の地震と津波の報道では、輪島港の漁船の数が３００隻だと知りました。そのうち２５０隻ほどが、灯りを照らして港の外に避難したとのことです。地形的に津波の向きが輪島港に直撃するとは考えにくく、地元の宇出津港の方が津波が来る方向を向いているように思います。

　現在は村上市が山形県と県境になっているようですが、昭和の終わり頃は、村上市と山が県境との間に、北蒲原郡があったはずかと思います。ミールを運んで養鶏場に行った運行が特に印象に残っていて、これまでに取り上げたこともあったかと思います。缶酎ハイで足元がふらついたことなど。

　同じ頃に金沢市八日市の焼肉屋で、酎ハイを飲んで酔いが回り、外の踏切のような道路にへたりこんだことも書いたと思いますが、若者が焼酎を飲むようになり、酎ハイが流行ったのも社会的な変化ではなかったかと思います。焼酎に対するイメージもずいぶん変わりました。

　テレビの報道ステーションでは、北陸地方を中心に大きな地震があったと繰り返していますが、新潟県の村上市というのは東北地方の山形県に近く、日本一横に長いとも聞いたことのある新潟県全体でも、北陸地方に含める場合と含めない場合があるようなので、かなり違和感を感じます。

　これまで余り耳にしたことがなかったのですが、新潟県の山形県よりは下越ということで、新潟市内も下越になるという情報を先にTwitterの検索タイムラインで見かけていました。中越や上越というのはよく見聞きしてきました。

　さきほどは報道ステーションで、新潟県村上市役所からの中継がありましたが、今のところ大きな被害は確認されていないようです。津波ということでは、数年前にも福島県の小名浜港などで到達予想が大きく報道されていましたが、漁港の小型漁船が転覆する以上の被害は出なかったようです。

　繰り返しになりますが、大きな地震で思い起こすのは、熊本地震時の深澤諭史弁護士のタイムラインです。余震の方が大きかったというのも他に例を知らない地震でしたが、その最初の自信がM６．５、今回の山形県沖の自信がM６．８という情報もテレビでみています。

＜＜＜2019-06-19（水曜日）00：28＿［これまでの記述範囲の終了時刻］＜＜＜

