#+TITLE: "深澤諭史弁護士（第二東京弁護士会）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-07-18 11:44:07 +0900
FILE_NAME: 2019-07-18-114407_深澤諭史弁護士（第二東京弁護士会）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士（第二東京弁護士会） 
記事タイトル名の文字数：17　保存ファイル名の文字数：39

* 深澤諭史弁護士（第二東京弁護士会）

** 「否認すると，あっさり勾留請求してくるんだよなぁ・・，いまだに。「勾留請求するな。」って意見書もだしたのに・。」という深澤諭史弁護士のツイート
   :LOGBOOK:
   CLOCK: [2019-07-18 木 12:54]--[2019-07-18 木 13:41] =>  0:47
   :END:

＞＞＞2019-07-18（木曜日）12：54＿［これからの記述範囲の開始時刻］＞＞＞

▶ ツイート％fukazawas（深澤諭史）％2019/07/18 10:10％ https://twitter.com/fukazawas/status/1151660485827108866
&twitter(1151660485827108866){theme:light}
> 否認すると，あっさり勾留請求してくるんだよなぁ・・，いまだに。
> 「勾留請求するな。」って意見書もだしたのに・。
> なお，同様の意見を裁判所にも述べて，無事に勾留請求却下。  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-07-18 13:08／2019-07-18 13:00 URL： https://twitter.com/kk_hirono/status/1151705165478551552 https://twitter.com/s_hirono/status/1151703370219966464
&twitter(1151705165478551552){theme:light}
> 2019-07-18-125751_櫻井光政さんがリツイート＞　深澤諭史（@fukazawas）：　否認すると，あっさり勾留請求してくるんだよなぁ・・，いまだに。「勾留請求するな。」って意.jpg https://t.co/pfAOQCEmSp
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-07-18 13:08／2019-07-18 13:00 URL： https://twitter.com/kk_hirono/status/1151705191990775808 https://twitter.com/s_hirono/status/1151703297134194688
&twitter(1151705191990775808){theme:light}
> 2019-07-18-125150_深澤諭史さんのツイート：　”否認すると，あっさり勾留請求してくるんだよなぁ・・，いまだに。　「勾留請求するな。」って意見書もだしたのに・。　なお，同様の意.jpg https://t.co/n3YpUV7Ane
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-07-18 13:08／2019-07-18 13:00 URL： https://twitter.com/kk_hirono/status/1151705215051059200 https://twitter.com/s_hirono/status/1151703224673394690
&twitter(1151705215051059200){theme:light}
> 2019-07-18-125112_深澤諭史さんのツイート：　”否認すると，あっさり勾留請求してくるんだよなぁ・・，いまだに。　「勾留請求するな。」って意見書もだしたのに・。　なお，同様の意.jpg https://t.co/JohS3QpmI3
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-07-18 13:08／2019-07-18 13:00 URL： https://twitter.com/kk_hirono/status/1151705239621292034 https://twitter.com/s_hirono/status/1151703151688314886
&twitter(1151705239621292034){theme:light}
> 2019-07-18-114208_深澤諭史（@fukazawas）：　否認すると，あっさり勾留請求してくるんだよなぁ・・，いまだに。「勾留請求するな。」って意見書もだしたのに・。なお，同.jpg https://t.co/KmgUzLICGk
◁◁◁
<hr />

[link:] 2019年07月18日11時41分の登録： ＼深澤諭史　@fukazawas＼否認すると，あっさり勾留請求してくるんだよなぁ・・，いまだに。\n「勾留請求するな。」って意見書もだしたのに・。\nなお，同様の意見を裁判所 http://hirono2014sk.blogspot.com/2019/07/fukazawas_18.html

[link:] 2019年07月18日11時41分の登録： ＼櫻井光政　@okinahimeji＼否認、黙秘のまま、勾留請求が却下されました。意見書では検事が黙秘を勾留請求の理由にしていることを批判しました。 http://hirono2014sk.blogspot.com/2019/07/okinahimeji_18.html

　あらためて確認すると投稿時刻が本日１０時１０分の深澤諭史弁護士のツイートです。最初のスクリーンショットの記録が2019-07-18-114208でした。思っていたより時間差がありましたが、目を疑う衝撃を受けました。まるっきり漫画の世界のスーパー弁護士のようです。

　事実関係や背景事情が全く不明ですが、「「勾留請求するな。」って意見書もだした」というのは検察庁が相手なのでしょう。これを頼もしい、頼りになる弁護士と考える人はいるのかもしれないですが、挑発、愚弄としていっそう不利な扱いを受ける可能性もありそうです。

　ともあれ、櫻井光政弁護士がリツイートをしているというのは、一種のお墨付きというか、それが刑事弁護の現状でもあるのでしょう。顧客というか依頼者のニーズや立場もあるのかとは想像しますが、それにしてもただただ驚きました。漫画でもあり得ないストーリー展開です。

　素人なので確実とは言えないですが、深澤諭史弁護士のツイートの内容では、否認すると勾留請求してきたと読めます。勾留請求というのは、逮捕に続く手続きかと思います。任意捜査で否認をして勾留請求だとしても、逮捕状の請求なしに、いきなりというのは疑問です。

　通常問題になるのも、逮捕の後の勾留請求ではないかと思います。裁判所が勾留請求を認めなかったということでニュースになるのは、たまに見ることがあります。

　検察庁が独自で捜査をする場合は、いきなり起訴というのをずっとまえに一度見かけたような気がします。起訴と同時の勾留請求で、これは起訴後の勾留請求と同じで、事実上無限に延長できるものと聞きます。

　逮捕状が出て、その次の勾留請求となると、裁判所が逮捕の必要性を認めたわけで、相当程度の嫌疑があるということになるかと想像しますが、「「勾留請求するな。」って意見書もだした」という弁護士の態度は、想像を絶するものです。

＜＜＜2019-07-18（木曜日）13：41＿［これまでの記述範囲の終了時刻］＜＜＜

** 深澤諭史弁護士に反応した「検察庁は弁護人がついて黙秘されるまでに身柄拘束を利用して自白を取ろうと本気で」というＫＢブラックのツイート
   :LOGBOOK:
   CLOCK: [2019-07-18 木 13:45]--[2019-07-18 木 16:10] =>  2:25
   :END:

＞＞＞2019-07-18（木曜日）13：45＿［これからの記述範囲の開始時刻］＞＞＞

　午前中、秋重実弁護士（京都弁護士会）と漫画について書いていたところですが、テレビのバイキングからグッディへの引き継ぎという段階で、安藤優子アナウンサーが言った通り、大きなニュースが飛び込んできました。京都のアニメスタジオで放火というニュースです。

　ＫＢブラックというアカウントのタイムラインを開いていたところですが、トレンドを確認すると１０のうち７つが京都のアニメスタジオの事件に関するキーワードでした。今、１人死亡、２０人が安否不明とのことです。これは秋葉原無差別殺傷事件より被害が大きい大事件となりそうです。

▶ ツイート％battamon_black（ＫＢブラック）％2019/07/18 11:48％ https://twitter.com/battamon_black/status/1151685045779697665
&twitter(1151685045779697665){theme:light}
> 検察庁は弁護人がついて黙秘されるまでに身柄拘束を利用して自白を取ろうと本気で考えてるっぽいですね。。 https://t.co/1yAGJtmcbv  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-07-18 15:36／2019-07-18 13:59 URL： https://twitter.com/kk_hirono/status/1151742573012123654 https://twitter.com/s_hirono/status/1151718036153479173
&twitter(1151742573012123654){theme:light}
> 2019-07-18-131324_ＫＢブラックさんのツイート：　”検察庁は弁護人がついて黙秘されるまでに身柄拘束を利用して自白を取ろうと本気で考えてるっぽいですね。。…　”.jpg https://t.co/2dBsAyZogJ
◁◁◁
<hr />

　はっきりとは憶えていませんが、日弁連が大々的に黙秘を推奨しているのを見て、４，５年は経つように思います。そういう意識や価値観が現場の弁護士にも浸透しているようです。この弁護士による黙秘の推奨というのは、他にも様々なかたちで社会に影響を与えていそうです。

　黙秘については、ネット上のごく小さなニュースとしてたまたましりましたが、大分市でとても気になる事件がありました。黙秘の効果や利益を、具体的に初めて知ったケースだったと言えます。そこまで黙秘が強調されていない印象もありましたが他に名古屋の喫茶店店員の事件もあります。

　名古屋の喫茶店店員の事件は、ネット上に１つだけでしたが、金岡弁護士が担当したという話がありました。もう一つの名古屋の弁護士の名前は思い出せないですが、どちらも大崎事件のことでコメントを出していたかと思います。そちらも記録の必要を感じていました。

　本日１１時４８分という投稿時刻になっているＫＢブラックというアカウントのツイートですが、「検察庁は弁護人がついて黙秘されるまでに身柄拘束を利用して自白を取ろう」という論理性が、真新しく特異な発想として映ります。

　弁護人が救世主のようにも映りますが、防犯カメラなどが普及する一昔前ならまだしも、黙秘が奏功する事件の割合というのは、ずいぶん減っていると思われ、黙秘は弁明の機会の放棄ともなりうるので、捜査や取り調べをいたずらに混乱させる弊害もあるように思われます。

　黙秘事件という印象はないですが、弁護士によって初動捜査が大きく妨害された例として、私の頭に真っ先に浮かぶのが、いわゆる東電OL殺人事件でした。ここに出てくる弁護士の一人が、神山啓史弁護士になります。２，３日前も教官のことで触れたかと思います。

　現在のことは確認していないので変わっている可能性はあるかと思いますが、その神山啓史弁護士が所属したというのが、深澤諭史弁護士のタイムラインで見かけることの少なくない櫻井光政弁護士が所長をする法律事務所です。

＜＜＜2019-07-18（木曜日）16：10＿［これまでの記述範囲の終了時刻］＜＜＜


