#+TITLE: "山形県沖地震をきっかけで調べた、２０１６年４月の熊本地震における深澤諭史弁護士のマスコミ報道批判ツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-06-19 10:24:50 +0900
FILE_NAME: 2019-06-19-102450_山形県沖地震をきっかけで調べた、２０１６年４月の熊本地震における深澤諭史弁護士のマスコミ報道批判ツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士（第二東京弁護士会）  深澤諭史弁護士 マスコミ 報道
記事タイトル名の文字数：52　保存ファイル名の文字数：74

* 山形県沖地震をきっかけで調べた、２０１６年４月の熊本地震における深澤諭史弁護士のマスコミ報道批判ツイート
  :LOGBOOK:
  CLOCK: [2019-06-20 木 16:29]--[2019-06-20 木 17:18] =>  0:49
  CLOCK: [2019-06-19 水 10:26]--[2019-06-19 水 16:38] =>  6:12
  :END:

＞＞＞2019-06-19（水曜日）10：26＿［これからの記述範囲の開始時刻］＞＞＞

　まずは昨夜のスクリーンショットの記録をリツイートとしてご紹介したいと思います。ずっと考え続けてきた深澤諭史弁護士の問題の１つでしたが、昨夜２２時２２分発生の山形県沖地震の発生がきっかけとなりました。幸い震度が大きかった割に被害は少なかったようです。

非常上告-最高検察庁御中_ツイッター(@s_hirono) - Twilog https://t.co/RRYsghNgir

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:35／2019-06-19 01:19 URL： https://twitter.com/kk_hirono/status/1141248227636736000 https://twitter.com/s_hirono/status/1141017680289267712
&twitter(1141248227636736000){theme:light}
> 2019-06-19-010336_深澤諭史さんのツイート：　”人間扱いしていないから，「注意されているのに」割り込みをして給油を続けるし，邪魔になってどかせと言われても，あろう事かそのまま.jpg https://t.co/AcpxOQV5va
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:36／2019-06-19 01:20 URL： https://twitter.com/kk_hirono/status/1141248268573089792 https://twitter.com/s_hirono/status/1141017752758415360
&twitter(1141248268573089792){theme:light}
> 2019-06-19-010445_深澤諭史さんのツイート：　”大メディアの方々に，是非，お願いしたいのは，事件関係者も被害者も被災者も，みんなみんな「あなたと同じ人間」だと忘れないこと。　.jpg https://t.co/RQ4GXybyvG
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:36／2019-06-19 01:20 URL： https://twitter.com/kk_hirono/status/1141248312755937280 https://twitter.com/s_hirono/status/1141017824996937729
&twitter(1141248312755937280){theme:light}
> 2019-06-19-010927_深澤諭史さんのツイート：　”【放送事故】TBS生放送中に被災者がブチ切れて正論を吐きまくる「見世物じゃねーて、どっかいけ！車邪魔！どかせよ！」　　Ａ．貴方.jpg https://t.co/7ap0ZJAo1j
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:36／2019-06-19 01:20 URL： https://twitter.com/kk_hirono/status/1141248346880794624 https://twitter.com/s_hirono/status/1141017897491259392
&twitter(1141248346880794624){theme:light}
> 2019-06-19-011053_深澤諭史（@fukazawas）：　非弁のトレンドは、昔探偵、今ＮＰＯって感じだな。というか、非弁でも非弁っぽくないように見せかけるなら、条文くらいよん.jpg https://t.co/eiE9uBCVk2
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:36／2019-06-19 01:20 URL： https://twitter.com/kk_hirono/status/1141248379613143041 https://twitter.com/s_hirono/status/1141017969989828608
&twitter(1141248379613143041){theme:light}
> 2019-06-19-011321_深澤諭史さんのツイート：　”大災害や大事故が起きるたんびに横行する不謹慎狩り。　「ヒャッハー！不謹慎な奴を見つけたぞーー！！」　「おい！こいつ！こんなこと.jpg https://t.co/M9hJUBwHUO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:36／2019-06-19 01:31 URL： https://twitter.com/kk_hirono/status/1141248462177988608 https://twitter.com/s_hirono/status/1141020534332727296
&twitter(1141248462177988608){theme:light}
> 2019-06-19-012411_ブロックされているため、@zakiyama487さんのフォローや@zakiyama487さんのツイートの表示はできません。詳細はこちら.jpg https://t.co/rouzUiZX1T
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:36／2019-06-19 01:31 URL： https://twitter.com/kk_hirono/status/1141248489998827520 https://twitter.com/s_hirono/status/1141020607653355520
&twitter(1141248489998827520){theme:light}
> 2019-06-19-012710_from：fukazawas　since：2016-04-14　until：2016-04-30　-　Twitter検索.jpg https://t.co/M4TF1GhcCx
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:37／2019-06-19 01:31 URL： https://twitter.com/kk_hirono/status/1141248538145251329 https://twitter.com/s_hirono/status/1141020684023320576
&twitter(1141248538145251329){theme:light}
> 2019-06-19-012930_深澤諭史さんのツイート：　”（＾ω＾）地方はエルドラドだお！仕事一杯需要一杯，夢一杯！！　＊某地方にて　（；＃・∀・）（イノシシを追いかけながら）まてーー.jpg https://t.co/tnXpsnVgk9
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:37／2019-06-19 01:32 URL： https://twitter.com/kk_hirono/status/1141248595347136512 https://twitter.com/s_hirono/status/1141020756974817280
&twitter(1141248595347136512){theme:light}
> 2019-06-19-013006_深澤諭史さんのツイート：　”@zakiyama487　ちょｗｗｗｗ　新美先生をブルー卿と並べるのはダメですお（＾ω＾；）”.jpg https://t.co/0J8Qq79aOR
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:37／2019-06-19 01:32 URL： https://twitter.com/kk_hirono/status/1141248629098680322 https://twitter.com/s_hirono/status/1141020830035394560
&twitter(1141248629098680322){theme:light}
> 2019-06-19-013020_深澤諭史さんのツイート：　”公職選挙法の運動員買収って，結構鬼門なんですよね。　公選法についてセミナーやると，この点に関する質問が多いし，結構あぶない誤解.jpg https://t.co/xwUh15Wl4H
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-19 16:37／2019-06-19 01:32 URL： https://twitter.com/kk_hirono/status/1141248666918801408 https://twitter.com/s_hirono/status/1141020902202601472
&twitter(1141248666918801408){theme:light}
> 2019-06-19-013034_深澤諭史さんのツイート：　”あれだけ司法改革で，弁護士に気軽に依頼できる，頼りがいがあるって，喧伝したのに，いざ小さい事件まで「法の光」が行き渡ると，非難.jpg https://t.co/wK8jZ5e0ke
◁◁◁
<hr />

＜＜＜2019-06-19（水曜日）16：38＿［これまでの記述範囲の終了時刻］＜＜＜

＞＞＞2019-06-20（木曜日）16：29＿［これからの記述範囲の開始時刻］＞＞＞

　時間的にだいぶん開きができましたが、次が熊本地震と深澤諭史弁護士に関連して2019年6月19日にまとめた情報のツイートになります。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「熊本」の検索結果 - Twilog https://t.co/mhOViITvif

<hr />
[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年06月19日 - Twilog https://t.co/4v4m76m6yO

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:36／2019-06-19 00:54 URL： https://twitter.com/kk_hirono/status/1141610689120763904 https://twitter.com/hirono_hideki/status/1141011251318816768
&twitter(1141610689120763904){theme:light}
> from:fukazawas since:2016-04-14 until:2016-04-30 - Twitter検索 https://t.co/25x8QHjAvU
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:39／2019-06-19 01:28 URL： https://twitter.com/kk_hirono/status/1141611432850513922 https://twitter.com/hirono_hideki/status/1141019903740088322
&twitter(1141611432850513922){theme:light}
> 2019年06月19日01時01分の登録： ％@fukazawas　深澤諭史％＞RT （＃＾ω＾）成仏したくないと，既存法曹どころかロー生までいっているお！ （＃＾ω＾）成仏を嫌がるのは歪んだ特権意識だお！ （＃＾ https://t.co/UQ95lcU6sD
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:39／2019-06-19 01:28 URL： https://twitter.com/kk_hirono/status/1141611516887613440 https://twitter.com/hirono_hideki/status/1141019956470882304
&twitter(1141611516887613440){theme:light}
> 2019年06月19日01時02分の登録： ％@fukazawas　深澤諭史％ 返信先: @fukazawasさん\n\n人間扱いしていないから，「注意されているのに」割り込みをして給油を続けるし，邪魔になってどか https://t.co/WkWcskYzxy
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:39／2019-06-19 01:28 URL： https://twitter.com/kk_hirono/status/1141611560944537600 https://twitter.com/hirono_hideki/status/1141019982798524416
&twitter(1141611560944537600){theme:light}
> 2019年06月19日01時03分の登録： ％@fukazawas　深澤諭史％人間扱いしていないから，「注意されているのに」割り込みをして給油を続けるし，邪魔になってどかせと言われても，あろう事かそのまま生中継を始 https://t.co/caadgzUHi4
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:39／2019-06-19 01:29 URL： https://twitter.com/kk_hirono/status/1141611593723072513 https://twitter.com/hirono_hideki/status/1141020009117786113
&twitter(1141611593723072513){theme:light}
> 2019年06月19日01時04分の登録： ％@fukazawas　深澤諭史％大メディアの方々に，是非，お願いしたいのは，事件関係者も被害者も被災者も，みんなみんな「あなたと同じ人間」だと忘れないこと。\n昨今の振 https://t.co/hTLiJphMrM
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:39／2019-06-19 01:29 URL： https://twitter.com/kk_hirono/status/1141611628959420416 https://twitter.com/hirono_hideki/status/1141020035432906752
&twitter(1141611628959420416){theme:light}
> 2019年06月19日01時05分の登録： ％@fukazawas　深澤諭史％こんな振る舞い，責任を問われない前提で「やれ」といわれても皆さんやらないというか，やりたくないと思います。するのも嫌ですよね？\nでも， https://t.co/Xxq2vOGJXa
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:40／2019-06-19 01:29 URL： https://twitter.com/kk_hirono/status/1141611686031314944 https://twitter.com/hirono_hideki/status/1141020061735374848
&twitter(1141611686031314944){theme:light}
> 2019年06月19日01時09分の登録： ％@fukazawas　深澤諭史％【放送事故】TBS生放送中に被災者がブチ切れて正論を吐きまくる「見世物じゃねーて、どっかいけ！車邪魔！どかせよ！」 https://t.co/HnX5kkaBWp
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:40／2019-06-19 01:29 URL： https://twitter.com/kk_hirono/status/1141611759565860864 https://twitter.com/hirono_hideki/status/1141020140680515584
&twitter(1141611759565860864){theme:light}
> 2019年06月19日01時12分の登録： ％@fukazawas　深澤諭史％大災害や大事故が起きるたんびに横行する不謹慎狩り。 「ヒャッハー！不謹慎な奴を見つけたぞーー！！」 「おい！こいつ！こんなことつぶやいてるぞー！！」 「… https://t.co/3rTGg0mQL9
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:40／2019-06-19 01:29 URL： https://twitter.com/kk_hirono/status/1141611800820998145 https://twitter.com/hirono_hideki/status/1141020167016603648
&twitter(1141611800820998145){theme:light}
> 2019年06月19日01時16分の登録： ％@fukazawas　深澤諭史％以前法クラのツイートで，「ＤＶ冤罪を法廷で訴える者がいたが，その言動が，そのまんま『ＤＶ加害者の振る舞い』だった」というコントみたいな話がありましたね。 https://t.co/WzGCgp2Pjs
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:40／2019-06-19 01:29 URL： https://twitter.com/kk_hirono/status/1141611834891313152 https://twitter.com/hirono_hideki/status/1141020193281363973
&twitter(1141611834891313152){theme:light}
> 2019年06月19日01時16分の登録： ％@fukazawas　深澤諭史％あるあるある。 そういう思いこみをする人だからこそ，愛想尽かされて離婚を求められたり，ＤＶに走ったりするわけで，言動が自分の有責性の証明になっているとい… https://t.co/QlhVZK13qL
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:41／2019-06-19 01:30 URL： https://twitter.com/kk_hirono/status/1141612086063067136 https://twitter.com/hirono_hideki/status/1141020351293345793
&twitter(1141612086063067136){theme:light}
> 2019年06月19日01時19分の登録： ％@fukazawas　深澤諭史％ストーカー規制法の行為一覧をみても明らかだけど，つきまとい，いやがらせ，情報収集してそれをアピール，そんなことをやっても，誰一人好意を抱 https://t.co/UCsYhQaDj3
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:41／2019-06-19 01:30 URL： https://twitter.com/kk_hirono/status/1141612116517904384 https://twitter.com/hirono_hideki/status/1141020377721663488
&twitter(1141612116517904384){theme:light}
> 2019年06月19日01時22分の登録： ％@fukazawas　深澤諭史％（＾ω＾）地方はエルドラドだお！仕事一杯需要一杯，夢一杯！！ ＊某地方にて （；＃・∀・）（イノシシを追いかけながら）まてーー！！今晩の当職の晩飯ーーー… https://t.co/7XLKOq15ta
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:42／2019-06-19 01:30 URL： https://twitter.com/kk_hirono/status/1141612254833467392 https://twitter.com/hirono_hideki/status/1141020482952548353
&twitter(1141612254833467392){theme:light}
> 2019年06月19日01時26分の登録： ％@fukazawas　深澤諭史％公職選挙法の運動員買収って，結構鬼門なんですよね。 公選法についてセミナーやると，この点に関する質問が多いし，結構あぶない誤解があったりすることを実感す… https://t.co/ZDpTkKgTNo
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:42／2019-06-19 01:31 URL： https://twitter.com/kk_hirono/status/1141612349603758080 https://twitter.com/hirono_hideki/status/1141020509473103872
&twitter(1141612349603758080){theme:light}
> 2019年06月19日01時26分の登録： ％@fukazawas　深澤諭史％あれだけ司法改革で，弁護士に気軽に依頼できる，頼りがいがあるって，喧伝したのに，いざ小さい事件まで「法の光」が行き渡ると，非難されるとか，なにをいいたい… https://t.co/XZq7FhQlwV
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-20 16:43／2019-06-19 01:31 URL： https://twitter.com/kk_hirono/status/1141612562099785728 https://twitter.com/hirono_hideki/status/1141020535859499008
&twitter(1141612562099785728){theme:light}
> 2019年06月19日01時26分の登録： ％@fukazawas　深澤諭史％\n深澤諭史\n @fukazawas\n2016年4月14日\n\n交通事故審理、迅速化へモデルを作成…最高裁（読売新聞） - Ya https://t.co/i5tcgcdBl6
◁◁◁
<hr />

　見出しというか記事のタイトルなどをみただけではわかりづらくなっていますが、熊本地震が発生した2016年4月14日から同年同月30日までの期間の深澤諭史弁護士のツイートをTwitterの検索で調べ、これはと思うものをピックアップし記録化しました。

　当時の深澤諭史弁護士のタイムラインでは、深澤諭史弁護士本人のツイートよりリツイートの内容の方が際立っていたという印象が強かったのですが、改めて調べてみると、深澤諭史弁護士自身が自身のツイートでずいぶんと積極的なマスコミ、報道批判を行っていたようです。

　次に、私のデータベースに記録されている範囲で、熊本地震からおよそ半月という同じ期間の深澤諭史弁護士のツイートをまとめ記事として作成したいと思います。こちらだと深澤諭史弁護士のリツイートも含まれているのかもしれません。その前に過去に作成したものをあたってみます。

```
[888]  % dp -l|grep fukazawas |grep '2016-04'
2017年11月15日07時58分の登録： TWEET：”2016-04-14 00:35〜2016-04-20 23:13”／深澤諭史（@fukazawas）の検索（2017年11月15日07時58分の記録229件） http://hirono2014sk.blogspot.com/2017/11/tweet2016-04-14-00352016-04-20.html
2018年01月20日12時10分の登録： REGEXP：”今市”／深澤諭史（@fukazawas）の検索（2016-04-09〜2016-04-09／2018年01月20日12時10分の記録1件） http://hirono2014sk.blogspot.com/2018/01/regexpfukazawas2016-04-092016-04.html
2018年03月02日08時46分の登録： REGEXP：”視聴者．＊写真”／深澤諭史（@fukazawas）の検索（2016-04-19〜2016-04-19／2018年03月02日08時46分の記録1件） http://hirono2014sk.blogspot.com/2018/03/regexpfukazawas2016-04-192016-04.html
2018年03月02日08時47分の登録： REGEXP：”報道の公正．＊写真”／深澤諭史（@fukazawas）の検索（2015-06-30〜2016-04-19／2018年03月02日08時47分の記録2件） http://hirono2014sk.blogspot.com/2018/03/regexpfukazawas2015-06-302016-04.html
2019年06月18日08時36分の登録： REGEXP：”モラハラ”／深澤諭史（@fukazawas）の検索（2016-04-17〜2019-06-17／2019年06月18日08時36分の記録22件） http://hirono2014sk.blogspot.com/2019/06/regexpfukazawas2016-04-172019-06.html
```

　調べて確認したところ、2017年11月15日の登録でまとめ記事がありましたが、検索の範囲を2016年4月20日終日としているようです。データベース操作の注意点として年月日を指定しただけだと、当日の00時00分だけが対象となるので、23：59などと時刻を付加して指定します。

　4月19日に調べたところ、深澤諭史弁護士のツイートが熊本地震について活発だったのは4月20日前後だったと思います。2週間ぐらいは大きな報道が続き、Twitterの議論も活発だったと思われるので、今回の記録は期間を長めに指定し4月いっぱいとしています。

```
[889]  % time ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '.*' '2016-04-14/2016-04-30 23:59'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2016-04-14' AND '2016-04-30 23:59' AND (user LIKE "fukazawas") AND  tweet REGEXP ".*"  ORDER BY tw_date ASC
TWEET：”2016-04-14 00:35〜2016-04-30 23:25”／深澤諭史（@fukazawas）の検索（2019年06月20日16時59分の記録458件）

real    0m9.529s
user    0m0.931s
sys     0m0.202s
```

　10秒ほどで記録の作成とブログへの投稿という処理が完了しましたが、ツイートの数が458件と想定より多い数でした。最も活性化していた時期について、別途まとめ記事を作成しておきたいと思います。

[link:] » 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: ％@fukazawas　深澤諭史％ 返信先: @fukazawasさん\n\n人間扱いしていないから，「注意されているのに」割り込みをして給油を続けるし，邪魔になって… https://t.co/yUfB9euEzA

<hr />

　上記の記録にある深澤諭史弁護士のツイートを基準にまとめ記事を作成します。次のツイートになりますが、投稿日時が2016年4月22日11時52分となっています。

```
[890]  % time ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '.*' '2016-04-22/2016-04-22 23:59'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2016-04-22' AND '2016-04-22 23:59' AND (user LIKE "fukazawas") AND  tweet REGEXP ".*"  ORDER BY tw_date ASC
TWEET：”2016-04-22 00:12〜2016-04-22 23:52”／深澤諭史（@fukazawas）の検索（2019年06月20日17時06分の記録38件）

real    0m6.641s
user    0m0.719s
sys     0m0.216s
```

2019年06月20日16時59分の登録： TWEET：”2016-04-14 00:35〜2016-04-30 23:25”／深澤諭史（@fukazawas）の検索（2019年06月20日16時59分の記録458件） http://hirono2014sk.blogspot.com/2019/06/tweet2016-04-14-00352016-04-30.html

2019年06月20日17時06分の登録： TWEET：”2016-04-22 00:12〜2016-04-22 23:52”／深澤諭史（@fukazawas）の検索（2019年06月20日17時06分の記録38件） http://hirono2014sk.blogspot.com/2019/06/tweet2016-04-22-00122016-04-22.html

　次の深澤諭史弁護士のツイートになりますが、4月19日に資料作成の作業時には気が付かなかった気がします。まとめ記事を作成することで見通しが良くなり、新たな発見となることは多いです。

```
▶（17／38） TW fukazawas（深澤諭史） 日時：2016-04-22 02：30：00 +0900 URL： https：//twitter.com/fukazawas/status/723338072197238784
{% tweet 723338072197238784 %}
> 【放送事故】TBS生放送中に被災者がブチ切れて正論を吐きまくる「見世物じゃねーて、どっかいけ！車邪魔！どかせよ！」 https：//t.co/vAOo6J2mKV \n \n Ｑ．現地ではどんなボランティアが必要ですか？ \n Ａ．貴方たちの様な迷惑な人を追い出してくれるボランティアが必要です

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： TWEET：”2016-04-22 00：12〜2016-04-22 23：52”／深澤諭史（@fukazawas）の検索（2019年06月20日17時06分の記録38件） http://hirono2014sk.blogspot.com/2019/06/tweet2016-04-22-00122016-04-22.html
```

　リンクの記事を開いてざっと目を通しましたが、次の深澤諭史弁護士のツイートの記載は見当たりませんでした。→Ｑ．現地ではどんなボランティアが必要ですか？ \n Ａ．貴方たちの様な迷惑な人を追い出してくれるボランティアが必要です

＜＜＜2019-06-20（木曜日）17：18＿［これまでの記述範囲の終了時刻］＜＜＜

