#+TITLE: "外科医のツイートに対して「法律問題、弁護士への相談について200％妥当する話ですね。（・∀・）」という深澤諭史弁護士のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-06-25 21:47:10 +0900
FILE_NAME: 2019-06-25-214710_外科医のツイートに対して「法律問題、弁護士への相談について200％妥当する話ですね。（・∀・）」という深澤諭史弁護士のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士（第二東京弁護士会）  深澤諭史弁護士 モトケンこと矢部善朗弁護士（京都弁護士会） 医療問題
記事タイトル名の文字数：63　保存ファイル名の文字数：85

* 外科医のツイートに対して「法律問題、弁護士への相談について200％妥当する話ですね。（・∀・）」という深澤諭史弁護士のツイート

** 「法律問題、弁護士への相談について200％妥当する話ですね。（・∀・）」という深澤諭史弁護士のツイート
   :LOGBOOK:
   CLOCK: [2019-06-25 火 21:50]--[2019-06-26 水 00:02] =>  2:12
   :END:

＞＞＞2019-06-25（火曜日）21：50＿［これからの記述範囲の開始時刻］＞＞＞

▶ ツイート％fukazawas（深澤諭史）％2019/06/24 20:36％ https://twitter.com/fukazawas/status/1143120767418134528
&twitter(1143120767418134528){theme:light}
> 法律問題、弁護士への相談について200％妥当する話ですね。
> （・∀・） https://t.co/EQEfjNJiVp  
▶

　昨夜遅い時間に見たように思っていたのですが、あらためて深澤諭史弁護士のツイートの投稿時刻を確認すると、昨夜でも20時36分という比較的早い時間でした。これは久しぶりに物凄さとともに歴史的な記録の必要性を感じたのですぐにスクリーンキャストをとったように思います。

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/2019年06月24日 - Twilog https://t.co/vvZ1RGQd0f

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-25 21:56／2019-06-24 22:47 URL： https://twitter.com/kk_hirono/status/1143503220490117120 https://twitter.com/s_hirono/status/1143153601419702272
&twitter(1143503220490117120){theme:light}
> 2019-06-24-214918_深澤諭史さんがリツイート＞　外科医けいゆう（@keiyou30）：　テレビに医師がどう関わるか、ということに関して考えをまとめました。テレビには、依然と.jpg https://t.co/kXktB4mdYy
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-25 21:56／2019-06-24 22:47 URL： https://twitter.com/kk_hirono/status/1143503246675152896 https://twitter.com/s_hirono/status/1143153674870353920
&twitter(1143503246675152896){theme:light}
> 2019-06-24-214958_深澤諭史（@fukazawas）：　法律問題、弁護士への相談について200％妥当する話ですね。（・∀・）.jpg https://t.co/m7LCFaqkRZ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-25 21:56／2019-06-24 22:47 URL： https://twitter.com/kk_hirono/status/1143503284230971393 https://twitter.com/s_hirono/status/1143153748933394432
&twitter(1143503284230971393){theme:light}
> 2019-06-24-215008_深澤諭史さんのツイート：　”法律問題、弁護士への相談について200％妥当する話ですね。　（・∀・）…　”.jpg https://t.co/09ZobnrQFz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-25 21:56／2019-06-24 22:48 URL： https://twitter.com/kk_hirono/status/1143503347757883394 https://twitter.com/s_hirono/status/1143153821742333952
&twitter(1143503347757883394){theme:light}
> 2019-06-24-224240_深澤諭史さんのツイート：　”あなたが突然倒れて意識を失って緊急搬送された病院・・　そこの医師の報酬は　１．あなたが重病になればなるほど増える　２．後遺症が.jpg https://t.co/v4DJtC05Zp
◁◁◁
<hr />

　昨夜、21時49分から22時42分の間に4件のスクリーンショットを記録していたことをTwilogで確認しましたが、最初の21時49分18秒のものと、50分ほど時間がありますが最後の22時42分のものは記憶から消えていたというか、すっかりと忘れていました。

▷ リツイート→fukazawas（深澤諭史）＞keiyou30（外科医けいゆう）｜2019/06/24 20:36／2019/06/24 12:13｜https://twitter.com/fukazawas/status/1143120775743823873 ／ https://twitter.com/keiyou30/status/1142994111051382784
&twitter(1143120775743823873){theme:light}
> RT @keiyou30: 「〇〇な症状で病院に行ったら医師から〇〇な説明を受けたのでご参考に」
> 
> 親切な情報発信ですが、取り扱い注意です。
> 発信者には「専門性の高い情報を正確に伝達する力」が、受信者には「他人の症例を自分に適用できるかどうかを判断する力」が必要ですが、いずれも…  

　中断していてまだ取り上げていませんが、北口雅章弁護士の名古屋刑務所の受刑者死亡事件に対する説明と重なって考えるところがありました。自身に満ち溢れて有罪判決の不当性を主張していましたが、最高裁で有罪判決が確定し、また、受刑者の死亡も疑いのない事実でした。

　北口雅章弁護士は受刑者の自傷行為の可能性を指摘し、自らの糞尿を壁に塗りたくるような精神病の異常行動を説明していましたが、いくらか共通した体験のある私は不可解に感じました。保護房で監視するのも刑務官の負担となりますし、医療刑務所への移送がないものかと考えました。

　古い記憶なので、このあと確認しますが、愛知県では岡崎刑務所が医療刑務所だったように思いますし、医療刑務所で有名なのは八王子刑務所でした。医療刑務所は全国的に数が限られていてごく少数という情報も見た覚えがあります。

```
一般の刑務所では収容できない、専門的な医療行為を必要とする受刑者を収容し、治療を行う刑務所。薬物やアルコール依存症、摂食障害の受刑者も収容対象となる。法務省設置法に基づいて設置されるもので、法務省矯正局が所管し、医務部のほか、総務部、処遇部が置かれる。全国に八王子医療刑務所（東京都八王子市）、岡崎医療刑務所（愛知県岡崎市）、大阪医療刑務所（大阪府堺(さかい)市）、北九州医療刑務所（福岡県北九州市）の4施設がある。おもに精神疾患のある受刑者を収容する施設であるが、八王子医療刑務所と大阪医療刑務所は身体に疾病がある受刑者も収容対象とする。また、八王子医療刑務所では受刑者の終末期ケアも行う。

［source：］医療刑務所(いりょうけいむしょ)とは - コトバンク https://kotobank.jp/word/%E5%8C%BB%E7%99%82%E5%88%91%E5%8B%99%E6%89%80-32470
```

　大阪医療刑務所というのは、少しだけ見かけたことがあるように思いましたが、北九州医療刑務所というのは全く初めて知ったように思います。岡崎医療刑務所というのも名前を知っていた程度で、規模や収容人数は見当もつきません。

　視聴した動画で、北口雅章弁護士は、保護房の放水で死亡した受刑者は、自らの糞尿を食べていたとも語っていたように思います。拘置所で未決の被告人が心神喪失での無罪判決を狙って、そのような行動をするという話は見かけたことがありましたが、受刑者では聞いたことがありません。

　なお、北口雅章弁護士は、特別公務員暴行陵虐致死に問われた刑務官の弁護人です。被害者は死亡しているので話は聞けなかったと思いますが、当事者に状況を詳しく聞き取れる立場で、それを前提に代弁者のような立場で無罪主張をしていたはずかと思います。

　中には豚を使った放水による死亡の再現実験もあったようですが、それも初めて知った話であったと思いました。その実験は検察側の申請だったようです。豚を使った再現実験で強く印象にあったのは、北海道の恵庭事件で冤罪を主張する刑事裁判でしたが、豚を丸焼きにしたそうです。

　同じく弁護士による燃焼実験で有名だったのは、大阪の東住吉事件で、再審無罪となりましたが、そのしばらくあとに埼玉県の事件でも燃焼実験をしたものの関係性が認められないとして有罪判決になったものもあったかと思います。モトケンこと矢部善朗弁護士（京都弁護士会）のツイートで見た記憶です。

[link:] » モトケン(@motoken_tw)/「埼玉」の検索結果 - Twilog https://t.co/4SGUWPsuD3

<hr />

　「埼玉」の前に、「放火」、「実験」というキーワードでモトケンこと矢部善朗弁護士（京都弁護士会）のTwilogを検索したのですが、それと思うツイートは見つかりませんでした。弁護士らの反応が余に乏しかったので、東住吉事件との対比でも不思議に思った刑事裁判でした。

　いろいろと方法を駆使しながら探していたのですが、モトケンこと矢部善朗弁護士（京都弁護士会）のツイートというのは、私の勘違いというかあるいは記憶の変容で、意外なことに深澤諭史弁護士のツイートとして、それらしいものを発見しました。2016年7月14日のツイートです。

　深澤諭史弁護士がこのようなツイートをするのは、かなり珍しい意外な発見だと思いました。モトケンこと矢部善朗弁護士（京都弁護士会）のツイートの傾向にも似ているのですが、弁護士にとって不利であったり、不都合な事実は、極力触れないと感じてきたことです。

　そのさいたま地裁の一審無罪判決では、検察側の燃焼実験が無罪の判断につながったというニュースをさきほど調べている過程で見かけていたので、あるいは不当性の意味で同業弁護士らの喚起を促す意味で、行ったツイートなのかとも考えますが、本人にしかわからないことかもしれません。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「放火殺人」の検索結果 - Twilog https://t.co/CUDTyTzd69

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-25 23:08／2016-07-14 17:02 URL： https://twitter.com/kk_hirono/status/1143521332614688768 https://twitter.com/hirono_hideki/status/753499932779089920
&twitter(1143521332614688768){theme:light}
> 奉納＼弁護士妖怪大泥棒神社・金沢地方検察庁御中: 深澤諭史さんのツイート: ”妻子放火殺人：東京高裁「無罪」破棄　裁判員判決差し戻し - 毎日新聞 https://t.co/JfDaHe8mQC
◁◁◁
<hr />
[link:] » 奉納＼弁護士妖怪大泥棒神社・金沢地方検察庁御中: 深澤諭史さんのツイート: ”妻子放火殺人：東京高裁「無罪」破棄　裁判員判決差し戻し - 毎日新聞 https://t.co/r2OZ0W7BSU

<hr />

　次が、2016年7月14日14時13分となっている深澤諭史弁護士のツイートですが、ニュース記事の見出しとURLのみ言及なしのツイートのようです。前後のツイートが気になるところですが、2016年7月であれば、全件記録をデータベースで開始していたのかもしれません。

　さくっとまとめ記事を作成してみます。

[link:] 2019年06月25日23時14分の登録： TWEET：”2016-07-14 09:24〜2016-07-14 22:11”／深澤諭史（@fukazawas）の検索（2019年06月25日23時13分の記録58件） http://hirono2014sk.blogspot.com/2019/06/tweet2016-07-14-09242016-07-14.html


▷ リツイート→fukazawas（深澤諭史）＞nakanori930（弁護士 中村憲昭）｜2016/07/14 11:10／2016/07/14 11:00｜https://twitter.com/fukazawas/status/753411264307531776 ／ https://twitter.com/nakanori930/status/753408808869781504
&twitter(753411264307531776){theme:light}
> RT @nakanori930: 詳しく話すと、弁護士を増やせば世の中が良くなるのだ、というのが法の光教団の教義です。「人の役に立つ仕事をしていれば誰かがお布施をくれる。そうでなければ成仏すればいい」という主張もあります。弁護士成仏論と呼ばれる重要な教義です。 https://…  

▶ ツイート％fukazawas（深澤諭史）％2016/07/14 11:11％ https://twitter.com/fukazawas/status/753411508026023936
&twitter(753411508026023936){theme:light}
> 平成の司法改革に流れる「みんな（ただし自分たちは除く）が，自分の思い通りに，自分の計画のために，利害を無視して全力で頑張ってくれる」という謎の確信・・・。
> （・∀・；）  
▶

▷ リツイート→fukazawas（深澤諭史）＞kumaemon9（くまえもん）｜2016/07/14 11:27／2016/02/06 21:42｜https://twitter.com/fukazawas/status/753415687654080512 ／ https://twitter.com/kumaemon9/status/695950746496335872
&twitter(753415687654080512){theme:light}
> RT @kumaemon9: 自分には何人も弁護士の知り合いがいると主張する相手方は、最後まで弁護士を付けない。#弁護士あるある  

▶ ツイート％fukazawas（深澤諭史）％2016/07/14 12:15％ https://twitter.com/fukazawas/status/753427664459804673
&twitter(753427664459804673){theme:light}
> 一刻も早く対処しなきゃいけないのに、なぜか、インターネットで匿名の同じ問題を抱えた人たちと相談という名の傷の舐め合いを続けて、すぐに対処すれば大したこと無かったのに、取り返しのつかない状態まで放置する例が散見される。。。  
▶

　まとめ記事のツイートが新しいものから順に並んでいました。次のツイートは13時48分、妻子放火殺人事件のツイートは13時14分で1つ前のツイートとなるようです。

▶ ツイート％fukazawas（深澤諭史）％2016/07/14 13:48％ https://twitter.com/fukazawas/status/753451074585894912
&twitter(753451074585894912){theme:light}
> （＃＾ω＾）勘違いするなよ！弁護士ども！！！
> （＃＾ω＾）おれ達の利権と面子はなぁ・・・・！お前ら弁護士や修習生，受験生の人生より重いんだ！！
> （＃＾ω＾）その認識を誤魔化す者は，生涯借金にまみれる！！！ https://t.co/m7wwufZES5  
▶

　深澤諭史弁護士の2016年7月14日13時14分のツイートをよく見ると、一審の裁判員裁判の無罪判決が破棄差し戻しとなっていました。深澤諭史弁護士は裁判員裁判について批判的で皮肉や嫌味のようなツイートもたびたび見かけてきたので、その意図が込められているのかもしれません。

```
▶（46／58） RT fukazawas（深澤諭史）｜Noooooooorth（このノース㌠が！） 日時：2016-07-14 15：17：00 +0900／2016-07-14 14：46：00 +0900 URL： https：//twitter.com/fukazawas/status/753473579484717056 https：//twitter.com/Noooooooorth/status/753465715135385601
{% tweet 753473579484717056 %}
> 単独事務所で法律事務所用のソフトウェア開発するとかきついので複数の法律事務所が共同でソフトウェア開発を依頼するとかどうだろう。

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： TWEET：”2016-07-14 09：24〜2016-07-14 22：11”／深澤諭史（@fukazawas）の検索（2019年06月25日23時13分の記録58件） http://hirono2014sk.blogspot.com/2019/06/tweet2016-07-14-09242016-07-14.html
```

　埋め込みツイートの表示がなく、リンク切れとなっていることも確認しましたが、北周士弁護士がアカウントを削除する前のツイートという時期だったようです。深澤諭史弁護士のリツイートの時刻が2016年7月14日15時17分となっています。

[link:]  妻子放火殺人：東京高裁「無罪」破棄 - Twitter検索 <https://twitter.com/search?q=%E5%A6%BB%E5%AD%90%E6%94%BE%E7%81%AB%E6%AE%BA%E4%BA%BA%EF%BC%9A%E6%9D%B1%E4%BA%AC%E9%AB%98%E8%A3%81%E3%80%8C%E7%84%A1%E7%BD%AA%E3%80%8D%E7%A0%B4%E6%A3%84&src=typd>

　ニュース記事の見出しの一部と思われる同じ内容でTwitter検索を行いましたが、ざっと数えてツイートの数は17件ほどです。この検索結果は、検索の精度に期待も出来ないので、検索の実施毎に内容が異なるかもしれません。これも以前作成したスクリプトで記録化しておきます。

[link:] 2019年06月25日23時39分の登録： 妻子放火殺人：東京高裁「無罪」破棄　-　Twitter検索　2019年06月25日23時39分：18件の取得 http://hirono2014sk.blogspot.com/2019/06/twitter20190625233918.html

　18件という検索結果ですが、広告と思われる無関係のツイートが1件紛れていました。ニュースサイトのツイートもけっこうあります。毎日新聞だけでもざっと3件です。弁護士と思われるアカウントは深澤諭史弁護士だけです。弁護士業界を代表した妙なツイートだったのだと改めて考えました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-25 23:47／2019-06-25 23:47 URL： https://twitter.com/kk_hirono/status/1143531267301896193 https://twitter.com/s_hirono/status/1143531059528663045
&twitter(1143531267301896193){theme:light}
> 2019-06-25-234645_深澤諭史さんのツイート：　”妻子放火殺人：東京高裁「無罪」破棄　裁判員判決差し戻し　-　毎日新聞　https：／／t。co／vthpiaAY1d”.jpg https://t.co/HuE2wSMH6n
◁◁◁
<hr />

　スクリーンショットを記録しましたが、妻子放火殺人の深澤諭史弁護士のツイートのリツイートの数は1件のみで、プロフィールの名前に「法律の素人」が含まれ、プロフィールにも「非法曹」とありました。

```
Tuba56@法律の素人
@Tuba56
2歳半児と5歳半児の父。非法曹。クリスチャン(プロテスタント)。第一種情報処理技術者/二級知的財産管理技能士(管理業務)/第一種衛生管理者

togetter.com/id/Tuba56
2010年5月に登録

［source：］Tuba56@法律の素人(@Tuba56)さん | Twitter https://twitter.com/Tuba56
```

　赤いバラのような花びらがプロフィールのアイコンの写真となっていますが、これはずっと前に何度か見かけたようにおもいました。

　告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でログインした状態で6月14日辺りまでタイムラインを遡りましたが、結構な数、弁護士アカウントをリツイートしたものがありました。私がブロックされているものは表示されていないはずです。

　時刻は23時59分で、まもなく日付が変わります。15時過ぎにテレビを消して、そのあとは一度もテレビをつけずにいました。

　この項目で取り上げた深澤諭史弁護士のツイートについては、モトケンこと矢部善朗弁護士（京都弁護士会）のリツイートとして再度取り上げておく予定です。0時1分と日付が変わってしまいましたが、今朝起きて最初に目に飛び込んだのが、そのリツイートでした。

＜＜＜2019-06-26（水曜日）00：02＿［これまでの記述範囲の終了時刻］＜＜＜


