#+TITLE: "「弁護士の介入を異常に嫌い、弁護士のせいで家庭が壊れたと信じ込むロジックがよくわかる」という深澤諭史弁護士のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-20 13:55:56 +0900
FILE_NAME: 2019-08-20-135556_「弁護士の介入を異常に嫌い、弁護士のせいで家庭が壊れたと信じ込むロジックがよくわかる」という深澤諭史弁護士のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 深澤諭史弁護士（第二東京弁護士会）  大貫憲介弁護士 モラ夫
記事タイトル名の文字数：58　保存ファイル名の文字数：80

* 「弁護士の介入を異常に嫌い、弁護士のせいで家庭が壊れたと信じ込むロジックがよくわかる」という深澤諭史弁護士のツイート
  :LOGBOOK:
  CLOCK: [2019-08-20 火 13:57]--[2019-08-20 火 18:00] =>  4:03
  :END:

＞＞＞2019-08-20（火曜日）13：57＿［これからの記述範囲の開始時刻］＞＞＞

SatsukiLaw ===> You have been blocked from retweeting this user's tweets at their request.
ブロックされているのでリツイートできませんでした。→　https://twitter.com/SatsukiLaw
▶ ブロックされたツイート％SatsukiLaw（大貫憲介）％2019/08/20 12:58％ https://twitter.com/SatsukiLaw/status/1163661506224857088
&twitter(1163661506224857088){theme:light}
> @fukazawas 同意します。  
▶

　まず気になったのは深澤諭史弁護士のタイムラインで深澤諭史弁護士にリツイートされていた上記のツイートになりますが、意外なことにブロックされていました。ブロックはしないタイプの弁護士かと思っていたし、直接メッセージを送ることもなかったと思います。

　上記のブロックされた大貫憲介弁護士のツイートは次の深澤諭史弁護士のツイートへの返信だと、ツイートを個別に開いたことでわかりました。深澤諭史弁護士にもブロックされているかと思いますが、８月１２日まではブロックされておらずリツイートが出来ていました。

fukazawas ===> You have been blocked from retweeting this user's tweets at their request.
ブロックされているのでリツイートできませんでした。→　https://twitter.com/fukazawas
▶ ブロックされたツイート％fukazawas（深澤諭史）％2019/08/20 10:43％ https://twitter.com/fukazawas/status/1163627681167994880
&twitter(1163627681167994880){theme:light}
> 弁護士の介入を異常に嫌い、弁護士のせいで家庭が壊れたと信じ込むロジックがよくわかる。
> モラハラとＤＶの最良証拠は、しばしば夫であるという典型例。
> （・∀・；） https://t.co/ypyupXQoAo  
▶

　深澤諭史弁護士のタイムラインでみかけて気になっていたツイートでしたが、これも大貫憲介弁護士のツイートを個別に開いたことで、次の深澤諭史弁護士のツイートを引用していたものだと気が付きました。

SatsukiLaw ===> You have been blocked from retweeting this user's tweets at their request.
ブロックされているのでリツイートできませんでした。→　https://twitter.com/SatsukiLaw
▶ ブロックされたツイート％SatsukiLaw（大貫憲介）％2019/08/20 09:18％ https://twitter.com/SatsukiLaw/status/1163606099095740416
&twitter(1163606099095740416){theme:light}
> https://t.co/mw6XnHQUMN
> 
> モラ夫バスターな日々25がアップされました。是非、ご一読下さい。  
▶

「愛してる」イコール「俺の奴隷になれ」。モラハラ夫の歪んだ言語感覚＜モラ夫バスターな日々25＞ | ハーバービジネスオンライン https://hbol.jp/199813?display=b

　ハーバービジネスオンラインというのがサイト名で、記事の配信サービスのような感じですが、これは初めて目にしたように思います。

　大貫憲介弁護士といえば「モラ夫」や「モラ夫バスター」のツイートがほとんどで、私はそのほとんどを深澤諭史弁護士のタイムラインでリツイートとして見かけてきたように思います。

　広告や宣伝という印象が強く、それもかなり過剰な表現と感じてきましたが、さほど問題視することもありませんでした。今回、より問題性が高いと感じている深澤諭史弁護士に、同意という趣旨の返信をしていたことで、改めて注目し、少し調べてみました。

　調べたと言っても、Twitterのアカウントのページを開き、プロフィールにあったリンクを開いた程度なのですが、その法律事務所のホームページが、事務所名を含めて初めてみた感覚をおぼえたので、不思議な気分になっています。

```
大貫憲介
@SatsukiLaw
国際離婚、離婚、親権、相続、外国法案件、入管(ビザ)、労働、刑事事件等を扱っています。英、タガログ、中国、韓国･朝鮮、日本語の多言語対応の弁護士事務所です。依頼者に寄り添い、常に最善を目指します!
東京都satsukilaw.com2010年4月からTwitterを利用しています
5,417 フォロー中
9,129 フォロワー

［source：］大貫憲介（@SatsukiLaw）さん / Twitter https://twitter.com/SatsukiLaw
```

　大貫憲介弁護士のTwitterのプロフィールを読んだのも初めてではないと思いますが、今回はずいぶん手堅いしっかりした内容の紹介文だと思いました。弁護士のTwitterアカウントのプロフィールでもかなり珍しい部類と感じました。別の要素を盛り込む弁護士が多いと感じます。

```
さつき法律事務所は、日本人の一般民事から外国法適用事件まで、広範囲の案件を取り扱っています。 当事務所は、殊に、外国人を当事者とする案件(外国人事件、国際的な案件)の分野では、先駆的な役割を果たしてきました。 私たちは、国際離婚／離婚弁護士として、数多くの国際離婚／離婚の案件を扱い、経験も豊富です。 当然ですが、日本人間の離婚も扱っています。 今後も、離婚、国際離婚に積極的に取り組んでいきます。 

ご相談者のお話しをじっくり聞き、証拠などを確認して、具体的な見通しと法的戦略を立てる、
リーガルプランニングを始めました。

［source：］さつき法律事務所 http://www.satsukilaw.com/
```

　多国語対応をうりとしており、専門性が高く感じます。モラ夫バスターなどと世間に挑発的なツイートをする必要性も疑問なのですが、ご本人の経験やポリシーもあるのでしょう。

　「さつき法律事務所」とありますが、ホームページのデザインも地球儀を平たくしたような世界地図に、女性の２つの手を合わせたような写真があり、他に青空と草原の丘のような写真もあって、爽やかな自然のいぶきを感じさせるもので、モラ夫バスターとは相容れないものです。

　すぐに思い出したのはモトケンこと矢部善朗弁護士（京都弁護士会）の法律事務所、四季の風法律事務所のホームページのことです。与える印象にも共通性がありますが、事務所の人員の構成と紹介にも似たものを感じました。その辺りを含めスクリーンショットを記録しています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 14:37 URL： https://twitter.com/kk_hirono/status/1163687378046709760 https://twitter.com/s_hirono/status/1163686519871115265
&twitter(1163687378046709760){theme:light}
> 2019-08-20-143556_「愛してる」イコール「俺の奴隷になれ」。モラハラ夫の歪んだ言語感覚＜モラ夫バスターな日々25＞　｜　ハーバービジネスオンライン.jpg https://t.co/GpQbLsjR6e
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 14:37 URL： https://twitter.com/kk_hirono/status/1163687392693243905 https://twitter.com/s_hirono/status/1163686447603314688
&twitter(1163687392693243905){theme:light}
> 2019-08-20-143528_「愛してる」イコール「俺の奴隷になれ」。モラハラ夫の歪んだ言語感覚＜モラ夫バスターな日々25＞　｜　ハーバービジネスオンライン.jpg https://t.co/Mjil25ECGl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 14:37 URL： https://twitter.com/kk_hirono/status/1163687410338684928 https://twitter.com/s_hirono/status/1163686375188602881
&twitter(1163687410338684928){theme:light}
> 2019-08-20-143503_「愛してる」イコール「俺の奴隷になれ」。モラハラ夫の歪んだ言語感覚＜モラ夫バスターな日々25＞　｜　ハーバービジネスオンライン.jpg https://t.co/M2TxtXSW0I
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 13:55 URL： https://twitter.com/kk_hirono/status/1163687431775739910 https://twitter.com/s_hirono/status/1163675998388248577
&twitter(1163687431775739910){theme:light}
> 2019-08-20-134712_スタッフ紹介　｜　四季の風法律事務所.jpg https://t.co/kRbI7cAXeq
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 13:55 URL： https://twitter.com/kk_hirono/status/1163687449467355136 https://twitter.com/s_hirono/status/1163675925969399808
&twitter(1163687449467355136){theme:light}
> 2019-08-20-134632_スタッフ紹介　｜　四季の風法律事務所.jpg https://t.co/XfMW0nYJdA
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 13:55 URL： https://twitter.com/kk_hirono/status/1163687467561582592 https://twitter.com/s_hirono/status/1163675854028677121
&twitter(1163687467561582592){theme:light}
> 2019-08-20-134601_スタッフ紹介　｜　四季の風法律事務所.jpg https://t.co/KhIrzQ8q6O
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 13:55 URL： https://twitter.com/kk_hirono/status/1163687485139906560 https://twitter.com/s_hirono/status/1163675781240770560
&twitter(1163687485139906560){theme:light}
> 2019-08-20-134525_四季の風法律事務所　｜　敷居の低い法律事務所を目指します。.jpg https://t.co/oUaUp2CH59
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 13:54 URL： https://twitter.com/kk_hirono/status/1163687519579332608 https://twitter.com/s_hirono/status/1163675708767387648
&twitter(1163687519579332608){theme:light}
> 2019-08-20-134355_モトケン（@motoken_tw）さんの返信があるツイート　／　Twitter.jpg https://t.co/wSDu6BHuap
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 13:54 URL： https://twitter.com/kk_hirono/status/1163687551250468864 https://twitter.com/s_hirono/status/1163675636692447232
&twitter(1163687551250468864){theme:light}
> 2019-08-20-134326_弁護士紹介　-　さつき法律事務所.jpg https://t.co/5KKYyZ4sPJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 13:54 URL： https://twitter.com/kk_hirono/status/1163687572431708161 https://twitter.com/s_hirono/status/1163675563971600384
&twitter(1163687572431708161){theme:light}
> 2019-08-20-134233_弁護士紹介　-　さつき法律事務所.jpg https://t.co/GY7G2f6kMI
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:41／2019-08-20 13:53 URL： https://twitter.com/kk_hirono/status/1163687603058536448 https://twitter.com/s_hirono/status/1163675491577896960
&twitter(1163687603058536448){theme:light}
> 2019-08-20-134149_さつき法律事務所.jpg https://t.co/TO8ZTuyJGR
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:42／2019-08-20 13:53 URL： https://twitter.com/kk_hirono/status/1163687621094072321 https://twitter.com/s_hirono/status/1163675419058425856
&twitter(1163687621094072321){theme:light}
> 2019-08-20-134126_大貫憲介（@SatsukiLaw）さん　／　Twitter.jpg https://t.co/aR7GC5xPZh
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-20 14:42／2019-08-20 13:53 URL： https://twitter.com/kk_hirono/status/1163687638609485824 https://twitter.com/s_hirono/status/1163675346853494784
&twitter(1163687638609485824){theme:light}
> 2019-08-20-134049_大貫憲介さんはTwitterを使っています：　「@fukazawas　同意します。」　／　Twitter.jpg https://t.co/1WFhxxSyJ6
◁◁◁
<hr />

　さつき法律事務所にある大貫憲介弁護士の顔写真ですが、ずいぶん前にどこかで見かけていたものと同じで、サイズが大きくなっていると思ったのですが、いつ頃どこで見ていたのか、はっきりとは思い出せません。ただ、ずいぶん前だったので５年以上かもしれません。

　大貫憲介弁護士のTwitterのプロフィールにも２０１０年４月からの利用とあります。これも今回意外な情報と感じたのですが、以前はモラ夫というツイートはなかったのかもしれません。たまに見かける弁護士アカウントとして、あの顔写真のアイコンがあったとも考えられます。

　警察官が被疑者に表立って挑発的な言動をすれば大問題になるかと想像しますし、以前は、警察の暴力や威圧的態度、逆に警察に根深い恨みを持つ犯罪者というのは、ごく身近な存在として社会に浸透していたかと思います。少なくとも平成の初めころは、そういう時代の雰囲気がありました。

　モラ夫というのは、最近、モトケンこと矢部善朗弁護士（京都弁護士会）も使った時期がありました。深澤諭史弁護士においては大貫憲介弁護士に手放しで完全同意といった感じです。

　たしかにモラ夫として取り沙汰すモデルはあるのかと思います。ここ数日、テレビで取り上げている茨城県での煽り運転暴行事件の被疑者など典型的な危険人物のような報道ですが、精神的に病気だった可能性も示唆されながら、それを問題視する弁護士のツイートはみていません。

　そういえば、深澤諭史弁護士のタイムラインに大貫憲介弁護士のツイートと隣接するかたちで、かなり気になる内容のツイートがありました。スクリーンショットには映り込んでいるかと思います。映り込むことを意識して記録をしました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jmtpjmgmt（優良にゃん🍒🐱緊縮財政） 日時：2019-08-20 15:06／2019-08-20 12:57 URL： https://twitter.com/kk_hirono/status/1163693735923736576 https://twitter.com/jmtpjmgmt/status/1163661256865112065
&twitter(1163693735923736576){theme:light}
> 健康で文化的な最低限度の生活が「衣食足りて礼節を知る」最低限であり、これを下回ったら無敵の人を生むのだと思います。無敵の人を生んだ不利益は、無敵の人の人本人の破滅だけにとどまらないことは、京アニ事件でよくわかったのではないでしょうか。あれが今後どんどん起こったらどうなることやら。
◁◁◁
<hr />

　ブロックされていると思ったのですが、リツイートが成功しました。実行してみないとわからないものです。奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)でもリツイートが出来ていました。

　奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントを開いたところで、高校野球のことを思い出したのですが、トレンドのさらに表示で、星稜のことが出てきました。中京学院大中京に９対０で勝ち、決勝進出とのことです。

　決勝は履正社ですが、春の選抜では３ｘ０で石川星稜が勝っているとのことです。星稜は以前にも決勝戦進出がありましたが、あのときは幸運が重なったとしか思えず、決勝戦では勝ち目がないと見ていてそのとおりの結果になったのですが、今回の決勝戦は期待が出来そうです。

　星稜は投手が活躍し期待されても、打線が今一つで延長戦というのも多いという印象だったのですが、智弁和歌山に延長戦で勝ってからは、１７ｘ１，９ｘ０と打線が大量点を獲得しているようです。優勝すれば石川県勢初になります。

　Twitterのトレンドには大雨の避難勧告というのもありました。昼前のニュースでは富山で大雨で床下浸水というのを見かけていましたが、新潟県の上越地方などで避難勧告が出ているようです。テレビのミヤネ屋は気象情報や災害に力を入れているのですが、ニュースはありませんでした。

　テレビには余り集中せず、つけているという感じですが、今日も司会の宮根誠司さんの姿を見かけていないと気が付きました。昨日の放送でも見ておらず、説明は見なかったのですが、夏休みに入っているのでしょう。

　深澤諭史弁護士のリツイートとしてみた優良にゃんというアカウントですが、３，４ヶ月ほど前から注目しています。最初に注目したのはツイートの数の多さでした。何かのツイートがきっかけで記録用のアカウントに入れたのですが、頻繁に更新作業でエラーが発生しました。

　一週間ほど前になりますか、正確な日数など記憶するのも無理なのですが、この優良にゃんというTwitterアカウントは、非公開設定に切り替わっていたかと思います。その復活に気がついたのも深澤諭史弁護士のリツイートであり、ツイートの内容も深いものがあります。

```
Diginnos-PC:~/2017_法務検察当局宛て注目参考資料弁護士のリスト化ツイート_m
[5670]  % time TU=`xsel -b|sed 's/.*twitter\.com\/\([^ /]\+\).*/\1/'`; echo $TU; h-show-twitter-profile.rb $TU; for x in {1..17};do tw_user_timeline_1line.rb $TU 200 $x >> $TU; done &&  st=$(grep "^\(▶TW \|▶RT \).*" $TU |tail -1|sed "s/.*日時：\(....\)-\(..\)-\(..\) \(..\):\(..\)[ ／].*/\1\2\3\4\5/"); et=$(grep "^\(▶TW \|▶RT \).*" $TU |head -1|sed "s/.*日時：\(....\)-\(..\)-\(..\) \(..\):\(..\)[ ／].*/\1\2\3\4\5/"); mv $TU ${TU}_${st}-${et}.txt; echo  -e "\n取得件数： ";  grep "^\(▶TW \|▶RT \).*" ${TU}_${st}-${et}.txt| wc -l; echo "取得した最新ツイート："; sed -n '1p' ${TU}_${st}-${et}.txt; echo "取得した最古ツイート："; sed -n '$p' ${TU}_${st}-${et}.txt

real	0m0.012s
user	0m0.002s
sys	0m0.012s
jmtpjmgmt
＜2019年08月20日(火) 15時41分03秒にTwitterAPIで取得したjmtpjmgmt（優良にゃん🍒🐱緊縮財政）のプロフィール情報＞
特定ダメゼッタイ（晒したら断固たる手段！！！徹底抗戦！！！！許すまじ！！！）/ブルッ弁の超零細事務所/読書好き📕/旅行好き/温泉好き♨️/猫が好き🐱/緊縮財政

取得件数： 
3220
取得した最新ツイート：
▶TW jmtpjmgmt（優良にゃん🍒🐱緊縮財政） 日時：2019-08-20 12:58 URL： https://twitter.com/jmtpjmgmt/status/1163661661007253505 TWEET： たまたまBとつながったことなど運の要素が強かったです。このまま放置していたら、テロでも起こってたかもなと思いましたね。。  
取得した最古ツイート：
▶TW jmtpjmgmt（優良にゃん🍒🐱緊縮財政） 日時：2019-08-08 21:30 URL： https://twitter.com/jmtpjmgmt/status/1159441831857283074 TWEET： @princessbea1215 @ryouheitakaki 上訴審で引いた事件は、原審がryなのが半分くらいありましたね。
```

　エラーが出たままだったので、手動での更新作業を実行しました。jmtpjmgmt_201904280642-201908161727.txt  jmtpjmgmt_201908082130-201908201258.txt　これからマージを行います。

　201908082130-201908201258.txtが更新のため取得した最新のデータになりますが、８月８日２１時３０分から８月２０日１２時５８分までの間で、取得件数が３２２０になります。リツイートを含むものではありますが、相当な数です。

　にわかに信じがたい現象を目の当たりにしたので、「tu3 jmtpjmgmt」という自作のコマンドを実行して、記事を作成しました。これはアカウントを引数として指定したコマンドで。TwitterAPIで最大限のタイムラインのツイートを取得しテキストデータとしてアップロードします。

[link:] 2019年08月20日15時54分の登録： @jmtpjmgmt（優良にゃん??緊縮財政）のツイート　”．＊”　3220／3220：2019-08-08　21：30〜2019-08-20　12：58　2019年08月20日15時54分の記録 http://hirono2014sk.blogspot.com/2019/08/jmtpjmgmt322032202019-08-0821302019-08.html 

　単純に３２２０件のツイートを１２日間で割っても一日あたり２６８件のツイートになります。リツイートが含まれますが、読まないツイートをリツイートしているとは考えにくく、短文のツイートも数が多くなれば、読むのにけっこうな時間がかかるものと思います。

　ツイートでアフェリエイトのブログ記事でも紹介していれば収益につながることもあるのかと想像しますが、このTwitterに費やす時間と労力、それが弁護士の業務と両立するものなのか前々から不思議に思っていました。同じ傾向の弁護士アカウントは実名でもいます。

　機会的な処理としてgrepコマンドで確認したので間違いがないと保証は出来ないですが、2238が３２２０件中の優良にゃん本人のツイートの数のようです。計算をやったみたのですが、約６９％がツイートの割合のようです。残りの約２１パーがリツイートになるのでしょう。

　２２３８件を１２日間で割ってみると１８６件でした。８月８日から８月２０日までで１２日間ですが、８月８日のツイートは２１時３０分からの計測算入開始です。８月２０日は本日になりますが、１２時５８分で計測が終了しています。

　ざっとみると、平均で一日あたりリツイートを別にしたツイートが１９０件ほどになるかと思います。ずいぶんツイートをしまくったと思っても、なかなか１９０件という数にはならないことを経験しています。ただ、この数に実感がわかない人がほとんどとも考えられます。

　時刻は１６時３９分です。とある処理を行っているのですが、思いの外時間が掛かっています。処理に時間がかかるのは取得している結果が多いということになります。データベースへの登録が多いので、さらに時間が掛かっているようです。

　作業が終わるまで、優良にゃんのTwitterのプロフィールを引用で掲載してご紹介しておこうと思います。弁護士生物の生態の１つです。悪性か否かは今回問題としていません。私としては深澤諭史弁護士のリツイートがあればこその注目でもあります。

```
優良にゃん緊縮財政
@jmtpjmgmt
特定ダメゼッタイ（晒したら断固たる手段！！！徹底抗戦！！！！許すまじ！！！）/ブルッ弁の超零細事務所/読書好き/旅行好き/温泉好き/猫が好き/緊縮財政
スガモプリズンmatome.naver.jp/m/odai/2139450…2017年10月からTwitterを利用しています
1,126 フォロー中
1,646 フォロワー

［source：］(1) 優良にゃん🍒🐱緊縮財政（@jmtpjmgmt）さん / Twitter https://twitter.com/jmtpjmgmt
```

　引用の範囲選択時にブル弁ではなく「ブルッ弁」となっていることに気が付きました。ブル弁というのはSNSが登場する以前、平成１０年代の中頃にも見かけていたと思いますし、それ以前も書籍などで見かけていたかもしれません。ブルジョア弁護士、つまりお金持ち弁護士のことと思います。

　ブルジョアというのは、私が本を読むようになる前に使われていた古い言葉で、マルクスの資本論や共産主義と関係する言葉のようです。最近は見かけることも少ないので知らない人が多いのかもしれません。独特の世界観を持った言葉ですが、時代背景の理解が前提となりそうです。

　ブル弁は多くの場合、バス弁と一致しそうに思います。法律事務所の経営者を意味するのだと思いますが、弁護士法人というのもあるので時には上司の弁護士を指すこともあるのかもしれません。

　ボス弁と対義語のように見かけるのがイソ弁で、最近は見かける機会が少なくなっているとも思いますが、居候弁護士を意味するとされています。他にアソシエイトというものを見かけたり、法律事務所に所属する弁護士同士の関係も契約等でいろいろと形態があるようです。

　時刻は１６時５９分ですが、まだ処理が続いています。処理件数は７６８件辺りまで確認しました。このスクリプトはエラーが出る前に８５００件で終了するようにしています。データベースの登録が少ないと８５００件まで行っても、それほど時間は掛かりません。

　どうも優良にゃんは、私が想定していた以上に法クラの間で人気者のようです。弁護士ではないと疑問の声があがったのも記憶にないですが、優良にゃんが弁護士と明示するのも余り見かけていない気がします。弁護士というワードは避けているのかもしれません。

　これも確認をしておこうかと思います。

　何十分か前にプロフィールの引用をしたときも気が付かなかったのですが、優良にゃんのTwitterアカウントのヘッダ画像が鉄道の列車の写真となっていました。そういえばだいぶん前から同じものを目にしていたような気もするのですが、今回はっきり気が付きました。

　私の人生、生活において、弁護士と鉄道というのは切り離せない関係性があります。比較的最近になって、その感を強めた追加の出来事は、テレビのゲゲゲの鬼太郎でみた「幽霊電車」でした。小倉秀夫弁護士も「女性専用（電車）」に異様なこだわりを発揮していました。

"弁護士" (from：@jmtpjmgmt) - Twitter検索 / Twitter https://twitter.com/search?q=%22%E5%BC%81%E8%AD%B7%E5%A3%AB%22%20(from%3A%40jmtpjmgmt)&src=typed_query

　上記のTwitterの検索結果のURLがEmacsで一部「&src=typed_query」という部分がURLインクから外れていて、直接ブラウザにURLを打ち込んだりしていたのですが、検索結果がなしとなっていました。

　検索結果の表示されたページがブラウザのタブとして残っていたので、スクリーンショットの記録をしましたが、そのあとページの再読込をすると、検索結果がなしと表示されました。まだ確認していませんがアカウントが非公開設定になった可能性が高そうです。

　案の定、非公開設定になっていましたが、これは私の一連の作業に気が付き対処した可能性がありそうです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-20 17:28／2019-08-20 17:28 URL： https://twitter.com/kk_hirono/status/1163729595222224896 https://twitter.com/hirono_hideki/status/1163729422093975553
&twitter(1163729595222224896){theme:light}
> 2019年08月20日17時24分の実行記録 \n  twitterAPI-search-lawList-mydql-add.rb "@jmtpjmgmt" \n  ツイート数：524/1499 リツイート数：155/1499 トータル：1410… https://t.co/775jB4vkVh
◁◁◁
<hr />

　作業が終わっていたので記録しました。しかし、TwitterAPIで取得したツイートの内容は、末尾がカットされています。

```
2019年08月20日17時24分の実行記録
twitterAPI-search-lawList-mydql-add.rb "@jmtpjmgmt"
ツイート数：524/1499 リツイート数：155/1499 トータル：1410
hirono_hideki 2／1件
kk_hirono 1／1件
s_hirono 1／0件
```

　上記にテキストを貼り付けました。コマンドの実行結果です。自作のコマンドなので、表示の内容も自分で設定済みのものです。数字の部分などは変数の値を参照させていますが、定形の書式を設定しています。

[link:] 2019年08月20日17時39分の登録： REGEXP：”@jmtpjmgmt”／データベース登録済みツイート：2019年08月20日17時33分の記録：ユーザ・投稿：146／1529件 http://hirono2014sk.blogspot.com/2019/08/regexpjmtpjmgmt2019082017331461529.html

[link:] 2019年08月20日17時43分の登録： REGEXP：”@jmtpjmgmt”／データベース登録済みツイートの検索：2019-08-13〜2019-08-20／2019年08月20日17時40分の記録：ユーザ・投稿：66／390件 http://hirono2014sk.blogspot.com/2019/08/regexpjmtpjmgmt2019-08-132019-08.html

[link:] 2019年08月20日17時45分の登録： REGEXP：”@jmtpjmgmt”／データベース登録済みツイートの検索：2019-08-17〜2019-08-20／2019年08月20日17時44分の記録：ユーザ・投稿：47／194件 http://hirono2014sk.blogspot.com/2019/08/regexpjmtpjmgmt2019-08-172019-08.html

[link:] 2019年08月20日17時47分の登録： REGEXP：”@jmtpjmgmt”／データベース登録済みツイートの検索：2019-08-19〜2019-08-20／2019年08月20日17時46分の記録：ユーザ・投稿：30／91件 http://hirono2014sk.blogspot.com/2019/08/regexpjmtpjmgmt2019-08-192019-08.html

　上記のまとめ記事は、優良にゃんの＠ユーザ名を含むツイートで、期間指定なし（146／1529件）、直近７日間（66／390件）、直近３日間（47／194件）、直近１日間（30／91件）となっています。／の左の数値は該当アカウント数です。

　一日分（２４時間）だけで次の結果です。思いの外、優良にゃんのツイートのリツイートではなく、優良にゃんのアカウントに対する返信ツイートが多いようです。

```
アカウント名	ツイート数	リツイート数
優良にゃん??緊縮財政（jmtpjmgmt）	0	3
芦原修一?（ashiharashuichi）	7	0
ひなた荘の管理人（弁護士）（shinobuhome）	1	0
K - 9 9 9 9（k999941457035）	0	1
なべきょう＠過眠症（wata_nabekyo_ko）	20	0
えるにえ（Ernie2326）	1	0
D弁（dben82716007）	0	1
高木良平（ryouheitakaki）	8	0
ふくろうの家（bgsh_owl）	3	0
橋本太地（弁護士・あなたのみかた法律事務所）（kojin_syugi）	7	0
さばかん（sabalog）	1	0
坂本正幸（sakamotomasayuk）	2	0
mototakiryu（mototakiryu）	1	0
弁護士7286（jmjhjmwtad）	9	0
KURODA TAKASHI（kitaguni_b）	3	0
まゆこ（mayukotaniguchi）	3	0
TｰTAKA（TGN54）	1	0
ぷら（purapura415）	1	0
弁護士岡田晃朝（あさがお法律事務所）（asagaolaw）	1	0
ぽぽひと@内閣調査室所属（popohito）	1	3
鳩屋（haya_rt）	1	0
泥濘大魔王サイケ（k_sawmen）	0	1
Takumi-Aikawa（公法1位論文16位全科目Aの司法試験合格アドバイザー）19（TA_legal32）	0	1
dtk（dtk1970）	0	1
深澤諭史（fukazawas）	0	1
芝原章吾（shogoshibahara）	0	1
非常上告-最高検察庁御中_ツイッター（s_hirono）	1	0
アリアンデルの猫（laparkadejapon）	0	1
告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中（kk_hirono）	1	1
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	2	1


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”@jmtpjmgmt”／データベース登録済みツイートの検索：2019-08-19〜2019-08-20／2019年08月20日17時46分の記録：ユーザ・投稿：30／91件 http://hirono2014sk.blogspot.com/2019/08/regexpjmtpjmgmt2019-08-192019-08.html
```

＜＜＜2019-08-20（火曜日）18：00＿［これまでの記述範囲の終了時刻］＜＜＜

