#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "参考資料／弁護士業界の現状／深澤諭史弁護士のリツイート／「本当に有益な情報は有料だ」ということにいつまで経っても気がつくことができず、ゴミ情報ばかりに振り回されることになる。"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-19 23:22:53 +0900
FILE_NAME: 2018-12-19-232253_「本当に有益な情報は有料だ」ということにいつまで経っても気がつくことができず、ゴミ情報ばかりに振り回されることになる。.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  深澤諭史弁護士のリツイート 中村剛弁護士 66期 東京弁護士会 無料 情報
記事タイトル名の文字数：87　保存ファイル名の文字数：81

#contents

* 深澤諭史弁護士がリツイートした中村剛弁護士のツイート

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜take___five（中村剛（take-five）） 日時：2018-12-19 23:27／2018-12-18 22:43 URL： https://twitter.com/kk_hirono/status/1075397227256791040 https://twitter.com/take___five/status/1075023782966812677
&twitter(1075397227256791040){theme:light}
> 「情報は無料だ」としか思っていない人は、「本当に有益な情報は有料だ」ということにいつまで経っても気がつくことができず、ゴミ情報ばかりに振り回されることになる。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜XxDAISOxX1（零式てーとくPS3.PS4対応HACK代行） 日時：2018-12-19 23:28／2018-12-18 23:44 URL： https://twitter.com/kk_hirono/status/1075397457687629824 https://twitter.com/XxDAISOxX1/status/1075039191334088704
&twitter(1075397457687629824){theme:light}
> @take___five 有料でゴミも多いですよね
◁◁◁
<hr />

▷ リツイート→fukazawas（深澤諭史）＞take___five（中村剛（take-five））｜2018/12/19 22:01／2018/12/18 22:43｜https://twitter.com/fukazawas/status/1075375550330335232 ／ https://twitter.com/take___five/status/1075023782966812677
&twitter(1075375550330335232){theme:light}
> RT @take___five: 「情報は無料だ」としか思っていない人は、「本当に有益な情報は有料だ」ということにいつまで経っても気がつくことができず、ゴミ情報ばかりに振り回されることになる。  

* 「無料」をキーワードにした深澤諭史弁護士のツイートの記録（2018年12月19日作成）

[link:] 2018年12月19日23時35分の登録： REGEXP：”無料”／深澤諭史（@fukazawas）の検索（2012-12-14〜2018-12-17／2018年12月19日23時35分の記録341件） http://hirono2014sk.blogspot.com/2018/12/regexpfukazawas2012-12-142018-12.html

```
取得件数が199件を超えています。埋め込みツイートのデザインが反映されない場合があるので、古いものから表示される初めの100件と最終（最新）部分の99件のみ埋め込みツイートを適用します。

REGEXP（サーチ）： "無料"　該当：341件　取得ツイートの投稿日時の範囲：（2012-12-14 12：05〜2018-12-17 12：15）

SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND tweet REGEXP "無料" ORDER BY tw_date ASC

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”無料”／深澤諭史（@fukazawas）の検索（2012-12-14〜2018-12-17／2018年12月19日23時35分の記録341件） http://hirono2014sk.blogspot.com/2018/12/regexpfukazawas2012-12-142018-12.html
```

　思いの外、数が多くて、とても全部に目を通すことはできません。成り行き任せになりますが、ざっとスクロースをしながら気になったものを次にいくつかご紹介しておきたいと思います。

▶（002／341） TW fukazawas（深澤諭史） 日時： 2013-02-12 00:05:00 +0900 URL： https://twitter.com/fukazawas/status/300983812173729793
{% tweet 300983812173729793 %}
> Visual Studio Express っていうのなら，無料なんだよね。私は，Mono Developに浮気しているけれど（Ｃ＃の場合） RT

　深澤諭史弁護士はこれまで、プログラミングについてはゲームの作成をしたというようなツイートをしていたと思います。このツイートもそういえばと思いだしたものですが、テキスト処理などはどうしているのかと前から気になっていました。

　「Mono Develop」というのは何のことかわかりません。デベロッパーなら開発者という意味なのでしょう。Monoというのも少し見かけた気はします。やはり気になるので、少し調べておきましょう。

```
個人的にはUnityインストール時に付属するBuiltin-MonoDevelopは使いづらいと思っている。
単純に日本語が標準で使えないのと、立ち上げ直すたびに設定した項目が初期化されていたりなど、パッと使いやすいものの気にし始めたら気になる所が多く、ままならないので思い切って他のエディターを使うことに決めた。

［source：］Unity付属のMonodevelop以外でコーディングをする - Qiita https://qiita.com/niwatori/items/a862d50cf61f45d77dba
```

　Unityについては、以前少し調べたことがありました。当時、Ubuntuの標準のディスクトップ環境となっていたのもUnityという名称でしたが、まったく別物だったと思います。

```
この項目では、ゲームエンジンについて説明しています。Ubuntuに同梱されていたユーザインタフェースについては「Unity (ユーザインタフェース)」をご覧ください。

［source：］Unity (ゲームエンジン) - Wikipedia https://ja.wikipedia.org/wiki/Unity_(%E3%82%B2%E3%83%BC%E3%83%A0%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3)
```

　ゲームエンジンとあります。ゲームを作るような高度なプログラミングなのかと思われます。ざっとみると「パチンコ・パチスロを含む日本国内の遊技機およびアーケードゲーム機開発用ライセンス「Unity for 遊技機」の販売も開始された[6]。」ともあります。

　同じプログラミングでもテキスト処理の方が弁護士業務としては役立つ気がするのですが、深澤諭史弁護士に関してはワープロソフトの一太郎を愛用し、Macの環境で何かが使えないという不満を述べているツイートは見かけています。

　検索の趣旨の無料とは意味が無関係になりますが、最近、深澤諭史弁護士はシステム開発の訴訟代理人もしているようなツイートをしていました。インターネットに強いというような趣旨の紹介もネットの検索では目につきます。

▶（016／341） TW fukazawas（深澤諭史） 日時： 2013-05-12 21:40:00 +0900 URL： https://twitter.com/fukazawas/status/333562252642902016
{% tweet 333562252642902016 %}
> 私選刑事弁護では，家族からの相談は無料というものが多いですね。あえてこれ以上は，何もいいませんが…。

▶（021／341） TW fukazawas（深澤諭史） 日時： 2013-06-26 14:00:00 +0900 URL： https://twitter.com/fukazawas/status/349754101787131904
{% tweet 349754101787131904 %}
> 無料相談とはいえ，トンデモ契約にはまりそうな企業を救えたりするのは気分がよい。

　私が深澤諭史弁護士のTwitterアカウントの存在を認識したのは2014年と思われます。スクリーンショットの記録でも卵アイコンとして見つけたところから始まっていました。2013年のツイートをみると、無料の法律相談も行っていたようです。

▶（024／341） TW fukazawas（深澤諭史） 日時： 2013-10-28 11:41:00 +0900 URL： https://twitter.com/fukazawas/status/394655188180418561
{% tweet 394655188180418561 %}
> 法律事務所の立派なビルの賃借料、無料相談の相談料、綺麗な広告の宣伝広告費、結局最後に支払うのは、弁護士ではなくて依頼した人です。 \n ちょっと一面的な見方ではありますが、心の片隅にはおいておいても良いかもしれません。

　深澤諭史弁護士らしい世界観、価値観のツイートが出てきました。弁護士をいつまで経っても変わらない絶対的な存在として位置づけ、それを前提に思考しているようです。弁護士の迷惑には真剣に目を向けず、ときには司法制度改革の過悪だと意味づけています。

▶（025／341） TW fukazawas（深澤諭史） 日時： 2014-01-07 08:54:00 +0900 URL： https://twitter.com/fukazawas/status/420342593994518528
{% tweet 420342593994518528 %}
> @Shingo_Nakao １０００円のランチを無料で出さないレストランは責められませんね(･∀･) \n 私は料理とシェフに敬意を払っているので，もちろん要求しませんが

　次のツイートへの返信ツイートのようです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Shingo_Nakao（中尾慎吾/Shingo Nakao） 日時：2018-12-20 00:08／2014-01-07 08:47 URL： https://twitter.com/kk_hirono/status/1075407646339944449 https://twitter.com/Shingo_Nakao/status/420340888624041984
&twitter(1075407646339944449){theme:light}
> 無料相談を行っていないことがそんなに責られるべきことなのかな？
◁◁◁
<hr />

　ときどき深澤諭史弁護士のタイムラインなどで見かけてきた弁護士アカウントのツイートです。中尾慎吾とありますが、実名なのでしょう。これまで調べたことはなかったように思います。ウィスキーと思われる宮城峡のカバー写真はだいぶん前から見覚えがあります。

```
［link：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＃中尾慎吾/Shingo Nakao　@Shingo_Nakao＃のツイート／2018-12-14_2352〜2018-12-19_2259／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月20日00時13分 http：//hirono2014sk.blogspot.com/2018/12/shingo-nakaoshingonakao2018-12_20.html
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
指定アカウントの最新199件のツイート
2018-12-14 23：52から199件：最新2018-12-19 22：59という範囲（4日23時間7分）の取得

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＃中尾慎吾/Shingo Nakao　@Shingo_Nakao＃のツイート／2018-12-14_2352〜2018-12-19_2259／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月20日00時13分 http://hirono2014sk.blogspot.com/2018/12/shingo-nakaoshingonakao2018-12_20.html
```

```
中尾慎吾/Shingo Nakao（Shingo_Nakao）のプロフィール情報（2018年12月20日00時13分44秒頃の取得）：
-----------------------------------------------------------
［name］ユーザ名称：中尾慎吾/Shingo Nakao

［screen_name］ユーザ名：Shingo_Nakao

位置情報：インターネット/大阪/東京/仙台/福島

ユーザ説明：
弁護士. コンサルタント. 効率化と合理化の追求. Twitterはメルマガやブログ的に使っています. (e-mail) shingo.nakao1015@gmail.com (instagram)https：//t.co/qgJGbvIMaD

ユーザのフォロワー数：4039

ユーザのフォロー数：701

ユーザがTwitterに登録した日時：2009-11-16 06：00：32 UTC

ユーザの投稿ツイート数：72849

===========================================================

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＃中尾慎吾/Shingo Nakao　@Shingo_Nakao＃のツイート／2018-12-14_2352〜2018-12-19_2259／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月20日00時13分 http://hirono2014sk.blogspot.com/2018/12/shingo-nakaoshingonakao2018-12_20.html
```

　位置情報が「インターネット/大阪/東京/仙台/福島」となっています。ユーザ説明に「弁護士、コンサルタント」とあります。これは珍しく感じました。APIの情報ですが、Twitterのプロフィールのことだと思います。

```
弁護士は最強のコンサルタントである
相談件数、年間200超え

☆電話カウンセリング・コンサルティングを始めました。遠方の方もまずはお問い合わせ下さい☆

［source：］中尾 慎吾弁護士（小原法律事務所） - 大阪府大阪市 - 弁護士ドットコム https://www.bengo4.com/osaka/a_27100/g_27127/l_192729/
```

　ちょっと気になったので調べてみました。住所が「大阪府大阪市北区西天満」とあります。たまにリツイートなどで見かけてきましたが、ブックマークにも入れてなかったと思います。コンサルタント業務の実績もおありなのかもしれません。

▶（026／341） TW fukazawas（深澤諭史） 日時： 2014-01-23 13:29:00 +0900 URL： https://twitter.com/fukazawas/status/426210117759926272
{% tweet 426210117759926272 %}
> 総本山の地下一階にて、飲み物無料のサービスを受ける(･∀･*) \n 昼間だが、光速で赤ワインを選択(･∀･)

　総本山というのは日弁連（日本弁護士連合会）のことで、団体というよりは団体の入るクレオという会館というか建物を意味するようでもあります。クレオについては過去にまとめたものもあるかと思うのでご紹介しておきます。

```
[10122]  % dp -p|grep クレオ
[link:] 2017年10月04日15時37分の登録： ＼第二東京弁護士会　@niben_net＼９月１１日午後６時から、人権擁護大会のプレシンポジウム「犯罪被害者のための『連携』を考えよう！」が弁護士会館２階講堂クレオにて開催 http://hirono2014sk.blogspot.com/2017/10/nibennet_4.html
[link:] 2017年10月15日16時49分の登録： ＼第二東京弁護士会　@niben_net＼９月１１日午後６時から、人権擁護大会のプレシンポジウム「犯罪被害者のための『連携』を考えよう！」が弁護士会館２階講堂クレオにて開催されます http://hirono2014sk.blogspot.com/2017/10/nibennet_15.html
[link:] 2017年10月27日21時41分の登録： REGEXP：”全裸．＊クレオ”／サイ太（@uwaaaa）の検索（2014-11-10 09:31〜2017-03-04 09:02／2017年10月27日21時41分の記録3件） http://hirono2014sk.blogspot.com/2017/10/regexpuwaaaa2014-11-10-09312017-03-04.html
[link:] 2017年10月29日01時09分の登録： REGEXP：”総本山（日弁連｜クレオ）？”／データベース登録済みツイートの検索（2017-01-13〜2017-10-25／2017年10月29日01時08分の記録199件）<br /> http://hirono2014sk.blogspot.com/2017/10/regexp2017-01-132017-10.html
[link:] 2018年01月11日23時12分の登録： ＼サイ太　@uwaaaa＼「弁護士快感　２回見てクレオ」っていうAVありそう http://hirono2014sk.blogspot.com/2018/01/uwaaaaav.html
[link:] 2018年09月27日16時49分の登録： ＼中村元弥　@1961kumachin＼9月29日（土）午前10時30分～午後5時30分　日弁連2階講堂クレオで開催される第28回司法シンポジウム「司法における国民的基盤 http://hirono2014sk.blogspot.com/2018/09/1961kumachin9291030530228.html
[link:] 2018年11月27日21時54分の登録： ＼こたぴょん　@kotadon＼今日、総本山にいるよ。運が良ければお菓子あげるよ。ただ、クレオにはいないからね http://hirono2014sk.blogspot.com/2018/11/kotadon_27.html
```

▶（2／3） TW uwaaaa（サイ太） 日時： 2016-01-28 19:13:00 +0900 URL： https://twitter.com/uwaaaa/status/692651731415478272
> 「なーにが臨時総会決議じゃ！　ワシのケツ議案も審議してクレオ！」全裸中年男性がいつものように弁護士会館クレオに侵入！　壇上に上がり自らのクレオ像を開帳する姿は，まさに前門の虎ならぬ肛門の虎！

▶（3／3） TW uwaaaa（サイ太） 日時： 2017-03-04 09:02:00 +0900 URL： https://twitter.com/uwaaaa/status/837815595705913346
> 昨日の臨時総会は感動した。特にラストシーンで会長が全裸になり「見てクレオ！」と絶叫するシーンは涙無しには見られなかった。

　刑裁サイ太というのは匿名の弁護士のようです。以前、日弁連のプロモーションビデオのようなものがYouTubeにあり、多数の弁護士がいましたが、その中の一人として映像にあるというツイートを見かけたこともありました。匿名性は保たれているようです。

▶（027／341） TW fukazawas（深澤諭史） 日時： 2014-02-05 20:22:00 +0900 URL： https://twitter.com/fukazawas/status/431025137991696386
{% tweet 431025137991696386 %}
> 「絶対に勝つと思います」 \n 「とにかく懲らしめてやりたい」 \n という人の着手金無料を希望する率は異常

　深澤諭史弁護士らしいツイートです。実に。

▶（028／341） TW fukazawas（深澤諭史） 日時： 2014-02-07 11:27:00 +0900 URL： https://twitter.com/fukazawas/status/431615248223567872
{% tweet 431615248223567872 %}
> ＴＬ見て思いましたが，せっかくＴｗｉｔｔｅｒ上で高名なプロのアドバイスをしかも無料で聞けるチャンスなのに言い負かそうとすることしか考えないのはもったいない \n (･∀･)

　まだ2014年2月7日のツイートです。ワープというか大幅に飛ばしたいと思います。

▶（038／341） TW fukazawas（深澤諭史） 日時： 2014-08-30 10:21:00 +0900 URL： https://twitter.com/fukazawas/status/505525655388168192
{% tweet 505525655388168192 %}
> 弁護士があえて無料相談を受ける理由は，いろいろあるが，一つに， \n \n 「相談料を気にして相談せずに放置すると取り返しがつかなくなる可能性の高い事案」 \n \n というものがある。 \n 無料相談を無断キャンセルする人たちは，そのあたりは分かっているのだろうか。

▶（039／341） TW fukazawas（深澤諭史） 日時： 2014-09-20 17:01:00 +0900 URL： https://twitter.com/fukazawas/status/513236371490607104
{% tweet 513236371490607104 %}
> 「弁護士は増やしまくって自由競争！」 \n という人と、 \n 「弁護士は無料で●●してほしい！」 \n っていう人とは、 \n まさか同じではないですよね？(笑) \n (･∀･)

▶（041／341） TW fukazawas（深澤諭史） 日時： 2014-11-01 13:25:00 +0900 URL： https://twitter.com/fukazawas/status/528402424197705730
{% tweet 528402424197705730 %}
> 電話で名乗りもせずに， \n 「ちょっと無料で●●を教えて下さい。」 \n っていわれることがある。 \n \n 人助けだと思って，基本的には答えているが，この人達は，きっとコンビニやレストランでも， \n 「ちょっと無料でお弁当１つ下さい。ワインを１杯下さい。」 \n って，お願いしているのだろう。

　改行を入れて2分割でツイートしました。まるで漫画のようなツイートです。これほどのものは最近見かけていませんが、少年時代に読んだ小林よしのり、の「東大一直線」のような漫画の世界観がリアルに蘇ってきました。世紀的な大発見だとも思いました。

▶（046／341） TW fukazawas（深澤諭史） 日時： 2015-03-29 08:30:00 +0900 URL： https://twitter.com/fukazawas/status/581961663198400512
{% tweet 581961663198400512 %}
> ①無料で，②公開されていて，③短い文章であっても，著作権も著作者人格権もあるわけでだから，取り扱いには慎重な注意が必要。 \n \n 無断で複製すれば民事・刑事の責任を問われるし，特に，その著作者を中傷する目的があった場合，法的紛争を誘発することになる。

　先日視聴したところのAbemaPrimeでも、ネット記事の引用を違法と断定するような深澤諭史弁護士の発言があり、隣あたりにいたITジャーナリストのような人が慌てた感じで、URLを使った引用はOKなどとフォローを入れていました。巻き添えを恐れた感じでもありました。

　時刻は12月20日0時43分です。日付が変わっているのでややこしいのですが、一昨日あたりも深澤諭史弁護士はAbemaPrimeに出演をしていたようです。しかし、その番組が見当たらず、少し調べても見つかりませんでした。

* 「昨日も出演させていただきました！（・∀・）」という深澤諭史弁護士のツイート　AbemaPrime　#アベプラ　

```
このユーザーはTwilogに登録されていません

最新100件のツイートのみを表示しています。
自動的にツイートを記録するには、こちらから新規登録してください。
現在表示されているツイートは、取得してから1時間だけTwilogのサーバに保持されます。最新のツイートを取得したいときは、右上の「最新の情報に更新する」ボタンを押してください。

［source：］深澤諭史(@fukazawas) - Twilog https://twilog.org/fukazawas
```

　相変わらず登録はなかった深澤諭史弁護士のTwilogのページです。このTwilogだとリツイートのURLが通常の元のツイートのURLではなく、リツイートしたアカウントのリツイートとしてURLを取得できます。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2018-12-20 00:54／2018-12-19 19:55 URL： https://twitter.com/kk_hirono/status/1075419063633862658 https://twitter.com/fukazawas/status/1075343771967967232
&twitter(1075419063633862658){theme:light}
> 昨日も出演させていただきました！ \n  （・∀・） https://t.co/MW8wBGKKxz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2018-12-20 00:54／2018-12-14 12:44 URL： https://twitter.com/kk_hirono/status/1075419088799772672 https://twitter.com/fukazawas/status/1073423415158042625
&twitter(1075419088799772672){theme:light}
> （・∀・）昨日のアベプラへの出演は実に楽しかった。 \n  （＾ω＾）色々と好評だったお！
◁◁◁
<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2018-12-20 00:55／2018-12-19 09:32 URL： https://twitter.com/kk_hirono/status/1075419301249671168 https://twitter.com/fukazawas/status/1075187083302465536
&twitter(1075419301249671168){theme:light}
> にしても、生放送は疲れるお（＾ω＾；；）
◁◁◁
<hr />

▷ リツイート→fukazawas（深澤諭史）＞karaabe10004（カラアゲという名の犬＠アベプラ用）｜2018/12/18 23:17／2018/12/18 22:33｜https://twitter.com/fukazawas/status/1075032362545700864 ／ https://twitter.com/karaabe10004/status/1075021342850727937
&twitter(1075032362545700864){theme:light}
> RT @karaabe10004: 腹黒弁護士ｗ　お金取ろうとかｗ #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞tomohop（とも）｜2018/12/18 23:17／2018/12/18 22:34｜https://twitter.com/fukazawas/status/1075032335790161922 ／ https://twitter.com/tomohop/status/1075021506634121216
&twitter(1075032335790161922){theme:light}
> RT @tomohop: 深澤弁腰士面白い！ #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞0macarons0（まかろんらすく）｜2018/12/18 23:17／2018/12/18 22:34｜https://twitter.com/fukazawas/status/1075032328160796674 ／ https://twitter.com/0macarons0/status/1075021549483085824
&twitter(1075032328160796674){theme:light}
> RT @0macarons0: やっぱり弁護士は敵に回さない方がいい(笑)
> #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞mukuri（／む／く／り／）｜2018/12/18 23:17／2018/12/18 22:35｜https://twitter.com/fukazawas/status/1075032316928352256 ／ https://twitter.com/mukuri/status/1075021745856294912
&twitter(1075032316928352256){theme:light}
> RT @mukuri: アベプラに深澤弁護士出ると期待値高い。面白い。  

▷ リツイート→fukazawas（深澤諭史）＞toron0123（toron0123）｜2018/12/18 23:17／2018/12/18 22:36｜https://twitter.com/fukazawas/status/1075032308191617025 ／ https://twitter.com/toron0123/status/1075021955340787712
&twitter(1075032308191617025){theme:light}
> RT @toron0123: 深澤先生、怖っ！
> 弁護士を怒らせると怖いということか…
> #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞RINKIRO（あんのーん）｜2018/12/18 23:17／2018/12/18 22:39｜https://twitter.com/fukazawas/status/1075032285274005505 ／ https://twitter.com/RINKIRO/status/1075022859922137088
&twitter(1075032285274005505){theme:light}
> RT @RINKIRO: 深澤ドットコム #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞WhiteKnight2036（🦕io🦖）｜2018/12/18 23:17／2018/12/18 22:40｜https://twitter.com/fukazawas/status/1075032273563484161 ／ https://twitter.com/WhiteKnight2036/status/1075022989400301573
&twitter(1075032273563484161){theme:light}
> RT @WhiteKnight2036: アベプラでキャラ立ちしてきた弁護士の深沢.com(笑)  

▷ リツイート→fukazawas（深澤諭史）＞karaabe10004（カラアゲという名の犬＠アベプラ用）｜2018/12/18 23:17／2018/12/18 22:42｜https://twitter.com/fukazawas/status/1075032248762560512 ／ https://twitter.com/karaabe10004/status/1075023550170390528
&twitter(1075032248762560512){theme:light}
> RT @karaabe10004: 深澤ドットコム利用しまくる小藪さんｗ #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞QECvjNnEudebEBR（ケン）｜2018/12/18 23:17／2018/12/18 22:44｜https://twitter.com/fukazawas/status/1075032198929997824 ／ https://twitter.com/QECvjNnEudebEBR/status/1075024051943297024
&twitter(1075032198929997824){theme:light}
> RT @QECvjNnEudebEBR: 深澤.com　の説明わかりやすい。
> これから弁護士ゲストは深澤,com　でお願いします。
> ＃アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞heMOAK5yA8e4n5J（実況用）｜2018/12/18 23:17／2018/12/18 22:47｜https://twitter.com/fukazawas/status/1075032186087063553 ／ https://twitter.com/heMOAK5yA8e4n5J/status/1075024796340039686
&twitter(1075032186087063553){theme:light}
> RT @heMOAK5yA8e4n5J: 深澤.comていう芸人さん
> わかりやすいわあー
> #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞0macarons0（まかろんらすく）｜2018/12/18 23:16／2018/12/18 22:47｜https://twitter.com/fukazawas/status/1075032175806836739 ／ https://twitter.com/0macarons0/status/1075024829755977729
&twitter(1075032175806836739){theme:light}
> RT @0macarons0: 深澤弁護士有能☆
> 説明が理路整然としてて分かりやすい！
> #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞RINKIRO（あんのーん）｜2018/12/18 23:16／2018/12/18 22:48｜https://twitter.com/fukazawas/status/1075032160153698304 ／ https://twitter.com/RINKIRO/status/1075025118680633347
&twitter(1075032160153698304){theme:light}
> RT @RINKIRO: 深澤ドットコム、Abema向きだな。地上波なら多分イラッとくるんだけど #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞speed_bird_1（ゆう）｜2018/12/18 23:16／2018/12/18 22:49｜https://twitter.com/fukazawas/status/1075032148501917696 ／ https://twitter.com/speed_bird_1/status/1075025183247818757
&twitter(1075032148501917696){theme:light}
> RT @speed_bird_1: 本日の教訓。
> 弁護士は自分の事件は自分でやらない❗
> #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞karaabe10004（カラアゲという名の犬＠アベプラ用）｜2018/12/18 23:16／2018/12/18 22:49｜https://twitter.com/fukazawas/status/1075032133347885057 ／ https://twitter.com/karaabe10004/status/1075025212469436417
&twitter(1075032133347885057){theme:light}
> RT @karaabe10004: 医者が教える健康法も医者は全くやらない理論と一緒やなｗ　弁護士も #アベプラ  

▷ リツイート→fukazawas（深澤諭史）＞tomohop（とも）｜2018/12/18 23:16／2018/12/18 22:52｜https://twitter.com/fukazawas/status/1075032101538263041 ／ https://twitter.com/tomohop/status/1075025907516026881
&twitter(1075032101538263041){theme:light}
> RT @tomohop: ほかのんと深澤さんのお天気コーナー見てみたい。 #アベプラ  

▶ ツイート％fukazawas（深澤諭史）％2018/12/18 21:24％ https://twitter.com/fukazawas/status/1075003990708957184
&twitter(1075003990708957184){theme:light}
> 楽屋なう（・∀・）  
▶

▶ ツイート％fukazawas（深澤諭史）％2018/12/18 20:40％ https://twitter.com/fukazawas/status/1074992787513200641
&twitter(1074992787513200641){theme:light}
> テレビ朝日の社屋ってかっこいいなぁ。
> （・∀・）  
▶

　それと思われるツイートとリツイートを深澤諭史弁護士のタイムラインから引用しましたが、これだけの数があっても出演したと思われる番組の内容やタイトルがまったく不明です。昨夜の段階では、他に検索をしても情報は見つかりませんでした。

　「深澤ドットコム」というのも出てきましたが、これもちょっと意味がわかりませんでした。深澤諭史弁護士に関しては深澤先生としてTwitterで検索した方が情報が見つかることもありますが、もちろん無関係の学校の先生のツイートも出てきます。

　#アベプラ についてはAbemaPrimeのことに間違いないと思います。調べて確認をしました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Abema_Prime（AbemaPrime【公式】） 日時：2018-12-20 01:07／2018-12-18 18:00 URL： https://twitter.com/kk_hirono/status/1075422291985555456 https://twitter.com/Abema_Prime/status/1074952579031822336
&twitter(1075422291985555456){theme:light}
> ＼今夜９時～／ \n   \n  ①〝海に浮く航空基地〟国が空母保有へ \n  　🔻持たないと言ってたのに…なぜ今？ \n  　🔻米にとってはメリット大？ \n   \n  ②大戸屋客離れ？#アベプラ で良さを再発見 \n  　🔻やよい軒大好き芸人と大戸屋ごはんを実食＆分析 \n   \n  ③世界最… https://t.co/ZW20HAo2XE
◁◁◁
<hr />

* 「深澤ドットコム」とは？　TwitterとGoogleで検索してみたが、深澤諭史弁護士とは結びつきを確認できず

[link:] » 深澤ドットコム - Twitter検索 https://t.co/nd6oDLDl37

<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 01:13／2018-12-20 01:12 URL： https://twitter.com/kk_hirono/status/1075423768997023744 https://twitter.com/s_hirono/status/1075423569163603969
&twitter(1075423768997023744){theme:light}
> 2018-12-20-011123_深澤ドットコム　-　Twitter検索.jpg https://t.co/25UYiKwa17
◁◁◁
<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 01:15／2018-12-20 01:15 URL： https://twitter.com/kk_hirono/status/1075424386323177473 https://twitter.com/s_hirono/status/1075424311400255488
&twitter(1075424386323177473){theme:light}
> 2018-12-20-011440_深澤ドットコム　-　Google　検索.jpg https://t.co/FFafKE1L7v
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 01:15／2018-12-20 01:15 URL： https://twitter.com/kk_hirono/status/1075424412210364417 https://twitter.com/s_hirono/status/1075424279238344704
&twitter(1075424412210364417){theme:light}
> 2018-12-20-011425_深澤ドットコム　-　Google　検索.jpg https://t.co/FMMlETzgtg
◁◁◁
<hr />

* #AbemaPrime【公式】　@Abema_Prime のTwitterアカウントから調べてみた深澤諭史弁護士の出演番組

　まずまとめ記事を制作しました。

```
［link：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＃AbemaPrime【公式】　@Abema_Prime＃のツイート／2018-11-30_2209〜2018-12-19_2335／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月20日01時17分 http：//hirono2014sk.blogspot.com/2018/12/abemaprimeabemaprime2018-11-3022092018.html
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
指定アカウントの最新199件のツイート
2018-11-30 22：09から199件：最新2018-12-19 23：35という範囲（19日1時間26分）の取得
===========================================================

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＃AbemaPrime【公式】　@Abema_Prime＃のツイート／2018-11-30_2209〜2018-12-19_2335／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月20日01時17分 http://hirono2014sk.blogspot.com/2018/12/abemaprimeabemaprime2018-11-3022092018.html
```

　そのままページのテキストを上記にコピペしましたが、改行を含め書式は見直した方がいいかなと思いました。さて、深澤諭史弁護士の関連していると思われるツイートを捜します。

　その前にAbemaPrimeのTwitter公式アカウントのプロフィールも掲載してご紹介しておきます。

```
AbemaPrime【公式】（Abema_Prime）のプロフィール情報（2018年12月20日01時17分13秒頃の取得）：
-----------------------------------------------------------
［name］ユーザ名称：AbemaPrime【公式】

［screen_name］ユーザ名：Abema_Prime

位置情報：

ユーザ説明：
「オトナの事情をスルーするニュース番組」AbemaPrime(アベマプライム)です。インターネットの報道番組だからこそできる独自の視点や情報量で〝今気になるニュース〟をお届けします！番組へのご意見やご要望などは #アベプラ まで📺 ※投稿している内容は、放送では予告なく変更することがございます。予めご了承ください。

ユーザのフォロワー数：9346

ユーザのフォロー数：1077

ユーザがTwitterに登録した日時：2016-03-15 01：48：58 UTC

ユーザの投稿ツイート数：162108

===========================================================

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＃AbemaPrime【公式】　@Abema_Prime＃のツイート／2018-11-30_2209〜2018-12-19_2335／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月20日01時17分 http://hirono2014sk.blogspot.com/2018/12/abemaprimeabemaprime2018-11-3022092018.html
```

　フォロワー数は9346と意外に多くなかったのですが、162108というツイート数には驚きました。よく見るとTwitterを開始した日の情報がないようです。これもAPIで一緒に取得できる情報であったように思います。いや、ありました。2016-03-15です。

　深澤諭史弁護士に直接関係なくても、気になったものは掲載してご紹介しておきたいと思います。社会的な影響のこともあります。

4件目 ￼戻る ツイート： Abema_Prime（AbemaPrime【公式】） 日時： 2018-12-19 19:29 URL： https://twitter.com/Abema_Prime/status/1075337211061489665 
{% tweet 1075337211061489665 %}
> ＼今夜のMCはカンニング竹山（@takeyama0330）／ \n \n ①ソフトバンク上場でスマホ→AIへ！？ \n 　🔻〝孫正義の元右腕〟が解説 \n \n ②寝屋川中１殺害事件で死刑判決 \n 　🔻極刑は必要？不要？ \n \n ③透過画像が数秒で作れる無料サービ… https://t.co/RnIkAShbZK 
　
　カンニング竹山というテレビの人は、もともと芸人なのかタレントなのかよくわからないのですが、このところテレビで見る機会は少なくなっています。それでも日付が変わっていますが昨日の19日のグッディには出演を見たように思います。

　あまり見ていなかった連続テレビ小説「花子とアン」で、カンニング竹山さんは地主の長者のような役柄を演じていたのも印象的でした。他にドラマでは見ていないような気がします。調べれば確認できる情報は出てくるでしょう。先を急いでいます。

7件目 ￼戻る ツイート： Abema_Prime（AbemaPrime【公式】） 日時： 2018-12-18 21:25 URL： https://twitter.com/Abema_Prime/status/1075004247748444160 
{% tweet 1075004247748444160 %}
> 小籔千豊「憲法９条があるから戦争はおきないってずっと言ってた人たちが、北朝鮮がミサイルを飛ばしてきたとき、みんな戦争になると言っていた。憲法９条があるからミサイル撃たないよ大丈夫だよって人はひとりもいなかった。だから、軍事力は必要だと思うけれど‥」＃アベプラ 

　小籔千豊というテレビの人は吉本新喜劇の芸人のようですが、ここ最近テレビで見ることは少なくなっている気がします。バイキングで番組の方針に納得できず降板したというような情報もありました。

```
　9月25日に放送された情報番組「バイキング」（フジテレビ系）にて、火曜レギュラーを務めていた小籔千豊が、番組を卒業することを発表した。小藪は約4年半にわたって同番組に出演していた。

「この日の番組の最後、MCの坂上忍が、25日をもって小藪が番組を卒業すると報告しました。それを受けて小藪は、世間を騒がせている作曲家・平尾昌晃氏の遺産トラブルの話題に引っ掛けて、『お金を残さないような人生を送りたいと思います』とコメント。スタジオの笑いを誘っていました」（テレビ誌記者）

［source：］坂上忍と対立！？小籔千豊が「バイキング」をクビになった裏事情 | アサ芸プラス https://www.asagei.com/excerpt/113074
```

　確認も必要なので調べたのですが、今年の9月25日の放送を最後に降板されたようです。意外に最近のことなのでちょっと驚きました。先を急いでいるので記事の内容は全て読んではいません。

8件目 ￼戻る ツイート： Abema_Prime（AbemaPrime【公式】） 日時： 2018-12-18 18:00 URL： https://twitter.com/Abema_Prime/status/1074952579031822336 
{% tweet 1074952579031822336 %}
> ＼今夜９時～／ \n \n ①〝海に浮く航空基地〟国が空母保有へ \n 　🔻持たないと言ってたのに…なぜ今？ \n 　🔻米にとってはメリット大？ \n \n ②大戸屋客離れ？#アベプラ で良さを再発見 \n 　🔻やよい軒大好き芸人と大戸屋ごはんを実食＆分析 \n \n ③世界最… https://t.co/ZW20HAo2XE 

　18日のツイートで今夜9時とあるので、日付が変わった前日が19日で、その前日となれば、深澤諭史弁護士の出演日と一致するように思われます。3つの項目が出ていますが、深澤諭史弁護士が弁護士として解説する内容なのか少し疑問です。

　深澤諭史弁護士のツイートでは、番組に出演するためテレビ朝日に行ったというツイートがありました。前回、深澤諭史弁護士の放送をみた番組は、テレビ朝日の女子アナが司会者のような感じで出演をしていました。

　そのテレビ朝日の女子アナについては名前も覚えていませんが、そのAbemaPrimeの放送の初めの方で、なにやら「リーガルV」のドラマに出演したと聞こえるような発言があり気になっていました。調べてはいませんし、他に情報も見てはいません。

9件目 ￼戻る ツイート： Abema_Prime（AbemaPrime【公式】） 日時： 2018-12-18 15:26 URL： https://twitter.com/Abema_Prime/status/1074913693643636736 
{% tweet 1074913693643636736 %}
> 【村本が聞いた生の声…基地問題に今必要なこと】 \n \n 村本(@WRHMURAMOTO)「米兵によるレイプや殺人が起こっても回転寿司の皿のようにすぐに違うニュースへと流れてしまう」 \n \n 宇野(@wakusei2nd)「沖縄に負担を強いてい… https://t.co/j2qUj8x8AY 

```
@WRHMURAMOTO
ひっそりと聴ける会員制ラジオ始めました「THE SECRET COMEDY SHOW」毎週日曜深夜０時開演 https：//bookstand.webdoku.jp/melma_box/page.php?k=wrhmuramoto …英語勉強してます。発音の先生探し中。

東京
instagram.com/p/BfxLFnNFQ_Y/
2010年6月に登録
誕生日： 11月25日

［source：］村本大輔(ウーマンラッシュアワー)(@WRHMURAMOTO)さん | Twitter https://twitter.com/WRHMURAMOTO?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1074913693643636736&ref_url=http%3A%2F%2Fhirono2014sk.blogspot.com%2F2018%2F12%2Fabemaprimeabemaprime2018-11-3022092018.html
```

　村本という名前を見て、同じAbemaPrime公式のタイムラインで、前にそれらしい情報を見かけていたので、そうだろうと思っていたのですが、ツイートに含まれたメンションでTwitterアカウントが確認でき、やはり同一人物でした。

　なにかネットで炎上騒ぎのようなものがあり、そのあとテレビでまったく姿を見かけなくなっていました。一時期は弁護士のタイムラインでも批判の対象のようなかたちでツイートを見かけていたことがありました。それも、だいぶん前のことだと思います。

11件目 ￼戻る ツイート： Abema_Prime（AbemaPrime【公式】） 日時： 2018-12-17 22:54 URL： https://twitter.com/Abema_Prime/status/1074664043888013312 
{% tweet 1074664043888013312 %}
> 乙武洋匡（@h_ototake） \n 「ウィルチェアーラグビーというこんなに面白いスポーツを障害者にだけ独占させてたらいけないと思うんですよ」#アベプラ 

　乙武洋匡さんもテレビでは姿も話題もみかけなくなり、忘れかけていた人でした。あまり良くはしらないですが、頭がよく面白い話をしそうな人なので、マイペースのラジオの司会者の方が向いているのかもしれません。なんとなくの感想です。

13件目 ￼戻る ツイート： Abema_Prime（AbemaPrime【公式】） 日時： 2018-12-17 22:21 URL： https://twitter.com/Abema_Prime/status/1074655855784603648 
{% tweet 1074655855784603648 %}
> 宇野常寛（@wakusei2nd） \n 「沖縄だけに負担を押し付けているのは明らか」「基地・原発がないと食えないのは事実だ。だからこそそれらに頼らない経済を持続的に育てていこうという議論がおこなわれないと意味がない」#アベプラ 

　さきほど「宇野」という略称だけが出ていて、元警察官で職務質問を専門とされていたTwitterアカウントの方かとも少し思ったのですが、違っていたようです。富田林警察署の逃走事件でも弁護士アカウントらにこれでもかと叩かれていました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「宇野博幸」の検索結果 - Twilog https://t.co/PPqLgch8pr

<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-20 02:01／2018-10-02 15:28 URL： https://twitter.com/kk_hirono/status/1075436016071192577 https://twitter.com/hirono_hideki/status/1047010347146760192
&twitter(1075436016071192577){theme:light}
> 職務質問の指導者、元警察官の宇野博幸氏に対する弁護士らの反応：富田林警察署の被疑者逃走事件／8月12日の逃走事件発生当時／佐藤大和弁護士のTwitterでの反応 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/iw21jStqDa
◁◁◁
<hr />

```
▶ ツイート％O59K2dPQH59QEJx（ピピピーッ）％2018/08/15 11：15％ https：//twitter.com/O59K2dPQH59QEJx/status/1029552007609110528

> 今テレビに出ている自称犯罪ジャーナリストの小川泰平氏によると「お盆の夜に弁護士が接見をするのは不自然」だそうです。 
▶

［source：］職務質問の指導者、元警察官の宇野博幸氏に対する弁護士らの反応：富田林警察署の被疑者逃走事件／8月12日の逃走事件発生当時／佐藤大和弁護士のTwitterでの反応 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/entry/2018/10/02/134721#mark
```

　10日ほど前になりますが、以前よくテレビで見ていた元警察官の犯罪ジャーナリストの人の姿が、テレビでさっぱり見かけなくなったと気が付き、気になっていたのですが、名前が思い出せず、すぐに調べることもできませんでした。小川泰平氏でした。

14件目 ￼戻る ツイート： Abema_Prime（AbemaPrime【公式】） 日時： 2018-12-17 21:25 URL： https://twitter.com/Abema_Prime/status/1074641797492617216 
{% tweet 1074641797492617216 %}
> 【札幌・爆発事故】 \n 一日経った被害の状況は？ \n \n #アベプラ で生放送中！ 

24件目 ￼戻る ツイート： Abema_Prime（AbemaPrime【公式】） 日時： 2018-12-13 21:34 URL： https://twitter.com/Abema_Prime/status/1073194560229072896 
{% tweet 1073194560229072896 %}
> 深澤弁護士 \n 「他のまとめサイトにも損害賠償の可能性がある」 \n \n ”転載にも表現責任” \n まとめサイトに「冬の時代」到来‥🤔？ \n ＃アベプラ で詳しく解説中！ 

　ようやく出てきました。深澤諭史弁護士の名前を含む番組紹介のツイートです。その後にも深澤諭史弁護士の出演した番組があるようなのですが、ここまでタイムラインを遡ってきても、それらしいものは見つかりませんでした。

　ちょっとわかりづらいのですが、放送日時の情報が見当たらず、よくみるとハッシュタグ以外のリンクはないようです。

　リツイートになっていたとも思いますが、このAbemaPrime公式アカウントのツイートにあるリンクを開いたことで、動画の視聴が出来たように思います。

　ちょっと奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のTwilogの方で調べて確認をしておきたいと思います。12月13日ということで、そこから調べてみます。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年12月13日 - Twilog https://t.co/hrGZvVXysT

<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-20 02:20／2018-12-13 22:24 URL： https://twitter.com/kk_hirono/status/1075440809871175680 https://twitter.com/hirono_hideki/status/1073206923107790851
&twitter(1075440809871175680){theme:light}
> 「誰より腹黒い男では」『リーガルV』8話、向井理が初めて見せる裏の顔に視聴者驚愕｜サイゾーウーマン https://t.co/iKm71dzMex \n  　今日は１３日だったらしい、１４日と思っていた気がする。
◁◁◁
<hr />

　やはりリーガルVの最終回があった日のことです。気がついたのですがリーガルVの放送は木曜日の夜だったので、今日でちょうど一週間ということになります。

　深澤諭史弁護士が出演したAbemaPrimeの放送についてのツイートが見当たりませんでした。思い出したのですが、メモを兼ねたツイートをするのを忘れ、気がついた数時間後にやったように思います。0時を過ぎて日付が変わっていたようにも思います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年12月14日 - Twilog https://t.co/QXeTr9j2a0

<hr />

　見つかったのですが、リツイート済みだった可能性があります。この12月14日は、東名高速あおり運転夫婦死亡事故で危険運転致死傷罪を認め懲役18年の判決が出た日でした。以前は、赤穂浪士の討ち入りで決まったように「忠臣蔵」のドラマがテレビで放送されていた日かと思います。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/12/14 16:43％ https://twitter.com/hirono_hideki/status/1073483657136893952
&twitter(1073483657136893952){theme:light}
> AbemaPrime まとめサイトにも表現責任！賠償判決で〝冬の時代〟へ！？ | 【AbemaTV】国内最大の無料インターネットテレビ局 https://t.co/JoVIlavlIJ  
▶

　ツイートをよくみると16時43分という夕方早めの時間です。夜の遅い時間になって視聴したものかと思っていました。

　あるように思っていたのですが、AbemaPrime公式のツイートのリツイートというのはやってきなかったようです。あるいは告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントでやっていたことかもしれません。確認します。

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/2018年12月14日 - Twilog https://t.co/0HQFvu6ZYt

<hr />

　確認してみましたが、自分の他２つのアカウントのツイートのリツイート以外のリツイートというのは１つも見当たりませんでした。非常上告-最高検察庁御中_ツイッター（@s_hirono）にはスクリーンショットがあるかもしれません。

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/2018年12月14日 - Twilog https://t.co/S0CH8GuHk0

<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:38／2018-12-14 22:14 URL： https://twitter.com/kk_hirono/status/1075445324691386368 https://twitter.com/s_hirono/status/1073566777949343744
&twitter(1075445324691386368){theme:light}
> 2018-12-14-220933_深澤諭史のリツイート（村本大輔（ウーマンラッシュアワー）　認証済みアカウント@WRHMURAMOTO）：政府が強行で沖縄の辺野古の海に大量.jpg https://t.co/xk3EhmY00P
◁◁◁
<hr />

　忘れていたスクリーンショットですが、深澤諭史弁護士と村本大輔（ウーマンラッシュアワー）は、番組などを通じて知り合いである可能性もあるのでは、という考えが頭に浮かんだ上記のリツイートです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:41／2018-12-14 22:12 URL： https://twitter.com/kk_hirono/status/1075446012259356672 https://twitter.com/s_hirono/status/1073566388223004672
&twitter(1075446012259356672){theme:light}
> 2018-12-14-211518_落合洋司🇯🇵「ニチョウー東京地検特捜部特別分室」1月4日発売！のリツイート（cnn_co_jp　認証済みアカウント@cnn_co_jp）：.jpg https://t.co/HahZNSKUUP
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:41／2018-12-14 22:12 URL： https://twitter.com/kk_hirono/status/1075446034925383680 https://twitter.com/s_hirono/status/1073566356430180352
&twitter(1075446034925383680){theme:light}
> 2018-12-14-210051_堀江貴文氏、戦慄！　検察の取り調べ、リアル過ぎ！　落合洋司弁護士の本.jpg https://t.co/lsI5i5xpjN
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:41／2018-12-14 22:12 URL： https://twitter.com/kk_hirono/status/1075446062314250240 https://twitter.com/s_hirono/status/1073566324792614912
&twitter(1075446062314250240){theme:light}
> 2018-12-14-205812_落合洋司（🇯🇵「ニチョウー東京地検特捜部特別分室」発売！）：@yjochi9時間9時間前手前味噌ながら、拙著「ニチョウー東京地検特捜部特別.jpg https://t.co/Cho7e8ElRg
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:41／2018-12-14 22:12 URL： https://twitter.com/kk_hirono/status/1075446135169343488 https://twitter.com/s_hirono/status/1073566291510812677
&twitter(1075446135169343488){theme:light}
> 2018-12-14-205451_落合洋司（🇯🇵「ニチョウー東京地検特捜部特別分室」発売！）：@yjochi6時間6時間前落合洋司被告人は控訴するだろうから、この判決が高裁.jpg https://t.co/MJfoPWaScK
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:42／2018-12-14 22:11 URL： https://twitter.com/kk_hirono/status/1075446160368660480 https://twitter.com/s_hirono/status/1073566260355420160
&twitter(1075446160368660480){theme:light}
> 2018-12-14-205426_落合洋司（🇯🇵「ニチョウー東京地検特捜部特別分室」発売！）：@yjochi出版記念会を、政治家も招いて大々的にやるよう勧めてくれる人もいる.jpg https://t.co/owEMjqKFUN
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:42／2018-12-14 22:11 URL： https://twitter.com/kk_hirono/status/1075446203242823680 https://twitter.com/s_hirono/status/1073566228537462784
&twitter(1075446203242823680){theme:light}
> 2018-12-14-205302_落合洋司（🇯🇵「ニチョウー東京地検特捜部特別分室」発売！）：@yjochi3時間3時間前この人はなかなか難しい立場っぽいな。→「西川社長も.jpg https://t.co/dhIMTGwLdV
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:42／2018-12-14 22:11 URL： https://twitter.com/kk_hirono/status/1075446268212666369 https://twitter.com/s_hirono/status/1073566196975362049
&twitter(1075446268212666369){theme:light}
> 2018-12-14-205006_落合洋司🇯🇵「ニチョウー東京地検特捜部特別分室」1月4日発売！のリツイート（YosukeOKADA　@ellhgj）：愛媛県宇和島市は、大.jpg https://t.co/YVW3pt1yti
◁◁◁
<hr />

　捜しているスクリーンショットではありませんが、上記の７つのスクリーンショットにあるのも、記録的価値のあるなかなかの発見でした。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:44／2018-12-14 15:16 URL： https://twitter.com/kk_hirono/status/1075446728709496832 https://twitter.com/s_hirono/status/1073461824018833411
&twitter(1075446728709496832){theme:light}
> 2018-12-14-135317_AbemaPrime　まとめサイトにも表現責任！賠償判決で〝冬の時代〟へ！？　｜　【AbemaTV】.jpg https://t.co/nx9cFUxw6Z
◁◁◁
<hr />

　出てきました。ツイートの投稿時刻は15時16分となっていますが、スクリーンショットの撮影時刻は13時53分となっていて、一連のスクリーンショットとしての記録としては締めくくりというか最後のものとなっているようです。別にスマホの写真で記録したものもあります。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:47／2018-12-14 15:16 URL： https://twitter.com/kk_hirono/status/1075447585706405888 https://twitter.com/s_hirono/status/1073461727411335168
&twitter(1075447585706405888){theme:light}
> 2018-12-14-135026_深澤諭史のリツイート（pico。　@pico_happy）：きょうのふかわさんの好物は深澤弁護士！＃アベプラ.jpg https://t.co/MpQr5TSOlD
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 02:47／2018-12-14 15:16 URL： https://twitter.com/kk_hirono/status/1075447605226700801 https://twitter.com/s_hirono/status/1073461694007922690
&twitter(1075447605226700801){theme:light}
> 2018-12-14-134927_深澤諭史のリツイート（サイ太　@uwaaaa）：非弁を斬っているだけで小川彩佳と共演した弁護士.jpg https://t.co/TNlzEACyH9
◁◁◁
<hr />

　一週間前のことなのに忘れていたことが多く、スクリーンショットに救われたと思いました。深澤諭史弁護士のタイムラインでの刑裁サイ太のツイートのリツイートを見たのが、最初の方のきっかけだったと今になって思い出しました。これは記憶喚起の訓練にもなります。

　おまけのようなかたちになりますが、次のスクリーンショットにある内容もなかなかのものです。リツイートは次回のために残しておこうと思います。

▶ ツイート％s_hirono（非常上告-最高検察庁御中_ツイッター）％2018/12/14 15:16％ https://twitter.com/s_hirono/status/1073461631500181504
&twitter(1073461631500181504){theme:light}
> 2018-12-14-134357_深澤諭史のリツイート（新谷泰真　@yasumasa218）：私もない。金は出さないが魂を売ってくれ、体を売ってくれみたいな話はたまにある。.jpg https://t.co/YmMcl5BM2q  
▶

　時刻は11時07分です。3時過ぎまで起きていたことは憶えています。目が覚めて起きると外があまりにも静かだったので、7時頃かと思ったのですが、少しして時計を見ると10時30分となっていました。

　テレビをつけて「ひるおび」をみていると、今日も独自色のある意外な情報が出てきた。三波春夫の有名は「お客様は神様です」という言葉のことですが、次はこれに関連して思い出すことなどを記述したいと思います。

