#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "参考資料／弁護士業界の現状／深澤諭史弁護士のリツイート／今の法テラスの地獄を見ると、「国が報酬決定権を握る」ことの恐ろしさを感じるので、そんな方向には全く進んで欲しくない（中村憲昭弁護士）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-11-14 10:30:22 +0900
FILE_NAME: 2018-11-14-103022_今の法テラスの地獄を見ると、「国が報酬決定権を握る」ことの恐ろしさを感じるので、そんな方向には全く進んで欲しくない（中村憲昭弁護士）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  深澤諭史弁護士 中村憲昭弁護士 法テラス 弁護士報酬
記事タイトル名の文字数：94　保存ファイル名の文字数：88

#contents

* 深澤諭史弁護士のリツイート

▷ リツイート→fukazawas（深澤諭史）＞take___five（中村剛（take-five））｜2018/11/13 23:16／2018/11/13 22:27｜https://twitter.com/fukazawas/status/1062348469250060290 ／ https://twitter.com/take___five/status/1062336253301932032
&twitter(1062348469250060290){theme:light}
> RT @take___five: 今日の弁護士の業務拡大の会合で、「弁護士にも健康保険類似の制度を」という意見が出た。自分も昔はそう思ってたけど、今の法テラスの地獄を見ると、「国が報酬決定権を握る」ことの恐ろしさを感じるので、そんな方向には全く進んで欲しくない。報酬決定権を手放…  

* スクリーンショットの記録

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-11-14 10:46／2018-11-14 10:42 URL： https://twitter.com/kk_hirono/status/1062522208000458752 https://twitter.com/s_hirono/status/1062521131037417473
&twitter(1062522208000458752){theme:light}
> 2018-11-14-100358_深澤諭史（@fukazawas）：ほんこれ。生活できる水準の報酬が確保されないと、どうにもならないですね。（・∀・；）.jpg https://t.co/p0pVw5Snft
◁◁◁
<hr />

* 深澤諭史弁護士の言及ツイートとタイムライン

▶ ツイート％fukazawas（深澤諭史）％2018/11/13 23:16％ https://twitter.com/fukazawas/status/1062348450430238720
&twitter(1062348450430238720){theme:light}
> ほんこれ。
> 生活できる水準の報酬が確保されないと、どうにもならないですね。
> （・∀・；） https://t.co/um0NkC3cl7  
▶

▷ リツイート→fukazawas（深澤諭史）＞yasumasa218（新谷泰真）｜2018/11/13 23:35／2018/11/13 23:26｜https://twitter.com/fukazawas/status/1062353328233865216 ／ https://twitter.com/yasumasa218/status/1062350937946152963
&twitter(1062353328233865216){theme:light}
> RT @yasumasa218: 隣の芝生は青く見えるし、メリットばかり目について、表裏一体のデメリットが目に付かないのはよくあること。 https://t.co/PrFCpI7Y8m  

▷ リツイート→fukazawas（深澤諭史）＞eru19721103（小西　憲臣）｜2018/11/13 23:35／2018/11/13 23:21｜https://twitter.com/fukazawas/status/1062353334101635072 ／ https://twitter.com/eru19721103/status/1062349684969074689
&twitter(1062353334101635072){theme:light}
> RT @eru19721103: 「弁護士にも健康保険類似の制度を」って言ってる人は、一度、保険医・保険薬剤師の監査に帯同することをおすすめします。厚労省に睨まれてしまうと、理不尽な言いがかりをつけられてお取り潰しにあいます。 https://t.co/xIQXXblYdr  

* Twitterをやっている弁護士の法テラスに対する不満

　弁護士の法テラスに対する不満というのは、これまでも繰り返し目にしてきました。そのほとんどはTwitterのツイートですが、例外を除き弁護士に限らず、ブログの記事というのは見かけることも少なくなっているので、主たる情報源ということにもなるかと思います。

　なお、上記の例外というのは落合洋司弁護士（東京弁護士会）のブログや、３，４ヶ月ほど前に初めたと思われる深澤諭史弁護士のブログがあります。他に郷原信郎弁護士のブログもありますが、同じ内容をニュースサイトのようなものに転載することも多いようです。

　郷原信郎弁護士に関しては、昨夜から読み続けている記事があります。これまでも長文の記事を見てきましたが、今回のはとりわけ長いようです。ずいぶん読んだつもりですが、スクロールの位置を見ると、まだ半分いくかいかないぐらいです。

[link:]  企業を蝕む「第三者委員会」の“病理”：横行する「第三者委員会ビジネス」 – アゴラ http://agora-web.jp/archives/2035573.html

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-11-14 11:18／2018-11-14 11:17 URL： https://twitter.com/kk_hirono/status/1062530189773561856 https://twitter.com/s_hirono/status/1062530028628402176
&twitter(1062530189773561856){theme:light}
> 2018-11-14-111736_もともと、第三者委員会による調査は、任意の協力によるヒアリングが中心であり、不利益供述を引き出して事案の真相を解明する上で限界があった。それ.jpg https://t.co/CPeaHxW2P1
◁◁◁
<hr />

　弁護士による「第三者委員会」というのも社会問題のテーマとしてかねて関心を持ってきたところであり、昨日は日大の危険タックル問題でも、警視庁が見解を示し書類送検したというニュースがあり、より気にかけていたところです。できれば、郷原信郎弁護士のことも取り上げたいです。

　弁護士による法テラスに対する不満というのは「クソテラス」という言葉で表現されることもありました。最近は見かけていないですが、「法寺」という言葉で揶揄するようなツイートも散見され、成仏理論とともに不当な受難者と位置づけているようです。

　弁護士による法テラスに対する不満というのは、具体的に「報酬加算」の不適用というかたちで見てきたようにも思います。一つだけブログだったと思いますが、さほど不満をいうほどでもないと割り切り、従来の７割程度の報酬で安定感もあるというのも見かけました。

　法テラスと国選弁護については、とりわけ弁護士の不満のはけ口としてツイートを見かけることがほとんどですが、実際にどれだけ不当な扱いを受けているかとなると、外部からはうかがい知れない面が大きいように考えます。

▶ ツイート％take___five（中村剛（take-five））％2018/11/13 22:27％ https://twitter.com/take___five/status/1062336253301932032
&twitter(1062336253301932032){theme:light}
> 今日の弁護士の業務拡大の会合で、「弁護士にも健康保険類似の制度を」という意見が出た。自分も昔はそう思ってたけど、今の法テラスの地獄を見ると、「国が報酬決定権を握る」ことの恐ろしさを感じるので、そんな方向には全く進んで欲しくない。報酬決定権を手放すなんて、自殺行為だよ。  
▶

　あらためて中村憲昭弁護士のツイートを見てみますと、「今日の弁護士の業務拡大の会合で、「弁護士にも健康保険類似の制度を」という意見が出た。」とあります。業務拡大と健康保険類似制度の関連性が部外者にはわかりづらいです。

　国選刑事弁護と医療保険制度を同じようにせよ、というご意見は小倉秀夫弁護士のツイートなどで見かけてきました。医療と弁護を同格の有益性の水準と捉える傾向性は、深澤諭史弁護士にも強く見られてきたもので、度々ご紹介してきた盲腸のツイートもその１つです。

* 「盲腸」をキーワードに含む深澤諭史弁護士のツイート

[link:] » "盲腸" from:fukazawas - Twitter検索 https://t.co/nslCOx1hxb

▶ ツイート％fukazawas（深澤諭史）％2016/05/23 11:32％ https://twitter.com/fukazawas/status/734572617651347459
&twitter(734572617651347459){theme:light}
> 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。  
▶

▶ ツイート％fukazawas（深澤諭史）％2018/06/22 08:52％ https://twitter.com/fukazawas/status/1009947234241134592
&twitter(1009947234241134592){theme:light}
> 病院に行って，「盲腸みたいなんですけれども，盲腸手術って簡単なんでしょ？だから，お金ももったいないし，自分でやってみようと思うんスけれども，やり方，教えてもらえます？」って話ですね。
> （・∀・；） https://t.co/QO529zyprH  
▶

▶ ツイート％fukazawas（深澤諭史）％2017/09/02 15:48％ https://twitter.com/fukazawas/status/903872305301831680
&twitter(903872305301831680){theme:light}
> そして，「簡単！誰でも，自分で出来る盲腸手術！」とか言い出す人とか，「盲腸手術は自分で簡単にできます。やり方は◯◯するだけ！」とかいうツイートがＲＴされまくることも基本的にはないが，法律の世界で似た様なことは山ほどある。
> https://t.co/ilKWmYIxYi  
▶

▶ ツイート％fukazawas（深澤諭史）％2017/09/02 15:48％ https://twitter.com/fukazawas/status/903872305301831680
&twitter(903872305301831680){theme:light}
> そして，「簡単！誰でも，自分で出来る盲腸手術！」とか言い出す人とか，「盲腸手術は自分で簡単にできます。やり方は◯◯するだけ！」とかいうツイートがＲＴされまくることも基本的にはないが，法律の世界で似た様なことは山ほどある。
> https://t.co/ilKWmYIxYi  
▶

▶ ツイート％fukazawas（深澤諭史）％2016/09/13 12:42％ https://twitter.com/fukazawas/status/775540241495040000
&twitter(775540241495040000){theme:light}
> 盲腸の手術をやるのでくじ引きで選ばれた医療員が執刀に参加
> 医療員「うーん，間違ったかな？」
> #もし医療で平成の司法改革をやったら  
▶


▶ ツイート％fukazawas（深澤諭史）％2016/09/13 12:42％ https://twitter.com/fukazawas/status/775540241495040000
&twitter(775540241495040000){theme:light}
> 盲腸の手術をやるのでくじ引きで選ばれた医療員が執刀に参加
> 医療員「うーん，間違ったかな？」
> #もし医療で平成の司法改革をやったら  
▶

* 気になる、「今の法テラスの地獄を見ると、「国が報酬決定権を握る」ことの恐ろしさを感じるの」というツイートの「地獄」の内容

▶ ツイート％take___five（中村剛（take-five））％2018/11/13 22:27％ https://twitter.com/take___five/status/1062336253301932032
&twitter(1062336253301932032){theme:light}
> 今日の弁護士の業務拡大の会合で、「弁護士にも健康保険類似の制度を」という意見が出た。自分も昔はそう思ってたけど、今の法テラスの地獄を見ると、「国が報酬決定権を握る」ことの恐ろしさを感じるので、そんな方向には全く進んで欲しくない。報酬決定権を手放すなんて、自殺行為だよ。  
▶

　深澤諭史弁護士のタイムラインで、この「地獄」を含むツイートを見かけた少し前、別の弁護士のタイムラインでも「地獄」を含む気になるツイートを見かけていました。ブロックされている京都弁護士会の副会長のアカウントです。

▶ ツイート％akishigemakoto（弁護士秋重実）％2018/11/13 23:21％ https://twitter.com/akishigemakoto/status/1062349682871959552
&twitter(1062349682871959552){theme:light}
> 地獄の蓋が開きました
> 
> 「ババアはいらねぇ」「死んじまえ」　ディズニーランドの“キャラクター出演者”がパワハラ巡り訴訟　原告が「ゲストの夢最優先してきたが限界」と涙の訴え（ねとらぼ） - Yahoo!ニュース… https://t.co/ffTqFIfr9x  
▶

[link:] » 弁護士秋重実さんのツイート: "地獄の蓋が開きました 「ババアはいらねぇ」「死んじまえ」　ディズニーランドの“キャラクター出演者”がパワハラ巡り訴訟　原告が「ゲストの夢最優先してきたが限界」と涙の訴え（ねとらぼ） - Yaho… https://t.co/f0shemjzT2

　この秋重実弁護士のツイートについても、単独の項目として取り上げておきたいところです。昨日になるかと思いますが、ディズニーランドの訴訟は法廷の様子を含め、繰り返しテレビで見かけています。今日の午前中の情報番組でも見かけていました。

　東京ディズニーランドで思い出すのは、東日本大震災の時の対応が高く評価されていたことです。同じ日になるかと思いますが、昨日は久兵衛という有名寿司店とホテルオークラの訴訟も繰り返しテレビで取り上げられていました。

　一つだけテレビの報道で、見たことのある高齢の寿司職人の姿をみたので、ああ、あの人物のいる寿司店だったのかと理解ができました。これも調べた結果を含め、取り上げておきたいと思います。

　時刻は１２時３０分です。ちょうど前行を書き終えたようなタイミングで、テレビのバイキングで司会者の坂上忍さんの声で、次は久兵衛・・・などという声が聞こえ、CMに入ったところです。

　時刻は１２時３９分になっています。バイキングで説明をみていると問題の理解が進みました。アーケード街という言葉が出ていたので、横丁の商店街の一角か地下街のようなものを想像していたのですが、実際はツインタワーの別棟で同じ４Fということのようです。

　この「すし久兵衛」のニュースについては、昨日、落合洋司弁護士（東京弁護士会）の気になるツイートを見かけていました。気になったものをいちいち取り上げるわけにもいかないと考えていたのですが、他の問題との関連性の１つとして重視しておきたいとも思います。

▷ リツイート→fukazawas（深澤諭史）＞yasumasa218（新谷泰真）｜2018/11/13 23:35／2018/11/13 23:26｜https://twitter.com/fukazawas/status/1062353328233865216 ／ https://twitter.com/yasumasa218/status/1062350937946152963
&twitter(1062353328233865216){theme:light}
> RT @yasumasa218: 隣の芝生は青く見えるし、メリットばかり目について、表裏一体のデメリットが目に付かないのはよくあること。 https://t.co/PrFCpI7Y8m  

　上記は再掲になりますが、深澤諭史弁護士がリツイートした新谷泰真弁護士のツイートです。新谷泰真弁護士といえば、老舗弁護士法律事務所という印象の強い櫻井光政弁護士との関係も考えさせられるものです。

　時刻は１２時５３分です。炊飯器のスイッチを入れ忘れていたことに気が付きました。あまりないミスです。

　新谷泰真弁護士と櫻井光政弁護士についても、前からしっかり取り上げておきたいと考えていました。本件告訴事件と共通する問題や事実関係があって、今後の対応についても参考になるところが大きいと考えています。事実というのは国選弁護人となった山口治夫弁護士のことです。

