#+TITLE: "参考資料／弁護士業界の現状／深澤諭史弁護士のリツイート／岡口基一裁判官に国会の裁判官訴追委員会が出頭要請、罷免を判断する弾劾裁判の検討"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-02-16 17:03:28 +0900
FILE_NAME: 2019-02-16-170328_岡口基一裁判官に国会の裁判官訴追委員会が出頭要請、罷免を判断する弾劾裁判の検討.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  深澤諭史弁護士のリツイート 岡口基一裁判官 弾劾裁判
記事タイトル名の文字数：67　保存ファイル名の文字数：61

#contents

* 深澤諭史弁護士のリツイートがきっかけで知った。岡口基一裁判官の罷免を検討する国会の裁判官訴追委員会が出頭要請というニュース、思わぬ展開
  :LOGBOOK:
  CLOCK: [2019-02-16 土 17:08]--[2019-02-17 日 00:20] =>  7:12
  :END:

＞＞＞2019-02-16（土曜日）17：08＿［これからの記述範囲の開始時刻］＞＞＞

▷ リツイート→fukazawas（深澤諭史）＞ginkanmuri_0202（銀冠　「グリーンブック」の公開を前倒しせよ）｜2019/02/16 11:05／2019/02/16 08:54｜https://twitter.com/fukazawas/status/1096591310205513728 ／ https://twitter.com/ginkanmuri_0202/status/1096558366724222976
&twitter(1096591310205513728){theme:light}
> RT @ginkanmuri_0202: 岡口Ｊの従前の投稿に関する好き嫌いや賛否はさておくとして、「ここまでやる話じゃないだろ」というのは相当数の業界関係者が考えるところなのではと思う。  

　深澤諭史弁護士がリツイートしたツイートのアカウントですが、深澤諭史弁護士のタイムラインでも初めて見たような気がしました。タイムラインを開いたところ法曹関係者の可能性があるようにも思いましたが、プロフィールにそれらしい記載はありませんでした。

　プロフィールの名前にある「グリーンブック」がなんだろうと思って調べたところ、３月１日に劇場公開になる映画のタイトルのようでした。１９６０年代のアメリカが舞台のアメリカ映画のようです。

```
人種差別が色濃く残る1960年代のアメリカ南部を舞台に、黒人ジャズピアニストとイタリア系白人運転手の2人が旅を続けるなかで友情を深めていく姿を、実話をもとに描いたドラマ。1962年、ニューヨークの高級クラブで用心棒として働くトニー・リップは、粗野で無教養だが口が達者で、何かと周囲から頼りにされていた。クラブが改装のため閉鎖になり、しばらくの間、無職になってしまったトニーは、南部でコンサートツアーを計画する黒人ジャズピアニストのドクター・シャーリーに運転手として雇われる。黒人差別が色濃い南部へ、あえてツアーにでかけようとするドクター・シャーリーと、黒人用旅行ガイド「グリーンブック」を頼りに、その旅に同行することになったトニー。出自も性格も全く異なる2人は、当初は衝突を繰り返すものの、次第に友情を築いていく。トニー役に「イースタン・プロミス」のビゴ・モーテンセン、ドクター・シャーリー役に「ムーンライト」のマハーシャラ・アリ。トニー・リップ（本名トニー・バレロンガ）の実の息子であるニック・バレロンガが製作・脚本を手がけ、父とドクター・シャーリーの友情の物語を映画化した。監督は、「メリーに首ったけ」などコメディ映画を得意としてきたファレリー兄弟の兄ピーター・ファレリー。アカデミー賞の有力な前哨戦として知られる第41回トロント国際映画祭で最高賞の観客賞、第76回ゴールデングローブ賞でも作品賞（コメディ／ミュージカル）を受賞した。

［source：］グリーンブック ： 作品情報 - 映画.com https://eiga.com/movie/89815/
```

　正確な年代は調べないとわからないですが、それに近い時代の黒人差別で思い出すのは「キング牧師」です。福井刑務所の受刑中、録画されたNHKスペシャルで知りました。殺害される数日前のキング牧師の映像があって、危機感と決意が伝わってきたのが印象的でした。

　今の時代、アメリカでも暗殺というニュースは聞かないですが、表現の自由を旗印に多くの弁護士の支持と評価を受けているという印象のある岡口基一裁判官が、裁判官の罷免となる弾劾裁判への手続きに入ったというのは、これも予想外で衝撃的なニュースです。

　個人的には、岡口基一裁判官の主義主張の表現方法はそれとして、Googleの画像検索を見ていると、そのまま公然わいせつ罪などで逮捕されても全く不思議に思わないのが率直なところです。公然わいせつ罪に告発というのは聞いたことがないですが、立場も身分保障の裁判官、一般ではないので。

　法律の勉強をしている頃、文章でのわいせつ表現で、有罪になった判例があるように見ました。理解は不十分だと自覚していましたが、確かそういう判例があったと思います。「チャタレイ夫人の恋人」と他にもあった気がします。これから調べて確認します。

```
チャタレー裁判【チャタレーさいばん】
D.H.ロレンスの《チャタレー夫人の恋人》を伊藤整が日本語訳した出版物が猥褻(わいせつ)文書であるか否かで争われた裁判。1950年訳者伊藤整と発行者小山久二郎が猥褻文書販売罪で起訴され，一審では小山だけが有罪。二審では両者とも罰金10万円。1957年最高裁が被告側上告を棄却して有罪が確定。これらの判決に現れた猥褻観などには数々の批判がなされたが，判例は以後の裁判を規制し，ようやく1969年《悪徳の栄え》事件の最高裁判決以後，見直しがなされるようになった。
→関連項目正木ひろし

［source：］チャタレー裁判(チャタレーさいばん)とは - コトバンク https://kotobank.jp/word/%E3%83%81%E3%83%A3%E3%82%BF%E3%83%AC%E3%83%BC%E8%A3%81%E5%88%A4-326215
```

　岡口基一裁判官の丸禁のような股間の部分だけ修正した写真は、最高裁の判例にあるような「性欲をいたずらに刺激」するものかどうかは疑問もありますが、一般のアカウントでも普通に目にすることのない写真が、裁判官の実名の検索結果に出てくるというのは、公然性は高そうです。

＜＜＜2019-02-17（日曜日）00：19＿［これまでの記述範囲の終了時刻］＜＜＜

