#+TITLE: "参考資料／刑事裁判／国選弁護人／「12人の国選弁護人に支払われた弁護士報酬は計4億5200万円」と知ったオウム真理教事件、教祖の刑事裁判と、ひな祭り"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-03-03 13:20:06 +0900
FILE_NAME: 2019-03-03-132006_「12人の国選弁護人に支払われた弁護士報酬は計4億5200万円」と知ったオウム真理教事件、教祖の刑事裁判と、ひな祭り.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  オウム真理教事件 国選弁護人 栃木女児殺害事件 弁護士報酬 冤罪 そこまで言って委員会NP
記事タイトル名の文字数：74　保存ファイル名の文字数：80

#contents

* そこまで言って委員会NP【弁護士のお仕事スペシャル】2019年3月3日（日）12時55分～15時00分の放送
  :LOGBOOK:
  CLOCK: [2019-03-03 日 13:27]--[2019-03-03 日 15:59] =>  2:32
  :END:

＞＞＞2019-03-03（日曜日）13：27＿［これからの記述範囲の開始時刻］＞＞＞

　台所で、残り野菜等の肉野菜炒めで昼食と洗い物を済まし、インスタントコーヒーを飲むためのお湯をヤカンで沸かしている間、郵便受けから北陸中日新聞をとってきて、事件面の見出しにざっと目を通した後、テレビ欄を見て少しすると、そこまで言って委員会NPの番組内容に気が付きました。

　この番組は通常13時30分からの放送開始ですが、よく見ると12時55分からの放送開始になっていることに気が付きました。テレビの方に向かうと、再起動していたパソコンのログイン画面の時計が13時04分となっていたと思います。すぐにテレビをつけ、チャンネルを合わせました。

　先日のベトナムでの米朝会談の映像が出てきたので、弁護士の特集前なのかと思ったのですが、トランプ大統領の元顧問弁護士がトランプ氏の不利な事実を証言したという話で、司会の辛坊治郎氏らは、守秘義務違反などと笑いながら批判をしていました。

```
ドナルド・トランプ米大統領の元顧問弁護士で、連邦議会への偽証、選挙資金法違反、脱税などの罪で禁錮3年の有罪判決を受けたマイケル・コーエン元弁護士（52）は、連邦議会で27日以降、大統領による犯罪行為について証言する見通しとなった。

［source：］トランプ氏の元顧問弁護士、大統領の「うそと人種差別といんちき」を議会証言へ - BBCニュース https://www.bbc.com/japanese/47385685
```

　上記の記事は2月27日付となっています。「証言する見通しとなった。」などと書いてあるので、実際に証言する前の報道のようですが、内容はテレビで見聞きしたのとほぼ同じではないかと思います。

　テレビはCMに入りましたが、5分か10分前に番組の議題は「遺産相続」になっています。その前の議題というかテーマはよく見ていなかったですが、番組は途中から録画を開始しました。

　午前中は、久しぶりに栃木女児殺害事件について調べていました。市町村名が変わる前は「今市小1女児殺害事件」などと呼ばれることが多い事件でした。今市市はその後、栃木市となっているようです。この事件は今日が、ひな祭りということで、2,3日前から考えるようになっていました。

　今年は3月1日に日弁連の総会があったようですが、1,2年前には3月3日に開催されていたと思いますし、その前の年は、東日本大震災のあった3月11日に開催されたように記憶しています。

```
個性派弁護士6人が緊急参戦!!裁判のウラ側から業界のトレンドまで徹底討論▽えん罪VSスゴ腕弁護士▽仁義なき企業買収戦争▽他人事ではない?遺産相続の“落とし穴”

出演者
司会
 辛坊治郎 渡辺真理 
パネリスト
 牛島信 長谷川幸洋 紀藤正樹 須田慎一郎 本村健太郎 萩谷麻衣子 嵩原安三郎 菅野朋子 竹田恒泰 丸田佳奈
番組内容
春の超拡大版!!理不尽な世の中と戦う「弁護士のお仕事」スペシャル  ◎世の弁護士は実際どのような仕事をしているのか?その“理想”と“現実”について個性派弁護士6人と徹底討論!!▽「無実の刑事被告人のえん罪を晴らす」 ▽「M&Aなどの実務を行う」 ▽「遺産相続など家族の問題を解決」 ▽「過払い金返還、B型肝炎など最近のトレンド」 など、気になる業務の難易度を判定!!

［source：］そこまで言って委員会NP - Yahoo!テレビ.Gガイド［テレビ番組表］ https://tv.yahoo.co.jp/program/55480117/
```

　テレビの番組に、弁護士ではなさそうな女性の姿があって気になっていたのですが、上記の引用したパネリストの中に、丸田佳奈という名前があって、少し見覚えがあったのですが、ネットで調べると、やはり女医の女性でした。そこまで言って委員会NP以外で見た記憶はありません。

```
丸田 佳奈（まるた かな、1981年8月20日 - ）は、産婦人科医・モデル・タレント。芸能事務所の株式会社スクロールに在籍してハーモニープロモーションと業務提携している。血液型はA型。

［source：］丸田佳奈 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%B8%E7%94%B0%E4%BD%B3%E5%A5%88
```

　来歴として「北海道網走市で生まれ、北海道北見北斗高校を経て日本大学医学部医学科を卒業し、産婦人科医として各種のマスメディアに登場している。」という記載があります。

　私の世代では、網走といえば網走刑務所で任侠映画の世界を思い出します。流氷が押し寄せる場所に近い寒さの厳しいところでもありますが、テレビの女性の姿とはイメージが一致しません。女性の産婦人科医というのも意外に感じました。

　3日ほど前になりますが、テレビのローカル番組で、珠洲市の産婦人科医が紹介されていました。午前中辺りに番組内容の紹介を見ていたのですが、その時は女性と思っていたのが男性だったようです。年齢は69歳となっていた気がしますが、能登町出身ということでした。

　常に出産等に備えた待機の状態で、フリーになるのは金沢の大学病院から交代の医師が来る月に1日だけという話でした。珠洲市総合病院で、その映像も出ていましたが、母親が平成21年8月31日から翌年1月の20日辺りまで入院していて、よく通った病院でもありました。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2019/02/28 18:55％ https://twitter.com/hirono_hideki/status/1101058337716633600
&twitter(1101058337716633600){theme:light}
> » 石川さんプライムニュース https://t.co/um5fr0HqCe
> ▽石テレ・北中共同企画「守る」珠洲で唯一の産婦人科ドクター密着  
▶

　北中というのは何のことだろうと思ったのですが、北陸中日新聞だったと思い出しました。しかし、北中という省略はこれまで見たことがなく、この短縮の必要が疑問に思いました。

　時刻は14時26分です。CMに入りましたが次のテーマは「過払い金」のようです。これまで観たところでも、弁護士業界の実情暴露のところがあって、参考になる番組内容です。CM前には総会屋という言葉が牛島信弁護士から出ていましたが、今では聞かなくなった言葉です。

　総会屋の頃は銀行の支店長が刺されるようなことがあった、という牛島信弁護士の解説でした。安藤健次郎さんが金沢信用金庫の銀行員で、定年退職してすぐに平成4年の傷害・準強姦被告事件があったという話を取調べ中、谷内孝志警部補に聞いたことを思い出しました。

　こまかく正確に言えば、定年退職してすぐ、という話は、金沢西警察署の取調べ中谷内孝志警部補に聞きましたが、職業について、金沢信用金庫と知ったのは、上告審で東京の国選弁護人、斐川雅文弁護士から郵送された供述調書に記載を見たものでした。

　平成4年4月1日の事件前、私が聞いていた安藤健次郎さんの職業は弁護士でした。被告発人多田敏明が私に吹き込んだ話です。これは金沢西警察署の留置係の藤井さんと坂井さんにも話、その場で弁護士名簿のようなものを取り出して確認したらしく、安藤という名前の弁護士はしないと言われました。

　時刻は14時59分です。そこまで言って委員会NPの放送が終わってCMに入りました。パソコンをしながらだったので、集中してみていないところもあったと思いますが、いろいろと勉強になりました。肝炎訴訟について、国がやるべき、という丸田佳奈さんの言葉がもっとも心に残りました。

　「そこまで言って委員会NP」ですが、ここ2,3年は余り視聴していません。最近は特に視聴することが少なくなっていました。「たかじんのそこまで言って委員会」の頃はよく視聴していましたが、羽咋市に住んでいる頃、当日、羽咋市に帰る時間を考えながらよくみていました。

［link：］ そこまで言って委員会NP - Twitter検索 https://twitter.com/search?q=%E3%81%9D%E3%81%93%E3%81%BE%E3%81%A7%E8%A8%80%E3%81%A3%E3%81%A6%E5%A7%94%E5%93%A1%E4%BC%9ANP&src=typd

　本日の番組内容に関するツイートは、ごく少ないですが、そこまで言って委員会NPの番組に関するツイート自体もかなり少ないようです。「たかじんのそこまで言って委員会」の頃は、東京都や神奈川県で放送がないと聞いていましたが、そこまで言って委員会NPになってからは確認していません。

```
今回は、２時間の拡大スペシャル！
「刑事裁判」「M＆A業務」「遺産相続・離婚裁判」「過払い金返還訴訟・B型肝炎訴訟」
など、いろいろな「弁護士のお仕事」をテーマに、６人の専門弁護士をゲストに招いて、
それぞれのお仕事の「難易度」はどれくらいなのかを判定し、徹底討論！
さらに、先日行なわれた「米朝首脳会談」についても議論します！ 

［source：］そこまで言って委員会NP｜読売テレビ https://www.ytv.co.jp/iinkai/
```

　石川県で「そこまで言って委員会NP」の放送はテレビ金沢になるのですが、テレビ金沢は日テレ系とばかり思ってきました。「そこまで言って委員会NP」は読売テレビと知りました。聞いたことはある放送局名です。

［link：］ そこまで言って委員会NP｜読売テレビ https://www.ytv.co.jp/iinkai/area/index.html

　そこまで言って委員会NPの放送エリアとして、わかりやすい日本地図の色分け表示になっていますが、福井県、関東全域、福島県、山形県、岩手県、青森県がエリア外のようです。西日本では福井県だけがエリア外になっているようですが、これは不思議な現象にも思えます。

　たかじんのそこまで言って委員会という番組名だった頃になりますが、そこまで言って委員会NPの番組名がもっとも注目され有名になったのは、橋下徹弁護士の光市母子殺害事件に対する弁護士の懲戒請求扇動発言だったと思います。

［link：］ 橋下徹、波紋の「講演料一律2百万請求」は高いのか？トランプと人脈ある意外な日本人は？ | ビジネスジャーナル https://biz-journal.jp/2016/12/post_17382.html

　記事の日付は2016年12月6日となっています。以前少し見かけた橋下徹弁護士の講演料のことを思い出したので調べてみました。講演の時間がわからないですが、講演というのは余り見た経験もないものの、2時間から長くて3時間という気がします。

```
余談になりますが、最近の橋下氏の話題といえば講演料の高さでしょう。維新の会所属の国会議員が政治資金パーティに講師として橋下氏を呼んだ場合、「一律200万円」の講演料を請求されるそうです。もちろん、維新の会以外の団体からの依頼でも、同じ金額です。一律の金額を定め、「特定の政党に肩入れしていない」という態度を見せているのでしょう。

［source：］以前は100万円単位の講演料も珍しくなかったが、このご時世では有権者にいい印象を与えない | ビジネスジャーナル https://biz-journal.jp/2016/12/post_17382_2.html
```

```
講師料や講演料は、どこの団体が主催するのか、何のための講演なのか、講師は講師業が主な収入源なのか、講演か、研修か、セミナーかなどの種別、かかる時間、講師は知名度があるか、等さまざまな条件によって変わってきます。

一番よくあるパターンは、90分から2時間くらいの「講演」スタイル。

これは、あるテーマについて講師が壇上に登ってほぼ一方的に話すものでレジュメなども配布しないか、Ａ4ペラ一枚で簡単な講演の概要などが配布されるだけということが多い。

最もオーソドックスな講演のスタイルですが、この講演の相場は、だいたい5万円～10万円くらいのことが多く、ちょっと著名な人だと20～30万円くらい。

有名人や売れっ子講師、タレントクラスだと50万～200万と幅広いです。

ちなみに、私の場合、一番安かったのは2時間で5万円（交通費込み・都内だったから）、一番高くて2時間で30万円（ただ話すだけ+交通費）でした。

ちなみに、これは講演の料金で、研修講師として専門的なことを教える時は、もうちょっと高くいただいています。

［source：］講師料や講演料の相場とシビアな現実と、20年業界で見てきた、あなたの価値を3倍にする方法 | 青山華子ウェブサイト（札幌ときどき東京） https://aoyamahanako.com/blog/fee/
```

　ちょっと社会勉強も必要かと思い、調べてみました。やはり公演時間は90分から2時間が相場のようです。報酬に相当すると思われる料金は、「この講演の相場は、だいたい5万円～10万円くらいのことが多く、ちょっと著名な人だと20～30万円くらい。」とのことです。

　これをみると、弁護士の公判廷での報酬というのも考えさせられるところです。出廷にかかる報酬をを報酬体系に明示していたのは、最近見た高野隆弁護士の法律事務所のホームページだけでした。

　今日のそこまで言って委員会NPでは、嵩原安三郎だったように思いますが、刑事事件の国選弁護人の報酬の相場を1件8万円としていました。私が最初に見た頃はもう少し幅があったように思いますが、同じく8万円と記憶します。平成5年から7年あたりの頃のことです。

　今日のそこまで言って委員会NP「弁護士のお仕事スペシャル」の感想を総括すると、弁護士業界もしのぎをけずる戦国時代に突入していたのだな、ということになるかと思います。番組の締めくくりあたりでも、弁護士はよく選ぶ必要がある、というような話がありました。

＜＜＜2019-03-03（日曜日）15：58＿［これまでの記述範囲の終了時刻］＜＜＜

