#+TITLE: "神山啓史弁護士（第二東京弁護士会）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-07-18 16:30:03 +0900
FILE_NAME: 2019-07-18-163003_神山啓史弁護士（第二東京弁護士会）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 神山啓史弁護士（第二東京弁護士会） 
記事タイトル名の文字数：17　保存ファイル名の文字数：39

* 神山啓史弁護士（第二東京弁護士会）

** 「高野隆、後藤貞人と共に、三大刑事弁護人として知られている」と記載のある神山啓史弁護士のwikipediaページ
   :LOGBOOK:
   CLOCK: [2019-07-18 木 16:33]--[2019-07-18 木 18:46] =>  2:13
   :END:

＞＞＞2019-07-18（木曜日）16：33＿［これからの記述範囲の開始時刻］＞＞＞

```
神山 啓史（かみやま ひろし、1955年 - ）は、日本の刑事弁護士。龍谷大学法科大学院客員教授。日弁連裁判員本部事務局次長。第二東京弁護士会裁判員裁判推進センター委員。法テラス裁判員裁判対応室室長。司法研修所教官［1］。

［source：］神山啓史 - Wikipedia https://ja.wikipedia.org/wiki/%E7%A5%9E%E5%B1%B1%E5%95%93%E5%8F%B2
```

　神山啓史弁護士の啓史を「ひろし」と読むとは今回初めて気がついたように思います。「龍谷大学法科大学院客員教授」というのも意外に感じた情報です。龍谷大学は仏教の大学だったと思います。石川県にも関連の学校があって、昨年あたり何かニュースになっていました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「龍谷」の検索結果 - Twilog https://t.co/vIUuyWn3ZG

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-18 16:38／2018-11-04 18:48 URL： https://twitter.com/kk_hirono/status/1151758079161065474 https://twitter.com/hirono_hideki/status/1059019547603218432
&twitter(1151758079161065474){theme:light}
> 橋本 太地弁護士（あなたのみかた法律事務所） - 大阪府大阪市 - 弁護士ドットコム https://t.co/xv8ezteg88 \n   \n  学歴 \n   \n  2009年 3月 \n      龍谷大学法学部卒業  \n  2012年 3月 \n      立命館大学大学院法務研究科法曹養成専攻修了
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-18 16:38／2018-10-14 13:21 URL： https://twitter.com/kk_hirono/status/1151758116712669184 https://twitter.com/hirono_hideki/status/1051327188409012224
&twitter(1151758116712669184){theme:light}
> 金沢龍谷高校の教頭・○○○容疑者(62)を当て逃げで逮捕 呼気から基準値を超えるアルコール分が検出 | ぶんぐのぶろぐ https://t.co/kASFIJ1WYU \n  引用→　平日の午後6時に教頭が飲酒して当て逃げってか。 \n  （実名部分も置換）
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-18 16:38／2018-10-14 13:15 URL： https://twitter.com/kk_hirono/status/1151758159456792577 https://twitter.com/hirono_hideki/status/1051325500788944896
&twitter(1151758159456792577){theme:light}
> 車で追突し逃走 私立高教頭逮捕｜NHK 石川県のニュース https://t.co/EKpdfmPKZK \n  容疑者は県教育委員会の教育次長を務めたあと、ことし４月から金沢龍谷高校の教頭を務めていたということです。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-18 16:38／2018-10-14 13:06 URL： https://twitter.com/kk_hirono/status/1151758230814507008 https://twitter.com/hirono_hideki/status/1051323426189672449
&twitter(1151758230814507008){theme:light}
> 金沢龍谷高等学校について｜学校紹介 | 金沢龍谷高等学校 https://t.co/uQvRAEvE71 \n  1922年の開校以来、本校は仏教の教えを基本とした建学精神のもと、生徒と教師が一丸となって、夢と心を大切にする「心の学園」づくりを追求してまいりました。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-18 16:39／2018-10-14 12:50 URL： https://twitter.com/kk_hirono/status/1151758279120310272 https://twitter.com/hirono_hideki/status/1051319401490800641
&twitter(1151758279120310272){theme:light}
> 当て逃げ疑い高校教頭逮捕　軽傷男性が１１０番中に逃走 - 芸能社会 - https://t.co/M6hh8hNsyx（サンスポ） https://t.co/QNS3IpOTxt \n  金沢西署は１３日、自動車運転処罰法違反（過失傷害）… https://t.co/B7K2SmyjyT
◁◁◁
<hr />

　橋本太地弁護士の経歴に龍谷大学法学部があったことは忘れていました。立命館大学大学院ともありますが、この立命館大学が中心になってえん罪を救済する団体が発足したというニュースがありました。佐藤博史弁護士が参加していたことで強く印象に残ったニュースでした。

　２０１８年１０月１４日とあるので昨年のニュースになりますが、その日限りで続報は見ていませんでした。事件というか問題の内容もよく憶えていなかったのですが、飲酒で当て逃げ事故を起こしたようです。リンクの記事を１つ開くと逮捕とありました。

```
金沢西署は１３日、自動車運転処罰法違反（過失傷害）と道交法違反（当て逃げ）の疑いで、石川県かほく市、私立金沢龍谷高の教頭竹中功容疑者（６２）を逮捕した。

［source：］当て逃げ疑い高校教頭逮捕　軽傷男性が１１０番中に逃走 - 芸能社会 - SANSPO.COM（サンスポ） https://www.sanspo.com/geino/news/20181013/tro18101312230002-n1.html
```

　龍谷高校の教頭だったというのも記憶にはなかったですが、今日の昼頃にも学校の教頭のことで信じがたいニュースを見ました。長年無免許運転をしていたことが発覚したというニュースは見ていたのですが、通行禁止の許可証を得るため免許証を偽造していたという新たなニュースでした。

```
逮捕容疑は４月１０日、同小付近のスクールゾーンを通勤時間帯に車で通るための許可を申請する際に、偽造した免許証の写しを提出したとしている。

　同署によると、岩倉容疑者は妻の免許証のコピーに自身の顔写真と名前を上から貼り付け、コピーを取ったものを提出していた。岩倉容疑者は昨年４月に同小の教頭になっており、同署は、昨年も同様の方法で申請を行っていたとみて余罪を調べている。

　岩倉容疑者は今月８日に無免許で軽乗用車を運転したとして、道交法違反（無免許運転）容疑で逮捕され、１２日に釈放されていた。同署によると、運転免許を取得した記録がなく、長期間にわたって無免許運転をしていた可能性があるという。

［source：］無免許容疑で逮捕の教頭　妻の免許偽造しスクールゾーン通行許可申請　 - 産経ニュース https://www.sankei.com/affairs/news/190718/afr1907180026-n1.html
```

　テレビのニュースより具体的で詳細ですが、いっそう信じられない内容です。そういえば昨日辺り、判決書を偽造した弁護士に執行猶予というニュースがありましたが、小さなニュースで、テレビでは見ていません。

```
離婚訴訟の判決文を偽造したとして、有印公文書偽造・同行使の罪に問われた大阪弁護士会所属の弁護士、鈴木健介被告（41）＝神戸市東灘区＝の判決公判で、大阪地裁は17日、懲役1年6月・執行猶予3年（求刑・懲役1年6月）を言い渡した。長瀬敬昭裁判長は「弁護士の専門知識を使っていて悪質だ」と指摘した。

［source：］離婚訴訟の判決文を偽造 弁護士に執行猶予つきの有罪判決 大阪地裁 https://www.msn.com/ja-jp/news/national/%E9%9B%A2%E5%A9%9A%E8%A8%B4%E8%A8%9F%E3%81%AE%E5%88%A4%E6%B1%BA%E6%96%87%E3%82%92%E5%81%BD%E9%80%A0-%E5%BC%81%E8%AD%B7%E5%A3%AB%E3%81%AB%E5%9F%B7%E8%A1%8C%E7%8C%B6%E4%BA%88%E3%81%A4%E3%81%8D%E3%81%AE%E6%9C%89%E7%BD%AA%E5%88%A4%E6%B1%BA-%E5%A4%A7%E9%98%AA%E5%9C%B0%E8%A3%81/ar-AAEsj3p#page=2
```

　弁護士が判決書を偽造したというニュースは数年前にも見ていますが、同じく小さな扱いでした。理由はいずれも事件放置だったと思いますが、事件放置だけだと懲戒処分になっても軽いようです。

　「。日弁連裁判員本部事務局次長。第二東京弁護士会裁判員裁判推進センター委員。法テラス裁判員裁判対応室室長。」と裁判員制度に関する役職があるようです。これも初めて知ったように感じました。神山啓史弁護士のwikipediaは前にも見ていると思いますが、記憶にない感じです。

　繰り返しになりますが、「高野隆、後藤貞人と共に、三大刑事弁護人として知られている[3]。」という記載もある神山啓史弁護士です。繰り返しというか見出しにしただけでした。この高野隆弁護士については裁判員制度に積極的に関与すているという情報を見てきました。

　とりわけすごい、歴史的と思ったのが高野隆弁護士が姫路の裁判員制度を手がけたとこで、日数が最長になったとのことです。このニュースは、NHKのニュースで知りました。たぶんNEWS９だったと思うのですが、そのニュースがなければ今でも知らないままだったかもしれません。

　「高野隆弁護士　最長」とGoogleで検索をしたのですが、次の記事がみつかりました。意外な発見です。

```
自身が執刀した女性患者に対してわいせつな行為をしたとして、準強制わいせつ罪で逮捕・起訴された男性外科医に対する裁判で、東京地裁（大川隆男裁判長）は2月20日、男性外科医に無罪（求刑懲役3年）を言い渡した。主任弁護人は刑事弁護の第一人者として知られる高野隆氏。完全無罪判決は今回で16回目という。本裁判の争点や、判決の意義を振り返っていただいた。（2019年2月21日にインタビュー。計2回連載の1回目）

判決はこちら⇒ 『乳腺外科医裁判で無罪判決、わいせつ行為否定』
第2回公判での高野氏の弁護側冒頭陳述はこちら⇒『乳腺外科医裁判が再開、「『犯罪』ではなく『症例』』

［source：］「あり得ないと肌で感じた」、乳腺外科医裁判－高野隆・主任弁護人に聞く◆Vol.1｜医療維新 - m3.comの医療コラム https://www.m3.com/open/iryoIshin/article/662058/
```

　無罪判決が出たのが２月２０日とのことです。控訴の期限は１４日間だったと思いますが、たしか検察が控訴をした前後に、弘中惇一郎弁護士と高野隆弁護士のカルロス・ゴーン被告の弁護人就任のニュースがありました。

　繰り返しテレビで報道されていたので、テレビをみる習慣のある人の多くは高野隆弁護士の姿を目にしていると思いますが、高野隆弁護士がテレビであれほど注目されたのも私の知る範囲で初めてのことで、忙しくもあったのだと想像しますが、検察控訴後の乳腺外科医に関する発言は見ていません。

　この高野隆弁護士がその前にテレビで注目されたのは、日曜劇場『99.9－刑事専門弁護士－』というドラマでした。ネット上の情報を交えて、私には高野隆弁護士の予備知識があり、それだけ印象も強かったのですが、なんとかというかたちでドラマに関与していたようです。

　ところが、日曜劇場『99.9－刑事専門弁護士－』の主人公のモデルが神山啓史弁護士というのは、本日wikipediaでみて初めて知ったように思いました。モデルと言われても、正直なところしっくりとはきません。

　日曜劇場『99.9－刑事専門弁護士－』のドラマの内容も余りよくは憶えていないし、全作品を視聴したわけでもなかったように思います。たしか、父親がえん罪で獄死したようなストーリーで、出身地か子供の頃に育った場所が石川県の金沢市ということになっていたように思います。

　朱色の崖の上のような場所にある大きな寺社がドラマに出てきましたが、これは絶対に石川県にある寺社ではないと思いました。ネットで少し調べたように思いますが、神奈川県内の寺社がロケ地になっているような情報を見かけたように思います。

```
人物・経歴［編集］
中央大学法学部を卒業後、1983年に弁護士登録［2］。刑事弁護の中でも、特に冤罪事件を専門として取り扱っている。裁判員制度の推進者の一人。 テレビドラマ『99.9 -刑事専門弁護士-』での、松本潤が演じる主人公の深山大翔（みやま ひろと）のモデルの人物である。

三大刑事弁護人［編集］
高野隆、後藤貞人と共に、三大刑事弁護人として知られている［3］。

［source：］神山啓史 - Wikipedia https://ja.wikipedia.org/wiki/%E7%A5%9E%E5%B1%B1%E5%95%93%E5%8F%B2
```

　後藤貞人弁護士についても取り上げておきたいことがありますが、最も著名な事件が大阪市の平野区の母子殺害事件でした。被疑者が大阪刑務所の刑務官であったことも特徴的な事件でしたが、無罪判決が確定したことで、母子の魂が救われるのかと宗教的に考えさせられる刑事裁判でした。

　もう１件も大阪ですが、親族間の強姦で再審無罪判決がありました。一年ほど前になるのでしょうか、国家賠償請求の訴訟があり、敗訴となっていましたが、その訴訟の過程で、再審無罪事件に関する具体的で詳細な情報を多く見かけるようになりました。事件に対する印象もずいぶん変わりました。

　もう５年ぐらい前になるように思いますが、高野隆弁護士と後藤貞人弁護士が仲睦まじく一緒にいる写真をたまたま見たことがあったと記憶します。Twilogでちょっと探してみます。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「後藤 高野」の検索結果 - Twilog https://t.co/Iu6LDY6R7D

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-18 17:47／2018-01-03 11:57 URL： https://twitter.com/kk_hirono/status/1151775511254667264 https://twitter.com/hirono_hideki/status/948387878060548096
&twitter(1151775511254667264){theme:light}
> ２月６，７日の二日間，札幌弁護士会の法廷技術研修で講師をつとめました。 \n   \n  今回の講師陣は，後藤貞人先生，高野隆先生，坂根真也先生と私の４人でした。 \n  いつもながら，後藤さん，高野さん，坂根さんの講義・講評は参考になります。 https://t.co/to2Qzovggu
◁◁◁
<hr />

　思いの外あっさり簡単に情報が見つかったのですが、２０１８年１月３日のツイートとなっています。昨年ということで１年７ヶ月ほど前のことになるようですが、私の感覚では４，５年前に見かけた情報という感覚でした。期間の違いが大きいので少なからず衝撃です。

```
札幌弁護士会・法廷技術研修で講師をつとめました
2016.02.19ブログ
２月６，７日の二日間，札幌弁護士会の法廷技術研修で講師をつとめました。

今回の講師陣は，後藤貞人先生，高野隆先生，坂根真也先生と私の４人でした。
いつもながら，後藤さん，高野さん，坂根さんの講義・講評は参考になります。
まだまだ技術を磨きたいと思いました。
（たまたま）雪祭りの時期でラッキーでした。

［source：］札幌弁護士会・法廷技術研修で講師をつとめました｜お知らせ・ブログ｜千葉県千葉市の弁護士事務所　法律事務所シリウス http://www.sirius-law.com/news/20160219/180/
```

　法律事務所シリウスというのも記憶にはなかったのですが、記事に私とあるのは、弁護士紹介のリックのトップで表示された次の弁護士のことかと思われます。菅野完というのは、森友学園問題などでよく見かけてきたお名前ですが、菅野亮というのは見覚えのない名前です。

```
菅野亮すげの あきら

経歴
1993年4月	早稲田大学法学部入学
1996年11月	司法試験合格
1997年3月	早稲田大学法学部卒業
1997年5月	アジア中近東諸国を放浪
1998年4月	イスタンブールから帰国
司法修習生(52期)
2000年4月	司法修習終了
弁護士登録
レークス法律事務所勤務
2003年6月	ヨーロッパ諸国を放浪
2004年2月	イタリアから帰国し弁護士業務再開
2005年11月	レークス法律事務所から独立「法律事務所シリウス」開設
役職等
日弁連	刑事弁護センター　事務局長
最高裁	刑事規則制定諮問委員会　幹事
法務省	裁判員制度の施行状況等に関する検討会　委員
千葉県弁護士会　	倒産法運用検討委員会　委員長
千葉市	精神医療審査会委員
法務局	筆界特定委員
境界紛争センター	調停委員
過去の役職等
日弁連	刑事調査室嘱託
司法研修所	刑事弁護教官
千葉県弁護士会	刑事弁護センター　副委員長
千葉県信用保証協会	外部評価委員
季刊刑事弁護	編集委員

［source：］弁護士紹介｜千葉県千葉市の弁護士事務所　法律事務所シリウス http://www.sirius-law.com/members/
```

　貼り付けたページタイトルで初めて気がついたのですが、千葉県千葉市の弁護士事務所とのことです。同じ千葉市だったと思いますが、Twitterで強く印象に残る実名弁護士が２人いました。最近は見かけていないですが、たくさんの刑事弁護を手がけ、無罪などの実績も多いようでした。

　シリウスというTwitterの弁護士と思われるアカウントがありましたが、実在する名称と関連付けて考えたことはなく、無関係である可能性の方が高いとも思います。法律事務所シリウスは全部で６人の弁護士の名前がありますが、見覚えのある名前はありません。

```
シリウスＡ
@eeyy888777
６５べし。しごとかたらず。ほどほど。

2015年7月に登録

［source：］シリウスＡ(@eeyy888777)さん | Twitterからの返信付きツイート https://twitter.com/eeyy888777/with_replies
```

　プロフィールの内容が変わっているように思いましたが、６５とあるのは、司法修習６５期の意味が高そうです。現時点で最も新しい司法修習の期として見かけるのは７３期かと思います。現在修習中なのが７４期なのかもしれないですが、７４期というのは見かけていない気がします。

```
2010年11月1日、常勤弁護士総合企画部に、裁判員裁判弁護技術研究室が設置されました。 裁判員裁判における弁護技術の研究及び普及，スタッフ弁護士の裁判員裁判事件に対する業務支援を目的としています。

「研究室」のメンバーは、室長 神山啓史（第二東京弁護士会）、主任研究員 岡慎一（埼玉弁護士会）、主任研究員 坂根真也（東京弁護士会）、研究員　趙誠峰（第二東京弁護士会）の4名です。

［source：］裁判員裁判弁護技術研究室・常勤弁護士業務支援室｜法テラス https://www.houterasu.or.jp/houterasu_gaiyou/saiyo/staff_bengoshi/kenshuu_backup/kenshuu08.html
```

　坂根真也という弁護士名には見覚えがあったので、確認のため調べたところ、上記の情報が見つかりました。坂根真也弁護士については、似たような名前の弁護士がいてそちらと混同することがありました。一方の弁護士はいわゆるヤメ検で、テレビにも出ていたかと思います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「羅針盤」の検索結果 - Twilog https://t.co/7vdgppXFcV

<hr />

[link:] » 日本羅針盤法律事務所 代表／弁護士 望月宣武 | 仕事を楽しむためのWebマガジン、B-plus（ビープラス） https://t.co/BRtQf1MZJs

<hr />

　坂根真也弁護士かその勘違いした弁護士の名前で、変わった名前の法律事務所があったと記憶にあり、数日前にも久しぶりに思い出していたのですが、１５分ほど思い出そうと集中していたところ、羅針盤ではなかったかと思い調べました。結果は予想外の望月宣武弁護士の名前が出てきました。

　経営者インタビューとも出ている上記のページにある望月宣武弁護士の顔写真は、これまで見てきたものといくらか印象に違いがあります。この弁護士の名前を知っている人も少ないと思いますが、テレビで見かけた人は少なくないと思います。

　「望月　愛媛　アイドル」とGoogle検索をやってみます。たぶん思い通りの情報が見つかると思います。

[link:] » 望月 愛媛 アイドル - Google 検索 https://t.co/uJtOae1XMP

<hr />
[link:] » 注目裁判・話題の会見：愛媛アイドル自殺初弁論　遺族側「辞めるなら1億円と言われた」、事務所側「社員とは兄妹のように親密」 - 毎日新聞 https://t.co/ctfoKo0nv5

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜166mochizuki（望月宣武Hiromu MOCHIZUKI） 日時：2019-07-18 18:35／2018-12-28 16:43 URL： https://twitter.com/kk_hirono/status/1151787639676133376 https://twitter.com/166mochizuki/status/1078557077138599941
&twitter(1151787639676133376){theme:light}
> 愛媛アイドル自殺訴訟、第1回口頭弁論期日の日時と法廷が決まりました。ご支援よろしくお願いいたします。 \n  https://t.co/VpsZLoO7qs \n  #農業アイドル #大本萌景
◁◁◁
<hr />

　２，３週間ほど前には一度見ていたように思う望月宣武弁護士のTwitterですが、固定ツイートとして次のツイートを目にしました。２０１８年１０月１３日のツイートとなっていますが、これは初めて目にしたように思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜166mochizuki（望月宣武Hiromu MOCHIZUKI） 日時：2019-07-18 18:40／2018-10-13 17:22 URL： https://twitter.com/kk_hirono/status/1151788937741918211 https://twitter.com/166mochizuki/status/1051025336245268480
&twitter(1151788937741918211){theme:light}
> #電通 の #高橋まつり さんは、生前に当事務所に遊びに来てくれたことがありました。そのあと彼女が自死で亡くなって、#働き方改革 が始まりました。 \n  今回の #大本萌景 さんの自死を無駄にしないために、芸能界とアイドルの働き方改革のきっかけにしたいと思っています。 \n  #農業アイドル
◁◁◁
<hr />

　NHKの女性記者だったと思いますが、そちらは過労死のニュースであったように思います。そちらは福岡の向原栄大朗弁護士が生前に親交があったとツイートしているのを見た記憶があります。向原栄大朗弁護士も愛媛の弁護団としてテレビに姿がありましたが、深い角度で下を向いたままでした。

＜＜＜2019-07-18（木曜日）18：46＿［これまでの記述範囲の終了時刻］＜＜＜

** wikipediaに三大刑事弁護人の一人としての神山啓史弁護士と、その過去の担当事件３つのうちの「名張ぶどう酒事件」
   :LOGBOOK:
   CLOCK: [2019-07-18 木 18:51]--[2019-07-18 木 20:37] =>  1:46
   :END:

＞＞＞2019-07-18（木曜日）18：51＿［これからの記述範囲の開始時刻］＞＞＞

```
三大刑事弁護人［編集］
高野隆、後藤貞人と共に、三大刑事弁護人として知られている［3］。

過去の担当事件［編集］
東電OL殺人事件
名張毒ぶどう酒事件
足利事件

［source：］神山啓史 - Wikipedia https://ja.wikipedia.org/wiki/%E7%A5%9E%E5%B1%B1%E5%95%93%E5%8F%B2
```

　前にも見かけていたようには思いましたが、上記の引用の通り、神山啓史弁護士の過去の担当事件として「名張ぶどう酒事件」があります。この「名張ぶどう酒事件」については、ジャーナリストの江川紹子氏のひとかたならぬ強い思いがあり、それが裁判官への批判として強烈なものとなっていました。

　足利事件にも神山啓史弁護士の名前がありますが、足利事件においては、佐藤博史弁護士の名前が大きく出ていたと思いますし、菅家さんを自宅に住まわせ面倒をみていたという情報もあったかと思います。

　泉澤章弁護士の名前も足利事件としてみかけた覚えがあるのですが、泉澤章弁護士と佐藤博史弁護士、泉澤章弁護士と神山啓史弁護士という横の繋がりをみたことはありません。気になったので調べたとも思いますが、確認が出来なかったように思います。

　ここでは軽く触れるにとどめておきますが、衝撃的に泉澤章弁護士の名前を記録したのは次のニュースでした。名前で検索すれば、すぐに情報が見つかると思います。

[link:] » 泉澤章弁護士 - Google 検索 https://t.co/sYjaRs8yZs

<hr />
[link:] » 泉澤章弁護士が自由法曹団幹事長に就任しました https://t.co/Bg6FS1Wllo

<hr />
[link:] » 死体遺棄の“お嬢様女子大生”に有罪判決　法廷で笑いだす弁護人に裁判長ムッ！ (2016年9月7日) - エキサイトニュース https://t.co/kaZ6Lme8Ou

<hr />
続けて「遺体が“人の可能性はない”と認識する特段の事情はない」と裁判長が見解を述べると、泉澤章弁護士は突然噴き出し、声を立てて笑いだした。裁判長が「途中なので黙って聞いてください！」とムッとするも、泉澤弁護士は「面白いから笑っただ… https://t.co/DUJkq8cRM4

<hr />
判決後の会見で泉澤弁護士は「あの裁判体では有罪になる予想はついたので被告にも『高裁で頑張ればいい』と話し、あらかじめ控訴状を作ってきた。高裁では必ず逆転する」と息巻いた。 https://t.co/kaZ6Lme8Ou

<hr />
“お嬢様女子大生”が当時の交際相手、佐藤一麿被告（殺人罪で起訴）にそそのかされ死体遺棄を手伝った衝撃や、阿部さんと両被告の三角関係などが臆測を呼び、大きく報じられたこの裁判は、弁護人が裁判長の読み上げる判決文を一笑に付すなど、緊迫… https://t.co/lqXhKYRtWR

<hr />

　そういえば数日前に佐藤一麿被告の有罪判決が出たというようなニュースをテレビでみたのですが、深夜のニュース番組で夢の中で見たような記憶ともなっています。たぶんスマホでテレビ画面の撮影はしていると思いますが、ネットでもニュースは見ていないように思います。

[link:] » 佐藤一麿 - Google 検索 https://t.co/TaQ8yNpDFk

<hr />
[link:] » 相模原女性遺体　元交際相手に懲役17年判決　東京地裁　　:日本経済新聞 https://t.co/b1bbQcIpf6 \n 2019/7/10 15:55

<hr />
[link:] » 佐藤一麿　判決 - Google 検索 https://t.co/EEPjFkCOy7

<hr />
[link:] » 女性遺体は殺人か 佐藤一麿被告に判決 https://t.co/Otfe3pXkiv \n 遺体を隠したことは深く反省しているが、殺害をやっていない。 \n  \n 元交際相手の女性を殺害したとして、起訴されていた男に判決。

<hr />
[link:] » 女性遺体は殺人か 佐藤一麿被告に判決 https://t.co/Otfe3pXkiv \n 2015年、神奈川・相模原市の墓地で遺体が見つかった阿部由香利さん(当時25)。 \n  \n その死は、自殺か殺人か。

<hr />
[link:] » 女性遺体は殺人か 佐藤一麿被告に判決 https://t.co/Otfe3pXkiv \n 殺人の罪に問われる前、すでに阿部さんの遺体を墓地に遺棄した罪で、執行猶予付きの有罪判決が確定していた佐藤被告。

<hr />
[link:] » 女性遺体は殺人か 佐藤一麿被告に判決 https://t.co/Otfe3pXkiv \n 阿部さんの遺体からは、大量の睡眠薬反応が出ており、弁護側は、睡眠薬の成分による中毒死で、自殺か事故の可能性があると主張していた。

<hr />
[link:] » 女性遺体は殺人か 佐藤一麿被告に判決 https://t.co/Otfe3pXkiv \n 一方、検察側は、佐藤被告が睡眠薬を飲ませたうえで、頸部(けいぶ)を圧迫し、窒息死させたと主張。 \n  \n 判決では、検察側の主張が全面的に認められた。

<hr />
[link:] » 女性遺体は殺人か 佐藤一麿被告に判決 https://t.co/Otfe3pXkiv \n 7月2日、この裁判の法廷で睡眠薬について「睡眠薬を買えるだけ買ってほしいと言われて、10箱以上買った」と証言した。

<hr />
[link:] » 女性遺体は殺人か 佐藤一麿被告に判決 https://t.co/Otfe3pXkiv \n 10日の判決では、佐藤被告が女性に睡眠薬の購入を指示したことや、遺棄現場の下見をさせたことなどから、犯人性を指摘。 \n  \n 殺意は強固であるとの判断を示した。

<hr />

　テレビでみたニュースより詳細かと思いますが、裁判の争点というのが大崎事件に似ているとも、上記の記事を読んでいて感じました。

　７月１０日のニュースのようですが、７月６日に宇出津のあばれ祭りが終わったあと、あまりテレビをつけない時期があり、夕方から夜寝るまでまったくつけないこともあったかと思います。あるいはちょうどその時期だったのかもしれません。

　ただ、ネットで検索をしても佐藤一麿被告の判決に関するニュースは少ないという印象です。以前はかなり大々的に報道されていたという印象が強い事件であるだけに、この違いはなんなのかと考えます。弁護士が取材に消極的だったというのもあるいは一因なのかもしれません。

　泉澤章弁護士に関しては、その神奈川県相模原市の事件の報道が落ち着いた頃、鹿児島県の大崎事件の応援に行くとか、行ったというネットニュースを見かけた憶えがあり、泉澤章弁護士が絡んだことでそれまで余り関心のなかった大崎事件に関する関心も強まったと記憶にあります。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「泉澤 大崎」の検索結果 - Twilog https://t.co/FaPGvzE2Jw

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-18 19:26／2019-06-28 21:00 URL： https://twitter.com/kk_hirono/status/1151800335372967936 https://twitter.com/hirono_hideki/status/1144576408376659968
&twitter(1151800335372967936){theme:light}
> 大崎事件　泉澤　弁護士 - Google 検索 https://t.co/cHRign3LG0
◁◁◁
<hr />

　残念ながら検索結果は６月２８日の１件のみでした。大崎事件の再審取り消しの決定が最高裁であったとテレビで報道されたのが６月２５日だったと思います。しばらくして前日の２５日付の決定だったと知りました。これは刑事司法において歴史的なものであったと思います。

　時刻は２０時３５分です。中断していたままになっていたことに気が付きましたが、京都アニメーション放火殺人事件に関する山口貴士弁護士と平野敬弁護士に関するツイートを早急に取り上げておきたいので、とりあえず切り上げます。

＜＜＜2019-07-18（木曜日）20：37＿［これまでの記述範囲の終了時刻］＜＜＜

