#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "参考資料／弁護士業界の現状／落合洋司弁護士（東京弁護士会）／タレントのローラさんの政治的な発言の問題がきっかけで落合洋司弁護士と堀江貴文氏について調べた"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-24 00:11:28 +0900
FILE_NAME: 2018-12-24-001128_タレントのローラさんの政治的な発言の問題がきっかけで落合洋司弁護士と堀江貴文氏について調べた.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  落合洋司弁護士（東京弁護士会） サンジャポ 堀江貴文氏 ホリエモン カルロス・ゴーン氏 特別背 検察批判
記事タイトル名の文字数：76　保存ファイル名の文字数：68

#contents

* 落合洋司弁護士（東京弁護士会）とホリエモンこと堀江貴文氏の関係性について調べてみた意外な結果
  :LOGBOOK:
  CLOCK: [2018-12-24 月 00:15]--[2018-12-24 月 00:16] =>  0:01
  :END:

＞＞＞2018-12-24（月曜日）00：16＿［これからの記述範囲の開始時刻］＞＞＞

　これから奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントでのツイートを53件、スクリプトの処理でリツイートします。なかなか興味深く、意外な結果が出たので、遺跡の発掘作業のような記録です。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:18／2018-12-24 00:18 URL： https://twitter.com/kk_hirono/status/1076859687809601536 https://twitter.com/hirono_hideki/status/1076859653248606208
&twitter(1076859687809601536){theme:light}
> 『2018年12月23日のつぶやき』MakeMyDay｜https://t.co/pLp1bllOzR
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:18／2018-12-24 00:04 URL： https://twitter.com/kk_hirono/status/1076859701571215360 https://twitter.com/hirono_hideki/status/1076855977343762432
&twitter(1076859701571215360){theme:light}
> 落合洋司🇯🇵 「ニチョウ 東京地検特捜部特別分室」1月4日発売！さんのツイート: "検察改革案を法相に提言　在り方検討会議 https://t.co/OuwiXB1sk0" https://t.co/hkSPZIM6rY \n  　これも… https://t.co/vUAyiw8XQb
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:18／2018-12-24 00:01 URL： https://twitter.com/kk_hirono/status/1076859715630510080 https://twitter.com/hirono_hideki/status/1076855426468048903
&twitter(1076859715630510080){theme:light}
> 2011年03月31日のツイート - 弁護士落合洋司（東京弁護士会）の日々是好日 https://t.co/zpzZ7d1uEI
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:19／2018-12-24 00:01 URL： https://twitter.com/kk_hirono/status/1076859729337409536 https://twitter.com/hirono_hideki/status/1076855202127372288
&twitter(1076859729337409536){theme:light}
> 在り方検討会議 の検索結果 - 弁護士落合洋司（東京弁護士会）の日々是好日 https://t.co/Amf0SjSHRw
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:19／2018-12-24 00:00 URL： https://twitter.com/kk_hirono/status/1076859743778426882 https://twitter.com/hirono_hideki/status/1076854982190686209
&twitter(1076859743778426882){theme:light}
> ぬるい。ぬるすぎる の検索結果 - 弁護士落合洋司（東京弁護士会）の日々是好日 https://t.co/OMg7ypAm1N \n  記事はありません
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:19／2018-12-23 23:56 URL： https://twitter.com/kk_hirono/status/1076859757632270336 https://twitter.com/hirono_hideki/status/1076854009523331072
&twitter(1076859757632270336){theme:light}
> 落合洋司🇯🇵 「ニチョウ 東京地検特捜部特別分室」1月4日発売！さんのツイート: "フジテレビのニュース用の電話コメントしたら、ギャラの口座確認の電話があった。偉いぞフジテレビ。笑" https://t.co/djkN3Ngano
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:19／2018-12-23 23:55 URL： https://twitter.com/kk_hirono/status/1076859771393724416 https://twitter.com/hirono_hideki/status/1076853881408110593
&twitter(1076859771393724416){theme:light}
> 落合洋司🇯🇵 「ニチョウ 東京地検特捜部特別分室」1月4日発売！さんのツイート: "聞くだけでギャラをケチったりしていると、和田アキ子みたいに紅白から見放されたり。笑… " https://t.co/PUMl8H9ldP
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:19／2018-12-23 23:55 URL： https://twitter.com/kk_hirono/status/1076859785427841024 https://twitter.com/hirono_hideki/status/1076853811434508288
&twitter(1076859785427841024){theme:light}
> 落合洋司🇯🇵 「ニチョウ 東京地検特捜部特別分室」1月4日発売！さんのツイート: "特捜部の事情聴取は既に受けているだろう。→ゴーン18億円付け回し事件　求められる政井日銀審議委員の説明 #ゴーン #スクープ速報 #週刊文春… https://t.co/Lkj11k72eY
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:19／2018-12-23 23:53 URL： https://twitter.com/kk_hirono/status/1076859799462064129 https://twitter.com/hirono_hideki/status/1076853396622139392
&twitter(1076859799462064129){theme:light}
> 塩田直也 裁判官 - Google 検索 https://t.co/32IEz3PyaZ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:19／2018-12-23 23:50 URL： https://twitter.com/kk_hirono/status/1076859813181550594 https://twitter.com/hirono_hideki/status/1076852658080632832
&twitter(1076859813181550594){theme:light}
> 落合洋司🇯🇵 「ニチョウ 東京地検特捜部特別分室」1月4日発売！さんのツイート: "噴火しそうな火山のそばにある支部とか。笑→ 文春オンラインのインタビューを読んだので岡口さんの次の異動先を予想してみる - だいたい週刊宇都宮地裁… https://t.co/wAULU9r513
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:19／2018-12-23 23:50 URL： https://twitter.com/kk_hirono/status/1076859827077271552 https://twitter.com/hirono_hideki/status/1076852563641720833
&twitter(1076859827077271552){theme:light}
> 落合洋司🇯🇵 「ニチョウ 東京地検特捜部特別分室」1月4日発売！さんのツイート: "アベマテレビ出演時の落合コメントあり。→「異例中の異例」元検察官も驚いた東京地裁の”勾留却下”、そして東京地検の”前倒し再逮捕” #BLOGOS… https://t.co/aYTdjv22LG
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:19／2018-12-23 23:50 URL： https://twitter.com/kk_hirono/status/1076859840989868032 https://twitter.com/hirono_hideki/status/1076852458020790274
&twitter(1076859840989868032){theme:light}
> 落合洋司🇯🇵 「ニチョウ 東京地検特捜部特別分室」1月4日発売！さんのツイート: "どの党が政権取って、誰が首相になっても、日本はよくならんだろう。朽ちかけたボロ屋は、いずれ倒壊する。" https://t.co/GGgA8yKx8q
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜takapon_jp（堀江貴文(Takafumi Horie)） 日時：2018-12-24 00:19／2011-04-12 17:24 URL： https://twitter.com/kk_hirono/status/1076859854998822913 https://twitter.com/takapon_jp/status/57720652475539456
&twitter(1076859854998822913){theme:light}
> ブログ更新です。 震災の陰で検察高笑い。 - 久しぶりの落合弁護士ブログより。■[話題]検察改革案を法相に提言　在り方検討会議 ぬるい。ぬるすぎる。。。検察は.. ☞ http://am6.jp/f9lCiA
◁◁◁
<hr />

　13件リツイートしたところでエラーが出てスクリプトが停止していました。You have already retweeted this Tweet.というエラーです。

　すでにリツイート済みのツイートをリツイートしようとしたのでエラーが出たようです。たぶん非常上告-最高検察庁御中_ツイッター（@s_hirono）のツイートだと思われます。それと、自動投稿された予期せぬツイートが1件、最初にリツイートされていました。

　やはり例外処理を行った方が良さそうです。

　時刻は12月24日00時42分です。スクリプトに例外処理を加えました。リツイート済みとして例外が出た場合、それを補足して、別のツイートをするようにしました。これから実行してエラーが出れば再度見直します。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:44／2018-12-23 23:48 URL： https://twitter.com/kk_hirono/status/1076866247478759425 https://twitter.com/hirono_hideki/status/1076851934252883968
&twitter(1076866247478759425){theme:light}
> 検察改革案を法相に提言 在り方検討会議 ぬるい。ぬるすぎる - Google 検索 https://t.co/RugaEkBjVS
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜karaage__20（から揚げにじゅー） 日時：2018-12-24 00:44／2014-06-05 22:41 URL： https://twitter.com/kk_hirono/status/1076866261139709952 https://twitter.com/karaage__20/status/474546504971993088
&twitter(1076866261139709952){theme:light}
> 私、堀江貴文に対するよくある質問、手がけているらしい！落合さんブチギレ「馬鹿スタッフ」弁護士がアッコ...
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜RSSchneuer（schneuer） 日時：2018-12-24 00:45／2011-04-08 15:19 URL： https://twitter.com/kk_hirono/status/1076866276021043201 https://twitter.com/RSSchneuer/status/56239615341891584
&twitter(1076866276021043201){theme:light}
> 【堀江貴文】 震災の陰で検察高笑い。: 久しぶりの落合弁護士ブログより。 ■[話題]検察改革案を法相に提言　在り方検討会議 ぬるい。ぬるすぎる。。。検察はほんと大震災の陰で高笑いしているように思えます。。。... http://dlvr.it/MqQ89
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜masaki_kito（紀藤正樹 MasakiKito） 日時：2018-12-24 00:45／2011-06-19 12:52 URL： https://twitter.com/kk_hirono/status/1076866290684313600 https://twitter.com/masaki_kito/status/82294681865695232
&twitter(1076866290684313600){theme:light}
> 興味深い議論⇒　落合洋司弁護士（元検事）@yjochi 　VS　堀江貴文@takapon_jp 　本当は参戦したいが、僕は今から日弁連消費者問題対策委員会の会議で、午後全部がつぶれている。　#horiemon #livedoor
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜rss_bot1（rss_bot） 日時：2018-12-24 00:45／2013-03-28 11:44 URL： https://twitter.com/kk_hirono/status/1076866305326604289 https://twitter.com/rss_bot1/status/317104796379275266
&twitter(1076866305326604289){theme:light}
> 『日本一の服役コンサルタント』のおかげ？刑期の74%で仮釈放できたホリエモン: 「刑期の74%」で仮釈放となったライブドア社元社長、堀江貴文氏。落合洋司弁護士が「日本一の服役コンサルタントのおかげでもあるのだろう。」とツ... http://t.co/eGjMl6UcLI
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜karaage012159（から揚げごじゅーきゅー） 日時：2018-12-24 00:45／2014-06-05 19:54 URL： https://twitter.com/kk_hirono/status/1076866320061190144 https://twitter.com/karaage012159/status/474504578184921088
&twitter(1076866320061190144){theme:light}
> -事実関係とかオフレコネタもあるから。私、堀江貴文に対するよくある質問、手がけている理由 - 落合さんブチギレ「馬鹿スタッフ」弁護士がアッコにおまかせ！を痛烈批判...
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:45／2018-12-23 23:44 URL： https://twitter.com/kk_hirono/status/1076866334779105280 https://twitter.com/hirono_hideki/status/1076851125557456901
&twitter(1076866334779105280){theme:light}
> 堀江貴文　落合　弁護士 - Twitter検索 https://t.co/3cmtYIewK4 \n  　「堀江貴文さんと落合陽一さん」という組み合わせが多く目につく。弁護士と絞り込みを入れているのに関わらず。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:45／2018-12-23 23:43 URL： https://twitter.com/kk_hirono/status/1076866348637138944 https://twitter.com/hirono_hideki/status/1076850728084226048
&twitter(1076866348637138944){theme:light}
> 落合弁護士ネタ | 堀江貴文オフィシャルブログ「六本木で働いていた元社長のアメブロ」 https://t.co/S3SHqIWLpK \n  　2014年2月で更新が止まっていた。2008年8月から始まっていた様子。アメブロは更新がなくても5年以上残るらしい。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:45／2018-12-23 23:39 URL： https://twitter.com/kk_hirono/status/1076866362482425856 https://twitter.com/hirono_hideki/status/1076849789315080192
&twitter(1076866362482425856){theme:light}
> 落合弁護士ネタ | 堀江貴文オフィシャルブログ「六本木で働いていた元社長のアメブロ」 https://t.co/S3SHqIWLpK \n  　ずいぶん久しぶりに見たブログ。今でも更新されているのかはまだ確認していない。10年近く経つのかもしれない。7年は少なくとも経過していると思う。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜phekka（あるふぇっか） 日時：2018-12-24 00:45／2013-12-26 15:13 URL： https://twitter.com/kk_hirono/status/1076866376176885760 https://twitter.com/phekka/status/416089361499701249
&twitter(1076866376176885760){theme:light}
> 堀江貴文『落合弁護士ネタ』 http://t.co/W2CNI3lrkN
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:45／2013-04-09 00:53 URL： https://twitter.com/kk_hirono/status/1076866392668819456 https://twitter.com/hirono_hideki/status/321289751409868801
&twitter(1076866392668819456){theme:light}
> @amneris84 堀江貴文さんの「正義ほど胡散臭いものはない。」という言葉を思い出すとき、自分はまっさき郷原信郎弁護士の顔がリアルに思い浮かべます。もちろん写真です。お目にかかったことはあるはずもないです。古巣がというのも堀江さんのブログで見たことあります。落合弁護士のこと。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:45／2018-12-23 23:36 URL： https://twitter.com/kk_hirono/status/1076866407323717632 https://twitter.com/hirono_hideki/status/1076849045287518213
&twitter(1076866407323717632){theme:light}
> 堀江貴文　落合　弁護士 - Twitter検索 https://t.co/3cmtYIewK4
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Amb_Now（アメーバなう） 日時：2018-12-24 00:45／2010-01-16 20:56 URL： https://twitter.com/kk_hirono/status/1076866421064294401 https://twitter.com/Amb_Now/status/7824332280
&twitter(1076866421064294401){theme:light}
> RN ホリエモン: ブログ更新です。 検察 vs 小沢 最終戦争にみる司法制度の問題点 - 小沢抹殺を狙う検察官僚の荒々しき国家権力この記事や、ヤメ検弁護士落合氏のtweetにもいくつか問題点が指摘されているが、遂に検.. ☞  #amebanow
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Ikken_t（Tatsuya I.） 日時：2018-12-24 00:45／2010-07-12 00:54 URL： https://twitter.com/kk_hirono/status/1076866435693989889 https://twitter.com/Ikken_t/status/18280264873
&twitter(1076866435693989889){theme:light}
> 落合弁護士が立候補！そしてホリエモンが承認！ｗ QT @takapon_jp 是非！ RT @yjochi: 法務大臣になれば、千葉なにがしよりはマシな法務大臣になる自信はあるのだが。笑
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜LOFTPLUSONE（ロフトプラスワン） 日時：2018-12-24 00:45／2011-05-13 10:55 URL： https://twitter.com/kk_hirono/status/1076866450327928832 https://twitter.com/LOFTPLUSONE/status/68856876250566656
&twitter(1076866450327928832){theme:light}
> お客さんは少なかったけど江川紹子さん＆落合弁護士を迎えての検察トークも印象的だった。今まで思い通りにしてきた堀江さんが、この検察問題は自分の思い通りには動かない。その悔しさが滲み出る内容だった。是非DVDにしたいな～。ホリエモン仮釈放要求署名http://t.co/VKII9Tl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Hideo_Ogura（小倉秀夫） 日時：2018-12-24 00:45／2011-06-20 14:28 URL： https://twitter.com/kk_hirono/status/1076866464953421824 https://twitter.com/Hideo_Ogura/status/82681274766082048
&twitter(1076866464953421824){theme:light}
> 単なるスパム以外、私もブロックしていないけどね。RT @akiosan: @satocharms ふるくは池田信夫w 早川火山学者w 小倉法匪w きょうは落合弁護士w 。。。ホリエモンや津田大介さんはたしかどんな批判を受けてもブロックゼロのはず ʕ•̫͡•ʔ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-24 00:45／2013-07-16 14:14 URL： https://twitter.com/kk_hirono/status/1076866479650304001 https://twitter.com/s_hirono/status/357005204220153857
&twitter(1076866479650304001){theme:light}
> 取材してみたら記事にできそうにない、ということはありがちと思うが、依頼して取材している以上、無礼はいかんだろうな。→ホリエモンが朝日新聞記者に／落合洋司弁護士 http://t.co/rWKPMRVf6n
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜njshojin（ショー） 日時：2018-12-24 00:45／2011-06-19 19:25 URL： https://twitter.com/kk_hirono/status/1076866494296875015 https://twitter.com/njshojin/status/82393493191917569
&twitter(1076866494296875015){theme:light}
> 落合弁護士 @yjochi とホリエモン @takapon_jp の議論にザッと目を通したが、非常に興味深かった。確実に自分よりも見識ある人たちによる議論をリアルタイムで拝見できることが、Twitterの醍醐味の一つであることを再認識した。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:45／2018-12-23 23:32 URL： https://twitter.com/kk_hirono/status/1076866508947505152 https://twitter.com/hirono_hideki/status/1076847969729540097
&twitter(1076866508947505152){theme:light}
> 2011-11-20 https://t.co/R7ckS8G36o \n  　リンクは落合洋司弁護士（東京弁護士会）のはてなダイアリーだったが、はてなのブログとして表示されたらしく、ドメインを確認すると落合洋司弁護士（東京弁護士会）の独… https://t.co/yL9BaKisq8
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:46／2018-12-23 23:27 URL： https://twitter.com/kk_hirono/status/1076866522763583488 https://twitter.com/hirono_hideki/status/1076846801741705216
&twitter(1076866522763583488){theme:light}
> ホリエモン『刑務所の飯はマジで旨い』とTwitterで強がり話題に。 - 弁護士落合洋司（東京弁護士会）の日々是好日 https://t.co/S22EpQkqPn
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜liontaro（T.Inamura） 日時：2018-12-24 00:46／2011-11-20 11:26 URL： https://twitter.com/kk_hirono/status/1076866536550260738 https://twitter.com/liontaro/status/138080820366811136
&twitter(1076866536550260738){theme:light}
> ホリエモン『刑務所の飯はマジで旨い』とTwitterで強がり話題に。 - 弁護士 落合洋司　（東京弁護士会）　の 「日々是好日」 (id:yjochi / @yjochi) http://t.co/xh19VaLr なるほどなぁ、説得力ある！
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Toshimitsu_Dan（だんどじみつ） 日時：2018-12-24 00:46／2014-03-19 23:37 URL： https://twitter.com/kk_hirono/status/1076866551465168896 https://twitter.com/Toshimitsu_Dan/status/446294384456511488
&twitter(1076866551465168896){theme:light}
> それはけしからん。RT @okaguchik: 片山祐輔被告人は，保釈後に，落合弁護士のブログやホリエモンのツイッターは読んだが，俺のツイッターは読んでいないようだ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:46／2018-12-23 23:23 URL： https://twitter.com/kk_hirono/status/1076866566132617216 https://twitter.com/hirono_hideki/status/1076845846816186369
&twitter(1076866566132617216){theme:light}
> ホリエモン　落合　弁護士 - Twitter検索 https://t.co/EuA7TelZk0
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜marx0910（空々空） 日時：2018-12-24 00:46／2018-12-21 12:20 URL： https://twitter.com/kk_hirono/status/1076866579789275136 https://twitter.com/marx0910/status/1075954008924147712
&twitter(1076866579789275136){theme:light}
> 検察は色々怖いとホリエモンと佐藤優氏の本で先入観を抱いてる
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜passykis（PassyKis） 日時：2018-12-24 00:46／2018-12-23 02:52 URL： https://twitter.com/kk_hirono/status/1076866594305785856 https://twitter.com/passykis/status/1076536027479662592
&twitter(1076866594305785856){theme:light}
> 日本の検察の人質司法は確かに批判されて当然だけれど、なぜメディアはゴーンだと毎日取り上げるのか。籠池夫妻、村木厚子氏、ホリエモンの時には沈黙していたくせに。日産を私物化してた人物なのに外圧には弱い？ \n   \n  追い詰められた特捜 「人質司… https://t.co/86aviADPxN
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kuma_sun（くまさん） 日時：2018-12-24 00:46／2018-12-23 10:47 URL： https://twitter.com/kk_hirono/status/1076866608948080640 https://twitter.com/kuma_sun/status/1076655448810352641
&twitter(1076866608948080640){theme:light}
> サンデージャポンで、ホリエモンがゴーン逮捕のくだりで検察側の戦略を語る中、「？？？」って顔して聞いてるニコルの表情が何とも味わい深かった。 \n  この番組、ゲストの得意分野でレベルが違いつつも、それぞれの意見があって、いいキャスティング… https://t.co/dByrbduRaF
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ksk1086（ksk1086） 日時：2018-12-24 00:46／2018-12-17 12:48 URL： https://twitter.com/kk_hirono/status/1076866623607205888 https://twitter.com/ksk1086/status/1074511669441617921
&twitter(1076866623607205888){theme:light}
> ホリエモン生出演！"日産前会長ゴーン事件"を語る 検察・マスコミのあり方  https://t.co/OJw2ivl2I1
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜aozoratosa（MeatTech@自社株買） 日時：2018-12-24 00:46／2018-12-23 14:31 URL： https://twitter.com/kk_hirono/status/1076866638253707264 https://twitter.com/aozoratosa/status/1076711947729395712
&twitter(1076866638253707264){theme:light}
> 有罪に出来れば #検察 の勝ち。#日産 から追い出して有罪にして、その後ゴーン容疑者がどうなろうがどうでもいいと思ってる。虚偽記載が大した罪とかどうでもいい。有罪だけ云々。(ホリエモン
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜d42nxy（ガラスおじさん🌀就活界隈のパパ） 日時：2018-12-24 00:46／2018-12-22 14:12 URL： https://twitter.com/kk_hirono/status/1076866652816388097 https://twitter.com/d42nxy/status/1076344687076696064
&twitter(1076866652816388097){theme:light}
> ホリエモン検察嫌いすぎだろ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜takapon_jp（堀江貴文(Takafumi Horie)） 日時：2018-12-24 00:46／2018-12-21 23:22 URL： https://twitter.com/kk_hirono/status/1076866667399938048 https://twitter.com/takapon_jp/status/1076120630385364992
&twitter(1076866667399938048){theme:light}
> カルロスゴーン前会長の勾留延長を却下についてホリエモンが解説「検察は正月を狙っている」 https://t.co/p1AadQrIJL
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:46／2018-12-23 23:18 URL： https://twitter.com/kk_hirono/status/1076866682356871168 https://twitter.com/hirono_hideki/status/1076844560179855361
&twitter(1076866682356871168){theme:light}
> #サンジャポ　ホリエモン　検察 - Twitter検索 https://t.co/WxWOvHips6 \n  　これも同じだった。自分の5分前のツイート1件のみの検索結果。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:46／2018-12-23 23:17 URL： https://twitter.com/kk_hirono/status/1076866695996747777 https://twitter.com/hirono_hideki/status/1076844328146788352
&twitter(1076866695996747777){theme:light}
> #サンジャポ　堀江　検察 - Twitter検索 https://t.co/26kwi66sRx \n  　こちらも結果は同じ。堀江は堀江氏、堀江貴文氏をどちらも対象にするため。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:46／2018-12-23 23:16 URL： https://twitter.com/kk_hirono/status/1076866709737205762 https://twitter.com/hirono_hideki/status/1076843993508458497
&twitter(1076866709737205762){theme:light}
> #サンジャポ　堀江　特別背任 - Twitter検索 https://t.co/UIBhKeaE5f \n  　この検索ワードの組み合わせだと出てきたのは先ほどの自分のツイートだけ。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜VabXikCdEfz4J5O（カバ子） 日時：2018-12-24 00:46／2018-12-23 10:31 URL： https://twitter.com/kk_hirono/status/1076866723423313926 https://twitter.com/VabXikCdEfz4J5O/status/1076651455187083264
&twitter(1076866723423313926){theme:light}
> 堀江氏 ゴーン氏を日産から追い出してって...追い出したわけではないと思うけど #サンジャポ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:46／2018-12-23 23:13 URL： https://twitter.com/kk_hirono/status/1076866738019434496 https://twitter.com/hirono_hideki/status/1076843304828887040
&twitter(1076866738019434496){theme:light}
> #サンジャポ　堀江 - Twitter検索 https://t.co/lPX3AZXaHV
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-24 00:46／2018-12-23 23:13 URL： https://twitter.com/kk_hirono/status/1076866751873175553 https://twitter.com/hirono_hideki/status/1076843187837095937
&twitter(1076866751873175553){theme:light}
> ハッシュタグ #サンジャポ https://t.co/eS4EOEy45f \n  　今朝の番組の、ホリエモンこと堀江貴文氏の日産元会長のカルロス・ゴーン氏の件に関するツイートは見当たらない。特別背任罪の件はおまけのようなもので、有罪にさ… https://t.co/H3URaVfcZv
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜CybershotTad（Tad） 日時：2018-12-24 00:46／2018-12-23 12:20 URL： https://twitter.com/kk_hirono/status/1076866765567586308 https://twitter.com/CybershotTad/status/1076678884068753408
&twitter(1076866765567586308){theme:light}
> #サンジャポ \n  藤田ニコルさん「ローラさんがつぶやいてくれたきっかけで私もその問題を知ることができた。それがきっかけで若い世代が知ることがめちゃくちゃあります」 \n  ローラの立場では発言の必然性を感じないとか対案がないとかアホな意見があ… https://t.co/zdn1ucRkUX
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜CybershotTad（Tad） 日時：2018-12-24 00:47／2018-12-23 11:58 URL： https://twitter.com/kk_hirono/status/1076866780465836032 https://twitter.com/CybershotTad/status/1076673448678547456
&twitter(1076866780465836032){theme:light}
> 先ほどの #サンジャポ で太田光がとてもよいことを言ってた。 \n  「すべての表現は政治的メッセージを含んでいる。ましてローラのいるファッション業界には政治的メッセージがある。ローラが世界的なファッション業界に出ようという意識があるなら… https://t.co/8gm67bcPn8
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜zCy6KGKag6xGmVx（ひなこ） 日時：2018-12-24 00:47／2018-12-23 10:36 URL： https://twitter.com/kk_hirono/status/1076866795074506752 https://twitter.com/zCy6KGKag6xGmVx/status/1076652750857859072
&twitter(1076866795074506752){theme:light}
> ＃サンジャポ \n  ローラの辺野古署名の件で、西川史子やら堀江貴文らが、「代案がない」「勉強不足」やら批判してますが…「代案ガー」と言った時点で、自分が勉強不足なことさらしてんだけど？
◁◁◁
<hr />

　エラーが出た場合、リツイートしようとした元のツイートの内容を告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)にツイートするつもりだったのですが、スクリプトに処理を加えるのを忘れていました。

　リツイート済み意外にもブロックされているなどして例外（エラー）が出る可能性もあるので、それも踏まえた上の処理にしておいた方が良さそうに思えてきました。

　You have already retweeted this Tweet. ＝＞ https://t.co/4laGVnoo4r

<hr />

　上記のツイートがエラー処理での投稿ツイートになります。次にテストとして確実にブロックされている落合洋司弁護士（東京弁護士会）のアカウントでやってみます。たぶん違ったエラーメッセージが出ると思います。

　You have been blocked from retweeting this user's tweets at their request. ＝＞ https://t.co/B6sZXVGvy0

<hr />

　頂きました、「You have been blocked」というエラーメッセージが返りました。正確なことはわからないですが、「あなたはブロックされています。」という意味なのでしょう。

　投稿されたブラウザのツイートを見ると、翻訳のリンクがあったので実行すると、「あなたは、彼らの要求でこのユーザーのつぶやきをローテーションからブロックされています.⇒」と出ました。

　たぶんうまくいくと思うのですが、リツイートの場合の投稿処理の内容を変えてみました。さきほどタイムラインで確認したモトケンこと矢部善朗弁護士（京都弁護士会）の最新3件のツイート（うち2件リツイート）で試してみます。

　実行する前に、このままではうまく行かないことに気が付きました。元のツイートをリツイートする処理になっているので、リツイートしたアカウントにブロックされているかいないかは無関係になるからです。

　> いつの間にか「レーダー作動してたらP-1が飛び込んで来た」設定がナシになってるんですが、これ日本側が電波記録を録ってたら（録ってますよね）一発即死なのでは…勝算あるの？バカなの？ \n >  \n > https://t.co/7gv1MZmj5S

<hr />
　motoken_tw（モトケン）のリツイート：　ikuyuk（にこ( ´ω` )） 日時：2018-12-24 01:28／2018-12-23 18:49 URL： https://t.co/XRfEwv4s2X https://t.co/m9EOmXo9rf

<hr />
　motoken_tw（モトケン）のツイート 日時： 2018-12-24 01:19 URL： https://t.co/iMfX6UYAhn ＝＞ You have been blocked from retweeting th… https://t.co/5SxmTyll3D

<hr />
　> 腹抱えて笑ってる \n > （鈴木先生はガチの国際政治学者です） https://t.co/ZSJwGrbkHF

<hr />
　motoken_tw（モトケン）のリツイート：　ikuyuk（にこ( ´ω` )） 日時：2018-12-23 19:07／2018-12-22 22:01 URL： https://t.co/IzdCHIv1vW https://t.co/8sDZAxkYM2

<hr />

　時刻は03時00分です。スクリプトを修正し、モトケンこと矢部善朗弁護士（京都弁護士会）の最新3件のツイート（リツイートを含む）を投稿処理しました。やはり誰のリツイートで、どんな内容だったかは誤解の原因ともなりうるので２つのツイートで明示することにしました。

　> こちらにも出演させていただいております（・∀・） \n > これもネットで見られますので、是非是非（・∀・） https://t.co/NrKZ7UIrxN

<hr />
　fukazawas（深澤諭史）のリツイート：　fukazawas（深澤諭史） 日時：2018-12-23 23:43／2018-12-23 20:57 URL： https://t.co/1pJrYwveeW https://t.co/l8PJbIVcvN

<hr />

　上記のリツイートは、深澤諭史弁護士の最新ツイートで、自身のツイートのリツイートとなっています。これもテストしましたが、深澤諭史弁護士の場合は過去のリツイートを取り消して何度でもリツイートを繰り返すことがあります。それでも問題ないとは思います。

　日付が変わっているので昨日のサンジャポは、ホリエモンこと堀江貴文氏が出演していました。この番組は取り上げる内容に応じてゲストを選ぶ傾向がうかがえます。ライブドア事件で有罪から服役までした堀江氏は、かねてより検察に批判的なスタンスを表明してきました。

　それで同じ東京地検特捜部の手がけるカルロス・ゴーン氏の特別背任罪での再逮捕の話題に呼んだのかと考えたのですが、番組の終わりの方では、それとは別に「なんとかまつり」というのを紹介していました。他に見ていないですが、ネットで探せば出てくるはずかと思います。

［link：］ ホリエモン祭【公式】(@hori_fes)さん | Twitter https://twitter.com/hori_fes?lang=ja

　ページトップの固定されたツイートを見て思い出したのですが、サンジャポのテレビでは「ホリエモン万博」と紹介されていたと思います。勘違いで「ホリエモン　祭り」などとGoogleで検索したのですが、Twitterのアカウントが祭の方になっていました。

　Twitterで検索して意外だったのは、落合洋司弁護士（東京弁護士会）が大々的に宣伝している本の帯に、顔写真とコメントを寄稿しているのですが、それに言及したツイートが全く見られなかったことです。あったとすれば私のツイートだったと思います。

　もう一週間から10日ほど経つと思うのですが、いやそれより前かもしれません。落合洋司弁護士（東京弁護士会）は自らのTwitterアカウントのプロフィールの名前まで、その本のものとし、同時にアイコンも本のカバー写真のようなものに変更していました。

　さきほどのスクリプトで最新のツイート3件をリツイート処理していますが、ブロックされているので全てエラー処理での投稿になるでしょう。確認したところ3件とも落合洋司弁護士（東京弁護士会）本人のツイートでした。

　> 世の中に不満持つパヨク系の人って、必ず一定数いるから、労働組合に応援してもらいながら、そういう人たちやシンパをかき集めれば、支持率10パーセント前後の抵抗政党で当面いけるわね。立憲民主は。

<hr />
　yjochi（落合洋司🇯🇵 「ニチョウ  東京地検特捜部特別分室」1月4日発売！）のツイート 日時： 2018-12-24 00:04 URL： https://t.co/B6sZXVGvy0 ＝＞ You have been b… https://t.co/2I42hvtnXY

<hr />
　> 政権は到底無理だろうから、昔の社会党みたいな、存在して抵抗することに意義あり路線だろう。それでも人はそこそこついてくる。→立憲民主・枝野代表「一日も早く政権を取る」　参院選は「野党共闘で勝機あり」 - 産経ニュース https://t.co/3mpAmx5W8b

<hr />
　yjochi（落合洋司🇯🇵 「ニチョウ  東京地検特捜部特別分室」1月4日発売！）のツイート 日時： 2018-12-23 23:59 URL： https://t.co/NFptojbRps ＝＞ You have been b… https://t.co/Lb2VzhQS3b

<hr />
　> こっちも女だな。→立憲民主、参院選京都で会社社長を擁立へ - 毎日新聞 https://t.co/2fA9qW7N2N

<hr />
　yjochi（落合洋司🇯🇵 「ニチョウ  東京地検特捜部特別分室」1月4日発売！）のツイート 日時： 2018-12-23 23:55 URL： https://t.co/qdmxizmoA0 ＝＞ You have been b… https://t.co/3rml0bRTHC

<hr />

　ツイートの処理もリツイートのときと同じく、ツイートの本文を１つのツイートとして引用符付きで投稿するようにしました。リツイートが成功した場合も同様に本文を明示することで同一性を確認できるようにしておこうと思います。そのあとでまたテストします。

　郷原信郎弁護士のツイートを13件ほどスクリプトでリツイートしようと思ったのですが、再度リツイートができなくなるので、思いとどまりました。告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でブロックされていないアカウントです。

　「Could not authenticate you」というエラーが出ました。調べると不吉なことが書いてありました。

　> 『東京パパ友ラブストーリー 』 \n > 樋口毅宏がパパ友のラブストーリーを描いたって！2019年1月25日ころ刊行。是非手に取ってみてくださいね。(こっちはフィクションですよ) \n > https://t.co/YR8HgyY9Rk #Amazon

<hr />
　bi_miwa（三輪記子）のリツイート：　bi_miwa（三輪記子） 日時：2018-12-23 23:22／2018-12-23 22:23 URL： https://t.co/2Sk5d6h1WK https://t.co/7ewEmqPblC

<hr />

　アカウントを変えるとエラーは出ませんでした。ここ1年ほど、もう少し前かもしれないですが、ちょくちょくとテレビの情報番組で姿を見ることのある三輪記子弁護士のTwitterアカウントです。ツイートは久しぶりに見たように思いました。

* リンク法律事務所の紀藤正樹弁護士と、森友学園問題の国会証人喚問で籠池泰典氏の補佐人も務めた山口貴士弁護士、はじまりは銀河鉄道９９９のブログ記事

　投稿済みのツイートからの読み込みで字下げ用の全角スペース１つが付加されていることに気が付き、修正しました。これはもともとスマホからの投稿を想定した処理でした。TwitterAPIの投稿で行頭の全角スペースが消されてしまうからです。

> 週刊 ＊きとうまさき＊の一週間 is out! https://t.co/jq4msILCXC #ゴーン逮捕 #日産

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜masaki_kito（紀藤正樹 MasakiKito） 日時：2018-12-24 04:39／2018-12-23 07:04 URL： https://twitter.com/kk_hirono/status/1076925187667316737 https://twitter.com/masaki_kito/status/1076599445071032323
&twitter(1076925187667316737){theme:light}
> 週刊 *きとうまさき*の一週間 is out! https://t.co/h4q4cI2Qm9 #ゴーン逮捕 #日産
◁◁◁
<hr />

　さきほどのエラーの原因がわかり、対処もしました。紀藤正樹弁護士のツイートだったのですが、ツイートに半角のアスタリスクが含まれていました。通常の投稿だと出来るのですが、TwitterAPIからだと認証段階でではねられるようです。全角文字に置換処理しました。

　絵文字でもないのに全角の日本語の間に半角のアスタリスクを使うツイートはとても珍しいと思います。このタイミングで、そんな珍しいツイートをテスト用に選んだのも不思議なことで、何かの導きがあったのかもしれません。認証エラーで肝を冷やしました。

　紀藤正樹弁護士のツイートを見たのも久しぶりのことで、タイムラインを開くこともほとんどなかったのですが、より注目しているのは同じ事務所という山口貴士弁護士のことです。最新の情報は確認していません。

　あえて最新の情報を確認していないとお断りしたのかというと、北周士弁護士の事務所が変わっていたということが、ここ1,2ヶ月ほどの間にあったからです。

［link：］ まずはお気軽にご相談ください。市民・消費者の立場のリンク総合法律事務所－LINK LAW OFFICE OFFICIAL WEB SITE　東京都千代田区 http://linklaw.jp/

　山口貴士弁護士のTwitterのプロフィールに事務所名とURLリンクがあったものです。これをみると変更はなさそうですが、ずいぶん大世帯の法律事務所なのだと思いました。

　ざっと数えると弁護士が13人、客員弁護士というのが1人名を連ねています。知っている名前は所長の紀藤正樹と山口貴士弁護士だけだと思ったのですが、江川剛という名前の部分の色が前2者と同様に文字の色が変わっていたので、訪問済みのリンクかと最初思いました。

　よく見ると下線も入っていて、名前の文字列にリンクがついている名前はこの3者のみのようです。山口貴士弁護士のリンクは、羽咋市に住んでいた2009年3月以前にも見ていたと思うココログのブログでした。当時は小倉秀夫弁護士もココログのブログを使っていたと思います。

　だいぶん前に取り上げていると思いますが、銀河鉄道９９９の作者、松本零士氏と音楽家、槇原敬之氏の民事裁判を取り上げた記事だけが、とりわけ強く印象に残っています。その当時の生活ぶりや時代背景を含めての感覚です。羽咋市もUFOの町としていました。

［link：］ 弁護士山口貴士大いに語る http://yama-ben.cocolog-nifty.com/ooinikataru/

　こちらはホリエモンこと堀江貴文氏のアメブロのブログとは違い、現在も更新が続いているようです。今月の2018年12月は2件と少ないようですが、最終更新が9日となっていることがカレンダーのリンクの日付で確認されました。

　トップページにいたのをスクロールダウンさせていくと、次の記事が目につきました。そんなにスクロールはしなかったですが、昨年の2017年4月3日の投稿記事のようです。

［link：］ 籠池氏の代理人として提出した平成２９年３月３１日付抗議書　テキストベタ打ち版： 弁護士山口貴士大いに語る http://yama-ben.cocolog-nifty.com/ooinikataru/2017/04/post-c7a1.html

　時刻は5時13分となり、しばらくすると夜も明けそうですが、今夜は森友学園問題と縁があるようです。日付では昨日になるかもしれないですが、菅野完氏の訴訟代理人となった三浦義隆弁護士、そして籠池氏の補佐人（保佐人？）の山口貴士弁護士の関係は私において謎のままです。

* 壇弁護士がブーケを受け取ったという、北周士弁護士のノースの椿事と呼ばれた結婚式、多くの法クラの出席者

　そういえば、今夜は久しぶりに団弁護士のツイートも見かけ、それも気になる内容でした。初めに山口貴士弁護士のココログのブログを見た頃というのは、Winy裁判が世間の注目で団弁護士が中心のように弁護活動をしていたようです。同じ頃にそのブログの方も見ていました。

［link：］ Winny事件弁護団祝勝会： 壇弁護士の事務室 http://danblog.cocolog-nifty.com/index/2012/01/winny-c68b.html

　WinyではなくWinnyで、団弁護士ではなく壇弁護士だったのですが、Googleでは「Winy　団弁護士」でこのブログが見つかりました。見るとこちらもココログニフティのドメインとなっていますが、山口貴士弁護士のブログと同じようにテキスト本文の表示幅が狭くなっています。

［link：］ タトゥー裁判控訴審逆転無罪判決： 壇弁護士の事務室 http://danblog.cocolog-nifty.com/index/2018/11/post-c626.html

　上記が最新記事のようです。今年2018年の11月15日となっています。数えると文字の横幅は30文字となっていました。私の記憶では壇弁護士は大阪の弁護士なのですが、「ノースの椿事」と呼ばれた北周士弁護士の結婚式の写真では、ブーケを受取り満面の笑みだったのが印象的でした。

　それとは別に岡口基一裁判官が大勢の弁護士らと撮影された集合写真をネットで見かけ、そこにも壇弁護士と見られる人物の姿があったように思うのですが、ずいぶんと前のことであり、正確な情報としては未確認です。20,30人の集まりであったとも記憶にはあります。

　8月の記事を探していたのですが、画面の一番左下に「バックナンバー」という項目があって、全部で10のリンクがあります。8月は10日、22日、29日の３つですが、富田林警察署の接見室からの逃走事件についての投稿はないようです。同じ10件の最近の記事にもそれらしいのは見当たりません。

　もう5年ほど前になるようにも思いますが、何かの社会的な問題で、衝撃的に考えさせられる内容をこの壇弁護士のブログで読んだという記憶が残っています。Twilogで調べれば見つかるかもしれないですが、また機会があればと思います。

［link：］ ハッシュタグ #ノース春の椿事 https://twitter.com/hashtag/%E3%83%8E%E3%83%BC%E3%82%B9%E6%98%A5%E3%81%AE%E6%A4%BF%E4%BA%8B

　画像で検索すると出てきたのですが、ずいぶん久しぶりに見る写真や動画です。ずいぶん前に調べたときは見えなかったので、削除されたのかとも考え、それ以上探し回ることもありませんでした。また色々と発見はありましたが、その都度取り上げていると際限がなくなってしまいます。

　ツイートの日付を見るとほとんどが2016年4月2日となっていますが、もう1,2年前の同時期のことかと思っていました。深澤諭史弁護士のアカウントを知る前かもしれないと思っていたぐらいです。先日2014年のスクリーンショットを発見したように思います。

　すっかり忘れていた弁護士アカウントのツイートも見つけたのですが、どうも告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントではブロックされていないようです。

　今月の17日、14日というツイートもあるのですが、ずいぶん長い間、他のタイムラインでもリツイートとしてツイートを見かけずにいたものです。自然消滅のようなかたちで記憶から消えてしまうところでした。消えていた蝋燭に火が灯ったような気分にもなります。今日はクリスマスイブでした。

　タイムラインを遡り、7月24日のツイートまで辿りついたのですが、こちらも大阪の富田林警察署の接見室からの逃走事件に触れたツイートは見当たりませんでした。ざっと目を通しただけですが、特に違和感や非常識さを覚えなかった弁護士のTwitterタイムラインは珍しいです。

　とりわけすごいと思ったのが、昨夜のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートでした。落合洋司弁護士（東京弁護士会）とは違い直接ではないようですが、内容はそれ以上のものを感じる郷原信郎弁護士に向けた批判のようです。

▶ ツイート％motoken_tw（モトケン）％2018/12/24 01:19％ https://twitter.com/motoken_tw/status/1076874921031098368
&twitter(1076874921031098368){theme:light}
> @ESQ_JPN 古巣憎しなのかどうかわかりませんが、検察を批判することばかりを考えて目が曇っているみたいで、ものすごく頭が悪そうに見えます。  
▶

　郷原信郎弁護士に関しては最高裁まで争った藤井美濃加茂市長事件のときに、同業者の弁護士から疑問が出なかった方が私としては不思議なぐらいなのですが、カルロス・ゴーン氏のことは桁違いの資産家でもあるようなので、他の事件とは気合の入り方がまるで違うのかもしれません。

　一見すると手厳しい批判にみえる、上記のモトケンこと矢部善朗弁護士（京都弁護士会）の郷原信郎弁護士に向けた内容のツイートも、本質から目をそらせることを狙った意図があるようにも感じられますし、検察批判に燃料をふり注いでいるようにも思えてきます。

　プロというのは一度にたくさんのことを考えて処理を出す、というような趣旨のツイートをモトケンこと矢部善朗弁護士（京都弁護士会）がやっていたことも思い出しました。プロでまとめた記事があって、そこにあると思いますが、数が多いのですぐにはみつからないかもしれません。

＜＜＜2018-12-24（月曜日）06：30＿［これまでの記述範囲の終了時刻］＜＜＜

* REGEXP：”ローラ．＊辺野古”／データベース登録済みツイート：2018年12月24日06時43分の記録：ユーザ・投稿：30／86件

　最終的なデータの全体更新が「2018年 12月 23日 日曜日 13:21:50 JST」ということで、いくらか時間に開きが出ているのですが、まとめ記事を制作しました。弁護士と若干のジャーナリストのツイートをデータベースに記録したものから抽出したデータです。

```
［link：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”ローラ．＊辺野古”／データベース登録済みツイート：2018年12月24日06時43分の記録：ユーザ・投稿：30／86件 http：//hirono2014sk.blogspot.com/2018/12/regexp2018122406433086.html
REGEXP（サーチ）： "ローラ.*辺野古"　該当：86件　取得ツイートの投稿日時の範囲：（2018-12-18 12：36〜2018-12-23 12：22）

SELECT * FROM tw_user_tweet WHERE tweet REGEXP "ローラ.*辺野古" ORDER BY tw_date ASC

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”ローラ．＊辺野古”／データベース登録済みツイート：2018年12月24日06時43分の記録：ユーザ・投稿：30／86件 http://hirono2014sk.blogspot.com/2018/12/regexp2018122406433086.html
```

```
アカウント名	ツイート数	リツイート数
問題解決のお手伝い業者（okinawabengoshi）	0	4
／友弘　克幸＼（ktyk_TOMOHIRO）	0	2
弁護士　戸舘圭之（todateyoshiyuki）	0	1
高木良平（ryouheitakaki）	0	4
平　裕介（YusukeTaira）	1	0
鳩屋（haya_rt）	0	1
Kazuko Ito 伊藤和子@神楽坂　ミモザの森法律事務所（KazukoIto_Law）	1	1
川口創（kahajime）	0	1
三毛猫B（poorpartner）	0	1
山口一臣（kazu1961omi）	0	3
尾林 芳匡（YOSHIMASAOBAYAS）	0	2
ぽぽひと@常時発動型煽りスキル持ち（popohito）	0	7
嶋﨑量（弁護士）（shima_chikara）	0	1
弁護士 星　正秀（hoshimasahide）	0	4
嘘つき弁護士。（LiarLawyer800）	0	2
本田 正男（adnoh7）	0	1
弁護士あだちけいた ボヘミアン・ラプソディ4回観戦（keita_adachi）	0	2
丙弁（heibenn）	0	1
清水 潔（NOSUKE0607）	0	1
comedyofZ（comedyofZ）	0	28
津田大介（tsuda）	0	2
弁護士 太田啓子（katepanda2）	0	4
?朕朕（un_co_the2nd）	0	1
青木　俊（AokiTonko）	0	1
三輪記子（bi_miwa）	0	1
藤本一郎 Fujimoto Ichiro（ifujimoto）	0	1
指宿昭一（ibu61）	0	2
長尾　忠昭（tadaaki_n）	0	1
ささきりょう（ssk_ryo）	1	2
深井 剛志（TSUYOSHIFUKAI）	0	1


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”ローラ．＊辺野古”／データベース登録済みツイート：2018年12月24日06時43分の記録：ユーザ・投稿：30／86件 http://hirono2014sk.blogspot.com/2018/12/regexp2018122406433086.html
```

▶（01／86） RT okinawabengoshi（問題解決のお手伝い業者）｜BFJNews（BuzzFeed Japan News） 日時：2018-12-18 12:36:00 +0900／2018-12-18 12:00:00 +0900 URL： https://twitter.com/okinawabengoshi/status/1074871114516459520 https://twitter.com/BFJNews/status/1074861879628042241
{% tweet 1074871114516459520 %}
> タレントのローラさんが、自身のインスラグラムに「みんなで沖縄をまもろう！」と投稿しました。呼びかけたのは、ホワイトハウスに向けた「辺野古の埋め立て中止」を求める嘆願書への署名です。（籏智広太 @togemaru_k） \n \n 【New】… https://t.co/8TqtGGwoss

　私がデータベースに記録したデータでは、上記の12月18日12時00分の元のツイートが、最初に出たキーワード２つのキーワードを含むツイートだったようです。テレビで取り上げられているのを見るようになったのは、ここ2,3日のようにも思うのですが、勘違いかもしれません。

▶（07／86） TW KazukoIto_Law（Kazuko Ito 伊藤和子@神楽坂　ミモザの森法律事務所） 日時： 2018-12-19 09:13:00 +0900 URL： https://twitter.com/KazukoIto_Law/status/1075182299619090432
{% tweet 1075182299619090432 %}
> ローラさんが辺野古移設反対　インスタで署名呼びかけ（産経新聞） - Yahoo!ニュース https://t.co/LQ8fYUzPhi @YahooNewsTopics

　伊藤和子弁護士のTwitterアカウントのようですが、いつの間にかプロフィールの名前が変わっていたように思います。「ミモザの森法律事務所」というのも、なんとなく森の妖精をイメージさせるメルヘンチックな名称です。

▶（64／86） TW ssk_ryo（ささきりょう） 日時： 2018-12-22 12:04:00 +0900 URL： https://twitter.com/ssk_ryo/status/1076312462847139840
{% tweet 1076312462847139840 %}
> ローラさんの辺野古工事阻止10万筆署名賛同こそ、真の保守であり愛国者だ(古谷経衡) - Y!ニュース https://t.co/8J9zLasvu7

　上記の佐々木亮弁護士のツイートは、リンクの記事のタイトルをそのまま引用しただけのようです。記事の記者の名前のようなものもありますが、初めて見る名前と思います。作業も足早に進めているので、リンクの記事を読むことも開くこともありません。

▶（86／86） RT popohito（ぽぽひと@常時発動型煽りスキル持ち）｜yagainstfascism（YAF） 日時：2018-12-23 12:22:00 +0900／2018-12-23 10:57:00 +0900 URL： https://twitter.com/popohito/status/1076679463151140864 https://twitter.com/yagainstfascism/status/1076657954550509569
{% tweet 1076679463151140864 %}
> サンジャポ。ローラさんの辺野古埋立反対署名呼びかけについて。「勉強不足、解決策がないのに言うな」的な間抜け発言も出る一方、藤田ニコルさんは「ローラさんが呟いてくれたきっかけで私もその問題を知ることが出来ました」「ローラさんの呟きで… https://t.co/bj7FwShPs3

　ざっとページをスクロールダウンしながらみてきましたが、ほとんどがリツイートのようでした。突っ込んだ弁護士の意見表明を期待しただけに残念な結果です。賛否両論は大きいかと思います。同じサンジャポでも英語が完璧すぎて誰かに利用あるいは洗脳されている可能性が指摘されていました。

　今は、ほとんどCM契約だけやっているので、CMのスポンサーとの関係をこじらせるリスクが大きいという意見もサンジャポでは出ていたと思いますが、ネットでは余り見ておらず、この記録にも出てこなかったように思います。なお、思考力も低下気味の状態ではあります。

* REGEXP：”サンジャポ．＊（堀江貴文｜ホリエモン｜堀江氏）”／データベース登録済みツイート：2018年12月24日07時15分の記録：ユーザ・投稿：1／4件
  :LOGBOOK:
  CLOCK: [2018-12-24 月 07:18]
  :END:

＞＞＞2018-12-24（月曜日）07：18＿［これからの記述範囲の開始時刻］＞＞＞

　これはあとで、データ全体を更新してからやり直したいと思っています。更新には30分弱掛かると思います。開始しました。更新処理です。

```
REGEXP（サーチ）： "サンジャポ.*(堀江貴文|ホリエモン|堀江氏)"　該当：4件　取得ツイートの投稿日時の範囲：（2018-12-23 23：09〜2018-12-23 23：18）

SELECT * FROM tw_user_tweet WHERE tweet REGEXP "サンジャポ.*(堀江貴文|ホリエモン|堀江氏)" ORDER BY tw_date ASC

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”サンジャポ．＊（堀江貴文｜ホリエモン｜堀江氏）”／データベース登録済みツイート：2018年12月24日07時15分の記録：ユーザ・投稿：1／4件 http://hirono2014sk.blogspot.com/2018/12/regexp20181224071514.html
```

▶（1／4） RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜zCy6KGKag6xGmVx（ひなこ） 日時：2018-12-23 23:09:00 +0900／2018-12-23 10:36:00 +0900 URL： https://twitter.com/hirono_hideki/status/1076842134668374016 https://twitter.com/zCy6KGKag6xGmVx/status/1076652750857859072
{% tweet 1076842134668374016 %}
> ＃サンジャポ \n ローラの辺野古署名の件で、西川史子やら堀江貴文らが、「代案がない」「勉強不足」やら批判してますが…「代案ガー」と言った時点で、自分が勉強不足なことさらしてんだけど？

　私が最初にリツイートをしたのは12月23日10時36分だったようです。さきほどの18日とはだいぶん開きがあります。

　考えてみると23日というのは昨日の日曜日のことで、10時36分というのはサンジャポの放送中の時間でした。その前にもテレビでは見かけていましたが、それほど大きな問題としては取り上げられてはいなかったと思います。ネットで少し見かけていたかもしれません。

▶（2／4） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2018-12-23 23:13:00 +0900 URL： https://twitter.com/hirono_hideki/status/1076843187837095937
{% tweet 1076843187837095937 %}
> ハッシュタグ #サンジャポ https://t.co/eS4EOEy45f \n 　今朝の番組の、ホリエモンこと堀江貴文氏の日産元会長のカルロス・ゴーン氏の件に関するツイートは見当たらない。特別背任罪の件はおまけのようなもので、有罪にさ… https://t.co/H3URaVfcZv

▶（3／4） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2018-12-23 23:17:00 +0900 URL： https://twitter.com/hirono_hideki/status/1076844328146788352
{% tweet 1076844328146788352 %}
> #サンジャポ　堀江　検察 - Twitter検索 https://t.co/26kwi66sRx \n 　こちらも結果は同じ。堀江は堀江氏、堀江貴文氏をどちらも対象にするため。

▶（4／4） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2018-12-23 23:18:00 +0900 URL： https://twitter.com/hirono_hideki/status/1076844560179855361
{% tweet 1076844560179855361 %}
> #サンジャポ　ホリエモン　検察 - Twitter検索 https://t.co/WxWOvHips6 \n 　これも同じだった。自分の5分前のツイート1件のみの検索結果。

　時刻は12月24日07時29分となっていますが、昨夜、日付が変わる前からテレビはつけていないと思います。余りテレビを見たいという気分ではなく、まったく予定していなかった徹夜となっています。朝方はかなり冷え込んでもいます。

　サンジャポは11時20分には放送が終わり、次の他の番組が始まっていたように思います。スマホで撮影したテレビの画面で確認すると、11時15分の時点ではまだサンジャポの放送中でした。11時31分の時点では、JNNニュースが始まっていました。

　その11時33分の撮影写真にはテレビの画面のテロップに「”私的”損失　独断で日産に負わせたか　東京地検特捜部　ゴーン容疑者が経営への強い影響力を背景に日産を「私物化」していたとみて操作」記録されています。

　まるでサンデーモーニングやサンジャポことサンデージャポンの放送終了を見越し狙ったかのようなテレビニュースでした。この辺りも内容では、警察のリークなどとモトケンこと矢部善朗弁護士（京都弁護士会）辺りから批判が出そうですが、そういうのも見てはいません。

　テレビドラマはもう何年も見たことがないとツイートしていたモトケンこと矢部善朗弁護士（京都弁護士会）ですが、テレビの報道番組や情報番組についてツイートしているのも見たことがなく、テレビを見ているのかどうかも、本人でないとわかりようのない事実です。

　処理でエラーが出ていました。確認すると次の弁護士アカウントがまた1つTwitterから消えたようです。リンクを開くと存在しないアカウントなどとエラーが出ていました。昨日の13時の段階ではエラーは出ていなかったと考えられます。

```
たけるbot (@bexa930) | Twitter
https：//twitter.com/bexa930
The latest Tweets from たけるbot (@bexa930). 富山の弁護士/基本憲法の著者/季刊刑事弁護第14回新人賞最優秀/の人物と同姓同名の個人アカウント/情報発信専用/発言は本人やその所属する組織とは一切関係ありません/本人への勉強法の質問 ...

［source：］bexa930 - Google 検索 https://www.google.co.jp/search?source=hp&ei=HhIgXLrRJpb8wQP4m7DQDg&q=bexa930&btnK=Google+%E6%A4%9C%E7%B4%A2&oq=bexa930&gs_l=psy-ab.3..0.1921.1921..3767...0.0..0.341.417.1j3-1......0....1j2..gws-wiz.....0.2JuJxr2rqQ8
```

　次のアカウントのデータ処理でもエラーが出ていましたが、時間内でのツイートの更新件数が多すぎたのではなく、プロフィールの名前を変更したことがエラーの原因ではと思われます。

```
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
指定アカウントの最新199件のツイート
2018-12-11 22：51から199件：最新2018-12-23 23：11という範囲（12日0時間20分）の取得

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＃当職ぴっぴ@痛風と痔　@emeth_pippi＃のツイート／2018-12-11_2251〜2018-12-23_2311／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月24日08時05分 http://hirono2014sk.blogspot.com/2018/12/emethpippi2018-12-1122512018-12.html
```

　もう一つかれこれ半年ほど前からエラーが出たままにしているTwitterアカウントがあるのですが、岩手県の実名の女性弁護士です。どうもTwitter社からロックか凍結をされたようですが、ホームページなどをみても原因がまるで検討のつかない女性弁護士でした。

```
このアカウントのツイートは非公開です。
@yokowatanabeさんから承認された場合のみツイートやプロフィールの表示ができます。［フォローする］ をクリックすると承認リクエストが送信されます。

［source：］Yoko Watanabe(@yokowatanabe)さん | Twitter https://twitter.com/yokowatanabe
```

　以前は違ったように思いますが、改めて調べると、アカウントが非公開となっていました。納得の出来ない検索結果です。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-24 08:21／2018-12-24 08:19 URL： https://twitter.com/kk_hirono/status/1076981116974772224 https://twitter.com/s_hirono/status/1076980747855028224
&twitter(1076981116974772224){theme:light}
> 2018-05-11-063100_渡部　容子　（@yokowatanabe_）。　岩手県盛岡市の弁護士、ビギナーズ・ネット初代代表です。.jpg https://t.co/Shf2BnN15I
◁◁◁
<hr />

　探し出したスクリーンショットを非常上告-最高検察庁御中_ツイッター（@s_hirono）に投稿し、それを上記にリツイートしましたが、やはり「凍結済みアカウント」と表示が出たスクリーンショットとなっています。

　せっかく見つけたスクリーンショットでしたが、ファイル名の付け方も状況に対応しておらず、Twitterでは文字が小さくて見づらかった画像をダウンロードして画像ビューアで拡大したところ、URLにアカウントの特定する情報は含まれていませんでした。

　岡口基一裁判官の凍結されたアカウントもあるいは同じだったのかもしれません。とりいそぎ、再度調べてみます。

　スクリーンショットをとるまでもなく結果は同じでした。URLが同じなので、どのアカウントが凍結済みアカウントなのか特定の仕様もありません。スクリーンキャストの動画としてリンクからの遷移を記録しても、さほど意味があるとは思えないことです。

```
凍結済みアカウント
このアカウントは凍結されています。アカウントの凍結についてはこちらをご覧ください。タイムラインに戻る場合はこちら。

［source：］Twitter / アカウント凍結 https://twitter.com/account/suspended
```

　「凍結済みアカウント」であって「永久凍結」とは違うようです。これも確認をしておきたいと思いますが、思い当たるのは菅野完氏のアカウントしかありません。

　なお、次のページが岡口基一裁判官のTwitterアカウントを探し当てたページです。凍結から時間が経過したためか、通常のリンクとしてはGoogleの検索結果には見えなくなっていました。

［link：］  https://meyou.jp/okaguchik

　今度は、ページタイトルのないURLのようです。あるいは半角スペース一文字がページタイトルとされているのかもしれません。それ意外に私の知識と経験では思い当たる節がないですが不思議なことです。

