#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "参考資料／弁護士業界の現状／高島章弁護士（新潟県弁護士会）／「金玉神社」、「金玉踊り」、「刑事訴訟愛好会」（フェイスブック）をキーワードに含む2017-02-27の記録"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-11-21 16:49:01 +0900
FILE_NAME: 2018-11-21-164901_「金玉神社」、「金玉踊り」、「刑事訴訟愛好会」（フェイスブック）をキーワードに含む2017-02-27の記録.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  高島章弁護士（新潟県弁護士会） 刑事訴訟愛好会 スクリーンショットの記録
記事タイトル名の文字数：84　保存ファイル名の文字数：76

#contents

* 前回のエントリー、TwitterAPIの半角アスタリスクの問題

[link:] 2018年11月21日16時30分の登録： 告発に至る経緯／書面作成／パソコン／告発状開発環境としてのAtomエディタ http://hirono2017kk.blogspot.com/2018/11/atom.html

　上記の前回エントリーで書き忘れていたのですが、１１月１７日に中断をした原因は、AtomエディタからのTwitterへの投稿で、見出しとなる行頭の半角アスタリスクの入った行の投稿が出来なかったことです。javascriptの特殊文字の処理に問題があるものと思い込みました。

　あとになってわかったことですが、Emacsの環境でも同じく半角アスタリスクの入った行は投稿が出来ていませんでした。つまりTwitterAPIで半角アスタリスクの含まれたツイートを受け付けず、弾くという仕組みになっていたようです。

　調べてもそれらしい情報は見つかりませんでしたが、行頭だけではなく１つでも半角のアスタリスクが含まれていると投稿は出来ず、エラーが返っていました。

　「Could not authenticate you.」というのがTwitterAPIから返されたエラーメッセージだと思われるものです。Googleで調べると、別の原因によるエラーという情報ばかりなのですが、スクリプトで半角アスタリスクを置換処理することで問題は解決しました。

▶ ツイート％kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）％2018/11/21 17:15％ https://twitter.com/kk_hirono/status/1065156810431062016
&twitter(1065156810431062016){theme:light}
> ああああ*aaa
▶

　ブラウザのTwitterから投稿したのが上記のツイートですが、半角のアスタリスクは、そのまま受け付けられているようです。プログラムの処理で半角アスタリスクは全てを処理の対象とすることがあるので、危険な特殊文字であることは納得ですが、時間を沢山つぶしました。

* Linuxのlocateコマンドを使ったスクリーンショットのファイルの一括コピー

>|sh|
locate -r ".*2017-02-27-.*" | xargs -i cp -p {} ./
||<

　事前に作成した仮の作業用ディレクトリで上記のコマンドを実行しました。これでパソコン内の検索ファイルをまとめてコピーすることが出来ます。検索結果はもちろん事前に確認しています。

　次が上記の作業で作業用ディレクトリにコピーしたファイルの内容になります。

```
2017-02-27-072416_日弁連の依頼者見舞金制度議案について、新潟県弁護士会としては反対票を投じることになりました。日弁連会則39条1項により、日弁連総会では各弁護.jpg
2017-02-27-083256_また懲戒請求されると大変なので，もう辞める。明日は金玉神社にお参りしよう。.jpg
2017-02-27-083334_放送大学。だったら，宗教社会学で，「金玉神社の研究」でも修士号がもらえるだろうな？.jpg
2017-02-27-083408_「金玉神社」の研究をしたいのだが，國學院大學や皇學館大学で紀要とかないかなぁ。金玉博士の学位をもらいたい。.jpg
2017-02-27-083445_仙台には，金玉神社や金玉稲荷神社はないのだろうか？　すれ違う女性は不細工なデブばかりだ。.jpg
2017-02-27-083514_「金玉神社」「綺麗な金玉神社」「金玉稲荷神社」の代理人をやりたいのだが，いかんせん依頼がない。.jpg
2017-02-27-083600_「金玉神社に関する一考察」という論文で神学博士か宗教学博士の学位をもらって，牧師か神主になろうと思っている今日この頃。.jpg
2017-02-27-083642_でも当職が作詞作曲した「綺麗な金玉神社の歌」を歌うと，やっぱり公然わいせつ罪等になり，まずいだろうなぁ。.jpg
2017-02-27-083729_金玉神社というのは，実在する神社です。そこの神社の近くに沼があって，ザリガニ釣りをしたものです。（小学校時代）.jpg
2017-02-27-084041_誰かメンバーになってくれないか？　「金玉稲荷神社奉賛会」でも良いのだが・・・。.jpg
2017-02-27-094201_私は本当に生々しい衝撃を受けた（新発田強姦致死事件　その当時は，強姦+殺人＝死刑の起訴を検察は検討していた）。.jpg
2017-02-27-094428_春はわいせつ，夏は強姦，秋は殺人，冬は放火。当番弁護士の罪名別季節変動。.jpg
2017-02-27-095156_「刑罰とは何か？」という根本問題は、宗教と切り離せない問題です。.jpg
2017-02-27-095318_つまり，「死刑」は遺族や死者の応報感情で正当性を基礎づけられないということではありませんか？.jpg
2017-02-27-095457_「当然だ！」とか「法治国家」などといって，快哉を叫ぶ人たちはどうかしていると思う。.jpg
2017-02-27-112525_私の引用を私の発言と誤読したことを素直に認めればすむ話なのに、「問題は引用の仕方です。」とか言い出すから見苦しくなる。.jpg
2017-02-27-113951_法実務家（裁判官・検察官・弁護士）や関連する職（司法精神医学，法廷通訳等），大学等における研究者に限定した会議室です。.jpg
2017-02-27-114123_@motoken_tw　刑事訴訟愛好会のメンバー資格は、日本刑法学会のそれに準じており（研究者・実務家、研究大学院博士課程後期以上、司法試験.jpg
2017-02-27-114437_@motoken_tw　私が創立し管理者の一人である「刑事訴訟愛好会」ですね。現在会員数５３４名。.jpg
2017-02-27-115859_刑事訴訟愛好会（フェイスブック）こそ，救いの鍵です。野田先生も必殺異議仕置人　佐藤正子先生もご加入です。.jpg
2017-02-27-121142_民間研究者のご様子ですが，刑事訴訟愛好会の会員資格の認定が出来ます（刑事訴訟だけでなく，刑罰論や刑事政策の話も出来ます）。facebokから.jpg
2017-02-27-121329_@nodahayato：　刑事訴訟愛好会なるものに加入してみた。僕は，刑事訴訟法愛好家であって，刑事訴訟愛好家ではないと思うのだけれども。.jpg
2017-02-27-134825_共謀罪法案を審議しようという時期に、あんな（少なくとも法律論的に）無能な人間を法務大臣に任命した安倍総理に、本気で法案を成立させるつもりがあ.jpg
2017-02-27-191051_〈警察官の偽証は闇から闇へ葬られる〉〈刑事裁判における不正義について、法務検察と裁判所において、再発防止を具体的に検討したふしはない〉.jpg
2017-02-27-192006_「国民は法に従うべし。犯罪をなすべからず」という言葉は「法治国家」とは無縁です。これは、「云々」を「でんでん」と読むくらいの恥ずかしい間違い.jpg
2017-02-27-193143_ポケGOをやりながらの事故でも沖縄タイムスを読みながらの事故でも量刑に変わりはないと思う。.jpg
2017-02-27-193202_ポケGOをやりながらの事故でも沖縄タイムスを読みながらの事故でも量刑に変わりはないと思う。.jpg
2017-02-27-202850_某警察署の受付のところに、「書類の作成代行は行政書士しかできません」という趣旨の掲示があるんだ…　問題にしたいけど署内なのでさすがに無断で写.jpg
2017-02-27-203311_まさにこれ.jpg
2017-02-27-203535_被疑者を呼び出して取り調べたところ結局その被疑者を犯人と証明する資料が得られなかったとしても、何の結果責任をとらされませんよ。RT.jpg
2017-02-27-204221_警察官や検察官は身が持ちませんね。RT　.jpg
2017-02-27-205026_行政府を監督するのは国会議員の重要な職務ですよ。RT　.jpg
2017-02-27-205225_！！RT　@o2441：　小倉先生とローカス先生以外の弁護士は信用できない。　—　Σ（ﾟДﾟ）ｶﾞｰﾝ.jpg
2017-02-27-210015_小倉先生とローカス先生以外の弁護士は信用できない。Σ（ﾟДﾟ）ｶﾞｰﾝ.jpg
2017-02-27-210303_渡辺輝人@nabeteru1Q78　　1時間1時間前　￼Hootlet￼　その他渡辺輝人さんが宮武嶺をリツイートしましたんだんだ。.jpg
2017-02-27-210555_弁護士　野田隼人　Retweeted￼深澤諭史@fukazawas　　2014年8月26日　￼Hootlet￼　その他　企業法務ネタを一つ.jpg
2017-02-27-210637_うちの客を持ってったのは君か！？”@yasumasa218：　弁護士は事務所より弁護士個人に客がつく傾向が顕著で、代替わりはものすごく難しそ.jpg
2017-02-27-210900_私のIT屋としての立ち位置は多分，SEなんだけど，これは自分で設計もコードのイメージができる状況の中で，ただコードを書くのがめんどくさいとい.jpg
2017-02-27-211033_大山定伸@oyamalawS51大阪市生野区生まれ。法務博士。弁護士。ウリは「分かりやすいシャベリ」　大阪市立巽小学校卒／愛媛県愛光学園中学.jpg
2017-02-27-211115_国の土地というのは国の根本である。それを不当に安い値段で売買しているとすれば、まさに売国奴ではないか。私と同じ右派の皆さんが、国の根本を揺る.jpg
2017-02-27-212014_なぜ幻に終わったのか。→東京新聞：大阪女児焼死　最高裁判事が「冤罪」意見　退官で書面が幻に：社会（TOKYO　Web）.jpg
2017-02-27-214546_プロに任せたほうがいいということです。民事訴訟はゲームなのだから、ゲームのルールに精通している人間がプレイするほうがいいに決まっている。（木.jpg
2017-02-27-214617_民事訴訟はゲームなのだから、ゲームのルールに精通している人間がプレイするほうがいいに決まっている。（木山泰嗣弁護士）.jpg
2017-02-27-215056_毎月6万近い会費でシャンパンタワーやった泥棒弁護士の尻拭いをするのか。弁護士になって心からよかったと思うよ〔棒.jpg
2017-02-27-215220_裁判員制度なんか教えんでいい。裁判所が選定された人に教えてくれるからね。それよりも刑訴法の基本原則だよ。でもこれ教えると、裁判員制度っておか.jpg
2017-02-27-222333_こういう時に安倍首相と飯食いに行く奴はジャーナリストを名乗る資格はない。　／　他5コメント.jpg
```

　ターミナルの画面で見ているとファイルの数は３０もないぐらいだと思っていたのですが、ツイートとしていると数が多いと感じ、「% ls -1|wc -l」というコマンドで確認すると４６ありました。
