#+TITLE: "検事総長が６月２０日付で、確定判決の誤りを正す「非常上告」の手続きを最高裁に対してとった。水戸地検の横井朗次席検事は"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-12 11:09:15 +0900
FILE_NAME: 2019-08-12-110915_検事総長が６月２０日付で、確定判決の誤りを正す「非常上告」の手続きを最高裁に対してとった。水戸地検の横井朗次席検事は.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 非常上告  ジャーナリストの江川紹子氏
記事タイトル名の文字数：58　保存ファイル名の文字数：80

* 検事総長が６月２０日付で、確定判決の誤りを正す「非常上告」の手続きを最高裁に対してとった。水戸地検の横井朗次席検事は
  :LOGBOOK:
  CLOCK: [2019-08-12 月 11:11]--[2019-08-12 月 12:07] =>  0:56
  :END:

＞＞＞2019-08-12（月曜日）11：11＿［これからの記述範囲の開始時刻］＞＞＞

　ジャーナリストの江川紹子氏のタイムライン、ジャーナリストの江川紹子氏のリツイートから知りました。まれに非常上告があることは知っていましたが、このようにリアルタイムでニュース記事になっているのは初めて見たかもしれません。

```
　水戸地検は９日、検察官による誤った法令の解釈が原因で道路交通法違反の略式命令に至ったとして、最高裁判所がこの略式命令を取り消す判決を言い渡した、と発表した。

　地検によると、判決は同日付。罰金刑を受けた対象者は２０１０年４月、境町の道路で、牽引（けんいん）免許がないのに小型特殊自動車（トラクターなど）を使って車両を牽引したとして、古河区検によって道交法違反（無免許運転）の罪で略式起訴された。古河簡裁もそのまま略式命令を出し、対象者は罰金２５万円を納付した。

　ところが今年３月、同種の事案を調べていた際に、小型特殊自動車による牽引には牽引免許が不要だと気づき、誤認だったと判明したという。

［source：］水戸地検が道交法の解釈誤り、罰金に　最高裁が取り消し：朝日新聞デジタル https://www.asahi.com/articles/ASM895STPM89UJHB00J.html?iref=pc_ss_date
```

　2010年4月の事件で、今年3月になって同種事案を調べていた際に誤認が判明したとのことです。「検察官による誤った法令の解釈」とあり、略式命令ともあるので副検事が担当した案件という可能性が高そうに思いました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2019-08-12 11:20／2019-08-11 22:54 URL： https://twitter.com/kk_hirono/status/1160737693359198208 https://twitter.com/amneris84/status/1160550136210046978
&twitter(1160737693359198208){theme:light}
> 裁判官は何やってんの〜⁈ https://t.co/y8BjqPLJqi
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜TAKEDAmasahiro（竹田昌弘） 日時：2019-08-12 11:20／2019-08-11 13:17 URL： https://twitter.com/kk_hirono/status/1160737800167161856 https://twitter.com/TAKEDAmasahiro/status/1160404926956068866
&twitter(1160737800167161856){theme:light}
> 「水戸地検は…検察官による誤った法令の解釈が原因で道路交通法違反の略式命令に至（り）…最高裁…が…取り消す判決を言い渡した、と発表…小型特殊自動車による牽引に…免許が（必要と）…誤認…検事総長が…非常上告（していた）…」（朝日） \n  https://t.co/cetia2VquV
◁◁◁
<hr />

　これまでの傾向でもありますが、ジャーナリストの江川紹子氏は裁判官の責任をより重く捉えているようです。このような過ちは量刑の上限を超えた求刑、判決としてネットでニュース記事を見た覚えがありますが、いずれもテレビのニュースになるようなことはない感じです。

　ジャーナリストの江川紹子氏がツイートを引用した竹田昌弘というアカウント名は見覚えがあったのですが、アイコンがアニメの肖像画のようなものに変わっていました。プロフィールをみると冒頭に「1961年富山県生まれ」とあったので間違いなく同じアカウントだと思いました。

```
1961年富山県生まれ。共同通信編集委員。twitterは個人の活動です。単著『知る、考える裁判員制度』（岩波）、編著『憲法ルネサンス』（インパクト出版会）、共著『避難する権利、それぞれの選択』（岩波）、『裁判員司法』（日評）などを書きました。お読みいただけると幸いです。詳しいプロフは (link： http：//goo.gl/Yeu16j) goo.gl/Yeu16j
東京twilog.org/TAKEDAmasahiro2010年5月からTwitterを利用しています

［source：］竹田昌弘（@TAKEDAmasahiro）さん / Twitter https://twitter.com/TAKEDAmasahiro
```

　あらためてTwitterのプロフィールに目を通すと、裁判員制度や憲法に関連したものが並んでいました。今まで気が付かなかったのも多少不思議ではあります。タイムラインを遡って見るようなこともなかったような気がします。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜TAKEDAmasahiro（竹田昌弘） 日時：2019-08-12 11:29／2019-08-11 13:06 URL： https://twitter.com/kk_hirono/status/1160740128509218817 https://twitter.com/TAKEDAmasahiro/status/1160402173538131968
&twitter(1160740128509218817){theme:light}
> 「首相の街頭演説中にヤジを飛ばした市民を北海道警の警官が取り押さえて排除した問題で…排除された人ら約150人が10日夕、札幌市中心部で抗議デモ…『…えらい人に一言二言文句を言っただけで警察に強制的に連れて行かれるって、ただの独裁国… https://t.co/h3hSFIk4My
◁◁◁
<hr />

　上記のツイートにある札幌市の警察官の問題ですが、2,3日前から法クラのツイートやタイムラインで見かけていました。テレビでは見ていないニュースかと思います。愛媛の女子大生の誤認逮捕は、テレビでも見た方と思いますが、共通性もありそうに感じています。

[link:] » imanishi（@maido_osaka）さん / Twitter https://t.co/E5ENdioJig

<hr />

　上記のアカウントですが、竹田昌弘氏のTwitterアカウントのページで「おすすめユーザー」として見かけました。こちらもずいぶん久しぶりにアカウントの存在に気が付きましたが、饅頭が笑っているようなアイコンはずっと前から変わっていないものだと思います。

　プロフィールでも「いまにしのりゆき」と平仮名で書いてありますが、今西憲之として読み終えたネット記事の終わりに名前を見かけたこともこれまでに何度かありました。

　似たようにたまにみかける名前があって、最初は日航機の墜落事故、上野村の取材の記事から知ったように思います。まだ一月は経っていないと思いますが、刑事事件として山口県の死刑判決が確定したことでネット記事をみかけました。拘置所にも面会に行っていたとのことです。

　その日航機の墜落事故ですが、昨日の夕方、銭湯のテレビで大きく34年前と出ていたのが印象的でした。正直まだ34年7日という印象を受けました。毎年目にしているニュースで、そのたびに経過年数も出ているはずですが、今回は違って感じました。

[link:] » いまにしのりゆき 商売繁盛でささもって来い！ https://t.co/QOBNhX7dC3

<hr />

　プロフィールのリンクからページを開きましたが、ヘッダ画像が同じものだと確認しました。何か象徴的で衝撃的なヘッダ画像です。写真の建物は東日本大震災で被災したビルと思われます。その上に「＼まいど！／　商売繁盛で笹もってこい」という文字があります。

　右手に赤い丸の白地で「大阪のジャーナリスト、今西憲之がニュースに迫る！」とこちらは漢字で名前が書いてありました。Twitterアカウントは見ていないように思いますし、ジャーナリストとしての経歴や活動というのも調べたことはなかったように思います。

```
imanishi
@maido_osaka
まいど（＾◇＾）いまにしです。
メルマガは、 まいど！ 週刊！ 今西憲之ジャーナル  
(link： http：//www.mag2.com/m/0001439730.html) mag2.com/m/0001439730.h…
ブログは、いまにしのりゆき 商売繁盛でささもってこい！  
(link： http：//www.imanishinoriyuki.jp/) imanishinoriyuki.jp
もちろん野球は阪神でっせ。
おおさかでっせ！2010年3月からTwitterを利用しています
2,002 フォロー中
8,033 フォロワー

［source：］imanishi（@maido_osaka）さん / Twitter https://twitter.com/maido_osaka
```

　Twitterアカウントのリンクがあることに気が付きました。Twitterのアカウントとしても見かけたことがあるような気がしましたが、滅多に見かけるものではなかったと思います。私がよく見る法クラがリツイートすることはほとんどないと推定されます。

　タイムラインをさかのぼっていくと、亀石倫子弁護士のツイートのリツイートをみつけました。警察のGPS捜査をプライバシーの侵害として批判する記事を紹介するもののようです。まだリンクも開いていないですが、これは独立した記事として記録しておこうと思います。

　時刻は12時02分です。先ほどテレビのバイキングのオープニングで、今日のラインナップの項目が２つあり、2つ目に日航機の墜落事故今日で34年があって、坂上忍さんが、当時取材したジャーナリストから話を聞く、などと解説をされていました。

　個人的に名前をおぼえられない人なのですが、その人が日航機事故を取材したジャーナリストとして出てくることを期待したいと思っています。現在は移住者問題を中心に活動をされているようですが、いろいろと考えさせられることが多いと感じてきました。興味深くあります。

＜＜＜2019-08-12（月曜日）12：07＿［これまでの記述範囲の終了時刻］＜＜＜

