#+TITLE: "弁護士が選ぶ刑事弁護人というＷｅｂサイト"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-06-26 10:33:27 +0900
FILE_NAME: 2019-06-26-103327_弁護士が選ぶ刑事弁護人というＷｅｂサイト.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 刑事司法  刑事弁護 弁護人
記事タイトル名の文字数：20　保存ファイル名の文字数：42

* 弁護士が選ぶ刑事弁護人というＷｅｂサイト

** 埼玉県の志木市妻子放火殺人事件で刑事弁護人だったと知った岩本憲武弁護士
   :LOGBOOK:
   CLOCK: [2019-06-26 水 10:37]--[2019-06-26 水 11:49] =>  1:12
   :END:

＞＞＞2019-06-26（水曜日）10：37＿［これからの記述範囲の開始時刻］＞＞＞

　この志布志妻子放火殺人事件については、昨夜、予定外の方向というか成り行きで取り上げました。埼玉県の志木市の地理的位置についても調べたのですが、やはり埼玉県でも東京都に近く、さらに司法研修所で有名な和光市の近くでした。

　しかし、なぜだか私は、その控訴審で逆転有罪となった妻子の放火殺人事件について、場所を埼玉県ではあるものの群馬県の高崎市の近くだとイメージしていました。

```
「埼玉」の前に、「放火」、「実験」というキーワードでモトケンこと矢部善朗弁護士（京都弁護士会）のTwilogを検索したのですが、それと思うツイートは見つかりませんでした。弁護士らの反応が余に乏しかったので、東住吉事件との対比でも不思議に思った刑事裁判でした。

　いろいろと方法を駆使しながら探していたのですが、モトケンこと矢部善朗弁護士（京都弁護士会）のツイートというのは、私の勘違いというかあるいは記憶の変容で、意外なことに深澤諭史弁護士のツイートとして、それらしいものを発見しました。2016年7月14日のツイートです。

　深澤諭史弁護士がこのようなツイートをするのは、かなり珍しい意外な発見だと思いました。モトケンこと矢部善朗弁護士（京都弁護士会）のツイートの傾向にも似ているのですが、弁護士にとって不利であったり、不都合な事実は、極力触れないと感じてきたことです。

　そのさいたま地裁の一審無罪判決では、検察側の燃焼実験が無罪の判断につながったというニュースをさきほど調べている過程で見かけていたので、あるいは不当性の意味で同業弁護士らの喚起を促す意味で、行ったツイートなのかとも考えますが、本人にしかわからないことかもしれません。

［source：］「法律問題、弁護士への相談について200％妥当する話ですね。（・∀・）」という深澤諭史弁護士のツイート - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/entry/2019/06/26/000333
```

　昨夜は、この志木市妻子放火殺人事件についていろいろと調べたのですが、この事件名のような名称も余り見覚えのないものでした。埼玉県の重大事件で無罪が争われたこともあり、高野隆弁護士が手がけた刑事裁判ではないかとずっと気になった時機もありました。

　最終的に、「弁護人」というような検察条件を付け加えることで、すぐに岩本憲武弁護士のことがわかったのですが、岩本憲武弁護士についてGoogleで検索しても、めぼしい情報は見つからず、ただ一つだけ「弁護士が選ぶ刑事弁護人」という歳とのページが出てきました。

　たまたまの偶然なのだと思いますが、昨日になるちょうどその日の朝、それも深澤諭史弁護士のTwitterタイムラインであったように思うのですが、ちょっと気になったリンクで、その「弁護士が選ぶ刑事弁護人」のサイトのページが出てきました。

　すぐにこれは訪問したことのあるサイトだと思いました。それというのもＷｅｂページのデザインに出ている女性の顔写真が、妙に明るく楽しげで、メルヘンというかそういう世界観があって、それが殺伐とした刑事弁護人の仕事や人生におけるその関わりに不思議なものを感じたからです。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「岩本 弁護士」の検索結果 - Twilog https://t.co/FUzpPkTFjf

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-26 11:04／2019-06-26 00:57 URL： https://twitter.com/kk_hirono/status/1143701628601503744 https://twitter.com/hirono_hideki/status/1143548738842972160
&twitter(1143701628601503744){theme:light}
> 弁護士　岩本憲武【弁護士が選ぶ刑事弁護人】 https://t.co/MzRtMIIiiI
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k_shinri_shien（㈱越谷心理支援センター） 日時：2019-06-26 11:04／2017-05-13 20:29 URL： https://twitter.com/kk_hirono/status/1143701646813171712 https://twitter.com/k_shinri_shien/status/863355546493083648
&twitter(1143701646813171712){theme:light}
> 相談の中には、法の観点からも介入が必要なものがございます。そこで、弁護士法人モッキンバード法律事務所の岩本憲武（いわもと けんぶ）弁護士と顧問契約を締結いたしました！ \n  詳しくはhttps://t.co/0LmTQQPjmL \n  またはhttps://t.co/tHnuKfWNNr
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-06-26 11:05／2019-06-26 07:49 URL： https://twitter.com/kk_hirono/status/1143701671165304832 https://twitter.com/hirono_hideki/status/1143652567265632256
&twitter(1143701671165304832){theme:light}
> 2019年06月26日01時00分の登録： ＼弁護士法人モッキンバード法律事務所　@mockinglawyer＼当事務所の岩本憲武弁護士がパネラーを務めた「さいたま医療訴訟連絡協議会・ドキュメント２０１８～ドキュメ https://t.co/Jbl5OPAkw6
◁◁◁
<hr />

　Twilogで確認ともなりましたが、「岩本　弁護士」の検索結果は、本日の2019年6月26日だけで、2件のツイートと1件のリツイート、ツイートは0時57分と7時49分でした。起きてすぐのツイートだったようですが、寝ぼけ気味だったのか自分のやった行為としてよく覚えていません。

　ツイートの内容をよく見ると、ツイートの投稿時刻が7時49分ですが、その内容というのは「2019年06月26日01時00分の登録： 」というブログ記事のリンクでした。更新した記事のリンクをまとめて投稿した処理だったのだと理解が出来ました。

　「モッキンバード法律事務所」とありますが、これもひと目見て変わった名称と思いました。実在する鳥の名前のような説明も見かけたのですが、中学生の頃、音楽の授業で木琴という楽器の名前があったような古い記憶を思い出したりしていました。

　モンキーとも空目しそうですが、アラベスクという女性グループの「ハロー・ハロー・ミスターモンキー」などという曲が流行していたのも、その能都中学校の音楽室で授業を受けていた頃のことだったと思います。

[link:] » ハロー・ミスター・モンキー 　/　アラベスク. - YouTube https://t.co/9uvfYbCkjx

<hr />

[link:] » 「ハロー.ミスターモンキー.」の歌詞は陰気だった | 茶の湯放浪記 https://t.co/oMKxSfMSrC

<hr />

　曲の流行した時期を調べたのですが、1977年とあるので昭和52年のようです。アラベスクが西ドイツのグループだったというのは意外に感じましたが、記事の下の方に「ジンギスカン」というグループのことも書いてあります。こちらは西ドイツだと知っていました。

　当時はノーランズというようなグループも人気で、そちらもヨーロッパの女性グループであったように思います。考えてみると平成になってからヨーロッパの音楽グループで、日本で大人気になったというのは余り聞いていない気がしました。

　ノーランズ、アイルランドだったようです。アラベスクについてもディスコという言葉が一緒になっていましたが、ディスコという言葉を聞くようになったのは昭和56年辺りかと思います。バブルの時代の象徴として最近でもテレビで見かけることはありますが、今もあるのか不明です。

```
「モッキンバード」は、「物まね鳥」の意味である。和名をマネシツグミという、メキシコなど北米大陸南部に生息する鳥で、他の鳥の鳴き声をまねする性質があることからこの名がある。メキシコの地酒であるテキーラをベースにしたカクテルなので、この名が付けられたとされる。グリーン・ペパーミントの緑色が鮮やかなカクテルである。

［source：］モッキンバード - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%A2%E3%83%83%E3%82%AD%E3%83%B3%E3%83%90%E3%83%BC%E3%83%89
```

　なにかディスコミュージックの曲のタイトルのようなイメージが抜けないのですが、確認のため調べると、鳥の名前以外にテキーラのカクテルという意味があるとのことです。テキーラといえば3月の久留米支部の性犯罪無罪判決で、やたらと目にした言葉です。

　4月1日に金沢に行ったとき、イオンの大きな酒店で、テキーラらしいものを探したのですが見つかりませんでした。テキーラというのはまだ見たことも口にしたこともないように思います。ロシアのウォッカと同じでとてもアルコールの強い酒という知識は前からありました。

＜＜＜2019-06-26（水曜日）11：49＿［これまでの記述範囲の終了時刻］＜＜＜

** 「お葬式」や「遺品整理」という項目が右サイドに並ぶ、弁護士法人モッキンバード法律事務所　弁護士紹介のホームページ
   :LOGBOOK:
   CLOCK: [2019-06-26 水 11:52]--[2019-06-26 水 13:06] =>  1:14
   :END:

＞＞＞2019-06-26（水曜日）11：52＿［これからの記述範囲の開始時刻］＞＞＞

　遺品整理や新しいスタイルのお葬式といえば、2時間ドラマのシリーズを思い出すのですが、「赤い霊柩車シリーズ」ではなかったかと思います。もう思い出せないぐらい前から宇出津という田舎でも家で葬式をする家は見たことがありません。

　宇出津というかたぶん能登町全部だと思うのですが、「三郷」という斎場が長坂にあります。地元の人はなぜか「さんご」と発音する人がほとんどなので、珊瑚というイメージも抜けないのですが、新しいゴミ処理場と隣接し、いつのまにか出来ていました。

```
115件目 » 2018-07-24_171219＿平体　能都町火葬場跡地（１９６６年５月〜１９９６年１２月）　慰霊碑　聖観世音菩薩像.jpg

［link：］ 2018-07-24_171219＿平体　能都町火葬場跡地（１９６６年５月〜１９９６年１２月）　慰霊碑　聖観世音菩薩像.jpg <http：//hirono2014sk.blogspot.com/2018/08/2018080214192018-07-151924202018-08.html#20180724171205#20180724171219> 

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： 2018年08月02日14：19記録＼法務検察・石川県警察宛＼写真資料：2018-07-15_192420〜2018-08-01_000629：287件 http://hirono2014sk.blogspot.com/2018/08/2018080214192018-07-151924202018-08.html#20180724171205
```

　上記の写真で確認をしましたが、能都町火葬場跡地の聖観世音菩薩像の慰霊碑には、1966年5月から1996年12月と刻まれています。私の父親の火葬が昭和42年かあるいは昭和43年の4月だったので出来て間もない頃だったのだと知りましたが、遠い記憶に建物が新しい感じはありませんでした。

　1996年というのは平成8年ですが、私は平成9年1月18日に福井刑務所を満期出所し宇出津に戻りました。当日の最終の電車で、宇出津駅着は22時10分頃だったと記憶しています。

　私が経験した火葬というのは2回だけで、ぼんやり少しだけ記憶に残る父親の火葬と、その2,3年後と思う父方の親戚の葬式でした。その家で葬式があったのですが、ちょうどラジオで沖縄返還のニュースを聞いていたことが記憶に残っています。

　宇出津では、高齢化で葬式も多く、商売をしている人はお通夜に月に2,3回顔を出して香典を包んでいると聞きますが、私は小学校の時以来、葬式にも行ったことがないように思います。遠い親戚らしい、田町の豆腐屋に葬式に出て、そこに同級生がいて驚いたことを憶えています。

　宇出津に田町という町内はないのですが、立町と横町を田町と呼んでいて、昔は神野方面への街道筋として牛馬の通行があり賑わいがあったと聞きます。

　その田町に「やたろうざか」と呼ばれる急な坂があって、火葬場への桶を担いで死体を運んだと聞きます。道路がなく車で運ぶことも出来なかったと聞きます。私はその話を、2015年ぐらいになって初めて知りました。

　宇出津の町内は上田町になるかと思いますが、藤波の辺田の浜との間にはトンネルがあって、辺田の浜の方からみるとトンネルの上に古い火葬場の建物がありました。いつのまにかなくなっていたのですが、昭和の時代はまだずっとあったように思います。

　同じく2015年頃に初めて知ったのですが、私が生まれた昭和39年か、その少し前には、そのトンネルも辺田の浜から宇出津の新町に出る道路自体がなかったと聞きました。今はバイパスがありますが、昭和の時代、バイパスが開通する前は国道249号線だったと思います。

　家のどこかには、裁判の資料に戸籍謄本があって、そこに父親の生年と没年の記載があったと思うのですが、だいぶん前から気になりながら、まだ探して確認をしていません。大正11年の生まれと聞いていたように思うのですが、記憶が薄れているので確信はもてないのです。

　父親は私が３つのときに亡くなったと聞いてきたと思うのですが、昔の人は、満と数え年を使い分けることも多く、どちらであったのかはっきりしません。4月の20日かあるいは23日が命日であったとも思います。

　火葬場や葬式の時代の移り変わりと、廃線となった能登鉄道、弁護士によって狂わされた人生というものが私の中では渾然一体となっており、弁護士法人モッキンバード法律事務所のホームページで、葬式関連の情報を見たのは感慨深さがあり、いずれ母親の葬式のこともあります。

　弁護士法人モッキンバード法律事務所の弁護士紹介のホームページには、胸像のような顔写真が一枚だけ掲載されています。その右手に4人の弁護士の名前と経歴の紹介があるのですが、１つフォントの大きさが違ったり、区切りがわかりづらくなっています。

　いくらか手作り感のあるホームページでもあります。ホームページのソースを確認すると、複雑なHTMLとなっていましたが、ホームページ作成のアプリを使っても自動的に生成されるコードなのかもしれません。専門の業者に依頼したにすれば、どうかと思うところです。

　上から「川目武彦（かわめたけひこ）」「岩本憲武（いわもとけんぶ）」「武田浩一（たけだひろかず）」「大塚晃央（おおつかあきお）」という弁護士の名前が、経歴、趣味などとともに並んでいます。

　川目弁護士については、所属弁護士会の記載が見当たらず、大塚弁護士が群馬弁護士会所属となっています。東京都に近いのであれば、東京の弁護士会に所属している可能性もあるのかと確認したのですが、群馬弁護士会というのは意外でした。

　岩本憲武弁護士の名前も昨夜、初めて知ったばかりと思いますが、「元・最高裁判所司法研修所刑事弁護教官（２０１５年～２０１８年）」というのも意外な経歴です。

　そういえば3週間ほど前になりますか、母親の病室で、隣のベッドの人がテレビをつけていて、その画面に司法教官シリーズの2時間ドラマが出ていました。ちょうど結婚式での殺人未遂の場面であったように思います。ドラマを静止状態にさせて解説するのも、そのドラマの特徴です。

　あまりよく思い出せないのですが、結婚式場を襲撃し、花嫁と勘違いしてマネキンを刺したというような内容ではなかったかと思います。たまたまいきなりその場面が目に入ったので、なんの番組なのかすらしばらく理解ができませんでした。

　繰り返しますが、埼玉県の和光市といえば、司法修習生の司法研修所があることで有名です。これは初めに知ってから変わっていないと思うので、ずっと和光市に司法研修所があるようです。光市母子殺害事件の検索で、光市とすると和光市の司法研修所のことが出てきて、最初は怪奇現象にも思えました。

＜＜＜2019-06-26（水曜日）13：06＿［これまでの記述範囲の終了時刻］＜＜＜

