#+TITLE: "参考資料／弁護士業界／深澤諭史弁護士のリツイート／人工透析の中止で４０代女性が死亡した問題、ゴーン弁護団クラスを探す、ゆくゆくは病院と意思個人の利害が対立"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-03-09 16:46:42 +0900
FILE_NAME: 2019-03-09-164642_人工透析の中止で４０代女性が死亡した問題、ゴーン弁護団クラスを探す、ゆくゆくは病院と意思個人の利害が対立.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  医療問題 ゴーン弁護団 深澤諭史弁護士のリツイート
記事タイトル名の文字数：77　保存ファイル名の文字数：74

#contents

* ピピピーッさんのツイート：”透析中止の件の関係者は、病院に任せきりにせずに、ゴーン弁護団クラスの弁護士のあてを探しておいたほうがいいかも。ゆくゆくは病院と医師個人の利害が対立しそうだし・・・”
  :LOGBOOK:
  CLOCK: [2019-03-09 土 16:51]--[2019-03-09 土 17:27] =>  0:36
  :END:

＞＞＞2019-03-09（土曜日）16：51＿［これからの記述範囲の開始時刻］＞＞＞

▷ リツイート→fukazawas（深澤諭史）＞O59K2dPQH59QEJx（ピピピーッ）｜2019/03/09 14:42／2019/03/09 14:02｜https://twitter.com/fukazawas/status/1104256020107354113 ／ https://twitter.com/O59K2dPQH59QEJx/status/1104246017082290176
&twitter(1104256020107354113){theme:light}
> RT @O59K2dPQH59QEJx: 透析中止の件の関係者は、病院に任せきりにせずに、ゴーン弁護団クラスの弁護士のあてを探しておいたほうがいいかも。ゆくゆくは病院と医師個人の利害が対立しそうだし。
> 
> それに逮捕されちゃう可能性があるから。  

▷ リツイート→fukazawas（深澤諭史）＞O59K2dPQH59QEJx（ピピピーッ）｜2019/03/09 14:42／2019/03/09 14:10｜https://twitter.com/fukazawas/status/1104256024985260032 ／ https://twitter.com/O59K2dPQH59QEJx/status/1104248013336133632
&twitter(1104256024985260032){theme:light}
> RT @O59K2dPQH59QEJx: ゴーン弁護団クラスが無理なら、とりあえず「フットワークが軽く刑事をきちんとやってる身近な弁護士」に相談しておくべき。
> 逮捕されて大騒ぎになればやがて学会やら医師会やら有志やらが動いてゴーン弁護団クラスの大物につないでくれるけど、その間の…  

　時刻は１６時５７分です。明日の夜、グッドワイフとかいう弁護士ドラマの番宣がテレビでありましたが、CMの合間の番宣としては、これまでにないぐらい長いもので、いろいろな場面が紹介されていました。

　時刻は１７時０６分です。郵便受けら新聞を取って来て、ざっと目を通すと、カルロス・ゴーン弁護団の高野隆弁護士のブログのことが記事になっていました。見出しが小さいので目立たない記事でしたが、北陸中日新聞です。

　ピピピーッというアカウントですが、テキストの弁護士データに記録がありませんでした。以前に記録していたファイルは存在したのですが、システムの移行で引き継ぎが出来ていなかったようです。次のようにデータを新規に作成しました。

```
[10038]  % TU=`xsel -b|sed 's/.*twitter\.com\/\([^ /]\+\).*/\1/'`; echo $TU; h-show-twitter-profile.rb $TU; for x in {1..16};do tw_user_timeline_1line.rb $TU 200 $x >> $TU; done &&  st=$(grep "^\(▶TW \|▶RT \).*" $TU |tail -1|sed "s/.*日時：\(....\)-\(..\)-\(..\) \(..\):\(..\)[ ／].*/\1\2\3\4\5/"); et=$(grep "^\(▶TW \|▶RT \).*" $TU |head -1|sed "s/.*日時：\(....\)-\(..\)-\(..\) \(..\):\(..\)[ ／].*/\1\2\3\4\5/"); mv $TU ${TU}_${st}-${et}.txt; echo  -e "\n取得件数： ";  grep "^\(▶TW \|▶RT \).*" ${TU}_${st}-${et}.txt| wc -l; echo "取得した最新ツイート："; sed -n '1p' ${TU}_${st}-${et}.txt; echo "取得した最古ツイート："; sed -n '$p' ${TU}_${st}-${et}.txt
O59K2dPQH59QEJx
＜2019年03月09日(土) 17時12分06秒にTwitterAPIで取得したO59K2dPQH59QEJx（ピピピーッ）のプロフィール情報＞


取得件数： 
3193
取得した最新ツイート：
▶TW O59K2dPQH59QEJx（ピピピーッ） 日時：2019-03-09 14:10 URL： https://twitter.com/O59K2dPQH59QEJx/status/1104248013336133632 TWEET： ゴーン弁護団クラスが無理なら、とりあえず「フットワークが軽く刑事をきちんとやってる身近な弁護士」に相談しておくべき。 \n 逮捕されて大騒ぎになればやがて学会やら医師会やら有志やらが動いてゴーン弁護団クラスの大物につないでくれるけど、その間のつなぎの弁護士が必要なんだよね。  
取得した最古ツイート：
▶TW O59K2dPQH59QEJx（ピピピーッ） 日時：2018-02-18 22:44 URL： https://twitter.com/O59K2dPQH59QEJx/status/965220577303605249 TWEET： 出てしまったら、これからもずっと出ないといけなくなる。 \n  \n 催眠術をかけましょう！そう、携帯電話は事務所の机の中にあるのです。 https://t.co/K9LqWM81TD
```

　「O59K2dPQH59QEJx_201802182244-201903091410.txt」が今回、新規で作成したテキストデータのファイルです。３１９３件の最新ツイートを記録しました。

　「O59K2dPQH59QEJx_201609032159-201710220138.txt」というのが以前記録していたテキストデータファイルです。２０１７年１０月２２日で記録が止まっているので、ずいぶん前になりますが、他にもありそうです。昨日あたりも１つ見つけて対処しました。

　ピピピーッというアカウントは、直接タイムラインを開くことは少ないですが、主に深澤諭史弁護士のタイムラインでリツイートとしてほぼ毎日のように見ているという気がします。プロフィールは無記入のようですが、ツイートの内容は弁護士らしいものが多いです。

＜＜＜2019-03-09（土曜日）17：27＿［これまでの記述範囲の終了時刻］＜＜＜




