#+TITLE: "参考資料／国家賠償請求／秋田の弁護士殺害事件／日本では裁判官や検察官が殺された例を聞いたことはないのですが、弁護士はこれまでに何人も刺されて命を失ってきているのですよね"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-05-23 10:35:05 +0900
FILE_NAME: 2019-05-23-103505_日本では裁判官や検察官が殺された例を聞いたことはないのですが、弁護士はこれまでに何人も刺されて命を失ってきているのですよね.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  秋田の弁護士殺害事件
記事タイトル名の文字数：84　保存ファイル名の文字数：83

#contents

* REGEXP：”弁護士はこれまでに何人も刺されて命を失ってきているのですよね”／データベース登録済みツイート：2019年05月23日10時36分の記録：ユーザ・投稿：18／18件
  :LOGBOOK:
  CLOCK: [2019-05-23 木 10:38]--[2019-05-23 木 11:00] =>  0:22
  :END:

＞＞＞2019-05-23（木曜日）10：38＿［これからの記述範囲の開始時刻］＞＞＞

```
アカウント名	ツイート数	リツイート数
HRK（hKodama）	1	0
大窪和久（okuboka）	0	1
中村元弥（1961kumachin）	0	1
えきなんローヤー?（ekinan_lawyer）	0	1
村松 謙（kmuramatsu）	0	1
ノースライム・St（noooooooorth）	0	1
しゃんす弁護士（KshAb76）	0	1
なべきょう＠過眠症（wata_nabekyo_ko）	0	1
Hiroaki Miura（MobileMiura）	0	1
佐藤正子（SATOMasako）	0	1
半田 望（Handalaw）	0	1
toujin（tou_jin）	0	1
ルート６６（元ルパン３世）（Route66_LP3）	0	1
リーチ一発ツモ裏１（luckymangan）	0	1
霞 司郎?（kasumi_shiro）	0	1
芳賀淳（jjjhaga）	0	1
弁護士　金田万作（mansakukanada）	0	1
Pokomoko（Pokomoko5）	0	1


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”弁護士はこれまでに何人も刺されて命を失ってきているのですよね”／データベース登録済みツイート：2019年05月23日10時36分の記録：ユーザ・投稿：18／18件 http://hirono2014sk.blogspot.com/2019/05/regexp2019052310361818.html
```

　上記の引用ではレイアウトが崩れわかりづらいと思いますが、ツイートは1件、他すべてがその1件のツイートのリツイートとなっています。

　弁護士が殺され、それもかなりの人数が殺されたという印象のツイートは、これまでにも見かけてきたのですが、このようなかたちで記録とするのは初めてかと思います。

　このツイートを目にした後、初めて少し調べてみたのですが、実際に弁護士が殺害された事件というのは、私の記憶と認識にあった横浜と秋田の弁護士で、それ以外の情報としてオウム真理教事件の坂本弁護士一家殺害事件がありました。

　オウム真理教事件の一連の事件は特異で規模の大きな事件で、弁護士が業務に関連して殺害された事件という認識はなかったのですが、広い意味ではそうなるのかと思いました。たしか横浜の事件は弁護士事務所、秋田の事件は弁護士の自宅が殺害現場でした。

　正直なところ、横浜の事件と秋田の事件のどちらが先か記憶にないのですが、いずれも金沢弁護士会などで会長の声明文が出され、どちらも似た時期だったと記憶にあります。

　また、弁護士の法律事務所での立て籠もり事件やガソリン等の火器危険物を持ち込んでの事件というのも、私個人の知る限り聞いたことがなく、上記のツイートにあるとおり、検事や裁判官の殺人事件というのも同様かと思います。ただ、裁判官の自殺が多いと言われた時期はあります。

　やはり個人的に坂本弁護士一家殺害事件は異なる印象が強いですが、横浜と秋田の事件は似た事件で、各弁護士会の会長声明も、一律、ただの逆恨みとして片づけ、弁護士が社会的な使命を全うするための安全保障を強く訴えかけていました。

＜＜＜2019-05-23（木曜日）11：00＿［これまでの記述範囲の終了時刻］＜＜＜

* 弁護士らが想定し主張する「逆恨み」についての記録と分析
  :LOGBOOK:
  CLOCK: [2019-05-23 木 11:04]--[2019-05-23 木 11:41] =>  0:37
  :END:

＞＞＞2019-05-23（木曜日）11：04＿［これからの記述範囲の開始時刻］＞＞＞

　新規にまとめ記事を作成中です。まとめ記事はツイートの文字列を機械的に検索し収集するものなので、関連性の薄いものが含まれることもあるかと思います。ただ、この「逆恨み」に関しては無関係のものがまぎれる可能性は低いように考えています。

```
===========================================================
アカウント名	ツイート数	リツイート数
小倉秀夫（Hideo_Ogura）	5	0
おおがっちゃん（ohgachan）	2	0
坂本正幸（sakamotomasayuk）	1	0
山口貴士（otakulawyer）	1	1
延命政之（emmei1）	1	0
田中・鈴木・木村（tanakasuzukikim）	0	1
Shoko Egawa（amneris84）	1	0
山内 憲之（kyrino）	1	0
モトケン（motoken_tw）	10	3
大貫憲介（SatsukiLaw）	3	0
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	8	5
Which（which0623）	1	0
深澤諭史（fukazawas）	28	11
hznf（_hznf_）	1	0
町村泰貴（matimura）	2	0
弁護士 市川 寛（imaloser15）	0	1
弁護士ばびろん（mackckckck）	0	2
小久保　哲郎（tetsurokokubo）	1	0
ほうたろう（lawyerhotaro）	2	0
Kenji Sarukura 弁護士（Kenji__Sarukura）	1	0
ystk（lawkus）	2	0
弁護士　浜ちゃん（satoshihamada）	0	1
饂飩愛好家（siusiudon）	1	0
饂飩愛好家（ramenman365）	1	0
弁護士・弁理士 松田 誠司（seijimatsudalaw）	0	1
ささきりょう（ssk_ryo）	1	1
今野晴貴（konno_haruki）	1	0
ダイジョーブ法務博士（forblogb）	1	0
小澤里奈（academentian）	1	0
高橋雄一郎（kamatatylaw）	0	1
obata（obata_1115）	0	1
愛（ailuv2u）	0	2
感熱紙(エイハブリアクター)（thermalpaper00）	1	0
霞 司郎㌥（kasumi_shiro）	0	3
亀石（kame_ishi）	0	3
泥濘大魔王サイケ（k_sawmen）	0	1
カロ（calowyer）	0	1
ＫＢブラック（bengoshi_black）	0	1
弁護士 井垣孝之（igaki）	1	0
自家製パンチェッタ（jikapan）	1	0
給費制実現活動弁護士（kyuhi_realize）	0	1
八田隆 Terry Hatta（thatta0529）	0	2
望月衣塑子（ISOKO_MOCHIZUKI）	1	0
おおはしひろき（hiroki0084）	0	1
ピピピーッ（O59K2dPQH59QEJx）	6	0
過疎地域のB（B01542213）	0	1
うの字（un_co_the2nd）	3	1
弁護士 Ms. X（msX_lawyer）	0	2
レモン牛乳（beautifulday00）	1	1
落合洋司 Yoji Ochiai（yjochi）	1	0
たけるbot（bexa930）	1	0
せいりゅう みわこ（Seiryu_Miwako）	0	1
YUKI　Keiichi（yuki_k1）	0	1
リーチ一発ツモ裏１（luckymangan）	2	11
しゃんす弁護士（KshAb76）	2	4
くまえもん（kumaemon9）	1	1
赤ネコ（Redips00）	0	1
芳賀淳（jjjhaga）	0	3
寺澤有（Yu_TERASAWA）	0	2
飛鳥＠6/8,9 Aqours5th現地（kiwi250r）	0	1
すてぃっち（TAS6284）	1	3
弁護士(平成JUMP)（okinawabengoshi）	0	4
玉井克哉（Katsuya TAMAI）（tamai1961）	0	5
青木　俊（AokiTonko）	0	3
自称善良な弁護士（Jisyou_Zenryou）	0	1
同志フミン少佐（IcyFumin）	1	3
ツンデレブログ（tsundereblog）	0	1
ぽぽひと@常時発動型煽りスキル持ち（popohito）	0	12
弁護士 都 行志（Miyako_Koji）	1	0
弁護士 太田啓子（katepanda2）	1	3
嘘つき弁護士。（LiarLawyer800）	1	4
J（may18_nj）	0	1
Pokomoko（Pokomoko5）	2	6
なべきょう＠過眠症（wata_nabekyo_ko）	5	4
shoya（sho_ya）	0	3
清水 潔（NOSUKE0607）	0	2
Kenji Takeuchi（KPf_M）	0	1
暇弁＠もうだめぽ（himaben1st）	1	0
弁護士篠田奈保子（yorisoibengoshi）	1	1
てらやさん☆（terayasan）	1	0
山口二郎（260yamaguchi）	1	0
アンバサダ（anbasalaw）	1	0
えきなんローヤー?（ekinan_lawyer）	3	9
yuji kigami　木上雄二（39801）	0	3
微笑みのロイヤー（smile_spirits）	0	5
弁護士あだちけいた　春の大山 打つんだ。（keita_adachi）	2	4
佐藤正子（SATOMasako）	1	0
1313（Kurosiro1313）	0	1
Taka（tnakamura23）	0	1
鳩屋（haya_rt）	0	1
丙弁（heibenn）	0	1
arima（arima_yukimi）	3	1
弁護士 上瀧浩子（sanngatuusagino）	1	0
国際弁護士＆気象予報士ヒロ（HiroshiKiyohara）	1	0
安藤俊文（toshifumi_Ando）	0	1
浜ちゃん（lawer_hamachan）	0	3
蛇毒（bigbrother939）	0	1
エンリケ股份有限公司（kd_ixi）	0	2
弁護士 星　正秀（hoshimasahide）	1	1
中野希美（kimi1114nakano）	0	1
吉田哲也（yosidatetuya）	0	2
非常上告-最高検察庁御中_ツイッター（s_hirono）	5	0
ささもひょんⁿ@赤腹魔王（yukihirosasamo）	0	1
弁護士南川麻由子（lawyerMAYUZO）	1	0
嶋﨑量（弁護士）（shima_chikara）	0	1
中村剛（take-five）（take___five）	0	1
高木良平（ryouheitakaki）	1	1
魚占い（sakanauranai）	0	2
三毛猫B（poorpartner）	0	1
工藤啓介（keisukekudou）	0	2
こたべん@事務所経営コンサル×弁護士（nakahaya0427）	0	1
中野 俊徳（kanonjilawfirm）	0	4
弁護士　荘司雅彦（shoji_lawyer）	2	0
イケメン弁護士(絶対起案するマン)（ikemen_lawyer）	0	1
弁護士 吉峯耕平（「カンママル」撲滅委員会）（kyoshimine）	0	1
ほりぐちです（mstk_Horiguchi）	0	2
モンストの才覚がない若手弁護士（aohina2011）	0	1
カール=レーフラー（hirohika777）	0	1
木村草太（SotaKimura）	1	0
りっぴぃ（rippy08）	2	0
山口一臣（kazu1961omi）	1	0
弁護士杉山程彦5東慶應三丁目（r34CXRsvHnOj2GB）	1	0
寺町東子（teramachi_toko）	0	2
櫻井光政（okinahimeji）	0	1
心までサン社員☀️社畜猫@鳥獣戯画（depon2010）	1	3
猪野 亨（inotoru）	1	0
ルート６６（元ルパン３世）（Route66_LP3）	0	2
弁護士秋重実（civilista）（akishigemakoto）	0	1
らめーん（shouwayoroyoro）	2	0
k9999（k999941457035）	0	2
TｰTAKA（TGN54）	0	2
弁護士 中原潤一（lawyernakahara）	0	1
レモミル（Lemon_and_Milk）	2	2
しゃいん（shine_sann）	0	1
弁護士岡田晃朝（あさがお法律事務所）（asagaolaw）	1	0
弁護士　山中理司（yamanaka_osaka）	0	1
白黒つけるパンダ弁?（pandabengoshi）	0	1
まゆこ（mayukotaniguchi）	2	0
弁護士ドットコムニュース（bengo4topics）	1	0
強制わいせつ/準強姦/買春/児童ポルノ/児童福祉法/青少年条例弁護人弁護士奥村徹(大阪弁護士会)（okumuraosaka）	0	2
スドー?（stdaux）	1	0
aiko（ponikitiai）	1	0
弁護士 マンション管理士 桃尾俊明（momoo_t）	0	1
村松 謙（kmuramatsu）	0	1
中村元弥（1961kumachin）	0	1



［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”逆恨み”／データベース登録済みツイート：2019年05月23日11時09分の記録：ユーザ・投稿：145／365件 http://hirono2014sk.blogspot.com/2019/05/regexp201905231109145365.html
```
　繰り返しますが、まとめ記事はツイートやリツイートの投稿日時で古いものから並んでいます。これは機械的な処理になりますが、データベースの時刻型データを扱うものなので間違いの出る可能性はほぼないものと思います。

　その1件目、もっとも古いものが次の小倉秀夫弁護士のツイートでした。こういうのもまとめ記事を作成してみないと、なかなか見えては来ない情報です。

▶（001／365） TW Hideo_Ogura（小倉秀夫） 日時： 2010-05-19 09:20:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/14259970932
{% tweet 14259970932 %}
> ええ。匿名による誹謗中傷の「主犯格」の多くは被害者の周囲の人物。以前担当したケースでは、解雇された職員が逆恨みでデマ情報を延々と投稿していたり。RT @arukakan: 仮に匿名性が完全に担保されていれば、本人が傷ついている様を目の当たりにしながら同じことができるとお考えですか

▶（022／365） TW fukazawas（深澤諭史） 日時： 2015-08-05 17:07:00 +0900 URL： https://twitter.com/fukazawas/status/628839794517225473
{% tweet 628839794517225473 %}
> 具体的な被害者がいるので難しいけれど，ストーカー犯罪も覚醒剤のドラッグコートみたいな議論があってもいいかもしれないですね。 \n 一般予防のみならず特別予防も考慮しないと，被害者や処罰，司法を逆恨みしたり，再犯を誘発するおそれもあります。

▶（024／365） TW fukazawas（深澤諭史） 日時： 2015-08-28 12:15:00 +0900 URL： https://twitter.com/fukazawas/status/637101287033540608
{% tweet 637101287033540608 %}
> 被害者は，加害者の厳重処罰よりも隔離を強く求める傾向があるが，それは再被害を怖れているから。 \n 逆に加害者は，自分は悪くない（逆恨みから事実すら認めないことも）から，被害者が感じる再犯の恐怖は大きい。 \n ストーカーに限らず，薬物等も，処罰だけでなく治療の発想があっていいと思う。

▶（025／365） TW fukazawas（深澤諭史） 日時： 2015-09-09 21:26:00 +0900 URL： https://twitter.com/fukazawas/status/641588431756197889
{% tweet 641588431756197889 %}
> 予備校に学生を取られて，逆恨みして，予備校排除のためにヘンテコな制度を作って，各方面に莫大な迷惑かけている業界があるそうですよ。 \n どこなんでしょね？（・∀・） \n \n https://t.co/wz2J21CD9m

▶（029／365） TW fukazawas（深澤諭史） 日時： 2015-10-19 12:32:00 +0900 URL： https://twitter.com/fukazawas/status/655949493922205697
{% tweet 655949493922205697 %}
> 凶行に走るストーカーの「真意を確かめたい」率は異常に高い。 \n 更に「相手が自分のいうとおりになれば『こんなこと』にならなかった」のだから「自分は悪くない」として，社会を逆恨みしかねない。 \n ただひたすら厳重処罰するだけでは改善更生は期待しにくいので，治療という発想もあっていいと思う。

　時間がかかるのでこのあたりで引用はやめておこうかと思いますが、深澤諭史弁護士の場合、ストーカーと逆恨みがしっかりと結びついているのだと再確認しました。

＜＜＜2019-05-23（木曜日）11：41＿［これまでの記述範囲の終了時刻］＜＜＜

