#+TITLE: "ネットフェミニストの人たち炎上させてくんないかな。＞神奈川逃走事件を招いた甘過ぎ「女性裁判官」の知られざる人物像"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-07-09 15:22:16 +0900
FILE_NAME: 2019-07-09-152216_ネットフェミニストの人たち炎上させてくんないかな。＞神奈川逃走事件を招いた甘過ぎ「女性裁判官」の知られざる人物像.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 村松謙弁護士（神奈川県弁護士会）  村松謙弁護士（神奈川県弁護士会） 神奈川県弁護士会
記事タイトル名の文字数：56　保存ファイル名の文字数：78

* ネットフェミニストの人たち炎上させてくんないかな。＞神奈川逃走事件を招いた甘過ぎ「女性裁判官」の知られざる人物像（神奈川県弁護士会）
  :LOGBOOK:
  CLOCK: [2019-07-09 火 15:49]--[2019-07-09 火 17:47] =>  1:58
  :END:

＞＞＞2019-07-09（火曜日）15：49＿［これからの記述範囲の開始時刻］＞＞＞

　リンクの記事は昨日かに読んでいたものです。深澤諭史弁護士について記述を進めていたところ、この村松謙弁護士のツイートが気になって手が止まり、中断をしていました。迷いはあったのですが、取り上げておくこととしました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kmuramatsu（村松 謙） 日時：2019-07-09 15:52／2019-07-08 19:44 URL： https://twitter.com/kk_hirono/status/1148484939135893505 https://twitter.com/kmuramatsu/status/1148181064692617216
&twitter(1148484939135893505){theme:light}
> 女性、女性いってるこの記事ほんとムカつくんだけど、ネットフェミニストの人たち炎上させてくんないかな。＞神奈川逃走事件を招いた甘過ぎ「女性裁判官」の知られざる人物像 https://t.co/3P30gtqNIp #デイリー新潮
◁◁◁
<hr />

[link:] » 神奈川逃走事件を招いた甘過ぎ「女性裁判官」の知られざる人物像 | デイリー新潮 https://t.co/LXmwGa2QKi

<hr />

　既読の記事と思いながらリンクを開いたところ、デイリー新潮の記事ということで意外に感じました。内容はたぶん同じだと思いますが、前に読んだものは別のページだったように思います。Twilogに足跡が残っていると思うのでこれから確認をしてみます。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「神奈川逃走事件」の検索結果 - Twilog https://t.co/cGVKckFWF3

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-09 15:56／2019-07-07 14:29 URL： https://twitter.com/kk_hirono/status/1148486102321250304 https://twitter.com/hirono_hideki/status/1147739319093743616
&twitter(1148486102321250304){theme:light}
> 神奈川逃走事件を招いた甘過ぎ「女性裁判官」の知られざる人物像（デイリー新潮） - Yahoo!ニュース https://t.co/V3kWD4r0Uq
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-07-09 15:56／2019-07-07 20:51 URL： https://twitter.com/kk_hirono/status/1148486123175305216 https://twitter.com/hirono_hideki/status/1147835588034191360
&twitter(1148486123175305216){theme:light}
> 2019年07月07日20時31分の登録： ＼中野 俊徳　@kanonjilawfirm＼再保釈の問題ではないのに、ひどい記事だ。\n\n神奈川逃走事件を招いた甘過ぎ「女性裁判官」の知られざる人物像（デイリー新潮） - https://t.co/jQOcVw8FEq
◁◁◁
<hr />

　やはりYahooニュースとして読んでいたようですが、デイリー新潮の記事とは気が付かずにいたようです。文春や新潮の記事の方が人目に触れる機会は多いはずですが、意外にネットでは余り話題にもなっていないと感じることが度々ありました。

　横浜地裁小田原支部の女性裁判官ということは、最初に記事を読んだ時、意外に感じていましたが、他に集中していたことがあったためか深くは考えていなかったようです。同じ神奈川県内で裁判所の転勤を繰り返しているということも、この記事にはあったと思います。

```
「保釈も再保釈も、横浜地裁小田原支部の佐脇有紀裁判官の判断です」

　と、司法関係者が囁く。

「現在49歳の佐脇さんは神奈川県出身で、そのせいか小田原支部をはじめ、川崎支部や横浜地裁（本部）を転々とし、神奈川勤務が多い。有名どころでは、11年に霊感商法詐欺の『神世界（しんせかい）事件』に関わった元警視の裁判を担当したり、その前年には、桑田真澄（元巨人）の元義兄の詐欺公判に携わったりしています。神世界事件では、詐欺グループのトップの逃走を助けた元警視に対し、『彼は反省している』として執行猶予判決を出していました……」　

［source：］神奈川逃走事件を招いた甘過ぎ「女性裁判官」の知られざる人物像（デイリー新潮） - Yahoo!ニュース https://headlines.yahoo.co.jp/article?a=20190707-00569737-shincho-soci&p=2
```

　確認をすると冒頭に近い部分に「「現在49歳の佐脇さんは神奈川県出身で、そのせいか小田原支部をはじめ、川崎支部や横浜地裁（本部）を転々とし、神奈川勤務が多い」とありました。

　本人の希望や事情というのもあるものと思いますが、同一県内での裁判官の転勤というのも、初めて聞く話で珍しいと感じていました。名古屋高裁の管区内での転勤というのは多く見かけてきたのですが、同じ頃見かけた、札幌から名古屋での転勤ということで気になり、保留中の問題もあります。

[link:] » 逃走事件で神奈川県の厚木市長と愛川町長　横浜地検に要望書提出 - 産経ニュース https://t.co/A18cgJolsi

<hr />

[link:] » 愛川町 - Google マップ https://t.co/kSiWTKxl0U

<hr />

　逃走事件は神奈川県愛川町ということで、同県相模原市と同県厚木市の近くというのをテレビの報道でもみていましたが、あらためて上記のGoogleマップでみると、近いと思っていた川崎市からは遠く、遠いと思っていた小田原市には近い位置にあるようです。

　逃走事件というのは数年前、神奈川県川崎市でもありましたが、ＰＣ遠隔操作事件で神奈川県警や横浜地検が大きな負担を負わされていると感じるタイミングでの逃走事件でした。私が神奈川県での弁護士活動に注目するようになったのも、最初はそれがきっかけだったかもしれません。

　２０１５年に、NHK連続テレビ小説まれ、の放送があって、私の住む石川県の輪島市と神奈川県の横浜市がドラマの部隊となっていました。ちょうどその頃、「うの字」という横浜と関係があると思われる匿名弁護士アカウントのTwitterにも大いに注目するようになりました。

［link：］ うの字(@un_co_the2nd)さん | Twitterからの返信付きツイート https://twitter.com/un_co_the2nd/with_replies

　上記が現在の「うの字」のTwitterアカウントですが、これは前のアカウントが削除さらた後で作成されたアカウントです。以前のアカウント名にはローマ字で「横浜」が含まれていました。神奈川県弁護士会所属の可能性が高い実在弁護士になります。

　ところで、全国の弁護士会には県を含めたものと含めていないものが混在しており、なかなか正確に記憶することも出来ないので、その都度確認するようにしております。

　先ほど、村松謙弁護士の所属弁護士会を確認するため調べたところ、神奈川県弁護士会と県が入っていることを確認したのですが、そのときに２０１６年４月１日から横浜弁護士会から神奈川県弁護士会に移行したとありました。

　この横浜弁護士会から神奈川県弁護士会への移行の話は、NHK連続テレビ小説まれ、の放送中の２０１５年に情報を見かけていました。全国の県で県名が弁護士会の名称に含まれないものは３つほどしかなく、横浜の名称変更のあと残るには金沢だけと見たように思います。金沢弁護士会です。

[link:] » 弁護士会名 https://t.co/we7SgdnAEm

<hr />

　記憶に自身がなかったのですが、栃木県弁護士会の以前の名称が宇都宮弁護士会なのかと考えていたのですが、宮城県という県名が含まれていないのは仙台弁護士会でした。あらためて余り見かけない弁護士会名だとも思いました。

[link:] » 仙台弁護士会 https://t.co/rNYTSqszJe

<hr />

　確認したところ仙台弁護士会というのはそのままのようです。ざっとした確認ですが、県名が含まれない県庁所在地名の弁護士会は、金沢弁護士会と仙台弁護士会の２つだけのようです。神奈川県弁護士会があえて名称変更に踏み切った理由も気になるところですが、この辺りにしておきます。

　すさまじい弁護士パワーのようなものを感じるのも、神奈川県の特徴です。いくらか関連性もあるのだと考えますが、重大事件も多く社会問題化されて来ました。もっとも大阪府より人工が多いという神奈川県の規模も１つ考慮に入れておく必要はあるかとは思います。

　神社などでパワースポットという言葉を近年よく見聞きするようになりましたが、私はかねてよりその神奈川県に強い弁護士パワーを感じてきました。その目の１つが小田原の村松謙弁護士です。法教育に熱心なようでもありますが、その辺りにも一層、社会的問題性を強く感じています。

　とれたてほやほやになりますが、次がうの字の最新ツイート２件になります。２件目はリツイートです。

▶ ツイート％un_co_the2nd（うの字）％2019/07/09 16:42％ https://twitter.com/un_co_the2nd/status/1148497678101123072
&twitter(1148497678101123072){theme:light}
> アホくさ  
▶

▶ ツイート％juntaba1（過食弁）％2019/07/09 12:37％ https://twitter.com/juntaba1/status/1148435990085693440
&twitter(1148435990085693440){theme:light}
> 色がある記事だし煽っており、記事は信用はできない。
> でもこの界隈の秋原場への異様な拘りやホスト（弁護士やると如何にクズか分かるはず）に好意的な話を見ると、「キモいオタク」への憎悪を正当な人権問題に糊塗しているという感想は否めない。… https://t.co/CG5A2NZUdk  
▶

　過食弁とありますが、割と最近までこのプロフィールの名前は「過食弁護士」だったと思います。匿名アカウントですが、実名情報がいくつか確認できるものがあり、それによると神奈川県川崎市に法律事務所を構える弁護士だったと思います。９５％ぐらいは間違いないと思います。

　深澤諭史弁護士らと共著を出したり、北周士弁護士らの弁護団にも参加していた弁護士です。

[link:] » 弁護士 独立・経営の不安解消Q&amp;A | 北周士, 田畑淳, 野田隼人, 深澤諭史, 向原栄大朗 |本 | 通販 | Amazon https://t.co/8KNk56cabW

<hr />

　上記がその共著となりますが、共著者の５人の弁護士のうち田畑淳という弁護士以外は、実名でTwitterアカウントを運用しています。残りの共著者という紹介をしていたと記憶にあり、消去法で残る弁護士は一人となります。

　次も弁護士パワーを強く感じるうの字のツイートです。

▶ ツイート％un_co_the2nd（うの字）％2019/07/09 15:38％ https://twitter.com/un_co_the2nd/status/1148481504680431618
&twitter(1148481504680431618){theme:light}
> ぼうちんと弁論要旨で「迷ったら無罪が刑事裁判です」って繰り返す必要性  
▶

　今は１７時０３分ですが、１５時３８分の投稿となっているうの字のツイートです。その１つ前には、深澤諭史弁護士のツイートのリツイートがありました。相変わらずシンパシーや価値の共有を感じあっているようです。深澤諭史弁護士も半端ないパワーの持ち主です。

▷ リツイート→un_co_the2nd（うの字）＞fukazawas（深澤諭史）｜2019/07/09 15:37／2019/07/08 23:08｜https://twitter.com/un_co_the2nd/status/1148481232541405184 ／ https://twitter.com/fukazawas/status/1148232290306183168
&twitter(1148481232541405184){theme:light}
> RT @fukazawas: （；・∀・）「無罪っぽいんで刑を軽くする」という趣旨の量刑理由を述べた某裁判員裁判の判決を思い出した。 https://t.co/52CVaxGG6m  

　うの字に関しては、現在は法政大学教授となっている坂本正幸弁護士のリツイートや返信も多かったと思います、いくらか古くなっていると思いますが、作成、公開済みのまとめ記事があるかと思います。

```
[3087]  % dp -p|grep un_co_the|grep sakamoto
[link:] 2017年11月25日08時26分の登録： SQL＝｛対象ユーザー：sakamotomasayuk（坂本正幸）　｜リツイートされたユーザ：un_co_the2nd（黄金糞闘士うのじ）｝ユーザー数：1／112件 http://hirono2014sk.blogspot.com/2017/11/sqlsakamotomasayukuncothe2nd1112.html
[link:] 2017年11月29日23時56分の登録： ＼坂本正幸　@sakamotomasayuk＼ 返信先: @un_co_the2ndさん\n\n一度うのじを連れてこないとならん店だな\n http://hirono2014sk.blogspot.com/2017/11/sakamotomasayuk-uncothe2nd.html
[link:] 2018年02月18日20時58分の登録： REGEXP：”@un_co_the2nd　（＃うの字）？”／坂本正幸（@sakamotomasayuk）の検索（2016-01-15〜2018-02-18／2018年02月18日20時58分の記録241件） http://hirono2014sk.blogspot.com/2018/02/regexpuncothe2ndsakamotomasayuk2016-01.html
[link:] 2019年05月17日10時45分の登録： egrep　-h　”RT　sakamotomasayuk．＊un_co_the2nd” 法務検察当局宛て参考資料弁護士等リスト化ツイートの検索＊／＊” http://hirono2014sk.blogspot.com/2019/05/egrep-hrtsakamotomasayukuncothe2nd.html
[link:] 2019年06月28日09時19分の登録： ”@un_co_the2nd”　from：sakamotomasayuk　-　Twitter検索　2019年06月28日09時18分：48件の取得 http://hirono2014sk.blogspot.com/2019/06/uncothe2ndfromsakamotomasayuk.html
[link:] 2019年06月28日09時35分の登録： REGEXP：”@un_co_the2nd”／坂本正幸（@sakamotomasayuk）の検索（2016-01-15〜2019-06-12／2019年06月28日09時35分の記録411件） http://hirono2014sk.blogspot.com/2019/06/regexpuncothe2ndsakamotomasayuk2016-01.html
```

```
▶（411／411） TW sakamotomasayuk（坂本正幸） 日時： 2019-06-12 13：09：00 +0900 URL： https：//twitter.com/sakamotomasayuk/status/1138659623055925249
{% tweet 1138659623055925249 %}
> @un_co_the2nd すべてが間違っている \n 最期は妖精が見えてｗ

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”@un_co_the2nd”／坂本正幸（@sakamotomasayuk）の検索（2016-01-15〜2019-06-12／2019年06月28日09時35分の記録411件） http://hirono2014sk.blogspot.com/2019/06/regexpuncothe2ndsakamotomasayuk2016-01.html#p411
```

　うの字に関しても「search-tweet.py "to:un_co_the2nd"」という自作のコマンドを日に何度か実行しているのですが、TwitterAPIの検索の精度が悪くて、収集とそれにつながるデータベース登録がしっかり出来ていないようです。

```
Diginnos-PC:~/2017_法務検察当局宛て注目参考資料弁護士のリスト化ツイート_m
[3095]  % list-tweet-egrep.sh '@un_co_the2nd'|grep sakamoto
https://twitter.com/sakamotomasayuk/status/1148468701127036928
https://twitter.com/sakamotomasayuk/status/1147665169390026752
https://twitter.com/sakamotomasayuk/status/1147661356792872960
https://twitter.com/sakamotomasayuk/status/1146657185834758144
https://twitter.com/sakamotomasayuk/status/1145979184713355264
https://twitter.com/sakamotomasayuk/status/1145975815584137216
https://twitter.com/sakamotomasayuk/status/1145343315052621829
https://twitter.com/sakamotomasayuk/status/1145343038681538560
https://twitter.com/sakamotomasayuk/status/1144594729071329281
https://twitter.com/sakamotomasayuk/status/1138659623055925249
https://twitter.com/sakamotomasayuk/status/1138657317585543168
https://twitter.com/sakamotomasayuk/status/1138652611077234688
https://twitter.com/sakamotomasayuk/status/1137988629668683776
https://twitter.com/sakamotomasayuk/status/1137927833785757696
https://twitter.com/sakamotomasayuk/status/1131135693009313792
```

　上記のデータを利用してあらたに法政大学教授坂本正幸弁護士とうの字の関係性をうかがう記録資料を作成しておきたいと思います。坂本正幸弁護士に関しては鹿児島大学で研究室というツイートも目にしたのですが、こちらの方も生物学を含めた研究科のような気分にさせられます。

[link:] 2019年07月09日17時29分の登録： REGEXP：”@un_co_the2nd”／坂本正幸（@sakamotomasayuk）の検索（2016-01-15〜2019-07-09／2019年07月09日17時29分の記録420件） http://hirono2014sk.blogspot.com/2019/07/regexpuncothe2ndsakamotomasayuk2016-01.html

```
▶（420／420） TW sakamotomasayuk（坂本正幸） 日時： 2019-07-09 14：47：00 +0900 URL： https：//twitter.com/sakamotomasayuk/status/1148468701127036928
{% tweet 1148468701127036928 %}
> @un_co_the2nd どうやら手続きがないのでああするしかなかったらしいが…

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”@un_co_the2nd”／坂本正幸（@sakamotomasayuk）の検索（2016-01-15〜2019-07-09／2019年07月09日17時29分の記録420件） http://hirono2014sk.blogspot.com/2019/07/regexpuncothe2ndsakamotomasayuk2016-01.html#p420
```

　上記がまとめ記事の最新ツイートになりますが、意外なことに大崎事件に関するものでした。そういえば大崎事件に関する坂本正幸弁護士のツイートというのは余り見た記憶がありません。上記のツイートも大崎事件はないですが、次のうの字のツイートの返信となっています。

▶ ツイート％un_co_the2nd（うの字）％2019/07/09 14:41％ https://twitter.com/un_co_the2nd/status/1148467176250019840
&twitter(1148467176250019840){theme:light}
> 大崎事件の特別抗告のアレ、タイミングが選挙前だったら…とか考えちゃっていかんな  
▶

　よく見ると本日７月９日の１４時４１分のツイートでした。今日は「選挙前」に絡めた弁護士ツイートをいくつか目にしてきたのですが、もう一つ取り上げておく必要を感じたローカスこと三浦義隆弁護士のツイートがありました。村松謙弁護士のツイートに近いタイミングだったと思います。

　よくよく考えてみると坂本正幸弁護士は、鹿児島大学の教授でその前は准教授でした。いずれもTwitterのプロフィールに掲載された情報ですが、現在の法政大学教授となったのは、ここ１，２年前のことかと思います。

　本書における大崎事件の取扱も情報量が多すぎて、どうしたものかと思いあぐねてきたのですが、とりあえず坂本正幸弁護士を切り口に取り上げておきたいと思います。

＜＜＜2019-07-09（火曜日）17：47＿［これまでの記述範囲の終了時刻］＜＜＜

