#+TITLE: "関テレ常務　息子逮捕でおわび　｜　2019／6／17（月）　17：39　-　Yahoo！ニュース（吹田市の警察官刺傷拳銃強奪事件）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-06-18 11:50:52 +0900
FILE_NAME: 2019-06-18-115052_関テレ常務　息子逮捕でおわび　｜　2019／6／17（月）　17：39　-　Yahoo！ニュース（吹田市の警察官刺傷拳銃強奪事件）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 報道  吹田市の警察官刺傷拳銃強奪事件 ジャーナリストの江川紹子氏
記事タイトル名の文字数：65　保存ファイル名の文字数：87

* 関テレ常務　息子逮捕でおわび　｜　2019／6／17（月）　17：39　-　Yahoo！ニュース（吹田市の警察官刺傷拳銃強奪事件）
  :LOGBOOK:
  CLOCK: [2019-06-18 火 11:52]--[2019-06-18 火 12:43] =>  0:51
  :END:

＞＞＞2019-06-18（火曜日）11：52＿［これからの記述範囲の開始時刻］＞＞＞

　ジャーナリストの江川紹子氏のタイムラインのツイートで知りました。ツイートの記事の見出しを見た時は、全く別の小さな事件だと思っていたので、記事の内容を読んで驚きました。父親のコメントはテレビで少し見ていましたが、職業や役職には触れていなかったように思います。

▶ ツイート％amneris84（Shoko Egawa）％2019/06/17 18:21％ https://twitter.com/amneris84/status/1140550063552368641
&twitter(1140550063552368641){theme:light}
> 自ら実名をさらして謝罪したのか…。息子はすでに33歳というのに。報じる側の責任みたいなのも感じたのだろうが…　→関テレ常務 息子逮捕でおわび https://t.co/568ASWXerm #Yahooニュースアプリ  
▶

　ジャーナリストの江川紹子氏のTwitterでタイムラインでこのツイートは「１８時間前」と表示されています。この１つ前の次のツイートは見覚えがあったのですが、今朝になって初めて知りました。他でも情報はまだ１つも見ていません。

▶ ツイート％amneris84（Shoko Egawa）％2019/06/17 10:22％ https://twitter.com/amneris84/status/1140429407909056512
&twitter(1140429407909056512){theme:light}
> 大阪の交番襲撃事件、被疑者が確保され、拳銃も押収されたとのこと。ただし、被疑者は否認。これ以上被害者が出ないのはよかったが、刺されたお巡りさん大丈夫かな。容態が気になる。防刃の服を着ててもこんなになるなんて…。  
▶

[link:] 2019年06月18日11時27分の登録： ＼Shoko Egawa　@amneris84＼見本が届いた、にゃう。店頭に並ぶのは20日です。カルトに人生を奪われないための゛心のワクチン゛としてもどうぞ。 http://hirono2014sk.blogspot.com/2019/06/shoko-egawaamneris8420.html

[link:] 2019年06月18日11時29分の登録： ＼Shoko Egawa　@amneris84＼自ら実名をさらして謝罪したのか…。息子はすでに33歳というのに。報じる側の責任みたいなのも感じたのだろうが…　→関テレ常務 http://hirono2014sk.blogspot.com/2019/06/shoko-egawaamneris8433.html

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-18 12:10／2019-06-18 12:08 URL： https://twitter.com/kk_hirono/status/1140819083987845121 https://twitter.com/s_hirono/status/1140818555899744257
&twitter(1140819083987845121){theme:light}
> 2019-06-18-112947_関テレ常務　息子逮捕でおわび　｜　2019／6／17（月）　17：39　-　Yahoo!ニュース.jpg https://t.co/caasVuR77o
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-18 12:10／2019-06-18 12:08 URL： https://twitter.com/kk_hirono/status/1140819103478796288 https://twitter.com/s_hirono/status/1140818483283820545
&twitter(1140819103478796288){theme:light}
> 2019-06-18-112655_ShokoEgawa（@amneris84）：　見本が届いた、にゃう。店頭に並ぶのは20日です。カルトに人生を奪われないための゛心のワクチン゛としてもど.jpg https://t.co/mzsCENK9zJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-06-18 12:10／2019-06-18 12:07 URL： https://twitter.com/kk_hirono/status/1140819133359017984 https://twitter.com/s_hirono/status/1140818410374230016
&twitter(1140819133359017984){theme:light}
> 2019-06-18-112533_ShokoEgawaさんがリツイート＞　NHK「クローズアップ現代＋」公式（@nhk_kurogen）：　【夜10時】もし、身近な人が逮捕されたら･･･.jpg https://t.co/OdFxmpBtmU
◁◁◁
<hr />

　「2019-06-18-112655_ShokoEgawa（@amneris84）」というスクリーンショットの記録ですが、この少し後に記事に関するツイートを見かけました。

　１１時半頃のことになると確認しましたが、感覚より少し前の出来事でした。実はこの少し前にも実名報道に関するかなり気になるツイートがありました。

　よくみるとジャーナリストの江川紹子氏のツイートは、「関テレ常務」と記事の見出しをカットしていたようです。関テレというのは関西テレビのことだと思いますが、名前は少し知っているだけの放送局です。それでもちょくちょくと見かけるので、かなり大きな規模かと思います。

　記事のページタイトルは「関テレ常務 息子逮捕でおわび | 2019/6/17(月) 17:39 - Yahoo!ニュース」なのですが、リンクを開いた記事には「拳銃強奪　容疑者の父・関西テレビ常務が謝罪「いまだ信じられない」デイリースポーツ」が見出しのようになっています。

```
大阪府吹田市で警察官が刃物で刺され、拳銃が強奪された事件で、強盗殺人未遂容疑で逮捕された飯森裕次郎容疑者（３３）の父で、関西テレビの飯森睦尚（むつひさ）常務取締役（６３）が１７日、代理人の弁護士を通じて、報道各社に書面コメントを発表した。「心よりお詫び申し上げます」と謝罪。「いまだ信じられない気持ち」と胸中を伝えている。なお、同局によると、この日は出社していない。


［source：］拳銃強奪　容疑者の父・関西テレビ常務が謝罪「いまだ信じられない」（デイリースポーツ） - Yahoo!ニュース https://headlines.yahoo.co.jp/hl?a=20190617-00000104-dal-ent
```

　ここでも気になったのは「代理人の弁護士を通じて、報道各社に書面コメントを発表した。」という点です。深澤諭史弁護士のタイムラインで刑裁サイ太らのツイートを見た衝撃的な余韻の中でのことでした。

＜＜＜2019-06-18（火曜日）12：43＿［これまでの記述範囲の終了時刻］＜＜＜


