#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "告発に至る経緯／金沢西警察署／平成4年／金沢西警察署の留置場での生活の始まり"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-20 13:46:08 +0900
FILE_NAME: 2018-12-20-134608_金沢西警察署の留置場での生活の始まり.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  ひるおび カルロス・ゴーン容疑者 人質司法 谷内孝志警部補
記事タイトル名の文字数：38　保存ファイル名の文字数：40

#contents

* テレビの「ひるおび（2018年12月20日放送）」でのカスハラ問題に出てきた「三波春夫オフィシャルブログ」お客様は神様、について

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:51／2018-12-20 13:39 URL： https://twitter.com/kk_hirono/status/1075614584428322816 https://twitter.com/s_hirono/status/1075611531922989056
&twitter(1075614584428322816){theme:light}
> 2018-12-20_110048＿テレビの画面・ひるおび・”カスハラ”対策「お客様は神様ではありません」　深刻化する”カスハラ」実態.jpg https://t.co/oVL91yimZ9
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:51／2018-12-20 13:38 URL： https://twitter.com/kk_hirono/status/1075614601935388675 https://twitter.com/s_hirono/status/1075611498209193984
&twitter(1075614601935388675){theme:light}
> 2018-12-20_110036＿テレビの画面・ひるおび・”カスハラ”対策「お客様は神様ではありません」　深刻化する”カスハラ」実態.jpg https://t.co/gsHQdZ2cwQ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:51／2018-12-20 13:38 URL： https://twitter.com/kk_hirono/status/1075614628242108417 https://twitter.com/s_hirono/status/1075611467217420288
&twitter(1075614628242108417){theme:light}
> 2018-12-20_110008＿テレビの画面・ひるおび・”カスハラ”対策「お客様は神様ではありません」　深刻化する”カスハラ」実態.jpg https://t.co/lcbpbXEu6U
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:51／2018-12-20 13:38 URL： https://twitter.com/kk_hirono/status/1075614648789983232 https://twitter.com/s_hirono/status/1075611435860819968
&twitter(1075614648789983232){theme:light}
> 2018-12-20_105916＿テレビの画面・ひるおび・”カスハラ”背景「格差の広がり」　深刻化する”カスハラ」実態.jpg https://t.co/YIgQRyITqb
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:51／2018-12-20 13:38 URL： https://twitter.com/kk_hirono/status/1075614667718852608 https://twitter.com/s_hirono/status/1075611403879297024
&twitter(1075614667718852608){theme:light}
> 2018-12-20_105843＿テレビの画面・ひるおび・”カスハラ”背景「お客様は神様」　深刻化する”カスハラ”実態.jpg https://t.co/bKodsW49pq
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:51／2018-12-20 13:38 URL： https://twitter.com/kk_hirono/status/1075614693274771456 https://twitter.com/s_hirono/status/1075611372853985280
&twitter(1075614693274771456){theme:light}
> 2018-12-20_105833＿テレビの画面・ひるおび・”カスハラ”背景「お客様は神様」　深刻化する”カスハラ”実態　三波春夫オフィシャルブログ.jpg https://t.co/WkJMTUC09H
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:51／2018-12-20 13:38 URL： https://twitter.com/kk_hirono/status/1075614717782020097 https://twitter.com/s_hirono/status/1075611341606445056
&twitter(1075614717782020097){theme:light}
> 2018-12-20_105815＿テレビの画面・ひるおび・”カスハラ”背景「お客様は神様」　深刻化する”カスハラ”実態　三波春夫オフィシャルブログ.jpg https://t.co/WcIG92ksdW
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:51／2018-12-20 13:38 URL： https://twitter.com/kk_hirono/status/1075614742062891008 https://twitter.com/s_hirono/status/1075611307619999744
&twitter(1075614742062891008){theme:light}
> 2018-12-20_105804＿テレビの画面・ひるおび・”カスハラ”背景「お客様は神様」　深刻化する”カスハラ”実態　三波春夫オフィシャルブログ.jpg https://t.co/2h4FBvdnGu
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:52／2018-12-20 13:38 URL： https://twitter.com/kk_hirono/status/1075614775499878400 https://twitter.com/s_hirono/status/1075611274350710784
&twitter(1075614775499878400){theme:light}
> 2018-12-20_105749＿テレビの画面・ひるおび・”カスハラ”背景「お客様は神様」　深刻化する”カスハラ”実態　三波春夫オフィシャルブログ.jpg https://t.co/i8JILhnq2a
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-20 13:52／2018-12-20 13:37 URL： https://twitter.com/kk_hirono/status/1075614806952964096 https://twitter.com/s_hirono/status/1075611239147950080
&twitter(1075614806952964096){theme:light}
> 2018-12-20_105303＿テレビの画面・ひるおび・深刻化する”カスタマーハラスメント”実態.jpg https://t.co/LQ6COo2cWs
◁◁◁
<hr />

　まだ確認していないのですが、「三波春夫オフィシャルブログ」という存在があるということは、ご存命でご活躍中なのかもしれません。もう長い間、テレビで姿も情報も見ていなかったので、遠い昔の時代の人としてご他界されているのではと思っていました。

　三波春夫という人は、昭和の時代の演歌界の大御所で、当時は視聴率も高かったNHK紅白歌合戦でトリをつとめられるなど、とても存在感の大きな人物として記憶に残っています。

　最近でも大阪万博の開催決定で、昭和の時代の大阪万博のテーマソングが何度もテレビで流れていたし、東京オリンピック関係の報道でも三波春夫の歌はよく流れていたように思います。しかし、三波春夫ご本人の話題というのはさっぱり見たことがありません。

　「カスハラ」という言葉がきっかけとなりましたが、「セクハラ」「パワハラ」に似ています。初めて見たような気もしたのですが、「カスタマーハラスメント」の略語だと知るとすぐに理解できました。定着したカスタマーサポートという言葉もあります。

　しかし、慣れないためか「カステラ」のことが頭に浮かぶこともあります。そういえば最近、どんたく宇出津店で長崎カステラが売っているのを見て、子供の頃に食べたことを思い出しました。カステラは好きではなかったですが、他とは味が地がていました。

* 歌手、三波春夫で思い出すのは個人的に、シベリア抑留、金沢西警察署の留置場で読んだ「黒パン俘虜記」という本のこと

　ちょっと三波春夫氏について調べてみたいと思います。昭和40年代にテレビで見ていたという印象がとても強いのですが、当時もかなり年配で、古老のような雰囲気や貫禄があったとして記憶に残っています。正確な年齢は、正直、想像がつきかねます。

```
三波 春夫（みなみ はるお、1923年7月19日 - 2001年4月14日、本名・北詰 文司（きたづめ ぶんじ））は、新潟県三島郡越路町（現・長岡市）出身の浪曲師、演歌歌手。紫綬褒章受章、勲四等旭日小綬章受章、新潟県民栄誉賞受賞。自身の長編歌謡浪曲などの作詞・構成時のペンネームとして「北村 桃児（きたむら とうじ）」を用いた。俳号は「北桃子（ほくとうし）」。

［source：］三波春夫 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%89%E6%B3%A2%E6%98%A5%E5%A4%AB
```

　ご他界されていたようですが、それもずいぶんと前のことで、2001年4月14日とあります。平成13年となるようです。私としては金沢刑務所に服役中の時期です。レクではスポーツ新聞の閲覧もあったのですが、レクのない日は見れませんでした。

　そういえば、新潟県で越路町という地名というか看板を見ていたと思うのですが、現在の長岡市とあります。金沢市場輸送での昭和59年の仕事では、金沢からの鮮魚の定期便で、長岡市から小千谷市に決まって行っていました。直江津、長岡、小千谷、新潟となっていました。

　1923年というのは大正12年となるようです。新潟県の出身というのは知らなかったような気もしますが、長岡市の近くとなると思い出すのは、元新潟市長のことです。名前がすぐに浮かんで来ませんが、あの騒動があった時期も今年だったのか時期がはっきり思い出せません。

　その元新潟市長は、弁護士でありながら医師でもあり、医療団体の理事長でもあったように思います。なにより注目したのは、三浦義隆弁護士とパートナー弁護士だったという話です。まるでお伽話にも思えたのですが、信憑性はありそうな話でした。

```
1945年（昭和20年）8月9日未明、日ソ中立条約を一方的に破棄して満洲国に侵攻してきたソビエト連邦（ソ連）軍と部隊は交戦。敗戦を同地で迎え9月11日に武装解除を受けソ連軍の捕虜となる。10月にハバロフスクの捕虜収容所に送られ、その後22歳から26歳までの約4年間、シベリア抑留生活を過ごす。収容所内でも浪曲を披露していたが、ソ連側による徹底した思想教育の中で、演目にも検閲が入るようになり、自らも強い影響を受け、オリジナルの「思想浪曲」や芝居を創作しソ連各地の収容所で披露するなど、捕虜教育係のような役割を負っていた。そうした事実を受け、帰国直後は「共産主義に洗脳されていた」と述べている［2］。また、当時のソ連の捕虜の扱いについては「国際法を無視し、捕虜の人権を蹂躙した国家的犯罪。更にソ連は謝罪も賠償も全くしていない」と非難している。こうした自身の戦争体験・抑留体験もあり、後に1986年11月10日「天皇陛下御在位60年大奉祝祭」に奉祝委員としてテープカットに参加［3］したり、日本を守る国民会議（現・日本会議）の代表委員となるなど、右翼系政治活動に参加するようになった。

［source：］三波春夫 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%89%E6%B3%A2%E6%98%A5%E5%A4%AB
```

　上記の引用部分にまったく意外な初めて知ることが書いてありました。「日本を守る国民会議（現・日本会議）の代表委員となるなど、右翼系政治活動に参加するようになった。」とあります。三波春夫で軍歌のような曲は聴いたことがなかったとも思います。

　「10月にハバロフスクの捕虜収容所に送られ、その後22歳から26歳までの約4年間、シベリア抑留生活を過ごす。」というのもずいぶんと長く感じます。

　時刻は17時35分です。外に出ていて、少し前に家に戻りました。図書館にも行っていました。久しぶりのことです。ちょっとした発見もありました。

　どうも出掛ける前と深澤諭史弁護士のタイムラインに変化がなく更新がされていないようです。やはり広く多くの人に見てもらいたいツイートは、更新せずにタイムラインの上位に表示させておきたいという傾向があるのかもしれません。

▶ ツイート％s_hirono（非常上告-最高検察庁御中_ツイッター）％2018/12/20 13:04％ https://twitter.com/s_hirono/status/1075602893372182528
&twitter(1075602893372182528){theme:light}
> 2018-12-20-125754_深澤諭史（@fukazawas）：お、バズってる（・∀・）.jpg https://t.co/M0zn6wIuwG  
▶

▶ ツイート％s_hirono（非常上告-最高検察庁御中_ツイッター）％2018/12/20 17:44％ https://twitter.com/s_hirono/status/1075673318185852929
&twitter(1075673318185852929){theme:light}
> 2018-12-20-173848_深澤諭史のリツイート（とろろ　@lit_soc）：弁護士登録を外すと非弁の問題を忘れるのって、ドラクエで転職すると前の職業固有の特技を忘れ.jpg https://t.co/9hI2hoxlCw  
▶

ISBN:4167402017:detail

```
商品の説明
受賞歴
第89回（昭和58年度上半期） 直木賞受賞

内容紹介
軍律の崩壊した集団に君臨する大ボス、小ボス。襲いくる飢餓、寒冷、暴力に耐えてひたすら帰国を待ち侘びる日々の支えは、小説と映画と流行歌への熱い思いだった
登録情報
文庫： 307ページ
出版社： 文藝春秋 (1986/1/25)
言語： 日本語
ISBN-10： 4167402017
ISBN-13： 978-4167402013
発売日： 1986/1/25
梱包サイズ： 15.6 x 11.4 x 2 cm

［source：］黒パン俘虜記 (文春文庫 (402‐1)) | 胡桃沢 耕史 |本 | 通販 | Amazon https://www.amazon.co.jp/%E9%BB%92%E3%83%91%E3%83%B3%E4%BF%98%E8%99%9C%E8%A8%98-%E6%96%87%E6%98%A5%E6%96%87%E5%BA%AB-402%E2%80%901-%E8%83%A1%E6%A1%83%E6%B2%A2-%E8%80%95%E5%8F%B2/dp/4167402017
```

　午前中に調べていたように思います。はてなブログの記事だと商品のサムネイル画像が表示されると思いますが、表紙は火事や地獄の灼熱をイメージさせる赤い色で、ポルターガイストの幽霊のような人の顔の挿絵があります。これは全く見覚えがないです。

　石川県金沢市には３つの警察署があって、金沢中警察署、金沢西警察署、金沢東警察署になるのですが、これは昭和の時代から今も変わっていないと思います。このうち金沢中警察署が現在の本多町に新築移転したのは、昭和の終わりか平成の初めだったと思います。

　前の金沢中警察署というのは少し離れた別の場所にありました。私が16歳の昭和56年8月28日、取り調べを受け鑑別所に送られた警察署でもあります。

　免停というのは平成に入ってから受けていないと思うので現在のことはわからないのですが、たぶん昭和61年春の免停明けで、夜の遅い時間に免許証を受け取りに行ったのが、前の金沢中警察署の建物に行った最後だったと思います。

　よく憶えているのは、警察官が私の免許書の顔写真を見て、本人かどうかずいぶん疑っていたことです。その免許証の写真というのはアフローヘアーでやせていて顔つきもだいぶん違っていたのだと思います。

　平成4年4月当時の金沢西警察署というのは、現在とほぼ同じで金石街道沿いになりますが、かなり古い建物で上に階段がなかったので2階建てに間違いないと思いますが、現在の新築となった建物と比較すると、かなり小さな規模であったと思います。

　金沢中警察署と金沢西警察署の管轄の違いというのも私はよくわかっていませんが、金沢西警察署の建物が大きくなることで管轄の範囲も広がったったことは考えられます。

　ついでに書く金沢東警察署ですが、金沢市内に住んでいても滅多にいく場所ではありませんでした。ただ、Googleマップを見ると、場所というのは大きな交差点の角で昭和56年当時から変わってはいないようでした。浅野本町のアパートにいた頃のことです。

　とにかく平成4年4月当時の金沢西警察署というのはこじんまりとしていて、2階の刑事課の部屋は全体がリビングルームのようになっていました。部屋の手前の階段を登ったところが舞踏会の踊り場のように広く、レトロで昔の映画に出てくるような雰囲気がありました。

　その当時の金沢西警察署の建物というのは、Googleの検索結果でも見たことがないですが、外からみる外見と建物の中の様子がずいぶん違っていたと思います。

　現在の金沢西警察署も金石街道沿いではありますが、建物の前に広い駐車場があるので金石街道からはけっこう奥まっています。これはテレビニュースでも見ることが多い風景です。以前の金沢西警察署は、ほぼ金石街道に面していて、駐車場のスペースも最低限に近かったと思います。

　その以前の金沢西警察署の建物はまだ調べたことがないのですが、同じ前の金沢中警察署は、Googleの画像検索で調べても写真が全く見つかりませんでした。図書館にでも行って探せば見つけることはできそうには思っています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜asahi（朝日新聞(asahi shimbun）） 日時：2018-12-21 11:45／2018-12-21 10:58 URL： https://twitter.com/kk_hirono/status/1075945265041879040 https://twitter.com/asahi/status/1075933386592514048
&twitter(1075945265041879040){theme:light}
> ゴーン前会長を会社法違反容疑で再逮捕　東京地検特捜部 https://t.co/drwTlbfzrE
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mainichijpnews（毎日新聞ニュース速報） 日時：2018-12-21 11:45／2018-12-21 11:20 URL： https://twitter.com/kk_hirono/status/1075945384730488832 https://twitter.com/mainichijpnews/status/1075938942417960960
&twitter(1075945384730488832){theme:light}
> ゴーン前会長を再逮捕　特別背任容疑　保釈の動き不透明に https://t.co/NEOrm7UXgd
◁◁◁
<hr />

　時刻は12月22日09時47分になります。昨日はまるまるお休みをしていたかと思います。ゴーン前会長再逮捕のニュースを２つリツイートしただけかと思います。久しぶりに早朝から小木港の東一文字堤防に行き、夜遅いの時間までアジ釣りをしていまいした。

　勾留延長取り消しが出て保釈が期待されていた状況での再逮捕だったので、Twitterの弁護士らの反応を活況を呈していました。いろいろといっぱいありすぎて、とても対応しきれないということを思い知らされたというのが、私としては一番大きなことかもしれません。

　このあと取り上げる項目について吟味をしていましたが、平成11年の安藤健次郎さんに対する傷害事件と、その裁判での弁護士らの対応を重視して、一審の金沢地方裁判所の判決を出した小川賢司裁判官にスポットを当てたいと考えています。

　裁判所のチェック機能という点でも、日産の元会長カルロス・ゴーン氏の刑事事件、刑事裁判は、弁護士らによる裁判所に対する厳しい態度ということで表示に参考になるものがあります。保釈や勾留請求理由開示などの従来の問題が、際立って表面化しています。

　その前に、この小項目を締めくくっておきたいと思います。平成4年当時の金沢西警察署は、平成11年当時の金沢中警察署にくらべ、規模の小さなものでした。留置場の部屋は３つだったと思います。縦にやや奥行きのある部屋でした。座敷牢という雰囲気でしたが、部屋にトイレはありませんでした。

　いちいち部屋から出してもらってトイレに言っていました。そのトイレの前辺りだったと思いますが、小さな古い本棚がありました。一般の家にもありそうな大きな本棚で、おそらく市販品だったとも思います。大きな本棚ではなかったので、本の数も限られていました。

　そこで借りて読んだ本として記憶にあるのが、「黒パン俘虜記」と「仮釈放」という本でした。他に「ドラえもん」の漫画の単行本を読みましたが、本棚から借りて読んだ本の記憶というのはそれぐらいです。被害者安藤文さんの意識不明の容体が気になって、集中ができませんでした。

