#+TITLE: "京アニ事件「労災前向き」に胸なでおろす　意外と難しい「業務起因」の線引き　-　弁護士ドットコム"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-11 11:34:48 +0900
FILE_NAME: 2019-08-11-113448_京アニ事件「労災前向き」に胸なでおろす　意外と難しい「業務起因」の線引き　-　弁護士ドットコム.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 労災認定  弁護士ドットコム うの字
記事タイトル名の文字数：47　保存ファイル名の文字数：69

* 京アニ事件「労災前向き」に胸なでおろす　意外と難しい「業務起因」の線引き　-　弁護士ドットコム
  :LOGBOOK:
  CLOCK: [2019-08-11 日 11:37]--[2019-08-11 日 12:42] =>  1:05
  :END:

＞＞＞2019-08-11（日曜日）11：37＿［これからの記述範囲の開始時刻］＞＞＞

　記事の発見は、深澤諭史弁護士のタイムラインで見たうの字のツイートのリツイート。前後のツイートの流れが気になってうの字のタイムラインを開いたところ、そこで見つけた弁護士ドットコムのツイートのリツイートでした。

▷ リツイート→fukazawas（深澤諭史）＞un_co_the2nd（うの字）｜2019/08/11 09:55／2019/08/11 09:52｜https://twitter.com/fukazawas/status/1160354054561656833 ／ https://twitter.com/un_co_the2nd/status/1160353301801525248
&twitter(1160354054561656833){theme:light}
> RT @un_co_the2nd: この警察官も自分が何をしてるか理解してないんだろうな。権力行使する者の無知は罪だ。  

▷ リツイート→un_co_the2nd（うの字）＞bengo4topics（弁護士ドットコムニュース）｜2019/08/11 09:45／2019/08/11 09:28｜https://twitter.com/un_co_the2nd/status/1160351419116879872 ／ https://twitter.com/bengo4topics/status/1160347217254727680
&twitter(1160351419116879872){theme:light}
> RT @bengo4topics: 京アニ放火事件では、京都労働局が労災認定に前向きだといいます。業務中でも「個人的な恨みによる第三者からの暴行」は原則対象外。それだけに歓迎したい判断です。理不尽な事件に巻き込まれた方々が最大限の補償を受けられるようになればと思います。
> 
>  h…  

　京都アニメーション放火殺人事件で労災というニュースは、前にも１つ見かけていましたが、内容はよく覚えていません。ただ、この弁護士ドットコムの記事ほど具体的で踏み込んだものではなかったと思います。なお、テレビでは労災問題として報道を見ていない気がします。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「労災」の検索結果 - Twilog https://t.co/Qul9Kdqv9F

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 11:54／2019-08-11 10:33 URL： https://twitter.com/kk_hirono/status/1160383907545489408 https://twitter.com/hirono_hideki/status/1160363642312724480
&twitter(1160383907545489408){theme:light}
> 京アニ事件「労災前向き」に胸なでおろす　意外と難しい「業務起因」の線引き - 弁護士ドットコム https://t.co/aiizuwaAm7
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 11:54／2019-08-09 23:45 URL： https://twitter.com/kk_hirono/status/1160383927195852801 https://twitter.com/hirono_hideki/status/1159838182122242048
&twitter(1160383927195852801){theme:light}
> 2019年08月09日22時29分の登録： ＼?落合洋司（弁護士・元検事・元法科大学院教授）?　@yjochi＼森友改ざん、職員自殺は「労災」　財務局認定、過重公務と因果関係 - 弁護士落合洋司（東京弁護士会）の日 https://t.co/wSKlijm7kr
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 11:54／2019-08-08 14:06 URL： https://twitter.com/kk_hirono/status/1160383959097729024 https://twitter.com/hirono_hideki/status/1159329938731782144
&twitter(1160383959097729024){theme:light}
> 未払残業・労災・解雇から働く人を守る金沢の弁護士ブログ | 金沢合同法律事務所 https://t.co/7lYJegaAPJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kyoto_np（京都新聞） 日時：2019-08-11 11:54／2019-07-30 20:33 URL： https://twitter.com/kk_hirono/status/1160384006325542915 https://twitter.com/kyoto_np/status/1156165975907164161
&twitter(1160384006325542915){theme:light}
> [京都新聞]京アニ事件、被害の従業員に労災適用の可能性　京都労働局が見解 https://t.co/nCaR9HQgOb
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 11:54／2019-07-30 23:48 URL： https://twitter.com/kk_hirono/status/1160384032821039105 https://twitter.com/hirono_hideki/status/1156214924944670720
&twitter(1160384032821039105){theme:light}
> 京アニ事件、被害の従業員に労災適用の可能性　京都労働局が見解 : 京都新聞 https://t.co/XwPwS9WWMa
◁◁◁
<hr />

```
京都アニメーションの放火殺人事件で、京都労働局の南保昌孝局長は３０日、従業員は就業中に被害に遭ったとみられることから、「労働災害として補償などの給付対象となる可能性が高い」と定例会見で述べた。

　一般的に、労災の認定は事件の事実関係や受給資格などを調査して判断される。同局によると、管轄の京都南労働基準監督署（伏見区）を中心に、従業員や遺族からの請求に迅速な対応ができるよう備えているという。

【 2019年07月30日 20時24分 】


［source：］京アニ事件、被害の従業員に労災適用の可能性　京都労働局が見解 ： 京都新聞 https://www.kyoto-np.co.jp/politics/article/20190730000145
```

　短い記事で内容も余り覚えていなかったですが、京都労働局の局長が30日定例記者会見で述べた、とあります。労働局というのも初めて目にしたように思います。労働基準監督署との違いもわからず、京都というのも京都府なのか京都市なのかと考えてしまいます。

　労働局の記者会見というのも聞いた覚えがないですし、それも定例会見とあります。日本経済新聞のような新聞であれば定期的に取材を記事にすることもあるのかとは想像する程度の知識です。

　記事をよく読むと「同局によると、管轄の京都南労働基準監督署（伏見区）を中心に、従業員や遺族からの請求に迅速な対応ができるよう備えているという。」とありました。労働基準監督署の監督官庁ということになるのかと想像はしますが、あらためて労働局とは見知らぬ存在でした。

　考えてみると、相模原市の津久井やまゆり園の殺傷事件でも、ニュースで職員が被害にあったと見たように思いますが、労災が問題にされたニュースは見ていない気がします。

　京都アニメーション放火殺人事件は刑事事件として被害者の数も記録的と聞きますが、事件の地元紙である京都新聞でもこのような短い内容の記事となっていて、テレビではほとんどニュースを見ていないと思うのは、いろいろと考えさせられるところでもあります。

　京都では京都弁護士会が、京都アニメーション放火殺人事件の被害者や遺族を対象に無料の法律相談を行っているという情報もネットで見かけています。労災問題でテレビで姿を見ることが多いのは川人博弁護士ですが、近頃はなぜか、名前の表示を見かけず、気になていました。

　この川人博弁護士についても以前ネットで調べたことがあったのですが、個人経営に近いスタイルで弁護士業務を行っている印象でした。まだ調べ方が足らず、それで記憶もしっかりしていないのだと思いますが、労働災害の在り方や補償について深く考えさせられる存在です。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「川人博」の検索結果 - Twilog https://t.co/PgCUwaxRfU

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:20／2019-07-28 16:36 URL： https://twitter.com/kk_hirono/status/1160390488307847169 https://twitter.com/hirono_hideki/status/1155381446061649921
&twitter(1160390488307847169){theme:light}
> 「見せかけの副業」が認定を困難に…残業134h、トラック運転手の過労死が明らかにした課題 - 弁護士ドットコム https://t.co/7I5NMS0RBx \n  代理人の川人博弁護士は「これほど明確な事案でも労基署が慎重になった。実… https://t.co/AfcS3qTw3M
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:20／2019-04-06 06:38 URL： https://twitter.com/kk_hirono/status/1160390527189041154 https://twitter.com/hirono_hideki/status/1114281256928174080
&twitter(1160390527189041154){theme:light}
> ツイート数：1 リツイート数：0 トータル：128 \n  川人博 \n  ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "川人博"
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:20／2019-04-05 09:24 URL： https://twitter.com/kk_hirono/status/1160390580364382208 https://twitter.com/hirono_hideki/status/1113960682209206272
&twitter(1160390580364382208){theme:light}
> JAXA「いぶき」管制、過労自殺を認定　夜勤16時間「達成困難なノルマ」 - 弁護士ドットコム https://t.co/nWpzJHpRFC \n  遺族代理人を務める川人博弁護士らが厚労省記者クラブで会見を開き、明らかにした。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:21／2019-03-24 12:12 URL： https://twitter.com/kk_hirono/status/1160390637276946432 https://twitter.com/hirono_hideki/status/1109654106212167680
&twitter(1160390637276946432){theme:light}
> 厚生労働省が全国に設置する労働基準監督署が、労災認定をする際、本来認めるべき時間を「労働時間」と認めない事例が目立つようになったとして、「過労死弁護団全国連絡会議」の幹事長を務める川人博弁護士や遺族が3月11日、東京・霞が関の厚労… https://t.co/Qx6lIdArCL
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:21／2018-10-18 13:42 URL： https://twitter.com/kk_hirono/status/1160390694470426624 https://twitter.com/hirono_hideki/status/1052781846382014464
&twitter(1160390694470426624){theme:light}
> 高齢警備員死亡 遺族が労災申請｜NHK 首都圏のニュース https://t.co/5s2fD3IxQ6 \n  代理人の川人博弁護士は「政府は高齢者の労働を促進しているが、警備や運送業など過酷な仕事で働いている高齢者も多い。その労働環境のあり方を議論すべきだ」と
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:21／2017-11-20 10:37 URL： https://twitter.com/kk_hirono/status/1160390762451701762 https://twitter.com/hirono_hideki/status/932422639393456130
&twitter(1160390762451701762){theme:light}
> 今日のNHK「プロフェッショナル仕事の流儀」には、過労死と闘う川人博弁護士が登場！！　見なきゃ！！ https://t.co/yxuRJC2rhO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:21／2017-11-16 16:39 URL： https://twitter.com/kk_hirono/status/1160390802587058176 https://twitter.com/hirono_hideki/status/931064047805480960
&twitter(1160390802587058176){theme:light}
> REGEXP：”（弁護士）？川人博（弁護士）？”／データベース登録済みツイートの検索（2017年11月16日15時44分の記録19件） https://t.co/3aI7ZsT5tp
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:21／2017-11-14 21:15 URL： https://twitter.com/kk_hirono/status/1160390857196855296 https://twitter.com/hirono_hideki/status/930408850246713344
&twitter(1160390857196855296){theme:light}
> プロフェッショナル 仕事の流儀「過労死と闘い、命を守る～弁護士・川人博～」 2017年11月20日（月） 22時25分～23時15分 の放送内容 https://t.co/FgDtINpzIs
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:22／2017-09-01 21:55 URL： https://twitter.com/kk_hirono/status/1160390901585235969 https://twitter.com/hirono_hideki/status/903602128165490688
&twitter(1160390901585235969){theme:light}
> 最長で月１３５時間に上った長時間労働が原因として、長野労働基準監督署が労災認定していたことが３１日、分かった。遺族代理人の川人博弁護士が記者会見し明らかにした。認定は２４日付。 https://t.co/Uhy5U3dWnc
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 12:22／2017-08-11 16:42 URL： https://twitter.com/kk_hirono/status/1160390933591941120 https://twitter.com/hirono_hideki/status/895913384620814336
&twitter(1160390933591941120){theme:light}
> 電通過労死の遺族代理人・川人博弁護士「経営者が無能」｜注目の人 直撃インタビュー https://t.co/kZRDVHOivn
◁◁◁
<hr />

　Twilogでの「川人博」の検索結果ですが、思ったより数は少ない内容も簡素ものばかりでした。この労働災害問題というのは事実関係や利害関係も複雑で資料も膨大になりがちと想像するのですが、かなり多く手がけている様子の川人博弁護士の存在についてかねて大きな疑問を抱いておりました。

　弁護士という社会的存在についてよくよく考える機会でもあるように思います。たいていの労働災害は警察が過失致死傷罪などの嫌疑で捜査をする印象もありますが、ずっと前の事故の報道をすっかり忘れていた頃に見かけたりすると、ずいぶんと長引く印象も受けます。

　労災や損害賠償が認定されるか否かは、遺族や当事者にとって人生を左右する大きな岐路となるもので、それだけ弁護士に対する期待も大きく、依存度も高まるのではと想像されるところです。

　次は、弁護士ドットコムの記事から引用をしておきたいと思います。川人博弁護士については、別の記事として記録を作成しておこうと思います。

```
労働問題にくわしい波多野進弁護士は、京アニ事件で労災が適用されそうなことに、ホッとしたひとりです。

「第三者の『犯罪行為がたまたま会社で起こっただけ』として、労災が認められないことがあるからです」

実際、厚生労働省の労災パンフレットにも、事業場施設内での仕事中であっても業務災害として認められない例の一つとして、「労働者が個人的な恨みなどにより、第三者から暴行を受けて被災した場合」が挙げられています。

［source：］京アニ事件「労災前向き」に胸なでおろす　意外と難しい「業務起因」の線引き - 弁護士ドットコム https://www.bengo4.com/c_5/n_9989/
```

　労働災害についても以前いくらか勉強をしたことがあるのですが、最近は特に調べるようなこともしていないので、最新の動向というのもわかっていません。もともと弁護士が抱え込んで表に出にくい情報とも考えるところは、勾留期間の未決通算にも共通するものです。

＜＜＜2019-08-11（日曜日）12：42＿［これまでの記述範囲の終了時刻］＜＜＜

