#+TITLE: "参考資料／弁護士業界の現状／秋田の弁護士刺殺／深澤諭史弁護士のタイムラインで見ていた秋田の弁護士刺殺の損害賠償の判決、２月１３日に出ていた判決と今日知った"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-02-20 23:47:55 +0900
FILE_NAME: 2019-02-20-234755_深澤諭史弁護士のタイムラインで見ていた秋田の弁護士刺殺の損害賠償の判決、２月１３日に出ていた判決と今日知った.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  深澤諭史弁護士 秋田の弁護士刺殺
記事タイトル名の文字数：77　保存ファイル名の文字数：76

#contents

* 深澤諭史弁護士のタイムラインで見ていた秋田の弁護士刺殺の民事裁判の控訴審逆転勝訴判決
  :LOGBOOK:
  CLOCK: [2019-02-20 水 23:50]--[2019-02-21 木 01:33] =>  1:43
  :END:

＞＞＞2019-02-20（水曜日）23：50＿［これからの記述範囲の開始時刻］＞＞＞

```
[10008]  % grep 秋田 fukazawas_201703201148-201902202101.txt |tac
▶RT fukazawas（深澤諭史）｜ria_cat（りあ） 日時：2017-07-15 20:35／2017-07-15 20:09 URL： https://twitter.com/fukazawas/status/886187426535809024 https://twitter.com/ria_cat/status/886180998311890946 TWEET： セブンイレブン由利本荘大門本町通店。景観条例地区のため、秋田県で唯一の「黒いセブンイレブン」になっているのだそうです。偶然通りかかってびっくりしました。 https://t.co/pRH0NtMcyj  
▶RT fukazawas（深澤諭史）｜asamorihisaya（朝森久弥） 日時：2017-07-18 15:25／2017-07-16 21:31 URL： https://twitter.com/fukazawas/status/887196576585703424 https://twitter.com/asamorihisaya/status/886563990687502336 TWEET： 韓国より最低賃金が安い青森県・秋田県・宮城県・秋田県・山形県・福島県・鳥取県・島根県・徳島県・香川県・愛媛県・高知県・佐賀県・長崎県・熊本県・大分県・宮崎県・鹿児島県・沖縄県の皆さん… \n https://t.co/3nyRf0Zb0g  
▶RT fukazawas（深澤諭史）｜sitimi502（502/七味） 日時：2017-09-01 23:55／2017-09-01 14:27 URL： https://twitter.com/fukazawas/status/903632445043392512 https://twitter.com/sitimi502/status/903489564919992320 TWEET： 今朝の秋田魁新報。関東大震災の時、デマが原因で朝鮮人殺人事件が立て続けに起きたけど、被害者には訛りの強い日本の地方出身者もいたんだよという社説。地元では授業でも余談的に先生が話してたんだけど、ネットとかだとあんまりこの手の話題を見… https://t.co/W85zZ84zxT  
▶RT fukazawas（深澤諭史）｜BB45_Colorado（LN BB-45） 日時：2017-12-10 14:08／2017-12-10 11:14 URL： https://twitter.com/fukazawas/status/939723511840489472 https://twitter.com/BB45_Colorado/status/939679684840734720 TWEET： 秋田・・・・ハワイ防衛用 \n 山口・・・・グァム防衛用 \n  \n 以前指摘した通りになった｡ https://t.co/s9APpHQDrE  
▶RT fukazawas（深澤諭史）｜trks0007（秋田犬あさり） 日時：2018-03-27 13:27／2018-03-25 15:44 URL： https://twitter.com/fukazawas/status/978488725037498368 https://twitter.com/trks0007/status/977798380884815872 TWEET： 中学入学に向けて二階で大掃除中の妹ちゃんから… \n 「ランドセルどうしたらいい？」と声が。 \n 「好きにしなさぁ～い！」と何気なく答える私。 \n 庭に出た時…改めて娘の柔軟な発想力にある意味成長を感じた💦 #秋田犬 https://t.co/oPBSQkSqUQ  
▶RT fukazawas（深澤諭史）｜Beriozka1917（異邦人） 日時：2018-05-27 12:32／2018-05-27 09:17 URL： https://twitter.com/fukazawas/status/1000580445501767680 https://twitter.com/Beriozka1917/status/1000531342298267648 TWEET： 平昌五輪の時に、主役であるメダリストを差し置いて安倍首相のドアップを載せた時も神経を疑いましたが、この秋田犬をザギトーヴァ選手に送ったのは秋田犬保存会ですよね？それなのに何故、写っているのは安倍夫妻ばかりなのでしょうか。過労死遺族… https://t.co/y2cEdRbFeQ  
▶RT fukazawas（深澤諭史）｜kou_1970（鈴木　耕） 日時：2018-06-17 19:41／2018-06-17 10:46 URL： https://twitter.com/fukazawas/status/1008298484636663808 https://twitter.com/kou_1970/status/1008164064529223680 TWEET： これが、淋しい我が町のメインストリート。秋田は今や、どこへ行っても……。 https://t.co/YWvzfLQjaw  
▶RT fukazawas（深澤諭史）｜Komatsucraft（小松和彦（小松クラフトスペース）） 日時：2018-07-25 07:30／2018-07-24 08:57 URL： https://twitter.com/fukazawas/status/1021885400422338562 https://twitter.com/Komatsucraft/status/1021544832215351296 TWEET： 某議員のLGBT発言でナチスの同性愛者に対する迫害についても話題になっていますが、そのことを報じる昭和9年12月の秋田魁新報の記事がこちらです（秋田の花柳界と売春関係の記事に挟まれている） https://t.co/GXHJynreRd  
▶RT fukazawas（深澤諭史）｜syoyuri（yuri） 日時：2019-02-13 21:11／2019-02-13 20:42 URL： https://twitter.com/fukazawas/status/1095656633332510720 https://twitter.com/syoyuri/status/1095649286237315072 TWEET： 弁護士殺害２審 県にも賠償命令｜NHK 秋田県のニュース   https://t.co/Vs5vkLVXj8 \n  \n 日弁連消費者問題対策委発行「消費者問題ニュース」140号は津谷先生の追悼特集でした。津谷先生がどれほどの方だったか、石… https://t.co/i4RnRgdfwy
```

▷ リツイート→fukazawas（深澤諭史）＞syoyuri（yuri）｜2019/02/13 21:11／2019/02/13 20:42｜https://twitter.com/fukazawas/status/1095656633332510720 ／ https://twitter.com/syoyuri/status/1095649286237315072
&twitter(1095656633332510720){theme:light}
> RT @syoyuri: 弁護士殺害２審 県にも賠償命令｜NHK 秋田県のニュース   https://t.co/Vs5vkLVXj8
> 
> 日弁連消費者問題対策委発行「消費者問題ニュース」140号は津谷先生の追悼特集でした。津谷先生がどれほどの方だったか、石戸谷先生ほか先生方のこ…  

　時刻は２３時５７分です。ついさきほどテレビでニュースzeroが終わりましたが、特に印象的なニュースはありませんでした。八王子市の大型犬が乳児を死亡させた問題で祖父母が書類送検されたニュースは、夕方のeveryで見た内容とほとんど同じだったと思います。

　もちろん、わいせつ事件で無罪判決が出た外科医のニュースはありませんでした。前のエントリーで書き忘れたようにも思いますが、夕方のeveryでニュースの項目を見ただけだったものは、「準強制わいせつ」となっていました。これはネットのニュースの見出しでは見ていない気がします。

　準強姦も準強制性交などとなっているものと思いますが、泥酔状態にさせて性交に及ぶなど近年テレビで何度か大きく取り上げられてきたので、知っている人も多いのではと思います。睡眠薬のようなものを使う場合もあったかと思います。

　医師の場合は治療行為だと誤信させたり、信頼関係で抵抗が困難だった場合も準強姦を認めた判例があったかもしれません。考えてみると弁護側は、被害者がせん妄状態で意識が混濁していたような主張をしているので、まさに準強制わいせつの構成要件に該当する状態だったようです。

［link：］ ゴルフ場経営者に無罪＝準強姦罪で強制起訴－鹿児島 - アルコール・カフェイン中毒と広告の影響 https://blog.goo.ne.jp/caffeineaddiction/e/3c922698ea40b3298ce5de49354c0b26

　調べると上記の鹿児島の事件が出てきました。検察審査会の議決を受けた起訴だったことを思い出しましたが、鹿児島地裁の判決で確定したのか、その先のことは記憶にないです。鹿児島地裁だと控訴した場合は、福岡高裁宮崎支部の審理になりますが、それは情報を見ていない気がします。

　もう一つの鹿児島の強姦事件は、被疑者・被告人が泥酔状態で記憶がなかったという主張でしたが、無罪判決が確定しているかと思います。その事件もDNA鑑定や科捜研の証拠品の管理や保存が問題とされた刑事裁判でした。せん妄の外科医の事件と一緒に思い出しながら考えていました。

　2017年03月20日11時48分以降のの深澤諭史弁護士のツイートで、「秋田」をキーワードに含むものを検索結果として冒頭に列挙しましたが、秋田の弁護士刺殺に関するツイートは、上記の１件だけでした。

　他に似たものを１つか２つ目にしていたように思っていたのですが、これは目視で確認をしておきたいと思います。上記の深澤諭史弁護士のツイートをよく見ると、２月１３日２１時１１分がリツイートの時刻となっていました。

　2,3日前に見たものとばかり思っていたのですが、見てにすぐスクリーンショットの記録は行っているはずなので、そちらで確認ができそうです。

　やっているとばかり思っていた深澤諭史弁護士のタイムラインのスクリーンショットは、やっていなかったようです。いずれにせよ、奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)で秋田をキーワードにしたツイートは、ここ最近のものだと思います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「秋田」の検索結果 - Twilog https://t.co/WcXebC9d43

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-21 00:45／2019-02-18 10:38 URL： https://twitter.com/kk_hirono/status/1098247306405531648 https://twitter.com/hirono_hideki/status/1097309435993583616
&twitter(1098247306405531648){theme:light}
> 秋田名物「しょっつる鍋」とは？お家で作る簡単レシピとおすすめ店 - macaroni https://t.co/WJwFM5mOcS
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-21 00:45／2019-02-19 22:18 URL： https://twitter.com/kk_hirono/status/1098247354870722560 https://twitter.com/hirono_hideki/status/1097847778582003712
&twitter(1098247354870722560){theme:light}
> » 弁護士刺殺、秋田県が上告へ　警官過失認定の判決を不服（共同通信） - Yahoo!ニュース https://t.co/DhtzUlIs9D
◁◁◁
<hr />

　１８日にも秋田を含むツイートがありますが、これは前日に小木港の釣具店でもらってきたハタハタを調理するために調べたときの情報でした。「しょっつる鍋」というのは聞いたことがあったのですが、ハタハタの魚醤のことだとは思わず、少なくとも記憶にありませんでした。

　なお、小木港や宇出津でも「いしり」というイカの魚醤を作っているので、魚醤というのは、けっこう身近な存在です。伝統調理とのことですが、私が存在を知ったのは平成に入ってからだと思います。母親が買ってくることはなかったですが、何かで知って使ってみました。

　最初に「いしり」を使ったときは、醤油と同じつもりで沢山入れてしまい、余に癖が強かったので、それから何年も買ったこともなかったのですが、数年前に買ったとき、少量で使ってみると悪い感じではなかったです。最近も買ってこようと思いながら忘れています。

　考えてみると、秋田県内というのは国道７号線沿いに食堂が余りなかったように思います。能代市から大館市の間には食堂があって入った記憶もありますが、八郎潟のあたりにゲームセンターがあって、そこに弁当屋がありました。余り好きではなかったポテトサラダが美味しかったと記憶に残っています。

　秋田は夜中に市場で魚を降ろすことがほとんどでした。鮮魚を運んでいて食堂に入るということは、まずありません。食べても高速道路のパーキングのうどんぐらいで、他はコンビニで買ったおにぎりなどを運転しながら食べていました。

　そういう事情もありましたが、それを別にしても秋田県内の国道７号線沿いの食堂というのは、ほとんど見なかった気がします。鮮魚以外の急がない仕事で、のんびりと秋田県内を走行することもありましたが、地元の人と会話をしたという記憶もほとんどありません。

［link：］ 秋田 OR 津谷 from：fukazawas - Twitter検索 https://twitter.com/search?l=&q=%E7%A7%8B%E7%94%B0%20OR%20%E6%B4%A5%E8%B0%B7%20from%3Afukazawas&src=typd&lang=ja

　精度がかなり悪いTwitter検索で調べましたが、秋田にマッチしたのは次の３件のツイートだけでした。津谷というのは、秋田の弁護士刺殺で刺殺された弁護士の名前のようですが、該当はありませんでした。

▶ ツイート％fukazawas（深澤諭史）％2016/06/30 17:11％ https://twitter.com/fukazawas/status/748428672500019200
&twitter(748428672500019200){theme:light}
> ストーカーやＤＶ、加害者の治療促進　県警が再発防止策｜秋田魁新報電子版 https://t.co/WVc5XEpiA3
> 県警少年女性安全課は「被害者の安全確保だけではなく、加害者へのアプローチを行い、被害防止に結び付けたい」  
▶

▶ ツイート％fukazawas（深澤諭史）％2014/12/28 09:53％ https://twitter.com/fukazawas/status/549005238854639616
&twitter(549005238854639616){theme:light}
> どの都道府県なら弁護士は儲かるのか？（２０１４年版）
> http://t.co/dafCfY39JY
> ＞ＲＴ
> そういえば，こんなデータがありましたね。
> 
> 「４年経った今でも茨城が強い！
> 
> そして，僅差で秋田が追ってきました！
> 
> 以下，富山，岩手，滋賀と続きます。」  
▶

▶ ツイート％fukazawas（深澤諭史）％2014/10/30 14:07％ https://twitter.com/fukazawas/status/527688196402847744
&twitter(527688196402847744){theme:light}
> どの都道府県なら弁護士は儲かるのか？（２０１４年版）
> http://t.co/dafCfXcmlM
> 
> 茨城，秋田，富山，岩手，滋賀の順だそうです。
> 
> 一側面でしかないですけれど，地域における弁護士資格そのものの経済的価値という，それなりに重要な指標かも。
> 
> 相変わらず東京は…（汗  
▶

　そういえば秋田といえばナマハゲで、一月ほど前になりますか、世界遺産の登録で繰り返しテレビで取り上げられていたこともありました。能登町にもアマメハギという似たものがあって、同じく世界遺産に登録されたのですが、紙で作った包丁を持っていたことを思い出しました。

　秋田の弁護士宅には、刃物と拳銃を手にして襲撃があったようです。そこに至るにはやりとりもあったのかと想像をしますが、その以前の情報が一切出てこなかったのも、この弁護士刺殺事件の特徴でした。被疑者・被告人の声も一切聞こえてはいないと思います。ずいぶん調べもしました。

　その拳銃ですが、本物とも偽物とも弾が入っていたともいなかったとも情報は一切みていません。たまたま私の目に触れなかったという可能性は否定できないですが、模造という情報は見ていないので、おそらくは本物の拳銃だったのでしょう。

　このあと確認のため調べておきたいと思いますが、私の記憶では刑事裁判の一審が有期の懲役刑で、それが控訴審で無期懲役になったように思います。裁判所が確定的で強固な殺意を認定したと読んだ記憶が鮮明に残っています。

＜＜＜2019-02-21（木曜日）01：32＿［これまでの記述範囲の終了時刻］＜＜＜

* 「弁護士刺殺で秋田県が上告」というニュース、初めに見たのは深澤諭史弁護士のタイムラインではなく、１９日の夜、奥村徹弁護士のタイムラインの奥村徹弁護士のツイートだった
  :LOGBOOK:
  CLOCK: [2019-02-21 木 02:40]--[2019-02-21 木 03:27] =>  0:47
  :END:

＞＞＞2019-02-21（木曜日）02：40＿［これからの記述範囲の開始時刻］＞＞＞

　深澤諭史弁護士のタイムラインを直に遡って、秋田の弁護士刺殺に関するリツイートを発見したのですが、調べると深澤諭史弁護士のリツイートの時刻が２０日となっていました。

　さきほど私自身のツイートで、秋田の弁護士刺殺に関するツイートを１９日の２２時台として見つけていたので、深澤諭史弁護士のタイムラインで最初に知ったとすると、順序が合わないことになります。

　２０１９年２月１９日２２時ころのスクリーンショットを探したところ、奥村徹弁護士のタイムラインのスクリーンショットを見つけました。もう一つ思い出したのは、その奥村徹弁護士のツイートの記事のリンクが弁護士ドットコムのもので、ログインを要求され閲覧できなかったことです。

　弁護士ドットコムといえば、創業者の弁護士の名前をかなり長い間、見かけていないことですが、2,3年前の秋だと思いますが、弁護士会のシンポジウムの同じブースで、深澤諭史弁護士とその創業者の弁護士が肩を並べるように、講演をしたという情報を見たことが強く印象的でした。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-21 02:52／2019-02-19 22:15 URL： https://twitter.com/kk_hirono/status/1098279122604683264 https://twitter.com/s_hirono/status/1097847161213964289
&twitter(1098279122604683264){theme:light}
> 2019-02-19-220713_ystkさんのツイート：　”敵が病的だからといって通院させる術などあるはずもないので、医療関係者のお力をお借りすることは基本的にないですね。お借りできれば.jpg https://t.co/6EDQbdR5Cm
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-21 02:52／2019-02-19 22:15 URL： https://twitter.com/kk_hirono/status/1098279147917402112 https://twitter.com/s_hirono/status/1097847233481854976
&twitter(1098279147917402112){theme:light}
> 2019-02-19-221418_強制わいせつ／準強姦／買春／児童ポルノ／児童福祉法／青少年条例弁護人弁護士奥村徹（大阪弁護士会）4時間4時間前その他弁護士刺殺、県上告へ　弁護団「遺憾」.jpg https://t.co/ilY5ZPAUA2
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-21 02:52／2019-02-19 22:39 URL： https://twitter.com/kk_hirono/status/1098279175515848706 https://twitter.com/s_hirono/status/1097853076407373824
&twitter(1098279175515848706){theme:light}
> 2019-02-19-221622_ログイン　-　弁護士ドットコム.jpg https://t.co/TRWUE84odS
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-21 02:52／2019-02-19 22:39 URL： https://twitter.com/kk_hirono/status/1098279238342328320 https://twitter.com/s_hirono/status/1097853149115703296
&twitter(1098279238342328320){theme:light}
> 2019-02-19-221726_弁護士刺殺、秋田県が上告へ　警官過失認定の判決を不服（共同通信）　-　Yahoo!ニュース.jpg https://t.co/PXZCAfH2x8
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-21 02:52／2019-02-19 22:39 URL： https://twitter.com/kk_hirono/status/1098279272261705728 https://twitter.com/s_hirono/status/1097853222364934144
&twitter(1098279272261705728){theme:light}
> 2019-02-19-223702_50万円〜3600万円！肝臓に病を抱えるあなたが国からもらえるかもしれない給付金とは？.jpg https://t.co/i5tVtNI9V7
◁◁◁
<hr />

　前後に秋田の弁護士刺殺とは無関係のスクリーンショットを一緒に掲載しましたが、いずれも同じ２２時台に目にした印象的なツイートやホームページで、当時の状況の流れとしてご紹介をしておきたいと思います。偶然ではない、何かの働きがあっての出会いかもしれません。

　先に、三浦義隆弁護士のツイートがあって、後に肝炎訴訟の宣伝のようなホームページがあります。肝炎訴訟に関する情報は久しぶりに目にしたとも思いました。

　肝炎訴訟について詳しくは調べていないので、正確なことは書けないのですが、法律の立法があって、その法律で一定の割内の報酬が公的に弁護士に入る仕組みとなっているようです。国庫というのか、国民の税金が原資になっているのだと思います。

　国が支払いの相手だととりっぱぐれもないので弁護士としては好都合なのだと思います。弁護士でなくても確実性や安心感は大きいのが当たり前のことかと思います。国に続くのが市町村ですが、警察相手の損害賠償の支払先は都道府県であり、検察だと国になるという話です。

　秋田の弁護士刺殺の場合、秋田県警の民事上の責任追及するということは秋田県に支払いを求めることになります。ずいぶん前に調べたことで、余り理解もできなかったのですが、公安委員会というのが県が警察を監督するかたちで関わっては来るようです。

　そのような関係性というのも私の告発・非常上告事件の場合は、石川県警察であり石川県ということになるのですが、秋田の弁護士刺殺のことは、手続き的な意味でもとても参考になるものです。本書を読んでもらう第一の相手方も石川県警であり、私は常にそれを意識しています。

　三浦義隆弁護士のツイートですが、次の記録を作成済みです。警察のことを法律の素人とツイートで公言したのも三浦義隆弁護士であり、適性手続きのためにもいろいろと石川県警には参考にしていただきたいですし、そのための情報提供の記録です。非常上告の最高検察庁も同じです。

[link:] 2019年02月19日22時06分の登録： ＼ystk　@lawkus＼敵が病的だからといって通院させる術などあるはずもないので、医療関係者のお力をお借りすることは基本的にないですね。お借りできれば嬉しいんですけど http://hirono2014sk.blogspot.com/2019/02/ystklawkus_19.html

　ここでは三浦義隆弁護士のツイートと、そのツイートの前後を含めた約１９９件のツイートをまとめた記事の紹介にとどめておきますが、石川県警の捜査の不手際を悪用し、私を精神的に追い詰め、精神に問題のある人間という烙印を押したのが被告発人の弁護士らの所業です。

　そういえば、昨日か一昨日に、過去の奥村徹弁護士のツイートを取り上げておこうと考えていました。中村元弥弁護士と落合洋司弁護士（東京弁護士会）のツイートのやりとりに似ていると書いた件です。早く思い出せましたが、忘れていたので、早めに取り上げておきます。

＜＜＜2019-02-21（木曜日）03：27＿［これまでの記述範囲の終了時刻］＜＜＜


