#+TITLE: "「共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！」という日隅一雄弁護士のブログ記事"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-14 18:39:49 +0900
FILE_NAME: 2019-08-14-183949_「共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！」という日隅一雄弁護士のブログ記事.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 海渡雄一弁護士（第二東京弁護士会）  日隅一雄弁護士 共謀罪
記事タイトル名の文字数：61　保存ファイル名の文字数：83

* 「共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！」という日隅一雄弁護士のブログ記事
  :LOGBOOK:
  CLOCK: [2019-08-14 水 18:40]--[2019-08-14 水 19:10] =>  0:30
  :END:

＞＞＞2019-08-14（水曜日）18：40＿［これからの記述範囲の開始時刻］＞＞＞

5690： ２００６年１０月と確認した、ヤメ蚊こと日隅一雄弁護士（故人）に、プライバシーを理由にブログのコメントを削除された件 http://hirono-hideki.hatenablog.com/entry/2019/08/14/173658

　上記の記録済み記事で取り上げた日隅一雄弁護士のブログ記事ですが、私の投稿したコメントを削除した痕跡が残されていて発見に至ったものです。その痕跡の記録は私のはてなのブログに記録されていたものですが、調べることになったきっかけというのも海渡雄一弁護士のツイートでした。

　記録の全体としては再掲の繰り返しになるかもしれませんが、TwitterAPIの読み込みで次に再掲載しておきます。

▶ ツイート％kidkaido（海渡雄一）％2019/06/10 18:48％ https://twitter.com/kidkaido/status/1138020203181137920
&twitter(1138020203181137920){theme:light}
> 日隅一雄情報流通促進賞の表彰式を12日18時15分から、日比谷図書館地下ホールで開催します。
> 大賞は書籍「サカナとヤクザ」を著した鈴木智彦さん、奨励賞は島明美さんと上西充子さん、特別賞は元県民投票の会代表の元山仁士郎さんです。
> い… https://t.co/x2YCyirBre  
▶

　朝に始まった日隅一雄弁護士だったように思いますが、再び夕べの海渡雄一弁護士として記録の作成を行っています。タイムスリップではないですが、２００６年当時の社会状況を確認する機会ともなりました。

```
削除のお知らせ (ヤメ蚊)
2006-10-22 08：13：08
プライバシー保護の観点から、削除したコメントがあることをお知らせします。

［source：］【転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！ - 情報流通促進計画 by ヤメ記者弁護士（ヤメ蚊）日隅一雄 https://blog.goo.ne.jp/tokyodo-2005/e/1cf5f4bedf3b8e43750df82308ca4771
```

```
トラックバックを一つ削除しました (ヤメ蚊)
2006-10-22 18：36：37
削除した理由は、プライバシー保護のためです。一市民について氏名を明らかにして書くべきか否か不明確な内容が掲載されているからです。また、これに先立ち、コメントも削除していますが、それも同様の理由によるものです（名前をクリックすると、同じ問題をはらんだ内容にアクセスすることになる）。

［source：］【転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！ - 情報流通促進計画 by ヤメ記者弁護士（ヤメ蚊）日隅一雄 https://blog.goo.ne.jp/tokyodo-2005/e/1cf5f4bedf3b8e43750df82308ca4771
```

　上記引用の２箇所がコメント欄で、私のコメントやトラックバックを削除した断り書きと思われる部分です。内容的には不明確ですが、私の側のスクリーンショットを含む記録と整合するので、間違いないと思いますが、もっとすっかり記録をしておくべきだったという悔いはあります。

　さきほど一通り記事に目を通したのですが、読みづらく分かりづらい内容でした。正直、集中して読む気持ちになれないところも大きいかと思います。他にやりたいことが一杯あるという焦燥感もあるのですが、あえて取り上げるところにその必要性を高め優先にしてあります。

　「【転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！」という見出しを見ただけでも、扇情的で刺激的なものを感じますが、ざっと読んだところ「騙す」という言葉が記事の本文に見当たらず、ページ内検索をしました。

　「騙」の一文字で検索しましたが、該当したのは４か所で、１つは上記の記事の見出し部分、他の３つは全てトラックバックの一覧にありました。そのトラックバックの一覧部分をそのまま次に引用しておこうと思います。

```
20 トラックバック
共謀罪：24日の法務委員会で強行採決の危険性 (雑木帖)
　衆院補選後の24日の法務委員会で、共謀罪が自民、公明の「数の論理」で強行採決をはかられる公算が高まってきたらしい。
耐震偽装その他 (政治・経済 メモ代わりに・・・)
「嗚呼、負け犬の遠吠え日記」さんのコメント欄からコピペ。（★引用開始★）藤田告発と新聞 http：//k-nanjoh.at.webry.info/200610/article_20.html共謀罪問題から目を離すなhttp：//empire2nd.blog79.fc2.com/blog-entry-6.html『奪われる日本』ついにベストセラ ...
テレブン（ＴＶ・新聞）報道にＮＯ！　ブログにＹＥＳ♪ (らんきーブログ)
藤田社長の昨日の安倍晋三首相官邸突撃ニュースは見られた方も多いかな？ きっこの日記：藤田社長からの続報　 　動画はこちら 果たしてあの藤田社長が持参したペーパーは安倍晋三の手元に届いたのでしょうか？ きっこのブロ
共謀罪の黒塗り文書。 (Tomorrow is Another Happy)
［情報流通促進計画 by ヤメ記者弁護士］より取り急ぎ、転載。 【転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る 海渡弁護士の解説～政府は国民をこうして騙す！ 先日、アラームを発した海渡弁護士の現時点での共謀罪
第138回　「これだけはダメ！怖いもの」　（ＦＣ２今週のＴＢテーマ） (わんばらんす)
共謀罪！！！ ◆これだけはダメ！怖いもの・・・「共謀罪」です。 何が好きだの嫌いだのといっても・・・ 日本が平和で　「自由」　があればこそだと思いませんか？ 共謀罪が成立してしまったら・・・ うかつに人
「核も持てる新憲法」・・新キャッチコピー (風を変えよう！)
= 「核も持てる新憲法」・・新キャッチコピー = === 安倍首相が「現憲法でも可能な集団的自衛権を研究」 === '''といったとき、改憲派の新憲法は「集団的自衛権」を可能にする憲法であるということが分かり、決して「独立国なら自衛の軍隊を持って当 ...
【転載】共謀罪を強行採決してはならない７つの理由（海渡雄一弁護士） (人工樂園)
　コピー元はこちら。「転載熱望」とありますし、わかりやすい解説ですので、以下に全文を掲げさせていただきます： 共謀罪を強行採決してはならない７つの理由 －国連条約批准のために共謀罪導入以外に選択肢はある－ 海渡　雄一（弁護士） はじめに ○ ...
22日の補選と共謀罪【転載歓迎】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！ (踊る新聞屋－。)
　きょう22日の補選二つの結果次第では、24日（火）の強行採決も危惧された共謀罪＜【転載歓迎】共謀罪は１０月２４日に法務委員会で強行採決との観測が急浮上！＞だが
【転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説 (共謀罪ってなんだ？)
以下も、ヤメ蚊さんのブログ「情報流通促進計画 by ヤメ記者弁護士」 からの転載です。 （ここから） --------------------------------------------------------------------------------------------------- 先日、アラームを発した海渡弁護士の ...
自民が勝てば道理が引っ込む～共謀罪成立、権力犯罪やりたい放題の世へ (きまぐれな日々)
先ほどトラックバックいただいた「雑木帖」さんの記事「共謀罪：24日の法務委員会で強行採決の可能性」が、「衆院補選後の24日の法務委員会で、共謀罪が自民、公明の「数の論理」で強行採決をはかられる公算が高まってきたらしい」と伝え
千葉補選、滋賀県知事選、長野県知事選を思い出そう。 (青山はここにありました：：社会批判がてんこ盛り！！)
自民に打ち勝った、千葉補選、滋賀県知事選を思い出そう ２２日は、大阪と神奈川で、衆議院補選が行われる。自民に対する応援演説が、北朝鮮からどんどん届いている。しかし、自民に打ち勝った下記の補選や、知事選を思い起こそう。さらには、今年３月に実施され ...
共謀罪は成立すべきか？ (りゅうちゃん別館)
共謀罪については補選後の２４にも強行採決があるかもしれないと以下の記事で書いた。 共謀罪、２４日に強行採決か？（りゅうちゃんミストラル） その後、共謀罪に関する海渡弁護士の解説があるのでここで転載する。 本当は「りゅうちゃんミストラル」に掲載した ...
日米政府の共謀を隠蔽？黒塗りの公電は雄弁に語る (そぞろ日記)
さて、塗りつぶしたり隠したりするのは、みんなに知られては困ることが書いてあるから
共謀罪強行採決間近？！海渡弁護士の解説と集会案内 (ここにいるということ)
　先日転載しました、海渡弁護士の文ですが、 「情報流通促進計画 by ヤメ記者弁護士」 http：//blog.goo.ne.jp/tokyodo-2005 「【転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！」 http：//blog.goo.ne.j ...
共謀罪法がカウントダウン？ (Vulcanの日記)
きっこの日記を見ていたら、またまた共謀罪法が強行採決されようとしていることを知りました。 自民が補選...
日本は民主主義の国ではない (ACダークサイド)
下北沢在住の友人より知らされたニュースです。 下北沢を高層ビルの街にする「地区計画」が、一昨日都市計画審議会を通過してしまったとのこと。 計画を通過させるかどうかは最終的には合計20名の委員達の投票によって決定する。 下北沢の住民の間では、 ...
またぞろ共謀罪 (謙遜と謙譲の音楽)
飽きたというより呆れました。左右問わず共謀罪法案には反対。つまり権力者の言う「国民の皆様」のほとんどが反対。もう反対に決ってるのに、なぜ懲りずに何度も地獄から甦ってくるのか謎。逆に考えると、誰が共謀罪を歓迎しているのだろう。死刑存置を主張する人 ...
危険！「共謀罪」採決間近！ (小さな山で、一匹の羊が迷っています.....)
前の国会で、なんとか流れた共謀罪。 今回の臨時国会で採択の動きが出ているようです
犯罪収益流通防止法・依頼者密告制度・ゲートキーパー制度（１）　弁護士の守秘義務は崩されていく (国家破綻研究ブログ)
皆様ご存知と思いますが、弁護士（その他の法律専門職も）には、守秘義務が課せられています。それによって、憲法に定める「公正な裁判を受ける権利」や、その他の被告人（被疑者）の権利が担保されている一面があるのです。 さて、そのような弁護士が、依頼者 ...
皆さまの暖かいご支援、感謝いたします。 (青山はここにありました：：社会批判がてんこ盛り！！)
W補選、連敗でがっくりと来た老体に風邪が襲いかかり・・・・ ということで、全然アクセスしていなかったら、今日はもう水曜日になる直前でした。しばらくアクセスしない間に、スパムTBやらスパムコメントが山ほどたまってしまいました。 これらのスパムを削除し ...

［source：］【転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！ - 情報流通促進計画 by ヤメ記者弁護士（ヤメ蚊）日隅一雄 https://blog.goo.ne.jp/tokyodo-2005/e/1cf5f4bedf3b8e43750df82308ca4771
```

　再びページ内検索で該当箇所を確認していくと、トラックバックの一覧にあるのは全てが、トラックバックを送信したと思われる記事に引用された見出しの部分のようでした。

　最近はここまで根拠を示さず、政府や公権力が「国民を騙す」などとネットで書いている人は見かけないですが、２００６年当時は、息を吐くように行われていたようです。息を吐くで思い出すのは最近の三浦義隆弁護士のツイートですが、それも警察が嘘をつくというものでした。

　日隅一雄弁護士は、海渡雄一弁護士の記事の引用部分にも注釈を入れているようですが、全体的に海渡雄一弁護士が書いた記事なのか、それとも日隅一雄弁護士の主観なのか混沌としてわかりづらい印象も受けました。原文にあたるのが確実とは思いますが、そこまで時間を使う気にもなりません。

＜＜＜2019-08-14（水曜日）19：10＿［これまでの記述範囲の終了時刻］＜＜＜

