#+TITLE: "平成5年9月7日控訴審判決直後の革手錠、保護房収容"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-06-24 10:14:32 +0900
FILE_NAME: 2019-06-24-101432_平成5年9月7日控訴審判決直後の革手錠、保護房収容.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: a66  木梨松嗣弁護士 名古屋高裁金沢支部 小島裕史裁判長 金沢刑務所の拘置所 北口雅章弁護士
記事タイトル名の文字数：25　保存ファイル名の文字数：47

* 平成5年9月7日控訴審判決直後の革手錠、保護房収容

** Windows10のAtomエディタでの作業

＞＞＞　2019-06-24(月曜日)10:31:51　＞＞＞

　まだ不慣れですが、パソコンはWindows10のAtomエディタでの作業となります。別に一太郎2019の体験版を使っていますが、本日で「試用期間はあと19日です。」というメッセージが出ています。確かその前日にATOKの体験版をインストールしていました。体験版は30日間ではなかったかと思います。

　もともとLinuxの日本語変換に不満があってATOKの購入を検討したのですが、ATOKが同梱される一太郎2019のアウトライン機能も試してみたいと思い一太郎の体験版をインストールしました。

　ここ2，3年Windowsパソコンはまともに使ったことがなかったので、それもよくない慣れておこうという考えもありました。

　Windows10にはWSLというLinux環境も整えUbuntuを使えるようにしていますが、いくつか使いづらさや不便を感じています。どうにも改善が期待できなかったので、数年ぶりにAtomエディタをメインに使うことにしました。AtomエディタはネイティブのUbuntuでも使っていますし、使い心地に違いは感じません。

　Windows10での作業は、ATOKを使った日本語入力がメインになります。Ubuntuの日本語変換mozcでも短文の入力であれば不満はないのですが、長い文節の区切りや文脈での日本語変換となると思うようにならず、けっこうストレスを感じてきました。

＜＜＜　2019-06-24(月曜日)10:55:50　＜＜＜

** 「名古屋刑務所受刑者放水死事件」と「名古屋刑務所受刑者暴行死傷事件」

＞＞＞　2019-06-24(月曜日)11:54:32　＞＞＞

　次の2つのページを参考にしています。

［link：］ 名古屋刑務所受刑者放水死事件 - Enpedia https://enpedia.rxy.jp/wiki/%E5%90%8D%E5%8F%A4%E5%B1%8B%E5%88%91%E5%8B%99%E6%89%80%E5%8F%97%E5%88%91%E8%80%85%E6%94%BE%E6%B0%B4%E6%AD%BB%E4%BA%8B%E4%BB%B6

［link：］ 名古屋刑務所受刑者暴行死傷事件 - Enpedia https://enpedia.rxy.jp/wiki/%E5%90%8D%E5%8F%A4%E5%B1%8B%E5%88%91%E5%8B%99%E6%89%80%E5%8F%97%E5%88%91%E8%80%85%E6%9A%B4%E8%A1%8C%E6%AD%BB%E5%82%B7%E4%BA%8B%E4%BB%B6

　詳細は省きますが、同じ名古屋刑務所での別々の受刑者死亡事件だったようです。私はこれまで混同して理解していたらしいと気がついたところなのですが、一つは保護房での放水が死因、一つは革手錠の使用が問題になっていたという理解はありました。革手錠の件は国会のテレビニュースが記憶にあります。

　自分自身の体験に基づく理解でもあったのですが、保護房で革手錠の使用を行った後の放水だと考え、経過や態様に違いはあるものの同一の被害者に対する同じ事件という認識で来たように思います。

　あとでLinuxのUbuntuのパソコン環境に戻ってから記述をする予定でいたのですが、きっかけは昨日、2019年6月23日の朝のことで、確か中村元弥弁護士のTwitterタイムラインでリツイートされていた霞史郎のツイートの内容に、北口雅章弁護士のブログ記事の紹介がありました。

　北口雅章弁護士については、以前注目した名古屋の弁護士の一人で、情報に接したのも久しぶりだったのですが、改めて少し調べたところ、たしかTwitterの検索だったと思いますが、名古屋刑務所の事件のことが出てきたのです。

　入念な確認作業までは行わなかったのですが、Twilogで確認したところ、私が最初に北口雅章弁護士について書いたツイートというのは、思っていたより最近のものでした。関心を持ったきっかけは、伊藤詩織さんの準強姦事件と岡口基一裁判官の分限裁判の2件だけだったようです。

　なお、昨日、再び北口雅章弁護士に注目したのは、医療裁判やその弁護士報酬でした。そういえばと思ったのですが、以前よりブログには医療裁判を専門にする旨の紹介文があったように思いました。

　Enpediaというサイトですが、Wikipediaに似たものとして、これまでにも見かけてきたように思います。Wikipediaとの違いについては、調べてもいないのでわかりませんが、内容もかなり似ていると思います。

　ここで求償権について新たな知見を得ることができました。国家賠償における求償権としてかなり参考になる情報です。ただ、被害者に関する情報はほとんど見当たらないので、具体性が感じられず、刑事裁判の結果を踏まえた手続き以上の参考例は見出しがたいとも思います。

```
概要［編集］
2001年12月14日午後2時頃、愛知県西加茂郡三好町にある名古屋刑務所の保護房で、男性受刑者が死亡する事件が発生。その後の捜査で、当時の副看守長Bが男性受刑者の肛門に消防用ホースで放水したために、肛門や直腸に傷を負わせて死亡させたとして、Bが逮捕された。元副看守長A、元看守部長Cも、受刑者のズボンを下ろすなどしたとして逮捕された。その後、副看守長Bは特別公務員暴行陵虐致死罪、看守部長は特別公務員暴行陵虐致死ほう助罪で起訴された。副看守長Aも、ズボンを下ろすなどして放水をしやすくするように手助けをしたとして起訴されている。

［source：］名古屋刑務所受刑者放水死事件 - Enpedia https://enpedia.rxy.jp/wiki/%E5%90%8D%E5%8F%A4%E5%B1%8B%E5%88%91%E5%8B%99%E6%89%80%E5%8F%97%E5%88%91%E8%80%85%E6%94%BE%E6%B0%B4%E6%AD%BB%E4%BA%8B%E4%BB%B6
```

```
概要［編集］
2002年11月8日、名古屋地検特捜部は、本事件に関わったとされる名古屋刑務所の副看守長M被告等の刑務官5人が特別公務員暴行陵虐致死傷の疑いで逮捕される。

副看守長Mと看守Oは2002年5月27日に名古屋刑務所において、懲らしめ目的で男性受刑者の腹部を革手錠で強く締め付け、外傷性腸間膜裂傷で死亡させたとされた。また2002年9月25日には、5人の刑務官副看守長M、看守O、看守S、看守長W、看守Iが、副看守長Aと共謀して全治70日の外傷性腸管膜損傷などの重傷を負わせた。この2件の容疑により、検察は、特別公務員暴行陵虐致死傷及びほう助罪で刑務官らを起訴した。

［source：］名古屋刑務所受刑者暴行死傷事件 - Enpedia https://enpedia.rxy.jp/wiki/%E5%90%8D%E5%8F%A4%E5%B1%8B%E5%88%91%E5%8B%99%E6%89%80%E5%8F%97%E5%88%91%E8%80%85%E6%9A%B4%E8%A1%8C%E6%AD%BB%E5%82%B7%E4%BA%8B%E4%BB%B6
```

　上記にそれぞれ「概要」部分を引用しました。事件の発生がそれぞれ2001年12月と2002年11月となっています。起訴や初公判の日時がちょっと見当たりませんが、放水死事件の名古屋地裁判決が2005年11月4日となっています。あまりテレビを見ない時期だったので、記憶にあるのもニュース報道ぐらいです。

　大相撲の相撲部屋の虐待死事件があったのも同じ頃のように思いますが、事故として処理されるところを鑑定医の告発で事件化したような話を見ています。その鑑定医ですが、確か岩手大学の関係者で、半月ほど前に気になる情報を一つ見かけています。そちらも忘れかけた問題でした。

　過去の記録の検索作業などは、LinuxのUbuntuのパソコン環境で行いたいと思います。Windows10のパソコン環境には不慣れもありますが、作業効率の悪さが大きいです。

　名古屋刑務所の特別公務員暴行陵虐致死事件が再審請求されたことも知ってはいましたが、強く関心を持つことはなく内容を調べることはありませんでした。判決に強い不満を持って刑事手続を続けたことは、郵便不正事件における大阪地検特捜部の元部長らの対応に似たものは感じていました。

　その郵便不正事件に関連した大阪地検特捜部の不祥事については、1年以上前から強い疑念を持つようになり、けっこう調べたこともあったのですが、情報量も多過ぎで納得の理解や整理されたまとめには至っておりません。無罪という結果だけが一人歩きし、一点に絞って利用されている感も否めません。

　なお、「2014年3月27日、名古屋高裁（石山容示裁判長）は再審支給を棄却。」と記載のある石山容示裁判官は、私の再審請求を棄却した裁判長でもありました。当時、調べたところ、被告発人小島裕史裁判長の部下であったような経歴が散見され、共通した著名な刑事裁判が戸塚ヨットースクール事件でした。

＜＜＜　2019-06-24(月曜日)13:04:05　＜＜＜
