#+TITLE: "参考資料／刑事裁判／控訴審／深澤諭史弁護士の「「所詮は地裁だし」は正しいの？控訴審のルールって？」から落合洋司弁護士の「どこにも持って行き場のない検事が集まった廃棄物中間処理場」"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-03-04 06:39:51 +0900
FILE_NAME: 2019-03-04-063951_深澤諭史弁護士の「「所詮は地裁だし」は正しいの？控訴審のルールって？」から落合洋司弁護士の「どこにも持って行き場のない検事が集まった廃棄物中間処理場」.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  落合洋司弁護士（東京弁護士会） 深澤諭史弁護士 控訴審 高検 検察庁
記事タイトル名の文字数：89　保存ファイル名の文字数：97

#contents

* 「「所詮は地裁だし」は正しいの？控訴審のルールって？ - 弁護士 深澤諭史のブログ」という深澤諭史弁護士のブログ記事について
  :LOGBOOK:
  CLOCK: [2019-03-04 月 06:54]--[2019-03-04 月 09:59] =>  3:05
  :END:

＞＞＞2019-03-04（月曜日）06：54＿［これからの記述範囲の開始時刻］＞＞＞

[link:] 2019年03月03日14時57分の登録： ＼深澤諭史　@fukazawas＼「所詮は地裁だし」は正しいの？控訴審のルールって？ - 弁護士 深澤諭史のブログ http://hirono2014sk.blogspot.com/2019/03/fukazawas_85.html

　スクリーンショットの記録をしていると思っていたのですが、見当たらなかったので新規に作成し、非常上告-最高検察庁御中_ツイッター（@s_hirono）に投稿しました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-03-04 07:15／2019-03-04 07:08 URL： https://twitter.com/kk_hirono/status/1102331801874255872 https://twitter.com/s_hirono/status/1102329951129223169
&twitter(1102331801874255872){theme:light}
> 2019-03-04-065953_「所詮は地裁だし」は正しいの？控訴審のルールって？　：　弁護士　深澤諭史のブログ.jpg https://t.co/oORk53n0ns
◁◁◁
<hr />

　脈絡を含め正確にお伝えする必要があるので、次に深澤諭史弁護士の当該ブログ記事の内容を全文引用します。

```
2019年03月03日

「所詮は地裁だし」は正しいの？控訴審のルールって？
よくネットで耳にする話
よくネットで、地方裁判所の判決について、自分の感情に合致しないからといって「所詮は地裁だし」という言動がままみられます。
これは、要するに、地方裁判所は、高等裁判所、そして最高裁判所より「下」の裁判所であり、しかも、通常は第一審の裁判所（簡易裁判所も家庭裁判所もありますが）から、二軍みたいなイメージが持たれているようです。

これは裁判所に限ったことではなく、弁護士も、特定の人たちにとって都合が悪い仕事をしていると、「そんな仕事はダメな・売れない弁護士しかやらない」みたいな言動がありますが、それと同種であるといえるかもしれません（自分に都合の悪いことをする連中や劣悪な連中だと思い込みたいというのは、自然な心理です。）。

地裁は質が低いのか？
さて、こういう議論は正しいのでしょうか？
賢明な読者諸氏にはお答えするまでもないですが、もちろん間違っています。

もちろん、ここの裁判官の資質の問題もありますので、絶対に正しい・間違っているという趣旨ではないですが、基本的に地裁だから能力が劣っているとか、そういうことはありません。

地方裁判所の重要性
確かに、高等裁判所には、地方裁判所より経験豊富な裁判官が配置されます。ですが、一方で、地方裁判所の裁判長にも、経験豊富な裁判官が配置されます。
地方裁判所が未熟な裁判官で溢れているかといえば、決してそういうことはありません。また、職制上、一人で通常訴訟を担当するには、原則として１０年、例外でも５年のキャリアが要求されます（なお、この原則と例外は運用上逆転していて５年が原則です。）。

また、実質的に考えても、地方裁判所は、（簡易裁判所が第一審でない限りは）一番最初に証拠に触れる仕事です。
イメージするとわかりやすいと思いますが、最初に当事者が供述する裁判所でもあります。高等裁判所は、それを書き取った調書を読むだけですが、地方裁判所は、生身の人間に触れます。高等裁判所でも供述をさせることはありますが、それは多くの場合「2回目」あるいは「やり直し」にすぎません。
ですから、重要な裁判所ですし、「二軍裁判所」なんてとんでもない話です。裁判所も、その前提で人材を配置しているはずです。

そういうわけで、個別の裁判官の資質を別にすれば、類型的に地方裁判所の質が低いという議論は誤りだと思います。

控訴のルール
さて、それでも、地方裁判所の判決に納得がいかない、誤りがあるという場合は、控訴という手続きで、高等裁判所で争うということになります。
この場合、地方裁判所での審理との関係はどうなるのでしょうか？
スポーツの再試合みたいに、やり直しになるのでしょうか？
実は、この関係には、3種類ほどの考え方があります。①覆審制、②続審制、③事後審制、というものです。

①覆審制とは、裁判を1からやり直すというものです。控訴というと、みなさんこういうイメージがあるでしょうが、現行法の通常訴訟では、こういう考えは採用されていません。
第一審が軽視される、無駄になる、生身の人間の初回の供述を無視することになるからです。２回目ですと、反対尋問を予想していろいろ対策も可能になるからです。
無駄が多いし、不合理でもあるからです。
スポーツでいえば、再試合でしょう。
②続審制とは、これまでの証拠や主張を引き継いで、さらに、新しい証拠があればそれを採用して、さらに審理を続行し、改めて判決するという仕組みです。
これは、民事訴訟において採用されている考えです。なお、実際には、裁判所の裁量で、あまり証拠採用しないケースもあります。
「自分だったらどう判決するか」という考えに結びつきやすく、さらに新しい主張立証もあるので、③よりはひっくり返りやすい仕組みであるともいえます。
スポーツでいえば、延長試合と例えられると思います。
③事後審制とは、これまでの証拠や主張を引き継ぎますが、審理の対象は事件というより、原審の判決である、という形式です。
新しい証拠提出は原則としてできません。第一審の結果をみて、その判決が合理的かどうか、ということで判断します。
これは、刑事訴訟において採用されている考えです。
ですから、一般的に刑事訴訟においては、控訴審でひっくり返る可能性は高くはないといわれています。同じ証拠関係が維持されるからです。
もっとも、実際には、特に検察官が控訴した場合、大量に証拠採用されるなどして、事実上の続審になっている、などと批判されています。
スポーツでいえば、試合終了後に写真判定をするとか、そういう形式であるといえます。

まとめ
地方裁判所は二軍裁判所ではない。むしろ重要だし、それにふさわしい人材配置が望まれ、現にされている。
控訴のルールは、民事事件では延長戦、刑事事件では、事後判定というのが原則の考え方
「法律」カテゴリの最新記事
大量懲戒請求事件にみる誤導・法律デマのまとめ（追加）
勤務先が倒産した方々へ、そして経営している会社が倒産した方々へ
東京司法書士会で司法書士の本人確認義務について講演をしてきました
勤務弁護士の労働者性
「問題が起きた！じゃあ、インターネットで『拡散希望』だ！」というリスク

［source：］「所詮は地裁だし」は正しいの？控訴審のルールって？ ： 弁護士 深澤諭史のブログ http://xn--zqs94lv37b.club/archives/15617144.html
```

　上記のデータベースへの登録が「2019年03月03日14時57分の登録：」となっているので、そこまで言って委員会NPの放送終了前に、上記の深澤諭史弁護士のブログ記事を読んでいた可能性がありそうです。てっきり放送終了後のことと思っていました。

　メモ代わりに奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)にツイートをしているとも思ったのですが、確認すると見当たりませんでした。そこまで言って委員会NPの終了近くはテレビに集中していたので、放送後に深澤諭史弁護士の記事を読んだ可能性はあります。

　細かいことにこだわるようですが、私にしてみれば歴史的な内容を含む深澤諭史弁護士のブログ記事であり、そのあとの大きな発見につながりました。落合洋司弁護士（東京弁護士会）の過去のブログ記事のことです、そちらは16時半ころにスクリーンショットの記録を確認しました。

　深澤諭史弁護士のブログ記事は、深澤諭史弁護士のタイムラインで本人のツイートとして発見しました。

▶ ツイート％fukazawas（深澤諭史）％2019/03/03 12:07％ https://twitter.com/fukazawas/status/1102042885262761984
&twitter(1102042885262761984){theme:light}
> なんか控訴審が話題なようなので（・∀・） https://t.co/xvVdX7YX7X  
▶

　控訴審が話題とありますが、それらしいツイートというのは見かけませんでした。もう一度、深澤諭史弁護士のタイムラインを確認しましたが、3月3日12時07分の上記の深澤諭史弁護士のツイートの前に、それらしい控訴審を含むツイートは見当たりません。

　ただ、その確認作業で気になるツイートの発見がありました。2件のツイートとリツイートは見ていたのですが、リツイートに引用されたツイートの内容に気がついたのです。リツイートのツイートの投稿時刻をみると昨日の10時32分となっていました。

　午後に見たそこまで言って委員会NPのパネラー弁護士の発言によく似ているのですが、番組では寿司となっていたものが、深澤諭史弁護士のタイムラインではカレーとなっています。これはまた別の項目として取り上げておきます。

　昨日のことなので、控訴審をキーワードにTwitter検索をやってみました。これから検索結果を確認し、それらしいものや弁護士らしいものがあれば、このあと掲載します。

［link：］ 控訴審に関するTwitterニュース https://twitter.com/search?q=%E6%8E%A7%E8%A8%B4%E5%AF%A9&src=typd

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Sankei_news（産経ニュース） 日時：2019-03-04 07:48／2019-03-01 17:20 URL： https://twitter.com/kk_hirono/status/1102340106348724224 https://twitter.com/Sankei_news/status/1101396852216217600
&twitter(1102340106348724224){theme:light}
> 連続青酸死事件　筧被告側、控訴審でも無罪主張 \n  https://t.co/YmGF7J0OKf \n   \n  　→筧被告は出廷せず。弁護側は「（筧被告は）１審の被告人質問で直前の質問も覚えていなかった」と訴訟能力がないことを訴えた。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜NewsPicks（NewsPicks） 日時：2019-03-04 07:51／2019-03-02 21:57 URL： https://twitter.com/kk_hirono/status/1102340638287192064 https://twitter.com/NewsPicks/status/1101828869408153600
&twitter(1102340638287192064){theme:light}
> ＪＴ、カナダで１４８０億円賠償命令…控訴審も敗訴（読売新聞） \n  https://t.co/h04P4ttfLe
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜6d745（ろくでなし子 祝デコまん無罪確定！） 日時：2019-03-04 07:51／2019-03-03 20:01 URL： https://twitter.com/kk_hirono/status/1102340731841077248 https://twitter.com/6d745/status/1102161981132271616
&twitter(1102340731841077248){theme:light}
> 【定期】よく聞かれますが、わたしのアート裁判は高等裁判所の控訴審で「デコまん」はめでたく無罪確定しました！現在は有罪部分について最高裁に上告中です。引き続きよろしくお願いいたしますhttps://t.co/UuVtK3wBqF
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hKodama（HRK） 日時：2019-03-04 07:52／2019-03-02 02:18 URL： https://twitter.com/kk_hirono/status/1102340928272924672 https://twitter.com/hKodama/status/1101532079848710150
&twitter(1102340928272924672){theme:light}
> 僕の中では、京都の谷山先生こそ本物の「若手弁護士」。なにしろ、検察官と裁判所が公に認定した若手。検察官に悪口を言われまくり。しかも控訴審の大阪高裁によれば、これは取調べとして社会通念上相当な範囲内のセリフらしい。つらいけど、若いと… https://t.co/S4w22MrbHW
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hKodama（HRK） 日時：2019-03-04 07:52／2019-02-28 14:30 URL： https://twitter.com/kk_hirono/status/1102341021055123456 https://twitter.com/hKodama/status/1100991690595131392
&twitter(1102341021055123456){theme:light}
> 高裁が、一審の量刑が重すぎると思っている様子ながら一項破棄もしにくそうに思われる事案で、「書ける二項破棄の理由」作りとして控訴審での贖罪寄付をしたことが
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-03-04 07:53／2019-02-27 18:47 URL： https://twitter.com/kk_hirono/status/1102341172578508800 https://twitter.com/hirono_hideki/status/1100693907686416384
&twitter(1102341172578508800){theme:light}
> 控訴審判決は一審を覆し、県警の保護義務違反を認め、県と津谷さんを刺殺した男に計１億６千万円余の賠償を命じていた。県は２７日に上告の手続きをとる。 https://t.co/B33QmHjRaQ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜pinpinkiri（小川一） 日時：2019-03-04 07:53／2019-02-27 09:45 URL： https://twitter.com/kk_hirono/status/1102341285203992577 https://twitter.com/pinpinkiri/status/1100557434974654465
&twitter(1102341285203992577){theme:light}
> 南洋戦・フィリピン戦の被害者たちによる国賠訴訟。３月７日、福岡高裁那覇支部で控訴審の判決が下されます。戦後補償を求める集団訴訟は今回が最後とみられます。戦後未補償問題を取材をしてきた記者の目です。  https://t.co/VVuytG4YQz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜keiben_oasis（刑事弁護オアシス） 日時：2019-03-04 07:53／2019-02-25 19:18 URL： https://twitter.com/kk_hirono/status/1102341373263470592 https://twitter.com/keiben_oasis/status/1099976997235712005
&twitter(1102341373263470592){theme:light}
> 記事を3件追加いたしました。 \n  ・ブックレビュー『刑事手続におけるプライバ シー保護――熟議による適正手続の実現 を目指して』 \n  ・不作為による死体遺棄の継続を認めて公訴時効の完成を否定した事例 \n  ・控訴審における事実誤認の審査方法 \n  よ… https://t.co/vu4s1tDcWH
◁◁◁
<hr />

　上記は告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でログインした状態でリツイートしたものです。同アカウントでブロックされているアカウントのツイートは表示されません。

　次のカナダでの日本たばこ産業の控訴審敗訴のニュースが気になりましたが、検索結果のタイムラインに主要メディアのツイートは見当たりませんでした。次のニュース記事は読売新聞が配信元のようです。もちろんテレビでもニュースは見ていません。

```
日本たばこ産業（ＪＴ）は２日、喫煙が健康に与える影響の説明が不十分だったとして、カナダの子会社が、同国ケベック州の住民らに起こされていた訴訟の控訴審で、同州控訴裁判所から約１７・７億カナダ・ドル（約１４８０億円）の損害賠償の支払いを命じられたと発表した。

　ＪＴは「判決内容を精査し、上告も含めてあらゆる手段を検討していく」としている。

［source：］カナダでJTに約1480億円の支払い命令 喫煙による影響の説明が不十分 - ライブドアニュース http://news.livedoor.com/article/detail/16100944/
```

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜niigata_nippo（新潟日報モア） 日時：2019-03-04 08:02／2019-03-02 10:12 URL： https://twitter.com/kk_hirono/status/1102343546730758145 https://twitter.com/niigata_nippo/status/1101651375539277825
&twitter(1102343546730758145){theme:light}
> [新潟日報モア] 付審判無罪の県警警部補　控訴審でも無罪　東京高裁 https://t.co/ml9D30Ppf8
◁◁◁
<hr />

　ブロックはされていなかったですが、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でログインしたブラウザの検索結果には見当たらなかったツイートです。付審判自体ずいぶん久しぶりに目にしました。


```
千葉県内で捜査対象の男性（５４）にけがを負わせたとして特別公務員暴行陵虐致傷罪で付審判となり、千葉地裁で無罪判決を受けた新潟県警警部補の...

【社会】 2019/03/02 10：00
このページは「モア会員」のみご覧いただけます

［source：］付審判無罪の県警警部補　控訴審でも無罪　東京高裁｜社会｜新潟県内のニュース｜新潟日報モア https://www.niigata-nippo.co.jp/news/national/20190302454517.html
```

　これは前に少しだけ見かけたニュースだったと思います。同じ頃、公然わいせつで刑事裁判となった警察官が佐藤大和弁護士の弁護で無罪になったという小さなニュースがありました。それも千葉県内だったと思います。控訴審での逆転無罪かもしれません。確認します。

［link：］ 逆転無罪　千葉県警巡査のチャック閉め忘れ事件　警察取調べ国家賠償訴訟へ | 全国情報-JC-NET（ジェイシーネット） http://n-seikei.jp/2018/08/post-53821.html

　上記の記事は2018年8月31日のもののようです。記事の見出しに「国家賠償訴訟へ」とありますが、記事の本文には「国家賠償訴訟を起こすことも検討しているという。」とあります。

　思い出したのですが、今日の3月4日は、岡口基一裁判官が国会の訴追委の呼び出しを受けた日だったと思います。正式名称はちょっと忘れましたが、弾劾裁判にかけるかどうかを審理する国会議員の集まりだそうです。

　これもちょっと調べて、正確なことを記載しておきましょう。

```
ツイッターへの投稿内容をめぐって最高裁から戒告処分を受けた東京高裁の岡口基一判事（５２）に対し、国会の裁判官訴追委員会（委員長・田村憲久衆院議員）が、事情聴取のために３月４日に出頭するよう要請したことがわかった。

［source：］ツイッター投稿の裁判官に出頭要請　国会の訴追委：朝日新聞デジタル https://www.asahi.com/articles/ASM2H5WGRM2HUTIL040.html
```

　よく見覚えのある記事ですが、2019年2月16日07時00分という配信時刻です。今のところ意外に反応は少なかったという感じですが、弾劾裁判で罷免となれば、裁判官としての退職金は不支給、間を置いて手続きを経なければ弁護士にもなれないという情報を見かけました。

　ただ、匿名裁判官と思われるブログの記事では、過去に国会の訴追委が弾劾裁判にしなかった事例も2件紹介していました。けっこう悪質そうな内容だったので、どうかとは思いましたが、それ以上調べることはなかったです。

　もう一つ、土曜日にジャーナリストの江川紹子氏のツイートとして知ったもので、柳原病院事件の検察控訴ですが、記事の見出しが「控訴へ」となっていて、控訴の方針などと書いてありました。上訴の申し立て期限も迫っているはずなので、正式なニュースが今日あたり出そうな感じです。

　「控訴」でTwitter検索していても、その柳原病院事件のことが出てきませんでした。筧被告の控訴審は、金曜日のミヤネ屋で見て知りましたが、出廷のするしないでごたごたがあったあと、弁護人の主張は全て排斥され即日結審をしたようです。

　控訴審の即日結審のことはあとでネットのニュースで見ましたが、それも「控訴審」のTwitter検索では、わずかにしか出ていないです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ariolajapan（アリオラジャパン） 日時：2019-03-04 08:35／2019-02-22 00:00 URL： https://twitter.com/kk_hirono/status/1102351885539786753 https://twitter.com/ariolajapan/status/1098598216864419841
&twitter(1102351885539786753){theme:light}
> 日本テレビ系土曜ドラマ「イノセンス 冤罪弁護士」主題歌 \n   \n  King Gnu 「 白日 」　配信中 \n   \n  #KingGnu \n  #イノセンス \n  #白日 \n  #坂口健太郎
◁◁◁
<hr />

　日本テレビ系土曜ドラマ「イノセンス 冤罪弁護士」、というテレビドラマですが、まだ1度もまともに放送をみていません。少し見たのも最初か、初めの頃の1回だけだったような気がします。上記の主題歌も耳にした覚えがまったくありませんでした。

　ちょっとおかしいと思って、よく見るとツイートの下の方に小さな文字で「プロモーション」とありました。控訴審のワードは見当たりません。Twitterの検索で面倒なのは、アカウントのプロフィールの名前にワードが含まれていても懸隔結果に出てくることです。

　時刻は9時25分です。ついさっきまでしばらくうとうとと寝ていたかもしれません。なにか被告発人多田敏明が出てくる夢をみていましたが、思い出せません。中止にしようかと思ったところ、ようやく1件、ブロックされたアカウントのツイートが出てきました。

▶ ツイート％GUv4i6（北白川）％2019/03/02 10:10％ https://twitter.com/GUv4i6/status/1101651054536474624
&twitter(1101651054536474624){theme:light}
> せん妄の件，検察官控訴するのか。
> 控訴審で専門家証人追加してくるんだろうな。
> 
> 被告人を何度危険にさらすのか。  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-03-04 09:29／2019-03-04 09:28 URL： https://twitter.com/kk_hirono/status/1102365406138793984 https://twitter.com/s_hirono/status/1102365198495543296
&twitter(1102365406138793984){theme:light}
> 2019-03-04-092529_北白川@GUv4i6ブロックされています@GUv4i6さんのフォローやツイートの表示はできません。詳細はこちら.jpg https://t.co/C3v67qUKfq
◁◁◁
<hr />

```
外科医師の無罪を勝ち取り、権力の横暴により医療現場へ萎縮を持ちこませないためにも、みなさんのご支援をよろしくお願いします。

2月20日、東京地裁にて無罪判決が出されました！皆様のご支援・ご協力の賜物であり、心より感謝申し上げます。3月6日が控訴期限となっております。引き続き控訴させず、無罪を勝ち取るためにご支援をお願い致します。ブログをご覧ください。

［source：］外科医師を守る会 – 無罪を確定させるためにご支援を…ブログとメッセージをご覧ください（2019.3.1更新） https://gekaimamoru.org/
```

　ジャーナリストの江川紹子氏のツイートのリプ欄の末尾に気になる内容のツイートがあって、Twitterの検索窓に「伊藤詩織」と入れようと思ったのですが、履歴に「わいせつ　控訴」と出てきたので、クリックしたところ上記の記事が見つかりました。

　気になっていた柳原病院事件の控訴ですが、3月6日が控訴期限で、現在のところ検察の控訴申し立ては行われていないようです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kikumaro5（畠山木久麿） 日時：2019-03-04 09:51／2019-03-04 04:21 URL： https://twitter.com/kk_hirono/status/1102371026011226112 https://twitter.com/kikumaro5/status/1102287969753292801
&twitter(1102371026011226112){theme:light}
> @amneris84 月刊HANADAを読んでびっくり！ 週刊誌の記事で彼女が言ってたことを裁判では全く言って無い。外国のテレビ出て被害者だと騒いでいたのに。検察審査会も不起訴にする分けだ。伊藤詩織さんて不思議なんだが知人や同級生… https://t.co/vErUQUTdHi
◁◁◁
<hr />

　ここ数日、控訴のことが気になっているのですが、検察審査会のことはすっかり忘れていました。陸山会事件のときにはずいぶんと話題になった検察審査会というワードで、ある種の現象のようでしたが、伊藤詩織の問題も似たような世相の空気感がありました。

　告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントのログイン状態で「伊藤詩織」とTwitter検索すると気になる情報が出てきたので、深澤諭史弁護士のブログ記事のことはいったん切り上げたいと思います。

＜＜＜2019-03-04（月曜日）09：58＿［これまでの記述範囲の終了時刻］＜＜＜


