#+TITLE: "参考資料／社会／カルロス・ゴーン氏／カルロス・ゴーン被告まもなく保釈、郷原信郎弁護士の反応。国策捜査など検察批判を繰り返してきた、広島地検特別捜査部部長、長崎地検次席にまでなった元検事"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-03-06 15:25:35 +0900
FILE_NAME: 2019-03-06-152535_カルロス・ゴーン被告まもなく保釈、郷原信郎弁護士の反応。国策捜査など検察批判を繰り返してきた、広島地検特別捜査部部長、長崎地検次席にまでなった元検事.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  郷原信郎弁護士 カルロス・ゴーン氏 国策捜査
記事タイトル名の文字数：92　保存ファイル名の文字数：96

#contents

* カルロス・ゴーン氏の保釈決定後、しばらく更新が止まっていた郷原信郎弁護士のTwitterアカウント
  :LOGBOOK:
  CLOCK: [2019-03-06 水 15:50]--[2019-03-06 水 16:41] =>  0:51
  :END:

＞＞＞2019-03-06（水曜日）15：50＿［これからの記述範囲の開始時刻］＞＞＞

　いくつか記録を作成していますので、まずはそちらからご紹介をしたいと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-03-06 15:53／2019-03-06 15:08 URL： https://twitter.com/kk_hirono/status/1103186820970405888 https://twitter.com/s_hirono/status/1103175579497459712
&twitter(1103186820970405888){theme:light}
> 2019-03-06-150719_郷原信郎（@nobuogohara）：　高井氏の理屈によれば、会社の内部では、常に「犯罪」に当たる行為がないか目を光らせ、検察と結託できるかどうかで会社.jpg https://t.co/qtYH6iaF02
◁◁◁
<hr />

[link:] 2019年03月06日15時05分の登録： ＼郷原信郎　@nobuogohara＼この後、 12:00からのAbemaTV「けやきヒルズ」に出演します。ゴーン氏保釈許可がテーマです。⇒ http://hirono2014sk.blogspot.com/2019/03/nobuogohara-1200abematv.html

[link:] 2019年03月06日15時06分の登録： ＼郷原信郎　@nobuogohara＼高井氏の理屈によれば、会社の内部では、常に「犯罪」に当たる行為がないか目を光らせ、検察と結託できるかどうかで会社の支配権が左右される http://hirono2014sk.blogspot.com/2019/03/nobuogohara_89.html

　次が郷原信郎弁護士のタイムラインで更新前のツイートになります。直前のものは郷原信郎弁護士のリツイート、その１つ前が郷原信郎弁護士本人のツイートです。

▷ リツイート→nobuogohara（郷原信郎）＞Lawcojp（岡村久道）｜2019/03/03 05:48／2019/03/02 18:53｜https://twitter.com/nobuogohara/status/1101947379299708929 ／ https://twitter.com/Lawcojp/status/1101782650920951808
&twitter(1101947379299708929){theme:light}
> RT @Lawcojp: 郷原さんが指摘するとおり、検察内部の事情で一方的に延期したのなら、公判で十分な説明責任を果たした上、関係者に謝罪して当然ではないか？
> 「求刑延期問題」と“検察官の職責”（郷原信郎）- Yahoo!ニュース https://t.co/E40GJt48Zj…  

▶ ツイート％nobuogohara（郷原信郎）％2019/03/02 17:27％ https://twitter.com/nobuogohara/status/1101761029283840000
&twitter(1101761029283840000){theme:light}
> 【「求刑延期問題」と“検察官の職責”】と題する記事を、ヤフーニュースにアップしました。⇒ https://t.co/eUajNlSkao  
▶

　求刑延期問題とありますが、たぶんこの元記事は読んでいます。郷原信郎弁護士の記事はリンクも開いていません。大事なのは３月２日１７時２７分という日付と時刻です。

　次がカルロス・ゴーン氏の保釈決定後の郷原信郎弁護士のツイートです。

▶ ツイート％nobuogohara（郷原信郎）％2019/03/06 08:24％ https://twitter.com/nobuogohara/status/1103073770024054785
&twitter(1103073770024054785){theme:light}
> ゴーン氏保釈の件でモーニングショーに出演した高井康行弁護士、浜田敬子氏の「日産の社内のガバナンスで解決すべきだったのではないか」との当然の指摘に、「会社は社会の公器、犯罪をみつけたら司法当局に通報するのが当然、それをしなければ隠ぺいと批判される」などと発言。  
▶

▶ ツイート％nobuogohara（郷原信郎）％2019/03/06 08:28％ https://twitter.com/nobuogohara/status/1103074869695066113
&twitter(1103074869695066113){theme:light}
> 高井氏の理屈によれば、会社の内部では、常に「犯罪」に当たる行為がないか目を光らせ、検察と結託できるかどうかで会社の支配権が左右されることになる。経済界は、検察や、特捜ＯＢヤメ検に支配される。高井氏は、それが「健全な社会」だと思っているのだろうか。  
▶

▶ ツイート％nobuogohara（郷原信郎）％2019/03/06 11:53％ https://twitter.com/nobuogohara/status/1103126413807239170
&twitter(1103126413807239170){theme:light}
> この後、 12:00からのAbemaTV「けやきヒルズ」に出演します。ゴーン氏保釈許可がテーマです。⇒ https://t.co/fwVsOhRvlM  
▶

　上記の郷原信郎弁護士のツイートの内容を読み返すと、ワグナーの「さまよえるオランダ人」という曲のことが思い出されました。どんな曲だったのか余り覚えていないのですが、曲調が醸し出す雰囲気が、さまよえる、というタイトルとともに蘇ってきました。

　ネットで検索すれば、すぐに曲が聴けると思います。さっそくやってみます。

[link:] » ワーグナー《さまよえるオランダ人》序曲／全幕　フィッシャー＝ディースカウ - YouTube https://t.co/hM7h83jWoV

<hr />

　ワグナーのオペラ鑑賞が好きというジャーナリストの江川紹子氏と郷原信郎弁護士の関係性というのも、劇場の舞台をみるような感覚で興味深いものがあります。私が初めに知ったのは、「検察のあり方委員会」に同じメンバーとなっていたことです。

```
江川紹子	ジャーナリスト（獨協大学経済学部特任教授、元神奈川新聞記者）
郷原信郎	弁護士（名城大学教授、元東京高等検察庁検事、前田恒彦元検事の元同僚）

［source：］検察の在り方検討会議 - Wikipedia https://ja.wikipedia.org/wiki/%E6%A4%9C%E5%AF%9F%E3%81%AE%E5%9C%A8%E3%82%8A%E6%96%B9%E6%A4%9C%E8%A8%8E%E4%BC%9A%E8%AD%B0
```

　「検察のあり方委員会」ではなく「検察の在り方検討会議」でした。訂正します。概要をざっとみたところ、弘中惇一郎弁護士が無罪判決を得たことで、今日もテレビでたびたび取り上げられている村木さんの裁判で、前田恒彦元検事がフロッピーの不正を行ったことが発端のようです。

　全１４名の選任を発表したのが２０１０年１１月４日とあります。東日本大震災の４ヶ月ほど前になるようです。議決のような結果発表の日付が見当たりません。座長が千葉景子弁護士（前法務大臣）とあります。その他を含め１５名とのことです。

　役職が、座長と委員にわかれているのですが、この座長というのが不思議に感じる役職名です。座長といえば、個人的に思い出されるのは、高野隆弁護士一座とツイートしていた中村元弥弁護士のことです。旅芸人のようなものをイメージします。

　「原田國男	弁護士（元東京高等裁判所部総括判事、田辺総合法律事務所パートナー）」という名前もありました。藤井美濃加茂市長事件の上告審で、郷原信郎弁護士の弁護団の一人となっていましたが、この２０１０年の時点で弁護士になっていたと確認しました。

　今日の午前中になるように思いますが、カルロス・ゴーン氏の弁護団の一員となっている喜田村洋一弁護士も、郷原信郎弁護士の藤井美濃加茂市長事件上告審の弁護団に加わっていたことを確認しました。弁護士の間でいろいろと接点やつながりがあるようです。

　それにしても、カルロス・ゴーン氏の保釈が認められたことで、テレビの情報番組がそこまで弘中惇一郎弁護士を持ち上げるとは想定外でした。どのチャンネルも「無罪請負人」と「カミソリ弘中」の文言が踊っています。ミヤネ屋では、コメンテーターが神格化されるとまで言っていました。

　東京拘置所前は、お祭りの縁日の参道のような様相になっていたのですが、そこに「差し入れ屋　池田屋」というような看板の古い感じの店があって、これまで何度も東京拘置所前の中継はテレビで見ているのに初めて見たので、これもいくらか不思議な感覚になりました。

　おそらくは日用品のみで食べ物は扱っていないのだと想像します。もうずいぶん前に聞いた話なので現在とは違っているかもしれないですが、東京拘置所で生活していたという人に直接、弁当など差し入れの出来る食べ物が売店に沢山あると聞いていました。

　あるいは店舗販売をしておらず、東京拘置所内に売店を持つ業者なのかもしれません。いずれにせよ、印象に残る珍しい光景でした。

＜＜＜2019-03-06（水曜日）16：40＿［これまでの記述範囲の終了時刻］＜＜＜

* 郷原信郎弁護士のツイートのURLを引用したモトケンこと矢部善朗弁護士（京都弁護士会）のツイート、コンプライアンスで警察や検察に相談するのは自然な流れ、という
  :LOGBOOK:
  CLOCK: [2019-03-06 水 16:57]--[2019-03-06 水 17:30] =>  0:33
  :END:

＞＞＞2019-03-06（水曜日）16：57＿［これからの記述範囲の開始時刻］＞＞＞

　テレビのプライムニュースに今日も高井康行弁護士が出てきましたが、高井の漢字が普通の高になっていました。Mozcでは変換候補が出てきませんでしたが、口ではなくあみだくじのようになった漢字をテレビの見出しで見てきたように思います。

　高井康行弁護士は、これまでよりふっくらした顔立ちに見えました。雰囲気もいくらか違っていて、不機嫌そうに強めの口調で語っているような印象もありました。１７時０４分には、ここまでありがとうございましたと言われ、スタジオから退場されたようです。

　モトケンこと矢部善朗弁護士（京都弁護士会）がURLを引用した郷原信郎弁護士のツイートに高井氏とあるのは、高井康行弁護士のことだと思います。

　テレビの方は、高井康行弁護士が去った後、森友学園の籠池被告の初公判のニュースに移っています。国策捜査という本人の声も聞こえてきますが、同じ刑事裁判なのに、高井康行弁護士が去ったのは気になるところです。

　「覚醒剤多量摂取させ殺害か　会社役員（６９）を逮捕」という初めて知るニュースに１７時１１分に変わりましたが、それも３０秒あるなしで終わりました。高井康行弁護士が拒否したので森友学園問題のコメントはなかったという可能性もありそうです。

▶ ツイート％motoken_tw（モトケン）％2019/03/06 16:30％ https://twitter.com/motoken_tw/status/1103196207264935936
&twitter(1103196207264935936){theme:light}
> 一般論的には、特に上場企業のコンプライアンスとしては、常に会社の内部で犯罪に当たる行為がないか目を光らせるのは当然のことだと思う。
> そして、会社の最高権力者に犯罪の疑いが生じれば、警察や検察に相談するのは自然な流れだと思う。
> それ… https://t.co/zqUQJP5t9F  
▶

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートの末尾で途切れているのは、「それが健全な会社だと思うが、私の認識は間違ってるのかな？」という部分です。いつものモトケンこと矢部善朗弁護士（京都弁護士会）らしい物言いです。

　次がモトケンこと矢部善朗弁護士（京都弁護士会）がURLを引用した郷原信郎弁護士のツイートです。気になったのは、返信扱いになっていないことです。ツイートの返信ボタンを押すと、その場で返信先のメンションが出ていました。

▶ ツイート％nobuogohara（郷原信郎）％2019/03/06 08:28％ https://twitter.com/nobuogohara/status/1103074869695066113
&twitter(1103074869695066113){theme:light}
> 高井氏の理屈によれば、会社の内部では、常に「犯罪」に当たる行為がないか目を光らせ、検察と結託できるかどうかで会社の支配権が左右されることになる。経済界は、検察や、特捜ＯＢヤメ検に支配される。高井氏は、それが「健全な社会」だと思っているのだろうか。  
▶

　同じモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインで見つけたものですが、次のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは他のツイートのURLを引用しながら「返信先」のメンションが表示されています。

▶ ツイート％motoken_tw（モトケン）％2019/03/06 15:55％ https://twitter.com/motoken_tw/status/1103187387184627713
&twitter(1103187387184627713){theme:light}
> @unite_daction リプ欄に再掲
> https://t.co/8E7PE4nrQQ  
▶

　今日のモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインのツイートは、久しぶりにかなりの投稿頻度となっていますが、その前にTwitterのトレンドで見かけていた、「東京新聞の望月衣塑子記者」や「誹謗中傷」に関して、挑発的な返信を行っていたようです。

　次がソース記事の１つのようです。他の記事のことは確認していません。

[link:] » 東京新聞の望月衣塑子記者を支援する署名をネットで集めた中2、誹謗中傷に「子どもが何か意見しちゃいけないんだと感じた」 | ハフポスト https://t.co/q45tSrLSFo

<hr />

＜＜＜2019-03-06（水曜日）17：29＿［これまでの記述範囲の終了時刻］＜＜＜

