#+TITLE: "告発に至る経緯／社会的な影響／ジャーナリストの江川紹子氏／全国検察審査協会連合会の十一面観音像カレンダーとジャーナリストの江川紹子氏のタンホイザー"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-02-14 21:36:45 +0900
FILE_NAME: 2019-02-14-213645_全国検察審査協会連合会の十一面観音像カレンダーとジャーナリストの江川紹子氏のタンホイザー.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  ジャーナリストの江川紹子氏 高野隆弁護士 検察審査会
記事タイトル名の文字数：73　保存ファイル名の文字数：66

#contents

* セラミックヒーターの故障で出掛けた宇出津新港と全国検察審査協会連合会の十一面観音像カレンダー
  :LOGBOOK:
  CLOCK: [2019-02-14 木 22:44]--[2019-02-15 金 00:16] =>  1:32
  :END:

＞＞＞2019-02-14（木曜日）22：44＿［これからの記述範囲の開始時刻］＞＞＞

　昨日の２月１３日になりますが、いろいろと変わったことがありました。まず、ずいぶん久しぶりに長い時間眠り続けていました。起きたのは７時５０分過ぎでしたが、眠ったのは日付が変わる前の前日だったと思います。

　最初、長時間寝ていたためと思ったのですが、起きてから目のかすみが気になっていました。それとセラミックヒーターの電源が無反応となっていました。心当たりはいつも二段階の６００ｗとしていたのを１２００ｗにしたことで、さらにそのまま寝てしまったようです。

　ネットで調べたところ、セラミックヒーターの温風の送出口が異物で塞がれたことで高温となり、なかのヒューズが切れた可能性が高いようでした。ヒューズの交換という方法もあるようでしたが修理が高額なので、新品を買った方がいいという情報もありました。

　セラミックヒーターは3,4年前に買ったものだったと思います。特に不具合もなかったのですが、二段階の切り替えで６００ｗというのは電気代的に気になっていました。ほとんどは６００ｗで使っていましたが、切ると寒くなったり、微妙なところもありました。

　寒いときは灯油の温風ヒーターを使いますが、この冬は、２０Lか１８Lの灯油を２回買っただけで、まだ１回分のポリタンクがまるまる残っています。セラミックヒーターだと寒いと思って温風ヒーターを使うと、ほとんどは室内気温が２度となっています。

　昨年は室内気温が０℃ということもちょくちょくあったのですが、このところは温風ヒーターを使っていると熱く感じてスイッチを切ることも多いです。部屋全体を温めるという使い方はしておらず、体の近くに置いているので、そうなるのだとは思います。

　いつもは、夜中に熱くなったり、寒くなったりで目が覚めることがほとんどでした。ほとんどの場合は寒さで目が覚め、寒さでなかなか寝付けないということがありました。床が底冷えすることがほとんどでした。

　前日なので２月１２日になりますが、部屋に断熱のシートがあるのを見つけて、それを使ってみました。１年以上前に買ったものだと思うのですが、宇出津新港のアルプの百円均一で買ったものでした。それを床に敷いて寝ることで、寒さを感じず、長時間寝ていたのです。

　宇出津新港に向かうとき、ちょっと立ち寄って話をしたところ、目のかすみは花粉症の症状ではないかと言われました。今までも目のかすみを感じたことはあったのですが、目を水でよく洗うことで治っていました。

　宇出津新港のクスリのアオキで目薬を買いました。２００９年に羽咋市から戻ってからは買った記憶も、使った記憶もないので、１０年以上は目薬を使ったことはなかったと思います。目薬を使うという発想自体がありませんでした。

　クスリのアオキでは６００円弱だったと思う目薬とおにぎりを１つ買いました。おにぎりは７８円だったと思いますが、クスリのアオキは税別価格だったと思います。税込価格の表示でわかっているのは、あとで新しいセラミックヒーターを買ったホームセンタームサシだけです。

　買った目薬を使うと右目のかすみはすぐに治ったのですが、左目が余りよくならず、今日の午後に目を水でよく洗ってから目薬を使うと、ようやく違和感を感じない程度に治りました。一時は、聞いたことのある白内障などではないかと、少し心配しました。

　目薬を買ってつけたあと、気が向いてアルプの中にある食堂で食事をしました。この店をやっている人は、夫婦ともによく知っているのですが、店に入って食事をしたのは、7,8年ぶりになるのではと思いました。羽咋市から戻ってから1,2回だったとも思います。

　店の一番奥の方で食事をしていたのですが、ふと外の窓ガラスに観音像のカレンダーがあることに気が付きました。気になったので近づいてみると、カレンダーに「全国検察審査協会連合会」などとありました。

　家に戻ってから調べると、その「全国検察審査協会連合会」は、数年前から毎年、十一面観音像のカレンダーを出しているようです。十一面観音像というのは、観音像の１つとして知識はありましたが、なぜ検察審査会の関係者が、そこにこだわるのか気になりました。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2019/02/14 09:17％ https://twitter.com/hirono_hideki/status/1095839316100562944
&twitter(1095839316100562944){theme:light}
> 11面観音像カレンダ－-ご存知ですか？検察審査会制度を！！ https://t.co/p1Ho4BUVe3  
▶

　上記のツイートは、今日の朝の９時１７分に投稿したもののようです。リンクのページは、昨日の夕方の遅い時間には見ていたと思います。もう一度調べ直してみます。

［link：］ 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年02月13日 - Twilog https://twilog.org/hirono_hideki/date-190213

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2019/02/13 13:15％ https://twitter.com/hirono_hideki/status/1095536846099046400
&twitter(1095536846099046400){theme:light}
> 著作権侵害、スクショもＮＧ　「全面的に違法」方針決定：朝日新聞デジタル https://t.co/lZjvHng2jE  
▶

　上記のツイートは、アルプの食堂でスマホを見ていた時に投稿したものですが、初めにツイートの投稿に失敗して、記事を読み終えてから投稿し直したものです。なぜエラーが出たのかわからなかったですが、それも気になってはいました。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2019/02/13 18:35％ https://twitter.com/hirono_hideki/status/1095617484453904384
&twitter(1095617484453904384){theme:light}
> CM中のアイリスオーヤマの人感センサー 大風量セラミックファンヒーターKJCH-12TD3とKJCHM-12TD3の特徴と違い | アイリスオーヤマ勝手に大好き．コム https://t.co/sfAaA8yHf1  
▶

　上記の昨日、１８時３５分のツイートは、宇出津新港から家に戻って最初のツイートとなっています。午前中に宇出津新港に買い物に出掛けたのもずいぶん久しぶりのことだったのですが、夕方まで宇出津新港のアルプとホームセンタームサシにいました。

　最近は、宇出津新港に買い物に行くことが少なくなっているのですが、外に出かけること自体も少なくなっています。寒さもありますが、お金の節約もあります。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2019/02/13 20:03％ https://twitter.com/hirono_hideki/status/1095639640789245952
&twitter(1095639640789245952){theme:light}
> 林修のニッポンドリル【知らないアナタは損!全国ご利益神社SP】
> 
> 2019年2月13日（水）  20時00分～20時54分  の放送内容 https://t.co/b001u22BFA  
▶

　上記の番組は、2,3日前からテレビの番宣で見ていて気になっていたのですが、同じ時間帯に所さんの番組に石川県川北町がでるということでそちらも気になっていました。

　十一面観音像のことは、それほど意識していなかったのですが、「林修のニッポンドリル【知らないアナタは損!全国ご利益神社SP】」の放送にも出てきたので、さすがに気になりました。気になることはほかにもあったのですが、最近とくに大きかったのが金沢市寺町の八阪神社のことです。

　最初、北陸中日新聞の朝刊の１面で知ったのですが、その八阪神社についてネットで調べてみると、古い神社の建物が、そのまま民家の一部になっているようでした。これは以前に一度だけ見たもので、能登町宇加塚にある宇加塚神社だったと思います。

　Googleマップでみると、宇加塚神社という名称はなく、同じ場所にあるのが「大乗寺」だったと思いますが、神社とお寺が隣り合っていました。最初に神社とお寺が隣接していることで驚いたのは輪島市の金蔵でのことでしたが、旧柳田村の諏訪神社の隣にもお寺があったことを思い出しました。

```
22件目 » 2018-06-26_143655＿母親の入院する上町の病院へ・宇加塚神社・左隣りに大乗寺.jpg

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： 2018年06月27日22：10記録＼法務検察・石川県警察宛＼写真資料：2018-06-26_131802〜2018-06-26_192521：183件 http://hirono2014sk.blogspot.com/2018/06/2018062722102018-06-261318022018-06.html#20180626143743
```

　自分の記憶だと、左手に神社があり、そちらの神社が住宅を兼ねていたように思っていたのですが、記録から上記の写真を探し出し開いてみると、神社の方が右手にあって、それも奥まっているようです。どちらも敷地の中には立ち入らなかったのですが、記憶に違いがあったようです。

```
30件目 » 2018-06-26_143940＿母親の入院する上町の病院へ・宇加塚・宇加塚神社右手のお地蔵さま３体の祠.jpg

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： 2018年06月27日22：10記録＼法務検察・石川県警察宛＼写真資料：2018-06-26_131802〜2018-06-26_192521：183件 http://hirono2014sk.blogspot.com/2018/06/2018062722102018-06-261318022018-06.html#20180626143743
```

　忘れていたのですが、宇加塚神社の右手に３体のお地蔵さまがある祠がありました。神社の敷地内のような場所にお墓があることで驚いたのは輪島市の曽々木の春日神社でした。はじめて曽々木大祭を見に行ったときのことでした。

　Googleマップで、調べたところ、宇加塚の大乗寺は表示がなくなっていました。廃寺となってしまったのかもしれないですが、神社が閉鎖になったと聞いたのも金沢市寺町の八阪神社のニュースが初めてのことでした。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2019/02/05 14:47％ https://twitter.com/hirono_hideki/status/1092661022769303552
&twitter(1092661022769303552){theme:light}
> 「年間の収入は千円とか二千円でした」。荒井宮司が明かす。八阪神社は特定の氏子がいない「崇敬神社」。さい銭や厄払いなどの祈とう（きとう）料が主な収入源だが、近年は参拝者が激減し、毎年七月の例祭にも人が集まらなくなった。このため副業や… https://t.co/pMHYlujfZv  
▶

＜＜＜2019-02-15（金曜日）00：16＿［これまでの記述範囲の終了時刻］＜＜＜



