#+TITLE: "告発に至る経緯／弁護士による影響・阻害要因／モトケンこと矢部善朗弁護士（京都弁護士会）／こういうバイトの犯罪行為に対しては、毅然として刑事告訴と損害賠償請求する・・・信頼回復のために必要かつ重要"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-02-11 15:01:53 +0900
FILE_NAME: 2019-02-11-150153_こういうバイトの犯罪行為に対しては、毅然として刑事告訴と損害賠償請求する・・・信頼回復のために必要かつ重要.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  モトケンこと矢部善朗弁護士（京都弁護士会） 刑事告訴 損害賠償
記事タイトル名の文字数：97　保存ファイル名の文字数：75

#contents

* バイトの犯罪行為に対して刑事告訴と損害賠償請求する、それが適切な管理・統制であり、信頼回復のために必要かつ重要というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート
  :LOGBOOK:
  CLOCK: [2019-02-11 月 15:05]--[2019-02-11 月 16:12] =>  1:07
  :END:

＞＞＞2019-02-11（月曜日）15：05＿［これからの記述範囲の開始時刻］＞＞＞

▶ ツイート％motoken_tw（モトケン）％2019/02/09 14:20％ https://twitter.com/motoken_tw/status/1094103755497168897
&twitter(1094103755497168897){theme:light}
> @dd2dtty @n_kanizuka こういうバイトの犯罪行為に対しては、毅然として刑事告訴と損害賠償請求する、というのが適切な管理・統制だと思います。
> それが信頼回復のために必要かつ重要。  
▶

　数日前に見かけていたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートですが、気になっていました、その後のツイートの更新は少ないようです。テレビで見たハマチの切り身をゴミ箱に捨て、まな板に戻した動画の問題のことだと思います。

　昨日は15時からの予定で小木港にアジ釣りに出掛けたのですが、道路に積雪が残っていそうだったので早めに出発し、道路の行きは少なくほとんど支障がなかったので、予定より早く小木港に到着しました。

　21時30分に渡船の迎えを頼んで帰ってきましたが、気温が低く路面凍結のおそれがあったので、慎重に時間を掛けて宇出津に戻ってきました。出掛けていた時間は短い方だったと思いますが、テレビやネットを見なかったそれだけの時間でも、ずいぶん変わったような気がしました。

　家に戻ってテレビをつけたのは22時30分を過ぎていたと思いますが、しばらくの間、平日だと勘違いし、23時頃からニュースzeroが始まるつもりで、チャンネルをテレビ金沢にしていました。23時ころに気がついてMr.サンデーに変更しましたが、ニュース関係はほぼ終わっていました。

　そのあと録画していた20時45分から15分間のニュース番組と、NEWS７を視聴しましたが、どれも見たことのないニュースに思え、数日間経過したような錯覚をおぼえました。

　NEWS７に気になったニュースが２つありました。１つは特集のような扱いでスクールロイヤーを取り上げていたこと、もう一つは、新岡山港での母親が子ども2人を道連れにした飛び込みのニュースです。どちらもネットでは、情報を見ていないと思います。

```
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
基準となる注目のツイートを含む最新199件のツイート
2019-02-01 15：40から199件：最新2019-02-11 10：56という範囲（9日19時間16分）の取得
基準となる注目ツイートの位置と内容タイムラインの該当箇所に移動
16件目 ツイート： motoken_tw（モトケン） 日時： 2019-02-09 14：20 URL： https：//twitter.com/motoken_tw/status/1094103755497168897 
{% tweet 1094103755497168897 %}
> @dd2dtty @n_kanizuka こういうバイトの犯罪行為に対しては、毅然として刑事告訴と損害賠償請求する、というのが適切な管理・統制だと思います。 \n それが信頼回復のために必要かつ重要。 

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＼モトケン　@motoken_tw＼こういうバイトの犯罪行為に対しては、毅然として刑事告訴と損害賠償請求する、というのが適切な管理・統制だと思います。 それが信頼回復のた http://hirono2014sk.blogspot.com/2019/02/motokentw_11.html
```

　上記はモトケンこと矢部善朗弁護士（京都弁護士会）のツイートのまとめ記事になります。そういえば昨夜、Bloggerの管理画面を開いたところ、英語のメッセージが出ていて、調べたところ、Google＋のサービスが終了するという情報が出てきました。

　まとめ記事でツイートを遡ると、やはりモトケンこと矢部善朗弁護士（京都弁護士会）が批判の矛先を向けるのは、くら寿司のバイトの問題だと確認しましたが、1,2日のほどの間、テレビで繰り返し同じ動画を見たものです。

　あらためてモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを読むと、刑事告訴とありますが、該当すべきとする罪名が見当たりません。考えられるのは業務妨害罪ぐらいなのですが、信用毀損というのが刑法の勉強をしているときに出ていたような気がしました。

　調べたところ刑法233条は、「信用毀損及び業務妨害」となっていて少し驚きました。業務妨害罪は、偽計と威力があったことは記憶にあったのですが、その違いというのはよく憶えていませんでした。

　業務妨害罪は、爆破予告などで警備員を増やしたり、爆発物を探すために人員を動員するなど、文字通り本来の業務を妨害することであり、保護法的も物理的な負担という側面が大きいのかと考えていたのですが、信用と業務が一体になっていたというのは、個人的に意外な発見です。

　調べたページの解説部分に、「本罪の保護法的は、人の経済的な評価である。」とありました。条文をよく見ると、「虚偽の風説を流布し、又は偽計を用いて、人の信用を毀損し、又はその業務を妨害した者は」とあるので、威力というのは見当たりません。

　もう一度調べると、「威力業務妨害」は刑法234条となっていました。条文は「威力を用いて人の業務を妨害した者も、前条の例による。」とあるので、罰則は２３３条の「信用毀損及び業務妨害」と全く同じようです。

　３年以下の懲役という罰則は、私が法律の勉強を始めた平成５年ぐらいから変わっていないと思います。また、罰則を重くするべきという意見を見た覚えもありません。そういえば、最近の芸能人の性犯罪のニュースで、強制性交罪の法定刑の下限が懲役５年と知って驚きました。

　１０年以上経つのか調べないとわからないですが、殺人罪の法定刑の下限が懲役３年だったのが懲役５年に引き上げられました。上限が死刑もある殺人罪とは違いますが、平成４年当時は、法定刑の下限が懲役２年だった強姦罪です。

　強制性交罪という罪名も生々しさを感じるとともに、暴力的で威圧的な独裁主義国家における制裁のような響きを感じます。一部の弁護士らが奔走して法改正にこぎつけたというイメージもありますが、本当に性犯罪の被害者の利益や、利益保護に役立つのか疑念を覚えます。

　モトケンこと矢部善朗弁護士（京都弁護士会）が主張するように刑事告訴が妥当なケースなのか疑問がありますし、告訴の場合は、構成要件に該当する被害者が刑事手続をとるかたちになるのかと思います。被害者として考えられるのは、会社あるいは企業としての「くら寿司」です。

　これと似たような違和感をおぼえたのは、日大アメフト部の危険タックル問題で、前監督、前コーチの不起訴処分の公算が高まったという報道に対するモトケンこと矢部善朗弁護士（京都弁護士会）のツイートでした。正式な処分を出す前の、見通しのような報道です。

＜＜＜2019-02-11（月曜日）16：12＿［これまでの記述範囲の終了時刻］＜＜＜

* 日大の内田元監督、井上元コーチの嫌疑を、かなり黒っぽいとし、警察のピンボケ捜査の可能性も指摘していたモトケンこと矢部善朗弁護士（京都弁護士会）の一連ツイート
  :LOGBOOK:
  CLOCK: [2019-02-11 月 16:37]--[2019-02-11 月 18:05] =>  1:28
  :END:

＞＞＞2019-02-11（月曜日）16：37＿［これからの記述範囲の開始時刻］＞＞＞

　ツイートを探し出すのに、けっこう手間取りました。「日大」や「監督」をキーワードにしたのですが、それではなかなか見つかりませんでした。探し出せたのは、Twilogのおかげです。ツイートの昨年１１月１３日という時期も、自分の記憶とだいたいあっていました。

▶ ツイート％motoken_tw（モトケン）％2018/11/13 11:13％ https://twitter.com/motoken_tw/status/1062166594225197056
&twitter(1062166594225197056){theme:light}
> @ken_kataoka かなり黒っぽいと感じたけどな。「「潰せ」という言葉が何を意味するかをアメフト界隈の一般論で認定しただけでは十分ではない。それを踏まえて本件ではどういう意味だったのかが問題になる。そして選手があのような行動に出たのはなぜかが問われる。  
▶

▶ ツイート％motoken_tw（モトケン）％2018/11/13 13:23％ https://twitter.com/motoken_tw/status/1062199365299666945
&twitter(1062199365299666945){theme:light}
> @ken_kataoka 少なくとも井上コーチには嫌疑がありますね。
> 当然、それ以前の監督の言動も「潰せ」の意味認定に影響します。  
▶

▶ ツイート％motoken_tw（モトケン）％2018/11/13 16:23％ https://twitter.com/motoken_tw/status/1062244591028469760
&twitter(1062244591028469760){theme:light}
> @ken_kataoka 検察の上司の考え次第ではひっくり返る可能性がゼロではない。  
▶

▶ ツイート％motoken_tw（モトケン）％2018/11/13 17:51％ https://twitter.com/motoken_tw/status/1062266797649420290
&twitter(1062266797649420290){theme:light}
> @ken_kataoka 今までに警察が集めた証拠だけで起訴できるかも知れません。警察がピンボケ捜査をしているかもわかりません。井上コーチの自白一つでどうにかなる事件とは思いませんよ。  
▶

　日付を頼りに、まとめ記事を探し出しました。

[link:] 2018年11月13日11時26分の登録： ＼モトケン　@motoken_tw＼かなり黒っぽいと感じたけどな。「「潰せ」という言葉が何を意味するかをアメフト界隈の一般論で認定しただけでは十分ではない。それを踏まえて http://hirono2014sk.blogspot.com/2018/11/motokentw_13.html

```
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
基準となる注目のツイートを含む最新199件のツイート
2018-11-05 20：02から199件：最新2018-11-13 11：13という範囲（7日15時間11分）の取得
基準となる注目ツイートの位置と内容タイムラインの該当箇所に移動
1件目 ツイート： motoken_tw（モトケン） 日時： 2018-11-13 11：13 URL： https：//twitter.com/motoken_tw/status/1062166594225197056 

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＼モトケン　@motoken_tw＼かなり黒っぽいと感じたけどな。「「潰せ」という言葉が何を意味するかをアメフト界隈の一般論で認定しただけでは十分ではない。それを踏まえて http://hirono2014sk.blogspot.com/2018/11/motokentw_13.html
```

　1件目のツイートとして記録されているので、それ以降のツイートの流れが不明です。これだとちょっとよくないな、と思いました。

[link:] 2018年11月14日03時53分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2018年11月13日”：42件 http://hirono2014sk.blogspot.com/2018/11/motokentw2018111342.html


　ちょっと記憶になかったのですが、2018年11月13日のモトケンこと矢部善朗弁護士（京都弁護士会）は、次のツイートも行っていたようです。モトケンこと矢部善朗弁護士（京都弁護士会）が返信したツイートと一緒にご紹介します。

▶ ツイート％Masashi_Yuki_XX（偽海洋地形学者Masashi Yu-ki）％2018/11/13 12:33％ https://twitter.com/Masashi_Yuki_XX/status/1062186785998950400
&twitter(1062186785998950400){theme:light}
> @motoken_tw @nogawam モトケン先生久しぶりにツイート拝見しましたが、方向性は違えど他の人のツイートに対し当たり屋的に突っ込んでく感じが大敵である小倉秀夫先生みたくなってる気がしますけど大丈夫ですか?  
▶

▶ ツイート％motoken_tw（モトケン）％2018/11/13 12:38％ https://twitter.com/motoken_tw/status/1062187897967697920
&twitter(1062187897967697920){theme:light}
> @Masashi_Yuki_JP @nogawam おぐりんの嫌フェミニズムと似たような感じかもね。
> 偏った見解に対する拒否反応みたいなもの。
> 自分が偏らないように気をつける必要があります(^^;  
▶

　次のツイートも以前見かけていたような気がしますが、モトケンこと矢部善朗弁護士（京都弁護士会）の法律家としての心構えのようなことが書いてあります。確認されたとは到底思えないので、刑事告訴を進めているという私の立場もあります。法律家としての責任の追求です。

▶ ツイート％motoken_tw（モトケン）％2018/11/13 12:41％ https://twitter.com/motoken_tw/status/1062188722706235392
&twitter(1062188722706235392){theme:light}
> @nogawam 法律家はどんなに明白なように見える事実だって確認するものです。
> あなたにとって自明な事実でも別の人にとってそうでない場合があるでしょう。
> だから「確認」が大事なんですよ。  
▶

　日大のアメフト部の前監督と前コーチの刑事処分ですが、昨年の11月13日頃の段階でも、不起訴処分になる見通しというようなニュースがあり、つい先日も、同じようなニュースがあって、そちらにモトケンこと矢部善朗弁護士（京都弁護士会）の反応は見ていません。

　その、つい先日とした日大アメフト部の前監督と前コーチの刑事処分については、ジャーナリストの江川紹子氏が記事を公開していましたし、その前になると思いますが、郷原信郎弁護士も第三者委員会のあり方を批評するようなかたちで、ブログ記事に取り上げていました。

　その、つい先日というのは、ここ一週間以内だと思いますが、テレビではニュース報道意外に、情報番組や報道番組が取り上げて、解説者に解説をさせるという対応は、一度も見ていないと思います。もっともここ最近の私は、テレビをつけなかったり、見ないことも多いので、見落としの可能性はあります。

　それでも、前回の昨年11月13日頃と思われる段階では、バイキングがその問題を取り上げ、連続の2日目だったように思うのですが、第三者委員会にコメントを求めたものの現在のところ返答がない、というような説明がありました。

　名前はわからないのですが、ほとんど毎回のようにバイキングの放送で見る人で、進行役のアナウンスやボードの読み上げをよくやっている人です。顔はよく見ますが、バイキング以外の報道では見ていないような気がします。

```
８日のフジテレビ系「バイキング」（月～金曜前１１・５５）から「直撃ＬＩＶＥ　グッディ！」（月～金曜後１・５５）へのリレータイムで、同局の榎並大二郎アナウンサー（３３）がスタジオを大爆笑させた。

［source：］「バイキング」榎並大二郎アナが雪予報に困惑　イチゴ狩りの予定明かし坂上忍ら爆笑｜ニフティニュース https://news.nifty.com/article/entame/etc/12273-186074/
```

　調べたところ、榎並大二郎というお名前のようです。初めて見るような名前だと思いました。大二郎という名前も珍しいと思いましたが、私の世代だと、昭和の時代のテレビドラマ「子連れ狼」の子役の役柄、大五郎を思い出し、文字を見比べても似ていると思いました。

　榎並という名前も初めて目にする漢字の組み合わせだと思いましたが、Mozcでは「えなみだいごろう」で一発に変換候補が出てきました。かなりの著名人と思われます。バイキング以外に見かけないというのも、考えてみると不思議なのですが、看板的な存在感もあります。

　上記の記事になっている「イチゴ狩り」の件は、生放送で見ていましたが、それがニュース記事のような扱いになっていることの方が、驚きでした。

```
65件目 » 2018-11-15_123406＿テレビの画面・バイキング・日大アメフト問題で急展開！内田前監督らの指示はなかった！？捜査に被害選手の父親の反応は？.jpg

［link：］ 2018-11-15_123406＿テレビの画面・バイキング・日大アメフト問題で急展開！内田前監督らの指示はなかった！？捜査に被害選手の父親の反応は？.jpg http：//hirono2014sk.blogspot.com/2018/11/2018111901142018-11-150703502018-11.html#20181115123406#20181115123406

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： 2018年11月19日01：14記録＼法務検察・石川県警察宛＼テレビの画面撮影資料：2018-11-15_070350〜2018-11-15_230334：201件 http://hirono2014sk.blogspot.com/2018/11/2018111901142018-11-150703502018-11.html#20181115123406
```

　上記のテレビの画面には、配色を３つに分けた3段の大きな文字で「日大アメフト　危険タックル問題　内田前監督らを立件見送りへ　警視庁の調べでわかった新事実とは？」と表示されています。これだけでも当時の報道がだいたい把握できました。

　そういえば、テレビの画面撮影とスマホの写真の整理がだいぶんたまっています。もう半月は整理を行っていないと思いますが、撮影の枚数は、このところかなりセーブ気味です。最近の日大問題の画面も撮影済みと思いますが、名前を付けていないので、探すにも容易でないです。

　そのままネットでニュース記事を探してみたいと思います。

　ちょっと気になる内容の記事を発見しました。続きは、本件エントリーのメイン、モトケンこと矢部善朗弁護士（京都弁護士会）から離れて、書いておきたいと思います。

＜＜＜2019-02-11（月曜日）18：05＿［これまでの記述範囲の終了時刻］＜＜＜

