#+TITLE: "警察の「GPS捜査」は、どれほどプライバシーを暴くのか（亀石　倫子）　｜　現代新書　｜　講談社（1／3）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-12 13:05:34 +0900
FILE_NAME: 2019-08-12-130534_警察の「GPS捜査」は、どれほどプライバシーを暴くのか（亀石　倫子）　｜　現代新書　｜　講談社（1／3）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 警察  亀石弁護士 GPS捜査 プライバシー
記事タイトル名の文字数：52　保存ファイル名の文字数：74

* 警察の「GPS捜査」は、どれほどプライバシーを暴くのか（亀石　倫子）　｜　現代新書　｜　講談社（1／3）
  :LOGBOOK:
  CLOCK: [2019-08-12 月 13:08]--[2019-08-12 月 14:08] =>  1:00
  :END:

＞＞＞2019-08-12（月曜日）13：08＿［これからの記述範囲の開始時刻］＞＞＞

▷ リツイート→maido_osaka（imanishi）＞MichikoKameishi（弁護士 亀石倫子）｜2019/08/09 16:54／2019/08/09 08:00｜https://twitter.com/maido_osaka/status/1159734723062538245 ／ https://twitter.com/MichikoKameishi/status/1159600361197334528
&twitter(1159734723062538245){theme:light}
> RT @MichikoKameishi: 警察の「GPS捜査」は、どれほどプライバシーを暴くのか https://t.co/kt47QCL100 #現代新書  

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MichikoKameishi（弁護士 亀石倫子） 日時：2019-08-12 13:10／2019-08-09 08:00 URL： https://twitter.com/kk_hirono/status/1160765541277040641 https://twitter.com/MichikoKameishi/status/1159600361197334528
&twitter(1160765541277040641){theme:light}
> 警察の「GPS捜査」は、どれほどプライバシーを暴くのか https://t.co/kt47QCL100 #現代新書
◁◁◁
<hr />

　繰り返しになりますが、大阪のジャーナリスト今西憲之氏のTwitterのタイムラインで、リツイートとして亀石倫子弁護士のツイートを目にしました。この経緯を強調しておきたいのは、いろいろな積み重ねや繋がりがあると感じるからです。

　その1つが、今日が34年前という日航機の墜落事故ですが、それが直接、今西憲之氏に関連するものではありません。ジャーナリストや報道のあり方、という意味で感じるところがあります。今西憲之氏に関してはまだ詳しくは知らないですが、非常に強いパワーは感じています。

　その非常に強いパワーを感じる今西憲之氏のリツイートとして目にした亀石倫子弁護士ですが、同弁護士にもまた違ったパワーを感じてきましたし、このパワーというのはそのまま社会的な影響力であるとも考えています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 13:24／2019-08-12 13:15 URL： https://twitter.com/kk_hirono/status/1160768943528669187 https://twitter.com/hirono_hideki/status/1160766623357079552
&twitter(1160768943528669187){theme:light}
> 2019年08月12日13時14分の登録： REGEXP：”警察の「GPS捜査」は、どれほどプライバシーを暴くのか”／データベース登録済みツイート：2019年08月12日13時14分の記録：ユーザ・投稿：5／9件 https://t.co/OhHDPnn7QC
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 13:24／2019-08-12 13:13 URL： https://twitter.com/kk_hirono/status/1160768957583724544 https://twitter.com/hirono_hideki/status/1160766324001296390
&twitter(1160768957583724544){theme:light}
> 2019年08月12日13時13分の実行記録 \n  twitterAPI-search-lawList-mydql-add.rb "警察の「GPS捜査」は、どれほどプライバシーを暴くのか" \n  ツイート数：5/1491 リツイート数：4/1… https://t.co/uyoSxWJBVq
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-12 13:34／2019-08-12 13:25 URL： https://twitter.com/kk_hirono/status/1160771618282459136 https://twitter.com/s_hirono/status/1160769199574147072
&twitter(1160771618282459136){theme:light}
> 2019-08-12-131139_imanishiさんがリツイート弁護士亀石倫子@MichikoKameishi·8月9日警察の「GPS捜査」は、どれほどプライバシーを暴くのか.jpg https://t.co/8N80UVd5z3
◁◁◁
<hr />

　メインとなる亀石倫子弁護士に関する記事ですが、ページを開き普通のサイトではなさそうと思ったところ、自作のコマンドでページタイトルを確認したところで、亀石倫子弁護士の本の紹介だとようやく気が付きました。

　「警察の「GPS捜査」は、どれほどプライバシーを暴くのか（亀石 倫子） | 現代新書 | 講談社（1/3）」がそのページタイトルになりますが、普通にホームページを見ているだけでは、気が付かない、気が付けないことも多いのではないかと感がてることがあります。

　亀石倫子弁護士のツイートは投稿時刻を確認すると、8月9日の午前8時となっていました。時刻の表示はないですがリンクの記事も同じ8月9日の日付がみえます。今日は8月12日ですが、3日ほど気が付かなかったことになります。

　亀石倫子弁護士に関するツイートは法クラのTwitterタイムラインでよく見かけているので、これは意外に感じました。亀石倫子弁護士を高く評価するものが多くて、参議院選挙で亀石倫子弁護士が落選した時は、残念がるツイートやリツイートを結構な数見かけていました。

　時刻は13時47分です。これから亀石倫子弁護士の記事の内容を読みます。ページタイトルをみると3ページになっているようですが、分量も読んでみないとわかりません。時間を使うもったいなさは少なからず感じていますが、警察批判は気になる問題なので、看過はしないこととします。

```
皆様、こんにちは。現代新書アルバイトのショウです。
本日は、現代新書の近刊「刑事弁護人」をご紹介させていただきます。
警察が秘密裏に行っていた「GPS捜査」。その違法性が争われ、最高裁が「令状なきGPS捜査は違法である」と判断したことで話題となりました。その裁判で弁護士として関わられた、亀石倫子先生の闘いを、息の詰まるような臨場感で描かれています。
その中でも、僕が特に面白かった箇所を、皆様と共有させていただきたいと思います。
警察が「GPSはなんとなくの位置しかわからず、プライバシーの侵害には当たらない」という事実と異なる発言をし、それに憤る弁護人団。そこで彼らが打った手は、「実際に車にGPSを取り付け、その正確性を証明する」というものでした。
なんとなく、裁判所で喋ってる人というイメージが、弁護士にはあるかと思いますが、先生方がいかに泥臭く真実を証明しようとしているか、その迫真の姿をぜひ御覧ください。

［source：］警察の「GPS捜査」は、どれほどプライバシーを暴くのか（亀石 倫子） | 現代新書 | 講談社（1/3） https://gendai.ismedia.jp/articles/-/66420?media=gs
```

　上記の引用は、ページの冒頭に引用部分のようなデザインも適用されている説明書きになります。「弁護人団」という言葉は初めて目にしたように思います。北海道の開拓団を連想しましたが、亀石倫子弁護士はその北海道の小樽市の出身ということでイメージの１つにもなっています。

　この冒頭の説明書きによると、書籍名は「刑事弁護人」となるようです。だとすれば、法クラのTwitterで話題として目にすることがあったように思いました。そのまま本の名前とまでは考えていなかった気もするのですが、魂というのかスピリッツや強い意気込みを感じさせます。

　途中から飛ばし読みになりましたが、GPSの精度の検証実験に終始した記事の内容かと思いました。ロケットの打ち上げが成功してGPSの位置情報の精度が上がり50メートルの誤差の解消が期待できるというようなニュースをテレビで見かけましたが、まだ1年経っていない気もします。

　警察の脅威を訴えかける感じでしたが、犯罪被害者の立場になれば加害者の確保や損害回復の期待も高まるわけですから歓迎する向きもありそうに思います。ともあれ、なんで8月9日のタイミングだったのかということが余計に気になりました。

　最後に余り時間を掛けずに済んで良かったです。

＜＜＜2019-08-12（月曜日）14：08＿［これまでの記述範囲の終了時刻］＜＜＜


