#+TITLE: "参考資料／社会／性犯罪／愛知県警は安倍政権の忠犬となった警察キャリアに臆することなく、捜査を尽くさないと、国民の信頼そのものを失いかねない　←リテラ編集部"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-03-04 10:14:44 +0900
FILE_NAME: 2019-03-04-101444_愛知県警は安倍政権の忠犬となった警察キャリアに臆することなく、捜査を尽くさないと、国民の信頼そのものを失いかねない　←リテラ編集部.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  リテラ 警察 性犯罪 安倍政権
記事タイトル名の文字数：77　保存ファイル名の文字数：87

#contents

* "愛知県警は安倍政権の忠犬となった警察キャリアに臆することなく、捜査を尽くさないと、国民の信頼そのものを失いかねないことを肝に銘じるべきだろう。"　←リテラ編集部
  :LOGBOOK:
  CLOCK: [2019-03-04 月 10:18]--[2019-03-04 月 15:53] =>  5:35
  :END:

＞＞＞2019-03-04（月曜日）10：18＿［これからの記述範囲の開始時刻］＞＞＞

　このリテラというネットニュースと思われるサイトですが、以前も、これはさすがにどうなのかと考える記事を見かけたことがありました。ページのデザインが特徴的なので印象にも残りやすいのですが、ファッションの通販サイトのような趣きも感じられます。

［link：］ 田畑毅元議員“準強制性交事件”で捜査潰しの動き！ 山口敬之氏への逮捕状執行を止めた中村格・警察庁官房長が介入か｜LITERA／リテラ https://lite-ra.com/2019/03/post-4581.html

　記事は２ページに分かれています。警察の対応を別にした事件の事実関係はテレビで見てきたものと変わりないと思います。警察や官邸の対応となると具体性もあるような初めて知ることが書いてありました。

　準強制性交容疑で処罰すべきという強い方向性の感じられる記事です。これは伊藤詩織さんの事件と同じ構図になりますし、２つの事件に共通した警察幹部を疑惑の対象と決めつけ実名を挙げています。

　被害者の気持ちや立場というのもあるので軽々には言えないことですが、強制性交罪は弁護士商売のための道具あるいは武器として罰則が強化されたのではという不信があります。以前は２年以上の懲役だったものが、２年ほど前になりますか、５年以上の懲役刑にされました。

　罪名自体が強姦罪から強制性交罪、同じく準強姦罪が準強制性交罪と変わりました。懲役２年以上の刑罰だった強姦罪の頃は、強姦罪の事実認定について、女性に酷と思われるハードルの高さを感じる情報を多く見かけたものですが、近頃はずいぶん緩やかに感じています。

　きわめつけが俳優の新井浩文被告の事件ですが、強制性交罪の構成要件である暴行の態様があいまいなまま、テレビのバイキングでそれを唯一指摘していた（私個人の観測範囲）清原博弁護士も、それを言い逃れの手段のように説明していました。

　本来、警察から取り調べの情報が漏れると、リークと痛罵するのが弁護士脳の傾向ですが、２０１６年８月の同じく俳優の高畑裕太氏の強姦致傷事件のときも、警察から漏れてくる情報を問題視する弁護士は一人も見かけませんでした（私個人の観測範囲）。

[link:] » リテラ 高畑裕太 - Google 検索 https://t.co/vfeFVEHEjm

<hr />
[link:] » 高畑裕太事件でも…性犯罪における警察、検察、裁判所の“男目線”が被害者をさらに傷つけている！｜LITERA／リテラ https://t.co/pqdwdkXhnN

<hr />

　高畑裕太氏の事件の年を確認するための検索でしたが、リテラでありそうと見当をつけたところてきめんにヒットしてきました。事件の日付は８月２３日とよく憶えています。理由は何度か書いてきましたが、輪島大祭２日目、重蔵神社大祭の当日だったからです。

　輪島市の海上６０キロ先と聞く舳倉島の女神が、年に一度、輪島市の男神に会いに来るのが輪島大祭の由来と見たことがありますが、舳倉島の女神は嫉妬深く、輪島大祭１日目の奥津比咩大祭の神輿の担ぎては化粧やエプロンで女装するとも聞きます。

　高畑裕太氏はNHK連続テレビ小説まれ、で一躍、俳優としてブレイクしたと聞きますが、輪島市でのロケも多かったはずです。そこで女性相手にとんでもない悪さをしていて、それに輪島の神様が怒って、お祭りの当日に大きな事件を起こさせたのかと、当初は想像もしました。一種の天変地異です。

　高畑裕太氏本人にすれば、まさに天変地異の驚天動地だったことでしょう。本人は合意の性交渉と思っていたらしく、寝ていたところを警察官に起こされ、警察署に連れて行かれたというような報道がありました。

```
実際、同書はおもに2011年に出されたある性犯罪の判決を疑問視し、問題提起した内容なのだが、それは当時18歳の女性が「ついてこないと殺すぞ」と男に脅迫され、ビルの踊り場で強姦されたという事件だった。

　この裁判では、まず地裁が女性の供述の信用性を認めて被告人に懲役4年の有罪、高裁も一審判決を支持して控訴を棄却したのだが、最高裁は自判し、“女性が助けを求めていないのが不自然”“「無理やり犯された」のに膣などに傷もついていない”“女性は供述を変化させている”などとし、一審判決を「経験則に照らして不合理であり、是認することができない」としたうえで逆転無罪が言い渡されたのだという。

［source：］(2ページ目)高畑裕太事件でも…性犯罪における警察、検察、裁判所の“男目線”が被害者をさらに傷つけている！｜LITERA／リテラ https://lite-ra.com/2016/09/post-2558_2.html
```

　あやうく大きな勘違いをしたままページを去るところでした。「これは酒の席で女性が下ネタ話をしたことを“合意”の理由にあげていると言っていいもので、言葉を失うしかない。」という記載が先にあって、それが最高裁の自判となったのかといったん思ってしまったことです。

　もう一度、記事の上の方に目を向けると「男に脅迫され、ビルの踊り場で強姦されたという事件だった。」という記載があったので、これは刑裁サイ太のツイートで最高裁の判例を読んだ千葉市の事件だったと気が付きました。その知識がなければ、気が付かなかったかもしれません。

　最高裁が原判決を破棄した場合、差し戻しと自判がありますが、2,3年前、その前年に刑事裁判で最高裁の破棄が一度もなかったとしりました。きっかけは藤井美濃加茂市長事件の控訴審逆転有罪判決で、弁護人だった郷原信郎弁護士が上告審で破棄のリスクを全く説明していなかったことです。

　上記の郷原信郎弁護士が上告審で破棄の可能性を一切説明していなかったというのも私個人の観測の範囲ですが、YouTubeに住民向けに上告審の勝訴の見込みや意義を熱心に説明していて、それを視聴しながら魔法に掛かったようにいつのまにか寝ていたということがありました。

　起きてから再び、動画を再生することはありませんでした。あまりにも馬鹿らしくて見る気にならなかったのですが、その場面は、リーガルハイというドラマで主人公の弁護士が山奥の公民館のような場所で、地域の住民に説明をしていたのと重なる非現実性がありました。

　リテラの記事も、事実を題材にしたフィクションか漫画として読めば、面白く需要もあるのかもしれないですが、自分や家族あるいは親族が、裁判の大きな負担と不当な刑事罰を受けた、と創造するとまったくどんでもない話です。

　このマスコミの風潮は、森友学園問題から始まっていると私は見ていますが、その森友学園問題の始まりも弁護士のあやしい活動があったと聞きますし、国会の証人喚問の籠池氏本人の発言にもそれを裏付けるようなものがあったと記憶しますが、その点を報道で見ることはありませんでした。

```
この判決からわかるのは、現在の裁判では驚くべきことに〈女性は強かんされそうになったら、暴行または脅迫に対して反抗するものだし反抗できる、という前提が、法のうちに確固として置かれている〉という事実だ。ここでは被害者が恐怖で声をあげることさえできなくなる追い込まれた心理状態がまったく無視されているし、痴漢被害に遭って大声で叫んでも周囲の誰も助けてもらえなかったという事例も見落とされているのだ。

　さらに、膣に傷がないことが理由のひとつにあげられてしまう点などは、〈「姦」（相手が望まない性交＝かん淫）自体は、かならずしも「強」的（forcible）なものとは限らない〉ということを裁判官が理解していない証拠だろう。脅され、さらなる暴力や死の恐怖を感じた被害者が加害者の言いなりになることは想像に容易く、〈加害者は、有形力を用いることなくやすやすと性交にいたる〉ものだということさえ最高裁には通じなかったのだ。

［source：］(3ページ目)高畑裕太事件でも…性犯罪における警察、検察、裁判所の“男目線”が被害者をさらに傷つけている！｜LITERA／リテラ https://lite-ra.com/2016/09/post-2558_3.html
```

　上記に引用した点は、説得力は感じられます。確かに当て嵌まるケースはあるのでしょう。最高裁で逆転無罪となった千葉市の事件は、被告人の他の性犯罪的な行動を含め、ずいぶん疑問のあるものでした。有罪という反対意見もあったかと思います。

　性犯罪的な行動と書きましたが、余罪として立件されたものではなかったように思います。かなり長文の判例でした。最高裁で公判が開かれるのは稀ですが、口頭弁論を経た裁判所の判断が判決、書面審理のみの判断が決定とされています。最高裁は、ほとんどは決定です。

　それでも１０年ほど前になりますか、それぐらいから死刑判決に不服がある上告審では最高裁で弁論が開かれることが出てきたと聞いています。それ以前は、弁論が開かれれば原判決の変更という話が当然のようになっていました。

　あまりまとまった記事は読んでいないので、自分の体験としての感覚になりますが、同じ頃から再審開始がかなりの割合で破棄されるようになりました。名張毒ぶどう酒事件もそうでしたし、福井女子中学生殺害事件もそうでした。開かずの扉といわれた再審の門です。

　それもころも弁護士のご都合主義、かってきままな泥棒根性の影響が大きいと私は見ていますし、それを確信として深めたのも、高畑裕太氏の強姦致傷事件であり、他に疑問の大きいのが栃木小１女児殺害事件でした。無実の可能性があるようにも思いながら、それを阻害する弁護士周波を感じます。

　弁護士周波というのは今思いついたものですが、変換候補に弁護士宗派と出てきました。この宗派というのは実際、一座と置き換えても良いと思います。茶番劇の一種です。際立つのは弁護士脳の異常性です。本当に病理学的に研究すべき対象と思います。

　弁護士脳の異常さは、宮崎の示談交渉の問題が際立っていました。１月の１７日ぐらいから2,3日続いた報道でしたが、ほとんどは毎日新聞の記事となっていました。

＜＜＜2019-03-04（月曜日）15：51＿［これまでの記述範囲の終了時刻］＜＜＜

* リテラの岡口基一裁判官に関する記事、本日２０１９年３月４日は岡口基一裁判官が国会の訴追委に呼び出しを受けた日
  :LOGBOOK:
  CLOCK: [2019-03-04 月 15:59]--[2019-03-04 月 18:31] =>  2:32
  :END:

＞＞＞2019-03-04（月曜日）15：59＿［これからの記述範囲の開始時刻］＞＞＞

［link：］ 岡口基一　訴追委 - Twitter検索 https://twitter.com/search?q=%E5%B2%A1%E5%8F%A3%E5%9F%BA%E4%B8%80%E3%80%80%E8%A8%B4%E8%BF%BD%E5%A7%94&src=typd

　一時間ほど前は「訴追委」をつけずに検索をしていたのですが、結果は余り変わらない感じです。あとで、「おすすめユーザー」から開いた弁護士と思われるアカウントのタイムラインに、情報の含まれるツイートがあって、資料の発見がありました。惑星アイコンです。

　思い出したのは「ほうたろう」という匿名弁護士アカウントのことですが、けっこう長い間見かけておらず、すっかり忘れていました。２０１５年に初めてみた頃は、アイコンを妖怪ウォッチの「コマさん」にしていましたが、しばらくは何の絵なのかさっぱりわかりませんでした。

　惑星のアイコンをよく見かけていたのも同じ頃だったような気がします。ダイオウグソクムシのアイコンのアカウントを見るようになったのも似た頃で、１１月ころが一番印象に残っています。珠洲市の海岸から釣ってきた小鯛の体内からウオノエを初めて見た頃のことです。

　ダイオウグソクムシのアイコンの弁護士と思われるアカウントは、最近もちょいちょいと見かけていますが、1,2年ほど前に、青っぽい背景の写真に変更されていました。前ほど目立っていないですが、同じダイオウグソクムシと思われる写真です。

［link：］ ブリーフ判事“厳しすぎる懲戒処分”の原因は安倍政権批判か? 森友加計でも敢然と批判ツイート｜LITERA／リテラ https://lite-ra.com/2018/10/post-4327.html

　上記のリテラの記事は２０１８年１０月２２日が配信となっています。３ページに分かれています。いちいち読むのも時間がかかりますが、見出しのタイトルを見ただけでだいたいの内容がわかるのは、こちらも助かります。

［link：］ ブリーフ判事がSNS で発信するのは司法の密室化に風穴をあけるため｜LITERA／リテラ https://lite-ra.com/2018/10/post-4327_3.html

　記事の見出しが違っていますが、同じ記事の２ページ目のようです。配信時刻も１ページ目と同じ２０１８年１０月２２日１１時００分となっています。

［link：］ 加計問題では加計学園の元監事が最高裁判事に就任していたことを指摘｜LITERA／リテラ https://lite-ra.com/2018/10/post-4327_2.html

　こちらも記事の見出しが違っていて、３ページ目かと思ったのですが、ページ下のリンクボタンで確認すると２ページ目となっていました。上記３つの記事は、次の検索結果の上位、１から３になっていて、その順位で並んでいます。

［link：］ 岡口基一裁判官　リテラ - Google 検索 https://www.google.com/search?q=%E5%B2%A1%E5%8F%A3%E5%9F%BA%E4%B8%80%E8%A3%81%E5%88%A4%E5%AE%98%E3%80%80%E3%83%AA%E3%83%86%E3%83%A9&sourceid=chrome&ie=UTF-8

　検索結果は２ページに分かれ、見出しにリテラを含むのは、上記の１番目から３番目の記事になりますが、２ページ目の最後に、もう１つありました。本文にリテラを含むので検索結果に出てきたのか、気になりますが内容の確認はしていません。

　最後のリテラをキーワードに含むリンクはTwitterのツイートでした。開いてみると、ちょっと気になる情報が岡口基一裁判官のキーワードと一緒に掲載されていました。

▶ ツイート％risa_mama117（rima）％2018/07/19 18:36％ https://twitter.com/risa_mama117/status/1019878715256332289
&twitter(1019878715256332289){theme:light}
> リテラ(7/18):大飯原発再稼働判決の裏側！運転差し止めの一審を覆した裁判所の策謀とは？一審判事の左遷、高裁判事と政権の関係…https://t.co/VvhjmOtso3
> 
> #戸倉三郎:岡口基一裁判官に厳重注意した人物… https://t.co/eBsm6xCI54  
▶

　ツイートが長いので、TwitterAPIからの取得だと全文が取得できていません。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜risa_mama117（rima） 日時：2019-03-04 16:34／2018-07-19 18:36 URL： https://twitter.com/kk_hirono/status/1102472374241255425 https://twitter.com/risa_mama117/status/1019878715256332289
&twitter(1102472374241255425){theme:light}
> リテラ(7/18):大飯原発再稼働判決の裏側！運転差し止めの一審を覆した裁判所の策謀とは？一審判事の左遷、高裁判事と政権の関係…https://t.co/VvhjmOtso3 \n   \n  #戸倉三郎:岡口基一裁判官に厳重注意した人物… https://t.co/eBsm6xCI54
◁◁◁
<hr />

　リツイートしたものを読み込んでも結果は同じでした。URLが３つ含まれているので、余計に長文のツイートに見えましたが、欠落したのは次の部分です。

#内藤正之 (link: https://twitter.com/momo4leaf/status/1016081040035606528?s=21) twitter.com/momo4leaf/stat…

　まず、戸倉三郎という人物名ですが、昨年秋の岡口基一裁判官の分限裁判のことで見かけていました。ちょっと憶えやすそうな、また、チンピラ役の多かった俳優にも似た名前ですが、羽咋市の住んでいた頃、落合洋司弁護士（東京弁護士会）のブログのコメント欄で見かけました。

［link：］ 追悼・高倉健 銀幕を共にした盟友が語る「高倉健」という人物（3）石倉三郎は役者としての気概を教えられた | アサ芸プラス https://www.asagei.com/excerpt/28944

　確認のために調べましたが、戸倉三郎ではなく「石倉三郎」でした。なんとなくイメージがあった名前だったのですが、一文字違いでかなり似ていたので、自分で納得しました。

［link：］ 石倉三郎 - Wikipedia https://ja.wikipedia.org/wiki/%E7%9F%B3%E5%80%89%E4%B8%89%E9%83%8E

　昭和の時代の任侠映画のイメージが強かったのですが、映画俳優というイメージよりはテレビドラマの出演も多かったようです。

　任侠映画と思われるものは、７作並んでいますが、昭和４５年と４６年に集中しています。新網走番外地というシリーズが３作あります。昭和から平成の初めころのレンタルビデオ店には、そういう任侠映画のビデオがいろいろ並んでいましたが、昭和４５年というのは少し意外でした。

　ツイートには２つの人物写真が並んでいます。どちらもツイートの添付画像のようですが、左手が戸倉三郎と思われます。右手が内藤正之裁判長とテロップ付きですが、そこに名古屋高裁金沢支部とあるのが気になりました。以前見覚えのある顔写真ですが、名前は見憶えがありません。

　顔写真といえば、今日のミヤネ屋の後半に、元シャネルズのミュージシャン鈴木雅之さんが出ていました。土曜日の２３時過ぎの番組でも見たのですが、今回、体型や顔立ちが被告発人としていた竹沢俊寿に似ていると思いました。

　鈴木雅之さんは、あえてそうしているのだと思いますが色黒です。被告発人だった竹沢俊寿は色白でしたが、平成２年辺りからはいつも色の濃い大きなサングラスを着用していました。糖尿病の悪化で目が見えなくなってきている、という話もありました。

　時刻は１７時０８分です。テレビはCMに入ったところですが、CMのあとは俳優の高嶋政伸さんの交通事故のニュースです。ミヤネ屋でも見ましたが、５２歳ということで少し驚きました。子供の頃からテレビで見ていたので、てっきり年上とばかり思っていたからです。

［link：］ 高島忠夫長男殺害事件 - Wikipedia https://ja.wikipedia.org/wiki/%E9%AB%98%E5%B3%B6%E5%BF%A0%E5%A4%AB%E9%95%B7%E7%94%B7%E6%AE%BA%E5%AE%B3%E4%BA%8B%E4%BB%B6

　名前の漢字を確認するためのGoogle検索だったのですが、上記のページが目に入り驚きました。幼い子どもに事件があったことは知っていたのですが、殺人事件だったとは知りませんでした。平成に入ってからテレビで知ったように思いますが、気の毒すぎる配慮が報道にあったのかと思いました。

　高嶋政伸さんといえば、数年前、ストーカーのような妻との離婚騒動がありましたが、演技ではなく真に迫った深刻さが伝わってきて考えさせられるものがありました。似た頃に、「お祭り弁護士」という２時間ドラマを昼に見ることがあり、そのギャップも大きなものでした。

　「お祭り弁護士」というのはシリーズ化されていたようで、徳島の阿波踊りと、青森のねぶた祭りを見たように思います。青森の方はまったく別の番組だったかも知れず、記憶がはっきりしなくなっています。

　そういえば、今日のミヤネ屋でもやっていましたが、数日前から元貴乃花、元若乃花兄弟が仲直りする可能性が話題となっています。どちらもテレビで見た、この兄弟が小学生の頃の４人家族の親子と、高嶋兄弟の４人家族の兄弟もどこか似たところのあるものとして、記憶に残っています。

　時刻は１７時３６分です。お米を研いでいましたが、その前に家の裏の方に行ったところ、ウグイスのような鳴き声を聞きました。例年は４月か、それに近くなってから聞いている気がします。それも午前中が多く、薄暗くなってきた時間帯というのも珍しいと思いました。

```
'05年には、長男の政宏が女優のシルビア・グラブと結婚。'15年になると、次男の政伸が14歳年下の一般女性と再婚してようやく明るい話題がもたらされたが、結婚式や披露宴は行われなかった。父母ともに、出席できる状態ではなかったからだ。

「政伸さんがもともと繊細なタイプなので、仕事への責任感から精神的に不安定になることも。両親と同居して介護しようとも考えたといいますが、自分も医者の支えを必要とする状態では難しい。高島さんと寿美さんの世話は、ヘルパーさんが見るしかなかったようですね」（前出・スポーツ紙記者）

　現在の高島家は、どのような状況なのだろうか─。

［source：］＜独占告白＞高嶋政伸が語った「壮絶介護」高島忠夫・寿美花代の今 | 週刊女性PRIME ［シュージョプライム］ | YOUのココロ刺激する https://www.jprime.jp/articles/-/12347
```

　上記の記事も同じ検索結果のページで見かけたものですが、ほとんど知らなかった話だと思います。昭和の時代は、理想的な夫婦、家族の姿としてテレビで見かけることが多かったので、いろいろと考えさせられます。

```
「政伸さんは、昨年8月に長男を授かっています。初めての子で、両親にとっては初孫となります。

　政伸さんは『メレンゲの気持ち』（日テレ系）で、最初に両親のもとに連れていったときのことを話していました。寿美さんは涙を流して喜び、忠夫さんは“この子は必ずスーパースターになる!”と太鼓判を押したそうですよ」（前出・テレビ誌ライター）

　初孫の誕生が高島ファミリーを勇気づけ、明るい家族の絆をより強くした。

［source：］＜独占告白＞高嶋政伸が語った「壮絶介護」高島忠夫・寿美花代の今 | 週刊女性PRIME ［シュージョプライム］ | YOUのココロ刺激する https://www.jprime.jp/articles/-/12347?page=4
```

　「週刊女性2018年5月29日号2018/5/15」となっています。昔は、書店に行くと同じ棚に女性誌と少年ジャップなどが一緒に並んでいたものです。益谷酒店の横にあった小さな書店で、化粧品店に週刊誌だけが置いてあるような店でした。

　店の人のことはまったく記憶にないのですが、2,3年前、９０歳以上になる健康そうなおばあさんが、その店の人だと聞くことがあって驚きました。向かいにあった奥が駄菓子屋のようになった果物店のおばさんと、その隣の玩具屋のおばさんのことは、なんとなく記憶に残っています。

　辺田の浜に住んでいた頃は、その化粧品店で漫画の週刊誌や月刊誌を買うことが多かったと思います。昭和４０年代後半の漫画になりますが、当時の漫画のことは、その店のことと一緒に思い出すことが多いです。

　女性誌というのも昭和の時代はよく開いてみる機会がありました。買って読むことはなかったですが、どこかの店に置いてあるのを手にとっていたという記憶です。男性向けの週刊誌が当時は少なかったという気もします。

　まだ辺田の浜にいた頃のなので、昭和４８年か４９年ころだと思いますが、週刊誌というのはプレイボーイと平凡パンチぐらいだと聞いたことがありました。よく遊びに行く家に置いてあったのですが、書店で見たという記憶はありません。ずいぶん時代が変わったとも思います。

　時代が変わったといえば、テレビの殺人物の２時間ドラマというのもずいぶん少なくなったのですが、昨夜、久しぶりに少し観ていました。舞台は大分県の別府温泉でした。だいぶん前からある温泉女将と刑事の夫婦のシリーズ物のようです。

```
『お祭り弁護士・澤田吾朗』（おまつりべんこし・さわだごろう）は、2000年から2004年までテレビ朝日系「土曜ワイド劇場」で放送されたテレビドラマシリーズ。全4回。主演は高嶋政伸。

弁護士の吾朗が訪れた祭りで起こる、殺人事件の解決に奮闘する姿を描く。

［source：］お祭り弁護士・澤田吾朗 - Wikipedia https://ja.wikipedia.org/wiki/%E3%81%8A%E7%A5%AD%E3%82%8A%E5%BC%81%E8%AD%B7%E5%A3%AB%E3%83%BB%E6%BE%A4%E7%94%B0%E5%90%BE%E6%9C%97
```

　第3作「青森ねぶた祭〜徳島阿波おどり 日本縦断二大祭 1600kmを結ぶ連続殺人！」（2002年）、が私のみたものであったようですが、青森と徳島が一緒になっていたことは記憶にありませんでした。昼にみたので、再放送のはずです。

　本当にお祭り弁護士というタイトル名だったのかと思ったぐらい、変わったドラマでしたが、澤田吾朗という名前は記憶になく、役柄のその名前と演じた高嶋政伸という名前とイメージが一致しません。

　同じ頃、高嶋政伸が主演で、東京駅の忘れ物係の２時間ドラマがありました。シリーズ化されていたようで、２作は観たように思います。主人公の駅員は、ほのぼの感がありながら、幼い頃に駅に置き去りにされた、忘れ物にされていたのが印象的なドラマでした。

```
『東京駅お忘れ物預り所』（とうきょうえきおわすれものあずかりしょ）は、2007年から2014年までテレビ朝日系「土曜ワイド劇場」で放送されたテレビドラマシリーズ。全7回。主演は高嶋政伸。

東京駅構内の遺失物預り所を舞台に、ひとつの遺失物にまつわる殺人事件の謎を解く、職員の活躍を描く。

実在の東京駅お忘れ物承り所は、東京駅1階日本橋口改札外に所在する。

［source：］東京駅お忘れ物預り所 - Wikipedia https://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E9%A7%85%E3%81%8A%E5%BF%98%E3%82%8C%E7%89%A9%E9%A0%90%E3%82%8A%E6%89%80
```

```
望月幸平
演 - 高嶋政伸（幼少期：鳥居颯［1］〈第6作・第7作〉）
職員。嶋田家の2階に間借りしている。
仕事熱心からか、よく持ち場を離れてお客様の「忘れ物」を探しにフラフラと出掛けてしまう悪いクセがある。実は彼自身が「忘れ物」であり、幼い頃ある駅に母親に置き去りにされたという経験を持つが故の行動であり、忘れ物（例えそれが犯人の遺留品であろうが）は持ち場以外の場所であろうが探し出して回収して持ち主に返さないと気が済まない。

［source：］東京駅お忘れ物預り所 - Wikipedia https://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E9%A7%85%E3%81%8A%E5%BF%98%E3%82%8C%E7%89%A9%E9%A0%90%E3%82%8A%E6%89%80
```

　ずいぶん前に終了したように思っていましたが、２０１４年の時点では、まだ「土曜ワイド劇場」が続いていたようです。エンディングに印象的な曲が流れていたことも思い出です。「さらば弁護士泥棒鉄道」という言葉が浮かんできました。

＜＜＜2019-03-04（月曜日）18：31＿［これまでの記述範囲の終了時刻］＜＜＜


