#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "告訴の事実／平成4年／2月／２４トンのミールを積んだ九州福岡市への運行"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-11-28 10:56:39 +0900
FILE_NAME: 2018-11-28-105639_２４トンのミールを積んだ九州福岡市への運行.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  被告発人安田繁克 被告発人梅野博之 中西運輸商
記事タイトル名の文字数：35　保存ファイル名の文字数：43

#contents

* 高千穂６人殺害事件をきっかけに、掘り下げる平成４年２月の九州福岡への運行

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-11-28 11:20／2018-11-28 11:16 URL： https://twitter.com/kk_hirono/status/1067604101876219904 https://twitter.com/s_hirono/status/1067603210288848897
&twitter(1067604101876219904){theme:light}
> 2018-11-26_171808＿テレビの画面・every・速報　宮崎・高千穂町の民家　６人の遺体発見　刃物のような傷.jpg https://t.co/J7eQFD6hoU
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-11-28 11:20／2018-11-28 11:17 URL： https://twitter.com/kk_hirono/status/1067604115344117760 https://twitter.com/s_hirono/status/1067603240970203136
&twitter(1067604115344117760){theme:light}
> 2018-11-26_171826＿テレビの画面・every・速報　宮崎・高千穂町の民家　６人の遺体発見　刃物のような傷.jpg https://t.co/5oEc0Pe2Gz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-11-28 11:20／2018-11-28 11:17 URL： https://twitter.com/kk_hirono/status/1067604139746578433 https://twitter.com/s_hirono/status/1067603271659872257
&twitter(1067604139746578433){theme:light}
> 2018-11-26_171838＿テレビの画面・every・速報　宮崎・高千穂町の民家　６人の遺体発見　刃物のような傷.jpg https://t.co/65IlL1PyMo
◁◁◁
<hr />

　上記のテレビ画面の撮影ファイルが、最初の事件の報道を知った時だったと思います。正確な日時がわかることは、記憶の整理にもなり、確認のために調べ回るという作業も免れうるので、正確で効率的な作業だと最近になって意識するようになりました。

　インターネット上でのニュース報道は、次のようなものとなっております。

```
宮崎県高千穂町の農業飯干（いいほし）保生さん（７２）方で家族ら男女６人の遺体が見つかった事件で、県警は２７日、町内の五ケ瀬川で見つかった男性遺体の身元について、事件後に行方が分からなくなっていた飯干さんの次男昌大さん（４２）と確認したと発表した。また、飯干さん方で凶器とみられる血の付いたなたが発見されていたことが捜査関係者への取材で判明。現場からは血の足跡も見つかっており、県警は犯人のものとみて調べている。

　昌大さんの遺体は２６日午後４時ごろ、飯干さん方から約２・５キロ離れた神都高千穂大橋下の五ケ瀬川で見つかり、県警が２７日朝、クレーンを使って引き揚げた。昌大さんは作業服姿で片方の靴が脱げた状態だったという。遺書はなかった。橋の高さは約１１５メートルあり、自殺の可能性が高いとみられる。

　捜査関係者によると、昌大さん夫婦は何らかのトラブルを抱えていたという。飯干さん一家とともに遺体で発見された同県五ケ瀬町の農業松岡史晃さん（４４）はトラブルを仲裁するため２５日夜に飯干さん方を訪れたとの情報もある。県警は昌大さんが６人の死亡について何らかの事情を知っていたとみて調べている。

［source：］高千穂６人殺害、被害者宅でなた押収　川の遺体は次男　夫婦間トラブルか｜【西日本新聞】 https://www.nishinippon.co.jp/nnp/national/article/468904/
```

　主にテレビで報道をみているのですが、当初、建設作業員のようにされていた自殺した次男の職業が、今日になってトラック運転手とされていました。仲裁に入って殺害されたという知人も以前はトラック運転手で、同僚という関係だったようです。

　高千穂は日本神話で有名ですが、これまでテレビで映像を見たことはほとんどなかったように思います。Twitterの検索を見ていると、最近、テレビの番組で取り上げられていたという話もありましたが、同じ九州の湯布院などは見ていたものの、高千穂は見ていなかったように思います。

　名所として高千穂峡も事件の報道で繰り返し出てきましたが、高千穂峡というのも知っていたのかとなると、はっきり思い出せるような記憶がありません。個人的には印象的な景色として広島県の帝釈峡があったので、高千穂峡を見ていれば関心を高め、調べていたような気もします。

　被疑者の可能性の高い人物が事件の直後に自殺したこと、それで真相の解明が絶望的になったことでも、昨年３月の能登高校の女子高生殺害事件のことを思い出し、共通性があるようにも考えました。

　時刻は１１時５１分になります。テレビの時計は１１時４８分ころ、チャンネルは石川テレビですが、能美市の海岸に埋めたという殺人事件の裁判員裁判の初公判のニュースがあり、それに被疑者と思われる人物の顔写真が大きく掲載されていました。

　すっかり忘れていた石川県内の殺人事件ですが、けっこう長い間、県内ニュースで報道がありました。被害者は加賀市内の男性だったと思いますが、その被害者の顔写真は繰り返し出ているのに、被疑者の顔写真が全く出ていなかったので、人物像をうかがうこともなく気になっていた事件ではありました。

　今回の裁判員裁判のニュースでは、弁護側の主張として、被害者に借金の返済を迫られ精神的に追い詰められた事件だったので情状酌量を求める、というような初めて知る話も出ていました。

　たぶん全国ニュースになることはなかったと思います。石川県内ニュースは短い時間で独自取材のようなものもほとんどないと思いますが、なにか遺体を埋める穴を誰かに指示をして掘らせたというような話があったような気がします。記憶が曖昧ですが。

　石川県の海岸線というのは、福井県の県境付近に一部、岩場や断崖があるようですが、長い砂浜が羽咋市の先の旧富来町の辺りまで続いているはずです。詳しくはわかりませんが、志賀町原発の辺りまでかと思います。

　金沢港や金石港は川の河口のようになっていますし、漁港というのは福井県との県境に近い橋立港、反対側の能登の方は柴垣港まで港らしい港はないように思います。ほとんどが砂浜の海岸線で、宝達志水町から羽咋市の辺りは千里浜になります。

　この橋立港についても、書いておきたいと予定していたことがあります。千里浜のはずれの方についても書いておきたいことがあります。裁判の資料には書いてきたことです。

　高千穂の殺人事件ですが、謎が大きいようです。Twitterでは神話の里であることから不思議な事件であるという見方も強かったようですが、これまでの報道では、夫婦げんかのトラブルとされ、ネットでは妻の不倫という話があったものの、午前中のテレビでは女性問題という話が出ていました。

　女性問題で父母、妻、子供２人という家族５人と仲裁の知人を殺害し、直後に自殺したというのは、これまでの事件報道の経験則からも理解を超えたものですが、同時に事実を説明し、記録するという必要性も強く感じました。

　Twitterで「高千穂」というキーワードで検索をしていると、かなりの数、近隣在住と思われるアカウントのツイートがありました。

　私自身、高千穂には一度行ったことがあるのですが、国道を通過したのは夜のことだったので、どういう町だったのかという印象も余り残ってはいません。ただ他の町とは異なるような雰囲気は感じていて、言葉にはしづらいですが、それは強く印象に残っています。

* 金沢市場輸送での、高千穂を通過した宮崎県延岡市への運行

　この運行については前に書いていると思います。高千穂に向かう分かれ道の入り口と記憶にあるのですが、左右に見たこともない大きな木がありました。真っ直ぐな気だったので杉の木だと思います。その先も高千穂の町に出る間の山道は、杉の木が多かったように思います。神秘的な体験でした。

　Googleのストリートビューで、その分かれ道の場所を捜したこともあったのですが、それらしい場所は見つかりませんでした。私の記憶では、緩やかな左カープから、右手に入る道があって、そこに高千穂への矢印が出ていたという状況でした。

　改めてGoogleマップの航空写真やストリートビューを見ていたのですが、それらしい場所はやはり見当たりません。暗くはなっていましたが、夕方の割合早い時間に、高千穂への分岐点に差し掛かったような記憶があります。

　九州自動車道の熊本県内に入った頃は、まだ夕方の明るい時間であったような記憶もかすかに残っています。その辺りで目的地の延岡市への地図を見たようにも思うのですが、ちょうど高千穂を通過する国道が最短の経路だとわかりました。

　同じ頃に似たような運行があって、そちらの方が少し鮮明な記憶として残っているのですが、朝に富山県の氷見港から鮮魚のシイラを積んで出発し、目的地の卸先が福岡市内と熊本市内の市場でした。

　福岡の魚市場というのは長浜になります。定期便もあって月に２回以上は鮮魚を積みに行っていた魚市場でしたが、魚を持っていったのは、そのシイラの時と、珠洲市の蛸島港からも正月にイワシを運んだように記憶にあるのですが、２，３回のことであったように思います。

　福岡の魚市場で荷降ろしをした状況は記憶に残っていないのですが、そのあと熊本の市場に向かうのに福岡の都市高速に乗った辺りの場面は１枚の写真のように記憶に残っており、夕方のまだ明るい時間であったように思います。

　夏場や冬場で日没の時間は大きく異なりますが、季節のことは覚えていないものの雪を気にする時期ではなかったように思います。

　なお、福岡市内には青果市場が別にあると聞いていましたが、そちらは一度も行く機会がなく、どの辺りにあるのかもわかりませんでした。北九州市の青果市場からは青果物を運んだことがあり、前に書いたと思いますが、青森県の弘前市からも一度リンゴを運びました。

　熊本市の市場というのもどのあたりにあったのか記憶にないですが、熊本市では福岡の方から来て、手前の方に植木という大きな市場があって、そこには何度か青果物を積みに行ったことがありました。別の出荷場からスイカを積むこともありました。

　ほとんどの場合、市場の建物は青果と鮮魚が一緒になっていたと思います。中には青果物だけ取り扱っているうような市場も都内にはなりましたが、漁港にある魚市場は、また別の市場になるかと思います。

　金沢市場輸送は、名前も市場とありますが、会社も金沢中央卸売市場に近く、鮮魚、青果と市場関係の仕事が中心でした。ただ、石川県内や北陸は農産物、鮮魚の出荷量も多くはなかったので、鮮魚は定期便として福岡や宮城県の石巻、塩釜から持ってくる仕事がほとんどでした。

　大型車で運ぶような鮮魚は、６月ころの金沢港でのスルメイカの仕事ぐらいでしたが、それも一月はないぐらいの期間であったように思います。例外もありましたが、ほとんどは４ｔ車での鮮魚の輸送で、それも仲買の業者が白ナンバーの自社便を使うという形態でした。

　その代表格が新幸とも呼ばれた新田商店でした。七塚の会社だと聞いていました。現在は「かほく市」となっていますが、以前は河北郡の一部でした。国道からはずれているので、範囲もよくわかっていなかったのですが、被告発人松平日出男がその七塚の出身だと聞いていました。

　港はないとも聞きますが、北前船の歴史があるとも聞いたことがあります。ケンミンショーのテレビ番組でも紹介されていた「とり野菜みそ」がその辺りの発祥のようです。全国放送で紹介されるようになってからずいぶん値段が上がったような印象もありますが、スーパーではよく見かけます。

　前に書いたことがあるように思いますが、私が初めて「とり野菜みそ」を食べたのは、石川県立水産高校の相撲部の合宿の夜の食事に参加した時のことでした。能都中学校の中学生のときでしたが、それまで口にした味ではなかったので強く印象に残りました。

　石川県でも橋立港、美川港、金石港、大野、それと現在は輪島市となっていますが門前町の黒島に北前船の歴史が色濃く残っているようです。富山湾の宇出津や七尾市も寄港地となってはいたようですが、北前船の歴史というのは余り見聞きすることがありません。

　最近になって富山県の氷見市の辺りも能登半島になるとはっきり知ったのですが、その氷見市と高岡市の間には伏木港があって、たぶん高岡市になるのだと思っていますが、伏木港は北前船の重要な拠点であったと聞きます。

[link:] » 伏木港 - Google マップ https://t.co/5usuN4E0qT

　Googleマップで確認したところ小矢部川の河口になるようです。富山市側には庄川の河口もあって、中洲のような地形になっているようにも見えます。庄川は五箇山の近くの山の川として有名なイメージでしたが、庄川という川の名前で海にそそいでいるというのは初めて知りました。

　小矢部川も名前だけは見聞きしていたというか、北陸自動車道のサービスエリアの名前になっていたように思います。その辺りには神通川という大きな川があって、小学校の社会科の授業でも習ったような覚えがあります。なんとなくでしたが、山間部の庄川なども支流のように思っていました。

　Googleマップを見ていると神通川は富山市内を流れているように見えます。高岡市の近くというイメージがあったのですが、高岡市の海の周辺が工業地帯のようになっていて、それが公害の発生源になっていたようなイメージがありました。

　昭和４０年代になると思いますが、テレビでイタイイタイ病のニュースを見て、そこに神通川があったように記憶していました。そういえば、前にイタイイタイ病について調べたとき、岐阜県の神岡町のことが出てきたように思い出しました。

　金沢市場輸送での行き荷のおそらく８割ぐらいは富山県内からの荷物でした。県外から運んでくる荷物の卸先も富山県内が少なくなかったので、富山県内のあちこちには行っていたのですが、地図というのはほとんど見ずに仕事をしていたように思います。

　だいたいは人の説明や手書きの地図で向かっていたように思います。かなり土地勘のある場所でもGoogleマップを見ているとかえってわかりづらいと感じることはあります。３０年ほど前とは道路の数が増えて複雑化しているという事情も大きいのかもしれません。

　イタイイタイ病について調べたのも、高島章弁護士（新潟県弁護士会）が弁護団長をしている新潟水俣病訴訟がきっかけでした。今は水俣病について知っている人も少なく、水俣が熊本県の鹿児島県に近い場所と知っている人は、さらに少ないように思います。

　新潟県も信濃川と阿倍野川であったか記憶ははっきりしませんが、地理で日本を代表するような川があると社会科の授業で習っていましたし、テストでも必ず出てきそうな問題だったと思います。

　長距離トラック運転手の仕事では、新潟県内もあちこち行っていました。近年、テレビで三条市や燕市の辺りで金属加工のような産業があり、世界的に高度な技術が評価されているとしりましたが、富山県内とは異なり新潟県内では大きな工場というのはほとんど見たことがありませんでした。

　新潟市内は大きな市街地でしたが、周辺は水田が広がり、その先は山沿いの山間部ということで、公害とは無縁というイメージだったのが、新潟水俣病ということになり、なぜ熊本県の地名がそのまま使われているのかも謎でした。

　私が物心ついてから、はじめに裁判というのもを知ったのも公害問題だったように思います。水俣病やイタイイタイ病の他、四日市ぜんそくがありましたが、いずれも昭和４０年代に集中していたように思います。

　これまでに何度か書いたことがあると思いますが、私が昭和５０年４月になるまで住んでいた辺田の浜は、富山湾の海沿いで、なぜか石川テレビの映りが悪く、富山放送と北日本テレビを見ることが多かったと思います。

　他にMRO北陸放送もあったと思いますが、金沢テレビや北陸朝日放送はまだない時代でもありました。当時はテレビの本体とは別にチューナーのような機器があって、つまみを回してチャンネルを合わせた時代でした。

　富山県内にある宇奈月温泉や金太郎温泉のCMをよく見ていたという記憶がありますが、今考えると県内ニュースも富山県内のものを見ることが多かったのかもしれません。

　昭和４０年代と昭和５０年代ではテレビの内容もだいぶん違っていたと思います。昭和４０年台はまだ白黒テレビが主流だったような気もします。番組の数も少なかったと思いますが、娯楽が少ない時代でテレビの存在感や影響は大きかったと思います。

　今はテレビの番組を見ていて、特定の企業の影響を感じることはないと思いますが、昭和の時代は、大企業がまる抱えをするようなイメージの番組がいくつかあったように思います。代表的なのが水戸黄門と松下電器でしたが、他にもロート製薬、日立など特定の番組に強く結びついたCMがありました。

　現地に着いてから初めて知ったように思うのですが、高千穂を通過して到着した目的地の宮崎県延岡市は、他にないほど特定の企業との結びつき、一体感を強く感じる土地でした。その企業というのは旭化成だったと思います。

　最近は旭化成の社名もCMも見かけていないように思うのですが、昭和の時代は番組を丸抱えするような大きなスポンサーのCMの企業だったように憶えています。いまでも旭化成が何を生産している会社なのかはよくわかっていません。

　同じく、最近はCMでも見かけなくなった企業としてYKK吉田工業がありますが、テレビのCMでよく見かけていた当時は、アルミサッシで世界一の会社だと聞いていました。初めにその大きな工場に行ったのは、昭和５８年の１２月頃のことで、ダクトの仕事をしていたときのことでした。

　YKK吉田工業の大きな工場は、富山県黒部市だったと思います。富山市から新潟に向かうと滑川市、魚津市とあってその次が黒部市でした。富山県でも高岡市とは富山市をはさんで逆方向の場所になります。

　高岡市からさらに石川県に近いのが小矢部市ですが、高岡市と小矢部市の周辺には、福光町や福野町などを含め、三協アルミ、立山アルミ、新日軽というアルミサッシの工場が点在し、それが金沢市場輸送で多い行き荷の仕事でした。

　回数は少なかったですが黒部の吉田工業のアルミサッシを積みに行ったこともありました。１つの工場としては吉田工業の黒部の工場が最も大きかったと思います。工場は大きかったですが、地域との一体感のようなものは余り感じませんでした。

　大きな工場といえば、高岡市内だったと思いますが、中越パルプの工場がありました。全国各地の大きな工場や倉庫に行くことも長距離トラック運転手の仕事柄ありましたが、中越パルプの敷地は他と比較してもとりわけ大きかったように思います。

　記憶が薄れていますが、中越パルプの仕事をしたのは３，４回だったように思います。平成４年の２月、３月中だったとも思います。たぶん全部が関東への運行で、埼玉県内の２か所が現在思い出せます。たぶん、それも七尾市の丸一運輸の請負だったように思うのですが、はっきりした記憶はありません。

　丸一運輸の仕事としてはっきり記憶にあるのは、行き荷として、七尾市の能登木材と林ベニア、帰り荷の仕事として和歌山県のかつらぎ農協のみかんとイヨカン、石灰の荷物で栃木県の葛生町と岐阜県の大垣市からの仕事がありました。

```
創業者の野口遵が、1906年に鹿児島県伊佐市（いわゆる曽木の滝）に発電事業をおこなう「曽木電気」を設立する。同社の水力発電の余剰電力を利用して、1907年に熊本県水俣市に「日本カーバイド商会」を設立。後に合併して、「日本窒素肥料」（現・チッソ（発祥は水俣市））となる。やがて1922年に宮崎県延岡市で、カザレー式アンモニア合成工場と滋賀県に設立した再生繊維レーヨン製造会社である旭絹織株式会社を設立し、合成アンモニアの製造を開始する。その後1923年に日本窒素肥料と旭絹織と合併（「日本窒素肥料・延岡工場」。旭化成としての発祥の地は延岡市）するがその後分離独立する。同社は旧財閥「日窒コンツェルン」の一員であった。

［source：］旭化成 - Wikipedia https://ja.wikipedia.org/wiki/%E6%97%AD%E5%8C%96%E6%88%90
```

　今回、旭化成について調べたところ熊本県水俣市が出てきました。滋賀県とも関わりが深いようですが、これは初めて知りました。しっかり確認はしていませんが、滋賀県はクボタというイメージはあります。

```
社名の由来は、「旭」は、滋賀県大津市に建設されたレーヨン繊維工場の近くにあった琵琶湖畔の義仲寺（木曽義仲＝旭将軍）から、「化成」は易経にある「よりよい方向 へ生成、変化、発展する」からきている［7］。

フジテレビにて長年に渡り、「スター千一夜」や「なるほど!ザ・ワールド」、「メトロポリタンジャーニー」など一連の番組の単独スポンサーを、開局した年の1959年から1997年の放送終了まで一貫して、旭化成と旭化成グループ各社として、のべ40年間近く行っていたことでも知られる。

［source：］旭化成 - Wikipedia https://ja.wikipedia.org/wiki/%E6%97%AD%E5%8C%96%E6%88%90
```

　「メトロポリタンジャーニー」という番組は全く記憶にないのですが、「スター千一夜」と「なるほど!ザ・ワールド」の単独スポンサーというのは意外でした。一月ほど前にも「スター千一夜」は、関口宏ことで調べたり、取り上げていると思います。

　社名の由来が滋賀県大津市というのも意外で、九州の宮崎県とは地理的にもずいぶんと離れています。「木曽義仲＝旭将軍」とありますが、木曽義仲と巴御前は、石川県の津幡町と、県境で隣接した富山県小矢部市がゆかりの地として、NHK大河ドラマの誘致をしてきたという話は聞いています。

　火牛の計や倶利伽羅峠の戦いです。数ヶ月前、テレビで津幡町のゆるキャラが出てきて、そのあと色々とネットで調べていたのですが、それがずっと前から気になっていた片山津温泉の近くの首洗池の歴史がわかりました。前妻の実家の近くだったので通りかかることも多かった場所です。

［link：］ 宮崎県延岡市にとって旭化成とは？ https://machi.to/bbs/read.cgi/kyusyu/1048617439/

　ネットで「旭化成　延岡市」と検索したところ、それらしい情報として見つかったのは上記のページだけでした。２ｃｈスタイルの掲示板です。スレッドの頭には「旭化成の工場のせいで川は汚れているし、空気も悪い。」と書いてありますが、２００３年３月２６日の投稿なので随分前のことです。

　テレビの時計をみると１６時５７分でしたが、家の中はほとんど夜のような暗さになっています。さきほどテレビのeveryでは、日産のゴーン容疑者がアメリカの弁護士を選任したというニュースがありました。何かでNo1に選ばれた弁護士ということです。これは日本の弁護士らも活気づきそうです。

　延岡市まで運んだ荷物は、金沢の展示会の仕事でした。たぶんトナミ航空の仕事だと思います。前にもご説明を書いたと思いますが、他に日本通運の増泉支店からの展示会の仕事もありましたが、ごく少数だったように思います。トナミ航空の仕事は「うまいもの会」とも呼ばれていたと思います。

　加賀能登の物産展ということで、昭和５９年にも始まっていた仕事でしたが、当初は荷物も回数も多くはなかったように思います。荷物も金沢中央卸売市場前にあった金沢市場輸送の事務所前にトラックの保冷車の扉を開き、業者がワゴン車などで持ってくる荷物を待ち受けていました。

　いつ頃か憶えていませんが、仕事の回数と荷物の量が増えた頃になると、金沢市問屋町のトナミ航空のホーム作業としてで荷物を積み込むようになっていました。問屋町でも諸江町に近い場所で、珍しいほど小さなホーム作業の現場でした。展示会の仕事以外で行くことはなかったと思います。

　延岡市内の百貨店で、大きな系列の支店ではなかったように思います。展示会の仕事でよくあったのは、三越、高島屋、ソゴウという大手百貨店の支店でした。他にその地域に根ざした老舗百貨店と思われるものもありました。秋田市や青森市もそうであったように思います。

　延岡市の百貨店もその地域の百貨店だったように思いますが、トヨタ自動車の企業城下町として有名な愛知県豊田市のデパートにも展示会の荷物を運んだことがありました。余り大きなデパートではなく、規模は延岡市のデパートに似ていたような印象が残っています。

　いずれも同じ頃だったようにも思うのですが、同じ宮崎県の宮崎市のデパートにも展示会の仕事で行きました。そちらは引き上げの仕事であったように思います。引き上げの仕事は、デパートの閉店後、夜の遅い時間に積み込みを始めることが多かったと思います。

　金沢市場輸送で宮崎県内の仕事として思い出せるのは３つだけです。行き荷としての延岡市の展示会の仕事、帰り荷としての宮崎市からの展示会の引き上げの仕事、それと、これも前に書いていると思いますが、宮崎県都城市から特殊車両のタイヤを神戸まで運んだ仕事でした。

　時刻は２１時３８分です。夕方は宇出津新港に買い物に行っていました。出掛ける前にテレビで群馬県の伊香保温泉を見て、２０時からは姫路城の特集の番組を見て、またそれぞれ書いておきたいことが出てきたのですが、群馬県の件は高千穂の事件と共通点があります。

　姫路のことはまだ書いたことがないかもしれません。さほど重要性がないとも考えていたからですが、裁判の資料ではそれも詳細に書いているはずです。細かい事実や人間関係でも全体で見れば、いろいろとつながりがあって、それが謎をとく手がかりにもなりうると考えています。

　宮崎の運行は３回だけだったと思いますが、もしかすると宮崎のデパートには２回行っていたかもしれません。宮崎市内の中心部だったと思いますが、県庁所在地の中心部とは思えず、観光地の土産物店などの集まる場所のような印象がありました。それも夜だったので雰囲気も違ったかもしれません。

　夜にデパートの仕事に行ったのは福井市内もそうでしたが、福井市内の方がずいぶん大きな街に見えました。福井市も仕事ではよく行っていましたが、駅に近いと思われる中心部というのは他に行くことがありませんでした。

　なお、福井市のデパートのようなところに夜に仕事に行ったのは展示会の仕事ではなかったように思います。なにか家具や調度品に近いものを搬入したように思いますが、記憶が薄れ、ぼんやりとしか思い出せません。

　Googleマップで調べれば早いとは思いますが、私の記憶にある宮崎市はとてもこじんまりしたところでした。大きな建物が見当たらなかったのは長野市や鳥取市、山口市にも共通していましたが、宮崎市の場合は隣県の鹿児島市があまりに大きかったので、その対称も気になるものでした。

```
宮崎市（みやざきし）は、宮崎県の南東部にある都市で同県の県庁所在地である。

フェニックス・シーガイア・リゾート、青島、プロ野球・プロサッカーキャンプといった数多くの観光資源を持つ観光都市であり、九州・沖縄地方では長崎市に次いで7番目に人口が多い。1998年（平成10年）から中核市に指定されている。

［source：］宮崎市 - Wikipedia https://ja.wikipedia.org/wiki/%E5%AE%AE%E5%B4%8E%E5%B8%82
```

　調べて驚いたのですが、宮崎市の人口は４０万人弱のようです。金沢市も現在は４５万人と聞くことがありますが、平成５年当時の辞林２１では、４２万人台であったと記憶にあります。ページにある写真を見ても、大きなホテルのような建物が並んでいます。

　宮崎県は昭和の時代、新婚旅行先として国内一だったとも聞いたことがあるので、観光客が多いのは頷けますが、自分が過去に行った時の記憶とはかけ離れた印象があります。宮崎市内は国道１０号線が通っているので、展示会とは別に鹿児島方面から通過したような記憶もあります。

　私の記憶では、夜に宮崎市内のデパートに仕事に行った時は一人で、展示会の仕事に来ていた人と会話をした記憶が残っています。他に展示会の仕事に来ていた人と一緒に仕事をしたり、会話をしたという機会は余りなかったので、特に印象に残っていました。

　それとは別に、輪島崎のOTと大型車２台で、大分県内の国道１０号線を、宮崎方面から北九州市に向かって走行していた記憶があります。夕方頃に、国道の広い道を走っていた場面が記憶にあります。明るい時間でした。

　そのあと、同じ国道１０号線で、大分県から福岡県に入る辺りを走行していましたが、急な坂ではなかったものの民家がずっと見えないような長い峠道で、それも印象に残っていますが、すっかり暗くなった夜だったと記憶にあります。

　夜の９時から１０時ぐらいに展示会の引き上げの荷物を積んで宮崎市内を出発していたとすると、その翌日の夕方に大分県内を走行していたとは、間の時間がありすぎて、長く仮眠をしていたとしてもまず考えられないことです。

　大分県内というのも大分市と別府市で、４，５回行ったことがありました。１度は、大分市内でも別府市内でもなかったと思いますが、中西運輸商の大型保冷車で、貝を積みに行きました。堤防がそのまま養殖場のようになっていて、その堤防にトラックを横付けして荷物を積み込みました。

　別府市に行ったのは引っ越しの仕事でした。夜の割と早い時間に現地に到着していました。大分県内から福岡市に向かったのも２回あったように記憶しています。一度は湯布院で雲海を見ました。その時は雲海を知らなかったように思うのですが、たまたま見かけて強く印象に残りました。

　今回の高千穂の事件では、地図で高千穂が大分県との県境に近いことを知って意外に感じました。高千穂の場所は前にもGoogleマップで見ていたのですが、どちらかといえば、鹿児島県に近いのではないかと考えていたぐらいでした。

　初めに鹿児島に行った頃も、熊本県の人吉市から宮崎県のえびの市に出てる道を通っていました。えびの市の手前は大きな山の上から下を見下ろすような景色で、天空から外界を見下ろすような気分になりました。北海道の日勝峠も走りましたが、他に似た風景は見ることがなかったように思います。

　鹿児島県には１０回近く行ったかもしれません。中西運輸商の４t車で加世田市に行きました。Googleマップをみると現在は南さつま市となっているのかと思われます。東シナ海に近いので、水俣市から出水市、阿久根市、串木野市という国道３号線のルートで向かいました。

　鹿児島へは富山のアルミサッシの仕事で行ったのが一番多かったと思います。３，４回行ったようにも思いますが、２，３回かもしれません。国分市の近くで加治木町に卸先の配送センターのようなものがありました。宮崎県から来ると、鹿児島県では入り口に近い辺りでした。

　他に、福岡の魚市場から臨時で頼まれた仕事で、木箱のサバを満載にして鹿児島市の市場に行ったことがありました。同じ市場だったのかはっきりしませんが、熊本県の八代市で荷降ろししたあとに向かって、鹿児島の市場から白菜を積んで、長野県の市場に向かったこともありました。

　白菜を積んだのは八代市で荷降ろしをした翌日だったと思いますが、途中どこで時間をつぶしたのか記憶にありません。夜のうちに鹿児島市内に着くようなことはなかったと思いますし、夜の鹿児島市内にいたという記憶もありません。

　鹿児島市内は大きな街で、道幅も広く、道路沿いの風景も下関市内に似ていましたが、市場まではその市街地を随分走ったような記憶があります。道幅などは、京都市内の市場に向かう道にも似ていましたが、より賑やかなようにも感じました。

* 鹿児島市の市場から白菜を積んで長野県に向かった運行と、イワシの運搬の現場監督のような仕事をしていた元石川県警機動隊員というKKさん。

　だいぶん前にはTwitterでも書いていると思うのですが、鹿児島市内の市場から積み込んだ白菜は、長野県内で夜中に荷降ろしをしました。１つは長野市の市場だったと思いますが、２箇所卸だったように思います。はっきりとは思い出せないですが、もう一箇所は上田市とも考えられます。

　夜中に荷降ろしを終えたあと、碓氷バイパスを下りた先、高崎市の手前の国道沿いの大きな駐車場の食堂で食事をした後、仮眠をしました。起きた後、午前中に前橋市内の国道５０号線の信号待ちで、KKさんに声を掛けられました。

　KKさんは、もともと金沢市場輸送の大型運転手でしたが、最初からローカルの仕事をしていたようです。それでもイワシの時期になると、ミールの運搬など長距離の仕事もやっていました。ダンベもやっていたと思います。

　平成元年１２月頃からのイワシの仕事では、市場急配センターの社員として現場監督のような立場で仕事をしていました。税金対策とも聞きましたが、市場急配センターが仕事を出して、金沢市場輸送が運搬を請け負うというかたちにしていたようです。

　真面目そうで嘘話をするような人物には見えなかったのですが、最高裁判事の息子だと話していました。その最高裁判事の父親が大学時代の竹沢俊寿会長の友人で、社会勉強ということで金沢市場輸送の仕事を始めたと話していました。

　竹沢俊寿会長の方も、それを認めるような発言をしていましたが、たぶんそのずっと前から、折に触れ、東京の中央大学の法学部で空手部にいたなどと、自慢話をしていました。中央大学は私立大学ですが、何かの資料で、私立大学出身の最高裁判事はいなかったという情報を見たことがありました。

　もっともその当時は、最高裁についてほとんど知識がなく全国で１５人しかいない判事で構成されていることは全く知らずにいました。彼はまた、元石川県警の機動隊員で白バイにも乗り、加賀市の派出所で勤務していたとも話していました。

　山代温泉の派出所と聞いたようにも思うのですが、山代温泉は国道８号線から離れていて、その入り口の辺りの国道８号線沿いに派出所があって、彼の話を聞きながら、その国道沿いの派出所のことだと思っていたのですが、山代温泉とは別の派出所だったのかもしれません。

[link:] » 派出所 - Google マップ https://t.co/SujsQIlOaL \n 　石川県加賀市山代温泉の付近

　確認のため調べたのですが、国道８号線沿いにそれらしい派出所は見当たりませんでした。

[link:] » 立石自動車 株式会社 - Google マップ https://t.co/Tp2AGztrYO

　立石自動車の近くに、同じ国道８号線沿いに派出所があったとも思ったので調べてみました。立石自動車に記憶の自信はなかったのですが、だいたいの場所はあっており、間違いはなさそうです。

　Googleマップを見ると、立石自動車の少し先に西島という交差点がありますが、金沢方面から来ると、以前はその交差点を左折して山代温泉からその先の山中温泉方面に向かっていたように思います。

　以前は、と断りをつけたのは、平成１１年当時、山中温泉の現場に向かううときは、粟津温泉の辺りから勅使町というところを通って山代温泉に出ていました。途中に小松市内の国道８号線を通らないで済むバイパスが出来ていたようにも思いますが、細かくは思い出せません。

　Googleマップで見ると県道１１号線というのがその道のようです。地図をよくみると、以前の小松市内の国道８号線が現在は国道３０５号線となっているようです。小松駅と小松警察署の位置で確認が出来ました。以前は、大型トラックの交通量が多く、片側２車線でも走りづらい道路でした。

　この勅使町や粟津温泉についても、ずいぶん前から書いておくことを予定していることがあります。

* 群馬県前橋市内の国道50号線の信号待ちで声を掛けられたKKさんと、その先の茨城県古河市の山三青果

　前橋市内の国道50号線の信号待ちで、KKさんに声を掛けられた時、私は古河の青果市場に向かっていました。金沢市場輸送で古河の青果市場の山三青果の仕事をするようになったのは、平成2年の12月に入ってからだったと思います。

　だいぶん前にも書いていると思いますが、古河の青果市場に仕事に行ったのは、その山三青果の仕事が始まってからが初めてではなく、昭和62年の4月か5月頃にも一度行っていました。

　茨城県古河市の青果市場は、バイパスではない国道4号線沿いで、小山市方面に向かい大きな陸橋の手前右手にありました。陸橋は新幹線のための陸橋であったとも思います。付近にそれらしい風景がありました。

[link:] » 古河青果（株） - Google マップ https://t.co/mhJsSxCTWe

　上記がその場所だと思われます。最初に「古河市　市場」で検索すると、古河中央青果地方卸売市場、古河中央青果、県政中央青果などが出てきて、だいたい同じ場所なのですが、すぐわきに古河小山バイパスがあって、市場が移転したのかと思いました。古河市には複数の青果市場があるようです。

　茨城県は全国的にも突出して野菜の出荷量が多いという話はテレビで見たことがありましたが、1つの市に複数の青果市場があるというのは、他に聞いたことのない話でした。もっとも私が古河の青果市場だと思っていたところは古河青果（株）となっていて、市場とはなっていないようではあります。

　Googleマップの範囲を広げると付近には（株）猿島中央青果市場というのもあるようです。古河市の近くには猿島郡などがありましたが、山三青果の封筒の住所には、その猿島郡と書いてあるのを見たことがありました。被告発人松平日出男のもてなしに感謝感激していたのも山三青果の人たちでした。

　どこでどのようなもてなしを受けたのか、詳しいことは聞かなかったか、聞いても忘れてしまったのだと思いますが、山三青果の人たちの満足ぶりをみて、よほどの接待があったのか、それが被告発人松平日出男の処世術の本領発揮なのかと考えはしました。

　その山三青果の仕事というのも、当初は金沢港のイワシの運搬の仕事と同じく、市場急配センターの仕事を金沢市場輸送が請け負うというかたちにしていると聞いていましたし、金沢市場輸送の作業日報でも荷主を市場急配センターとして記入していたような憶えがあります。

　前に書いたと思いますが、その山三青果の仕事というのは、もともとは同じ金沢市の日栄運送がしていた仕事で、それを金沢市場輸送の本恒夫社長が奪い取ったという話も聞いていました。

　日栄運送については、九州の青果の仕事がメインで、他に長野県の飯田市のリンゴの仕事もしていると聞いていましたが、飯田市のリンゴの仕事は規模が小さいのか6トン車がメインとも聞いたことがありました。

　金沢市場輸送の九州からの帰り荷としての青果の仕事も当初は日栄運送の仕事がメインでしたが、それが富山市の池田運送の仕事に変わったことも、前に思い出せる範囲で詳しいことを書いているかと思います。

　日栄運送の九州での仕事は熊本県の植木市場辺りの仕事がメインで、近くの熊本県内に住むという人物が駐在員のようになっていました。今名前は思い出せないですが、駐在員といっても現地の人だったと思います。冬場はその人も含め長崎県の長与農協の方に行っていました。ミカンの仕事です。

　冬場と言っても、ミカンの仕事は1月の10日から半ばぐらいまでだったと思います。それは市場急配センターでの和歌山県かつらぎ農協の仕事でも同じで、ミカンが出荷が終わる頃には、イヨカンの荷物が増えていました。それでも2月の中頃までではなかったかと思います。

　現在は品種改良でミカンの時期というのも変わっている可能性があると思いますが、2月、3月という時期は、九州からの青果や野菜の仕事が少なく、帰り荷がなかなか決まらず、待機時間が長かったという経験則も私にはあったように思います。

　時刻は11月29日1時21分となり日付も変わっています。滋賀県でクボタと書いていたことを確認していましたが、気になって調べたところヤンマーとの間違いであったことがわかりました。やはりヤンマーは滋賀県内の琵琶湖周辺にいくつも工場があるようです。

　Googleマップで見ると滋賀県内にはずいぶん沢山のヤンマーの工場や関連会社があるようです。そこまで多いとは思わなかったのですが、たまたま工場を見かけたのか滋賀県にはヤンマーというイメージがあって、その頃にはテレビの夕方の天気予報でもヤンマーを当たり前のように見かけていました。

　項目名をあとから２つほどつぎ足しました。

* 金沢港をメインとした冬場のイワシの運搬の仕事と、そのイワシの加工品であるミールの倉庫移動について

　これまでに何度か書いてきたと思いますが、私が最初に金沢市場輸送で長距離トラック運転手の仕事をしたのは、昭和59年の1月から10月で、当時私は19歳でした。普通免許で4トン保冷車に乗務していました。この頃はまだイワシの運搬の仕事もミールの仕事もありませんでした。

　10月に金沢市場輸送をやめたのは、免許停止が主たる原因だったようにも思うのですが、事故の車両保険のことで小島という事務員ともめたことで事務所で配車係らに無視され、すぐに会社に行かなくなったこともよく憶えています。

　当時の金沢市場輸送の配車係というのは年配の藤村さんと、珠洲市蛸島出身の北浜太一さんでした。北浜太一さんは運転手だったようですが、免許取り消しとなって配車係をしていたようにも思い出すのですが、記憶はいまいちはっきりしません。

　北浜太一さんは当時27歳と聞いていたように記憶にあるのですが、当時19歳だった私にはずいぶん年の離れた大人の年長者に見えていました。

　一方の藤村さんは、その昭和59年当時で60歳前後と聞いていたように思います。その後、竹沢俊寿会長の夫人と同じ年だと聞いたこともありました。竹沢俊寿会長が還暦を迎えたと聞いたのは、その数年後で昭和62,3年のことだったと記憶にあります。

　大型運転手の竹田さんがチャンチャンコをおくるような話にしていたのですが、当時の私は還暦とチャンチャンコの知識がまるでなかったので意味がよくわかりませんでした。ただ、辛口の発言が多かった竹田さんが贈り物をするというのは、親近感のあらわれではと当時でも理解はしました。

　武田さんについては、昭和59年当時は越田さんと同じく6トン車に乗務していました。金沢市場輸送で6トン車というのはその2台だけで、大型車でも10トン車よりは、4t車の方が少しだけ多いぐらいであったように思います。黒板に名前と運行状況を書くスペースがそのようになっていました。

　10トンの大型車の保冷車は、4トンの保冷車より少し多いぐらいでしたが、10トン車には平ボディ車が3台いたと思います。そのうち2台は日野の新車で、黄色のようなオレンジ色の日通カラーのものでした。そちらには原田さんと棟方さんが乗務していました。

　もう一台の10トンの平ボディ車はいすゞの旧型の古いトラックでしたが、そちらには小坂さんが乗務していたように思います。もともと保冷車と平ボディ車は仕事の内容がまるで違ったので顔を合わせることも少なかったのですが、小坂さんは特に顔を見ることが少なく極端に無口でもありました。

　昭和59年当時の金沢市場輸送の10トン保冷車の仕事というのは、東北の港から南九州や四国まで養殖ハマチのエサを運ぶ仕事がメインであり、一度出ると長い運行にもなっていたのですが、同じ社員の運転手でも間が合わなければ、半年ほど顔をあわすことがないと聞いていました。

　もうずいぶん前から養殖ハマチという言葉を見かけたことがないのですが、ハマチといってもブリのことでした。ブリの幼魚としてハマチと聞くことも当時はあったのですが、石川県では今でもブリの幼魚のことを大きくなるにつれ、コゾクラ、フクラギ、ガンドと呼んでいます。

　スーパーなどでみると6キロ台のサイズでもブリとされていますが、養殖ハマチは10キロを超えるサイズが普通であったと思います。

　昭和59年というのは不景気な時代で、仕事の内容もきつく高速道路の利用にも大きな制限がありましたが、今思い出しても不思議なぐらい、明るい雰囲気で仕事をし、なにかにつけ自由度が高い時代であったようにも思います。同時に不安定さや身に危険を感じるようなことも多くありました。

　全国的にも多いと聞いていましたが、ヤクザや暴力団が身近にある時代でもありました。その時代はそのご暴対法によって激変するのですが、法律のことは知らずとも、その法律の効果の大きさは、肌で感じた世代かと思います。暴力団による暴走族の勧誘や関係性が特に強い時期でもありました。

　少し前には学校での校内暴力というのも大きな社会問題となっていました。それと重なっていたようにも思いますが、受験戦争や交通戦争とも呼ばれた時代で、交通死亡事故の件数も現在よりはずいぶん多かったように思いますが、飲酒運転などは余り問題にはされない時代でもありました。

　昭和59年秋の免許停止というのは、普通免許で初めての免停だったと思いますが、何日の免停だったのか、実際に免停となったのかも現在は思い出せなくなっています。現在のことは知らないですが、当時30日の免停であれば、一日の講習を受けるだけで免停がとけたようにも思います。

　10月に金沢市場輸送をやめたあとは、仕事をするつもりで3週間ほど北海道の札幌市に行き、戻ってからは数人の友達と一緒に金沢市出雲町の北陸地建という土木工事の会社でアルバイトをしていました。被告発人大網健二もその一人だったように思います。

　12月20日すぎには、中西運輸商で長距離の仕事を始めていました。たぶん免停明けの直後だったと思うのですが、その免停のことが今ではかたちとして思い出せなくなっています。

　中西運輸商には、その昭和59年の12月の下旬から昭和61年の2月一杯か3月の初め頃までいました。その退社の理由は明確に免停でしたが、150日の免停と、60日か90日のいずれかの免停がダブルとなっていました。

　県外の違反だったので手続きがずれて２つの免停になりましたが、1つの処分だと免許取り消しになっていました。免停となったのは、ちょうど長男が生まれるということで、結婚をした時期でもありました。

　当時の免許停止の最長は180日でした。150日の免停でも約3ヶ月となりますが、講習を受けたためか6月の中頃には免停が明けました。その時もすぐに行動を起こし、被告発人安田敏を頼って岐阜県海津町に15万円で買ったスプリンターというポンコツの車で向かいました。

　スプリンターはトヨタの車だったと思いますが、近くの日産の会社で買いました。デザインはおかまいなしで15万円という値段だけで買った車でした。色も茶色だったので、人気がなくその分値段も下がっていたように思います。

　スプリンターというのは競走馬か何かのような名前かと思いますが、ぶっかっこうでふざけたようなデザインの車でした。ずっと前に車種として名前を聞かなくなっているので、すぐに生産が打ち切りとなったのかもしれません。ネットで画像を調べると、それらしい情報は見つかりそうです。

　Googleで調べると、もともとは2ドアでスポーツタイプの車でもあったようです。スプリンタートレノとして情報がありますが、そのトレノというのは、平成元年12月当時、レビンと少しだけデザインが異なるスポーツタイプの車になっていたように思います。

　当時は、車体がほぼ同じで、デザインが少し違うだけの車が他にもありました。代表的だったのがトヨタのマークツー、チェイサー、クレスタでした。いずれも現在は名前を聞かなくなっている車種かと思いますが、当時は人気車でした。

　レビンはカローラレビンとなっていたようにも思うので、トレノがスプリンターだとすると異なる車種のようにも思えてきました。レビンやトレノのことも、今夜になってずいぶん久しぶりに思い出したのですが、平成元年12月、笹田君が乗ってきた車がトレノかレビンだったことも思い出しました。

```
カローラレビン (COROLLA LEVIN) は、トヨタ自動車がかつて生産販売していた1,600ccクラスの小型スポーツクーペで、カローラセダンをベースとしていた。スプリンタートレノと車台はもちろん、内外装部品のほとんどを共用する姉妹車である。

［source：］トヨタ・カローラレビン - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%A8%E3%82%BF%E3%83%BB%E3%82%AB%E3%83%AD%E3%83%BC%E3%83%A9%E3%83%AC%E3%83%93%E3%83%B3
```

　やはりレビンとトレノは姉妹車だったと確認が出来ましたが、カローラレビンとスプリンタートレノがほぼ同じとなると違和感が拭えません。

　当時、トヨタの販売店にはトヨタカローラなどがありました。カローラというのは大衆車のイメージが強いですが、高級車のクラウンも販売店はトヨタカローラだったような気がします。あまり自信の持ていない記憶で、他のトヨタの販売店の名称も思い出せないところではあります。

［link：］ トヨタカローラ石川 https://www.c-ishikawa.jp/

　調べたところ、「トヨタカローラ石川」という名称は現在も残っているようです。輪島市や七尾市にも店舗があるようですが、まったく見かけた覚えがなく、トヨタ車の再編で、ずっと前に消滅しているものかと思っていました。

　ホームページをざっとみたところ、特に取り扱い車種というのは見当たらず、オススメ車種としてパッソ、ルーミー、シエンタというのがあります。少し耳にしたことのある車種ですが、ルーミーというのはまったく聞いたことがないと思いました。

［link：］ トヨタ 販売店 | トヨタ自動車WEBサイト https://toyota.jp/service/dealer/spt/car-lineup?CN=T

　どうも特定の車種の取扱店というのは特に決まりがないようです。バスやトラック、ダンプまで上記のページの「トヨタ店取扱車種一覧」にはありますが、カローラという車種は見当たりません。カリーナも見当たりませんが、トヨタカローラ石川などの名称は昔のまま残っているようです。

　Googleの「クラウン　取扱店」の検索結果には、トヨペット店やネッツ店という聞き覚えのある店舗があって、そちらではカムリやマークｘという別の車種もありました。

［link：］ トヨタ 販売店 | トヨタ自動車WEBサイト https://toyota.jp/service/dealer/spt/car-lineup?CN=C

　上記のページは、「カローラ店取扱車種一覧」とありますが、クラウンはみあたりません。

　カローラ店とクラウンにこだわったのは理由があります。被告発人松平日出男が以前働き、業績がよかったものの横領で会社をやめたと聞いたのは、カローラ店だったように思うからです。取扱車種がクラウンとなると、カローラとは客層がずいぶん違ってくるはずです。

　横領については、刑事事件になったとも賠償問題になったとも聞きませんでしたが、被告発人松平日出男が金沢市場輸送で仕事を始めた直後から、横領の話を聞かされていたので、なぜそんなことをわざわざ知らせるのか、不思議には感じていました。横領の原因も競馬と聞いていました。

　私の記憶では被告発人松平日出男が働いていたというトヨタの会社は、金沢市内の元車の交差点の近くだったように思います。現在そのあたりにトヨタの店舗は見当たりません。

　トヨタカローラ石川の店舗も金沢市内では、泉丘店、松村店、金沢駅西店、元町店と、元車とはまったく違う場所ばかりです。もともと金沢市内の中心部には近すぎて、車で訪れるお客にも不便と思われるので、移転は不思議ないですが、過去の確認が出来なかったのは残念です。

［link：］ トヨタカローラ店 - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%A8%E3%82%BF%E3%82%AB%E3%83%AD%E3%83%BC%E3%83%A9%E5%BA%97

　別の情報を見つけましたが、過去の取扱車種にもクラウンは見当たりませんでした。トヨタ自動車のディーラーの1つとあるので、クラウンのディーラーとして、次に調べることができそうです。

［link：］ トヨタのディーラーは４系列？！知っておきたい重要なポイント！ | 車の大辞典cacaca https://cacaca.jp/knowledge/9058/

　上記のページで、トヨタ店、トヨペット店、カローラ店、ネッツ店と４つあることがわかりました。クラウンなどの高級車はトヨタ店の取り扱いのようですが、トヨタ車のトヨタ店というのは初めて見たように思います。

　ふと気がついたのですが、石川トヨタというのもあったような気がしてきました。

［link：］ 金沢御影店 | 石川トヨタ自動車株式会社 公式WEBサイト https://www.ishikawatoyota.com/shop/2

　やはり金沢というか石川県でのクラウンの取扱店は石川トヨタだったようです。金沢市の御影店の場所は、元車の交差点からは犀川の御影大橋をはさんではいるものの、同じ通り沿いでした。あれほどの大きさの店舗となると移転や取り壊しも容易ではなかったとも考えられます。

　その石川トヨタの御影店の前は、仕事でたまに通ることがありました。別の言い方をすれば、普段の生活で通ることは余りない場所でした。しかし、道路の名称は聞かなかったものの、松任駅から野々市市の中心部を通って、一本道で金沢駅前に繋がる道路です。

　増泉の交差点から野々市町の方というは、割とよく通る道路でした。元車の交差点の辺りもそうでしたが、増泉の交差点と元車の交差点の間が、余り通ることのない道路となっていて、その道路沿いに石川トヨタがあったことを今回、確認しました。

　どこで、被告発人松平日出男が働いていたところをトヨタカローラと勘違いしていたのかわかりませんが、トヨタのディーラーについて知識がなかったので、いろいろと勉強になりました。時間を掛けた割に役に立つ知識でもないですが、もやもやがすっきりしただけ良かったです。

　トヨタ店である石川トヨタが、トヨタ自動車の最高級車種の取扱店らしいと知って、被告発人松平日出男に対する見方も少し変わった気がします。それだけ金沢で人脈も広かったということになりそうです。それらしいことは知っていましたが、実がともなったという感じです。

　昭和61年の3月のはじめから6月の中頃まで免許停止となり、免停明けとともに岐阜県海津町に被告発人安田敏を頼って出稼ぎに行きました。当時は、もちろん携帯電話のない時代で、被告発人安田敏との連絡は、彼の突然の訪問か、私のアパートの固定電話に電話を掛けてもらうことでした。

　岐阜県にいた被告発人安田敏に連絡を取るのは困難だったと思います。彼はライスセンターの敷地内にある平屋の集会所のような家に、珠洲市正院の富田さんと二人で住んでいました。固定電話があったという記憶はないですが、他に連絡の方法がないので、あったことも考えられます。

　事情は別の機会に書きたいと思いますが、8月の20日過ぎに私は金沢に戻り、すぐに金沢で仕事を探し出しました。

　他に求職活動をしたという記憶はなく、すぐに思いつきのダメもとで金沢市場輸送に電話をしました。応対したのは配車係の藤村さんで、最初は警戒され、何かあったらすぐにやめてもらう、と言われたのですが、仕事を始めるとすぐに高く評価をされるようになりました。

　中西運輸商の仕事が生命の危険が背中合わせなほど過酷であったことで、知らず知らずに鍛えられ、その後3カ月ちょっとの免停で不自由な生活をしたことで、性格が落ち着き慎重な仕事をするようになったのが、自分の自覚以上に大きかったようです。

　当時住んでいた東力二丁目のアパートは、車がないと不便な場所で、近くに高田舗装という道路工事の会社があって、そこでアルバイトをすることが出来ました。ちょうど雪解けの春先の時期で、とても忙しい時期でした。夜間工事もありました。

　社員になることを勧められたのですが、断ったところ、しばらくして仕事が暇になると、自宅待機の出勤といわれ、連絡がないまま1,2周間と過ぎたので、そのまま辞めることにしました。そんなときに、被告発人安田敏の訪問があったのだと思いますが、岐阜に行くことになりました。

　被告発人安田敏の供述調書には、その辺りの事実関係も存在しないようになっていましたが、前年の昭和60年の夏頃にも被告発人安田敏は、金沢市場輸送で仕事をしていたという事実関係があります。

　被告発人安田敏がどれほどの間、金沢市場輸送で仕事をしていたのかはっきりわからないのですが、その後、金沢市場輸送の社長となった本恒夫とは面識があった可能性があります。

　被告発人安田敏が金沢市場輸送で仕事をしたのは、以前は長距離以外に選択肢がなかった氷の運搬の仕事でした。その氷の運搬の仕事は、前年の昭和59年、私がいた頃は、長距離の仕事の合間にやらされていたものでした。

　1つ100キロほどある氷を、スクラップのようなポンコツの平ボディのトラックに積み込み、金沢港の冷蔵庫などに運んでいました。他に白菊町の冷蔵庫にもよく行っていました。市内の中心部に近かったですが、すごく古い歴史を感じさせる古い冷蔵庫でした。

　被告発人安田敏が金沢市場輸送で働いているという話を聞き、すぐに中西運輸商の4ｔ車に乗ったまま金沢市場輸送に行き、テナントビルの2階にあった金沢市場輸送の事務所の窓口と運転席で、会話をしたのですが、岐阜に仕事に行くといってやめたところだと言われました。

　そのとき、私と話したのは、蛸島の北浜太一さんの弟でした。「おっさま」と呼ばれていました。被告発人大網健二もよく話をしていました。

　おっさま、というのは能登の方言で次男や弟のことです。長男のことは「あんさま」と呼んでいましたが、最近は聞かなくなったような気もします。

　昭和61年8月25日頃から私は金沢市場輸送で市内配達の仕事をするようになりました。その時点で配車係だった北浜太一さんの姿はなく、珠洲市蛸島に帰って、浜田漁業で働いていると聞きました。配車係をしているとも聞いたように思います。

[link:] » （株）中部資源再開発 才田工場 - Google マップ https://t.co/Z9PO0n9hjG

　現在、上記の場所となっているのが浜田漁業金沢工場があったところです。Googleマップでみたところ、現在もその前の道路の道沿いは、田んぼか空き地が広がっているようです。少し離れたところには、以前はなかったと思われる新興の住宅地が広がっています。

　浜田漁業金沢工場の前の道路は、農免道路と呼ばれていました。Googleマップでは、同じような広さの道路が碁盤の目のように張り巡らされ、場所を探すのも少し手間取ったのですが、この農免道路は、金沢から能登の往復でよく通る道路でした。

　トラックの仕事でもちょくちょく通る道路でした。現在でも周辺には、建物が見当たらないので目立っていると思いますが、隣接した天狗中田の食肉工場と浜田漁業金沢工場は、決まって目につくものでした。

　少し離れたところに金沢競馬場があります。その辺りからは金沢港からイワシを積んだトラックが農免道路に出ていました。短い区間でしたが、それでも何度か、イワシを積んだ平ボディのトラックを見かけていました。

　平ボディ車に、よくある青色のビニールシートを張って、そこにイワシを積み込むようなスタイルでしたが、他には見ることのないようなトラックだったので、かなり目立っていました。たぶん、金沢東インターの近くのトラックステーションでも見かけていたように思います。

　昭和60年始め頃に見かけていたように思います。珠洲市の蛸島は、国鉄の能登線の終着駅でもありましたし、漁港としても知られていました。石川県立水産高校に通っている同級生などもいました。

　その珠洲市の漁業の会社が、金沢に工場をつくり稼働しているというのも、当時は他に余り見聞きしたことがなかった話で珍しさもありました。余りとしたのは、金沢駅前の都ホテルやパチンコ店を、小木港の水産会社が経営しているという話はよく聞いていたからです。

　私が金沢市場輸送で市内配達の仕事をしたのは、1つは一発試験で大型免許を取得するのが目的で、もう一つは免停で違反を重ねると免許取り消しの可能性が高くなっていた点数を回復させることでした。

　私はもう何年も交通違反がないので、現在の運転免許の点数制度のことはわからないのですが、当時は丸一年間、違反がないことで違反点数が全て回復すると言われていました。

　昭和58年当時は、金沢市の観音堂に運転免許センターがあったのですが、昭和61年の頃には、現在も同じと思われる東蚊爪に移転していました。この運転免許センターも、金沢港からイワシを運ぶ通り道の近くで、通る道は違っていましたが、北陸ハイミールの方が近くにありました。

　北陸ハイミールの方は、平成元年の12月ころから完成した工場で稼働を始めていましたが、平成9年頃には、廃棄物処理工場になっていたように思います。一日に1600トンのイワシの処理ができるということで、日本海側最大の規模とも聞いていました。

　金沢港でのイワシの運搬のシーズンというのは12月から4月ぐらいで、3月4月となると金沢市場輸送ではダンプだけの仕事となっていました。漁獲量が激減するためで、シーズンの始まりも同じだと聞いていましたが、12月の中頃には平ボディ車も集まり本格化していたと思います。

　私は2回のシーズン、そのイワシの運搬の仕事をしたのですが、1回目と2回目はまるで状況が違っていました。北海道の釧路に本社があるとも聞いた北陸中日新聞が参入したことで、取扱量が倍増し、トラックやダンプの数も大幅に増えました。

　平ボディのトラックやダンプが増えたと言っても、金沢市場輸送のトラックとダンプの数は変わっていませんでした。水槽のようなタンクを積んだ平ボディ車は5台で、いすゞが2台、三菱ふそうが3台ではなかったかと思います。すぐにやめていった運転手もいたので、常時稼働は2台でした。

　金沢市場輸送でミールの倉庫移動というのは昭和61年の12月の時点で始まっていましたが、それが始まったばかりではないような話も聞いていたように思います。2シーズン目あるいは3シーズン目ということになりますが、たぶん2シーズン目だったのだと思われます。

　私が前に金沢市場輸送にいた昭和59年10月の時点では、まったくイワシの運搬やミールの話はなかったと思います。年明けから始まったことなどを想定すると、3シーズン目だった可能性は否定は出来ませんが、当時の状況から可能性は低いように見ています。

　イワシの運搬がないと加工品であるミールの仕事は始まらないのですが、当初、そのイワシの運搬に従事していたのが、あとに八戸とか八戸軍団とも呼ばれた、白ナンバーの運転手のグループでした。

　時刻は16時09分になります。14時10分過ぎぐらいに出掛けて、珠洲警察署能登庁舎に運転免許の更新に行っていました。少し不安もあった視力検査と深視力も問題なかったのでほっとしました。更新は来月12月の22日ぐらいが期限になっていたように思います。

　思い出すのは、一度失効させてしまったことで、2008年の12月だったように思います。夕方の仕事中、機械のトラブルか何かで作業が中断し、人と会話しているときに、たまたま運転免許の話が出たので、更新を忘れていたことに気がついたのです。

　たしか期限いっぱいの当日に気がついたように思います。一日早ければ翌日に手続きに行くことも出来たと出来たという大きな後悔と同時に、完全に忘れていたので、その場で気がついて本当に助かったという思いが交錯しました。知らずに運転していれば、無免許となっていたのかと思います。

　気がついた翌日だったように思いますが、仕事を休んで金沢の免許センターに行きました。車は使わず、羽咋駅まで歩いて行ったのも初めてのことでした。帰りに金沢駅西口のデパ地下のようなところを歩いたことも憶えています。あれ以来、金沢駅には行っていないとも思います。

[link:] » hatena-diary_20080201 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/V97Sxc4UH3

　時刻は11月30日10時34分です。前の行の投稿ですが、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のタイムラインのツイートでは15時間前と表示されています。

　Twitterの投稿時刻は設定などによってアメリカ時間で表示されることもあるのですが、19時51分となっているので間違いはなさそうです。この投稿をするまでに、捜し物をしていました。この続きは別に書きたいと思います。いろいろと発見がありました。

　ミールはよくある肥料のような紙の袋で重さは25キロだったと思います。実際、肥料としての用途が多いと聞いていましたが、カップラーメンの粉末スープに使うとか、養鶏場のエサとして運んだこともありました。新潟県です。養鶏場はごく例外でしたが、ほとんどは倉庫への運搬でした。

　ミールの行き先は、愛知県がほとんどでした。知多半島の付け根辺りが特に多かったと思います。海に近い辺りです。平成4年1月か2月には三重県の津市か四日市に行ったこともありますが、それは珍しく感じました。

　もともとミールの仕事ばかりしていたわけではないですが、愛知県以外にミールを運ぶようになったのは平成4年になってからだったように思います。新潟の養鶏場にミールを運んだのは、それより前で金沢市場輸送にいたときでした。保冷車で運んだかもしれません。

　新潟県でも山形県との県境に近いところと、上越市の先の柿崎の養鶏場に行きました。前者では現地で缶チューハイを飲んだことをよく憶えています。トラックから降りる時、足元がふらつき危ない思いをしました。世間でもちょうど缶チューハイが流行りだしていた頃だったと思います。

　被告発人大網健二らと金沢市の八日市の焼肉店で飲んだときも、焼酎のチューハイを飲み、店を出た時、足がもつれていました。店の横には踏切があったことも記憶にあります。

[link:] » 八日市 - Google マップ https://t.co/seYjgXYqFN

　金沢市八日市は、野々市町（現在は野々市市）に隣接していたと思います。ちょっと裏道のような道でしたが、野々市方面に行くときはよくその焼肉屋の前の道路を通行していました。

　ここで金沢市八日市を強調しておきたいのは、当時私は、被告発人松平日出男の家が八日市の辺りだと聞いていたからです。それ以外に聞いたことは無かったですが、供述調書の住所は金沢市糸田新になっていたかと思います。金沢市内でも範囲の狭い町名かと思います。

　被告発人多田敏明に聞いたことですが、被告発人松平日出男の息子は西南部中学校の出身とのことでした。その中学校はたまに車で通ることがあったので、だいたいの場所は知っていましたが、西金沢の近くだったと思います。いくらか離れたところに東京ストアー西南部店もありました。

[link:] » 金沢市立西南部中学校 から 八日市 - Google マップ https://t.co/2wCdpQbg0w

　私の感覚では、八日市の右斜め下の方角に西南部中学校が位置すると思っていたのですが、上記のGoogleマップをみると、西南部中学校のほぼ真下に八日市があるようです。距離も１．２キロなどと出ていますが、これは金沢市内ではけっこう離れた距離になるように思いました。

　Googleマップは北を上として表示しているという情報を見かけたことがあります。私の頭の中の感覚では国道８号線を上として描いていました。その基準に当てはめると、八日市の右方向に西南部中学校が位置することになります。

　何度も書いていると思いますが、私は金沢市内で市内配達の仕事もしていましたが、地図を見て場所を捜したということはほとんどなかったと思います。会社には住宅地図があったとは思いますが、住宅地図などで場所を捜していると大変な手間が掛かったと思います。

　ちなみに現在はなくなっていると思いますが、能登町が能都町であった頃は、電話帳に住宅地図がついていました、それでさえ場所を探すのはややこしかったので、苦手意識もあり、よほどでないかぎり住宅地図は使いたくはなかったのだと思います。

　平成２１年の１月に最後に金沢市に行ったのも、その八日市のあたりでした。ドスパラという自作のパソコン店に行ったのです。そのときも、新しい道路が出来ていて、道がわかりにくくなっていると感じました。だいたいその辺りで目安としたのも東京ストアー西南部店でした。

　その東京ストアー西南部店の前の道路で、野々市とは反対方向ですが、数百メートルだったと思いますが、離れたところにうどん屋のような食堂があって、そこで被告発人大網健二、KYNと三人で食事をしたときに、KYNの配管設備の会社で仕事をすることが決まりました。

　会社と行っても当時は、株式でも有限でもありませんでした。もちろん会社の名前はありましたが、会社という言葉は含まれていませんでした。それでも普通に会社と呼んだり、KYNは社長と呼ばれていました。現在は株式会社となっているようですが、名称は少し変わっているようです。

　KYNの設備会社のことはFacebookで見ていたのですが、もう１年近くページを開いたことはないと思います。被告発人安田敏のFacebookも同じです。どちらも同じ頃に見つけました。３年前になるうように思いますが、１０月頃のことだったと思います。

　ミールについては、これまで色々書いてきたと思います。昨日書き忘れていたこととしては、浜田漁業金沢工場の一日の処理量ですが、北陸ハイミールが１６００トンというのに対して、６００トンと聞いていたように思います。違っていれば７００トンです。それ以上はなかったと思います。

　ミールについては、奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)でも投稿をしているかもしれません。より古いアカウントになりますし、始めた頃は、事件に関して具体的で詳細な投稿をやっていた時期もあったと思います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「ミール」の検索結果 - Twilog https://t.co/gK3KcxtFfG

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-11-30 12:42／2010-05-14 07:09 URL： https://twitter.com/kk_hirono/status/1068349441571151873 https://twitter.com/hirono_hideki/status/13937354589
&twitter(1068349441571151873){theme:light}
> この加工した魚粉はミールと呼ばれていました。平成4年に入ってから藤の会社のトラックがミールの積み込みに来ている姿もみているので、藤とI運送のMHK社長は仕事の付き合いもしていたようです。ここでもう一つ気になることがあります。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-11-30 12:42／2010-05-14 07:14 URL： https://twitter.com/kk_hirono/status/1068349525788581888 https://twitter.com/hirono_hideki/status/13937593209
&twitter(1068349525788581888){theme:light}
> 私は平成4年2月３日にミールを積んで福岡に向かいました。ミールをトラックに積んだのは1日の土曜日だったと思います。九州では佐賀県の鳥栖が、高速道路の交わるところでもあり、帰り荷の待機場所でした。私はここで二晩泊まったと思います。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-11-30 12:42／2011-06-18 22:17 URL： https://twitter.com/kk_hirono/status/1068349596575780865 https://twitter.com/hirono_hideki/status/82074499977187329
&twitter(1068349596575780865){theme:light}
> http://ow.ly/i/d89i http://ow.ly/i/d89n 昨夜の小木港です。輪島丸船団でした。平成２年頃、金沢港でイワシの運搬の時、蛸島丸船団と一緒に、水揚げからミールの加工場まで運んでいました。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-11-30 12:43／2013-06-27 21:17 URL： https://twitter.com/kk_hirono/status/1068349664829657090 https://twitter.com/hirono_hideki/status/350226384532144128
&twitter(1068349664829657090){theme:light}
> ドラマ始まっている。最先端のゴミ処理工場。ミール工場のことを思い出した。忘れかけていたかもしれない。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-11-30 12:43／2013-06-27 22:46 URL： https://twitter.com/kk_hirono/status/1068349731498119168 https://twitter.com/hirono_hideki/status/350248814331957249
&twitter(1068349731498119168){theme:light}
> フィッシュミール とは - コトバンク http://t.co/gcOkmI79w0 フィッシュをつけないと別の検索結果が多いみたい。北陸ハイミールは一日に1600トンの処理能力でに日本海側最大規模と記憶。
◁◁◁
<hr />

　このエントリーのテーマである福岡の運行のことが出てきましたが、私は佐賀県の鳥栖のトラックステーションで２泊していたようです。ここ２，３日も思い出しながら考えていたのですが、１泊と思い込んでいました。

　次は、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)の方を見てみたいと思います。余り数が多いようであれば、その時は考えます。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:48／2013-08-30 15:08 URL： https://twitter.com/kk_hirono/status/1068351099252310016 https://twitter.com/kk_hirono/status/373326426239287296
&twitter(1068351099252310016){theme:light}
> 大型免許をとってからは、市内配達の仕事はほとんどしなくなりました。ポンコツの6トン保冷車で仕事をすることもあったと記憶していますが、ちょうどイワシの仕事の時期になっていたので、10トン平ボディ車でのミールの仕事がほとんどになりました。ミールとは主にイワシを原料にした魚粉です。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:49／2013-08-30 15:19 URL： https://twitter.com/kk_hirono/status/1068351190264496128 https://twitter.com/kk_hirono/status/373329052473384960
&twitter(1068351190264496128){theme:light}
> 私がはじめにいた昭和59年当時はなかった仕事ですが、早ければその年の12月頃から始めた仕事のようでした。同じ石川県の珠洲市蛸島にある浜田漁業の仕事でした。浜田漁業金沢工場というミール工場が出来ていたのです。浜田漁業は蛸島丸という船団を所有していました。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:49／2013-08-30 15:26 URL： https://twitter.com/kk_hirono/status/1068351260066144257 https://twitter.com/kk_hirono/status/373330820515127296
&twitter(1068351260066144257){theme:light}
> 昭和61年の8月に2回目の入社をしたときには姿はなく、前回に私がやめてまもなく蛸島に帰り、浜田漁業の配車係をしているとも聞いていました。詳しい話を聞いていたような気もするのですが、憶えていないです。それでも北浜がきっかけでミールの仕事をするようになった可能性は高いと思います。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:49／2013-11-07 20:59 URL： https://twitter.com/kk_hirono/status/1068351343008464898 https://twitter.com/kk_hirono/status/398419324261515265
&twitter(1068351343008464898){theme:light}
> もう一つはYTの父親のことです。父親の話というのはYT本人から余り聞いてはいなかったように思いますが、他の運転手からYTの父親がイワシの運搬をするようになったと聞き、それらしい人の姿を北陸ハイミールの台貫場で何度か見かけていました。遠目にしか見たことがなく顔の認識もないです。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:51／2014-01-18 21:39 URL： https://twitter.com/kk_hirono/status/1068351717140353024 https://twitter.com/kk_hirono/status/424521434350632960
&twitter(1068351717140353024){theme:light}
> 私が金沢市場輸送の長距離の仕事で最後の運行になったのは神戸市内の港の方で、たしかミールをおろし、帰り荷がなくって空車で戻った運行でした。輪島のYと一緒でした。彼は大型保冷車の払い下げを受け傭車の持ち込み運転手として、金沢市場輸送の仕事をしていたはずです。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:51／2014-01-29 06:53 URL： https://twitter.com/kk_hirono/status/1068351837252726784 https://twitter.com/kk_hirono/status/428284616374378497
&twitter(1068351837252726784){theme:light}
> 平成1年の1月頃に能都町松波の港で自殺をした珠洲のTSさんも同じ頃で、浜田漁業金沢工場でミールの運搬の仕事が始まった頃でした。TSさんは宇出津の石川県立水産高校を卒業してすぐに金沢市場輸送に入社し、４トン車で長距離の仕事をしていたと聞いています。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:52／2014-01-31 01:18 URL： https://twitter.com/kk_hirono/status/1068351927241474048 https://twitter.com/kk_hirono/status/428925159198584833
&twitter(1068351927241474048){theme:light}
> 小坂さんという人も同じく10トン平ボディに乗務していたと思いますがその頃は日通カラーではないものに乗務していたように思います。あるいは型の古いイスズの10トン平ボディだったかと思います。この古いイスズの平ボディは私が大型免許を取って間もない頃ミールを運んだりしていました。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:52／2014-05-03 12:55 URL： https://twitter.com/kk_hirono/status/1068352147291394049 https://twitter.com/kk_hirono/status/462440330357260288
&twitter(1068352147291394049){theme:light}
> この2回めのイワシの時期というのはだいたい平成1年の12月から平成2年の3月ころということになると思いますが、前回とは仕事の規模が倍以上になっていました。北陸ハイミールができていたからで、北海度の釧路市の愛国運輸のダンプもけっこうな台数が来ていました。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:53／2014-05-03 16:36 URL： https://twitter.com/kk_hirono/status/1068352336194498561 https://twitter.com/kk_hirono/status/462495995926835200
&twitter(1068352336194498561){theme:light}
> 北陸ハイミールのお抱えとなったのは輪島丸船団でした。輪島市の漁港では海士町と輪島崎町があって仲が悪いとも聞いていましたが、輪島丸はその輪島崎町の船だと聞いていました。現在でも小木港で見かけることが多いです。佐渡方面の漁に出るときは、小木港に停泊するとか聞きました。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:54／2014-05-16 15:42 URL： https://twitter.com/kk_hirono/status/1068352420042891264 https://twitter.com/kk_hirono/status/467193301527851008
&twitter(1068352420042891264){theme:light}
> 彼女が裏駐車場での駐車をやめたのは平成4年2月3日のことでした。ちょうど私が24トンのミールを積んで九州の福岡市に向けて出発した日のことです。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:54／2014-06-21 11:26 URL： https://twitter.com/kk_hirono/status/1068352521524015104 https://twitter.com/kk_hirono/status/480174948267200515
&twitter(1068352521524015104){theme:light}
> 「市川タイヤ」に関しては書いておきたいことが２つあります。ひとつは被害者AAさんが自分の軽四で私を迎えに来てくれたこと、もう一つはミールの清水倉庫での被告訴人安田敏のタイヤの爆発問題です。そういえば工事現場突入の件もまだ中途でした。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:54／2014-06-24 19:12 URL： https://twitter.com/kk_hirono/status/1068352613144350721 https://twitter.com/kk_hirono/status/481379436214763520
&twitter(1068352613144350721){theme:light}
> あれも平成4年の1月か2月頃だったと思いますが、北陸ハイミールでその会社の大型トラックを見ることがありました。その時の運転手ですが昭和59年に私が初めて金沢市場輸送に入社した時にいた運転手だったと思います。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:55／2014-06-28 15:28 URL： https://twitter.com/kk_hirono/status/1068352824092766210 https://twitter.com/kk_hirono/status/482772552247291905
&twitter(1068352824092766210){theme:light}
> 輪島屋鮮冷の大型車が北陸ハイミールにミールを積みに来ていることもありましたが、それは平成4年の1月ころだったかもしれません。たしか福岡県行きのミールを積んでいると聞いたように思います。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:56／2015-07-17 23:39 URL： https://twitter.com/kk_hirono/status/1068353015600402434 https://twitter.com/kk_hirono/status/622053057577091072
&twitter(1068353015600402434){theme:light}
> この平成4年2月1日は土曜日で私は福岡県福岡市の須崎埠頭行きのミール24トンを積み込んでいました。普通はちょっとない運行でもあったのですが、月曜日の朝に出発をして夕方に予約を入れていたフェリーで神戸から北九州の門司港に行くことになっていました。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:56／2015-07-25 14:27 URL： https://twitter.com/kk_hirono/status/1068353126275502081 https://twitter.com/kk_hirono/status/624813099002916864
&twitter(1068353126275502081){theme:light}
> 缶チューハイで記憶に残っていることと言えば、金沢市場輸送の平ボディ車でミールを積んで新潟県の村上市より奥の方の場所に行った時のことです。当時、新潟県には頸城郡や蒲原郡というのがあったのですが、住所もそんな感じでした。山形県との県境にも近い辺りです。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2018-11-30 12:57／2015-07-26 16:43 URL： https://twitter.com/kk_hirono/status/1068353283742257152 https://twitter.com/kk_hirono/status/625209923375206400
&twitter(1068353283742257152){theme:light}
> 私はその昭和61年の11月27日に念願だった大型免許に合格しました。誕生日の翌日だったので日付のことはよく憶えています。すぐにでも大型の保冷車に乗務したかったのですが、保冷車の空きがなく、平ボディ車でミールの仕事などしていました。
◁◁◁
<hr />

　なるべく記憶のはっきりした時期のものがよいとも判断しました。これは忘れていたというものは余りなかったですが、福岡市の須崎埠頭というのは忘れていました。私が最初に福岡市に行った昭和５９年頃は、箱崎から先に都市高速はなかったように思います。

　金沢市場輸送で大型保冷車に乗務した昭和６２年４月から一定期間もなかったように思います。市街地を走って箱崎まで行き、箱崎から福岡インターまでは一本道でした。途中、国道３号線に出て左折したと思いますが、その上空には都市高速の高架があったような記憶もあります。

　金沢市場輸送とウロコ運送の一日交代の福岡の定期便では、富山の富山中央店からの雑貨が行き荷で、あとになると砺波店の立ち寄りも増えたように記憶しますが、北九州と福岡の２箇所卸しで、卸先はどちらもトナミ運輸ではなく九州西武運輸でした。

　福岡市の九州西武運輸に行くときは、決まって大宰府インターで降りていました。九州自動車道です。これは中西運輸商での佐川急便と同じでしたが、０１４の東福岡店に立ち寄る時は、福岡インターで降りていました。ほとんどの場合、東福岡店の立ち寄りがあったようにも思います。

　先ほど引用した過去のツイートにもあったと思いますが、私は昭和６１年１１月２７日に大型免許を取得しました。誕生日の翌日だったのでこの日付はよく憶えています。大型保冷車の空きがなかったことで、１２月頃になるとよくミールの倉庫移動をしていました。

　市場急配センターの給料というのは２５日が締め切りで翌月の５日払いでしたが、金沢市場輸送のことは思い出せません。なんとなくですが市場急配センターとは違っていたような気もします。

　給料の締切とは別に大型免許の取得と同時に市内配達の仕事はしなくなったように思います。引き継ぎのような指導もなかったと思います。そのあとも４t車や６トン車で、市内配達をするようなことはありました。正確には金沢市内の配達ではなかったかもしれません。

　１２月というのは中央市場の青果物などを扱う市内配達では一年で最も忙しい時期でした。４t車で一車単位の貸し切りの仕事がありました。記憶にあるのは山中温泉で妻子を同行させていました。珠洲市のスーパーにも行きましたが、その頃かどうかははっきりしません。

　ミールは、倉庫移動だけでなく、名古屋方面に行くこともありました。そのときに乗務したのは、いすゞの旧型車の１０トン平ボディでした。ギアのレバーの根本の袋が破けていて、そこからエンジンの中が見えましたし、エンジンの騒音もそのまま車内に聞こえるようなポンコツでした。

　それでもエンジンの調子はよく、４t車とは比較にならない安定感を感じて、運転するのも楽しかったように憶えています。暖房もまともに効かないトラックで、外仕事をしていたような寒さも記憶に残っています。

　その頃、ミールの移動先の倉庫は１つだけだったと思います。日通の倉庫と聞いていたようにも思いますが、松任市の外れでした。その辺りには八幡のすしべん、があって、その少し先の交差点の右斜めの角だったと思います。もう少し行くと川北町になったと思います。あるいは寺井町です。

　川北町も寺井町も現在の能美市で、当時は能美郡だったと思います。寺井町の先が小松市です。あとで書く清水倉庫は、さらに川北町か寺井町に近いところで、小松方面に向かうと左折して、しばらく走った奥の方にありました。

　昨夜、Googleマップで調べたのですが、八幡のしすべん、の場所は白山市福留町になるようです。福留町というのは、他でも見たような憶えがあったのですが、最近、白山市福留町としてテレビで見たようにも思います。現在の白山市は以前の松任市を丸々含むようです。

　八幡のすしべん、は、テレビのケンミンショーなどでも石川県のソウルフードのように紹介されています。しかし、金沢市周辺では、よく行った昭和５８年当時は、入江店と、その松任の店舗ぐらいしかありませんでした。

　八幡のすしべん、は羽咋市が始まりのようです。１，２年前たまたまテレビで見たのですが、羽咋市内の神社が名前の由来とも紹介されていました。現在は七尾市になっている中島にも店舗がありますが、そこは昭和５７年の１，２月頃に店に入った記憶があります。

[link:] » 福留町 - Google マップ https://t.co/d5NgNgcGg1

<hr />
[link:] » 水島町 - Google マップ https://t.co/57l8xamAVZ

<hr />

　今、Googleマップを見て気がついたのですが、八幡のすしべん、の少し手前には斜めに寺井町に行く旧道があるようです。この道は仕事でも通りましたが、しばらく行った先で手取川の橋を渡ると左手に「手取フィッシュランド」がありました。現在も同じようです。

　水島倉庫の近くに手取フィッシュランドがあるとは考えていませんでした。間違えて手取フィッシュセンターとしていたのですが、間違いに気が付き訂正しました。間に川北町立という小学校も見えます。川北町といえば、川北大橋のイメージが強く、場所も離れていると思います。

[link:] » 川北大橋 - Google マップ https://t.co/vzwDFO8nyt

<hr />

　川北大橋は有料だったと思いますが、KYNの配管設備の仕事で、北陸先端大学、辰口庁舎、いしかわ動物園の現場に通った時は、よく通っていたとも思います。やはり川北大橋を通ることもありましたが、国道８号線から別の道を使うことが多かったと思います。

[link:] » Yahataすしべん https://t.co/1l09IM5owo

<hr />

　さきほど、昭和５８年当時、八幡のすしべん、の店舗は金沢市近郊で、入江店と松任のバイパス店ぐらいだと書きましたが、それは２４時間営業のことかと思います。当時２４時間営業で食事ができる店は、それぐらいしかなかったので店は大きくなかったですが、存在感は大きかったです。

　当時は、かけうどんが１００円でした。現在はいくらか知りません。現在も２４時間営業というのは全店舗で４つしかないようです。その１つが野々市市の二日市のようです。マルモ設備があった場所の近くかと思います。

[link:] » 二日市 - Google マップ https://t.co/ryr3UQwB81

<hr />

　直接つながってはいないようですが、敷地を見ると１００満ボルト金沢本店の隣になるようです。御経塚の陸橋の坂の辺りになるようです。そういえば、この場所に、八幡のすしべん、を見たことはあったかもしれません。住所が二日市になるのは意外でした。

　　この辺りは、金沢市と野々市町の境目がわかりにくくなっていました。さきほども金沢市八日市も同じです。１００満ボルト金沢本店は、野々市店かと思っていました。古い記憶が１つ蘇ったのですが、被告発人大網健二の付き合いでこの店に行き、彼がパソコンを買ったことがありました。

　その店舗は現在のビルの店舗ではなく、国道８号線バイパスからもう少しだけ離れた場所で、平屋のパチンコ店のような店舗であったような記憶があります。買ったのはディスクトップのパソコンだったと思いますが、買ったあと、そのパソコンを見ることはなかったと思います。夜でした。

　パソコンといえば、平成９年の春頃の時点で、被告発人大網健二はノートパソコンを持っていました。メビウスという商品でした。CDドライブとフロッピーディスクドライブが別になっていて、取り外して脱着することでどちらか１つだけが使えていたのも印象的でした。

　今考えると、平成１１年８月の事件を起こす前、最後に被告発人大網健二に会ったのは、その時だったようにも思います。夕方でしたが外はすっかり暗くなっていました。ずっと忘れていたのですが、ふと思い出しました。

　その１００満ボルト金沢本店のことでもっと印象的に憶えているのは、平成１４年の年末、２０日頃だったようにも思うのですが、仕事が休みの日に、そこでボイスレコーダーを買いました。そのままKYNの自宅に行き、録音した音声ファイルも再審請求の資料として提出済みかと思います。

　Googleマップの地図をよく見ると、野々市市二日市とは別に野々市市二日市町があるようです。それも小さな一角ですが、あすなろ団地に隣接しています。あすなろ団地は、車で通り抜けをすることがありましたが、知り合いが住んだとか住んでいるという話は聞いたことがありませんでした。

　金沢市には他に、みどり団地と平和町に市営か県営の団地があり、みどり団地は特に大きかったですが、同じく知り合いが住んだとか住んでいるという話は聞いたことがなく、遊びに行くことはありませんでした。Nテックのあれで営業に回ったぐらいです。

　平和町の団地は、県営団地と聞いていたように思いますが、近くを通りかかっただけで敷地にも入ったことありませんでした。これも縁がなかったのですが、唯一、被告発人梅野博之がその平和町の団地に住んでいるという話は聞いていました。

　最近、Googleマップで知ったのですが、平和町の県営団地は陸上自衛隊の駐屯地と隣接しているようです。その辺りは仕事でも余り行くことがありませんでした。ただ、野田専光寺線の道路沿いに自衛隊の門があることは見ていて記憶に残っていました。

　ストリートビューで平和町の団地の中を見ていますが、みどり団地のような大きな建物はなく、比較的新しい建物が多いように見えます。みどり団地は、平成１１年の時点でも、時代を感じさせる古い建物が多く、かなりゴーストタウン化しているという印象がありました。

[link:] » 平和町 - Google マップ https://t.co/FrCiZ1hiK8

<hr />

[link:] » みどり - Google マップ https://t.co/CEXT4EnCWR

<hr />

　どうも、みどり団地では検索もうまくいかず、みどり住宅という表記もあります。関東など行けば遥かに規模の大きな団地はいくらでもあるのだと思いますが、石川県では最大だと思いますし、Googleマップで見た方が、過去の記憶より建物の数が多いようにも見えます。

　少し離れると安原という地名が見えます。KYNにいたMT君の家の住所も安原が付いたのかもしれません。車でもみどり団地からはけっこう離れていて、田畑の道路沿いにある割と大きな家でした。田舎以上に田舎らしいと感じるのは他にもあったことですが、それは裕福そうにみえたとも言えます。

　能登で農家といえば、以前はバカにされるようなこともあり、裕福というイメージとは真逆でもありましたが、金沢の近郊では農家といえば、ほとんどが裕福なお金持ちと聞いていました。まだ田畑が多い時代だったので、そのあと土地を売って儲けた人はさらに多そうな気がします。

　現在では、ブルーベリーなど他の栽培も多いようですし、農家の方がお金持ちのように思えることもあります。天坂のパチンコ店も盛況でした。最近のことは店に行かないのでわからないです。漁業より農業の方が儲かっているような気もしますが、実際のところはよくわかりません。

　農家はバカにされたというより、差別されていたように思います。そういう差別をするのも特定の人が多かったとは思います。今では、そいうのは全く感じることがないですし、普通にどこにでも移動できます。昔は、他所へ行くともめたり危害を加えられる危険も感じたものです。

　平成１８年頃でも、金沢市の近郊は店も道路もずいぶん増えたと感じていました。特に深夜営業の店が多いとも感じていました。昭和５０年代の方が少子化でもなく、若者のの数も多かったはずですが、深夜にやっている店というのは、バイパス沿いでも数えるほどしかなかったと思います。

　金沢へは、昨年か一昨年の１月に、人の用事に同行して少しだけ行ってきました。早い時間に帰っている日帰りでしたし、行ったのも金沢市内の一部でした。その時、数えて、７年ぶりであったように思います。

　裁判官には地方に飛ばされただけで強い不満や不遇を感じる人がいると聞きますが、そのような感覚の違いや偏りというのは、弁護士にも大きいだろうと見ています。それがいいとこ取りの発想や生き方に通じるのかもしれません。

　ミールの仕事についてもう少し書いておきたいと思います。今思い出せる範囲で、平成４年のミール移動では、五高倉庫、清水倉庫、国勝倉庫がありました。国勝倉庫は、ライスセンターのような倉庫で別の名前があったようにも思います。

[link:] » 石川県金沢市才田町 から 〒924-0017 石川県白山市宮永町２０９６−１ - Google マップ https://t.co/cBnA7uwJXa

<hr />

　上記はGoogleマップで浜田漁業金沢工場からの経路を調べたものです。たぶん示された経路とは少し違っていると思いますが、トラックステーションの横から国道８号線バイパスに出て、御経塚の交差点を右折、美川方面に向かい、金石方向からきた宮永の交差点の少し手前、左手に倉庫がありました。

　数年前から北陸自動車道には、白山インターがあるようですが、私は行ったことも見たこともありません。宮永の交差点というのは広い交差点でしたが、当時は片側２車線同士の道路が交わっていたと思います。

　その宮永の交差点から松任駅の近くに出ることもありましたが、そちらの方が狭く田舎の集落を通り抜けるような道だったと記憶にあります。トラックの仕事でたまに通ったことがありましたが、市内配達ではなかったと思います。１つは、松任駅の向かいにある橋本商事でした。

　普通、松任駅に行くにも国道８号線バイパスの野々市町との間にある大きな交差点から右折して向かっていたと思うのですが、なぜか松任の橋本祥路に関しては、宮永の交差点との間の道路を通行したという記憶が残っています。

　当時、どこまでが野々市町で、どこからが松任市になるのかもわかりにくかったです。バイパスから松任駅に向かうと広い道路の右手に新潟運輸の建物がありました。通りかかるだけで仕事で行ったことは一度もなかったです。

　新潟運輸に関しては自社便のみで傭車は使わないと聞いたこともありました。新潟運輸へは一度だけ仕事で行ったことがありましたが、それは新潟市の新潟運輸で、神奈川県か埼玉県から積んだお菓子を持っていきました。関東から新潟というのも他にない珍しい仕事でした。

　有名なメーカーのお菓子だったと思いますが、現在は思い出せません。神奈川県から積むことが多かったと思います。小田原市からというのも一度ありました。「あずまうんそう」か「あずまうんゆ」の仕事で、その会社に電話して指示を受けることはありましたが、他にわからない会社でした。

　あずま、というのも漢字で東や吾妻が考えられます。東京に行った時の帰りにだったので、東京の会社なのかと想像したこともあったのですが、よくわからず幽霊会社のようなイメージもありました。都内だと電話番号でもわかった気がしますが、まあ、不思議には思っていました。

　金沢市場輸送では、東京ストアの定期便がありましたが、それ以外は帰り荷が余りなく、空車で帰ることも多かったように思います。定期便以外では、スルメイカとタケノコの時期に集中して東京に行きました。九州から鮮魚で築地に行くこともけっこうありました。

　冷蔵庫から冷凍物や冷凍食品を積んで帰ることもありましたが、空車だと高速代が出ず、それもぎりぎりまで待たされるので、出発の時間も遅れがちでした。ほとんどは国道２０号線から山梨、松本、大町、糸魚川というルートで帰りました。とても嫌な仕事のパターンでした。

　なお、金沢市場輸送の給料というのは平成２年の春ぐらいまで、距離の歩合が固定給に上乗せとなっていましたが、その距離というのは、少しでも荷物を積んで走る距離と決まっていました。空車は歩合なしでしたが、満載でも近場だと歩合はわずかでした。

　他に内容な変わったシステムでしたが、これは社員の運転手の間で不公平や不満も生じさせやくなっていたと思います。極端な場合、展示会の荷物でしたが、茨城県水戸市のデパートから栃木県宇都宮市のデパートまで荷物を運んだというのもありました。１００キロなかったと思います。

　私は、余り考えずに割り切って仕事をしていたのですが、その分、割の合わない仕事もよく回ってきていたようです。それでも荷物を運んだ距離だけで月に１５０００キロ以上ということもありました。大手運送会社は月に７００キロぐらいと聞いていました。

　荷物を運んだ距離なので、積み込み先や卸先が多い仕事でも歩合は同じでした。当時は深く考えなかったですが、不満や不信感、軋轢を運転手の竹沢俊寿社長、会長の計算高い狙いであったようにも思えます。なお、併記は被告発人松平日出男と本恒夫が社長になった時点での会長職です。

　東京から空荷の空車で帰るときも、労いや謝辞というものはなく、それどころか挑発するような物言いが決まって感じられました。このスタイルは高島の北浜太一さんが配車の時から感じていたように思います。本来は帰り荷を探すのも配車係の仕事のはずですが、攻撃的でさえありました。

　そういうことも積み重ねで余り自覚のないトラウマのようになっていたのかと思います。下道だと運行の時間も長くなりましたが、不愉快な思いも長引きました。一番、本恒夫ともめたのは、茨城県鹿島市から空車で帰った運行でした。古河市で国道４号線を横切ったのが夜の１１時ころだったとも思います。

　どの道を選んで帰って来たのか憶えていないですが、自腹で高速道路は絶対に使わないというのも当時の自分のこだわりとして徹底していました。関越道を全部使っても、古河からは普通に５，６時間掛かりそうな気がします。２３時とすると金沢に戻るのは未明の４時か５時になります。

　その翌日というのも休みではなく運行があるのが普通だったと思います。今風に言えばブラックだったのだと思いますが、金沢市場輸送の仕事は内容が多彩で変化もあったので、勉強や修行になるようなところもあり、達成感や充実感というのもありました。

　鍛えられたという点では中西運輸商の方が身につき得たものも大きかったと思いますが、鮮魚の仕事などしていると初めていく市場でも道を間違えるととんでもないことになります。それだけ張り詰めた緊張感と集中力もありました。

　普通に運転をしていても昼と夜とでは条件が違うと思います。県内と県外とでは安心感も違いますが、市内配達の仕事をなんなくこなせ、高い評価を受けたのも、そういう過去の積み重ねや経験値があったからだと思います。この評価は本来、被害者安藤文さんとの関係にも大きく影響しているはずです。

　同じ鮮魚の仕事でも、金沢市場輸送の東北便は特に混載で、卸先も多かったです。練り製品や貝類、北海道からの中継の荷物も多かったので、慣れない人はずいぶん大変そうにも見えました。大型車と市内配達の２t車では、扱う量も違いますが、時間に追われることもなく楽に仕事が出来ました。

　北都運輸の市内配達の仕事をしていたことも書いていると思いますが、そちらは４トン保冷車でした。金沢市内は空襲がなかったので、全国的にも道幅が狭いところが多いと聞いていました。それでも混雑した夜の市場の場内に比較すれば、さほど苦に感じることはなかったです。

　大型車の運転手は、小型のトラックや市内配達の仕事をするのがかっこ悪いと嫌がる人が多かったと思いますが、似て異なる共通性のある仕事は、なんでも出来た方が自分の力になるし、役に立つという考えでいました。こだわりはなかったです。

　そういう運送業界も、当時とはずいぶん変わったと聞いています。運送業界の実態を聞く話し相手はほとんどいませんが、金沢から魚釣りに来ていた人に話を聞いたり、他はテレビで情報を見ました。

　運行管理が厳しく、トラックはリミッターの装着で物理的に速度超過が出来ないとも聞いています。私の頃は、大型トラックでも高速道路で１４０キロのメーターを振り切って走行するのが当たり前のような状況でした。平均で１２０キロという感覚でした。

　乗用車の平均速度は安定できると思いますが、大型トラックでは高速道路でも勾配がきついと最高速度が３０キロまで落ちました。６０キロぐらいはもっと多かったと思います。積み荷の重量もありますが、重量オーバーというのもほとんど当たり前でした。

　犯罪者ではなかったですが、常に警察には捕まる可能性のあることを意識しながら仕事をしていました。捕まることより、重大事故を起こしてしまうことをさらに注意していました。家族連れの乗用車に追突すれば取り返しのつかない事態になることは日頃考えていました。

　一度、本当に危ない思いをしたことがありました。中西運輸商の大型保冷車でしたが、中国自動車道で３車線となった長い下り坂を降りてきた時、カーブの先に渋滞の停車がありました。すぐにスピードは落とせず、速度を落とした車の間を縫うことで、安全に停車させることが出来ました。

　当時のトラックというのは、メーカーや個体によってもブレーキの効き具合がまるで違っていました。ブレーキパッドが焼けて白煙が上がるというのも、何度か経験したことです。重量を積んで急で長い下り坂を降りる時は、とくに神経をすり減らしました。凍結だとなおさらのことです。

　私の場合、どんなに気をつけていても運が悪ければ重大事故を起こし、会社の評価も一変するだろうという考えがありましたが、さいわいそのような事故を起こすことはありませんでした。また、その事故の心配がピークに達したのも、傷害・準強姦被告事件の大きな要因です。

　時刻は20時19分です。今日は夕方前の早い時間にテレビを消して、まだ一度もつけていません。夕食もこれからです。いろいろと気になることや、取り上げておきたいこともあるのですが、告訴事件の事実関係を優先させています。

[link:] » 金曜プレミアム - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/xPtLiNK40U \n 金曜プレミアム・日本一のものまね王者が今夜決定!ものまね王座決定戦 \n 2018年11月30日（金）  19時00分～22時46分  の放送内容

<hr />

　さきほど初めて今夜のテレビの番組表をみたのですが、「ものまね」の特番をやっているようです。時間も19時から22時46分と長いようです。最近は余り見なくなっていたのですっかり忘れていましたし、前に見た時は時間も短かったように思います。

　まだテレビは付けていないですが、「ものまね」を見ると、刑務所の生活を思い出すことが多いです。よく放送されていました。当時は放送回数自体も多く、人気も高かったのかもしれません。

　テレビをつけると、CMかと思い、少しして、巨大生物というCMが始まり、旭硝子と出ていました。初めて見るCMです。どうも最近は生物とみるだけで、理解を超えた存在感として弁護士のことが頭に浮かびます。有害性や社会汚染を含めての問題意識です。

　五高倉庫と清水倉庫については、また別のところで書きたいと思います。五高倉庫については、平成4年3月の静岡県清水市の運行とつながりがあります。そこを転機として4月1日の傷害・準強姦被告事件に発展したという事実関係のつながりもあります。

　清水倉庫については、平成4年2月を中心とした被告発人安田敏の異常行動の1つがあります。現在は記憶が薄れ時期の特定も困難となっているので、過去の記述を調べ、引用などしたいと思います。市川タイヤのこともです。

　いちおう異常行動と書いておきましたが、計画された演出、演技の可能性の高いものです。当時は確かに異常にも思え、混乱したり影響も受けたので、外形的な事実関係として異常行動としました。彼の場合は、シンナー中毒での異常行動や精神病院への入院もありました。免罪符としての利用も想定です。

* 殺人未遂としての告発事件の舞台である市場急配センターのホームページの今も変わらぬ代表者堂野俊一、と金沢港のイワシの運搬

[link:] » 市場急配センター株式会社│トップページ https://t.co/Opy0jDra7a

<hr />

　上記のページタイトルは「トップページ」となっていますが、実際は「会社概要」というリンクをクリックしたページです。http://www.kyuhai.jp/profile.html がURLです。

　トップページはindex.htmlというファイル名ですが、これはＷｅｂサーバーで、ページの指定がないときにも表示される仕組みとなったページです。ドメインの真下にあるサーバ上のディレクトリなので、ドキュメントルートとも呼ばれていたかと思います。まさにトップページです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-11-30 21:08／2018-11-30 21:00 URL： https://twitter.com/kk_hirono/status/1068476879202480130 https://twitter.com/s_hirono/status/1068474963173097472
&twitter(1068476879202480130){theme:light}
> 2018-11-30-205251_市場急配センター株式会社│トップページ.jpg https://t.co/gPvJ0Cs1qx
◁◁◁
<hr />

　これまで何度か記憶しているスクリーンショットの最新です。ざっとみたところずいぶん前から変更や更新は見当たりません。

　これまでに何度も断りをしていると思いますが、私が知る、一緒にイワシの運搬の仕事をした堂野さんと、市場急配センターのホームページにある代表者堂野俊一という人物が同一であるという確認は出来ていません。しかしながら社長にまでなった経緯に鑑み疑いの余地はないほどと考えます。

　しかし、同じ姓名ということは親戚や兄弟として市場急配センターに入社し、その後、社長になったという可能性もあり得ないことではないような見方もあるかと思います。堂野というのはそれほど珍しい名前でもない気がしますが、私の知る人は少なくとも他にはいません。

　平成10年11月20日ころ、市場急配センターの事務所で、休日に被告発人松平日出男と事前に日時を取り決めた会見で、労務の責任者として話を聞く、と言って同席したのも私の知る堂野さんでした。その場では、「かたわと結婚したいてかぁ？」という発言まで堂野さんからはありました。

　事前に取り決めていた時刻は13時半か14時だったと思います。2,3日か前に、少しずらした時間だったように思いますが、被害者安藤文さんの父親である安藤健次郎さんにも電話で、その場に来ることをおすすめしていました。

　それは、マルエー間明店前の電話ボックスからの電話であったとも思います。午後の比較的早い時間であったようにも憶えています。11月も半ばを過ぎていたので日の暮れる時間も早かったと思います。

　それだけではなく安藤健次郎さんが部長をしていた松任市の旭工業団地内の西鐵工所へは、夕方の18時半か19時以降に電話をするように言われていました。平成9年9月以降は、少なくても月に1,2回は電話をしていましたし、電話ぐらいいいとも言われていました。

　マルエー間明店は、現在でも同じ場所にあるのではないかと思います。このマルエーというスーパーは、昭和61年の時点でも金沢市場輸送の市内配達が早朝に配達をする唯一のスーパーチェーンでした。平成3年にはさらに店舗数も増え、加賀市の片山津店なども出来ていました。

　片山津店には被告発人梅野博之が配達を担当しているという話も聞いた覚えがあるのですが、私も1回は配達に行ったことがありました。しかし、間明店の方は一度も配達に行ったことがなかったので、店舗としても新しい方なのかと考えていました。

[link:] » （株）マルエー まぎら店 - Google マップ https://t.co/JaZMpSVMUw

<hr />

　間明は、金沢市に住んだことのある人以外に読める感じではないのではと考え、その旨書こうと思っていたタイミングでしたが、Googleマップの店名は平仮名で「まぎら」と出てきました。

　正直なところ店の場所は、同じ野田専光寺線沿いでも間明の陸橋を渡った先のようにも考えていましたが、陸橋の手前側でした。黒田一丁目から橋を渡ってきた大きな交差点の角でもありました。この交差点の手前の右角には、オメガ間明店というパチンコ店がありました。

　いえ、オメガ間明店があったのは交差点手前の左角だったかと思います。橋を渡ってすぐに北陸名鉄運輸金沢支店がありますが、これは昭和59年当時も同じ場所にあり、金沢市場輸送の大型保冷車が九州各地の荷降ろしで鹿児島まで行くという定期便をやっていました。積み込みの手伝いで行きました。

　間違えた間明町の交差点の手前右側には、日産のディーラーの工場があったはずです。同じ小棚木の1つ上の先輩もそこで仕事をしていましたし、同級生も就職していました。寮が武家屋敷で有名な金沢市長町にありましたが、路地が狭かったこともあり、建物の中にまで入ったことはなかったです。

　マルエーまぎら店の向かいは、現在、クスリのアオキ間明店となっているようです。この場所には、マカオというパチンコ店がありました。黒田一丁目のKYNの配管設備の自宅兼会社にに通勤していた頃も、その店でパチンコやスロットをしたという憶えがあります。

　他のパチンコ店では余りみかけないダイヤモンドのような図柄のあるパチスロ機があったことが記憶に残っています。金沢市内では珍しくなっていた、ずいぶんと懐かしい昭和の面影を残すパチンコ店でもありました。

　オメガ間明店は野田専光寺線をはさんで向かいになっていましたが、金沢市場輸送で大型車の長距離運転をし、妻子と近くの東力二丁目のアパートに住んでいた頃は、そのオメガの方にはちょくちょくと行っていたのですが、マカオの方はほとんど入ったこともなかったように思います。

　昭和63年だったとも思いますが、そのオメガ間明店が休店となりました。リニューアルオープンの工事のための休店と聞くこともあったのですが、店はそのまま復活しませんでした。パチンコ店の閉店というのは初めて見たもので、パチンコ店はすごく安定した仕事というのも当時の常識でした。

　時刻は23時23分です。深夜番組で0時を過ぎているのかと思っていましたが、さきほどからテレビではオリエンタルラジオの藤森という芸人が出ています。ストーカー、そして今は違法薬物をパロディのようにしていますが、ずいぶん久しぶりにテレビで見た芸人です。

　見た感じは、数年前とほとんど変わりがないように思いますが、二人組の相方の芸人の方は出ていないし、同じくずいぶん長い間、テレビでは見ていません。すっかり忘れていたことにも気がついたのですが、なぜかこの芸人を見ると、金沢市間明のことが頭に浮かんでいたようにも思います。

　たぶんオリエンタルラジオのオリエンタルという部分が、間明あたりで見た看板にあったような気もしないではありません。オリエンタルカレーというのも、つい2,3日前にスーパーで見かけ、懐かしい気がしました。余り食べた記憶もない商品ですが、記憶には残っていました。

　マギラ、というのもマカオに似ていますが、多分その辺りの語感からオリエンタルというイメージがつながっていたのだと思います。オリエンタルという言葉の意味も調べないと正確にわからないですが、東洋とかそういうイメージで東洋でありながら西洋のような地名のマカオに向いていたのだと思います。

　Googleで検索すると、オリエンタルはそのまま東洋という意味のようです。詳しくは調べませんが、私の中では東洋でもヨーロッパの西洋人から見た東洋というイメージや文化があります。マカオはイギリスの植民地だったとも思います。香港も返還されてから30年経っているのでしょうか。

```
ポルトガル植民地であったマカオは、イギリス領香港と同様、１９９９年に中国に返還され、一国二制度が導入された。

　ポルトガル植民地のマカオは１８８７年に正式にポルトガルに割譲され、その植民地として第二次世界大戦後も続いていた。

［source：］マカオ返還 https://www.y-history.net/appendix/wh1702-052.html
```

　少し調べて引用しました。マカオはアメリカのラスベガスに近いぐらいギャンブルの街というイメージがあったのですが、ポルトガルの植民地であったというのは意外でした。そうかと思っていたのですが、香港とは同じ年に返還されたらしく、それが1999年となっています。

　1999年は平成11年かと思います。私の人生では大きな転換点ともなりましたが、テレビで報道を見ていたような記憶がかすかにあるので、8月12日に金沢中警察署に逮捕される前のことかと思います。

　上記のページを読み進めると12月20日とありますが、実現のその前に大きなニュースになっていたと考えられます。少なかったとも思いますが、金沢刑務所の拘置所でもラジオニュースはあったので、変換当時のニュースを聞いていた可能性は高いかと思います。

　歌謡曲もそうでしたが、拘置所や刑務所の生活では、外から入る情報が限定されている割に、他に選択肢がないので、あまり関心のなかった特定分野の情報を知るということはありました。自由な生活ほど選択の自由度も大きくなるので、偏る傾向も強いのかと思います。一般論として。

[link:] » 金沢市西部衛生センター - Google マップ https://t.co/8QfrWpUSjX

<hr />

　間明からGoogleマップを少し移動させました。住所は金沢市東力町ハと表示されています。私が住んでいたのは東力二丁目でした。周辺を見ると少なくとも東力4丁目まではあるようです。東力3丁目というのは本恒夫の家があると聞いていた場所の辺りです。

　ただのゴミ処理場の1つという認識しか当時はなかったのですが、この「金沢市西部衛生センター」についても前々から書いておきたいことがありました。別の関連として取り上げたいと思います。

[link:] » 文苑堂TSUTAYA 入江店 - Google マップ https://t.co/PDk6AkNoIk

<hr />

　入江店となっていますが、住所は金沢市東力4丁目236です。被告発人安田繁克の住所は供述調書にも記載がありますが、この文苑堂TSUTAYA 入江店の駐車場の奥の方に家があるとは、平成4年当時に聞いていたように思います。近所ということもあり、だいたいの場所は把握できていました。

　被告発人安田繁克の母親というのも、その近くでスナックを経営しているか働いていると聞いていました。平成4年当時少なくとも東力にはスナックがなかったように思いましたし、入江かもう少し離れた間明にスナックがあるのかとは想像していました。

　なにか規制があったのかどうかわかりませんが、東力では店自体が少なく、ガソリンスタンドと食品もおいたタバコ屋があるぐらいでした。目立たない場所でしたが、食堂も1つありました。松本か松元食堂でしたが、現在も同じと思われる場所に「まつもと食堂東力店」があるようです。

[link:] » 食堂まつもと東力店 - Google マップ https://t.co/aFyUA3X9lT

<hr />

　私が住んでいた金沢市東力2丁目28の4という住所であったと思うアパートは、更地となっているようです。Googleマップは下部に2018年とありますが、月日は出ていないようです。

　2,3年からもっと前になるでしょうか、その時は建て替えられたアパートの建物が表示されていました。新しい建物に見えました。更地にする必要があったとも考えにくいのですが、火災でもあったのかとも思いを巡らしてしまいます。

　周辺を見ると、田畑というのは少なくなっていますが、それでも少しは残っているようです。ほとんどが住宅地であるというのも変わりがないかと思います。近くにはナルックスというスーパーも出来ているので、不便も少なそうですが、それだけ地価が上がっているとも考えられます。

　被告発人安田繁克の母親が愛人と聞いたのが松浦さんでした。下の名前まで思い出せないですが、二文字で上が健だったように思います。イワシの運搬の中心的な人物でしたが、名前の漢字を見たのも、作業日報のような書面だったと思います。これは運転手の作成するものではなかったと思います。

　金沢市場輸送の長距離や市場急配センターの市内配達でも伝票と呼ばれた受領書とともに作業日報を提出するのが決まりとなっていましたが、イワシの運搬場合は、運転手の自己管理がなかったように思います。

　それでも松浦さんの場合は、金沢市場輸送の社員とも聞いていなかったし、一年中、金沢市場輸送の仕事をしているわけでもなかったので、特別な契約か請負のような形態であったものと考えられます。

　そういう金沢港での現場の管理をしていたのも市場急配センターの社員になったと聞いていたKKさんの仕事で、彼はウサギの絵が描いてあってラビット号と呼ばれた、けっこうポンコツのワゴン車でいつも現場にいましたし、私も同乗して雑談をしているのが多かったです。

　そんなときに、帳簿のようなものをみて、松浦さんのフルネームを見ていた可能性はあると思いますが、堂野さんについては、はっきりと記憶にないですし、当初は腰掛けで一時的にしている仕事だと思っていました。

　堂野さんがイワシの運搬の仕事をするようになったのは、私の2度目のシーズンの途中でした。途中でも終わりの時期に近かったようにも思います。具体的には、早めに幅を広げても平成2年の1月から2月のことだと思います。

　言葉遣いも含め丁寧な物腰の人でしたが、元プロボクサーで、名古屋で暴力団組長のボディガードをしていたとも聞いたので、現役のヤクザ者とは思いませんでしたが、それなりの交流もある裏社会に近い人なのだろうとは考えていました。

　松浦さんの紹介で仕事をするようになったとも聞いていましたが、それほど仲良くしている様子を見たことはなく、友人としてはタイプが違うようにも見えました。松浦さんも元ヤクザとは聞いていましたが、現役のヤクザ者以上に、それらしい行動をすることもあり、価値観をお持ちの様子でした。

　わかりやすく言えば、昭和のヤクザ映画の仁義ない闘い、などの世界観です。そのような古き良き時代の価値観を大切にしたので、ヤクザ者としては大成しなかったように思えました。昭和57年頃の時点で、ヤクザ者はこれから経済性のある方が大きくなると言われていた時代でした。

　そのような新しい価値観から見ると、被告発人松平日出男こそヤクザ者であることも感じさせず、関係性をうまく利用した成功したヤクザ者に思えることもありました。被告発人松平日出男本人も、ヤクザや右翼にも顔が利くなどと、少し子供をからかうような言い方でしたが、自慢もしていました。

　被告発人松平日出男の身体的特徴としては、小柄の割に体格は少し幅広で、さらに体全体における顔面を含めた頭部の割合がかなり大きいというのがありました。江戸時代のやり手の薬売りや商人としても出てきそうなタイプでしたが、他には余り見かけない特徴でした。

　最近になってその特徴に似ていると思ったのが、今、検察庁との関係でも大きく注目されているカルロス・ゴーン氏です。ゴーン氏のような鷹の目のような鋭さというのは被告発人松平日出男にはなかったですが、逆に内に秘めた不気味さというか凄みのようなものを感じることはありました。

　被告発人松平日出男が金沢市場輸送で市内配達の責任者のような立場で仕事をするようになったのは、昭和63年の8月の終わりか9月の初めのことです。この時期というのは、7月の初め頃に、金沢市場輸送の事務所が移転していたこともあるので、誤差はあっても僅かなはずです。

　被告発人松平日出男は、トラックの運転をしているのも見たことがなかったし、運送や配達の仕事はずぶの素人だったのだろうと思いますが、商才と人脈はあったのだろうと思いますし、話術も巧みな感じでした。

　これは被告発人大網健二とも共通していたことですが、運が良かったのか、転職を機に、世にいうバブル景気の波に乗って上昇したというところも大きかったように思います。付け加えると本恒夫も同じになります。

　本恒夫が金沢市場輸送で運転手から配車係をするようになったのは、藤村さんの入院がきっかけでした。なにか手術をするという話を聞いていたように思いますが、体のどこが悪いということまでは話になっていなかったとも思います。

　これも昭和62年の12月頃のことで、ちょうどその頃に入社したと記憶にあるのが、被告発人池田宏美と被告発人梅野博之でした。当時は池田ではなく、吉村という名前だったようにも思います。再婚で名前が変わったと聞きましたが、本人は3,4回目の結婚とも後に話していました。

　時刻は12月1日12時57分です。金沢市場輸送でイワシのダンプに乗っていた堂野さんについては、また書くことがあります。ダンプは持ち込みだったので金沢市場輸送の社員というわけではなかったと思います。

　ずっと前には書いていると思いますが、金沢市場輸送では保冷車の仕事でも、社員をやめて持ち込みトラックとして仕事をする人が出てきました。ざっと思い出すところ、大型車の保冷車でで4人、4トンの保冷車が一人でした。ミールの運搬にもいたようなですが、詳しくは憶えていません。

　私と中西運輸商で一緒だったYTの姉の夫という人でした。必要最低限しか会社に顔を出さない人だったので、私は言葉を交わす機会はほとんどなかったように思います。YTの父親もその後、イワシの運搬の仕事をしていたようなので、堂野さんとも付き合いがあった可能性はあるかと思います。

　堂野さんも会社には余り顔を出さず、金沢港の現場中心で仕事をしていたと思いますが、金沢市場輸送でほとんど毎日のように夕方から行われていた麻雀には、よく参加する姿を見かけたと思います。

　配車係をしていたYTも途中から麻雀をするようになっていましたが、やったことのなかった麻雀をその場で覚えたという話でした。YTと藤田さんが金沢市場輸送にいたのは平成2年の6月までだったと記憶にあります。

　7月ではなかったと思うのですが、YTは、片山津温泉ホテルながやま、で開かれた慰安会に出席していました。あとで、坂田さんともめたとかケンカになりかけたという話を聞いたので、よく憶えています。

　その片山津温泉ながやま、ですが、以前はホテル長山と書いていたように思います。確認するためGoogleマップで調べると現在は、「大江戸温泉物語　ながやま」となっているようです。建物までは見ていないですが、場所はだいたい合っていると思います。

　片山津温泉の中心部からは離れた場所にありました。前に書いていると思いますが、姫のNKさん、大谷のYSさんらと金沢市場輸送の輪島の運転手がケンカになったという話でした。部屋で寝ていたところを起こされて輪島の連中と一緒に帰ったのですが、怪我をした様子はなく不思議に思っていました。

　また、その時点では、市場急配センターに被告発人HTNの姿はまだありませんでした。姿はその半月から一月後ぐらいだったと思います。仕事の相談をするのに私のアパートに電話をしていたという話を聞きましたが、前妻が姫のNKさんと勘違いしていたというような話もありました。

　前妻に聞いたところ、勘違いしたような様子はなく、どちらとも以前に面識はあったはずで、声などもずいぶん違うので、それもずいぶん不思議というか不可解な話だとは考えていました。

　安藤文さんの姿も、片山津温泉ホテルながやま、の慰安会にはありませんでした。その頃には、市場急配センターの事務員らしいと知っていたように思うのですが、参加がなかったので、来なかったのだろうと思っていました。

　堂野さんのダンプですが、土砂積み禁止車両にしては、ずいぶん小型でした。トラック野郎の映画にも出ていたような古い型の三菱ふそう、の大型車でした。色の関係なのか、キャビンという運転席の車体の部分も、通常の大型よりは小さく見えました。

　色というのはワインレッドのような単色でした。私も経験があるのですが、少年時代バイクのタンクなどにラッカースプレーで色を塗りました。まさにそんな感じの塗装でしたが、他に4t車でも見たことのないような手作り感のある塗装でした。

　土砂積み禁止のダンプで多いのは、木材のチップを運ぶダンプです。物が軽いので荷台がずいぶん大きいのがほとんどです。特定の場所は区間でないと滅多に見かけないダンプかもしれません。扱う業者もかなり限られると考えられるからです。

　金沢市場輸送の2台のダンプは、その木材チップを運ぶダンプに近い荷台の大きさがありました。一度に積めるイワシの量も平ボディ車よりは安定して多かったです。だいたい総重量で見ることが多かったですが、平ボディ車では最高で43トンぐらいだったと思います。

　イワシの状態によっても重さは、けっこう違っていました。新鮮なものほど比重が低く、傷んでクタクタになったようなイワシは重くなっていました。ダンプの場合だと、47トンほどあったように思います。48トンぐらいかもしれません。それも荷台が高い分、安定した重さでした。

　私のような社員の運転手は固定給もあったので歩合は大きくなかったように思うし、余り気に掛けることもなかったです。しかし、他の車輌持ち込みの運転手は、積んで運んだ重量が売り上げの全てだと聞いていました。

　運搬するイワシは、金沢港の堤防のすぐ先で漁ができることもあれば、イワシを探し求めて、京都府の舞鶴沖や大和堆まで行くと聞いていました。大和堆は、近年、北朝鮮の違法操業で全国ニュースにもなっていますが、当時は他に聞くことがなく、私は場所を間違えたまま記憶していました。

　金額の方は正確に思い出せなくなっていますが、北陸ハイミールでは機械を動かすだけで100万円掛かるというような話でした。イワシの原料が切れれば、その機械を停止させることになります。

　そういうこともあったので、イワシが捕れだすと、ぶっ通しの仕事となりました。ダンプやトラックの荷積みの順番待ちの時間もあるので、体は休めたと思います。拘束時間が2,3日と続くことがありましたが、長距離の仕事に比べれば、地元なのでやりくりできる時間もありました。

　船が遠いところにいると、何時間後までは仕事がないという見通しも立ちました。逆に近いところにいると、待機のような状態が長く続きました。昼夜関係なしの仕事でしたが、それほど負担には感じませんでした。中西運輸商では25日間、家に帰らなかったこともあるぐらいです。

　ダンプの場合は、レバー操作だけで確実に荷降ろしができるという利点もありました。平ボディ車の場合は、トラックを前後に動かし、急ブレーキを掛けることで、イワシを落とすという原始的な方法でした。下に溢れることもあり、その片付けに時間が掛かることもありました。

　はっきり言ってかなり汚い仕事でもありました。その場で刺し身に出来るほど新鮮なことも多かったですが、潰れてヘドロに近い状態になっていることもありました。それでもミールの製品の出来上がりには違いがないという話でした。

　金沢市場輸送の会社には洗車機がありました。高圧洗浄の機械です。イワシの運搬の仕事はトラックに脂や泥がこびりつくので、普通の洗剤できれいになることはなく、苛性ソーダというものを使っていました。

　ダンプの運転手が洗車をしている姿は、余り見なかったのですが、まあ、私がいないときにやっていたのかもしれません。基本的に、ダンプの運転手が会社に来るという用事も、洗車ぐらいだったとも考えられます。

　金沢市場輸送の保冷車の仕事で金沢港に行くのは、毎年6月頃のスルメイカの時期以外は、ほとんどなかったと思います。金沢港には大きな冷蔵庫のようなものもありませんでした。

　そういうこともあるので、自分が金沢港のイワシの運搬の仕事をしなくなってからは、その仕事をしている現場の様子というのは、たぶん一度も見たことがなかったと思います。

　堂野さんの姿もずっと見ていなかったうようにも思いますが、さきほども書いたように麻雀をする姿はありました。麻雀は4人でするものですが、たぶん麻雀の台は一つだけだったと思います。電動で動く店にありそうな機械でした。

　一度に麻雀を出来るのは4人だけになりますが、その周りを数人が取り囲んで、大相撲の観戦でもしているかのように、真剣に後ろから見ていました。たまに雑談をするような人もいたと思いますが、本当に愛好家の集まりという感じでした。

　被告発人松平日出男の姿もちょくちょく見ていたように思いますが、中には会社とまったく関係のなさそうな人の姿もありました。あるいは市場急配センターの市内配達の運転手で、たまたま仕事をしているところを見ていなかったという可能性はありますが、本当に無関係だったとも考えられます。

　ゼンゴと呼ばれた人物のように、麻雀をしていてから、そのあと少し金沢市場輸送の仕事をした人もいましたが、いつもの見慣れた風景となっていたので、余り深くは考えず、長距離トラック運転手の仕事柄、毎日、会社にいたわけでもないので、見ていたのもごく一面だったのかもしれません。

　長距離トラック運転手の仕事では、当日、運行に出ないことを「あがり」と呼んでいました。17時だったように思いますが、その時刻までは会社にいることになっていました。私の場合、夕方の渋滞がいやだったので、18時過ぎまで会社に残っていることが多かったとも思います。

　17時か、あるいは17時半が会社の定時となっていましたが、その時間になると、本恒夫が事務所の方から、そそくさと出ていて、待ちかねたように麻雀の準備のようなことを始めていました。

　だいたい22時か23時頃まで麻雀をやっているような話でした。ミールを積んだ名古屋方面への出発では、そういう時間に会社に行き、麻雀をやっている様子を見ることもありました。そんな時間に麻雀を終えてから運行に出発する運転手もいたわけです。

　前に書いたと思いますが、最後に堂野さんと会ったのは、平成4年に入ってからのことで、群馬県の火薬工場でした。ちょうど私が荷降ろしを終えた頃に入ってきたので、すれ違いのような状況でもあり、会釈だけか、ほんの少し言葉を交わしただけだったと思います。

　過去の裁判の書面には、細かいことを克明に記していると思いますが、私はけっこう長い間、松浦さんの愛人の女性と、堂野さんの愛人の女性を取り違えていたように思います。話を聞いた時、愛人という言葉だったのでそのまま使っていますが、本当は妻以外の交際女性のことを愛人と呼ぶのかと思います。

　松浦さんには2人の小さい子どもがいましたが、戸籍上のことはわかりませんが、離婚したような状態だったと考えられます。同じく堂野さんについても、実際のことはわからなかったですが、妻子がいる、家族がいるという話は聞いたことがありませんでした。

　独身者の交際女性であれば、単に彼女などとい言うのが今風に思えますが、私にその話をした人は、愛人の意味も誤解していたのか、私には愛人として説明をしていました。

　松浦さんについては、書き忘れがありましたが、竹沢俊寿がヤクザか土建屋をしていたときに、自分のところに来たがすぐにいなくなった、という昔話をしていました。竹沢俊寿には他に、日通の幹部社員をしていたような話もありました。

　金沢市場輸送については、昭和59年に初めて入社した当時、以前は中央市場の正門の向かいの派出所の辺りに事務所があった。竹沢俊寿がつぶれかけた運送会社を買い取ったらしい、というような話は耳にしていました。

　その頃、金沢市場輸送で最古参の運転手と言われていたのが、本恒夫でしたが、それでも入社から8年と聞いていました。以前は、被告発人、被告訴人に含めていた本恒夫ですが、私の記憶も薄れ、容疑も親告罪ではないので、刑事手続からは外していますが、重要な接点を持つ人物に変わりはありません。

　昭和59年というのは、4トントラックにもエアブレーキがつくようになった時代で、金沢市場輸送の古い4t車では、パワーステアリングではない思いハンドルのものもありました。トラックの性能や外観も大きく変わりつつある時期であったと思います。

　本恒夫については、昭和61年から63年の間辺りに、48歳とか聞いたような気がします。年齢を疑うことはなかったですが、当時の年齢の相場からは、かなり若く見ていました。昭和59年当時は、50歳の長距離トラック運転手は珍しい、引退すると聞いていた時代でした。

　堂野さんの年齢というのもはっきりとは聞いた憶えがないですが、初めに会った平成2年の時点で40歳台前半という認識でした。30歳代とは聞かなかったですが、金沢市場輸送では、20代と40台以外は、すごく例外でした。渡辺さんだけが30代と聞いたように思います。

* 金沢市場輸送で配車係をしていた藤田博巳さんと、佐川急便、名前をはっきりおもいだせない津幡町の運送会社、被告発人松平日出男との関係性

　津幡町にあったと思われる運送会社の名前は、Twilog、はてな、の方を検索しても見つけ出すことが出来ませんでした。話し言葉では「きょうとも」だったように思います。当てはまると思われる感じは、協、共、共、友です。よく見る感じ２つの組み合わせだったことは間違いありません。

　石川県では類似した会社名に「共立自動車」、「共栄運輸」というのがありました。「とも」は、共と友、以外に思い浮かばないのですが、友ということはなかったように思います。ほとんど会話での耳からの言葉だったので、漢字は余り見る機会がなかったと思います。

　一度、車での通りかかりに、それと思われる会社を見たことがありました。河北郡津幡町でも、能瀬という地区の辺りだったと思います。高架の道路上から昼に見下ろすような感じで、その会社を見たような場面が記憶として残っています。

　平成14年11月から平成21年3月にかけ羽咋市に住んでいる頃も、その道は通ることがありました。平成11年に見たような気もするのですが、その頃は余り通る道ではなかったと思います。

　金沢から能登方面には、金沢東インターのトラックステーションの辺りから才田町を通る農免道路で、宇ノ気に出ることが多かったのですが、津幡町から能瀬を通って宇ノ気に出る道を選んだのは、プラント３といった大型ショッピング店で買い物に立ち寄る目的があったからです。

　道路の方も良くなり、宇ノ気の先は金沢までほとんどが高架の自動車専用道路のようになっていました。

[link:] » 能瀬 - Google マップ https://t.co/BlVp4wbqYz

<hr />

　Googleマップだと枠線で能瀬の範囲が一目瞭然ですが、横に広がり、国道１５９号線沿いの区間は短いようです。その国道１５９号線も複数の道路が束になっているように見えます。平成４年当時は、対面通行のただの国道だったと思います。

　英田郵便局が目に入って、すぐに思い出したのですが、その辺りには英運送というような運送会社があったように思います。車両台数も多かったのかよく見かけるトラックでした。誰に聞いたのか、何で見たのか思い出せないですが、英は「はやぶさ」と読んだように思います。

　英運送について調べたのですが、古い情報だけ残っているのか、それも能瀬には近いものの、国道からはかなり外れた山間の集落のような場所でした。その英運送の会社も国道１５９号線に見たような記憶があります。

　きょうとも（仮）運送の近くだったような気もしたのですが、会社自体が見当たりません。束のように見える新しい道路は、津幡バイパスということがわかりました。国道８号線とは立体交差で分岐しているようですが、こういう道路が出来ていたのも今回初めて知りました。

[link:] » 津幡検問所前 - Google マップ https://t.co/36gF92FxI4

<hr />

　平成４年当時の名残を残す手がかりは、上記の津幡検問所ぐらいかと思います。現在は県道２１５号線となっているようですが、これが国道８号線だったと思います。

[link:] » 八幡のすしべん 津幡店 から 津幡検問所前 - Google マップ https://t.co/onrKPL0bU5

　もう一つの手がかりが上記の、八幡のしすべん津幡店です。この検問所と「八幡のすしべん」の間の、向かって右側辺りに、平成４年５月２８日に金沢西警察署で出会ったSが住んでいると聞いていました。アパートで女子大生と同棲し、とび職の仕事をしているかしていたと話していました。

　ご覧の通り、津幡町の中心部からは外れていますが、特定された情報として私の記憶に残っています。平成３年の秋のことですが、そのSには、１万円の借金を頼まれ、そのまま踏み倒されました。信用させるために特定した住所などを話していた騙しの手口だった可能性もありそうです。

　八幡のすしべん津幡店の手前には、左方向から斜めに来る広い道がありました。ちょうど陸橋の下ったところで交わっていたとも記憶します。地図をみても陸橋の手前あたりに津幡高校が見えますが、その辺りを特定して被告発人大網健二は、会社の移転先と私に説明していました。

　移転前の会社というのは、ビルでしたが、金沢市古府の辺りだったと思います。建物の特定まで出来ないと思いますが、だいたいの場所は、指し示しておきたいと思います。

[link:] » 北陸朝日放送本社 - Google マップ https://t.co/oZ36PB195L \n 〒920-0364 石川県金沢市松島１丁目３２−２

<hr />

　だいたいの場所になりますが、上記の北陸朝日放送本社を目安にしました。こんなところに北陸朝日放送があるのも初めてしったように思います。住所も古府ではなく、松島となっています。

　Googleマップの航空写真をみると古府のあたりは住宅地が多いですが、被告発人大網健二の会社があったというビルは、住宅地からかなり離れていました。会社としておきましたが、正確には学校法人になるのかと思われます。

　金沢市で松島といえば、野田専光寺線と国道８号線バイパスが交差する交差点の辺りかと思っていましたが、地図を見ると「松島北」の交差点となっているようです。ラジオの渋滞情報でも松島交差点となっていたような気もするのですが、思ったより範囲が広いとわかりました。

　時刻は１２月２日１１時２７分です。昨夜は久しぶりに、すき焼きを作っていました。昼食も夕食もそれを食べる予定です。昨日は、空が明るくなっても小雨など降っていましたが、今日は朝から晴天のようです。寒くなってきました。灯油はまだ買っていません。

　昨日は、Googleマップで中央市場の周辺を見た時、公園があることに気が付きました。それもあって今朝は、石巻の公園のことを思い出したのですが、できれば、そちらも今日中に記述しておきたいと思います。

　「きょうとも運送（仮）」ですが、昨日も書いたように、たまたま車で通りかかったときに、ここに会社があったのかと思いました。けっこう大きくて新しい社屋の会社に見えました。デザインなども運送会社と言うよりは、カー用品店のように見えたように記憶に残っています。

　津幡の方に会社があるということは、最初に「きょうとも運送（仮）」について話を聞いたときに一緒に話を聞いていたようにも思います。金沢市内の運送会社という認識はなかったと思います。津幡町は金沢市の近郊ですが、河北郡津幡町になります。

　同じ河北郡でも、高松町、宇ノ気町、七塚町の三町は、かほく市となりましたが、津幡町と、海にも面した内灘町はそのまま現在も河北郡となっているようです。数日前にも書いたところですが、七塚は、被告発人松平日出男の出身地と聞いていました。

　過去のはてなダイアリーの投稿を独自にインポートした「はてなのブログ」で昨日、検索をしたところ「藤田」と検索をすると詳しく具体的な記述が出てきましたが、目的とした「きょうとも運送（仮）」の漢字を含めた社名の確認は出来ませんでした。

［link：］ 藤田 の検索結果 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/search?q=%E8%97%A4%E7%94%B0

　２００６年や２００５年という時点での記述です。１０年以上前になるので、今よりずっと記憶も鮮明だったと思います。社名を探すためにざっと目を通した程度ですが、良質の情報源ともなるので、特にポイントを指摘する以外は、重複を避けたいと思います。

　また、その時、目を通した範囲では、平成４年２月の福岡の運行のことも見かけなかったように思います。鳥栖のトラックステーションで２泊していたことなどは、同じ昨日ですが、Twilogの検索結果で見かけたいたように思います。

　試しにこれから鳥栖で検索をやってみようかと思います。鳥栖というのは九州自動車道と長崎自動車道の大きな分岐点ともなった交通の要衝でしたが、トラックステーションが九州方面の運行での仕事の中心のようにもなっていました。

　ガソリンスタンドでも同じことは出来たのですが、トラックステーションでは、会社からの電話連絡で声掛けをしてくれていました。もちろん携帯電話などなかった時代なので、そうでない場合は、３０分おきとかで、運転手の方から会社に電話を入れていました。

　なお、トラックステーションについては過去に、「TS」などと表記したこともあったかもしれません。実際に現地ではそのような表示を見ることが多かったようにも思います。

［link：］ 鳥栖 の検索結果 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/search?q=%E9%B3%A5%E6%A0%96

　意外なことに検索結果は１つだけでした。必ずあると想定していたものですが、佐世保の魚市場にいったときの運行のもので、日栄運送の運転手が竹沢俊寿について話していた内容です。

　時刻は１５時１０分になります。しばらくテレビに集中していました。個人的にとても興味深い内容でした。１４時からは見たい番組が重なったので、それまで見ていた番組の続きを録画しました。先日、取り上げたばかりの宮崎県延岡市がロケ地でした。

　その延岡市のコーナーの前だったと思いますが、同じ０円住宅で、長野県飯田市がロケ地でした。そこでふと気がついて調べたのですが、私は最近も長野県飯山市を長野県飯田市と書いていたかもしれません。初めは番組のスタッフが間違えているのではないかと疑いました。

　長野県飯山市については、さきほども鳥栖のトラックステーションのことで触れた日栄運送の主要な仕事の１つとして書いてきました。一度、U君を同情させて、そこからリンゴを積み、滋賀県の大津市の市場まで運んだことも、今年の秋以降に書いたように思います。

　あとで気がついたのですが、飯田市と思っていた長野市の近くは、国産のディスプレイのメーカーとして有名で、パソコンの雑誌にもよく商品を見かけていた時期がありました。そこで思い出したのですが、メーカーの名前は「イイヤマ」でした。よくローマ字として出ていたかと思います。

　同じ頃ですが、同じ国産ディスプレイのメーカーで、ナナオというのもありました。何かで調べたとき、名前と同じで石川県七尾市と関係のあるメーカーだと知りました。ウシツ電子が、そこの仕事をしていたようなことも聞いたことがあったように思います。平成１０年代中頃のことです。

　長野県飯田市は、長野県の南部で静岡県とも接しているようです。そこの簡単な地図をテレビでみたのですが、Googleマップで調べると、岐阜県中津川市にも近く、一部が国道１９号線沿いとなっていました。

　国道１９号線は、名古屋しかその近くから長野市までつながっている国道かと思いますが、普通はほとんど通行しない道路でした。一時期だけ、よく通ったことがあったのですが、ほとんどが夜中か明け方の早朝という時間帯でした。

　それも中西運輸商の４t車での仕事でしたが、一時期、広島県の福山市から雑貨の定期便で、長野市、上越市（新潟県）に行く仕事がありました。尾道でも荷物を積んだような気がするのですがはっきりしません。卸先はどちらもトナミ運輸でした。福山市もたぶんそうだったと思います。

　現在のことはわかりませんが、富山県に本社のあるトナミ運輸は、昭和の終わりから平成の初めころ、全国で５，６番目という大手の運送会社でした。金沢市場輸送は、そのトナミ運輸の仕事も多かったです。

　北九州と福岡市については、先日も書いた頃かと思いますが、卸先は九州西武運輸でした。他に卸先がトナミ運輸以外だったのは、仙台便で、国道４号線沿いに大きな敷地があった第一貨物でした。

　中西運輸商は、同じ頃に、広島県福山市で福山通運の仕事をするようになっていたのですが、それは大型車のみの仕事であったように思います。ずいぶんきつい運行とも聞いていました。福山通運は、トラックの保有台数だったように思いますが、当時、業界で全国２位とも聞いていました。

　トナミ運輸の広島県福山市からの長野・上越便も、仕事がきつかったです。出発の時間が遅く、国道１９号線で松本市に向かう間が、ちょうど明け方の早朝で、時期的にもとても寒かったことが印象に残っています。路面の凍結にも気を使いました。

　はてなのブログの「鳥栖」の検索は意外な結果で期待はずれでした。Twilogの方を次に見ておきたいと思います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「鳥栖」の検索結果 - Twilog https://t.co/onibEvEiV3

<hr />

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2010/05/14 07:14％ https://twitter.com/hirono_hideki/status/13937593209
&twitter(13937593209){theme:light}
> 私は平成4年2月３日にミールを積んで福岡に向かいました。ミールをトラックに積んだのは1日の土曜日だったと思います。九州では佐賀県の鳥栖が、高速道路の交わるところでもあり、帰り荷の待機場所でした。私はここで二晩泊まったと思います。  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-02 15:51／2013-11-10 09:02 URL： https://twitter.com/kk_hirono/status/1069121839849398272 https://twitter.com/hirono_hideki/status/399326274772295680
&twitter(1069121839849398272){theme:light}
> ゆるキャラが「わいせつ発言」　鳥栖市に苦情、活動自粛 （朝日新聞デジタル） - Yahoo!ニュース http://t.co/gXyF7BG4G3 先月下旬、出演した全国放送のラジオ番組でわいせつな発言を繰り返したとして、市に苦情が数件寄せられたことを受けた。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-02 15:51／2013-11-15 21:01 URL： https://twitter.com/kk_hirono/status/1069121866818715648 https://twitter.com/hirono_hideki/status/401319005606404096
&twitter(1069121866818715648){theme:light}
> 市などによると、先月２３日未明の番組への出演は、市がとっとちゃんの使用許可を出している鳥栖観光コンベンション協会の希望もあり決まった。その際、協会職員は番組担当者に「下ネタもＯＫ」と伝えていた。 http://t.co/FXewklyQ9l
◁◁◁
<hr />

　奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントは、わずか３件のみの検索結果でした。Twilogの検索の精度は高いと思いますが、思いの外少ない数でした。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2010/05/14 07:14％ https://twitter.com/hirono_hideki/status/13937593209
&twitter(13937593209){theme:light}
> 私は平成4年2月３日にミールを積んで福岡に向かいました。ミールをトラックに積んだのは1日の土曜日だったと思います。九州では佐賀県の鳥栖が、高速道路の交わるところでもあり、帰り荷の待機場所でした。私はここで二晩泊まったと思います。  
▶

▶ ツイート％kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）％2016/12/01 16:15％ https://twitter.com/kk_hirono/status/804222310471192576
&twitter(804222310471192576){theme:light}
> 過去の書面にも書いていると思いますが、佐賀県の鳥栖インターの近くのトラックステーションのレストランで、夜に金山さんと食事をしていたとき、となりのテーブルにいた日栄運送の運転手が、ずっと前からもうすぐ死ぬ、と言いながら生きていると呆れたように話していました。  
▶

▷ リツイート→kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）＞hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜2018/11/30 12:42／2010/05/14 07:14｜https://twitter.com/kk_hirono/status/1068349525788581888 ／ https://twitter.com/hirono_hideki/status/13937593209
&twitter(1068349525788581888){theme:light}
> RT @hirono_hideki: 私は平成4年2月３日にミールを積んで福岡に向かいました。ミールをトラックに積んだのは1日の土曜日だったと思います。九州では佐賀県の鳥栖が、高速道路の交わるところでもあり、帰り荷の待機場所でした。私はここで二晩泊まったと思います。  

　古いものからTwilogで表示させましたが、２０１６年１２月１日の１件のツイートの後は、一昨日の１１月３０日の自分自身の他のアカウントのツイートのリツイートとなっていました。これまでさほど重視していなかったこともうかがえます。

　時刻は１２月４日１１時２９分です。昨日はまるまる中断をしていました。夕方頃には、家の中の片付けをしていたのですが、いろいろと発見もありました。電源コードが見つからなかった古いノートパソコンを数年ぶりに起動させることも出来ました。

　期待していた写真ファイルは見つけることが出来なかったですが、OSはFedora14となっていました。Ubuntuと同じだと２０１４年のリリースになるのかと思います。４年前ならば、比較的最近とも思えたのですが、ノートパソコンは平成１６年あたりに買ったものです。

　羽咋市にいる頃、よく使っていました。国道８号線バイパスのヤマダ電機で買ったように思います。１５万円ぐらいで、消費税を入れると１６万円を超えていたかもしれません。そのヤマダ電機ですが、住所がどこになるのかよくわかりません。今も同じ場所に店があるのかもわかりません。

[link:] » ヤマダ電機 テックランド金沢本店 - Google マップ https://t.co/Grk82z90wZ \n 石川県金沢市西都１丁目４０

<hr />

　側に国道８号線バイパスで西念という大きな交差点がありますが、平成４年当時は、金沢港方面が通行止めで、建物というのもまばらにあったバイパス沿いの店を除けば、ほとんどなかったと思います。

　金沢市西都という住所も、今回初めてみたように思います。どこかで見かけたような気もしましたが、この場所とは知りませんでした。西都市というのは、宮崎県で見かけたような気もします。余り自信の持てない記憶です。

[link:] » 西都市 - Google マップ https://t.co/bK7aDSONkH

<hr />

　西都というのも都の西という意味なので、他にもありそうに思いましたが、長距離トラック運転手の仕事でも他で見たような記憶はありません。似たように思っていたのが、駅南です。駅の南になるので、けっこうありそうですが、実際に見たという記憶はありません。

　ちなみに金沢市では駅西、城南、城北、西南部という地名や呼び名はあります。駅南というのは、気になった匿名弁護士アカウントのTwitterです。３ヶ月ほど前でしょうか、比較的最近になってブロックされていることに気が付きました。情報を見ると富山市の弁護士の可能性があります。

　ヤマダ電機テックランド金沢本店とありますが、平成１３年１２月３１日、被告発人大網健二と立ち寄った家電店でもあります。そのあと、粟崎の交差点の先にある回転寿司で食事をし、宇出津に送ってもらいました。食事も彼のおごりだったように思います。

　その時の、ヤマダ電機では大きなプラズマテレビが印象的でしたが、プラズマテレビというのはその後、普及はしなかったようです。液晶テレビというのもまだ出ていないか、出始めという時代であったようにも思います。

　この前、書くのを忘れていたかもしれませんが、ヤマダ電機に行く前に、被告発人大網健二は、自分の会社だったというビルの前に立ち寄っていました。松島となっていた住所の場所です。被告発人大網健二には、服役中、車をあずかってもらっていました。軽四ですが、ホンダトゥディという車です。

　その場で車を見たような気もするのですが、移転した津幡の方で預かっているという話でした。車検切れともなっていたはずです。その車検は、平成１４年９月頃になって入れました。車を買ったのが被告発人大網健二の知人でもあったのですが、津幡の方に行くことはなく、中古車店は示野でした。

　そのホンダトゥディを買ったのは、平成９年８月の終わりか９月に入った頃のことです。８月のお盆休みでは、代車だったローレルに乗っていました。金石の海岸で砂に埋まりJAFを呼び、その夜、あすなろ公園で被告発人多田敏明と会った後、金沢西警察署に相談に行きました。

　さきほど、Googleマップで思い出したのですが、国道８号線バイパスの西念の交差点を少し富山方面に向かった左側に、けっこう大きな喫茶店があって、そこで被告発人大網健二とコーヒーを飲んだか軽食を食べました。

　その前になると思いますが、金石街道のパチンコオークラの隣あたりに大きな花屋がありました。小さなホームセンターのようにも見える建物でしたが、よく通る道路沿いであるにも関わらず、建設中のところを見たことがないのに、いつの間にか出来上がって開店をしていました。

　市場急配センターの事務所も同じだったのですが、いつの間にか出来上がっていました。その近くには、イケウチやカナカンという食品会社があって、金沢市場輸送の東北便では、お決まりの場外の卸先でした。仕事をするのは夜中だったので、気が付きにくかったとは思います。

　あるいは、長距離トラック運転手の仕事に復帰する少し前だったのかもしれません。更地の駐車場となっていた市場急配センターの事務所が出来る前の場所は、イワシの運搬の仕事が終わった頃に、配車係をしていたYTと藤田さんの３人で、その場所に行ったときに見ていました。

　過去の記録にも書いていると思いますが、その場で藤田さんは、中継の作業場にするらしい、というような話をしていました。金沢中央卸売市場の仕事で中継というのは、そのほとんどが鮮魚になります。

　例外だったのが山三青果の仕事の福井中継でしたが、他に青果物の仕事で、荷物の積替えをする中継というのは、ほとんど経験が無かったからです。鮮魚とは単価も違いますし、鮮魚ほど鮮度の影響で時間を急ぐこともなかったはずです。そもそも小口の仕事というのがありませんでした。

　鮮魚の場合は、私の経験になりますが、東京の築地市場だけでしたが、場内中継というのもありました。場内の入り口で中継をして、売り場まで運んでもらうというものでした。そこで活躍したのが豊洲市場への移転で注目され、テレビで見ることの多かったターレーでした。

　現在のことはわかりませんが、金沢中央卸売市場で鮮魚の中継をしていたのは、山水運輸、守田水産輸送、ウロコ運送です。山水運輸は、会えば少し言葉を交わす被告発人安田敏とも共通の知人がいたし、数人の友人が仕事をしていた時期もありました。

　守田水産輸送の中継は、都商事という名前を聞いたり、看板のようなものを見ることもあったのですが、金沢市場輸送の東北便でも高岡（富山県高岡市）の荷物を中継に出していました。

　同じ東北便の福井分は、早い段階から金沢市場輸送の４t車で中継をしていました。やっていたのはずっと同じ人で、中野さんでした。傷害・準強姦被告事件の当日か、数日前に久しぶに姿を見ました。

　ちょうど中野さんが、被害者安藤文さんに伝票を手渡すようなタイミングだったのですが、彼女は、そのときにおもむろにメガネを取り出し、顔に掛けたのです。ちょうど私の面前でした。彼女がメガネをしたのは、その時が初めてでしたし、中野さんもずいぶん驚いた様子でした。

　時刻は１４時４４分になっています。昼食は、冷凍食品で済ませましたが、これがけっこう美味かったです。辛いものは余り得意でも好きでもないのですが、担々麺でした。予想通り汗が出ました。まぜそばのような担々麺は前に食べたことがあり、それと同じかと思っていたが違いました。

　テレビでは、昨日に続き、東名高速の夫婦死亡事件の裁判員裁判が取り上げられていました。危険運転致死傷罪の構成要件が問題になっている事件で、昨日には、これまで余りテレビでは見てこなかった罪刑法定主義という専門用語も出ていました。

　一番、意外に思ったのは、横浜地裁前からの報道でしたが、テレビを含め横浜地裁の建物を見たのは初めてという気がしました。裁判所では珍しく近代的でありながら美術館や博物館のように見える建物でした。今まで見てこなかったのが不思議でしたが、それだけ大きな裁判はなかったのかも。

　神奈川県というのは大阪府より人口が大きと聞いており、重大事件の発生もそのぶん多いようには思いますが、考えてみると、小田原の新幹線の殺傷事件も、事件当時は大きな報道があったものの、裁判になってからはテレビで報道は見ていません。

　藤田さんですが、YTの入社よりは、いくらかあとだったと思います。YTは、私の紹介というかたちでしたが、彼の方から連絡があり、入社になったという経緯も、平成３年４月の被告発人安田敏のときとよく似ていました。

　YTについても、今は記憶が薄れ、忘れてしまっていることもあるかと思います。彼が結婚をした頃は、金沢市の黒田に住んでいたように思います。すぐ近くのアパートになったと思いますが、被告発人安田敏と共通の知人の珠洲市三崎のHMも黒田でした。

　ついでになるかと思いますが、被告発人松平日出男が石川トヨタをやめたあと、個人で経営していたという中古車店も金沢市黒田になったかと思います。その中古車店は、昭和５８年ぐらいに、中古車を見に入ったような記憶もあるような場所でした。

[link:] » 黒田 - Google マップ https://t.co/7eYa78HQt5

<hr />

　前に調べた頃もあったのですが、やはり金沢市黒田は１丁目と２丁目しかないようです。Googleマップを見ても橋の名前が見当たりませんが、間明町の交差点から黒田に向かうと、犀川にかかる橋を渡ります。

　そのまま道沿いに行くと、三叉路のような交差点にぶつかりました。今も同じように見えますが、信号機はないようです。この交差点の手前、間明から来ると左側でしたが、そこに中古車店がありました。当時の金沢市内の中古車店では、よくある大きさだったと思います。

　この中古車販売というのも被告発人松平日出男を特徴づける要素で、保険の取り扱いなどもしていたようです。市場急配センターにおいても、金沢市場輸送の運転手の事故処理や保険の扱いをやっていると聞いていました。

　三崎のHMが住んでいたアパートの辺りに意外なものを見つけたのですが、それはここで触れないでおこうと思います。現在は匿名扱いをしていることもあるので、そうなりますが、そういえば２年ほど前に調べたときに、見ていたようにも思いました。

[link:] » にしむら酒販 - Google マップ https://t.co/xijqS15JFi

<hr />

　にしむら酒販という店がありますが、ほぼ同じと思われる場所に、昭和６２年当時も、現在のコンビニのような店がありました。当時、金沢市内ではコンビニと呼ばれる店がまだなかったように思いますが、同じような品揃えの似たような店舗は市内にいくつかありました。

　そういえば、酒店だったような気もしたのですが、その隣には喫茶店がありました。喫茶店と言っても夜は、飲み屋をしているような店で、そのように話を聞いていたとも思います。私は店に昼しか入ったことがなかったと思いますが、それも１，２回のことだったと思います。

　その店で、TYの妻が仕事をしてたという話を思い出しました。それで当時のTYの住まいのことも、少し思い出したのですが、なぜか玄関先のような場所の記憶しか残っていません。アパートだったようには思うのですが、一般的なアパートとは違っていたように思え、一軒家に近かったような。

　三崎のHMのアパートですが、昭和５８年の秋、珠洲市三崎の彼の家から軽トラだったように思いますが、引っ越しを手伝ったということもありました。前に書いていると思いますが、半年ほど前だったかもしれません。

　三崎のHMの部屋があったのは、２階建ての２階で、一番、道路に近い部屋だったと思います。その隣か隣の隣の部屋でしたが、KYNと一緒に遊びに行った、石川県立水産高校小木分校の同級生の部屋でした。小木中学校の出身で上の名前は今でも憶えています。よくある苗字です。

　そのKYNですが、平成３年当時は、黒田２丁目のマンションに住んでいました。古い建物で市営や県営の住宅にも似ていましたが、普通の賃貸だったように思います。その前は、金沢市松村の古い下宿のような建物に住んでいました。場所も大通りの金石街道からかなり外れていました。

　平成９年には、黒田１丁目で中古住宅を購入し、住居兼の会社としていたので、よくよく黒田とは縁があったのかもしれません。近所付き合いの話はなかったですが、家の前に大きなマンションが出来た時は、住民運動のようなものに参加しているような話は聞きました。

　金沢市内でも場所によって違いはあるのかと思いますが、町内会のようなものの話を聞いたこともなかったし、回覧板なども見たこともありませんでした。他の地域に住んだ経験も少ないので、比較も難しいですが、羽咋市も同じではありました。

　ふと思ったのですが、KYNが黒田に続けて住んだのも、偶然ではなく、なにか事情があったのかもしれません。商売をやっていれば、場所が大きく変わらないというのもメリットがあるのかもしれません。

　平成１６年の１月だったように思いますが、そのときのKYNの会社は、黒田１丁目の自宅からは離れた別の場所にありました。場所は、金沢市神田と聞いていたように思います。神田の陸橋の下辺りで、少し先に鐵道の線路が見えました。

　金沢市神田というのは、昭和５８年頃、友達が住んでいたアパートがあったということもあるのですが、周辺は車でよく走ることがありました。今はどうかしりませんが、古い建物が多かったり、小さな工業団地のような趣もあったかと思います。

　KYNの会社という建物も、ずいぶんと年代を感じさせるものでした。トラックの仕事をしていると工場や倉庫に行くことは多いですが、あれほど歴史を感じさせたのは、かなり珍しいと印象に残りました。工場も一緒になっていたと思いますが、そちらは現在記憶に残っていません。

　ちょうど、YTから金沢市場輸送で仕事をしたいという相談があった頃だと思いますが、彼の住む団地のようなところへ遊びに行ったことがありました。松任市の一番はずれの方で、清水倉庫や寺井町にも近かったのだと思います。

　団地といっても、大きなところではなく、公設の住宅とも聞いてはいなかったように思うのですが、名称が変わっていたので、よく憶えています。まだ調べたことはないのですが、「オレンジ団地」と聞いていました。あるいは平仮名で「おれんじ団地」とも考えられます。

　Googleマップでは、「オレンジ団地」としても「おれんじ団地」としても該当はありませんでした。全国的に見れば、ありそうに思っていたのですが、思っていた以上に珍しい名称だったようです。

　Googleで、オレンジ団地や白山市、松任市との組み合わせで調べましたが、それらしい情報は見つかりませんでした。当時の松任市の最果てのような場所で、新しい建物だったことも記憶に残っています。

　当時の松任市というのは、水田や空き地も多かったように思いますが、あそこまで金沢市内から離れているのも珍しかったし、辺りには買い物をする店のようなものも見当たりませんでした。不思議な光景にも見えたので、よく憶えています。

[link:] » 信開ウェラコートオレンジ - Google マップ https://t.co/lGg7nYbpNF

<hr />

　Googleマップでそれらしい場所を見ていると、先ほどの検索結果で少し見かけていた「信開ウェラコートオレンジ」というのが出てきました。ただの建物の名称だと思っていたのですが、新開オレンジマンション、A棟、B棟が隣接しています。通称がオレンジ団地だったのかもしれません。

　YTが金沢市黒田に住むようになったのは、そのあとだったのかもしれません。オレンジ団地の住所は源兵島町になるのかもしれません。聞いたことはない地名ですが、道路標識としては見かけていたような気もします。

```
御祭神
経津主神 天児屋根命 比咩大神 白山比咩神 天照皇大神 武甕槌神

鎮座地
白山市福留町1

氏子区域
白山市
福新町福留町福留南
由緒
創立の年代不詳 初め福留白山神社と号したが明治40年神明社、春日社、白山社を合祀し味知郷神社と改める。 境内地は843坪周囲小高く中央が低く稀なる地形をなしている。

［source：］味知郷神社（白山市福留町1） - 石川県神社庁 http://www.ishikawa-jinjacho.or.jp/shrine/j0775/
```

　先日、テレビで見たばかりの神社が近くにありました。味知郷神社という変わった名称だと思っていたのですが、「明治40年神明社、春日社、白山社を合祀し味知郷神社と改める。」とあります。

　白山市の神社については、ずっと前から書いておきたいことがあるのですが、なかなか進みません。私は、白山市にもその前の松任市にも一度も住んだことはありませんでした。

　私は、当初、被害者安藤文さんの家が松任市だとあたりをつけていました。彼女の車は、最初に見た当時、出たばかりだったと思われるホンダのトゥディという軽四でした。そこにホンダの販売店として松任市のシールかステッカーのようなものが貼られていたようにも思います。

　金沢市内に家があれば、金沢市内の販売店で買うという単純な考えがあったのだと思いますが、隣接した野々市町と考えたことは一度もなかったように思います。あるいは他に原因があったのかもしれないですが、今では思い出せません。

　被害者安藤文さんの名前も、最初は、「安養」ではないかと思っていました。彼女が事務所の電話で、運転手の津幡町の山下くんと話していた時だったと思いますが、彼女が自分の名前を「あんよう」と言っているように聞こえたのです。

　「あんよう」と「あんどう」では、聞こえ方がだいぶん違っていたと思いますし、もともと彼女は、声は大きい方ではなかったですが、落ち着いた声ではっきりと聞き取りやすい声というか話し方でした。

　３，４カ月前になるかと思いますが、「あんよう」というのも松任市か野々市町のあたりで見かけていた地名だと思っていたのですが、確認のため調べたところ、「安養寺」という地名がありました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「安養寺」の検索結果 - Twilog https://t.co/HNwMpw2bqk

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-04 16:52／2018-09-03 21:00 URL： https://twitter.com/kk_hirono/status/1069862083229958144 https://twitter.com/hirono_hideki/status/1036584719301791744
&twitter(1069862083229958144){theme:light}
> 安養寺 - Google マップ https://t.co/mFb383tzso
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-04 16:53／2018-09-18 20:31 URL： https://twitter.com/kk_hirono/status/1069862119741390848 https://twitter.com/hirono_hideki/status/1042013291105533952
&twitter(1069862119741390848){theme:light}
> 白山市　安養寺 - Google 検索 https://t.co/siZFykKAL9
◁◁◁
<hr />

　９月３日に調べた安養寺は、能登町の旧柳田村の白山神社になります。Googleマップでは、白山神社ではなく安養寺として表示されていましたが、その白山神社では、「安養寺阯」という石碑を見かけていました。

[link:] » 安養寺 - Google マップ https://t.co/0FlZGB0UtR \n 石川県白山市

<hr />

　あらためてGoogleマップで確認すると、鶴来桑島町と隣り合うように隣接しているようです。近くに上林という交差点が見えることに今回は気が付きましたが、この上林というのも、以前、通りがかりによく見かけたいたような地名です。

　桑島町が鶴来桑島町となっていることも今回気がついたことかと思います。現在は同じ白山市ですが、以前は鶴来町があって野々市町と同じ石川郡となっていました。鶴来町は仕事で通りかかることも少なかったはずですが、上林はよく見かけていたような気がします。

　Googleマップを拡大すると、ケーズデンキ野々市新庄店があって、もう少し右手のやや下には四十万があります。四十万は金沢市内のはずなので、安養寺もその近くだったようです。この辺りは平成１１年の派遣社員の仕事でもよく行っていました。堀田建設の土場があった辺りです。

　Googleマップをよくみると、安養寺北、安養寺、安養寺南という３つの交差点があって、いずれも国道１５７号線上となっています。鶴来バイパスとも表示がありますが、その後に出来て、私が通ったことのない道路という可能性もあるのかと思います。

　そのあたりは、目印となる建物も少なく、どこをどこへ向かって走っているのか注意しないとわからなくなってしまいそうな場所でもありました。そういうこともあったので、交差点の標識などをよく憶えていたとも考えられます。

　市内配達の仕事で鶴来町の中心部に行ったこともありましたが、被告発人安田敏も同じような場所に行ったと話していたことがあったようにも思います。そこで何かあった、というような話であったようも思いますが、昔のことなので思い出せません。

　時刻は１２月５日１０時５５分となっています。昨日は夕方に銭湯に行ったのですが、Aコープ能都店で買い物をして戻ってから再開することはなかったようです。

　雨の中、バイクで走り、銭湯に入ったタイミングで、テレビに気になるニュースがありました。通常の報道ニュースというよりは、番組独自の特集に近い感じでもありました。銭湯のテレビのチャンネルは、ほとんどがテレビ金沢だったのですが、最近違っているのも見たことがありました。

　たぶんですが、テレビのリモコンは女湯にあるようです。１９時以降だと、以前急にチャンネルが変わることもありました。そのニュースについて気になるのは、ニュースの内容だけではなく、ネットを含めその他一切で別の報道をまったく見ていないことです。今朝の情報番組も同じです。

　いくらなんでもGoogleで検索をすれば、情報は出てくると思いますので、これからやってみます。キーワードは「１円　スーパー」でいけそうに思います。前にもテレビで見かけたことが、２回はあったように思います。

[link:] » １円　スーパー - Google 検索 https://t.co/dcjjv6GJgs

<hr />

　検索結果の１ページ目に、事件の情報は見当たりませんでした。パチンコ屋のような店名だったことも思い出したのですが、玉出というスーパーだったようです。

```
　大阪府内を中心に展開する「スーパー玉出」の創業者が、大阪市西成区の歓楽街「飛田新地」で売春に使われた店舗を暴力団に貸し賃料を受け取ったとして逮捕されました。

　組織犯罪処罰法違反の疑いで逮捕されたのは「スーパー玉出」の創業者で不動産会社「玉出ホールディングス」社長・

［source：］スーパー玉出の創業者が逮捕　暴力団から売春利益受け取った疑い | MBS 関西のニュース https://www.mbs.jp/news/kansainews/20181203/GE000000000000025550.shtml
```

　Google検索ページの「ニュース」という項目をクリックし、そこから上記の記事を見つけましたが、記事の数がずいぶん少ないようです。昨日のテレビでは気が付かなかったですが、逮捕容疑は組織犯罪処罰法違反とのことです。

　テレビの映像か写真では、有名な飛田新地に小さなスーパーがあって、そのスーパーを閉店後に賃貸し、そこで売春が行われていたという説明になっていました。暴力団のゴルフ会員権などが問題になったことはありましたが、逮捕容疑が賃料というのも初めてみたように思います。

　全く別の事件ですが、このテレビの報道を見て思い出したこともありました。割と最近のことです。大きなニュースになったカルロス・ゴーン氏の逮捕の２，３日後だったように思います。不動産王と呼ばれた丸源の会長に実刑判決が出たというニュースでした。

　最初、夜中に目が覚めたときに、バイキングの放送内容のツイートをみて、そこにそれらしいニュースの見出しを見ていたのですが、丸源の会長のことだったとは想像もしませんでした。それというのも、前にニュースになっていたのは、随分と前のことで、裁判が続いていたことに驚きました。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/11/21 05:22％ https://twitter.com/hirono_hideki/status/1064977234186792960
&twitter(1064977234186792960){theme:light}
> 放送内容
> 次回 | 11月21日(水) 11:55～13:45 放送
> バイキング【日産ゴーン容疑者「権力集中」の闇▽銀座有名ビルオーナーが脱税で有罪】 https://t.co/BHx2C8fV6i  
▶

　バイキングのツイートのリツイートというのは、私の勘違いだったようです。たぶんバイキングのホームページをブラウザのタブで開いたままにしていて、それで見つけたのかと思います。「銀座有名ビルオーナーが脱税で有罪】」という完結な見出しとなっています。

　丸源ビルオーナーについては、次が私の最新ツイートになるようですが、内容自体は数年前のかなり古い情報です。

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/11/21 16:15％ https://twitter.com/hirono_hideki/status/1065141616153784320
&twitter(1065141616153784320){theme:light}
> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: 日刊ゲンダイ|丸源ビル会長が弁護士に要求された金額 「ヤメ検が２０日間で ５０００万円と言ってきた」 https://t.co/9cV3jm2Sru  
▶

　丸源と聞いて思い出すのは、宇出津にあったスーパーのことです。もう７年ぐらいになるかと思いますが、いきなり閉店しました。小木にも店舗があったのですが、同時に閉店しました。従業員も当日まで閉店することを知らなかったという話も聞きました。

　マルゲンは、宇出津駅前にあったスーパーですが、たまに店に入って買い物をしたこともありました。いつ行っても客が少なかったですが、新聞では広告チラシが目立ちました。聞いた話では、腐ったお惣菜を出していて、客が離れたという話もありました。

　なにより人口減少が大きかったようにも思えますが、電撃的ないきなりの閉店だったので驚きました。はじめはしばらく休業という意味合いの札が出ていたようにも思います。

　宇出津駅前のマルゲンの建物は、一年ほどあとだったと思いますが改装され、「のむら」という着物の店になっています。貸衣装なのかもしれません。祭礼委員会の寄付金をお願いに行ったこともありました。

　「のむら」は、輪島市門前の方に本店があるような話も見たことがあります。私が子供の頃から宇出津にあったと思うのですが、場所は変わっているようにも思います。

［link：］ 株式会社のむら | 金沢流通会館 / 協同組合金沢問屋センター http://kimassi.or.jp/member/%E6%9C%89%E9%99%90%E4%BC%9A%E7%A4%BE%E5%8A%A0%E8%B3%80%E3%81%AE%E8%88%9E/

　会社のホームページは見当たらなかったのですが、上記のページに会社の情報がありました。まず、代表者の名前が能村となっています。野村とばかり思っていたので、これは意外でした。創業も平成元年となっています。

　昭和５０年代、宇出津の町にはけっこうな数の呉服店があったと思います。小さな食料品店もありました。いまでも看板だけ残っているような呉服店もありますが、野村というのは元々、宇出津にあった呉服店かと考えていたようにも思います。

　当時すでに「のむら」と平仮名の店名になっていたように思いますが、被告発人大網健二が仕事をしている、と聞いたことで記憶にある呉服店です。同じ頃には、同じ宇出津で「漁運会」でも仕事をしていると被告発人大網健二が話していたことがありました。

　「漁運会」で正しかったように思いますが、「ぎょうんかい」と読みます。鮮魚を運ぶ運送会社ですが、私が子供の頃からあったと思います。全て持ち込みトラックとか、普通とは違う形態の会社とも聞いていました。

　６トン車が多く、被告発人大網健二も６トン車に乗務していると話していたように思いますが、その仕事をしていたのも、「のむら」と同じく短い間だったと思います。どちらも冬の寒いような季節ではなかったようなことも記憶に残っています。

　「漁運会」のトラックは、今でも魚市場の辺りを通りかかると見かけることが多いですが、トラックの数は昔にくらべてずいぶん少なくなったように思います。以前は、水産高校の近くの崎山の灯台の真下辺りに駐車場があり、トラックがよく駐車していたという記憶もあります。

[link:] » 漁運会 - Google 検索 https://t.co/BebnlfvehY

<hr />

　Googleで検索してもタウンページ以外の情報は見当たらないようです。PDFファイルになりますが、石川県トラック協会奥能登地区の名簿を見つけました。平成２６年４月１日現在となっています。

　金沢市場輸送で一緒に仕事をしていた人物と同じ名前を見つけました。代表者名とあります。宇出津タクシーや鼎建設も会員になっているようです。

　（有）新崎という会社がありますが、こちらも宇出津の魚市場で保冷車を見かけることがあります。最近は、私の外出も少ないですが、しばらく見かけていないかもしれません。平成１４年の春頃ですが、被告発人安田敏が前に仕事をしていたと話していた会社でした。

　被告発人安田敏は崎山に会社があると話していましたが、トラックは別の場所に駐車場があるようです。

　同じ時だったような気もしますが、被告発人安田敏は、柳田運送にもいたと話していました。ちょっとした人身事故を起こし、免停になったと話していたかもしれません。罰金刑を受けるような軽い刑事裁判になったとも話していた気もするのですが、不本意であるような口ぶり、という印象も。

　柳田運送は、旧柳田村にあった運送会社だったと思いますが。トラックの保有台数も多かったのか、割とよく見かけていたような記憶となっています。もうずいぶん前からまったく見かけなくなっているので、会社はやめた可能性が高そうです。

　ページをさげると珠洲市が出てきましたが、「（有）北浜運送」として北濱泰一という代表者名があります。これは、昭和５９年当時の金沢市場輸送の配車係で、これまで北浜太一と書いてきた人物の可能性がありそうです。

　泰一だと「たいいち」と読みそうに思いますが、金沢市場輸送では「たいち」という風に呼ばれていたように思います。本人に「たいち」などと呼びかける人はいなかったような気もしますが、「きたはまたいち」として、よく耳にしていました。

　テレビの飛田新地のスーパー跡地ですが、かなり小さな店舗だったようです。マルゲンには仙人町店があって、興能信用金庫宇出津本店の向かいなのですが、建物は外見そのままで残っています。宇出津の小さな食料品店でも早く閉店していたように思います。昭和５０年代かもしれません。

　思い出したのですが、昨夜、銭湯からAコープ能都店に向かう時、持木病院の向かいにあった食堂が更地になっていることに気が付きました。もうずいぶん前に閉店していて、店が閉まったまま人の出入りなども見たことがありませんでした。

　時刻は１５時５２分になります。テレビで「あえのこと」が行われたという石川県内ニュースを見ていて、昼前に見たときと同じ内容でしたが、今回、アテの枝に宿った神様を家にお招きすると知りました。それらしい木の葉は昼前にも見ていたのですが、アテのことは今回初めてしりました。

　アテの木というのは能登ヒバのことで全国的にはアスナロと呼ばれるようです。茶色くなった枯れ葉のような枝は、松明によく使われています。輪島大祭では藁のようなものを松明に使うようですが、宇出津ではアテの木が使われ、置き松明として束ねたものをスンバと呼ぶようです。

　山の方へ行くと、落ち葉となったアテの葉は、よく見るのですが、緑のものというのは余り見たことがありませんでした。以前、門前町の總持寺祖院の近くの蕎麦屋で蕎麦を食べたのですが、原始林のような葉っぱに蕎麦が載っていて気になっていました。たぶんアテの葉だったのだと思います。

［link：］ 2015年2月～能登・輪島～門前そばを召し上がれ～（3） - ポルトガルが好きなんです！ https://fado.muragon.com/entry/125.html

　上記のページにアテの葉に載った蕎麦の写真がありました。能登地方では刺し身の皿の下に敷く、とありますが、宇出津の周辺ではない風習だと思います。私の体験したのは一度だけでした。ヒバは檜葉とも書くようです。ヒノキと同じ漢字のようです。

　門前町の總持寺祖院は、小中学生の頃、何度かバス遠足で行ったはずなのですが、道路の突き当りになった正門付近の記憶しかなく、それを確認したのも、そのアテの葉の蕎麦を食べたときでした。總持寺祖院という名称を知ったのもその時だったと思います。以前は総持寺だけだったと思います。

［link：］ 干支の山第３弾　猿山（332ｍ） - よたよた山歩き（仮称） http://yotayotayoshi.blog.fc2.com/blog-entry-706.html?sp

　スンバについて調べると、猿山岬や娑婆捨て峠が出てきました。スンバは括弧書きで杉葉とありました。松明のスンバも杉の葉を混ぜないと火のつきが悪く、それで過去に問題になったこともあると祭礼委員で聞きました。

［link：］ 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： 2018年07月16日01：27記録＼法務検察・石川県警察宛＼写真資料：2018-07-14_125119〜2018-07-14_183330：126件 http://hirono2014sk.blogspot.com/2018/07/2018071601272018-07-141251192018-07.html

　スンバで検索をしていると自分のブログ記事も出てきました。緑のアテの葉を撮影していたことも思い出しましたが、大きさも違うのか、テレビで見たのとは違った印象です。榊というのも近くの山に自生するものだと立派なものは少ないという話を聞いたことがありました。

[link:] 2018-07-14_145308＿ポケモンで予期せぬ移動、平体の山まで・能登町藤波四明ケ丘の奥の林道・スンバの葉　たぶん能登ヒバの木.jpg http://hirono2014sk.blogspot.com/2018/07/2018071601272018-07-141251192018-07.html#20180714145308 

　７月だったのかと思った時は気が付かなかったのですが、７月１４日は辺田の浜の祭りの日でした。

[link:] » HERO - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/bPhRE0w7dv \n ごご☆プレ・HERO　【恋という名の犯罪】#3 \n 2018年12月5日（水）  15時53分～16時50分  の放送内容

<hr />

　エンディングの音楽が流れ、それも終わったところですが、テレビでHEROをやっていました。主演の木村拓哉がずいぶん若く見えていたのですが、エンディングの曲も、ずいぶん前にヒットしていた宇多田ひかるの曲でした。

　２時間ドラマや映画版のようなHEROは、これまでにテレビで少し見たことがあり、ドラマの方かと思うのですが、地検の支部に帰ったところの場面はいくらか見ていました。杉本哲太が出ていて、ほとんど年齢が変わっていないように感じていました。

[link:] 2018-07-14_135707＿ポケモンで予期せぬ移動、平体の山まで・神目神社から辺田の浜.jpg http://hirono2014sk.blogspot.com/2018/07/2018071601272018-07-141251192018-07.html#20180714135707

　この日も神目神社に行っていたようです。まだ１年経っていないですが、忘れていたように思います。子どもキリコだけが出されていたのは初めて見ていて、どうなのかと思っていたのですが、後日、大人のキリコは出さなくなったと聞きました。

　大人のキリコは出しても動かさなくなったとは聞いていたのですが、組み立てることもしなくなったようです。辺田の浜の祭りは７月１４日と１５日で、１５日は昼だけですが、この日付は私が子供の頃から変わっていないようです。宇出津も７月の第一金土と曜日に変わっています。

[link:] 2018-07-14_140316＿ポケモンで予期せぬ移動、平体の山まで・辺田の浜　神目神社　能登町指定絵図　奉納額鯨捕り絵図　案内板.jpg http://hirono2014sk.blogspot.com/2018/07/2018071601272018-07-141251192018-07.html#20180714140316 

　２年か３年前の４月だったと思いますが、上記の「奉納額鯨捕り絵図」の案内板をみたとき、そこに「親子鯨のうち親鯨を捕らえ」という説明があることに気が付きました。これが私の奉納というテーマの原点でもあります。

▶ ツイート％fukazawas（深澤諭史）％2018/12/05 16:55％ https://twitter.com/fukazawas/status/1070225220860964865
&twitter(1070225220860964865){theme:light}
> なんのことか存じ上げませんが、法律の顧問だったら、非弁ですね。
> （・∀・＃） https://t.co/HQZyd38HJX  
▶

▷ リツイート→fukazawas（深澤諭史）＞1961kumachin（中村元弥）｜2018/12/05 16:55／2018/12/05 14:34｜https://twitter.com/fukazawas/status/1070225234282704896 ／ https://twitter.com/1961kumachin/status/1070189767235526656
&twitter(1070225234282704896){theme:light}
> RT @1961kumachin: 「元弁護士が顧問」というので、早速見てみたら、あの方だったので、そっ閉じ  

　深澤諭史弁護士のタイムラインを見たところですが、今のところ、中村元弥弁護士が深澤諭史弁護士に返信を返したツイートというのは見たことがありません。

　時刻は、１７時２３分です。しばらくテレビに集中していました。久しぶりにテレビで見た里親制度、の特集でした。社会問題として物議を醸した民法のドラマのことも思い出しましたが、本当にドラマのようなことがあったり、ドラマ以上とも思えることが最近は多くなっています。

　ドラマ好きの元裁判官の弁護士である中村元弥弁護士のツイートのまとめ記事を作成したタイミングのことでもありました。

2018年12月05日17時14分の登録： ＼中村元弥　@1961kumachin＼１２月は、仕事上の必要性と刑事弁護センター委員としての興味から、やたらと刑事法廷を傍聴しまくる月になりそうだ http://hirono2014sk.blogspot.com/2018/12/1961kumachin.html

2018年12月05日17時14分の登録： ＃中村元弥　@1961kumachin＃のツイート／2018-12-01_1022〜2018-12-05_1635／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月05日17時14分 http://hirono2014sk.blogspot.com/2018/12/1961kumachin2018-12-0110222018-12.html

　元弁護士というのも、最近ネットで知ったもので、ドラマのような内容でした。正確には以前、ブログ記事を読んでいた元弁護士の女性だったのですが、それを見つけたのが別れさせ屋という看板を大きく掲げた探偵社と思われるホームページでした。

　別れさせ屋については、なにか裁判があって、半年ほど前だったように思いますが、テレビでミヤネ屋だけが取り上げていました。民事裁判の判決だったように思います。依頼者が支払いを拒絶し、訴えたというようなケースだったように思います。

　時刻は１２月６日１０時１７分になります。昨日も夕方に買い物に出掛け、戻ってから再開することはなかったようです。直前のツイートは１７時間前と表示されています。昨日は宇出津新港に買い物に行っていました。

　出掛ける前だったように思いますが、貴ノ岩の暴行が、また相撲界の不祥事としてニュースになっていました。不思議なくらいいろいろと続くものです。私が注目しているのは、貴ノ岩の訴訟代理人だった弁護士です。殺人事件になった富岡八幡宮の顧問弁護士として知ったのが最初です。

　思い出したのですが、買い物に出掛けたのは１９時少し前でした。テレビ金沢の「となりのテレ金ちゃん」という番組で、白山市の多川家というのを見ていました。予約が必要な有料の資料館となっているようです。全て初めて知りました。

　少し驚いたのは、Googleで調べた場所で、初めに味知郷神社が目に入りました。オレンジ団地とも近いようでした。松任市の最果てのように思っていた場所ですが、江戸時代は、文化や経済の中心地となっていたようです。番組では江戸時代の金沢城からの地図も紹介されていました。

　そういうこともあったので、松任市と田鶴浜町の橋本商事について、先に書いておきたいとも考えていたのですが、あれは本当に不思議な体験でした。偶然以外には考えられないことですが、人知を超えた働きがあったようにも感じられたことで、その辺りから私もものの見方が変わった気がします。

　現在の小項目のタイトル名を確認したところ、藤田博巳さんのことが出てきました。同時に思い出したのが、松任市にあった北都運輸のことです。トナミ運輸のような大手の運送会社を除くと、石川県で一番大きな運送会社と言われていました。２番目が国勝運送になります。

　北都運輸が倒産したのは平成３年７月頃だったと思います。その頃も新聞というのは余り見ていなかったのですが、たまたま朝刊で見て、そのことは知っていました。

　当日の午後だったようにも思うのですが、市場急配センターの事務所の前で数人が集まり雑談をしていました。他にも１回ぐらいはあったように思いますが、余りなかったことです。事務所前というのは外のことで、日向ぼっこのようなのどかな雰囲気でもありました。

　そこで被告発人松平日出男が、北都運輸の倒産のことを話題に出したのですが、笑いながらずいぶん嬉しそうな話しぶりだったのが印象的でした。何か社長の名前のような個人名も出していたような気もするのですが、北都運輸のことはよく知っているぞ、というアピールにも見えました。

　北都運輸の本社と思われた会社は、松任市でも金沢市に近い国道８号線沿いにありました。小松方面に向かうと左手です。私は一度、仕事でその敷地の中にも入ったことがあったのですが、どんな仕事だったのかも思い出せません。

　１回目のイワシの運搬のシーズンが終わったあと、平成元年の６月から１１月一杯ぐらいになると思いますが、私が北都運輸の仕事をしていたことは、すでに何度か書いてきたと思います。しかし、それは北都運輸の倉庫か営業所のような場所でした。

　場所は野々市町の中心部にありましたが、周辺は郊外で何もないような場所でした。野々市町自体が、現在は野々市市となっているほどの大きな町でしたが、特に大きな商店街のようなものもなかったように思います。店も点在していました。

　なお、私が野々市町の中心部としたのは、旧ジャスコ野々市店のことです。当時は、金沢市を含めても珍しかった高層ビルでした。Googleマップで見たところ、横宮という交差点が、角にジャスコのあった場所と思われるのですが、それらしい建物は見当たりません。解体されたのか。

[link:] » ジャスコ野々市店 - Google 検索 https://t.co/n58Zhb7a4Q

<hr />

　Googleで画像検索をしたのですが、それらしい建物の写真は見当たりませんでした。思い出したのですが、金沢中警察署の旧庁舎も以前調べたことがあったのですが、写真は見つかりませんでした。

　こじつけるつもりはないのですが、市場急配センター事務所前で北都運輸の倒産の話をしていた時、その場には、藤田博巳さんの姿があったような気もするのです。そのときのことは、過去の資料により具体的に記述しているはずなので、そちらに書いてあることが正しいと思います。

　藤田博巳さんとYTは、金沢市場輸送で配車係ということになっていましたが、配車の仕事というのは本恒夫社長がお山の大将のように独占していて、彼らも不満を口にしていましたし、事務所で見る姿というのもたまらないぐらい暇を持て余しているような様子でした。

　YTは免許取り消し中でしたし、藤田博巳さんもトラックを運転する様子も、自分で運行に出たという話も聞いたことがなかったので、たぶん免許取り消し中だったように思います。前は中西運輸商のトレーラーの運転手で、頭もよく運転もベテランという感じの人でした。

　当時もそうだったと思いますが、本恒夫社長は、無理に仕事をとってトラックを回しきれず、自ら長距離の運行に出ることも度々あったようです。その回しきれない場合というのは、あてにした運転手に運行を断られることが多かったと考えられます。

　そのように断られた仕事いうのは、他の運転手にもお鉢がまわっていました。一度引き受けた以上は、やるほかないという事情があったのでしょう。本恒夫社長は、夜も２２時か２３時ころまでは毎日会社にいたようですし、朝も８時から９時の間には会社に来ていたようです。

　頑張っていたことは、誰の目にも明らかでしたが、手柄を独り占めするような言動や呆れた自慢もあったようです。そういう呆れた話は、金沢市場輸送の女性事務員から話を聞くこともありました。今考えると、それも打算と演技であったという可能性があるようにも思えます。

　とりわけ本恒夫社長というのは、被告発人東渡好信を金沢市場輸送に招き入れた人物でもありますし、入社したあとの被告発人東渡好信の振る舞いというのが、策士のようなもので、本件告発事件の重要人物であり、現場監督的指揮者と目されます。

　被告発人東渡好信が金沢市場輸送に入社してきたのは、平成２年の１０月の初めころだったと思います。あるいは９月中かとも思うのですが、私は早い段階から１０月と書いてきたので、当初は何か出所があったように考えています。事実関係における日時のはっきりした要点です。

　被告発人東渡好信の会社内における言動や振る舞いというのもまるで芝居でもみているような不思議さがありました。それまでの自分の視野が狭かっただけで、それが開かれたような思いも同時にあったのですが、不可解に思えるものでした。

　その後、被告発人東渡好信は、自分の野心を市場急配センターで実現したようなかたちとなり、運転手ではなく配車係をするようになるのですが、そのあとには、会社に来なくなったり、挙動不審な精神病者を装うような行動をするようになりました。本当におかしくなっていた可能性は否定できないですが。

　それでも被告発人東渡好信の場合は、曲がりなりにも会社の運転手としての仕事はしていたようです。そういう意味でもより特異に見えたのは、藤田博巳さんとYTの二人と、本恒夫社長の関係性でした。しかし、それも理解できる事情がまったくなかったわけではありません。

　元を辿れば、中西運輸商が佐川急便の広島・九州便から切られるという話がありました。だいぶん前からそういう話は出ていたのですが、話を聞いてずいぶん経ってから、実際にそのようになり、九州運送の仕事になったという話は聞きました。

　九州運送も当時の佐川カラーの運送会社でした。現在のことはしりませんが、当時の佐川急便は、市内の集荷配達のみが自社便の仕事で、路線の長距離業務は全て下請けの会社に任せているという話でした。

　たとえば、金沢から関東便は大東実業という運送会社がやっていましたが、それは佐川カラーではなかったと思います。九州運送は佐川カラーでしたが、他にも佐川カラーの運送会社というのは多く、社名をみないと区別がつかないぐらいだったと思います。

　九州運送は、名前を見ても一目で九州の運送会社だと思っていましたが、中国自動車道では、以前よりよく見かけるトラックでした。トラックの保有台数も多かったのだと思いますが、よく見かけていました。

　その九州運送の大型トラックを北陸道で見かけることが多くなったので、噂通り中西運輸商に変わったのだと思いながら見ていました。

[link:] » 九州運送 - Google 検索 https://t.co/oJv8OetjRy

<hr />

　Googleで画像検索をしましたが、当時の九州運送と思われるトラックの写真は見当たらず、いくつか見当たるのは佐川急便グループと書き、懐かしい飛脚のマークもあるコンテナだけです。九州運輸などはあるようですが、九州運送という会社自体が存在しなくなっている可能性が高そうです。

　どうもGoogleで九州運送と検索をすると、九州の運送会社という意味での検索結果になるようです。

　YTは中西運輸商で運転手をしていた頃から、九州の運転手とは仲良くしていたようです。私が中西運輸商で大型車に乗務していたのは２ヶ月ほどで、昭和６２年の１月から４月の間だったと思いますが、以前とは仕事の内容も異なり、大規模化していました。

　その１つに、０１４である東福岡店からの金沢便がありました。出発の時間というのも夜中の２時、３時となったような気もしますが、ホーム作業の時間も長く、運転手同士で話をしたり、運行でサービスエリアのレストランに立ち寄り、一緒に食事をすることもありました。

　ホーム作業の始まりは金沢より遅く、２１時とか２２時という時間だったかもしれません。金沢の場合は１８時から遅くても１９時がホーム作業の始まりだったと思います。

　私が４t車に乗務していた頃は、積み残しを積み込むため最終便までいるのがほとんどでした。金沢では２３時から０時の間が最終便の出発の時刻だったと記憶しますが、加賀店や福井店に立ち寄ることがほとんどで、福井店を出発するのは夜中の２時、３時で、もっと遅くなることもあったかも。

　中西運輸商の給料というのも売り上げは無関係で距離数で歩合が出ていたように思います。売り上げというのは話題にもならなかったし、１個でも満載でも運賃が同じというのも当時の佐川急便の長距離の仕事でした。

　大型車に乗務すると、タイヤの爆発の心配がなくなっただけでも、仕事は比較にならないほど楽に感じました。もともと佐川急便の仕事というのは規則としての時間厳守で、気象条件の悪化や交通事情による遅延というのは、市場の仕事とは異なり、寛大でした。

　加賀店から１便で出たこともあったのですが、夕方の早い時間での出発で、北九州の立ち寄りがありましたが、朝の早い時間には福岡で仕事が終わっていたように記憶にあります。加賀店だけで３，４便出ているような話も聞いたように思います。

　加賀店での佐川急便の仕事というのは漆器がほとんどでした。現在はテレビも薄型になっていますが、当時のブラウン管のテレビというのは箱の大きさも大きなもので、その大型テレビと似たような大きさのダンボールに梱包され、大きい割に重さというのは余りないものでした。

　金沢店でも漆器の同じような荷物がありましたが、そのほとんどは「箔一」と社名があったように記憶します。北陸新幹線の開業以降、テレビの番組でちょくちょく見かけるようになった会社でもあります。

　時刻は１３時１８分です。テレビのバイキングで、清原博弁護士が、今回は相撲協会が事件として告発すべきと、持論を述べていました。昨日の夕方から始まった貴ノ岩の暴行問題です。予想はしていましたが、予想以上にバイキングは大問題として取り上げ、世論を焚き付けた印象もあります。

　実際は、表に出てこない部分が大きな原動力ともなった大きな結果とも思えるのですが、結果を起こせば最悪で、弁護士はそれを都合よく利用したとも思えるのですが、報道の範囲では大きな扱いでも、見えてこない部分が大きいように思われます。

　暴行といっても今回の貴ノ岩の問題は、頬がはれた程度のようです。診断書が出たという話も見ていませんが、刑事事件としても傷害罪ではなく暴行罪になりそうです。暴行罪の法定刑は、以前、上限が懲役２年でしたが、その暴行罪での告発というのは聞いたことのない発想です。

　貴ノ岩が被害者となった傷害事件では、テレビで弁護士が罰金刑から懲役刑になる目安が、怪我の程度として全治３ヶ月と解説をしていましたが、それはかなり重い怪我だろうと思いました。

　貴ノ岩が被害者となった日馬富士の傷害事件のときも、刑事裁判について社会的影響も大きいと思われるジャーナリストの江川紹子氏が、貴乃花親方や貴ノ岩には、ずいぶん冷淡とも思える発言をしていましたが、昨夜もタイムラインをみると、これはと考えるツイートがありました。

▶ ツイート％amneris84（Shoko Egawa）％2018/12/05 18:07％ https://twitter.com/amneris84/status/1070243335434989568
&twitter(1070243335434989568){theme:light}
> 日馬富士のことはもういいから、今回の件がどういう経緯でどういう結果になったのかを書いたら？　→貴ノ岩が付け人に暴行　日本相撲協会が発表（スポーツ報知） - Yahoo!ニュース https://t.co/kwLIV5xKjR @YahooNewsTopics  
▶

　現時点の再読込でリツイートの数も４４件と多くはないようです。フォロワーの数も同じく２７０，９７２となっています。数日前から２６万台に近づいているように見ていたのですが、２７万台を超えたものずいぶん前のことです。

　記憶に自信が持てず、はっきりしないということをお断りしておきますが、数年前、初めてジャーナリストの江川紹子氏のTwitterアカウントを見た頃は、フォロワー数が１２万人台であったようにも思います。急激に数が増えるような現象も目にしたように思います。

　それが２７万台になってからは、万単位の変動というのは見なくなりました。もう２，３年は、その状態が続いているような気がします。フォロワー数の推移を調べるサイトもあるようですが、数が多すぎると計測不能となるようです。

　それがどう影響しているのかわかりませんが、ジャーナリストの江川紹子氏の場合は、プロフィールの名前が「Shoko Egawa」となっており、ローマ字として読めば、それとわからなくはないですが、検索結果にも反映はされにくいように思われます。

　SEO対策という言葉自体、最近は余りみかけなくなっていますが、ジャーナリストとして活動するならば、知名度の上昇も収入のアップにつながるのが原則論のように思われます。その割にずいぶん早い段階で、認証済みアカウントのマークをつけていました。

　Twitterのプロフィールの内容というのも、Twilogのリンクのみです。これもアイコンのネコの写真とともに初めに見たときから変わっていないように思います。

　ジャーナリストの江川紹子氏についても、これはと取り上げておきたかったツイートやブログ記事がいくつかあるのですが、告発事件の事実関係を優先させています。深澤諭史弁護士やモトケンこと矢部善朗弁護士（京都弁護士会）も同じです。

　YTが金沢市場輸送に入社した時期として記憶にあるのは、昭和６３年の１２月です。１２月の２０日頃過ぎに、大型保冷車に彼を同乗させて、石巻に行きました。珍しいことに行き荷が石巻市内で、荷物は玩具のようなものでした。

[link:] » おもちゃのハローマック - Wikipedia https://t.co/dUMJpdNiXX

<hr />

　このハローマック石巻店への運行は、夕方に富山県高岡市から荷物を積んだような記憶があります。他のハローマックの仕事では金沢市の浅野本町から荷物を積んだ記憶があったので、今考えると整合しません。

[link:] » 浅野本町 - Google マップ https://t.co/OGxS5Uc4Cu

<hr />

　確認のため調べたのですが、金沢市の浅野本町というのは、思っていたより広範囲です。記憶にある荷物を積んだ場所は、なるわ方面に向かった東大通の右側の路地で、路地にしては大型車も余裕で駐車できるような広い道路でした。

　その東大通の右側は、別の住所になるのかとも考えていました。浅野本町には昭和５７年に２，３カ月、アパートに住んだこともあったのですが、乙丸陸橋に近い方で、東大通の右側の路地というのは、ほとんど足を踏み入れたこともなかったように思います。

　アパートには風呂がなかったので、スクーターで東山の広い道路沿いの銭湯まで行っていたのですが、それがずいぶん遠く感じたことも印象に残っています。

　そのスクーターで銭湯に通ったという記憶は残っているのですが、他にスクーターでどこかに行ったという記憶は残っておらず、神宮寺の辺りから鳴和の近くまで夜に歩いていたという記憶は残っています。住んでいた期間も短かったですが、記憶というのも断片的となっています。

　その浅野本町のことで、もう一つ記憶にあるのは、大学の下宿のような場所があったことです。金沢東署交差点から乙丸陸橋に向かうと、左手に少し入ったところにある建物でした。道路沿いは空き地かあるいは駐車場になっていたように思います。

　ちょうどその頃は、テレビアニメで、「おじゃまんが山田くん」という番組をやっていました。大学の寮のような下宿を舞台にしたアニメで、当時は新しく出てきたような、リアリティのある変わったアニメだったのも印象的でした。

　その下宿のような場所に、何度か出入りしたのも、被告発人安田敏がいたからです。被告発人安田敏自身もそこには住んではいなかったと思いますが、若者が出入りしたむろする溜まり場のようになっていました。

　昭和５６年の１０月ころのことであったと思います。その９月は２２日辺りまで、私は金沢市小立野の金沢少年鑑別所に入っていましたし、１７歳の誕生日を迎えた頃には、金沢市笠舞の他の溜まり場に出入りしていました。鑑別所で知り合った小さな暴走族リーダーのところです。

　それもちょうど１７歳の誕生日の前後だったので、まだ１１月中だったと考えられるのですが、七尾市の家庭裁判所に金沢の調査官との接見に行ったとき、その待合室で、被告発人安田敏とその母親と会ったのです。

　けっこう久しぶりに会ったと思っていたのですが、それというのも前回会ったときとは、別人のように被告発人安田敏が痩せこけていたからです。シンナー中毒が体に大きなダメージを与えていたようです。その次に会ったのが、松原病院の精神科の閉鎖病棟でしたが、今度は肥えていました。

　被告発人安田敏とは、昭和５６年の１０月ころ、金沢市入江のアパートでも一緒になったことがありましたが、その場には、当時、松元組の暴力団員だった被告発人HTNも顔を出していました。OSNもいましたし、被告発人大網健二もいたように思います。

　私はもともとOSNや被告発人大網健二と一緒に行動していたのですが、その時は別行動という感じで、被告発人安田敏と一緒に浅野本町の下宿のような場所に行っていたのです。

　その下宿のような場所に住んでいる人は、大学に通っているという人もいたように思いますし、歯科技工士の専門学校に通っていると話す人もいました。その時は歯科技工士という知識もなかったのですが、説明を受け、なんとなく理解は出来ました。

　だいぶん前に書いていると思いますが、松原病院に被告発人安田敏の面会に行ったのは、翌年の昭和５６年になりますが、２月頃だったように思います。３月になっていたとも、まだ１月中だったとも考えられるのですが、雪が残る寒い季節であったと思います。

　３人で兼六園に遊びに行っていたのですが、そのうち一人が近くの松原病院に被告発人安田敏がいるはずなので、会いに行ってみようと言い出し、病院の正面玄関でも実弟だと言い出し、建物の裏側の鉄扉から病院に入り、５階あたりで被告発人安田敏に面会をしました。

　面会室のようなものはなく、看護婦の女の人らも慣れていなかったので、実弟というでまかせを確認することもなく、面会をさせたのだと思いますが、本当のことを知っている側から見ると、かなりふざけた態度での申し出でした。

　被告発人安田敏は、「おっさまぁ」などと言いながら、大歓迎で迎え入れてくれました。なにか病院に対する不満も訴えていたかと思いますが、細かい話は、よく憶えていません。眉を剃るなどして保護房に収容されたなどとも話していたように思います。

　体の方はすこぶる元気そうでしたが、入院患者の心得としては病院から相応の扱いを受けるのも無理のないことかと思っていました。その次、どこで被告発人安田敏に会ったのか、すぐには思い出せないですが、違和感の言動は特になく落ち着いた感じになっていたようには思います。

　被告発人安田敏は、その後、シンナーに手を出して、もう一度、松原病院に入院したようです。本人の話でしたが、そのときは自分で体に異変を感じ、自ら病院に行って入院をしたという話でした。入院期間も長くはなかったと聞いたようにも思うのですが、私の記憶も曖昧になっています。

　消火器販売の出張で新潟のホテルの宿泊しているときに、シンナーで手を出したという話と、消火器販売で新潟の警察署で取り調べを受けたという話の記憶が、私の中では混在しています。いずれにせよ、消火器販売は昭和５８年９月以降のことです。さらに１１月以降とも特定出来ます。

　石巻市のハローマックへの仕事は、私が新車の時から乗務していた石７５９９号の大型保冷車での最後の運行ともなりました。イワシの運搬の仕事への移行でした。当時のナンバーは石だけでしたた、その翌年辺りには石川ナンバーと変わりました。

　時刻は１７時１６分です。ミヤネ屋でも特集のようなかたちで取り上げていましたが、everyのニュースでも静岡県の看護師連れ去り殺害事件の初公判を取り上げていました。主犯格が新潟市内のビジネスホテルで自殺したとされる事件で、逮捕監禁などの起訴で、殺人ではないようです。

　映像に法廷内の様子が映し出され、３人の裁判官と、裁判官に向かって右側の席に二人の女性の姿がありましたが、向かって左側の席は空席でした。左右の陪席裁判官も女性だったようです。

　気になったのは、２，３日前の東名高速の危険運転致死傷罪の裁判のことで、席に「弁護側」というような大きな張り紙があったことです。そのときも裁判官に向かって右側の席が検察官の席となっていました。

　以前、裁判官に向かって右側の席が弁護人の席で、左側の席が検察官と決まっていたように思います。私がTwitterを始めた頃には、やはりそれが当然のことのように発言する弁護士の可能性の高いアカウントもいました。こたんせ、のことです。

　ネットで話題になっていたのですが、裁判所の構造で左右が逆になるという話もありました。つまり傍聴人らが出入りするドアのある側が検察官で、反対側が弁護人になるという話です。それは合理性のある説明と思っていました。

　テレビのドラマでも見たことがないし、他の裁判所の法廷のことはわからないので比較は出来ないのですが、金沢地方裁判所の場合、法廷の外の窓側に通路があって、被告人は刑務官に連行され、その通路から出入りをしていました。裁判官に向かっては右側になります。

　平成１１年の事件の控訴審で、国選弁護人だった小堀秀行弁護士と高検の検察官の席が入れ替わっていたことも、前に、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のツイートの範囲で記録があると思います。

　このところ、残っているはずと思っていた記録が、検索で見つからないということがけっこうあるので、断言はすべきでないし、確認もして方がよいとか考えています。

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「小堀 席」の検索結果 - Twilog https://t.co/oM9VBs5HCY

<hr />

▶ ツイート％kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）％2018/08/03 12:22％ https://twitter.com/kk_hirono/status/1025220434659176448
&twitter(1025220434659176448){theme:light}
> もう１，２年は書いていない気もしますが、完全に忘れていたわけではなかったと思います。それは、平成１１年の傷害事件の控訴審で、国選弁護人だった弁護士と検察官の席が入れ替わっていたことです。名前が思い出せないと思ったのですが、小堀秀行弁護士でした。  
▶

▶ ツイート％kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）％2016/03/07 19:53％ https://twitter.com/kk_hirono/status/706794948717228033
&twitter(706794948717228033){theme:light}
> 改めて考えてみると、国選弁護人だった小堀秀行弁護士から席を変わろうともちかけるはずなどなく、名古屋高検金沢支部の検察官からの持ちかけであったと考えるのが自然です。  
▶

▶ ツイート％kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）％2016/03/07 19:25％ https://twitter.com/kk_hirono/status/706787805079298048
&twitter(706787805079298048){theme:light}
> それを私が細かく調べたのは理由があって、平成11年の被害者AAさんの父親AKさんの傷害事件での控訴審の公判において、国選弁護人だった小堀秀行弁護士が通路側の普通、検察官のいる席に座り、名前は忘れ声もほとんど記憶のない肩幅の広い立派な体格の検察官が窓側の席にいたのです。  
▶

　Twilogでの検索結果は、２０１８年８月３日に１つ、２０１６年８月７日に２つという３つのツイートでした。数も少なく感じましたが、２０１５年より前にないのは、どうかと思いました。奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)の方もみておきましょう。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-06 17:41／2010-08-06 18:33 URL： https://twitter.com/kk_hirono/status/1070599134707503105 https://twitter.com/hirono_hideki/status/20455558369
&twitter(1070599134707503105){theme:light}
> 自分の平成１１年の事件の控訴審でも、国選弁護人だった小堀秀行弁護士が、裁判官に向かって左側の席に座っていたことがあった。検察官は右側。ほとんど何もしゃべらない高検の検察官だった。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-06 17:41／2011-05-28 22:46 URL： https://twitter.com/kk_hirono/status/1070599160657719296 https://twitter.com/hirono_hideki/status/74471555924639744
&twitter(1070599160657719296){theme:light}
> 兼六法律事務所 http://ow.ly/555Uw こちらの二木 克明弁護士が主任弁護人だった、とのことですが、テレビでは所長の小堀秀行弁護士の姿も法廷の弁護人席（3人いました）にありました。二木弁護士は、元検察官でもあったようです。ここの経歴に書いてあります。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-06 17:41／2011-05-28 23:16 URL： https://twitter.com/kk_hirono/status/1070599193889136640 https://twitter.com/hirono_hideki/status/74479123464077313
&twitter(1070599193889136640){theme:light}
> 庶民の弁護士　伊東良徳　刑事裁判の法廷の様子 http://ow.ly/556A6 傍聴席から見て左側は全国的には検察官席です。←　これ見ると裁判所の場所や構造によって変わることがあるみたいです。何が理由だったのか小堀秀行弁護士に証言してもらいたいです。
◁◁◁
<hr />

　検索結果は同じ３件のツイートで２日分となっていますが、二木克明弁護士が主任弁護人という無関係のツイートも１つあります。２０１０年８月６日と２０１１年５月２８日のツイートで、２０１２年から２０１５年は、なかったということになりそうです。

　このところ、テレビの法廷映像で、裁判官に向かって右側の席の方が検察官ということが多いのではと感じていたのですが、東名高速の裁判員裁判は、その構成で席に張り紙がしてあったのでとてもわかりやすかったです。

　その東名高速の危険運転致死傷罪での裁判員裁判では、張り紙をされた弁護側の席に、男性の弁護士が２人座っていましたが、ネットで調べても、弁護士の名前がわかるような情報はありませんでした。富田林警察署の逃走事件と同じで、弁護士の特定に繋がる情報は皆無でした。

　刑裁サイ太のツイートととしては、あるいはご紹介済みかもしれませんが、深澤諭史弁護士のリツイートとしてご紹介をしておきたいと思います。東名高速の危険運転致死傷罪の裁判員裁判に言及したツイートです。

▷ リツイート→fukazawas（深澤諭史）＞uwaaaa（サイ太）｜2018/12/04 15:03／2018/12/04 12:56｜https://twitter.com/fukazawas/status/1069834609930657792 ／ https://twitter.com/uwaaaa/status/1069802517075156993
&twitter(1069834609930657792){theme:light}
> RT @uwaaaa: 例の東名高速のあおり運転の事件で，冒頭陳述で弁護人が「報道されている話は全部リセットしてください」と言ったらしいんだけど，ワイドショーがそれを伝えた直後なのに，ガンガン被告人の人格攻撃をやり始めていて，本当に頭がおかしいと思った。  

　時刻は１８時１７分です。テレビの石川県内ニュースで、白山警察署が出ていました。そんなに経っていないように思いますが、同じくテレビで松任警察署を見ていて、白山市の警察署の名称は、そのまま松任警察署になっているのかと思っていました。建物も初めてみたように思います。

　ちょうど半年前ということでしたが、白山市内の製紙工場で硫化水素による死亡事故があって、書類送検されたというニュースでした。３人ほどの人が亡くなったという事故だったように思います。社長のような人もテレビに出て責任を感じるというようなお話をしていました。

[link:] » 石川県白山警察署 - Google マップ https://t.co/VNNhXfxGvl

<hr />

　調べたところ、白山警察署は、松任警察署とは違う場所にあるようです。国道８号線で小松方面に向かった左手です。国道を基準にすると松任駅とは逆方向です。松任警察署は、松任駅に向かう左手に見えたと思います。道路からは少し離れていましたが、新しい建物に見えました。

```
白山警察署（はくさんけいさつしょ）は、石川県警察が管轄する警察署の一つである。2012年4月1日に、松任警察署と鶴来警察署を統合し開署した。

本項目では、統合前の松任警察署についても記述する。

［source：］白山警察署 - Wikipedia https://ja.wikipedia.org/wiki/%E7%99%BD%E5%B1%B1%E8%AD%A6%E5%AF%9F%E7%BD%B2
```

```
松任警察署（まっとうけいさつしょ）は、白山警察署に統合される前の警察署で、白山市の旧松任市と旧石川郡美川町の両地域、野々市市を管轄していた。

［source：］白山警察署 - Wikipedia https://ja.wikipedia.org/wiki/%E7%99%BD%E5%B1%B1%E8%AD%A6%E5%AF%9F%E7%BD%B2
```

[link:] » 〒924-0882 石川県白山市八ツ矢町６１７ - Google マップ https://t.co/WdKkCXe6wp

<hr />

　上記が松任警察署があった住所のようです。Googleでみると、記憶にあったより、松任駅に近く近く見えます。歩いてすぐに行けるような距離に見えますが、車やトラックで通りかかっていた記憶では、けっこう離れていたような感覚でいました。

　松任警察署は大きな建物ではなかったですが、道路から５０メートルぐらいか奥まった場所で、周囲に大きな建物がなかったので、通りかかると目立っていました。最初に見たのが昭和５７年の春のことで、そのあとで二日市で免許取り消しとなるスピード違反で捕まりました。

```
銘文によると康永元年（1342）の作で、鎌倉時代の技法を踏襲した大変美しい仕上がりです。なお、本像は、明治維新以前は、白山本宮（現白山比咩神社）の白山寺にあった、地蔵院護摩堂の本尊であったと伝えられています。

［source：］銅造 地蔵菩薩半跏像 附台座、光背 - hakusansibunkazaitanboumap http://www.city.hakusan.ishikawa.jp/bunkazai-tanboumap/zizoubosatuhankazou.html
```

　Googleマップで松任駅の近くに印が出ていたので、気になって調べてみました。白山寺というお寺の名称は初めて見たように思いますが、「白山本宮（現白山比咩神社）の白山寺」とあります。

　前にも松任市の近くに白山姫神社というのを見つけて、気になって調べたことがありました。奥津比咩神社は奥津姫神社とも表記されることがあるようですが、白山市の鶴来にある白山比咩神社は、石川県内でも特に有名な神社で、全国の白山神社の総本宮とも聞きます。

　テレビで松任金剣宮というのを見て、気になることがあったので、Googleマップで場所を調べたところ、すぐ近くに白山姫神社があったのです。

　松任市というのは、私自身あまり縁もなかったのですが、特に印象に残っているのは、被告発人大網健二が姫のNKさんのアパートがあって、遊びに行っているとか、行ってきたと私に話していたことです。

　松任市のどこあたりという話は聞かなかったし、私には松任駅と国道８号線ぐらいの土地勘しかありませんでした。ミールの倉庫移動などで仕事では行っていましたが、地名がいろいろとあって、憶えられるものではありませんでした。福留などもその１つです。

　平成３年の春か夏頃か、時期がはっきりしないのですが、たぶん金沢市場輸送の給油所で、会話をした人物が、姫のNKさんと同じアパートに住んでいると話していました。その人と会話をしたのは、そのときだけだったかもしれません。

　持ち込みの２t車で市内配達の仕事をしていると話していたように思います。自ら名乗っていましたが、とても変わった苗字だったので今でもよく憶えています。２，３カ月前、能登地方の七尾市の近くだったと思いますが、同じ苗字の人というのをテレビで見ました。

　Googleで調べたところ、全国人数が、およそ１５０人となっています。読み方が２つになっていますが、私の記憶にあるものとは少し違っていて、私の聞き取りに間違いがあったのかもしれません。能登地方では歴史のある苗字でもあるようです。

　持ち込みの運転手の人は、社員の運転手より自由度が高かったので、最低限会社に来ないような人もいました。私も北都運輸の市内配達の仕事をしていた頃は、乗務していた４トン保冷車を自家用車のように通勤にも使い、会社に顔を出すのは週一というようなこともありました。

　もともと自由度の高い社風でもあったと思います。会社の用事としては日報の提出と洗車と考えられますが、その姫のNKさんと同じアパートに住むという人については、日報を書く様子も見かけた記憶がありません。仕事の内容も不明です。

　中には、日報を書くのにずいぶんと時間をかけている人もいました。まだ、市内配達が金沢市場輸送の事務所で一緒になっていた頃のことです。

　金沢市場輸送の事務所というのは、事務所とは別に左手に小さなドアの出入り口があって、そこが長いテーブルを６つか８つほど並べた運転手の休憩室のようになっていました。奥の方には、４畳半より小さなスペースだったように思いますが、畳敷きでテレビのあるスペースがありました。

　麻雀が始まる時は、テーブルの一部を片付けて麻雀卓を設置していたようにも思いますが、向い合せ２列にしていたと思うテーブルでは、市内配達の運転手が、時間を掛けて日報を作成するという風景がよくみられました。

　市内配達といっても、卸先のスーパーなどでは伝票の形態もずいぶん変わっていたので、いちがいには言えないのですが、ずいぶんと難しいことを時間を掛けて取り組んでいるように見えていました。

　その後、平成３年の６月頃から私が経験した市内配達では、日報の作成に難儀するようなことはなかったのですが、それも仕事内容や配達先の決まり事が違っていたとも考えられます。また、そういう伝票のとりまとめも、被害者安藤文さんの仕事であったと考えられます。

　仕事をする被害者安藤文さんの姿は、電卓を打つスピードがとても早く正確に見えたという印象があります。一定のテンポで変化を見せずに同じことを繰り返していたので、タイプミスのようなこともほとんどなかったと考えられますし、それも簡単そうにやっていました。

　それは、市場急配センターの仕事をするようになってから市場急配センターの２階事務所で見ていた被害者安藤文さんの姿のことです。

　時刻は１２月７日１２時８分です。直前のツイートが１７時間前となっていましたが、一行投稿しないままになっていたので、そのまま投稿したところです。

　藤田博巳さんですが、被告発人松平日出男と一緒にいたところの記憶があるものの余り具体的には思い出せません。藤田博巳さんは、麻雀のメンバーとしては記憶も薄いのですが、麻雀をしていたような気もします。

　これまで余り注目してこなかった人物ということもあり、記憶が薄れるのも早かったのかもしれません。家が金沢市内のどの辺りにあるのか聞いていたようにも思うのですが、それも思い出せません。金沢市外とか会社から遠いところに住んでいるという話は聞いていなかったと思います。

　免許取り消し中だったとすると、通勤をどうしていたのかも気になるところです。家族が送迎するようなことはなかったように思いますし、家族の姿を見たり、あるいは家族の話も聞いたことがなかったかもしれません。それでも娘がいるような話は少し聞いたような気もしないではないです。

　なにぶん記憶が薄いので、歯切れの悪いはっきりしないことしか書けませんが、それはそれで書いておくことに意味はあると思います。私の勘違いで迷惑をおかけすることを避けるためでもあります。

　昭和から平成の変わり目というのは、月日の流れを追う上でも把握しづらい面があるのですが、YTが金沢市場輸送に来たのが、昭和６３年１２月とすると、藤田博巳さんが来たのは、それより１，２ヶ月後ぐらいであったような気がするので、平成元年になっていたと考えられます。

　藤田博巳さんとYTが金沢市場輸送をやめたのは、ほぼ同時で、平成２年６月の下旬ではないかと考えられます。片山津温泉ホテル長山の慰安会に参加していたのは確かなことで、５月６月はタケノコと金沢港のスルメイカの仕事で忙しいので、それが落ち着いた時期だったと考えられます。

　慰安会は、ほぼ全員参加だったと思います。それまでは希望者だけを募って慰安会に行っていたようです。その形態で私は参加したことはなかったのですが、昭和６２年６月も、ほぼ全員参加のような慰安会があり、場所は山中温泉で、キャッスルバーデンホテルでした。

　ややこしい名称でしたが、なぜかよく憶えています。一時期、テレビCMでも見ていたような気がします。その頃としては、名前だけではなく、新しいスタイルの温泉旅館という感じでした。KKさんが参加していましたし、OMさんの息子もいました。七尾市のSという社員運転手もいました。

　七尾市のSに関しては、佐川急便の市内配達の仕事をしていたという話で、年は私と同じか、１つか２つ年上だったと思います。他とは違うタイプの若者でもあり、積極性も強かったのか、竹沢俊寿夫妻に結婚式に参加してもらったという話を聞きました。

　金沢市場輸送の事務所が中央市場前のテナントビルから移転したのが、昭和６３年の７月だったと思います。７月でも初めの方だったと思うのですが、それは早い段階から割合はっきりした記憶として思い出していました。

　中央市場前にあった金沢市場輸送の住所は、今も憶えています。覚えやすい住所でもありましたが、金沢市西念町４リの１です。あるいは、西念と西念町は別になっているか、別になっていたのかもしれません。西念は金沢市内でもかなり範囲の広い住所だったと思います。

[link:] » 西念 - Google マップ https://t.co/L4hwB9ZPEO

<hr />

[link:] » 西念町 - Google マップ https://t.co/xxfzNyRUak

<hr />

　どういうわけか、西念町で検索すると、国道８号線バイパスの西念の交差点の一角だけが範囲表示されました。すべてバイパスのその上を通る北陸自動車道上となっています。ありえないことですが、そこに「西念町」という表示があります。

　これまでも金沢市の西念については、西念と西念町というのを両方見てきたように思います。Googleマップには西念町緑地という表示もありますが、よくみると、交差点の名称も、西念町西、西念三丁目東、西念南、西念町などと、すぐ近いでも混在しているようです。

　私の経験上の感覚としては、金沢市西念というのは、金沢中央卸売市場のことになりますが、いくらか離れた場所に、電波塔のような目立つ建物もありましたし、平成９年頃には出来ていたと思う法務局も、西念になるはずかと思います。

　金沢市で法務局というのは、他に新神田にありました。新神田の法務局は労働基準監督署が入っていました。そちらにも直接相談に行ったことがあったのですが、西念の法務局にも出向き、人権擁護局のような人と話をしたことがありました。

　西念の法務局は、被告発人大網健二と一緒に行ったこともありました。なにか登記簿のような話であったように思いますが、よく思い出せません。成り行きで久しぶりに思い出したとも思います。

[link:] » 金沢魚商会館 - Google マップ https://t.co/csdpn2ki9O

<hr />

　住所は「石川県金沢市西念４丁目１４−８」となっています。上記の「金沢魚商会館」が金沢市場輸送の前の事務所があったテナントビルです。「金沢魚商会館」というのは今回調べて初めてしりました。

　ストリートビューで確認しましたが、建物自体は昭和５９年当時と同じと思われます。外装のペンキの塗替えをしているとは考えられますが、比較的新しい建物にみえます。昭和５９年よりだいぶんあとに建設され、廃墟のようになった建物というのは、けっこうありそうに思います。

　２階建ての、テナントビルと言って良いと思いますが、ストリートビューをみると、飲食店が多いようです。昭和の時代もうどん屋が１つあり、平成３年には小さな食堂も１つあったように思いますが、以前は、乾物屋のような焦点が多かったように思います。

　２階を見ると、数えて１３の窓があります。窓の１つが１部屋になっていたと思います。たぶん右から３つ目が、金沢市場輸送の事務所のあった部屋です。隣の４つ目が、竹沢俊寿の社長室でしたが、壁の半分は空間で繋がっていて、アコーディオンカーテンで仕切られていたと思います。

　この道路沿いの並びではないですが、右端の階段から登った奥側に、守田水産輸送の事務所がありました。右から１番目、２番目の部屋は、余り人の出入りも見なかったように思います。

　竹沢俊寿の社長室から間に１つか２つあいていたようにも思うのですが、途中から市内配達の事務所が出来ました。その頃は市内配達の仕事をすることがなかったので、用事もなかったのですが、遊びに行くような感覚で部屋に入ったことはありました。

　Yという名前だったと思うのですが、女子事務員がいました。被告発人池田宏美よりあとに入社したように思いますが、金沢市場輸送の事務所で仕事をしていたという姿は思い出せません。たぶん当時、２０代の後半だったのだと思いますが、ずいぶん年上に見えていました。

　いかにも学校の先生という感じの女の人で、体格は大きかったと思います。真面目そうでいかにも学校の先生というイメージでしたが、その後、運転手のTさんと不倫関係になり、それを本恒夫に咎められて、退社したというような話を聞きましたが、噂レベルのようにも思える話でした。

　Yという女性事務員が金沢市場輸送をやめたのは、たぶん、二口町に事務所が移転した後だったと思いますが、新しい事務所の机で仕事をしている姿を見たという記憶も残っていません。

　一緒にイワシの運搬をしていた大西真さんのおごりで、片町に飲みに行ったことがあったのですが、その場には被告発人池田宏美とYさんがいたように思います。被告発人池田宏美がいたのはよりはっきりしています。他に輪島のMYがいました。私の２つ年上です。

　私がやった１回目のイワシのシーズンで、２台のダンプのうち１台に乗務したのが大西真さんでした。もう１台は松浦さんですが、その前のシーズンの時は、松浦さんの友人らしい別の人がもう１台のダンプに乗務していました。名前は現在思い出せなくなっています。

　正確にいえば、その前のイワシのシーズンと書きましたが、イワシの仕事はほとんど終わった頃で、運搬の仕事も少なかったと考えられます。具体的には昭和６２年４月になります。ダンプが新車で納車されたのが、その頃になるかと思います。

　私が新車の大型保冷車である７５９９号に乗務したのも同じ昭和６２年４月でしたが、ダンプの納車はそれよりいくらか早かったようにも思います。保冷車も２台のダンプもいすゞのトラックでした。

　松浦さんの姿を見たのもそれが最初でしたが、一緒にダンプに乗っていた人とは、一緒にミール移動の仕事をしたことがあったようにも思います。

　私は、ちょうど中西運輸商から金沢市場輸送に戻った時期でもあったので、松浦さんらはその前にも金沢市場輸送でミールやイワシ関連の仕事をしていたのかもしれません。しかし、私が中西運輸商に移る前には、金沢市場輸送にいなかったはずと思われます。

　今は、時期も特定しづらいですが、中西運輸商で大型車に乗務していたのは、ちょうど２カ月ほどでした。月は１月から４月にまたがっていたようにも思うのですが、それだけ計算が合わない気もするので、１から３月か、２から４月だったのかもしれません。

　前にも書いてきたことだと思いますが、本恒夫が私のアパートに夜に訪ねてきて、車の中で話をしたのですが、新車を入れて台数を増やすので、戻ってきたほしいという誘いがありました。私を新車に乗務させたのは竹沢俊寿の鶴の一声だったという話もありました。

　大型保冷車もほぼ同時にもう一台の新車の納入があり、私より少し早かったように思いますが、それに乗務したのが名古屋のKさんでした。正確には愛知県瀬戸市と聞いたこともありました。瀬戸市というのは、瀬戸少年院として知名度があり、知っていました。

　名古屋のKさんは、元暴力団員で、無茶苦茶な運転をするとも聞いていました。耳を疑ったのですが、高速道路ではクラッチを踏むのが面倒で、踏まずにギアを変えているという話でした。ギアが壊れてエンジンがロックすれば、とんでもないことになりそうですが、そういう話は聞いていました。

　福井県の敦賀市から京都府の舞鶴市への国道２７号線というのも、よく通行する国道で、ほとんど全てが対面通行でしたが、大型車で反対車線をそのまま突っ走り、対向車が反対車線に出て避けるという話でした。

　もともとは、竹沢俊寿がヤクザの組長をしていた頃の子分という話もあったのですが、トラブルを起こしたり、もめたりして会社をやめたようです。やめた頃には金沢市場輸送の駐車場で次々にタイヤをパンクさせたということがあり、それが新聞の小さな記事にもなっていました。

　金沢中央卸売市場の鮮魚の売り場で、トラブルを起こした時は、上半身裸になって入れ墨を見せて居直り、袋叩きのような状態にされて、荷受けの人の集まる小屋をホークリフトで持ち上げたとか、持ち上げようとしたというような話も聞きました。

　１年ほどすると、また戻ってくるというのな話もあったのですが、反対の声が強かったということも今は考えられますが、その話は立ち消えとなり実現はしませんでした。

　その名古屋のKさんと松浦さんの３人で、双葉湯という銭湯に行ったことがあったのですが、二人とも前身が入れ墨で、それも宗教色の強い入れ墨であったように印象に残っています。鮮やかな黄色の色も入っていて、それは当時、珍しくも思いました。

　思い出したのですが、平成４元２月１日の夜に、被告発人安田繁克と会ったとき、彼は黒い暴走族の特攻服のような作業着で、肩から腕の辺りに縦書きで「松浦商店」という刺繍を入れていたように思います。松浦とあったことは間違いないように思います。

　時刻は１５時５９分です。告発事件の記述に専念することを心掛けてきたのですが、やはり刑事司法を取り巻く現状として、取り上げておいた方がよいと考えることが出てきました。

　まだまだ書いておきたいことがあるのですが、それもひとまとめとして１つのファイルにしておきたいとも考えています。このファイルは現在、２０２７行です。ツイートのこともあるので、空行を１つずつ入れていますが、半分としても１０００行を超えたあたりです。

　改めて考えていたのですが、藤田博巳さんとYTが金沢市場輸送にいた期間を昭和６３年１２月から平成２年６月とすると、平成元年中というのも、私は北都運輸のローカルの仕事などで、金沢市場輸送の会社の事務所には、余り顔を出してはいなかった時期ということになりそうです。

　道理で、金沢市場輸送の事務所で藤田博巳さんとYTの姿を見た機会は、比較的少なかったと合点したのですが、同様に長距離の仕事先から金沢市場輸送の会社に掛けた電話でも、彼ら２人が出たことは多くなく、直接指示を受けることもほとんどなかったように思いました。

　YTに関しては、中西運輸商で配車係をしていました。配車係をするようになったのも免許取り消しがきっかけだったように思うのですが、細かいことは思い出せません。ただ、少なくとも大きな違反や事故で点数がなくなったという話は聞いておらず、違反の積み重ねだったのかもしれません。

　中西運輸商というのはもともと配車の会社でした。ややこしくなって誤解を生じる可能性もあるかと思ったので、これまでは中西運輸商で通してきましたが、中西運輸商の自社便の運転手というのは、中西水産輸送の社員だと聞いたことがありました。どちらも有限会社だったと思います。

　「みずや」という言葉も聞いたことがありましたが、要は、長距離の運行を請け負って、それを他の運送会社や運転手にやらせる、という実質、紹介業のような仕事だったようです。中西運輸商は、初めからそれを徹底したようなスタイルでやっていました。

　それでも私が最初に入社した昭和５９年１２月から昭和６０年というのは、それほど規模は大きくなかったと思います。それでも当時から佐川急便の九州便は、傭車が多かったように思います。

　傭車というのは、傭兵という言葉もありますが、簡単にいえば傭われのトラックになるかと思います。これは金沢市場輸送で本恒夫などがよく使っていた言葉で、中西運輸商ではそれほど聞いてはいなかったような気もします。

　前にも書きましたが、私は４t車だったので、佐川急便の仕事というのも、広島・九州便の最終便まで待った積み残しがほとんどでした。季節によって日暮れの時間は違いますが、まだ明るい時間からホーム作業を始めていたという記憶もあります。

　現在のことはしりませんが、当時の佐川急便の長距離の仕事というのは、ホームにベルトコンベアで荷物が流れ、それを支流のようなかたちで担当路線に引き込んでいました。そのローラーは、ホームにつけたトラックの荷台の奥まで繋がっていました。

　荷台の中央にはローラーが３つほど連結されていたと思います。ローラーをそのままにして荷物を積み上げていくというのも当時の佐川急便のお決まりのスタイルでした。荷物は満載が基本で、荷物の隙間に拳が入っていはいけないという指導を受けていました。

　ベルトコンベアから路線の荷物を引き込むのは、段ボール箱などに大書きされた番号でした。九州便の場合は、全てが０番台でした。例えば福岡は０１でしたが、０９までは全て同じ九州便の荷物でした。一つだけ例外があったのは、０１４という番号で、これだけは東福岡店降ろしでした。

　ベルトコンベアの荷物は流れっぱなしということはなく、集配のトラックが戻ってきて流す荷物でした。運転手同士で雑談をすることもよくありました。出発の早い順に１便、２便などと呼んでいましたが、金沢店は荷物の量も多くはなかったと思います。

　２３時頃か、黒部便というのが到着して、その時は一番忙しくなりましたが、富山のYKK吉田工業のアルミサッシの荷物で、ほとんどは部品のような軽い荷物でしたが、細かい荷物でもありました。それも積み残しのようなものを持ってきていたようです。

　中西運輸商は４t車の数が少なく、それ以上に４t車の運転手がいませんでした。もともと大型車がメインの仕事でもありました。当時の中西運輸商の運転手というのは、大半が九州の運転手でした。中には鹿児島という人もいました。

　九州の運転手の方が地元に帰って休める時間が多いとも言われていました。それでも中西運輸商の自社便よりは、九州各地の運送会社の傭車が多かったように思います。自社便の方は、富山や加賀店の方に多く割り振っていたとも考えられます。

　当時は携帯電話もない時代でしたが、急に傭車の都合が悪くなったとか対処を迫られた場合、会社と同じ金沢店の方が安心という考えもあったのかもしれません。当時はそこまで考えなかったですが、金沢店に優先的に傭車を回していた可能性はあるかと思います。

　特によく見たのが、鹿児島県の橋口商店と長崎県の鷹島運送でした。他にも串木野とか、宮崎の日南などの運送会社もあったと思います。橋口商店は特に信頼が高いという話もありました。鹿児島県阿久根市の運送会社でした。

　阿久根市でも大きな橋で渡る島のようなところで、東町（あずまちょう）とも聞いていました。私は、金沢市場輸送の大型車で一度、そこに養殖ブリを積みに行ったことがありました。行き先は、大阪と京都の市場だったと思います。

　京都市で荷降ろしを終えた後、広い道路にトラックをとめてパチンコをしていたのですが、そこでパトカーに駐車違反の切符を切られたこともよく憶えています。数年ぶりの違反であったようにも思います。他に富山で反対車線のパトカーにスピード違反の切符を切られました。

　北陸自動車道の反対車線を走行していたパトカーが、少し先のインターチェンジでUターンし、追いかけて来たのです。正確な速度など計測できていなかったと思いますが、適当なスピードで切符は切られました。

　鷹島運送の運転手とYTは特に親しくしているような話を聞いたこともありました。長崎県の鷹島は鎌倉時代の元寇の襲来で有名なようですが、当時はまだ元寇のことは知らなかったかもしれません。長崎県松浦市の近くだったと思います。

　その長崎県松浦市には西日本最大ともいわれる大きな魚市場がありました。金沢市場輸送の大型車で、２，３回、鮮魚を積みに行ったことがありました。

　平成３年になっていたように思いますが、その長崎の松浦市の魚市場で、被告発人東渡好信がトラブルを起こしてきたという話を聞いたことがありました。金沢市場輸送のIという運転手と二人だったようです。Iさんは、ただ一人、九州から来て残っていた運転手でした。

　Iさんについては、他にも車の保険のことで被告発人松平日出男との関係で書いておきたいことがあります。どちらかといえば、当たり屋の被害に遭ったような話として聞いたように思います。他に似たような話として西口君のこともありました。下関市です。

　その話を私はIさん本人から聞いたように思います。その時期と場所が現在の私の記憶では、はっきりしないのですが、その時、Iさんとはずいぶん久しぶりに会ったというか、姿を見たとも思いました。ずっと姿を見なかったこともあったと思うので、再入社ということも。

　私は、２回目のイワシのシーズンが終わったあと、車番は１０８号だったと思いますが、冷凍機付きの保冷車に乗務しました。日野のトラックで、新車に近かったですが、保冷車の箱は載せ替えた古いものでした。

　私は平成３年１月１７日に納車された日野の大型ウィング車の新車に乗務するまでは、その１０８号の保冷車に乗務していたと思います。１月１７日という日付をよく憶えているのは、当日の朝、納車を待っているとき、会社のテレビで湾岸戦争のイラク攻撃開始のようなニュースを見たからです。

　これまでに何度か書いてきましたが、茨城県古河市の山三青果の仕事が始まったのが、平成２年の１２月に入った頃のことでした。大型ウィング車は、その山三青果の仕事を本格化させるために導入したとも聞いていました。

　だいぶん前には、記憶も新しい状態で詳しく書いていると思いますが、山三青果の仕事は帰り荷で、２つの行き荷の雑貨の定期便が当初はセットとなっていました。

　１つはトナミ運輸の栃木便。宇都宮市の近くでしたが、少し手前で住所は郡部となっていたと思います。もう１つが、日通の定期便で、埼玉県岩槻市と千葉県千葉市の２箇所降ろしでした。以前調べた時点でも、岩槻市という地名はなくなっていました。

　金沢市場輸送では同じ頃、トナミ運輸からの九州福岡便や、仙台便もやっていたので、ややこしくなっているのですが、栃木便は小松市のトナミ運輸でも荷物を積んでいたように思います。

　小松市のトナミ運輸というのは、国道８号線沿いで、福井方面に向かって左手にありましたが、住所は加賀市に入っていたようにも思います。金沢のトナミ運輸というのは、西インターの近くにありました。現在も同じトラックターミナル内にあるようですが、金沢市神野町となっています。

[link:] » トナミ運輸金沢（支） - Google マップ https://t.co/s8kRM1X9tg

<hr />

　日通の方は、金沢市の高柳支店から積み込んでいたように思います。金沢市には他に増泉支店がありましたが、ホーム作業の雑貨の定期便で仕事に行ったことはなかったと思います。昭和５９年の頃は、よく仕事に行くことがありました。

　前に書いたと思いますが、竹沢俊寿は、その日通の増泉支店と縁があったという話を聞いたこともあり、言葉は違っていたように思いますが、幹部社員のような話として聞きました。幹部という言葉は、現在違ったイメージですが、昭和５０年代は、暴力団やヤクザの幹部としてのみ聞いた言葉です。

　のれん会、というようなデパートの展示会の仕事として書いたこともあると思いますが、仕事でそのメンバーや業者の人と顔を合わせたという記憶もなく、実態のわからないものでもありました。のれん会は、仕事自体も少なかったと思います。

　昭和５９年というのは金沢市場輸送でも紡績の反物のような荷物を運ぶこともありました。それも日通の仕事だったように思います。日通の増泉支店と西泉だったように思いますがボーリング場があり、その間には、以前、大きな紡績工場があったという話を聞いたこともありました。

　平成１８年１０月、その大きな紡績工場があったと聞くあたりは、マルハンという大きなパチンコ店になっていました。その時はやらなかったと思いますが、安藤健次郎さんの家に行くのに、そのパチンコ店に入り、時間を調整していました。

[link:] » 増泉 - Google マップ https://t.co/knRG8skgTm

<hr />

　上記の増泉の交差点の近くだったと思いますが、日通増泉支店は、跡形もなく消滅しているようにGoogleマップからは見えます。けっこう広い敷地で、昭和３０年代とか４０年代の歴史を感じさせる構造物でもありました。

　その後、仕事で行くこともほとんどなかったと思うのですが、ずいぶん久しぶりだと思ったのが、平成４年２月のことでした。２月中だったと思いますが、前後のことが思い浮かばない状態でもあります。

　時刻は１２月９日１７時４４分になります。今日は灯油を買ってきました。まだ使っていませんが今年初です。朝、薄っすらと雪が積もっていました。金沢の初雪は昨日だったようですが、昨日は雪を見ていなかったように思います。

　今のところ、小さな電気カーペットとセラミックファンヒーターでしのいでいます。こたつは出していません。近いうちに出す予定です。電気代が気になる今日この頃です。

　昨日は、朝から夕方まで画像ファイルのファイル名変更やネットへのアップロードに時間を費やしていました。はっきりは忘れましたが、１１月２７日あたりから溜まっていたように思います。

　自分のデータベースに登録済みの画像・写真ファイルですが、現時点で31594あるようです。

```
Diginnos-PC:~
[10016]  % pp -l|grep '^2018-12-*'|wc -l
760
Diginnos-PC:~
[10017]  % pp -l|grep '^2018-11-*'|wc -l
8597
```

　今月の１２月分で７６０件。手間を掛けた割に少ないと思ったのですが、先月の１１月分をみると８５９７件でした。プログラムを駆使してファイル名の変更をやっていますが、プログラムを使わずにやったら、それだけでものすごい時間が掛かりそうです。

　スマホの天気をみると、能登町で３℃でした。そう寒いとは感じていないですが、これからは３月まで寒い日が続きそうです。まだ使っていないファンヒーターの温度計で室内が０℃というもけっこうありました。４℃ぐらいになっているとファンヒーターを使うことは少ないです。

　こたつだけでは寒いと思ってファンヒーターをつけると温度が２℃ということが多いです。夏は涼しい家なのですが、その分、冬は寒いのかもしれません。それでも北海道や山間部に比較すれば、問題にならない寒さとも思います。

　例年、１２月というのは雷が多いのですが、今のところ雷はないように思います。それでも気象が不安定なのか風は強いことが多いようです。外が暗くなって、ずいぶん時間が経ったと思いながら家に戻って買い物の片付けをしてから時計を見ると１７時３０分ころでした。

　外は雪もちらついていましたが、積もるような雪ではありませんでした。あの日もよく似た天候の夕方だったのは、中断前に書く予定だった平成４年のことです。２月中だったと思いますが、やはり時期は特定できません。

　１２月と２月では、日の暮れる時間も違うと思います。少し違っているかもしれませんが、１２月２３日頃に冬至があって、その日が最も日の短い日で、変わり目であると聞いています。

　その日、夕方のほとんど暗くなりかけた時間に、日通増泉支店で荷物を積みました。果物だったように思います。あるいはトマトのような青果物だったのかもしれません。日通で生鮮食品を積んだのもそのときが初めてだったように思います。急に入ったような仕事でもありました。

　さらにその運行は変わった仕事で、荷物を積んだのも主に被告発人多田敏明が乗務していた日野の４トンウィング車だったと思いますが、私と同じ大型車に乗務していた和田くんとの３人での運行でした。会社の指示のままの仕事でしたが、ドライブがてらの仕事でした。

　おそらくは被告発人松平日出男や被告発人東渡好信の狙いがあっての運行だったのだと思います。ただ、その時点では私も余り気にかけてはいませんでした。似てようなことは他にもあったのですが、最も露骨だったのが、傷害・準強姦被告事件の事件の翌日に予定されていた運行です。

　詳細は別のところで書きたいと思いますが、被告発人多田敏明を長距離の運行に同乗させたのは２回でした。１つは、愛媛から積んできたイヨカンを新潟に降ろしに行く仕事。これは一応、長距離になるかと思いますが、午後に出発して、夜中の２時から遅くて４時頃には戻っています。

　もう一つは、馬鈴薯を積んで。名古屋の北部市場で夜中に荷降ろしし、朝に、岐阜県大垣市から石灰を積んで戻ったという仕事でした。その時、松任駅の向かいの橋本商事で荷降ろしした可能性が高いと思うのですが、はっきりとは思い出せません。

　夕方に日通増泉支店で積んだ荷物の行き先は、長野市でした。長野市の市場だったと思います。私の記憶にあるのは、２度目の長野市の市場への仕事でした。前回が、前に書いていると思いますが、鹿児島市の市場から積み込んだ白菜です。

　長野県全体でもいえることですが、私の長距離トラック運転手の仕事で、長野県内での荷降ろしというのは数少ないものでした。荷物を積んだのも同じです。他の運送会社でも余り聞かなかったので、石川県と長野県は物流自体が少なかったのかもしれません。鮮魚もなかったと思います。



