#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "告発に至る経緯／社会的な影響／山口成良金沢大学教授／モトケンこと矢部善朗弁護士（京都弁護士会）もリツイートしていた「弁護士は精神医学の素人ではあるが、病識が」というツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-13 08:44:18 +0900
FILE_NAME: 2018-12-13-084418_モトケンこと矢部善朗弁護士（京都弁護士会）もリツイートしていた「弁護士は精神医学の素人ではあるが、病識が」というツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  モトケンこと矢部善朗弁護士（京都弁護士会） 三浦義隆弁護士 深澤諭史弁護士
記事タイトル名の文字数：86　保存ファイル名の文字数：82
URL: http://hirono-hideki.hatenablog.com/entry/2018/12/13/163524

#contents

* APIで「はてなブログ」の記事を更新出来るようにしたこと

　実質は、次のツイートからの更新、書面作成の再開になります。

▶ ツイート％kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）％2018/12/12 07:35％ https://twitter.com/kk_hirono/status/1072620945217593344
&twitter(1072620945217593344){theme:light}
> ２０１８年４月８日のことで何より驚いたのは、当日の日曜日の午前中に、遠島山公園に行き、月見御殿から離れ島まで散策していたことです。その日のうちにYouTubeに動画をアップロードしていたようです。実は、今もだいぶん前の撮影の動画が、いくつかそのまま残っています。  
▶

　時刻は１０時４０分です。スクリプトに不具合を見つけたので手直しをしていました。いったん投稿したものを削除して投稿のやり直しも行いました。修正後になりますが、次が直前のデータベース登録として最新のものになります。

　5704： ＃　「全国犯罪被害者の会（あすの会）の解散」で「そこまで言って委員会NP」に出演していた光市母子殺害事件の本村洋氏のこと https://t.co/EouzABN3lF

<hr />

　そのままリンクのURLを使うと、URLがものすごく長くなってしまいます。ページ内リンクとして見出しの日本語をURLエンコードしているからです。Twitterに投稿すると、Twitterで短縮URLに変換するようです。

　セキュリティに関わる問題なので余り具体的には書きたくないのですが、APIで、パソコンのファイルの更新をそのままはてなのブログの記事の更新として反映できるようにしました。作業を進める上で、これはけっこう大きなことなのです。

　いろいろと自分なりに工夫しながらプログラムを行いましたが、すんなり行く部分とすんなり行かない部分がありました。ともあれ目的の機能は実現できました。コマンド１つでの処理完了になります。今までも時間を掛ければ、目的の処理はほとんど実現してきました。

* Bloggerのブログへの投稿で不具合が起きていたのを修正、更新についてのご説明

　以前、スプリクトに変更を行ったためと思いますが、Bloggerの投稿がおかしくなっていました。単純なことだったのですが、影響が出ていたことに気が付かずにいました。Bloggerへの投稿は次のようになっています。

[link:] 2018年11月02日12時20分の登録： 告発に至る経緯：参考事件／座間市9遺体遺棄事件／匿名弁護士弁護士アカウント「くまえもん　@kumaemon9」のツイートからTwilogで調べる2017年11月15日当時 http://hirono2017kk.blogspot.com/2018/11/9kumaemon9twilog20171115.html

[link:] 2018年11月13日16時19分の登録： 告発に至る経緯／書面作成／パソコン／自動生成するファイルの保存位置とブログの記事タイトル書式の関係性 http://hirono2017kk.blogspot.com/2018/11/blog-post_89.html

[link:] 2018年11月14日12時58分の登録： 参考資料／弁護士業界の現状／深澤諭史弁護士のリツイート／今の法テラスの地獄を見ると、「国が報酬決定権を握る」ことの恐ろしさを感じるので、そんな方向には全く進んで欲しくない（中村憲昭弁護士） http://hirono2017kk.blogspot.com/2018/11/blog-post_14.html

[link:] 2018年11月15日12時41分の登録： 参考資料／弁護士業界の現状／新谷泰真弁護士／「すし久兵衛、オークラを提訴」というニュースから思い出した、櫻井光政弁護士と新谷泰真弁護士の関係性 http://hirono2017kk.blogspot.com/2018/11/blog-post_15.html

[link:] 2018年11月21日16時30分の登録： 告発に至る経緯／書面作成／パソコン／告発状開発環境としてのAtomエディタ http://hirono2017kk.blogspot.com/2018/11/atom.html

[link:] 2018年11月30日10時41分の登録： 告訴の事実／平成4年／2月／２４トンのミールを積んだ九州福岡市への運行 http://hirono2017kk.blogspot.com/2018/11/42.html

[link:] 2018年12月13日10時20分の登録： 告発に至る経緯／社会的な影響／石川県トラック協会／本件告発事件の舞台、市場急配センターの労働環境、労災を含む労働問題という側面 http://hirono2017kk.blogspot.com/2018/12/blog-post_3.html

　このうち「2018年11月13日16時19分の登録」から「2018年11月30日10時41分の登録」の間で不具合が起きています。記事の中身が空っぽのものもあります。これについては、あとで再投稿する予定です。

　更新しました。

[link:] 2018年12月13日12時04分の登録： 告発に至る経緯／書面作成／パソコン／自動生成するファイルの保存位置とブログの記事タイトル書式の関係性 http://hirono2017kk.blogspot.com/2018/12/blog-post_31.html

[link:] 2018年12月13日12時09分の登録： 参考資料／弁護士業界の現状／深澤諭史弁護士のリツイート／今の法テラスの地獄を見ると、「国が報酬決定権を握る」ことの恐ろしさを感じるので、そんな方向には全く進んで欲しくない（中村憲昭弁護士） http://hirono2017kk.blogspot.com/2018/12/blog-post_28.html

[link:] 2018年12月13日12時10分の登録： 参考資料／弁護士業界の現状／新谷泰真弁護士／「すし久兵衛、オークラを提訴」というニュースから思い出した、櫻井光政弁護士と新谷泰真弁護士の関係性 http://hirono2017kk.blogspot.com/2018/12/blog-post_95.html

[link:] 2018年12月13日12時11分の登録： 告発に至る経緯／書面作成／パソコン／告発状開発環境としてのAtomエディタ http://hirono2017kk.blogspot.com/2018/12/atom.html

[link:] 2018年12月13日12時12分の登録： 告訴の事実／平成4年／2月／２４トンのミールを積んだ九州福岡市への運行 http://hirono2017kk.blogspot.com/2018/12/42_13.html

　こちらのBloggerでは、ファイルの内容の更新は同一記事名の新規投稿で行います。投稿日が新しいほど最新の内容になるわけですが、それ以前の内容も経過を示すためそのまま残しておこうと思いました。

* はてなブログにおける投稿記事タイトルの書式と、データベースへの登録方法

　5683： 告発に至る経緯／社会的な影響／石川県トラック協会／本件告発事件の舞台、市場急配センターの労働環境、労災を含む労働問題という側面 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/5UjULWSGV5

<hr />
　5684： ＃　気になっていた数日前のブラック企業に関する佐々木亮弁護士（ささきりょう）のツイート https://t.co/qFa3UcjWw5

<hr />
　5686： ＃　弘中惇一郎弁護士が武富士側の主任弁護士としてジャーナリストに億単位の賠償請求をし、全面敗訴していたという。 https://t.co/RJgfScOVYr

<hr />
　5688： ＃　２０１６年弁護士が横領した金額（新聞発表・判決）というツイートの画像、久保田昇（大阪）５億円 https://t.co/U7PWX7vqWV

<hr />
　5690： ＃　、「共謀罪と日韓断交　余命三年時事日記」、佐々木亮弁護士（ささきりょう）や北周士弁護士を含めた弁護士に対する大量懲戒請求の中心的人物 https://t.co/ElN1xXhVz5

<hr />
　5692： ＃　「猪　弁護士」とTwitterで検索すると「猪狩り」が出てきた。多分間違っていた札幌の弁護士の一文字 https://t.co/yzHXeuNSXa

<hr />
　5694： ＃　ブロックされていて出てこなかった「猪　弁護士」のツイートを検索、弁護士のイノシシ狩りの発祥は確か岐阜だった。豚コレラで狩猟禁止になったとも聞く https://t.co/Sy0nqy6amQ

<hr />
　5696： ＃　北海道の足立啓太弁護士のツイートで一つだけ見るけることが出来た「猪野先生」という手がかり https://t.co/c0pS54aP1J

<hr />
　5698： ＃　確認できた猪野詩織さんという桶川ストーカー殺人事件の被害者名 https://t.co/rytmDCpEeV

<hr />
　5700： ＃　遺族が国家賠償を求め、捜査怠慢の違法性を一部認め、埼玉県に５５０万円の賠償を命じる判決が確定していたという桶川ストーカー殺人事件で初めて知る情報 https://t.co/eeeorJ5B7Y

<hr />
　5702： ＃　『埼玉県のＡ子さん』、匿名では警察に都合の悪い事実は隠されてしまう、という桶川ストーカー殺人事件の被害者の父親の言葉 https://t.co/t8LdD9HNFX

<hr />
　5704： ＃　「全国犯罪被害者の会（あすの会）の解散」で「そこまで言って委員会NP」に出演していた光市母子殺害事件の本村洋氏のこと https://t.co/EouzABN3lF

<hr />
　5706： 告発に至る経緯／社会的な影響／山口成良金沢大学教授／モトケンこと矢部善朗弁護士（京都弁護士会）もリツイートしていた「弁護士は精神医学の素人ではあるが、病識が」というツイート - 奉納：危険生物・弁護士脳汚染除去装置＼金… https://t.co/RvbZi2WaRf

<hr />
　5707： ＃　APIで「はてなブログ」の記事を更新出来るようにしたこと https://t.co/ZsmbD1zCWa

<hr />
　5709： ＃　Bloggerのブログへの投稿で不具合が起きていたのを修正、更新についてのご説明 https://t.co/bdvCA4j8Uf

<hr />

　時刻は１３時２５分です。また、問題というか不具合が出ていることに気が付きました。データベースのIDのオートインクリメントが、２つ飛ばしになっています。７の次が９になっているという具合です。

　データベースをみると、次のデータの後に不具合が出るようになったようです。

5686： ＃　弘中惇一郎弁護士が武富士側の主任弁護士としてジャーナリストに億単位の賠償請求をし、全面敗訴していたという。 http://hirono-hideki.hatenablog.com/entry/2018/12/13/102105#%E5%BC%98%E4%B8%AD%E6%83%87%E4%B8%80%E9%83%8E%E5%BC%81%E8%AD%B7%E5%A3%AB%E3%81%8C%E6%AD%A6%E5%AF%8C%E5%A3%AB%E5%81%B4%E3%81%AE%E4%B8%BB%E4%BB%BB%E5%BC%81%E8%AD%B7%E5%A3%AB%E3%81%A8%E3%81%97%E3%81%A6%E3%82%B8%E3%83%A3%E3%83%BC%E3%83%8A%E3%83%AA%E3%82%B9%E3%83%88%E3%81%AB%E5%84%84%E5%8D%98%E4%BD%8D%E3%81%AE%E8%B3%A0%E5%84%9F%E8%AB%8B%E6%B1%82%E3%82%92%E3%81%97%E5%85%A8%E9%9D%A2%E6%95%97%E8%A8%B4%E3%81%97%E3%81%A6%E3%81%84%E3%81%9F%E3%81%A8%E3%81%84%E3%81%86

　前行は５８１文字あります。TwitterはURLの文字列も決まった少ない文字数として処理しています。はっきりとは憶えていないですが、１１文字ではなかったかと思います。さきほどご説明した日本語のURLエンコードのためですが、ブログでは長いURLになります。

　時刻は１３時４７分です。これはかなりまずいので、これから修正作業に入りたいと思います。スクリプトの繰り返し処理でエラーが出ていたのですが、MySQLはエラーが起きてもオートインクリメントを加算するようです。さきほど調べてわかりました。

　オートインクリメントのIDも１から振り直しをしたいと思います。これは以前何度かやったことがあるので、なんとかなりそうです。データベースのテーブルの作り直しになるかもしれないです。

　IDの番号でURLのリンク切れのようなことにはならないですが、正確なデータ数も早くできなくなりますし、誤解を与えることにもなるかと思います。早めに対処しておきたいと思います。

　時刻は１４時０７分です。スクリプトのバグは修正しました。２箇所にタブってコードのコピペをしていたのですが、今までに一度もなかったミスです。通りで、条件式の真と偽がどちらも実行されると思っていました。

* はてなブログの記録用データベース、テーブルをいったん空にしてデータの入れ直し

　１４時５０分頃にデータベースへの登録が完了しました。実はIDに抜けた部分があって３０ぐらいから始まっていました。他にも抜けた番号があって、データ数は３千台ぐらいまで減るのかと思ったのですが、現時点で5338という数でした。

　５千以上あるデータのIDが連番で続いているか、全てを目視で確認したわけではないですが、問題はないと思います。途中で一度エラーが起きたのですが、インクリメントの状態は確認しました。

　エントリーという呼び方もしてきましたがファイル名と、そのファイルに含まれる小項目は別の処理としてデータベースに登録しています。昨日か一昨日、ファイル名の登録処理でエラーがあり、そちらは対処していたのですが、今回は小項目でエラーが出ました。

　原因は、半角のダブルクォートです。そのままではデータベースに登録できないので対処しました。最近は他でもエラーが起こす可能性があるので半角の特殊文字は使わないようにしています。使わないというよりは、データベースへの登録前に置換処理をしています。

5338： ＃　はてなブログにおける投稿記事タイトルの書式と、データベースへの登録方法 http://hirono-hideki.hatenablog.com/entry/2018/12/13/123736#%E3%81%AF%E3%81%A6%E3%81%AA%E3%83%96%E3%83%AD%E3%82%B0%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E6%8A%95%E7%A8%BF%E8%A8%98%E4%BA%8B%E3%82%BF%E3%82%A4%E3%83%88%E3%83%AB%E3%81%AE%E6%9B%B8%E5%BC%8F%E3%81%A8%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%81%B8%E3%81%AE%E7%99%BB%E9%8C%B2%E6%96%B9%E6%B3%95

　テレビで魚のブリのことをやっているのですが、５キロからブリ、３，４キロだとガンド（ワラサ）だという説明がありました。金沢中央卸売市場の仲買の人のようです。宇出津では６キロからブリとして扱うような話は聞いていました。

　テレビで氷見の料理人が寒ブリは９キロないと脂がのっていると保証できないという話をしていたことがありました。ここ数年、宇出津のスーパーで寒ブリを買っても余り脂が乗っていないという感じです。いいものは高く売れる外に出すという話もあります。

　寒ブリは能登町で３００本、佐渡で２０００，３０００本という話もありました。海水温で回遊ルートが変わるとは聞いておりますが、漁業というのも自然条件でずいぶん当たり外れが出るものです。

　１４時５０分過ぎぐらいからのテレビのミヤネ屋の全国ニュースのコーナーですが、そこで気になるニュースがあり、その直後に弁護士らの気になるツイートを発見しました。撒き餌に反応した魚のような現象でした。

　はてなブログの記事の更新が容易になったので、そちらの方を先に取り上げ、記録化しておきたいと思います。時間軸を優先する傾向があるのですが、分類を別にして取り扱いをしておきたいと思います。けっこうな収穫感のあるものです。

