#+TITLE: "報道について考えさせられた清泉亮氏について調べてみる"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-12 16:38:18 +0900
FILE_NAME: 2019-08-12-163818_報道について考えさせられた清泉亮氏について調べてみる.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 報道  清泉亮氏
記事タイトル名の文字数：26　保存ファイル名の文字数：48

* 報道について考えさせられた清泉亮氏について調べてみる
  :LOGBOOK:
  CLOCK: [2019-08-12 月 16:38]--[2019-08-12 月 23:55] =>  7:17
  :END:

＞＞＞2019-08-12（月曜日）16：38＿［これからの記述範囲の開始時刻］＞＞＞

　ずいぶん前から気になっていたことの一つですが、改めて清泉亮氏について調べておきたいと思います。さきほど調べたところ、ジャーナリストという肩書は見つからず、確認できた職業のようなものは「移住アドバイザー」のみでした。

　私の記憶で初めて清泉亮氏のことを知ったのは、最初のきっかけが群馬県の上野村にヘリが墜落したというテレビニュースで、墜落現場は橋の上だったと思いますが、その前に歴史を感じさせる神社がありました。この神社について調べ始めたのがきっかけだったと思います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「上野村」の検索結果 - Twilog https://t.co/eVLWYbf8Dn

<hr />

▷ リツイート→hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞pinpinkiri（小川一）｜2017/11/09 08:27／2017/11/09 06:43｜https://twitter.com/hirono_hideki/status/928403562224222208 ／ https://twitter.com/pinpinkiri/status/928377362307170304
&twitter(928403562224222208){theme:light}
> RT @pinpinkiri: 二次被害が起きかねない事故でした。群馬、上野村、墜落。この言葉か並ぶと脊髄反射してしまいます。日航機墜落事故から３２年、またあの上野村で。 https://t.co/LukMIhCKuy  

　上野村のTwilogの検索で、古いものから最初に出たのが上記のリツイートでした。2017年11月09日となっていますが、当日に「上野村」をキーワードにするのは上記1件のリツイートのみです。次に上野村をキーワードに含むツイートは2018年1月3日となっています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 16:49／2018-01-03 20:13 URL： https://twitter.com/kk_hirono/status/1160820655362727937 https://twitter.com/hirono_hideki/status/948512685624209409
&twitter(1160820655362727937){theme:light}
> 平成23年9月24〜25日撮影　撮影＆編集：うえのテレビ 上野村乙母(おとも)地区の「宇佐八幡宮」の例大祭の前夜に行なわれるおこもり、当日の神事、奉納される「乙母太々神楽(おともだいだいかぐら)」の様子です。  https://t.co/5JNaoQCI2p
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 16:50／2019-04-15 16:54 URL： https://twitter.com/kk_hirono/status/1160820755875033088 https://twitter.com/hirono_hideki/status/1117697567456776192
&twitter(1160820755875033088){theme:light}
> 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「上野村」の検索結果 - Twilog https://t.co/nvCR3qUNaA
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 16:50／2019-04-15 17:04 URL： https://twitter.com/kk_hirono/status/1160820770223710209 https://twitter.com/hirono_hideki/status/1117700240386084864
&twitter(1160820770223710209){theme:light}
> ヘリ墜落：橋の上で炎上、４人死亡　群馬・上野村 - 毎日新聞 https://t.co/rgQUGMMj82
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 16:50／2019-04-15 17:27 URL： https://twitter.com/kk_hirono/status/1160820788171161601 https://twitter.com/hirono_hideki/status/1117705913001844736
&twitter(1160820788171161601){theme:light}
> 上野村　取材 - Google 検索 https://t.co/CfBMRngsdl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 16:50／2019-07-28 14:28 URL： https://twitter.com/kk_hirono/status/1160820826905518081 https://twitter.com/hirono_hideki/status/1155349193256366080
&twitter(1160820826905518081){theme:light}
> 上野村 - Google マップ https://t.co/TAfA7sciHI
◁◁◁
<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜pinpinkiri（小川一） 日時：2019-08-12 16:51／2017-11-09 06:43 URL： https://twitter.com/kk_hirono/status/1160821120477433857 https://twitter.com/pinpinkiri/status/928377362307170304
&twitter(1160821120477433857){theme:light}
> 二次被害が起きかねない事故でした。群馬、上野村、墜落。この言葉か並ぶと脊髄反射してしまいます。日航機墜落事故から３２年、またあの上野村で。 https://t.co/LukMIhCKuy
◁◁◁
<hr />

　小川一という認証付きのアカウントは見覚えがあると思ったのですが、政治家か議員と思ったのが、プロフィールを確認すると毎日新聞グループホールディングス取締役となっていました。これも見覚えがありますが、あらためてホールディングスとは何かと頭をひねりました。

　ツイートの頭にRTとあるので非公式RTなのかと思いましたが、続くアカウントはご本人のものでした。再掲というかたちであったのかと思われます。次にツイートで紹介されたリンクの記事を開き内容を見てみます。

```
激しい炎に包まれ、黒い煙を上げる機体。付近には機体の破片が散乱し、油のような臭いが立ちこめた。群馬県上野村で８日、４人が犠牲になったヘリコプターの墜落事故。機体の落下はあっという間だったという。墜落現場から数百メートルの範囲には住宅や旅館がある。「家に落ちていたらどうなっていたか」と住民は声を震わせた。

　「尾翼から煙が出たと思ったら、２、３度傾いて墜落した」。事故現場近くに住む今井トキさん（７８）は墜…

この記事は有料記事です。

残り798文字（全文1001文字）

［source：］ヘリ墜落：「家に落ちていたら」　住民声震わせ　群馬・上野 - 毎日新聞 https://mainichi.jp/articles/20171109/ddm/041/040/135000c
```

　記事の配信は2017年11月9日で東京朝刊とも記載がありますが、記事の内容に8日とあるので、墜落事故があったのは前日の11月8日に間違いないでしょう。テレビで夕方の早い時間に繰り返し集中した報道があったと印象深く記憶にあります。

　墜落現場の映像がテレビに出ていて、なにか見覚えのある風景に似ているとも思い、なおさら気になっていろいろと調べたのだと思いますが、その風景というのがNHKのテレビドラマと映画で見た「八日目の蝉」の虫送りの場面であったと、今は鮮明に思い出せます。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2017年11月08日 - Twilog https://t.co/RRC180Stxr

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:08／2017-11-08 04:50 URL： https://twitter.com/kk_hirono/status/1160825283219316738 https://twitter.com/hirono_hideki/status/927986529376485376
&twitter(1160825283219316738){theme:light}
> 高校球児 球拾いで川に転落 意識不明 金沢 | NHKニュース https://t.co/80DM6q5rOL
◁◁◁
<hr />
[link:] » エラー｜NHK NEWS WEB https://t.co/gw5jKzeRjg

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:08／2017-11-08 04:52 URL： https://twitter.com/kk_hirono/status/1160825403616845824 https://twitter.com/hirono_hideki/status/927987218932625408
&twitter(1160825403616845824){theme:light}
> 山尾志桜里衆院議員、交際疑惑の弁護士を政策顧問に - 社会 : 日刊スポーツ https://t.co/QEehym2sPR
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:09／2017-11-08 04:58 URL： https://twitter.com/kk_hirono/status/1160825538228838400 https://twitter.com/hirono_hideki/status/927988541975617537
&twitter(1160825538228838400){theme:light}
> 石川県立金沢西高等学校 - Wikipedia https://t.co/dvJqdJ4Oam
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:09／2017-11-08 11:56 URL： https://twitter.com/kk_hirono/status/1160825562740346880 https://twitter.com/hirono_hideki/status/928093823741304833
&twitter(1160825562740346880){theme:light}
> 能登島の沖合の定置網に4メートルのホオジロザメが入ったというテレビのニュース。その前は鵜川の菅原神社のいどり祭り。国の無形文化財に指定されているらしい。ここ1,2年程の間に知った神事だが、今の時期とは思わず、正月明けの1,2月かと思っていた。昨夜ということなので11月7日らしい。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:09／2017-11-08 17:29 URL： https://twitter.com/kk_hirono/status/1160825678939340800 https://twitter.com/hirono_hideki/status/928177716821667840
&twitter(1160825678939340800){theme:light}
> 秋空のもと 賑やかに 乙母八幡神社祭 https://t.co/lbdq5HNHoM
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:09／2017-11-08 17:31 URL： https://twitter.com/kk_hirono/status/1160825721637335040 https://twitter.com/hirono_hideki/status/928178152957980672
&twitter(1160825721637335040){theme:light}
> 平成24年 乙母神社祭（お籠りー祭典・神楽） https://t.co/RMKGMEG87S
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:09／2017-11-08 17:36 URL： https://twitter.com/kk_hirono/status/1160825742457888768 https://twitter.com/hirono_hideki/status/928179337106460672
&twitter(1160825742457888768){theme:light}
> 熱演に拍手喝采 乙母神楽 奉納 https://t.co/HbuqPIBdxO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:10／2017-11-08 17:50 URL： https://twitter.com/kk_hirono/status/1160825782911922176 https://twitter.com/hirono_hideki/status/928182971760177152
&twitter(1160825782911922176){theme:light}
> 宇都宮地裁足利支部　マラソン選手の万引き事件。すっかり忘れていた。栃木県の事件という記憶もなかった。足利支部というのも初めて聞いたような気がする。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:10／2017-11-08 19:12 URL： https://twitter.com/kk_hirono/status/1160825899408695302 https://twitter.com/hirono_hideki/status/928203595584962560
&twitter(1160825899408695302){theme:light}
> 衛星写真で発見!京都の山奥に「ピラミッド型建物?」これは何…秘境探検6弾▽東北・謎多き樹海「田代峠」へ!禁断洞窟大発掘で…秘密空間が出た▽田中隊長も! https://t.co/PsZ9nIzolx
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:11／2017-11-08 20:00 URL： https://twitter.com/kk_hirono/status/1160826031546257409 https://twitter.com/hirono_hideki/status/928215684500164609
&twitter(1160826031546257409){theme:light}
> 田代峠はミステリーゾーンとして有名だったらしい。今夜、テレビで初めて知った。まだ確認していないが山形県最上地方と宮城県の県境付近ということなので、鳴子温泉の近くではないかと思われる。秋田方面から石巻に向かうのに、何度か通行したことがある。3桁の国道だったと思う。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-12 17:11／2017-11-08 22:51 URL： https://twitter.com/kk_hirono/status/1160826228531613696 https://twitter.com/hirono_hideki/status/928258779342258177
&twitter(1160826228531613696){theme:light}
> 思川流しびな～栃木県小山市 - YouTube https://t.co/ohJcFVr1Pq
◁◁◁
<hr />

　久しぶりに思い出したことがいくつかありましたが、ほとんどが同じ日の出来事だったようです。特に能登島の定置網でホオジロザメが捕獲されたというニュースは、ニュースの扱いが小さすぎただけに気になっていろいろと調べたことで発見もありました。

　4メートルのホオジロザメというのは相当大きいと思いますが、そのくらいの大きさになると小型船が襲われた死亡事故も外国ではあるという情報を見かけました。日本海でのホオジロザメの目撃もずいぶん珍しく事例も少ないようでしたが、注意喚起で大きなニュースにならないのが不思議でした。

　リンクのNHKの記事がリンク切れとなっていたので、当日なのか確認は出来なかったのですが、金沢西高校での野球部員の川への転落死亡事故というのも父親の強い意思で金沢西警察署への刑事告訴か刑事告発になっていたことを思い出しました。

　どこかで書いていると思いますが、この金沢西高校というのは昭和59年、金沢港の魚市場にスルメイカを積みに行く裏道としてよく通っていました。そしてこの野球部員の死亡事故で川の場所を調べたところ、金沢西高校の場所自体が移転していたことを知りました。

　相変わらず新聞を開いて見ない日が多いのですが、一時期繰り返し報道されていたニュースが、その後続報が全くなくなるということがあります。それを強く意識したのが、能登町の死体遺棄事件でしたが、ネットで調べても続報は見当たりませんでした。

　前に調べてから3ヶ月は経っているように思いますが、ここで検索をしてみたいと思います。

[link:] » 能登町 遺体遺棄 - Google 検索 https://t.co/2VBsgezQdG

<hr />
[link:] » 山林に女性の遺体遺棄容疑　４４歳男逮捕、石川県警 - 産経ニュース https://t.co/23YxRaGt9x \n 飲食店を経営する金沢市の女性＝当時（３０）＝の遺体を石川県能登町の山林に埋めたとして、石川県警は１４日、死体遺棄容疑で

<hr />

　Google検索で一ヶ月以内を指定すると情報がありませんでした。昨年10月14日の逮捕で当日のニュースとなっていたようです。検索結果の要約には10月9日ごろ遺体を遺棄したとも見えます。能登町柳田の山林ともあります。

　平成17年ではなかったかと思いますが、鳳至郡能登町、鳳至郡柳田村、珠洲郡内浦町が合併し現在の鳳珠郡能登町となりました。その旧柳田村に柳田という住所の場所があると知ったのも昨年のことで、その柳田に白山神社があって、そこに柳田大祭というのも知って驚きました。

　旧柳田村の中心部というのは、白山神社の場所からけっこう離れていて、宇出津から輪島市町野に通じる県道沿いの辺りになります。県道沿いの坂を登ったところに諏訪神社というこの辺りでは比較的大きな神社があって、そこが柳田大祭の場所だとずっと思い込んでいました。

```
飲食店を経営する金沢市の女性＝当時（３０）＝の遺体を石川県能登町の山林に埋めたとして、石川県警は１４日、死体遺棄の疑いで知人で飲食店従業員の岡本充治容疑者（４４）＝自称大阪市浪速区＝を逮捕し、金沢西署に捜査本部を設置した。

　県警によると、女性は金沢市の喜多あき乃さん。県警は喜多さんに対する傷害容疑で、岡本容疑者を１３日に、喜多さんの店の従業員、佐藤祐樹容疑者（２７）＝同市藤江南＝を１１日に逮捕。死因の特定を急ぐとともに、佐藤容疑者も遺棄に関わった疑いがあるとみて調べている。

　岡本容疑者の逮捕容疑は９日ごろ、喜多さんの遺体を能登町の山林に埋めた疑い。

［source：］石川の山林に３０歳女性遺体 遺棄容疑で知人の男逮捕 ： 京都新聞 https://www.kyoto-np.co.jp/top/article/20181014000106
```

　検索結果に京都新聞の記事があって、開くと会見で2人の顔写真があります。写真の下に石川県警幹部とありますが、初めて目にした顔に見えました。そういえばと思いだしたのですが、金沢西警察署に捜査本部とあります。

　逮捕した被疑者の一人の住所が藤江南となっているためと思われます。この金沢市の藤江は藤江北、藤江西もあったかもしれません。どれがどの辺りかわからずに走行していたのですが、以前、金沢西高校があったあたりも住所が藤江で、電信柱に看板があったように記憶しています。

　藤江東は見たことがなかったと思いますが、藤江というのは金石街道と国道8号線バイパスが交わる一帯でした。バイパスの金沢市内寄りは、すぐに住所が北町になっていたので、範囲は狭いような感じでした。

　連れ去られた被害者の家は住所が金沢市の糸田か糸田新町になっていました。その辺りはまず間違いなく金沢中警察署の管轄で、なぜ連れ去り現場より、被疑者の一人の住所が優先され、金沢西警察署の事件となったのか、それも不思議に感じていました。

　金沢西警察署の建物は平成4年当時と違いますが、場所はほぼ同じで敷地が広くなっていると思います。他の事件でもテレビニュースで金沢西警察署の映像を見ることがありますが、ちょくちょく目にするのが神社の鳥居です。Googleで調べると大野湊神社でした。

　大野湊神社は、金沢西警察署の横からずいぶん奥の場所にあるとGoogleマップでみましたが、その鳥居というのは平成4年当時、金沢西警察署の留置場の裏側の小さな窓からも見ていました。洗濯物を干す時によく見ていたとも記憶にあります。

　神社の鳥居のことを思い出していると、迷宮入りという言葉のことが頭に浮かんできました。不思議と最近は見かけることがないですが、未解決事件を象徴するような言葉でした。なぜ私が神社にこだわりを持ってきたのか、１つ謎が解けたような気分にもなりました。

　弁護士妖怪大泥棒神社です。未だ弁護士鉄道の列車に乗せられ走り続けさせられている気分でもありますが、昨日も宇出津の銭湯のテレビをふと気になって眺めていると、本物のシベリア鉄道と蒸気機関車が出てきた驚きました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-12 18:07／2019-08-12 17:44 URL： https://twitter.com/kk_hirono/status/1160840140974985216 https://twitter.com/fukazawas/status/1160834554896109568
&twitter(1160840140974985216){theme:light}
> あー、言われてみると、その傾向あるかも（・∀・） https://t.co/tWQBStSola
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jmjhjmwtad（弁護士7286） 日時：2019-08-12 18:07／2019-08-12 17:03 URL： https://twitter.com/kk_hirono/status/1160840156993056768 https://twitter.com/jmjhjmwtad/status/1160824172081082368
&twitter(1160840156993056768){theme:light}
> 筋悪い相手方に内容証明送って、電話かけると「お前ほんとに弁護士か！」を高い確率で言われるんやけど、相手方がワイにそういうことを言う共通の心理状態があるはずなんよな。多分やけど、警察類似の存在に見られてるのかもしれん。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜taneri777（三宅はるひさ＠慰安婦像立った、朝日新聞死ね） 日時：2019-08-12 18:07／2019-08-12 16:57 URL： https://twitter.com/kk_hirono/status/1160840308944322561 https://twitter.com/taneri777/status/1160822649410478081
&twitter(1160840308944322561){theme:light}
> 自称弁護士がなんか言ってる件。 https://t.co/3lzYv1MinV
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jmjhjmwtad（弁護士7286） 日時：2019-08-12 18:08／2019-08-12 15:10 URL： https://twitter.com/kk_hirono/status/1160840355756986368 https://twitter.com/jmjhjmwtad/status/1160795786159935491
&twitter(1160840355756986368){theme:light}
> 出版社も、元ヤクザを自称する人間が書いた、ヤクザとしての経験を踏まえた本を出版するの、コンプライアンスとの関係で問題ないんかね。 \n  元ヤクザの書いた本で金儲けなんて、まっとうな人間を泣かせた武勇伝で金儲けしてる訳で、ヤクザ使って金儲けしてるのと何ら変わらないと思うけどね。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜BrMdi3OiyA8GJ1r（高田） 日時：2019-08-12 18:08／2019-08-12 16:08 URL： https://twitter.com/kk_hirono/status/1160840436048510976 https://twitter.com/BrMdi3OiyA8GJ1r/status/1160810241123995653
&twitter(1160840436048510976){theme:light}
> @jmjhjmwtad すみません。関係ないツイートしたので《他人宛です、消去させて頂きました
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hagebouzu07（はげぼうず☆いい気分☆） 日時：2019-08-12 18:08／2019-08-12 16:27 URL： https://twitter.com/kk_hirono/status/1160840458764820480 https://twitter.com/hagebouzu07/status/1160815058965843969
&twitter(1160840458764820480){theme:light}
> @jmjhjmwtad 弁護士なら自分で調べろよ。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Pideyuki1（Pideyuki） 日時：2019-08-12 18:08／2019-08-12 16:11 URL： https://twitter.com/kk_hirono/status/1160840487990808576 https://twitter.com/Pideyuki1/status/1160810994265837571
&twitter(1160840487990808576){theme:light}
> @jmjhjmwtad 嫌なら読まなきゃいいのでは？
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜skymods（𝘴𝘬𝘺𝘮𝘰𝘥𝘴） 日時：2019-08-12 18:08／2019-08-12 16:23 URL： https://twitter.com/kk_hirono/status/1160840563416944640 https://twitter.com/skymods/status/1160813997379084288
&twitter(1160840563416944640){theme:light}
> @jmjhjmwtad 弁護士7286さんの考え方だと、ジャン・ジュネ（元泥棒）や永山則夫（元ライフル魔）の本も「元悪いヤツの本」だからそれで儲けてんじゃね～よ、で終わる。 \n  大体、本物の作家なんてのはアウトサイダーなのが本質だから… https://t.co/lrED0xOMNo
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yacYYzO2I2UvvmG（画面ライター） 日時：2019-08-12 18:09／2019-08-12 16:40 URL： https://twitter.com/kk_hirono/status/1160840601782276097 https://twitter.com/yacYYzO2I2UvvmG/status/1160818428237664256
&twitter(1160840601782276097){theme:light}
> @skymods @jmjhjmwtad ヤクザが本とか出版していけないと言っておられるの。よく　わかりませんが。そう言えばフランスで人食した日本人　本　を出版した。読んでないが。 \n  ドスエフスキーなんか　死刑執行　直前に放免された。 \n  そんな作家・芸術家　案外たくさんいるかも？
◁◁◁
<hr />

　ふと気になって深澤諭史弁護士のタイムラインを開くと上記のようなツイートやリツイートがありました。すべて深澤諭史弁護士のタイムラインのものではなく、深澤諭史弁護士がリツイートしたものや言及ツイートの関連ツイートを含みます。

　トーマスと言ったでしょうか、顔だけが人間のような機関車の漫画です。私が最初に知ったのは平成10年頃のころで、KYNのところで一緒に仕事をしていたM君が、自分の小さい子供のお気に入りだと話していました。M君でも良かったと思いますが、名前が思い出せません。

　金沢市の緑団地の近くのM君です。名前を思い出しましたが、私が使う姓（苗字）・名前のイニシャルだとMK君になります。Mはかなりよくある名前です。芸能人にも見かけることが多いですが、金沢市では2つ目の漢字に違いがあって、もう一つは全国的には見かけません。

　このMK君については、ネットでは余り書いていないかもしれないですが、確か年上の、妻が被告発人多田敏明と歳が近く、同じ高岡中学校の出身だと聞いたように思います。金沢市には香林坊の近くに高岡町があって、富山県高岡市もお隣に近いですが、それとは別です。

```
通学区域［編集］
中央小学校通学町（武蔵町17番3号～17番21号、長町1丁目4番28号～4番53号、5番～10番、長町2丁目4番19号～4番34号、5番22号～5番36号、6番、7番、長町3丁目、中央通町11番27号～11番39号、16番、17番2号～17番30号、18番3号～18番21号、19番～22番、長土塀1丁目、長土塀2丁目、長土塀3丁目、三社町、昭和町1番、2番、3番20号、5番8号～5番21号、6番1号～6番19号、6番21号～6番28号、11番19号～11番24号、13番3号～13番27号、13番33号～13番37号、14番～16番、20番、21番4号～21番17号、芳斉1丁目、芳斉2丁目、六枚町、玉川町3番～17番、本町1丁目1番5号～1番38号、2番5号～2番46号、3番4号～3番24号、本町2丁目1番～14番、18番1号～18番15号、18番31号、18番32号、柳町、島田町、玉井町、元菊町1番～5番、6番6号～6番15号、10番6号～10番14号、11番1号～11番4号、11番21号、11番22号、大和町1番、2番、3番1号～3番24号、3番36号～3番40号、4番、5番に限る。）、米丸小学校通学町、新神田小学校通学町［2］

［source：］金沢市立高岡中学校 - Wikipedia https://ja.wikipedia.org/wiki/%E9%87%91%E6%B2%A2%E5%B8%82%E7%AB%8B%E9%AB%98%E5%B2%A1%E4%B8%AD%E5%AD%A6%E6%A0%A1
```

　上記に引用をしましたが、通学区域が金沢市内の住所としてずらりと並んでいます。不思議なもので私が知らなかったものが多く、金沢市本町というのは金沢駅の真ん前あたりかと思います。殆どが犀川の大豆田大橋を挟んで、高岡中学校の反対側のようです。

　逆に高岡中学校の通学区域と思っていていたものが見当たりません。被告訴人安田繁克の東力、被告発人多田敏明の間明も見当たらないですし、さらに不思議なのもっと高岡中学校に近いはずの入江が見当たらないことです。ページ内検索で確認をしておきます。

　やはり入江はありませんでした。玉鉾もないですが、永久開発の住所が玉鉾になっていたと思うので、高岡中学校とは目と鼻の先になるはずなのです。合併で通学区域が広がることは十分考えられますが、逆に範囲が大幅に狭まっているように見えます。

　いちおう高岡中学校に隣接したものとして想定されるのは、野田中学校と西南部中学校です。もっとも高岡中学校に近くて大きな住所として入江が浮かびますが、西南部中学校からだとずいぶん離れているという印象です。そちらのwikipediaにも通学区域はありそうです。

　西南部中学校の住所は金沢市新保本町1丁目となっていました。住所は八日市辺りを想像していました。個人的な経験として新保本は金沢西インターに近く、西南部中学校はその前を通りかかることがありましたが、西金沢に近かったと思います。

```
通学区域［編集］
押野小学校通学町、三和小学校通学町、西南部小学校通学町［2］

［source：］金沢市立西南部中学校 - Wikipedia https://ja.wikipedia.org/wiki/%E9%87%91%E6%B2%A2%E5%B8%82%E7%AB%8B%E8%A5%BF%E5%8D%97%E9%83%A8%E4%B8%AD%E5%AD%A6%E6%A0%A1
```

　こちらは高岡中学校と違って通学区域に金沢市内の住所はなく、「押野小学校通学町、三和小学校通学町、西南部小学校通学町［2］」とあります。ずいぶんと簡潔です。押野小学校とありますが、押野という住所は、金沢市と野々市市に隣接して別々にあると比較的最近しりました。

　個人的に押野といえば、懲戒処分のタイミングで自殺したという押野弁護士を思い出すのですが、これも前に取り上げたことがあったと思います。たしか小松市にも懲戒処分ですごい弁護士がいましたが、そちらの弁護士の名前は思い出せません。退会命令や除斥にはなっていなかったような。

```
金沢市立野田中学校（かなざわしりつのだちゅううがっこう）は石川県金沢市若草町に所在する公立の中学校。

［source：］金沢市立野田中学校 - Wikipedia https://ja.wikipedia.org/wiki/%E9%87%91%E6%B2%A2%E5%B8%82%E7%AB%8B%E9%87%8E%E7%94%B0%E4%B8%AD%E5%AD%A6%E6%A0%A1
```

　こちらは通学区域に関する情報の記載がありませんでした。金沢市若草という住所も初耳です。この野田中学校を私は金沢市野町にある中学校と思い込んでいたのですが、あるいは勘違いだったのかもしれません。金沢市の外れの方には野田山墓地があります。

[link:] » 金沢市立野田中学校 - Google マップ https://t.co/qWqJYS1EuY

<hr />

　調べてみると、野田中学校は、金沢市寺町と金沢市平和町の間にありました。ずっと前から見たことのない中学校とは思っていたのですが、金沢市野町から金沢高校の間にあるものと想像していました。野町というより石坂に近い西茶屋街になります。

　北陸新幹線の開業以来、全国的にひがし茶屋街が金沢市を代表する景観のようにテレビで見かけますが、それ以前は、西茶屋街の方が金沢で知られた存在であったように思います。特に石坂は有名でした。「いっさか」と読みますが、売春街でその名残も残していました。

　ずっと前に死んでいる可能性も高いので、被告発人、被告訴人から外していますが、竹沢俊寿の家が野町の西の茶屋街にあると聞いていました。金沢市の住宅地図でその場所を確認したこともあったのですが、Googleマップを知る前のことで、建物などは確認していません。

　石坂の住所は金沢市増泉一丁目と聞いていましたが、一部野町にまたがるとも聞いていました。西の茶屋街については住所を野町と聞き、増泉にまたがると聞いたことはありませんでした。増泉、白菊町、千日町、中村町は片町という繁華街に近く、暴力団関係者が多く済んでいるという話でした。

　今はあとかたもなくなくなっていると思い、調べたこともないですが、昭和59年当時は、白菊町に古い冷蔵庫があって、金沢市場輸送の仕事でちょくちょく頻繁に行っていました。似たような更に古さを感じる冷蔵庫は、現在の滋賀県高島市にもありました。今津ではと思います。

[link:] » 金沢市入江 中学 通学区域 - Google 検索 https://t.co/JiudchEglW

<hr />
[link:] » 金沢市立小中学校通学区域（町別） https://t.co/gD8FsZa3dz

<hr />

```
入江町	 	 	米丸	高岡
入江１丁目	 	 	新神田	高岡
入江２丁目	 	 	新神田	高岡
入江３丁目	 	 	米丸	高岡

［source：］金沢市立小中学校通学区域（町別） https://www4.city.kanazawa.lg.jp/39001/tsugaku/tyoubetsu_2.html
```

　金沢市の入江は、入江町と入江1丁目から3丁目になるようです。しかし、これも平成の初めとは違っているかもしれません。前にも書いてきましたが駅西本町と二口町はその場所がずいぶんと変わっています。前の市場急配センターの住所になりますが、二口町から駅西本町に変わっていました。

　間明も東力も通学区域は高岡中学校となっていました。wikipediaの情報がまぎわらしく道草を食うことになりましたが、意外な発見もあったように思うので、いずれ役立つこともあるかもしれません。

　東力はすべてが米丸小学校となっていました。この米丸小学校も見覚えがあると思っていたのですが、どのあたりにあったのか思い出せずにいました。入江に神社があったことは記憶にあるのですが、小学校というのははっきり記憶にないのです。間明も同じです。

　[link:] » 米丸小学校 - Google マップ https://t.co/6nFgz0Ihiz

<hr />

　石川県町の移転もあり田畑から大きく拓けた周辺の金沢西高校のように移転されたとは考えにくいですが、米丸小学校の場所を見て、こんなところに小学校があったのかと驚きました。入江の交番の近くで、住所も東力となっていますが、その近くには昭和59年から平成4年まで住んでいたからです。

　しょうのうが防虫剤で樟だと初めて知りました。樟は楠だとずっと思っていました。テレビの太宰府天満宮です。5分ほど前になりますかテレビをつけました。

　テレビの番宣では栃木の陽明門だけをみていたので、太宰府天満宮が番組に出てくるとは思いもよりませんでした。

[link:] » 樟脳(ショウノウ)とは - コトバンク https://t.co/t6kuHEnx8Q

<hr />

　勘違いかと思ったので「しょうのう」と平仮名にしておいたのですが、確認するとやはり樟脳でした。樟脳は人間の脳の髄液のことと思っていました。金沢刑務所で大阪の暴力団組長が、抗争の殺し合いで相手の頭から飛び散ったと話していたことで印象的な言葉でした。

　樟脳が「衣類の虫除けや芳香剤」というのは、やはり不思議です。脳は医学や生物学的な言葉というイメージしかありません。解説をみていると、脳をリラックスさせる意味が大きくあったのかと考える他はないですが、それだとお香のほうが近いような気がします。

　前にも書いているはずですが、私は物心のついた頃の記憶として、大阪の万国博覧会に行ったことと、麻疹にかかって京都の親戚の家で養生し、快癒して宇出津に帰るという前日に、近所の北野天満宮にいたという記憶があって、それが学問の神様、菅原道真の記憶ともなっています。

　菅原道真は天神様ですが、法律の勉強を初めて判例をみていると、「天人ともに許さざる」がありました。宇出津の桜町の能登警察署で、大家警部補に「神様の目線でふざけたやつ」と言われたことに重なります。

　テレビでは菅原道真の道真と観世音菩薩、それと鐘の音が出てきました。これも初めて知る関係性ですが、菅原道真と牛の関係性というのも昨年の夏、テレビの天神祭の中継で初めて知りました。

ぶっちゃけ寺　「令和」を迎えたこの夏こそ行っておきたい!全国のスゴい寺社SP \n 2019年8月12日（月）  19時00分～21時48分  の放送内容 https://t.co/Mkzp1pSigE

<hr />
令和最初のお盆に「今年こそ行くべき」神社仏閣を巡る3時間!「太宰府天満宮」では“令和”ゆかりの地を訪問!「日光東照宮」では平成の大修理を終えた陽明門の謎を解明! https://t.co/Mkzp1pSigE

<hr />

◆新元号“令和”ゆかりの地・太宰府天満宮に太田光&amp;室井滋が訪問!この夏行くべき開運スポットが続々登場!さらに「観世音寺」では、菅原道真がその音を聴いたという国宝の梵鐘を特別に撞かせてもらえることに!その鐘の音とは!?  https://t.co/Mkzp1pSigE

<hr />

　観世音菩薩は見かけることが多いですが、観世音寺というのは見てこなかった気がします。それも菅原道真とゆかりがあるとは想像をしたこともなかったです。菅原道真は神道や同じ時代背景の陰陽道のイメージが強く、仏教との関連は考えたこともなかった気がします。

　前にも書いていると思いますが、テレビの猛暑の話題で、小学生のような女の子が団扇で臥せた牛をあおぎ、カメラに気がついたのか牛が驚いた表情で一瞬体を動かし、すぐに落ち着いたのがとても印象的でした。牛に関心を強く持つようになったのもそれ以来かと思います。

```
観世音寺（かんぜおんじ）は、福岡県太宰府市観世音寺五丁目にある天台宗の寺院。山号は清水山。本尊は聖観音［1］（しょうかんのん）。開基は天智天皇である。九州西国三十三箇所第三十三番札所。

九州を代表する古寺で、造営開始は7世紀後半にさかのぼる。奈良の東大寺・栃木の下野薬師寺とともに「天下三戒壇」の1つに数えられる。平安時代以降は徐々に衰退したが、仏像をはじめとする文化財を豊富に有する。

［source：］観世音寺 - Wikipedia https://ja.wikipedia.org/wiki/%E8%A6%B3%E4%B8%96%E9%9F%B3%E5%AF%BA
```

　観世音と観音の違いもよくわかっていないのですが、観音寺は四国というイメージが強く観音寺市があります。長崎県になると思いますが、対馬の観音寺は韓国の仏像盗難のことで、最初に観音寺に関心を持つきっかけとなり、それも小倉秀夫弁護士に導かれた気がします。

　テレビに徳川家康が使っていたとされる湯たんぽが出てきました。日本最古とも話が出てきましたが、湯たんぽというのは実際に、金沢刑務所の拘置所で使ったことがありました。一回何十円だったと思いますが、未決の購入品目の１つになっていたかと思います。

　徳川家康という歴史上の人物も昭和の時代はたぬき親父とか、人を騙し化かす悪いイメージで見ることが多かったと記憶にあります。そういうマイナスイメージは、思い出せないほど前にすっかり見かけなくなりました。

　清泉亮氏のについて調べるのが、今回の目的でした。命題やミッションというほどではないですが、参考資料としては重要性はあるかと思い、ここで正確なことを記録しておきたいと思いました。時間が経過するほどに、調べて確認するにも難儀なことが出てきます。

[link:] » 清泉亮 - Google 検索 https://t.co/ATAy8lmXrE

<hr />
[link:] » 誰も教えてくれない田舎暮らしの教科書 | 清泉 亮 |本 | 通販 | Amazon https://t.co/mNzCTPRKgk

<hr />
[link:] » 監視と縛りの日常生活“ブラック集落”を避けるには　移住民が落ちた「村八分」地獄 | デイリー新潮 https://t.co/gD8TCPRgXq

<hr />

　検索の上位にブラック集落というワードが出てきましたが、これは初めて見たように思います。清泉亮氏の記述には、情報が乏しく社会が狭かった昭和の時代の香りが感じられ、それも興味深いところです。真偽の程度ももちろん不明ですが、もっともらしいことになっていると思います。

　私は能登半島の否か生まれの田舎暮らしですが、清泉亮氏の記述には全く実感の伴わないものばかりです。他の地域の田舎暮らしは経験がないので、にわかに否定をすることも出来ませんし、能登半島は大陸との交易の歴史もあって混血も含め時代背景が違うような気もしています。

[link:] » 恐怖の実話！悪夢と化した｢夢の田舎暮らし｣ 場所によってはこんなにヤバい｢人間関係｣ https://t.co/EEImwHc1JM \n 清泉 亮  2018/07/07 10:00

<hr />

　同じくGoogleの検索結果ですが、記事の内容は読んでいません。見出しを見ただけでただらなぬものが伝わりますが、昨年の7月7日の記事のようです。深澤諭史弁護士の二弁フロンティアの記事の見出しのことも思い出したのですが、たぶん深澤諭史弁護士の方が古そうです。

[link:] » 本当は 深澤諭史弁護士 - Google 検索 https://t.co/78l0OME38v

<hr />
[link:] » 2017_NO10_19.pdf https://t.co/xOdFo0peQL

<hr />
[link:] » 非弁提携とは？～利用者も弁護士も破滅する恐ろしい犯罪～ : 弁護士 深澤諭史のブログ https://t.co/ZvvYBLp5Nd

<hr />
[link:] » (4) 深澤諭史さんはTwitterを使っています: 「二弁フロンティア「非弁フロンティア 本当に怖い非弁提携」が、誰でもネットで読めるようになりました！ https://t.co/AKIRgWktmc」 / Twitter https://t.co/8pjSXpbWoy

<hr />

[link:] » 『NIBENFrontier』2017年10月号|第二東京弁護士会ひまわり https://t.co/AKIRgWktmc \n 『NIBEN Frontier』2017年10月号 \n ￼ \n 【特集】19 \n 本当に怖い非弁提携 \n 深澤諭史

<hr />

　二弁フロンティアの深澤諭史弁護士の記事は2017年10月号となっていました。「本当に怖い非弁提携」が見出しというかタイトルのようです。深澤諭史弁護士の肝いりで、公開された記事を読みましたが、清泉亮氏の記事ような具体性は感じられなかったと記憶にあります。

　痴は物事を正しく見抜けない、という解説がテレビでありました。孫悟空の河童の解説として出てきました。猪八戒が貪、孫悟空が怒という解説のあとでしたが、沙悟浄とここで思い出しました。物事を正しく見抜いているようなことを書いていると感心するのが深澤諭史弁護士というタイミングでした。

　深澤諭史弁護士に関しては、出身地というか産地に関する情報を見かけず、気にかけることも多かったのですが、最近になって静岡市にゆかりがあるような本人のツイートを見かけました。個人的には歴史上の人物以上に興味深さのある研究対象が深澤諭史弁護士でもあります。

　「% dp -p |grep fukazawas |grep 静岡」というコマンドの実行結果はゼロでした。静岡県か静岡市の確認をするつもりでしたが、それ以前の段階で情報の記録が出来ていなかったようです。

[link:] » 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”静岡”／深澤諭史（@fukazawas）の検索（2014-04-30〜2019-08-08／2019年08月12日21時04分の記録18件） https://t.co/HU6CwR9k80

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-12 21:07／2019-07-23 14:40 URL： https://twitter.com/kk_hirono/status/1160885398689550336 https://twitter.com/fukazawas/status/1153540410830012416
&twitter(1160885398689550336){theme:light}
> 山田太郎票を山本太郎票に　静岡県富士宮市選管ミス　市民指摘で判明 | 毎日新聞 https://t.co/psLDDtt7tu \n  あるとおもったら，本当に合ったのか。 \n  なお，当職とゆかりのある市ですお（＾ω＾）
◁◁◁
<hr />

　まとめ記事を作成したことで見つけ出すことが出来ました。記憶になかったですが静岡県富士宮市だったようです。7月23日の深澤諭史弁護士のツイートです。一月経っていないですが、かすかにしか記憶に残っていませんでした。かすかな手がかりで見つけ出せたと思います。

　富士宮という地名は印象的に記憶にあります。能都中学校の1年生のとき、金沢市の卯辰山の全国高校相撲大会に行ったのですが、練習に通っていた石川県立水産高校が団体戦で準優勝となり、決勝戦で破れたのが富士宮北高校ではなかったかと思います。

```
第61回
1977年
昭和52年	富士宮北（静岡）

［source：］歴代優勝校・優勝者｜高等学校相撲金沢大会 https://hk-event.jp/sumou/winner/
```

　優勝校のみの情報ですが昭和52年に富士宮北（静岡）と確認できました。その3年前の昭和49年が石川水産（石川）の団体優勝となっています。この全国優勝した時の大将が間接的な縁となって、私は能都中学校の相撲部に入り、2年続けて卯辰山の全国大会の観戦にも行きました。

　深澤諭史弁護士のツイートにある「なお，当職とゆかりのある市ですお（＾ω＾）」はとても気になる情報ですが、その富士宮市の近くと思われる清水市（現在は静岡市清水区）と御殿場インターは、平成4年の傷害・準強姦被告事件に至る経緯に密接な関わりがあります。

　深澤諭史弁護士については昨夜みた「刑事一代」というドラマに匹敵以上に、弁護士一代、爆走弁護士野郎という言葉が頭に浮かぶ、強烈な存在です。さかのぼれば「男一匹ガキ大将」という物心ついて初めの頃にみた漫画に通じる、物語の初め感があります。すさまじい存在感です。

　数日前にも少し書いたように思いますが、モトケンこと矢部善朗弁護士（京都弁護士会）、小倉秀夫弁護士、深澤諭史弁護士には、現在の弁護士業界を根底から吹き飛ばすパワーも期待してきた危機感と表裏一体の思いがありました。

```
集英社の漫画雑誌『少年ジャンプ』（1969年より『週刊少年ジャンプ』に改名）にて1968年11号から1973年13号まで連載。単行本はジャンプ・コミックス全20巻、集英社漫画文庫版全20巻、JCDX全12巻、集英社文庫コミック版全7巻（後半部未収録、後述）。

［source：］男一匹ガキ大将 - Wikipedia https://ja.wikipedia.org/wiki/%E7%94%B7%E4%B8%80%E5%8C%B9%E3%82%AC%E3%82%AD%E5%A4%A7%E5%B0%86
```

　昭和44年に「少年ジャンプ」が「週刊少年ジャンプ」に改名とありますが、これは初めて知ったように思います。週刊少年ジャンプしか記憶にはありません。昭和43年から昭和48年までの連載とありますが、この男一匹ガキ大将は、単行本でみた記憶しかないとも思います。

　「弁護士一代深澤稼業」というのも、深澤諭史弁護士のツイートをみながらしばしば頭に浮かんできた言葉の一つです。それも表現の1つかと思います。非弁に強いこだわりで弁護士会での活動もしているという深澤諭史弁護士なので、正規版にも見えますが、その辺りを含めた印象です。

　時刻は21時39分です。夕食もまだなのですが、深澤諭史弁護士のタイムラインを再び確認しておきたいと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜okinahimeji（櫻井光政） 日時：2019-08-12 21:41／2019-08-12 20:55 URL： https://twitter.com/kk_hirono/status/1160894100930883589 https://twitter.com/okinahimeji/status/1160882497573404673
&twitter(1160894100930883589){theme:light}
> この人とか。 https://t.co/4CL4s1uQ5Y
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jkubokawa（クボカワジュン） 日時：2019-08-12 21:41／2019-08-12 20:20 URL： https://twitter.com/kk_hirono/status/1160894147701592069 https://twitter.com/jkubokawa/status/1160873623936065536
&twitter(1160894147701592069){theme:light}
> @mmmmmaroooooonn @hirochka65 @ryouheitakaki @okinahimeji 天罰当たって高校生の娘があの世に逝った奴もいたな😂
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mmmmmaroooooonn（まろーん） 日時：2019-08-12 21:42／2019-08-12 20:18 URL： https://twitter.com/kk_hirono/status/1160894218228793346 https://twitter.com/mmmmmaroooooonn/status/1160873214135812097
&twitter(1160894218228793346){theme:light}
> @jkubokawa @hirochka65 @ryouheitakaki @okinahimeji これから下るところです。 \n   \n  高本、お天道様は見てるよ。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jkubokawa（クボカワジュン） 日時：2019-08-12 21:42／2019-08-12 18:16 URL： https://twitter.com/kk_hirono/status/1160894240877977600 https://twitter.com/jkubokawa/status/1160842604814016518
&twitter(1160894240877977600){theme:light}
> @mmmmmaroooooonn @hirochka65 @ryouheitakaki @okinahimeji 天罰が下ったか？
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mmmmmaroooooonn（まろーん） 日時：2019-08-12 21:42／2019-08-03 21:13 URL： https://twitter.com/kk_hirono/status/1160894262168305664 https://twitter.com/mmmmmaroooooonn/status/1157625586598080512
&twitter(1160894262168305664){theme:light}
> @ryouheitakaki @okinahimeji 毎夜、悪夢に魘され、臨終の間際には貴方の家族を食べさせる為に犠牲になった（自殺者を含む）別居親達の顔を思い浮かべて下さい。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ryouheitakaki（高木良平） 日時：2019-08-12 21:42／2019-08-02 12:23 URL： https://twitter.com/kk_hirono/status/1160894289515167749 https://twitter.com/ryouheitakaki/status/1157129850085244930
&twitter(1160894289515167749){theme:light}
> @okinahimeji なかなか自分が病院に行く時間って確保できないですね｡｡｡
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜okinahimeji（櫻井光政） 日時：2019-08-12 21:42／2019-08-02 12:13 URL： https://twitter.com/kk_hirono/status/1160894307911397376 https://twitter.com/okinahimeji/status/1157127230654275584
&twitter(1160894307911397376){theme:light}
> @ryouheitakaki 病院へはよ。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ryouheitakaki（高木良平） 日時：2019-08-12 21:42／2019-08-01 22:34 URL： https://twitter.com/kk_hirono/status/1160894326265614336 https://twitter.com/ryouheitakaki/status/1156921056835194880
&twitter(1160894326265614336){theme:light}
> 元々かなりの頭痛持ちなんですが、昨日辺りから後頭部に激痛が走ります｡｡｡なんか怖いな｡｡｡
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mmmmmaroooooonn（まろーん） 日時：2019-08-12 21:42／2019-08-12 20:26 URL： https://twitter.com/kk_hirono/status/1160894370796601344 https://twitter.com/mmmmmaroooooonn/status/1160875088721223680
&twitter(1160894370796601344){theme:light}
> @jkubokawa @hirochka65 @ryouheitakaki @okinahimeji 娘さんを溺愛しているようですね。 \n  高木は天罰を受けるべきですが娘さんは可哀相。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jkubokawa（クボカワジュン） 日時：2019-08-12 21:42／2019-08-12 20:27 URL： https://twitter.com/kk_hirono/status/1160894384956592128 https://twitter.com/jkubokawa/status/1160875394913857537
&twitter(1160894384956592128){theme:light}
> @mmmmmaroooooonn @hirochka65 @ryouheitakaki @okinahimeji まぁね。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mmmmmaroooooonn（まろーん） 日時：2019-08-12 21:42／2019-08-12 20:35 URL： https://twitter.com/kk_hirono/status/1160894408767635457 https://twitter.com/mmmmmaroooooonn/status/1160877365792108544
&twitter(1160894408767635457){theme:light}
> @jkubokawa @hirochka65 @ryouheitakaki @okinahimeji 繰り返しますが高木は天罰を受けるべきです。 \n  その場合娘さんは父親を…… \n  という事ですよ。 \n  悪い奴だけ裁かれれば、それでよいと思います。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jkubokawa（クボカワジュン） 日時：2019-08-12 21:42／2019-08-12 20:35 URL： https://twitter.com/kk_hirono/status/1160894424177471488 https://twitter.com/jkubokawa/status/1160877535372046336
&twitter(1160894424177471488){theme:light}
> @mmmmmaroooooonn @hirochka65 @ryouheitakaki @okinahimeji 楽しみですね^_^
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mmmmmaroooooonn（まろーん） 日時：2019-08-12 21:42／2019-08-12 20:36 URL： https://twitter.com/kk_hirono/status/1160894444775723009 https://twitter.com/mmmmmaroooooonn/status/1160877764586528768
&twitter(1160894444775723009){theme:light}
> @jkubokawa @hirochka65 @ryouheitakaki @okinahimeji 高木本人はロクな死に方をしない。 \n  それでいいではないですか。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜jkubokawa（クボカワジュン） 日時：2019-08-12 21:43／2019-08-12 20:37 URL： https://twitter.com/kk_hirono/status/1160894455093686272 https://twitter.com/jkubokawa/status/1160877901455060992
&twitter(1160894455093686272){theme:light}
> @mmmmmaroooooonn @hirochka65 @ryouheitakaki @okinahimeji そうですね。
◁◁◁
<hr />

　深澤諭史弁護士の返信やリツイートで見かけることが多い高木良平弁護士が、批判の的となり、櫻井光政弁護士がそれを批判するツイートを深澤諭史弁護士がリツイートしているようです。昼に見かけていたアカウントのツイートは、この流れにありませんでした。

　弁護士の仕事というのは依頼者の利益を守るものなので、それを真面目に徹底するほど反感や恨みを買いやすい因果な商売とも理解はありますが、前の高木良平弁護士のツイートを見ていると、現実的な加害に備え、ずいぶんと注意しながら生活をされているようでもありました。

　高木良平弁護士は真面目で誠実な人にも見えますが、向原栄大朗弁護士と同じく深澤諭史弁護士に異常性を感じず親和的なところに、より深刻な問題性を感じてきました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirochka65（hirochka　クソ弁護士から日本を守る） 日時：2019-08-12 21:51／2019-08-11 18:55 URL： https://twitter.com/kk_hirono/status/1160896654309916673 https://twitter.com/hirochka65/status/1160489950149664768
&twitter(1160896654309916673){theme:light}
> @r34CXRsvHnOj2GB @ryouheitakaki @okinahimeji 高木さん、不謹慎なコメントをお詫びします。私は貴方が大嫌いだけど娘さんの為に御自愛下さい。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜r34CXRsvHnOj2GB（弁護士杉山程彦5東慶應三丁目） 日時：2019-08-12 21:52／2019-08-11 15:31 URL： https://twitter.com/kk_hirono/status/1160896733867495424 https://twitter.com/r34CXRsvHnOj2GB/status/1160438539634401280
&twitter(1160896733867495424){theme:light}
> @hirochka65 @ryouheitakaki @okinahimeji これはやめよう。 \n  いくら憎いからといって、このツリーはそれとはなんの関係もない。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirochka65（hirochka　クソ弁護士から日本を守る） 日時：2019-08-12 21:52／2019-08-11 04:02 URL： https://twitter.com/kk_hirono/status/1160896750007177216 https://twitter.com/hirochka65/status/1160265282172026880
&twitter(1160896750007177216){theme:light}
> @ryouheitakaki @okinahimeji アマゾンでお坊さん手配しましょうか？
◁◁◁
<hr />

　関連性の高いアカウント、から見覚えのあるアカウントのタイムラインを開き、見覚えのあるツイートをリツイートしました。個人的に深澤諭史弁護士に弁護士全体に対する怒りや不信が向かないのは不思議でしょうがないのですが、いずれも客観的な資料です。

```
高木良平
@ryouheitakaki
MJ法律事務所の代表弁護士（59期、第二東京弁護士会所属）football/rugby/boxing/michael jackson/育児 安全ピントラブル対策弁護団代表 (link： http：//anzenpin.jtwla.com/) anzenpin.jtwla.com 50パーセント弁護士友の会
東京都墨田区mjlawoffice.business.site2010年10月からTwitterを利用しています
2,131 フォロー中
3,239 フォロワー

［source：］(6) 高木良平（@ryouheitakaki）さんの返信があるツイート / Twitter https://twitter.com/ryouheitakaki/with_replies
```

　高木良平弁護士については、比較的深刻な問題性、社会的害悪姓、危険生物性も感じることなく、それほど詳しく調べてもいないと思うのですが、顔出しの実名で、プロフィールを確認すると法律事務所の名称もありました。

　ぶっちゃけた話、深澤諭史弁護士に関してはずっと前から、公開されている所属の法律事務所に爆破事件がニュースとなっても全く驚かないという思いがありました。一つの参考は宇都宮の爆発事件です。ストーカーに対しても実に挑発的で病気と切り捨てたツイートが目立ってきました。

　そのストーカーにも似た形態の問題に親権や連れ去りの問題がありましたが、本日、深澤諭史弁護士がリツイートなどしていたのはその親権や連れ去りに関連のあるツイートでした。深澤諭史弁護士に対する根深い不信や反感というツイートはこれまで見かけてはいません。

　深澤諭史弁護士に関しては不快度の指数も飛び抜けた高いところですが、弁護士業界全体に対するダメージには大いに期待するところがあり、時間の無駄にも我慢を続けています。弁護士業界ともにこの社会から木っ端微塵に吹き飛んでくれれば、それこそ明るい未来の希望が差し込みます。

　時刻は22時09分です。今日は夕方の早い時間にお好み焼きを作って食事を済ませるつもりでした。長芋はだいぶん前に買ったものがあり、キャベツ1玉と豚肉の小間切れは、昨日、どんたく宇出津店で買ったものがあります。今日は買い物にも外にも出掛けませんでした。

時刻は22時09分です。今日は夕方の早い時間にお好み焼きを作って食事を済ませるつもりでした。長芋はだいぶん前に買ったものがあり、キャベツ1玉と豚肉の小間切れは、昨日、どんたく宇出津店で買ったものがあります。今日は買い物にも外にも出掛けませんでした。

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-12 22:12／2019-08-11 11:34 URL： https://twitter.com/kk_hirono/status/1160901876927217665 https://twitter.com/fukazawas/status/1160378829866557440
&twitter(1160901876927217665){theme:light}
> （；・∀・）そういう案件の後始末を何度かしたことがある者。 https://t.co/uFbAQYavpH
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜0o2441（法律・法曹版　悪魔の辞典） 日時：2019-08-12 22:12／2019-08-11 11:31 URL： https://twitter.com/kk_hirono/status/1160901910401974272 https://twitter.com/0o2441/status/1160378224171343875
&twitter(1160901910401974272){theme:light}
> 【法務部】「なぜこの法律事務所にしたんだ」と後で怒られるのが嫌で、特殊事件でもないのに、当該事件の解決のために依頼するには費用対効果が悪い高い法律事務所に漫然と依頼し続けてしまう部署。※すみません、ちょっと極端に書きすぎました。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-12 22:12／2019-08-11 10:54 URL： https://twitter.com/kk_hirono/status/1160901937782329346 https://twitter.com/fukazawas/status/1160368924354994176
&twitter(1160901937782329346){theme:light}
> （・∀・）私、結構ネットの表現者側での弁護することありますが（軽く３桁件はやっている）、実際に、権利（人権）侵害であるが適法ということで勝ったことも何度もあるし。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜0o2441（法律・法曹版　悪魔の辞典） 日時：2019-08-12 22:13／2019-06-14 06:03 URL： https://twitter.com/kk_hirono/status/1160902036138803201 https://twitter.com/0o2441/status/1139277068816932866
&twitter(1160902036138803201){theme:light}
> 【そういうとこだぞ。】モラハラ相手の離婚調停事件などで、相手からの反論内容自体が、相手がモラハラであることを真正面から特徴づけてしまっているような場合に思わず口にでてしまうセリフ。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜0o2441（法律・法曹版　悪魔の辞典） 日時：2019-08-12 22:13／2019-07-17 10:40 URL： https://twitter.com/kk_hirono/status/1160902054627254275 https://twitter.com/0o2441/status/1151305687336546304
&twitter(1160902054627254275){theme:light}
> @hibito_2525 「そういうとこだぞ」案件ですね。 \n   \n  https://t.co/pwqiUyb60X
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-12 22:13／2019-08-11 10:51 URL： https://twitter.com/kk_hirono/status/1160902105139298304 https://twitter.com/fukazawas/status/1160368151013416962
&twitter(1160902105139298304){theme:light}
> （・∀・）「他人の人権を侵害する表現の自由は認められない」は、実は現行法上間違いです。もちろん、無制限ではないですが。 \n  （＾ω＾）奇しくも今書いている書籍、他人の人権を侵害する表現の自由も広範囲に認められている、ということの裁判例や実務の解説なんだお。
◁◁◁
<hr />

　思い出したことがあったので、深澤諭史弁護士のタイムラインを遡り、あらためてリツイートをしました。告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でリツイート済みのツイートもありましたが、軽く3桁とあります。

```
深澤　諭史　(Fukazawa SATOSHI)
ＩＴ法務（システム開発紛争，インターネット上の取引トラブル，インターネット上の誹謗中傷・風評被害対策），労働事件を中心に取り扱ってきました。

IT法務.jp もご覧下さい。


経歴・役職
明治大学法学部法律学科　卒業
東京大学大学院法学政治学研究科　法曹養成専攻　修了
最高裁判所司法研修所　修了
弁護士登録（第二東京弁護士会）
都内法律事務所勤務，参画
服部啓法律事務所　参画
第二東京弁護士会 非弁護士取締委員会 委員（平成２３年４月～）
第二東京弁護士会 常議会 常議員（平成２５年４月～平成２６年３月）
第二東京弁護士会 国際委員会 幹事（平成２６年４月～）
第二東京弁護士会 弁護士業務センター 幹事（平成２６年４月～平成２７年３月）
第二東京弁護士会 弁護士業務センター 副委員長（平成２７年４月～）
日本弁護士連合会 業務改革委員会 幹事（平成２６年５月～）
日本弁護士連合会 弁護士紹介制度検討ＷＧ（平成２６年６月～平成２８年３月）
日本弁護士連合会 インターネットを利用した弁護士業務広告の在り方ＷＧ（平成２７年４月～平成２８年３月） 
第二東京弁護士会 嘱託弁護士（非弁護士取締担当）（平成２８年６月～平成３０年３月）

［source：］服部啓法律事務所 ：： 所属弁護士について http://hklaw.jp/%E4%BA%8B%E5%8B%99%E6%89%80%E3%83%BB%E5%BC%81%E8%AD%B7%E5%A3%AB%E7%B4%B9%E4%BB%8B/%E6%89%80%E5%B1%9E%E5%BC%81%E8%AD%B7%E5%A3%AB%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6/
```

　深澤諭史弁護士の公開しているプロフィールや経歴というのは、上記の引用をみても分かりづらいものとなっています。司法修習が63期となっていたと思いますが、これだと弁護士としての職務経験は多めに見込んで最大で10年ではないかと思います。

　行列のできる法律相談所というのはテレビ番組のタイトルにもなっていますが、三桁というのは最少でも100件となります。10年だと年間10件でしょうか。含みをもたせた大きく見せるというのも深澤諭史弁護士に感じてきた特徴の一つですが、疑問の方が大きいです。

　時刻は22時22分です。テレビの報道ステーションだと思いますが、韓国が日本をホワイト国から外したというニュースです。こういう先行き不透明な関係悪化のニュースを見ると、数年前から蓄積されてきた深澤諭史弁護士のツイートの悪影響というのも真剣に考えます。

```
自己紹介
法学部の出身ではありますが,コンピューターが趣味で,プログラミング等について経験があります。
最近では,IT関連,例えば,インターネット上の取引,ソフトウェア,ウェブサイトをめぐる法的紛争に興味を持っています。
そのようなトラブルをお抱えの企業・個人の方は,是非ご相談下さい。

所属弁護士会
第二東京弁護士会
弁護士登録年
2010年
経歴・技能
学歴
2006年 3月
明治大学法学部卒業
2009年 3月
東京大学法科大学院修了
活動履歴
所属団体・役職
2011年 4月
第二東京弁護士会 非弁護士取締委員会 委員
2013年 4月
第二東京弁護士会 常議員会 常議員

［source：］深澤 諭史弁護士（服部啓法律事務所） - 東京都港区 - 弁護士ドットコム https://www.bengo4.com/tokyo/a_13103/l_137982/
```

　上記に引用した弁護士ドットコムの記事で、深澤諭史弁護士の弁護士登録が2010年と確認できました。昨日今日弁護士登録が10月というのを目にしましたが、12月から1月が司法修習の終了時期で多いという情報を過去に見かけたようにも思いました。早くて10月なのではと思います。

　弁護士としての経験が9年でも少ないとも未熟ともまったく思いませんが、軽く三桁はやっている、という自己紹介を目にすると、かえって現実感が薄れ、漫画や別世界の登場人物のように思えてきますし、その印象をいっそう深めました。

　知的好奇心も強いのではと自己分析しますが、深澤諭史弁護士について書き出すと、このように止まらなくなってしまいます。過去のツイートを掘り起こせば、さらにとめどもなくなってしまうことでしょう。それだけでも全く物凄い存在感と放ち与えるパワーです。

　時刻は22時38分です。テレビに外国人の親子が浴衣姿で出てきて、越前市の花火大会のCMでした。越前市は以前の武生市だと2,3年前に知りました。同じ石川県でも加賀地方の花火大会はCMで見ていない気がします。和倉温泉の花火大会もCMにはなっていなかった気がします。

　それでも和倉温泉の花火大会は、終わった翌日に石川県内ニュースになっていて、終了した催しとしてはずいぶん珍しいと感じました。

[link:] » 『誰も教えてくれない田舎暮らしの教科書』（清泉亮著、東洋経済新報社）の著者は、自称「ベテラン・イジュラー」。いまからおよそ20年前、22歳のときに長野県・佐久に駐車場つき4万円のアパートを借り、週末移住… | いつか家を |… https://t.co/wvblywN1KC

<hr />

　再び清泉亮氏の検索結果の記載を始めました。Googleの検索結果に今のところ日航機墜落事故が見当たらないように思います。報道ステーションでは、今日が34年目という日航機墜落事故を取り上げていないような気がしました。さきほどスポーツコーナーに移りました。

[link:] » 清泉亮　山口 - Google 検索 https://t.co/Eb6m20lFxB

<hr />
[link:] » 山口「八つ墓村事件」、保見光成死刑囚が弁護士にも語らなかった“田舎暮らしの地獄”（デイリー新潮） - Yahoo!ニュース https://t.co/Es6ykUWzSW

<hr />

[link:] » 清泉亮　上野村 - Google 検索 https://t.co/tBwzRqpY0Y

<hr />

　Google検索のキーワードに絞り込みを掛けたことで、検索結果が変わってきました。以前に見かけた予備知識があってのことと思います。

[link:] » 日航と航空機墜落の村、陰で罵声浴びせ合う現実　剥き出しの村民たちの私利私欲 | ビジネスジャーナル https://t.co/tEzcGBVmL4 \n 2015.08.14

<hr />
[link:] » 【日航機墜落30年】御巣鷹の村、日航の「下請け化」＝経済的依存が深まる歪んだ関係 | ビジネスジャーナル https://t.co/k515GrNaFM \n 2015.08.13 \n ￼ ジャーナリズム \n ノンフィクションライター　清泉亮インタビュー（1）

<hr />
[link:] » 【日航機墜落30年】御巣鷹の村、日航の「下請け化」＝経済的依存が深まる歪んだ関係 (2015年8月13日) - エキサイトニュース https://t.co/VdzRMlpr35 \n 2015年8月13日 06:05

<hr />
[link:] » 十字架を背負った尾根: 日航機墜落現場の知られざる四季 | 清泉 亮 |本 | 通販 | Amazon https://t.co/Z2pHgAj8Qp

<hr />
[link:] » 日本航空123便墜落事故現場、まだ誰も見たことのない四季折々の風景 - 草思社のblog https://t.co/b7MnuzKzjH \n 著者・清泉亮さんが語る \n  \n 「御巣鷹の尾根、四季おりおりの風景のなかで、 \n 死者を想い、生者… https://t.co/WgpbxuDRke

<hr />
[link:] » 十字架を背負った尾根 清泉亮(著/文) - 草思社 | 版元ドットコム https://t.co/0LJuxMl6vD \n 清泉亮(著/文) \n 発行：草思社 \n 四六判   224ページ \n 定価 1,800円+税

<hr />

　検索結果にあるのは、刺激的、衝撃的な見出しで、内容も気になりますが、だいたいのパターンはこれまで読んできたもので共通がありそうなので、この先の作業を終了したいと思います。

　清泉亮氏の記事について前回調べて確認できなかったのは、山梨県だったと思いますが、祖父の権限が異常に強く孫娘を普通に強姦しているというような驚きのものがありました。重ねますが、この部分は調べたものの確認が出来なかったので、清泉亮氏の記事として断定は出来ません。

　時刻は23時01分です。チャンネルは変えていないので報道ステーションだと思いますが、元プロボクサーの坂本博之さんが出てきました。久しぶりです。その生き様として負けた試合が最も印象的な人物ですが、その対戦相手の活躍を最近テレビでみました。

　やはり報道ステーションでした。世界戦に4回挑んで失敗したともありました。福岡県の筑豊地方の施設で育ち、壮絶ないじめを受けたとも聞きますが、その筑豊地方が、日本でまれにみるほど治安の悪い土地だとしりました。アカマタ・クロマタを知ったのと同じ夜だったと思います。

　少し調べると、やはり沖縄県八重山列島とありますが、その辺りはDr. コトー診療所の撮影地ともなっていたように思います。このDr. コトー診療所についてもいくつか書いておきたいことが残っているのですが、清泉亮氏のこととも重ねて見えるところがありました。

[link:] » Dr. コトー診療所　撮影地 - Google 検索 https://t.co/HbNm6ll25Y

<hr />
[link:] » 西の最果ての地・与那国島には、Dr.コトー診療所のロケ地がそのまま残されていた https://t.co/dDPExsTCSr

<hr />
[link:] » 与那国島 - Wikipedia https://t.co/1X8bzGJjjb \n 与那国島（よなぐにじま）は、南西諸島八重山列島の島。島としては日本の最西端に位置しており、国境の島と呼ばれる。

<hr />
[link:] » 与那国島 - Google マップ https://t.co/DbPCjQpLgK

<hr />

　これまでに何度か地図を見てきたと思いますが、改めてGoogleマップで確認すると、台湾との近さに驚きました。沖縄本島に近い位置で石垣島、宮古島と並んでいます。この宮古島は父親が最前線の戦地として送り込まれたものの戦火を免れ、2,3年終戦を知らずに過ごしたと聞きます。

　父親が海がきれいだった話していたと聞きますが、遺伝子レベルではなにか体験的な記憶が残る土地なのではと、自分の子供の幼少期をあわせて考えたことがあります。

　そのような歴史的な人の人生、営みに思いを馳せると、清泉亮氏の記事には凄まじい負の部分を感じますし、昭和40年代から50年代に見聞きした日中戦争や太平洋戦争における日本軍、日本兵の負の部分とも重ねて考えることがあります。

　その日本軍、日本兵の負の部分を爽快かつ明快に揶揄、愚弄するのも深澤諭史弁護士と小倉秀夫弁護士に共通した特徴であって、深澤諭史弁護士においてはインパール作戦と「はだしのゲン」の町内会長に、より顕著な特徴を見ることができます。史実と病的認識の狭間についても考えさせられる資料です。

　戦争を経験していない私には、韓国の従軍慰安婦の問題についても名にした資料以上の判断は出来ませんが、刑事弁護においてはその弁護士の狂人性、おぞましさを体験として疑いもなく感じとってきたものがあります。それ故に深澤諭史弁護士の人間的異常性、危険性もビンビンに感じています。

　山梨県については、清泉亮氏の記事を読んだのと同じ頃に、地方病というのを知りました。たまたまテレビでみかけた衝撃的な映像かあるいは写真がきっかけで、ネットで調べたものです。

　他に、奥村徹弁護士が「殺生な」とした最高裁の性犯罪に関する大きな判例変更があって、その裁判例というのも山梨県で起こった事件でした。奥村徹弁護士の人間離れをした凄まじさもそこで改めて感じましたが、昔、レンタルビデオ店で見た「人間の条件」というテーマに近いものを感じました。

[link:] » ＃児童ポルノ･児童買春・青少年条例・児童福祉法・強制わいせつ弁護人奥村徹(大阪弁護士会)　@okumuraosaka＃のツイート／2019-08-08_1353〜2019-08-12_2256／法務検察・石川県警察宛参考資料／… https://t.co/p8JsoIrOoM

<hr />

　奥村徹弁護士のツイートを最新のまとめとして記録しました。奥村徹弁護士には救済的な宗教性を含め、日常的な人間の営み、感覚を超越したものを感じています。ことに性犯罪は平成4年から私が被害者安藤文さん、父親の安藤健次郎さんの人生を含めて背負うテーマでもあります。

　弁護士商売にしても奥村徹弁護士には、他の追随を突き放す最先端性があって、それはTwitterアカウントのプロフィールの名前にも象徴されているかと思います。ブログ名の方が長かったかも知れません。普通にツイートするのも困難です。

　「児童ポルノ･児童買春・青少年条例・児童福祉法・強制わいせつ弁護人奥村徹(大阪弁護士会)」が奥村徹弁護士のTwitterのプロフィールの名前になります。一月ほど前になりますか、しばらくの間、もっと簡潔で当たり障りもなさそうんものとなっていたのが復活しました。

児童ポルノ・児童買春・児童福祉法・監護者性交・強制わいせつ・青少年条例・不正アクセス禁止法・わいせつ電磁的記録記録被告事件弁護人　奥村徹弁護士の見解（弁護士直通050-5861-8888　hp@okumura-tanaka-law.com）

　上記がブログ名です。120文字と出ました。これならばURLを含めてツイートが出来そうです。

[link:] » 児童ポルノ・児童買春・児童福祉法・監護者性交・強制わいせつ・青少年条例・不正アクセス禁止法・わいせつ電磁的記録記録被告事件弁護人　奥村徹弁護士の見解（弁護士直通050-5861-8888　hp@okumura-tanaka-l… https://t.co/fhcZMpzXiO

<hr />

　清泉亮氏、深澤諭史弁護士、奥村徹弁護士と共通して、私個人の理解をはるかに超絶したものがあります。ありのままに記録しご紹介しておきたいと思いつつ、共通性、共通項もあると思うのでまとめて記載をしました。

＜＜＜2019-08-12（月曜日）23：55＿［これまでの記述範囲の終了時刻］＜＜＜

