#+TITLE: "「殺生」をキーワードに含む奥村徹弁護士のツイートの記録"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-13 00:05:32 +0900
FILE_NAME: 2019-08-13-000532_「殺生」をキーワードに含む奥村徹弁護士のツイートの記録.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 奥村徹弁護士（大阪弁護士会） 
記事タイトル名の文字数：27　保存ファイル名の文字数：49

* 「殺生」をキーワードに含む奥村徹弁護士のツイートの記録
  :LOGBOOK:
  CLOCK: [2019-08-13 火 00:06]--[2019-08-13 火 01:52] =>  1:46
  :END:

＞＞＞2019-08-13（火曜日）00：06＿［これからの記述範囲の開始時刻］＞＞＞

```
[5405]  % dp -p |grep 殺生
[link:] 2017年11月29日17時48分の登録： ＼児童ポルノ/わいせつ/青少年淫行弁護人　@okumuraosaka＼殺生でっせ」　強制わいせつ罪の判例変更、被告の弁護団「従来なら無罪なのに…殺生だ」 - 産経ニュース http://hirono2014sk.blogspot.com/2017/11/okumuraosaka_29.html
[link:] 2017年11月30日13時40分の登録： REGEXP：”殺生”／データベース登録済みツイート：2017年11月30日13時39分の記録：ユーザ・投稿：40／53件 http://hirono2014sk.blogspot.com/2017/11/regexp2017113013394053.html
[link:] 2017年11月30日13時41分の登録： REGEXP：”強制わいせつ罪の判例変更、被告の弁護団「従来なら無罪なのに…殺生だ」”／データベース登録済みツイート：2017年11月30日13時40分の記録：ユーザ・投稿：13／14件 http://hirono2014sk.blogspot.com/2017/11/regexp2017113013401314.html
[link:] 2017年12月09日11時22分の登録： ＼ystk　@lawkus＼生活保護受給者って事務所に呼び出して打ち合わせしようとしても数百円の交通費が厳しいみたいなことよくあるんだけど、今よりもっと減らすだなんて殺生 http://hirono2014sk.blogspot.com/2017/12/ystklawkus_24.html
[link:] 2019年01月12日10時17分の登録： REGEXP：”殺生”／強制わいせつ/準強姦/買春/児童ポルノ/児童福祉法/青少年条例弁護人弁護士奥村徹(大阪弁護士会)（@okumuraosaka）の検索（2010-01-06〜2018-03-24／2019年01月12日10時17分の記録5件） http://hirono2014sk.blogspot.com/2019/01/regexpokumuraosaka2010-01-062018-03.html
[link:] 2019年03月15日07時26分の登録： REGEXP：”殺生”／データベース登録済みツイート：2019年03月15日07時23分の記録：ユーザ・投稿：68／124件 http://hirono2014sk.blogspot.com/2019/03/regexp20190315072368124.html
[link:] 2019年03月15日07時26分の登録： REGEXP：”殺生でっせ”／データベース登録済みツイート：2019年03月15日07時26分の記録：ユーザ・投稿：8／10件 http://hirono2014sk.blogspot.com/2019/03/regexp201903150726810.html
```

　奥村徹弁護士のツイートに限定せずに検索していたことに気が付きました。三浦義隆弁護士のツイートが１つ明らかに紛れていることで気が付きました。殺生という言葉も近年は滅多に見かけることがないので、若い世代だと知らない人も多いのかも知れません。

　かくいう私も殺生の意味をよく知っているわけではないですが、仏教の宗教的なイメージが色濃くあります。また「殺生」と「殺生な」では意味がまったく違ってくるかもしれません。「殺生でっせ」は大阪弁のようですが、より強調されたニュアンスは感じられます。

```
奥村徹弁護士はこの分類について「境目が分からない」と指摘。「この判例で５０年近くやってきたのに、この事件から判例を変えるのは不公平だ」と話した。

　最高検の中原亮一公判部長は「検察官の主張が認められた妥当な判決と考える」とコメントした。

［source：］強制わいせつ罪の判例変更、被告の弁護団「従来なら無罪なのに…不公平だ」 - 産経ニュース https://www.sankei.com/affairs/news/171129/afr1711290038-n1.html
```

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜okumuraosaka（児童ポルノ･児童買春・青少年条例・児童福祉法・強制わいせつ弁護人奥村徹(大阪弁護士会)） 日時：2019-08-13 00:17／2017-11-29 14:22 URL： https://twitter.com/kk_hirono/status/1160933248827920385 https://twitter.com/okumuraosaka/status/935740724636680198
&twitter(1160933248827920385){theme:light}
> 殺生でっせ」　強制わいせつ罪の判例変更、被告の弁護団「従来なら無罪なのに…殺生だ」 - 産経ニュース https://t.co/tg5z8kFopz @Sankei_newsさんから
◁◁◁
<hr />

　いつのまにか産経ニュースの記事が「殺生」から「不公平」に変わっているようです。奥村徹弁護士のツイートは索条もされずそのままのようです。告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)ではブロックされていないのでリツイートできています。

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「殺生」の検索結果 - Twilog https://t.co/kIXFKY0Mih

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:20／2019-01-12 10:56 URL： https://twitter.com/kk_hirono/status/1160934198581927936 https://twitter.com/s_hirono/status/1083905582946349056
&twitter(1160934198581927936){theme:light}
> 2019-01-12-102002_強制わいせつ／準強姦／買春／児童ポルノ／児童福祉法／青少年条例弁護人弁護士奥村徹（大阪弁護士会）さんのツイート：　”殺生でっせ」　強制わいせつ罪の判例変更.jpg https://t.co/1k7LqKgYcD
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:21／2019-01-12 10:56 URL： https://twitter.com/kk_hirono/status/1160934225513611269 https://twitter.com/s_hirono/status/1083905613933903872
&twitter(1160934225513611269){theme:light}
> 2019-01-12-102016_強制わいせつ／準強姦／買春／児童ポルノ／児童福祉法／青少年条例弁護人弁護士奥村徹（大阪弁護士会）さんのツイート：　”判例変更は殺生だっせ～判例変更と憲法3.jpg https://t.co/watHeAd0Nx
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:21／2015-06-14 04:45 URL： https://twitter.com/kk_hirono/status/1160934278378557442 https://twitter.com/s_hirono/status/609808712300036096
&twitter(1160934278378557442){theme:light}
> ロー生が肉を食べるのはおかしい。殺生は成仏から遠のくぞ。何のためにローに入ったのか思い出せよ。／泥濘大魔王サイケ https://t.co/wcQkpIojBe
◁◁◁
<hr />

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/2019年01月12日 - Twilog https://t.co/9k5K3dVRNC

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:26／2019-01-12 12:30 URL： https://twitter.com/kk_hirono/status/1160935594899283968 https://twitter.com/s_hirono/status/1083929228964290560
&twitter(1160935594899283968){theme:light}
> 2019-01-12-120033_奥村徹弁護士のリツイート＞　朝日新聞大阪社会部（@osakashakai）：　強姦冤罪、男性の国家賠償請求を棄却　女性のウソで服役：朝日新聞デジタル.jpg https://t.co/jpTWwQFpaa
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:26／2019-01-12 12:32 URL： https://twitter.com/kk_hirono/status/1160935691338956800 https://twitter.com/s_hirono/status/1083929739440472064
&twitter(1160935691338956800){theme:light}
> 2019-01-12-120617_奥村徹弁護士のツイート：　”山吉彩子検事（56期…　”.jpg https://t.co/mksMNZlNMH
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:27／2019-01-12 12:33 URL： https://twitter.com/kk_hirono/status/1160935732279562241 https://twitter.com/s_hirono/status/1083929811964182529
&twitter(1160935732279562241){theme:light}
> 2019-01-12-120731_奥村徹弁護士のツイート：　”強姦冤罪事件、国賠請求を棄却　大阪地裁.jpg https://t.co/kLRalj5E5m
◁◁◁
<hr />

　途中で追うのをやめたのですが、2019年1月12日の非常上告-最高検察庁御中_ツイッター（@s_hirono）のツイートはTwilogで203件とありました。この時期だとすべてがスクリーンショットの記録だと思います。

　付随して思わぬ発見もありましたが、産経の記事のスクリーンショットの記録は見当たらず、「殺生」を含む見出しと記事本文は確認できなかったように思います。あまり集中できていないので見落としの可能性もあります。まだ済ませていない夕食のことも気になっています。

　新たに記録したスクリーンショットを非常上告-最高検察庁御中_ツイッター（@s_hirono）にアップロードしていますが、早めに夕食を済ませておけばよかったと後悔しています。今夜は暑さもましで過ごしやすくも感じますが、空腹のためか体調もすっきりしません。

　アップロードが終わっていたので、リツイートに掛かります。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:40／2019-08-13 00:37 URL： https://twitter.com/kk_hirono/status/1160939119402315776 https://twitter.com/s_hirono/status/1160938368483545088
&twitter(1160939119402315776){theme:light}
> 2019-08-13-003517_強制わいせつ罪の判例変更、被告の弁護団「従来なら無罪なのに…不公平だ」　-　産経ニュース.jpg https://t.co/FbDzE497iJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:40／2019-08-13 00:37 URL： https://twitter.com/kk_hirono/status/1160939143360204800 https://twitter.com/s_hirono/status/1160938294001037317
&twitter(1160939143360204800){theme:light}
> 2019-08-13-003458_奥村徹弁護士　殺生　-　Google　検索.jpg https://t.co/pm6MuG7jRm
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:40／2019-08-13 00:36 URL： https://twitter.com/kk_hirono/status/1160939163471888387 https://twitter.com/s_hirono/status/1160938221162778626
&twitter(1160939163471888387){theme:light}
> 2019-08-13-003424_判例変更は殺生だっせ～判例変更と憲法31条，39条との関係～最高裁調査官馬渡香津子「強制わいせつ罪の成立と行為者の性的意図の要否　最高裁平成29年11月2.jpg https://t.co/n37lq4wwk2
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:40／2019-08-13 00:36 URL： https://twitter.com/kk_hirono/status/1160939200515985408 https://twitter.com/s_hirono/status/1160938075528105984
&twitter(1160939200515985408){theme:light}
> 2019-08-13-001556_強制わいせつ罪の判例変更、被告の弁護団「従来なら無罪なのに…不公平だ」　-　産経ニュース.jpg https://t.co/ZnN3xFQ4Up
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-13 00:40／2019-08-13 00:36 URL： https://twitter.com/kk_hirono/status/1160939217754550272 https://twitter.com/s_hirono/status/1160938002048143361
&twitter(1160939217754550272){theme:light}
> 2019-08-12-235952_児童ポルノ・児童買春・児童福祉法・監護者性交・強制わいせつ・青少年条例・不正アクセス禁止法・わいせつ電磁的記録記録被告事件弁護人　奥村徹弁護士の見解（弁護.jpg https://t.co/HZcL7n2f2C
◁◁◁
<hr />

```
強制わいせつ罪の成立には「性的意図が必要」とする判例を変更した２９日の最高裁大法廷判決。同罪について有罪とされた被告（４０）の弁護団が東京・霞が関の司法記者クラブで会見し、「従来の判例なら無罪なのに、納得しがたい」と話した。

　大法廷判決は強制わいせつ罪が成立するかの判断にあたり、（１）ただちにわいせつだと評価できる行為（２）具体的状況なども考慮しなければ性的な意味があるか評価しづらい行為－の２類型に分類。性的意図を一律に要件とすることは相当でないとする一方、（２）の場合には、行為者の目的など主観的事情も含めて考慮すべきケースもあるとした。

　奥村徹弁護士はこの分類について「境目が分からない」と指摘。「この判例で５０年近くやってきたのに、この事件から判例を変えるのは不公平だ」と話した。

　最高検の中原亮一公判部長は「検察官の主張が認められた妥当な判決と考える」とコメントした。

［source：］強制わいせつ罪の判例変更、被告の弁護団「従来なら無罪なのに…不公平だ」 - 産経ニュース https://www.sankei.com/affairs/news/171129/afr1711290038-n1.html
```

　あらためて上記に産経ニュースの記事を全文引用しましたが、これを読んでもさほどインパクトは感じません。裁判の中身の事件をみるとその異様さが際立つのですが、被害者の女児の将来を考えると掲載には大きなためらいがありました。同時に人柱のような犠牲、神事も感じました。

[link:] » 強制わいせつ罪の判例変更、被告の弁護団「従来なら無罪なのに…不公平だ」 - 産経ニュース https://t.co/p8wByHKOnl \n 強制わいせつ罪の最高裁判決を受けて会見する奥村徹弁護士（中央）ら＝２９日午後、東京・霞が関の司法記者クラブ（佐藤徳昭撮影）

<hr />

　記者会見の3人の写真がありますが、左端の人物は、これも弁護士と思われるものの誰なのかわかりません。右端の奥に見えるのは園田寿弁護士です。弁護士というよりは大学教授のイメージが強いですが、名前が正確に思い出せず、捜すのに多少手間取りました。園部と勘違いもしていました。

[link:] » 園田寿（@sonoda_hisashi）さん / Twitter https://t.co/RmxumWbxTf

<hr />

　Twitterのアカウントのページも久しぶりにみましたが、ご自身のツイートは7月5日で止まり、そのあとリツイートが２つあります。最新となっているリツイートは見覚えのあるアカウントのもので、和歌山カレー事件の長男のツイートでした。

　0時56分です。まだ日付が変わって1時間経っていないものの火曜日となっていますが、ちょうど先週の月曜日に、珠洲道路沿いの神和住の食堂に初めて入り、丁度テレビのバイキングで、銀河鉄道999のイラストの問題を取り上げた後、このカレー事件の長男のTwitterを取り上げていました。

　食堂のテレビがずいぶん古いもので、ワイド画面ではなく左右に字幕が途切れて表示されないという見たこともない状態だったのですが、画質も荒く、20,30年ほど前にタイムスリップしたような気分でテレビの映像をみていました。

　神和住という住所は、家に戻ってからGoogleマップで確認したものです。その数日前に、旧柳田村の笹川から来て突き当たった道路を左折して、どこに出るのかと思いながらバイクで走行していたところ、ちょうどその食堂がある敷地の横の道路で珠洲道路に出ました。

　その敷地に食堂があることは少し知っていたのですが、たぶん敷地の中に入ったのも初めてで、食堂を見ると営業時間が11時から14時となっていて、珍しく時間が短いので驚いてもいました。母親のタオルケットを買いに行ったことで、またその食堂の近くに出ることになりました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜wakayamacurry（カレー事件 長男） 日時：2019-08-13 01:06／2019-07-15 19:04 URL： https://twitter.com/kk_hirono/status/1160945646464933888 https://twitter.com/wakayamacurry/status/1150707764169039872
&twitter(1160945646464933888){theme:light}
> 毒カレー事件から20年…主任弁護士が語るヒ素鑑定の“矛盾” https://t.co/9nAS3LWBOa #日刊ゲンダイDIGITAL
◁◁◁
<hr />

　この和歌山の毒カレー事件については、もう5年以上は経っていると思いますが、ネットで弁護士らが公開した再審請求書を読んだことがありました。PDFファイルだったと思いますが、黒塗りされた関係者の名前部分を範囲選択すると、隠された文字列が見える状態となっていました。

　コメント欄だったと思いますが、その旨を指摘したところ、翌日か翌々日に見たときには隠された文字が表示されないようになっていましたが、何事もなかったように反応を確認することもなかったのが印象的でした。

　和歌山毒物カレー事件の長男のTwitterはネットで数日前に少し見かけていました。銀河鉄道999のメーテルのイラストの問題はネットだけではなくテレビの他の番組でも少し見かけていたような気がしますが、家に戻ってからは幻でも見ていたかのように全く情報を見かけなくなりました。

　笹川から来た突き当りの広い道路は、右折したことしかなく、柳田の白山神社の近くに出る道で、そちらから柳田温泉に向かうつもりだったのですが、左折したらどこに出るのだろうとふと頭をよぎって実行したところ、能登空港から二子山、宇加川、鵜川で宇出津に戻ることになりました。

　この二子山というのも個人的に大きな発見だったのです。穴水町だと思い込み、かなり離れた場所だと想定していました。あとで調べると二子山の辺りは能登町武連という住所だったのですが、これはもっと離れた場所の能登空港の近くだと思い込んでいました。

　ネットで調べて確認は出来なかったのですが、半年ほど前に能登町の武連に火事があって、体の不自由な年配の女の人が逃げ遅れて死亡したというニュースを見たのですが、助けを求める電話をしていたとか、体が不自由なのに不便な場所で独り暮らしをしていたのかと、思いを巡らすことがありました。

[link:] 2018-11-23_181519＿テレビの画面・火事　能登町で住宅全焼　焼け跡から遺体　不明の女性か.jpg http://hirono2014sk.blogspot.com/2018/11/2018112512312018-11-230351102018-11.html#20181123181512#20181123181519 

　記録から確認できる情報を見つけ出すことが出来たのですが、同じ能登町でも武連ではなく宮地でした。「火事　足が不自由で1人暮らし遺体は不明の高齢女性か」とあって、78歳とあります。

　この宮地という地名も能登町のどの辺りなのかよくわかっていなかったのですが、同じ二子山に行ったときに、あの栃木県の葛生町の風景に似た石切り場のような風景の場所だとはっきり気がついたのです。思っていたより瑞穂の国道249号線に近い場所でもありました。

　武連と宮地をすっかり勘違いしていたのも不思議、漢字も全然違います。勘違いの記憶違いを確認できたのもスマホの写真による記録のおかげでした。記録の重要性をあらためて感じる機会となりました。犠牲のおかげと感謝したいですが、この不幸なニュースのときも神事のようなものを感じていました。

　数えるとあと3月少しで55歳となります。最近になってなぜ今ごろになって気がついたのかと思うことがあったり、ふとしたきっかけで思わぬ発見がいろいろとあったりします。

　深澤諭史弁護士や小倉秀夫弁護士、モトケンこと矢部善朗弁護士（京都弁護士会）、奥村徹弁護士、北周士弁護士といった面々に、すさまじいパワーと記録の必要性を感じ、それも実行に移してきました。最近になってようやく成果が出始めたとも感じています。

　やはり忍びなく、被害者の女児の将来を優先させたいので山梨の事件のことは、これ以上立ち入らないことにしたいと思いますが、産経ニュースの記事の写真にも記録されているように、奥村徹弁護士のこれでもかというような弁護士パワーを感じました。諸悪の根源と思わるような異様なパワーです。

　1つ前の記事になりますか、山梨の地方病についても少し触れたかと思います。その地方病はある人物によって原因が突き止められ、原因の生物にはその人物の名前で「ミヤイリガイ」と名付けられたと聞きます。宇出津のお祭りも締めくくりは神輿の宮入りだと聞いてきました。

　危険生物としての弁護士脳汚染の除去、それが問題の解決と同時に家内安全につながる神事ではないかとも考えています。

＜＜＜2019-08-13（火曜日）01：52＿［これまでの記述範囲の終了時刻］＜＜＜

