#+TITLE: "２００６年１０月と確認した、ヤメ蚊こと日隅一雄弁護士（故人）に、プライバシーを理由にブログのコメントを削除された件"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-14 15:40:21 +0900
FILE_NAME: 2019-08-14-154021_２００６年１０月と確認した、ヤメ蚊こと日隅一雄弁護士（故人）に、プライバシーを理由にブログのコメントを削除された件.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 石川県羽咋市で生活した平成14年11月から平成21年3月当時の状況  日隅一雄弁護士 海渡雄一弁護士 共謀罪 プライバシー
記事タイトル名の文字数：57　保存ファイル名の文字数：79

* ２００６年１０月と確認した、ヤメ蚊こと日隅一雄弁護士（故人）に、プライバシーを理由にブログのコメントを削除された件
  :LOGBOOK:
  CLOCK: [2019-08-14 水 15:50]--[2019-08-14 水 17:35] =>  1:45
  :END:

＞＞＞2019-08-14（水曜日）15：50＿［これからの記述範囲の開始時刻］＞＞＞

　家の中にいて今日は少し暑さがましかと思っていたのですが、少し外に出ると強い日差しでかなり暑かったです。平均してずっと暑い日が続いています。それもほとんど２４時間、あまり変わらない暑さがずっと続いています。

　はてなブログで、目的の情報を探しました。キーワードは「ヤメ蚊」でした。今日、日隅一雄弁護士について検索を始めてすぐに目に入った「ヤメ蚊」ですが、これはすっかり忘れていました。しかし、思い出してみると、以前は日隅一雄弁護士より馴染みのある言葉だったと思いました。

　思い出してみると、モトケンこと矢部善朗弁護士（京都弁護士会）のモトケンにも似ていますが、２００６年当時は、元検弁護士などと見ることも多く、ヤメ蚊とモトケン、元検の組み合わせで似たようなものとして捉えていました。

　ヤメ蚊こと日隅一雄弁護士は「情報流通促進計画 by ヤメ記者弁護士（ヤメ蚊）日隅一雄」というブログ名と確認しましたが、「情報流通促進計画」という部分がやたらと印象的で、実際の行動として実現していると感じるのはモトケンこと矢部善朗弁護士（京都弁護士会）のブログでした。

[link:] » ヤメ蚊 の検索結果 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/NJQYmydYff

<hr />

　検索結果の記事は、はてなダイアリーからの転載になります。そのはてなダイアリーの仕組みがややこしかったこともあり、日付単位の記事の転載となって、やたらと長くなっています。飛ばしながらわずかに拾い読みをした程度なのですが、明らかに該当する部分を次に引用します。

```
　あと、これも本日の朝方にかけて、見ていた現職弁護士のブログですが、元記者という特異な経歴もお持ちのようです。このブログ自体は、昨年の末頃から知っていて、たまにちょくちょく訪れ、最近になってトラックバックもよく入れていました。
＜情報流通促進計画 by ヤメ記者弁護士＞
というブログ名です。
　そして、次の記事にコメントを入れたところ、起きてから見てみると次のような断り書きとともに削除され、これまでに入れたトラックバックも丸ごと削除されたようです。

削除のお知らせ (ヤメ蚊)
2006-10-22 08：13：08
プライバシー保護の観点から、削除したコメントがあることをお知らせします。
http：//blog.goo.ne.jp/tokyodo-2005/e/1cf5f4bedf3b8e43750df82308ca4771

＜転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！＞
という記事です。
　はてなのブログではエントリと呼ぶようですが、gooのブログでは記事と呼んでいるようなので、一応それにあわせています。
　削除されたコメントの内容は、次のとおりです。

検察には迷惑しています。（廣野秀樹）


　私は、あなたがたのような分からず屋がいるので、検察から当て擦りをされて、とんでもない迷惑を蒙っている気がしてならないのです。
　何度もトラックバックを入れている私のブログをご覧になり、トラックバックを送るなり、見解を示してはもらえないでしょうか。



　次にキャプチャした画面を記録として、gooのブログの方にアップしておきました。
＜情報流通促進計画 by ヤメ記者弁護士ブログでのコメント削除２００６．１０．２２＞
http：//blog.goo.ne.jp/hirono_2005/e/f5aa73f97e535c33b0dc3350afd0512b


　誰の何のためのプライバシー保護の観点なのか意味不明ですが、言論封殺の恐怖政治を彷彿とさせる気もします。こんなことやっているから、共謀罪も強行採決されるのかもしれないですね。検察の意図がまったく見えていない気がします。


　その検察の意思表示は、同じgooのブログで写真画像を公開しています。昨日のエントリの中でもご紹介しているはずですが、改めてご紹介しておきます。
＜金沢地方検察庁平成１８年１０月１６日付け返戻書＞
http：//blog.goo.ne.jp/hirono_2005/e/88d9546518f5d4a9619fc93e7adadf91


　正義が何たるか、法的救済には何が必要なのか、議論すべき諸課題が沢山あるように思いますが、これではまさに百年河清を待つ、ようなもので、個人的にはどうでもいいようなことですが、強行採決ということになるのかもしれません。無駄な時間の付き合いをさせられてきたような気もしていますよ。


　そういえば、その記事に入っていたトラックバックを辿って、久しぶりに有名な「きっこの日記」というブログをみましたが、そこでも共謀罪が取り沙汰されていました。
http：//www3.diary.ne.jp/logdisp.cgi?user=338790&log=20061022
と一応リンクをご紹介しておきますが、「日記内の文章の無断転載転用を禁止します。」との断り書きが示されています。とにかくすごい人気で、アクセス数もすごいらしいです。世相を反映し、世相の期待にもかなっているのでしょう。
　しかもトラックバックやコメントなしでこれだけのアクセス数を叩きだしているのかもしれません。なかなか読む余裕もありませんが、すごいことです。
　そういえば、トラックバックの必要性自体、わからないというようなことも書いておられたような。真実を語るのは私の自由とか、なんとかは馬鹿、とかどこかで書いてあったような。どこかの人気ランキングのサイトだったと思いますが、はっきりわからなくなってしまいました。
　いずれにせよ、結果がすごいので、私も実力を認める他はありません。メールでの問い合わせには応じられているらしいので、あるいはそのうちメールを出してみるかもしれません。
　マスコミを説得するのが、先になると思いますし、路線が違うような気もしますので、メールの送信は実行しないかもしれません。コメントでのご意見も参考にしたいところです。


［source：］hatena-diary_20061022 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/entry/2006/10/22/000000
```

　キャプチャと書いてありますがスクリーンショットの画像はgooのブログでした。ちょうど昨日辺り、テーマのヘッダ画像のことで久しぶりに思い出していたのですが、リンクを開いて出てきたので少し驚きました。

　このgooのブログはずっと前にパスワードを忘れていてログインすることが出来ない状態です。

　テーマの画像は、可愛らしい絵なのですが、さくらんぼの恋人の生涯を描いているようです。兄弟にも見えるのですが、「７がつ」というコマに「ほうよう」「LOVE」とあるので恋人と思いました。「さいごの日」がメインの思われますが、人間の手でつままれ、食べられてしまうところのようです。

　個人的に「さくらんぼ」で思い出すのは、山形県の南陽市から山形市の間の国道１３号線で、買ったことは一度もなかったのですが、時期になると道路沿いに農作業服姿のような女の人がさくらんぼの直売をやっていました。頬かむりで顔もみえなかったですが、日本昔ばなしのような感じもありました。

[link:] » 山形　さくらんぼ　直売 - Google 検索 https://t.co/sU7S5I2gqx

<hr />

　遠い記憶でぼんやりとしか思い出せないので、Googleで画像検索を行ってみましたが、それらしい画像は見当たらず、今は大きな直晩所も出来ているようです。秋田の方であったか国道沿いでアイスクリームを売る女の人もいて、それはテレビのバラエティ系番組でも見た気がします。

　同じ頃は、石川県の河北郡高松町（現在はかほく市）辺りの国道沿いでも、直売所がいくつかあって、家族連れで立ち寄ったとき買い物をしたこともありました。小さいことですが個人的に印象深く思い出に残っています。

　上記のはてなのブログの記事で見つけた範囲に、「某氏」は見当たりませんでした。某氏の方が遥かに強く印象に残っているのですが、スクリーンショットとして確認することも出来ていません。なにか勘違いしていたのかと少し不安にもなったのですが、Twilogで痕跡を発見しました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「某氏」の検索結果 - Twilog https://t.co/MvVp8ICPoA

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-14 16:46／2011-01-27 11:28 URL： https://twitter.com/kk_hirono/status/1161544667554562048 https://twitter.com/hirono_hideki/status/30451992207826944
&twitter(1161544667554562048){theme:light}
> 無罪を争うために必要があれば、他人のプライバシーを侵害するような情報だって証言しなければならないことはよくある。それを封じるわけにはいかんでしょう。（引用）この弁護士に、某氏以外のプライバシーのため / 取り調べを可視化しても捜査に支障… http://htn.to/f2UzL7
◁◁◁
<hr />
[link:] » 取り調べを可視化しても捜査に支障はない～法務省の挑戦への回答案（前半） - 情報流通促進計画 by ヤメ記者弁護士（ヤメ蚊）日隅一雄 https://t.co/hrLcN8fY2x

<hr />

　リンクはヤメ蚊こと日隅一雄弁護士のブログ記事でした。そのツイートにあるリンクがhtn.toという短縮URLと思われるものなのですが、見覚えのないものです。

　私はTwitterを始めてしばらくしてから長い間、hootsuiteというサービスを使うことが多く、それは別の短縮URLになっていました。画像の投稿というのもそのサービスを使うことが多く、当時はTwitterに画像投稿機能はありませんでした。

[link:] » 某氏 の検索結果 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/S0VTSOUNVG

<hr />

　はてなのブログで「某氏」と検索をしても思ったような結果は得られませんでした。

　ツイートのリンクにあった「取り調べを可視化しても捜査に支障はない～法務省の挑戦への回答案（前半） - 情報流通促進計画 by ヤメ記者弁護士（ヤメ蚊）日隅一」という記事は、コメントが０でトラックバックが１件でした。

　リンクとなっているところをみると、この記事に私のコメントがあって、某氏の断り書きとともに日隅一雄弁護士に削除されたと考えるのが自然かと思います。

```
　あと、これも本日の朝方にかけて、見ていた現職弁護士のブログですが、元記者という特異な経歴もお持ちのようです。このブログ自体は、昨年の末頃から知っていて、たまにちょくちょく訪れ、最近になってトラックバックもよく入れていました。
＜情報流通促進計画 by ヤメ記者弁護士＞
というブログ名です。
　そして、次の記事にコメントを入れたところ、起きてから見てみると次のような断り書きとともに削除され、これまでに入れたトラックバックも丸ごと削除されたようです。

削除のお知らせ (ヤメ蚊)
2006-10-22 08：13：08
プライバシー保護の観点から、削除したコメントがあることをお知らせします。
http：//blog.goo.ne.jp/tokyodo-2005/e/1cf5f4bedf3b8e43750df82308ca4771

＜転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！＞
という記事です。
　はてなのブログではエントリと呼ぶようですが、gooのブログでは記事と呼んでいるようなので、一応それにあわせています。
　削除されたコメントの内容は、次のとおりです。

検察には迷惑しています。（廣野秀樹）


　私は、あなたがたのような分からず屋がいるので、検察から当て擦りをされて、とんでもない迷惑を蒙っている気がしてならないのです。
　何度もトラックバックを入れている私のブログをご覧になり、トラックバックを送るなり、見解を示してはもらえないでしょうか。



　次にキャプチャした画面を記録として、gooのブログの方にアップしておきました。
＜情報流通促進計画 by ヤメ記者弁護士ブログでのコメント削除２００６．１０．２２＞
http：//blog.goo.ne.jp/hirono_2005/e/f5aa73f97e535c33b0dc3350afd0512b


　誰の何のためのプライバシー保護の観点なのか意味不明ですが、言論封殺の恐怖政治を彷彿とさせる気もします。こんなことやっているから、共謀罪も強行採決されるのかもしれないですね。検察の意図がまったく見えていない気がします。


　その検察の意思表示は、同じgooのブログで写真画像を公開しています。昨日のエントリの中でもご紹介しているはずですが、改めてご紹介しておきます。
＜金沢地方検察庁平成１８年１０月１６日付け返戻書＞
http：//blog.goo.ne.jp/hirono_2005/e/88d9546518f5d4a9619fc93e7adadf91


　正義が何たるか、法的救済には何が必要なのか、議論すべき諸課題が沢山あるように思いますが、これではまさに百年河清を待つ、ようなもので、個人的にはどうでもいいようなことですが、強行採決ということになるのかもしれません。無駄な時間の付き合いをさせられてきたような気もしていますよ。


　そういえば、その記事に入っていたトラックバックを辿って、久しぶりに有名な「きっこの日記」というブログをみましたが、そこでも共謀罪が取り沙汰されていました。
http：//www3.diary.ne.jp/logdisp.cgi?user=338790&log=20061022
と一応リンクをご紹介しておきますが、「日記内の文章の無断転載転用を禁止します。」との断り書きが示されています。とにかくすごい人気で、アクセス数もすごいらしいです。世相を反映し、世相の期待にもかなっているのでしょう。
　しかもトラックバックやコメントなしでこれだけのアクセス数を叩きだしているのかもしれません。なかなか読む余裕もありませんが、すごいことです。
　そういえば、トラックバックの必要性自体、わからないというようなことも書いておられたような。真実を語るのは私の自由とか、なんとかは馬鹿、とかどこかで書いてあったような。どこかの人気ランキングのサイトだったと思いますが、はっきりわからなくなってしまいました。
　いずれにせよ、結果がすごいので、私も実力を認める他はありません。メールでの問い合わせには応じられているらしいので、あるいはそのうちメールを出してみるかもしれません。
　マスコミを説得するのが、先になると思いますし、路線が違うような気もしますので、メールの送信は実行しないかもしれません。コメントでのご意見も参考にしたいところです。


［source：］hatena-diary_20061022 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/entry/2006/10/22/000000
```

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2011年01月27日 - Twilog https://t.co/xWCiT9nLPz

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-14 17:19／2011-01-27 11:31 URL： https://twitter.com/kk_hirono/status/1161552885769019393 https://twitter.com/hirono_hideki/status/30452723841236994
&twitter(1161552885769019393){theme:light}
> という理由でコメント削除されたことがありました。
◁◁◁
<hr />

　記事の内容は無関係だったようです。

　残念ですが、はてなフォトライフをみても、それと思われるスクリーンショットは見当たりませんでした。しっかり記録しておきべきだったと悔やまれますが、今後の糧にしたいと思います。

[link:] » 【転載熱望】共謀罪の行方に関心を寄せるすべての方へ送る海渡弁護士の解説～政府は国民をこうして騙す！ - 情報流通促進計画 by ヤメ記者弁護士（ヤメ蚊）日隅一雄 https://t.co/EGo1LJ3yJt

<hr />

　「某氏」はなかったですが、コメントとトラックバックを削除した日隅一雄弁護士の断りが発見された記事です。考えてみると、某氏のコメントが別の記事だったとすると、断りを受けた記事は２つあったことになります。

　これ以上捜し出すのは困難と諦めがちですが、コメントがあったのは最初から１つの記事で、断り書きの内容を日隅一雄弁護士が書き換えていたという可能性もあるいはあるのかもしれません。

　妙な疑いをかけるつもりはないですが、記録の不徹底がジャーナリストの信用に影響を与えかねないとも思いました。これも今後の教訓にしておきたいと思いました。

＜＜＜2019-08-14（水曜日）17：35＿［これまでの記述範囲の終了時刻］＜＜＜

