#+TITLE: "嫌韓問題でモトケンこと矢部善朗弁護士（京都弁護士会）を批判したのか？　深澤諭史弁護士のリツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-15 20:01:49 +0900
FILE_NAME: 2019-09-15-200149_嫌韓問題でモトケンこと矢部善朗弁護士（京都弁護士会）を批判したのか？　深澤諭史弁護士のリツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: モトケンこと矢部善朗弁護士（京都弁護士会） ,深澤諭史弁護士のリツイート,ぎたべん
記事タイトル名の文字数：48　保存ファイル名の文字数：70

* 嫌韓問題でモトケンこと矢部善朗弁護士（京都弁護士会）を批判したのか？　深澤諭史弁護士のリツイート
  :LOGBOOK:
  CLOCK: [2019-09-15 日 20:04]--[2019-09-15 日 20:40] =>  0:36
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 深澤諭史弁護士のリツイート,ぎたべん

＞＞＞ 2019-09-15（日曜日）20：04 ＞＞＞

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-15 20:11／2019/09/15 20:10 URL： https://twitter.com/kk_hirono/status/1173192689707184128 https://twitter.com/s_hirono/status/1173192468369559552
> 2019-09-15-201012_ぎたべん（@guitar_ben）さん　／　Twitter.jpg https://t.co/3hhemhmd3Q
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-15 20:11／2019/09/15 20:10 URL： https://twitter.com/kk_hirono/status/1173192671856168960 https://twitter.com/s_hirono/status/1173192396416249856
> 2019-09-15-200931_ぎたべんさんはTwitterを使っています：　「1人の在日3世の発言で韓国全部嫌いになるなんて言うヤツは差別の理由探してるだけだから。差別主義自白ご苦労さ.jpg https://t.co/iOWfwVuTPx
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-09-15 20:08／2019/09/15 20:07 URL： https://twitter.com/kk_hirono/status/1173191804411244545 https://twitter.com/hirono_hideki/status/1173191490345955328
> 2019年09月15日19時06分の登録： ＼ぎたべん　@guitar_ben＼1人の在日3世の発言で韓国全部嫌いになるなんて言うヤツは差別の理由探してるだけだから。差別主義自白ご苦労さん。 https://t.co/lmIWoD0AaF
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-09-15 20:07／2019/09/15 19:07 URL： https://twitter.com/kk_hirono/status/1173191626396536832 https://twitter.com/s_hirono/status/1173176381577949184
> 2019-09-15-190623_深澤諭史さんがリツイートぎたべん@guitar_ben·6h1人の在日3世の発言で韓国全部嫌いになるなんて言うヤツは差別の理由探してるだけだから。差別主義.jpg https://t.co/1bjmwVnOdn
▶▶▶　　　　　End　　　　　▶▶▶

▶▶▶　kk_hironoのリツイート　▶▶▶
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜guitar_ben（ぎたべん） 日時：2019-09-15 20:12／2019/09/15 12:49 URL： https://twitter.com/kk_hirono/status/1173192942627897344 https://twitter.com/guitar_ben/status/1173081399445741569
> 1人の在日3世の発言で韓国全部嫌いになるなんて言うヤツは差別の理由探してるだけだから。差別主義自白ご苦労さん。 https://t.co/TNc98k4ESX
▶▶▶　　　　　End　　　　　▶▶▶

```
ぎたべん
@guitar_ben
ギターを弾く新進気鋭の若手弁護士。それ以上でもそれ以下でもない。
東京都2009年9月からTwitterを利用しています
652 フォロー中
1,170 フォロワー

［source：］ぎたべん（@guitar_ben）さん / Twitter https://twitter.com/guitar_ben
```

　ぎたべん、というアカウントですが上記にTwitterのプロフィールを引用しました。だいぶん前から時々ツイートを見かけてきた弁護士らしいアカウントですが、プロフィールのアイコンの写真は以前のものと違っているように思います。

　以前のプロフィールのアイコンというのもはっきりとは憶えていないのですが、それをみるとザ・ブルーハーツのパチスロ機のことをよく思い出していました。

```
THE BLUE HEARTS（ザ・ブルーハーツ）は、日本のパンク・ロックバンド。1985年結成。1987年にメジャーデビューし、1980年代後半から1990年代前半にかけて活動し、1995年に解散した。

ヒット曲は「リンダリンダ」「TRAIN-TRAIN」「情熱の薔薇」など［1］。コード進行は3、4コードを主としたシンプルなものが多いにもかかわらず、オリジナリティ溢れる楽曲を多く作り上げた。

［source：］THE BLUE HEARTS - Wikipedia https://ja.wikipedia.org/wiki/THE_BLUE_HEARTS
```

[link:] 2019年09月15日20時22分の登録： TWEET：”2015-10-01 21:41〜2019-09-15 12:49”／ぎたべん（@guitar_ben）の検索（2019年09月15日20時22分の記録459件） http://hirono2014sk.blogspot.com/2019/09/tweet2015-10-01-21412019-09-15.html

　まとめ記事を作成しました。100件もないだろうと予想していたのですが、459件の取得となったので驚きました。印象に残るツイートがいくつかあって、それらをデータベースに記録してきたのですが、はっきりと印象に残っているツイートというのは１つもありません。

　ギター好きというのは市川寛弁護士とも共通点がありますが、音楽バンドということでは小倉秀夫弁護士とも共通するかもしれません。2,3日前、久しぶりに小倉秀夫弁護士のFacebookを遡って投稿に目を通したのですが、ライブハウスのバンドに参加しているような話がありました。

　小倉秀夫弁護士がライブハウスのようなところによく出かけ、熱心に贔屓のバイドがあることは以前の投稿で知っていました。ただ、小倉秀夫弁護士本人が楽器を演奏するという話は全く見かけていませんでした。

　ぎたべん、のツイートはモトケンこと矢部善朗弁護士（京都弁護士会）の次のツイートのURLを引用したもので、返信や会話というツイートの流れにはなっていないようです。そのあたりもツイートの趣旨を分かりづらくしています。

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
▷▷▷　次のツイートはブロックされているのでリツイートできませんでした。 ▷▷▷
TW motoken_tw（モトケン） 日時：2019/09/15 10:03 URL： https://twitter.com/motoken_tw/status/1173039604829577216
> 私の個人的感覚に基づく憶測だが、この三世さんの発言によって、今まで嫌韓であった人が嫌韓でなくなる可能性より、今まで嫌韓でなかった人が嫌韓になる可能性のほうがはるかに高いと思う。 \n たぶん、前者は限りなくゼロに近い。
▷▷▷　　　　　End　　　　　▷▷▷

　当然ながらモトケンこと矢部善朗弁護士（京都弁護士会）にはブロックされているのでリツイートは出来ませんでした。次に深澤諭史弁護士のリツイートも記録しておきますが、そちらもブロックされているかと思います。

fukazawas ===> You have already retweeted this Tweet.
▷▷▷　@kk_hironoでリツイート済みのツイートです。　▷▷▷
RT fukazawas（深澤諭史） 日時：2019/09/15 13:06 URL： https://twitter.com/fukazawas/status/1173085592889872386
> RT @guitar_ben: 1人の在日3世の発言で韓国全部嫌いになるなんて言うヤツは差別の理由探してるだけだから。差別主義自白ご苦労さん。 https://t.co/TNc98k4ESX
▷▷▷　　　　　End　　　　　▷▷▷

　3日ほど前になりますか、深澤諭史弁護士の気になるツイートをモトケンこと矢部善朗弁護士（京都弁護士会）と刑裁サイ太がリツイートをしていて、それを取り上げた直後にSSDが壊れました。記事としては中途半端で完成させていないかもしれません。

　モトケンこと矢部善朗弁護士（京都弁護士会）のツイートとして通常運航で、取り立てて記録する必要は感じなかったですが、その関連を深澤諭史弁護士がリツイートしていることに注目し、これは記録の必要性ありと判断しました。

＜＜＜ 2019-09-15（日曜日）20：40 ＜＜＜

