#+TITLE: "富山県高岡市出身という情報のあるバイキング出演の清原博弁護士と平成１１年当時の高岡市近辺での日雇い人夫の仕事"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-15 13:26:45 +0900
FILE_NAME: 2019-08-15-132645_富山県高岡市出身という情報のあるバイキング出演の清原博弁護士と平成１１年当時の高岡市近辺での日雇い人夫の仕事.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 平成９年７月から平成１１年８月１２日まで金沢市での生活  永久開発
記事タイトル名の文字数：54　保存ファイル名の文字数：76

* 富山県高岡市出身という情報のあるバイキング出演の清原博弁護士と平成１１年当時の高岡市近辺での日雇い人夫の仕事
  :LOGBOOK:
  CLOCK: [2019-08-15 木 13:28]--[2019-08-15 木 16:44] =>  3:16
  :END:

＞＞＞2019-08-15（木曜日）13：28＿［これからの記述範囲の開始時刻］＞＞＞

　テレビのバイキングという番組で、出演者の清原博弁護士が４８歳で結婚目前に破談したという打ち明け話をしていました。その場所というのも探偵小説のドラマに出てくるようなお屋敷の豪華な部屋で、ドラマの出演者としてテレビで見てきた人が周りを囲んでいました。

[link:] » 清原博弁護士 - Twitter検索 / Twitter https://t.co/6PbD3WOaVq

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜livedoornews（ライブドアニュース） 日時：2019-08-15 13:34／2016-09-10 10:06 URL： https://twitter.com/kk_hirono/status/1161858798933299201 https://twitter.com/livedoornews/status/774413660605165568
&twitter(1161858798933299201){theme:light}
> 【危惧】高畑裕太さんの再犯の可能性「絶対に食い止めなければ」 \n  https://t.co/wOLyXoIRGp \n   \n  弁護士の清原博氏が「高畑淳子さんがサポートするべき」と指摘。 https://t.co/mxcayEUS6D
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜JCC_NEWS（JCC株式会社） 日時：2019-08-15 13:37／2019-08-15 12:57 URL： https://twitter.com/kk_hirono/status/1161859359636246529 https://twitter.com/JCC_NEWS/status/1161849272855175168
&twitter(1161859359636246529){theme:light}
> 8/15 12:29 フジ バイキング \n  高速道路であおり運転し“強制停車”・暴行行為まで…同一犯か？相次ぐ目撃情報 \n  茨城県の常磐自動車道で起きた悪質なあおり運転と暴行事件について。清原弁護士によると、道路交通法違反（車間距離保持義… https://t.co/TfuQppwHG9
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜viking_fujitv（【フジテレビ公式】バイキング） 日時：2019-08-15 13:39／2019-08-14 11:22 URL： https://twitter.com/kk_hirono/status/1161859838160146434 https://twitter.com/viking_fujitv/status/1161463102191222784
&twitter(1161859838160146434){theme:light}
> 🌈本日8月14日(水)の放送は？🌈 \n  坂上忍52歳が初体験づくし！大人気㊙️ヨガに悶絶？絶品串焼きに舌鼓！🎤大物歌手Sも熱唱🎢大注目スポットでホラン絶叫！坂上は逃亡💰️大金ゲット!? \n  💕速水もこみち&amp;平山あや💕新川優愛ロケバス婚💕遼… https://t.co/DkKt5EJrjS
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamato_lawyer（レイ法律事務所代表弁護士佐藤大和） 日時：2019-08-15 13:39／2019-07-21 13:59 URL： https://twitter.com/kk_hirono/status/1161860016682389504 https://twitter.com/yamato_lawyer/status/1152805162341130243
&twitter(1161860016682389504){theme:light}
> 明日、私は『バイキング』には出演しません。他の弁護士を出演させるようです。元々、芸能法務に強い弁護士とし、約２年間出演を続けていたのであるから、こういうときこそ芸能人側の権利を守る活動をしている私を呼んでくれると信じていましたが、… https://t.co/LN6jwWVaj5
◁◁◁
<hr />

　個人アカウントでリツイートの数も少ないものはリツイートを避けました。バイキングのTwitterアカウントも今日１５日の番組情報は今のところ出していないようです。USJのロケでしたが、私の知るUSJというのは大阪だけでなのですが、今は東京の近辺にもあるのかもしれません。

　それにしても印象的で現実とは思わないような映像と清原博弁護士のお話でした。前にネットで調べたことがあったので年齢も見ていたように思うのですが、４８歳と聞いて割と歳が近く意外でした。

　ちょうど昨日、被害者安藤文さんの年齢のことを考えることがあったのですが、自分が今年１１月で５５歳、６歳年下なので４９歳になるのかと考えていたのですが、書き始めて気がつくと今日がその安藤文さんの誕生日でした。昭和４５年８月１５日生まれです。

　２００６年だと３６歳だったと考えると、モトケンこと矢部善朗弁護士（京都弁護士会）のブログで受けた影響というのも全く重いものだとあらためて考えてしまいます。

```
秋葉原通り魔事件（あきはばら とおりまじけん、英語： Akihabara massacre）とは、2008年（平成20年）6月8日に東京都千代田区外神田（秋葉原）で発生した通り魔殺傷事件。7人が死亡、10人が負傷（重軽傷）した。マスメディアや本件に言及した書籍においては秋葉原無差別殺傷事件と呼ばれることが多い［6］。

［source：］秋葉原通り魔事件 - Wikipedia https://ja.wikipedia.org/wiki/%E7%A7%8B%E8%91%89%E5%8E%9F%E9%80%9A%E3%82%8A%E9%AD%94%E4%BA%8B%E4%BB%B6
```

　ちょっと勘違いしていたことに気が付きました。秋葉原無差別殺傷事件は２００８年６月だったので、この頃もっとも大きくモトケンこと矢部善朗弁護士（京都弁護士会）の影響を受けました。

　少し整理すると、２００６年の１０月に被害者安藤文さんの自宅で彼女の声を聞いたのが最後で、翌年の３月３１日いっぱいで殺人未遂事件としての１５年の公訴時効を迎えました。これが平成１９年であることは、公訴時効の少し前に能登半島地震があったことで確認をしています。

```
能登半島地震（のとはんとうじしん）は、2007年（平成19年）3月25日9時41分58秒（JST）に石川県輪島市西南西沖40kmの日本海で発生した、マグニチュード（M）6.9（気象庁暫定値）の地震。地震空白域とされる地域で発生した。気象庁はこの地震を平成19年（2007年）能登半島地震（英： Noto Hanto Earthquake in 2007）と命名した。以下、時刻は全てJSTで表記する。

［source：］能登半島地震 - Wikipedia https://ja.wikipedia.org/wiki/%E8%83%BD%E7%99%BB%E5%8D%8A%E5%B3%B6%E5%9C%B0%E9%9C%87
```

　あらためて確認をしましたが平成１９年３月２５日とあります。私は長い間３月の１７日か１８日だったと思い込んでいました。公訴時効を迎えたのが４月１日になります。その２週間ほど前だったという感覚は今も変わらず、２５日というのは釈然としないのです。

　日曜日の地震の発生で、羽咋市のアパートで眠っていたところ投げ出されるような衝撃で目が覚めました。

　また、公訴時効を迎える１週間ほど前に金沢地方検察庁に告訴状か告発状を提出し、３月３１日付という返礼書が届いたように記憶にあります。これに似たことは平成２８年だったように思いますが、３月３１日付で不起訴の処分通知書が金沢地方検察庁の検事から届きました。

　あれは告訴状だったように思います。２年目の祭礼委員会であばれ祭りのときに郵送し、翌年の４月過ぎに処分通知書が届いたのです。封筒と書面は撮影し、写真を非常上告-最高検察庁御中_ツイッター（@s_hirono）でも公開してあると思います。

[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「通知書」の検索結果 - Twilog https://t.co/J6EQeY7pTZ

<hr />
[link:] » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「封筒」の検索結果 - Twilog https://t.co/Snnyf4wv3T

<hr />

　十分いけると思っていたのですが、上記２件のキーワードの検索は失敗しました。これでだめだとキーワードの指定での検索は期待できないように思います。時期から特定していった方が早いでしょう。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「処分通知書」の検索結果 - Twilog https://t.co/fUwJn5o6g6

<hr />

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/02/23 00:59％ https://twitter.com/hirono_hideki/status/966703884197445635
&twitter(966703884197445635){theme:light}
> あらためて金沢地方検察庁の不起訴処分通知書の写真。数日前に処分の宮下検事からスマホの形態に電話があった。通知書が届いて電話をすると、移動でいなくなったと言われ、女性検事が対応。
> 
> 2017-04-04_16.07.09.jpg… https://t.co/FYu5wNUKnU  
▶

　TwitterAPIからの取得で「2017-04-04_16.07.09.jpg 2017-04-04_16.07.32.jpg 2017-04-04_16.09.15.jpg 2017-04-04_16.56.08.jpg」という部分が取得しきれていません。

　私の記憶では２０１５年に輪島と横浜が舞台のNHK連続テレビ小説まれ、の放送があって、その翌年から２年間、祭礼委員をつとめたという記憶でした。しかし、今年が２０１９年ということから、私たちの後の祭礼委員が２年の任期を終えたことから計算すると合っていることになります。

　つまり２０１９年、２０１８年が今回任期を終えた祭礼委員になるので、私はその前の２０１７年、２０１６年の任期を務めたということになります。これだと２０１５年がNHK連続テレビ小説まれ、の放送であったことも辻褄があいますが、割と最近のことでも記憶が混同しがちです。

　パソコン内を処分通知書で検索すると「2018-12/2018-12-20_162928＿図書館のパソコン　金沢地方検察庁　処分通知書　平成２９年３月３１日付　告発人廣野秀 樹殿.jpg」という結果が１件だけありました。

　日付も違うしなんのことか理解できなかったのですが、画像ビューアで開いてみると、図書館のパソコンの画面を撮影した写真であったと思い出すとともに理解が出来ました。

　時刻は１４時３９分です。テレビのミヤネ屋で青森で震度４の地震があったという速報が入っていました。ずっと台風関連の放送で、たまに見かける若い女性の気象予報士が台風予想の解説をしていたところでしたが、以前、その女性が青森県の出身と話していたことを思い出しました。

　地震の震度の地図をみると八甲田山のあたりで震度４を観測したようでした。これまで地震情報としては見かけてこなかったように思いますし、それも震源地なのかもっとも震度が高くなっています。台風１０号は今夜の高波が最も警戒されるようです。

　日本海側の能登半島に住んでいると、いきなり台風が上陸する心配はないので、その辺りも安心はできますが、西日本の太平洋側の海沿いに住んでいる人は犠牲者が出る可能性もあるので不安も大きいと思います。

　Twitterの検索で清原博弁護士のことを見直しましたが、ほとんど情報は増えておらず、関心も低いようです。

　午前中、腰の辺りも痛いので横になってウトウトしていたところ、「しまじろうのわお！」の主題歌が変わっているように聴いていたのですが、次にヒルナンデスの放送直前の番宣のような感じで、「いしかわ動物園から」と聞こえてきました。

　時計を見ると５４分とかで、バイキングが始まる時間だと思いチャンネルを変えたのですが、番組が始まらず、少ししてまだ１０時だと気が付きました。テレビの番組表を見たのですが、番組内容に「いしかわ動物園」はなかったものの、一応録画を入れておきました。

　早送りでみましたが、ヒルナンデスに「いしかわ動物園」は出ていませんでした。新潟のロケで、半年ほど前にテレビ番組で初めて知った弥彦神社も出ていましたが、その後はスタジオで蚊の対策のようなコーナー、そのあとは八景島シーパラダイスでした。

　夕方は「となりのテレ金ちゃん」というローカル番組があって、そちらの放送内容もみたのですが、「いしかわ動物園」はありませんでした。前にも触れたことがあると思いますが、平成１０年に仕事の現場としてよく行っていたのが建設中の「いしかわ動物園」でした。

　石川県で唯一の動物園なのでテレビの放送も珍しくはないですが、全体をじっくり見渡せるような放送はこれまで見たことがないのです。特に現場作業の多かったアザラシ館は、建物の姿をはっきり見ていないように思い、少なからず気になっていたのです。完成後はもちろん行ったことがありません。

　ウトウトした状態で聞こえてきたので余計に気になっています。新潟の方も少し聞いた気がするので、八景島シーパラダイスをいしかわ動物園と聞き違えた可能性も考えられますが、違いは大きいように思います。寝ぼけていたのかもしれないです。

　富山県高岡市の周辺というのも建設や建築現場として行ったところです。その前に長距離トラック運転手の仕事でもよく行っていたのですが、その場所に密着するようなことはありませんでした。

　高岡市の方に仕事に行くようになったのは平成１１年の５月以降だった気がします。あるいは６月以降です。それまでは金沢市山科や江沼郡の山中温泉の山奥での仕事が中心でした。

　永久開発で日雇い人夫の仕事を始めたのは平成１１年の２月の２０日過ぎだったと思います。金沢市鳴和の職業安定所からの紹介で、面接に行った翌日には仕事を始めていたかもしれません。仕事を始めてすぐに、金沢地方裁判所から再審請求棄却の決定書が届きました。

　決定の日付は２月２５日か２６日で、夕方に家に帰って目にしたのは、その翌日か翌々日だったと思います。金沢市木越の近くから夕方に安藤健次郎さんに電話をしたことも前に書いたことがあると思います。それ以降、安藤健次郎さんの態度が和らいだとも思います。

　記憶が薄れているので時期の特定も難しくなっているのですが、山中温泉の現場に通うようになってしばらくしてから、安藤健次郎さんにPHSの電話番号を教えられました。これもネットで記述してある部分があると思います。今は記憶が薄れているだけなので、正確なことは書けません。

　まだ普通に雪が降る寒い時期だったと思います。富山県高岡市は岐阜県高山市の方から国道１５６号線がつながっているのですが、ちょうど高山方面から来て、高岡市内に入ってすぐの右手の集落の現場に仕事に行ったことがありました。

　一日だけの仕事だったかもしれませんが、最悪に近く記憶に残る仕事でした。古い大きな民家の玄関先の便所の取り壊し工事で、粉砕した石のようなものを運び出す仕事でした。石には原始時代の大きな貝の化石のようなものが多数こびりつき、不気味なものでした。

　ずいぶん寒かったこともあり、匂いのようなものは気にならなかったように思いますが、悪夢のような仕事として長く記憶に残っています。

　５月か６月以降の高岡市での仕事というのは、国道８号線より氷見市側の現場として記憶にあります。解体作業や廃材の運搬というのも永久開発の日雇い人夫の仕事ではよくあることでしたが、ちょうど高岡市と氷見市の境になる丘の左上のようなところに廃棄物の処理場のようなところがありました。

　ここは、２，３ヶ月ほど前でしょうか、Googleマップで確認をし、見覚えのある会社名として見つけてあります。

[link:] » （株）ヒヨシ 本社 - Google マップ https://t.co/aJZrZx73y3 \n 富山県高岡市東海老坂１２

<hr />

　国道１６０号線というのもちょっと忘れていたのですが、これは石川県七尾市から富山県高岡市の国道８号線につながる道区間の路だと思います。平成４年の傷害・準強姦被告事件の前、私は集中的にこの国道１６０号線を通って、七尾市から関東方面に向かっていました。

　そのあと永久開発の日雇い人夫の仕事では、同じ富山県でも魚津市の現場によく行くようになりました。平成１１年８月１２日に、金沢中警察署の捜査員が待ち構え玉鉾の永久開発で逮捕されたときも、その魚津市の現場から戻ったときのことでした。

　高岡市のことを記述するきっかけとなった清原博弁護士について、調べておきたいと思います。

```
清原 博（きよはら ひろし、1970年11月20日［1］ - ）は、国際弁護士。埼玉弁護士会所属（No.35061）。専門分野は国際取引法、国際金融法、アメリカ法、航空・宇宙法、知的財産法。

芸能事務所のシンクバンクに所属し、コメンテーターとしてテレビ・ラジオなどの出演も多い。


目次
1	来歴
2	メディア出演
3	著書
4	脚注
5	外部リンク
来歴［編集］
富山県出身。1989年、富山県立高岡高等学校卒業。1994年、東京外国語大学外国語学部英米学科卒業。

1995年、2度目の受験で［2］司法試験に合格。司法修習を修了後、1998年、裁判官に任命（東京地方裁判所に所属）。

2000年、検察官に任命（法務省民事局に配属）。同年に裁判官・検察官を退職し［3］、サンフランシスコへ渡米。

2002年、ゴールデンゲート大学ロースクール（法学修士課程）卒業、法学修士号（LL.M.）取得。 LLM卒業式にて成績優秀者として表彰された。

2003年、ニューヨーク州司法試験に合格し、ニューヨーク州弁護士登録。 2004年、カリフォルニア州司法試験に合格し、カリフォルニア州弁護士登録。ゴールデンゲート大学ロースクール（法学博士課程）前期課程修了［4］［5］。カリフォルニア州の事務所にて勤務する。

2007年に帰国し、むさし国際法律事務所を開業、2013年、カンボジア政府法律顧問に就任、むさし国際法律事務所カンボジア支所を開設［6］。2016年、気象予報士試験に合格［7］。

防災士資格も所持している。

2019年1月12日放送の「芸能界特技王決定戦 TEPPEN2019」（フジテレビ）において体脂肪率7.5％、48kgのバーベルベンチプレスを41回を記録した。

［source：］清原博 - Wikipedia https://ja.wikipedia.org/wiki/%E6%B8%85%E5%8E%9F%E5%8D%9A
```

　当然かもしれませんが、このwikipediaだけで、けっこう情報が揃っていました。今回始めて見たと思ったのは「2000年、検察官に任命（法務省民事局に配属）」の部分です。検事が色んな所に出向をする話は聞いていますが、法務省民事局に配属とあります。

　富山県出身とだけありますが、高校が富山県立高岡高等学校とあります。名前からして優秀な進学校というイメージですが、富山県の高校の事情はなにもしりません。ただ、進学校であれば、富山県内全域から集まってくると思いますし、富山県は人の生活圏自体が狭いと思います。

　石川県の金沢市から国道８号線でも新潟県との県境まではそう離れていないと思いますし、立山連峰が広がっているので、人が住む場所も限られてくると思います。立山連峰などに遊びに行ったことはないですが、トラックの仕事ではおおよそ全域を巡っているように思います。

[link:] » 母校の井波中学校のみなさん、ありがとうございました　(⌒・⌒)ゞ：筋肉弁護士ヒロ　あきらめるな！そのとき自分が変わる：So-netブログ https://t.co/AsNk39PavF

<hr />

　ブログ名やサブタイトルに名前はないですが、清原博弁護士本人のブログのようです。そういえば前に一度見かけていたような気がしましたが、すぐにすっかり忘れていたようです。検索結果で見つけた記事には井波中学校とあります。

　富山県の井波がどの辺りかすぐにはわからないですが、井波というのは木彫りの彫刻で有名であったように思います。これまで何度かテレビで見てきましたし、比較的最近も鶴瓶の家族に乾杯で見たように思います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「井波」の検索結果 - Twilog https://t.co/wBHyiyPE9H

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-15 16:36／2019-06-03 20:10 URL： https://twitter.com/kk_hirono/status/1161904357069078529 https://twitter.com/hirono_hideki/status/1135504022125735936
&twitter(1161904357069078529){theme:light}
> 鶴瓶の家族に乾杯「V6の三宅健と富山県南砺市井波ぶっつけ本番旅！」 \n   \n  2019年6月3日（月）  19時30分～20時42分  の放送内容 https://t.co/LD0LxpvQOC
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-15 16:36／2019-06-03 20:11 URL： https://twitter.com/kk_hirono/status/1161904373795942405 https://twitter.com/hirono_hideki/status/1135504373159645187
&twitter(1161904373795942405){theme:light}
> ステキな家族を求めて、笑福亭鶴瓶とV6の三宅健が「井波彫刻」で有名な富山県南砺市井波でぶっつけ本番旅！二人の旅はのどかな田園風景から始まる。 https://t.co/LD0LxpvQOC
◁◁◁
<hr />

　確実な自信は持てていなかったのですが、間違いはなかったようです。やはり「井波彫刻」とあります。大きな寺院も番組では撮影地になっていました。富山県西部は他にも大きな寺院がいくつかあるようです。

[link:] » 井波 - Google マップ https://t.co/PyfJu4WZjr

<hr />

　Googleマップで場所を確認しましたが、一部だけ国道１５６号線に隣接し、高岡市内から来た反対側は大きな山ばかりが広がっているように見えます。だいぶん自然豊かなところで清原博弁護士は育ったようです。都会の方からの転勤の家庭を想像していました。

＜＜＜2019-08-15（木曜日）16：44＿［これまでの記述範囲の終了時刻］＜＜＜

