#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "参考資料／弁護士業界の現状／第三者委員会／塚原夫妻パワハラ認定されず"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-11 12:51:39 +0900
FILE_NAME: 2018-12-11-125139_塚原夫妻パワハラ認定されず.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  第三者委員会 パワハラ 金沢市天神町 金沢市場輸送の市内配達
記事タイトル名の文字数：34　保存ファイル名の文字数：35

#contents

* テレビのバイキング（２０１８年１２月１１日放送・石川テレビ）「新展開！塚原夫妻　パワハラ認定されず」

　なにか塚原夫妻の問題で処分のようなものが出たことは、昨日あたりのテレビで見ていたのですが、第三者委員会という言葉は見ていませんでした。短いテレビニュースというかたちで見てきたと思うのですが、本格的に取り上げているのはバイキングが初めてです。

　時刻は１２時５８分ですが、今も同じテーマでバイキングの放送は続いています。今日は番組の最初に怒りの４連発というようなコーナーがあったので、それに１０分ほど時間があったように思いますが、少なく見ても４０分以上は、このテーマで放送は続いているようです。

　バイキングが独自に大きく取り上げてきた社会問題としては他に、日大アメフト部の違法タックル問題がありますが、それと共通するのも第三者委員会です。おそらく本日のバイキングの放送をみなければ、塚原夫妻のパワハラ問題と第三者委員会のことは知らないままだった気がします。

　バイキングの画面に出る見出しのような字幕は１３時４分の時点で、「新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？」となっています。この場面を見ているだけでは、やはり第三者委員会の存在、関与というのは見えてきません。

　時刻は１８時４８分です。グッディが始まった頃に出掛け、１７時過ぎに家に戻ってきました。宇出津新港の回転寿司で食事をした後、ゆっくりと時間を掛けて買い物をしていました。別の店になりますが、長靴と毛布も買ってきました。

　家に戻ってからテレビはつけていません。グッディを録画して出掛けましたが、もちろんそれもまだ見ていません。本当はミヤネ屋を録画するつもりだったのですが、安藤優子さんと坂上忍さんとの会話で、宮川選手の代理人山口弁護士と聞いたので、録画の選択をしました。

　まさかとは思いましたが、山口貴士弁護士のことが思い浮かび、他に山口という弁護士の名前も思い浮かばなかったので、あとで確認できるように録画しました。体操の宮川選手の代理人弁護士の名前だけならネットで探し出せるかもしれません。

　それでも宮川選手の代理人弁護士というのは、今まで聞いたことがなかったようにも思いました。そもそも裁判や訴訟をしているわけではないような気もしました。体操選手としての地位保全のための弁護士なのかもしれないですが、仮にそうだとしても、それを代理人弁護士というのは気になりました。

　バイキングの放送の画面を撮影したスマホの写真は、数を削って非常上告-最高検察庁御中_ツイッター（@s_hirono）のツイートにアップロードしました。数を削りましたが、それでもけっこうな数です。ご説明にさきだち、リツイートとしてご紹介しておきたいと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:11／2018-12-11 18:39 URL： https://twitter.com/kk_hirono/status/1072433775248859136 https://twitter.com/s_hirono/status/1072425689012469760
&twitter(1072433775248859136){theme:light}
> 2018-12-11_134551＿テレビの画面・直撃LIVEグッディ！.jpg https://t.co/y51qAWcyno
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:11／2018-12-11 18:39 URL： https://twitter.com/kk_hirono/status/1072433792164524032 https://twitter.com/s_hirono/status/1072425656288448512
&twitter(1072433792164524032){theme:light}
> 2018-12-11_134538＿テレビの画面・最新ニュース言いたい放題　バイキングｘグッディ.jpg https://t.co/WTuWHFWr1V
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:12／2018-12-11 18:39 URL： https://twitter.com/kk_hirono/status/1072433816499822593 https://twitter.com/s_hirono/status/1072425623602237440
&twitter(1072433816499822593){theme:light}
> 2018-12-11_134522＿テレビの画面・最新ニュース言いたい放題　バイキングｘグッディ　体操パワハラ認定はなし・・・第三者委なぜ判断.jpg https://t.co/PxxbfJA4UO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:12／2018-12-11 18:39 URL： https://twitter.com/kk_hirono/status/1072433845440573442 https://twitter.com/s_hirono/status/1072425590643482624
&twitter(1072433845440573442){theme:light}
> 2018-12-11_134515＿テレビの画面・最新ニュース言いたい放題　バイキングｘグッディ.jpg https://t.co/yAPN6nbxOe
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:12／2018-12-11 18:39 URL： https://twitter.com/kk_hirono/status/1072433868228255744 https://twitter.com/s_hirono/status/1072425557743284224
&twitter(1072433868228255744){theme:light}
> 2018-12-11_134352＿テレビの画面・最新ニュース言いたい放題　バイキングｘグッディ.jpg https://t.co/AfLbWp5ZRb
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:12／2018-12-11 18:39 URL： https://twitter.com/kk_hirono/status/1072433902608941057 https://twitter.com/s_hirono/status/1072425521542254592
&twitter(1072433902608941057){theme:light}
> 2018-12-11_134316＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　この辺りで貴ノ岩を取り上げなかったと　ゲストの大至さんも.jpg https://t.co/gUUeDPF6Fe
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:12／2018-12-11 18:38 URL： https://twitter.com/kk_hirono/status/1072433937664929792 https://twitter.com/s_hirono/status/1072425488520540160
&twitter(1072433937664929792){theme:light}
> 2018-12-11_134250＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　明日のバイキング.jpg https://t.co/FHb9xG6xUV
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:12／2018-12-11 18:38 URL： https://twitter.com/kk_hirono/status/1072433959580114944 https://twitter.com/s_hirono/status/1072425455641354241
&twitter(1072433959580114944){theme:light}
> 2018-12-11_134228＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　協会に相談しても問題の解決に至らないと.jpg https://t.co/JgcFoTw1gN
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:12／2018-12-11 18:38 URL： https://twitter.com/kk_hirono/status/1072433980333535233 https://twitter.com/s_hirono/status/1072425422514806784
&twitter(1072433980333535233){theme:light}
> 2018-12-11_133600＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　特別調査委員会とは.jpg https://t.co/wxqWiLCalC
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:12／2018-12-11 18:38 URL： https://twitter.com/kk_hirono/status/1072434004668887040 https://twitter.com/s_hirono/status/1072425389589495808
&twitter(1072434004668887040){theme:light}
> 2018-12-11_133543＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　協会通さず報道に発信問題視.jpg https://t.co/2I9ZSIUWdn
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:12／2018-12-11 18:38 URL： https://twitter.com/kk_hirono/status/1072434028849102848 https://twitter.com/s_hirono/status/1072425356513173505
&twitter(1072434028849102848){theme:light}
> 2018-12-11_133210＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　双方に処分の可能性アリ！？.jpg https://t.co/6ipzu0ZXcW
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:38 URL： https://twitter.com/kk_hirono/status/1072434071895191552 https://twitter.com/s_hirono/status/1072425323562700801
&twitter(1072434071895191552){theme:light}
> 2018-12-11_133023＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　誰だかわからないゲストコメンテーター.jpg https://t.co/kzwtUNC3yl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:38 URL： https://twitter.com/kk_hirono/status/1072434094296981504 https://twitter.com/s_hirono/status/1072425286854152192
&twitter(1072434094296981504){theme:light}
> 2018-12-11_132918＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　立っている柳原可奈子.jpg https://t.co/BvzrgPM3zO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:37 URL： https://twitter.com/kk_hirono/status/1072434114979119106 https://twitter.com/s_hirono/status/1072425253647908864
&twitter(1072434114979119106){theme:light}
> 2018-12-11_132554＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　高須克弥氏　相手が感じたらパワハラ.jpg https://t.co/dqnervAF4O
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:37 URL： https://twitter.com/kk_hirono/status/1072434139373191170 https://twitter.com/s_hirono/status/1072425221011984384
&twitter(1072434139373191170){theme:light}
> 2018-12-11_132044＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　弁護士・元裁判官　清原博.jpg https://t.co/Chat19P2Us
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:37 URL： https://twitter.com/kk_hirono/status/1072434169207246848 https://twitter.com/s_hirono/status/1072425135758557184
&twitter(1072434169207246848){theme:light}
> 2018-12-11_131928＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　第三者委員会が前提とするパワハラの定義.jpg https://t.co/xHfIKCz8Jj
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:37 URL： https://twitter.com/kk_hirono/status/1072434190782775296 https://twitter.com/s_hirono/status/1072425103248580609
&twitter(1072434190782775296){theme:light}
> 2018-12-11_131458＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　座っている柳原可奈子.jpg https://t.co/KiXtiuRpBX
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:37 URL： https://twitter.com/kk_hirono/status/1072434209162215425 https://twitter.com/s_hirono/status/1072425070792974336
&twitter(1072434209162215425){theme:light}
> 2018-12-11_131449＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　代理人弁護士に対し第一声が・・・.jpg https://t.co/uQi5vnLLkm
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:37 URL： https://twitter.com/kk_hirono/status/1072434233220698112 https://twitter.com/s_hirono/status/1072425037016244224
&twitter(1072434233220698112){theme:light}
> 2018-12-11_131421＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　座っている柳原可奈子.jpg https://t.co/ZEupKrKXpa
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:37 URL： https://twitter.com/kk_hirono/status/1072434256067072001 https://twitter.com/s_hirono/status/1072425004162256897
&twitter(1072434256067072001){theme:light}
> 2018-12-11_122620＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　立っている柳原可奈子.jpg https://t.co/J2OMa63DyM
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:36 URL： https://twitter.com/kk_hirono/status/1072434283791429632 https://twitter.com/s_hirono/status/1072424967176896513
&twitter(1072434283791429632){theme:light}
> 2018-12-11_122434＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　弁護士・元裁判官　清原博.jpg https://t.co/SNvN4hj4Ui
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:13／2018-12-11 18:36 URL： https://twitter.com/kk_hirono/status/1072434308869169152 https://twitter.com/s_hirono/status/1072424930485112832
&twitter(1072434308869169152){theme:light}
> 2018-12-11_122410＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？　第三者委員会　５人の弁護士により構成.jpg https://t.co/7PVuKHYjxg
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:14／2018-12-11 18:36 URL： https://twitter.com/kk_hirono/status/1072434375663456261 https://twitter.com/s_hirono/status/1072424897765351425
&twitter(1072434375663456261){theme:light}
> 2018-12-11_120608＿テレビの画面・新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？.jpg https://t.co/iaa07mAfR4
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-11 19:14／2018-12-11 18:36 URL： https://twitter.com/kk_hirono/status/1072434405476589574 https://twitter.com/s_hirono/status/1072424865221754885
&twitter(1072434405476589574){theme:light}
> 2018-12-11_115516＿テレビの画面・バイキング・今日のラインナップ　パワハラ女子体操　塚原夫妻に処分なし！・緊急取材　元貴ノ岩　故郷モンゴルは厳しい声！？.jpg https://t.co/E7mHgsOU8h
◁◁◁
<hr />

　撮影していたので気がつくことが出来たのですが、１２時６分の時点で、「新展開！塚原夫妻　パワハラ認定されず　体操協会「不適切だったが・・・」宮川選手は？」という見出しになっていました。これがそのまま１３時４３分まで続いたわけですから驚きました。

　本当は他に取り上げておきたいこと、すぐにでも書いておきたい告発の事実関係もあるのですが、総合的に考えてこの体操のパワハラ問題を新たなエントリーとして取り上げました。ちょうど強制的でしたが、前回のエントリーを打ち切った直後のタイミングでもありました。

　もともとパワハラの問題として気に掛かることもあったのですが、それが第三者委員会と結びついたので即決しました。微妙にシャッターのタイミングが遅れ撮影できなかったのですが、テレビの画面右下に「弁護士だけで５人」というような小見出しも出ていました。

　バイキングは、弁護士について問題意識を持ち、それを直接コメンテータの弁護士にぶつけることもあるので、番組を注目し視聴する動機にもなっています。他に問題性を感じることも多々あるのですが、そういうこともひっくるめた上で、いろいろと参考にしています。

　前にも一度あったことですが、決まっていたテーマをその場の成り行きで取り上げませんでした。前回は自殺した女子中学生の話題でした八王子だったようにも思います。

　時計は１９時３３分になっています。３０分からだと思いますが、NHKで「わが心の大阪メロディ」という歌番組が始まり、１曲目が「大阪ラプソティ」でした。昭和５１年の曲ということです。私がよく聴いたと記憶にあるのは昭和６０年のことです。中西運輸商にいたときのことです。

　テレビの中継の背景に「スーパー玉出」という大きなネオンの看板が出ていました。もう１０日ほど経つように思いますが、経営者が逮捕されたというニュースを取り上げました。スーパーの方は転売されたという話も見かけたので、正確には元経営者になるのかもしれません。

　銭湯のテレビで見たことを書きましたが、結局あれ以外に報道はみませんでした。話題性も法律的な問題点もありそうに思っていただけに不思議でした。

　大阪とか関係なさそうな気がしますが、荻野目洋子の「ダンシングヒーロー」をやっていて、曲紹介の字幕に昭和６０年と出ていました。スケバン刑事というのも同じ頃だったと思います。

　今のNHKの朝ドラ「まんぷく」のオープニングの曲がドリカムだと知って驚きました。ドリカムがすごい人気だったのはずいぶん前のことで、ここ数年は名前を聞いたこともなくすっかり忘れていたように思います。

［link：］ 出場歌手｜第69回NHK紅白歌合戦 https://www.nhk.or.jp/kouhaku/artist/

　気になったので調べてみましたが、今年の紅白の出場歌手にドリカムは見当たらないようです。

```
福田は１１月２３日、福島・白河市内でのコンサートの昼の部終了後に体調不良を訴え、楽屋で大量に吐血。夜の部を中止し、救急搬送された。胃と食道の接合部に亀裂が入っていたことが判明し、クリップで止血する応急処置を行った。２５日に「ＮＨＫのど自慢」に生出演したが、出演後に故郷・盛岡市に戻って入院。「急性胃粘膜病変にともなう黒色吐物」と診断され、１０日間の治療が必要とされた。

［source：］大量吐血の福田こうへい、復帰コンサートで熱唱「完全復活です」（スポーツ報知） - Yahoo!ニュース https://headlines.yahoo.co.jp/hl?a=20181210-00000131-sph-ent
```

　元気そうに三波春夫の大阪万博のテーマ曲を歌っていたので、別人かとも思ったのですが、調べたところ、やはり最近大量吐血でニュースになっていた演歌歌手の人でした。番組では病気について触れられることもなかったようです。頑張る人だなって思いました。

　先ほどは少しだけでしたが、曲の合間にミスターオクレが出ていました。１，２年前にもテレビで少し姿を見ましたが、NHKというのも意外です。若い世代の人は全然知らない人が多そうですが、一時期の知名度は相当高かったと思われます。

　今は、May.Jが「セクシャルバイオレットNo.1」を歌っています。桑名正博の曲ですが、そういえば妻だったアンルイスのこともすっかり忘れていたことに気が付きました。歌番組はほとんどみませんが、NHKの歌謡番組だけは割とみています。

```
「オレたちひょうきん族」（フジテレビ）のコーナー「ラブ・ユー・貧乏」で「何人トリオ」（前田政二、村上ショージ、Mr.オクレの3人）として出演し、全国区でブレイクした。

［source：］Mr.オクレ - Wikipedia https://ja.wikipedia.org/wiki/Mr.%E3%82%AA%E3%82%AF%E3%83%AC
```

　何人トリオという芸名は知らなかったように思います。吉本新喜劇の所属というのも今夜初めて知り、意外に感じました。当時のビートたけしと同じ東京人というようなイメージがなんとなくありました。替え歌になっていた「ラブ・ユー・東京」のイメージが強かったのかもしれません。

2018-11-08_115512＿テレビの画面・バイキング・今日のニュースバイキング・悲痛　八王子・中２自殺　遺書に「無視は辛かった」　学校側　当初「いじめなし」なぜ一転？.jpg http://hirono2014sk.blogspot.com/2018/11/2018110819192018-11-081018252018-11.html#20181108115512

2018-11-08_133218＿テレビの画面・バイキング・悲痛　八王子・中２自殺　遺書に「無視は辛かった」　学校側　当初「いじめなし」なぜ一転？.jpg http://hirono2014sk.blogspot.com/2018/11/2018110819192018-11-081018252018-11.html#20181108133218

　自分のデータベースで調べました。上記に２つ取り上げましたが、同じテーマでは最初と最後の撮影になるかと思います。

　最初の方で今日のニュースとして「注目　米・中間選挙トランプ大統領強気な発言のワケ」「悲痛　中２女子自殺　学校側のずさんな対応」「なぜ？　世田谷の保育所　保育士ら１８人一斉退職」の３つの項目が紹介されています。

　私の記憶でボツにされたのは、そのときも大相撲の話題だったように思います。スタンバイしていたゲストに申し訳ないというような陳謝の言葉もありました。だが、この今日のニュースを見ると、飛ばされたかボツにされたのは、「世田谷の保育所」だった可能性がありそうです。

　また、そのときは、司会者の坂上忍さんが、自分が子役だった頃のいじめや辛い思いを重ね合わせてしまう、というような強い思い入れを明らかにしていたので、ついついやってしまったことなのかと思っていたのですが、本日の場合は、通常運行であることをゲストにふる所作もありました。

[link:] » バイキング - Twitter検索 https://t.co/dTbt7IsrHH

<hr />

　Twitterの検索をやってみました。バイキングで検索すると文字通りの食べ放題サービスが出てくることもあるのですが、今回は特に番組に関するツイートが少ないのか、数日前のツイートも目立ちます。視聴率も良いらしいので、前から不思議に思っていました。

[link:] » バイキング　貴ノ岩 - Twitter検索 https://t.co/tAiKk8H7Li

<hr />

　絞り込みのように「貴ノ岩」というワードを追加しましたが、結果はほぼ同じで、さらに数日前のツイートばかり表示されるようになりました。１２月６日が多いようです。

　検索結果のタイムラインを下げていくと、２０１７年のツイートが多くなりました。この検索結果は、リツイートやあるいは「いいね」でも、最新のツイートとしてタイムラインの最初に表示させていく仕組みになっているようには考えてきました。正確なアルゴリズムは不明ですが。

* テレビがきっかけで開いた石川県トラック協会のホームページと、市場急配センターの確認したかった会員名簿について

　時刻は２１時５０分です。テレビをNHKから北陸朝日放送にチャンネル変更したタイミングで、県トラック協会の理事だったと思いますが、そのような人物がお話をしていました。県トラック協会とありましたが、石川県トラック協会のことだと思います。

　石川県トラック協会は、私がトラック運転手をしていた平成４年以前から存在は知っていました。初めに市場急配センターのホームページをみた平成１５年頃も、石川県トラック協会に関するネット上の情報は見かけていました。被告発人松平日出男が役員か役職だったかもしれません。

　先日も奥能登地区のトラック協会の会員名簿のようなものを取り上げたように思います。宇出津のタクシー会社や建設会社も会員のようで、それもけっこう意外なことでした。

[link:] » 一般社団法人 石川県トラック協会 https://t.co/78KmU3TvYd

<hr />

```
ディスクロージャー
［情報公開対象文書］


1. 定款

2. 役員名簿

3. 会員名簿

4. 平成29年度事業報告

5. 平成29年度正味財産増減計算書内訳表

6. 平成29年度貸借対照表内訳表

7. 平成30年度事業計画

8. 平成30年度収支予算書

9. 国民保護に関する業務計画

［source：］協会の概要 http://www.ishitokyo.or.jp/about.php
```

　上記の石川県トラック協会のホームページを見たところ、会員目簿は見当たりません。市場急配センターや被告訴人HTNが社長をする運送会社が会員であることを確認しておきたいと思い検索しました。この検索は少なくとも２０１０年４月にTwitterを始めてから初のことかと思います。

* エディタEmacsでの日本語ブックマークの作成と、同時期編集、切り替え進行での書面（エントリー）の作成について

　時刻は２３時２１分です。夕食を済ませ、洗い物を済ませてパソコンの前に戻ってきました。テレビのチャンネルは北陸朝日放送の報道ステーションのままになっていたので、テレビ金沢のzeroに変更しました。まだ番組が始まっていないことも期待していたのですが、予想外に時間が過ぎていました。

　夕食は少し離れた台所で済ませてきました。メインは昨夜の残りの香箱カニの味噌汁でした。Aコープ能都店で半額になっていたのを買ってきた２杯のカニでした。他に入れたのは大根だけです。朝も食べたので今回も３食分でした。量的にはあと１食分でもよかったぐらいです。

　台所に行く前にこの文書を編集中のエディタEmacsで、ブックマークを作成していました。余りやった憶えがなかったので、出来るのかはっきりとはわからなかったのですが、日本語でブックマークを作成しました。キーワードはそのまま「バイキング」です。

　これまでEmacsのブックマークはｊやｍなどの半角のローマ字１つで済ませていました。１つのファイルを開き直すぐらいならそれで十分用が足りたからです。

　小見出しを２つ追加しました。バイキングの本日１２月１１日の放送については、ほぼ書いておきたいことを書き記したかと思うのですが、体操協会のパワハラ問題については、金沢市天神町と関連付けて書き記しておきたいことがあります。また戻ってきます。


