#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "告発に至る経緯／弁護士による影響・阻害要因／小倉秀夫弁護士（東京弁護士会）／Twitterへの書き込みができなくなったという小倉秀夫弁護士とFacebookの埋め込み"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-17 18:43:11 +0900
FILE_NAME: 2018-12-17-184311_Twitterへの書き込みができなくなったという小倉秀夫弁護士とFacebookの埋め込み.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  Twitter 小倉秀夫弁護士 Facebook
記事タイトル名の文字数：83　保存ファイル名の文字数：67

#contents

* 最初にやってみたFacebookの埋め込み

<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fhideo.ogura%2Fposts%2F10156914586609732&width=500" width="500" height="174" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>

　上記にFacebookの埋め込みを行いましたた、HTMLのコードに本文の文字列は含まれていないようです。これがFacebookにログインしていない状態で閲覧できるのか、仮にブロックされた場合にも表示されるのかは不明です。

　余りやった憶えもないのですが、Facebookも投稿を特定できるので、普通の引用は出来るかと思います。やってみないとわからないのでやってみます。

```
12月8日 17：19 · 
法律家のextra-judicialな発言を採り上げるのであれば、余命三年日記系の大量懲戒請求問題と、岡口分限裁判を採り上げるべきだとは思うんだけど。

［source：］Hideo Ogura - 法律家のextra-judicialな発言を採り上げるのであれば、余命三年日記系の大量懲戒請求問題と、岡口... https://www.facebook.com/hideo.ogura/posts/10156914586609732
```

　Facebookにログインしていない状態のブラウザでページを開いてみましたが、単体の記事の閲覧は出来ました。以前は出来なかったように思うのですが、それもFacebookを余り使わないできた理由の１つです。

　Facebookの埋め込みはHTMLのソースコードがiframeタグになっています。これも以前は使えないブログがあったように思いますが、はてなブログでは表示が出来たので使えるようです。

　FacebookはTwitterでもブロックはしないと公言していたので、その意味、その点では稀に見るほど信頼の置ける、パブリックなアカウントです。だからこそTwitterを停止しているのは残念なことです。

　先日、Twitterの書き込み禁止について調べたのですが、Twitter社から指摘された特定（あるいは複数？）のツイートを削除すれば、すぐにでも元の状態に戻れるようです。後で書いておきたいと思いますが、小倉秀夫弁護士は不服の表明を行っています。

* 小倉秀夫弁護士のFacebookアカウント

［link：］ Hideo Ogura https://www.facebook.com/hideo.ogura?fref=nf

　日本語ではなくローマ字を使っているようです。ヨーロッパ旅行にも行くらしいので英語はある程度堪能であり、海外や外国人にも友人、知人がいる可能性はありそうです。したがって、日本語のみのアカウント名では不都合もあるのかもしれません。

　Facebookの場合、アカウント名と読むべきかユーザ名と呼ぶべきかわかっていないのですが、Twitterだと＠のユーザ名と「プロフィールの名前」が別物となっています。次が小倉秀夫弁護士のTwitterアカウントになります。

[link:]  小倉秀夫(@Hideo_Ogura)さん | Twitterからの返信付きツイート https://twitter.com/Hideo_Ogura/with_replies

　@Hideo_Oguraがユーザ名になるかと思います。APIでTwitterの仕様をみるとスクリーンネームとなっているのですが、API以外でこれを見ることはなく、普通に通じなさそうなのでユーザ名としています。

　Twitterの場合、ユーザ名は英語のみで文字列を区切る記号としてハイフンは使えず、アンダーバーのみが使えるはずです。小倉秀夫弁護士もその決まりに従ったのだと思いますが、Facebookでは半角スペースが使えるようです。

　Facebookの自分のアカウントの設定を確認したところ、「名前」が廣野秀樹、「ユーザーネーム（ユニークURL）」が https://facebook.com/hirono.hideki となっていました。

　どうもFacebookの名前というのはTwitterのプロフィールの名前とほぼ同じ扱いとなるようです。それならば半角スペースが含まれていても悪影響は少ないと思いますが、プログラムの処理となるとバグの要因となるものです。あえて使っているのかと勘ぐります。

* 「MeToo運動は、ある種の憎悪を正当化する運動と受け取られている側面があるので」という2018年12月10日の小倉秀夫弁護士のFacebook投稿

```
12月10日 13：47 · 
#MeToo運動は、ある種の憎悪を正当化する運動と受け取られている側面があるので、それはそれとして、刑法犯に踏み出さないようにクールダウンするような配慮が場の提供者には求められるのでしょうね。

［source：］Hideo Ogura - #MeToo運動は、ある種の憎悪を正当化する運動と受け取られている側面があるので、それはそれとして、刑法犯... https://www.facebook.com/hideo.ogura/posts/10156919356809732
```

　どうも山口貴士弁護士のツイートのURLを引用した投稿のようです。数日前に見た山口貴士弁護士と伊藤和子弁護士のTwitterでのやりとりについても、調べたり、記録化しておきたかったのですが、なかなか手が回りません。

　同じく手が回らないという理由で、伊藤和子弁護士についても中途半端にしか取り上げてきていないと思いますが、性犯罪や女性の権利擁護については、特別な存在感を放ち、実績のようなものもあるらしい女性弁護士です。

　もう一つ伊藤和子について注目すべき点は、小倉秀夫弁護士とは司法修習が同期で、同じく同期の岡口基一裁判官の分限裁判には、弁護団の一員のようなかたちで参加し、記者会見にも参加しています。テレビニュースなどにも取り上げられているかと思います。

　これまで小倉秀夫弁護士が強いこだわりをみせ、独自の意見表明を行ってきたのは、痴漢対策としての女性専用車両への批判です。これまで、まとめ記事も制作しているかと思いますが、MeTooについてはやっていないかもしれません。

　なお、この小項目の見出しというかタイトル名には本来、#MeTooとハッシュタグになっているのですが、将来、データ処理でファイル名などとして利用する可能性もあるので、半角の特殊文字は避けておきました。

　最近はLinuxでもファイル文字に半角の特殊文字がエスケープ無しで使えるようになっているのですが、lsコマンドでファイル名を確認すると、シングルクォートで囲まれています。プログラムに対策を施せばなんとかなりそうですが、まだやっていないので使わないようにしています。

* 「自動運転自動車にAI機能を搭載した結果、弁護士バッジをつけている歩行者を見つけたら高速でその歩行者めがけて突進」という小倉秀夫弁護士の2018年12月10日のFacebook投稿

```
12月10日 2：43 · 
自動運転自動車にAI機能を搭載した結果、弁護士バッジをつけている歩行者を見つけたら高速でその歩行者めがけて突進していくようになった場合、メーカーは免責されるべきですかね。

［source：］Hideo Ogura - 自動運転自動車にAI機能を搭載した結果、弁護士バッジをつけている歩行者を見つけたら高速でその歩行者めがけて... https://www.facebook.com/hideo.ogura/posts/10156918124419732
```

　これまでタイムラインを遡りながらみてきた小倉秀夫弁護士のFacebook投稿ですが、Twitterのような人をくったり、小馬鹿にした、非常識な投稿は見当たらなかったのですが、これはかなり変わった内容であるものの脈絡が不明です。

　誰かに向けた皮肉や自虐ネタでもなさそうです。2,3週間ぶりに思い出したのは、元検察幹部の弁護士が起こしたブレーキの誤操作ともいわれる死傷事故です。検察幹部というのは東京地検特捜部長だったかもしれません。その弁護士の名前も思い出せなくなっています。

　12月10日に何があったのか思い出せないですが、どうも小倉秀夫弁護士は、逆恨みの報復手段として無差別に弁護士のみを殺傷させるため、AI搭載機能のプログラムを改変し悪用するということを想定しているようです。

　そういえば、渋谷のハロウィーンで軽トラを横転させた事件で、監視カメラで警察が被疑者の自宅まで追跡し逮捕したというニュースがありました。ちょっと手軽に調べてみたいと思います。

[link:] 2018-12-09_224654＿テレビの画面・Mr．サンデー・軽トラ横転事件　スピード逮捕　警視庁「SSBC」驚きの捜査能力！.jpg  http://hirono2014sk.blogspot.com/2018/12/2018121512482018-12-081858082018-12.html#20181209224654

　ちょっと忘れていたようなものも一緒に出てきたので、ご紹介をしておきたいと思います。

[link:] 2018-10-30_122719＿テレビの画面・バイキング・怒　渋谷で若者らが”暴徒化”！軽トラ囲み横転　清原博弁護士「騒乱罪を適応しても良い事案」.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181030122719

　12月9日がMr.サンデーの放送日のようなので、日曜日になりますが、今日は月曜日なので12月10日の小倉秀夫弁護士の投稿というのは、ちょうど一週間前のことだったようです。

　そういえば、昨日あたりに制作した「次男.*執行猶予」というまとめ記事は、検索結果がゼロでした。ゼロでは話しにならず、意味不明になるので、にわかに私のアカウントから検索結果の記事を投稿し、体裁を取り繕いました。

* 「次男.*執行猶予」と正規表現で検索した弁護士ツイートのまとめ記事、弁護士のものは該当なしという記録

```
[10033]  % dp -p |grep 次男
[link:] 2018年04月27日14時54分の登録： REGEXP：”矢田（次男）？弁護士”／データベース登録済みツイート：2018年04月27日14時54分の記録：ユーザ・投稿：4／30件 http://hirono2014sk.blogspot.com/2018/04/regexp201804271454430.html
[link:] 2018年04月29日11時27分の登録： REGEXP：”矢田（次男）？弁護士”／データベース登録済みツイート：2018年04月29日11時26分の記録：ユーザ・投稿：4／30件 http://hirono2014sk.blogspot.com/2018/04/regexp201804291126430.html
[link:] 2018年12月17日02時09分の登録： REGEXP：”次男．＊執行猶予”／データベース登録済みツイート：2018年12月17日02時09分の記録：ユーザ・投稿：1／2件 http://hirono2014sk.blogspot.com/2018/12/regexp20181217020912.html
```

　矢田次男弁護士の検索が出てきたのは意外な結果でした。TOKIOの山口達也氏の記者会見に同席していたジャニーズ事務所の顧問弁護士で、僅かな情報でしたが、日馬富士の代理人弁護士という情報もネットで見かけたように思います。余りはっきりしない情報です。

　次が、検索対象のテキストファイルになります。出力は最後の10行に絞り込んでいます。弁護士関連のアカウント数が480件、1つのテキストファイルに対応させたアカウントのツイートの総数が現時点で3099738件となっています。310万弱です。

```
Diginnos-PC:~/git/tweet-log_2015
[10038]  % find 2017_法務検察当局宛て注目参考資料弁護士のリスト化ツイート* -maxdepth 1 -name '*.txt' -exec wc -l {} \; | awk 'BEGIN{num=0}{sum+=$1; num+=1; sub(/.+\//, "", $2); printf("%3d： ツイート数：%5d ファイル名：%s\n", num, $1, $2);} END{print "-----------\n合計 " sum  "\n-----------\n"}' | tail
475： ツイート数： 3913 ファイル名：fraise5743_201705211210-201712171854.txt
476： ツイート数：19018 ファイル名：wata_nabekyo_ko_201708161828-201810250058.txt
477： ツイート数： 5648 ファイル名：ponikitiai_201705282218-201805061856.txt
478： ツイート数：17942 ファイル名：suka_t_201710182304-201805081255.txt
479： ツイート数： 1598 ファイル名：torakiti0405_201611220926-201801301816.txt
480： ツイート数：  531 ファイル名：harumanabi_201706041849-201805041619.txt
-----------
合計 3099738
-----------

Diginnos-PC:~/git/tweet-log_2015
[10039]  % date
2018年 12月 17日 月曜日 20:16:11 JST
Diginnos-PC:~/git/tweet-log_2015
[10040]  % 
```

　次が、今回目的として探し出したまとめ記事の内容です。一部引用します。

```
[link:] 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”次男．＊執行猶予”／データベース登録済みツイート：2018年12月17日02時09分の記録：ユーザ・投稿：1／2件 http://hirono2014sk.blogspot.com/2018/12/regexp20181217020912.html
REGEXP（サーチ）： "次男.*執行猶予"　該当：2件　取得ツイートの投稿日時の範囲：（2018-12-17 02:06〜2018-12-17 02:06）

SELECT * FROM tw_user_tweet WHERE tweet REGEXP "次男.*執行猶予" ORDER BY tw_date ASC
```

▶（1／2） RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜sponichibunsha（スポニチ文化社会部） 日時：2018-12-17 02:06:00 +0900／2018-12-14 05:30:00 +0900 URL： https://twitter.com/hirono_hideki/status/1074349997003395072 https://twitter.com/sponichibunsha/status/1073314120617750529
{% tweet 1074349997003395072 %}
> 三田佳子次男に“大甘”執行猶予５年判決　覚せい剤巡り４度目逮捕も治療施設入所を考慮 https://t.co/PO8R30bI9F

▶（2／2） RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜SportsHochi（スポーツ報知） 日時：2018-12-17 02:06:00 +0900／2018-12-13 12:10:00 +0900 URL： https://twitter.com/hirono_hideki/status/1074349937914048512 https://twitter.com/SportsHochi/status/1073052406026362880
{% tweet 1074349937914048512 %}
> 三田佳子次男、高橋祐也被告に懲役２年６月、執行猶予５年の判決 https://t.co/1IZevQdWep #芸能ニュース #スポーツ報知

　特に関係はないかもしれないですが、個人的に女優の三田佳子さんで思い出すのは、確か「花の乱」というNHK大河ドラマです。はっきりしているのは日野富子役だったということです。福井刑務所で、受刑生活が始まった頃に視聴したように思います。あるいは翌年の放送です。

　日野富子という歴史上の人物の名前はその大河ドラマで初めて知りました。室町時代を舞台にしたドラマでしたが、そんな時代にも今風の女性の名前があったのかという意外性がありました。北条政子は別にしてのことです。

　もともと三田佳子さんはかなり有名で大御所的な女優だったと思いますが、私はドラマも見ない方だったので、その「花の乱」の日野富子役のことが、イメージとしても重なり、テレビで報道をみるたびに思い出していました。

```
『花の乱』（はなのらん）は、1994年4月3日から同年12月11日にかけて放送された33作目のNHK大河ドラマ。放送回数は全37話。

［source：］花の乱 - Wikipedia https://ja.wikipedia.org/wiki/%E8%8A%B1%E3%81%AE%E4%B9%B1
```

　やはり平成6年の放送だったようです。どうもドラマの最初から見たような記憶があり、その最初の方のみがなにか印象的だったのですが、普通、大河ドラマが1月から始まるとすると、それはありえないと先ほど考えていたところです。

　大河ドラマの放送回数が37話というのも、昨夜、録画でしたが見たばかりの大河ドラマ「西郷どん」の最終回は、47回か48回になっていたような気がしたのです。これも記録のデータベースから確認してみます。

[link:] 2018-12-16_221632＿テレビの画面・録画再生　NHK大河ドラマ　西郷どん　（４７）　「敬天愛人」　最終回.jpg  http://hirono2014sk.blogspot.com/2018/12/2018121717402018-12-161852432018-12.html#20181216221632

* 金沢刑務所からの移送が平成6年3月17日、同年4月3日から放送開始となっていたというNHK大河ドラマ「花の乱」

　内容は、このエントリーの中心、主軸である小倉秀夫弁護士とは離れますが、記述の時間軸を優先し、ここに取り上げておきたいと思います。些細といえば些細なことですし、何が重要性を帯びてくるかも想定しきれないものです。

　時刻は12月18日9時17分です。昨夜は、ずいぶん久しぶりに遅い時間になって銭湯に行きました。夕方に雨が降っていたのも理由の1つです。以前は夕方の早い時間に銭湯に行くことの方が珍しかったので、ちょっといつもとは違ったような気分になっていました。

　出掛けたのは22時前後だったと思います。夕食の片付けまでしていたので出掛けるのも少しあわてていました。出掛ける前に書いておきたかったことを続けます。まず、次の引用です。

```
備考［編集］
8月14日放送の第20回「戦雲の都」が記録した視聴率10.1%は、2012年の大河ドラマ『平清盛』の第45回「以仁王の令旨」にて7.3%を記録するまで、大河ドラマ歴代ワースト1位だった［3］。
市川團十郎にとって1985年の團十郎襲名以来、初のNHKドラマ出演になった。また野村萬斎もドラマの放映が始まる1ヶ月前に「萬斎」を襲名したばかりだった（そのため放送前のテレビ雑誌では野村武司名義である）。
この作品は本来、連続テレビ小説の方式に倣って、1年間を10月を分岐とした前期・後期の半年間ずつで展開する作品（1年2作品）の第1弾として企画される予定だったが、準備段階の1993年度に放送された番組の形式（『琉球の風』『炎立つ』）が振るわなかったため、9月終了の予定を変更して12月まで放送された。1995年以後の大河ドラマは1月開始・12月終了の暦年制による1年1作品に戻された。

［source：］花の乱 - Wikipedia https://ja.wikipedia.org/wiki/%E8%8A%B1%E3%81%AE%E4%B9%B1
```

　大河ドラマの最低視聴率を更新したという「平清盛」ですが、私もほとんど視聴しなかったもののTwitterで小倉秀夫弁護士が高く評価していたのが印象的だったドラマです。

　いまテレビで「秘話　伝説”QUEEN”日本との深い絆」というコーナーをやっています。ビビットという情報番組です。ここでも思い出すのが小倉秀夫弁護士の音楽愛好家のような一面です。

　昨夜、ざっと12月10日頃まで遡って小倉秀夫弁護士のFacebookのタイムラインを見てきましたが、音楽関係のものが多く見られました。Twitterでもときたまみられたものですが、割合が全然多くなっています。

　田舎にはそういうものが全くないので余り想像もできないのですが、小倉秀夫弁護士が応援する音楽家というのは、ライブハウスで活動する音楽家のようです。流行や他人の評価には左右される、自分の感性で評価するというスタイルのようです。

　そういう活動の場があるというのも都会ならではのことかと思います。小倉秀夫弁護士は子どもの頃、図書館で沢山の本を読んでいたともツイートしていたことがありました。歴史についても詳しいようですが、それも独自のこだわりで掘り下げているように感じました。

　歴史についても知識量は全般に多いようです。博覧強記ということなのでしょう。記憶力にはずいぶん必要があり、メモの必要を感じない、というような趣旨のツイートをしていたこともありました。

　上記の引用にありますが、NHKの大河ドラマは、平成5年に年2回となったようです。そのことは私の記憶にもありました。年間2本の大河ドラマで、その１つが琉球の歴史という沖縄を舞台にしたものというのも印象的でした。

　私自身、NHKの大河ドラマというのはほとんど見たことがありませんでした。唯一の例外が、以前取り上げていると思いますが、平将門を主人公とした「風と雲と虹と」でした。これは年間を通じで全て視聴しました。

　録画無しで全作を視聴するのは負担が大きく、町内の火の用心の呼び出しで居留守を使い、しんどい思いをしたことも前回に書いていると思います。どうもそのときの負担が、連続性のあるテレビドラマを視聴しなくなったという一因のようにも思われます。

　昭和60年代にはビデオ機器を買っていましたが、レンタルビデオ店から借りてきたものを再生するだけで、テレビ番組の録画というのはしたことがなく、録画の操作方法が理解できなかったし、録画したいという番組もありませんでした。

　今のブルーレイレコーダーを3万円ちょっとで買ったのは、2014年であったように思います。2月頃で、ちょうど「ダムキーパー」というアメリカで活動する日本人監督の作品が、アカデミー賞にノミネートされた頃だったと思います。

　今、録画機器の録画一覧を確認したのですが、最も古いものが「２／２０（金）　ダム／キーパー　めざましテレビ」となっています。サムネイルのような画像があって、長編アニメ部門のノミネート作「かぐや姫の物語」も２つ並んで表示されています。

```
『風と雲と虹と』（かぜとくもとにじと）は、1976年1月4日から12月26日にかけて放送されたNHK大河ドラマ。第14作。

［source：］風と雲と虹と - Wikipedia https://ja.wikipedia.org/wiki/%E9%A2%A8%E3%81%A8%E9%9B%B2%E3%81%A8%E8%99%B9%E3%81%A8
```

　福井刑務所では、分類審査の後、２周間の新入教育がありました。分類審査は１週間ぐらいだったように思います。独居房で軽作業をしながら様子見を受けていたという感じでしょうか、特に何かをすることはなかったように思います。


