#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "告発に至る経緯／社会的な影響／石川県トラック協会／本件告発事件の舞台、市場急配センターの労働環境、労災を含む労働問題という側面"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-11 23:57:37 +0900
FILE_NAME: 2018-12-11-235737_本件告発事件の舞台、市場急配センターの労働環境、労災を含む労働問題という側面.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  石川県トラック協会 市場急配センター 金沢中央卸売市場 労働問題 労災 堂野さん 被告発人松平日出男 金沢中警察署 労働基準監督署 ブラック企業
記事タイトル名の文字数：63　保存ファイル名の文字数：60

#contents

* 気になっていた数日前のブラック企業に関する佐々木亮弁護士（ささきりょう）のツイート

　最初、深澤諭史弁護士のタイムラインでリツイートとして見かけたようにも思うのですが、これから１つまとめ記事を作成しておきたいと思います。

[link:] 2018年12月12日00時21分の登録： REGEXP：”弁護団の収入が、昨年の収入の約4万倍に”／データベース登録済みツイート：2018年12月12日00時21分の記録：ユーザ・投稿：6／6件 http://hirono2014sk.blogspot.com/2018/12/regexp420181212002166.html

```

アカウント名	ツイート数	リツイート数
ささきりょう（ssk_ryo）	1	0
?朕朕（un_co_the2nd）	0	1
弁護士あだちけいた ボヘミアン・ラプソディ（keita_adachi）	0	1
嶋﨑量（弁護士）（shima_chikara）	0	1
鳩屋（haya_rt）	0	1
高木良平（ryouheitakaki）	0	1


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”弁護団の収入が、昨年の収入の約4万倍に”／データベース登録済みツイート：2018年12月12日00時21分の記録：ユーザ・投稿：6／6件 http://hirono2014sk.blogspot.com/2018/12/regexp420181212002166.html
```

　スプリクトの処理で取りこぼしがあったらしく鉄板であるはずの深澤諭史弁護士のリツイートがまとめ記事に含まれていませんでした。

　そもそも佐々木亮弁護士（ささきりょう）のツイートの内容を探し出したのが、「grep ブラック fukazawas_201703201148-201812111403.txt |tac」というコマンド実行でした。

▷ リツイート→fukazawas（深澤諭史）＞ssk_ryo（ささきりょう）｜2018/12/08 14:39／2018/12/08 14:09｜https://twitter.com/fukazawas/status/1071278167212478464 ／ https://twitter.com/ssk_ryo/status/1071270495436255232
&twitter(1071278167212478464){theme:light}
> RT @ssk_ryo: 年に1回のブラック企業被害対策弁護団の総会が始まった。今年で第6回である。
> 今年の1年の弁護団の収入が、昨年の収入の約4万倍に達したことが報告された。素晴らしい前進である。  

　TwitterAPIで深澤諭史弁護士のリツイートの内容が取得できました。リツイートが取り消されていればエラーが出るはずですが、データベースに登録済みのものは影響を受けず、深澤諭史弁護士、モトケンこと矢部善朗弁護士（京都弁護士会）、小倉秀夫弁護士は全件の記録を行っています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ssk_ryo（ささきりょう） 日時：2018-12-12 00:36／2018-12-08 14:09 URL： https://twitter.com/kk_hirono/status/1072515418164748289 https://twitter.com/ssk_ryo/status/1071270495436255232
&twitter(1072515418164748289){theme:light}
> 年に1回のブラック企業被害対策弁護団の総会が始まった。今年で第6回である。 \n  今年の1年の弁護団の収入が、昨年の収入の約4万倍に達したことが報告された。素晴らしい前進である。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ssk_ryo（ささきりょう） 日時：2018-12-12 00:36／2018-12-08 14:20 URL： https://twitter.com/kk_hirono/status/1072515436162572289 https://twitter.com/ssk_ryo/status/1071273387975004160
&twitter(1072515436162572289){theme:light}
> 昨年の収入が4円というのが大前進の勝因である。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ssk_ryo（ささきりょう） 日時：2018-12-12 00:36／2018-12-08 16:25 URL： https://twitter.com/kk_hirono/status/1072515462469169152 https://twitter.com/ssk_ryo/status/1071304767014498307
&twitter(1072515462469169152){theme:light}
> なお、総会では、梅田和尊弁護士より「固定残業代についての最新裁判例の検討」と題する講演が行われて、とっても勉強になりました。
◁◁◁
<hr />

　佐々木亮弁護士（ささきりょう）にはブロックされていないので、リツイートを３件行いました、前年の収入が４円とありますが、これは深澤諭史弁護士のリツイートとして確認はしませんでした。

　４円のツイートは現時点でリツイートが１０３件、元の４万倍のリツイートが同じく１９９件となっていました。あるのかどうかわかりませんが、今時４円で買えるものといえば１円切手ぐらいかと思います。実際、拘置所では１円切手を使うことがあったように思います。端数の必要です。

　他に考えられるのは銀行預金の利子ぐらいのものでしょう。佐々木亮弁護士（ささきりょう）の４枚倍のツイートが際立って感じられたのは、不当という大量懲戒請求に対する損害賠償が、億単位の収入にもなりうるという情報を見かけていたからです。

[link:] » 懲戒請求　億 - Twitter検索 https://t.co/VbkluTY7TT

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Takzos（Pochy） 日時：2018-12-12 00:50／2018-10-29 22:23 URL： https://twitter.com/kk_hirono/status/1072519115041071104 https://twitter.com/Takzos/status/1056899347499995137
&twitter(1072519115041071104){theme:light}
> @nhk_kurogen 一人の和解金が40万、数百人居るらしいので億単位になるんですね。 \n  懲戒請求された弁護士に渡るのかなぁ。。。 \n  例えば悪いけど、「ゴキブリほいほい」だったのかも。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sinsinsinku02（シンシン(•ө•)） 日時：2018-12-12 00:51／2018-10-24 00:07 URL： https://twitter.com/kk_hirono/status/1072519194934169601 https://twitter.com/sinsinsinku02/status/1054751210492780545
&twitter(1072519194934169601){theme:light}
> @cleanrevofjmn ＞本気出せば合計億単位にもなりかねないぞ \n  ４ヶ月ほど動きが無かったので、話題に成らないが、 \n  会見後複数の弁護士も品位を損なう非行とか言ってたけど \n  再浮上するだろうか？ \n  #懲戒請求
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kagekubou（影公方） 日時：2018-12-12 00:51／2018-08-23 14:05 URL： https://twitter.com/kk_hirono/status/1072519318989168642 https://twitter.com/kagekubou/status/1032494012131753984
&twitter(1072519318989168642){theme:light}
> 一切おかしくない構図ぞよ。そもそも衆愚が大量に #不当懲戒請求 したのが想定外の事態。和解額×愚者数で億になるのも当然の帰結。おかしきは請求者側の構図にてコケカキィキィ。 \n  弁護士に対する大量懲戒請求事件を考える、1億円に近い「和解… https://t.co/srN4h8qNlP
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜360Yosshi360（要介護者の「強制」安楽死を切望するパワハラが怖いニート） 日時：2018-12-12 00:53／2018-05-18 23:02 URL： https://twitter.com/kk_hirono/status/1072519722518876165 https://twitter.com/360Yosshi360/status/997477603798802432
&twitter(1072519722518876165){theme:light}
> 不当懲戒請求で弁護士が和解や訴訟で手にするかもしれない金額が数千万もしくは億単位になる可能性を口実に叩いてるのがいるけど、多勢に無勢って言葉があるように数百数千から石を一人に投げられたことの抵抗と考えれば結果的にそうなってもおかしくは無いだろ。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜battlecom（脱原発.com 【改憲阻止】） 日時：2018-12-12 00:53／2018-05-17 12:58 URL： https://twitter.com/kk_hirono/status/1072519836759154688 https://twitter.com/battlecom/status/996963048664416265
&twitter(1072519836759154688){theme:light}
> @TOxMOxNIx67 懲戒請求をノリでやって反省しているという人は \n   \n  二度と民族差別をしない、権力礼賛による民主主義の破壊をしないということを約束し、それを破った場合には違約金として賠償相当額を支払うという確約を個別契約すれば… https://t.co/LQxoSoCRow
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜suido7（福わはは　日本株上昇(非上場株式を含む)とGDP増加は、日本を幸福と勝利へ導く） 日時：2018-12-12 00:54／2016-07-21 12:59 URL： https://twitter.com/kk_hirono/status/1072520098164940800 https://twitter.com/suido7/status/755975561495711744
&twitter(1072520098164940800){theme:light}
> 弘中惇一郎は「武富士口封じ裁判」の武富士側の主任弁護士。 武富士に都合の悪い記事を書くジャーナリストに億単位の賠償を請求する悪質な物で、勿論武富士・弘中側は全面敗訴。 知る人ぞ知る名誉毀損ビジネスの恫喝弁護士。やり口が余りに汚く、宇都宮健児弁護士会会長から弁護士懲戒請求まであった
◁◁◁
<hr />

　目的とした事実関係の確認は出来ましたが、ツイートの数は思ったより少なく、札幌の弁護士のツイートもありませんでした。もともとブログがメインでツイートは記事の紹介として使っているような弁護士なので、ツイートがないのも納得ですが、記事名に億は含まれていないようです。

　今になって上の名前だけ思い出してきました。猪野であったように思いますが、猪にしか記憶に自信が持てません。なお、さきほどのTwitterの検索は、ブロックされている弁護士やアカウントのツイートが他にある可能性もあるかと思います。これもまとめ記事を作成した方が早そうです。

　時刻は１２月１２日１時７分です。日付が変わっていることにも気が付かずにいました。zeroが終わってからだいぶん経つので、よく考えるとそんな時間ではあります。まとめ記事の作成が完了したところです。

* 弘中惇一郎弁護士が武富士側の主任弁護士としてジャーナリストに億単位の賠償請求をし、全面敗訴していたという。

　さきほどのTwitterの検索で、弘中惇一郎弁護士のことが出てきました。武富士の弁護人だったという話はネットで見て知っていましたが、ジャーナリストに億単位の賠償請求をしていたとは、思い出すような気もするので、忘れていたようにも思います。

　全面敗訴とありますが、ジャーナリストが弁護士に依頼し、普通の計算だと弁護士費用も相当大きなものになったのかもしれません。マスコミ相手に勝訴を重ねたというのはロス疑惑の三浦和義氏ですが、そのロス疑惑の刑事裁判の無罪の弘中惇一郎弁護士を無罪請負人といわしめた業績と聞きます。

　マスコミ相手に民事の勝訴を重ねたということで、私がより注目していたのは富山・長野連続殺人事件の女性被告人のことです。はっきりとはわかりませんが、現在は死刑囚となっているのかもしれません。この事件についても書いておきたいことがありました。

　ページを開いたままにしていますが、さきほどのTwitter検索に、次の内容のツイートがあったことに気が付きました。主な内容は本文ではなく３つの画像です。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜takarin_7（たかりん。7） 日時：2018-12-12 01:22／2017-06-21 12:18 URL： https://twitter.com/kk_hirono/status/1072527169010786305 https://twitter.com/takarin_7/status/877365011852673024
&twitter(1072527169010786305){theme:light}
> #日弁連 \n  まだ５ヶ月しか経っていないのに \n  懲戒請求が…９００件もあるなんて… \n  本当に余命様のおっしゃる通りの \n  ヤクザもびっくりの犯罪件数です \n  …横領や詐欺事件等のその額の大きさ \n  億？えええ？本当に信じられない◀抜粋 \n   \n  大半は朝鮮系… https://t.co/kaOyZy0AtI
◁◁◁
<hr />

　さきほどタイムラインをみているときに、「ヤクザもびっくり」という言葉がみえていたのですが、先を急いでいました。横領や詐欺事件の額の大きさとしてキーワードの億が含まれていました。


* ２０１６年弁護士が横領した金額（新聞発表・判決）というツイートの画像、久保田昇（大阪）５億円

　ツイートの３つの添付画像の１つです。括弧書きで（起訴時点）、（逮捕時の報道）などというものがあり、４千万円で懲役３年というのものもありますが、久保田昇弁護士については備考欄のような記載がありません。

　たぶん私の記憶にある弁護士だと思います。深澤諭史弁護士が間接的に言及した「脳機能障害の少女の家族」を被害者とした弁護士のことだと思います。当時は他に岡山と福岡で５億を超えるような弁護士の横領・詐欺事件のネット記事がありました。福岡の方は立件として５億より少なかったかも。

　岡山の弁護士の横領事件は被害額が９億円か１０億円という話もあったかもしれません。福岡の弁護士と懲役刑は同じぐらいだったと思いますが、懲役１０年は超えていたと思います。はっきり思い出せないですが、懲役１２年ぐらいだったように思います。

　岡山と福岡の大きな額の横領事件は、刑事裁判となり判決も出ていたので実在感もはっきりしていましたが、大阪のたぶん久保田昇弁護士のことは、逮捕や容疑という段階の報道しか見かけていなかった気がします。いずれもネットのみの情報です。テレビでは一切報道を見ていません。

　以下は私のパソコンでの「% dp -p |grep 脳機能障害」というコマンドの実行結果になります。

[link:] 2018年04月10日02時39分の登録： REGEXP：”脳機能障害．＊少女”／データベース登録済みツイート：2018年04月10日02時38分の記録：ユーザ・投稿：5／23件 http://hirono2014sk.blogspot.com/2018/04/regexp201804100238523.html

[link:] 2018年09月08日15時54分の登録： REGEXP：”脳機能障害．＊少女”／データベース登録済みツイート：2018年09月08日15時54分の記録：ユーザ・投稿：5／24件 http://hirono2014sk.blogspot.com/2018/09/regexp201809081554524.html

[link:] 2018年09月08日16時08分の登録： REGEXP：”脳機能障害．＊少女”／データベース登録済みツイート：2018年09月08日16時08分の記録：ユーザ・投稿：6／35件 http://hirono2014sk.blogspot.com/2018/09/regexp201809081608635.html

　次は同様に、「% locate 脳機能障害| gawk -F/ '{print $NF}'」というコマンドの実行結果になります。

2017-04-20-222038_交通事故に遭った女性　高次脳機能障害となり，その後の人生はメチャクチャ.jpg

2018-11-10_040605＿北陸中日新聞・１１月８日　事故によって思考能力の低下を招く高次脳機能障害を患っている影響か、口調はたどたどしかった。.jpg

2017年04月21日05時25分22秒／記録資料／そもそも裁判所が「高次脳機能障害」を認めずに，雀の涙ほどの賠償金で終わることもある.mkv

2015-08-10-223347_提供社の都合により、削除されました。概要のみ掲載しております。→　脳機能障害を負った少女の一家から着服　「示談不成立」とウソ　-　ライブドア.jpg

2016-04-26-114744_ささもたん@赤腹魔王@yukihirosasamoさっきのと同一人物ですか……。開いた口が塞がらないよ……。脳機能障害を負った少女の一家か.jpg

2016-04-29-040303_井上雄樹さんがリツイート　satomi　inoue　@satomiot　　7時間7時間前警察の方と話して驚いたのは、「高次脳機能障害」とい.jpg

2016-05-17-021845_ささもたん@赤腹魔王さんのツイート：　”さっきのと同一人物ですか……。開いた口が塞がらないよ……。　脳機能障害を負った少女の一家から着服　「.jpg

2016-05-17-022544_脳機能障害を負った少女の一家から着服　「示談不成立」とウソ　-　ライブドアニュース.jpg

　２枚目として表示される画像には、横に振り向くような胸から上の人物の写真に「高山正之ジャーナリスト」という文字が見え、上から重ねるような赤字の文字で「【衝撃】日弁連はキレイ事　ばかりで一貫性が無い！」とあります。バナー公告のような小さな写真です。

　高山正之という人物は見覚えのない名前です。よくみると江村正之検察官と下の名前が同じなので、なにか機会があれば記憶にのこっていたように思います。ジャーナリストのようです。

* 、「共謀罪と日韓断交　余命三年時事日記」、佐々木亮弁護士（ささきりょう）や北周士弁護士を含めた弁護士に対する大量懲戒請求の中心的人物

　３枚目として表示される画像には、本の表紙のようですが、「共謀罪と日韓断交　余命三年時事日記」とあり、帯のように見える部分には左端に「余命プロジェクトチーム」という文字が読み取れます。

　この余命三年というペンネームのような人物が、佐々木亮弁護士（ささきりょう）や北周士弁護士に対する不当といわれる大量懲戒請求を先導した人のようです。この問題はNHKのクローズアップ現代＋でも見ています。これもppコマンドから探し出せそうです。

　以下は、「% pp -p |grep 大量懲戒請求|egrep '(クロ現|クローズアップ現代)'」という私のパソコンでのコマンドの実行結果になります。ppというのは私の自作のコマンドであり、適当につけたコマンド名であります。

[link:] 2018-10-30-064435_深澤諭史のリツイート（totemo　@migattena_kimi）：クローズアップ現代＋「大量懲戒請求異例の裁判で賠償命令」まとめ請求者.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103011052018-10-27-1114542018-10-30.html#20181030064435

[link:] 2018-10-29_203229＿テレビの画面・ビエラ　録画予約・クローズアップ現代＋「弁護士に大量懲戒請求異例の賠償命令.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029203229

[link:] 2018-10-29_204445＿テレビの画面・総合　今夜１０時　クローズアップ現代＋　なぜ起きた？弁護士への大量懲戒請求.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029204445

[link:] 2018-10-29_204447＿テレビの画面・総合　今夜１０時　クローズアップ現代＋　なぜ起きた？弁護士への大量懲戒請求.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029204447

[link:] 2018-10-29_221706＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221706

[link:] 2018-10-29_221714＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221714

[link:] 2018-10-29_221739＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221739

[link:] 2018-10-29_221805＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221805

[link:] 2018-10-29_221830＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221830

[link:] 2018-10-29_221843＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221843

[link:] 2018-10-29_221853＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221853

[link:] 2018-10-29_221914＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221914

[link:] 2018-10-29_221927＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221927

[link:] 2018-10-29_221937＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221937

[link:] 2018-10-29_221949＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221949

[link:] 2018-10-29_221959＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネット特有の仕組みが関係　社会分断　エコチェンバー.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029221959

[link:] 2018-10-29_222004＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネットで社会が分断・・・　いま何が起きているのか.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029222004

[link:] 2018-10-29_222011＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネットで社会が分断・・・　いま何が起きているのか.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029222011

[link:] 2018-10-29_222018＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネットで社会が分断・・・　いま何が起きているのか.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029222018

[link:] 2018-10-29_222048＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネットで社会が分断・・・　いま何が起きているのか.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029222048

[link:] 2018-10-29_222431＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネットで社会が分断・・・　いま何が起きているのか.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029222431

[link:] 2018-10-29_222448＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネットで社会が分断・・・　いま何が起きているのか.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029222448

[link:] 2018-10-29_222453＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネットで社会が分断・・・　いま何が起きているのか.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029222453

[link:] 2018-10-29_222456＿テレビの画面・クロ現＋・「弁護士に大量懲戒請求異例の裁判で賠償命令▽ネットで何が」　ネットで社会が分断・・・　いま何が起きているのか.jpg  http://hirono2014sk.blogspot.com/2018/10/2018103018382018-10-290536232018-10.html#20181029222456

　連続した同じ見出し名のものは告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)にツイートしませんでした。

　余命三年という人物については、その大量懲戒請求に関するツイートや記事などその他の情報でみていましたが、「共謀罪」が大きなテーマのようになっていたとは知らず、それも「日韓断交」との組み合わせとなっているようです。「外患誘致罪」の方はどこかで見ていたように思います。

* 「猪　弁護士」とTwitterで検索すると「猪狩り」が出てきた。多分間違っていた札幌の弁護士の一文字

[link:] » 猪　弁護士 - Twitter検索 https://t.co/DwJWlnnwTo

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜o2441（弁護士大西洋一） 日時：2018-12-12 02:29／2017-12-05 07:08 URL： https://twitter.com/kk_hirono/status/1072543893558882304 https://twitter.com/o2441/status/937805826454155266
&twitter(1072543893558882304){theme:light}
> 自称中３の謎キャラの作家さんだけど（スライムキャラやってる弁護士にそんなこと言われたくないか・・笑）、この方の作品好きなので見に行こうと思う。 \n   \n  【猪風来美術館】村上原野 縄文土器展『ハロ－、縄文！』 - Togetter https://t.co/37x1wob4fP
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜consaba（河村書店） 日時：2018-12-12 02:29／2017-01-08 05:44 URL： https://twitter.com/kk_hirono/status/1072544018146516993 https://twitter.com/consaba/status/817834216817704961
&twitter(1072544018146516993){theme:light}
> 「ハコモノ行政、失敗から学んでいない」猪谷千香さんが見た「オガール」成功の要因「こんな町に住みたいな、と心から思った」|弁護士ドットコム  https://t.co/dCkBFh2wZZ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜okuboka（大窪和久） 日時：2018-12-12 02:30／2016-10-17 17:26 URL： https://twitter.com/kk_hirono/status/1072544046168576002 https://twitter.com/okuboka/status/787932801983143936
&twitter(1072544046168576002){theme:light}
> 自由と正義の「法テラス地方事務所の現場」では、岐阜の鷲見地方事務所所長の発言として、民事扶助と国選で「若手の弁護士の事務所の経費がまかなえます。必要とされる仕事をして、高くはないけれども報酬が得られる構造となってきています」とのこと。事実ならば猪狩りをしなくても良いですね。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜terayasan（てらやさん☆） 日時：2018-12-12 02:30／2016-03-11 17:46 URL： https://twitter.com/kk_hirono/status/1072544157497995264 https://twitter.com/terayasan/status/708212391096352768
&twitter(1072544157497995264){theme:light}
> 弁護士の徽章に描かれた天秤は，捕まえた猪の肉の目方を量るものです。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜okuboka（大窪和久） 日時：2018-12-12 02:30／2016-03-11 17:27 URL： https://twitter.com/kk_hirono/status/1072544179983663105 https://twitter.com/okuboka/status/708207797826027520
&twitter(1072544179983663105){theme:light}
> 猪をとると8000円の補助金がでるので、猪をとるための研修を受けに行った弁護士がいるとの報告@岐阜 #日弁連臨時総会
◁◁◁
<hr />

* ブロックされていて出てこなかった「猪　弁護士」のツイートを検索、弁護士のイノシシ狩りの発祥は確か岐阜だった。豚コレラで狩猟禁止になったとも聞く

▶ ツイート％Toshimitsu_Dan（だんどじみつ）％2016/03/16 07:46％ https://twitter.com/Toshimitsu_Dan/status/709873417034539009
&twitter(709873417034539009){theme:light}
> 猪な弁護士RT @ymnmsyk: 猪に強い弁護士（物理）  
▶

▶ ツイート％allgreen76b（おるぐり豚🦐）％2018/04/28 17:19％ https://twitter.com/allgreen76b/status/990143485616373760
&twitter(990143485616373760){theme:light}
> 弁護士に送るのが懲戒請求。
> デブのお代わり注文が猪八戒請求。  
▶

▶ ツイート％nodahayato（弁護士　野田隼人）％2016/05/10 15:38％ https://twitter.com/nodahayato/status/729923636124000256
&twitter(729923636124000256){theme:light}
> 弁護士会の図書室に「わが国の狩猟法制―殺生禁断と乱場」（青林書院）が入ったが，猪関連か？ href="https://t.co/VEHNX9seIf  
▶

▶ ツイート％sakamotomasayuk（坂本正幸）％2016/03/17 20:45％ https://twitter.com/sakamotomasayuk/status/710431849453989889
&twitter(710431849453989889){theme:light}
> 愛子先生のイラストをプリントしたTシャツをユニフォームにして、全国から届けられる猪や鹿などを素材に、こたんせをシェフにして
> という構想(妄想)が進んでいる
> あとはどれだけ弁護士が狩猟をしてくれるかだ  
▶

▶ ツイート％ry925（乙）％2016/03/15 12:51％ https://twitter.com/ry925/status/709587770939822080
&twitter(709587770939822080){theme:light}
> 弁護士が猪狩りをすれば、神戸大学の猪問題も解決できそう。  
▶

▶ ツイート％uwaaaa（サイ太）％2016/03/11 17:45％ https://twitter.com/uwaaaa/status/708212325480665088
&twitter(708212325480665088){theme:light}
> 「いのししだろ，これ」 RT @nodahayato: 弁護士が狩った猪は協同組合で販売すればいいんじゃないかな？  
▶

▶ ツイート％keita_adachi（弁護士あだちけいた ボヘミアン・ラプソディ）％2011/09/30 17:48％ https://twitter.com/keita_adachi/status/119695122660212736
&twitter(119695122660212736){theme:light}
> 猪野先生のブログ　http://t.co/PpX4nkrX　「青『弁護士がいない市町村が多数あり』→猪：全国の市町村すべてに弁護士がいないと何故、問題なのでしょうか。」 　全道一斉相談は「弁護士がいない市町村が多数あ」る現状は問題だというメッセージを発信しまっているのではないかな  
▶

　全部がブロックされているとは限らないようです。告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントで実行した検索で見当たらず、弁護士や法律の大学関係者と思われるツイートをピックアップしました。

　少なくとも、次の２つのアカウントのツイートは、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)にログインした状態で表示されましたので、次にリツイートを行います。

　不思議に思ったのは、坂本正幸弁護士や野田隼人弁護士、刑裁サイ太、足立啓太弁護士などブロックされていることが明らかなアカウントのツイートを含め、ほとんど全部が、１つのアカウントに１つのツイートで表示されたことです。

　特に坂本正幸弁護士だけでも猪に関するツイートの数が多かったことはよく憶えていました。なので途中で「猪」では無理があり、「イノシシ」がほとんどだったのかという考えも頭に浮かんできました。それでも役者は揃ったようです。

　実は、今年、生まれて初めて野生のイノシシをみました。動物園でも見たという記憶はないのですが、見ていたという可能性は排除できないところです。それも海で泳いでいるのを目撃しました。小木港の東一文字堤防でのことです。気がつくとすぐ目の前で泳いでいました。

　犬かきのように泳いでいる姿はテレビで見たことがありました。七尾市の御祓川ではなかったかと思います。私が海で見たイノシシは、泳いでいるとは見えず、回転しながら転がっているように見えました。太陽の日差しの加減もあったのか、長い毛が赤茶色に近いようにみました。

　テレビで見かけることの多いカピバラの毛の色に近かったと思います。しかし、最初はゴザの塊かと思い、それが生きている動物だとわかったので、大きなネズミに思えました。すぐにありえないと否定し、次に浮かんだのがカピバラで、南米と聞いていたのでありえないと思い、そのあと漸く猪と。

　それは８月１２日のことでした。九十九湾で特別なことがあった８月１３日を、１２日と勘違いしていたので、特に印象深い日の出来事でした。ツイートはしてこなかったかもしれませんが、写真や動画もスマホで撮影しています。白日夢という言葉を思い出すほど不思議な体験でした。

[link:] 2018-08-14_173946＿小木港東一文字堤防アジ釣り　泳ぐイノシシ.jpg  http://hirono2014sk.blogspot.com/2018/08/2018082711152018-08-011101372018-08.html#20180814173946

[link:] 2018-08-14_173948＿小木港東一文字堤防アジ釣り　泳ぐイノシシ.jpg  http://hirono2014sk.blogspot.com/2018/08/2018082711152018-08-011101372018-08.html#20180814173948

　記録していた写真ファイル名で、自分の記憶違いに気が付きました。８月１２日ではなく８月１４日でした。８月１５日の前日というのも意外です。８月１５日はお盆としても特別な日だと思いますし、昭和４５年８月１５日が被害者安藤文さんの誕生日でもあります。

　時刻も１７時３９分とあります。今の１２月の季節だと外は夜中と同じ暗さになっている時間かと思います。私はこれまで昼過ぎの１４時頃のことかと思っていました。１５時という気もしましたが、どんなに遅くても１６時より前とは考えていませんでした。

　初めに海にイノシシがいることに気がついたのは、釣り竿持って立っていた堤防の先端から２５メートルほど離れた場所でした。ちょうどアジがタイミングで遠投をしていたので巻き上げるのに時間が掛かっていました。あとで考えると、そのまま竿を置いても良かったのですが、釣り上げました。

　釣れたといっても１７センチほどのアジが一匹でした。その頃だと釣れた魚を取り込む時の鳶の襲来にも気を張っていました。油断するとケガをさせられますし、釣り竿を海に持っていかれる可能性もあります。

　鳶もウミネコもいるときはいますし、いない時はまったくいないことも多いです。海の中でアジが釣れたまま放置していると、気になるのはアジが暴れて、サビキの仕掛けが絡まることです。消費税を入れて３５０円程度のものかと思いますが、私は何度も使いまわしをする方です。

　それまで頭に浮かばなかったことも不思議なのですが、アジを取り込んですぐに写真撮影に気が付き、急いで駆けつけたのですが、イノシシはちょうど堤防の先端にいました。４，５メートル離れていたように思います。そのあと潮の流れにのるように早く遠ざかっていきました。

　最初に見た時は、ちょうど目の前という距離でした。堤防の高さは５．２メートルほどのタモでも短く感じることがあるので、３メートルはあるように思います。それを含めてちょうど見やすい距離だったので泳いでいる足の様子まで見えたのですが、堤防の先端では光の反射もあったのか見えませんでした。

　能登半島で記録に残る熊の目撃情報というのはないはずですが、数年前、能登島の監視カメラに撮影されていたというニュースがありました。７年ほど前までは、能登半島に熊の生息はないといわれていました。イノシシもそれに近いもので、河北郡の津幡町辺りでは出没が多いとは聞いていました。

　昨年だったように思いますが、能登町の笹川で熊の目撃があり、今年の秋だったと思いますが、能登町の藤ノ瀬で熊の目撃があったという告知放送がありました。それはテレビのニュースにはなっていないようでした。実際に見た人がいるのでしょうが、撮影などの記録は出来なかったようです。

　イノシシについては宇出津の周辺でもよくいるという話を聞いていますし、私の家のすぐ近くでも親子連れのイノシシがいて、車の中からすぐ近くにいるのを撮影したという話は聞きました。それでも不思議と宇出津では農業被害の話も聞きません。農作物自体が少ないですが。

　神野や旧柳田村の方では、田畑に電気柵をしているという話を聞きましたが、一度だけ上町の近くでそれらしい電気柵を見たものの、そのあとテレビの番組で見た大掛かりな電気柵とはまるで違っていました。イノシシが食べ物にそれほど不自由しないという自然環境もあるのかもしれません。

　テレビではイノシシで死人まで出たという話を聞いています。福岡県だったと思いますが、通行人に襲いかかるイノシシの映像も繰り返し放送されていました。２カ月近く前になるのかと思いますが、テレビで「もののけ姫」を見て、途中から見たのですが、イノシシが出ていました。

```

NHK
能登島クマ目撃バスや車で登校
21日から22日に掛けて、初めてクマが目撃された七尾市の能登島では、23日朝、島に住むすべての小学生を車やバスで登校させる措置が取られました。七尾市の能登島では、21日から22日にかけて、祖母ケ浦町の県道などで体長1メートルあまりのクマが相次いで目撃されました。能登島でクマが目撃されたのは初めてです。

>>続きを読む

［source：］【島】初めて熊が目撃された能登島で、島に住むすべての小学生を車やバスで登校させる措置が取らる - 2NN 2ちゃんねるニュース速報＋ナビ https://www.2nn.jp/newsplus/1466705391/
```

　能登島といえば、今年の夏の火祭で、山火事になったというニュースがありました。調べても火事の程度が不明でしたが、大きな被害は出ず早く鎮火させることが出来たようです。かなり風の強い状況で、日本三大火祭りの１つにも数えられる火祭を実行したようです。

```
祭りは県指定無形民俗文化財の「能登島向田の火祭」。市のホームページによると、日本三大火祭りの一つで、高さ３０メートルのたいまつが火柱となって燃え、倒れた方向によって豊漁や豊作を占う。

　署によると、２８日午後９時４５分ごろ、山林が燃えているのを署員が見つけた。約５００平方メートルを焼き、２９日午前２時前に鎮火し、けが人はいなかった。山林は祭りの会場から南に約４００メートル離れている。

　金沢地方気象台によると、七尾市には当時、台風１２号の影響で強風注意報が出ていた。

［source：］台風の強風で火の粉飛び散り山林火災か　日本三大火祭りの巨大たいまつから - 芸能社会 - SANSPO.COM（サンスポ） https://www.sanspo.com/geino/news/20180729/acc18072918360007-n1.html
```

```
2018年11月06日 08：01

　岐阜市の養豚場の豚が家畜伝染病「豚（とん）コレラ」に感染した問題で、県は５日、銃猟が始まる今月１５日から来年３月１５日のシーズン終了まで、県内２０市町にまたがるエリアで全ての狩猟を禁止すると決めた。今月に入り可児市など新たな地域で感染イノシシが見つかるなど感染の広がりが確認されたことから、狩猟者が山に入り野生イノシシを追うことでさらに拡大するのを防ぐため。

［source：］豚コレラ問題で２０市町区域狩猟禁止　県が決定 | 岐阜新聞Web https://www.gifu-np.co.jp/news/20181106/20181106-87907.html
```

　そういえば、つい最近、昭和の初め頃だったように思いますが、「豚（とん）コレラ」の発生でイノシシが絶滅しかけたというような記事を読んだことを思い出しました。その部分しか思い出せなくなっています。何かを調べている時に出てきました。今年になって初めて聞いた豚コレラです。

* 北海道の足立啓太弁護士のツイートで一つだけ見るけることが出来た「猪野先生」という手がかり

　ふと思い出したのですが、猪野という名前は何かの事件の被害者の女性の名前として見かけていたことを思い出しました。

　間違えていたので小見出しを「滋賀県の野田隼人弁護士」から「北海道の足立啓太弁護士」に変更しました。野田隼人弁護士の猪を含むツイートが２つあったのかとも考えたのですが、数が多くない検索結果を２，３度読み返すことで、気が付きました。

▶ ツイート％keita_adachi（弁護士あだちけいた ボヘミアン・ラプソディ）％2011/09/30 17:48％ https://twitter.com/keita_adachi/status/119695122660212736
&twitter(119695122660212736){theme:light}
> 猪野先生のブログ　http://t.co/PpX4nkrX　「青『弁護士がいない市町村が多数あり』→猪：全国の市町村すべてに弁護士がいないと何故、問題なのでしょうか。」 　全道一斉相談は「弁護士がいない市町村が多数あ」る現状は問題だというメッセージを発信しまっているのではないかな  
▶

```
2011.01.09 Sun

09：47：22

　2011年1月9日付北海道新聞のサンデー討論に「司法修習給費制度維持の是非」と題して、2名の方がそれぞれの立場で意見を述べています。 
　坂口唯彦さん（弁護士）「多様な人材確保に必要」 
　青山善充さん（法科大学院協会理事長）「法曹人口の抑制が本音」 

　坂口唯彦さんは、札幌弁護士会所属の弁護士ですが、そこで主張されている内容はしごくもっとも、当然の主張です。 
　これに対し、青山善充氏の主張は、何とも言えない暴論です。 
　以前にも青山善充氏の暴論批判は、当ブログでも掲載しましたが、改めて検討することにしましょう。 

［source：］弁護士　猪野亨のブログ 青山善充氏の見解　その２ http://inotoru.dtiblog.com/blog-entry-262.html
```

　EmacsからURLのリンクを開くとエラーが出たので、ブラウザのURL欄をみると、URLに文字列が繋がっていました。URLとタイトル名を全角スペースが区切っていたようです。普通のツイートだと今は出てこないエラーかと思います。確認するとツイートの方はURLで区切られていました。

　以前は、郷原信郎弁護士のツイートでも同じ現象を目にしたことがありました。他の弁護士のツイートでもいくつかありました。半角と全角の違いを理解しておらず、プログラムでは半角スペースと改行でデータを区切って扱うという基本を理解しないままパソコンを使っていたようです。

　無効となっているURLリンクの原因に気がつく人の方がまれだと思いますが、一般人はともかくテキストを扱う専門家である弁護士という立場であれば、それぐらいの基本は弁えておいてもらいたいところです。

* 確認できた猪野詩織さんという桶川ストーカー殺人事件の被害者名

```
《平成１１年、女子大生の猪野詩織さん＝当時（２１）＝がストーカー被害の末に殺害された事件は、警察の不適切な対応、報道被害など多くの問題を浮き彫りにした。現在も父の憲一さん（６７）と母の京子さん（６８）は、各地で再発防止を訴えている》

［source：］【被害者・遺族は問う】（３）桶川ストーカー殺人事件、猪野憲一さん（６７）、京子さん（６８）　「娘の名誉回復のため」実名公開（1/3ページ） - 産経ニュース https://www.sankei.com/premium/news/180620/prm1806200004-n1.html
```

　「猪野　事件」という大雑把なキーワードでGoogle検索を実行しましたが、すぐに情報が出て、やはり桶川ストーカー殺人事件だったのかと確認できました。父親のお顔はこれまで見たことがあったのですが、母親と思われる女性の写真を見たのは今回が初めてだと思います。

　そもそも「猪野」という名前を調べたのは、イノシシが目的でもなく、佐々木亮弁護士（ささきりょう）や北周士弁護士の大量懲戒請求に対する損害賠償請求裁判に、異議を唱えるような否定的な意見を表明していた札幌の猪野亨弁護士について、確認のため調べるのが目的でした。

　上記の記事で今回初めてのことのように目に入ったのは、桶川ストーカー殺人事件の被害者、猪野詩織さんの事件当時の年齢が２１歳となっていることです。この被害者の年齢については、昨日もテレビニュースを見ながら気になっていたところでした。

　今のところ、テレビの報道ではストーカーという言葉はみていませんが、一方的に女性に好意を抱き殺害したという事件です。最初に気になったのは逮捕された加害者の年齢が２７歳ということです。これは平成４年の傷害・準強姦被告事件のときの私の年齢と同じです。

　殺害された被害者の年齢は２０歳となっていました。もう日付が変わっているので昨夜の報道ステーションになりますが、具体的な情報が次々と出ていました。事件の第一報も昨日のことであったように思います。

* 遺族が国家賠償を求め、捜査怠慢の違法性を一部認め、埼玉県に５５０万円の賠償を命じる判決が確定していたという桶川ストーカー殺人事件で初めて知る情報

```
《被害を相談した埼玉県警の対応は鈍く、遺族が国家賠償を求めた訴訟では、捜査怠慢の違法性を一部認め、埼玉県へ５５０万円の賠償を命じる判決が確定した》

　憲一さん「警察はきちんと対応してくれると信じていましたが、勤務先でまかれた中傷ビラを持っていっても動いてくれませんでした。詩織が『交際相手にブランド品をねだった』という事実無根の報道もされ、マスコミも警察と一緒になって詩織を抹殺しようとしていると感じました」

［source：］【被害者・遺族は問う】（３）桶川ストーカー殺人事件、猪野憲一さん（６７）、京子さん（６８）　「娘の名誉回復のため」実名公開（1/3ページ） - 産経ニュース https://www.sankei.com/premium/news/180620/prm1806200004-n1.html
```

　刑事事件や刑事裁判で国家賠償を認める裁判は、ほとんど滅多にないとずっと前から情報を見ていました。ここ数年では、そのような国家賠償の訴訟提起というニュース自体を、ほとんど目にはしていないように思います。

　富山県氷見市の強姦の冤罪事件では、国である検察官の責任を認めず、富山県警である富山県の賠償責任を認めたという事例はありましたが、真犯人が自ら余罪を自供して明らかになったという冤罪事件でした。

　そもそも冤罪事件の国家賠償と比較するのがおかしいことだと気が付きましたが、事件捜査の被害者家族に対して警察の捜査の違法性を認めて賠償を命じたというのは、他に類例を見ていないと思ったし、今日まで気が付かなかったとすれば、不思議なことです。

```
　《京子さんは１２年、設立直後の全国犯罪被害者の会（あすの会）に参加。幹事を務めた。あすの会などの活動で、犯罪被害者等基本法が成立し１７年４月に施行。２０年１２月には被害者参加制度が導入され、被害者らが刑事裁判で被告に質問できるようになった》

［source：］【被害者・遺族は問う】（３）桶川ストーカー殺人事件、猪野憲一さん（６７）、京子さん（６８）　「娘の名誉回復のため」実名公開（2/3ページ） - 産経ニュース https://www.sankei.com/premium/news/180620/prm1806200004-n2.html
```

　上記の引用部分も今回初めてしったように思います。父親が映像や写真などに出ているのは見てきました。中にはテレビ番組も会った気がしますし、YouTube動画としても見ることがあったような気がします。母親の方が、具体化された積極的な活動をされていたとは全く意外でした。

* 『埼玉県のＡ子さん』、匿名では警察に都合の悪い事実は隠されてしまう、という桶川ストーカー殺人事件の被害者の父親の言葉

```
憲一さん「詩織の名前や写真を出すと、思い出がはじけてとてもつらい。でも、傷つけられた詩織の名誉を回復しようと思うと、『埼玉県のＡ子さん』ではだめなんです。匿名では警察に都合の悪い事実を隠されてしまう。つらいけれど、悲しいけれど、実名でなければ伝わらないことがあるんです」

　《憲一さんは１７年に癌が見つかったが、手術を経て今は体調も良好だ》

［source：］【被害者・遺族は問う】（３）桶川ストーカー殺人事件、猪野憲一さん（６７）、京子さん（６８）　「娘の名誉回復のため」実名公開（3/3ページ） - 産経ニュース https://www.sankei.com/premium/news/180620/prm1806200004-n3.html
```

　すべて引用はしなかったですが、父親に癌が見つかり手術をしていたというのは、これも初めて知ったお話かと思います。警察に対する不信感は根強いものがあることを改めて感じましたが、実際の必要以上に警察が悪者にされたようにも思いますし、間接的に影響を受けてきた気もします。

　桶川ストーカー殺人事件といえば、ジャーナリストの清水潔氏ですが、今回、目にした３ページに分かれたネット記事からは、その存在感は全く伝わってきませんでした。

　確認をして驚いたのですが、上記の記事の日付が２０１８年６月２０日となっていました。もちろん今年のことです。これはちょうどテレビで、全国犯罪被害者の会（あすの会）の解散のニュースを見ていた頃のように思います。

　テレビニュースとして明確なものを見たという記憶は残っていないのですが、明け方に近いような深夜に、たまたま政見放送のような岡村勲弁護士の話す姿を見たことは、印象的に記憶に残っています。

　昼のテレビ、そこまで言って委員会NPだったと思いますが、光市母子殺害事件の遺族である本村さんの姿を数年ぶりに見たのも、その数日後だったように思います。途中から見たのか、番組の内容がいまひとつ理解できませんでした。

　Twilogで検索すれば、時期の特定が出来、他に思い出すこともあるかもしれません。

* 「全国犯罪被害者の会（あすの会）の解散」で「そこまで言って委員会NP」に出演していた光市母子殺害事件の本村洋氏のこと

　光市母子殺害事件といえば、思い出すのはモトケンこと矢部善朗弁護士（京都弁護士会）の主催していたブログのことで、そのコメント欄で、犯罪被害者について語るなら本村洋さんの爪の垢でも煎じて飲め、などと言われたこともありました。

　本村洋も大きな存在感があり、メディアを通じた影響力もあったと思いますが、私としては同時に、加害者となった少年や、その父親について思いを馳せることもありました。

　モザイクが掛かっていましたが、私はその光市母子殺害事件の加害者の父親の姿をたまたまテレビで見ることがありました。余りテレビを見ない時期でもあったので、なおさら鮮明に記憶に残っていますた。たぶん平日の２３時ころからの放送だったニュースZEROの放送だったように思います。

　前にも書いたことがあると思いますが、父親がインタビューのような取材を受けていたのは、少し岩場があるような海の浜辺でした。山口県光市なので、地理的に考えて、瀬戸内海の可能性が高かったとも思います。

　光市母子殺害事件の加害者は１８歳の少年として逮捕されたように思います。あと数日で１９歳という情報も見たような気がしますが、ここでは正確な情報ではなく、私の現在の記憶のままにあえて書いているつもりです。

　私は１６歳の時、昭和５６年８月２８日ですが、金沢少年鑑別所に入りました。非行歴のようなものはなかったので、普通は釈放されていたはずですが、たまたま母親が不在で連絡がつかなかったことと、取り調べで共犯者のことを頑なに否認したので、心情も悪く一緒に送られたようです。

　新聞では１３人の補導となっていたように思いますが、一人は成人だったので逮捕かもしれず、鑑別所に送られたのは５人でした。１人が１７歳の女子でした。女子は他に５人ほどいたように思いますが、取り調べだけで釈放されたようです。

　私の場合は５人全員、金沢中警察署から家庭裁判所に連れて行かれ、そこでいきなり鑑別所行きだと言われたのでびっくりしました。家裁だったこともあとで理解したことです。夕食より前の時間には小立野の鑑別所の独居房に収容されていました。

　それはそれでこれまでの事実関係の１つ、ひとコマでもあるのですが、次に金沢西警察署の留置場に収容されたのが平成４年の２７歳のときでした。留置場は３，４人の雑居部屋と聞きましたが、入ったときからいる間はずっと一人だったので、独居房のようでした。

　ずっと眠っていた体の記憶というのか、１６歳の時、金沢少年鑑別所の独居房に入れられたときの感覚がフラッシュバックのように蘇りました。長く続いたこともあるのか拘置所での独居房の生活は慣れましたが、１６歳から２７歳まで入り続けていたことを想像するだけで、途方のないことと実感しました。

　光市母子殺害事件の加害者の少年については、欲望と好奇心の並外れた大きさも想像されましたが、報道にあるように短期の数年で社会に戻れるという見通しの手紙を外に出したり、少年事件における刑事罰に対する見通しの甘さも際立っていました。

　なにがそのような少年の考え、人格形成に影響したのかと突き詰めて考えると、それは弁護士商売による宣伝効果の一種が最大の要因という結論に至ります。これは、小学校に上がる一年前に分かれた長男と、学年ではその一つ下になる次男の成長、行く末が心配されました。

　その思いと疑問をぶつけたのも、元検事ということを全面に打ち出していたモトケンこと矢部善朗弁護士（京都弁護士会）のブログでのことです。

▶ ツイート％motoken_tw（モトケン）％2018/12/11 21:05％ https://twitter.com/motoken_tw/status/1072462385380777985
&twitter(1072462385380777985){theme:light}
> @TGN54 私はかなり許容してしまうのですが。
> 受け子の処罰回避可能性は充分あるように思いますので。  
▶

　上記が確認したモトケンこと矢部善朗弁護士（京都弁護士会）の最新ツイートになります。そのあとにはリツイートが１つありました。たまに見かけてきた実名と思われる弁護士アカウントですが・・・、と書いたところでプロフィールには弁護士でなさそうなことがかいてありました。

　プロフィールに、主な仕事は科学ライターと書いてあり、直後に説明に導くようなホームページのリンクがありました。ぱっと見た感じ、宇宙のような雰囲気で、空に、とローマ字で書いてあるようですが、初めはソラリスの英語の綴りなのかと思いました。

　ソラリスというのは宇宙空間をイメージさせる言葉ですが、私にはUNIXのOSの１つとしてのソラリスの思い出があります。一度だけインストールをして使ったことがありましたが、当時の他のLinuxからはずいぶんと古臭く感じるようなデザインと不便さがありました。

　次がそのモトケンこと矢部善朗弁護士（京都弁護士会）の最新リツイートになります。

▷ リツイート→motoken_tw（モトケン）＞ohnuki_tsuyoshi（大貫剛）｜2018/12/11 21:20／2018/12/11 16:04｜https://twitter.com/motoken_tw/status/1072466067535134720 ／ https://twitter.com/ohnuki_tsuyoshi/status/1072386692156456960
&twitter(1072466067535134720){theme:light}
> RT @ohnuki_tsuyoshi: デマをデマとして「こういうデマを言ってる人がいた」と言うぶんには、デマの拡散とは言えない。でも「こういう話がある」とだけ書けば、自分の責任でその話を広めたとしか言いようがない。  

　モトケンこと矢部善朗弁護士（京都弁護士会）については、ここ最近もまるで復活祭でも行ったように、東日本大震災における原発事故、その放射能汚染問題に対する、独自の世界観を印象づける言葉の強いメッセージ性の高いツイートが散見されていました。

　モトケンこと矢部善朗弁護士（京都弁護士会）については、ここではあえて軽く触れた扱いにしておきたいと思います。小見出しに対応した軌道修正を行います。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「本村」の検索結果 - Twilog https://t.co/ADzrsKkOr9

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:43／2018-04-08 14:04 URL： https://twitter.com/kk_hirono/status/1072607819394891776 https://twitter.com/hirono_hideki/status/982846709003837441
&twitter(1072607819394891776){theme:light}
> そこまで言って委員会NP \n   \n  2018年4月8日（日）  13時30分～15時00分  の放送内容 \n   https://t.co/nUwVUkhHTX \n  緊急討論SP「犯罪被害者の声を聴く」▽国を動かした遺族の闘い・・・本村洋氏の19年… https://t.co/rKW08S6ORo
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:43／2018-04-11 00:03 URL： https://twitter.com/kk_hirono/status/1072607855512031232 https://twitter.com/hirono_hideki/status/983722254688124928
&twitter(1072607855512031232){theme:light}
> 「あすの会」解散という。録画再生した日曜日のそこまで言って委員会NP。１４時過ぎからの録画。直前に番組の内容に気が付き、録画を始め別の番組を視聴していた。本村さんが出ていたので不思議に思っていたが、これは納得。ネットではまるで見ていない情報。
◁◁◁
<hr />
[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年04月08日 - Twilog https://t.co/1vJaBbIhLq

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:45／2018-04-08 08:49 URL： https://twitter.com/kk_hirono/status/1072608219074322432 https://twitter.com/hirono_hideki/status/982767305355444225
&twitter(1072608219074322432){theme:light}
> Only Yesterday | 『おもひでぽろぽろ』 - YouTube https://t.co/d4qN9O4DsP
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:45／2018-04-08 08:50 URL： https://twitter.com/kk_hirono/status/1072608280046911488 https://twitter.com/hirono_hideki/status/982767596712771586
&twitter(1072608280046911488){theme:light}
> 20秒で登る高尾城址見晴らし台（金沢市） - YouTube https://t.co/Y0NgjwZzxu
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:45／2018-04-08 08:54 URL： https://twitter.com/kk_hirono/status/1072608361731026944 https://twitter.com/hirono_hideki/status/982768487893352448
&twitter(1072608361731026944){theme:light}
> 高尾城 - YouTube https://t.co/h4HvrVhrxR
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:45／2018-04-08 09:07 URL： https://twitter.com/kk_hirono/status/1072608401388175361 https://twitter.com/hirono_hideki/status/982771947913146368
&twitter(1072608401388175361){theme:light}
> 観音寺城 　歴史解説12分 - YouTube https://t.co/t8kxd2g8Hl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:46／2018-04-08 11:47 URL： https://twitter.com/kk_hirono/status/1072608580564606978 https://twitter.com/hirono_hideki/status/982812189420503041
&twitter(1072608580564606978){theme:light}
> 深澤諭史さんのツイート: "ほんこれ。 やたら，猜疑心を抱えていたり，絶対の保証がないと嫌だとかいう人は，弁護士を使う上で，すっごい損をしている。 その逆も又然り。… " https://t.co/r5u35OGsFI
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:46／2018-04-08 12:27 URL： https://twitter.com/kk_hirono/status/1072608638613770240 https://twitter.com/hirono_hideki/status/982822332249985024
&twitter(1072608638613770240){theme:light}
> 【Beyond 2020（47）】4万件の被災者の声を”希望”に変える弁護士 | 東北復興新聞 https://t.co/Unnx5PY9xH
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:47／2018-04-08 12:28 URL： https://twitter.com/kk_hirono/status/1072608719949709312 https://twitter.com/hirono_hideki/status/982822589021151232
&twitter(1072608719949709312){theme:light}
> 震災発生当時、内閣府に出向していた私は、「弁護士として何ができるのか」と自問自答していた。被災地では、全国から駆けつけた弁護士が無料の相談業務に奔走していた。聞けば相談件数はどんどん積み上がる一方で、その分析や活用に現場は手が回ら… https://t.co/ECNfqf83ij
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:47／2018-04-08 14:06 URL： https://twitter.com/kk_hirono/status/1072608778233765888 https://twitter.com/hirono_hideki/status/982847016895111168
&twitter(1072608778233765888){theme:light}
> 世界!ニッポン行きたい人応援団 \n   \n  2018年4月8日（日）  14時00分～14時55分  の放送内容 https://t.co/pIiekfvaVj \n  “合掌造り"と“畳"を愛すリトアニア人!憧れの五箇山に…感動1200年畳職人の伝統技
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:47／2018-04-08 15:02 URL： https://twitter.com/kk_hirono/status/1072608864816820230 https://twitter.com/hirono_hideki/status/982861199745343488
&twitter(1072608864816820230){theme:light}
> 例えば、2014年に広島市で豪雨による土砂災害が発生したときには、初日から多くの弁護士が現地に入って法律相談を実施。また熊本地震（2016年）の後にも、東日本大震災のデータベース化を参考に、相談内容を記録する取り組みが行われている。 https://t.co/Unnx5PY9xH
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:47／2018-04-08 15:04 URL： https://twitter.com/kk_hirono/status/1072608941220265984 https://twitter.com/hirono_hideki/status/982861636443582465
&twitter(1072608941220265984){theme:light}
> 災害関連死についても、指摘しておきたい。原則、各市町村に設置された委員会に認定されれば、遺族に災害弔慰金が支払われる。しかし、中には認定されず、訴訟につながるケースもある。認定方法のノウハウが少なく、基準が医学的な観点に偏りがちに… https://t.co/AA7PWi68Dg
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:48／2018-04-08 15:10 URL： https://twitter.com/kk_hirono/status/1072609020102500354 https://twitter.com/hirono_hideki/status/982863353092554760
&twitter(1072609020102500354){theme:light}
> 「きっと私たちが何とかしますので、あきらめずにお話を聞かせてください」。何の確証もなかったが、震災直後の多くの弁護士は、こう答えるしかなかった。弁護士でありながら、解決策を提供できない。あのときの忸怩たる思いを、仲間たちも私も抱え… https://t.co/j4QELNoMju
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:49／2018-04-08 15:48 URL： https://twitter.com/kk_hirono/status/1072609320699871233 https://twitter.com/hirono_hideki/status/982872898414133248
&twitter(1072609320699871233){theme:light}
> 2018-04-08_10.56.07＿遠島山公園・宇出津港・宇出津新港.mov: https://t.co/r0a0MWxEMm、@YouTube がアップロード
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:49／2018-04-08 15:49 URL： https://twitter.com/kk_hirono/status/1072609419777753088 https://twitter.com/hirono_hideki/status/982873085958176768
&twitter(1072609419777753088){theme:light}
> 2018-04-08_10.24.51＿遠島山公園・月見御殿.mov: https://t.co/T4dHpyapz1、@YouTube がアップロード
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-12 06:49／2018-04-08 18:27 URL： https://twitter.com/kk_hirono/status/1072609463562059776 https://twitter.com/hirono_hideki/status/982912759963648000
&twitter(1072609463562059776){theme:light}
> ダーウィンが来た！「神社の島へGO！青森ウミネコ物語」 \n   \n  2018年4月8日（日）  19時30分～20時00分  の放送内容 https://t.co/fNCj9dMd2n
◁◁◁
<hr />

　Twilogを見ながらいろいろと思い出すことがありましたが、その全てが同じ日に収斂されるというのは、数年前、東日本大震災も含めたNHK連続テレビ小説あまちゃん、の逆回転の場面を思い出しました。

　記憶が不鮮明だったので確認のため調べたところ、まるで虚構新聞のような情報が見つかりました。「あまちゃん」とは出ていないし、アキちゃんというのも天野アキ、というあまちゃんの能年玲奈という女優とは、違う人物のようです。

```
身近なものを見つけては壊すことで、物の大切さを、逆説的に教える新番組。その斬新な設定が受け「子どもが、物のありがたみを知るきっかけになった」。「コップやお皿を割らなくなった」という声が、続々寄せられた。

しかし実際は、物を壊してもすぐに逆回転（後述）して治せると勘違いした子供が続出。両親の結婚指輪を床に叩きつけダイヤモンドの部分が欠けたり、他人の家に置いてあった骨董品コレクションを右から左へ全て割りつくしたり、博物館に置いてあるティラノサウルスの化石を粉々に粉砕、玉砕し大喝采したりと被害が多発し、被害総額は3.6億円にもなっている。

2011年3月11日に東日本大震災が発生したため、4月より番組名が「じぇじぇじぇのぎょぎょぎょ」に変更されたうえで続けられた。

番組の流れ［編集］
アキちゃんとさかなクンが壊すものを探す。場を仕切る「見」の形の顔をしたおじいちゃんに壊してよいか尋ね、了解されれば、台の上からものを落とし粉々に壊す。その後、アキちゃんの超能力「逆回転」を使って、壊す前に戻す。落としただけで派手に壊れる坪や金魚鉢が主に壊されるようである。

出演者［編集］
アキちゃん - 天野アキ
超能力が使える女の子。
さかなクン - さかなクン
おじいちゃん
キーボードクラッシャー
キーボードを破壊することを専門としている。

［source：］見つけてこわそう - アンサイクロペディア http://ja.uncyclopedia.info/wiki/%E8%A6%8B%E3%81%A4%E3%81%91%E3%81%A6%E3%81%93%E3%82%8F%E3%81%9D%E3%81%86
```

```
１１２話
アキ（能年玲奈）はＧＭＴを辞めたことへの後悔から、春子（小泉今日子）とぶつかる。水口（松田龍平）が「だったらユイちゃん、どうなるの？もし、お父さんが倒れてなかったら、あのタイミングでユイちゃんと一緒に東京に来てたら、２人でアイドルになれてたかな」　アキ「当たりめぇだべ」　水口「でも、実際なってないでしょ、今２人とも。あれから、もうすぐ１年になるよ。
「もし」とか「誰のせい」とか言ってたら、１年なんかあっという間に過ぎちゃうんだよ。
ズルとかインチキとか、アキちゃんも俺もそんな事、言える身分じゃないんだ。せっぱ詰まってんだ」ととりなして、前向きに仕事に挑戦することになる。
アキは子ども向けの教育番組「見つけてこわそう」にさかなクンと出演して、人気が出る。
一方、北三陸にいるユイ（橋本愛）は夏休みに夏（宮本信子）とともに東京に遊びに行く計画を練っていた。
アキに予備校のＣＭの出演依頼が来る。しかし、契約は恋愛禁止が条件。ないしょで種市（福士蒼汰）とつきあい始めていたアキは言い出せない。

［source：］連続テレビ小説　あまちゃん　第19週・後半　「おらのハート、再点火」 ： こんなテレビを見た。 http://blog.livedoor.jp/konnnatv/archives/32047639.html
```

　ようやく確認できる情報がみつかりました。考えてみると天野アキというのは、あまちゃんのドラマでの主人公の名前だったように思います。そういえばと思い出せる程度ですが、あのさかなクンがドラマに出演していたというのは、湿気った花火のようにくすぶったままの記憶です。

　時刻は７時１９分です。録画のためにテレビをつけ、連続テレビ小説の予約取り消し操作をしたタイミングで、チャンネルが変わったのか、ユーチューバーの「はじめしゃちょー」という人が出てきました。名前はしっていましたが、全く初めて見る人の顔でした。

　確認するとチャンネルはNHKでした。昨夜は１時過ぎにテレビを消しましたが、zeroからの延長だったので、チャンネルはテレビ金沢になっていたはずです。切る前のテレビのチャンネルが、電源を入れた時に映るというのが当たり前のことだと思ってきたし、間違いはなさそうに思います。

　テレビで何度かみていた有名ユーチューバーは「ヒカキン」という人だったと思います。いくつかの番組で見てきました。NHKもあったかもしれません。「はじめしゃちょー」についてはテレビで見たのが初めてなので、民法ではまだ見ていないように思います。

　「はじめしゃちょー」については、何かで話題になっているのを見かけたのですが、話題のことは思い出せません。今回は、人気ナンバーワンのユーチューバーとして紹介されていましたが、数カ月全く名前を見かけていなかったので、すっかり忘れていました。

　連続テレビ小説の録画ですが、連続テレビ小説まれ、の頃から毎回録画の設定にしていたのですが、録画機器のリモコンでは次回の放送しか取り消すことが出来ません。大河ドラマの毎回録画の解除は成功したように思うのですが、やりかたがよくわからないままです。

　２０１８年４月８日のことで何より驚いたのは、当日の日曜日の午前中に、遠島山公園に行き、月見御殿から離れ島まで散策していたことです。その日のうちにYouTubeに動画をアップロードしていたようです。実は、今もだいぶん前の撮影の動画が、いくつかそのまま残っています。

