#+TITLE: "Microsoft　Office365の環境が整った直後のSSDの故障"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-13 09:29:07 +0900
FILE_NAME: 2019-09-13-092907_Microsoft　Office365の環境が整った直後のSSDの故障.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: Windows10
記事タイトル名の文字数：35　保存ファイル名の文字数：57

* Microsoft　Office365の環境が整った直後のSSDの故障
  :LOGBOOK:
  CLOCK: [2019-09-13 金 09:41]--[2019-09-13 金 10:54] =>  1:13
  :END:

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: Windows10

＞＞＞ 2019-09-13（金曜日）09：41 ＞＞＞

　昨日の9月12日、次のツイートととしてTwitterに投稿した直後になりますが、Windows10で作業を始めてすぐ深刻なエラーが出て起動が出来なくなりました。BIOSの画面から先に進めず、よく見るとBIOSがSSDのディスクを認識していないことがわかりました。

TW kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時： 2019/09/12 14:36 URL： https://twitter.com/kk_hirono/status/1172021070905262080
> RT uwaaaa（サイ太）｜fukazawas（深澤諭史） 日時：2019-09-12 10:51／2019-09-12 10:51 URL： https://t.co/B51UlJn4gV https://t.co/1W9EzPlEgq

　Windows10はつい最近、半月ほど前までほとんど使っていなかったこともあり、回復ディスクの作成を行っていませんでした。8月の終わり頃から集中的にWindows10を使うようになったのですが、ようやく環境が整ったという矢先にSSDにWindows10のシステムが全滅しました。

　なぜこのタイミングで故障をしたのか不思議ですが、この先、Windows10で作業を進めデータの編集が必要な時期に故障をしていたならばもっと痛手は大きかったともいえます。

　それまで使っていたメインのLinux（Ubuntu）のシステムもSSDに入れていたので同じく全滅しましたが、昨夜のうちにインストールをし直して、データを含めほぼ全面復旧に至っています。

　8月の終わり頃から個人的ではない目的でWindows10を使うようになったのですが、データのバックアップをしっかり管理する態勢を強化していたので、それがさっそく大いに役立ちました。個人的ではない必要なデータも無傷です。

　その個人的ではない目的や用事については、いずれ書くときが来ると思いますが、今しばらくは前提となる目的や作業を優先して進めたいと考えています。おいおいと折りに触れることもあるかもしれません。

　SSDが故障する前日か前々日に、一晩をかけて「Microsoft Teams」の設定を済ませていました。法クラの弁護士らのツイートで、裁判所が訴訟のオンライン会議にTeamsというものを採用するような話を見かけていたのですが、使う機会がこんなに早く訪れるとは想定外でした。

　SSDの買い替えでDSP版のWindows10を購入するには消費税を含めると2万円ぐらい必要になりそうです。個人的ではない用事でWindows10を使うのは来年の3月以降のことになり、ちょうど今回、秋祭りで行ったパソコンの作業も一通り済ませたところだったので、それも幸いでした。

　Windows10のWordもExcelも2017年の7月以来、ほとんど使うことはなく、まもなく一つだけOfficeがインストールされていたノートパソコンのWindows10を削除して、Linuxの専用機としたので使うにも使えませんでした。

　Office365となっていますが、WordもExcelもずいぶん使いやすく機能も進化していると感じました。

　ただ、Windows10の環境自体は、慣れたLinuxの環境に比べると、未だ作業がずいぶんと非効率でストレスも高まります。Windows10が優れているのは他にATOKの日本語変換ぐらいです。

　WSLでWindows10のなかでUbuntuも使えていたのですが、セレクションが使えないのも難儀しました。範囲選択でクリップボードにコピーされてしまうか、設定を変更すると無視されるだけでした。調べたのですが解決方法も見つからず、不便に感じない人がいないのか不思議でした。

　セレクションというのはテキストを範囲選択することで、次に中ボタンクリックでテキストの貼付けが出来るというLinuxでは定番の機能ですが、このセレクションの値は「xsel -o」としてプログラムの処理でも使えます。

　私は、そのセレクションの値を、プログラムを使ったブログ投稿のタイトルとして使ってきたのですが、Windows10のWSLでは、「xsel -b」となるクリップボードの値と同じになってしまうので、Linuxの環境で行っていた処理が出来なくなり、ずいぶん効率が悪くなりました。

　Windows10でSSDが壊れる直前は、ずいぶんとパソコンの処理が遅く重く感じていたのですがその前から、データベースの操作などネイティブのLinux環境の10倍ぐらい時間がかかるように感じていました。

　もともとずっと前にインストールして全然使わないようなアプリもけっこうあったので、そのあたりも負担にはなったいたのかと考えます。Ubuntuでもずっと使い続けていると調子が悪くなるので、半年に一回は、システムを入れ替えて使っています。全面以降も一日あれば十分です。

　Windows10のようにウィンドウを次々クリックしながらアプリをインストールすることもないので、作業の手順を記録しておけば、台本のように同じ処理が繰り返されます。変更点に対応を迫られることはありますが、それも半年ぐらいという周期で経験を重ねるようにしています。

　Windows10は何かと手間と時間のかかる環境だと改めて痛感しました。バッチ処理で行う方法も調べればあるのかと思いますが、少なくともアプリは個別のインストールが手作業として必要になるかと思います。慣れないこともありましたが、時間を沢山使った上での、SSDの故障でした。

＜＜＜ 2019-09-13（金曜日）10：54 ＜＜＜

