#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "告発に至る経緯／書面作成／パソコン／告発状開発環境としてのAtomエディタ"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-11-17 07:43:10 +0900
FILE_NAME: 2018-11-17-074310_告発状開発環境としてのAtomエディタ.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  Atom プログラム
記事タイトル名の文字数：37　保存ファイル名の文字数：4

#contents

* カーソルのある行のコピー

　このファイルを作成したのが１１月１７日の土曜日で、すぐに中断をしていました。ようやくAtomから外部プログラムの実行で現在行をTwitterに投稿できるようになったと一息ついていたのですが、すぐに問題があることに気がついたからです。

　時刻は１１時２９分です。確認すると７時５０分にツイートをしてから中断をしていました。ツイートするため、行の文字数を確認する関数を作ろうとしたのですが、うまく行かず試行錯誤をしていました。

　atomエディタでは、ウィンドウの下にあるステータスバーにカーソル位置の文字数が表示されるのですが、ウィンドウを分割して表示すると、ファイル名などの文字列の表示が優先され、文字数が表示されていないことに気がついたのです。

　結局、現在行の文字列をコピーする関数と、現在行のテキストをツイートに投稿する関数のメッセージに、文字数を表示させるように変更しました。

　初めに現在行の文字列をコピーする関数を自作で作成しました。ネット上から情報を集め、試行錯誤でやってみたのですが、英語の情報がわずかにみつかるだけで、思い通りの結果を得ることは出来たのですが、仕組みが他のプログラムに比べわかりづらいものとなっています。

　他に方法がありそうですが、処理は申し分なく早いです。関数というよりはメソッドになるのかと思いますが、内容は次のものとなっています。

>|javascript|
  linecopy() {
      var ed = atom.workspace.getActiveTextEditor();
      ed.moveToBeginningOfLine();
      ed.selectToEndOfLine();
      ed.copySelectedText();
      ed.moveToEndOfLine();
      var cnt = ed.getLineCount();
      var point = ed.getCursorBufferPosition()
      var text = ed.lineTextForBufferRow(point.row);
      atom.notifications.addSuccess("LINE: " + text.length);
  },
||<

　メッセージを表示させる部分は後で追加したものですが、行をクリップボードにコピーするという目的の機能は、一時再開した前日の昼前であったように記憶にあるので、先週の金曜日のことになります。このメソッドはF8（ファンクションキー）などに割り当てています。

* Atomエディタでの自作パッケージのキーバインド（ショートカットキー）

>|javascript|
{
  "atom-workspace": {
    "ctrl-alt-o": "kk-package:toggle",
    "f12": "kk-package:copylinetweet",
    "f9": "kk-package:linecopy",
    "nonconvert l": "kk-package:linecopy",
    "insert": "kk-package:linecopy",
    "f2": "kk-package:linecopy",
    "f10": "kk-package:getTweet",
    "f8": "kk-package:lineCnt"

  }
}
||<

　上記にはうまく動いていないキーもあります。設定の再読込をすると、特定のキーが反応せず、別に登録済みのキーを一度使用することで、他の登録キーが有効になることがあります。他のプログラムでは経験のないことですが、最初はこのクセがわからず、余計なやり直しを繰り返していました。

　時刻は１３時２６分です。また３０，４０分ほどになりますか中断をしていました。また、独自のキーバインドが使えなくなったからで、その直前にスニペットを１つ作っていました。メニューからの操作でしたが内容は白紙だったので、新規にファイルを作成したのかもしれません。

　Linuxの場合、スニペットのファイルは「~/.atom/snippets.cson」になります。ファイルはもともとあったのかもしれないですが、内容は空っぽでした。そこにスニペットを１つ登録しました。次の内容になります。

>|javascript|
'.source.org-mode':
  'Hatena js':
    'prefix': 'hjs'
    'body': """
    >|javascript|
    $1
    ||<
    """
||<


　この書式ははてなブログのもので、ソースコードのシンタックスハイライトです。スニペットはEmacsでも使ってきましたが、これはずいぶん単純でわかりやすい構造となっています。

　テレビではバイキングが終わり、グッディが始まったところですが、台風が発生したということです。偏西風に乗るとあっという間に日本に来るという安藤優子さんの説明もありました。そのバイキングですが、意外なニュースがありました。

　数年前から気になっていた刑事裁判でしたが、今頃になって一審の判決が出たようです。スニペットとキーマップの問題に取り組みながら、その放送を見ていました。今日のバイキングには、意外なゲストの姿もありました。初出演という話も出ていたように思います。
　テレビではバイキングが終わり、グッディが始まったところですが、台風が発生したということです。偏西風に乗るとあっという間に日本に来るという安藤優子さんの説明もありました。そのバイキングですが、意外なニュースがありました
