#+TITLE: "告発に至る経緯／書面作成／パソコン／はてなブログのデータベースの作り直し"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-03-13 19:05:51 +0900
FILE_NAME: 2019-03-13-190551_はてなブログのデータベースの作り直し.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  はてなブログ データベース
記事タイトル名の文字数：36　保存ファイル名の文字数：40

#contents

＞＞＞2019-03-13（水曜日）19：07＿［これからの記述範囲の開始時刻］＞＞＞

　データベースの作り直しをしました。データの重複した投稿があったため、URLのカラムにユニーク属性をつけようとしたのですが、そこでURLに重複があることに気が付きました。データベースへの登録時に重複はチェックしていたのですが、結果として紛れていました。

　データは5618件あったと思いますが、データベースを作り直したあとは5587件となっています。IDもいったん削除して振り直しをしたので、これまで掲載してきたIDとは違っていると思います。また、このIDは投稿順にはなっていません。

　誤算だったのはデータベースへのデータの登録時の日時が全て失われたことです。すべてデータベースを作り直した本日2019年3月13日の日付日時となりました。正確にはデータベースではなくテーブルの作り直しになるのですが、データはそのまま全て移行できるものと思っていました。

　記事のタイトルとURLのタイトルの対応は崩れていないはずなので、リンクとしての機能に問題はないと考えています。昨日、付加した短縮URLもそのまま引き継がれているはずです。短縮URLを使ったことで、一覧の表示もずいぶんすっきり見やすくなりました。次が最新の10件です。

```
[10024]  % get-db-hatena-short-url.rb | tail -n 10
5578： ＃＃＃　東京弁護士会会報「LIBRA」に掲載された「坂本弁護士殺害事件と弁護士業務妨害」という特集、ダウンロード可のPDFファイルに含まれず http://bit.ly/2XTECje
5579： ＃＃＃　深澤諭史弁護士の「「所詮は地裁だし」は正しいの？控訴審のルールって？」から落合洋司弁護士の「どこにも持って行き場のない検事が集まった廃棄物中間処理場」 http://bit.ly/2XTECje
5580： ＃＃＃　「準強姦で起訴の男性会社役員に無罪判決　地裁久留米支部 - 毎日新聞」というニュースに対するモトケンこと矢部善朗弁護士（京都弁護士会）の反応 http://bit.ly/2XTECje
5581： ＃　石川県警察提出に係る再捜査要望書作成に至る経緯及び本書の構成と位置づけ http://bit.ly/2XTECje
5582： ＃＃　社会／カルロス・ゴーン氏 http://bit.ly/2XTECje
5583： ＃＃　社会／岡口基一裁判官 http://bit.ly/2XTECje
5584： ＃＃＃　紀藤正樹弁護士のTwitterタイムラインから参議院議員の有田芳生氏が立憲民主党だと知った経緯 http://bit.ly/2XTECje
5585： ＃＃　金沢地方検察庁 http://bit.ly/2XTECje
5586： ＃＃＃　２０１９年３月６日のニュース：：：　カルロス・ゴーン被告の保釈釈放　森友学園籠池夫妻の初公判　清原和博氏、厚労省の依存症啓発イベントに登場 http://bit.ly/2XTECje
5587： ＃＃＃　「12人の国選弁護人に支払われた弁護士報酬は計4億5200万円」と知ったオウム真理教事件、教祖の刑事裁判と、ひな祭り：本文 http://bit.ly/2XTECje
```

　IDの5587が登録として最新となっていますが、現時点で最新の編集からの投稿は5580になります。これはファイルの投稿時点での階層位置に関係しますが、編集済みの位置に追加で挿入したことで、さらにファイルの内容を新規にまるごと投稿したことで順序がこのようになっています。

　プログラムでの処理ですが、しっかりした参照データの規則性がないため、かなりトリッキーな方法を用いています。全て自分で管理できるデータであれば、そうでもないのですが、はてなブログのデータや書式に依存しているため、難儀が生じており、今後も起こる可能性があります。

　昨日の夕方は、12月にアメーバピグが終了するという残念な情報がありました。サービス継続を断念した理由は、FLASHという技術の終了によるとのことです。サービスや技術の終了や変更には、これまでも対処してきましたが、これもまた常につきまとう問題です。

　今回のデータベースの件は、初期の設計のミスとも言えますが、常に試行錯誤でやってきたことです。これからも柔軟に対応していきたいところです。

＜＜＜2019-03-13（水曜日）19：33＿［これまでの記述範囲の終了時刻］＜＜＜

