#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "告訴の事実／平成6年／福井刑務所／福井刑務所での服役、受刑生活の始まり"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-18 11:16:13 +0900
FILE_NAME: 2018-12-18-111613_福井刑務所での服役、受刑生活の始まり.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  福井刑務所 宗像三女神 若杉幸平弁護士 ひるおび 八代英輝弁護士 富岡八幡宮
記事タイトル名の文字数：35　保存ファイル名の文字数：40

#contents

* 宗像大社の神職が飲酒運転で逮捕されたというテレビの情報番組「ひるおび」

　ちょうどこのエントリーのファイルを作成しているタイミングでした。「福井刑務所での服役、」とまで入力し、その続きを考えていたところでした。

　以前にも似たようなニュースがあったのですが、ただ一つの番組でのみ取り上げているのを見たように思います。そちらも神社関係者でしたが、不法投棄の容疑だったと思います。宮城県の金華山の神社でした。記録から探し出せると思います。

```
[10074]  % pp -p |grep 金華山 |head -n 1
[link:] 2018-11-12_113213＿テレビの画面・独自　国立公園に不法投棄　宮司ら逮捕　金華山黄金山神社　宮城・石巻市.jpg  http://hirono2014sk.blogspot.com/2018/11/2018111407582018-11-120850182018-11.html#20181112113213
```

　どうも番組名をファイル名に入れるのを忘れていたようです。たまに画面の字幕で番組名がわからず、編集までに時間があって思い出せないため、番組名を入れないことはあります。ニュース番組だと番組名がはっきりせず、いれないことが多いかもしれません。

　時刻は11月40分です。今見ているテレビのニュース番組も画面を見ていて番組名がわからないと思っていたのですが、リモコンのデータボタンで確認するとMRO放送でした。番組表には「N　ひるおび！　JNNニュース字」などとあります。

　自衛隊の海外派遣について平成史を振り返るような特集をやっていましたが、平成3年1月に始まったのが湾岸戦争と呼ばれる戦争で、当時の総理大臣が海部総理であることがわかりました。

　テレビのチャンネルを石川テレビに変更しました。いつもと同じニュース番組ですが、こちらも画面の字幕で番組名はわからず、同じくリモコンの番組表で確認すると「FNNプライムニュース」となっていました。

　前に書いたと思いますが、11時30分ころには、バイキングの放送開始の見忘れを防ぐため、気がついた段階で石川テレビに変更するようにしています。リモコンで見るだけの番組予約をすれば済む話ではありますが、そうまでしたいとか考えてきませんでした。

　私はバイキングという情報番組を、社会の鑑、世相の反映として見るようにしています。11時55分から始まる番組ですが、冒頭に「今日のラインナップ」というのが出ます。2,3週間ほど前までは「今日のニュース」となっていました。

　「今日のラインナップ」になってからずっと画面の2分割のような2項目だったのですが、今日は4分割になってニュースの3項目と、スタジオの3人の映像となっていました。

　冒頭で司会の坂上忍さんが、「きょう火曜日は・・・」と言ったので、曜日ごとにテーマの違いもあるのかと思ったのですが、そのあと「怒　世間が衝撃！　話題の炎上ニュース5連発」というこれまでに何度も見覚えるのある字幕となっています。

　一昨日の札幌の爆発事故の後だったと思いますが、香港のバス事故が出てきて、なにかと思いながら見ていたのですが、運転手がバスから降りた直後にバスが動き出しました。

　運転席に不審者か好奇心の強い子どもが乗って運転を始めたのかと思ったのですが、そこは坂道の下り坂で走り出したバスが突き当たりの大通りの商店街のような店に突っ込んでいました。

　運転手はバスが動き出してすぐに、まるでバスと相撲でもとるように正面で食い止めようとし、そのまま姿がみえなくなりました。そのあとナレーションで4人が死亡し、運転手を含む○人がけがをしたと出ていました。

　日本でも建物に車やトラックが突っ込むという事故の報道がたびたびあり、大破していても余り死者が出たというニュースは見てこなかったのですが、それほど大きいとは思えなかった衝突現場で4人が死亡したようです。

　ここでも思い出したのは、元検察幹部の高齢弁護士のレクサスでのアクセス踏み違え事故のことです。本人は踏み違えを認めていないような報道を見たようにも思うのですが、実際に怪奇現象のように事故が起こりうるのかもと考えたことはあります。

　今日の「ひるおび」の宗像大社の神職の飲酒運転逮捕のニュースですが、意外な発見だと思ったのは宗像大社が交通安全の神社であったことです。交通安全のお守りの発祥のようなことも紹介していました。

　宗像三女神の田心姫命が祀られる奥津宮のある沖ノ島は、古くから海上安全の信仰があることはネットで調べて知っていました。田心姫命の字も田霧とされ、海の安全をおびやかす海上の霧を意味すとるとのことです。

* ホームページにある、湍津姫神（たぎつひめのかみ）をお祀りする中津宮、の七夕信仰

```
季節の風物詩「七夕」。
中津宮七夕祭は鎌倉時代まで遡ることができ、七夕伝説発祥の地といわれています。 「正平年中行事」（1346）には「七月七日、七夕虫振（むしふり）神事」とあり、境内にある牽牛社（けんぎゅうしゃ）、織女社（しょくじょしゃ）に参籠（さんろう）し、水に映る姿によって男女の縁を定める信仰があると記されています。

［source：］宗像大社 公式ホームページ　｜　宗像三宮 沖津宮・中津宮・辺津宮詳細 http://www.munakata-taisha.or.jp/html/sangu_syosai.html
```

　つい先程最初に読んだ時は気がつなかったのですが、「中津宮七夕祭は鎌倉時代まで遡ることができ、七夕伝説発祥の地といわれています。」とあります。

　七夕はよく知られていますが、仙台の七夕まつり、が全国的にも有名かと思われます。七夕の由来や発祥について調べたこともなかったのですが、杜の都とも呼ばれる仙台のイメージが強かったように思います。

　私は長距離トラック運転手の仕事で仙台にもよく行った時期がありました。正確には同じ宮城県の塩釜市と石巻市の鮮魚の定期便が金沢市場輸送の仕事のメインだったのですが、仙台市内は通過の他、荷降ろしも東北では一番多くありました。

　塩釜、石巻間の移動というのも多く、塩釜のとなりには松島という観光地があって、日本三景の１つとして知られている場所だと思います。そこは、ほとんどトラックで通過するだけでしたが、能登の恋路海岸や見附島の店をそのままスケールアップしたような観光地の風景がありました。

　たしか、昭和56年の夏に大ヒットした「みちのくひとり旅」という曲に「月の松島、しぐれの白河」という歌詞があったかと記憶にあります。先日テレビで、その松島から見える月が特別であることを番組で紹介していました。どんな番組だったのかは思い出せません。

[link:] 2018-11-26_205621＿テレビの画面・この秋コレが見たくて日本に来ました！ベスト２５　第８位　宮城県　松島.jpg  http://hirono2014sk.blogspot.com/2018/12/2018120313262018-11-260959392018-11.html#20181126205621

　「松島」で絞り込みの検索をすると、次の女子駅伝が出てきましたが、その数日前に福岡県の宗像市の辺りであった女子駅伝で、這いつくばったままタスキを渡し、なぜ棄権させなかったのかと問題になっていたことを思い出しました。

[link:] 2018-11-25_115654＿テレビの画面・女子駅伝日本一決定戦・クイーンズ駅伝2018　LIVE　宮城県松島町.jpg  http://hirono2014sk.blogspot.com/2018/11/2018112512312018-11-230351102018-11.html#20181125115654

　確認したところ、次の写真に、「日本を代表するお月見スポット」と字幕が出ていました。

[link:] 2018-11-26_205841＿テレビの画面・この秋コレが見たくて日本に来ました！ベスト２５　第８位　宮城県　松島.jpg http://hirono2014sk.blogspot.com/2018/12/2018120313262018-11-260959392018-11.html#20181126205621#20181126205841 

　星空がきれいに見える場所というのは聞いたことがありました。能登町の旧柳田村にある、やなぎだ植物公園がその百選に選ばれているというのをその周辺で見かけたように思います。

　確認のため調べているのですが、４つの小惑星が発見され、1999年10月9日に初めて発見されたものは能登半島からNotoと命名されたとのことです。初めて見た話ではないような気もしますが、たぶん地元の能登町でも余り知られてはいなさそうな情報です。

```
満天星で発見された小惑星は、2010年6月21日時点で次の4個である。大きさはどれも十数キロと考えられている。

（20625）Noto
発見： 1999年10月9日、命名登録： 2001年5月9日、公転周期： 5.04年
満天星で発見し、最初に登録された小惑星である。Notoは能登半島の能登から命名された。
アメリカの天文学者パーシバル・ローウェルが北陸・能登を旅して書いた旅行記「NOTO-能登・人に知られる日本の辺境」にちなんだ命名でもある。

［source：］星の観察館満天星 - Wikipedia https://ja.wikipedia.org/wiki/%E6%98%9F%E3%81%AE%E8%A6%B3%E5%AF%9F%E9%A4%A8%E6%BA%80%E5%A4%A9%E6%98%9F
```

```
星の観察館「満天星」の館内にあるプラネタリウムは、2011年にリニューアルされ4,000万個の星とドームいっぱいに広がる映像が写しだされます。美しい能登の星空を学芸員が解説してくれる「星の観察会」もあります。季節によって変わる星空は日常から離れて心を癒してくれます。

［source：］星の観察館「満天星」｜その他｜能登半島-能登町観光ガイド http://www.notocho.jp/experience/1535/
```

　調べていて初めて知ったのですが、やなぎだ植物公園にある満天星というのはプラネタリウムのことだったようです。天体の望遠鏡があるのかと思い込んでいたように思います。

　前に書いていると思いますが、私がプラネタリウムで思い出すのは、ただ一つ、宇出津小学校のときの修学旅行のことです。当時はスーパーカーショーというのも話題になっていましたが、似たような仮設の施設のように思えたプラネタリウムの会場でした。

　金沢市の泉野のあたりにあったと思います。金沢市内に土地勘がなかったときに、その場所を車で通りかかった時、このあたりに間違いないだろうと思いました。プラネタリウムがあった場所です。

[link:] » 能登 天の川 - Google 検索 https://t.co/n6KCNd1Ejf

<hr />

　検索していると「能登　天の川」というキーワードが出てきました。天の川はミルキーウェイとも聞いたように思いますが、日本で身近に見れるものとはしらなかった気がします。季節と気象条件が必要であるとは考えられます。

　なにかで情報を見たようにも思いますが、日本で星空がきれいに見える場所というと、長野県や岩手県の遠野市、雫石町がイメージされます。遠野市についても銀河鉄道の夜のことなどで、これまでに書いてきたことがあると思います。

　雫石町は、現在、民間の水道供給が社会問題となり、今日のバイキングでも取り上げられていました。本当は今日が供給停止の期日で、昨日、住民側の弁護士が食い止めるための仮払いをしたようなニュースがあり、弁護士と思われる男女2人の姿も出ていました。

　よく考えてみると、宮城県の松島の場合、月そのものというよりは、月と一緒にみえる樹木の風景などが特別な趣として愛でられてきたのかと思いました。

　仙台といえば、「青葉城恋唄」というヒット曲があり、ここ最近もテレビでみたことがあります。歌は歌っていなかった気がしますが、歌を歌っていた人が、番組に出て青葉城から紹介している場面がありました。

　私が初めて仙台に行ったのも昭和59年、金沢市場輸送の4トン保冷車でのことで、その頃も広瀬川や青葉城という曲の歌詞に出てくるイメージがありました。広瀬川は看板が出ていましたが、青葉城というのは仙台市内のどのあたりにあるのか今もわかりません。

　長距離トラック運転手の仕事で行った仙台というのは、ほとんどが国道4号線と国道45号線の周辺で、山形県の天童市から国道48号線を通行することもありました。地図をみると国道48線だと仙台市内の中心部付近を通るようです。

　ずっと前には書いたことがあると思いますが、一度だけ、タクシーで仙台市内の繁華街に飲みに行ったことがありました。金山さんに誘われてのことです。仙台のトラックステーションからタクシーで行きましたが、かなり距離があるように感じました。

* ミヤネ屋のテレビ電話中継で出演している遠藤誉氏、『卡子（チャーズ） 出口なき大地』を金沢刑務所の受刑中に官本で読んだこと

　今日はいつも以上にテレビには集中しておらず、情報番組グッディとミヤネ屋の間で気が向く度にチャンネルを変えていたのですが、そこにテレビ電話での中継と思われる遠藤誉氏の姿がありました。ずっと画面右下に小さな枠として時折、表示されています。

　途中から見たように思うので、最初のところはわからないのですが、一度も画面一杯で表示されることはないようです。テレビ電話だと思いますが、それにしては生中継のような通常の画面と見分けのつかない映像です。枠が小さいのもあるのかもしれません。

　遠藤誉氏は、一年ほど前まで北陸朝日放送のワイドスクランブルでスタジオ出演しているのをちょくちょくと見ていましたが、最近はすっかり見かけなくなったと思い、健康面を含め気になっていました。それというのも歴史の生き証人のような人物だからです。

```
遠藤 誉
（えんどう ほまれ）
生誕	1941年1月3日（77歳）
 満州国新京
（現： 中華人民共和国吉林省長春市）
国籍	 日本
研究分野	物理学、社会学
博士課程
指導教員	東京都立大学
主な受賞歴	読売ヒューマンドキュメンタリー大賞優秀賞（1983年）
プロジェクト：人物伝
遠藤 誉（えんどう ほまれ、1941年1月3日［1］ - ）は、日本の女性物理学者、社会学者、作家。東京福祉大学国際交流センター長、筑波大学名誉教授、理学博士［2］。

［source：］遠藤誉 - Wikipedia https://ja.wikipedia.org/wiki/%E9%81%A0%E8%97%A4%E8%AA%89
```

　遠藤誉氏について調べ、上記と同じwikipediaのページを見たのも初めてとは思えないのですが、今回は昭和16年生まれの77歳と知って、思ったよりずいぶん若い人だったのだと感じました。

　大学の名誉教授ということは知っていましたが、物理学者というはずいぶん意外でした。理系ということになりますが、文系の専門家という思い込みがあったように思います。社会学者というのも少し意外でしたが、政治や国際関係となると納得できます。

　時刻は15時35分です。先ほどよりミヤネ屋は、「速報　樹木希林さん　助演女優賞受賞」などとなっています。久しぶりに関連した情報をテレビでみましたが、今年はテレビで取り上げられる機会と時間がとても多かった人物だと思います。

　午前中の予定では、今日のうちに「寺内貫太郎一家」というドラマについても取り上げておきたいと考えていたタイミングでした。本当は違ったドラマという可能性もあるのですが、つい最近まで私は過去の記憶をいくつか混同させていました。

　Mozcで日本語変換が出来なかったので「きききりん」とGoogle検索したのですが、昭和18年11月15日生まれという情報が検索結果の要約にみえます。芸能人の訃報というのは他にもいくつかありましたが、その度に、昭和11年生まれの安藤健次郎さんのことが気にかかります。

　安藤健次郎さんは12月生まれなので1月生まれという遠藤誉氏とはちょっと違ってくるかもしれないですが、単純計算で5歳違い、私と被害者安藤文は、昭和39年と昭和45年で6歳違いでした。

　平成13年中になるかと思いますが、金沢刑務所の官本で『卡子（チャーズ） 出口なき大地』という本を読みました。ずっと昔の話だと思いながら読んでいたのですが、その傷害事件の被害者ともなっていた安藤健次郎さんより年下だったというのは違和感すらおぼえます。

　「約30万人の民衆が餓死に追い込まれた。長春包囲網を生き残った7歳だった遠藤は当時の飢餓極限状態の実録として『チャーズ 中国建国の残火』を出版している [6]。」と先ほどのwikipediaにはあります。

　どうやら幼少期の思い出を本に綴られていたのだと思いますが、本を読んでいるときも少女時代という時代背景は理解しながら読んでいました。ただ、7歳というのは、ずいぶん小さい頃の体験だったのだと、今回認識が改まりました。

　私の人生に置き換えると、7歳というのは昭和46年に相当します。昭和45年の大阪万博のことは前にも書きましたが、ずいぶんぼやけた薄い記憶となっています。女子と男子の成長の違いのことは、昨日あたりもテレビで問題とされていました。個人差もあるはずです。

　昭和46年ということで改めて思い出したのですが、どんたく宇出津店に買い物に行ったとき気になる曲が流れていて、家に戻ってから調べると「あわてんぼうのサンタクロース」というような曲名で、昭和46年となっていたので驚いていたのです。

　初めて耳にする曲だと思ったのですが、どうも曲調に昭和46年代の子供の頃に耳にしていたような懐かしさがあり、コンピューターのデータ処理で制作されたAIつまり人工知能の産物なのかとも考えたのです。

　官本のことですが、同じ頃には「ある紅衛兵の告白」というような本も読みました。文化大革命の時代だったので、それも昭和40年代の回想を綴った本なのかと思われます。

　ここ半年ほどのことでしょうか、昭和40年代のことを思い出したり、考えることが多くなりました。他に強く記憶に残る言葉として、沖縄返還、キューバ危機、水俣病、四日市ぜんそく、日中国交回復、ベトナム戦争、連合赤軍などがあります。

　以前、Googleで調べたときキューバ危機については、昭和30年代の終わりとなっていたようにも思います。新たに思い出しましたが、アポロ宇宙や月面着陸というのも強く印象に残るものでした。ゴジラの映画も昭和40年代の後半であったように思います。

　記述に専念していると、他のツイートを投稿したり、いつもの弁護士アカウントのタイムラインのツイートを閲覧することすらままならぬのですが、作業の手を止め深澤諭史弁護士のタイムラインをみていました。

　見る度に、考えたり、記録しておきたいという衝動に駆られることが日常化しているのですが、いちいち対応しきれないというのが現実であり、閲覧に用した時間というのも果たしてどうなのかと、過ぎゆく時の虚しさを感じることもしばしばでした。

　このエントリーは「福井刑務所での服役、受刑生活の始まり」というタイトル、テーマから出発しています。旅行でたとえるならば、急行の停車する駅がエントリーに、その駅の間の無人駅が小項目に相当するイメージかと思います。

　しかしながら、テーマの設定と選択の対象にはいまだに思い悩むところがあります。いまだに弁護士鉄道の宇宙空間をさまよい続け、掌の上を転がされているような気がしないではないからです。孫悟空のようなイメージです。

* 弁護士鉄道の大きな停車駅としての福井刑務所での生活の始まり

　弁護士鉄道という人生のレール、それは弁護士の思惑と打算が膨れ上がった全知全能の世界観ではないかと考えるようになりました。彼ら弁護士は、その装置の価値と生産性を社会の基盤として作り上げ共有し、共有しているとも考えられます。天井のない大きな工場でもあります。

　現在の弁護士業界において、その弁護士としての希望と理想を推進し、強力に牽引していると思われるのが深澤諭史弁護士です。深澤諭史弁護士の見る世界には、その裏側にある人間社会の不条理をプラネタリウムのような宇宙観で大きく映し出しているようにも思えます。

　不条理という言葉を思い出すのとほぼ同時に、先ほど取り上げてご紹介したばかりの遠藤誉氏の『卡子（チャーズ） 出口なき大地』には、「不条理のかなた」というサブタイトルが付いていたような気がしてきました。

　確認のためGoogle検索したところ、次のような意外な情報が見つかりました。直接的な答えにはなっていない気がしますが、質問は「遠藤誉（えんどう　ほまれ）著 「不条理のかなたに」 が読みたい。」とあります。

```
回答プロセス
(Answering process)	
①本市システムで検索し、ヒットしなかった。
②著者について、インターネットのウィキペディアを見たところ、「不条理のかなたに」は1983年に「読売ヒューマンドキュメンタリー大賞」の優秀賞を受賞した作品であることが分かった。
③国立国会図書館サーチ、NDL‐OPACでの検索により、「不条理のかなた」という題で 『こぶしの花』 に収録されていることが分かった。
④『こぶしの花』を検索したところ、本市図書館には無く、栃木県立図書館に所蔵されていることが分かった。
⑤栃木県立図書館に連絡をして、『こぶしの花』に「不条理のかなた」が入っていることを確認していただき、貸出を依頼した。

［source：］遠藤誉（えんどう　ほまれ）著 「不条理のかなたに」 が読みたい。 | レファレンス協同データベース http://crd.ndl.go.jp/reference/modules/d3ndlcrdentry/index.php?page=ref_view&id=1000136206
```

　あまりはっきりした情報は見つかっていないのですが、先ほどのwikipediaに「不条理のかなたに」という部分が含まれていたようです。たぶん目を通していたように思うのですが、気が付かなかったように思います。

```
1983年、『不条理のかなたに』で読売ヒューマンドキュメンタリー大賞優秀賞を受賞し、日中社会の社会学的考察に基づいた社会評論や自伝小説などを発表。

［source：］遠藤誉 - Wikipedia https://ja.wikipedia.org/wiki/%E9%81%A0%E8%97%A4%E8%AA%89
```

　「卡子」という書名のことを捜していたので、軽く読み飛ばしていたように思います。元は新聞の連載だったというような情報も見かけているので、よくある加筆編集を加えたかたちで出版されたのが、私が官本で読んだ「卡子」だったのかもしれません。

　チャーズについては、はてなダイアリーで、羽咋市に住んでいた平成21年3月以前にも記述したことがあったと思いますが、当時は「卡子」という特殊な漢字をパソコンで扱うのは容易でなかったようにも思われます。

```
数年前にも遺跡の大発見を繰り返していた大家の学者の捏造が発覚し、その方面の学界で大問題になったニュースがありました。
　あまり詳しいことは知らないのですが、第二次世界大戦終結後、国民党だったかの蒋介石と、共産軍の毛沢東が大きな内戦を繰り返し、毛沢東が勝利し、台湾に逃げた蒋介石が別の国を作りいまの台湾に繋がっていると習ったように思います。
　この大規模な内戦で間接的に大きな被害を受けた人々がいて、その一人の日本人が書いた「チャーズ」という本を金沢刑務所の官本で読み、深く考えされられるとともに影響を受けました。本当の本のタイトルは、上下という文字を一つにあわせたような一文字に「子」と書いた二文字なのですが、この文字はパソコンで入力不可能だったように思います。
　ちょっと「はてな」の「はまぞう」で調べてみます。


〓子(チャーズ)―出口なき大地

作者： 遠藤誉
出版社/メーカー： 読売新聞社
発売日： 1984/01
メディア： ハードカバー
クリック： 8回
この商品を含むブログ (3件) を見る
　見つかりました。上に表示されるはずですが、カバーの画像は出ていないようです。著者は、とても有名になった「大地の子」の作者を相手取り、著作権侵害だったかの裁判を起こし、判決も出ているはずです。数年前ネットで調べたところ、著者は茨城県の大学で先生（あるいは教授か助教授）をされているようでした。
　世間の注目を集めたホリエモンこと堀江貴文被告が東京拘置所を出た直後、山崎豊子氏の「沈まぬ太陽」という本を読んで痛く感銘を受けたらしく、登山に行ったなどとテレビで紹介されていました。拘置中には「史記」かあるいは「十八史略」も読んでいるようなニュースを観ましたが、そちらの方はあまり印象が薄かったのかもしれません。
　私はこれも金沢刑務所の二度目の拘置所生活のとき官本で、次の本を読み、とても面白くて大きな参考になりました。

［source：］*1157027243*［司法全般］告訴事件の感慨（２００６．０８．３１） - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/entry/20060831
```

　インポートした、はてなのブログで検索したところ、チャーズに該当したのは上記の引用部分だけのようです。検索結果には他に「ソニー・ピクチャーズ」というヒット部分がありますが、金沢刑務所で視聴したフェイスオフという洋画のデータの一部のようです。

　金沢刑務所で服役したのは、懲役1年8月だったと思いますが、平成12年の11月の初めから翌13年の12月31日までという1年2カ月ほどの期間でした。未決の期間がそれほど長かったということも現すものです。もちろん満期出所です。

　フェイスオフの視聴は、5月のゴールデンウィークよりは後だったように思いますが、正確な時期は思い出せません。チャーズを読んだのとある程度近い時期であったとは考えられますし、最大以上に幅を広げたとしても1年前後のことです。

　本の画像がサムネイルとして商品表示されていますが、これも平成18年当時のコードで、はてな記法を使っているはずです。書籍やDVDに固有のなんとかIDかコードを使っていますが、ここ数年は見かけないものでした。

［link：］ 〓子(チャーズ)―出口なき大地 | 遠藤 誉 |本 | 通販 | Amazon https://www.amazon.co.jp/exec/obidos/ASIN/4643737808/hatena-blog-22/

　ISBNというコードを確認するため開いたページですが、どうやら「卡子ー出口なき大地」とwikipediaにあった「卡子　中国建国の残火」は、別の本だったようです。出口なき大地は昭和59年1月が初版のようです。中国建国の残火は平成24年12月7日となるようです。

　卡子（チャーズ）を読んでいてイメージしたのは「猿の惑星」という洋画でした。これも金沢刑務所の服役中で独居房のテレビでの視聴、それもビデオとして見たように思います。

　しかし、チャーズと猿の惑星の関係性については、これまで考えたことがなかったように思います。猿の惑星は、広大な大地、砂漠のような場所が映像として印象的でした。

* 金沢刑務所の受刑中で独居房のテレビで視聴した「猿の惑星」という洋画、弁護士業界という惑星で特異な存在感を示す深澤諭史弁護士

　猿といえば、私の頭にすぐに思い浮かぶのが数年前の深澤諭史弁護士のTwitterのアイコンです。以前は干支ごとにアイコンを変えていたようですが、2,3年前から現在のシン・ゴジラを模した「ベン・ゴシラ」に固定化となっています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 18:35／2018-12-18 18:34 URL： https://twitter.com/kk_hirono/status/1074961323148996614 https://twitter.com/s_hirono/status/1074960970609377280
&twitter(1074961323148996614){theme:light}
> 2018-12-18-183211_深澤諭史（@fukazawas）さん　｜　Twitterからの返信付きツイート.jpg https://t.co/5rOQbMCkBo
◁◁◁
<hr />

　リツイートとして掲載しましたが、まずは深澤諭史弁護士のTwitterアカウントのページのスクリーンショットの記録の最新版となります。

　2014年5月分のスクリーンショットの記録を調べたのですが、深澤諭史弁護士のTwitterと思われるものは見当たりませんでした。かなり急いで調べたので、見落としの可能性はあります。ＰＣ遠隔操作事件関係のものが散見されました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜tsundereblog（ツンデレブログ） 日時：2018-12-18 19:05／2018-10-29 14:43 URL： https://twitter.com/kk_hirono/status/1074968876155232256 https://twitter.com/tsundereblog/status/1056783475225718784
&twitter(1074968876155232256){theme:light}
> 吉田広志教授（北海道大学）の画像や学歴は？年収公開で話題に！ | 寄り道Express！ https://t.co/57ebX7oZwD
◁◁◁
<hr />

　スクリーンショットで深澤諭史弁護士の過去のアイコンを探すという作業中、ずっと前から気になっていたものの発見がありました。まるで井上陽水の「夢の中へ」の歌詞のようです。上記のリツイートにある「吉田広志教授（北海道大学）」のことです。

　名前も何も記憶になかったので捜し様もなくやる前から諦めていたのですが、北海道の大学の先生ということは記憶にありました。今回調べたところでは北海道大学教授となっていますが、違った役職として記憶していました。教授は最高位ともいえるでしょう。

　この続きもあとで取り上げたいと思います。Twitterのアカウントは残念ながら非公開設定となっていましたが、記録としてのスクリーンショットは制作済みです。

　時刻は19時35分です。買い物に出掛ける予定だったのですが、本降りの雨が続いているのでやめました。ネットの天気予報では19時から曇りマークとなっていました。炊飯を始めました、レトルトカレーで済ませることも考えています。

　急に消えることはないと思いますが、Facebookの「刑事訴訟愛好会」での苦い経験もあるので、とりあえずページのコピペをしておきます。

```
研究キーワード
新規性, パブリック・ドメイン, 用途発明, 補正・訂正, 専用品, 用尽, 大合議判決, 職務発明, 間接侵害, プロダクト・バイ・プロセス, 修理, 再生産, 消耗品, 記載要件, 医薬品延長問題, 物の発明と方法の発明, 発明のカテゴリ, 多機能型間接侵害, 修理と再生産, 多機能品, 侵害警告, 先願主義, 知的財産法
研究分野
法学 / 新領域法学
研究分野を全て表示する
職歴
2013年04月 - 現在
北海道大学大学院法学研究科（教授）
2003年07月 - 2013年03月
北海道大学大学院法学研究科（准教授）
2000年04月 - 2003年06月
吉田・近藤特許事務所（弁理士）
1993年04月 - 2000年03月
旭電化工業株式会社（職員（技術系））
職歴を全て表示する
学歴
2002年04月 - 2003年06月
北海道大学大学院 法学研究科 博士課程
2000年04月 - 2002年03月
北海道大学大学院 法学研究科 修士課程
1989年04月 - 1993年03月
埼玉大学 工学部 応用化学科
学歴を全て表示する
所属学協会
日本知財学会
工業所有権法学会
著作権法学会

［source：］吉田　広志 (法学研究科　法学政治学専攻　現代法講座) | 北海道大学の研究者（北海道大学研究者総覧） https://researchers.general.hokudai.ac.jp/profile/ja.GOk2aIQOZ8OTaf7czF7pmA==.html
```

　ページの更新日が2018年12月05日となっています。つい最近のことです。さきほど別のページで見たように思いますが、生年が昭和45年9月となっていたように思います。学年では私の６つ下になりますが、5年半ほど前の2013年4月に買い額教授となっていたようです。

　公然とブロックされた大学関係者がプロフィールが教授であれば、もっと記憶に残るなり、その後も観察するなどしていたように思うのですが、私はその場かぎりのスクリーンショットの記録だけで終わっていたように思います。

　そのブロックされたというのも小倉秀夫弁護士とのからみでした。研究活動や専門分野が小倉秀夫弁護士と同じ知的財産法というのも今回初めて知りました。ブロックされた時は意気消沈もあり、プロフィールを調べることもなかったように思いますが、後ほど確認します。

　時刻は19時52分です。出掛けるつもりだったので19時10過ぎぐらいからテレビは消しています。19時少し前にリモコンの番組表をみたところ、20時頃から「ものまね」番組があるようでした。見るだけ予約を入れています。

　テレビをつけるとNHKで、コブダイが出てきました。フランケンシュタインともいわれる海の大型魚です。コブダイではなくカンダイでした。ブループラネット全6回完全版と出ていますが、番組の内容はノーチェックです。

　見るだけ予約でチャンネルが自動で切り替わりました。そういえば夕方はテレビで初めて経験するような現象がありました。気になる特集のニュースを見ている時に、前触れも何もなくいきなり札幌の爆発事件の不動産会社の社長の記者会見に切り替わったのです。

[link:] » ブループラネット完全版 - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/AHtWZ9IWGJ \n 4K国際共同制作　ブループラネット完全版　第1集「熱帯から極地の海へ」 \n 2018年12月18日（火）  19時30分～20時15分  の放送内容

<hr />

[link:] » ものまねグランプリ - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/tG2pj5nekU \n ものまねグランプリ2018～ザ・トーナメント～ \n 2018年12月18日（火）  19時56分～22時54分  の放送内容

<hr />

　深澤諭史弁護士の過去のアイコンのスクリーンショットを探す作業に戻ります。

　トップバッターということになりそうですが、先日テレビでみた和田あき子のモノマネ芸人が、最近、48歳の先輩芸人の女性と結婚したという話が出ていました。かなりの年の差婚のようでした。男性が年上というのはよくありますが、珍しい気がします。

```
みはるは1997年に
デビューをしたものまね芸人。

［source：］Mr.シャチホコがみはると結婚！以前から嫁とし公開プロポーズ https://sarattosokuhou.com/entame/shachihoko-miharu/
```

　少し調べてみました。収入が上という結婚相手の先輩女性芸人は1997年がデビューのものまね芸人とあります。ちょっとテレビで見た記憶はなかったのですが、生年月日が1970年2月9日とあります。安藤文さんと同じ昭和45年ですが、学年は1つ上になります。

　テレビはCMに入ったところです。パソコンで作業をしながらちょこちょこと見ていましたが、まだ、司会者と審査員の姿を見ていないように思います。以前は島田紳助の司会でよく見たような気がしますが、名前も見かけなくなっていることに気が付きました。

　ものまね番組はここ最近で2回目だと思いますが、前回とはかなり違った雰囲気を感じています。ものまね番組というのは、刑務所での生活を、紅白歌合戦と同様、もっとも色濃く思い出すテレビ番組です。当時とはバラエティ番組もかなり変わったと感じています。

　司会者の姿を見ました。左の女性は見覚えのない人です。右の男性は、渡辺満里奈の夫ですが、名前などは憶えられません。メンバーの一人は珍百景の常連で、NHK連続テレビ小説ごちそうさん、で主人公の女性の父親役をしていました。

　結婚を申し込む回だけは見落としたのでよく憶えています。スマホのワンセグで放送をみるつもりだったのですが、チャンネル合わせの操作がうまくいかず、最初の方の声だけ聞こえて終わりました。小木港の西側の堤防にアジ釣りに行っていた時のことです。

［link：］ Mr.シャチホコ みはる 結婚相手が衝撃的過ぎた......画像あり - 気になる最新ニュース速報 https://kininaru-saishin-news.com/archives/11783

　上記のページは右クリック禁止でしたが、Mr.シャチホコという芸人の年齢が25歳であることは確認できました。23歳の年の差婚ということになるようです。行列のできる法律相談所に出ていた磯野キリコという女の人のことも久しぶりに思い出しました。

```
名前：磯野貴理子 (いそのきりこ)
本名：高橋貴理子
別名義：磯野貴理
生年月日：1964年2月1日
年齢：54歳
出身地：三重県
身長：155cm
血液型：A型
職業：タレント
活動期間：1980年～
事務所：ジャパン・ミュージックエンターテインメント
 

wikipediaで調べましたが・・・・・磯野貴理子さんはタレント、女優・・・・「コメディアン」と書いてありました！

［source：］磯野貴理子の2度目の離婚危機!?原因は旦那の浮気で若い頃がかわいい衝撃事実！ | まろぐ～marog～ https://marog01.com/isono-kiriko-talent/
```

　上記のページは右クリック禁止ではなかったです。前々回も同じだったのですが、このような感じのページはほとんどが右クリック禁止となっているので、範囲選択が出来た時はちょっと驚きました。

　磯野キリコではなく、磯野貴理子で本名も同じようです。三重県出身というのは見覚えがあります。生年月日が1964年2月1日となっていますが、これも私と生まれた年は同じ昭和39年になりますが、学年は1つ上です。落合洋司弁護士（東京弁護士会）も同じです。

　磯野キリコで調べて検索結果で思い出したのですが、磯野貴理子は脳梗塞からテレビに復帰していました。よく見ると本名は磯野ではなく高橋となっています。結婚したことで名前が変わった可能性も考えられますが、確かなことは不明です。

　行列のできる法律相談所という番組は今もやっているのだと思いますが、すっかりみていません。同じ時間に特に見たい番組があるわけでもないですが、なんとなく見る気がしなくなりました。いつから始まったか思い出せないですが、弁護士に対するイメージを変えた番組です。

　まだ深澤諭史弁護士のTwitterアイコンを含むスクリーンショットは見つからないですが、「'2014-06-18-235850_その「つぶやき」は犯罪です：　知らないとマズいネットの法律知識　（新潮新書）　[単行本].jpg'」というファイルを発見しました。

　ファイル名がシングルクォートで囲まれていますが、これは文字列に本来使えない特殊文字が含まれているためだと思います。2014年6月18日の時点で、エラーを起こさずファイル保存が出来ていたようです。

[link:] » 賞味期限が半年過ぎた、ちらし寿司の素（すし太郎）が出てきたんですが使え... - Yahoo!知恵袋 https://t.co/81vOdYZnoC

<hr />

　すし太郎の賞味期限が8月24日でした。ずいぶん前から目につくところに置いていたのですが、賞味期限は確認していませんでした。賞味期限はかなり長い商品だと思います。すし太郎で思い出したのは「法テラス太郎」です。

```
賞味期限切れのちらし寿司の素を食べるか食べないか、どのくらいまで過ぎたものなら食べるかというのは、個人の感覚で判断することになります。

賞味期限が一日でも過ぎたら食べない人もいれば、数カ月あるいは数年たっても食べる人まで、判断基準は様々です。

 

また、保存状態によっては、風味だけでなく安全面においても劣化してしまう可能性がないわけではありません。

［source：］ちらし寿司の素は賞味期限切れでも食べられる?いつまで大丈夫? https://news-trip555.com/2257.html
```

　なんか弁護士の利用に通じる個人差があるように感じました。どうしても弁護士に頼らなければならない場合と、訴訟自体を処分権として割り切るという立場の違いという幅もありそうです。そういう意味でも深澤諭史弁護士の弁護士必要論はとても参考になるものです。

　一青窈の「もらい泣き」という曲が、ものまね番組に出てきましたが、夕方にもテレビニュースで見ていました。3児を出産したというニュースであったように思います。懐かしい曲でしたが、平成17年となっていたように思います。

［link：］ 歌手の一青窈（42）が第3子を妊娠　2015年4月にギタリストの山口周平と結婚｜ニフティニュース https://news.nifty.com/article/entame/showbizd/12160-148351/

　出産ではなく妊娠でした。Googleで「一青窈」と検索を入れると、サジェストの検索候補に「一青窈　石川県」と出てきて、少し思い出しました。七尾市の近くの駅だったと思います。以前の私の検索履歴が残っていたのかもしれません。

```
質問者：ライムライト質問日時：2015/08/08 23：37回答数：1件
私は、現在、本を執筆中です。タイトルは仮題ですが、「なぜなぜどうして、毎日が自由研究」です。この本に、一青窈「ヒトトヨウ」の名字の由来について、栃木県の小山市内にある地名、神鳥谷「ヒトトノヤ」と関連して紹介します。私は埼玉に住んでおり、神鳥谷の道路標識の写真は撮りました。しかし、石川県の「鳥屋町一青」の標識は、遠くて撮れません。

［source：］一青窈のルーツの地、石川県鳥屋町「一青」の道路標識の写真を出版予定- その他(教育・科学・学問) | 教えて!goo https://oshiete.goo.ne.jp/qa/9040343.html
```

　この石川県鳥屋町というのは、平成11年に日雇い人夫の仕事で、町役場にコンクリート打設の仕事で行ったような記憶があります。同行者の若者に金沢市の泉中学校の話を聞いたことも印象にあります。「魔物が住む」というような話でした。生徒数もそれだけ多いのでしょう。

　インドネシアのスマトラ沖地震が12月に起こった翌年だったので平成17年の1月になると思いますが、半月から3週間ほど七尾市内のはずれの派遣先に通ったことがありました。羽咋市からだと七尾市内の手前側になったと思います。

　その七尾市への通勤の帰りに、鳥屋町だったと思いますが「どんたく」の店舗で惣菜など夕食を買って帰ることがありました。宇出津に戻ってもどんたく宇出津店にはほとんど行っていない時期だったと思います。

　「どんたく」は七尾市を拠点にしたスーパーで金沢市内にも店舗が出ていますが、石川県内のスーパーとしては後進だと思います。羽咋市の鋳物工場で一緒に仕事をしていたYさんが、どんたくは売れ残りが半額にならず、羽咋市のバローが羨ましいと愚痴を言っていたのが印象的でした。

　どんたく宇出津店では数年前から全てではないですが、惣菜は夜になると半額になっていることが多いです。たくさん残っているときと、ほとんど残っていない時の違いも大きいですが、店員のマナーもよく良心的な販売価格を含め店舗だと思っています。

　「どんたく」というのは福岡県福岡市の大きなお祭りの名前だったと思います。中学生になった頃、歴史の授業で福岡の貝塚遺跡を習ったのと同じ頃に、初めて知ったような言葉のようにも思う「どんたく」です。青銅器の名前だったような気もします。

　前に貝塚についてGoogleで調べたところ、福岡県という情報は貝塚という地名以外には余り見当たらず、東京都の大森という地名のことが多く出てきたように思います。しかし、私が授業で習ったのは、太宰府天満宮と同じ福岡県だったという記憶となっています。

　博多どんたくの、博多という地名ですが、個人的には中学生の頃に読んだ「東大一直線」という少年ジャンプの連載漫画の舞台としてのイメージが最初にあったように思います。その主人公、東大通は、そのまま現在の、深澤諭史弁護士に重なる漫画性があります。

　時刻は21時26分です。ものまね界の先駆者的な大御所と思われるコロッケが出ています。かなり久しぶりに姿を見たように思いましたが、ずいぶん前から余り変わっていない感じです。熊本県出身だったと思いますが、同じ頃のオウム真理教事件の松本智津夫教祖も同じ熊本県出身でした。

　コロッケがよくものまねをしていた八代亜紀という演歌歌手も熊本県出身であったような気がしますが、個人的には熊本県といえば、熊本市よりは鹿児島、宮崎への通過点でもあった八代市のことが記憶にあるぐらいです。その熊本市と八代市の間を最大被害地とする大地震が数年前にありました。

　その熊本の大地震のときも、とりわけて目を引きつけ、考えさせられたのが深澤諭史弁護士のタイムラインでした。多くはリツイートだったとも思います。火事場泥棒的なものを今でも心に刻んでいます。弁護士妖怪大泥棒神社の由来、来歴の1つです。

　なお、弁護士妖怪大泥棒神社の略称が奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)にある「弁護士泥棒神社」になります。弁護士の化け物じみた泥棒根性から子孫繁栄、家内安全、社会平和を守りたい、弁護士による社会汚染を除去する目的と祈願があります。

　弁護士妖怪大泥棒神社（略称、弁護士泥棒神社）は、インターネット上にのみ存在する実態のない存在ですが、日本古来の神々と信仰という社会全体の利益を考え、客観性を重視し、気になったことは調べなどの勉強もしており、資料として残すという作業も併せて行っています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜muramasanico（レイン村正） 日時：2018-12-18 21:49／2018-12-18 17:34 URL： https://twitter.com/kk_hirono/status/1075010061909471235 https://twitter.com/muramasanico/status/1074946018288889856
&twitter(1075010061909471235){theme:light}
> @kk_hirono 弁護士と不当要求の圧力県議ですね https://t.co/YYXno5S2bI
◁◁◁
<hr />

　返信を1つ頂いていたようなのでリツイートしました。岩手県雫石町の水道の件での住民側の弁護士と思われますが、名前などは調べておらず、お隣の秋田県の弁護士というのも意外でした。弁護士にしては珍しく温厚で誠実そうという印象は受けていました。

　秋田県で弁護士といえば、まっさきに思い出すのは弁護士の刺殺事件でしたが、拳銃を手にしている人から拳銃を奪取しようとするのが、警察官の喫緊の任務だったと思うのですが、事件はその合間に、拳銃とは別の刃物を手にした犯人に弁護士は刺殺されたようです。

　記憶に自信はなく、調べて確認する余裕はないとお断りで書いておきますが、一審で有期懲役だった判決が控訴審で無期懲役となり、裁判所はその理由を確定的殺意としていましたが、確定的殺意であれば、先に拳銃を発泡していたと考えられます。なお拳銃が本物か偽物かの情報も見つかりませんでした。

[link:] » 大越大輔　弁護士 - Twitter検索 https://t.co/uFngCEbi3f

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜muramasanico（レイン村正） 日時：2018-12-18 22:00／2018-12-18 17:54 URL： https://twitter.com/kk_hirono/status/1075012836185632771 https://twitter.com/muramasanico/status/1074951074140762112
&twitter(1075012836185632771){theme:light}
> 雫石騒動で、とりあえず吉田瑞彦法律事務所の大越大輔弁護士は信用ならない。東北電力に乗り込むのはいいが、東北電力担当者に一度会っただけで東北電力がコメントしていないにも関わらず交渉第一段階で電力供給の目処がついたとデマを吹聴している… https://t.co/Y8V1ZknWMZ
◁◁◁
<hr />

　後にしようかとも迷ったのですが、「大越大輔　弁護士」とTwitter検索したところ、見つかったのは上記のツイート1件のみでした。

　中断している深澤諭史弁護士の過去のTwitterアイコンですが、少なくともヤギと猿がありました。十二支にヤギがあったのか疑問にも思いますが、少なくとも私にはヤギに見えたという記憶として残っています。

　パソコンで深澤諭史弁護士の過去のTwitterアカウントのアイコンのあるスクリーンショットの画像ファイルを捜していましたが、ようやう1つを見つけました、意外なことにオレンジが下地のタマゴアイコンでした。アイコンの設定がない場合に表示されていたものです。

　それを含めて、非常上告-最高検察庁御中_ツイッター（@s_hirono）に画像つきツイートととしてAPIから投稿しました。次に、ここではリツイートとして他に作業の過程で副次的に発見したものと一緒にご紹介しておきたいと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:11／2018-12-18 22:06 URL： https://twitter.com/kk_hirono/status/1075015735653482503 https://twitter.com/s_hirono/status/1075014462371901440
&twitter(1075015735653482503){theme:light}
> 2014-06-19-000400_犯人は，さらに警察も遠隔操作して笑いものにしました。　しかし，今度は，警察が事前リークで，マスコミを遠隔操作しています.jpg https://t.co/v9qGpqiATs
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:11／2018-12-18 22:06 URL： https://twitter.com/kk_hirono/status/1075015754204893185 https://twitter.com/s_hirono/status/1075014427949158400
&twitter(1075015754204893185){theme:light}
> 2014-06-18-235850_その「つぶやき」は犯罪です：　知らないとマズいネットの法律知識　（新潮新書）　[単行本].jpg https://t.co/ovl735nFG7
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:11／2018-12-18 22:06 URL： https://twitter.com/kk_hirono/status/1075015774211694592 https://twitter.com/s_hirono/status/1075014396479365120
&twitter(1075015774211694592){theme:light}
> 2014-06-18-114122_@hirono_hideki　@Hideo_Ogura　そういう言い方はやめてほしいと思います。.jpg https://t.co/Ddo3UxASm1
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:11／2018-12-18 22:06 URL： https://twitter.com/kk_hirono/status/1075015796105990145 https://twitter.com/s_hirono/status/1075014365198180352
&twitter(1075015796105990145){theme:light}
> 2014-06-18-114023_ブロックした.jpg https://t.co/1oPG92pvnD
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:11／2018-12-18 22:06 URL： https://twitter.com/kk_hirono/status/1075015816985292802 https://twitter.com/s_hirono/status/1075014334248452096
&twitter(1075015816985292802){theme:light}
> 2014-06-18-113944_そういう言い方はやめてほしいと思います。少なくとも私にリプを送るのはやめてください。.jpg https://t.co/0HMOtSzx2S
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:12／2018-12-18 22:05 URL： https://twitter.com/kk_hirono/status/1075015839848423424 https://twitter.com/s_hirono/status/1075014303198064640
&twitter(1075015839848423424){theme:light}
> 2014-06-18-113852_そういう言い方はやめてほしいと思います。少なくとも私にリプを送るのはやめてください。.jpg https://t.co/Ab20LeuTQw
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:12／2018-12-18 22:05 URL： https://twitter.com/kk_hirono/status/1075015872115167237 https://twitter.com/s_hirono/status/1075014272277598209
&twitter(1075015872115167237){theme:light}
> 2014-06-18-113709_マスコミによって集中的に報道されるような事件を弁護人または代理人として担当すると、いわゆるリーク記事って.jpg https://t.co/NAOQz56vAA
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:12／2018-12-18 22:05 URL： https://twitter.com/kk_hirono/status/1075015895095771136 https://twitter.com/s_hirono/status/1075014239985623041
&twitter(1075015895095771136){theme:light}
> 2014-06-06-074834_検事時代に上司や先輩から受けた教育はどれも「弁護人がいかに問題のある弁護活動をしているか.jpg https://t.co/6zQ0Vr7RPm
◁◁◁
<hr />

　作業を続けます。テレビはCMに入っていますが、コロッケは対戦で負けたようです。たぶんトーナメント形式と思われますが、確認はしておらず、余り重要な話でもありません。ここで歴史に刻むのは第二東京弁護士会の深澤諭史弁護士です。

[link:] » 犯人は，さらに警察も遠隔操作して笑いものにしました。 しかし，今度は，警察が事前リークで，マスコミを遠隔操作しています. - Google 検索 https://t.co/lOFA37TCLs

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2018-12-18 22:16／2013-02-11 10:37 URL： https://twitter.com/kk_hirono/status/1075016852269555718 https://twitter.com/fukazawas/status/300780645884514304
&twitter(1075016852269555718){theme:light}
> 遠隔操作事件では，犯人が他人のＰＣを操作しました。犯人は，さらに警察も遠隔操作して笑いものにしました。 \n  しかし，今度は，警察が事前リークで，マスコミを遠隔操作しています。 \n  前の２つは珍しいケースでしたが，最後の一つは，何度繰り返されても誰も懲りないし反省もしません。
◁◁◁
<hr />

　深澤諭史弁護士には告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントに対してブロックを受けていないので、今回もリツイートが出来ました。

▶ ツイート％fukazawas（深澤諭史）％2013/02/11 10:37％ https://twitter.com/fukazawas/status/300780645884514304
&twitter(300780645884514304){theme:light}
> 遠隔操作事件では，犯人が他人のＰＣを操作しました。犯人は，さらに警察も遠隔操作して笑いものにしました。
> しかし，今度は，警察が事前リークで，マスコミを遠隔操作しています。
> 前の２つは珍しいケースでしたが，最後の一つは，何度繰り返されても誰も懲りないし反省もしません。  
▶

　ツイートとしては長文なのでどうかと思いましたが、TwitterAPIでもツイートの内容が全て取得できたようです。私が深澤諭史弁護士に対して、モトケンこと矢部善朗弁護士（京都弁護士会）や小倉秀夫弁護士と同等に記録してきた理由と必要性が、ここに十分現れていると思います。

　自分のYouTubeに投稿した動画のスクリーンショットとなっていましたが、小木港の堤防でカエルを見たのも不思議なことの1つでした。田んぼのない小木にカエルが出たのもありますが、そこまで偶然が重なるものなのかという思いがあり、神のお使いのようにも思えました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:31／2018-12-18 22:27 URL： https://twitter.com/kk_hirono/status/1075020624462934016 https://twitter.com/s_hirono/status/1075019736767811584
&twitter(1075020624462934016){theme:light}
> 2014-07-02-175547_小木港の堤防で片付けて帰ろうとしたら出てきたカエル＿2014年06月29日2.jpg https://t.co/2zEySfTyPx
◁◁◁
<hr />

　2014年6月29日が撮影日かと思われます。他にも九十九湾で手で捕まえた37センチのアジの写真、宇出津の遠島山公園で待っていたような蛇の写真と動画、今年の8月13日に小木港の東一文字堤防で泳いできたイノシシの写真と動画があります。いずれも公開済みです。

　しかし、最も不思議に思えたのは、今年9月の雨で中止となった柳田大祭の長い時間、燃えなかった松明の御幣のことです。柳田大祭の場所もその少し前まで柳田白山神社とは別に完全に勘違いしていました。そのあとしばらくして近くで死体遺棄事件も起こっています。

　「神様の目線でふざけたやつ」、これは平成21年9月の10日頃、当時の能登警察署で大家警部補に言われた言葉ですが、そのあと神様の目線でふざけたやつ、というのは弁護士のことに違いないと考えるようになり、神様の存在というのも次第に意識するようになり現在に至っています。

　今回のものまね番組は、4位から1位を一度に発表する王者決定戦だったようです。1位は神奈月という芸人でしたが、こちらも全くではないですが余り記憶にはありません。Mr.シャチホコは次点の2位でした。

　今回は時間軸を重視した記録としているので、さきほど記録したてのモトケンこと矢部善朗弁護士（京都弁護士会）のツイートもご紹介しておきます。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:57／2018-12-18 22:56 URL： https://twitter.com/kk_hirono/status/1075027206861012992 https://twitter.com/s_hirono/status/1075027063877189632
&twitter(1075027206861012992){theme:light}
> 2018-12-18-224915_モトケン（@motoken_tw）：バランスを崩している人が多すぎて、、、.jpg https://t.co/O55Ynd3WAn
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 22:57／2018-12-18 22:56 URL： https://twitter.com/kk_hirono/status/1075027262062288897 https://twitter.com/s_hirono/status/1075027095003119616
&twitter(1075027262062288897){theme:light}
> 2018-12-18-224948_モトケン（@motoken_tw）：論理的な思考が苦手な人は、相手の主張の論理が理解できないだけでなく、自分の主張の非論理性にも気づかない.jpg https://t.co/7KaqG4WXly
◁◁◁
<hr />

```
[10091]  % dp -p|tail -n 10|sed 's/$/\n/'
[link:] 2018年12月18日16時20分の登録： ＼サイ太　@uwaaaa＼だからモチベーションを上げるために妊婦加算を」って，医師のモラル凄いな http://hirono2014sk.blogspot.com/2018/12/uwaaaa_42.html

[link:] 2018年12月18日16時20分の登録： ＃サイ太　@uwaaaa＃のツイート／2018-12-05_1200〜2018-12-18_1511／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月18日16時20分 http://hirono2014sk.blogspot.com/2018/12/uwaaaa2018-12-0512002018-12.html

[link:] 2018年12月18日16時21分の登録： ＼深澤諭史　@fukazawas＼法科大学院の利権もポストもメンツも俺のもの・・・。 受験資格付与だけは誰にも譲りたくない、手放したくない・・・。 http://hirono2014sk.blogspot.com/2018/12/fukazawas_18.html

[link:] 2018年12月18日16時21分の登録： ＃深澤諭史　@fukazawas＃のツイート／2018-12-14_2015〜2018-12-18_1609／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月18日16時21分 http://hirono2014sk.blogspot.com/2018/12/fukazawas2018-12-1420152018-12.html

[link:] 2018年12月18日16時23分の登録： ＼渡辺輝人　@nabeteru1Q78＼「つかれて弁護士に相談する気力が無い」については、どういうことはあり得るが、ではなぜ、違法の可能性が高く、職務放棄して逃げ出すかも http://hirono2014sk.blogspot.com/2018/12/nabeteru1q78_18.html

[link:] 2018年12月18日16時24分の登録： ＃渡辺輝人　@nabeteru1Q78＃のツイート／2018-12-10_1028〜2018-12-18_1419／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月18日16時24分 http://hirono2014sk.blogspot.com/2018/12/nabeteru1q782018-12-1010282018-12.html

[link:] 2018年12月18日18時19分の登録： ＼モトケン　@motoken_tw＼このアカウントに対しては、これが全てだな。 被災地のことなんか何も考えてない。 自分の主張のためには、被災地の皆さんを嘲笑することも厭 http://hirono2014sk.blogspot.com/2018/12/motokentw_18.html

[link:] 2018年12月18日18時20分の登録： ＃モトケン　@motoken_tw＃のツイート／2018-12-13_1856〜2018-12-18_1737／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月18日18時20分 http://hirono2014sk.blogspot.com/2018/12/motokentw2018-12-1318562018-12.html

[link:] 2018年12月18日22時48分の登録： ＼モトケン　@motoken_tw＼バランスを崩している人が多すぎて、、、 http://hirono2014sk.blogspot.com/2018/12/motokentw_70.html

[link:] 2018年12月18日22時48分の登録： ＃モトケン　@motoken_tw＃のツイート／2018-12-14_0740〜2018-12-18_2048／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月18日22時48分 http://hirono2014sk.blogspot.com/2018/12/motokentw2018-12-1407402018-12.html
```

　テレビはzeroが始まったところです。2,3カ月前になるかと思いますが、司会者がNHKの元女子アナ、有働由美子さんに代わってから大文字だったZEROが小文字に変わったように思います。

　夕方に見た、アパマンショップの社長の会見をトップニュースにしているようですが、弁護士抜きの記者会見というのは弁護士的には無防備で突っ込みどころ満載に映るのかもしれません。

　ネットの情報では事故の火元となったアパマンショップはフランチャイズではなく直営店ということでしたが、社長というのも北海道でのことのようです。アパマンショップリーティング北海道などという字幕も出ていました。

　これは被害者の立場からみてもどうかのかと思ったのが、ローカスこと三浦義隆弁護士のツイートでした。三浦義隆弁護士のツイートの削除というのは、見かけていないと思うので今もあると思います。

▶ ツイート％lawkus（ystk）％2018/12/17 14:22％ https://twitter.com/lawkus/status/1074535349500534785
&twitter(1074535349500534785){theme:light}
> 爆発したアパマンって直営店なのか。なら余裕で賠償できるだろうから、被害者としてはフランチャイズじゃなくてよかったな。  
▶

　余り重要とも思えないので現時点での再確認はしていませんが、三浦義隆弁護士には告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントでブロックされているので、リツイートは出来ないと思います。

　他にも三浦義隆弁護士のTwitterタイムラインで気になったリツイートを含め、記録作業を行いました。いちいち取り上げていては際限がないのですが、今夜は特別です。zeroの韓国の扇風機おばさんと呼ばれた女性の訃報も気になるニュースです。整形の始まりは楽しい思い出の日本とも。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 23:26／2018-12-18 23:24 URL： https://twitter.com/kk_hirono/status/1075034581592612865 https://twitter.com/s_hirono/status/1075034190897278976
&twitter(1075034581592612865){theme:light}
> 2018-12-18-231426_ystk（@lawkus）：爆発したアパマンって直営店なのか。なら余裕で賠償できるだろうから、被害者としてはフランチャイズじゃなくてよかっ.jpg https://t.co/zwjPg91xGl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 23:26／2018-12-18 23:24 URL： https://twitter.com/kk_hirono/status/1075034598533464066 https://twitter.com/s_hirono/status/1075034159611965440
&twitter(1075034598533464066){theme:light}
> 2018-12-18-231349_ystk（@lawkus）：アポなしで来た新規相談者は勿論受けないし、既存の依頼者でもアポなしで来たら辞任を検討します。.jpg https://t.co/MdIRJALPcU
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 23:26／2018-12-18 23:24 URL： https://twitter.com/kk_hirono/status/1075034619253284864 https://twitter.com/s_hirono/status/1075034125084561409
&twitter(1075034619253284864){theme:light}
> 2018-12-18-231324_ystk（@lawkus）：嫌がらせ投稿はいけないが、仮にも法律ライターを名乗るなら、「死ねと言った相手がうつ病とかで自殺したら殺人」なん.jpg https://t.co/xE6LFX1NzY
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 23:26／2018-12-18 23:24 URL： https://twitter.com/kk_hirono/status/1075034637615988736 https://twitter.com/s_hirono/status/1075034093262233600
&twitter(1075034637615988736){theme:light}
> 2018-12-18-231105_ystkのリツイート（ささきりょう　@ssk_ryo）：年末にとてもいいものをもらった。来年は勝訴ラッシュになるだろう。.jpg https://t.co/lr5PboCuyX
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-18 23:26／2018-12-18 23:24 URL： https://twitter.com/kk_hirono/status/1075034655726825472 https://twitter.com/s_hirono/status/1075034060605468672
&twitter(1075034655726825472){theme:light}
> 2018-12-18-231036_ystkのリツイート（ノースライム　@noooooooorth）：やばいワイン達②.jpg https://t.co/vEMNmfigWr
◁◁◁
<hr />

```
[10094]  % dp -p|tail -n 6|sed 's/$/\n/'
[link:] 2018年12月18日23時11分の登録： ＼ささきりょう　@ssk_ryo＼年末にとてもいいものをもらった。来年は勝訴ラッシュになるだろう。 http://hirono2014sk.blogspot.com/2018/12/sskryo_18.html

[link:] 2018年12月18日23時11分の登録： ＃ささきりょう　@ssk_ryo＃のツイート／2018-12-01_1455〜2018-12-18_2048／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月18日23時11分 http://hirono2014sk.blogspot.com/2018/12/sskryo2018-12-0114552018-12.html

[link:] 2018年12月18日23時13分の登録： ＼ystk　@lawkus＼嫌がらせ投稿はいけないが、仮にも法律ライターを名乗るなら、「死ねと言った相手がうつ病とかで自殺したら殺人」なんて無茶苦茶なことを書くのはやめた http://hirono2014sk.blogspot.com/2018/12/ystklawkus_25.html

[link:] 2018年12月18日23時13分の登録： ＃ystk　@lawkus＃のツイート／2018-12-07_0919〜2018-12-18_1933／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月18日23時13分 http://hirono2014sk.blogspot.com/2018/12/ystklawkus2018-12-0709192018-12.html

[link:] 2018年12月18日23時17分の登録： ＼ノースライム　@noooooooorth＼フォアグラのテリーヌは王道の調理であるからこそ光る王道的な美味しさ。手前の玉ねぎのソースがフォアグラとこんなに合うとは知らなか http://hirono2014sk.blogspot.com/2018/12/noooooooorth_18.html

[link:] 2018年12月18日23時17分の登録： ＃ノースライム　@noooooooorth＃のツイート／2018-12-14_0953〜2018-12-18_2105／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月18日23時17分 http://hirono2014sk.blogspot.com/2018/12/noooooooorth2018-12-1409532018-12.html

```

　さきほどzeroの合間のCMで久しぶりに有村架純の東芝のCMのCMを見たのですが、ザ・ブルーハーツの「情熱の薔薇」は古さを感じさせない新鮮な曲です。平成4年になってからトラックのカセットテープでよく聴いていました。

［link：］ 有村架純、ブルーハーツ「情熱の薔薇」カバー　本家と“合唱”　東芝新TV-CM「未来をつくる人がいる」篇＆メイキング - YouTube https://www.youtube.com/watch?v=cZDEU28ym_E

　日本企業の努力を愚弄するようなツイートをたびたび見かけるのも落合洋司弁護士（東京弁護士会）と深澤諭史弁護士のツイートに共通した特徴です。夕方は戦時中のリツイートについても取り上げる予定でした。

　有村架純という女優についても書いておきたいことがいくつかあります。能登の富来を舞台した映画でも共演していた、あまちゃんの漁師役の俳優、蟹江敬三さんのこともありますが、銀河鉄道の夜は、「さらば弁護士鉄道」のモチーフの１つともなっています。

［link：］ 蟹江敬三さん『お別れ会』に700人参列　能年ら“あまちゃん”ファミリーも | ORICON NEWS https://www.oricon.co.jp/news/2037388/full/

　調べるとお亡くなりになったのは2014年3月30日のことであったようです。3月30日というのは・・・。フランスで思い出す、曲の日本語の歌詞にあった日付かと思われます。平成11年の秋だったと思いますが、金沢刑務所の拘置所によく流れていた曲でした。

[link:] » フランシーヌの場合 / 新谷のり子 - YouTube https://t.co/Sh5toRVXP8

<hr />

　これまでテレビなどでは一度も聴いたことのない曲ですが、これも昭和40年代という時代背景を感じさせる曲調です。曲の発売は以前調べたことがあったように思いますが、憶えてはいません。

```
「フランシーヌの場合」
新谷のり子 の シングル
B面	帰らないパパ
リリース	1969年6月
ジャンル	フォーク
レーベル	DENON
作詞・作曲	いまいずみあきら（作詞）
郷伍郎（作曲）
プロデュース	飯塚恆雄
チャート最高順位
オリコン4位
テンプレートを表示
フランシーヌの場合（フランシーヌのばあい）は、1969年6月に発売された新谷のり子のデビューシングル。いまいずみあきら作詞、郷伍郎作曲。フランス語のナレーションは古賀力（つとむ）［1］、プロデュースは飯塚恆雄。売り上げは80万枚［2］。

解説［編集］
1969年3月30日の日曜日、パリの路上でフランシーヌ・ルコント（当時30歳の女性）が、ビアフラの飢餓に抗議して焼身自殺した［2］。３月31の朝日新聞夕刊が小さなスペースでこの外電（AFP）を載せた。

［source：］フランシーヌの場合 - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%95%E3%83%A9%E3%83%B3%E3%82%B7%E3%83%BC%E3%83%8C%E3%81%AE%E5%A0%B4%E5%90%88
```

　上記のwikipediaのページをよく読むと、この曲も「あわてんぼうのサンタクロース」と同じで、日本人による作詞作曲だったようです。独特の旅情や哀愁を感じさせる曲で、歌詞も当時としては相当の覚悟と決意もあったと思われる政治的なものを感じさせます。

［link：］ ♪小坂恭子　「想い出まくら」 - YouTube https://www.youtube.com/watch?v=cSUo4OC6a8A

　YouTubeが自動再生となっているのですが、上記の曲は聴いたことのある曲ですが、歌い手の名前と映像は初めて見たように思います。何を基準にYouTubeが次の動画や自動再生の候補を選択肢ているのか不思議です。

［link：］ 面影　しまざき由理 - YouTube https://www.youtube.com/watch?v=4Jxke4DtTbQ

　これは以前再生したこともあったので次の動画の候補にあってもなっとくです。「Gメン’７５」という連続ドラマのエンディング曲として記憶にありますが、昭和４０年代に見ていたという記憶です。ドラマのタイトルは昭和５０年を意味していると思われます。

　時刻を見ると0時11分ということで日付が変わっていました。さきほどzeroが終わったテレビのテレビ金沢ですが、次の深夜帯のバラエティ番組に春日というタレントが出てきました。ここ数ヶ月テレビで姿を見ずすっかり忘れていましたが、全く変わらずに元気そうです。

[link:] » ウチのガヤがすみません! - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/zhGc4D0iXd \n ウチのガヤがすみません!【無敗の神童那須川天心&amp;春日VSガヤ芸人ガチンコ対決】 \n 2018年12月18日（火）  24時09分～25時04分  の放送内容

<hr />

　Gメン’75は刑事ドラマだったと思いますが、ボスというか主役だったと思われる丹波哲郎という俳優は、その後、大霊界というブームで一山当てたという感じでしたが、その後お亡くなりになったようです。思い出せませんが、もう思い出せないぐらいずいぶん前のことだと思います。

```
丹波 哲郎（たんば てつろう、1922年7月17日 - 2006年9月24日）は、日本の俳優・芸能プロモーター・心霊研究家。東京府豊多摩郡大久保町（現：東京都新宿区）出身［1］。身長175cm。血液型はO型。

俳優活動は50年以上で出演した映画は外国映画10本を含んだ300本以上に及ぶ名優［2］。テレビドラマでも活躍し、映画製作にも携わった。オールスターの超大作に相応しい映画では常連の一人として、権力者など上層部の人物役で特別出演もした。丹波プロダクション［注 1］・俳優養成所「丹波道場」を設立して後進の育成も手がけており、宮内洋は丹波の一番弟子である。

心霊学と霊界の研究もし、多数の書籍を著しており、『丹波哲郎の大霊界』はベストセラーとなった［2］。

［source：］丹波哲郎 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%B9%E6%B3%A2%E5%93%B2%E9%83%8E
```

　調べると平成18年9月24日にお亡くなりになっていたということですが、余りテレビを見ない時期だったので詳しいことは記憶にないと思います。意外に思ったのは84歳という没年齢です。1922年生まれとあるので大正11年生まれということになるようです。

　これも取り上げて置きたかったし、今後取り上げる予定でもあるのですが、加藤剛さんの訃報がきっかけでネットの動画として視聴した「砂の器」という映画では、事件解決を果たした刑事役でしたが、昭和40年代との記憶とは違いずいぶんと若く見えたのも印象的でした。

　上記のwikipediaには、興味深い次のエピソードも掲載されています。全部初めて知るものだと思います。昭和50年代も情報が乏しい時代で、特定の情報が流布、蔓延されやすい時代でした。大霊界は、そのあとだったようにも思いますが、ほとんど無関心でした。

```
心霊研究など［編集］
心霊学と霊界に造詣を持ち、霊界の存在を確信していた［2］。多数の著作をものし、年間20回以上の講演を行っていた。本人もロンドンのホテルで中国人女性の複数の霊に遭遇しており、これが死後の確信に変わる出来事だったと話す。子供の頃には、腐ったまんじゅうを食べて死にかけた時に、母親が自分の傍で自分の名を叫び続けているのをすぐ真上で見ていたことがあったと話していた［22］。なお、本人の公式サイトも霊界についてまとめたサイトになっている。
霊界の世界に興味を持ち始めたのは、ある俳優仲間の死であった。ある俳優仲間がガン宣告され、毎日のように「死ぬのが怖い」と連呼していたことから、彼の不安を和らげるために死後の世界について徹底的に調べようと思ったことがきっかけであった［36］［37］。
その他、催眠術への造詣も深く、自ら催眠術を操れたという。しかし『Gメン'75』などで共演の夏木によれば、実際に丹波の催眠術に掛かった人は見たことがない、丹波に気を遣い、催眠に掛かったふりをしていたのかもしれないとしている［38］。また自ら「催眠術は馬鹿と子供には掛からない」と話していたという（丹波義隆の談）［22］。
『人間革命』出演後、創価学会の大会に招待された際、創価学会の活動をさかんに顕揚する講演をした後で「南無妙法蓮華経」とすべきところを「南無阿弥陀仏」としめくくり、場内を騒然とさせた。丹波は著書に、自分のオッチョコチョイな性格を示す逸話として、この失敗談を載せている。

［source：］丹波哲郎 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%B9%E6%B3%A2%E5%93%B2%E9%83%8E#%E5%BF%83%E9%9C%8A%E7%A0%94%E7%A9%B6%E3%81%AA%E3%81%A9
```

　前に、丹波哲郎について調べていたときだと思いますが、YouTube動画の残り4分の1ぐらいのタイミングで、突然と内容が一変し、滋賀県大津市の近くの心霊スポットのような建物が出てきました。

　あとで調べたところ、大阪万博の前後の昭和40年代だったと思いますが、建設途中で工事が中断したマンションで、そこに幽霊が出るような話は、昭和59年に金沢市場輸送で長距離トラック運転手の仕事をしていた頃に聞いていました。よく通る国道161号線沿いでした。

　深澤諭史弁護士のTwitterのプロフィールのアイコンの変遷を記録したスクリーンショットから追うつもりでいましたが、ずいぶんと時間も掛かりそうなので、今回の小項目では継続を断念したいと思います。

　深澤諭史弁護士のタイムラインでは、リツイートですが、これぞ弁護士脳と思わせるツイートを見つけたので、とりあえずはそれをご紹介しておきたいと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜take___five（中村剛（take-five）） 日時：2018-12-19 00:43／2018-12-18 21:55 URL： https://twitter.com/kk_hirono/status/1075053869846061056 https://twitter.com/take___five/status/1075011786372313092
&twitter(1075053869846061056){theme:light}
> 「法律ではどうなってるか知らんが、社会常識としてはこうだろ」とか、「人の道としてはこうだろ」と言われるときのその人にとっての「社会常識」や「人の道」がロクでもない確率は異常。
◁◁◁
<hr />

　ちょっとマウス操作を誤ったのですが、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でリツイート出来ることが確認できた深澤諭史弁護士のリツイートの元のツイートです。

▷ リツイート→fukazawas（深澤諭史）＞take___five（中村剛（take-five））｜2018/12/19 00:01／2018/12/18 21:55｜https://twitter.com/fukazawas/status/1075043413664374785 ／ https://twitter.com/take___five/status/1075011786372313092
&twitter(1075043413664374785){theme:light}
> RT @take___five: 「法律ではどうなってるか知らんが、社会常識としてはこうだろ」とか、「人の道としてはこうだろ」と言われるときのその人にとっての「社会常識」や「人の道」がロクでもない確率は異常。  

　まさに惑星を思わせるツイートであり、それがリツイートとして集まるのも深澤諭史弁護士のタイムラインです。大敷網のような社会的歴史的資料として質の高い収穫性を期待を裏切らずに感じさせてくれます。

　深澤諭史弁護士のツイートやブログを見ていて時折思い出すのは、刑務所で視聴した「マスクマン」というようなタイトルの洋画です。最初に視聴したのは福井刑務所でしたが、2回目というのが記憶ではっきりしません。「絶好調」という言葉がキメ台詞のようでした。

```
『マスク』（原題： The Mask）は、1994年7月29日にアメリカ合衆国より公開されたコメディ映画作品。


目次
1	概要
2	ストーリー
3	登場人物
3.1	主要人物　
3.2	スタンリーの周辺の人物
3.3	ギャング
3.4	警察
3.5	その他の人物
4	日本語吹き替え
5	スタッフ
6	備考
7	脚注
8	外部リンク
概要［編集］
冴えない男が偶然に不思議な緑色の木の仮面を手に入れ、超人的な力を持った黄緑色の顔の怪人・マスクに大変身する物語。ダークホースコミックスのコミック『マスク（英語版）』が原作。

主演のジム・キャリーを一躍スターにのしあげた作品だが、ティナ役のキャメロン・ディアスも当時演技経験皆無の新人だったにもかかわらず、本作のヒロインに大抜擢され、デビュー作にしてトップスターの仲間入りを果たした。目玉や心臓が飛び出すなど漫画的なオーバーアクションを実写で表現し、『トムとジェリー』をそのまま実写にしたような雰囲気のスラップスティック・コメディ映画となっている。映像はSFXが駆使され、アカデミー賞で視覚効果賞にノミネートされた。

日本では、1995年2月25日に劇場公開された。1996年12月1日に東宝よりVHSソフトが発売されている。

［source：］マスク (1994年の映画) - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%9E%E3%82%B9%E3%82%AF_(1994%E5%B9%B4%E3%81%AE%E6%98%A0%E7%94%BB)
```

　ジム・キャリーという俳優の名前は記憶にあるのですが主演だったようです。マスクマンではなく「マスク」というタイトルだったようです。弁護士という資格を手に入れるのも似たようなことがありそうに思えます。人様に迷惑を与えない範囲なら無関心でもいられそうですが。

　上記のwikipediaでは日本で平成7年2月25日に劇場公開されたとありますが、福井刑務所でのテレビ視聴ではビデオ放送ではなく、テレビの映画番組の録画として視聴した記憶となっています。

　2週間ほど前にテレビで視聴した「鎌倉ものがたり」という映画も、上映がテレビで話題となっていたのも1年から2年ほど前であったような感覚でいます。地上波初放送となっていたように思いますが、平成ひと桁代には、地上波初放送という言葉は聞かなかった気がします。

```
『鎌倉ものがたり』（かまくらものがたり）は、『まんがタウン』（双葉社発行）に連載されている西岸良平の漫画作品。2017年7月現在、コミックスは34巻まで発行している。第38回日本漫画家協会賞大賞受賞作品。2017年12月に実写映画化された［1］。

［source：］鎌倉ものがたり - Wikipedia https://ja.wikipedia.org/wiki/%E9%8E%8C%E5%80%89%E3%82%82%E3%81%AE%E3%81%8C%E3%81%9F%E3%82%8A
```

　2017年12月というのはちょうど一年前になりますが、「実写映画化された」とあるだけで、上映の開始であったのかははっきり確認できない気もします。

　長距離トラック運転手の仕事をしていた平成の始め頃に、漫画で何度か見ていた作品の実写化だと最近になって知ったのですが、難度も見たという記憶も物語の内容も記憶もなかったのが、漫画アクションという余り見なかった媒体での連載と知り、納得しました。

　当初はビッグコミックかビックコミックスピリッツの連載であったように思っていました。その割には、内容に記憶がなかったので、どうかと思っていました。どちらもコンビニでの立ち読みよりは購入を優先していたという記憶があったからのことです。

　時刻は12月19日1時8分です。録画再生でテレビをつけているのかと思ったのですが、金曜日に「ホームアローン２」という番宣がありました。「鎌倉ものがたり」の次週予告が、福井刑務所で視聴したと思う「ホームアローン」でした。

　この小項目では、「猿の惑星」について書いておかないと次には進めません。切り替えをします。洋画の「猿の惑星」も総和40年代の後半にテレビで視聴したという記憶があるのですが、内容はほとんど理解できませんでした。とにかく大きく話題になっていた洋画でした。

```
『猿の惑星』（さるのわくせい、PLANET OF THE APES）は、1968年のアメリカ合衆国の映画。ピエール・ブールによるSF小説『猿の惑星』を原作とする『猿の惑星』シリーズ全5作の第1作。

［source：］猿の惑星 (映画) - Wikipedia https://ja.wikipedia.org/wiki/%E7%8C%BF%E3%81%AE%E6%83%91%E6%98%9F_(%E6%98%A0%E7%94%BB)
```

　調べたところ「猿の惑星」もシリーズ化されていて全5作があるようですが、私の記憶にあるのは、たぶん昭和43年とある第1作だけだと思います。思っていたより少し古い映画でした。劇場公開からテレビ放映までの当時の相場としてのタイムラグは不明です。

　親切なことに「TBS初回放送:1973年12月24日21:00-23:26『月曜ロードショー』※ノーカット　フジテレビ初回放送:1975年4月11日21:00-22:55『ゴールデン洋画劇場』(約98分)」という情報の記載までありました。

　当時の都会と田舎の放送日の違いというのも気になるのですが、同じだとすれば1973年12月24日の放送を見た可能性がありそうです。しかし、23時26分までの放送となると、途中で寝ていた可能性も高そうです。

　昭和48年は小学校の低学年ですが、当時は夜に眠いのを我慢するのも苦手でした。ただ、一度だけインスタントのコーヒーを飲みすぎて、眠れなくなって困っていたことを今でもよく憶えています。

　時刻は1時27分です。思い出したのですが、深澤諭史弁護士のTwitterのプロフィールの過去のアイコンの1つはヤギではなくヒツジでした。そういえば、日付の変わった昨日は、吉田羊という女優が休職するというテレビのニュースもありました。

　吉田羊という女優も連続テレビ小説まれ、の出演者だったと思いますが、役柄が思い出せません。それでもパワハラのような問題でマスコミの標的になったとき、これで「まれ」出演者の3人目なのかと思ったことを憶えています。

```
女優の吉田羊（年齢非公表）が１８日、自身のインスタグラムを更新。一時的に芸能活動を休業して英ロンドンに演技留学すると一部週刊誌に報じられたことについて「来年も日本でがんばります」と否定した。

［source：］吉田羊、芸能活動休止報道を否定　インスタで「来年も日本でがんばります」（スポニチアネックス） - Yahoo!ニュース https://headlines.yahoo.co.jp/hl?a=20181218-00000158-spnannex-ent
```

　情報の確認も兼ねて調べたところ、意外な情報が出てきました。いわゆるフェイクニュースという印象はまるでなかったですが、誤報だとすれば、それも原因や過程が気になるところです。

[link:] » 吉田羊　連続テレビ小説　まれ - Google 検索 https://t.co/G2vvYAS07V

<hr />

　上記の検索結果の4ページ目まで目を通したところですが、連続テレビ小説まれ、に吉田羊が出演していたという情報は確認できませんでした。もう少し調べますが、私の勘違いだとすれば、その原因も不思議です。HEROに出演していたという情報は少し見ています。

```
蔵本はる（くらもと はる）
演 - 鈴木砂羽
一子の母。美容師で美容院「サロン はる」を経営。東京への憧れから上京を画策する一子を危惧し、なんとか家業を継がせようとするが、一方で娘の意志を尊重し、東京での挑戦を応援する［注 69］。
後述するコーラス・グループ「うみねこ座」のリーダーでもある。

［source：］まれ - Wikipedia https://ja.wikipedia.org/wiki/%E3%81%BE%E3%82%8C
```

　どうも「鈴木砂羽」という女優をそのまま「吉田羊」として勘違いしたまま記憶していたようです。蔵本という作品中の名前にも記憶はないと思ったのですが、清水富美加が演じた一子の母親役だったようです。それほど似ていたとも思えないのですが、自分でも勘違いが不思議です。

　なんか調べてみると意外な情報が出てきました。Googleの検索ワードは「吉田羊　連続テレビ小説」です。

```
映像デビューに至るまで
福岡県久留米市で牧師の家庭に生まれ［5］、兄2人・姉2人の5人兄弟の末っ子として育った。子供の頃からお芝居のマネをしたり人前で歌を歌ったりするのが好きで、松田聖子や中森明菜のモノマネをしたり、トイレの中で一人芝居をしたり、誰かを演じるおままごとが好きで中学1年生までやめられなかった。久留米信愛女学院高校へ進学［6］［7］、3年生の時に体育祭で応援団長を務めて注目や歓声を浴び、後輩に慕われファンクラブのようなものもできるなど、後に女優を志すきっかけの一つとなった［8］［9］［10］。高校卒業後に久留米を離れ、女優を目指し高速バスにて上京［4］［11］［12］。金沢市内の大学に通う姉を頼って金沢で生活し、喫茶店でアルバイトをしていた時期もあった［13］［14］。

［source：］吉田羊 - Wikipedia https://ja.wikipedia.org/wiki/%E5%90%89%E7%94%B0%E7%BE%8A
```

　福岡県の久留米市で思い出すのは、チェッカーズの藤井フミヤとホリエモンこと堀江貴文氏です。久留米市は長距離トラック運転手の仕事でも行ったことが何度かありました。佐賀県のあとに福岡県に戻るので、他には余りないことで少し不思議な気分にもなっていました。

　「2008年に出演したNHK連続テレビ小説『瞳』」とありますが、全く記憶にないNHK連続テレビ小説です。瞳といえば思い出すのは「24の瞳」という昔の映画があるので、少しでも見ていれば記憶に残っていただろうと思います。

　完全に女優の名前と顔を取り違えていたようですが、もともと吉田羊という名前は見覚えや聞き覚えのないもので、ヒツジという漢字なのが印象に残っていました。羊といえばジンギスカンですが、札幌で食べた昭和60年以来、口にはしていない気もします。味も記憶にないです。

　ジンギスカンは長野県内でも食堂で見かけた記憶がありますが、当時は珍しかったと思います。今でも宇出津のスーパーで袋に入ったものは見かけると思いますが、売っている数は少ないと思いますし、ここ最近は見かけていません。

　北海道では牛や豚より食肉としてよく食べるという話は昭和59年当時にも聞いていましたし、ここ最近もテレビで見たことがあります。当時は気にしなかったですが、今は羊の肉と考えると少し抵抗があり、余り食べたいという気持ちはありません。

　北海道では豚丼というのも深夜のテレビショッピングで取り上げられていたことが記憶にあります。根昆布というのもありました。今は、その深夜の時間帯にテレビをつけていることが少ないので、見ることもありません。あの豚丼も美味そうで気になっていました。

　金沢刑務所で「猿の惑星」をテレビで視聴した当時、工場の官本には「惑星へ」というタイトルの本があって、それも気になっていました。手に取ることはあったと思いますが、借りることはなかったようにも思います。

　同じ金沢刑務所でも未決の拘置所にいるときとは違い、受刑者としての工場出役では、食堂の棚にある官本が、工場にいるときは毎日、入れ替えで借り放題だったので、とても恵まれた環境にいるようにも感じていました。雑役の人にお願いするだけのことでした。

```
太陽系の果てから振り返れば、地球は宇宙の闇に浮かぶ青白い点にすぎない―。米国の宇宙探査の初期から指導的役割を果たしてきた著者が、世界的ベストセラー『コスモス』についで送る惑星たちの鮮明な素顔。ボイジャーとガリレオが調べたその姿を、NASAの最新データも駆使して克明に描

［source：］惑星へ - カールセーガン - Google ブックス https://books.google.co.jp/books/about/%E6%83%91%E6%98%9F%E3%81%B8.html?id=H1LGQgAACAAJ&source=kp_cover&redir_esc=y
```

　たぶん上記の本だったのだと思います。1998年とあるので平成10年4月1日の発売と思われますが、それにしては古びた本であったような記憶が残っています。それだけ人気のある本で多くの人の手を渡ったので傷み古びて見えていたのかもしれません。

　金沢刑務所の官本として読んだ本として、以前、徹底的に調べたのですが、どうしても見つけさすことのできない本がありました。上下巻となっていたと思いますがとても真新しく分厚い本でした。

　上巻の半分ぐらい読んだところで読むのをやめたように記憶しますが、その本で私は、仏教の釈迦の名前がゴータマ・シッダールタなどということを初めて知りました。ジッタールータとなっていたような気もします。本のタイトルは漢字の2文字で、上が「あ」と読む漢字でした。

　それだけの情報、手がかりがあるのでGoogleで探し出せると思ったのですが、何度かやってもうまく行かずに挫折したという経緯があります。釈迦の弟子だったようにも思い「阿南」とも考えたことがありましたが、とにかく確認できる情報は見つかりませんでした。

　そもそも阿南というのは旧陸軍の人物としても有名だった名前で、徳島県阿南市は、鮎を積みに2回ほど行ったことのある土地だったのですが、本のタイトルとそのまま一致するという感覚は残っていませんでした。「あ」に始まる漢字も不明のままです。

▷ リツイート→fukazawas（深澤諭史）＞k999941457035（K - 9 9 9 9）｜2018/12/18 19:12／2018/12/18 19:08｜https://twitter.com/fukazawas/status/1074970774794993665 ／ https://twitter.com/k999941457035/status/1074969619172012032
&twitter(1074970774794993665){theme:light}
> RT @k999941457035: 当会の会長に基本規定改訂推進論者のお考えを聞きましたが東京の先生が東京のヤバい弁護士を何とか規制したいという事情が背景にあるらしいですね。  

　上記の@k999941457035（K - 9 9 9 9）という匿名弁護士と思われるTwitterアカウントは、深澤諭史弁護士のリツイートとして久しぶり（それでも一月ぐらい）で見たものでしたが、釈迦の弟子として気になる永久保存版のツイートを見ていました。

　あえて＠の半角を入れてメンションとしてツイートをしましたが、現時点で告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカンとはブロックされていないようです。ブックマークにはしていない気もします。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:30／2018-10-26 12:45 URL： https://twitter.com/kk_hirono/status/1075080973862166529 https://twitter.com/k999941457035/status/1055666714468220928
&twitter(1075080973862166529){theme:light}
> ただ文化的な教養はあるにこしたことないですね。教養豊かな当職は彼女の両親に挨拶に行ったとき「どんな画家が好きだね？」とキラーパスを受けましたがギャラリーフェイクを読んでいたので無事乗り切りましたよ。ありがとうフジタレイジ。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kame_ishi（亀石） 日時：2018-12-19 02:31／2018-12-18 21:12 URL： https://twitter.com/kk_hirono/status/1075081048365486080 https://twitter.com/kame_ishi/status/1075000869987311616
&twitter(1075081048365486080){theme:light}
> 現行で厳しく対応するのではダメで、規程を変えないと実現できないんですかね。 \n  東京なら東京で始末つけろよ、オリンピックじゃあるまいし全国に迷惑かけるな。 https://t.co/egQrjtt4PZ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2018-12-19 02:31／2018-12-18 20:32 URL： https://twitter.com/kk_hirono/status/1075081173125091328 https://twitter.com/O59K2dPQH59QEJx/status/1074990730056151040
&twitter(1075081173125091328){theme:light}
> ヤバい弁護士って本当にいるからなぁ。ヤバい弁護士は、想像をはるかに超えているからね。 \n   \n  尋問期日前に相手方本人から「あのぅ、事件どうなってますか？うちの弁護士とは会ったことも話したこともなくて、最近事務員さんとも連絡がつかないんで… https://t.co/N84B8RY70d
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:31／2018-12-18 19:08 URL： https://twitter.com/kk_hirono/status/1075081227592335360 https://twitter.com/k999941457035/status/1074969619172012032
&twitter(1075081227592335360){theme:light}
> 当会の会長に基本規定改訂推進論者のお考えを聞きましたが東京の先生が東京のヤバい弁護士を何とか規制したいという事情が背景にあるらしいですね。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:31／2018-12-18 19:10 URL： https://twitter.com/kk_hirono/status/1075081246911262720 https://twitter.com/k999941457035/status/1074970043253813251
&twitter(1075081246911262720){theme:light}
> 本当にヤバい弁護士なら東京の弁護士会で内部規定作ったうえで現行規則で対応できないんですかね。関係ない他会を巻き込まんでくださいとしか言えない。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:32／2018-12-18 19:18 URL： https://twitter.com/kk_hirono/status/1075081267467628544 https://twitter.com/k999941457035/status/1074972110261411840
&twitter(1075081267467628544){theme:light}
> 本来なら「現行規則で対応できないので改訂したいです」からはじめて議論になるはずです。ただ、規制かけると萎縮効果生むので「けしからんから規制」との意見には原則反対です。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:32／2018-12-18 19:44 URL： https://twitter.com/kk_hirono/status/1075081315936985088 https://twitter.com/k999941457035/status/1074978667774730242
&twitter(1075081315936985088){theme:light}
> 聖帝十字陵 \n   \n  #南青山に建てたい施設
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bdcxxxdy（リアちゃん@婚活） 日時：2018-12-19 02:32／2018-12-18 00:07 URL： https://twitter.com/kk_hirono/status/1075081361990406145 https://twitter.com/bdcxxxdy/status/1074682556820336640
&twitter(1075081361990406145){theme:light}
> 初アポで源泉徴収票、免許証、弁護士バッジの3点セットを「まぁこれが俺の誠意だから？」と最強のドヤ顔で見せてきた弁護士 #クソ男オブザイヤー2018
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜n5dhBKCHJEcOAzR（チー太郎@精神科医） 日時：2018-12-19 02:32／2018-12-18 19:11 URL： https://twitter.com/kk_hirono/status/1075081377991647232 https://twitter.com/n5dhBKCHJEcOAzR/status/1074970399836823553
&twitter(1075081377991647232){theme:light}
> 自分で言うのも何だが医者って本人か親が変なやつであるパターンが多いし、学生時代勉強漬けかつ非モテだった怨念から浮気する男も多いから、高収入に惹かれて捕まえようとしない方がいいかもしれないな、、、。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜demacchiee（でまっちー） 日時：2018-12-19 02:33／2018-12-18 19:22 URL： https://twitter.com/kk_hirono/status/1075081507193085952 https://twitter.com/demacchiee/status/1074973245760098305
&twitter(1075081507193085952){theme:light}
> まあ、弁護士は専門分野の表示がないから選びにくいとはよく言われますから、やりたいことは分かるんですけどね。 \n   \n  専門の得意な人に頼みたいという人は多いですし。 \n   \n  ただ、その分値段張りますよと言ったら大体「じゃ、いいです」ということになるんですけど・・・。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ezweb_dylan（四谷 啓太郎） 日時：2018-12-19 02:33／2018-12-18 01:12 URL： https://twitter.com/kk_hirono/status/1075081553439412224 https://twitter.com/ezweb_dylan/status/1074698813296668672
&twitter(1075081553439412224){theme:light}
> ポンコツ悪魔が奮闘する漫画「悪魔のメムメムちゃん」の最新話が更新されました！ \n  よかったら読んでみてください。リンク先からすぐ読めます。 \n  https://t.co/Vq0KYSXGfj https://t.co/b2c0OXc5Em
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:33／2018-12-18 18:14 URL： https://twitter.com/kk_hirono/status/1075081593549512704 https://twitter.com/k999941457035/status/1074955955056476160
&twitter(1075081593549512704){theme:light}
> 個人間の貸金や不動産売買の相談で「どうしたらいいのかわからん」系統にはお前には荷が重いからやめとけという回答から入ってます＞rt
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜47news（47NEWS） 日時：2018-12-19 02:33／2018-12-18 17:46 URL： https://twitter.com/kk_hirono/status/1075081625677946880 https://twitter.com/47news/status/1074948938724126722
&twitter(1075081625677946880){theme:light}
> 比、5千人の麻薬容疑者を殺害　ドゥテルテ政権発足2年半で https://t.co/Trs2Pt9EXT
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜noooooooorth（ノースライム） 日時：2018-12-19 02:33／2018-12-18 11:12 URL： https://twitter.com/kk_hirono/status/1075081685505458176 https://twitter.com/noooooooorth/status/1074849857418883077
&twitter(1075081685505458176){theme:light}
> #不当懲戒請求 について本日も和解の申し入れがあった。やはり訴状が来てから初めてことの大きさを自覚するという人がそれなりにいるのだな…。現実的なものとして受け止めていないのかしら。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:33／2018-12-17 16:43 URL： https://twitter.com/kk_hirono/status/1075081734822064128 https://twitter.com/k999941457035/status/1074570780661276673
&twitter(1075081734822064128){theme:light}
> 弁護士ドットコムみたいなポータルサイトは本来弁護士会主導でやるべきとして業務改革の一貫としてやるんならまだわかる
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:34／2018-12-17 15:09 URL： https://twitter.com/kk_hirono/status/1075081813691789312 https://twitter.com/k999941457035/status/1074547041617858561
&twitter(1075081813691789312){theme:light}
> 新しく弁護士になる皆さん。仕事の名簿に登録するときは笑顔で歓迎し登録を外そうとするとあの手この手で阻止しようとするヤクザな団体があるらしいので気を付けてください。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yuukinoaru（岡村優希（京都CBTセンター）） 日時：2018-12-19 02:34／2018-12-16 20:33 URL： https://twitter.com/kk_hirono/status/1075081851201413120 https://twitter.com/yuukinoaru/status/1074266168267927552
&twitter(1075081851201413120){theme:light}
> 相談したいことを五七五で書いてください。心理士が七七で返します。^_^ \n   \n  #友人発案企画
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:34／2018-12-17 10:25 URL： https://twitter.com/kk_hirono/status/1075081947687268352 https://twitter.com/k999941457035/status/1074475628655652864
&twitter(1075081947687268352){theme:light}
> 男に『お酒強い？』って聞かれたら『弱くて。今練習中です♡』って飲めないとアピるのがモテる秘訣らしいですね。確かに夜の女子もこのモテテクを駆使しているよね。私が『アフター飲みに行こ？』って誘ったら判で押したように『友達誘っていい？』って言われて複数人に奢らされるよ。財布が辛いよ。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜partyhike（説教おじさん） 日時：2018-12-19 02:34／2018-12-17 10:02 URL： https://twitter.com/kk_hirono/status/1075082003064578048 https://twitter.com/partyhike/status/1074469775055585280
&twitter(1075082003064578048){theme:light}
> 男に『お酒強い？』って聞かれたら、『弱くて。今練習中です♡』って飲めないとアピるのがモテる秘訣らしいけど、確かに僕の周りの女子もこのモテテクを駆使しているよね。僕が『今後飲みに行こ？』って誘ったら、みんな判で押したように『お酒飲めなくて』『飲みが苦手で』って断ってくるよ。辛いよ。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜557dg4（脱税レイヤー風呂屋さん） 日時：2018-12-19 02:35／2018-12-16 10:01 URL： https://twitter.com/kk_hirono/status/1075082032869400576 https://twitter.com/557dg4/status/1074107187339771904
&twitter(1075082032869400576){theme:light}
> 南青山の児相建設について、反対住民は「青山ブランドが下がる」「児相の子が辛くなる」etcと、完全に児童が余所から来る前提だけど、そもそもコノ計画は「港区の児童虐待件数の異常な増加&amp;重篤化」が発端也 \n  コノ当事者意識の欠如が上記の事態… https://t.co/EPF79YDa9r
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜keiichisennsei（はぁとふる舞国土@3日目東ス26a） 日時：2018-12-19 02:35／2016-09-07 22:01 URL： https://twitter.com/kk_hirono/status/1075082061600280576 https://twitter.com/keiichisennsei/status/773506595078549504
&twitter(1075082061600280576){theme:light}
> 尾頭ヒロミ役の市川実日子さんに「この藤子Fタッチの尾頭が一番似ている」と言っていただき舞い上がる田中圭一は、ゴジラキャラたちをもっともっと描くのであった。 \n  #シンゴジラ https://t.co/POoRiUUQ99
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yosidatetuya（吉田哲也） 日時：2018-12-19 02:35／2018-12-15 16:16 URL： https://twitter.com/kk_hirono/status/1075082148963446784 https://twitter.com/yosidatetuya/status/1073839083623874561
&twitter(1075082148963446784){theme:light}
> クーリングオフしていいかどうか迷ってはいけない。とりあえず、クーリングオフ通知を送るのだ。期間が経過してるかもと思っても、送るのだ。クーリングオフが有効かどうかは、後でゆっくり考えればよい。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ssk_ryo（ささきりょう） 日時：2018-12-19 02:35／2018-12-14 11:48 URL： https://twitter.com/kk_hirono/status/1075082177912532992 https://twitter.com/ssk_ryo/status/1073409409844314112
&twitter(1075082177912532992){theme:light}
> 12月25日に期日がある東京第一次被告団の6名中5名の方から答弁書が来ました。請求の趣旨に対しては棄却を求めていますが、請求原因については「追って調査する」「改めて調査する」という内容で具体的な反論はまだされていませんでした。　#不当懲戒請求
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:35／2018-12-14 12:59 URL： https://twitter.com/kk_hirono/status/1075082224112885761 https://twitter.com/k999941457035/status/1073427165369184256
&twitter(1075082224112885761){theme:light}
> ロー生のとき仲の良かった女友達と空教室でｷｬｯｷｬｳﾌﾌしながら昼食とってたときに「僕も隣いいですか」って座ってきたクチャラーは俺に殴られても文句言えなかったと思う
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜reeeiinaaaa（麗奈） 日時：2018-12-19 02:35／2018-12-14 12:25 URL： https://twitter.com/kk_hirono/status/1075082240198041600 https://twitter.com/reeeiinaaaa/status/1073418589917503489
&twitter(1075082240198041600){theme:light}
> 外食時、クチャラー(食事中、クチャクチャ音を食べて周りに迷惑をかけるやつ)の被害を防止すべく、イヤフォンを持参して、クチャラーいる時は音楽聴くことで自衛することにした。 \n   \n  イヤフォンしながらお食事するには決してお行儀良いとはいえな… https://t.co/S5zf0vee3k
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜k999941457035（K - 9 9 9 9） 日時：2018-12-19 02:36／2018-12-14 12:19 URL： https://twitter.com/kk_hirono/status/1075082270648655877 https://twitter.com/k999941457035/status/1073417089891762176
&twitter(1075082270648655877){theme:light}
> 危険運転認めちゃったよ
◁◁◁
<hr />

　タイムラインにあった（一部その関連）ツイートとリツイートを26件、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でリツイートしました。

　ちょっと意外に思ったのですが、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)では北周士弁護士にブロックされていなかったことを思い出しました。

　いずれのツイート（一部、返信のぶら下がりとして除く）も次のまとめ記事の射程に入っているのではと思います。

[link:] 2018年12月19日00時36分の登録： ＼K - 9 9 9 9　@k999941457035＼当会の会長に基本規定改訂推進論者のお考えを聞きましたが東京の先生が東京のヤバい弁護士を何とか規制したいという事情が http://hirono2014sk.blogspot.com/2018/12/k-9-9-9-9k999941457035.html

[link:] 2018年12月19日00時36分の登録： ＃K - 9 9 9 9　@k999941457035＃のツイート／2018-11-29_1703〜2018-12-18_2254／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月19日00時36分 http://hirono2014sk.blogspot.com/2018/12/k-9-9-9-9k9999414570352018-11_19.html

　時刻は10時40分です。確認すると直前のツイートとしての投稿が3時9分となっていました。起きて5分ほどして時間を見ると8時58分でした。電気をつけたまま寝ていて、寝た時のこともよく憶えていません。

```
目次
1	小説
2	映画
2.1	オリジナル・シリーズ
2.1.1	『猿の惑星』
2.1.2	『続・猿の惑星』
2.1.3	『新・猿の惑星』
2.1.4	『猿の惑星・征服』
2.1.5	『最後の猿の惑星』
2.2	再始動の試みとリ・イマジネーション
2.2.1	『PLANET OF THE APES/猿の惑星』
2.3	リブート・シリーズ
2.3.1	『猿の惑星： 創世記』
2.3.2	『猿の惑星： 新世紀』
2.3.3	『猿の惑星： 聖戦記』
3	映像化作品一覧
4	テレビ
4.1	テレビ版『猿の惑星』
4.2	『まんが猿の惑星』
5	テーマ
6	後年への影響
6.1	文化面
6.2	政治面
7	出典


［source：］猿の惑星シリーズ - Wikipedia https://ja.wikipedia.org/wiki/%E7%8C%BF%E3%81%AE%E6%83%91%E6%98%9F%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA
```

　上記にwikipediaの目次部分を引用しました。ざっと数えると映画は9作あるようです。2年ぐらい前になるかと思いますが、何か最新作の紹介をテレビの情報番組で見たことはあったのですが、こんなに沢山あったのは意外でした。

　基本的に私は宇宙というかSF物の映画にまったく関心がなく、有名で作品も多いと思われる「スターウォーズ」も1作も見たことがないと思います。映画だけではなくSFの小説というのも同じです。

　しかし、それが中学生の頃に見たテレビアニメの「宇宙戦艦ヤマト」と「銀河鉄道９９９」のことは今でも印象的に記憶にあります。しかし、それも特に関心が強かったわけではなく、見た放送回数も多くはなかったと思います。

　猿の惑星のストーリーというのも全く記憶に残っていません。オレンジ色の砂漠のような不思議な風景だけが印象に残っているというか、記憶に焼きついているという感じです。

* 福井刑務所と金沢刑務所のテレビ視聴について

　金沢刑務所も福井刑務所も同じでしたが、舎房でのテレビ視聴には、基本的に週２回、夜に映画やテレビの録画放送がありました。正月、お盆、GWは別に放送があり、午後の午睡明けに映画をみることもありました。

　連休の場合は特別放送の映画でしたが、それは決まってビデオだったと思います。レンタルビデオ店から借りてくるのと同じです。連休以外の放送は、テレビの録画が多く、ビデオは珍しくも感じました。

　なお、私が福井刑務所に受刑者として服役していたのは平成6年3月17日から平成9年1月18日まで、金沢刑務所の場合は、日付の特定が出来ないですが、平成12年の11月の初めに工場出役が始まり、出所が平成13年12月31日でした。

　福井刑務所と金沢刑務所では新入教育に違いがありました。福井刑務所では一般の受刑者と同じ一工場に出役しながら出役以外の時間は、指導係のような受刑者が1人いる雑居房で生活しました。工場の作業以外は一般の受刑者と同じ生活でした。

　金沢刑務所の場合は、合宿のような雰囲気で新入教育を受ける受刑者だけの生活で、講義室のようなところにいることがほとんどで、みっちり教育を受けたような気もします。

　新入教育を受ける受刑者だけの雑居房があるという話でしたが、私は金沢地方検察庁に提出する書面の認書の作成が許可され、一人だけ独居房で生活していました。テレビはなかったと思います。雑居房にテレビがあるとも聞かなかったように思います。

　適切な言葉が思いつかないので一応、講義室としましたが、工場の並びにある部屋でした。金沢刑務所の場合は、全体的に軍隊の駐屯地のような建物で、工場や通路は、以前の石川県立水産高校ともよく似ていました。

　現在は能登高校となっている宇出津の石川県立水産高校は本校とも呼ばれ、無線通信科だけの小木分校がありました。私が昭和55年4月から翌年の6月まで通って中退した高校です。始業式では宇出津の本校に行くこともありましたが、それぐらいだったと思います。

　時刻は11時33分です。31分ぐらいに気がついてチャンネルをMRO放送から石川テレビに変更しました。北海道で捜索願を出した夫が妻の死体を川に捨てた、ニュースの雪山の場面。そこで思い出したのですが、昨日の宗像大社の神職の飲酒運転で逮捕のニュースは、他に見ることがありませんでした。

　時刻は11時40分です。しばらくテレビの方に注目していました。ネットで検索して掲載したいと思いますが次の２つのニュースです。姫路の保育所の方が先でした。はれのひ社長の判決は、それより前の今朝の番組で見ていましたが、それも短いニュースでした。

[link:] » 姫路　保育所 - Google 検索 https://t.co/ckvHuti7Yw

<hr />
[link:] » 姫路　103万円 - Google 検索 https://t.co/Yge9VxmI2Q

<hr />
[link:] » 姫路　判決 - Google 検索 https://t.co/O7x0lQdKKc

<hr />

　３つの検索を試みましたが、探す情報は出てきませんでした。保育所ではなく保育園だったかもしれません。ひと頃、さかんに情報番組で取り上げられ、社会問題化していました。過去のニュースは探せ出せるとおもます。

[link:] » 姫路　認定保育園 - Google 検索 https://t.co/wBEDWGBZ6B

<hr />

　上記の検索で、さきほどテレビで見ていたニュースが見つかりました。100万円となっていますが、テレビでは字幕にも103万円と出ていたと思います。被告の欠席裁判ということで、裁判官に向かって左手の席にまとまった数の人が座っていました。弁護士もいるのでしょう。

```
園児の大幅な定員超過や少量の給食が問題になった兵庫県姫路市の「わんずまざー保育園」（廃園）に通っていた男児（４）と両親が、元園長の女性（４７）に約１２０万円の慰謝料を求めた訴訟の判決で、神戸地裁姫路支部（徳岡由美子裁判長）は１９日、「利益追求のため、園児の安全や発育をないがしろにした」として約１００万円の支払いを命じた。


［source：］元園長に賠償命令、兵庫・姫路　わんずまざー保育園、１００万円｜カナロコ｜神奈川新聞ニュース http://www.kanaloco.jp/article/378472
```

　さきほどのテレビニュースでは見なかったように思いますが、請求額が約120万円だったということです。しかし、上記に引用したネット記事では、被告が出廷しなかったいわゆる欠席裁判であることには触れていないようです。法廷の写真もありません。
