#+TITLE: "参考資料／性犯罪／大阪市強姦虚偽証言再審事件／大阪市強姦虚偽証言再審事件に関連したと思われる「こんな検事が組織に守られ出世するので法曹一般の話ではないかもなぁ」というツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-05-27 11:37:25 +0900
FILE_NAME: 2019-05-27-113725_大阪市強姦虚偽証言再審事件に関連したと思われる「こんな検事が組織に守られ出世するので法曹一般の話ではないかもなぁ」というツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  坂本正幸弁護士 駅南ローヤー えきなんローやー 大阪市強姦虚偽証言再審事件 後藤貞人弁護士
記事タイトル名の文字数：87　保存ファイル名の文字数：86

#contents

* 「こんな検事が組織に守られ出世するので法曹一般の話ではないかもなぁ」という法政大学教授坂本正幸弁護士のツイート
  :LOGBOOK:
  CLOCK: [2019-05-27 月 11:42]--[2019-05-27 月 11:53] =>  0:11
  :END:

＞＞＞2019-05-27（月曜日）11：42＿［これからの記述範囲の開始時刻］＞＞＞

▶ ツイート％sakamotomasayuk（坂本正幸）％2019/05/27 09:28％ https://twitter.com/sakamotomasayuk/status/1132805760411291648
&twitter(1132805760411291648){theme:light}
> こんな検事が組織に守られ出世するので法曹一般の話ではないかもなぁ https://t.co/iS6t3Nv4dJ  
▶

　「こんな検事」と坂本正幸弁護士が指すのは、URLを引用した次のえきなんローヤーというアカウントのツイートで、「あなたのことは絶対に許さない！！」とある検事のことだと思われます。

▶ ツイート％ekinan_lawyer（えきなんローヤー🕊）％2019/05/26 20:13％ https://twitter.com/ekinan_lawyer/status/1132605712654143489
&twitter(1132605712654143489){theme:light}
> しっかし、正義感強すぎる人が法曹になったら、ストレス溜めまくりになるよね。
> 
> 例えば、検察官で、後に冤罪だと判明する被疑者に向かって
> 「あなたのことは絶対に許さない！！」
> なんて法廷で言った黒歴史などあろうものなら、適応障害とか鬱… https://t.co/45HkCYnSVz  
▶

　明示はないですが、「あなたのことは絶対に許さない」という発言には見覚えがあり、大阪市強姦虚偽証言再審事件で有罪判決とした女性検事の発言かと思われます。その女性検事は実名で話題となり、司法修習の教官をしているような話も出てきました。

＜＜＜2019-05-27（月曜日）11：53＿［これまでの記述範囲の終了時刻］＜＜＜

* REGEXP：”山吉彩子検事”／データベース登録済みツイート：2019年05月27日12時01分の記録：ユーザ・投稿：48／97件
  :LOGBOOK:
  CLOCK: [2019-05-27 月 12:08]--[2019-05-27 月 12:40] =>  0:32
  :END:

＞＞＞2019-05-27（月曜日）12：08＿［これからの記述範囲の開始時刻］＞＞＞

```
アカウント名	ツイート数	リツイート数
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	6	0
弁護士あだちあだちけいたけいた（keita_adachi）	1	3
TｰTAKA（TGN54）	0	1
らめーん（shouwayoroyoro）	0	3
フミン（IcyFumin）	0	1
tochi0428（Mr_Bluegoat）	0	1
リーチ一発ツモ裏１（luckymangan）	0	3
!omikuji !dama ほりぐち（mstk_Horiguchi）	1	1
渡辺輝人（nabeteru1Q78）	0	1
えきなんローヤー?（ekinan_lawyer）	0	4
三毛猫B（poorpartner）	0	4
カロ（calowyer）	0	1
阿胡ノ海（agonoumi）	0	1
中村元弥（1961kumachin）	0	2
河﨑健一郎（kappamark）	0	1
高橋雄一郎（kamatatylaw）	3	0
1313（Kurosiro1313）	0	1
アリアンデルの猫（laparkadejapon）	0	2
皮下注（hirohika777）	0	2
サイ太（uwaaaa）	0	2
ワーキングプア弁護士（sokudokubengosi）	0	1
微笑みのロイヤー（smile_spirits）	0	1
けっす（keskil_）	0	1
当職ぴっぴ@梅吉（emeth_pippi）	0	1
井上雄樹（yinoue1975）	0	2
強制わいせつ/準強姦/買春/児童ポルノ/児童福祉法/青少年条例弁護人弁護士奥村徹(大阪弁護士会)（okumuraosaka）	1	0
弁護士 星　正秀（hoshimasahide）	0	1
鳩屋（haya_rt）	0	2
吉田哲也（yosidatetuya）	0	1
蛇毒（bigbrother939）	0	1
非常上告-最高検察庁御中_ツイッター（s_hirono）	9	0
霞 司郎（kasumi_shiro）	0	1
弁護士　山中理司（yamanaka_osaka）	0	9
yuji kigami　木上雄二（39801）	0	2
toujin（tou_jin）	0	1
山。（standing_Mt）	0	1
ちばまこと（makomayu1）	0	1
問題解決のお手伝い業者（okinawabengoshi）	0	1
けーぞ伯爵?（kzo_tan）	0	1
中野 俊徳（kanonjilawfirm）	0	2
玉井克哉（Katsuya TAMAI）（tamai1961）	0	5
田中・鈴木・木村（tanakasuzukikim）	0	1
ささきりょう（ssk_ryo）	0	1
中村剛（take-five）（take___five）	0	1
なべきょう＠過眠症（wata_nabekyo_ko）	0	1
浜ちゃん（lawer_hamachan）	0	1
たろう teacher（tomo_law_）	0	1
深澤諭史（fukazawas）	0	1


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”山吉彩子検事”／データベース登録済みツイート：2019年05月27日12時01分の記録：ユーザ・投稿：48／97件 http://hirono2014sk.blogspot.com/2019/05/regexp2019052712014897.html
```

　「山吉彩子検事」をキーワードにまとめ記事を作成してみて、まず最初に意外に思ったのが、私自身のツイートが最初にあったことです。繰り返しご説明していますが、このまとめ記事はツイートやリツイートの投稿時刻で、過去の古いものから順に並べています。

　なお、データベースの操作では「ORDER BY tw_date DESC」という指定をすることで、値の大きな順番で並び替えることも簡単に出来ます。日付時刻のデータ型は、値が大きなものほど最近のものになっていたかと思います。昇順だと古いものから並ぶことになります。

▶（01／97） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-01-08 07:17:00 +0900 URL： https://twitter.com/hirono_hideki/status/1082400831863808000
{% tweet 1082400831863808000 %}
> 弁護側は、捜査・公判を通じて虚偽の被害証言が見逃された原因を明らかにするために男性を取り調べた山吉彩子検事らの証人尋問を求めるも、芦高源（あしたかみなもと）裁判長は退けている。 https://t.co/KZohZNx5T0

　数も多いので時間を掛けて眺めてはいないのですが、ざっと３つの弁護士アカウントのツイートが中心となり、他はそのツイートのリツイートがほとんどとなっているようです。

　時系列で見ると、足立敬太弁護士のツイートがあって、その次にほりぐち弁護士のツイート、そして高橋雄一郎弁護士のツイートがあるのですが、私の記憶では、その高橋雄一郎弁護士のツイートが最も印象的で、それが山吉彩子検事の名前を知った最初と考えていました。

▶（02／97） TW keita_adachi（弁護士あだちあだちけいたけいた） 日時： 2019-01-08 14:13:00 +0900 URL： https://twitter.com/keita_adachi/status/1082505494105706496
{% tweet 1082505494105706496 %}
> ＞捜査段階で男性を取り調べた山吉彩子検事（2017年4月から司法研修所の検察教官）は、潔白を主張する男性に「絶対許さない」と言い放ち、全く取り合おうとしなかった。 \n \n 性的被害を受けたというウソの証言で約6年も身柄拘束　人が人を裁… https://t.co/yeCxLAjw0M

▶（10／97） TW mstk_Horiguchi（!omikuji !dama ほりぐち） 日時： 2019-01-08 14:56:00 +0900 URL： https://twitter.com/mstk_Horiguchi/status/1082516400999022592
{% tweet 1082516400999022592 %}
> 山吉彩子検事はあだちさんと同期か。つまり有名ツイッタラー弁護士の面々と同期なんだな

▶（17／97） TW kamatatylaw（高橋雄一郎） 日時： 2019-01-08 15:35:00 +0900 URL： https://twitter.com/kamatatylaw/status/1082526213132832768
{% tweet 1082526213132832768 %}
> 山吉彩子検事、俺と同期同クラスなんだ。模擬裁判で相手方だった。優秀で常識と人望があって教官に向いている人だよ。「潔白を主張する男性に「絶対許さない」と言い放ち、全く取り合おうとしなかった。」という一方的な報道はさすがに文字通り信じることはできないよ。

▶（39／97） TW okumuraosaka（強制わいせつ/準強姦/買春/児童ポルノ/児童福祉法/青少年条例弁護人弁護士奥村徹(大阪弁護士会)） 日時： 2019-01-08 17:11:00 +0900 URL： https://twitter.com/okumuraosaka/status/1082550286093144064
{% tweet 1082550286093144064 %}
> 山吉彩子検事（56期 https://t.co/CDwFpfBQXv

▶（69／97） TW kamatatylaw（高橋雄一郎） 日時： 2019-01-09 07:40:00 +0900 URL： https://twitter.com/kamatatylaw/status/1082769095043366912
{% tweet 1082769095043366912 %}
> 山吉彩子検事批判が散見されるが、証拠から有罪判決がとれると判断して起訴した検事の職務執行には違法性はないし結果的に有罪判決はでたし昨日の国賠判決もそう判断している。批判すべきは起訴検事一人ではなく被害者と目撃者が口裏会わせし迫真の演技をすれば冤罪が生まれる現行刑事手続ではないか。

▶（82／97） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-01-10 00:58:00 +0900 URL： https://twitter.com/hirono_hideki/status/1083030267168677893
{% tweet 1083030267168677893 %}
> 山吉彩子検事（５６期）の経歴 – 弁護士山中理司（大阪弁護士会所属）のブログ https://t.co/2bRHkwl3rC

▶（97／97） RT luckymangan（リーチ一発ツモ裏１）｜keita_adachi（弁護士あだちけいた　春の大山 打つんだ。） 日時：2019-04-10 13:10:00 +0900／2019-01-08 14:13:00 +0900 URL： https://twitter.com/luckymangan/status/1115829266070085633 https://twitter.com/keita_adachi/status/1082505494105706496
{% tweet 1115829266070085633 %}
> 

　まとめ記事で９７件目のもっとも最近のツイートは、リツイートの時刻が２０１９年４月１０日１３時１０分のものです。ツイート自体は同年１月８日から同月１０日辺りに集中しているようです。話題となったのは国賠請求の棄却判決がきっかけであったように思われます。

　３月には４つの性犯罪無罪判決が大きな話題となっていました。現在もその余波は続いていて、性犯罪の過失犯の処罰や暴行・脅迫要件の撤廃という社会運動や議論に発展しているようです。

　時期はまだ確認していませんが、大阪市強姦虚偽証言再審事件が再び注目を集めたのは、国家賠償請求訴訟でした。私自身、その段階になった初めて知った事実があって、再審無罪判決に対する印象もずいぶん変わりました。

＜＜＜2019-05-27（月曜日）12：40＿［これまでの記述範囲の終了時刻］＜＜＜

