#+TITLE: "大型トラックと衝突した京急脱線事故と弁護士鉄道"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-09-15 10:25:29 +0900
FILE_NAME: 2019-09-15-102529_大型トラックと衝突した京急脱線事故と弁護士鉄道.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 弁護士鉄道 
記事タイトル名の文字数：23　保存ファイル名の文字数：45

* 大型トラックと衝突した京急脱線事故と弁護士鉄道

:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 




:CATEGORIES: 石川県警察珠洲警察署御中
:TAGS: 栃木小1女児殺人事件


≫≫≫ 2019/09/06 9:35:07 ≫≫≫

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-09-06 08:54 URL： https://twitter.com/hirono_hideki/status/1169760659954778112
> 京急衝突　事故直前のトラック映像を入手｜日テレNEWS24 https://t.co/wk3xUtYQVo

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-09-06 08:55 URL： https://twitter.com/hirono_hideki/status/1169761115179339778
> 右折トラック、何度も切り返し…踏切入った直後に遮断機降下 : 国内 : 読売新聞オンライン https://t.co/GkhB5ui1YK

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-09-06 09:02 URL： https://twitter.com/hirono_hideki/status/1169762787259633670
> 「＃がんばれ京急」ツイッターのトレンド上位に　脱線復旧作業で「頭が下がります」との声も : J-CASTニュース https://t.co/fMjtFcr7He

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-09-06 09:13 URL： https://twitter.com/hirono_hideki/status/1169765496104685568
> 「お前、俺の小説パクったろ」飲み屋街で絡まれ...　志茂田景樹、京アニ事件で「体験談」振り返る : J-CASTニュース https://t.co/ky2NA7kgUO

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-09-06 09:23 URL： https://twitter.com/hirono_hideki/status/1169767925089107968
> 京アニ代理人、25人公表・報道に「大変遺憾」 「一部ご遺族の意向に関わらず...」 : J-CASTニュース https://t.co/96J0NyvYef \n 京アニ代理人の桶田大介弁護士は同日、ツイッターで「弊社の度重なる要請及び… https://t.co/0IezC1KzIg

　ゴミ出しに行った後だったと思いますが、時刻がちょうど8時でテレビをつけました。昨夜もテレビをつけていましたが、ここ一週間ほどは、テレビをつける時間が少なかったり、まったく見ない時間も長くありました。

　トップニュースは昨日の京急脱線事故で、これは昨日、昼の情報番組グッディで見たのが最初であったように思います。少ししてチャンネルをミヤネ屋に変えましたが、そちらでもずいぶん時間を掛けて京急脱線事故を報じていました。

　怪我人が多数で一人が重傷と聞いていたように思いますが、夜のニュースでは一人が死亡で、衝突した大型トラックの運転手となったいたように思います。

　今朝はチャンネルをあちこち変えていたのですが、京急脱線事故の詳細があって、死亡したトラック運転手以外の怪我人33人は全員が軽傷で、踏切事故は大型トラックが路地を曲がりきれず何度も切り返しをしながら踏切に進入したとのことでした。

　その少し前だったと思いますが、台所で昨夜の洗い物をしているとき、考え事のなかで弁護士鉄道から「弁護士システム」という言葉が頭に浮かんできました。

　今、テレビのスッキリで京急脱線事故のニュースがありましたが、これも気になったのは、死亡したトラック運転手の勤務する千葉県の運送会社の家宅捜索に乗り出した、ということです。

　過労運転が原因の事故とは考えにくいのですが、運転手がなぜ踏切の遮断機がおりたあとも逃げ出さずに死亡したのかという点が不可解でした。車内に残ったままなくなったのか、それとも車外に脱出したところで衝突に巻き込まれたのか、報道では不明です。

　もう1点、この京急脱線事故のニュースで気になったのは、脱線復旧作業が明日の復旧を目途にしているとかで、それだけ早い復旧が見込めるのは、保守基地から歩いて行ける距離とのことでした。

　軽傷者の33人という数も気になるもので、その後、35人となりましたが京アニ放火殺人事件の亡くなった犠牲者の数も33人として報道されていたことをすぐに思い出しました。そのときにも書いたと思いますが、三十三観音などと特別な意味を持つ数です。

　10時25分からの放送開始と確認しましたが、テレビにいきなり輪島市海士町の神輿渡御入水神事が出てきたので驚きました。放送が何なのかすぐに理解が出来なかったのですが、「遠くへ行きたい」という旅番組でした。

　輪島大祭の海士町は毎年8月22日から4日間続く初日で、奥津比咩神社になります。遠くへ行きたいの番組で、女神なので神輿を担ぐ男性が女性のいでたちと説明していましたが、その女神は田心姫命とのことです。

　田心姫命について以前調べていたとき最も驚いたのは、栃木県の思川のことでした。平成4年4月1日の傷害・準強姦被告事件の前、長距離トラックの仕事の中心が茨城県古河市からの青果物の運送だったので、国道50号線沿いの思川はちょくちょくと通りかかっていました。

　その平成4年当時は知らなかったように思いますが、思川の近くには日本有数の女子刑務所という栃木刑務所があるとのことです。少なくとも私は平成6年3月から平成9年1月の福井刑務所での受刑中、栃木刑務所のことを知っていました。

　栃木で思い出すことはいくつもありますが、その1つが栃木の弁護士会で刑務所を出所した女性を朝まで事務所に留めおいたとして問題となった弁護士のことです。たぶん戒告程度の懲戒処分になっていたと思います。

　栃木の弁護士会というのは栃木弁護士会か栃木県弁護士会のどちらかと思いますが、県をつける弁護士会とつけない弁護士会があるのでややこしく憶えづらいです。あとで確認しますが、栃木県弁護士会だったとは思います。

　栃木県には黒羽刑務所だったと思いますが男性の初犯刑務所があるとも聞いていました。これも福井刑務所での受刑中には知っていたように思います。職業訓練の募集のようなものでも見かけていたのかもしれません。

　このあと栃木県弁護士会の事務所に女性を留めおいたとして問題と同じく独立の見出しをつけて記録しておきたいと考えています。現在の編集は、これまでのEmacsとは違い、Windows10のWordで行っています。

　簡単に紹介しておくと神奈川県川崎市のトンネルでの通り魔女性殺害事件になりますが、受刑中で出所が近かった真犯人が神奈川県警の刑事に連絡をして名乗り出たというニュースがテレビにもありました。

　この件もだいぶん前から取り上げておきたい事項ではあったのですが、ずっと延び延びになっていたものの一つです。

　私の個人的な経験や知識になりますが、刑事事件において栃木県と神奈川県は特別な土地柄と考えることが多々ありました。栃木県にはその後、市町村名の変更で栃木小1女児殺人事件ともされる今市小1女児殺人事件もあります。

　栃木県と神奈川県は弁護士の活動としても特別なものがあります。尊属殺人罪の条文削除のきっかけになったという父親に対する殺人事件があったのも栃木県とのことです。リュックサック一杯のジャガイモというのも弁護士鉄道の歴史の1ページです。

　最近の京都府宇治市の京アニ放火殺人事件とも大きな共通性がある座間市の遺体遺棄事件、津久井やまゆり園の殺傷事件も神奈川県です。PC遠隔操作事件も主な舞台として注目されたのが神奈川県内であったと思います。

　さかのぼると神奈川県警察の不祥事というのもありましたが、余りテレビを見ることがない時期だったので、詳しくはしらないですが、ずいぶんと長く大きな報道があったことは割と強く印象に残っています。

　前にも書いていると思いますが、神奈川県は大阪府より人口が多いので、大きな事件の発生確率も高くなるのかと考えますが、こと弁護士の活動に関しては特異なものを感じることが多いです。

　2015年なので4年前になりますが、私が住む石川県の輪島市と横浜市を舞台とした連続テレビ小説まれ、の放送がありました。同じ頃だったと思いますが、横浜弁護士会が神奈川県弁護士会に名称変更するというニュースをネットで見かけていました。

　そのネットのニュースの中にあったと思いますが、県名ではなく県庁所在地の市名の弁護士会は全国でも少なく、それも石川県と神奈川県に共通したもので金沢弁護士会と横浜弁護士会でした。最近調べたところ他に仙台弁護士会があるようです。

　時刻は12時47分です。袋入りのヨーグルト、プチトマト、日清焼そばで昼食を済ませていました。それで台所に行ったタイミングだったと思いますが、石川県と神奈川県の関係で一つ思い出したことがあります。総持寺のことです。

　法クラと自称、他称する主にネットのTwitter上の弁護士ですが、日弁連（日本弁護士連合会）のことを総本山と呼ぶことが多いです。私は2010年4月にTwitterを始めていますが、その2，3年後ぐらいから見かけるようになったと思います。

　すでにいくつかまとめ記事を作成しているはずなので、そちらで確認をしたいと思いますが、あまねく情報を集めたものではありません。ツイートのデータベースに本格的に記録するようになったのも2015年ぐらいからかと思います。

TW kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時： 2019-09-06 12:58 URL： https://twitter.com/kk_hirono/status/1169822171520061440
> 弁護士　除去装置 - Google 検索 https://t.co/CXzRrm2bI8

TW kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時： 2019-09-06 12:59 URL： https://twitter.com/kk_hirono/status/1169822468900454401
> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: 総本山の検索結果 https://t.co/xnvO9e7Z8j

TW kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時： 2019-09-06 13:01 URL： https://twitter.com/kk_hirono/status/1169822825021988864
> 弁護士 除去装置　総本山 - Google 検索 https://t.co/G0LYuP9HWD

TW kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時： 2019-09-06 13:01 URL： https://twitter.com/kk_hirono/status/1169823018945695746
> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”総本山”／データベース登録済みツイート：2018年01月24日21時07分の記録：ユーザ・投稿：180／927件 https://t.co/XvbmXObSk9

　Bloggerのブログで日本語の検索がうまくいったので驚いたのですが、そのまま該当した記事を表示しているようですが、まとめ記事は長いものがほとんどなので、これでは検索として事実上使い物になりません。

```
▶（001／927） TW at1117（Aki Tsurumaki） 日時： 2009-09-04 09：04：00 +0900 URL： https：//twitter.com/at1117/status/3745364670
> それにしても140字では無理だなあ。とにかく「あらゆる個人情報が自己情報コントロール権の対象であり、現行の個人情報保護法はそれを具現化したものであり、現行法で不十分ならばその方向に改正をすべきだ」という総本山の見解には全く賛同できない。

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”総本山”／データベース登録済みツイート：2018年01月24日21時07分の記録：ユーザ・投稿：180／927件 http://hirono2014sk.blogspot.com/2018/01/regexp201801242107180927.html
```


　上記に引用した2009年9月4日のツイートがデータベースに記録したツイートで「総本山」をキーワードに含む最初のものとなっていました。

　余り見かけないアイコンで、アイコンが変更されたアカウントとも思ったのですが、Twitterのアカウントを開いてプロフィールに見覚えがありました。似たようなアイコンで道路標識に「だまれ」などとしたものもありました。たまに見かけるものです。

```
Aki Tsurumaki
@at1117
1968年生まれの弁護士（東京弁護士会所属。1997年登録）。twitterでのご相談は承ることができません。あしからずご了承ください。

Tokyo,JAPAN
2009年5月に登録

［source：］Aki Tsurumaki(@at1117)さん | Twitter https://twitter.com/at1117
```

　上記にTwitterのプロフィールを引用しました。よく見るとプロフィールの名前がAki Tsurumakiとなっていて、実名のローマ字表記のようです。アキと読めるので女性弁護士の可能性が高そうです。

RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜at1117（Aki Tsurumaki） 日時：2019-09-06 13:32／2019-07-29 23:40 URL： https://twitter.com/kk_hirono/status/1169830826432851969 https://twitter.com/at1117/status/1155850615018250243
> 乗る上w https://t.co/4peOpu1fcs

　挨拶代わりに、最新のツイートを1つリツイートしましたが、7月29日の投稿となっています。「ツイートと返信」で見ても同じでした。ざっとタイムラインをみても更新の頻度がかなり少ないようです。道理で見かけることが少ないと納得しました。


　この文章はアウトラインで4階層の4階層目として記述をしていますが、上位の階層というのはまだ作成していません。長文になりつつあるのでこの辺りでいったん切り上げたいと思います。

≪≪≪ 2019/09/06 13:38:57 ≪≪≪

