#+TITLE: "参考資料／労災／労働裁判／佐々木亮弁護士と親交のあるらしい大仏アイコンの明石順平弁護士が代理人として提訴した労災死"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-02-23 06:17:22 +0900
FILE_NAME: 2019-02-23-061722_佐々木亮弁護士と親交のあるらしい大仏アイコンの明石順平弁護士が代理人として提訴した労災死.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  明石順平弁護士 佐々木亮弁護士 労災
記事タイトル名の文字数：57　保存ファイル名の文字数：66

#contents

* これまでに何度か見かけてきた二人のTwitterの大仏アイコンの一人、実名の明石順平弁護士
  :LOGBOOK:
  CLOCK: [2019-02-23 土 06:20]--[2019-02-23 土 07:56] =>  1:36
  :END:

＞＞＞2019-02-23（土曜日）06：20＿［これからの記述範囲の開始時刻］＞＞＞

　これまでほとんど意識してこなかった弁護士アカウントなのですが、佐々木亮弁護士と親交があると知って関心が高まりました。まず佐々木亮弁護士は労働裁判の専門家、あるいはエキスパートのような存在感があるからです。別の言い方をすればそれらしい情報発信をしています。

```
明石順平
@junpeiakashi
弁護士。 著書「アベノミクスによろしく」「データが語る日本財政の未来」発売中。ブログ：モノシリンの3分でまとめるモノシリ話「http：//blog.monoshirin.com/ 」 すぐブロックします。

2018年7月に登録

［source：］明石順平(@junpeiakashi)さん | Twitter https://twitter.com/junpeiakashi
```

　上記が明石順平弁護士のTwitterアカウントのプロフィールになります。ずいぶん前から何度か目にしてきたものですが、著書に「「アベノミクスによろしく」「データが語る日本財政の未来」発売中」とあります。

　政治的な問題に関心が強く、本まで出している弁護士なのだとは思いましたが特に関心は持ちませんでした。政治経済というのは基本的に私の抱える告発・非常上告問題とは関わりが薄いという意識があったからだと思います。

　だいぶん前の記憶なので不確かですが、ちょうど森友学園問題が籠池氏の国会の証人喚問で報道と世間の関心がピークの頃に、初めてこのプロフィールを見たように思いますが、大仏アイコンとの一致は記憶になかったと思います。

▶ ツイート％s_hirono（非常上告-最高検察庁御中_ツイッター）％2019/02/23 06:23％ https://twitter.com/s_hirono/status/1099057126280810497
&twitter(1099057126280810497){theme:light}
> 2019-02-23-055748_明石順平（@junpeiakashi）さん　｜　Twitter.jpg https://t.co/xunLxIHoKb  
▶

　上記が明石順平弁護士のTwitterアカウントのスクリーンショットになります。このヘッダ画像ですが、前に見たときも少し気になっていました。割と大きな地方都市の港湾にみえます。コンテナを船に乗せるクレーンも見えるので、外国船が出入りするような港のようです。

　もう２５年ほど以上前のことになるので、現在とは違いがあると思いますが、私は長距離トラック運転手の仕事で、日本の主要な港というのは、かなり回っています。例えば広島県の呉市などは行ったことがありませんが、けっこういろいろと行っています。

　他の弁護士アカウントのヘッダ画像でも、それ以上に気になった港の写真があって、そちらはGoogleマップで実際に調べてみました。明石順平弁護士のヘッダ画像と同様に、山が港の近くにある地形でしたが、そういう大きな港というのは、日本にそう多くはないと思い、関心を持ちました。

```
Diginnos-PC:~
[9986]  % dp -p |grep 明石順平
[link:] 2019年02月01日20時57分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-01-23_2222〜2019-02-01_1808／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月01日20時57分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-01-2322222019-02.html
[link:] 2019年02月01日20時57分の登録： ＼明石順平　@junpeiakashi＼ついに降伏したか。 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi.html
[link:] 2019年02月04日06時38分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-01-28_2257〜2019-02-04_0115／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月04日06時37分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-01-2822572019-02.html
[link:] 2019年02月04日06時38分の登録： ＼明石順平　@junpeiakashi＼弁護士＝サヨク＝攻撃対象みたいな認識のツイッタラーが一定割合いる気がする。 こういう輩がクソリプを飛ばして来たら即ブロック。 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi_4.html
[link:] 2019年02月05日11時15分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-02-01_1418〜2019-02-05_1059／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月05日11時15分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-02-0114182019-02.html
[link:] 2019年02月05日11時15分の登録： ＼明石順平　@junpeiakashi＼私は小泉進次郎を「ガス抜きマン」と呼んでいる。\n正義のヒーローっぽく振る舞うのが得意で，自民党の強い味方，それがガス抜きマン。 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi_5.html
[link:] 2019年02月19日21時54分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-02-15_2250〜2019-02-19_2149／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月19日21時54分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-02-1522502019-02.html
[link:] 2019年02月19日21時54分の登録： ＼明石順平　@junpeiakashi＼拙著の宣伝ありがとうございます！\nあのぅ・・大変申し上げにくいのですがわたくし1984年8月8日生の34歳でして，40代ではないの http://hirono2014sk.blogspot.com/2019/02/junpeiakashi-1984883440.html
[link:] 2019年02月23日05時59分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-02-18_2305〜2019-02-23_0240／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月23日05時59分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-02-1823052019-02.html
Diginnos-PC:~
[9987]  % dp -p |grep junpeiakashi
[link:] 2019年02月01日20時57分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-01-23_2222〜2019-02-01_1808／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月01日20時57分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-01-2322222019-02.html
[link:] 2019年02月01日20時57分の登録： ＼明石順平　@junpeiakashi＼ついに降伏したか。 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi.html
[link:] 2019年02月04日06時38分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-01-28_2257〜2019-02-04_0115／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月04日06時37分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-01-2822572019-02.html
[link:] 2019年02月04日06時38分の登録： ＼明石順平　@junpeiakashi＼弁護士＝サヨク＝攻撃対象みたいな認識のツイッタラーが一定割合いる気がする。 こういう輩がクソリプを飛ばして来たら即ブロック。 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi_4.html
[link:] 2019年02月05日11時15分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-02-01_1418〜2019-02-05_1059／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月05日11時15分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-02-0114182019-02.html
[link:] 2019年02月05日11時15分の登録： ＼明石順平　@junpeiakashi＼私は小泉進次郎を「ガス抜きマン」と呼んでいる。\n正義のヒーローっぽく振る舞うのが得意で，自民党の強い味方，それがガス抜きマン。 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi_5.html
[link:] 2019年02月19日21時54分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-02-15_2250〜2019-02-19_2149／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月19日21時54分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-02-1522502019-02.html
[link:] 2019年02月19日21時54分の登録： ＼明石順平　@junpeiakashi＼拙著の宣伝ありがとうございます！\nあのぅ・・大変申し上げにくいのですがわたくし1984年8月8日生の34歳でして，40代ではないの http://hirono2014sk.blogspot.com/2019/02/junpeiakashi-1984883440.html
[link:] 2019年02月23日05時52分の登録： ＼ささきりょう　@ssk_ryo＼明石さん（@junpeiakashi）から統計問題についてレクチャーを受ける。 http://hirono2014sk.blogspot.com/2019/02/sskryojunpeiakashi.html
[link:] 2019年02月23日05時59分の登録： ＃明石順平　@junpeiakashi＃のツイート／2019-02-18_2305〜2019-02-23_0240／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月23日05時59分 http://hirono2014sk.blogspot.com/2019/02/junpeiakashi2019-02-1823052019-02.html
Diginnos-PC:~
```

　プロフィールの名前「明石順平」とアカウント名「junpeiakashi」の検索結果は同じようです。中には頻繁にプロフィールの名前を変更する弁護士アカウントも少数ですが、います。

　今年の２月１日が最初の記録だったのは、かなり意外でした。それだけ目にする機会が少ない弁護士アカウントだったのだと思います。これは、同業者の弁護士に余りリツイートされていないこと、特に感想のないツイートが多かった、という傾向になりますが、目安です。

　次に、スクリーンショットについて調べてみました。スクリーンショットの記録は昨年つまり２０１８年の７月３０日からありますが、ほとんどは他の弁護士アカウントのリツイートとなっています。

```
[9993]  % locate junpeiakashi | grep -E '.*\.jpg$' | gawk -F/ '{print $NF "\n"}'
2018-07-30-183402_深澤諭史のリツイート（明石順平　@junpeiakashi）：【本当にあった怖い話】過労死が発生したとある会社が取った手段は，タイムカード.jpg

2018-08-11-214846_佐藤正子のリツイート（明石順平　@junpeiakashi）：大事なのは、P６の「ア被告人ＢがＧ議員に対し，怨恨を持つに至った経緯」ってい.jpg

2018-08-11-214935_佐藤正子のリツイート（明石順平　@junpeiakashi）：例の安倍晋三宅火炎瓶投擲事件というのは、裁判所ウェブサイトの裁判例情報に掲載.jpg

2018-09-02-142130_深澤諭史のリツイート（明石順平　@junpeiakashi）：岡口さんの件は，「懲戒申立自体がパワハラの一環としてなされているのでは？」と.jpg

2018-09-18-202318_明石順平（@junpeiakashi）：この返し，カッコイイ。.jpg

2019-02-04-063933_ささきりょうのリツイート（明石順平　@junpeiakashi）：弁護士＝サヨク＝攻撃対象みたいな認識のツイッタラーが一定割合いる気がする.jpg

2019-02-04-064109_ささきりょうさんがリツイート＞　明石順平（@junpeiakashi）：　弁護士＝サヨク＝攻撃対象みたいな認識のツイッタラーが一定割合いる気がする。こう.jpg

2019-02-04-064149_明石順平（@junpeiakashi）さん　｜　Twitter.jpg
```

　なお、検索に使ったlocateコマンドは、最新の状態にするのにコマンドの実行が必要となるのですが、事前に行っていないので、今日を含めた最近のものは存在していても反映されていません。

　「locate junpeiakashi | grep -E '.*\.jpg$' | xargs -i cp -p {} w/」というコマンドで画像ファイルをコピーし、非常上告-最高検察庁御中_ツイッター（@s_hirono）に投稿しました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-23 07:20／2019-02-23 07:11 URL： https://twitter.com/kk_hirono/status/1099071371831795718 https://twitter.com/s_hirono/status/1099069069762846720
&twitter(1099071371831795718){theme:light}
> 2018-07-30-183402_深澤諭史のリツイート（明石順平　@junpeiakashi）：【本当にあった怖い話】過労死が発生したとある会社が取った手段は，タイムカード.jpg https://t.co/piPirr1dTS
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-23 07:20／2019-02-23 07:11 URL： https://twitter.com/kk_hirono/status/1099071387677876224 https://twitter.com/s_hirono/status/1099069143003713536
&twitter(1099071387677876224){theme:light}
> 2018-08-11-214846_佐藤正子のリツイート（明石順平　@junpeiakashi）：大事なのは、P６の「ア被告人ＢがＧ議員に対し，怨恨を持つに至った経緯」ってい.jpg https://t.co/v98puxWFeH
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-23 07:20／2019-02-23 07:11 URL： https://twitter.com/kk_hirono/status/1099071408334725121 https://twitter.com/s_hirono/status/1099069216362098689
&twitter(1099071408334725121){theme:light}
> 2018-08-11-214935_佐藤正子のリツイート（明石順平　@junpeiakashi）：例の安倍晋三宅火炎瓶投擲事件というのは、裁判所ウェブサイトの裁判例情報に掲載.jpg https://t.co/3y9soO8OK8
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-23 07:20／2019-02-23 07:11 URL： https://twitter.com/kk_hirono/status/1099071425753706497 https://twitter.com/s_hirono/status/1099069290467098626
&twitter(1099071425753706497){theme:light}
> 2018-09-02-142130_深澤諭史のリツイート（明石順平　@junpeiakashi）：岡口さんの件は，「懲戒申立自体がパワハラの一環としてなされているのでは？」と.jpg https://t.co/CWJIsTZNCt
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-23 07:20／2019-02-23 07:12 URL： https://twitter.com/kk_hirono/status/1099071445877977088 https://twitter.com/s_hirono/status/1099069363900960768
&twitter(1099071445877977088){theme:light}
> 2018-09-18-202318_明石順平（@junpeiakashi）：この返し，カッコイイ。.jpg https://t.co/HRCnHoQTaN
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-23 07:20／2019-02-23 07:12 URL： https://twitter.com/kk_hirono/status/1099071469940690945 https://twitter.com/s_hirono/status/1099069436806389760
&twitter(1099071469940690945){theme:light}
> 2019-02-04-063933_ささきりょうのリツイート（明石順平　@junpeiakashi）：弁護士＝サヨク＝攻撃対象みたいな認識のツイッタラーが一定割合いる気がする.jpg https://t.co/xx23QM39Uf
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-23 07:20／2019-02-23 07:12 URL： https://twitter.com/kk_hirono/status/1099071491763654668 https://twitter.com/s_hirono/status/1099069509950832640
&twitter(1099071491763654668){theme:light}
> 2019-02-04-064109_ささきりょうさんがリツイート＞　明石順平（@junpeiakashi）：　弁護士＝サヨク＝攻撃対象みたいな認識のツイッタラーが一定割合いる気がする。こう.jpg https://t.co/idzKjkcIjk
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-23 07:20／2019-02-23 07:13 URL： https://twitter.com/kk_hirono/status/1099071528140910593 https://twitter.com/s_hirono/status/1099069584085213186
&twitter(1099071528140910593){theme:light}
> 2019-02-04-064149_明石順平（@junpeiakashi）さん　｜　Twitter.jpg https://t.co/XYzTnHXUNw
◁◁◁
<hr />

　２０１７年９月１８日から２０１８年２月４日というけっこう長い間がありますが、こういうのも記録をしっかりしておかないと、他のアカウントと混同し迷惑を掛ける可能性もありそうです。昨年はアイコンが違っていたようですが、そういえばと思い出すアイコンでした。

　なにか沖縄のシーサ像に似た、古代の遺跡なのかと思っていましたが、それが大仏にアイコンに変わるとは思いませんでした。信仰心のあらわれなのか、それはご本人しかわからないですが、人を救済したいという気持ちがあってのことなのかもしれません。

　次に、テキストファイルとして登録済みの弁護士ツイートデータから調べてみました。出来ないことはないですが、現時点でそれほどの必要性は認めないので、まとめ記事は作成しません。これはデータベースへの登録とまとめ記事の作成、投稿を行うコマンドです。

```
[10009]  % list-tweet-egrep.sh 明石順平|tail -n 12
https://twitter.com/kubotch52/status/1080049764819886080
https://twitter.com/kubotch52/status/1078637943735037954
https://twitter.com/kubotch52/status/1077488710713729024
https://twitter.com/kubotch52/status/1037305765311131648
https://twitter.com/reeeiinaaaa/status/1082907988006862849
https://twitter.com/wata_nabekyo_ko/status/1026358173718917120
4384 /home/a66/l



for i in `cat ~/l`; do k4-tweet-add-mysql-uniq-argv.rb $i; done
ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "明石順平"
```

```
なべきょう＠過眠症
@wata_nabekyo_ko
東京→小規模支部→地方本庁。登録１３年めに入りました。「居眠り病」ナルコレプシーの中核群患者、眠気ともたたかう弁護士。

ねこのいる場所
2011年12月に登録

［source：］なべきょう＠過眠症(@wata_nabekyo_ko)さん | Twitter https://twitter.com/wata_nabekyo_ko/
```

　最後になっている上記の「なべきょう＠過眠症(@wata_nabekyo_ko)さん」のリツイートですが、元の明石順平弁護士のツイートは次の内容となっていました。とても考えさせられる内容であり、とても具体的です。

▷ リツイート→wata_nabekyo_ko（なべきょう＠過眠症）＞junpeiakashi（明石順平）｜2018/08/06 15:43／2018/08/05 22:25｜https://twitter.com/wata_nabekyo_ko/status/1026358173718917120 ／ https://twitter.com/junpeiakashi/status/1026096798727725057
&twitter(1026358173718917120){theme:light}
> RT @junpeiakashi: 長時間労働は無くせると信じている。日本人は同調圧力に弱いので、社会全体が「長時間労働は絶対にあり得ない」っていう空気になれば無くなると思うんだ。あんなにタバコがそこらじゅうでスパスパ吸われていたのが、今は「禁煙当たり前」になったようにね。  

　社員のために長時間労働をなくす、という考えなのでしょうが、弁護士が会社や社会に与える負担が、そのまま労働者のしわ寄せとなって悪循環を繰り返す、負のスパイラルという側面があるように思えてなりません。裁判所に対する負担も大きなもので、その代表格が佐々木亮弁護士とも。

　佐々木亮弁護士は人としては悪くないように感じてきました。むやみにブロックをすることもなさそうですが、明石順平弁護士は、プロフィールで「すぐブロックします。」という宣言をしています。それも個人の考えとは思いますが、高く理想を抱えながら排他的には感じます。

　次に、その佐々木亮弁護士について取り上げておこうかと思いますが、なるべく簡略にしておきたいと思います。データがとりわけ少ない明石順平弁護士でも、けっこうな分量の記載になったかと思います。

＜＜＜2019-02-23（土曜日）07：56＿［これまでの記述範囲の終了時刻］＜＜＜

* 「日本労働弁護団常任幹事。ブラック企業被害対策弁護団代表。」とTwitterのプロフィールにある佐々木亮弁護士
  :LOGBOOK:
  CLOCK: [2019-02-23 土 08:03]--[2019-02-23 土 10:49] =>  2:46
  :END:

＞＞＞2019-02-23（土曜日）08：03＿［これからの記述範囲の開始時刻］＞＞＞

　これまでに何度も見てきた佐々木亮弁護士のTwitterプロフィールだと思いますが、「ブラック企業被害対策弁護団代表」という部分で、「代表」とあるのは、今回初めて気がついた気がします。あるいは、可能性の１つですが、最近、代表になったということもあるのかもしれません。

　ここでは簡単にご紹介しようと思いながら、ずっと前から日本の刑事弁護を語る上で、とても重要な事例と考えている冤罪事件がありまして、佐々木亮弁護士のことは、その冤罪事件の担当弁護士ということで知ったのが初めてだったと思います。

　私は２０１０年４月２日からTwitterを始めていますが、佐々木亮弁護士のことを知ったのは、その前だったように思います。Yahooのニュース記事のようなブログ記事で見てきたように思うのですが、そういえば、もう何年も目にしていない佐々木亮弁護士のニュース記事です。

　このYahooのニュース記事というのは、最近もジャーナリストの江川紹子氏の記事として見かけることが多いと思います。あるいはYahooのニュース記事ということ自体が、私の記憶違いなのかもしれないですが、その冤罪事件については、検索しても情報が見つかりづらくなっていました。

　先に、次が現在の佐々木亮弁護士のTwitterアカウントのプロフィールになります。


```
ささきりょう
@ssk_ryo
弁護士（東京弁護士会）、旬報法律事務所。労働者側で労働事件をやっています。日本労働弁護団常任幹事。ブラック企業被害対策弁護団代表。ブラック企業大賞実行委員。見る将棋好き。活動は東京近辺。なお、ここでの投稿は私の所属する弁護団や団体とは無関係であり、あくまでも私的見解です。

東京都
bylines.news.yahoo.co.jp/sasakiryo/
2010年6月に登録

［source：］ささきりょう(@ssk_ryo)さん | Twitter https://twitter.com/ssk_ryo
```

　時刻は８時１５分になります。さきほどこれまでのエントリーを奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)に投稿処理したところ、パソコンの時刻が７時５８分となっていたので驚きました。けっこう長い時間、時間のことを忘れ没頭していたようです。

　もう１０日ほどになりますか「hatenablog-twitter-update.sh」というコマンドを作成しました。シェルスクリプトです。

　外部のサーバにあるデータを使って、Twitterに投稿済みでないエントリーを、Twitterに投稿処理します。最後に投稿した情報をサーバに送り、書き換えます。今回は次の４件が新規の投稿でした。長くなる日本語エンコードのURLがTwitterの短縮URLとなっています。

```
[9999]  % ut hirono_hideki 4
TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-02-23 07:57 URL： https://twitter.com/hirono_hideki/status/1099080869409480704
> 5491： 参考資料／弁護士業界の現状／秋田の弁護士刺殺／深澤諭史弁護士のタイムラインで見ていた秋田の弁護士刺殺の損害賠償の判決、２月１３日に出ていた判決と今日知った - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/HWwLbfrk5l

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-02-23 07:58 URL： https://twitter.com/hirono_hideki/status/1099080895724630016
> 5492： ＃　深澤諭史弁護士のタイムラインで見ていた秋田の弁護士刺殺の民事裁判の控訴審逆転勝訴判決 https://t.co/T0MBtcBMoO

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-02-23 07:58 URL： https://twitter.com/hirono_hideki/status/1099080922085740549
> 5493： 参考資料／労災／労働裁判／佐々木亮弁護士と親交のあるらしい大仏アイコンの明石順平弁護士が代理人として提訴した労災死 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/siYWztfw2b

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2019-02-23 07:58 URL： https://twitter.com/hirono_hideki/status/1099080948446986240
> 5494： ＃　これまでに何度か見かけてきた二人のTwitterの大仏アイコンの一人、実名の明石順平弁護士 https://t.co/NPtwIsqsDV
```

　厳密に私の定義でいうと、5491、と5493がエントリー名になります。その他は項目名です。「＃　」を接頭辞にすることで項目名を区別していますが、これがブログ記事のページ内リンクとなっていて、それが本来、日本語のエンコードを含む長いURLとなっています。

　この項目も2カ月ほど前になりますか、階層の3段階まで対応するようにしたのですが、2段階、3段階ともに使用はしていません。ややこしくするとかえって混乱を招きかねないと考えたからです。ただでさえエントリーが長くなりがちなのに、余計に長くなることも危惧しました。

　このエントリーというのは、はてなブログの１つの記事に対応しますが、個別のブログ記事では1ページに相当します。ツイートの埋め込みが200件を超えると、全部適用されなくなるという現象を過去に経験してきました。それも1つの制約となっています。

　はてなブログも、一日の投稿に文字数の制限があるらしく、具体的に確実な情報は探しても見つけることが出来なかったのですが、はてなダイアリーの頃は、なんの警告もエラーも出ないまま、文章の末尾がカットされていたことがありました。たぶんデータベースのデータ型なのだと思います。

```
BLOB型はバイナリデータを扱うデータ型で格納できるデータのサイズを指定しません。ただ最大長は決まっており、最大長の種類によって次の4つが用意されています。

TINYBLOB
  最長255 (28 - 1) バイト

BLOB［(M)］
  最長65,535 (216 - 1) バイト

MEDIUMBLOB
  最長16,777,215 (224 - 1) バイト

LONGBLOB
  最長4,294,967,295、または4GB (232 - 1) バイト
TEXT型は文字列データを扱うデータ型で格納できるデータのサイズを指定しません。ただ最大長は決まっており、最大長の種類によって次の4つが用意されています。

TINYTEXT
  最長255 (28 - 1) バイト

TEXT［(M)］
  最長65,535 (216 - 1) バイト

MEDIUMTEXT
  最長16,777,215 (224 - 1) バイト
  別名：LONG, LONG VARCHAR

LONGTEXT
  最長4,294,967,295、または4GB (232 - 1) バイト
BLOG型及びTEXT型はそれぞれ巨大なバイナリデータとテキストデータを格納する時に利用されます。

［source：］BLOB型とTEXT型 - MySQLのデータ型 - MySQLの使い方 https://www.dbonline.jp/mysql/type/index6.html
```

　私個人の目測では、「最長65,535 (216 - 1) バイト」が、はてなブログの一日辺りの投稿データの限界と考えています。はてなブログは、一日辺りの記事の投稿数にも上限があって、過去記事の再投稿をプログラムの処理でやって、リミットを超えたことがあります。

　翌日まで普通の記事の投稿ができなくなったのですが、その一日の始まりというのもよくわかりませんでした。はてなダイアリーの頃も、その一日の始まりが問題となったことがあったのですが、0時が一日の始まりでなかったことは記憶にあります。6時だったような気もします。

　はてなブログの場合は、通常のブログのようになっているので、今のところそれほど癖の強さも感じないですが、はてなダイアリーの頃は、その癖の強さで翻弄されるようなこともありました。まあ、普通に使っていれば問題は出ないと思いますし、他のブログに比べ制限は緩やかとも思います。

　本当はWordPressが自由度も高く、慣れもあったのですが、WordPress.comでは、有料ユーザと差別化があり、無料ユーザだとCSSの編集も出来ませんでした。本当は有料でもよかったのですが、クレジットカードを持っていないので断念していました。

　はてな、も有料オプションがあって、それは利用したことがあったのですが、はてなのポイントの購入は当時、ファミリーマートでないと出来ませんでした。実際、30キロほど離れた穴水町のファミリーマートまで行って、はてなのポイントを購入したことがありました。

　もう3年ぐらいは経つように思いますが、宇出津にあるコンビニがサークルKからファミリーマートに変わりました。これは吸収合併のようなものだったと思います。

　宇出津のコンビニでは「ダム・キーパー」のiTunesをダウンロードするため、なにかのポイントのカードを購入したことがありました。今ならWordPress.comでもコンビニで購入できるポイント決済が可能なのかもしれません。

　少しでも余裕があり、羽咋市で生活していた頃のように上限は少なかったですが、クレジットカードを持っていれば、WordPressの有料オプションを使っていたと思います。しかし、その有料オプションを使っていると思われる弁護士というのは全く見ない気がするので、気になっていました。

　WordPressはたくさんのプラグインもあるはずですが、それを使っているのも見た覚えがありません。私はWordPress.orgを主に使っていましたが、これは自前のサーバでのインストールになります。制約はありませんが、ネット回線の帯域が事実上の制限になると思います。

　時刻は9時26分です。台所で井村屋のピザマンを食べていました。2,3日前、Aコープ能都店で広告の品などとシールがあったので買ってきたものです。3つ入りですが、小ぶりで具も少ないように感じました。そういえば大きなサイズの肉まん系は、このところ久しく見かけていません。

　最近はスーパーに行く回数がだいぶん減っているので見かける機会も少ないのだとは思いますが、この冬になっては一度も見ていない気がします。安売りでない時に4個入りで398円ぐらいの商品です。ほとんどは組み合わせで2種類が入っていたと思います。

[link:] » https://t.co/obVfYSIe1X プランと料金 – 今すぐ無料で開始 ! https://t.co/lnBT4pTDLT

<hr />

　ピザまん、を食べる前に開いて少し見ていたページです。そのままURLを貼り付けたのですが、URLがものすごく長いものだったので、ツイートに変更しました。何というのか忘れましたが、WordPressの自由度が高いとURLの形式を変更することが出来るはずです。

　普通のWordPress.comでも、idで記事を開くことが出来て、普通は見つけにくいidの情報でしたが、Webページのソースから探し出すことは出来たように思います。

　次が実際のidを指定したURLになります。

中村元弥さんのツイート: "@amneris84 朝飯に行っていて、お返事遅れました。要旨しか把握していませんが、落合コメントに同感です。調書裁判からの脱却はこんなラフな判断ではないはずです。登石さんは、元司法研修所教官のようですが、教え子にこの判決をどう説明するのかと思います" https://hirono2016s.wordpress.com/?p=84413

　文字数が長いので一時的に2分割して、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)に投稿しました。

　WordPressでは最新の投稿になりますが、このところ余り投稿はしていません。84413が記事のidになりますが、ｐというのがリクエストパラメータの変数になります。このあたりはWebアプリを自作でやってきたので、仕組みがよくわかります。

　最近の佐々木亮弁護士の動向に関しては、ご自身の次の固定ツイートをみるだけで、だいたいよくわかると思います。自ら公明正大にやっておられるようですし、一点の曇も感じられません。

▶ ツイート％ssk_ryo（ささきりょう）％2018/11/02 07:40％ https://twitter.com/ssk_ryo/status/1058126771441135617
&twitter(1058126771441135617){theme:light}
> 書いておいた。：＜大量懲戒請求＞提訴に至る経緯とその意義について(佐々木亮) - Y!ニュース https://t.co/vD5M8Lcq8V  
▶

　よく見ると、リンクの記事がyahooニュースでした。yahooニュース個人というのは、ジャーナリストの江川紹子氏と同じだと思いますが、記事のデザインが違っているようにも感じます。

［link：］ 乳腺外科医への無罪判決が意味するもの(江川紹子) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/egawashoko/20190220-00115538/

　ランキング5位となっていたジャーナリストの江川紹子氏の記事を開いたところ、ページのデザインは佐々木亮弁護士のものと変わりがないようでした。なにか印象が違っていたので、ページのデザインまで違っているように勘違いしていたようです。

　20日の公開ということで3日ほど経過していますが、5位というランキングは関心が余りないことの現れなのか、ジャーナリストの江川紹子氏に対する不信感や悪印象が影響しているのかなど、いろいろと想像します。無罪に対する関心自体が低くなっている傾向はありそうです。

［link：］ 24時間のコンビニが「ブラック化」する構図(今野晴貴) - 個人 - Yahoo!ニュース https://news.yahoo.co.jp/byline/konnoharuki/20190222-00115736/

　ランニングの1位となっているのは上記の記事で、今野晴貴という人が筆者のようですが、ランニングではジャーナリストの江川紹子氏以外で、唯一見覚えのある名前です。しかし、どこでどんな記事を見たのか、それさえ思い出せません。

```
[10001]  % dp -p|grep 今野晴貴
[link:] 2017年10月22日23時32分の登録： ＼徳武聡子　@Satoko_Tokutake＼子どもの貧困率削減は本当に「好ましい」のか？  貧困率削減の「カラクリ」(今野晴貴) - Y!ニュース http://hirono2014sk.blogspot.com/2017/10/satokotokutake-y.html
[link:] 2017年11月06日13時31分の登録： ＼今野晴貴　@konno_haruki＼めざそうホワイト企業 経営者のための労務管理改善マニュアル ホワイト弁護団 http://hirono2014sk.blogspot.com/2017/11/konnoharuki.html
```

　思い浮かばないのですが、Twitterのアカウントが存在したようです。「ホワイト弁護団」とある記事の内容もさっぱり記憶にありません。ちょっと気になったので確認のため検索を実行したのですが、結果が出たことに少し驚きました。あると思ったものが存在しないことはあります。

```
今野晴貴
@konno_haruki
労働・福祉運動家／社会学者。ＮＰＯ法人ＰＯＳＳＥ代表。ブラック企業対策プロジェクト共同代表。年間2500件以上の労働・生活相談に関わり、労働・福祉政策について研究・提言している。著書に『ブラック企業』、『生活保護』、『裁量労働制はなぜ危険か』など多数。大佛次郎論壇賞、流行語大賞トップ１０などを受賞。1983年生まれ。

日本
npoposse.jp
2010年4月に登録

［source：］今野晴貴(@konno_haruki)さん | Twitter https://twitter.com/konno_haruki
```

　アイコンを見たところ、全く見覚えがないですが、形が警察官などが肩の辺りにつけていそうなワッペンに見えます。昔、テレビの西部劇で見たアメリカの保安官に近いかもしれません。そこに「ブラック企業」と書いてあるのが読み取れます。

　社会学者とあるので大学の関係者にも思えますが、プロフィールに大学名は見当たりません。労働・生活相談に関わり、とありますが、弁護士資格がないのに報酬を得ていれば、深澤諭史弁護士が目の敵とする非弁ということにもなりそうな気がします。

　年間2500件というのもとてつもない数字です。多種多様な経験はされていることでしょう。Twitterに記事のブログカードがあってそこに顔写真と思われるものがありました。まだリンクも開いていないですが、どこかで見覚えのある人物の顔写真だと思いました。しかし、相当前とも思います。

［link：］ 人身事故 - Twitter検索 https://twitter.com/search?q=%E4%BA%BA%E8%BA%AB%E4%BA%8B%E6%95%85&src=tren

　今野晴貴氏のTwitterアカウントをみているとき、トレンドに「人身事故」とあったので、少し気になり開いてみました。昨夜の22時に小田原付近で人身事故があったというツイートがありましたが、他の場所に関するツイートも散見されます。

　そういえば、21日だったと思うので一昨日になりますが、新井浩文氏の強制性交等罪の起訴があった日、けっこう意識してTwitterのトレンドを見ていたのですが、それに関連したワードを見ることがなく、気になっていました。

　時刻は10時29分になったところですが、テレビはつけていません。金曜日は普通で23時30分からの開始となるニュースzeroですが、それが終わって次の番組が始まってすぐにテレビを消し、それからつけていません。目が覚めてしばらくしてから時間を見ると5時45分でした。

　ウェークアップぷらす、という情報番組ですが、今日の土曜日の放送だったと思うので、録画しておけばよかったと今になって思いました。気になる一番のニュースは、高野隆弁護士が担当した、外科医のわいせつ事件の無罪判決です。準強制わいせつという見出しも内容を見ていない気がします。

　そういえば、昨夜、一日前のeveryを途中から録画をしていたのを再生していたのですが、弁護士の横領などと項目の見出しがあったものが、内容の放送がなかったように思いました。これは再生も途中で中断したので、全ての確認はしていません。

　everyは「となりのテレ金ちゃん」として録画されていました。最初に録画の一覧でみたとき違和感を感じたのですが、番組一本の録画だと約3時間ほどの録画にもなるようです。銭湯に行くために録画をしたのだと思います。

　弁護士の横領の件は、寺への寄付を横領したという事件で、被害額も1億6千万円と高額でした。ネットの記事で見たものですが、元弁護士となっていました。他に開いて読んでいた記事の枠外にリンクとして目にしたニュースでした。

　テレビニュースとしては見ていないです、外科医の無罪判決とは違って、最初からテレビのニュースになることはないという思い込みがあり、調べることも確認する作業もしていませんでした。

　あるキーワードでまとめ記事を作成しましたが、私のアカウント以外は1件だけのツイートでした。佐々木亮弁護士のことからはしばらく離れ、そちらを記録用に取り上げておきたいと思います。

＜＜＜2019-02-23（土曜日）10：49＿［これまでの記述範囲の終了時刻］＜＜＜

