#+TITLE: "保険金目的計画殺人事件のニュースから考える市場急配センターへの疑惑と事実"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-30 08:52:51 +0900
FILE_NAME: 2019-08-30-085251_保険金目的計画殺人事件のニュースから考える市場急配センターへの疑惑と事実.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 平成3年6月と思われる金沢市場輸送から市場急配センターへの移行  被告発人松平日出男 被告発人安田敏 被告発人安田繁克 被告発人多田敏明 被告訴人池田宏美 本恒夫社長 金沢市場輸送 市場急配センター
記事タイトル名の文字数：36　保存ファイル名の文字数：58

* 保険金目的計画殺人事件のニュースから考える市場急配センターへの疑惑と事実
  :LOGBOOK:
  CLOCK: [2019-08-30 金 08:54]--[2019-08-30 金 12:56] =>  4:02
  :END:

＞＞＞2019-08-30（金曜日）08：54＿［これからの記述範囲の開始時刻］＞＞＞

　昨夜になりますがテレビで会社での保険金目的殺人事件のニュースをみました。この手の事件が発覚してニュースになるのもここ数年、珍しいことだとあらためて思いました。今朝は８時からテレビのチャンネルを変更していますが、同じ事件を取り上げた放送は見ていません。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-30 09:04／2019-08-30 08:45 URL： https://twitter.com/kk_hirono/status/1167226488850022400 https://twitter.com/hirono_hideki/status/1167221801341947905
&twitter(1167226488850022400){theme:light}
> 【独自】養子にし保険金殺人の疑い　LINEの“殺人計画”入手 - https://t.co/rhl1VQHP9pプライムオンライン https://t.co/S9gbar4onD
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-30 09:04／2019-08-29 22:14 URL： https://twitter.com/kk_hirono/status/1167226622849630208 https://twitter.com/hirono_hideki/status/1167062953759137797
&twitter(1167226622849630208){theme:light}
> 大阪のトラック運転手殺害事件が一件落着---犯人、そして事件の真相は! | レスポンス（https://t.co/PR64r8UBAL） https://t.co/8yPERDXkn1 \n  2002年5月7日（火） 12時00分
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-30 09:04／2019-08-29 22:09 URL： https://twitter.com/kk_hirono/status/1167226639354232832 https://twitter.com/hirono_hideki/status/1167061605080633344
&twitter(1167226639354232832){theme:light}
> 大阪のトラック運転手殺害事件が一件落着---犯人、そして事件の真相は! | レスポンス（https://t.co/PR64r8UBAL） https://t.co/8yPERDXkn1 \n  父親は借金の返済のために自らに保険をかけて、… https://t.co/6HZuyIef6Y
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-30 09:04／2019-08-29 22:08 URL： https://twitter.com/kk_hirono/status/1167226663525990400 https://twitter.com/hirono_hideki/status/1167061522167652353
&twitter(1167226663525990400){theme:light}
> 大阪のトラック運転手殺害事件が一件落着---犯人、そして事件の真相は! | レスポンス（https://t.co/PR64r8UBAL） https://t.co/8yPERDXkn1 \n  親子をトラック運転手に対する殺人と死体遺棄の… https://t.co/fISS8qmdVU
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜news23_tbs（NEWS23） 日時：2019-08-30 09:05／2019-08-29 18:45 URL： https://twitter.com/kk_hirono/status/1167226678419972096 https://twitter.com/news23_tbs/status/1167010280657698817
&twitter(1167226678419972096){theme:light}
> こんや１１時のnews23▼保険金目的で男性を殺害したとして千葉県の内装会社社長ら３人を逮捕。去年、男性は容疑者の養子になったばかり･･･事件の詳細は▼”最側近“に次々と浮上する疑惑･･･韓国・文大統領にも批判が集まっています。日… https://t.co/EMh4q5TIPy
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bleedingLOVEjw（イトウ） 日時：2019-08-30 09:05／2019-08-27 02:50 URL： https://twitter.com/kk_hirono/status/1167226704831508481 https://twitter.com/bleedingLOVEjw/status/1166045380091363328
&twitter(1167226704831508481){theme:light}
> トラック 保険金 \n  https://t.co/kFxxBBd0bm
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜FNN_News（FNN.jpプライムオンライン） 日時：2019-08-30 09:05／2019-08-29 12:15 URL： https://twitter.com/kk_hirono/status/1167226730878128128 https://twitter.com/FNN_News/status/1166912103405375488
&twitter(1167226730878128128){theme:light}
> 海に転落させ養子殺害か　保険金目的? 3人逮捕 \n   \n  2019年1月、養子にした23歳の男性を保険金目的で海に転落させ殺害したとして、養父の男ら3人が逮捕された。逮捕されたのは、内装会社社長・宍倉靖雄容疑者(48)と佐中佑輔容疑者(3… https://t.co/WlaAYpRSf7
◁◁◁
<hr />

　Twitterで検索をしたのですが、指定したキーワードの記録がなく、記憶にもありません。「保険金殺人」などというものであったかもしれません。内容で驚いたのは大阪のトラック運転手の殺害事件ですが、確認すると２００２年の事件となっていました。初めて知った事件と思います。

　2002年5月7日といえば、ずっと前になくなっていますが、家の近くの電子部品の工場に仕事に行っていた時期で、朝は７時から８時の間の出社で、終わって家に戻るのは毎日２３時ぐらいだったと思います。はっきりした時間は忘れていますが、ハンダ槽の管理をしていました。

　テレビを見る時間も少なくて、事件事故という社会のニュースも情報としてほとんど入らない生活をしていました。自分がやっていることがどうのというより、そのような生活を長年、普通に続けていることを知ったのが、１つの社会勉強だったと思い出す時期です。

　４月に入っての入社でしたが、すぐにソーテックのパソコンを買いました。七尾市の消費者金融まで１０万円ほど借りに行ったこともよく憶えています。４月の中頃だったと思いますが、いきなりKYNが宇出津の自宅に訪ねてきたことがありました。

　被告発人安田敏と会い、宇出津の自宅に来てもらったのも同じ頃のことで、４月の７日ぐらいであったように思うのですが、その翌日にも宇出津新港の職業安定所で被告発人安田敏と会ったような記憶があります。

　妻が運転していたと思われる古いパジェロのような車のことも記憶にあるのですが、それは職業安定所ではなく、別の場所で見たという記憶がかすかに残っていて、近くのショッピングタウンアルプの駐車場であったかもしれません。いずれも記憶の新しい段階の記述が記録にあると思います。

　その時、被告発人安田敏は、富山県の高岡市の方に仕事の面接に行くことが決まったというような話をしていたように思います。話を聞いていると、長続きする仕事がなく、出稼ぎのようなかたちで石川県内を転々としていて、妻子は七見の町営住宅に残しているような話でした。

　その時だったかわかりませんが、宇出津の新崎という小さな運送会社で、宇出津の魚市場から金沢まで鮮魚を運ぶ仕事もしていたと話していました。もっと時期が不明ですが、柳田運送で仕事をしているとき、ちょっとした人身事故で送検されたような話もしていました。

　新崎という運送会社のことは全く知らず、宇出津で聞いたこともない名前だったのですが、柳田運送は割と大きな会社だったのか、トラックを見かけることも多かったのですが、それもずっと前に会社がなくなったようです。そういえば新崎のトラックもここ数年は見かけていないと思います。

　宇出津の魚市場は、早朝から午前中が忙しく、今は宇出津新港に魚釣りに行くこともないので、その忙しい時間に魚市場の前を通ることはなく、それでたまたま新崎のトラックを見かけていないだけかもしれません。ただ、漁運会のトラックは、魚市場以外でも見かけることが多いです。

[link:] » 字七見 - Google マップ https://t.co/0yhf4LfQxs

<hr />

[link:] » 能登桜木（バス） - Google マップ https://t.co/SGfIAStrwc

<hr />

　七見と聞いていた町営住宅は、桜木団地という看板が近くにあって、そういう名称なのかと考えていたのですが、Googleマップで調べると、桜木という地名は七見ではなく鵜川になるようです。　

　国道２４９号線で団地の入り口のような交差点のところに、ずっと前から学校があって、私はそれをずっと鵜川中学校の校舎だと思い込んでいたのですが、つい最近になって人から鵜川小学校だと教えられたことがありました。Googleマップでも旧鵜川小学校となっていて確認が出来ました。

　被告発人安田敏の実家は鵜川になります。平成１４年だとまだ能都町でしたが電話帳で調べると、１０件弱ほど鵜川に安田という家の電話番号があって、２，３件目ぐらいですぐに親戚というような人から、被告発人安田敏の実家の電話番号を教えてもらうことが出来ました。

　被告発人安田敏の実家に電話を掛けて母親と話をした記憶はないのですが、七見の町営住宅に住んでることがわかって、電話番号もすぐにわかったように思います。実家には直接電話を掛けていないかもしれません。

　前にも少し書いたことがあると思いますが、私は昭和５６年の１１月頃、七尾市の家庭裁判所の待合室で、被告発人安田敏とその母親とたまたま出くわしたということがありました。

　ついでに書いておくと、平成９年の２月頃も、私は被告発人安田敏に連絡をとっていて、その時は、すぐに折り返しで被告発人安田敏から電話がありました。場所は金沢市湊が住所だったと思いますが、北都高速の寮だと話していました。

　携帯電話から掛けていると言っていましたが、時間のあたりの通話料を気にすることもなくけっこう長話をしたと記憶にあります。私に関する情報を少しでも知りたがっている様子でもあり、以前の被告発人安田敏とは態度にも変化を感じました。

　電話といえば、平成３年当時、被告発人安田敏は金沢市花里の自宅アパートの固定電話の線を抜き、被告発人松平日出男や被告発人東渡好信にせかされて、アパートまで車で確認に行ったことまでありました。市場急配センターの会社からはかなり離れた場所です。

　アパートと行っても普通の共同住宅のような建物ではなく、工務店の作業場の２階を間借りしているような住居でした。外から見るとまずアパートには見えなかったと思いますが、中に入ると普通のアパートと違いはなかったと思います。

　入ってすぐに割と広く感じるダイニングキッチンがあり、その奥に和室が一つだけありました。８畳ぐらいあったように思いますが、奥の半分ほどはダブルベッドが専有していました。余り見かけるものではなかったですが、大きさはセミダブルのサイズだったかもしれません。

　そのベッドで寝そべって頭からすっぽりタオルケットを被っている、それが妻がいる時のお決まりの行動でした。そう何回も被告発人安田敏アパートに行っていたわけではないですが、妻が不在のことも同じ回数ぐらいあったような気もします。

　いちおう被告発人安田敏の妻としてきましたが、その平成３年１２月２５日頃に妻は長女を出産しており、それに近い時期に入籍したとも考えられるので、７月から９月頃の時点では、まだ結婚はしていなかったと考えられますし、知ってすぐに妻だと言われた記憶もありません。

　８月の最終日辺りから市場急配センターで長距離の仕事を始めました。８月の３０日か３１日の出発で、被告発人安田敏と二人で、神奈川県厚木市に荷物を運んだのが最初の運行だったと思います。

　車番は石川２３１３号だったと思うのですが、三菱ふそうの大型ウィング車で、被告発人安田敏はまもなくそのトラックの専属となりました。私の方は、石川３０６８号という日野の大型ウィング車に乗務したのですが、それが１０月１２日の土曜日のことでした。

　被告発人安田敏と同乗した長距離の運行というのは、その厚木市の１回しか現在記憶にありません。個人的に私の方が同乗した運行というのは１０月６日の日曜日にあって、朝からの日帰りで名古屋の北部市場に馬鈴薯を運んだ運行です。

　９月から１０月というのは、山三青果の仕事も少なかったと思いますし、多かったのは馬鈴薯の仕事で、東京の大田市場にも何度か行きました。そして晴海、有明の倉庫から外果というオレンジやレモン、キウィという外国から輸入されてきた果物を金沢に運ぶ仕事が多かったと記憶にあります。

　市場急配センターの長距離の仕事のメインは、茨城県古河市の山三青果の仕事でしたが、その古河市の青果市場で被告発人安田敏と一緒になったことは一度もなかったように思います。他の運転手が嫌がる負担のある仕事だったので、私と被告発人安田敏に集中的に回されていたというのはあると思います。

　市場急配センターで長距離の仕事をするようになってから金沢市花里の被告発人安田敏のアパートに遊びに行くことは、ほとんどなかったように思います。記憶にあるのは、さきほど書いた固定電話の線抜きで、呼びに行かされたことです。

　被告発人松平日出男も被告発人東渡好信も直接、被告発人安田敏を注意することはなく、決まって私に話を向けてきました。よくある口癖のように記憶にあるのは、「大丈夫なんかあの男」だったと思います。言葉のニュアンスが違っているかもしれないですが、記録には正確なものがあると思います。

　被告発人安田敏は非常識な振る舞いをみせるようになり、それがいつものことのように常態化して行ったのですが、その辺りも記録にはことこまかに記述をしていると思います。極めつけと思えたのが、水島倉庫でのタイヤの爆発と、愛知県の豊川インターでの白菜の散乱でした。

　豊川インターの白菜散乱は、平成４年２月１４日になります。いわずとしれたバレンタインデーの当日でした。にわかに信じがたい話で、ずっと半信半疑でしたが、被告発人安田敏との会話を録音した音声ファイルのなかで、言質を取るような質問を向け、成功したと思います。

　富山県の北陸自動車道、朝日インターの辺りで、大型トラックを崖下に転落させたという話もしていましたが、それも音声ファイルの中で確認が出来ていたように思います。東名高速岡崎インター付近かあるいは北陸自動車道長浜インター付近での、大がトラックでのパトカーからの逃走もありました。

　被告発人安田敏に話を聞いた時期が、現在ははっきり思い出せないものがあるのですが、たぶん高速道路上でのパトカーからの逃走を聞いたのと同じ時に、金沢市場輸送の運転手が石巻市の公園で首吊り自殺をしたという話を聞きました。

　新入の運転手という話だったと思いますが、元自衛隊員とも被告発人安田敏は話していたと思います。もしかすると別の被告発人安田敏の話と混同しているかもしれません。新入の運転手が２人いたとも聞いたような気もするからです。

　同じ時だったと思いますが、大倉さんが事故死したという話も被告発人安田敏に聞きました。事故の場所は国道１７号線の群馬県高崎市付近だったと思います。昭和５９年当時金沢市場輸送にいた原田さんが事故死しいたとYTに話を聞いたのも同じ高崎市付近だったので、余計に印象深く記憶にあります。

　被告発人松平日出男ですが、石川トヨタの営業で売上もよかったものの、競馬にのめりこんで会社の金を横領したという話でした。これは被告発人松平日出男を金沢市場輸送で初めて見て、ずいぶん早い段階で耳にした話でした。

　前にも書いていますが、昭和６３年の９月に入った頃だったと思います。同じ年の７月の初めころに、金沢市場輸送の事務所は金沢中央卸売市場前のテナントビル２階の事務所から二口町に移転していました。建物は現在でもGoogleストリートビューで、当時のまま確認できるのではと思います。

　もう２年ほどは見ていない気がしますが、これから確認をしたいと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-30 12:04／2019-08-30 11:40 URL： https://twitter.com/kk_hirono/status/1167271911744782336 https://twitter.com/s_hirono/status/1167265806234734592
&twitter(1167271911744782336){theme:light}
> 2019-08-30-112454_Googleストリートビュー＿金沢市場輸送の事務所があった場所＿06.jpg https://t.co/aY50BHgM5P
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-30 12:04／2019-08-30 11:40 URL： https://twitter.com/kk_hirono/status/1167271936897863680 https://twitter.com/s_hirono/status/1167265734101094401
&twitter(1167271936897863680){theme:light}
> 2019-08-30-112325_Googleストリートビュー＿金沢市場輸送の事務所があった場所＿05.jpg https://t.co/lqIAyHe35N
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-30 12:04／2019-08-30 11:39 URL： https://twitter.com/kk_hirono/status/1167271965050036224 https://twitter.com/s_hirono/status/1167265661770272768
&twitter(1167271965050036224){theme:light}
> 2019-08-30-112253_Googleストリートビュー＿金沢市場輸送の事務所があった場所＿04.jpg https://t.co/COvgqjgKzw
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-30 12:05／2019-08-30 11:39 URL： https://twitter.com/kk_hirono/status/1167271981814706176 https://twitter.com/s_hirono/status/1167265589691183104
&twitter(1167271981814706176){theme:light}
> 2019-08-30-112153_Googleストリートビュー＿金沢市場輸送の事務所があった場所＿03.jpg https://t.co/tycqruy1kc
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-30 12:05／2019-08-30 11:39 URL： https://twitter.com/kk_hirono/status/1167272004438740992 https://twitter.com/s_hirono/status/1167265517050007552
&twitter(1167272004438740992){theme:light}
> 2019-08-30-112133_Googleストリートビュー＿金沢市場輸送の事務所があった場所＿02.jpg https://t.co/QNQObfyqrz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-30 12:05／2019-08-30 11:39 URL： https://twitter.com/kk_hirono/status/1167272024386895872 https://twitter.com/s_hirono/status/1167265445042278401
&twitter(1167272024386895872){theme:light}
> 2019-08-30-112104_Googleストリートビュー＿金沢市場輸送の事務所があった場所＿01.jpg https://t.co/eF2zpO6LQl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-30 12:05／2019-08-30 11:38 URL： https://twitter.com/kk_hirono/status/1167272045387767808 https://twitter.com/s_hirono/status/1167265372292038656
&twitter(1167272045387767808){theme:light}
> 2019-08-30-112031_Google　マップ.jpg https://t.co/t4sGOFTH0G
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-30 12:05／2019-08-30 11:38 URL： https://twitter.com/kk_hirono/status/1167272063163224064 https://twitter.com/s_hirono/status/1167265298971410432
&twitter(1167272063163224064){theme:light}
> 2019-08-30-111926_二口町　-　Google　マップ.jpg https://t.co/LKk1XPYFDA
◁◁◁
<hr />

　金沢市場輸送の事務所があった建物自体は変わっていないと思いましたが、いつの間にか駐車場の向かい側に別の建物が出来ていて、それもずっと前からある風景に溶け込んだ建物に見えたので驚きました。

　「2019-08-30-112104_Googleストリートビュー＿金沢市場輸送の事務所があった場所＿01.jpg」のスクリーンショットに見えるのが金沢市場輸送の事務所の正面玄関ですが、運転手がここから出入りすることはほとんどありませんでした。

　「2019-08-30-112454_Googleストリートビュー＿金沢市場輸送の事務所があった場所＿06.jpg」のスクリーンショットに見えるのが、運転手の控室のドアで、運転手はここから出入りをしていました。このドアから初めて被告発人松平日出男の姿を見たとも記憶にあります。

　運転手の控室と事務所の間にも奥の方に、同じ様な大きさの出入り口のドアがありましたが、たいていはアルミサッシの窓越しで話をしたり、運行費の受け渡しなど物のやり取りをしていました。外壁にアルミサッシが建物の中にもある感じではなかったかと思います。

　「2019-08-30-112133_Googleストリートビュー＿金沢市場輸送の事務所があった場所＿02.jpg」のスクリーンショットで建物を見ると、前にも何度か同じGoogleストリートビューで見ていましたが、それ以上に複雑なかたちの建物だったのだと思いました。

　事務所の奥の方に社長室があり、滅多に中に入ることはなかったのですが、忍者屋敷の隠し部屋のような趣もありました。この外からの外観をみると、社長室の奥にも立ち入ったことのない部屋があったのかもしれないという気がしました。

　なお、上記のスクリーンショットの一番手前の建物の部分ですが、横に出入り口のドアがあって、物置のようになっていました。そこにドラム缶のオイルが置いてあって、運転手が各自でオイル交換をするようになったのですが、物置に入るのはその時だけだったと思います。

　以前はマルモ設備に行ってオイル交換をしていました。これも前に書いていると思います。オイル交換は１万キロに１回で、たしか２回に１回はオイルエレメントの交換もしていたように思います。マルモ設備にはほとんど行くことがなくなったとも思います。

　たいていのトラックの修理はメーカーの工場に行っていました。イスズであれば、野々市町の近くで金沢市横川ではなかったかと思います。Googleマップでだいたいの場所の確認をしましたが、イスズの工場は見当たりませんでした。国道１５７号線沿いかと思います。

　日野のトラックであれば、金沢市森本町で河北郡津幡町の近くに工場がありましたが、平成９年辺りには国道８号線沿いの別の場所に新しく大きな工場が出来ていました。

　マルモ設備については、平成３年９月の中頃にパンチパーマの人が、私と被害者安藤文さんがフィルム貼りをしているのを見て驚いたのですが、金沢市場輸送の事務所でもマルモ設備の人の姿をみることはほとんどなくなっていたので、偶然であれば、すごい偶然だったと思います。

　今考えると、被告発人松平日出男が意図的に事務所に呼びつけて私に印象づけたという可能性は大いにあると思います。マルモ設備にオイル交換に行っていた頃というのは、妻子を同乗させていたことが多く、マルモ設備の人もよく知っていたはずかと思います。

　オイル交換以外でもマルモ設備に行くことはありました。ただどの程度の修理や整備だったのかは記憶になく、電気系のトラブルは、金沢市場輸送の事務所から近かった金沢電装に行くことになっていました。

　昭和５９年当時は、割とよく金沢電装に行くことがありましたが、その後は電気系統の故障も少なかったためか余り行くことがなかったと思います。ただ、１つよく憶えているのは、カセットテープの音楽機器の故障のときで、長男が小銭を詰め込んでいたらしく、店の人も驚いていました。

　ちょっと思い出したのですが、平成３年１２月の終わり頃だった気がしますが、自分の軽四アルトワークスの修理か何かで金沢電装に行ったことがあったように思います。詳しいことは思い出せません。

[link:] » 吉本ビル - Google マップ https://t.co/oL7aGpE8xs

<hr />

　周辺の道路自体は昭和５９年当時と変わっていないように思います。上記の吉本ビルとなっている建物ですが、そのもう少し右手の辺りに金沢電装があったように思います。小さな個人商店のような店でした。修理も外の駐車スペースでやっていましたが、雨が降ったらどうしていたのかと思います。

　大型トラックでも運転席の部分は中に入れることが出来る工場はあったかもしれません。従業員がいるようにも見えない小さな店でしたが、名前は金沢電装となかなか大きな会社をイメージさせるものになっているかと思います。店主のこともなんとなく記憶にあります。

　吉本ビルの向かい側にセイロモータースという小さな中古車店のような会社が見えますが、平成４年１月頃、その辺りには新しい焼肉店がありました。一度だけ入ったことがあったのですが、１月１８日の夜で、被告発人多田敏明と二人でした。

＜＜＜2019-08-30（金曜日）12：56＿［これまでの記述範囲の終了時刻］＜＜＜



