#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "参考資料／弁護士業界の現状／山口貴士弁護士／「接見した弁護士に責任があると騒いでいた皆様、こんにちは。」という富田林警察署逃走事件に対するツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-13 19:25:35 +0900
FILE_NAME: 2018-12-13-192535_「接見した弁護士に責任があると騒いでいた皆様、こんにちは。」という富田林警察署逃走事件に対するツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  山口貴士弁護士 深澤諭史弁護士のリツイート 刑裁サイ太のリツイート 富田林警察署逃走事件 接見 刑事弁護
記事タイトル名の文字数：73　保存ファイル名の文字数：73
URL: http://hirono-hideki.hatenablog.com/entry/2018/12/13/195459

#contents

* 刑裁サイ太のツイートの村松謙弁護士のリツイートとしての記録

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-13 20:03／2018-12-13 18:40 URL： https://twitter.com/kk_hirono/status/1073171533957259264 https://twitter.com/s_hirono/status/1073150696055140352
&twitter(1073171533957259264){theme:light}
> 2018-12-13-145549_村松謙のリツイート（サイ太　@uwaaaa）：報道はもはやエンタメとして消費されてるからね，キン肉マンや北斗の拳のストーリーに論理的なツッ.jpg https://t.co/IoRvayKhoU
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-13 20:03／2018-12-13 18:40 URL： https://twitter.com/kk_hirono/status/1073171550587637761 https://twitter.com/s_hirono/status/1073150727764070400
&twitter(1073171550587637761){theme:light}
> 2018-12-13-145835_サイ太（@uwaaaa）：富田林署の件で，接見した弁護士に責任があると叩いてた人は，詳細も知らずに叩いてたことに対する反省もないまま，この.jpg https://t.co/VHG8AtUo1Z
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-13 20:03／2018-12-13 18:40 URL： https://twitter.com/kk_hirono/status/1073171615628709888 https://twitter.com/s_hirono/status/1073150759233937410
&twitter(1073171615628709888){theme:light}
> 2018-12-13-145912_サイ太（@uwaaaa）：富田林署の件で，接見した弁護士に責任があると叩いてた人は，詳細も知らずに叩いてたことに対する反省もないまま，この.jpg https://t.co/4scWFBzL65
◁◁◁
<hr />

[link:] 2018年12月13日20時06分の登録： ＃村松 謙　@kmuramatsu＃のツイート／2018-12-10_1748〜2018-12-13_1857／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月13日20時06分 http://hirono2014sk.blogspot.com/2018/12/kmuramatsu2018-12-1017482018-12.html

```
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
指定アカウントの最新199件のツイート
2018-12-10 17：48から199件：最新2018-12-13 18：57という範囲（3日1時間9分）の取得
===========================================================

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＃村松 謙　@kmuramatsu＃のツイート／2018-12-10_1748〜2018-12-13_1857／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月13日20時06分 http://hirono2014sk.blogspot.com/2018/12/kmuramatsu2018-12-1017482018-12.html
```

14件目 ￼戻る （リツイート）： kmuramatsu（村松 謙）｜uwaaaa（サイ太） 日時：2018-12-13 14:47／2018-12-13 14:05 URL： https://twitter.com/kmuramatsu/status/1073091976088641536 https://twitter.com/uwaaaa/status/1073081533697642496
{% tweet 1073091976088641536 %}
> 報道はもはやエンタメとして消費されてるからね，キン肉マンや北斗の拳のストーリーに論理的なツッコミを入れないのと同様，自分の発言の一貫性なんて気にしないんだ https://t.co/fRVIBHDCJS 

22件目 ￼戻る （リツイート）： kmuramatsu（村松 謙）｜luckymangan（リーチ一発ツモ裏１） 日時：2018-12-13 13:01／2018-12-13 12:31 URL： https://twitter.com/kmuramatsu/status/1073065279955988481 https://twitter.com/luckymangan/status/1073057798009741313
{% tweet 1073065279955988481 %}
> この件は弁護士の責任とか言ってた人ら、今、息してる？ https://t.co/UnCDMDxEj7 

▶ ツイート％luckymangan（リーチ一発ツモ裏１）％2018/12/13 12:31％ https://twitter.com/luckymangan/status/1073057798009741313
&twitter(1073057798009741313){theme:light}
> この件は弁護士の責任とか言ってた人ら、今、息してる？ https://t.co/UnCDMDxEj7  
▶

28件目 ￼戻る （リツイート）： kmuramatsu（村松 謙）｜okumuraosaka（強制わいせつ/準強姦/買春/児童ポルノ/児童福祉法/青少年条例弁護人弁護士奥村徹(大阪弁護士会)） 日時：2018-12-13 11:03／2018-12-13 10:58 URL： https://twitter.com/kmuramatsu/status/1073035639937880064 https://twitter.com/okumuraosaka/status/1073034325459759104
{% tweet 1073035639937880064 %}
> こういう実態を調べずして懲役5年の刑を決めたんだよね。実害はどう説明すればいいんでしょうか・・・　　　　　児童買春被害者 70％余が非行歴なし 警察庁が初の実態調査 | NHKニュース https://t.co/kykVceHDPu 

[link:] » 宇佐津彦(うさつひこ)とは - コトバンク https://t.co/3JYP0JM5zl

<hr />

[link:] » 宇佐津彦命　桃太郎 - Google 検索 https://t.co/9bKrcy7Jmz

<hr />

[link:] » 所さん!大変ですよ - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/oGMIlylipA \n 所さん！大変ですよ「昔話“桃太郎”をめぐる大論争！？」 \n 2018年12月13日（木）  20時15分～20時43分  の放送内容

<hr />

[link:] » 所さん!大変ですよ - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/oGMIlylipA \n 昔話「桃太郎」をめぐる珍騒動。いま全国で9の地域が「うちこそ桃太郎発祥の地」と主張している。なかには桃太郎の… https://t.co/W33GwqsjgO

<hr />

　時刻は２０時５３分です。だいぶん前から鶏肉でシチューを作っています。もう食べごろとなっています。あると思った山口貴士弁護士のツイートの村松謙弁護士のリツイートはなかったのですが、他に見落としのあったと思われる発見があったので上記の記録に追加しました。

　作業中にテレビで、宇佐津彦命が出てきたのですが、ちょうど外では雷が鳴り出しました。初めて見る神様のお名前と思いましたが、宇出津に似ているので気になりました。宇佐は大分県の地名で八幡宮の総神宮である宇佐八幡宮ではなかったかと思います。

　総神宮ではなく総本宮だったかもしれません。仏教の総本山に相当すると２，３年前に調べて知りました。

```
宇佐神宮は全国に4万社あまりある八幡様の総本宮です。
八幡大神（応神天皇）・比売大神・神功皇后をご祭神にお祀りし、
神亀2年に創建されました。

皇室も伊勢の神宮につぐ第二の宗廟(そうびょう)として御崇敬になり、
一般の人々にも鎮守の神として古来より広く親しまれてきました。

由緒はこちら>>

［source：］八幡総本宮 宇佐神宮 http://www.usajinguu.com/
```

　ネットで調べてもはっきりした情報がすぐには出てこなかったのですが、宇佐津彦命は桃太郎と関係があるようです。シチューを作りながら何度も台所に行ったり、パソコンの操作をやっていたので、番組の内容はほとんどわかりませんでした。

　しかし、久しぶりに思い出しのは、弁護士ら、法クラとも自称したりするようですが、一時期、「法テラス太郎」というワードを頻繁に目にしていたことです。

　シチューを作ったのは久しぶりになります。カレーも同じですが、鶏肉を使うと肉が固くなって美味しくないと感じていたので、事前に調べたところ、焦げ目がつくぐらいよく焼いた方がよいという情報がありました。実行したところ、それで美味しく出来た気がします。

　肉というのは焼きすぎると固くなるという固定観念があったのですが、鶏肉の場合は違うのかもしれません。余り美味しく作れないので、作らなかったというのもあると思います。鶏肉は、どんたく宇出津店で特売で買ってきたものです。

　鶏肉の消費期限が今日でした。昼にシチューを作るつもりだったのですが、午前中にマグロの幼魚であるシビコをもらったので、冷凍庫に長く残っていた大根と煮付けにしました。少し刺し身にして食べたのですが、うまく捌けずかなり滅茶苦茶になりました。

　シビコを捌いたのは初めてでしたが、皮をむくのが難しかったです。皮が柔らかすぎて難しいという感じでした。事前に調べてからやった方が良かったとも思います。シビコで検索しても料理の情報は見つからず、メジマグロでやってみました。サイズの違いがわかりません。

　時刻は２１時２７分です。テレビのNHKのNEWS９ですが、「温暖化の影響にどう向き合うか」というような特集をやっており、海藻が珊瑚に変わったら、その漁場は終わりだという話がありました。五島列島です。長崎県だったと思います。堤防で魚が余り釣れなくなったのも・・・。

　温暖化による環境問題と考えられますが、私としては弁護士脳による社会環境問題も大きいかと思います。と書いたところで、今日は、木曜日の弁護士ドラマの最終回だったことを思い出しました。

　録画機器の予約確認をするとNEWS９が優先されていました。リモコンで録画の停止をすると、画面も「リーガルV」に切り替わり、すぐに録画が始まったようです。すっかり忘れていました。

　時刻は１２月１４日６時３９分です。

* 刑裁サイ太のツイートの足立啓太弁護士のリツイートとしての記録
  :LOGBOOK:
  CLOCK: [2018-12-14 金 09:25]--[2018-12-14 金 12:00] =>  2:35
  :END:

***＞＞2018-12-14（金曜日）09：25＿［これからの記述範囲の開始時刻］＞＞***

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-14 09:26／2018-12-14 08:13 URL： https://twitter.com/kk_hirono/status/1073373693210877952 https://twitter.com/s_hirono/status/1073355284972797952
&twitter(1073373693210877952){theme:light}
> 2018-12-14-081317_弁護士あだちけいたボヘミアン・ラプソディ4回観戦（@keita_adachi）：明日14日の午後から尋問スタート。.jpg https://t.co/MNEFb7DOuy
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-14 09:26／2018-12-14 08:08 URL： https://twitter.com/kk_hirono/status/1073373722575233025 https://twitter.com/s_hirono/status/1073353883026509824
&twitter(1073373722575233025){theme:light}
> 2018-12-14-080240_弁護士あだちけいたボヘミアン・ラプソディ4回観戦のリツイート（サイ太　@uwaaaa）：富田林署の件で，接見した弁護士に責任があると叩いて.jpg https://t.co/1TB6GNNCKK
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-14 09:26／2018-12-14 08:07 URL： https://twitter.com/kk_hirono/status/1073373745702592513 https://twitter.com/s_hirono/status/1073353851917414400
&twitter(1073373745702592513){theme:light}
> 2018-12-14-080222_弁護士あだちけいたボヘミアン・ラプソディ4回観戦のリツイート（リーチ一発ツモ裏１　@luckymangan）：この件は弁護士の責任とか言っ.jpg https://t.co/Fgkaz0ze2q
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-14 09:27／2018-12-14 08:07 URL： https://twitter.com/kk_hirono/status/1073373775800918016 https://twitter.com/s_hirono/status/1073353820619460608
&twitter(1073373775800918016){theme:light}
> 2018-12-14-080127_弁護士あだちけいたボヘミアン・ラプソディ4回観戦のリツイート（ピピピーッ　@O59K2dPQH59QEJx）：脱走事件で警察から「弁護士が.jpg https://t.co/Mdf6D2XIsj
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-14 09:27／2018-12-14 08:07 URL： https://twitter.com/kk_hirono/status/1073373809472765952 https://twitter.com/s_hirono/status/1073353788889546752
&twitter(1073373809472765952){theme:light}
> 2018-12-14-080026_弁護士あだちけいたボヘミアン・ラプソディ4回観戦のリツイート（岡ロ基ー　@okaguchikii）：今年の漢字は「災」手続保障の不存在＆あ.jpg https://t.co/YQ4TPuxaBi
◁◁◁
<hr />

2018年12月14日08時04分の登録： ＼弁護士あだちけいた ボヘミアン・ラプソディ4回観戦　@keita_adachi　RT：　@uwaaaa＼富田林署の件で，接見した弁護士に責任があると叩いてた人は，詳細も http://hirono2014sk.blogspot.com/2018/12/4keitaadachirtuwaaaa.html

2018年12月14日08時04分の登録： ＃弁護士あだちけいた ボヘミアン・ラプソディ4回観戦　@keita_adachi＃のツイート／2018-12-11_0944〜2018-12-14_0758／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月14日08時04分 http://hirono2014sk.blogspot.com/2018/12/4keitaadachi2018-12-1109442018-12.html

▷ リツイート→keita_adachi（弁護士あだちけいた ボヘミアン・ラプソディ4回観戦）＞uwaaaa（サイ太）｜2018/12/13 16:10／2018/12/13 13:59｜https://twitter.com/keita_adachi/status/1073112929480826880 ／ https://twitter.com/uwaaaa/status/1073079999156998144
&twitter(1073112929480826880){theme:light}
> RT @uwaaaa: 富田林署の件で，接見した弁護士に責任があると叩いてた人は，詳細も知らずに叩いてたことに対する反省もないまま，この警察官を叩いてると思いますよ。  

* 足立啓太弁護士（旭川弁護士会）について：２０１８年１２月１４日の記録

```
略歴

弁護士　足立敬太
（アダチ　ケイタ）

旭川弁護士会所属

愛知県春日井市出身
 

1997年　 早稲田大学政治経済学部政治学科卒業
2003年　 愛知県弁護士会（当時名古屋弁護士会）登録
2006年　 留萌ひまわり基金法律事務所 （過疎地型公設事務所）所長
2010年　 富良野・凛と 法律事務所開所

現在
【日本弁護士連合会】　
法律相談センター・ＬＣ委員会・幹事
釧路管内ひまわり基金法律事務所支援委員会・委員
ほか各種委員会・委員

【北海道弁護士会連合会】
道弁連理事会・理事
旭川管内すずらん基金法律事務所運営委員会・委員
ほか各種委員会・委員

【旭川弁護士会】
常議委員会・議員
業務改革委員会・委員長
ほか各種委員会・委員に就任

ＮＰＯ法人ふらの演劇工房・理事
一般社団法人函館馬主協会・会員
富良野商工会議所・議員
 

得意案件	企業法務（労使関係・契約・医療介護・農業）・消費者問題・離婚
実績情報	
著書・論文	「Q&A先物被害110番」(名古屋先物・証券問題研究会編)
講演・セミナー	2009年11月 北大ロースクール「司法制度論」
2010年11月 旭川商工会議所「問題社員対策」
メディア掲載履歴	2009年5月 北海道新聞特集記事「弁護士過疎問題」
趣味	家電量販店巡り・一口馬主
好きな言葉	Stay Hungry, Stay Foolish.(ハングリーであれ、愚か者であれ。)
好きな食べ物	ラーメン・焼肉・鮨・ナポリピザ

［source：］弁護士紹介 – 旭川‐富良野‐あい弁護士法人 富良野・凛と 法律事務所 https://www.furano-rinto.com/lawyer
```

　上記に法律事務所のホームページにある足立啓太弁護士のプロフィールを引用しました。このホームページは前にも見たことがありましたが、今回、目を通したところ意外な発見もいくつかありました。

　平成９年に早稲田大学政治経済学部を卒業し、平成１５年に愛知県弁護士会（当時名古屋弁護士会）に登録。平成１８年に留萌市の過疎地型公設事務所の所長となり、平成２２年に現在のものと思われる富良野・凛と 法律事務所を開所とのことです。

　このホームページをみるちょっと前ですが、Twitterのプロフィールに旭川とあったので、おやっと思っていました。北海道の富良野市で弁護士活動を行っていることはわかっていましたが、富良野市というのは北海道でも札幌に近いところというイメージがあったからです。

　一方で、今から半月ほど前になるでしょうか、旭川弁護士会について調べ、ホームページなどをみていたところ、管轄地域のようなものがずいぶん広いとしりました。うろ覚えになりますが、北海道は４つの地域にわけられていたように思います。旭川が一番、上というか北になるのでしょう。

　なぜそのとき旭川弁護士会について調べたかというと、あるTwitterの実名弁護士が副会長であることを確認するためでした。ところが調べてみると、弁護士会の会長になっていたので驚きました。自分が勘違いしていたのかとそのときは思いました。

　ちょっと弁護士の名前がすぐには浮かんできません。最近知ったことですが、金沢弁護士会をみていると弁護士会の会長というのは一年交代のようです。それも４月から始まるようです。副会長については、複数人いる可能性もツイートから感じているのですが、確認はしていません。

　あちこちの弁護士会のホームページをみているわけではないですが、これまでのところ、決まって「会長の挨拶」というようなページがあるようです。一方で、副会長については情報を見たことがないので、確認するのも珍しいのかもしれません。

　雅樹という名前だったのは思い出したのですが、井上だったようにも思い出してきました。私が、北海道で注目する、注目してきた弁護士の一人です。他に岩田圭只弁護士、中村元弥弁護士、中村憲昭弁護士がいて、Twitterはほとんど見ませんが札幌の猪野亨弁護士もいます。

　いずれも発言内容に特色がありますが、北海道の弁護士に注目したのは他にも理由があります。１０年ほど前たまたま読んだ記事に、日本で最も権利意識で積極的なのが北海道の弁護士、その逆が地縁が強く保守的な沖縄の弁護士という話がありました。

　もともと北海道というのは移民が多く開拓精神で有名です。日本の中央から離れ、周辺も北の方はロシアのシベリアやアラスカという未開の部分が大きい地域というのも、他の影響を受けにくいとともに独立心が強くなる傾向が考えられます。

　他に北海道には警察の裏金という社会問題がありました。最近は見ていないことに気がついたのですが、中村憲昭弁護士のTwitterには、その北海道警の不正や、ロシア人の再審無罪事件に関するツイートをいろいろと見てきました。警察の負と映る部分についても参考になりました。

　足立啓太弁護士のTwitterアカウントには、ずいぶん前からブロックされています。特にメンションを送ったという記憶はなく、返信を受けることは、まずなかったと思うのですが、当たり前のようにブロックされておりますし、それが長く続いています。

　岩田圭只弁護士にも一時期、ブロックされていたように思いますが、その後、解除されていたかと思います。ブロックされていた期間も長くはなかったと思うのですが、私の方からメンションを送ったことはあったと思います。返信はなかったと思います。

　他に今回の新たな発見となったのは、旭川弁護士会の常議委員会・議員ということです。「業務改革委員会・委員長」ともあります。先ほどは気が付かなかったのですが、委員長となっています。

　弁護士会の常議員については、深澤諭史弁護士のツイートで初めて知り、そのあとも情報を見てきました。深澤諭史弁護士の場合は、第二東京弁護士会です。うろ覚えですが、日弁連（日本弁護士連合会）でも委員をしているかのようなツイートを見ていたような気もします。

　深澤諭史弁護士については、一月ほど前になるように思うのですが、独立したかに思えるツイートがあって、それで調べたりもしたのですが、現在も前と同じ渋谷の法律事務所にいるようです。

　時刻は１１時２４分です。洗濯などのタイミングでしたが、東名高速のあおり運転夫婦死亡事故で判決が出たようです。求刑は２３年でしたが、同じか２２年、２１年かと予想していましたが、懲役１８年だったようです。汲むべき事情があったのでしょう。

　そういえば、北海道も危険運転での大きな死亡事故がいくつかありました。もともと北海道は死亡事故が日本で一番多いとも言われていましたが、最近は聞きません。

　北海道の弁護士のツイートを見ていると、車での移動が大変だという話がありました。不思議と話題になっているのをみませんが、高等裁判所の控訴審となると、被告人の身柄も管轄の拘置所に移されるはずなので、接見なども大変そうですが、そもそも接見に行くことはないのかもしれません。

　時刻は１１時３５分です。テレビのニュースで、富山県砺波市鹿島で火災があり４人が行方不明とのことです。今年の春は登山の遭難事故のニュースが例年になく多いと思っていたのですが、先月の１１月辺りから全国的にも石川県内でも火事のニュースが多いと感じています。

　そういえば、昨日の石川県内ニュースで観光地化している近江町の火災の防犯パトロールを放送していましたが、火災の原因として最も多いのが放火だと話していました。放火についても書いておきたいことがありました。片町の新天地というところのお話で、平成３年１２月２１日の夜のこともです。

　旭川弁護士会についても、旭川刑務所の事件問題と一緒に書いておきたいことがありました。

　時刻は１１時４６分です。テレビでは、兵庫県宝塚市の中国自動車道で、京都府長岡京市の４５歳の医師があおり運転をし、警察官を羽交い締めにして現行犯逮捕されたということです。医師の粗暴犯というのは最近他にも見たように思いますが、以前はあり得なかった気がします。

　テレビで金沢地方裁判所の法廷が出ていましたが、裁判官に向かって右手の席に男性が一人座っていて、そちらから左手の席にカメラが移動した時、空席でしたが、一方弁護側はというようなアナウンスがありました。よく見ていなかったですが、横領事件のような裁判官が１つの刑事裁判でした。

　テレビはバイキングが始まりました、このあと中継という坂上忍さんの声がありましたが、バイキングで中継というのはかなり珍しいように思います。ずっと前には見たような気もするのですが、ここ１年ほどは全く見ていないと思います。スタジオばかりです。

***＜＜2018-12-14（金曜日）12：00＿［これまでの記述範囲の終了時刻］＜＜***


