#+TITLE: "「たぶん、多くの法クラアカウントもそうでしょう」というモトケンこと矢部善朗弁護士、辿ると海渡雄一弁護士のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-14 05:14:37 +0900
FILE_NAME: 2019-08-14-051437_「たぶん、多くの法クラアカウントもそうでしょう」というモトケンこと矢部善朗弁護士、辿ると海渡雄一弁護士のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: モトケンこと矢部善朗弁護士（京都弁護士会）  海渡雄一弁護士 表現の自由
記事タイトル名の文字数：56　保存ファイル名の文字数：78

* 「たぶん、多くの法クラアカウントもそうでしょう」というモトケンこと矢部善朗弁護士、辿ると海渡雄一弁護士のツイート
  :LOGBOOK:
  CLOCK: [2019-08-14 水 05:16]--[2019-08-14 水 06:25] =>  1:09
  :END:

＞＞＞2019-08-14（水曜日）05：16＿［これからの記述範囲の開始時刻］＞＞＞

　テレビと電気をつけたまま横になって寝ていて目がさめたのが３時４０分過ぎぐらいでした。二度寝しようと思ったのですが眠れませんでした。昨日の１３日に起きたときから腰の調子が悪く時折痛みが走り、普通に体も動かせなくなっています。２年ほど前にも似たことがありました。

　テレビをつけるとチャンネルが北陸朝日放送だったので、報道ステーションをみていたところで、ニュースzeroのテレビ金沢に変更する前のタイミングだったようです。高校野球の結果をみていたことはなんとなく憶えています。急に眠くなりました。

　ほとんど連日、夜中も朝方も一日中暑いので、なかなか熟睡も出来ていないのだと思います。お盆をすぎれば朝夕は肌寒さを感じることも多くなっていくので、もう少しの辛坊かと思います。なかなか集中もできません。クーラーはなく扇風機だけです。

　その扇風機もリモコンがどこに行ったのかわからないので、タイマーを使うことができません。扇風機の風が当たったまま寝ていることもあったのですが、それが体調不良の原因とも考えることがあります。または、寝返りで腰をひねったことも考えられます。

　昨日の夕方の遅い時間だったと思いますが、モトケンこと矢部善朗弁護士（京都弁護士会）の気になるツイートを見かけていました。引用されたツイートを辿ると、海渡雄一弁護士のツイートが大本にありました。

▶ ツイート％motoken_tw（モトケン）％2019/08/13 19:20％ https://twitter.com/motoken_tw/status/1161221060487835648
&twitter(1161221060487835648){theme:light}
> @3wM6bi391seMwoW 私の理解ではそうです。たぶん、多くの法クラアカウントもそうでしょう。
> ただし、思いっきり批判されて非難されてバカにされて軽蔑される表現ですけどね。  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜3wM6bi391seMwoW（ジョン卍郎） 日時：2019-08-14 05:35／2019-08-13 19:16 URL： https://twitter.com/kk_hirono/status/1161375633525489664 https://twitter.com/3wM6bi391seMwoW/status/1161219981679321088
&twitter(1161375633525489664){theme:light}
> @motoken_tw これも表現の自由だっていうんですかね。
◁◁◁
<hr />

▶ ツイート％motoken_tw（モトケン）％2019/08/12 18:55％ https://twitter.com/motoken_tw/status/1160852381828993024
&twitter(1160852381828993024){theme:light}
> この人、フォロワー二桁で大した影響力はないと思うけど、こういうデマツイートの積み重ねがいわゆるリベラル側の信用性や信頼性を削っていくんだと思う。
> リベラル側に限った話じゃないけどね。 https://t.co/Nf5agrAkUK  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜donkeygrape（Donkey） 日時：2019-08-14 05:36／2019-08-12 11:57 URL： https://twitter.com/kk_hirono/status/1161375996194373633 https://twitter.com/donkeygrape/status/1160746988771504128
&twitter(1161375996194373633){theme:light}
> @kidkaido 事故が起きたとき　緊急着陸を要請したが　横田基地は拒否した＜基地は民間人を守らない＞　諦めて飛び続けた機影を忘れられない
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 05:36／2019-08-12 11:33 URL： https://twitter.com/kk_hirono/status/1161376035918639104 https://twitter.com/kidkaido/status/1160741008214151168
&twitter(1161376035918639104){theme:light}
> 御巣鷹、遺族ら慰霊の登山 日航機墜落事故から３４年 https://t.co/LyiQvDmIa7 \n  御巣鷹山は、多くの事故で家族を喪った人たちが、事故を繰り返さぬよう祈るための聖地となった。
◁◁◁
<hr />

　モトケンこと矢部善朗弁護士（京都弁護士会）らしい挑発的な批判もありますが、その批判の的としたツイートは、海渡雄一弁護士のツイートへの返信だったことになります。

　この海渡雄一弁護士は日本を代表するような弁護士で大御所感があります。最近他のことで調べ直したのですが、経歴や役職などをみているとその感を強くしました。ただ知名度となるとどうかと思います。妻の福島瑞穂弁護士も最近はテレビで見ることも少なくなっています。

　社民党ではなかったかと思いますが、この前の参院選でも議席の確保で存続が危ういとか、崖っぷちという話がテレビに出ていました。選挙後も話題は見かけていないので、結果がどうなったのかもよくわかっていません。ほとんど話題になっていたかったことは確かかと思います。

　海渡雄一弁護士といえば、原発問題で活躍しているというイメージも強いですが、それもネット上のことで、テレビでは姿を見たこともないかもしれません。それがかえって存在感や影響力について考えさせられるところでもあります。

　本人がメディアを避けているのか、メディアが関わりを避けているのかは不明ということになります。昨夜のNEWS９だったと思いますが、いきなり松本清張の日本の黒い霧から始まって、松山事件で死刑判決から無罪になった９５歳の男性をインタビューしていました。

　自白の強要や司法取引という最先端の刑事司法との問題にからめていました。そのうちやるのかとも期待はしているのですが、大崎事件の最高裁決定を大きく取り上げないのが気になっています。決定が出る前は特集で取り上げていたように思います。

　海渡雄一弁護士のTwitterタイムラインをみていると、伊藤詩織さんのマイクを握る写真が出てきたので、リツイートされたツイートをリツイートします。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜FayOkinawa（Fay） 日時：2019-08-14 05:58／2019-08-08 22:00 URL： https://twitter.com/kk_hirono/status/1161381509896404992 https://twitter.com/FayOkinawa/status/1159449337404907520
&twitter(1161381509896404992){theme:light}
> 新宿ピカデリーで行われた映画『新聞記者』トークイベント。スペシャルゲストに伊藤詩織さんが来てた！短時間でしたが、事件のこと、映画のこと、今作成中のドキュメンタリーのことを語ってくれた。事件前に戻ることはできないけど、前向きに、意欲… https://t.co/9gTmFSvGY6
◁◁◁
<hr />

　プロフィールの記載がなくフォロワーも７１というアカウントですが、リツイートの数が９１４，いいねが２２９４とけっこうな数です。なお、メインで取り上げた御巣鷹山慰霊の海渡雄一弁護士のツイートはリツイートが３２，いいねが４２と表示されています。

　そういえば海渡雄一弁護士も、批判されているのは見たことがないように思いました。見た感じ温厚な人柄ということもあるのかもしれないですが、目立つ存在ではないのかもしれません。いろいろと幅広く積極的な活動はされている感じなのですが。

　ついでのようなかたちになりますが、他にも海渡雄一弁護士の最近のツイートで気になったものをリツイートしておきたいと思います。憲法に触れたものもあります。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:06／2019-08-10 09:13 URL： https://twitter.com/kk_hirono/status/1161383643035496449 https://twitter.com/kidkaido/status/1159981182013935617
&twitter(1161383643035496449){theme:light}
> 不自由展「再開を」　「警備面クリアなら」と岩手知事 | 2019/8/9 - 共同通信 https://t.co/NyK3FoJK1I
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:07／2019-08-09 09:04 URL： https://twitter.com/kk_hirono/status/1161383759221911552 https://twitter.com/kidkaido/status/1159616355613626368
&twitter(1161383759221911552){theme:light}
> 〈レベル７スクープ〉福島県、東電に津波対応催促していた | 週刊金曜日オンライン https://t.co/kgdJQQFWBc
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:07／2019-08-09 08:19 URL： https://twitter.com/kk_hirono/status/1161383774011006976 https://twitter.com/kidkaido/status/1159605183694790657
&twitter(1161383774011006976){theme:light}
> 飯舘村のADR申立団は解散しましたが、村には若者と子ども達は戻らず、コミュニティは壊れたままです。これから、何をすべきか、模索は続いています。 https://t.co/DDUA6inlbs
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:07／2019-08-08 23:13 URL： https://twitter.com/kk_hirono/status/1161383828243406848 https://twitter.com/kidkaido/status/1159467689720463360
&twitter(1161383828243406848){theme:light}
> ２０１９．８．８ \n  今こそ、韓国徴用工当事者と日韓政府、関係企業による \n  和解のテーブル作りを \n  ―徴用工事件韓国大法院判決と日韓外交関係― \n   \n  　　　　　　　　　　　　　　　　　海渡雄一（弁護士） \n   \n  はじめに... https://t.co/pQ9DUK5IJJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:07／2019-08-08 09:07 URL： https://twitter.com/kk_hirono/status/1161383843896578048 https://twitter.com/kidkaido/status/1159254725759385600
&twitter(1161383843896578048){theme:light}
> 「表現の不自由展・その後」とはそもそもどんな展覧会だったのか - 毎日新聞 https://t.co/ToHDOH8eSf
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:07／2019-08-07 10:13 URL： https://twitter.com/kk_hirono/status/1161383858941464577 https://twitter.com/kidkaido/status/1158909000395571201
&twitter(1161383858941464577){theme:light}
> 日本でも一刻も早く死刑が廃止できるように、市民の声を高めていきたいと思います。 https://t.co/z1tMKtTdyW
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:07／2019-08-05 19:35 URL： https://twitter.com/kk_hirono/status/1161383878562439169 https://twitter.com/kidkaido/status/1158325675817758720
&twitter(1161383878562439169){theme:light}
> 展示中止　大村知事が河村氏批判 https://t.co/HKUMlKmzlL #表現の不自由展・その後 \n   \n  憲法２１条で禁止された検閲ととられても仕方がない。 \n  行政や公的セクターこそ、表現の自由を守らなければならないのではないか。… https://t.co/dZr9efPA1j
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:07／2019-08-05 08:33 URL： https://twitter.com/kk_hirono/status/1161383908849532928 https://twitter.com/kidkaido/status/1158159152021028865
&twitter(1161383908849532928){theme:light}
> 「少女像」展示再開求めデモ集会に200人「表現の自由の弾圧だ」名古屋 https://t.co/ImHjxsyMZ4
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:08／2019-08-04 23:49 URL： https://twitter.com/kk_hirono/status/1161384012729876480 https://twitter.com/kidkaido/status/1158027228044677121
&twitter(1161384012729876480){theme:light}
> https://t.co/yEx2hTInVA \n  映画「日本と原発」のスタッフが、新しい短編映画「東電刑事裁判　動かぬ証拠と原発事故」を作成しました。 \n  監督は河合弁護士、私は構成監修を担当。 \n  ３７回に及んだ公判を２６分にぎゅっと圧縮… https://t.co/DMvX7Wofa4
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:08／2019-08-04 22:38 URL： https://twitter.com/kk_hirono/status/1161384068128182272 https://twitter.com/kidkaido/status/1158009374402465797
&twitter(1161384068128182272){theme:light}
> 展示中止でマスコミ労組が声明 「表現の自由失われる」 https://t.co/EyadSMhfGg \n  行政の中止措置は暴力による脅迫を追認したことになる。 \n  表現の自由を尊重するということは、異なる意見の存在に寛容になるということ。… https://t.co/1vlNdDf79K
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:08／2019-08-04 21:40 URL： https://twitter.com/kk_hirono/status/1161384100852142080 https://twitter.com/kidkaido/status/1157994751913689089
&twitter(1161384100852142080){theme:light}
> 日本は、憲法裁判の経過について歴史的な検証もできない国になっていたのか。 \n  最高裁は、実情を包括的に調べて、きちんと公表して欲しい。 https://t.co/EGAP5UPHKq
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ISOKO_MOCHIZUKI（望月衣塑子） 日時：2019-08-14 06:08／2019-08-03 11:59 URL： https://twitter.com/kk_hirono/status/1161384161879314432 https://twitter.com/ISOKO_MOCHIZUKI/status/1157486138405220352
&twitter(1161384161879314432){theme:light}
> #あいちトリエンナーレ の #表現の不自由展 をめぐり、#菅義偉 #官房長官 は「事実関係精査し、補助金を交付するか慎重に検討」と発言。 \n   \n   #表現の自由 への侵害が懸念されている中で、公権力が補助金を使って公然と展示に圧力をかけ… https://t.co/GA22ZXiYZc
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:09／2019-08-04 16:33 URL： https://twitter.com/kk_hirono/status/1161384204048818176 https://twitter.com/kidkaido/status/1157917459170545664
&twitter(1161384204048818176){theme:light}
> 表現の自由は、あらゆる自由の中で、一番尊重しなければならないものです。表現の自由が失われた社会では、民主主義は実現できなくなります。 \n  抗議の声明を支持します。 https://t.co/XZm7k6zDiV
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:09／2019-07-31 08:26 URL： https://twitter.com/kk_hirono/status/1161384335246671872 https://twitter.com/kidkaido/status/1156345473243836417
&twitter(1161384335246671872){theme:light}
> ユニセフが重大懸念 日本の子供貧困は安倍政権で加速する https://t.co/TAydTxGR6f #日刊ゲンダイDIGITAL \n   \n  ユニセフのレーク事務局長 \n  「日本のおよそ１６％の子供が深刻な貧困状態にある。豊かな社会において子供が飢えや格差に苦しむことがあってはならない」
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:09／2019-07-29 23:35 URL： https://twitter.com/kk_hirono/status/1161384375801376768 https://twitter.com/kidkaido/status/1155849256638398464
&twitter(1161384375801376768){theme:light}
> 【特別寄稿】スクープ！ 官邸への忖度か!?  参院選静岡選挙区に関する報道をめぐって、『報ステ』から消えた『6分』のVTR！ 官邸は国民民主候補への支援と引き換えに改憲賛成を要求か!? https://t.co/wfFn87OyCn @iwakamiyasumiさんから
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:09／2019-07-29 23:06 URL： https://twitter.com/kk_hirono/status/1161384417413087232 https://twitter.com/kidkaido/status/1155842038459355137
&twitter(1161384417413087232){theme:light}
> 【特別寄稿】スクープ！ 官邸への忖度か!? 参院選静岡選挙区に関する報道をめぐって、『報ステ』から消えた『6分』のVTR！ 官邸は国民民主候補への支援と引き換えに改憲賛成を要求か! https://t.co/GTs4k8qwy0
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:10／2019-07-26 18:27 URL： https://twitter.com/kk_hirono/status/1161384462527033344 https://twitter.com/kidkaido/status/1154684707251949568
&twitter(1161384462527033344){theme:light}
> どんどん自由度が下がってきています。 \n  安倍首相は、民主党政権の時代を悪く言いますが、民主党の時代より、今の方が、ずっと悪くなっているのですね。 \n  私は、もし原発事故が起きたときが安倍政権だったら、メルトダウンも汚染水もすべてが秘密に… https://t.co/bFEktEyWAS
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:10／2019-07-25 23:52 URL： https://twitter.com/kk_hirono/status/1161384496165478401 https://twitter.com/kidkaido/status/1154404049782890496
&twitter(1161384496165478401){theme:light}
> 福島県、東電に津波対応催促していた - level7 https://t.co/uNCkIWeyqK
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mizuhofukushima（福島みずほ） 日時：2019-08-14 06:10／2019-07-25 19:20 URL： https://twitter.com/kk_hirono/status/1161384524766253056 https://twitter.com/mizuhofukushima/status/1154335561236140033
&twitter(1161384524766253056){theme:light}
> 新潟選挙区で当選して打越さくらさんが挨拶に来てくれました。党を超えて選択的夫婦別姓の実現など様々なことで力を合わせます。本当に良かった。嬉しいです。 https://t.co/IqBa1vLCQj
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜mizuhofukushima（福島みずほ） 日時：2019-08-14 06:10／2019-07-24 01:36 URL： https://twitter.com/kk_hirono/status/1161384665925558272 https://twitter.com/mizuhofukushima/status/1153705347858591745
&twitter(1161384665925558272){theme:light}
> れいわ新選組から船後靖彦さんと木村英子さんが当選した。国会のバリアフリー化と委員会などを含めた合理的配慮が必要となる。障害者に対する合理的配慮については厚生労働委員会などで議論をしてきた。全力でバックアップしていきたい。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:11／2019-07-22 15:35 URL： https://twitter.com/kk_hirono/status/1161384745076326400 https://twitter.com/kidkaido/status/1153191722488254466
&twitter(1161384745076326400){theme:light}
> 参議院選挙が終わりました。... https://t.co/SGRoSbFmJi
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜utsunomiyakenji（宇都宮けんじ） 日時：2019-08-14 06:11／2019-07-18 12:36 URL： https://twitter.com/kk_hirono/status/1161384824474501120 https://twitter.com/utsunomiyakenji/status/1151697250797514752
&twitter(1161384824474501120){theme:light}
> 7月17日(水)は午後10時からウツケンTVでおしどりマコさん(立憲民主党参議院全国比例区候補)と対談しました。マコさんは、自分で考え行動することは面倒だけど誰か任せにせず私たちの社会は私たちみんなで作っていきたいのです！そのため… https://t.co/9IQHEAPIQx
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kikko_no_blog（きっこ） 日時：2019-08-14 06:11／2019-07-19 15:09 URL： https://twitter.com/kk_hirono/status/1161384887636484096 https://twitter.com/kikko_no_blog/status/1152098028800466945
&twitter(1161384887636484096){theme:light}
> 「安倍やめろ」と言って強制排除された男性のことばかり取り沙汰されているが、さらに問題なのは「増税反対」と言っただけで強制排除された女性だ。この国の国民は「これ以上、庶民の生活を壊さないでほしい」という歎願の声すら許されないのか？これが安倍晋三の目指す「美しい国」だと言うのか？
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜aokiaoki1111（青木美希） 日時：2019-08-14 06:12／2019-07-20 06:07 URL： https://twitter.com/kk_hirono/status/1161384960709632000 https://twitter.com/aokiaoki1111/status/1152324178382430208
&twitter(1161384960709632000){theme:light}
> 参院選で安倍首相の演説中にヤジを飛ばした男性らが警察官に排除された問題で、弁護士の団体らが抗議を申し入れました。「警察権力が民主主義社会の根幹を支える政治的言論の自由を不当に侵すことは絶対にあってはならない」（渡辺達生弁護士） \n  -… https://t.co/WYQeQ81gM2
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜suginamizuho_o（福島みずほ杉並応援団） 日時：2019-08-14 06:12／2019-07-19 22:31 URL： https://twitter.com/kk_hirono/status/1161385011041337344 https://twitter.com/suginamizuho_o/status/1152209318730555397
&twitter(1161385011041337344){theme:light}
> 💙2019年7月20日の予定です💙 https://t.co/ZA7Te7ut9y
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ISOKO_MOCHIZUKI（望月衣塑子） 日時：2019-08-14 06:12／2019-07-19 12:11 URL： https://twitter.com/kk_hirono/status/1161385048685158400 https://twitter.com/ISOKO_MOCHIZUKI/status/1152053295436853248
&twitter(1161385048685158400){theme:light}
> 本当におかしい。この程度のヤジを必死に防ごうとする警官たち。道警に続き、大津でも \n   \n  JR大津京駅前で18日、参院選の応援演説する #安倍首相 にヤジ飛ばす男性を警官らが会場後方で囲み動けなくさせていた。15日JR札幌駅前でもヤジ飛… https://t.co/xok32jA9A0
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MichikoKameishi（弁護士 亀石倫子） 日時：2019-08-14 06:12／2019-07-19 15:26 URL： https://twitter.com/kk_hirono/status/1161385087310557184 https://twitter.com/MichikoKameishi/status/1152102277391347714
&twitter(1161385087310557184){theme:light}
> 車離れ、結婚離れ。全部、若者の責任ですか？年収100とか200万で車を買えますか？子どもを育てられますか？ \n   \n  賃金が低いこと、雇用が安定しないことが問題なんです。まずは消費増税を止め、賃金を上げる。 \n   \n  暮らしの成長抜きに、大阪の成… https://t.co/fN33Cf1enT
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:13／2019-07-19 07:11 URL： https://twitter.com/kk_hirono/status/1161385276855296000 https://twitter.com/kidkaido/status/1151977829229187072
&twitter(1161385276855296000){theme:light}
> 本当に不器用だけど、この社会に必要な党だとおもいます。 \n  私も応援します。 https://t.co/JYTTWkWYbo
◁◁◁
<hr />

　参院選が終わりましたというわかりやすい海渡雄一弁護士のツイートがあって、もう少し時系列をさかのぼったかと思います。森友学園の捜査終結に関連したツイートは見当たらなかったと思います。テレビのニュースになっていた福島原発の汚染水問題も見当たりませんでした。

　最近、この海渡雄一弁護士に注目したんは大崎事件の最高裁決定でした。Facebookに長文の投稿があったのですが、いろいろと細かい数値のデータなどもあって、いろいろ参考になることもありました。７月１８日まで遡りましたが、大崎事件は見当たりません。

　大崎事件の最高裁決定は６月２５日で、弁護団に知らされニュースになったのは翌日の６月２６日だったと思います。６月２５日という日付をよく憶えているのは、岡口基一裁判官に対する大きな手続きが予定されていた期日だったからです。秋以降に延期されたとか。

　海渡雄一弁護士の大崎事件に対するコメントは記録資料とする必要性を感じていました。面倒に思ったのも長引いた要因ではあります。憲法問題の第一人者ではないかとも思うので、あらためて記録の作業に取り掛かりたいと思います。

＜＜＜2019-08-14（水曜日）06：25＿［これまでの記述範囲の終了時刻］＜＜＜

