#+TITLE: "「弁護士に相談しなかったのかな？報道情報によればあまりそういうことは期待できない感じだけど」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-18 14:35:00 +0900
FILE_NAME: 2019-08-18-143500_「弁護士に相談しなかったのかな？報道情報によればあまりそういうことは期待できない感じだけど」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: モトケンこと矢部善朗弁護士（京都弁護士会） 
記事タイトル名の文字数：75　保存ファイル名の文字数：97

* 「弁護士に相談しなかったのかな？報道情報によればあまりそういうことは期待できない感じだけど」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート
  :LOGBOOK:
  CLOCK: [2019-08-18 日 14:35]--[2019-08-18 日 16:54] =>  2:19
  :END:

＞＞＞2019-08-18（日曜日）14：35＿［これからの記述範囲の開始時刻］＞＞＞

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
ブロックされているのでリツイートできませんでした。→　https://twitter.com/motoken_tw
▶ ブロックされたツイート％motoken_tw（モトケン）％2019/08/18 12:09％ https://twitter.com/motoken_tw/status/1162924431422840833
&twitter(1162924431422840833){theme:light}
> この容疑者、自分が追われてることを知った後で弁護士に相談しなかったのかな？報道情報によればあまりそういうことは期待できない感じだけど。＞あおり運転、傷害容疑で手配の43歳男を逮捕　大阪市内で茨城県警 - 毎日新聞 https://t.co/PNX3zC4eQ5  
▶

　これもモトケンこと矢部善朗弁護士（京都弁護士会）らしいツイートですが、この「期待」が何を意味にするか考えさせられました。このモトケンこと矢部善朗弁護士（京都弁護士会）らしさには、この場合、被疑者にとっての利益を思い描く職人芸のようです。

　ちょうどテレビで和裁の職人の技術をみているところです。京都といえば祇園祭で刺繍のような縫い物を目にすることがあります。昭和５６年頃、石川県立水産高校では乗船実習でシンガポールに行くことが多く、その土産の定番に、刺繍の絨毯があって、文化的に共通するものを感じてきました。

　モトケンこと矢部善朗弁護士（京都弁護士会）は京都育ちであるらしく、徳川が豊臣家を滅ぼす口実にしたとされる寺院で小さい頃に遊んでいたようなツイートを見かけたことがありました。この際なので、少し調べてみたいと思います。

[link:] » 徳川 豊臣 京都 寺院 - Google 検索 https://t.co/Sy3plu8pfS

<hr />
[link:] » あの「国家安康」の鐘が - 方広寺の口コミ - トリップアドバイザー https://t.co/T9O4ra6kyt

<hr />
[link:] » 鐘銘事件(しょうめいじけん)とは - コトバンク https://t.co/kpxzDlIHvz

<hr />

　方広寺というのは記憶になく、豊という文字があったように記憶していました。

[link:] » モトケン(@motoken_tw)/「方広寺」の検索結果 - Twilog https://t.co/XAVa30y34q

<hr />

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
ブロックされているのでリツイートできませんでした。→　https://twitter.com/motoken_tw
▶ ブロックされたツイート％motoken_tw（モトケン）％2017/07/29 18:40％ https://twitter.com/motoken_tw/status/891231982633443330
&twitter(891231982633443330){theme:light}
> 今日は、豊国神社方面に散歩に行ってきました。子供の頃に遊んだ場所です。豊国神社の隣りにあるのが方広寺。そして方広寺と言えばこれですね。国家安康の鐘。
> #写真 https://t.co/5vvsYBW0Yh  
▶

世界!ニッポン行きたい人応援団 \n 2019年8月18日（日）  14時00分～15時00分  の放送内容 https://t.co/cik8K0JKl2 \n 日本の夏“ゆかた"を愛する…アルゼンチン人ご招待美しい染め物に感動!和裁職人の神ワザ連発

<hr />

　神社に梵鐘というのは聞いたことがないですが、モトケンこと矢部善朗弁護士（京都弁護士会）の２０１７年７月２９日のツイートには、豊国神社の隣の方広寺とありました。そういえば、今年の５月に行った氣多大社も隣接してけっこう大きなお寺がありました。

　この氣多大社についても書いておきたいことがあるのですが、最も期待した過去の記憶の喚起というのは、残念ながらほとんどありませんでした。昭和５５年に石川県立水産高校小木分校のバス遠足で行っているはずなのです。写真が残るのは近くの千里浜海岸だけでした。

[link:] » モトケン(@motoken_tw)/「八坂」の検索結果 - Twilog https://t.co/quEJiknVMQ \n ツイートが見つかりませんでした

<hr />

　120,104（30.7件/日）とTwilogにあるモトケンこと矢部善朗弁護士（京都弁護士会）のアカウントですが、八坂神社の検索結果は０で、八坂としても同じでした。割と近いところに四季の風法律事務所をやっていることは、Googleマップで距離を計測したこともあって確認済みです。

[link:] » モトケン(@motoken_tw)/「祇園」の検索結果 - Twilog https://t.co/KnWTyfi7EM

<hr />

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
ブロックされているのでリツイートできませんでした。→　https://twitter.com/motoken_tw
▶ ブロックされたツイート％motoken_tw（モトケン）％2012/04/16 14:23％ https://twitter.com/motoken_tw/status/191758659603267585
&twitter(191758659603267585){theme:light}
> 職務上の問題が何かあったのかな？＜祇園車暴走＞交通部長が当日飲酒…懇親会に出席　京都府警（毎日新聞） - Y!ニュース http://t.co/3rDK9G2K  
▶

　当時は、京都の八坂神社や祇園についてそれほど関心も持っていなかったためか、おやっと思ったのですが、てんかん持ちの呉服店の社員が、電柱に激突して死亡した事故と思われます。当時は珍しかったと思いますが、暴走し激突するまでの映像が繰り返し報道されていました。

　京都の中心部の事故というのはよく憶えていましたが、祇園というのは記憶にありませんでした。呉服というか着物の商いで、私の京都の親戚と同じ様な商売だったのでよく憶えています。女社長のような人がいて、事故後倒産したという話をネットで少し見かけたような記憶もあります。

　人に厳しいことの多いモトケンこと矢部善朗弁護士（京都弁護士会）のツイートで、それも京都府警本部長と交通部長が飲酒していたというニュースを、報道する側に非があるように指摘するモトケンこと矢部善朗弁護士（京都弁護士会）のツイートかと思います。報道に対しては厳しい感じです。

```
京都祇園軽ワゴン車暴走事故（きょうとぎおん けいワゴンしゃぼうそうじこ）とは、2012年4月12日に京都府京都市東山区祇園で、軽ワゴン車(ホンダ・バモス ホビオ［1］)を運転していた運転手の男性が、運転中に暴走事故を起こし、運転者を含む8名が死亡、12人が重軽傷を負った交通事故。事故原因は最終的に運転手の持病のてんかん発作とされた［2］。

［source：］京都祇園軽ワゴン車暴走事故 - Wikipedia https://ja.wikipedia.org/wiki/%E4%BA%AC%E9%83%BD%E7%A5%87%E5%9C%92%E8%BB%BD%E3%83%AF%E3%82%B4%E3%83%B3%E8%BB%8A%E6%9A%B4%E8%B5%B0%E4%BA%8B%E6%95%85
```

　８名が死亡した大事故だったとは、忘れていたためかいまさら驚きました。当時はこのようなニュースを身近に捉え、深く考える心のゆとりもなかったのかもしれません。

　まだ、ネットで書いたことがないかもしれないですが、このてんかんという病気についても忘れることのない思い出がありました。平成１１年の６月ぐらいかと思います。永久開発の日雇い人夫の仕事でしたが、仕事にも慣れ、数人のリーダー役のように現場に向かうことも多くなっていました。

　いや、まだその少し前の４月ころで、金沢市山科の現場に通っていた頃だったかもしれません。溶接が上手な職人で小松市から来ている人を一緒に現場に連れて行っている頃であったように思います。

　現場に向かうのに大勢が歩いていたとき、急に辺りが騒がしくなり、みると若者が地面に倒れ、全身で痙攣を起こしていました。世話役のような人が駆け寄って、タオルだと言い出し、何事か理解できなかったのですが、口にタオルを押し込んで舌を噛み切らないようにしていました。

　そのあとで、タオルを使った理由の説明とともに、てんかんという病気のことを初めて知ったのです。その日が、二日目か三日目の仕事で、てんかん持ちであることがわかっていれば、誰も採用しなかった。現場で発作を起こしていれば大変なことになっていたとも話していました。

```
なおこの事故の3日前に鹿沼市クレーン車暴走事故の遺族が危険運転致死傷罪の改正の署名を法務省に提出しており、その矢先に発生した事故であった。

［source：］京都祇園軽ワゴン車暴走事故 - Wikipedia https://ja.wikipedia.org/wiki/%E4%BA%AC%E9%83%BD%E7%A5%87%E5%9C%92%E8%BB%BD%E3%83%AF%E3%82%B4%E3%83%B3%E8%BB%8A%E6%9A%B4%E8%B5%B0%E4%BA%8B%E6%95%85
```

　上記も意外な情報でした。このクレーン車の事故のことも印象的に憶えています。平成１０年の何月ごろかまでは憶えていないですが、辰口庁舎の現場で、城西運輸の大型クレーンが倒れたことがありました。怪我人はいないと聞きましたが、物音にも気が付かなかったと記憶にあります。

　城西運輸は現在もほぼ独占的に石川県の建設現場のクレーンの作業をしていると思います。他にも建設関係と思われるトラック輸送も行っていて、あちこちでよくトラックを見かけていました。

　羽咋市から荷物を積んで山形県天童市だったと思いますが、そういう仕事がありました。平成３年１２月で、１０日前後か中頃だったと思います。はっきり思い出せないですが、津幡町の辺りかに城西運輸の営業所のようなものがあって、そこで安全靴を借りました。

　借りた安全靴は返すことがなかったのですが、それというのも被告発人松平日出男が返さなくっていいと言ったからで、ずいぶんと親しげな関係に感じられました。これはネットに記述があるように思います。寒河江市からリンゴを積んで帰った時の状況などと一緒に。

　羽咋市から荷物を積んだのは平鍛造であったように思います。平家一門のようでもありながら変わった名前の会社だと思っていました。

　その平鍛造だったと思いますが、イワシの運搬の連中がダンプの運転手も含め、一斉に荷物を運んでことがありました。大型車ばかりですが１０台以上はいたように思います。その荷物の行き先というのが、小松市のコマニーという会社であったように思います。

　ずいぶん前のことになるので記憶が薄れ、あるいは混同している部分もあるかもしれません。小松のコマニーには他にも長距離の仕事で行った覚えがあるのですが、事務所の内装に使われる間仕切りの会社だと聞いていました。

　間仕切りについては余りピンときていなかったのですが、市場急配センターの二階事務所では、小さい台所とトイレの横に、階段を登った出入り口からL型のようなかたちで、その間仕切りが設置され、なるほどこれが間仕切りなのかと深く納得したことを憶えています。

　その羽咋市から小松市への仕事は、とにかく大掛かりで大人数でした。確証は持てないのですが、すでに堂野さんの姿もあったように思います。昨日の１７日になるかと思いますが、起きた時に見ていた夢のこともあって、堂野さんについて取り上げるつもりでいました。

　その準備として市場急配センターのホームページなどのスクリーンショットも多数作成して用意をしていました。近いうちに使うようにしたいと思います。

[link:] » 会社概要 | 会社案内 | 平鍛造(R) / 羽咋丸善株式会社 - Taira Forging https://t.co/LcfEatOJAg

<hr />
[link:] » コマニー株式会社 – 「パーティション（間仕切り）」で快適空間・機能空間を創造するメーカー・コマニー株式会社 https://t.co/mLUVwZpAqK

<hr />

　コマニーは、小松空港より片山津インターに近い辺りにあったと記憶します。本社は石川県小松市と確認しました。第一から第四まである工場もすべて住所が小松市となっています。

　片山津インターの住所までは確認していないですが、小松市に近い加賀市になると思います。片山津温泉は知名度もあるように思います。妻の実家がその片山津温泉の近くでした。

　中西運輸商の仕事では、軽油グループのカードが使えるガソリンスタンドが昭和６０年当時、金沢市内にはなく、片山津インター側にありました。中西運輸商では他に吉田石油というカードも使っていましたが、利用した記憶があるのは中国自動車道の作用インターぐらいです。

　ほとんどが軽油グループのカードを使うガソリンスタンドで、同じ中国自動車道の北房インター（岡山県）、それと山口インターもよく使いました。泊まりや入浴によく使った佐賀県鳥栖市のガソリンスタンドは、吉田石油だったかもしれません。軽油グループもあったかもしれません。

　中西運輸商は佐川急便の九州・広島便をやっていたので、九州が多く次いで広島、岡山の仕事も多かったと思います。瀬戸内の国道２号線沿いで、広島県から岡山県に入ったところに笠岡市がありました。その笠岡市でスタイロフォームというものを積んだことがありました。畳の中身だと聞きました。

　畳の中に入る発泡スチロールのようなものだと聞きましたが、その時の荷物の行き先が、栃木県鹿沼市だったように思うのです。少なくとも同じスタイロフォームという荷物を鹿沼市のビルのような倉庫で、積み下ろしのどちらかをしたことは間違いありません。

　栃木県鹿沼市へ行った運行では、当時は入籍前だった妻を同乗させていたように思います。妻を同乗させて行ったことで、よりはっきり記憶にあるのは同じ栃木県の足利市で、国道５０号線から少し入ったトラックターミナルのような場所でした。

　九州から積んできた荷物でしたが、東西運輸の仕事と聞いていました。当時、中西運輸商で九州からの帰り荷としてよくある仕事でした。佐賀県の運送会社と聞いたようにも思います。その会社のトラックというのもよく見かけていました。

[link:] » 鹿沼市 - Google マップ https://t.co/8ZJpBMPuEP

<hr />

　長距離トラック運転手をしていた頃から地図というのはあまり見ませんでした。だいたいは道路標識でわかることで、現地に着いてから目的地の場所を探したりしました。なかにはどの経路を使った方がよいのか迷うこともありましたが、だいたいは決まっていたと思います。

　Googleマップで鹿沼市の場所を確認すると、宇都宮市に隣接しているように見えます。さらに山手の奥の方に、有名な日光東照宮のある日光市があるようです。日光市の方には行ったことはなかったと思いますが、国道４号線はそのまま福島県まで北上することがありました。

　気になったのは栃木市になったと聞く今市市のことでした。珍しく感じる地名だったので、現地の近くに行くと道路標識を見るだけでも気になったものでした。最近はまったく情報を見かけないだけに、余計に気になるのが今市小１女児殺人事件です。その後、事件名も栃木に変わっています。

　弁護士稼業の闇を感じさせる、神隠しのような謎深い事件でした。弁護士らの主張の通り、えん罪の可能性もあるかと思いますが、だとすれば、弁護士らが商売繁盛のために生贄を捧げた儀式の裁判のようにも思えます。

　下館か下妻か、調べて確認しないとわからなくなってきたのですが、神社前のミステリーゾーンのような場所には、江村正之検察官の弁護士としての法律事務所がありました。すぐ近くに裁判所も出てきて驚いたのですが、いずれもGoogleマップでの発見でした。

　この弁護士の得体のしれなさについて、手掛かりのような参考になると思い、取り上げたのが再掲になりますが、ブロックされた次のモトケンこと矢部善朗弁護士（京都弁護士会）の、ツイートになります。

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
ブロックされているのでリツイートできませんでした。→　https://twitter.com/motoken_tw
▶ ブロックされたツイート％motoken_tw（モトケン）％2019/08/18 12:09％ https://twitter.com/motoken_tw/status/1162924431422840833
&twitter(1162924431422840833){theme:light}
> この容疑者、自分が追われてることを知った後で弁護士に相談しなかったのかな？報道情報によればあまりそういうことは期待できない感じだけど。＞あおり運転、傷害容疑で手配の43歳男を逮捕　大阪市内で茨城県警 - 毎日新聞 https://t.co/PNX3zC4eQ5  
▶

　犯人であることが警察にしれているので、自首の成立もあり得ないはずですが、弁護士に相談すればいいことがあったような含みをもたせるモトケンこと矢部善朗弁護士（京都弁護士会）のツイートです。邪気というのが弁護士から発せられる現象として、近いのかもと考えました。

　報道によれば、茨城県守谷市の常磐自動車道での暴行が余にひどいので、薬物を使用中で薬が抜けるまで逃亡を続けるという見立てがありました。それと同じ見立てが当たったのは香川県愛川町の逃走事件でしたが、横須賀市での逮捕後、薬物反応が出ても、取り立てたニュースにはなっていない感じでした。

　弁護士費用に使うぐらいなら、被害者に賠償をした方が罪が軽くなりそうですが、そんな直接交渉を許さないのも弁護士泥棒神社たるゆえんのように思います。迸った泥棒根性が、見境なしに理屈をこね暴走をするように思えます。

＜＜＜2019-08-18（日曜日）16：54＿［これまでの記述範囲の終了時刻］＜＜＜

