#+TITLE: "「津田氏は「検閲」とか「表現の自由」というものをよく理解してない可能性がうかがわれる」と表現の不自由展に関するモトケンこと矢部善朗弁護士のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-18 09:33:08 +0900
FILE_NAME: 2019-08-18-093308_「津田氏は「検閲」とか「表現の自由」というものをよく理解してない可能性がうかがわれる」と表現の不自由展に関するモトケンこと矢部善朗弁護士のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: モトケンこと矢部善朗弁護士（京都弁護士会） 
記事タイトル名の文字数：73　保存ファイル名の文字数：95

* 「津田氏は「検閲」とか「表現の自由」というものをよく理解してない可能性がうかがわれる」と表現の不自由展に関するモトケンこと矢部善朗弁護士のツイート
  :LOGBOOK:
  CLOCK: [2019-08-18 日 09:34]--[2019-08-18 日 12:50] =>  3:16
  :END:

＞＞＞2019-08-18（日曜日）09：34＿［これからの記述範囲の開始時刻］＞＞＞

　この理解をしていないというモトケンこと矢部善朗弁護士（京都弁護士会）の文脈は、これまで何度か見かけてきたものですが、裏を返せば、自身は法律家として正しい理解をしている自信の現れに見えます。検察官から弁護士、大学で法律を教える立ちであったことは事実です。

[link:] 2019年08月18日09時14分の登録： ＼モトケン　@motoken_tw＼この記事を読むと、津田氏は「検閲」とか「表現の自由」というものをよく理解してない可能性がうかがわれる。そこを表現の不自由展の実行委員会 http://hirono2014sk.blogspot.com/2019/08/motokentw_18.html

　少し前に深澤諭史弁護士のタイムラインでリツイートですが、同じ問題を取り上げたツイートを見かけていました。プロフィールをみると弁護士ドットコムの関係者のようです。これまでに何度か見かけてきました。

motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.
ブロックされているのでリツイートできませんでした。→　https://twitter.com/motoken_tw
▶ ブロックされたツイート％motoken_tw（モトケン）％2019/08/17 12:31％ https://twitter.com/motoken_tw/status/1162567649840136192
&twitter(1162567649840136192){theme:light}
> この記事を読むと、津田氏は「検閲」とか「表現の自由」というものをよく理解してない可能性がうかがわれる。そこを表現の不自由展の実行委員会につけ込まれてごり押しまたは恫喝に屈したのではなかろうか？
> 検証委の経過検証が待たれる。 https://t.co/pj4E9j4HKr  
▶

　昨日８月１７日の午前中に作成したスクリプトでデータを貼り付けました。前日に深澤諭史弁護士にブロックされていることに気がついたのがきっかけでした。確認したところ８月１２日が最後にリツイートできた深澤諭史弁護士のツイートでした。次になります。

▷ リツイート→kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）＞fukazawas（深澤諭史）｜2019/08/12 22:13／2019/08/11 10:51｜https://twitter.com/kk_hirono/status/1160902105139298304 ／ https://twitter.com/fukazawas/status/1160368151013416962
&twitter(1160902105139298304){theme:light}
> RT @fukazawas: （・∀・）「他人の人権を侵害する表現の自由は認められない」は、実は現行法上間違いです。もちろん、無制限ではないですが。
> （＾ω＾）奇しくも今書いている書籍、他人の人権を侵害する表現の自由も広範囲に認められている、ということの裁判例や実務の解説なんだ…  

　これは次のTwilogの検索でみつけたものです。ツイートの内容を読み直すと、これも表現の不自由展に言及したもののようです。

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「kazawas」の検索結果 - Twilog https://t.co/fQJvHHGkxr

<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-18 09:56／2019-08-18 09:55 URL： https://twitter.com/kk_hirono/status/1162890897605849088 https://twitter.com/s_hirono/status/1162890747856617472
&twitter(1162890897605849088){theme:light}
> 2019-08-18-092829_モトケン@motoken_tw·20hこの記事を読むと、津田氏は「検閲」とか「表現の自由」というものをよく理解してない可能性がうかがわれる。そこを表現の不.jpg https://t.co/lTozs9AmqO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-18 09:56／2019-08-18 09:55 URL： https://twitter.com/kk_hirono/status/1162890913342820352 https://twitter.com/s_hirono/status/1162890675374813184
&twitter(1162890913342820352){theme:light}
> 2019-08-18-092753_深澤諭史さんがリツイート園田昌也@ライター@chew_bacca1987·9h不自由展中止　津田氏の懸念を実行委が拒絶　リスク承知で展示か.jpg https://t.co/NKXfLueSIF
◁◁◁
<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜chew_bacca1987（園田昌也@ライター） 日時：2019-08-18 09:58／2019-08-18 00:09 URL： https://twitter.com/kk_hirono/status/1162891490814676993 https://twitter.com/chew_bacca1987/status/1162743349385674760
&twitter(1162891490814676993){theme:light}
> 不自由展中止　津田氏の懸念を実行委が拒絶　リスク承知で展示か https://t.co/aj6XkhP1Lo \n   \n  表現の自由って何だったんだ、というより表現の自由ってこういうものよね、という感じがする。言語化できないけど。
◁◁◁
<hr />

　リンクの記事の内容ですが、まだ開いてもいないのでもちろん読んでいません。津田氏が強硬な実行委に押し切られたと読めますが、これは意外なところであると同時に、実行委という存在について関心を持ちました。これは愛知県や名古屋市という行政とも関わりがあったとされているからです。

　時刻は１０時０５分です。テレビのサンジャボでは「佐野SAストライキ騒動　運営会社社長ｖｓ従業員」という見出しでやっていますが、２，３日前からの報道かと思いますが、社長の名前が出てきたと思ったら、顔出しでインタビューを受けています。

　これも実行委とストライキ側という一方の強い動き構図が似ているように思いました。

　昨日の午前中であったとも思うのですが、東北自動車道に佐野SAというのはあたっけ？と考えたところで、佐野インターがあったことを思い出しました。仙台市内から古河市の青果市場に向かうのに佐野インターを降りたように思い出したのですが、家族を同乗させた最後の運行とも考えました。

　平成３年の春頃であったとも思ったのですが、だとすると１月１７日に新車で乗務した大型ウィング車での運行になるのですが、鮮魚関係以外の仕事で仙台に行ったのも珍しいと思いました。行き荷はアルミサッシだったと思いますが、仙台市から古河市だと移動も大きくなります。

　時刻は１０時１６分ですが、テレビのサンジャボでは佐野SAが続いています。と書いているタイミングで「全国指名手配　恐怖　”煽り運転”」に話題が移りました。それでも１５分ほど番組冒頭から続いたので、佐野SAの騒動はマスコミの関心も相当高いようです。

　煽り運転のニュースもこれで４，５日ぐらいでしょうか。大きく報道されています。これも暴行現場として茨城県守谷市の常磐自動車道が繰り返しテレビに出てきたのですが、茨城県で守谷市というのはピンと来ず、愛知県のイメージが強かったので昨夜調べると、そちらは刈谷市でした。

　２日ほど前に全国指名手配になったかと思います。ちょうど夜中に目が覚めたタイミングで深夜３時ころに顔写真のニュースをみました。そのあとも住所職業不詳とされていますが、ネットの情報では不動産会社の社長で、テレビでもマンションを貸し出しているという情報が出ています。

　大きな不動産を所有し家賃収入を得ていたといえば、思い出すのはベトナム人女児の連れ去り殺害事件でした。当初は我孫子市の事件として報道されていましたが、その後、被疑者の住まいの市の名前で報道がされるようになったと記憶します。

```
　父親の陳述中、傍聴席からはすすり泣く声がやむことはなかった。検察の論告求刑は死刑。判決は7月6日に下される。

※女性セブン2018年7月5日号

［source：］松戸女児殺害呆然の初公判　被告が遺族に叫んだ「謝罪」｜NEWSポストセブン https://www.news-postseven.com/archives/20180621_703675.html/3
```

　飛ばしながらざっと記事に目を通しました。やはり遺体の発見現場が我孫子市の用水路でしたが、父親が橋のたもとのようなところに祠を建てていたのがとても印象的な事件でした。

```
「リンさんのご家族に言いたいことがあります！　私が犯人だと思われているなか、私が行った募金活動を受け取っていただいて、ありがとうございます。また事件後忙しく、墓前にお参りに行くことができず、すいませんでした。見守り活動をしていたのに、リンさんのこと、守ることができず、すいませんでした！　以上です！」

［source：］松戸女児殺害呆然の初公判　被告が遺族に叫んだ「謝罪」｜NEWSポストセブン https://www.news-postseven.com/archives/20180621_703675.html/2
```

　上記の引用部分も前に報道でみたように思いましたが、「私が行った募金活動を受け取っていただいて、ありがとうございます。」という部分は何を目的としたのか真意をはかりかねました。

　この事件の被告人は、仲の良い男の子供がいて一緒に魚釣りにも行っていたとのことです。徹底的に否認を貫いたのも、子供の将来のために誤認逮捕の余地を残しておきたかったのかと考えたことがありました。証拠が揃いすぎていたためか、えん罪を疑う報道はみなかったように思います。

[link:] » 我孫子市、千葉県 から 千葉県松戸市 - Google マップ https://t.co/yjCsSMaMMB

<hr />

　千葉県松戸市の場所をGoogleマップで確認すると、東京都葛飾区に隣接しているように見えたのが意外でした。我孫子市とは思っていたより離れていて１８キロほどあるようです。

　平成４年２月の終わりか３月の初めの我孫子警察署で通行許可証のことは、これまでに１回以上書いてきたと思いますが、隣接した茨城県取手市の日清食品のことも、被告訴人HTNのことで書いているかと思います。

　国道６号線で千葉県我孫子市から茨城県取手市に入ってすぐ、左手に日清食品の会社か工場がありました。田舎によくある高さのあるライスセンターの建物のようにも見えました。最近、白山市のことでそのような穀物貯蔵庫の役割の解説をみたのですが、旧松任市でよく見かけたとも思いました。

　私が初めに東京都内から宮城県石巻市に向かったときも、その国道６号線を通過したと記憶にあります。とにかく日清食品の建物が目立って印象的でした。

　私が初めて東京都内から宮城県石巻市に向かったのは金沢市場輸送の４ｔ車保冷車だったと思います。それも長距離トラック運転手を専属でやっていたときではなく、臨時の仕事だったのですが、石巻港では丸２日か丸３日という泊まりになって、時間を持て余しました。

　そのとき石巻では魚市場の奥の方、左手にあった中華料理店でチャーハンを食べたことが不思議と強く記憶に残っています。その道路はもう少しさきに行くと、石巻市街から女川町に通じる道路に三叉路のようなかたちでぶつかっていました。

　その三叉路から女川町方面に向かって、数百メートル行った右手に東北陸運の石巻支店か営業所がありました。本社は塩釜市でした。なんとなくですが営業所となっていたように思います。広い空き地のような駐車場で、会社の建物は平屋であったように記憶にあります。

　三叉路を逆に左折して石巻市街に向かうと、これも数百メートルだったと思いますが、左手に空き地がありました。この空き地が荷物を積み込む場所となっていました。東北陸運の小型車が集荷してきた荷物をそこで積み替えていたのです。

　ほとんどの場合、夜中にその空き地にトラックをとめて寝ていました。さらに石巻市街に向かって１００メートルほど歩くとコンビニがあって、そこでよく買い物をしたり、週刊誌の立ち読みもしていたように思います。隣接してコンビニがもう１件あったかもしれません。１つはローソンかも。

　石巻で時間を持て余していたとき、牡鹿半島まで４トン保冷車でドライブに行ったことがありました。夕方の暗くなった時間帯で雨が降っていたような気もします。景色のようなものはほとんどみえなかったのですが、これもやたらと強く印象にのこっています。

　４トン保冷車で石巻に行ったとき、私は妻を同乗させていたと記憶にあるのですが、日清食品の前を通ったことや牡鹿半島にドライブに行ったとき一緒だったという記憶はなく、二人でいて強く印象に残ったのは中華料理店でした。不思議とその後、その店に入ったことはなかったとも思います。

　石巻は青森から福島県と東北各地から移動で向かうことが多く、現地に到着するのは深夜が多かったということもあります。途中で食事を済ませてきたり、それでもコンビニでの買い物が多かったように思います。このコンビニの利用というのも石巻ならではの特徴でした。

　サンドイッチマンの帰れマンデーという番組だったと思いますが、その舞台が牡鹿半島ということがありました。以前同じバスの乗り継ぎ旅で、輪島のねぶた温泉を終着地としてみたのですが、このねぶた温泉は平成４年の傷害・準強姦被告事件の頃、母親が仲居の仕事をしていました。

　母親の供述調書に職業が仲居とあったので、同じねぶた温泉だと思うのですが、機織り工場の仕事がなくなってから最初に仲居の仕事をするようになった時は、曽々木海岸とも聞いていました。昨夜は、ござれ祭りと重なって行けなかったのですが、曽々木大祭がありました。

　母親に繰り返しすすめられ、一度だけ輪島のねぶた温泉に入浴に行ったことがありました。冬で雪が降っていたとも記憶にあります。たぶん、イワシの運搬の仕事で宇出津に来ているときのことでした。イワシの運搬は、珠洲市の飯田港になることがあったからです。

　時刻は１１時４５分です。テレビにアッコにおまかせ！が始まったところですが、サンドイッチマンの２人が出てきて紹介されていました。このサンドイッチマンの１人は、石巻市の出身か縁があったと思います。初めに知った頃は福島県の出身と思っていました。

```

メンバー	伊達みきお
富澤たけし
結成年	1998年
事務所	グレープカンパニー
活動時期	1998年 -
出身	 日本 宮城県泉市
（現・仙台市泉区）
影響	バカルディ
出会い	仙台商業高等学校
（現・仙台市立仙台商業高等学校）ラグビー部
旧コンビ名	親不孝、ゆやゆよん
現在の活動状況	テレビ・ラジオ・ライブツアー など
芸種	漫才・コント
ネタ作成者	富澤たけし
現在の代表番組	バイキング
帰れマンデー見っけ隊!!
明日へつなげよう 未来塾
イッテンモノ!
KEYABINGO!
サンドのぼんやり〜ぬTV
熱烈!ホットサンド!
サンドウィッチマンの天使のつくり笑い
サンドウィッチマンの週刊ラジオジャンプ
サンドウィッチマンの東北魂
東北魂TV
など

［source：］サンドウィッチマン (お笑いコンビ) - Wikipedia https://ja.wikipedia.org/wiki/%E3%82%B5%E3%83%B3%E3%83%89%E3%82%A6%E3%82%A3%E3%83%83%E3%83%81%E3%83%9E%E3%83%B3_(%E3%81%8A%E7%AC%91%E3%81%84%E3%82%B3%E3%83%B3%E3%83%93)
```

　少なくともどちらかが福島県出身と思っていたのですが、２人とも宮城県泉市が出身とあります。（現・仙台市泉区）というのは、静岡県の静岡市清水区と似ていますが、宮城県の泉市というのは記憶にないと最初に思いました。

　宮城県は古川市や大和インターが長距離トラック運転手の仕事で印象深かったのですが、１，２年ほど前になるかと思いますが、いつの間にか宮城県大崎市となっていることを知りました。

```
泉市（いずみし）は、1971年（昭和46年）から1988年（昭和63年）まで宮城県に存在した市。

現在は仙台市泉区となっている。

［source：］泉市 - Wikipedia https://ja.wikipedia.org/wiki/%E6%B3%89%E5%B8%82
```

　調べてみて少し納得ですが、昭和の時代に市町村合併というのは珍しく感じました。これは仙台市の政令指定都市にともなったものであったとも考えられます。一方で、昭和５９年から仙台市には行っていましたが、その当時から区になっていたようにも思います。

```
1989年（平成元年）4月1日 - 政令指定都市に指定され、現在の5区制となる。

［source：］仙台市 - Wikipedia https://ja.wikipedia.org/wiki/%E4%BB%99%E5%8F%B0%E5%B8%82#%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%9F%9F%E3%81%AE%E6%B2%BF%E9%9D%A9
```

　これも調べてみると、平成元年が政令指定都市となっていました。昨日は、石川星稜と智弁和歌山の延長戦をみながら、仙台育英のことを思い出し、記憶の確認もしておきたくて仙台育英について調べたのですが、記憶とは違う納得のしがたい結果がありました。

　仙台育英の大越投手というのも記憶にあったのですが、その延長戦を私は仙台市内のトラックステーションで観ていました。高校野球はもともと余り観ないのですが、たまたまみていてとても印象に残る試合でした。

　私の記憶では仙台育英の対戦相手は大阪代表の近大付で、準々決勝か準決勝だと思っていました。名場面とされているのは仙台育英と大阪代表の上宮、しかしこちらに延長戦の記録は見当たらず、延長戦で名場面となっていたのは、決勝戦での帝京高校との試合でした。

　それも平成元年の夏の甲子園となっていたのですが、その頃私は、北都運輸の市内配達の仕事を専属でやっていたはずで、長距離トラック運転手の仕事で仙台市に行っていたとは考えにくいのです。

　４トン保冷車で仙台のトラックステーションに入った記憶はなく、大型保冷車で長距離トラック運転手をしていないときに臨時の運行をした記憶もありません。金沢市場輸送は乗務する大型保冷車がしっかり決まっていて、空きもほとんどありませんでした。

　大型保冷車に乗務員の空きが出るようになったのは平成３年になってからのことで、車番は石７１８０だったかもしれません。私が新車で乗務した石７５９９よりいくらか前に納車され、最初に愛知県の河村さんが乗務していました。川村だったかもしれないですが、これはずっと前から曖昧です。

　その石７１８０で金沢市場輸送から臨時の仕事を頼まれるようになったというのが、被告発人安田繁克でした。少なくとも２月いっぱいはイワシの運搬の仕事をしていたはずなので、それ以降になります。ダンプだったので３月から、あるいは４月に入ってもイワシの運搬はしていたかもしれません。

　イワシの運搬の仕事はダンプが優先でした。水揚げは少ないが４月中もやっていると聞いていました。平ボディ車は２月いっぱいで終わっていたように思います。それがイワシの水揚げのあるシーズンで１，２月がピークでした。

　被告訴人安田繁克は私に、金沢市場輸送の仕事で岩手県宮古市に行ってきたと話していました。話を聞いたのは平成３年の７月頃だったと思います。市場急配センターの２階の事務所で話をしていました。事務所があるのは２階だけです。

　アッコにおまかせ！をみたのも少し久しぶりですが、出演者が全員で立ち話をするという特徴があります。井戸端会議のような雰囲気もあるのですが、たまに見ると少し不思議な様子に見えました。

　ほんの僅かでタイミングが合わず、次の吉本闇営業の話題に移ったのですが、その前に女優が運転手と結婚したという話題があって、それは３日ほど前からみて知っていたのですが、お相手の運転手の顔写真が出ていました。

[link:] » 運転手　結婚 - Google 検索 https://t.co/vUvmlkEDxc

<hr />
[link:] » ロケバス運転手との結婚を発表した新川優愛「忘れ物した」と話す口実作り - ライブドアニュース https://t.co/ZLZbyOx9s5

<hr />

　新川という名前は女優として少し記憶にあったのですが、改めて新川優愛というフルネームを見ると、見覚えがなかったような気がしました。顔はなんとなく見覚えがありますが、思い出せる役柄などもなく、出演の映画やドラマを調べてもいないのでわかりません。

```
８日に一般男性との結婚を発表したモデルで女優の新川優愛（２５）が１１日、都内で取材に応じ、お相手は９学年年上のロケバスのドライバー（３５）だと明かした。１０代からの顔見知りだったが３年前から恋心に変わり、自分からアタックして交際をスタート。結婚発表するまでは公園での散歩デート以外、一緒の外出を控えていたといい「指輪を買いに行ったり、テラス席でお茶を飲みたい」と晴れやかだった。入籍は近日中。すでに都内で同居している。

［source：］ロケバス運転手との結婚を発表した新川優愛「忘れ物した」と話す口実作り - ライブドアニュース https://news.livedoor.com/article/detail/16914052/
```

　見出しを読み直すと内容が気になりました。９学年年上というのも初めて見る表現ですが、女優が２５歳というのはテレビでみていたものの、お相手が３５歳というのはこの記事で初めて知ったと思います。

　津田氏に関する記事はすでに目を通していますが、今のところ時間を使う気にはなりません。法クラに動きがあれば、そのとき考えます。

　時刻は１２時４３分です。さきほどテレビのアッコにおまかせ！で、新潟県胎内市が出てきたのですが、これもタイミングが合わずにスマホでの撮影に失敗しました。胎内市で４０．７度と出ていました。

　８月１５日であったように思うのですが、石川県の志賀町でも４０度を超えて、石川県で初の観測とニュースになっていました。新潟県胎内市は続けて、中条とテレビに表示されていました。

　この新潟県胎内市も以前はなかった市町村名だったと思います。私はそこに近い道路上の住所地として中条と思っていたのですが、平成４年の２月に、被告発人多田敏明を連れて、そこの市場に仕事に行っています。愛媛県松山市から積んできたいよかんの２つの荷降ろし先の２箇所目でした。

＜＜＜2019-08-18（日曜日）12：50＿［これまでの記述範囲の終了時刻］＜＜＜

