#+TITLE    : "告発に至る経緯／書面作成／報道機関／村松謙弁護士のタイムラインでリツイートとして見た、鴨志田裕美弁護士の「検察の有罪立証、特別抗告審の最高裁も相手にしなかったのに。」というツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-04-27 17:07:35 +0900
FILE_NAME: 2019-04-27-170735_村松謙弁護士のタイムラインでリツイートとして見た、鴨志田裕美弁護士の「検察の有罪立証、特別抗告審の最高裁も相手にしなかったのに。」というツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  村松謙弁護士 鴨志田裕美弁護士 大崎事件 志布志事件
記事タイトル名の文字数：90　保存ファイル名の文字数：94

#contents

:LOGBOOK:
CLOCK:&nbsp;[2019-04-24&nbsp;水&nbsp;18:14]--[2019-04-24&nbsp;水&nbsp;22:53]
:END:


＞＞＞2019-04-24（水曜日）18：15＿［これからの記述範囲の開始時刻］＞＞＞

2019年04月24日09時33分の登録： ＼かもん弓（鴨志田 祐美）　@kamo629782＼検察の有罪立証、特別抗告審の最高裁も相手にしなかったのに。\n\n同じ司法に生きる者として，ここまで悪あがきして有罪を取ろ http://hirono2014sk.blogspot.com/2019/04/kamo629782.html

　上記がツイートのまとめ記事になります。記事の投稿時刻を確認すると９時３３分となっていて、登録時刻と同じですが、この登録時刻はデータベースへの登録時刻となっていたと思います。

　「2018-03-31 15:09から197件：最新2019-04-24 07:52という範囲（388日16時間43分）の取得」という記載が記事の冒頭付近にありますが、これもプログラムの処理による出力です。

　本来は１９９件の取得が多いはずですが、これは１９７件となっていて、一番少ないほうかと思います。処理はTwitterAPIを使っています。一度のリクエストで取得できるツイートの数が最大で２００件だと思いますが、１件も２００件もリミットのある処理回数は同じようです。

　TwitterAPIの仕様は常に変更の可能性のあるものですが、現時点では９００件までのクエリーが出来、１５分でリミットがリセットされるようです。

　１件のツイートのデータの取得も２００件のそれも処理はほぼ同じになるのですが、１件のツイートのみの記載だと前後の流れが伝わらず誤解を招きやすいという指摘を、モトケンこと矢部善朗弁護士（京都弁護士会）のツイートで見ていて、それを大いに参考にした対処でもあります。

　TwitterAPIでのタイムラインの取得は２００件がワンセットで、それを１６回のオフセットで取得でき、最大で３２００件となるはずなのですが、実際には３１００件前後の取得となっており、２００件というのも１９９件から１９７件というのが多くあります。

　実際、次のような処理を行っています。小倉秀夫弁護士のツイートを出来る範囲で取得しました。３１９７件のツイートが取得できていますが、これは希に多い方かと思います。自前のプログラムをオフセットを変えながら１６回呼び出し、処理結果をファイルに書き込んでいます。


[9981]  % TU=`xsel -b|sed 's/.*twitter\.com\/\([^ /]\+\).*/\1/'`; echo $TU; h-show-twitter-profile.rb $TU; for x in {1..16};do tw_user_timeline_1line.rb $TU 200 $x >> $TU; done &&  st=$(grep "^\(▶TW \|▶RT \).*" $TU |tail -1|sed "s/.*日時：\(....\)-\(..\)-\(..\) \(..\):\(..\)[ ／].*/\1\2\3\4\5/"); et=$(grep "^\(▶TW \|▶RT \).*" $TU |head -1|sed "s/.*日時：\(....\)-\(..\)-\(..\) \(..\):\(..\)[ ／].*/\1\2\3\4\5/"); mv $TU ${TU}_${st}-${et}.txt; echo  -e "\n取得件数： ";  grep "^\(▶TW \|▶RT \).*" ${TU}_${st}-${et}.txt| wc -l; echo "取得した最新ツイー ト："; sed -n '1p' ${TU}_${st}-${et}.txt; echo "取得した最古ツイート："; sed -n '$p' ${TU}_${st}-${et}.txt

Hideo_Ogura

＜2019年04月24日(水) 18時41分45秒にTwitterAPIで取得したHideo_Ogura（小倉秀夫）のプロフィール情報＞

11月17日に行われる法とコンピュータ学会の研究大会（ https://t.co/xf9blhJRJC ）のシンポジウムでモデレーター（司会）を務める予定です。



取得件数： 

3197

取得した最新ツイート：

▶TW Hideo_Ogura（小倉秀夫） 日時：2019-04-24 18:04 URL： https://twitter.com/Hideo_Ogura/status/1120976887688249345 TWEET： 知財、IT系だと、一般人基準で故意の有無を認定するといわれるとまずWinny事件を思い浮かべると思うんですよね。RT @kyoshimine: @ryouheitakaki クレディ・スイスのストックオプションの無罪判決やWinny最高裁などみると、  

取得した最古ツイート：

▶ ツイート％Hideo_Ogura（小倉秀夫）％2018/08/10 01:56％ https://twitter.com/Hideo_Ogura/status/1027599589677793280
&twitter(1027599589677793280){theme:light}
> エストニアにおける医師の男女比を観て単純に「女性差別がなければこれくらい女子の割合が高くなるはずだ」と考えてしまう人たちって脳天気だよね。  

Diginnos-PC:~

[9982]  % wc -l Hideo_Ogura_201808100156-201904241804.txt 

3197 Hideo_Ogura_201808100156-201904241804.txt

　テキストファイルとしてツイートの内容を保存していますが、「Hideo_Ogura_201808100156-201904241804.txt」というのが生成したテキストファイルのファイル名です。取得範囲での最古と最新のツイートの投稿時刻を記録として使っています。

　小倉秀夫弁護士はけっこう長い間、Twitterを中断していました。Twitter社から規制を受け投稿が出来なかったようですが、いわゆる凍結という状態とは違っていました。いつの間にか投稿できるようになっていたと、小倉秀夫弁護士がツイートを再開したのは４月１０日辺りでした。

　私が３月３１日から４月２３日の再開まで作業を中断していた間のことですが、４月の初めには、落合洋司弁護士（東京弁護士会）の過去のツイートがヘイトスピーチだと問題化され、立憲民主党の公認取り消しとなり、しばらくはツイートを自粛するような動きもありました。

　正確に言えば、落合洋司弁護士（東京弁護士会）のツイートが問題化されたのが３月３０日辺りであったように思います。立憲民主党の公認取り消しが４月２日であったように思いますが、問題とされたツイートは２月１０日の投稿となっていたとも思います。例を見ない急展開でした。

検察の有罪立証、特別抗告審の最高裁も相手にしなかったのに。

同じ司法に生きる者として，ここまで悪あがきして有罪を取ろうとする人と組織が存在することが，心底腹立たしく，情けなく，やりきれなく，そして悲しい。

かもん弓（鴨志田 祐美）さんのツイート： "検察の有罪立証、特別抗告審の最高裁も相手にしなかったのに。 同じ司法に生きる者として，ここまで悪あがきして有罪を取ろうとする人と組織が存在することが，心底腹立たしく，情けなく，やりきれなく，そして悲しい。 https：//t.co/obk83IymyV"https://twitter.com/kamo629782/status/1120822794445410304

　上記の引用は、ここで取り上げた鴨志田裕美弁護士のツイートの全文引用になります。この程度の文字数だと大丈夫だと思いますが、ツイートが長すぎると、TwitterAPIでは全文が取得できず、点々で語尾が省略されることがあります。

　また、このファイルではTwitterの埋め込みは極力控えたいと思っています。２００件以内の埋め込みであれば、ページの読み込みで不具合は出ないと思いますが、数を計算しながら見通しを立てるのも困難なので、必要最低限のものに限っていきます。

　時刻は１９時１７分です。Twitterのトレンドから報道のあり方として気になる記事を読んでいたのですが、テレビのNHKのNEWS７で、池袋の暴走死亡事故の遺族が、顔出しで会見を行われていました。代理人の弁護士の存在は情報で少し見かけていましたが、それらしい人の姿もありました。

木嶋佳苗死刑囚　獄中結婚3回目のお相手は「週刊新潮」デスク | 文春オンライン https://bunshun.jp/articles/-/11668?utm_source=twitter.com&utm_medium=social&utm_campaign=socialLink

　どうも再審請求と関係があるようです。当初、鳥取県の似た事件のことが頭に浮かびながら記事を読んでいたのですが、逮捕したのが埼玉県警と出てきました。刑事司法において、さいたま地裁というのは、高野隆弁護士と木谷明弁護士が裁判官として無罪判決を量産したことで特別な意味があります。

昨年から司法関係者や彼女を逮捕した埼玉県警の関係者らの間では、再審請求に繋がる動きを警戒し、情報収集するなかで、「週刊新潮」のX氏の存在が浮上していた。

木嶋佳苗死刑囚　獄中結婚3回目のお相手は「週刊新潮」デスク | 文春オンライン https://bunshun.jp/articles/-/11668?utm_source=twitter.com&utm_medium=social&utm_campaign=socialLink


　高野隆弁護士についても書いておきたいことが沢山あるのですが、ひょんなことから高野隆弁護士の過去の講演のPDFファイルを読む機会がありました。それも先月の３月中のことであったように思います。

[link:] http://www.lawandpractice.net/files/no8/8_11.pdf

[link:]  奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年02月14日 - Twilog https://twilog.org/hirono_hideki/date-190214

　Twilogで調べたところ、２月１４日に高野隆弁護士のPDFファイルのリンクを含むリツイートがありました。高野隆弁護士が弘中惇一郎弁護士とともにカルロス・ゴーン氏の弁護人になったことで、マスコミに大きく注目されるようになったのは３月の初めであったように思います。

　その前の２月中であったと思いますが、柳原病院事件の無罪判決がありました。私はたまたま見かけた小さな情報で事前に知っていたのですが、無罪判決が出たことで記者会見が記事ともなっていました。その変化はジャーナリストの江川紹子氏の記事で、よく出ていたと思います。

かもん弓（鴨志田 祐美）

@kamo629782

大崎事件弁護団事務局長。かもん弓はバンド活動時の芸名です。

2016年5月に登録

かもん弓（鴨志田 祐美）(@kamo629782)さん | Twitter https://twitter.com/kamo629782

　これまで見ていなかった気もするのですが、鴨志田裕美のTwitterのプロフィールをみると、「大崎事件弁護団事務局長」とありました。弁護団の事務局というのも規模が大きそうです。大崎事件についてもいろいろと調べたことがあったのですが、忘れた部分もあるかと思います。

　大崎事件は鹿児島県の地名が事件名になっていたような気がします。袴田事件は人の名前が事件名となっていますが、地名の事件名の方が多いような気もします。

　今日もこの時間、テレビでNHKをつけていますが、昨夜の同じ頃の時間帯は、歴史秘話ヒストリアという番組で、牛小屋が出てきて、博労という言葉がその職業名のようでした。博労町という地名として記憶にあったのですが、牛と博労というのはイメージの結びつきがなかったように思います。

博労町 - Google マップ http://bit.ly/2VomJdQ

　かすかに金沢市内で見たような地名というか町名だったので調べたところ、最近は観光地として知名度が上がり、以前は金沢市民の台所とも呼ばれた近江町市場のすぐ近くでした。金沢西警察署から金沢地方検察庁に向かい右折する交差点が博労町という交差点名のようです。

　なぜだか博労町を「ばくろうちょう」と読むことは記憶にありました。「賭博」と同じ漢字の読みなので、あるいはそれで普通に読めていたのかもしれません。

　博労についてネットで調べると、「牛馬の仲買人」とありました。ネットで見たことはないですが、「牛馬解き放ち」という言葉が、以前なにかで見た言葉として長く記憶にありました。

明治5年太政官布告 295号。人身売買禁止令ともいわれる。娼妓，芸妓その他の隷属的奉公人の人身解放に関する布告の俗称。明治5 (1872) 年7月のマリア・ルーズ号事件に際し，ペルー側から日本にも娼妓という名の奴隷がいると指摘され，急遽この布告を発布して表面をとりつくろおうとしたもので，実質的には雇主側の脱法のための口実を官憲が認めたため，娼妓を解放するにはいたらなかった。しかし，のちの廃娼運動には，一つのきっかけを与えた。この娼妓解放令は 1898年の民法施行とともに廃止された。

娼妓解放令(しょうぎかいほうれい)とは - コトバンク https://kotobank.jp/word/%E5%A8%BC%E5%A6%93%E8%A7%A3%E6%94%BE%E4%BB%A4-78983


　上記に引用をしましたが、「牛馬解き放ち」で検索をすると、「娼妓解放令」という言葉が出てきました。




この、慰安婦は性奴隷、の言い出しっぺは、実は、国連人権調査員だったクマラスワミ弁護士でもマクデューガル弁護士でもない、実は日本人なのです、しかも明治政府の初代司法卿であった江藤新平です。



幕末の志士から身を起こし最後は梟首刑に処せられた江藤新平の悲劇的生涯については是非ご自分でお調べ下さい。

慰安婦＝公娼＝性奴隷　：牛馬解き放ち令 ( 日々の出来事 ) - chukaのブログ - Yahoo!ブログ https://blogs.yahoo.co.jp/kiko10da/18474416.html


　Googleの検索結果に気になる見出しのリンクがあったので開いてみたところ、江藤新平のことが出てきました。確か佐賀の乱で晒し首という最後を迎えた人物でしたが、日本初の司法大臣とも聞いたように思います。ずっと前から気になる歴史上の人物ですが、詳しくは知りません。


その後、文部大輔、左院副議長、創設された司法省の司法卿として、学制、四民平等、警察制度、司法制度の整備など、近代民主主義国家の確立に尽力します。その一方で、私腹を肥やす山形有朋や井上薫らの汚職を暴き辞職へと追い込んだため、同じ長州軍閥の木戸孝允や、大久保利通らの恨みを買い、征韓論に絡んだ政変で西郷隆盛らと共に下野することになりました。



江藤新平の略歴や評価を解説、子供や子孫はいるの？ | 日本の歴史の面白さを紹介！日本史はくぶつかん https://nihonshimuseum.com/eto-shimpei/

近代国家を目指し、司法の独立を主張、裁判所や検察機関の創設、民法の編纂に尽力した彼は「近代司法制度の父」と呼ばれています。この他にも警察制度や学制の創設にも関与しており、その功績が伺えます。

江藤新平の略歴や評価を解説、子供や子孫はいるの？ | 日本の歴史の面白さを紹介！日本史はくぶつかん https://nihonshimuseum.com/eto-shimpei/

また、江藤は「四民平等」を打ち出し、日本史の中で初めて国民の人権を認めた人物でもあります。司法制度はこれらの人権を保障するために整えられたのです。この他にも江藤は役人の汚職に厳しく、山県有朋や井上馨が関わったとされる疑惑を徹底的に追求した事でも評価されています。

江藤新平の略歴や評価を解説、子供や子孫はいるの？ | 日本の歴史の面白さを紹介！日本史はくぶつかん https://nihonshimuseum.com/eto-shimpei/

江藤兵部さんは2012年に行われた「江藤新平卿銅像まつり」で謝辞を送った際、ご自分の二人の娘さんが法曹家になった事を述べた事でも話題になりました。自分の子孫が司法の道を歩んだという事を聞けば、江藤新平も大いに喜ぶ事でしょうね。



江藤新平の略歴や評価を解説、子供や子孫はいるの？ | 日本の歴史の面白さを紹介！日本史はくぶつかん https://nihonshimuseum.com/eto-shimpei/


しかし、江藤は戦況不利と見るや、薩摩に逃亡。彼は西郷に会い、薩摩での挙兵を頼みましたが、断られてしまいました。

そして、今度は岩倉具視に話をしようと上京を試みましたが、すでに手配写真が出回っており、高知で捕らえられてしまいます。しかもその写真手配制度は、彼自身が制定したものだったのです。



【自分で自分の首を絞める羽目に…】江藤新平の悲劇 | 歴人マガジン https://rekijin.com/?p=25714



事件は帰国した山城屋が陸軍省内で割腹自殺を遂げたことで闇に葬られたが、追求を受けた山縣は一時的に失脚し、江藤は事件を摘発した張本人として長州閥の反感を買うことになった。



【明治の英傑たち】江藤新平（３）挫折した維新の理想とは | 国体文化 https://www.kokutaibunka.com/archives/2992


これに対して、江藤は「国の富強」を求めるためには「国民の安堵」を保障する法制度が不可欠であることを説き、三条実美に予算案が認められないのであれば辞職すると迫った。



【明治の英傑たち】江藤新平（３）挫折した維新の理想とは | 国体文化 https://www.kokutaibunka.com/archives/2992




　時刻は２１時２７分です。テレビのNHKのNEWS９で、旧優生保護法の救済法案成立というニュースを見ていましたが、締めくくりに今日、夕方、施行ということで驚きました。この救済法案のことは数日前からテレビで見ていました。旧優生保護法の問題は、さらに前から見ていました。

　思い出したのは、大崎事件の関係者に知的障害者が多かったという情報です。テレビでみるような情報ではなかったと思いますが、印象的に記憶にありました。




明治６年の政変による西郷・江藤らの下野は、このような状況で起された。政変を強引に主導した大久保利通は、内治優先を主唱しながら、その実は江藤に対する警戒心を露わにしていたのである。



【明治の英傑たち】江藤新平（３）挫折した維新の理想とは | 国体文化 https://www.kokutaibunka.com/archives/2992




　西郷隆盛の下野が明治６年というのは、明治維新からずいぶん早く感じました。江藤新平と同時期の下野だったというのは今夜初めて知ったことかと思いますが、西郷隆盛の下野については官本で見た「脱出す人間虎狼の群」という言葉が強烈だったのですが、以前ネットで調べても。




　『百千の窮鬼吾れ何ぞ畏れん。脱出す人間虎狼の群』



　　　＜どんな戦いにもひるむことはないが、このバケモノ(のような政治家)

　　　　どもと暮らすことなど出来ない＞

　　これは、大久保・木戸・岩倉に征韓論を覆され、薩摩に下野するさいに

　　放った一文です。

2015-02-18 - Tigers-1の日記 http://d.hatena.ne.jp/Tigers-1/20150218

　上記に引用をしましたが、今回はGoogleの検索ですぐに情報がいくつか見つかりました。上記の記事は２０１５年２月１８日が投稿日のようです。「百千の窮鬼吾れ何ぞ畏れん。脱出す人間虎狼の群」とありますが、前段の部分は初めて見たように思いました。

　大崎事件について調べていると、「大隈事件」というのが出てきました。「鹿児島夫婦殺し事件」とも呼ばれたようですが、この事件名の方は、ずっと前に少し見かけたことがあるように思いました。古い事件で国賠請求が認められていたようですが、内容な今夜初めて知ったように思います。

　これまで、冤罪で無罪が確定しても認められたのは刑事補償だけで、国賠請求が認められた試しはないという情報のみをずっと前から見てきた感覚だったので、そういうものだという思い込みがあったように思います。

　鹿児島県大隈町を「おおすみまち」と読むように思ったのですが、それは鹿児島県に大隅半島があったからで、漢字が違っていたのですが、Googleマップで大隅半島を調べたところ、大崎町が近くにあって、その大崎町も同じ冤罪の聖地のようになっている志布志市と隣接していることを確認しました。

　大崎事件の大崎町と志布志事件の同じ鹿児島県の志布志市が隣接していることは、１，２年前に知っていたのですが、記憶が曖昧になりかけていて、あらためて確認をしたというところです。鹿屋という地名は、戦時中の特攻隊の基地として知られた地名であったようにも思います。

　Googleで調べて鹿屋に特攻隊の基地があったことは確認したのですが、そのとき知覧という地名が出てきて、そちらの方が有名だったような気もしたので調べたところ、同じ鹿児島県でも薩摩半島で南九州市だと知りました。

　鹿児島県の大隅半島には行ったことがないですが、中西運輸商の４t車で、加世田市まで荷物を運び、そのついでに枕崎の港を見に行ったことがありました。指宿も温泉で有名ですが、その場所を志布志市とずっと勘違いしていたということもありました。

　鹿児島県は長距離トラック運転手の仕事で何度か行ったことがありました。幕末の薩摩藩でよく知られており、反骨というイメージも強くありますが、刑事裁判においても特別な土地柄であるように見てきました。その代表が志布志事件であり、警察の不正義を強烈に印象づけています。

　長崎か天草地方は熊本県だったように思いますが、中学生の頃の歴史の授業でも江戸時代のキリスト教徒の弾圧で、踏み絵というのは印象的なものがありました。志布志事件では警察が家族愛や良心を逆手に悪用し、「踏み字」を行ったとされ、歴史的なものを感じてきた、いわば聖地です。

　時刻は２２時３８分です。終わってCMに入ったところですが、テレビの報道ステーションでジャーナリストという後藤謙次氏が、安倍総理に提言のような発言をしていました。旧優生保護法での歴史的な謝罪のようでしたが、ここでも思い出したのが熊本県で鹿児島県に近い水俣病です。

　テレビの報道ステーションでは、川内原発が出てきましたが、鹿児島県で熊本県に近い川内市のことかと思います。そういえば聞いたような気はしましたが、川内原発というのは余り見聞きしてこなかった気がします。

[link:] 九電暗雲再び、テロ対策遅れで川内原発停止も　　:日本経済新聞 https://www.nikkei.com/article/DGXMZO44150900U9A420C1LX0000

　ネットでニュースを調べると、九電と出てきましたが、九州電力のことだと思います。九州電力で思い出すのは北九州市の方だったと思いますが、郷原信郎弁護士が関わりこじれていたらしい問題のことです。ずいぶん前のことで、藤井美濃加茂市長事件より前のように思います。

＜＜＜2019-04-24（水曜日）22：53＿［これまでの記述範囲の終了時刻］＜＜＜


