#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "参考資料／推定無罪／ジャーナリスト江川紹子／裁判で有罪判決が出るまでは、「犯罪者」ではなく、しかも無罪推定が原則です。"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-19 23:00:37 +0900
FILE_NAME: 2018-12-19-230037_裁判で有罪判決が出るまでは、「犯罪者」ではなく、しかも無罪推定が原則です。.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  カルロス・ゴーン容疑者 ジャーナリストの江川紹子氏 拘置所
記事タイトル名の文字数：59　保存ファイル名の文字数：59

#contents

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2018-12-19 23:05／2018-12-19 22:41 URL： https://twitter.com/kk_hirono/status/1075391569484607490 https://twitter.com/amneris84/status/1075385591611576320
&twitter(1075391569484607490){theme:light}
> @attacktoeatem 裁判で有罪判決が出るまでは、「犯罪者」ではなく、しかも無罪推定が原則です。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜attacktoeatem（lion_attack） 日時：2018-12-19 23:05／2018-12-19 22:39 URL： https://twitter.com/kk_hirono/status/1075391590313545728 https://twitter.com/attacktoeatem/status/1075385019936366592
&twitter(1075391590313545728){theme:light}
> 犯罪者ですから。 \n  酷い環境でなきゃ意味が無いでしょう？ \n   \n  馬鹿じゃん。 \n  守銭奴 https://t.co/0rKECO2r6M
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜amneris84（Shoko Egawa） 日時：2018-12-19 23:05／2018-12-19 22:37 URL： https://twitter.com/kk_hirono/status/1075391619711479808 https://twitter.com/amneris84/status/1075384692487073795
&twitter(1075391619711479808){theme:light}
> 「丁寧な説明」の出番かと…… →ゴーン容疑者勾留　「共産党時代の東欧よりひどい」と酷評（産経新聞） - Yahoo!ニュース https://t.co/qd8qUQKIoY
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2018-12-19 23:07／2018-12-19 23:06 URL： https://twitter.com/kk_hirono/status/1075392155676422145 https://twitter.com/s_hirono/status/1075391870539186176
&twitter(1075392155676422145){theme:light}
> 2018-12-19-224516_ShokoEgawa（認証済みアカウント@amneris84）：裁判で有罪判決が出るまでは、「犯罪者」ではなく、しかも無罪推定が原則です。.jpg https://t.co/mdZ0LpTu7J
◁◁◁
<hr />


[link:] 2018年12月19日23時09分の登録： ＼Shoko Egawa　@amneris84＼裁判で有罪判決が出るまでは、「犯罪者」ではなく、しかも無罪推定が原則です。 http://hirono2014sk.blogspot.com/2018/12/shoko-egawaamneris84_19.html

[link:] 2018年12月19日23時09分の登録： ＃Shoko Egawa　@amneris84＃のツイート／2018-12-04_0720〜2018-12-19_2241／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月19日23時09分 http://hirono2014sk.blogspot.com/2018/12/shoko-egawaamneris842018-12-0407202018.html

　わかりやすく明快な無罪推定ですが・・・。普通は推定無罪となっている気もしました。相変わらず感のあるジャーナリストの江川紹子氏でした。

