#+TITLE: "２０１１年３月１６日、福島原発の放射能漏れの最中、事務員に休んでもらうため官邸に講義したという日隅一雄弁護士のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-14 11:49:24 +0900
FILE_NAME: 2019-08-14-114924_２０１１年３月１６日、福島原発の放射能漏れの最中、事務員に休んでもらうため官邸に講義したという日隅一雄弁護士のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 原発問題 
記事タイトル名の文字数：59　保存ファイル名の文字数：81

* ２０１１年３月１６日、福島原発の放射能漏れの最中、事務員に休んでもらうため官邸に講義したという日隅一雄弁護士のツイート
  :LOGBOOK:
  CLOCK: [2019-08-14 水 11:51]--[2019-08-14 水 15:07] =>  3:16
  :END:

＞＞＞2019-08-14（水曜日）11：51＿［これからの記述範囲の開始時刻］＞＞＞

　日隅一雄弁護士は故人で、確認すると２０１２年６月１２日に亡くなられていたとのことです。生年も今回、確認したのですが１９６３年１月３０日とのことです。学年では２つ年上になりますが７年も前に亡くなられていたことになります。

　日隅一雄弁護士のことを思い出したのも久しぶりですが、原発反対の活動も代表的に行っているらしい海渡雄一弁護士のTwitterタイムラインで名前を見かけました。そちらの記事はまだ作成中で、こちらの記事を完成させてから編集に戻る予定でいます。

　日隅一雄弁護士のブログも残っていることを確認しましたが、コメント欄で自分の事件のことを書いたところ、そのコメントを削除され、「某氏のためではありません」などという理由で、私の被害者や事件の関係者のプライバシーを尊重したようなことが書いてありました。

　いつ頃か思い出せないですが、２０１０年４月に私がTwitterを始めるよりは前だったと思います。ツイートととして何かを書いたという記憶はないですが、ネットで何か反論のようなものを書いたという記憶は残っているので、現在ははてなのブログで、移行したデータがあるかもしれません。

　たぶんスクリーンショットのようなものも残していると思いますが、これもずっと眠っていた記憶で、海渡雄一弁護士がきっかけで、にわかに蘇りました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-14 12:14／2019-08-14 12:04 URL： https://twitter.com/kk_hirono/status/1161476099080982529 https://twitter.com/s_hirono/status/1161473700958523392
&twitter(1161476099080982529){theme:light}
> 2019-08-14-112408_（1）　情報流通促進計画さんはTwitterを使っています：　「申し訳ないのですが、原発に反対していた人はこういう事態があるからこそ、反対していたんです。.jpg https://t.co/nLFO3egOHs
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-14 12:14／2019-08-14 12:04 URL： https://twitter.com/kk_hirono/status/1161476114570731523 https://twitter.com/s_hirono/status/1161473627604209664
&twitter(1161476114570731523){theme:light}
> 2019-08-14-112057_（1）　情報流通促進計画さんはTwitterを使っています：　「直ちに抗議の電話をかけました。「殺すのか」と。RT　@11sasaki：　RT　@thot.jpg https://t.co/RD1bIqlkKY
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-14 12:14／2019-08-14 12:04 URL： https://twitter.com/kk_hirono/status/1161476130551074816 https://twitter.com/s_hirono/status/1161473554216435712
&twitter(1161476130551074816){theme:light}
> 2019-08-14-074117_（1）　情報流通促進計画さんはTwitterを使っています：　「事務所の事務員に休んでもらいたくても休日にしてもらわないと休んでもらうわけにいかないと官邸.jpg https://t.co/OM6kItq65T
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-14 12:14／2019-08-14 12:03 URL： https://twitter.com/kk_hirono/status/1161476154219352064 https://twitter.com/s_hirono/status/1161473480266620928
&twitter(1161476154219352064){theme:light}
> 2019-08-14-074022_（1）　（from：yamebun）　until：2011-03-17　since：2011-03-11　-　Twitter検索　／　Twitter.jpg https://t.co/87zTBjzfix
◁◁◁
<hr />

　リツイート済みでしたが、次の海渡雄一弁護士のツイートになります。リツイートとして見かけたように思っていたのですが、本人のツイートでした。次にTwitterＡＰＩから読み込みます。

▶ ツイート％kidkaido（海渡雄一）％2019/06/10 18:48％ https://twitter.com/kidkaido/status/1138020203181137920
&twitter(1138020203181137920){theme:light}
> 日隅一雄情報流通促進賞の表彰式を12日18時15分から、日比谷図書館地下ホールで開催します。
> 大賞は書籍「サカナとヤクザ」を著した鈴木智彦さん、奨励賞は島明美さんと上西充子さん、特別賞は元県民投票の会代表の元山仁士郎さんです。
> い… https://t.co/x2YCyirBre  
▶

　このあとスクリーンショットをリツイートする予定ですが、前に海渡雄一弁護士のツイートで「共謀罪は入らない」という広告のようなものが見えて、後ろには福島瑞穂弁護士のツイートがリツイートされています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-14 12:23／2019-08-14 12:23 URL： https://twitter.com/kk_hirono/status/1161478459652280322 https://twitter.com/s_hirono/status/1161478328639004672
&twitter(1161478459652280322){theme:light}
> 2019-08-14-121656_海渡雄一@kidkaido·6月10日日隅一雄情報流通促進賞の表彰式を12日18時15分から、日比谷図書館地下ホールで開催します。大賞は書籍「サカナとヤク.jpg https://t.co/HSilitYEns
◁◁◁
<hr />

　日隅一雄弁護士のツイートは、自作のスクリプトを使って３１００件ほどのツイートのまとめ記事を作成しました。３１５０ぐらいだったかもしれません。３２５０ぐらい取得できることもあるのですが、データの切れ目の関係なのか最も少ない方でした。

[link:] 2019年08月14日07時34分の登録： @yamebun（情報流通促進計画）のツイート　”．＊”　3153／3153：2010-10-14　10：54〜2012-06-10　12：15　2019年08月14日07時34分の記録 http://hirono2014sk.blogspot.com/2019/08/yamebun315331532010-10-1410542012-06.html

　ページをブラウザで開いて、「休日」をキーワードでページ内検索したところ、どんぴしゃですぐに該当箇所が見つかりました。意外なのは３つほど「休日」を含むツイートがかたまっていたことです。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜yamebun（情報流通促進計画） 日時：2019-08-14 12:32／2011-03-16 08:52 URL： https://twitter.com/kk_hirono/status/1161480606175387650 https://twitter.com/yamebun/status/47807420336058368
&twitter(1161480606175387650){theme:light}
> 事務所の事務員に休んでもらいたくても休日にしてもらわないと休んでもらうわけにいかないと官邸に抗議しました。真摯に聞いてもらいました。要望があるなら、直接、電話して伝えよう！身を守るためにも！ #genpatsu #fukushima #tsunami
◁◁◁
<hr />

　上記にリツイートしたのが探していたメインのツイートでした。読んだのも久しぶりですが、読んだ印象が以前とは違ったものでした。以前は事務員の日当を日本政府や官邸が負担しろと要求しているように感じたのですが、今回はよりソフトに税務対策に近いものを感じました。

　時刻は１４時１６分です。秋重実弁護士のタイムラインでまた取り上げておきたいものが出てきました。山口貴士弁護士のツイートもリツイートとして見かけるものに看過し難い問題性を感じています。表現の不自由展関連のものです。

```
1911. ［TW yamebun（情報流通促進計画） 日時：2011-03-16 08：37］
> 風で影響を受ける圏内に住む人に脱出する選択肢を与えるべく東北関東を休日にすべき→【産経】米シンクタンク、科学国際安全保障研究所（ＩＳＩＳ）は１５日、同原発の事故は最も深刻な「レベル７」に達する可能性もあると指摘した。 #genpatsu #fukushima #tsunami
- https：//twitter.com/yamebun/status/47803613933871104

1910. ［TW yamebun（情報流通促進計画） 日時：2011-03-16 08：40］
> 【官邸に電話するつもり】 風で影響を受ける圏内に住む人に脱出する選択肢を与えるべく東北関東を休日にすべき→【産経】科学国際安全保障研究所は１５日、同原発の事故は最も深刻な「レベル７」に達する可能性もあると指摘した。 #genpatsu #fukushima #tsunami
- https：//twitter.com/yamebun/status/47804331474436096

1909. ［TW yamebun（情報流通促進計画） 日時：2011-03-16 08：52］
> 事務所の事務員に休んでもらいたくても休日にしてもらわないと休んでもらうわけにいかないと官邸に抗議しました。真摯に聞いてもらいました。要望があるなら、直接、電話して伝えよう！身を守るためにも！ #genpatsu #fukushima #tsunami
- https：//twitter.com/yamebun/status/47807420336058368


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： @yamebun（情報流通促進計画）のツイート　”．＊”　3153／3153：2010-10-14　10：54〜2012-06-10　12：15　2019年08月14日07時34分の記録 http://hirono2014sk.blogspot.com/2019/08/yamebun315331532010-10-1410542012-06.html
```

　上記に引用したツイートは投稿順に一連のものです。２０１１年３月１６日８時５２分が最終になっていますが、１０つほど後に投稿されたツイートに目を通しました。３月１１日２時４６分とされていた東日本大震災発生前後のツイートから続けて身を通しました。

　日隅一雄弁護士のツイートにある事務員の休日について、背景や流れを把握し正確な理解につなげておきたいと考えたからです。

　可能性として国や政府が大災害発生の状態で「休日宣言」をすれば、休業補償につながるのかとも想像したのですが、それらしい説明は確認できませんでした。

　当時の混乱ぶりというのはテレビで見ていた記憶にありますが、休日宣言を求める声や有識者の提言というのも見た記憶はありません。テレビのチャンネルによって放送内容も違うので、たまたま目にすることがなかっただけかもしれないですが、大きな問題にはなっていなかったはずです。

　当時も日隅一雄弁護士の法律事務所について調べた記憶はありません。最近は事務員を雇っていない弁護士個人だけの法律事務所もあるという話は、ときたまTwitterで見かけています。

　法律事務所によってはホームページで事務員を紹介しているところもありますが、そういう事務所は弁護士の数もそこそこ多くて、大所帯という感じです。日隅一雄弁護士の法律事務所を探し出せるか、探し出せても当時の事務所の規模などは確認が難しく思われます。

```
日隅　一雄氏（ひずみ・かずお=弁護士）12日、胆のうがんのため死去、49歳。連絡先は東京共同法律事務所。お別れの会を行うが日取りなどは未定。

市民メディア「NPJ」の編集長を務め、情報公開や表現の自由に関して積極的に活動。東京電力福島第1原発事故後は東電の記者会見などに出席し、ブログで情報発信を続けた。

［source：］日隅一雄氏が死去　弁護士： 日本経済新聞 https://r.nikkei.com/article/DGXNASDG1300I_T10C12A6CC0000?s=3
```

　共同法律事務所は共産党系の色合いの極めて強い弁護士の集まりだという情報を見かけてきました。金沢にも金沢共同法律事務所があるかと思いますし、当時、所属していた西村依子弁護士に法律相談を受けたことなども、これまでに記述したことがあるかと思います。

　簡単な方法としては告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のTwilogで「共同法律事務所」と検索を実行すれば、手掛かりが得られるかと思います。

[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「共同法律事務所」の検索結果 - Twilog https://t.co/yH3RsL5dxM

<hr />

　実際にやってみた検索結果が予想とはずいぶん違っていて、喜久山大貴弁護士の京都市中京区の市民共同法律事務所というのも出てきました。２０１８年８月５日が最も古いもので、金沢共同法律事務所というのは本日のツイート以外にほとんどみられません。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「共同法律事務所」の検索結果 - Twilog https://t.co/Epv0gD0rxj

<hr />

　こちらの検索結果もおかしいと思いながら、ようやく勘違いに気が付きました。私が金沢共同法律事務所と考えたのは、金沢合同法律事務所が正しかったと思います。こんな勘違いもあるのかと思いました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「合同法律事務所」の検索結果 - Twilog https://t.co/c94HsTdrr7

<hr />
[link:] » 告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)/「合同法律事務所」の検索結果 - Twilog https://t.co/MUcTbTWUcw

<hr />

　この項目では２０１１年３月の日隅一雄弁護士のツイートを探しましたが、あのブログ記事とコメント欄の内容を捜すとなるとさらに困難が予想されます。しかし、それも情報を捜し出す訓練にもなりそうです。この機会にやってみたいと思います。

＜＜＜2019-08-14（水曜日）15：07＿［これまでの記述範囲の終了時刻］＜＜＜

