#+TITLE: "参考資料／再審／2015年大阪の同居少女強姦無罪判決／「確認した上で隠したのなら人間辞めていいレベル」とまで検事を批判したモトケンこと矢部善朗弁護士（京都弁護士会）のツイート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-01-10 14:17:08 +0900
FILE_NAME: 2019-01-10-141708_「確認した上で隠したのなら人間辞めていいレベル」とまで検事を批判したモトケンこと矢部善朗弁護士（京都弁護士会）のツイート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  大阪市強姦虚偽証言再審事件 モトケンこと矢部善朗弁護士（京都弁護士会） 検察批判 後藤貞人弁護士 ジャーナリストの江川紹子氏 冤罪 再審無罪
記事タイトル名の文字数：87　保存ファイル名の文字数：82

#contents

* 「確認した上で隠したのなら人間辞めていいレベル。」「裁判官も同罪。」「弁護人の評価は情報不足で保留」という強姦虚偽証言再審無罪に対するモトケンこと矢部善朗弁護士のツイート
  :LOGBOOK:
  CLOCK: [2019-01-10 木 14:23]--[2019-01-10 木 15:04] =>  0:41
  :END:

＞＞＞2019-01-10（木曜日）14：24＿［これからの記述範囲の開始時刻］＞＞＞

▶ ツイート％motoken_tw（モトケン）％2019/01/08 15:20％ https://twitter.com/motoken_tw/status/1082522471104884738
&twitter(1082522471104884738){theme:light}
> 自称被害者が診察を受けたとする医師から確認を取らなかったのなら重過失レベルの間抜けさなので検事を続けるべきではない。
> 確認した上で隠したのなら人間辞めていいレベル。
> 裁判官も同罪。
> 弁護人の評価は情報不足で保留。 https://t.co/pq1K9NY34x  
▶

　数日前に見かけていたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートです。改めて確認すると1月8日15時20分という投稿時刻となっています。今日は10日なので一昨日になります。ちょうど判決が出た日だと思いますが、私が判決を確認したのはもう少し後の時間だったと思います。

▶ ツイート％motoken_tw（モトケン）％2019/01/08 15:09％ https://twitter.com/motoken_tw/status/1082519592088420352
&twitter(1082519592088420352){theme:light}
> 性的被害を受けたというウソの証言で約6年も身柄拘束　人が人を裁く刑事裁判の怖さ(前田恒彦) - Y!ニュース https://t.co/dFxGI0FiVd  
▶

　上記の前田恒彦元検事の記事を紹介したモトケンこと矢部善朗弁護士（京都弁護士会）のツイートですが、同じ記事の紹介ツイートは他の弁護士のツイートでも見かけていたように思います。記事の方はまだ読んでおらず、リンクを開いてもいないかもしれません。

　リンクの記事をブラウザで開きました。こういうタイトルだったのかと思ったのですが、記事を読むのは後にしておきます。また悪い癖が出て、設定した項目の趣旨から外れた方向に進んでしまう可能性もあります。今は、モトケンこと矢部善朗弁護士（京都弁護士会）にフォーカスしています。

　この項目で取り上げたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは、これまでのモトケンこと矢部善朗弁護士（京都弁護士会）らしい、他者に向けた厳しさと、裁判官に対するより厳しい要求がありますが、「弁護人の評価は情報不足で保留」というのがミソです。

　モトケンこと矢部善朗弁護士（京都弁護士会）のTwitterライムラインについては、毎日記録しているものとは別に、他の弁護士アカウントと同じように、その都度記録しているものがあります。それも何度か実行していると思います、1月8日以降のものを確認します。

```
[9994]  % dp -p|grep -E '.* 2019年01月(0[89]|10)日.*@motoken_tw.*'
[link:] 2019年01月08日06時00分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2019年01月07日”：16件 http://hirono2014sk.blogspot.com/2019/01/motokentw2019010716.html
[link:] 2019年01月08日13時17分の登録： ＃モトケン　@motoken_tw＃のツイート／2018-12-31_0905〜2019-01-08_1306／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月08日13時17分 http://hirono2014sk.blogspot.com/2019/01/motokentw2018-12-3109052019-01.html
[link:] 2019年01月08日16時18分の登録： ＼モトケン　@motoken_tw＼自称被害者が診察を受けたとする医師から確認を取らなかったのなら重過失レベルの間抜けさなので検事を続けるべきではない。 http://hirono2014sk.blogspot.com/2019/01/motokentw_8.html
[link:] 2019年01月08日16時18分の登録： ＃モトケン　@motoken_tw＃のツイート／2018-12-31_1129〜2019-01-08_1544／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月08日16時18分 http://hirono2014sk.blogspot.com/2019/01/motokentw2018-12-3111292019-01.html
[link:] 2019年01月09日04時22分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2019年01月08日”：36件 http://hirono2014sk.blogspot.com/2019/01/motokentw2019010836.html
[link:] 2019年01月09日13時17分の登録： ＃モトケン　@motoken_tw＃のツイート／2019-01-01_0848〜2019-01-09_1313／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月09日13時17分 http://hirono2014sk.blogspot.com/2019/01/motokentw2019-01-0108482019-01.html
[link:] 2019年01月09日16時12分の登録： ＼モトケン　@motoken_tw＼風評被害に基づく賠償請求が難しいということは、事故直後から小倉秀夫弁護士も言っていたはずです。事故直後でも裁判で勝つのは難しい。まして http://hirono2014sk.blogspot.com/2019/01/motokentw_9.html
[link:] 2019年01月09日16時12分の登録： ＃モトケン　@motoken_tw＃のツイート／2019-01-02_0737〜2019-01-09_1548／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月09日16時12分 http://hirono2014sk.blogspot.com/2019/01/motokentw2019-01-0207372019-01.html
[link:] 2019年01月10日00時05分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2019年01月09日”：55件 http://hirono2014sk.blogspot.com/2019/01/motokentw2019010955.html
[link:] 2019年01月10日13時17分の登録： ＃モトケン　@motoken_tw＃のツイート／2019-01-04_1111〜2019-01-10_1248／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月10日13時17分 http://hirono2014sk.blogspot.com/2019/01/motokentw2019-01-0411112019-01.html
[link:] 2019年01月10日13時56分の登録： ＼モトケン　@motoken_tw＼虚偽報告をした検察官に対する制裁を具体的に検討する段階だと思う。＞「存在しない」「いや、実はありました…」～行政文書の隠蔽とは別の、も http://hirono2014sk.blogspot.com/2019/01/motokentw_10.html
[link:] 2019年01月10日13時56分の登録： ＃モトケン　@motoken_tw＃のツイート／2019-01-04_1111〜2019-01-10_1248／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月10日13時56分 http://hirono2014sk.blogspot.com/2019/01/motokentw2019-01-0411112019-01_10.html
```

　現在は、もっぱら画像つきツイートのTwitterAPIでの投稿となっている非常上告-最高検察庁御中_ツイッター（@s_hirono）のアカウントですが、最新200件のツイートから次のようにモトケンこと矢部善朗弁護士（京都弁護士会）を含むものを抽出しました。丁度8日以降でした。

```
[9996]  % tu s_hirono 200 |tac |grep motoken_tw
> 2019-01-08-160729_K-9999さんがリツイート＞　モトケン（@motoken_tw）：　自称被害者が診察を受けたとする医師から確認を取らなかったのなら重過失レベルの間抜け.jpg https://t.co/0t6ful86o3
> 2019-01-08-190824_弁護士あだちあだちけいたけいたさんがリツイート＞　モトケン（@motoken_tw）：　自称被害者が診察を受けたとする医師から確認を取らなかったのなら重.jpg https://t.co/Jc2DPnmGWK
> 2019-01-09-135048_深澤諭史のリツイート（モトケン　@motoken_tw）：自称被害者が診察を受けたとする医師から確認を取らなかったのなら重過失レベルの間抜.jpg https://t.co/5ZUD43xLqt
> 2019-01-09-161108_モトケン（@motoken_tw）：　返信先：@sei201さん風評被害に基づく賠償請求が難しいということは、事故直後から小倉秀夫弁護士も言っていたはず.jpg https://t.co/FgWRYTNFTH
> 2019-01-10-001334_モトケン（@motoken_tw）：風評被害の拡大は放置できない。.jpg https://t.co/zjHc8bAD9y
> 2019-01-10-001553_モトケン（@motoken_tw）：専門知識がない人のために弁護士がいる。弁護士を頼むためには費用がいる。裁判には時間がかかる。そして風評.jpg https://t.co/kIo6LB84Mb
> 2019-01-10-003146_弁護士秋重実さんがリツイート＞　モトケン（@motoken_tw）：　例の検事の同期の弁護士が検事を擁護しているが、私の同期の大阪地検次席検事は「無罪と.jpg https://t.co/KzKSNKdB3d
> 2019-01-10-003422_弁護士秋重実さんがリツイート＞　モトケン（@motoken_tw）：　例の検事の同期の弁護士が検事を擁護しているが、私の同期の大阪地検次席検事は「無罪と.jpg https://t.co/D83odmOYy8
> 2019-01-10-125122_モトケン（@motoken_tw）：　虚偽報告をした検察官に対する制裁を具体的に検討する段階だと思う。＞「存在しない」「いや、実はありました…」～行政文.jpg https://t.co/VRduSlmbPv
> 2019-01-10-140710_モトケン（@motoken_tw）：農家の人が切に願っていることは、商売の邪魔をしないでくれ、ということだと思いますよ。それと原発政策は関.jpg https://t.co/QlxPnwhiNd
> 2019-01-10-140935_モトケン（@motoken_tw）：してますよ。さんざん。私のツイログで「東京電力」または「東電」で検索すればわかります。.jpg https://t.co/KZ0b6765zy
> 2019-01-10-141403_モトケン（@motoken_tw）：自称被害者が診察を受けたとする医師から確認を取らなかったのなら重過失レベルの間抜けさなので検事を続ける.jpg https://t.co/lGbpl1K4Gx
```

　改めて「弁護人の評価は情報不足で保留」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイートでの発言ですが、情報不足であっても、自ら情報を探し確認をすることがあるのか疑問に思いましたし、その結果、前言を訂正することがあるのかとも考えました。

　実は、今日の午前中になって、それまでの再審無罪事件に対する認識を一変させる情報を読みました。その記事は、昨夜というか寝る前に目にしてブラウザで開いたままにしていたように思います。寝た時間というのもよく憶えていないのですが、テレビや電気をつけたままの寝落ちではなかったと思います。

　本当は、そちらを先に取り上げる予定でいたのですが、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインで、直接ではなかったですが、また検事を批判するような記事を見つけたことで、予定を変更しました。次に取り上げるジャーナリストの江川紹子氏の記事になります。

＜＜＜2019-01-10（木曜日）15：04＿［これまでの記述範囲の終了時刻］＜＜＜


