#+TITLE: "水戸家裁下妻支部で「犬のうんこですら肥料になるのに、君たちは何の役にも立たない産業廃棄物以下じゃないか」と発言したとされた裁判官"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-06-16 11:11:10 +0900
FILE_NAME: 2019-06-16-111110_水戸家裁下妻支部で「犬のうんこですら肥料になるのに、君たちは何の役にも立たない産業廃棄物以下じゃないか」と発言したとされた裁判官.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 中村元弥弁護士（旭川弁護士会）  中村元弥弁護士のリツイート 淡路島の若手弁護士 少年事件 江村正之検察官
記事タイトル名の文字数：64　保存ファイル名の文字数：86

* 水戸家裁下妻支部で「犬のうんこですら肥料になるのに、君たちは何の役にも立たない産業廃棄物以下じゃないか」と発言したとされた裁判官
  :LOGBOOK:
  CLOCK: [2019-06-16 日 11:43]--[2019-06-16 日 12:18] =>  0:35
  :END:

＞＞＞2019-06-16（日曜日）11：43＿［これからの記述範囲の開始時刻］＞＞＞

　今朝、中村元弥弁護士のTwitterタイムラインで見つけた情報でしたが、情報をたどっていくと色々な発見がありました。水戸家裁下妻支部とありますが、これは江村正之検察官の弁護士事務所のすぐ近くではないかと思います。

　今年に入ってからの事件だと思いますが、茨城県神栖市で、確か女子大生が殺害される事件があり、当初は謎の多い事件としてテレビで報道されていましたが、ネットのニュースや情報では売買春のトラブルで殺害された可能性が高そうでした。

　２，３日ぐらいの間だったと思いますが、テレビで茨城県の神栖市と鹿島神宮駅が繰り返し報道され、それがきっかけでGoogleマップで江村正之検察官の法律事務所を調べました。江村正之検察官が下妻市の辺りで弁護士をしていることは、Googleの検索でずっと前から知っていました。

　細かいことまではっきりとは記憶していないですが、岡口基一裁判官の経歴を知ったのと、江村正之検察官が茨城県下妻市の辺りで弁護士をしていると知ったのは同じ頃だったように思います。岡口基一裁判官が「ボツネタ」というはてなダイアリーをやっていた頃のことです。

　細かく言えば、はてなダイアリーというのはブログとは少し違っていて、１，２年ほど前に完全に消滅したネットサービスなのですが、岡口基一裁判官はそのはてなダイアリーに絡んで脅迫事件か何かの被害者となって運営を他に譲り、ボ２ネタなどとなっていました。

▷ リツイート→1961kumachin（中村元弥）＞tsundereblog（ツンデレブログ）｜2019/06/15 14:18／2019/06/15 13:49｜https://twitter.com/1961kumachin/status/1139764133962715136 ／ https://twitter.com/tsundereblog/status/1139756677350092800
&twitter(1139764133962715136){theme:light}
> RT @tsundereblog: 他罰性の強い性格が読みとれる、責任逃れのための文章。
> ７年前の（自称）誤報で、なにか「緊急避難」だ。 https://t.co/HRwCgK5erD  

▶ ツイート％asty_md（asty_md）％2019/06/13 11:44％ https://twitter.com/asty_md/status/1139000493600993280
&twitter(1139000493600993280){theme:light}
> 水戸家裁下妻支部で「犬のうんこですら肥料になるのに、君たちは何の役にも立たない産業廃棄物以下じゃないか」と発言したとされた裁判官について長嶺さんは匿名とされてますが、実はご本人が釈明記事を挙げておられます https://t.co/0gkByQxDpN  
▶

　上記のツイートの内容は初めて知ったように思います。どうも弁護士が裁判官を批判する意図でマスコミに情報を流したようです。すぐに思い出したのは同じ茨城県での、確か龍ケ崎支部の裁判官のことです。「先生の将来が心配です。」などと弁護士をたしなめたのが問題化されたようです。

　この件はずっと前から取り上げておく予定でいましたが、弁護士を批判したその裁判官は、その後、転落の人生を歩むこととなったようです。

　ツンデレブログというTwitterアカウント名の淡路島の弁護士ですが、これも印象的なツイートが、同じ中村元弥弁護士のタイムラインでリツイートとしてありました。２０１７年の３月の初めだったと思います。その数日後に能登高校で女子高生の殺害事件が起こり、更に感慨深さがあります。

＜＜＜2019-06-16（日曜日）12：18＿［これまでの記述範囲の終了時刻］＜＜＜

