#+STARTUP: content
#+TAGS: 検察(k) 警察(p) 弁護士(b) 裁判所(s) 報道(h) 裁判所(j) 公開(o)
#+OPTIONS:  H:3  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+STARTUP: hidestars
#+TITLE: "告発に至る経緯／福井刑務所／テレビ／主人公の弁護士が若狭湾の福井県小浜市辺りでくつろいでいた２時間ドラマの視聴"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2018-12-14 15:29:02 +0900
FILE_NAME: 2018-12-14-152902_主人公の弁護士が若狭湾の福井県小浜市辺りでくつろいでいた２時間ドラマの視聴.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  福井刑務所 上原千可子弁護士 大阪弁護士会 深澤諭史弁護士 @Abema_Prime #アベプラ
記事タイトル名の文字数：55　保存ファイル名の文字数：59

#contents

* 人助けで旅行し、小さなホテルのような旅館でくつろいでいた福井県の若狭湾が舞台の１つになっていた２時間の弁護士ドラマ

　このドラマのことはずっと前から気になっていて、書いておきたいと思っていました。福井刑務所に服役中、独居房の小型テレビで視聴したドラマでした。なお、７，８人収容だった雑居房でもテレビの大きさは同じでした。たぶん１４型の小型テレビだったように思います。

　もう２０年以上前にみたドラマだったので、記憶もわずかにしか残っていません。弁護士が主人公という当時はかなり珍しく感じた２時間ドラマでした。もともと私は余りテレビをみる週間がなく、特に２時間ドラマというのは時間が長く感じられて、集中して見る気になりませんでした。落ち着きがなかったと言えます。

　なので、当時、弁護士が主人公の２時間ドラマが少なかったというのは、私の個人的な感覚でした。当時の２時間ドラマというのはサスペンスドラマと言われたもので、現在でも締めくくりが東尋坊のような海の断崖絶壁といわれるタイプのドラマです。シリアスという言い方も出来るかもしれません。

　ただ、その当時のサスペンスドラマというのは、現在、ほとんど見かけていないようにも思うので、感覚を共有できない人はいそうです。そんな中で、そのドラマは、ずいぶんとくつろいだ、のんびりした雰囲気のドラマでした。あるいは殺人事件ではなかったのかもしれません。

　主人公の弁護士が住まいし活動する場所は、名古屋市という舞台設定だったと思います。当時は珍しく感じました。現在は、京都であったり、観光地を舞台に、旅番組のような趣の２時間ドラマが多いように思いますが、当時は、謎を解きながら真犯人にたどり着くという筋書きが多かったようにも思います。

　定年で引退した裁判官が、余暇を持て余し、道楽で人助けをするようにも見えるドラマでしたが、元裁判官という話はなかったと思いますし、主人公の俳優も定年するような年齢には見えませんでした。

　その主人公の俳優というのが、古谷一行か林隆三でした。林隆三の名前は忘れていたので調べてわかりましたが、数年前にお亡くなりになっていたことも今回始めて知ったように思います。

　古谷一行ももう長い間、テレビで姿を見ず話も聞かないですが、昭和の時代、八つ墓村などの横溝正史シリーズの金田一なんとか役で著名は俳優でした。

　私は余り真剣にドラマを見なかったし、当時はネットもないので簡単に調べることができなかったので、いつしか古谷一行と林隆三の区別ができなくなっていました。

　そんなにそっくりさんというわけでもなかったように思いますが、役柄を演じていると髪型も服装も個性的なものとなりうるので、わかりづらかったのだと思います。

　このドラマのことは、これまでたびたび思い出すことが多かったです。しかし、調べて確認しようと行動に移すことはありませんでした。結論をいうと調べても確認は得られなかったのですが、１つ思わぬものを見つけました。それも弁護士について考えさせられるもので、調べた目的と共通性がありました。

　本当は他に今すぐ取り上げておきたいことが２，３あったのですが、こちらを優先することとしました。弁護士が事件解決のため現地に向かって調べるというのは、珍しくはないと思いますが、とにかくそのドラマの弁護士はのんびりとくつろいで見えました。

　昨夜、最終回となったばかりですが、「リーガルV～元弁護士・小鳥遊翔子」で俳優の高橋英樹が演じた元大学教授という所長弁護士が、いくらか似ていたともいえます。

　あそこまで極端な役柄ではなかったですが、それがかえって、この弁護士はどうなっているのかと現実的な問題として考えさせられるものがありました。

　また、人助けと言っても、真犯人を追い詰め探し出し、遺族の無念を晴らす、というものではなかったと思います。どちらかといえば、夜逃げを手伝うのに近かったように思います。実際、夜逃げ屋本舗というようなドラマがあり、連ドラだったようにも思いますが、中村雅俊が主演でした。

```
日本テレビ系列で放送された。

第1シリーズ『夜逃げ屋本舗』は、1999年1月13日より3月17日まで毎週水曜日22：00 - 22：54に、「水曜ドラマ」枠で放送。

第2シリーズ『新・夜逃げ屋本舗』は、2003年4月16日より6月25日まで毎週水曜日22：00 - 22：54に、「水曜ドラマ」枠で放送。

スペシャルは1999年12月30日に放送。

毎回「プロの夜逃げ屋」「夜逃げのプロ」といった台詞が入っていた。

決め台詞は「お待たせしました、夜逃げ屋本舗です。」。

［source：］夜逃げ屋本舗 - Wikipedia https://ja.wikipedia.org/wiki/%E5%A4%9C%E9%80%83%E3%81%92%E5%B1%8B%E6%9C%AC%E8%88%97
```

　余りじっくりページを見ていないのですが、映画と思われる夜逃げ屋本舗は平成４年の１月にも公開されていたようです。最近では、夜逃げという言葉自体をほとんど見かけなくなっています。

* ドラマについて調べるきっかけとなった深澤諭史弁護士の出演生番組「AbemaPrime（アベマプライム）」
  :LOGBOOK:
  CLOCK: [2018-12-14 金 16:33]--[2018-12-14 金 17:52] =>  1:19
  :END:

　***＞＞2018-12-14（金曜日）16：33＿［これからの記述範囲の開始時刻］＞＞***

　直前の小項目では時間の記録をし忘れていました。時間の記録はこれが２つ目になると思いますが、ずいぶん久しぶりのことです。一年ほどやっていなかったようにも思います。

　このあとは、奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のツイートをリツイートするというかたちで記載をしたいと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-14 16:40／2018-12-14 14:51 URL： https://twitter.com/kk_hirono/status/1073482754665283585 https://twitter.com/hirono_hideki/status/1073455436601249792
&twitter(1073482754665283585){theme:light}
> 「若狭湾唯一の弁護士」として相談担う美人弁護士撮り下ろし | マイナビニュース https://t.co/sOLrIbLIY5 \n  現実世界でも美人弁護士は少なくない。ここで紹介するのは、「小浜ひまわり基金法律事務所」の3代目所長を務める上原千可子弁護士。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-14 16:40／2018-12-14 14:43 URL： https://twitter.com/kk_hirono/status/1073482776718893056 https://twitter.com/hirono_hideki/status/1073453514276233217
&twitter(1073482776718893056){theme:light}
> 古谷一行 - Wikiwand https://t.co/bUmuON9Mgp
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-14 16:40／2018-12-14 14:41 URL： https://twitter.com/kk_hirono/status/1073482795773657088 https://twitter.com/hirono_hideki/status/1073452984204374016
&twitter(1073482795773657088){theme:light}
> “花の１５期生”林隆三さん急死…「国盗り物語」などで名演技 (1/3ページ) - 芸能社会 - https://t.co/M6hh8hNsyx（サンスポ） https://t.co/X7loB2gwSg
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-14 16:40／2018-12-14 14:40 URL： https://twitter.com/kk_hirono/status/1073482813876256769 https://twitter.com/hirono_hideki/status/1073452531865464832
&twitter(1073482813876256769){theme:light}
> 古谷一行と林隆三は似ている？| そっくり?soKKuri? https://t.co/Va8khaNucH
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-14 16:40／2018-12-14 14:39 URL： https://twitter.com/kk_hirono/status/1073482831806967808 https://twitter.com/hirono_hideki/status/1073452278374268928
&twitter(1073482831806967808){theme:light}
> 柴田阿弥と藤本美貴は似ている？| そっくり?soKKuri? https://t.co/wSUu23ixhA
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-14 16:40／2018-12-14 14:38 URL： https://twitter.com/kk_hirono/status/1073482857216004096 https://twitter.com/hirono_hideki/status/1073452222934003712
&twitter(1073482857216004096){theme:light}
> 柴田阿弥　似ている - Google 検索 https://t.co/9h0O4foO30
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-14 16:40／2018-12-14 14:36 URL： https://twitter.com/kk_hirono/status/1073482881559814144 https://twitter.com/hirono_hideki/status/1073451587576549376
&twitter(1073482881559814144){theme:light}
> 柴田阿弥 - Wikiwand https://t.co/GhU1DOFrW5
◁◁◁
<hr />

　気がついたのですが、AbemaPrimeに関するツイートというのは行っていなかったようです。やったつもりでいました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2018-12-14 16:45／2018-12-14 16:43 URL： https://twitter.com/kk_hirono/status/1073484161111871488 https://twitter.com/hirono_hideki/status/1073483657136893952
&twitter(1073484161111871488){theme:light}
> AbemaPrime まとめサイトにも表現責任！賠償判決で〝冬の時代〟へ！？ | 【AbemaTV】国内最大の無料インターネットテレビ局 https://t.co/JoVIlavlIJ
◁◁◁
<hr />

```
「オトナの事情をスルーする」 スマホ発の本格ニュース番組「AbemaPrime」。〝スマホ世代〟若者のためのニュース番組を目指します。平日よる9時からテレビ朝日1階のオープンスタジオで公開生放送。放送中は#アベプラを付けて、ツイートを宜しくお願いします。

キャスト
MC ふかわりょう
アンカー 柴田阿弥 (フリーアナウンサー)
レギュラー
若新雄純(慶應義塾大学特任准教授)
柳瀬博一 (東京工業大学教授) ※隔週
山田俊浩 (東洋経済オンライン編集長) ※隔週
伊形城 (イケキャス.)
気象予報士 穂川果音
司会進行 小川彩佳(テレビ朝日アナウンサー)
スタッフ
テレビ朝日
(C)テレビ朝日

AbemaNews

［source：］AbemaPrime まとめサイトにも表現責任！賠償判決で〝冬の時代〟へ！？ | 【AbemaTV】国内最大の無料インターネットテレビ局 https://abema.tv/channels/abema-news/slots/Aq2KaVauf3qofD
```

　AbemaTVを視聴したのは、これが２回目になるかと思いますが、すぐに思い出せなかったのですが、つい今しがた、２ｃｈの西村ひろゆき氏と唐澤貴洋弁護士が出た番組だったと思い出しました。よく見るとページに「無料であと６日間視聴できます」と出ていました。

　時刻は１６時５４分です。テレビに若狭勝弁護士が出てきました。石川テレビのPRIMEという番組のようです。若狭湾を舞台にした弁護士ドラマをGoogleで検索したところ人名である若狭勝弁護士がずらずらと出てきました。最近は若狭湾というのも余り聞かないように思います。

　私は長距離トラック運転手の仕事で、国道２７号線をよく通行していたので、若狭湾のことはよく知っていましたが、紀伊半島や駿河湾のような全国的な知名度はないかもしれません。

　若狭勝弁護士の解説を聞いていて、なるほどと思ったのですが、裁判所が理由を示さず求刑懲役２３年を懲役１８年の判決としてのは、控訴や上告を避けたいという思いがあったのかもしれません。

　私の傷害・準強姦被告事件は求刑自体が懲役４年でした。それも懲役４年ぐらいならと、大きな不満や反発を避け、上訴審でも維持されやすい環境づくりを、江村正之検察官が意図したのではと勘ぐったこともありました。彼の顔色が変わったのも求刑の結審だったので変えようがなかったのかもしれません。

　実際に血の気が引くような顔色の変化はみていませんが、ずいぶんと驚いたようなリアクションをしていました。公判の初めに被害者安藤文さんの意識が戻ったと述べた時、私が手放しで喜ぶ反応を見たからです。都合の悪いことを誤魔化しているに違いないと思い込んでいたふしがあります。

　見た顔の最近もよく見ている女子アナだと思っていたのですが、「司会進行 小川彩佳(テレビ朝日アナウンサー)」のようです。報道ステーションで見ている顔ではないかと思いましたが、まだ確認はしていません。

　テレビ朝日アナウンサーということは社員と考えられますが、AbemaTVとの関係が不思議に思えます。上記の引用部分には名前がないようですが、以前、不倫で大問題となっていた元アイドルの女性の姿もありました。ふかわりょう、という人もタレントのようですがテレビで見なくなっていました。

　柴田阿弥という女性も、ずっと前によくバラエティ番組で見かけていた女性だと思い込んでいたのですが、番組が次のコーナーに移ったタイミングで、スタジオのカメラの前に出てきて、そこに柴田阿弥という名前の字幕がでてびっくりしたのです。これは初めて見る名前だと思いました。

　名前が阿弥陀如来に似ているので「あみ」と読むものと思い込んだのですが、これも調べると「あや」となっていました。弥生や弥栄と同じ読みなので、よく考えると「や」と読むのが普通かもしれないのですが、たぶん初めてみた女性の名前だと思います。

　すぐに頭に浮かんだのは弥勒という名前の少女のことです。ゴルフの天才少女ということでテレビで見たのですが、私がその番組をみるだいぶん前から他の番組に取り上げられて有名人となっていたようです。

　時刻は１７時２９分です。テレビでは先ほどから元貴乃花親方の長男が離婚したことを取り上げています。今日のバイキングで１３時３０分ぐらいに初めて知ったニュースでした。今日のバイキングは、これまでにないほど、内容や項目が盛りだくさんの放送でしたが、台所にいてよく見ていませんでした。

　若狭湾が舞台となった２時間ドラマのことですが、主人公の弁護士が若狭に来た時、同行者はいなかったと思います。旅館というのもビジネスホテルのような学校の学生寮にも見える古い建物で、そこで嬉しそうにご馳走に舌鼓をうっていたのですが、それも一人だったと思います。昼かもしれません。

　夏場だと夕食の時間というのも外は明るい時間だったのかもしれないですが、そういう明るい時間の夕食シーンというのもテレビでは余り見ないように思います。そのような意外な要素が満載の弁護士が主人公のテレビドラマでした。

　***＜＜2018-12-14（金曜日）17：51＿［これまでの記述範囲の終了時刻］＜＜***

* 『リーガルハイ』（フジテレビ系）で新垣結衣演じる黛真知子弁護士の奮闘ぶりが話題となっているが、現実世界でも美人弁護士は少なくない。

```
『リーガルハイ』（フジテレビ系）で新垣結衣演じる黛真知子弁護士の奮闘ぶりが話題となっているが、現実世界でも美人弁護士は少なくない。ここで紹介するのは、「小浜ひまわり基金法律事務所」の3代目所長を務める上原千可子弁護士。


「司法試験は4日で22時間超の長丁場で、乗り切るには精神力も必要です。私ほど勢い任せも、稀だとは思うのですが、精神力と神の力で合格しました（笑い）」　


　と、自身の経験を振り返る。初挑戦の司法試験は不合格。浪人中に法科大学院の先輩が市議に立候補し、選挙の手伝いと秘書活動に奔走。ほとんど勉強する時間はなかったが、そこでの経験が勉強不足を補った。


　検事志望から一転。議員秘書として政治に関わるなかで、「私も自分の足で人の役に立ちたい！」と、過疎地域の弁護士志望へ転向。いまは、福井県小浜市の過疎地域で、“若狭湾唯一の弁護士”として、法律相談を一手に担う。


「個人の依頼が中心で、離婚、借金を始め、刑事事件などありとあらゆる内容が寄せられるので、責任は重大ですね」

［source：］「若狭湾唯一の弁護士」として相談担う美人弁護士撮り下ろし｜BIGLOBEニュース https://news.biglobe.ne.jp/trend/1126/sgk_131126_9879010857.html
```

　さきほど検索したところ上記のページが出てきましたが、同じ内容の記事は他にもいくつかあるようです。グラビア写真のようなものがあるのですが、ピンク色のネグリジェのような服に、パンティまで見えそうな写真は尋常のものではないと思います。

　座っているソファーのような椅子も、小型のベッドのように見える珍しいものです。とにかく強烈に印象づける写真です。よく見ると部屋でハイヒールもはいているようです。一般人でも異様に見えますが、それが女性弁護士なのですから考えさせられるものがあります。

　実は、この写真を見て１時間以上経ってから、ずっと前に見たことがあったような気がしていきました。

　記事には「検事志望から一転。議員秘書として政治に関わるなかで、「私も自分の足で人の役に立ちたい！」と、過疎地域の弁護士志望へ転向。いまは、福井県小浜市の過疎地域で、“若狭湾唯一の弁護士”として、法律相談を一手に担う。」ともあります。

　こういうファッションというのも人それぞれの価値観があるので、無下に否定できるものではないですが、何をアピールしているのだろうと、過疎地域で法律相談を一手に担うというお立場をあわせて考えてしまいます。

　この記事は２０１３年１１月２６日のようです。リーガルハイという弁護士ドラマのことが書いてありますが、たしか私はそのドラマの２シーズン目の途中で、その弁護士ドラマの存在を初めて知りました。

　よく考えていると、その当時にこの記事をみていれば、リーガルハイという弁護士ドラマのことも知って調べていたはずです。少なくとも私は平成９年１月以前にリーガルという言葉を知っていました。リーガルマインドが多かったとも思いますが、専門的な本でした。

　最近も日産のカルロス・ゴーン氏の逮捕で、テレビニュースとしてリーガルを見かけましたが、それは共犯者として逮捕された、確かアメリカ人の弁護士資格を持つ人物に対し、リーガルでやってくれと支持していたということで、リーガルには適法と意訳がついていました。

　実は、だいぶん前から気になっていたのですが、リーガルの意味について調べていません。たぶん以前は辞書でも調べていたと思うのですが、記憶には残っていません。法そのものを意味にするのであれば、ロースクールと同じローが出てきそうとも考えていました。

　それではリーガルについて調べてみます。

```
デジタル大辞泉の解説
リーガル（legal）
多く複合語の形で用い、法律に関する、合法的な、の意を表す。「リーガルコンサルタント」
出典　小学館デジタル大辞泉について　情報 | 凡例

［source：］リーガルとは - コトバンク https://kotobank.jp/word/%E3%83%AA%E3%83%BC%E3%82%AC%E3%83%AB-148427
```

* テレビドラマ、「リーガルハイ」、「リーガルV」から考えるリーガルの意味

　リーガルについて調べるとたしかに「合法的な」という意味があるようです。リーガルハイというドラマが始まるかなり前になると思いますが、リーガルはリーガルマインドという組み合わせでみかけることが多く、法的思考とか法的精神として意訳を見てきたと思います。

　マインドが精神や心を意味することは、ほぼ間違いないと思います。このマインドという言葉は、同じく組み合わせで、マインドコントロールとしてちょくちょく頻繁に見かけるようになりました。オウム真理教事件がきっかけでした。

* Twilogで調べてみた「上原千可子弁護士」、過去に該当なし

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「上原千可子」の検索結果 - Twilog https://t.co/mWpWlFSUpW

<hr />

▶ ツイート％hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）％2018/12/14 14:51％ https://twitter.com/hirono_hideki/status/1073455436601249792
&twitter(1073455436601249792){theme:light}
> 「若狭湾唯一の弁護士」として相談担う美人弁護士撮り下ろし | マイナビニュース https://t.co/sOLrIbLIY5
> 現実世界でも美人弁護士は少なくない。ここで紹介するのは、「小浜ひまわり基金法律事務所」の3代目所長を務める上原千可子弁護士。  
▶

　該当は１件、しかし本日投稿のものでした。以前はいまほど、ホームページやネット記事のページタイトルをツイートすることはなかったと思いますが、それを差し引いても、まったく見ていなかった可能性が客観的に高そうです。

　しかし、私としては幼い頃に見た風景のような既視感がありました。３ヶ月ほど前か、既視感を意味する外国語を見つけたのですが、ちょっと思い出せないですし、見かけない言葉でした。

　時刻は２０時４分です。テレビですが、ブロッコリーは茹ですぎると青臭さが出るので茹で時間はおよそ１分、茎は２分という話がありました。最近になってブロッコリーを電子レンジで調理したのですが、その時はじめて青臭さのようなものを感じました。

　しばらくパソコンの作業に集中していたので、テレビの進行は見ていなかったのですが、最初に悪石島が出てきた番組で、チャンネルをNEWS７に変えようとしたタイミングで、そのまま視聴することにしました。地獄が出てきた辺りで、テレビからは意識が離れていました。

　テレビをよく見ると「伝説の家政婦がIKKOの豪邸へ！」とあります。悪石島について番組を見る気になったのも、パチスロ伝説の巫女の舞台が島であったからです。悪石島は商店や店がなく人口が８０人で、小中学校で９人という聞いたことのない環境でした。

　今になって北陸中日新聞のテレビ欄を見たのですが、「大誘拐２０１８」という変わった番組をやっているようです。ドラマなのでしょう。２１時からホームアローンという映画が放送になっていたことを思い出しました。

　ちょっと文字の違った金曜ロードショーだったと思いますが、先週は「鎌倉ものがたり」で、ずいぶん久しぶりに最初から最後まで視聴しました。その次週予告がホームアローンでしたが、これも福井刑務所で視聴した映画だったように思います。

　テレビでは美味そうなハンバーグをやっていますが、ハンバーグで思い出すのは前妻のことです。肉は食べないのにハンバーグなら食べられると言って作っていました。フライパンにケッチャップを入れていましたが、テレビはソースも一緒に入れていました。

　福井県小浜市の国道２７号線だったと思いますが、舞鶴市に向かって右側にゲームセンターがありました。同じ大きな敷地には松風というレストランがあったと記憶しますが、レストランに入ったことはなかったと思います。そこでもずっと記憶にあることがあります。

　テレビでは、さきほど新聞のテレビ欄で見ていたことですが、藤原紀香が出ています。テレビでみるのはずいぶん久しぶりです。日曜日の夜のドラマで主役のような役柄をしていたように思うのですが、どんなドラマであったか思い出せません。

　「超過酷な静岡の山奥へ！」とあるので、静岡の海かと思ったのですが、浅瀬なのに今までに見たことがないぐらい汚れているように見ました。そこに出てきたのがモズクカニ。子どもの頃、同じようなカニを遊びで捕まえたのですが、食べる話は聞かなかったです。

　地元では爪に毛が生えているためか毛ガニと呼んでいましたが、子どもの頃以来、海で一度も見かけたことがありません。ムスズと呼んでいましたが、大きなサヨリも同じです。ここ２，３年は小さなサヨリも見かけなくなりました。

　３年前になるように思いますが、春に小木港の東一文字堤防でサンマのような大きなサヨリがよく釣れていて、初めてサヨリを釣る仕掛けを買ったのですが、どういうわけかそれ以来、サヨリが姿を見せなくなりました。

　サヨリは群れで泳いでいることがほとんどなのですが、私が子どもの頃に見ていた大きなサヨリは海面を１匹で泳いでいて、それを針先が３つある引っ掛け針で釣り上げるのが決まった方法でした。

　自分で釣り上げたサヨリを食べた記憶はないのですが、焼いたサヨリはハラワタに苦味があり、好きな食べ物ではありませんでした。ハラワタが入ったまま干物にするのがほとんどだったように思います。刺し身は全般に好きではなかったです。


