#+TITLE: "深澤諭史弁護士のリツイート→刑裁サイ太のタイムライン→八日目の蝉→葛城事件というルート"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-14 21:01:44 +0900
FILE_NAME: 2019-08-14-210144_深澤諭史弁護士のリツイート→刑裁サイ太のタイムライン→八日目の蝉→葛城事件というルート.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 平成3年11月当時の状況  深澤諭史弁護士 刑裁サイ太 八日目の蝉 かつらぎ農協 丸一運輸 被告発人東渡好信
記事タイトル名の文字数：43　保存ファイル名の文字数：65

* 深澤諭史弁護士のリツイート→刑裁サイ太のタイムライン→八日目の蝉→葛城事件というルート
  :LOGBOOK:
  CLOCK: [2019-08-15 木 06:38]
  CLOCK: [2019-08-14 水 21:04]--[2019-08-14 水 21:49] =>  0:45
  :END:

＞＞＞2019-08-14（水曜日）21：04＿［これからの記述範囲の開始時刻］＞＞＞

　NHKドラマと映画の「八日目の蝉」については「観音寺橋」のところで取り上げる予定でいました。将来的に重複する部分も出るかもしれませんが、視点を変えて検証するのもよいことかと思います。

　このあとスクリーンショットの記録と登録済みのまとめ記事で経過を辿る予定ですが、夕方になって深澤諭史弁護士のタイムラインを見て、そこで気になる刑裁サイ太のツイートをリツイートとして見て、刑裁サイ太のタイムラインを見ていくことで、八日目の蝉が強く脳裏に去来しました。

　あらためて八日目の蝉について調べたのですが、そこで「葛城事件」という映画のことが出てきました。俳優の三浦友和が父親役で、事件の発生場所が和歌山県のかつらぎ町付近と思っていたところ、どうやら葛城というのは映画のドラマの家族の名前のようでした。

　和歌山県のかつらぎ町というのは、平成４年の傷害・準強姦被告事件に関わりがあります。平成３年の中頃からだったと思いますが、平成４年の１月の終わりか長くて２月の中頃にかけて、集中的に仕事に行った場所だったからです。

　それも被告発人東渡好信が取り持ったという石川県七尾市の丸一運輸の仕事の１つでした。これも裁判所や金沢地方検察庁に提出した書面の記録では集中的な記述を繰り返したことですが、ネットでの情報公開としては確認はしていないもののそれほど力点はないかもしれません。

　和歌山県かつらぎ町からの仕事というのは、かつらぎ農協だったと思うのですが、出荷場からミカンを積んでくるもので、１月の中頃にはほとんどがイヨカンに変わっていたとも思います。ミカンは金沢市場輸送で長崎県や福岡県から積んでくる仕事をしていましたが、終わりが早いとも感じていました。

　まだネットでは記述がないかもしれないので、先に記述をしておきますが、私が初めて和歌山県かつらぎ町に行ったのは、昭和６０年の１月か２月のことで、免許停止の関係で中西運輸商を退社することも決まっていたかもしれません。

　その時だけは和歌山市内からかつらぎ町に向かいました。着いてから荷主と大いにもめたのですが、それは積載の重量オーバーがあったからです。私はそこで重量オーバーで警察に捕まれば免許取り消しという危機感を強く持っていたので、会社のことはお構いなしに荷主と衝突しました。

　結局どうなったのか余り憶えていないのですが、荷主と積み荷のことであれほどもめたことのなかったので、強く印象に残っています。また、長男が生まれることもわかっていた時期だったと思います。少なくとも重量オーバーで警察に捕まることはありませんでした。

　市場急配センターではちょうど平成３年の１１月の半ば過ぎから和歌山県かつらぎ町にミカンを積みに行くようになりました。荷降ろし先は石川県の七尾市で、小松市での荷降ろしも毎回あったかもしれません。手積みの手降ろしの仕事で他の運転手が嫌がっていたので、集中的にまわってきました。

　行き荷はほとんどが金沢の市場の近くからの馬鈴薯メークインで、北海道から船のコンテナで金沢港に運ばれてきたものと聞いていました。昭和５９年当時のバナナセンターの横に馬鈴薯の倉庫はありました。このバナナセンターは平成３年当時に新しくなり場所も少し離れています。

　馬鈴薯やメークインの行き先は、ほとんどが名古屋北部市場、大阪本場市場、大阪北部市場でした。例外で１，２回、名古屋本場市場、大阪府高槻市の市場に行ったことがありました。高槻は市場急配センターでは１回だけだったと思いますが、とても印象にのこる運行となっています。

　この馬鈴薯やメークインの運送というのは、私は昭和５８年の春頃に、小林運送の長距離助手としても経験していました。ほとんどの行き先が名古屋だったと思いますが、大阪の本場市場にも一度行ったことがあり、荷物のことは記憶にないですが、とても珍しい運行だと聞かされました。

　この小林運送についても、金沢地方裁判所や金沢地方検察庁に提出済みの書面には詳しく繰り返しで記述をしていると思いますが、平成４年になってから小林運送の専務と被告発人松平日出男の関係で、小林運送の仕事を請け負うようになり、愛知県内から野菜を運びました。

　この小林運送の仕事は他の運転手に人気があったらしく、私に回ってきたのは２回だけかもしれません。１回は、豊橋市からの午前中の野菜の運送、２回目は渥美半島の先端付近からのトマトなどの運送でした。このときのトマトは小松市の市場でも荷降ろしをしたと記憶にあります。

　時計を見ると２１時４５分です。１２日の夜だったと思いますが、夕食が遅くなって日付の変わった２時過ぎとかになって、金ちゃんヌードルのカップ麺１つで済ませたのですが、起きてから急に体重が増えたような感覚で、腰も痛くなりました。

　いったん中断をして夕食を済ませたいと思います。Aコープ能都店で久しぶりに見かけた若狭の焼きサバを買ってきたのですが、手付かずで３切れの入った明太子も今日が賞味期限となっています。消費期限ではないので明日も火を通して食べようとは考えています。

＜＜＜2019-08-14（水曜日）21：49＿［これまでの記述範囲の終了時刻］＜＜＜

＞＞＞2019-08-15（木曜日）06：38＿［これからの記述範囲の開始時刻］＞＞＞

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-15 06:55／2019-08-14 23:19 URL： https://twitter.com/kk_hirono/status/1161758314373320704 https://twitter.com/s_hirono/status/1161643454989926401
&twitter(1161758314373320704){theme:light}
> 2019-08-14-230401_深澤諭史さんがリツイート玉響@Ilove122717·8月13日実際にこんな声をあげる父親もいる子供の顔写真をデカデカと載せる子供の写真を焼いているのを載.jpg https://t.co/5JKOTg4xsU
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-15 06:55／2019-08-14 21:04 URL： https://twitter.com/kk_hirono/status/1161758331301531648 https://twitter.com/s_hirono/status/1161609542360166400
&twitter(1161758331301531648){theme:light}
> 2019-08-14-200351_サイ太@uwaaaa·8月11日今回のブースです。新刊は余裕がありますが、旧刊は出てるだけです。おはやめに。.jpg https://t.co/Ckufg4UbTJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-15 06:55／2019-08-14 21:04 URL： https://twitter.com/kk_hirono/status/1161758361186029568 https://twitter.com/s_hirono/status/1161609467806437378
&twitter(1161758361186029568){theme:light}
> 2019-08-14-195857_サイ太さんがリツイート弁護士吉峯耕平（「カンママル」撲滅委員会）@kyoshimine·17h伊藤和子『なぜ、それが無罪なのか！？　性犯罪を軽視する日本の.jpg https://t.co/RTMScOYHkz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-15 06:56／2019-08-14 19:53 URL： https://twitter.com/kk_hirono/status/1161758394572664832 https://twitter.com/s_hirono/status/1161591750059651072
&twitter(1161758394572664832){theme:light}
> 2019-08-14-195219_深澤諭史さんがリツイートサイ太@uwaaaa·5hどんなに分かりやすく法律情報をツイートしてもほとんど伸びず、「知り合いが頼んだ弁護士の話なんだけど」みた.jpg https://t.co/6ZAFlVm4is
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-15 06:56／2019-08-14 19:53 URL： https://twitter.com/kk_hirono/status/1161758440219279360 https://twitter.com/s_hirono/status/1161591677145870338
&twitter(1161758440219279360){theme:light}
> 2019-08-14-195042_深澤諭史さんがリツイートサイ太@uwaaaa·5hどんなに正確な情報をホームページやブログに書いても依頼者には響かず、「国選は起訴後から」みたいな情報を書.jpg https://t.co/IyZvME9k8E
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-15 06:56／2019-08-14 19:53 URL： https://twitter.com/kk_hirono/status/1161758479494737920 https://twitter.com/s_hirono/status/1161591604420833280
&twitter(1161758479494737920){theme:light}
> 2019-08-14-194939_深澤諭史さんがリツイートサイ太@uwaaaa·5hんで，そういうことを言うと，「ちゃんとやってる弁護士側の努力が足りない」とか言われるんだけど，努力でなん.jpg https://t.co/oGYwuU7aaz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-15 06:56／2019-08-14 19:52 URL： https://twitter.com/kk_hirono/status/1161758497333080064 https://twitter.com/s_hirono/status/1161591531502854144
&twitter(1161758497333080064){theme:light}
> 2019-08-14-181342_深澤諭史さんがリツイートうの字@un_co_the2nd·18hヒューマンライツナウ「なぜそれが無罪なのか？！性犯罪を軽視する日本の司法」.jpg https://t.co/Ym0RL3VMuc
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-15 06:56／2019-08-14 19:52 URL： https://twitter.com/kk_hirono/status/1161758582817189888 https://twitter.com/s_hirono/status/1161591458471612416
&twitter(1161758582817189888){theme:light}
> 2019-08-14-181226_深澤諭史さんがリツイートみみずく@ahoaho1818·17h深澤先生ご出演.jpg https://t.co/Y4m4k4O0sz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-15 06:56／2019-08-14 18:12 URL： https://twitter.com/kk_hirono/status/1161758606087163904 https://twitter.com/s_hirono/status/1161566370103828480
&twitter(1161758606087163904){theme:light}
> 2019-08-14-180954_反日疑惑でクレーム殺到、“テレビに出ちゃいけない芸人”に…「8。6秒バズーカー」が語るデマの“真実と悪夢”　｜　AbemaTIMES.jpg https://t.co/pDybJBpsVn
◁◁◁
<hr />

```
[link:] 2019年08月14日19時51分の登録： ＼サイ太　@uwaaaa＼どんなに正確な情報をホームページやブログに書いても依頼者には響かず、「国選は起訴後から」みたいな情報を書く事務所や非弁業者が跋扈する http://hirono2014sk.blogspot.com/2019/08/uwaaaa_82.html
[link:] 2019年08月14日19時52分の登録： ＼サイ太　@uwaaaa＼どんなに分かりやすく法律情報をツイートしてもほとんど伸びず、「知り合いが頼んだ弁護士の話なんだけど」みたいな誤情報が大拡散する。 http://hirono2014sk.blogspot.com/2019/08/uwaaaa_67.html
```

　時間を開けてしまったこともありますが、なぜ刑裁サイ太のタイムラインを見ていて、強く「八日目の蝉」のことが頭に浮かんだのか、正直よくわかりませんでした。

　どちらかといえば、深澤諭史弁護士のタイムラインにその要素を感じたのですが、刑裁サイ太と深澤諭史弁護士の間で強い共鳴というかハーモニーのようなものを感じていました。

▶ ツイート％uwaaaa（サイ太）％2019/08/14 14:10％ https://twitter.com/uwaaaa/status/1161505471867625472
&twitter(1161505471867625472){theme:light}
> どんなに正確な情報をホームページやブログに書いても依頼者には響かず、「国選は起訴後から」みたいな情報を書く事務所や非弁業者が跋扈する  
▶

▶ ツイート％uwaaaa（サイ太）％2019/08/14 14:07％ https://twitter.com/uwaaaa/status/1161504537091420160
&twitter(1161504537091420160){theme:light}
> どんなに分かりやすく法律情報をツイートしてもほとんど伸びず、「知り合いが頼んだ弁護士の話なんだけど」みたいな誤情報が大拡散する。 https://t.co/4J2LcrOcpe  
▶

▶ ツイート％uwaaaa（サイ太）％2019/08/11 14:33％ https://twitter.com/uwaaaa/status/1160424025706790912
&twitter(1160424025706790912){theme:light}
> 旧刊はいつも大量に余るので今回はあえて増刷しなかったのですが、思いの外、旧刊をお求めになる方がおられたため、１２時過ぎに完売してしまい、お手にできなかった方たちが多くおられました。見込みが甘く申し訳ありませんでした。総集編はコミケ限定としているので、今後も増刷をしていきます。  
▶

　コミケ関係のツイートやリツイートが多かったことも思い出しました。例年、大嘘判例というような同人誌を販売しているとのことで、今年は特に売上が良かった様子で、喜びのツイートが丁重な感謝の言葉とともにタイムラインに散見されていました。

　さきほどスクリーンショットの記録を見たとき気が付かなかったのですが、刑裁サイ太のタイムラインで吉峯耕平弁護士のツイートのリツイートがあって、そこに伊藤和子弁護士のことを性犯罪の本の出版のことで、呆れ果てると酷評していました。

▶ ツイート％kyoshimine（弁護士 吉峯耕平（「カンママル」撲滅委員会））％2019/08/14 02:31％ https://twitter.com/kyoshimine/status/1161329318347169792
&twitter(1161329318347169792){theme:light}
> 伊藤和子『なぜ、それが無罪なのか！？　性犯罪を軽視する日本の司法』（ディスカバリー携書）
> @kazukoito_law
> 
> まだ読んでる途中だけど、久留米支部の準強制わいせつ無罪事件（スノボサークルの事案）を、ミスリーディングな第一… https://t.co/wfWQcvVHTU  
▶

　伊藤和子弁護士については、余り取り上げていないと思いますが、注目の弁護士の一人で、少女漫画の作家のようなイメージがあります。女性の救済や権利のために闘う姿勢を強く感じる女性弁護士でもあるのですが、それが八日目の蝉の物語性につながるパワーを感じたのかもしれません。

　吉峯耕平弁護士は生真面目すぎるところも感じる正統派の弁護士という印象があります。実はそれほどツイートも読み込んでいないので詳しい人柄はまだわかっていないのですが、それ故に他の弁護士と衝突をしたり、批判的な意見を受けることもあるようです。

　比較的最近だったと思いますが、吉峯耕平弁護士が重度の障害を持ち権利のために闘ったある弁護士の息子だと知りました。以前、探偵物のアニメだったと思いますが「じっちゃんの名にかけて」が流行語になっていたことがあり、それに近い物語性を感じていました。

　個人的にはそれ以上に印象的で根深い問題性を感じていたのが、吉峯耕平弁護士が藤井美濃加茂市長事件の上告審の弁護団に加わり、その弁護団会議の様子がYouTubeにあがっていました。

　そこには元裁判官で著名な弁護士もいて、最高裁の調査官を長く務めたというような話があって、いろいろと考えさせられました。自身の最高裁での上告審、再審請求の特別抗告の経験などを踏まえた上でのことです。

　スクリーンショットを作成しました。そこにもありますが、吉峯耕平弁護士のTwitterアカウントのアイコンは特徴的なものです。私が見てきた範囲でずっと同じものですが、ミカンにマジックでメガネ親父の顔を落書きしたようなものです。

　プロフィールの名前より印象的で目立つものでしたが、PC遠隔操作事件の頃、それに関連したツイートを見かけることが多く、プログラマーの知識や経験があるようにも感じていました。お顔もYouTube動画などで見かけてきましたが、若手医師のイメージが強いぐらいで頭も良さそうでした。

　深澤諭史弁護士、刑裁サイ太、伊藤和子弁護士、吉峯耕平弁護士に共通しているのですが、漫画をドラマ化したようなイメージが強く、昨夜は刑裁サイ太のタイムラインでこれまでにないぐらいそれを強く感じて、「八日目の蝉」について今一度調べることになりました。

　映画の方だったと思いますが、八日目の蝉の批評のようなページがあって、ざっとみたところ８０％ぐらいの高評価でありながら、賛否や好みはかなり極端に分かれることもあるようでした。その批評の中に「葛城事件」という映画のことが出てきました。

　天城山の心中事件のように、実際に起こった事件のことが頭に浮かんだのですが、刑事事件としては見かけたことのない事件名で、知らない事件に出会ったのかと思ったのですが、調べると葛城というのは三浦友和が演じる父親の名前のようでした。

　解説したページには、２つの重大事件がモチーフになったとあり、池田小の児童無差別殺傷事件と茨城県の無差別殺傷事件でした。死刑になるために起こしたり、死刑の執行を強く望んでいたとされる特異な事件でした。茨城の事件も家族関係を含め割と詳細な情報を以前読んだことがありました。

　上記２つの重大事件の加害者は共通して狂ったような凶暴性を感じましたが、やったことは同じ無差別殺傷事件でも、逮捕後の言動がずいぶん違うと思うのが、秋葉原無差別殺傷事件の犯人で、今は死刑囚になっているのではと思います。

　前にも書いていると思いますが、その秋葉原無差別殺傷事件の犯人の兄弟が将来を悲観し自殺したという話があって、それを私は、いつのまにか復活していた市川寛弁護士のTwitterタイムラインで知り、一夜の束の間のように、速攻でブロックされていたのも衝撃的でした。

　秋葉原無差別殺傷事件で思い出すのは、同じ月にモトケンこと矢部善朗弁護士（京都弁護士会）のブログのコメント欄から書き込み禁止で締め出しを受けたことです。６月だったと記憶しますし、事件の年月日を調べると、モトケンこと矢部善朗弁護士（京都弁護士会）のブログのことも確認できます。

　モトケンこと矢部善朗弁護士（京都弁護士会）のブログについては、情報を調べるのも月日が経ちすぎているので困難もあるかと思いますが、SNSが普及する前で、ネット上の情報も今ほど多くはなかった状況だったので、その影響は大きく、今でも影響を受けているように感じています。

　「葛城事件」という映画の内容についてはかいつまんでみたところなのですが、ごく普通の家庭がふとしたことで息子が死刑囚になる大事件を起こしかねない、というようなことが書いてありました。私もずっと気にかけてきたのは平成３年から会っていない２人の息子のことです。

　昨夜は１９時過ぎにAコープ能都店まで買い物に出掛けたのですが、出かける前、テレビに芸能人の水泳大会のような映像があって、なぜかそこに三浦友和の妻である山口百恵の「イミテーション・ゴールド」が流れていました。

　久しぶりに聴いた曲ですっかり忘れていたのですが、歌唱力というより歌の表現力がすごいというか、他には見ないように感じました。深澤諭史弁護士や刑裁サイ太の表現力もそれとは全く異質なものですが、目を見張るものを感じています。昔はなかった気もします。

▶ ツイート％fukazawas（深澤諭史）％2019/08/14 18:40％ https://twitter.com/fukazawas/status/1161573358560919552
&twitter(1161573358560919552){theme:light}
> コスプレイヤーを無断撮影することと法的責任 - 弁護士 深澤諭史のブログ https://t.co/aOzryouwZp
> （・∀・）なお，年１回くらいはコスプレしている者。
> （；＾ω＾）いや，あれはコスプレじゃないと思うお。  
▶

　確認すると昨夜１８時４０分のツイートですが、買い物から戻った後に目にしたように思います。紹介している深澤諭史弁護士のブログ記事の内容ですが、一言で言って圧倒されました。モトケンこと矢部善朗弁護士（京都弁護士会）の安全ピンにも共通したものを感じました。

　安全ピンについてはすでに必要な範囲で取り上げていると思います。もっとまとめたかたちにしておけばよかったとは思いますが、現時点でそれほどの重要性も感じてはおらず、Twilogで調べて確認しやすいかたちにはなっているかと思います。

