#+TITLE: "参考資料／弁護士業界の現状／弁護士の事件／寺に寄付予定だった1億6千万円を横領した弁護士と、外科医の無罪判決を得た高野隆弁護士、他の弁護士の反応"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-02-23 14:55:30 +0900
FILE_NAME: 2019-02-23-145530_寺に寄付予定だった1億6千万円を横領した弁護士と、外科医の無罪判決を得た高野隆弁護士、他の弁護士の反応.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  高野隆弁護士 ツイートのまとめ記事 弁護士の事件 横領 報道
記事タイトル名の文字数：72　保存ファイル名の文字数：73

#contents

* 医療現場における透析患者を増やすという話を、テレビが堂々と陰謀論を流し、信頼性がなくなっていく、テレビ業界の偉いさんはどう考えているのか、というモトケンこと矢部善朗弁護士（京都弁護士会）
  :LOGBOOK:
  CLOCK: [2019-02-23 土 15:40]--[2019-02-23 土 17:41] =>  2:01
  :END:

＞＞＞2019-02-23（土曜日）15：40＿［これからの記述範囲の開始時刻］＞＞＞

　台所から戻ったのが14時20分ころでした。洗い物はまだ済ませていないですが少なかったです。Aコープ能都店で一昨日辺りに買ったパック入りのサバの塩麹漬けをフライパンのクッキングシートで焼いて食べたのですが、これが期待以上に美味かったです。

　石巻の金華サバとなっていたので期待はしていました。予想外だったのは全然塩辛くなかったことです。塩麹漬けというのも塩漬けのようなイメージがあったので、ずいぶん辛いものを想定していました。豚肉のものは過去に買って食べたことがありますが、ちょっと記憶にないです。

　前回はどんたく宇出津店で買ってきたノルウェー産のサバの干物を食べましたが、フィレーだと思いますが、これが思いの外、塩辛かったです。数年前ほどではないですが、ノルウェー産のサバフィレーは、けっこう脂にくせがあって、くどく感じることがありました。

　生臭さが残るのは火加減にもあると思いますが、最近、フライパンで使うようになったクッキングシートはかなりのすぐれものです。いい感じに火が通り、失敗しにくいと思います。

　予定では、寺の寄付金を着服した元弁護士のことか、高野隆弁護士に対するTwitterの弁護士らの反応をすぐに取り上げる予定だったのですが、台所に行く前に読んでいたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを読み返し、２つ前のリツイートを見ると、予定が変わりました。

　そのモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは15時54分という現時点でもモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインの最新ツイートとなっており、4時間前と表示されています。次のツイートです。

▶ ツイート％motoken_tw（モトケン）％2019/02/23 11:48％ https://twitter.com/motoken_tw/status/1099138919696748545
&twitter(1099138919696748545){theme:light}
> 今日のTLに、テレビが堂々と陰謀論を真実だとして（少なくとも真実であるかのような体裁で）流している（みたいな）スクショが流れてきたが、そういうことをするとますますテレビ全体の信頼性がなくなっていくと思うんだけどな。テレビ局やテレビ業界の偉いさんはどう考えているのかな？  
▶

　1つ手前は北周士弁護士のツイートのリツイートとなっており、そのもう１つ前のツイートを見たところ、引用されたツイートに、それらしい文章とサムネイルの画像がありました。次のリツイートになります。

▷ リツイート→motoken_tw（モトケン）＞noooooooorth（ノースライム(50倍)）｜2019/02/23 11:32／2019/02/23 11:27｜https://twitter.com/motoken_tw/status/1099134891956944896 ／ https://twitter.com/noooooooorth/status/1099133636845006848
&twitter(1099134891956944896){theme:light}
> RT @noooooooorth: 弁護士たるもの多少困難な事件であっても依頼者が望むのであれば頭をこねくり回して法律構成を考えるものだと思う。が、そのリスクを依頼者に説明しないのは依頼者に対して誠実ではないのではないか。何でもイエスという事がイコール依頼者の利益になるわけでは…  

▷ リツイート→motoken_tw（モトケン）＞jpnlvnpn（Marilyn）｜2019/02/23 11:23／2019/02/22 17:36｜https://twitter.com/motoken_tw/status/1099132505343455233 ／ https://twitter.com/jpnlvnpn/status/1098864078552936448
&twitter(1099132505343455233){theme:light}
> RT @jpnlvnpn: アホちゃうか。何なのこの陰謀論。
> 本当、他のニュースの信憑性まで疑われるからやめなさいよ。この人医師免許持ってないじゃん。3.11から許せないとは思ってたけど…
> 反ワクチンとどうレベルが違うのよ。昨日の鳩山と同レベル。医療現場を馬鹿にするにもほどがあ…  

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のリツイートでURLを引用されているのが次のツイートになります。

▶ ツイート％take_off_dress（DAPPI）％2019/02/22 15:54％ https://twitter.com/take_off_dress/status/1098838297860702208
&twitter(1098838297860702208){theme:light}
> 武田邦彦「腎臓病の技術は向上してるが昔は10万人だった透析患者が今は40万人。これは増えたのじゃなく患者にある薬を飲ませると段々と透析に追いやる薬があり、透析の機械を売るため。これは中国じゃなく日本の話。現場の医者は努力してるが上… https://t.co/bMCwZowtcp  
▶

　文字数の関係で投稿されているのかブラウザで告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のタイムラインを確認したところ、北周士弁護士のツイートが表示されていました。少し遅れて、そういえばと思ったのですが、ブロックされていないようです。

　モトケンこと矢部善朗弁護士（京都弁護士会）の陰謀論に対するこだわりというのもずいぶんと前から目にしてきたものです。何度かまとめ記事も作成していたように思います。


```
[link:] 2017年10月27日22時24分の登録： REGEXP：”陰謀論”／モトケン（@motoken_tw）の検索（2010-05-24 00:11〜2017-10-18 13:25／2017年10月27日22時24分の記録68件） http://hirono2014sk.blogspot.com/2017/10/regexpmotokentw2010-05-24-00112017-10.html
[link:] 2018年02月01日23時52分の登録： ＼モトケン　@motoken_tw＼安倍総理には批判されるべき言動がごまんとあるんだから、批判するのにわざわざ陰謀論を持ち出す必要はないだろうに。 http://hirono2014sk.blogspot.com/2018/02/motokentw_73.html
[link:] 2018年07月03日20時13分の登録： ＼モトケン　@motoken_tw＼安倍政権陰謀論に矮小化してしまっているから、詩織さん以外の（詩織さんを含む）多数の被害者の保護の議論が深まらない。 逮捕状不執行の問題 http://hirono2014sk.blogspot.com/2018/07/motokentw_3.html
```

　２，３あると思ったのですが、まとめ記事は１つだけでした。2017年10月27日の記録68件となっています。このあと最新状態で、新たに同じ「陰謀論」をキーワードにしたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートのまとめ記事を作成します。すでにデータベースは更新済みです。

[link:] 2019年02月23日16時25分の登録： REGEXP：”大野病院”／モトケン（@motoken_tw）の検索（2010-09-09〜2019-02-21／2019年02月23日16時25分の記録26件） http://hirono2014sk.blogspot.com/2019/02/regexpmotokentw2010-09-092019-02.html

[link:] 2019年02月23日16時25分の登録： REGEXP：”陰謀論”／モトケン（@motoken_tw）の検索（2010-05-24〜2019-02-23／2019年02月23日16時25分の記録94件） http://hirono2014sk.blogspot.com/2019/02/regexpmotokentw2010-05-242019-02.html

　コマンド履歴を遡ると、「大野病院」をキーワードにしたコマンドの実行が出てきたので、そちらも最新のまとめ記事として作成しておきました。「陰謀論」の方は94件と、前回の68件よりだいぶん増えています。以前ほど見かけなくなったとは思っていたので、少し意外でした。

　2,3日前も、「大野病院事件」について、検察が十分な捜査をせず、見込みで無理な起訴をしたため、医療業界に大きな不安が広がり、産科医のなり手が少なくなって、社会に深刻な悪影響を与えたというツイートを見かけました。ツイートだったと思いますが、あまり良く思い出せません。

　これも高野隆弁護士が無罪判決を勝ちとった外科医のわいせつ事件の無罪判決に関係づけた声でした。

　人工透析については、たぶん長谷川という元テレビ関係者の発言が大炎上したことがあり、その人はテレビ番組の降板もさせられたようです。当時１つだけ見ていたのは、日曜日の16時あたりからの上沼恵美子が司会をするバラエティのような情報番組でした。

　現在もやっているのかもしれないですが、もうずっと長く見たことはないです。2017年の秋だったように思います。私がスマホでポケモンGOを始めた頃でもありました。人に人工透析について話を聞く機会もありました。毎日、入浴施設に入浴に来ているという患者の話でした。

　それまでも人工透析という言葉は聞いていましたが、想像していたよりずっと深刻で負担が大きいと感じました。毎日、長時間、入浴する必要があるという話も聞いたように思います。なお、患者本人の話ではありませんでした。

　たぶん、Googleで「長谷川　人工透析」と検索をすれば、その情報が出てくると思います。

[link:] » 長谷川 人工透析 - Google 検索 https://t.co/lE623IjB9F

<hr />
[link:] » 長谷川豊の「自業自得の透析患者を殺せ」という主張に変化なし。「8割の女はハエ」「60歳以上は選挙権剥奪」発言も - wezzy｜ウェジー https://t.co/nzs9tiUPdv

<hr />
[link:] » 「人工透析患者は殺せ」という長谷川豊のこれまでの暴言 - NAVER まとめ https://t.co/15sC6IoAqu

<hr />
[link:] » 長谷川豊アナの「人工透析患者を殺せ」発言に上杉隆、茂木健一郎が痛烈反論！ | アサ芸プラス https://t.co/h020kxHOU9

<hr />

　最後の記事は、日付が2016年10月3日となっています。レギュラー番組を降板することになったとありますが、ニュースリアルFRIDAY（テレビ大阪）、というのは全く聞いたことのない番組名です。

　私の記憶では、問題が炎上化する少し前に、さきほどの日曜日の16時ころに上沼恵美子の番組で姿を見ていました。それからすぐに姿を見なくなったので、その時点で降板となっていたものと思われます。

```
フリーの長谷川豊アナウンサー（４１）が１日、自身の公式ブログで、読売テレビのバラエティー番組「上沼・高田のクギズケ！」（日曜午前１１時４０分）のレギュラーの降板とＬＩＮＥ社の言論フォーム「ＢＬＯＧＯＳ」のライターから外れることを報告した。

　「一つは毎週レギュラー出演をしておりました、読売テレビの人気番組『上沼。高田のクギズケ！』（原文ママ）ですが、昨日読売テレビさんよりお電話がありまして、降板を伝えられました。テレビ大阪の降板を受けてのものなのだろうと推察します」と記し、２日の放送からは出演しないことを明らかにした。

　読売テレビ・総合広報部によると「長谷川氏のブログ、およびその後の患者団体による抗議への対応などから、総合的に判断した」という。

［source：］【長谷川豊アナ降板】読売テレビ「上沼・高田のクギズケ！」も降板　ブログ「人工透析患者に実費負担させよ」に批判殺到　「大切な仕事、最後に迷惑かけ…」（1/2ページ） - 産経ニュース https://www.sankei.com/premium/news/161001/prm1610010041-n1.html
```

　やはり2016年の10月だったようです。人工透析の具体的な話は、七尾市から戻りに中島町の入浴施設に入ったときに聞きました。その入浴施設に入ったのはそれが最初で最後だと思います。その時点で1年前のことを思い出し、当時の最近のことのように記憶していたようです。

　七尾市の和倉温泉でもポケモンGOをやっていたことをよく覚えているので、2016年ではなく2017年の秋だったことは、まず間違いないと思います。

　今回はこれまでデータベースに登録済みのモトケンこと矢部善朗弁護士（京都弁護士会）のツイートのみを対象にしますが、「長谷川豊」をキーワードにまとめ記事を作成しておきます。そういえば、ここ半年は、一度も名前をネットで見かけていない気がします。

[link:] 2019年02月23日17時01分の登録： REGEXP：”長谷川豊”／モトケン（@motoken_tw）の検索（2015-12-01〜2017-11-21／2019年02月23日17時01分の記録101件） http://hirono2014sk.blogspot.com/2019/02/regexpmotokentw2015-12-012017-11.html

　最後の101件目はリツイートでしたが、そちらも2017年11月21日がモトケンこと矢部善朗弁護士（京都弁護士会）のリツイートの時刻です。1つ前の100件目で、2017年11月17日となっているモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを次にご紹介します。

```
このページ内位置のURL：
奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”長谷川豊”／モトケン（@motoken_tw）の検索（2015-12-01〜2017-11-21／2019年02月23日17時01分の記録101件） http：//hirono2014sk.blogspot.com/2019/02/regexpmotokentw2015-12-012017-11.html#p100
motoken_tw（モトケン）のプロフィール情報へのリンク 100件目 
▶（100／101） TW motoken_tw（モトケン） 日時：2017-11-17 23：59：00 +0900 URL： https：//twitter.com/motoken_tw/status/931537174394048512
{% tweet 931537174394048512 %}
> いかにも長谷川豊が言いそうなツイートだ。自分と重ね合わせているな。 https：//t.co/8lSSMq0x1q

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”長谷川豊”／モトケン（@motoken_tw）の検索（2015-12-01〜2017-11-21／2019年02月23日17時01分の記録101件） http://hirono2014sk.blogspot.com/2019/02/regexpmotokentw2015-12-012017-11.html#p98
```

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートには、長谷川豊氏本人と思われるアカウントのツイートがURLとして引用されており、ツイートの内容が表示されているので、アカウント自体は現在も存在しているようです。

　次が長谷川豊氏のタイムラインで最新のツイートとなっていますが、46分前として表示されています。同じくネットやツイートでは、炎上中のような情報でたまに見かける作家の百田尚樹氏のツイートのURLを引用しているようです。一緒にご紹介しておきます。

▶ ツイート％y___hasegawa（長谷川 豊）％2019/02/23 16:37％ https://twitter.com/y___hasegawa/status/1099211511782764544
&twitter(1099211511782764544){theme:light}
> そうなんだよなぁ…
> これ…
> 一言で言うと「酷い」んだよ。
> 玉木さん、周りに助言してくれる人、いないのかなぁ…。
> 多分、今以上に支持率下がるかと思う。シリーズ化させてどんどん金を取られるヤツなんだけど…これ、広告代理店が酷いよ。 https://t.co/QY6LdHToTK  
▶

▶ ツイート％hyakutanaoki（百田尚樹）％2019/02/23 12:50％ https://twitter.com/hyakutanaoki/status/1099154444569141248
&twitter(1099154444569141248){theme:light}
> 放送作家の立場からひとこと言わせてもらうと、このVTRの台本も演出もお話にならないくらいひどい！
> しかし、作家もディレクターも、「これでやれ！」と指示されたのだろう。気の毒としか言いようがない。 https://t.co/MeTOgdClwv  
▶

　ちょっと奇遇ですが、上記の百田尚樹氏のツイートは、国民民主党のツイートのURLを引用しており、サムネイルで表示されている写真は、昨日辺り、テレビのニュース番組かなにかで、たぶん1度だけ見た、玉木氏が戦国武将に扮するショートムービーでした。

　しっかり忘れていましたが、長谷川豊氏も百田尚樹氏も口を揃えて、広告代理店やディレクターのカモにされたような話で、気の毒がっているようです。

▶ ツイート％DPFPnews（国民民主党）％2019/02/22 15:08％ https://twitter.com/DPFPnews/status/1098826745979953153
&twitter(1098826745979953153){theme:light}
> 国民民主党が2月22日に発表したショートムービーのダイジェスト版です。 https://t.co/pxowmTlX9Y  
▶

　私がテレビで見たのとは内容が違っている気がします。こちらは3人の参謀が作戦会議をしている様子で、1人は女性のようです。衣装も舞台のセットも絢爛豪華です。無駄金を使っているようにしか見えないところが痛いですが、本人らはプラスに考えての行動なのでしょう。

　玉木氏の下の名前は思い出せないですが、立憲民主党なのかとも思っていました。これを見ると国民民主党に間違いはなさそうです。これは国民民主党のみならず、野党全体にマイナス効果を与えそうに思います。これを見て、投票する気になったらどうかしている気がします。

　大事なことを書き忘れそうになっていましたが、この項目でモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを取り上げたのは、ここ最近、テレビがあえて取り上げないニュースがあると感じていた折りのことで、エントリーの趣旨とも合致するからです。タイミングはたまたまです。

＜＜＜2019-02-23（土曜日）17：41＿［これまでの記述範囲の終了時刻］＜＜＜


