#+TITLE: "参考資料／ジャーナリスト／清水潔／自著『殺人犯はそこにいる』を簡単にドラマ化にして良いなら、とっくの昔に自分でやってます。なぜそこに想いが至らないのか」と苦言"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-01-01 12:35:49 +0900
FILE_NAME: 2019-01-01-123549_自著『殺人犯はそこにいる』を簡単にドラマ化にして良いなら、とっくの昔に自分でやってます。なぜそこに想いが至らないのか」と苦言.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  清水潔 四宮隆史 桶川ストーカー殺人事件 足利事件 ジャーナリスト 江川紹子 深澤諭史弁護士 神原元弁護士 報道
記事タイトル名の文字数：79　保存ファイル名の文字数：84

#contents

* きっかけは神原元弁護士のあるツイートをみて、神原元弁護士に関するまとめ記事の作成を始めたこと
  :LOGBOOK:
  CLOCK: [2019-01-01 火 12:41]--[2019-01-01 火 13:40] =>  0:59
  :END:

＞＞＞2019-01-01（火曜日）12：41＿［これからの記述範囲の開始時刻］＞＞＞

▶ ツイート％kambara7（弁護士神原元）％2018/12/30 21:56％ https://twitter.com/kambara7/status/1079360653440147457
&twitter(1079360653440147457){theme:light}
> 自分の国も守れない無能な軍人どもに国を乗っ取られるのが無性に腹立つね。
> 
> 改憲論議の本質は一口に言えばこれに尽きる。  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-01-01 12:46／2019-01-01 11:55 URL： https://twitter.com/kk_hirono/status/1079947014102630400 https://twitter.com/s_hirono/status/1079934022959022080
&twitter(1079947014102630400){theme:light}
> 2019-01-01-104340_　弁護士神原元@kambara72000年から弁護士。武蔵小杉合同法律事務所に所属。自由法曹団常任幹事。植村隆東京弁護団事務局長。見守り弁護.jpg https://t.co/0hI7ijxMOi
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-01-01 12:47／2019-01-01 11:54 URL： https://twitter.com/kk_hirono/status/1079947281762119680 https://twitter.com/s_hirono/status/1079933897255804928
&twitter(1079947281762119680){theme:light}
> 2019-01-01-101550_弁護士神原元（@kambara7）：他国の軍隊（米軍）に頼らないと自国民を守ることができない、本当は有事に自国民を守るかどうかすら怪しい（.jpg https://t.co/wKRVRVKJcS
◁◁◁
<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-01-01 12:52／2019-01-01 12:51 URL： https://twitter.com/kk_hirono/status/1079948449330556929 https://twitter.com/s_hirono/status/1079948211404460032
&twitter(1079948449330556929){theme:light}
> 2019-01-01-125056_弁護士神原元さんのツイート_ _自分の国も守れない無能な軍人どもに国を乗っ取られるのが無性に腹立つね。 改憲論議の本質は一口に言えばこれに尽きる。_.jpg https://t.co/eKN4uDs6Hc
◁◁◁
<hr />

　ここでいう改憲論というのは、次の憲法9条のことと思われます。

```
憲法９条
（１）日本国民は、正義と秩序を基調とする国際平和を誠実に希求し、国権の発動たる戦争と、武力による威嚇又（また）は武力の行使は、国際紛争を解決する手段としては、永久にこれを放棄する。（２）前項の目的を達するため、陸海空軍その他の戦力は、これを保持しない。国の交戦権は、これを認めない。
(2014-10-09 朝日新聞 朝刊 １社会)

［source：］憲法９条とは - コトバンク https://kotobank.jp/word/%E6%86%B2%E6%B3%959%E6%9D%A1-896609
```

　さまざまな意見や議論のある問題かと思いますし、私自身、特に強い関心を持つ問題ではありません。しかし、それに絡めて「自分の国も守れない無能な軍人どもに国を乗っ取られるのが無性に腹立つね。」というのは、社会人として法律の専門家である弁護士としてどうなのかと疑問に感じました。

　私自身、数年前から「非常上告」という刑事手続を掲げていますが、その問題の本質も憲法問題と考えています。それに置き換えると、「自分らの権益を裏付ける責任と信頼を守れない無能な弁護士どもに刑事裁判を乗っ取られるのが無性に腹立つね。」てな感じに思えました。

　この神原元弁護士も大量懲戒請求の標的となり、私の知る範囲では他の弁護士にさきがけて不当懲戒請求とする、請求人らに対する損害賠償の提訴を行ったという情報を見かけています。

　そういう情報は他の弁護士らのタイムラインでツイートやリツイートとして見かけていました。数ヶ月前になるかと思います。最近はほとんど見かけていません。時期的には北周士弁護士や佐々木亮弁護士、嶋﨑量弁護士らが同様の提訴を行ったか、それに先立つ和解を呼びかけてからです。

　神原元弁護士のことは数年前から知っています。早い段階で私の３つのTwitterアカウントをすべてブロックされているかと思います。これはあとで確認しておきたいと思います。

　時刻は１３時３６分です。神原元弁護士に３つのアカウント全てがブロックされていることは確認し、記録としてのスクリーンショットも作成しました。

＜＜＜2019-01-01（火曜日）13：40＿［これまでの記述範囲の終了時刻］＜＜＜


