#+TITLE: "再審制度の制度趣旨を没却する最高裁判所の大崎事件第三次再審請求棄却決定に対し抗議する会長声明（福岡県弁護士会）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-10 10:28:39 +0900
FILE_NAME: 2019-08-10-102839_再審制度の制度趣旨を没却する最高裁判所の大崎事件第三次再審請求棄却決定に対し抗議する会長声明（福岡県弁護士会）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 再審請求 大崎事件
記事タイトル名の文字数：55　保存ファイル名の文字数：77

* 再審制度の制度趣旨を没却する最高裁判所の大崎事件第三次再審請求棄却決定に対し抗議する会長声明（福岡県弁護士会）
  :LOGBOOK:
  CLOCK: [2019-08-10 土 10:33]--[2019-08-10 土 12:27] =>  1:54
  :END:

＞＞＞2019-08-10（土曜日）10：33＿［これからの記述範囲の開始時刻］＞＞＞

　ここ何日か中断をしていました。「観音寺橋」については一休みです。この大崎事件についても前々から取り上げておきたいことが沢山あったのですが、ここに来て福岡県弁護士会の会長声明を発見しました。それも昨日の８月９日付となっていました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中） 日時：2019-08-10 10:43／2019-08-04 18:00 URL： https://twitter.com/kk_hirono/status/1160003652301414400 https://twitter.com/kk_hirono/status/1157939272105615361
&twitter(1160003652301414400){theme:light}
> 「日本の黒い霧」という短編集であったと思います。平成１１年の事件で、金沢刑務所の拘置所に入り、比較的早い段階で読んだ官本であったように思います。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kamo629782（かもん弓（鴨志田 祐美）） 日時：2019-08-10 10:45／2019-08-09 20:58 URL： https://twitter.com/kk_hirono/status/1160004116178862080 https://twitter.com/kamo629782/status/1159796121780142080
&twitter(1160004116178862080){theme:light}
> 福岡県弁護士会も，大崎最高裁決定に対する抗議声明を出しました！ \n  再審制度の制度趣旨を没却する最高裁判所の大崎事件第三次再審請求棄却決定に対し抗議する会長声明 福岡県弁護士会 https://t.co/n8oLogAvr7
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 10:45／2019-08-10 10:17 URL： https://twitter.com/kk_hirono/status/1160004309796311040 https://twitter.com/s_hirono/status/1159997098852376577
&twitter(1160004309796311040){theme:light}
> 2019-08-10-094103_福岡県弁護士会　宣言・決議・声明・計画：再審制度の制度趣旨を没却する最高裁判所の大崎事件第三次再審請求棄却決定に対し抗議する会長声明.jpg https://t.co/sMPXkmwnmm
◁◁◁
<hr />

　あらためて鴨志田裕美弁護士のツイートを確認すると、昨夜の８時５８分という投稿時刻でした。最近のTwitterは、リアルタイムに数が変わるのですが、リツイートの数が６，いいねが１１件と少ないです。たぶん変わりないと思いますが、さきほどスクリーンショットを作成しました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 10:52／2019-08-10 10:47 URL： https://twitter.com/kk_hirono/status/1160005905779322880 https://twitter.com/s_hirono/status/1160004806200553472
&twitter(1160005905779322880){theme:light}
> 2019-08-10-104737_かもん弓（鴨志田　祐美）さんはTwitterを使っています：　「福岡県弁護士会も，大崎最高裁決定に対する抗議声明を出しました！　再審制度の制度趣旨を没却す.jpg https://t.co/eyZe2sPENB
◁◁◁
<hr />

　クリックでリツイートしたユーザをみると、４件のアカウントが表示され、１つは私の告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でした。弁護士らしいアカウントは見当たりません。

　「いいね」をみると、これも１１件のうちの９件のアカウントが表示され、弁護士と確認できるアカウントは一件だけでした。なぜかリツイートはされなかったようですが、香川県観音寺市の中野俊徳弁護士でした。

```
中野 俊徳
@kanonjilawfirm
弁護士（香川県弁護士会・観音寺法律事務所・日弁連民暴委員会委員、2001年司法試験合格・56期鹿児島修習・2003年10月弁護士登録）
職場歴：福岡市（弁護士法人本店6か月）
→福岡県田川市（法人支店5年）
→秋田県能代市（公設2年4か月）
→福岡県飯塚市（5年8か月）
→香川県観音寺市（2017年4月～）
香川 観音寺市2014年7月からTwitterを利用しています
443 フォロー中
664 フォロワー


弁護士保険「Mikata/ミカタ」リーガルベストさんと弁護士大西洋一さんにフォローされています

［source：］中野 俊徳（@kanonjilawfirm）さん / Twitter https://twitter.com/kanonjilawfirm
```

　上記に現時点のプロフィール情報を引用しました。すぐに忘れてしまうことも多いのですが、「56期鹿児島修習」とあるのは、意外な情報に感じました。私は短時間で情報を詰め込むことも多く、頭に入りきれなかったり、他と混同することもあるのですが、新たな発見に感じました。

　平成１３年に司法試験合格、平成１５年１０月に弁護士登録というのは、非常にわかりやすい明朗な情報開示かと思います。このあたりに人柄や性格があらわれることもあるのかもしれません。

　３週間ほど前になりますか、司法修習の期間が段階的に短縮された具体的な情報に接しましたが、平成１３年というのは、ちょうどその期間に入っていたような気がしました。確認はしませんが、現行の１年になる前ではあったように思います。

　中野俊徳弁護士のTwitterをよくみると、２０１４年７月からの利用開始で、１．６万件のツイートと表示があるので、思っていた以上にツイートの頻度の高いアカウントだったようです。たまに思い出した時に、ブックマークからアカウントのTwitterを開くという感じでした。

　ほかに鹿児島修習として認識のあるTwitterの弁護士は向原栄大朗弁護士ですが、司法修習の期というのは記憶に残っていません。確認の必要はありますが、平成１３年というのは、大崎事件で最初に再審請求がされた年として情報を見てきたように思います。

　私の個人的な感覚では、服役中から再審請求を繰り返すケースがほとんどなのですが、この鹿児島の大崎事件に関しては、懲役１０年の出所後に、初めて再審請求を行ったという情報を繰り返し見ています。細かい情報としては佐賀県の麓刑務所で服役したということです。

　沖縄と北海道を例外にすれば、女子刑務所があるのは、西から佐賀県の麓刑務所、和歌山県の和歌山刑務所、岐阜県の笠松刑務所、そして栃木県の栃木刑務所という情報を、これまで見かけてきました。それだけ女性の刑法犯は数が少ないことの裏返しとも聞きます。

　なぜ、服役後の再審請求となったのか、これも大崎事件について気になっていたことの一つですが、理解の出来る情報には今のところ巡り合っていません。よく見かけてきたのは、仮釈放のため罪を認めるように刑務官に勧められたという話です。

　刑務所における受刑者の外部との交通も、ずいぶんと緩和されたという情報を見かけていました。と言ってもあのホリエモンこと堀江貴文氏が服役する直前の情報であったように思います。他に記憶にあるのは、私がすでにTwitterを初めていたということです。

[link:] » 堀江貴文(Takafumi Horie)(@takapon_jp)/「@hirono_hideki」の検索結果 - Twilog https://t.co/y6OojdHHkh

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜takapon_jp（堀江貴文(Takafumi Horie)） 日時：2019-08-10 11:34／2011-05-28 16:10 URL： https://twitter.com/kk_hirono/status/1160016447705235456 https://twitter.com/takapon_jp/status/74371865187057665
&twitter(1160016447705235456){theme:light}
> 平成18年施行です http://www.ron.gr.jp/law/law/kei_juke.htm QT @hirono_hideki  \n  そうなんですか。改正は知らなかったです。平成14年当時の話です。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜takapon_jp（堀江貴文(Takafumi Horie)） 日時：2019-08-10 11:34／2011-05-28 16:00 URL： https://twitter.com/kk_hirono/status/1160016495436394501 https://twitter.com/takapon_jp/status/74369466150039552
&twitter(1160016495436394501){theme:light}
> 新法制度下では知らせてくれます。それは旧監獄法の時代の話では？ QT @hirono_hideki  \n  届いても告知もされないはずです。出所時にまとめてくれるでしょう。
◁◁◁
<hr />

　記憶の片隅にあったものですが、Twilogから捜し出すことが出来ました。２０１１年５月２８日となっていますが、これはたぶんホリエモンこと堀江貴文氏が服役する前のことではなかったかと思われます。

　ホリエモンこと堀江貴文氏の服役に関しては、長野刑務所と聞いたように憶えています。私が刑務所生活の中でもとりわけ寒さの厳しい刑務所だと聞いたことがありました。暖房設備があるのは青森刑務所以北とも聞きましたが、長野は青森より記憶が下がるようなイメージもあります。

　青森刑務所の場所は確認していませんが、裁判所に近く拘置所が一緒になていると想像されるので、青森市内の中心部ではと考えています。青森市も長距離トラック運転手の仕事で行っていますが、海に近いところから平野がずいぶん広がった地形だったと印象にあります。

```
2011年4月、最高裁判所が上告棄却し、懲役2年6ヶ月の実刑判決が確定。
2011年6月20日に、長野刑務所へ収監された。

［source：］堀江貴文 - Wikipedia https://ja.wikipedia.org/wiki/%E5%A0%80%E6%B1%9F%E8%B2%B4%E6%96%87#%E5%8F%8E%E7%9B%A3%E5%BE%8C
```

　著名人なだけに情報がすぐに見つかりました。長野刑務所への収監が２０１１年６月２０日、仮釈放が２０１３年３月２７日とあります。見落としはあるかもしれないですが、ざっとみたところ未決通算関する情報はないように思いました。

　求刑が懲役４年とありますが、これは初めて知ったような気がしました。テレビで連日大きく取り上げられていたので、見聞きはしていたのだと思いますが、懲役４年というのは私の傷害・準強姦被告事件と同じ求刑なので、印象に残っていなかったのが、不思議に感じました。

　私の場合は、懲役４年の求刑で懲役４年の判決。未決勾留が長く算入されない部分もあったので、平成４年４月１日から平成９年１月１８日までの身柄の拘束、約４年１０か月でした。服役中に再審請求もやっていましたが、仮釈放の相談もなく満期出所でした。

　細かく言えば、仮面接はあったもののパロルは入らず、説明も何もありませんでした。通常はパロルという反省文のようなものの提出があったあと本面接となり、本面接の後、早ければ一月ほどで２週間の釈前教育に入るという話ではなかったかと思います。相場は３月とも聞いていた気がします。

　金沢刑務所の場合は、暴力団関係者が多かったので、仮釈放の条件に離脱届が必要となって、その離脱を勧める刑務官の呼び出しというのは実際に見かけたり、本人に話を聞くことがありました。

　そもそも仮釈放という制度が、正確なことは忘れていますが、更生保護協会というような刑務所とは違う外部の主導による手続きであり、仮釈放のことで刑務官が受刑者を呼び出したり、相談をするということは見聞きすることがなかったように思います。

　なお、私がB級の再犯刑務所である金沢刑務所に服役した平成１２年１１月から平成１３年１２月というのは、刑務所の過剰収容が社会問題としてピークとなっていた時期で、再犯刑務所においても積極的な仮釈放が行われていた時期でした。刑務官からの説明や訓示もありました。

　福井刑務所でも私は一番人数の多い２工場にいましたが、受刑者の呼び出しは他の刑務官が連れに来るもので、連れて行かれると用件を示した札が掲げられていました。多いのは、医務、面会、取り調べではなかったかと思います。

　取り調べ、というのは言葉が違っていたような気もしますが、懲罰審査にかけられる前の本人の取り調べの場合と、刑事事件における目撃者や参考人としての事情聴取の場合がありました。刑務官は警察官と同じ様な権限で、取り調べや供述調書の作成が出来るとも聞きました。

　どんなかたちであれ、刑務官と受刑者の個人的な接触というのは少なく、個別指導のようなものはほとんどなかったと思いますし、その機会というのも衆人監視のような状況下でしたので、ごくごく限られていたように思います。終わった裁判や事件のこととなるとなおさらかと思います。

　弁護士らは大崎事件で、服役中に刑務官から仮釈放のために罪を認めるように勧められたと吹聴しているように聞こえますたが、それは仮釈放の審査の面接官ではないかと思われますし、もともと否認を貫いていた受刑者に、翻意を仮釈放の条件にすることがあるのか不思議に思ってきました。

　否認を貫いた受刑者であっても仮釈放が認められたケースというのはあったように思いますし、この大崎事件以外に仮釈放の条件として確定判決で認めていなかった罪を認めるように勧められたという話は聞いたことがなく、それこそ不当な干渉や踏み絵のような拷問性を感じてしまいます。

　ともあれ、格調高らかな大崎事件に対する福岡県弁護士会の会長声明こそが、まぎれのない事実として存在する歴史的に貴重な資料と思われ、それに対する全国４万人ともいわれる弁護士らの関心の低さも、時代と現実の証明のように私には思えてなりません。

＜＜＜2019-08-10（土曜日）12：27＿［これまでの記述範囲の終了時刻］＜＜＜


