#+TITLE: "まだ最高裁はあるか？　大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない（海渡雄一弁護士）"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-14 06:37:45 +0900
FILE_NAME: 2019-08-14-063745_まだ最高裁はあるか？　大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない（海渡雄一弁護士）.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 大崎事件  海渡雄一弁護士 再審請求
記事タイトル名の文字数：56　保存ファイル名の文字数：78

* まだ最高裁はあるか？　大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない（海渡雄一弁護士）
  :LOGBOOK:
  CLOCK: [2019-08-14 水 06:39]--[2019-08-14 水 07:28] =>  0:49
  :END:

＞＞＞2019-08-14（水曜日）06：39＿［これからの記述範囲の開始時刻］＞＞＞

5688： 「たぶん、多くの法クラアカウントもそうでしょう」というモトケンこと矢部善朗弁護士、辿ると海渡雄一弁護士のツイート http://hirono-hideki.hatenablog.com/entry/2019/08/14/062735

　１つ前の記事になりますが、そちらでも海渡雄一弁護士を取り上げていました。海渡雄一弁護士の最新ツイートのまとめ記事も作成、投稿済みかと思います。前の記事で掲載し忘れていたスクリーンショットの記録も載せておこうと思います。

[link:] 2019年08月14日05時56分の登録： ＃海渡雄一　@kidkaido＃のツイート／2018-11-21_0908〜2019-08-13_0858／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年08月14日05時56分 http://hirono2014sk.blogspot.com/2019/08/kidkaido2018-11-2109082019-08.html

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-14 06:46／2019-08-14 05:40 URL： https://twitter.com/kk_hirono/status/1161393719288815617 https://twitter.com/s_hirono/status/1161377027565318144
&twitter(1161393719288815617){theme:light}
> 2019-08-14-053752_（5）　海渡雄一さんはTwitterを使っています：　「御巣鷹、遺族ら慰霊の登山　日航機墜落事故から３４年　　Twitter.jpg https://t.co/2qIOILxmkt
◁◁◁
<hr />

　海渡雄一弁護士のTwitterタイムラインでは７月１５日に大崎事件のツイートがありました。Facebookの投稿記事の紹介ツイートのようです。たぶん既読の記事かと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:49／2019-07-15 16:35 URL： https://twitter.com/kk_hirono/status/1161394432349917184 https://twitter.com/kidkaido/status/1150670246975377409
&twitter(1161394432349917184){theme:light}
> まだ最高裁はあるか？ \n  　大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない \n   \n  　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　海渡　雄一... https://t.co/Fon4nUV7rF
◁◁◁
<hr />

　返信はなくリツイートは３８件、いいねは４０件です。ツイートは２０１９年７月１５日午後４時３５分と表示されています。このツイートの投稿時刻というのはアメリカ時間で表示されることもあるので、常にそれは念頭におくように心がけています。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-14 06:54／2019-08-14 06:50 URL： https://twitter.com/kk_hirono/status/1161395639533441024 https://twitter.com/s_hirono/status/1161394617448722432
&twitter(1161395639533441024){theme:light}
> 2019-08-14-065013_（7）　海渡雄一さんはTwitterを使っています：　「まだ最高裁はあるか？　　大崎事件最高裁決定を、司法を変えていく反転攻勢の糸口としなければならない　.jpg https://t.co/qhe8HRpul1
◁◁◁
<hr />

　海渡雄一弁護士のツイートにあるFacebookの記事を開く前に、海渡雄一弁護士のTwitterを遡り、他に大崎事件に言及したものがないか先に確認しておきたいと思います。大崎事件と関係なくても、これはと思うツイートやリツイートを見かけたらリツイートして記録しておきます。

海渡雄一弁護士のツイートにあるFacebookの記事を開く前に、海渡雄一弁護士のTwitterを遡り、他に大崎事件に言及したものがないか先に確認しておきたいと思います。大崎事件と関係なくても、これはと思うツイートやリツイートを見かけたらリツイートして記録しておきます。

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 06:59／2019-07-13 13:21 URL： https://twitter.com/kk_hirono/status/1161396848323547136 https://twitter.com/kidkaido/status/1149896541257125888
&twitter(1161396848323547136){theme:light}
> 「＃新聞記者」の中で、 内調杉原に神崎の死の真相を問う吉岡記者に対して、杉原は「私は国側の人間です」と答える。 \n  吉岡ば「そんな言葉で、自分を納得させられるんですか？、#私たちこのままでいいんですか」と迫る。 \n  この私たちには、吉岡と… https://t.co/S8HsoI0oMF
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:00／2019-07-11 22:24 URL： https://twitter.com/kk_hirono/status/1161397060920152064 https://twitter.com/kidkaido/status/1149308556757229569
&twitter(1161397060920152064){theme:light}
> 河合弘之監督の映画「東電刑事裁判 動かぬ証拠と原発事故」Youtubeで公開！。 \n  東電元役員3名は事故の原因である巨大津波を予見し、津波対策工事を計画しながら、何もしませんでした。 \n  9月19日判決の日へ向けて必見の２６分間です。… https://t.co/ouWowuSiw7
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:00／2019-07-10 19:12 URL： https://twitter.com/kk_hirono/status/1161397139668267009 https://twitter.com/kidkaido/status/1148897720083501058
&twitter(1161397139668267009){theme:light}
> 先日、飯舘村の住民の皆さんのお気持ちを聞く機会がありました。 \n  村に戻ったのは、お年寄りばかり。キノコや山菜など自然の恵みを食べることもできない。村での生活は事故前とは全く違い、健康を害している住民も多いようです。 \n  安倍政権は、まる… https://t.co/IV0J7ogblv
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜brahmslover（前川喜平（右傾化を深く憂慮する一市民）） 日時：2019-08-14 07:00／2019-07-09 10:39 URL： https://twitter.com/kk_hirono/status/1161397219238375424 https://twitter.com/brahmslover/status/1148406321097531392
&twitter(1161397219238375424){theme:light}
> ウソを書いた本が売れ、ウソをつく政治家が支持される。これを放っておけるか？
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜minorucchu（ジャーナリスト　田中稔） 日時：2019-08-14 07:01／2019-07-07 11:26 URL： https://twitter.com/kk_hirono/status/1161397352030060544 https://twitter.com/minorucchu/status/1147693225123037184
&twitter(1161397352030060544){theme:light}
> 昨日、有楽町で映画『新聞記者』の河村プロデューサー、藤井監督のトークショー。河村は、政治嫌いで新聞を読まない若い世代にどう伝えられるかに苦心。その世代の32歳・藤井監督に製作を依頼。藤井は最初断ったが「政治から脱げるのは民主主義を… https://t.co/lOthjdPqQI
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:01／2019-07-08 08:52 URL： https://twitter.com/kk_hirono/status/1161397486109351936 https://twitter.com/kidkaido/status/1148017092190359552
&twitter(1161397486109351936){theme:light}
> 藤井監督　河村プロデューサー　ありがとう。 \n  日本で進む監視社会は、目に見えません。 \n  この映画は、それを可視化し、その恐怖を体感させてくれる。 \n  真実を知ることができれば、これを変えていくことができるはずだ。 https://t.co/AGU10PFJ7o
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:02／2019-07-07 22:55 URL： https://twitter.com/kk_hirono/status/1161397574873391104 https://twitter.com/kidkaido/status/1147866854536335360
&twitter(1161397574873391104){theme:light}
> 映画「新聞記者」の描くリアル日本の監視社会の絶望と希望 \n   \n  　　　　　　　　　　　　　　　　　　　　　　海渡雄一 \n   \n  映画「新聞記者」を見て... https://t.co/SJsrpzjMSv
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:02／2019-07-06 19:18 URL： https://twitter.com/kk_hirono/status/1161397615302307840 https://twitter.com/kidkaido/status/1147449648488955904
&twitter(1161397615302307840){theme:light}
> かめいしさんはGPS捜査違憲最高裁判決を勝ち取った素晴らしい刑事弁護人です。あなたの自由と平等を目指すひたむきな姿勢に拍手を送ります。必ず、当選して下さい。 https://t.co/jbHijUqypv
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜shimbunkisha（映画「新聞記者」） 日時：2019-08-14 07:02／2019-07-04 19:16 URL： https://twitter.com/kk_hirono/status/1161397657648029696 https://twitter.com/shimbunkisha/status/1146724351510642688
&twitter(1161397657648029696){theme:light}
> ◤映画評◢ \n   \n  俳優 \n  #石田純一 さん \n   \n  この映画は怖い。 \n  言いたいことが言えない世の中の異常性と緊迫感に満ちている。 \n  だからこそ多くの人に観てもらいたい、そして考えてほしい。 \n  なぜなら、これは今我々が住んでいる日本のことだから。… https://t.co/VP9z8KC4wD
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:03／2019-07-05 01:27 URL： https://twitter.com/kk_hirono/status/1161397770596470786 https://twitter.com/kidkaido/status/1146817823349465089
&twitter(1161397770596470786){theme:light}
> ＃新聞記者みた \n  内調杉原に上司神崎の死の真相を問う吉岡記者 \n  答える杉原のことば　「私は国側の人間です」 \n  返す吉岡のことば　「そんな言葉で、自分を、納得させられるんですか？」 \n  この映画が問うているのは深まる監視社会の中で、どうしたら… https://t.co/IYxhabyTeY
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:03／2019-07-04 22:37 URL： https://twitter.com/kk_hirono/status/1161397822320603138 https://twitter.com/kidkaido/status/1146775071622434816
&twitter(1161397822320603138){theme:light}
> 映画「新聞記者」見ました！ \n  とにかく面白い。 \n  日本の政治権力の醜い姿を、これだけ赤裸々に描いた映画があっただろうか？ \n  吉岡エリカ記者の真実をみつめるまっすぐの目線に心を動かされた。 \n  ためらいながら決断していく内閣情報調査室員杉浦拓… https://t.co/HsMHuUuKWJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:03／2019-06-28 20:02 URL： https://twitter.com/kk_hirono/status/1161397916847632385 https://twitter.com/kidkaido/status/1144561596791791616
&twitter(1161397916847632385){theme:light}
> 私も呼びかけ人を務める再審法改正をめざす市民の会が、「大崎事件再審を取り消した最高裁決定は、司法の正義への真っ向からの裏切りである。」とする緊急声明を公表しました。 \n  このような検察官と裁判所の暴挙をなくすために、再審開始決定に、検… https://t.co/2V9EpMEqtt
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜okaguchikii（岡ロ基ー） 日時：2019-08-14 07:03／2019-06-26 18:00 URL： https://twitter.com/kk_hirono/status/1161397981964201984 https://twitter.com/okaguchikii/status/1143806299387256832
&twitter(1161397981964201984){theme:light}
> 今の最高裁が， \n  欧米型の司法（少数者保護・他の二権との均衡抑制）ではなく、 \n  江戸時代の日本型の司法（社会秩序維持装置の一部）に変容しつつある事は， \n  「最高裁に告ぐ」で詳しく説明した通りです… https://t.co/Fm6EJ582J9
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:04／2019-06-27 18:29 URL： https://twitter.com/kk_hirono/status/1161398020551761920 https://twitter.com/kidkaido/status/1144175823001231360
&twitter(1161398020551761920){theme:light}
> 鴨志田先生の多年の献身的ご努力に心から敬意を表します。 \n  最高裁第一小法廷小池裕、池上政幸、木澤克之、山口厚、深山卓也裁判官は、鴨志田弁護士の問いに真摯に答えるべきだろう。 https://t.co/UupjNLvq5n
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:04／2019-06-15 20:03 URL： https://twitter.com/kk_hirono/status/1161398068840767488 https://twitter.com/kidkaido/status/1139850828901076993
&twitter(1161398068840767488){theme:light}
> 労働組合運動に対する共謀罪型弾圧が始まっている。 \n  今日、弁護士１１７名の共同アピールを公表しました！ https://t.co/ClfB5ZtmCa
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:04／2019-06-15 15:55 URL： https://twitter.com/kk_hirono/status/1161398104655925248 https://twitter.com/kidkaido/status/1139788503468822528
&twitter(1161398104655925248){theme:light}
> 今日15日は、共謀罪が強行成立されて２年目のくやしい記念日です。 \n  ６時から、文京区民センターで集会をします。 \n  吉岡忍さんと香山リカさんの対談があります。 \n  今のところ、共謀罪は適用されていませんが、関西で60人が逮捕された生コン支部… https://t.co/KnsOMcEhz4
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:04／2019-06-10 18:48 URL： https://twitter.com/kk_hirono/status/1161398142622810112 https://twitter.com/kidkaido/status/1138020203181137920
&twitter(1161398142622810112){theme:light}
> 日隅一雄情報流通促進賞の表彰式を12日18時15分から、日比谷図書館地下ホールで開催します。 \n  大賞は書籍「サカナとヤクザ」を著した鈴木智彦さん、奨励賞は島明美さんと上西充子さん、特別賞は元県民投票の会代表の元山仁士郎さんです。 \n  い… https://t.co/x2YCyirBre
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:04／2019-05-23 19:19 URL： https://twitter.com/kk_hirono/status/1161398269429219328 https://twitter.com/kidkaido/status/1131504993557630976
&twitter(1161398269429219328){theme:light}
> 台湾では、刑事事件について再審請求を求める弁護人は公判に提出されなかった証拠を含めて、すべての証拠の閲覧ができるそうです。日本では、裁判官が勧告しなければ、検察庁は何も開示しないのと大違い。 \n  台湾は、知らない間に人権先進国になって… https://t.co/wiWnLRXXy1
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:05／2019-04-24 13:07 URL： https://twitter.com/kk_hirono/status/1161398430746284032 https://twitter.com/kidkaido/status/1120902111988895744
&twitter(1161398430746284032){theme:light}
> テロ対策遅れ原発の停止求める声明 脱原発弁護団 | 全国のニュース | 福井新聞ONLINE https://t.co/i26urz7LZ7 \n  昨日、会見し、規制委員会に対してテロ対策のための特重施設設置期限の延期を認めないよう、声… https://t.co/fJ4LaoXiiO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜YoshihitoKAWAKA（川上資人） 日時：2019-08-14 07:06／2019-04-10 20:31 URL： https://twitter.com/kk_hirono/status/1161398529815769088 https://twitter.com/YoshihitoKAWAKA/status/1115940440438521856
&twitter(1161398529815769088){theme:light}
> 弁護士になって初めて代理人をさせてもらった事件です。裁判所は同性愛関係を認め、養子縁組は有効と判断。依頼者の方もとても喜んでいました \n  刑務所で服役中に同性愛の関係になった男性２人について、東京高等裁判所は「助け合って共に生活しよう… https://t.co/Ngq3CTOZ4K
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:06／2019-04-10 19:33 URL： https://twitter.com/kk_hirono/status/1161398647113654272 https://twitter.com/kidkaido/status/1115925731673092102
&twitter(1161398647113654272){theme:light}
> 私たちの事務所で担当してきた刑務所の国賠訴訟で、東京高裁で逆転原告勝訴判決を得ることができました。共同原告だった養子の方が亡くなっている悲しい事件でしたが、なんとか勝つことができて、本当に良かったと思います。 https://t.co/0rYTy4MgyJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:06／2019-04-10 19:25 URL： https://twitter.com/kk_hirono/status/1161398692584099840 https://twitter.com/kidkaido/status/1115923651864346625
&twitter(1161398692584099840){theme:light}
> 受刑者の同性愛認め養子縁組「有効」の判決 東京高裁 | NHKニュース   https://t.co/pgaB0t3zvE \n  東京地裁の棄却判決が東京高裁で逆転し、勝訴判決を得ることができました。 \n  受刑者の信書の自由を拡大するだけで… https://t.co/UxSJQGiHec
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:07／2019-04-07 22:53 URL： https://twitter.com/kk_hirono/status/1161398778957447170 https://twitter.com/kidkaido/status/1114889016254529538
&twitter(1161398778957447170){theme:light}
> 岡口基一裁判官著『最高裁に告ぐ』書評 \n  王様化する最高裁に対する事実と法論理による反撃 \n  　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 \n  １　分限裁判から裁判官訴追請求の対象に... https://t.co/6sOWKAuJVy
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:07／2019-03-29 21:45 URL： https://twitter.com/kk_hirono/status/1161398826147520512 https://twitter.com/kidkaido/status/1111610288707530755
&twitter(1161398826147520512){theme:light}
> 監獄人権センターが「日本の刑事拘禁と国際基準─刑事施設内医療・人質司法の問題を問う」を４月２日５時半から衆院第２議員会館で開催します。 \n  カルロス・ゴーン日産前会長の長期の勾留で問われた日本の刑事拘禁と被拘禁者の処遇のあり方について… https://t.co/d4GosFRK07
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:07／2019-03-10 15:40 URL： https://twitter.com/kk_hirono/status/1161398976622448641 https://twitter.com/kidkaido/status/1104633095813136384
&twitter(1161398976622448641){theme:light}
> 中野宏典弁護士と共同で、高松高裁平成30年11月15日の決定について「伊方原発訴訟のいま──火山巨大噴火の危険性と避難計画の不合理性を認めながら再稼働を認容」を執筆しました。 \n  負けた決定ではありますが、住民の主張を大幅に認めながら… https://t.co/sFwW8BnKNU
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:08／2019-03-09 04:14 URL： https://twitter.com/kk_hirono/status/1161399068481990657 https://twitter.com/kidkaido/status/1104098045015158784
&twitter(1161399068481990657){theme:light}
> こんなフェイク記事を書いた屋山氏もひどいけれど、こんな記事を掲載した静岡新聞も反省して欲しい。 \n   https://t.co/rKxvtN2xxR
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:08／2019-03-09 03:46 URL： https://twitter.com/kk_hirono/status/1161399106566160384 https://twitter.com/kidkaido/status/1104090931010158592
&twitter(1161399106566160384){theme:light}
> 問われているのは、ゴーン氏の人権だけでなく、私たちの人権なのだと言うことを論じました。ぜひご覧になって下さい。 https://t.co/gPGbtofUUc
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:08／2019-03-09 03:42 URL： https://twitter.com/kk_hirono/status/1161399130033291264 https://twitter.com/kidkaido/status/1104089957721792512
&twitter(1161399130033291264){theme:light}
> ゴーン事件で問われた、日本国民全体への人権侵害 - 海渡雄一｜WEBRONZA - 朝日新聞社の言論サイト https://t.co/gPGbtoxvLK  \n  国際社会から問われているのは、私たちの人権であることを論じました。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:08／2019-03-03 12:48 URL： https://twitter.com/kk_hirono/status/1161399178313863169 https://twitter.com/kidkaido/status/1102053098447486976
&twitter(1161399178313863169){theme:light}
> ツイートで戒告処分の裁判官 訴追委召喚で弁護士たちが批判 | \n   NHK \n   https://t.co/rJPI9jcwCh \n  私もこのアピールの呼びかけ人です。 \n  つぶやく自由すらない裁判官に市民の自由は守れません。 \n  ＃岡口裁判官　への… https://t.co/Lop7GeZOd9
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:09／2019-02-21 12:40 URL： https://twitter.com/kk_hirono/status/1161399344358014977 https://twitter.com/kidkaido/status/1098427116440346624
&twitter(1161399344358014977){theme:light}
> 望月さん \n  頑張って下さい。応援しています。 https://t.co/KcipMoCso5
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ISOKO_MOCHIZUKI（望月衣塑子） 日時：2019-08-14 07:09／2019-02-10 23:09 URL： https://twitter.com/kk_hirono/status/1161399408379871232 https://twitter.com/ISOKO_MOCHIZUKI/status/1094599294756085765
&twitter(1161399408379871232){theme:light}
> 安倍首相 は、#悪夢のような民主党政権 と言ったが、森友改ざんでは真面目な官僚が自殺に追い込まれ、加計疑惑では総理の友が優遇、詩織さんへの準強姦事件では逮捕状も取消。遂に統計不正でアベノミクスも偽装。どれだけの不公正と不正義、悪魔… https://t.co/d6iX4lDIkR
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:10／2019-01-20 16:30 URL： https://twitter.com/kk_hirono/status/1161399538222956544 https://twitter.com/kidkaido/status/1086888738947383296
&twitter(1161399538222956544){theme:light}
> 『映画で観る監視社会＃6：「空と風と星の詩人　尹東柱(ユン・ドンジュ)の生涯」　その2』 \n  ⇒ https://t.co/LRlHDVvPi8 #アメブロ @ameba_officialさんから 治安維持法違反の嫌疑は日本敗戦後の朝… https://t.co/s9yKkR37ik
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:10／2019-01-20 16:28 URL： https://twitter.com/kk_hirono/status/1161399580702830593 https://twitter.com/kidkaido/status/1086888202818936834
&twitter(1161399580702830593){theme:light}
> 『映画で観る監視社会＃5：「空と風と星の詩人　尹東柱(ユン・ドンジュ)の生涯」　その１』 \n  ⇒ https://t.co/dAIBJIArPD #アメブロ @ameba_officialさんから \n  韓国の素晴らしい詩人ユン・ドンジュ氏… https://t.co/nhKRqnSKYU
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:10／2019-01-11 12:35 URL： https://twitter.com/kk_hirono/status/1161399666329579520 https://twitter.com/kidkaido/status/1083567958058627077
&twitter(1161399666329579520){theme:light}
> 東電は08年には津波対策をとる方針を決めていた - 海渡雄一｜WEBRONZA - 朝日新聞社の言論サイト https://t.co/ahjrjHusQG  \n  東電福島原発事故刑事裁判の報告を朝日新聞WebRonza にまとめました。是非ごらんなって下さい。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜MichikoKameishi（弁護士 亀石倫子） 日時：2019-08-14 07:10／2018-12-31 23:44 URL： https://twitter.com/kk_hirono/status/1161399738781933568 https://twitter.com/MichikoKameishi/status/1079750170219286528
&twitter(1161399738781933568){theme:light}
> 辺野古の新基地建設計画阻止を目的に設立された辺野古基金の共同代表、宮崎駿氏「沖縄返還の年の4月、大事な沖縄の友人が東京の大学に入るためにパスポートと伝染病予防注射の紙を持って東京に来た。その時の話を思い出すと、沖縄の人にものすごく… https://t.co/lYWmXAQAnx
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:11／2018-12-29 19:21 URL： https://twitter.com/kk_hirono/status/1161399815705464832 https://twitter.com/kidkaido/status/1078959173776269312
&twitter(1161399815705464832){theme:light}
> かけがえのない一人一人の自由を守る延長線に政治がある。 \n  素晴らしい決断に、心から拍手を送ります！ https://t.co/GTHQwAPh8O
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:11／2018-12-08 20:50 URL： https://twitter.com/kk_hirono/status/1161399941882769408 https://twitter.com/kidkaido/status/1071371502254051329
&twitter(1161399941882769408){theme:light}
> 東電刑事裁判は、12月26，27日に論告求刑公判が行われます。私たち、犠牲者遺族代理人も意見を述べる予定です。 \n  12月11日には、札幌で東電刑事裁判の報告集会を行います。 \n  東電役員が津波を予見できたこと、社内で検討されていた対策を… https://t.co/MI6orOnIjP
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜kidkaido（海渡雄一） 日時：2019-08-14 07:12／2018-12-07 09:26 URL： https://twitter.com/kk_hirono/status/1161400057897160704 https://twitter.com/kidkaido/status/1070837030928543744
&twitter(1161400057897160704){theme:light}
> 今の日本の政治には、愛がない。 \n  海を越えて、日本に来る労働者とその家族への愛がない。 \n  災害に苦しむ地域への愛がない。 \n  命のもと水道への愛がない。 \n  美しい海を埋め立てられることに抗議する沖縄の人々への愛がない。 \n  愛のない政治を変えよ… https://t.co/k5wQBlW5ww
◁◁◁
<hr />

　海渡雄一弁護士がリツイートした亀石倫子弁護士のツイートでしたが、高野隆弁護士の顔写真と思ったものが、アニメの巨匠、宮崎駿氏の写真でした。似ていることで有名ですが、ぱっとみだと取り違えていました。

　海渡雄一弁護士が岡口基一裁判官を支持しているというのも意外な発見でした。そういえばその岡口基一裁判官も大崎事件の最高裁決定を厳しく批判していました。最近は岡口基一裁判官の情報を見ることも少ないのですが、今も仙台高裁の裁判官なのだと思います。

　日隅一雄という名前も久しぶりに見かけました。情報流通促進というブログを運営していましたが、主に２００９年３月より前の羽咋市に住んでいた頃に見ていたように記憶にあります。記者から弁護士になったという人でした。

　東日本大震災のとき、避難に事務員に早退してもらうため手当を出してほしいと官邸に電話をしたなどとツイートをしていたのが印象的です。目と耳を疑うようなことがツイートされていたのですが、そのままの情報ではないと、誤解を与えそうにも思います。

　反論の出来ない故人を悪くいうようなことは忍びなくもあるのですが、疑問も大きかったので、ありのままに記録をしておきたいと思います。以前やったこともあったと思うのですが、中途半端だったと思うので、まとめ直しになるかと思います。

＜＜＜2019-08-14（水曜日）07：28＿［これまでの記述範囲の終了時刻］＜＜＜



