#+TITLE: "参考資料／性犯罪／平成３１年３月の４つの無罪判決／匿名弁護士アカウント「くまえもん（@kumaemon9）さん　｜　Twitter」を軸とした弁護士らの反応"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-05-14 15:59:43 +0900
FILE_NAME: 2019-05-14-155943_匿名弁護士アカウント「くまえもん（@kumaemon9）さん　｜　Twitter」を軸とした弁護士らの反応.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  くまえもん
記事タイトル名の文字数：78　保存ファイル名の文字数：75

#contents

* 東京新聞：性犯罪「司法判断おかしい」　相次ぐ無罪「刑法改正を」：社会（TOKYO　Web）
  :LOGBOOK:
  CLOCK: [2019-05-14 火 16:02]--[2019-05-14 火 16:21] =>  0:19
  :END:

＞＞＞2019-05-14（火曜日）16：02＿［これからの記述範囲の開始時刻］＞＞＞

```
父親から娘への性暴力など、性犯罪での無罪判決が各地の地裁で相次いでいる。性暴力被害の当事者団体「スプリング」は十三日、「司法の判断は被害実態を反映しておらず、市民感覚とずれている」として、法務省と最高裁に刑法改正を求める要望書を出した。被害者にとってあまりに重い「暴行・脅迫要件」が見直されるか、注目されている。　（出田阿生）

　現行法でレイプが犯罪と認められるには、被害者が性交に同意していないことだけでなく、相手からの「暴行または脅迫」によって抵抗が不可能だった証明をしなければならない。二〇一七年に刑法の性犯罪規定が一部見直されたが、この要件は温存された。

［source：］東京新聞：性犯罪「司法判断おかしい」　相次ぐ無罪「刑法改正を」：社会(TOKYO Web) https://www.tokyo-np.co.jp/article/national/list/201905/CK2019051402000127.html
```

　ここに表になった４つの無罪判決の説明があるのですが、「３月１２日　福岡地裁久留米支部　準強姦　控訴」、「３月１９日　静岡地裁浜松支部　強制性交致傷・傷害　無罪確定」、「３月２６日　名古屋地裁岡崎支部　準強制性交等　控訴」

　「３月２８日　静岡地裁　強姦　控訴」となっています。４つ目の静岡地裁で強姦というのは意外でした。奥村徹弁護士のブログで判決文を読んでいますが、準強制性交等だと考えていたように思います。この罪名が違ってくると判決の内容も違って見えてくると思います。

　強姦罪ということは準強制性交への刑法改正前になりますが、犯罪成立の構成要件として相当強度な反抗の抑圧が必要とされるはずです。岡崎支部の件では同じ父娘ということもありますが支配服従の関係から準強制性交での起訴となっていたかと思います。

　静岡地裁の事件は、被害者である１２歳の娘の性犯罪被害の訴えを不合理で信用できないとして無罪としていたように思います。むしろ岡崎支部の事件の方がこめかみを圧迫されたり蹴りを入れられたという暴行の態様について検察官の立証があったという印象です。

　法クラというかネットのTwitter弁護士のツイートのなかでも、準強制性交ではなく暴行や脅迫を手段とした強制性交で起訴した方が有罪の可能性が高かったのではという声を、判決の報道の早い段階で２件ほど目にした記憶があります。

＜＜＜2019-05-14（火曜日）16：21＿［これまでの記述範囲の終了時刻］＜＜＜

* 平成３１年３月の４つの性犯罪無罪判決で唯一無罪が確定した静岡地裁浜松支部の強制性交致傷、不思議と法クラのツイートで一度も見ていない俳優、新井浩文被告人の事件との共通性の指摘
  :LOGBOOK:
  CLOCK: [2019-05-14 火 16:27]--[2019-05-14 火 18:52] =>  2:25
  :END:

＞＞＞2019-05-14（火曜日）16：27＿［これからの記述範囲の開始時刻］＞＞＞

[link:] 東京新聞：性犯罪「司法判断おかしい」　相次ぐ無罪「刑法改正を」：社会（TOKYO　Web） http://hirono-hideki.cocolog-nifty.com/blog/2019/05/post-9989f4.html

　前項目を上記の記事としてブログにアップロードしています。

　前項目に記載をしましたが、浜松支部の強制性交致傷の判決は３月１９日となっています。確認してみないと確かなことは言えませんが、先に毎日新聞で報道があった久留米支部の無罪判決を除き、３月２８日の静岡地裁の無罪判決が出たあとで、残り３件がまとめて報道された気がしています。

　おそらくですが、私の奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のTwilogでも、岡崎支部というワードを含むツイートは、それ以前になかったように思うので、それにあわせて確認が出来るかもしれません。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「岡崎支部」の検索結果 - Twilog https://t.co/45FqbauoRV

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-05-14 16:37／2014-10-26 13:32 URL： https://twitter.com/kk_hirono/status/1128202730181353472 https://twitter.com/hirono_hideki/status/526229798557720576
&twitter(1128202730181353472){theme:light}
> ＜名古屋家裁岡崎支部＞裁判官寝坊で期日取り消し - 弁護士 落合洋司　（東京弁護士会）　の 「日々是好日」 (id:yjochi / @yjochi) http://t.co/HjRjewurRv
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-05-14 16:37／2019-03-22 21:00 URL： https://twitter.com/kk_hirono/status/1128202750427144193 https://twitter.com/hirono_hideki/status/1109062215498264577
&twitter(1128202750427144193){theme:light}
> 三つ子の次男を死なせて実刑判決を受けた母に、執行猶予を求める署名が2万を突破。当事者が語る共感の理由 https://t.co/2tnBncnflF \n  判決公判で、名古屋地裁岡崎支部の野村充裁判長は「無抵抗、無防備の被害者を畳の上に… https://t.co/5gYpSetc0i
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-05-14 16:37／2019-04-04 22:48 URL： https://twitter.com/kk_hirono/status/1128202774531923968 https://twitter.com/hirono_hideki/status/1113800457472753666
&twitter(1128202774531923968){theme:light}
> 娘と準強制性交、父親無罪　「抵抗不能」認定できず　地裁岡崎支部 - 毎日新聞 https://t.co/O581zlQT4E
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜aya_deguchi（aya deguchi） 日時：2019-05-14 16:38／2019-04-05 00:03 URL： https://twitter.com/kk_hirono/status/1128202871097311232 https://twitter.com/aya_deguchi/status/1113819260030054400
&twitter(1128202871097311232){theme:light}
> 共同の原稿、「無罪判決（求刑懲役10年）を言い渡していたことが4日、分かった。判決は3月26日付」←なにでわかったんだろう \n   \n  娘と準強制性交、父親無罪　「抵抗不能」認定できず　地裁岡崎支部 - 毎日新聞 https://t.co/lWVXTPP7v1
◁◁◁
<hr />

　自分の記憶とは少し違った意外な結果が出たのですが、まず、三つ子の次男を死なせた実刑判決の刑事裁判が岡崎支部というのはすっかり忘れていました。野村充裁判長という名前も出ています。その名古屋地裁岡崎支部の建物ですが、昨夜のNEWS７で初めて目にしたとも思います。

　裁判長とあるので３人の裁判官による合議体だと思いますが、だとすると準強制性交で無罪判決を出した鵜飼祐充裁判長の合議体とは別の合議体が岡崎支部には存在することになりそうです。岡崎市の人口というのはわかりませんし、管轄となると豊田市やあるいは豊橋市まで含むのかもしれません。

　長距離トラック運転手の仕事で行った豊田市や豊橋市は余り大きな都市部ではなかったと思いますが、金沢地方裁判所でも合議体というのはずっと１つだけと思われ、同じ時期に２人の裁判長をテレビニュースで見たことは一度もありません。判決のニュース記事も同じです。

　金沢地方裁判所の場合は、北陸３県の福井、石川、富山の全域を管轄とする名古屋高裁金沢支部が同じ庁舎となっているので建物も大きめなのかと思いますが、昨夜テレビのニュースで写真か映像を見た岡崎支部の建物は、これまでにテレビで見てきたどの裁判所より小さく見えました。

　静岡地裁浜松支部というのも半年ほど前に何かの裁判の中継でテレビに映像が出ていましたが、刑事裁判の内容は憶えていません。浜松市の方は、近くを通過したような記憶しか無いのでよくわからないですが、何かのテレビの番組で見た映像では、かなり大きな都市部に見えました。

　岡崎市について検索すると人口が３８６６３９人とありました。金沢市が４５万人程度で、岡崎市の場合には近隣にも人工の多い市がいくつかあると思われるので、岡崎支部の管轄というのは対象人口がかなり多いとも考えられます。

[link:] » 裁判所｜愛知県内の管轄区域表 https://t.co/2UO4pU4hQN

<hr />

　わかりやすい情報ではなかったですが、愛知県内には名古屋地裁の一宮支部、岡崎支部、豊橋支部があるようです。

```
岡崎支部

岡崎市、額田郡幸田町、安城市、碧南市、刈谷市、西尾市、知立市、高浜市、豊田市、みよし市

［source：］名古屋地方裁判所 - Wikipedia https://ja.wikipedia.org/wiki/%E5%90%8D%E5%8F%A4%E5%B1%8B%E5%9C%B0%E6%96%B9%E8%A3%81%E5%88%A4%E6%89%80
```

　こちらの情報のほうがわかりやすいです。知立市というのは名古屋市にかなり近かったように思いますし、かなり広範囲に人工の多そうな市が岡崎市の他に８つもあります。これだと金沢地方裁判所など比較にならないのかと思われます。

ツイート数：2/1260 リツイート数：0/1260 トータル：446

　上記が「twitterAPI-search-lawList-mydql-add.rb 新井浩文」という自作コマンドの実行結果です。ここ一週間のTwitterの検索結果とも考えられますが、トータルで４４６というのはずいぶん少ない数です。

　以前、鵜飼祐充裁判長の名前で実行すると、決まってエラーが起こっていました。数が多すぎてリミットを超えたというような英語のエラーメッセージが出ていました。

　「twitterAPI-search-lawList-mydql-add.rb 鵜飼祐充裁判長」を実行しました。

　しばらくは結果待ちですが、エラーが起きてしまうと計測は不能です。時間を掛けてスクリプトを修正すれば、リミットに達する前に待機し、解除後に再開するなどの処理は可能とは考えています。

　意外に早く結果が出ていました。「ツイート数：6/1260 リツイート数：0/1260 トータル：44」になります。これは鵜飼祐充裁判長の検索なので、次に鵜飼裁判長でやってみます。たぶん、それほど結果は変わらない気はします。

　「こいつ鵜飼の判決の時の弁護士も特定しましょう \n  \n 鵜飼祐充のFacebook顔画像！娘を性的暴行の父に無罪判決を下した名古屋の裁判長！」というのも「鵜飼裁判長」の検索ワードでヒットしていました。かなり幅広くマッチするようになっています。

　「ツイート数：12/1260 リツイート数：0/1260 トータル：73」、やはり「鵜飼裁判長」でも検索結果はさほど変わっていませんでした。報道ステーションのことは忘れましたが、昨夜のNHKのNEWS７とNEWS９では、いずれも鵜飼祐充裁判長の名前が表示されていました。

　次は浜松支部について同様に調べてみます。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「浜松支部」の検索結果 - Twilog https://t.co/wK34DT6i7W

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-05-14 17:30／2011-02-16 23:51 URL： https://twitter.com/kk_hirono/status/1128215942050148352 https://twitter.com/hirono_hideki/status/37886889633656832
&twitter(1128215942050148352){theme:light}
> （引用）同居男性を刺殺したとして殺人罪に問われ、静岡地裁浜松支部の裁判員裁判で正当防衛が認められ無罪判決を受けた女性会社員（４３）について、静岡地検浜松支部は１６日、控訴しない方針を明らかにした。 http://ow.ly/3XvAc
◁◁◁
<hr />

　２０１１年６月７日のあと、今年に入るまで「浜松支部」をキーワードに含むツイートは出てきませんでした。私の経験の範囲ですが、Twitterの検索と違いTwilogの検索は精度が高く明らかに取りこぼしているなどの発見は今のところありません。検索結果を意外に感じることは多々あります。

　今年に入ったものは次の２件ですが、リツイートでいずれも同じアカウントのツイートのようです。最初は３月２２日のツイートで久留米支部の西崎健児裁判長と静岡地裁浜松支部で山田直之裁判長の名前があります。どちらもすっかり名前を忘れていました。

▷ リツイート→hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞shiparaku（ayam）｜2019/03/22 01:19／2019/03/21 23:04｜https://twitter.com/hirono_hideki/status/1108764998342336514 ／ https://twitter.com/shiparaku/status/1108731203639640064
&twitter(1108764998342336514){theme:light}
> RT @shiparaku: ★強姦・準強姦  無罪判決の裁判官リスト（順次修正・補足）
> 
> 裁判員裁判であったとしても、裁判長の果たす役割は大きい。
> 
> 【静岡地裁】浜松支部   山田直之裁判長
> 【福岡地裁】久留米支部   西崎健児裁判長  

▷ リツイート→hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞shiparaku（ayam）｜2019/04/23 17:21／2019/04/04 20:44｜https://twitter.com/hirono_hideki/status/1120603474545106944 ／ https://twitter.com/shiparaku/status/1113769289742290944
&twitter(1120603474545106944){theme:light}
> RT @shiparaku: ★強姦・準強姦  無罪判決の裁判官リスト（順次修正補足）
> 
> 裁判員裁判であったとしても裁判長の果たす役割は大きい。
> 
> 【静岡地裁】浜松支部   山田直之裁判長 
> 【福岡地裁】久留米支部   西崎健児裁判長
> 【静岡地裁】…  

　２つめの４月２３日の私のリツイートは、ツイートの全文が取得できていません。続きに「【静岡地裁】 伊東顕裁判長　【名古屋地裁】岡崎支部　鵜飼祐充裁判長 new!」などとあります。改行を省きました。

　どうも私の記憶違いで静岡地裁浜松支部の無罪判決は少なくとも３月２１日２３時０４分の時点でネット上に情報が出ていたようです。私もそれほど関心がなかったのか、浜松支部の無罪判決については突っ込んで調べていなかったとも考えられます。

　しばらくは様子見だという思いもあったのだと思いますが、浜松支部の無罪判決については、他の３件の無罪判決とは違って、裁判員裁判で検察が控訴せずに確定したこともあってか、すぐに話題を見かけなくなりました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「静岡地裁」の検索結果 - Twilog https://t.co/b0H4lqcmGF

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-05-14 17:48／2019-03-28 19:59 URL： https://twitter.com/kk_hirono/status/1128220448901042176 https://twitter.com/hirono_hideki/status/1111221231250870273
&twitter(1128220448901042176){theme:light}
> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”静岡地裁”／データベース登録済みツイート：2019年03月28日19時55分の記録：ユーザ・投稿：33／55件 https://t.co/vb2l4Sjpw1
◁◁◁
<hr />

▶（43／55） TW uwaaaa（サイ太） 日時： 2019-03-20 12:01:00 +0900 URL： https://twitter.com/uwaaaa/status/1108201898924924930
{% tweet 1108201898924924930 %}
> ＞静岡地裁浜松支部は20日までに無罪判決を言い渡した \n \n 「20日までに」ってなんだよ \n \n 静岡の強制性交致傷罪で無罪判決 ｜ 共同通信 https://t.co/TzM4JGGIFU

```
2019/3/20 11：44 (JST)3/20 11：53 (JST)updated
©一般社団法人共同通信社

　静岡県磐田市で昨年9月、女性に乱暴したなどとして強制性交致傷罪に問われたメキシコ国籍の男性の裁判員裁判で、静岡地裁浜松支部は20日までに無罪判決を言い渡した。「故意はなかった」と判断した。

［source：］静岡の強制性交致傷罪で無罪判決 ｜ 共同通信 https://this.kiji.is/480930247175160929
```

　刑裁サイ太のツイートにある共同通信の記事ですが、上記の９４文字ほどのものが記事の全文になります。久留米支部の無罪判決で法クラの弁護士らは、記事の内容が短い要約で意味がわからないと批判をしていましたが、こちらははるかに文字数の少ない内容の記事でした。

▶（48／55） TW yjochi（?落合洋司?立憲民主党参議院比例第19総支部長ヨージ 寛容で温かい社会へ） 日時： 2019-03-28 15:12:00 +0900 URL： https://twitter.com/yjochi/status/1111149112399806464
{% tweet 1111149112399806464 %}
> 徹底的に反抗抑圧されたら声も出ないのでは？レイプ天国化する日本になってないか。→12歳長女への強姦で無罪判決　静岡地裁 - 毎日新聞 https://t.co/42RwYrUHoe

　まとめ記事はツイートの投稿日時（リツイートの場合はリツイートされた日時）で時系列に並んでいます。意外な結果ですが、上記の落合洋司弁護士（東京弁護士会）のツイートが、私が収集したツイートの範囲で静岡地裁の１２歳長女への強姦無罪判決の最初のものであったようです。

　もちろんですが、ツイートの投稿日時と私のデータベースへの登録日時は別物です。データベースへの登録日時というのも意味のある情報ですが、まとめ記事でも使っていません。表示させようと考えたこともあるのですが、文字情報が増えてしまうので控えました。

　そういえば、昨夜、小倉秀夫弁護士のツイートのまとめ記事をいくつか作成していて、「弁護士」をキーワードにしたところツイートの数が４千を超えていました。これまでは多くても２千台であったように思います。深澤諭史弁護士だとエラーが出て、見ると7千を超えていました。

　一ページ分のツイートが４千を超えると、流石にページの読み込みに時間が掛かっていました。処理能力が非力なパソコンだとそのまま固まってしまう可能性もあるかもしれません。

2019年05月14日00時50分の登録： REGEXP：”弁護士”／小倉秀夫（@Hideo_Ogura）の検索（2009-08-10〜2019-05-13／2019年05月14日00時49分の記録4979件） http://hirono2014sk.blogspot.com/2019/05/regexphideoogura2009-08-102019-05.html

　よく見ると４９７９件となっていて、あと２１件で５千件になっていました。「警察」についてまとめ記事を作成しておこうと考えたついでだったのですが、そちらの方で思わぬ発見がけっこうありました。それも一部を見た範囲でのことです。

　ちょっとわかりづらくもあるので、「浜松支部」でまとめ記事を作成します。そこで「新井浩文」でページ内検索を実行すれば、手早く確認できるとも思います。ツイートの収集は限られた範囲になりますが。

　「ツイート数：20/1260 リツイート数：14/1260 トータル：151」という結果がまず出ています。これはTwitterAPIでの検索なので一週間以内のツイートしか取得できていない可能性がありますし、検索の精度そのものも経験上、信頼がおけません。

　「list-tweet-egrep.sh 浜松支部」の結果は意外に少なく１０１件でした。これからデータベースへの登録処理を行いますが、登録済みが多いと思われます。

　何度かご紹介していると思いますが、「for i in `cat ~/l`; do k4-tweet-add-mysql-uniq-argv.rb $i; done」がデータベースへの登録処理になります。

　新規登録が７，８割方あるようにも見えました。エラーが出ているツイートのURLもありますが、リツイートが取り消されたり、ツイートが削除された可能性もあるものです。たまたまエラーが出て、再実行で登録されることもありますが、再実行は余りやらなくなりました。

　思い出したのですが、アカウントが削除されたり、非公開設定になったときもツイートの取得が出来なくなります。非公開設定になった場合は、エラーメッセージが「 Sorry, you are not authorized」という感じで認証エラーになっているようです。

[link:] » 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”浜松支部”／データベース登録済みツイート：2019年05月14日18時29分の記録：ユーザ・投稿：52／117件 https://t.co/wlMc1E9clD

<hr />

　データベース操作で時間の範囲は指定していませんが「取得ツイートの投稿日時の範囲：（2009-08-03 17:25〜2019-05-14 18:16）」という表示も冒頭で行っています。１１７件と多くはないので指定しませんでした。あわよくば判決が出る前の情報も出るかもしれません。

▶（051／117） TW uwaaaa（サイ太） 日時： 2019-03-20 12:01:00 +0900 URL： https://twitter.com/uwaaaa/status/1108201898924924930
{% tweet 1108201898924924930 %}
> ＞静岡地裁浜松支部は20日までに無罪判決を言い渡した \n \n 「20日までに」ってなんだよ \n \n 静岡の強制性交致傷罪で無罪判決 ｜ 共同通信 https://t.co/TzM4JGGIFU

　ブラウザで「2019-03」というページ内検索を行っています。やはりさきほどと同じ刑裁サイ太のツイートが初出でした。１つ前の５０件目は１月１７日のツイートとなっています。「営利略取，逮捕監禁/静岡地裁浜松支部刑事部」などとあります。

　「新井浩文」のページ内検索は４件でしたが、いずれも本日の告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)で投稿で、この本文にあるのと内容は同じです。

　ブラウザでのTwitter検索もやったみたいと思います。こちらはTwitterAPIのような投稿時刻の時間的な取得制限はないと聞きます。以前はあったようですが、撤廃されたという情報を２年ほど前かに見かけています。ただ、精度に信頼がおけないことは同じです。

［link：］ 浜松支部 新井浩文 - Twitter検索 https://twitter.com/search?l=&q=%E6%B5%9C%E6%9D%BE%E6%94%AF%E9%83%A8%20%E6%96%B0%E4%BA%95%E6%B5%A9%E6%96%87&src=typd&lang=ja

　検索結果は私の告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のツイートの２件のみです。３５分前と２時間前として表示されています。

＜＜＜2019-05-14（火曜日）18：52＿［これまでの記述範囲の終了時刻］＜＜＜

