#+TITLE: "本件殺人未遂事件の舞台である市場急配センターのホームページで代表者と記される堂野俊一という人物について"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-19 10:44:32 +0900
FILE_NAME: 2019-08-19-104432_本件殺人未遂事件の舞台である市場急配センターのホームページで代表者と記される堂野俊一という人物について.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 市場急配センターにおける犯罪行為  堂野さん 松浦さん 被告発人松平日出男 被告発人安田繁克 被告発人安田敏
記事タイトル名の文字数：51　保存ファイル名の文字数：73

* 本件殺人未遂事件の舞台である市場急配センターのホームページで代表者と記される堂野俊一という人物について（２０１９．０８．１９）
  :LOGBOOK:
  CLOCK: [2019-08-19 月 10:47]--[2019-08-19 月 12:51] =>  2:04
  :END:

＞＞＞2019-08-19（月曜日）10：47＿［これからの記述範囲の開始時刻］＞＞＞

```
社名	市場急配センター株式会社
所 在 地	
本　社
石川県金沢市駅西本町5丁目10番20
TEL076-260-4050　FAX076-265-7555

代 表 者	堂野　俊一
創　　業	昭和62年5月20日
資 本 金	2,000万円
事業内容	一般貨物自動車運送事業
自動車運送取扱事業
自動車運送代弁業
自動車運送利用業
取引銀行	北國銀行　中央市場支店　
金沢信用金庫　駅西支店　
商工中金　金沢支店
従業員数	総数　141名 　　　　　
本社131名　
福井営業所 10名
保有車輌	総合車両台数　123輌　 　　　　　
本社
2ｔ53輌／4ｔ53輌／10ｔ6輌　
フォークリフト4輌
タイヤショベル1輌 
福井営業所
4ｔ9輌／10ｔ2輌　
　　　　　
加入保険	
社会保険制度・労災制度・任意保険（全車加入）
車輌・対物・対人・搭乗者・貨物（運送）
三井住友海上火災保険（株）

［source：］市場急配センター株式会社│トップページ http://www.kyuhai.jp/profile.html
```

　上記に引用をしました。２０１９年８月１９日１０時５２分現在の情報です。こまかくチェックをしたわけではないですが、数年前から情報に変化はないように思います。従業員数も１４１名となっていますが、これも数年前から変わっていないように思います。

　初めて市場急配センターのホームページをみたのは平成１５年の８月ぐらいだったと思います。２００３年です。当時の代表者は被告発人松平日出男で、それから２，３年後に現在の堂野俊一に変更されましたが、これも時期をはっきり憶えているわけではありません。

[link:] » 市場急配センター, ホームページ の検索結果 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/jtgfOEsQf6

<hr />

```
未提出の資料からの抜粋になります。


　市場急配センターのホームページのアクセスカウンターは２００６年７月１２日０時０３分現在２５３９件であり、代表取締役の紹介は松平日出男のままです。アクセス件数もほとんど増えることもなく、まったく何事もないように健在のようです。

［source：］金沢工業大学からの反応、黙殺する社会からの声 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/entry/20061006/1160130904
```

[link:] » 堂野, ホームページ の検索結果 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/SUfbM1byAA

<hr />

```
どうやら同じ会社の関係者らの供述調書がベースになっていたようですが、具体的な事実を知らされないままに、裁判は進んで行きました。私はその関係者らを殺人未遂の共謀共同正犯として、金沢地方検察庁に告発、告訴して来ましたが、それなりの具体的な根拠はあるはずなのです。

犯罪計画の中心人物と目される市場急配センターの松平日出男社長は、私が被害者と結婚したいと言ったとき、「ほう、それが一番都合のいい話やな」と言っていました。現在の市場急配センターの社長は、堂野俊一になっているようです。市場急配センターのホームページにそのような記載があるのですが、代表取締役になっています。

この堂野という人物が、その代表取締役である可能性が高いのですが、私の知る堂野という人物は、労務の担当者なので話を聞いておく必要があると言い、松平日出男に同席していました。その上で、「かたわ、と結婚したいってかぁ？」という言葉を私に投げつけていました。これは、平成10年の11月の20 日頃のことでした。

まあ、彼らの言い分に従うと、被害者家族に警察が肩入れをして、事実をねじ曲げるということになりそうです。近頃よく目につくパターンに通じるものがありますが、そのような先入観、固定観念が、18年以上に渡って問題を長期化させた一因とも思えるわけです。

とりわけ、障害となって行く手を阻んだのが、同郷宇出津の幼なじみでもある被告訴人OKN、被被告訴人OSNの兄弟と被告訴人KYNでしたが、単なる協力者という可能性と同時に、むしろ主体的な犯行実行者であった可能性があります。警察、検察は少なくとも形式上、私個人の事件として問題を片付けたので、私自身真相に迫ることは出来ませんでした。警察、検察が決め手となるような事実を掴んでいる可能性も否定できませんが、社会や市民の理解が先決と言うことで、今のところ放置しているのかもしれません。

平成11年の8月に、今度は被害者の父親に対する傷害事件を起こすことになり、金沢中警察署に逮捕されて、平成13年の12月31日まで、私は金沢刑務所に服役しました。それまでは、長くても一月に一度は父親の会社の方に電話をするという関係が続いていて、6月頃にはPHSの携帯電話の番号も教えてもらって、頻繁に電話をしていました。

結局、父親の要求は、お前の友達を連れてきて、一緒に話をしようというものでしたが、私が拒んだこともあり、その場の成り行きで、傷害事件に及んでしまいました。このあたりは具体的な事情を細かく書いておかなければならないのですが、今はその時間の余裕もないので、ごく大雑把に書きました。このあたりの説明をしておくことが、被害者家族の立場をご理解いただく上でも不可欠な要素と考えております。

半月ほど前の金曜日になりますが、立ち寄った書店で光市母子殺害事件の遺族の「なぜ君は絶望と闘えたのか　本村洋の3300日」という本が目に入り、買ってきて二日がかりで読了しました。一切関わりを持たず、沈黙を貫くべきか、敢然と社会に訴えかけて行くべきか、選択に迷ったようなことも書いてあり、この言葉は以前から知っていましたが、私の被害者の家族は、18年間沈黙を貫き通していることになります。

［source：］*1246977375*［金沢中警察署］4 途中経過、七夕 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/entry/20090707
```

　上記に引用したのは、２００９年７月７日の記述のようです。平成２１年ですが、その３月に私は５年３か月ほどだった羽咋市のアパートでの生活から宇出津に戻り現在に至っています。

　２，３年前ならそうでもないかもしれないですが、１０年前となると自分の書いたものを読み返しても、鮮やかに記憶が蘇るわけではありません。少なからず、こういうことも書いていたのかと他人事のように感じる部分もあります。

　しかし、引用部分を読むと、記述の時点で比較的最近に市場急配センターのホームページの代表者が被告発人松平日出男から堂野俊一に変更になったことに気がついた様子です。

　最近までそうでしたが、市場急配センターのホームページを開くのは数ヶ月に１回ぐらいで、半年から１年以上全くみない時期もあったように思います。市場急配センターのホームページは、Googleで市場急配センターと検索するとすぐに出てきます。

　私が知る堂野さんと市場急配センターのホームページに代表者堂野俊一と掲載のある人物は同一人物である可能性が高いですが、根拠は姓名が同じということと、イワシの運搬の仕事をやっていた頃、ラビット号にある書類で、そのような名前を見かけたような記憶があります。

　金沢市場輸送の事務所でも名前を見かける機会はあったかもしれません。より印象的に憶えているのは堂野さんを金沢市場輸送に紹介したと聞く、松浦さんのことで、下の名前に健という漢字があって２文字だったと思うのですが、珍しい漢字ではなかったもののやや珍しい組み合わせに感じました。

　入社という言葉は適切でないと思うのですが、堂野さんが金沢市場輸送でイワシの運搬の仕事をするようになったのは、平成２年の２月ころと推定します。まだピークの忙しさがあったと記憶しますが、時期的にイワシの運搬のシーズンが終わりかけの頃の登場であったと記憶にあります。

　堂野さんの姿をみかけるようになったのは、季節も春めいてきた時期、最近知ったところでは梅の時期とも重なりそうな気がします。小型に見える珍しいダンプの持ち込みでした。

　私も少年時代、ラッカースプレーでバイクに塗装をしたことがあったのですが、まさにキャビンがそれと同じ様な塗装のダンプでした。キャビンというのはトラックで運転席の部分です。荷台とは別になるのですが、トラックの仕事をした人でないと意識することもないかもしれません。

　車種は三菱ふそうの旧型でした。正確なことは思い出せないですが、昭和６２年に私がイスズの新車の大型車に乗務した時点で、モデルチェンジから１，２年後だったような気がします。三菱ふそうの大型車のモデルチェンジも、似た頃か少し早かったかもしれません。

　しかし、三菱ふそうの旧型車というのは、平成２年当時でも見かけることが少なかったように思います。塗装はピンクと赤の混じったワインレッドのような色で、若者のバイクの塗装がそのままダンプになったような珍しいものだったので、とても印象的でした。

　たぶん、土砂済み禁止と荷台に書いてあるダンプでしたが、土砂済み禁止のダンプとしては見たことのない小さなものでした。この土砂済み禁止というダンプは、主に木材のチップを運搬するもので、それは異様なぐらい荷台の高いものでした。

　なお、松浦さんと坂田さんが乗務していた金沢市場輸送のダンプは、どちらもイスズでしたが、チップ専用のダンプに匹敵するほど、荷台が高く大きいものでした。チップ専用のダンプというのも石川県内では見かけることが少なかったように思います。

　それでも金沢港というのは木材の扱いの大きな港で、木材を運搬するトラックやトレーラーは、金沢港から河北潟の間でよく見かけていました。この道路は、イワシの運搬での金沢港から北陸ハイミールへの往復と重なります。

　同じ石川県の七尾市の七尾港も木材の取扱が多く、七尾の方はロシアから来ていると聞いたこともありました。七尾市の丸一運輸の下請けで、能登木材と林ベニアの仕事を多くやっていたことは、数日前にも記述したと思いますが、これは全てが関東便だったように思います。

　茨城県古河市の山三青果の帰り荷の仕事と基本セットになっていたので、関東便が中心だったのはわかりますが、同じ丸一運輸の仕事では、これも数日前に記述した和歌山県かつらぎ町のミカンの仕事がありました。岐阜県大垣市から石灰を運んだこともありました。

　かつらぎ町のミカンの仕事も帰り荷の仕事で、ほとんどは大阪本場、大阪北部の市場へ馬鈴薯を運ぶのが行き荷でしたが、空車で向かったこともあったように思います。

　丸一運輸の仕事を市場急配センターに紹介したのは被告発人東渡好信と聞いていました。同じ七尾市の出身になりますが、被告発人東渡好信は七尾市内の実家から、通いの単身赴任のようなかっこうで、市場急配センターの仕事をしていました。

　市場急配センターの１階には、コンクリートの土間に机が１つある運転手の控室のようなスペースに隣接して、畳の座敷がありました。平成３年の９月に入ってからつくられたもので、工事期間も１０日ほどだったと思います。

　広くて６畳程度の畳の部屋でしたが、被告発人東渡好信はそこに寝泊まりすることもあったようです。金沢市内にアパートなどは借りていないと聞いていました。これは輪島市海士町の浜上さんも同じだったと思いますが、輪島の方が七尾より、倍ほど遠く感じます。

　被告発人東渡好信と浜上さんはもともと木材を運ぶ運送会社でトレーラーの運転手をしていたと聞きます。あとで市場急配センターに入社してきた和田くんも同じと聞きました。和田くんはその一年ほど前、金沢市場輸送にもいましたが、荷物の積み下ろしがきつかったらしくすぐに辞めていました。

　わりと身長もあって横に広がる体型でもなかったですが、体重が１００キロを超えることで荷物の積み下ろしの負担が大きかったようです。片山津温泉せきや、の大浴場で、体重計の針が振り切れるのを初めて見ましたが、それでも１０５キロか多くて１１０キロという話だったと思います。

　今も同じかどうかしらないですが、金沢市の粟崎のあたりから直線道路が河北潟に突き当たる一帯は、木材置き場が広がっっていました。見慣れた光景ではありましたが、木材の運搬の仕事をしたいとも考えたことはなかったので、あまり考えることはありませんでした。

　少し縁があったといえば、宇出津のTSさんと金沢港の近くで会ったことで、そのときTSさんは星崎運輸の大型車に乗務していました。トレーラーではなかったように思います。時期もはっきりとは憶えていませんが、久しぶりの再会でした。

　この宇出津のTSさんは、私の先輩の先輩になりまして４つほど年上だったと思います。昭和５９年１月に初めて金沢市場輸送に入社したのも、先輩にTSがいるのだから行ってみてはどうかと勧められたこともありました。

　また、昭和５８年４月ころの小林運送の長距離助手の仕事では、早朝に大型車の洗車をさせられるのが日課でしたが、そのすぐ近くに金沢市場輸送の駐車場があって、金沢市場輸送の保冷車を見かけていました。

　また、金沢市場輸送のことは、蛸島のTSさんのことでちょくちょく聞いていました。被告発人安田敏とは石川県立水産高校漁業科の同級生で、卒業後すぐに金沢市場輸送で長距離運転手を始めたと聞いていました。

　被告発人安田敏は石川県立水産高校を卒業後、金沢中央卸売市場のウロコ水産に入社したと聞きます。なかなか入れない将来性のある高待遇の会社で、親の口利きがあったので入社できたとも聞きました。

　なお、金沢中央卸売市場は大きく、青果と鮮魚に分かれます。青果は石川丸果１つだけでしたが、鮮魚は、石川中央魚市とウロコ水産があって、セリも交代で行われると聞いていました。

　金沢市場輸送と福岡の鮮魚の定期便を一日交代でやっていたウロコ運送は、名前が似ていますが、ウロコ水産とは無関係という話でした。ウロコ運送の息子は福岡に見習いとして駐在していたことがあり、よく話をしたり、遊びに出ることもありました。

　ウロコ運送は、宮城県の石巻・塩釜の鮮魚の定期便もやっており、松川運輸という地元の運送会社の仕事でした。規模が１，２の運送会社とも聞いていました。１位は清治丸水産とも聞いたことがありましたが、トラックの保有台数か売上だったのかこまかいことは記憶にありません。

　私は一度だけ、その松川運輸の仕事を石巻だったと思いますが、臨時でやったことがありました。それも宮城県とは隣県の福島県郡山市の市場への運搬でした。夕方の遅い時間には仕事が終わったようにも思うのですが、変わった雰囲気のある市場であったと記憶にあります。

　宇出津のTSさんとは金沢市場輸送に入社してすぐに打ち解けました。日野の大型保冷車の新車に乗務していました。１年ぐらいは経っているように聞いたとも思いますが、同じ頃に納車されたというもう一台の日野の新車に乗務していたのが、本恒夫でした。

　昭和５９年当時の話ですが、金沢市場輸送の運転手では最古参で、それでも入社８年目と聞いたように思います。昭和６１年の１２月ころからは、藤村さんの入院をきっかけに配車係となって、市場急配センター株式会社の誕生とともに、金沢市場輸送の社長となりました。

　市場急配センターの社長となったのは被告発人松平日出男です。金沢市場輸送の社長だった竹沢俊寿は、金沢市場輸送と市場急配センターの会長となりました。

　そんな話を聞いたのも、時期が特定できるほど思い出せなくなっています。秋頃であったようには思います。被告発人松平日出男を初めて見たのは、昭和６３年の９月に入ってすぐだったように記憶にはあります。

　次に記憶がはっきりするのは、いつのまにか市場急配センターの事務所が出来上がっていたことで、これは平成２年の４月頃になるかと思います。６月には片山津温泉ホテルながやま、で慰安会がありました。ホテル長山と漢字であったかもしれません。テレビCMでも見かける時期がありました。

＜＜＜2019-08-19（月曜日）12：51＿［これまでの記述範囲の終了時刻］＜＜＜


