#+TITLE: "本件殺人未遂事件の舞台である市場急配センターのホームページで代表者と記される堂野俊一という人物について"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-19 10:44:32 +0900
FILE_NAME: 2019-08-19-104432_本件殺人未遂事件の舞台である市場急配センターのホームページで代表者と記される堂野俊一という人物について.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 市場急配センターにおける犯罪行為  堂野さん 松浦さん 被告発人松平日出男 被告発人安田繁克 被告発人安田敏
記事タイトル名の文字数：51　保存ファイル名の文字数：73

* 本件殺人未遂事件の舞台である市場急配センターのホームページで代表者と記される堂野俊一という人物について（２０１９．０８．１９）
  :LOGBOOK:
  CLOCK: [2019-08-19 月 10:47]--[2019-08-19 月 12:51] =>  2:04
  :END:

＞＞＞2019-08-19（月曜日）10：47＿［これからの記述範囲の開始時刻］＞＞＞

```
社名	市場急配センター株式会社
所 在 地	
本　社
石川県金沢市駅西本町5丁目10番20
TEL076-260-4050　FAX076-265-7555

代 表 者	堂野　俊一
創　　業	昭和62年5月20日
資 本 金	2,000万円
事業内容	一般貨物自動車運送事業
自動車運送取扱事業
自動車運送代弁業
自動車運送利用業
取引銀行	北國銀行　中央市場支店　
金沢信用金庫　駅西支店　
商工中金　金沢支店
従業員数	総数　141名 　　　　　
本社131名　
福井営業所 10名
保有車輌	総合車両台数　123輌　 　　　　　
本社
2ｔ53輌／4ｔ53輌／10ｔ6輌　
フォークリフト4輌
タイヤショベル1輌 
福井営業所
4ｔ9輌／10ｔ2輌　
　　　　　
加入保険	
社会保険制度・労災制度・任意保険（全車加入）
車輌・対物・対人・搭乗者・貨物（運送）
三井住友海上火災保険（株）

［source：］市場急配センター株式会社│トップページ http://www.kyuhai.jp/profile.html
```

　上記に引用をしました。２０１９年８月１９日１０時５２分現在の情報です。こまかくチェックをしたわけではないですが、数年前から情報に変化はないように思います。従業員数も１４１名となっていますが、これも数年前から変わっていないように思います。

　初めて市場急配センターのホームページをみたのは平成１５年の８月ぐらいだったと思います。２００３年です。当時の代表者は被告発人松平日出男で、それから２，３年後に現在の堂野俊一に変更されましたが、これも時期をはっきり憶えているわけではありません。

[link:] » 市場急配センター, ホームページ の検索結果 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/jtgfOEsQf6

<hr />

```
未提出の資料からの抜粋になります。


　市場急配センターのホームページのアクセスカウンターは２００６年７月１２日０時０３分現在２５３９件であり、代表取締役の紹介は松平日出男のままです。アクセス件数もほとんど増えることもなく、まったく何事もないように健在のようです。

［source：］金沢工業大学からの反応、黙殺する社会からの声 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/entry/20061006/1160130904
```

[link:] » 堂野, ホームページ の検索結果 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 https://t.co/SUfbM1byAA

<hr />

```
どうやら同じ会社の関係者らの供述調書がベースになっていたようですが、具体的な事実を知らされないままに、裁判は進んで行きました。私はその関係者らを殺人未遂の共謀共同正犯として、金沢地方検察庁に告発、告訴して来ましたが、それなりの具体的な根拠はあるはずなのです。

犯罪計画の中心人物と目される市場急配センターの松平日出男社長は、私が被害者と結婚したいと言ったとき、「ほう、それが一番都合のいい話やな」と言っていました。現在の市場急配センターの社長は、堂野俊一になっているようです。市場急配センターのホームページにそのような記載があるのですが、代表取締役になっています。

この堂野という人物が、その代表取締役である可能性が高いのですが、私の知る堂野という人物は、労務の担当者なので話を聞いておく必要があると言い、松平日出男に同席していました。その上で、「かたわ、と結婚したいってかぁ？」という言葉を私に投げつけていました。これは、平成10年の11月の20 日頃のことでした。

まあ、彼らの言い分に従うと、被害者家族に警察が肩入れをして、事実をねじ曲げるということになりそうです。近頃よく目につくパターンに通じるものがありますが、そのような先入観、固定観念が、18年以上に渡って問題を長期化させた一因とも思えるわけです。

とりわけ、障害となって行く手を阻んだのが、同郷宇出津の幼なじみでもある被告訴人OKN、被被告訴人OSNの兄弟と被告訴人KYNでしたが、単なる協力者という可能性と同時に、むしろ主体的な犯行実行者であった可能性があります。警察、検察は少なくとも形式上、私個人の事件として問題を片付けたので、私自身真相に迫ることは出来ませんでした。警察、検察が決め手となるような事実を掴んでいる可能性も否定できませんが、社会や市民の理解が先決と言うことで、今のところ放置しているのかもしれません。

平成11年の8月に、今度は被害者の父親に対する傷害事件を起こすことになり、金沢中警察署に逮捕されて、平成13年の12月31日まで、私は金沢刑務所に服役しました。それまでは、長くても一月に一度は父親の会社の方に電話をするという関係が続いていて、6月頃にはPHSの携帯電話の番号も教えてもらって、頻繁に電話をしていました。

結局、父親の要求は、お前の友達を連れてきて、一緒に話をしようというものでしたが、私が拒んだこともあり、その場の成り行きで、傷害事件に及んでしまいました。このあたりは具体的な事情を細かく書いておかなければならないのですが、今はその時間の余裕もないので、ごく大雑把に書きました。このあたりの説明をしておくことが、被害者家族の立場をご理解いただく上でも不可欠な要素と考えております。

半月ほど前の金曜日になりますが、立ち寄った書店で光市母子殺害事件の遺族の「なぜ君は絶望と闘えたのか　本村洋の3300日」という本が目に入り、買ってきて二日がかりで読了しました。一切関わりを持たず、沈黙を貫くべきか、敢然と社会に訴えかけて行くべきか、選択に迷ったようなことも書いてあり、この言葉は以前から知っていましたが、私の被害者の家族は、18年間沈黙を貫き通していることになります。

［source：］*1246977375*［金沢中警察署］4 途中経過、七夕 - 奉納：危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中 http://hirono-hideki.hatenablog.com/entry/20090707
```

　上記に引用したのは、２００９年７月７日の記述のようです。平成２１年ですが、その３月に私は５年３か月ほどだった羽咋市のアパートでの生活から宇出津に戻り現在に至っています。

　２，３年前ならそうでもないかもしれないですが、１０年前となると自分の書いたものを読み返しても、鮮やかに記憶が蘇るわけではありません。少なからず、こういうことも書いていたのかと他人事のように感じる部分もあります。

　しかし、引用部分を読むと、記述の時点で比較的最近に市場急配センターのホームページの代表者が被告発人松平日出男から堂野俊一に変更になったことに気がついた様子です。

　最近までそうでしたが、市場急配センターのホームページを開くのは数ヶ月に１回ぐらいで、半年から１年以上全くみない時期もあったように思います。市場急配センターのホームページは、Googleで市場急配センターと検索するとすぐに出てきます。

　私が知る堂野さんと市場急配センターのホームページに代表者堂野俊一と掲載のある人物は同一人物である可能性が高いですが、根拠は姓名が同じということと、イワシの運搬の仕事をやっていた頃、ラビット号にある書類で、そのような名前を見かけたような記憶があります。

　金沢市場輸送の事務所でも名前を見かける機会はあったかもしれません。より印象的に憶えているのは堂野さんを金沢市場輸送に紹介したと聞く、松浦さんのことで、下の名前に健という漢字があって２文字だったと思うのですが、珍しい漢字ではなかったもののやや珍しい組み合わせに感じました。

　入社という言葉は適切でないと思うのですが、堂野さんが金沢市場輸送でイワシの運搬の仕事をするようになったのは、平成２年の２月ころと推定します。まだピークの忙しさがあったと記憶しますが、時期的にイワシの運搬のシーズンが終わりかけの頃の登場であったと記憶にあります。

　堂野さんの姿をみかけるようになったのは、季節も春めいてきた時期、最近知ったところでは梅の時期とも重なりそうな気がします。小型に見える珍しいダンプの持ち込みでした。

　私も少年時代、ラッカースプレーでバイクに塗装をしたことがあったのですが、まさにキャビンがそれと同じ様な塗装のダンプでした。キャビンというのはトラックで運転席の部分です。荷台とは別になるのですが、トラックの仕事をした人でないと意識することもないかもしれません。

　車種は三菱ふそうの旧型でした。正確なことは思い出せないですが、昭和６２年に私がイスズの新車の大型車に乗務した時点で、モデルチェンジから１，２年後だったような気がします。三菱ふそうの大型車のモデルチェンジも、似た頃か少し早かったかもしれません。

　しかし、三菱ふそうの旧型車というのは、平成２年当時でも見かけることが少なかったように思います。塗装はピンクと赤の混じったワインレッドのような色で、若者のバイクの塗装がそのままダンプになったような珍しいものだったので、とても印象的でした。

　たぶん、土砂済み禁止と荷台に書いてあるダンプでしたが、土砂済み禁止のダンプとしては見たことのない小さなものでした。この土砂済み禁止というダンプは、主に木材のチップを運搬するもので、それは異様なぐらい荷台の高いものでした。

　なお、松浦さんと坂田さんが乗務していた金沢市場輸送のダンプは、どちらもイスズでしたが、チップ専用のダンプに匹敵するほど、荷台が高く大きいものでした。チップ専用のダンプというのも石川県内では見かけることが少なかったように思います。

　それでも金沢港というのは木材の扱いの大きな港で、木材を運搬するトラックやトレーラーは、金沢港から河北潟の間でよく見かけていました。この道路は、イワシの運搬での金沢港から北陸ハイミールへの往復と重なります。

　同じ石川県の七尾市の七尾港も木材の取扱が多く、七尾の方はロシアから来ていると聞いたこともありました。七尾市の丸一運輸の下請けで、能登木材と林ベニアの仕事を多くやっていたことは、数日前にも記述したと思いますが、これは全てが関東便だったように思います。

　茨城県古河市の山三青果の帰り荷の仕事と基本セットになっていたので、関東便が中心だったのはわかりますが、同じ丸一運輸の仕事では、これも数日前に記述した和歌山県かつらぎ町のミカンの仕事がありました。岐阜県大垣市から石灰を運んだこともありました。

　かつらぎ町のミカンの仕事も帰り荷の仕事で、ほとんどは大阪本場、大阪北部の市場へ馬鈴薯を運ぶのが行き荷でしたが、空車で向かったこともあったように思います。

　丸一運輸の仕事を市場急配センターに紹介したのは被告発人東渡好信と聞いていました。同じ七尾市の出身になりますが、被告発人東渡好信は七尾市内の実家から、通いの単身赴任のようなかっこうで、市場急配センターの仕事をしていました。

　市場急配センターの１階には、コンクリートの土間に机が１つある運転手の控室のようなスペースに隣接して、畳の座敷がありました。平成３年の９月に入ってからつくられたもので、工事期間も１０日ほどだったと思います。

　広くて６畳程度の畳の部屋でしたが、被告発人東渡好信はそこに寝泊まりすることもあったようです。金沢市内にアパートなどは借りていないと聞いていました。これは輪島市海士町の浜上さんも同じだったと思いますが、輪島の方が七尾より、倍ほど遠く感じます。

　被告発人東渡好信と浜上さんはもともと木材を運ぶ運送会社でトレーラーの運転手をしていたと聞きます。あとで市場急配センターに入社してきた和田くんも同じと聞きました。和田くんはその一年ほど前、金沢市場輸送にもいましたが、荷物の積み下ろしがきつかったらしくすぐに辞めていました。

　わりと身長もあって横に広がる体型でもなかったですが、体重が１００キロを超えることで荷物の積み下ろしの負担が大きかったようです。片山津温泉せきや、の大浴場で、体重計の針が振り切れるのを初めて見ましたが、それでも１０５キロか多くて１１０キロという話だったと思います。

　今も同じかどうかしらないですが、金沢市の粟崎のあたりから直線道路が河北潟に突き当たる一帯は、木材置き場が広がっっていました。見慣れた光景ではありましたが、木材の運搬の仕事をしたいとも考えたことはなかったので、あまり考えることはありませんでした。

　少し縁があったといえば、宇出津のTSさんと金沢港の近くで会ったことで、そのときTSさんは星崎運輸の大型車に乗務していました。トレーラーではなかったように思います。時期もはっきりとは憶えていませんが、久しぶりの再会でした。

　この宇出津のTSさんは、私の先輩の先輩になりまして４つほど年上だったと思います。昭和５９年１月に初めて金沢市場輸送に入社したのも、先輩にTSがいるのだから行ってみてはどうかと勧められたこともありました。

　また、昭和５８年４月ころの小林運送の長距離助手の仕事では、早朝に大型車の洗車をさせられるのが日課でしたが、そのすぐ近くに金沢市場輸送の駐車場があって、金沢市場輸送の保冷車を見かけていました。

　また、金沢市場輸送のことは、蛸島のTSさんのことでちょくちょく聞いていました。被告発人安田敏とは石川県立水産高校漁業科の同級生で、卒業後すぐに金沢市場輸送で長距離運転手を始めたと聞いていました。

　被告発人安田敏は石川県立水産高校を卒業後、金沢中央卸売市場のウロコ水産に入社したと聞きます。なかなか入れない将来性のある高待遇の会社で、親の口利きがあったので入社できたとも聞きました。

　なお、金沢中央卸売市場は大きく、青果と鮮魚に分かれます。青果は石川丸果１つだけでしたが、鮮魚は、石川中央魚市とウロコ水産があって、セリも交代で行われると聞いていました。

　金沢市場輸送と福岡の鮮魚の定期便を一日交代でやっていたウロコ運送は、名前が似ていますが、ウロコ水産とは無関係という話でした。ウロコ運送の息子は福岡に見習いとして駐在していたことがあり、よく話をしたり、遊びに出ることもありました。

　ウロコ運送は、宮城県の石巻・塩釜の鮮魚の定期便もやっており、松川運輸という地元の運送会社の仕事でした。規模が１，２の運送会社とも聞いていました。１位は清治丸水産とも聞いたことがありましたが、トラックの保有台数か売上だったのかこまかいことは記憶にありません。

　私は一度だけ、その松川運輸の仕事を石巻だったと思いますが、臨時でやったことがありました。それも宮城県とは隣県の福島県郡山市の市場への運搬でした。夕方の遅い時間には仕事が終わったようにも思うのですが、変わった雰囲気のある市場であったと記憶にあります。

　宇出津のTSさんとは金沢市場輸送に入社してすぐに打ち解けました。日野の大型保冷車の新車に乗務していました。１年ぐらいは経っているように聞いたとも思いますが、同じ頃に納車されたというもう一台の日野の新車に乗務していたのが、本恒夫でした。

　昭和５９年当時の話ですが、金沢市場輸送の運転手では最古参で、それでも入社８年目と聞いたように思います。昭和６１年の１２月ころからは、藤村さんの入院をきっかけに配車係となって、市場急配センター株式会社の誕生とともに、金沢市場輸送の社長となりました。

　市場急配センターの社長となったのは被告発人松平日出男です。金沢市場輸送の社長だった竹沢俊寿は、金沢市場輸送と市場急配センターの会長となりました。

　そんな話を聞いたのも、時期が特定できるほど思い出せなくなっています。秋頃であったようには思います。被告発人松平日出男を初めて見たのは、昭和６３年の９月に入ってすぐだったように記憶にはあります。

　次に記憶がはっきりするのは、いつのまにか市場急配センターの事務所が出来上がっていたことで、これは平成２年の４月頃になるかと思います。６月には片山津温泉ホテルながやま、で慰安会がありました。ホテル長山と漢字であったかもしれません。テレビCMでも見かける時期がありました。

＜＜＜2019-08-19（月曜日）12：51＿［これまでの記述範囲の終了時刻］＜＜＜


* 本件殺人未遂事件の舞台である市場急配センターのホームページで代表者と記される堂野俊一という人物について（２０１９．０８．２９）
  :LOGBOOK:
  CLOCK: [2019-08-29 木 14:40]--[2019-08-29 木 19:12] =>  4:32
  :END:

＞＞＞2019-08-29（木曜日）14：40＿［これからの記述範囲の開始時刻］＞＞＞

　４，５日の間、中断をしていたかと思います。数日ぶりの投稿は、Windows10のパソコン環境からになります。

　数日前になりますが、朝目が覚めたとき、夢の続きだったのか、被告発人安田繁克の供述調書の冒頭部分のことが頭に浮かんでいました。長い間思い出すことがなかったような気もするのですが、思い出していたとしてもさほど重視はしていませんでした。

　ちょっと違っているかもしれないですが、「私は今言った住所に妻、美鈴と一緒に住み」と言った部分です。その女性の名前を知ったのは、その供述調書を読んだのが初めてでしたが、思いあたる女性については確かな記憶がありました。

　私が市場急配センターで市内配達の仕事をしたのは、平成3年6月22頃日から同年8月いっぱいぐらいです。早い段階の私の記憶では5月だったのですが、金沢市場輸送を退社前の運行表が出てきて、6月も金沢市場輸送で長距離の仕事をしていたことになっていたのです。

　その金沢市場輸送の運行表については、ネットで公開したと思われる写真をつい最近も目にすることがありました。これまではさほど重要視していなかった運行表なのですが、被告発人木梨松嗣弁護士の控訴審の段階での差し入れであったかもしれません。

　金沢市場輸送で会社を辞めると話してすぐ、私は市場急配センターに行きました。すでに紹介で入社していた被告発人安田敏が市場急配センターで仕事をしていたからです。私は50万円の前借りの保証人にもなっていたのですが、その安田敏の入社自体が、計画の1つであった可能性があります。

　記録には記憶の新しい段階で具体的な事実経過を繰り返し記述してあることです。被告発人東渡好信が主導した金沢市場輸送のストライキと連動した被告発人安田敏の登場でした。大型免許を取得するため大徳自動車学校に市内配達の仕事をしながら通う、ということがすぐに決まっていました。

　段取りが早すぎるとも感じましたが、金沢市場輸送での入社が決まってすぐ、被告発人安田敏は市場急配センターで市内配達の仕事をするようになっていました。ちょうど免許停止中だったという被告発人多田敏明を同乗させ、内灘コースの配達をしていました。

　その後、被告発人多田敏明は、フィアレディZに彼女を同乗させ、雨の中、北陸自動車道の小松インター付近で大きな事故を起こし、免許停止になったとも話していました。小松からのラブホテルの帰りと言っていましたが、小松市にラブホテルがあったかな、とは少し疑問でした。

　フィアレディZは、新型車に近いという話しぶりだったと記憶にあります。事故で廃車になったと言い、その後、免許停止が明けてからは、あまり若者らしくない軽四に乗っていました。それも祖父に買ってもらったというような話をしていました。

　被告発人多田敏明は、市場急配センターの事務所が出来てからの入社だと思います。金沢市場輸送の事務所と一緒だったときに見かけた顔ではありませんでした。

　今考えると、平成2年6月の片山津温泉ホテル長山での慰安会のときも、被告発人多田敏明の顔は見ていなかったような気がしますが、市場急配センターの市内配達でかなり若者が増えているとは感じたことを憶えています。あるいはそのなかに被告発人多田敏明もいたのかもしれません。

　被害者安藤文さんは、すでに市場急配センターの仕事していたかと思いますが、慰安会には参加していませんでした。これは当時、意識的に見て記憶していたことなので間違いはないと思います。被告発人HTNもまた市場急配センターで仕事を始める前でした。

　すでに告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)で投稿していると思いますが、片山津温泉ホテル長山での慰安会では、金沢市場輸送の輪島の運転手と市場急配センターの運転手がケンカになったという話でした。

　私はその現場を見ておらず、酒に酔って部屋に戻って眠っていたところを、輪島の運転手仲間に起こされて、一緒に金沢に帰ったのです。金沢市場輸送の給油所の前あたりで、長話をした後、くるまやラーメンに行ったことなど書いていると思います。

　ケンカになったという話でしたが、誰一人怪我をしている様子はなく不思議には感じていました。あとで被告発人安田繁克も参加して市場急配センター側で張り切っていたというような話を聞いたこともありました。誰に聞いたのかは覚えがないですが、金沢市場輸送の運転手ではないと思います。

　前にも書いたことがあると思いますが、金沢市場輸送を辞めたと市場急配センターの事務所で被告発人松平日出男に報告したとき、次の仕事が決まっていないのであれば、しばらく一日1万5千円という条件で市内配達の仕事をして欲しいと、誘われたのです。

　その翌日から市場急配センターで市内配達の仕事を始めたと記憶にあるのですが、すぐに正社員として市場急配センターに入社することが決まりました。当時は派遣という仕事の形態もなかったので、入社と言うことはそのまま正社員でした。

　市場急配センターの給料日は、25日締めの翌月5日払いでした。当時も珍しい支払日と聞いたことがありますが、5日の支払日が銀行の休みとなった場合、銀行の営業日明けの支払いになるともされていました。

　一日1万5千円というアルバイトは3日で終わったと記憶にあります。25日までの3日間となるので23日から市場急配センターの仕事を始めたと考えられます。

　被告発人安田敏から久しぶりの電話があったのは4月の終わり頃、ゴールデンウィークに入る4月30日の直前であったと思います。それから一週間か長くても10日の間に、被告発人安田敏の入社が決まり、決まった翌日ぐらいから市場急配センターで仕事の仕事をしていたようでした。

　なお、4月の終わりぐらいから2週間程度だったと思いますが、金沢中央卸売市場では毎年、集中してタケノコの出荷がありました。私は昭和59年から経験をしていたのですが、タケノコの出荷は、新潟県内や東京が多く、山形県や仙台市もありました。

　市場急配センターは2トン車でも新潟県内にタケノコを運んでいたらしく、金沢市場輸送の大型車に乗務していた頃ですが新潟県内で見かけたことがありました。

　繰り返しますが月末に近い23日あたりから私は市場急配センターで市内配達の仕事を始めました。被告発人安田敏が大型免許を取得したというのは、それからでも一月ほど後だったと思います。仕事が終わった後、大徳自動車学校に行って、それから藤江のゲームセンターに立ち寄ることもありました。

　あらためて考えると、被告発人安田敏の金沢市場輸送への入社は5月の5日前後と考えられ、大型免許を取得したのが早くて7月の中頃と考えられるので、2ヶ月半というのは長すぎるという気がします。

　私も金沢市場輸送で市内配達の仕事をしながらでしたが、一発試験で大型免許を取得しました。合格した日は誕生日の翌日だったのでよく憶えています。昭和61年11月27日のことです。9回目の合格であったように思います。あるいは13回目になりますが、その辺りの記憶は早くからあやふやでした。

　合格した当日に大型免許の交付があったと記憶にあるのですが、その免許証の交付の手数料を含めて1500円ぐらいだったと記憶にあり、合格しなかったときの費用はそれよりだいぶん安かったと記憶にあります。仮にすべて1500円としても10回で1万5千円になります。

　被告発人安田敏は、お金で生活に困っていると言いながら、前借りを入社の条件とし、当初30万円と言っていたように思うのですが、50万円につり上げました。口先で本当に生活に困窮とは思えなかったし、何よりおかしいと感じたのは、安田敏の妻が全く礼など言わなかったことです。

　そればかりか、徹底して顔を隠し見せようとはしませんでした。私も初めての経験だったので理解が出来なかったのですが、それが何事もなかったように、目の前で顔を見せたのが、平成3年12月22日のことでした。21日の翌日で日曜日だったと思います。

　それも出産予定日を5日ほど前に控えた状態で、マタニティ系の服ではなく、大きなお腹が目立つジャージのズボンに長袖シャツのような服装でした。数日後、ほぼ予定通りに出産したと被告発人安田敏に聞き、自分と同じ12月25日が長女の誕生日となったとも聞いたような覚えがあります。

　無事出産を終えたと被告発人安田敏に話を聞いたのは、栃木県足利市のガソリンスタンドから掛けた電話だったと思います。古河の山三青果の帰り荷を積んでいたときだったと思いますが、市場の荷物を積んでいるときガソリンスタンドに立ち寄ることは滅多になかったので、余計に印象的に憶えています。

　国道50号線沿いでしたが、大きな中央分離帯があって、佐野市から前橋市方面に向かっているときではないと、大きく迂回しなけらばならず、一度やって懲りた経験があったので、ほとんど利用しないガソリンスタンドでもありました。太陽鉱油のカードのガソリンスタンドでした。

　私は何度か一発試験に通うことを、大幅な費用の低減になるとも被告発人安田敏に説得したのですが、まるっきり聞く耳を持たない様子でした。多少なりとも違和感を感じていましたが、それは金沢市場輸送で入社が決まったときにも感じました。

　一応面接というかたちだったと思いますが、なぜか夕方の遅い時間に行われました。外はすっかり暗くなっていて、19時半から20時半の間であったように思います。金沢市場輸送の事務所ではなく、その隣の運転手の控え室のようなところ、外のドアから入ってすぐのテーブルで行われました。

　今思い出せるのは、本恒夫社長だけですが、他にも2，3人の幹部級が同席していたように思います。本恒夫社長はたんたんと面接をしていましたが、あまりに自然体だったので、不思議に思いました。

　それというのも昭和60年になりますが、被告発人安田敏は金沢市場輸送に入社をして、仕事をしていた時期があったからです。当時は本恒夫社長も大型車の長距離の仕事をしていたので、顔を合わす機会が少なかったとは考えられましたが、どうなのかという思いはありました。

　なにか私に負担を負わせて会社につなぎ止めるのが目的とも思えました。それがあらかじめ話が決まっていたように決まった被告発人安田敏の50万円の前借りと、私の保証人でした。被告発人安田敏に対する質問というのはほとんどなかったと思いますし、私に対しても同様でした。

　なにより金沢市場輸送への入社が決まってすぐに、市場急配センターでの仕事が決まったことが素早い動きでした。当時、金沢市場輸送の本恒夫社長と市場急配センターの被告発人松平日出男は対抗心が強く折り合いが悪いとも言われ、本恒夫社長に関しては対外的にも摩擦を起こしていると聞いていました。

　自尊心が強く独りよがりというのか、お山の大将という声を聞くこともありました。これは金沢市場輸送で事務員をしていた谷口さんから直接話を聞いたものです。当時20代後半と聞いたと思う女性事務員でしたが、当時25歳前後だった私には、かなり年上に見えていました。

　これまで少なくとも強調して書いたことはなかったと思いますが、この谷口さんという金沢市場輸送の女性事務員は、事件の鍵を握る人物かもしれないのです。前提となるのは被告発人安田敏の話です。

　金沢市場輸送を辞め、市場急配センターで仕事をするようになってからも定期的に金沢市場輸送に行く用事がありました。用事というのもどうかと思いますが、トラックの給油で金沢市場輸送の給油所を使っていたためです。

　この給油には鍵が使われたのですが、少なくとも市場急配センターでは1つの鍵を全社員の運転手が使い回していたと思います。この給油の鍵というのも私と被害者安藤文さんの接触の機会となっていました。鍵を彼女が管理するようになったからです。

　正確な時期が思い出せないですが、それ以前は金沢市場輸送の事務所で主に谷口さんから鍵を受け取り、給油が終わって返していました。金沢市場輸送の女性事務員は、谷口さんの他にもう一人いました。小柄で物静かな女性でしたが、20代前半と聞いたかもしれません。

　いつ頃に入社したのかもよくわかっていなかったのですが、平成3年の秋頃には、谷口さんと親しくいつも一緒にいるという感じでした。名前は聞いたことがあったと思いますが、早い段階で忘れていると思います。小柄で声も小さかったように思いますがそもそも声を聞いたことがなかったかもしれません。

　記録には繰り返し書いていると思いますが、被害者安藤文さんは、毎日、金沢市場輸送の事務所に行きコンピュータのデータ入力をしていました。私が金沢市場輸送にいた頃は、午前中に見かけることが多かったと記憶にあります。

　そのあとのことはよく思い出せないのですが、平成4年2月3日に、平成3年11月の終わり頃から続けていた裏駐車場での自分の軽四の駐車をやめてからは、私が会社にいる時間は市場急配センターの事務所にいるようにして、仕事に出る時間に出かける姿を見ることが多くなったように思います。

　私は午後に七尾市に積み荷に行くことが多かったのですが、午後2時から3時の間に会社を出ることが多かったような気がします。先ほど平成4年2月1日としましたが、2月3日だったので訂正しました。

　平成4年2月1日というのも特別な日でしたが、その日の夜遅く、23時頃ではなかったかと思いますが、偶然を装った被告発人安田繁克と会って市場急配センターの1階で話をすることになりました。供述調書で被告発人安田繁克はそれを、私の方からけんか腰で絡んできたように供述しています。

　平成3年の12月の中頃は、まだ金沢市場輸送に給油に行っていたと思うのですが、平成4年になってからはほとんど行かなくなっていたとも思うのです。代わりに給油に行くようになったのが、石川県河北郡になりますが津幡町のガソリンスタンドでした。

　金沢市内の市場急配センターの事務所からどのくらいの距離、時間が掛かったのかよく憶えておらず、あまり意識もしていなかったと思いますが、往復だと馬鹿にならない時間が掛かりました。それでも津幡まで給油に行くことが増えたと記憶にあります。

　市場急配センターで使えるカードは太陽鉱油のカードだけでした。名前は大きそうな会社ですが、カードが使える給油所はずいぶん少なく、関東でも給油をしたと記憶にあるのは、国道16号線沿いの千葉県野田市、ここはかなり大きなガソリンスタンドでした。

　バイパスではない旧道の国道4号線沿いで、ちょうど茨城県と栃木県の県境でしたが、間々田に太陽鉱油のカードが使える給油所がありました。ここはもっともよく利用したとも思いますが、大型トラックが出入りするとは思えないような小さめのガソリンスタンドでした。

　そしてもう一つが、さきほど被告発人安田敏の妻の出産のことで書いた足利市のガソリンスタンドです。規模はかなり大きめのガソリンスタンドでしたが、不都合もあったので利用はわずかだったと思います。

　当時の大型トラックの経由のタンクというのは2つ付いていて、300リッターずつ入ると聞いたことがありましたが、金沢市場輸送の保冷車ではよく入って530リッターぐらいだったと思います。

　一度、金沢から鮮魚を積んで青森に向かうとき、富山県の魚津インターで降りて給油するつもりが、富山インターの手前でガス欠を起こして肝を冷やしたことがありました。それ以来、余裕を持ってこまめに給油を行うようになりました。ガス欠した前日は長崎県にいたことも憶えています。

　やはり思い出せないのですが、なぜか平成4年に入ってからは金沢市場輸送に給油に行かなくなったように思います。

　一度だけ、七尾市に積み荷に向かうのに津幡町の太陽鉱油のカードの使えるガソリンスタンドに立ち寄ったことがありました。これも被害者安藤文さんとの間で特別に記憶に残る運行となったのですが、北陸ハイミールでミール移動をしているとき、急に長距離の仕事の指示が来たのです。

　津幡町の太陽鉱油のカードの使えるガソリンスタンドは、国道8号線沿いで、津幡の検問所の大きな交差点の少し手前、左側だったと思います。検問所のところは大きな三叉路で、右に富山方面、左に能登方面となっていましたが、通常、能登方面に向かうには遠回りにもなるので通らない道でした。

　2ヶ月ほど前になりますか、Googleマップで津幡町の周辺の国道8号線をみたのですが、平成4年当時とは道路事情がかなり変わっている感じでした。

　最後に金沢市場輸送の給油所に行ったと記憶にあるのは、平成3年12月の28日頃でした。仕事納めではなかったと思いますが、それに近い日のことです。12月も終わりだったので17時過ぎには外もだいぶん暗くなっていたと思います。

　すっかり暗くなった時間で、被告発人多田敏明と西口君がいたことははっきり憶えています。他にも数人がいたと思いますが、顔ぶれは現在思い出せなくなっています。

　不貞腐れたように不機嫌な態度を見えることも少なくなかった被告発人多田敏明ですが、そのときは妙に明るく、被告発人HTNのアパートに遊びに行こうと言い出しました。横にいた西口君も同じぐらい積極的に感じられたのですが、突然の言い出しとは考えにくく、織り込み済みと思えました。

　妙に明るい被告発人多田敏明の不自然な態度というのは、その数日前にも感じていました。12月24日のクリスマスの夜だったと思います。時間は23時から0時の間ぐらいだったように思います。場所は金沢中央卸売市場の中の高瀬商店の近くです。トイレの前ぐらいだったでしょうか。

　高瀬商店についてはTwilogで検索をすれば情報が出てくるのではと思います。一つの目印ような場所にもなっていましたが、その辺りで茨城県古河市の山三青果の荷物の福井分の中継を行っていました。

　だいたいは4トンウィング車に積み替えをしていましたが、ある程度荷物が多いと、そのまま被告発人多田敏明を同乗させて福井の市場に行っていました。この福井中継で思い出すのは、被告発人多田敏明と被告発人梅野博之だけですが、被告発人梅野博之を同乗させて向かったことはなかったと思います。

　はじめの頃に一度だけだったと思いますが、被告発人HTNと二人で福井の市場に行ったことがありました。私がまだ金沢市場輸送の大型運転手をしている頃であったと思います。

　この山三青果の仕事についても記録では思い出す限りの詳細を記述していると思います。そこにも書いてあると思いますが、最初に山三青果に行ったのは昭和62年の4月から5月頃のことでした。当時は、日榮運送の下請け仕事だったと考えられます。

　Googleで確認すると日榮運送でも検索結果が出ましたが、漢字は「日栄運送」が正しいようです。金沢市場輸送では長崎県長与町のミカンの仕事もしていましたが、その後、大きなケンカ別れをしたと聞きます。それも本恒夫社長が相手を怒らせたようでした。

　東北陸運塩釜本社では、実際に「坊主憎けりゃ袈裟まで憎い」とまで言われたことを記録には記述していると思いますが、本恒夫社長の仕事相手の怒らせ方というのも尋常ではなかった様子で、それも他の目的のための計算ずくの意図的なものがあったようにも思えます。

　東北陸運塩釜本社では、苫東陸運という同じデザインのトラックで、北海道の苫小牧港からフェリーで仙台港に来た荷物の積み替えも多かったのですが、確か高橋課長と呼ばれていたように思います。その人と、丸刈りのスポーツ選手のような若者が主に荷積みをしてくれました。

　「坊主憎けりゃ袈裟まで憎い」という言葉を金沢市場輸送の本恒夫社長に向けて発したのは、普段より温厚そうにも見えていた丸刈りのスポーツ選手のような若者でした。当時は名前も知っていたかもしれません。今もなんとなく顔立ちが高橋課長とともに記憶にあります。

　高橋課長ではなく高橋部長だったかもしれません。運転手としてもかなりベテランという感じでしたが、東北陸運塩釜本社でもトップクラスという感じでした。石巻からの立ち寄りが多かったですが、着くとすぐに事務所から出てきて、手際よく荷積みをしてくれました。

　私はいつの間にか慣れていたので余り苦労することもなかったのですが、東北便は卸先の数も多く、荷物の種類も多かったので、慣れない運転手は大変な思いをしたとも聞きます。300キロの生マグロからおでんの練り製品も多くありました。

　東北便で大変な思いをしたと記憶にあるのは、山形自動車道が開通する前で、冬場に有料の笹谷トンネルを通っていた頃のことです。山形自動車道の開通後は新潟市内まで行っている時間に、まだ山形県に入れていないということもありました。

　有料の笹谷トンネルではない笹谷峠という道路はもっとすごいと聞いたことがありましたが、通ったことがありませんでした。それでも坂が急で、冬場は路面が凍結し、まるで地獄巡りのような趣がありました。

　東北便は金沢市場輸送の保冷車で一番多い仕事となっていたので、その分慣れもあって、やりやすい仕事にもなっていました。九州の鮮魚の定期便のように京都市の辺りで大渋滞に遭う、同じく東京の首都高でも渋滞でトイレに行けない心配もなかったので、その分気楽でした。

　平成3年12月の中頃にも、金沢市場輸送の給油所で、被告発人安田敏の乗務していた三菱ふそうの大型ウィング車に同乗していた記憶が残っています。ちょうどジャスコ若宮店の笹寿司の弁当を彼に手渡していました。当日あったミーティングで出された弁当でした。

　この笹寿司の弁当ですが、鳥弁当と鮭弁当の2種類がありました。楕円形の木箱のような弁当でした。今年の4月1日になりますが、7年ぶりかに金沢市内に行った帰り、福久のイオンではなかったかと思いますが、ショッピングモールのようなところの笹寿司の店で鳥弁当を買いました。

　よく憶えていないのですが、平成3年当時とは鳥弁当の箱のデザインも変わっていたように思います。たぶんスマホで撮影した写真があるかと思います。

　ちょっとGoogleで検索をしましたが福久のイオンで間違いはないようです。家に戻ってから調べて知ったように思いますが、当初はサティだったようです。サティは同じような大型店舗が、金沢市のトラックステーションの近くにありました。

　サティ御経塚店となっていたかもしれません。近年のことですが、御経塚が金沢市ではなく野々市市らしいということを知って、少し驚いたことがありました。御経塚の交差点が国道8号線にあって、その角にはうつのみや書店があったのですが、ずっと前になくなっている気がします。

　平成10年の犀川まつりの当日になりますが、人混みが大嫌いというKYNが付き合ってくれて、日中に、その御経塚の近くのサティに買い物に行ったことがありました。これも記録にはあると思いますが、あらためて取り上げておきたい事実の一つです。

　Googleで検索すると、やはり御経塚のサティは現在、イオン御経塚店となっているようです。住所も石川県野々市市となっていますが、金沢西インターにかなり近い場所であるだけに、その辺りまで野々市市というのは、金沢市で生活をしていた当時の感覚として違和感があります。

　calコマンドでカレンダーの確認をすると、平成11年の第一土曜日、犀川まつりの日は、やはり8月7日となっていました。ちょうど花火大会が終わる頃に、若宮大橋だったと思いますが、車が混む中、被害者安藤文さんの自宅に向かっていました。

＜＜＜2019-08-29（木曜日）19：12＿［これまでの記述範囲の終了時刻］＜＜＜


