#+TITLE: "「ツイッターもユーザーが増えればこういう垢も増えることになるな」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイートから池袋の事故"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-16 11:33:04 +0900
FILE_NAME: 2019-08-16-113304_「ツイッターもユーザーが増えればこういう垢も増えることになるな」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイートから池袋の事故.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 名誉毀損での刑事告訴  モトケンこと矢部善朗弁護士（京都弁護士会）
記事タイトル名の文字数：68　保存ファイル名の文字数：90

* 「ツイッターもユーザーが増えればこういう垢も増えることになるな」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイートから池袋の事故
  :LOGBOOK:
  CLOCK: [2019-08-16 金 11:35]--[2019-08-16 金 14:17] =>  2:42
  :END:

＞＞＞2019-08-16（金曜日）11：35＿［これからの記述範囲の開始時刻］＞＞＞

　台風１０号は通り過ぎたらしく天気も回復しています。朝方はまだ風が強く、夜中には強い風の音で目が覚めることもありましたが、０時を過ぎ日付が変わった頃は、外は雲多いものの穏やかで、その雲の動きもぴたりと止まって見えていました。

　朝７時からのテレビニュースでも台風１０号の大きな被害はなかったらしく、潮位が９メートルになるというような厳戒情報も出ていただけに、高潮による被害がなかったのも不思議です。

　少し見たモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインは少し荒れ気味でした。モトケンこと矢部善朗弁護士（京都弁護士会）の正義感が迸った痕跡があり、よく人柄や思考があらわれていると思いました。それと同時に懸念されてきた問題性も明確化しました。

▶ ツイート％motoken_tw（モトケン）％2019/08/16 09:23％ https://twitter.com/motoken_tw/status/1162157852259057665
&twitter(1162157852259057665){theme:light}
> フォロワーが2400以上いるということは、ネタ垢としてそこそこ知られているということなのかな。
> ツイッターもユーザーが増えればこういう垢も増えることになるな。仕方がないことだけど、ひろゆき氏が言ったことがツイッターについても妥当す… https://t.co/0Y28XTlsd8  
▶

　なお、現時点でも次のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートが最新のものとなっています。

▶ ツイート％motoken_tw（モトケン）％2019/08/16 09:44％ https://twitter.com/motoken_tw/status/1162163084959444992
&twitter(1162163084959444992){theme:light}
> 誰が卑怯者か、と問われると津田氏ではないように思うw
> 彼は無能だ。
> https://t.co/P1cT5O0Eqx https://t.co/hLuSlik00l  
▶

　津田氏は著名人で社会的な影響も強いので、厳し目の批判も許される考えなのかと思いますが、「彼は無能だ」という断定はその根拠も見当たらず、この短絡的な批判は、これまで警察や裁判所に対しても見かけてきたパターンで、古いものだと検察も出てくるかと思います。

　フォロワーが２４００以上から切り出したツイートも特定のアカウントの批判のようですが、かなり辛辣で攻撃性を感じるものです。ネット上の思想警察のようにも映ったのですが、これは２，３日前の深澤諭史弁護士のツイートとブログ記事にも感じたことでした。

　少し触れたかと思いますが、モトケンこと矢部善朗弁護士（京都弁護士会）の「安全ピン」問題との類似性です。

　モトケンこと矢部善朗弁護士（京都弁護士会）に批判の的にされたアカウントは、モトケンこと矢部善朗弁護士（京都弁護士会）が引用した対象のツイートが消えていたものの、アカウントのタイムラインは見ることが出来ました。

　同じアカウントかどうかは憶えていないのですが、内容は日航機墜落事故の疑惑を具体化したもので、同じアカウントだった可能性は高めかと思います。しかし、実際にツイートをみると、リツイートの数も少なくモトケンこと矢部善朗弁護士（京都弁護士会）がなぜ的にしたのかと考えました。

　たまたま見かけたという可能性もありますが、日頃から網を張るように監視をし、ここぞと思うものを取り沙汰して、煽りを入れているようにも感じました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜GensuiAkainu（雀神の赤犬さん of 麻雀復帰 25代目天鳳位） 日時：2019-08-16 12:10／2019-08-16 08:02 URL： https://twitter.com/kk_hirono/status/1162199826987044865 https://twitter.com/GensuiAkainu/status/1162137634740658176
&twitter(1162199826987044865){theme:light}
> まあ、真相としちゃ、 \n  「ぐうぜん、自衛隊の放った標準機が、飛行機に当たった＝操縦不能になり１２３便が墜落＝このままでは自衛隊の不祥事になるので、日本政府が揉み消した」なんだろうけどね \n   \n  山に墜落したのは、おそらく、意図的なもので、証拠隠滅を容易にするため
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜GensuiAkainu（雀神の赤犬さん of 麻雀復帰 25代目天鳳位） 日時：2019-08-16 12:10／2019-08-16 07:58 URL： https://twitter.com/kk_hirono/status/1162199843504177152 https://twitter.com/GensuiAkainu/status/1162136427649368064
&twitter(1162199843504177152){theme:light}
> １２３便の墜落事件、調べていると、あまりに闇が深い、とかんじる \n   \n  おそらく、さいしょの「飛行機の後ろの破損」は、ただの事故＝自衛隊の誤射、偶然、標準機が当たっただけ、だったのだろう \n   \n  しかし、山に墜落したのは、おそらく、証拠隠滅＝「日本政府による意図的な撃墜」だった可能性が高い
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜GensuiAkainu（雀神の赤犬さん of 麻雀復帰 25代目天鳳位） 日時：2019-08-16 12:10／2019-08-16 05:08 URL： https://twitter.com/kk_hirono/status/1162199872281296896 https://twitter.com/GensuiAkainu/status/1162093735905116160
&twitter(1162199872281296896){theme:light}
> まあ、１２３便の墜落事故自体が、自衛隊の誤射によるものなので、 \n   \n  わざとオールエンジンと誤訳したというかんじだろうね \n   \n  明らかに、オールエンジンとは聞こえない
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜GensuiAkainu（雀神の赤犬さん of 麻雀復帰 25代目天鳳位） 日時：2019-08-16 12:10／2019-08-16 05:01 URL： https://twitter.com/kk_hirono/status/1162199907949670402 https://twitter.com/GensuiAkainu/status/1162091908300099584
&twitter(1162199907949670402){theme:light}
> １２３便の墜落事故： \n   \n  オールエンジン、とは絶対に発音してない \n   \n  オレンジエア、も違う \n   \n  たぶん、「オンレンジエア」＝飛行機の上の範囲で、なにか起きた、という意味の発音
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜2NN_Newsplus（2NN ニュース速報＋） 日時：2019-08-16 12:10／2019-08-16 04:12 URL： https://twitter.com/kk_hirono/status/1162199950337306624 https://twitter.com/2NN_Newsplus/status/1162079623338835969
&twitter(1162199950337306624){theme:light}
> 【強気】飯塚幸三元院長から皆様へ【池袋暴走事故】 https://t.co/ju8GxHotiI
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜GensuiAkainu（雀神の赤犬さん of 麻雀復帰 25代目天鳳位） 日時：2019-08-16 12:11／2019-08-15 10:33 URL： https://twitter.com/kk_hirono/status/1162200160459358210 https://twitter.com/GensuiAkainu/status/1161813072387792896
&twitter(1162200160459358210){theme:light}
> ７、真相をしっている自衛隊員は、精神ストレスをかかえ、数年間の大量自殺になっている \n   \n  ８、ボーイング社と日本政府で、闇の取引が結ばれ、墜落事故の原因をカブセルかわりに、多額の取引を結ぶことを議決 \n   \n  ９、１２３便の墜落事故は、真相はウヤムヤにされ、今にいたる
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜GensuiAkainu（雀神の赤犬さん of 麻雀復帰 25代目天鳳位） 日時：2019-08-16 12:11／2019-08-15 10:31 URL： https://twitter.com/kk_hirono/status/1162200185105027074 https://twitter.com/GensuiAkainu/status/1161812572590317568
&twitter(1162200185105027074){theme:light}
> ４、自衛隊員は、ミサイルの破片回収に際し、「周辺のものを火炎放射器で焼き払った」と推定できる \n   \n  ５、これにより、いくつかの死体に、２度焼きの痕跡が付き、医者や歯医者が死後検証したさいに不自然な痕跡となった \n   \n  ６、自衛隊員が、深夜のうちに山にいた、という証言は、多く集まっている
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜GensuiAkainu（雀神の赤犬さん of 麻雀復帰 25代目天鳳位） 日時：2019-08-16 12:11／2019-08-15 10:25 URL： https://twitter.com/kk_hirono/status/1162200204411469825 https://twitter.com/GensuiAkainu/status/1161811049768607745
&twitter(1162200204411469825){theme:light}
> １、墜落した山は、すぐ特定できたにも関わらず、なぜか特定できない、と情報操作 \n   \n  ２、山への救援を、１３時間遅らせた \n   \n  ３、その間に、山に自衛隊を派遣し、山狩り＝ミサイルの証拠を持ち帰った（自衛隊には、放射能物質の回収と命令されてた様子） \n   \n  これが１２３便の墜落事件の真相かな
◁◁◁
<hr />

　思い出したのですが、数日前に同じ日航機墜落事故で問題にされていたのが横田基地の緊急着陸要請拒否でした。犠牲者の数が５２０人と多く、利用者の大きい航空機の大事故だったので、都市伝説のような疑惑や作り話も多かったように思います。疑惑はテレビでも見たような気がします。

　上記にリツイートをしましたが、真偽は不明です。不明ですが説得力のある論拠が示されているとも思えませんでした。モトケンこと矢部善朗弁護士（京都弁護士会）はこれまでにも、このようなツイートをやり玉に上げてきました。以前は、福島県の風評被害も多かったと思います。

　以前まとめ記事を作成したこともあったと思いますが、原発関連だけでもものすごい数のツイートをモトケンこと矢部善朗弁護士（京都弁護士会）は行っていて、こだわりが強かったようです。もともと関心の強い問題なので、それ自体はおかしくないですが、内容を見ているどうかと思いました。

[link:] 2019年05月18日20時14分の登録： モトケン（@motoken_tw）／「原発」の検索結果　-　Twilog：2019年05月18日20時12分　3500件 http://hirono2014sk.blogspot.com/2019/05/motokentw-twilog2019051820123500.html

[link:] 2019年08月16日12時25分の登録： REGEXP：”風評被害”／モトケン（@motoken_tw）の検索（2010-05-08〜2019-05-16／2019年08月16日12時25分の記録229件） http://hirono2014sk.blogspot.com/2019/08/regexpmotokentw2010-05-082019-05.html

[link:] 2019年08月16日12時25分の登録： REGEXP：”原発”／モトケン（@motoken_tw）の検索（2011-03-15〜2019-07-22／2019年08月16日12時25分の記録676件） http://hirono2014sk.blogspot.com/2019/08/regexpmotokentw2011-03-152019-07.html

[link:] 2019年08月16日12時25分の登録： REGEXP：”福島”／モトケン（@motoken_tw）の検索（2010-05-06〜2019-05-26／2019年08月16日12時25分の記録481件） http://hirono2014sk.blogspot.com/2019/08/regexpmotokentw2010-05-062019-05.html

　あらためてまとめ記事を作成してみると、表板ほど多い数ではありませんでした。上記４件のうち２件目以降が登録済みのデータベースのデータを対象にしたものです。

　タイムラインに池袋の高齢者暴走事故に関するリツイートがありました。また別に見かける機会はあったかもしれませんが、今回は、モトケンこと矢部善朗弁護士（京都弁護士会）の挑発的なツイートで批判の対象とされたアカウントのタイムラインで見つけることになりました。

[link:] » 【強気】飯塚幸三元院長から皆様へ【池袋暴走事故】 - 2NN 2ちゃんねるニュース速報＋ナビ https://t.co/nQYQUYkQXm

<hr />
[link:] » 【強気】飯塚幸三元院長から皆様へ【池袋暴走事故】 https://t.co/RlWwQLt8FM

<hr />
[link:] » 《池袋高齢者暴走事故》逮捕されない容疑者宅に貼られた「強気な貼り紙」（週刊女性PRIME） - Yahoo!ニュース https://t.co/RdL04ekGIk

<hr />

[link:] » 《池袋高齢者暴走事故》逮捕されない容疑者宅に貼られた「強気な貼り紙」 | 週刊女性PRIME [シュージョプライム] | YOUのココロ刺激する https://t.co/Q6wDzDwh2r

<hr />

　たぶん記事の内容は同じだと思いますが、それぞれに印象も異なりました。Yahooニュースの記事は早くリンク切れとなるので、元記事と思われるものをリンクの週刊女性PRIMから探しました。

　この池袋高齢者暴走事故もいろいろと考えさせられる報道がありましたが、ちょうど昨夜辺りに、深澤諭史弁護士が過去のブログ記事を紹介するツイートを行っていました。

　深澤諭史弁護士のツイートをリツイートしようと思ってブックマークからタイムラインを開こうとしたのですが、今頃になってブロックされていることに気が付きました。告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントです。

▶ ツイート％fukazawas（深澤諭史）％2019/08/14 20:29％ https://twitter.com/fukazawas/status/1161600770631852039
&twitter(1161600770631852039){theme:light}
> 「上級国民だから逮捕されない」は弁護士から見ても本当と思う理由 : 弁護士 深澤諭史のブログ https://t.co/vDuYmWz2z5  
▶

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-16 13:56／2019-08-16 13:55 URL： https://twitter.com/kk_hirono/status/1162226692993081346 https://twitter.com/s_hirono/status/1162226250179497985
&twitter(1162226692993081346){theme:light}
> 2019-08-16-135444_深澤諭史さんはTwitterを使っています：　「「上級国民だから逮捕されない」は弁護士から見ても本当と思う理由　：　弁護士　深澤諭史のブログ　　Twitt.jpg https://t.co/G9qBSM9Hew
◁◁◁
<hr />

　８月１４日２０時２９分という深澤諭史弁護士のツイートですが、現在もリツイート、いいねともに０のようです。先日リツイートが8千を超えていた深澤諭史弁護士のツイートがあって、いいねは２万と表示されていたように思います。この違いは不思議な現象です。

　池袋高齢者暴走事故については、最初の事故の報道のときから特別なものを感じていました。ゴミ収集車が横転していたことが大きいです。これもいずれ取り上げたいと思いますが、平成４年１月の池袋のことから被害者安藤文さんとの関係を記述することもだいぶん前から考えていました。

　東京地検特捜部の元特捜部長であったように思いますが、あちらの暴走事故の方が不可解なものでした。若い女性とゴルフ場に行くところで、女性がトランクにゴルフ用具を乗せるか乗せようとしていた時に、いきなり暴走したという話も見かけています。

　停車中からの暴走事故で、パニックを起こしてアクセルの踏み違えをしたとも考えにくいのですが、社会的な批判も追及もはるかに軽く感じるのは、池袋高齢者暴走事故の被害者が母娘で悲惨さが強烈だったのかと考えます。

　ただ、残された家族の今後の生活を考えると、元東京地検特捜部長の暴走事故は、働き盛りの男性が入院をしていて、退院をする当日にコンビニに買い物に出掛け、その帰り道で亡くなったとのことです。残された家族のこともニュースで少しだけ見たように思いますが、よく憶えていません。

[link:] » 20代女性と早朝ゴルフで「暴走ひき殺し」超有名弁護士・78歳の転落（週刊現代） | 現代ビジネス | 講談社（4/4） https://t.co/s6H5cj2cYJ \n 無論、それ以上に不幸なのは亡くなった堀内さんやその家族、家… https://t.co/mp0DlFzBEE

<hr />

　ざっと目を通したので見落としがあるかもしれないですが、被害者の家族に関する情報は、上記の引用部分のみです。

＜＜＜2019-08-16（金曜日）14：17＿［これまでの記述範囲の終了時刻］＜＜＜

