#+TITLE: "home／a66／a_スクリーンショット／岡口基一裁判官の「最高裁に告ぐ」と、日弁連の憲法ソング「わたしのねがい」から考える告発事件の今後の方針"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-02-18 11:55:26 +0900
FILE_NAME: 2019-02-18-115526_岡口基一裁判官の「最高裁に告ぐ」と、日弁連の憲法ソング「わたしのねがい」から考える告発事件の今後の方針.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  岡口基一裁判官 最高裁 弾劾裁判 三浦義隆弁護士 岡田弁護士
記事タイトル名の文字数：72　保存ファイル名の文字数：73

#contents

* 本日の朝、三浦義隆弁護士のTwitterタイムラインで知った日弁連の憲法ソング「わたしのねがい」
  :LOGBOOK:
  CLOCK: [2019-02-18 月 11:59]--[2019-02-18 月 12:27] =>  0:28
  :END:

＞＞＞2019-02-18（月曜日）11：59＿［これからの記述範囲の開始時刻］＞＞＞

▷ リツイート→lawkus（ystk）＞ipple_apple（متى تنتظر）｜2019/02/18 05:18／2019/02/17 19:11｜https://twitter.com/lawkus/status/1097228843461398528 ／ https://twitter.com/ipple_apple/status/1097076046501896192
&twitter(1097228843461398528){theme:light}
> RT @ipple_apple: 日弁連の作った憲法ソング、くそみたいなポップソングかと思ったら、ジャズ的要素と現代音楽感があってかなりカッコいいのだが。会費かけて作ったことを俺は許すよ。
> https://t.co/yQG3IwKZOo  

　「2019/02/18 05:18／2019/02/17 19:11」という部分の表記がおかしくなっていることに気が付きました。たぶん２月１７日１９時１１分のツイートを２月１８日５時１８分に三浦義隆弁護士がリツイートしたものだと思います。

```
RT lawkus（ystk）｜ipple_apple（متى تنتظر） 日時：2019-02-18 05:18／2019-02-17 19:11 URL： https://twitter.com/lawkus/status/1097228843461398528 https://twitter.com/ipple_apple/status/1097076046501896192
> 日弁連の作った憲法ソング、くそみたいなポップソングかと思ったら、ジャズ的要素と現代音楽感があってかなりカッコいいのだが。会費かけて作ったことを俺は許すよ。 \n https://t.co/yQG3IwKZOo
```

　部分文字列の抜き出しを正規表現で行っていますが、アラビア語のような特殊な文字がプロフィールの名前に含まれているためバイト列の取得がおかしくなったのでしょうか。それにしてもデータの項目自体を別に取得しているようにも思えるので、よくわからない現象です。

　ためしに深澤諭史弁護士のリツイートを１つ、同じくTwitterAPIで取得してみたいと思います。同じ間違いが起こるようならTwitterAPIの仕様における書式が変わったのかもしれず、スクリプトの見直し作業に入ることにします。

▷ リツイート→fukazawas（深澤諭史）＞take___five（中村剛（take-five））｜2019/02/16 21:15／2019/02/16 21:14｜https://twitter.com/fukazawas/status/1096744975935520769 ／ https://twitter.com/take___five/status/1096744671919800321
&twitter(1096744975935520769){theme:light}
> RT @take___five: 貸与制については、給費制世代の人達には「自分達は一番お金が必要な時にお金が支給されず、就活も大変で（特に65〜67期）、それでいて兼業も禁止されて恨み骨髄なんです」ってことをわかってもらえればいいし、貸与制世代の人達には「300〜400万円でい…  

「2019/02/16 21:15／2019/02/16 21:14」という投稿時刻取得の部分は正常でした。これは／で区切った左がリツイートの投稿時刻、右が元のツイートの投稿時刻となっています。よく見ると深澤諭史弁護士の中村剛弁護士のツイートのリツイートは１分後となっていました。

　三浦義隆弁護士は早朝の５時１８分という早い時間に起きていて、Twitterをみながらリツイートをしていたようです。たまたま早く目が覚めるということもあるとは思いますが、弁護士の生活というのも不規則そうに思いました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-18 12:21／2019-02-18 10:05 URL： https://twitter.com/kk_hirono/status/1097335326958247936 https://twitter.com/s_hirono/status/1097301093434875904
&twitter(1097335326958247936){theme:light}
> 2019-02-18-095832_ystkさんがリツイート＞　متىتنتظر（@ipple_apple）：　日弁連の作った憲法ソング、くそみたいなポップソングかと思ったら、ジャズ的要素.jpg https://t.co/a2mXANCUyp
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-18 12:21／2019-02-18 10:05 URL： https://twitter.com/kk_hirono/status/1097335350115000321 https://twitter.com/s_hirono/status/1097301167279767552
&twitter(1097335350115000321){theme:light}
> 2019-02-18-100100_憲法ソング「わたしのねがい」｜日弁連｜　-　YouTube.jpg https://t.co/81IqBgReDw
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-02-18 12:21／2019-02-18 10:06 URL： https://twitter.com/kk_hirono/status/1097335384848003073 https://twitter.com/s_hirono/status/1097301241388879872
&twitter(1097335384848003073){theme:light}
> 2019-02-18-100257_日本弁護士連合会が実施した日本国憲法企画「憲法を詩おう♪コンテスト」の大賞作品に曲を付けて制作した憲法ソングです。.jpg https://t.co/nBE5RPMwic
◁◁◁
<hr />

　上記３点が、日弁連の憲法ソングの存在を私が知った経緯の記録です。憲法については、このあと取り上げていきたいと考えている非常上告との関係もあるので、事実関係をはっきりさせ、明確化しておくために記録を作成し、公開しました。

　これから昼食の支度に取り掛かります。昨日、小木港の東一文字堤防で釣ってきたアジを１つ刺身にし、そのときもらったハタハタを残っていたネギと、土曜日に安売りで買った豆腐で煮付けにする予定です。

＜＜＜2019-02-18（月曜日）12：27＿［これまでの記述範囲の終了時刻］＜＜＜


