#+TITLE: "ツイートをみてかねがね疑問が大きかった向原栄大朗弁護士の法律事務所の所属弁護士が九州大学名誉教授という驚きの発見"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-11 00:44:25 +0900
FILE_NAME: 2019-08-11-004425_ツイートをみてかねがね疑問が大きかった向原栄大朗弁護士の法律事務所の所属弁護士が九州大学名誉教授という驚きの発見.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 向原栄大朗弁護士（福岡県弁護士会） 
記事タイトル名の文字数：56　保存ファイル名の文字数：78

* ツイートをみてかねがね疑問が大きかった向原栄大朗弁護士の法律事務所の所属弁護士が九州大学名誉教授という驚きの発見
  :LOGBOOK:
  CLOCK: [2019-08-11 日 00:45]--[2019-08-11 日 03:41] =>  2:56
  :END:

＞＞＞2019-08-11（日曜日）00：45＿［これからの記述範囲の開始時刻］＞＞＞

　日付が変わり8月11日となっていますが、３つの記事として連続に向原栄大朗弁護士を取り上げました。その過程で一つ忘れていたことですが、独立した記事として記録しておく必要も後から感じたので、忘れていたことが幸いとも思いました。

　これは大学の名誉教授について調べるきっかけともなりました。なんとなくイメージしていた印象とは全然違うもので、職業でもないというのが個人的にかなり大きな驚きの発見でした。

　九州大学はかなり学力が高いとも聞いたことがあります。数年前に女子高生の殺傷事件があってその記事に書いてあったと記憶にあります。その九州大学の名誉教授という弁護士が、向原総合法律事務所の所属弁護士となっていたので、それは目を疑う驚きでした。

　2,3前の記事の部分でも取り上げたと思いますが、私は向原栄大朗弁護士を個人経営の弁護士の一人だと思いこんでいたフシがあります。同様に個人経営と確認した注目弁護士は、割と最近のことですが2人いました。Twitterのプロフィールを引用してご紹介します。

```
中村剛（take-five）
@take___five
弁護士です（66期、東京弁護士会）。元テレビの音効。3級FP技能士、日商簿記2級、介護職員初任者研修修了。介護事故や男女問題、労働事件、著作権（特に映像・音楽）を中心にやっています。 モットーは、素早い対応と依頼者の納得の行く解決。事務所理念は、「クライアントに勇気を与える事務所」。あと、法教育も力を入れています。
p13.bengo4.com/a_13104/l_3393…2011年3月からTwitterを利用しています
473 フォロー中
8,251 フォロワー

［source：］中村剛（take-five）（@take___five）さんの返信があるツイート / Twitter https://twitter.com/take___five/with_replies
```

```
弁護士　戸舘圭之
@todateyoshiyuki
弁護士 戸舘圭之（第二東京弁護士会）袴田事件弁護団、ブラック企業被害対策弁護団副代表、青法協弁学合同部会副議長、ホームレス総合相談ネットワーク、東洋経済オンラインレギュラー執筆者、都立豊多摩高校、静岡大学出身（渕野貴生ゼミ）(link： https：//www.bengo4.com/tokyo/a_13101/l_112740/) bengo4.com/tokyo/a_13101/…
東京 千代田区todatelaw.jp2010年10月からTwitterを利用しています
1,146 フォロー中
3,345 フォロワー
フォローしている人にフォロワーはいません

［source：］弁護士　戸舘圭之（@todateyoshiyuki）さんの返信があるツイート / Twitter https://twitter.com/todateyoshiyuki/with_replies
```

　中村剛弁護士と戸舘圭之弁護士です。まだ一月経っていないと思いますが、個人経営の弁護士事務所らしいということを調べて確認しました。戸舘圭之弁護士は袴田事件の弁護団として、幅広い活動もされているようです。

　もう少し半月から一月前に遡るかと思いますが、気になって調べた鹿児島の男性弁護士についても個人経営の弁護士らしいことを確認したという流れがありました。警察と弁護士の間で歴史的な即席を残した志布志事件に関与した弁護士ですが、名前は思い出せません。

　これから断片的な記録を頼りにGoogleで検索をしてみたいと思います。私のTwilogの方にも記録があるかと思いますので、手がかりを得たらそちらも調べてご紹介します。弁護士脳、弁護士生物の研究成果の発表という意味合いもありますので、大いに参考にしていただきたい資料です。

[link:] » 志布志事件　弁護士 - Google 検索 https://t.co/hiw4RbsEs2

<hr />

[link:] » 志布志事件　弁護人 - Google 検索 https://t.co/PQoyJjNWni

<hr />
[link:] » 冤罪・再審 | 刑事弁護オアシス https://t.co/jvNskuiSIM

<hr />
[link:] » 刑事弁護　オアシス　志布志 - Google 検索 https://t.co/I2z9HDFNcy

<hr />
[link:] » 虚罪―ドキュメント志布志事件 | 朝日新聞「志布志事件」取材班 |本 | 通販 | Amazon https://t.co/9TOjw3rI5c

<hr />
[link:] » えん罪志布志事件　つくられる自白 - 現代人文社 https://t.co/j0nuiinZO9

<hr />
[link:] » 検索結果: 志布志 | 刑事弁護オアシス https://t.co/MSwHRlWMtM

<hr />
[link:] » 突然、裁判長が定年を待たずに退官 | 刑事弁護オアシス https://t.co/XsNgpYjktt

<hr />
[link:] » 突然、裁判長が定年を待たずに退官 | 刑事弁護オアシス https://t.co/XsNgpYjktt \n をさせるため被告人を抑え込もうという意図があるとしか思えない。しかも接見内容を聞き取った調書をもとに、検事は７月３日の第１… https://t.co/afynvisr79

<hr />
[link:] » 野平康博弁護士 - Google 検索 https://t.co/pA0hFTGk7O

<hr />
[link:] » 志布志事件は終わらない / 木村 朗/野平 康博【編著】 - 紀伊國屋書店ウェブストア https://t.co/M4NFaSZELh

<hr />
[link:] » 強姦事件：証拠を都合良く評価…弁護側、ずさん捜査を批判 - 毎日新聞 https://t.co/cvtBSWGwjH \n 弁護団の野平康博弁護士（鹿児島県弁護士会）は１２日の判決後、宮崎市内で記者会見を開き鹿児島県警の捜査を批判した。【志村一也、杣谷健太】

<hr />
[link:] » 弁護士会の読書:天文館強姦えん罪事件報告書 https://t.co/f6fduuGBsI \n （霧山昴）  \n 著者　伊藤　俊介　・　西田　隆二　・　野平　康博ほか　、　非売品

<hr />
[link:] » 突然、裁判長が定年を待たずに退官 | 刑事弁護オアシス https://t.co/XsNgpYjktt \n テーブルの上にあるのは、志布志事件の公判記録。わずか3年足らずの間にここまでの量になった。

<hr />

　最後のツイートとして記録した「テーブルの上にあるのは、志布志事件の公判記録。わずか3年足らずの間にここまでの量になった。」と説明のある写真は、画像が一定間隔で切り替わるものの一つでした。Googleの画像検索から探し出したものですが、見つけ出すのに難儀しました。

　Googleの検索で予備知識はあったものの野平康博弁護士に辿り着くのは容易ではありませんでした。あらためて野平康博弁護士について調べてみます。個人経営の法律事務所の弁護士ということを、前に調べた結果として改めて確認をしておきたいと思います。

[link:] » 野平康博弁護士 - Google 検索 https://t.co/DUwFhcahoV

<hr />
[link:] » 野平 康博弁護士(野平法律事務所)に法律相談 - 鹿児島県鹿児島市、鹿児島市電１系統 朝日通駅 | Legalus https://t.co/JSx0He3eQH

<hr />
[link:] » 野平法律事務所に法律相談 - 鹿児島県鹿児島市、鹿児島市電１系統 朝日通駅 | Legalus https://t.co/7ryCSWFlAd

<hr />
[link:] » 野平康博 弁護士/鹿児島市 - エキテンプロ https://t.co/KrdNPOPUOg

<hr />
[link:] » 野平法律事務所/鹿児島市 - エキテンプロ https://t.co/5skK7kcavp

<hr />
[link:] » 野平法律事務所 - Google 検索 https://t.co/3f0FKjRJGo

<hr />
[link:] » 野平法律事務所 (鹿児島市｜弁護士事務所|電話番号:099-219-1248) - インターネット電話帳ならgooタウンページ https://t.co/DRyr6JM3yW

<hr />
[link:] » 野平法律事務所の店舗情報 | 検索＆口コミ https://t.co/cArHr3cYY6

<hr />
[link:] » 野平法律事務所（鹿児島市/法律事務所）の地図・住所・電話番号｜マピオン電話帳 https://t.co/62ovOGp99g

<hr />
[link:] » 野平法律事務所/鹿児島市名山町｜エキテン https://t.co/1rK8PBvJXk

<hr />
[link:] » 鹿児島県鹿児島市の野平法律事務所 | 弁護士検索サイト https://t.co/glomkLlxQ7

<hr />
[link:] » 電話番号0992191248の相手先は野平法律事務所 https://t.co/DoIl8aoakh

<hr />

　かなり調べまくりましたが、野平法律事務所が野平康博弁護士の個人経営という明確な情報を見つけることは出来ませんでした。所属弁護士に関する情報も一切見つからず、野平康博弁護士の名前一つだけのページもあったので、やはり個人経営の可能性は高いと判断します。

　同様に、中村剛弁護士と戸舘圭之弁護士についても確認をしておきたいと思います。これが確認できれば、個人的な感想ですが、向原栄大朗弁護士が個人経営でなかったという事実が、いっそうきわだつにわかに信じがたい発見となります。

[link:] » 中村剛弁護士 - Google 検索 https://t.co/gSYfw6GA6J

<hr />
[link:] » 中村 剛弁護士（中村総合法律事務所） - 東京都豊島区 - 弁護士ドットコム https://t.co/sq2uFvcKyM

<hr />
[link:] » [B! 弁護士] 中村 剛弁護士（中村総合法律事務所） - 東京都豊島区 - 弁護士ドットコム https://t.co/v7831ll14x

<hr />
[link:] » 中村剛 都民総合法律事務所 | Eight プロフィール https://t.co/LTiYiEURa6

<hr />
[link:] » 中村総合法律事務所 【豊島区の離婚・慰謝料で評判の良い弁護士】 | 離婚弁護士相談広場 https://t.co/vAc7a4WvQJ

<hr />
[link:] » 東京で顧問弁護士をお探しなら、中村綜合法律事務所にご相談を https://t.co/ejC5wRnnVd \n 所長 弁護士 中村 雅男　「法律を駆使し、弁護士17名体制で企業をサポートします」とも。

<hr />
[link:] » 虎ノ門・法律事務所『ヒューマンネットワーク　中村総合法律事務所』 https://t.co/Pvm49mNC5h \n ￼￼弁護士　中村雅人　弁護士　好川久治

<hr />
[link:] » 中村総合法律事務所　中村剛 - Google 検索 https://t.co/36AlG8RVq5

<hr />
[link:] » 中村総合法律事務所 - 弁護士ドットコム https://t.co/ElzwpYaTBp \n 東京都豊島区南池袋2-10-3齋藤ビル3階32 \n 弁護士ドットコム登録弁護士数1名 \n  \n ￼ 中村 剛 弁護士(東京弁護士会)

<hr />

　最終的に東京都豊島区南池袋2-10-3齋藤ビル3階32の中村総合法律事務所だと確認できました。同じ東京都だったと思いますが、同じ様な名前のものが他に２つあって、調べながら途中で混乱しました。この確認作業も容易ではなかったです。

　情報は見当たらないものの多数の事務員を抱えている可能性はあるのかもしれないですが、所属弁護士数1人となっているのに、中村総合法律事務所という名称は違和感を拭えません。向原栄大朗弁護士も向原総合法律事務所となっていたかと思いますがそちらは3人の弁護士がいるらしいと確認しています。

　この中村剛弁護士が先立ったと思いますが、一つのツイートがきっかけで、中村剛弁護士について詳しく知っておきたいと思い調べた結果が、所属弁護士数1人の法律事務所でした。考えてみると事務局長という名称で弁護士ではない可能性も想定されなくはないので、個人経営と断定するには躊躇しました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜take___five（中村剛（take-five）） 日時：2019-08-11 01:55／2019-07-18 23:25 URL： https://twitter.com/kk_hirono/status/1160233291472990208 https://twitter.com/take___five/status/1151860649024053249
&twitter(1160233291472990208){theme:light}
> あらかじめ言っておきますが、京都アニメーション放火事件の被害者の生い立ちとか、被害者がどんな作品作ってたとか、被害者家族の思いとか、全く知らなくていいんで、マスコミの皆さんは被害者の周りを取材することなくそっとしておいてあげてください。お願いします。
◁◁◁
<hr />

　タイムラインを遡って探し出しました。とりわけ強く印象に残っていたツイートでしたが、自作のdpコマンドによる記事の検索としては見つかりませんでした。比較的ツイートの頻度が少ないので、7月18日のツイートをタイムラインから探し出せたのだと思います。

　「% dp -p|grep 中村剛|grep 京都」の検索結果は、やはりありませんでした。間違いなく記録しているはずと思い込んでいただけに、少なからずショックがあります。あらためてまとめ記事を作成しました。ちゃんと出来ているか、これから確認します。

　今度は検索結果が出ました。よかったです。

```
[5291]  % dp -p|grep 中村剛|grep 京都
[link:] 2019年08月11日01時58分の登録： ％@take___five　中村剛（take-five）％あらかじめ言っておきますが、京都アニメーション放火事件の被害者の生い立ちとか、被害者がどんな作品作ってたとか、被 http://hirono2014sk.blogspot.com/2019/08/takefivetake-five.html
```

　警察は組織やチームとして動くもので国家予算や地方税の割当もあるものと思いますが、個人経営の弁護士が、どうしてここまで断定的に「被害者家族の思いとか、全く知らなくていいんで、マスコミの皆さんは被害者の周りを取材することなくそっとしておいてあげてください。お願いします。」なのか。

　不思議でなりませんでした。個人経営の弁護士でも横の繋がりや共同関係はあるとは想像しますが、さらに広げて、弁護士という業界自体に、社会的な責任を改めて問いかけ、追求する用意を記録しておく必要性を痛感しました。

　中村剛弁護士については、ひとまずここまでとし、次に戸舘圭之弁護士について調べますが、アプローチを変えて、Twilogから前に調べた経緯を確かめておきたいと思います。ここにも大きく心を動かされる契機があったと思います。いろいろとありすぎて、記憶に留めるのも難しくはあります。

　かえすがえすも思うのは、弁護士の社会的な存在としての異常性、人間として人として生物学的な特異性です。これほど常識と良心のかけらもない連中が、幅をきかしているのは、原始時代の恐竜を彷彿とさせるものがあります。向こうから返る呪文には中世という言葉もありました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「戸舘圭之」の検索結果 - Twilog https://t.co/VDUrvYvOfA

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:20／2019-08-07 11:44 URL： https://twitter.com/kk_hirono/status/1160239439718653952 https://twitter.com/hirono_hideki/status/1158931871809433600
&twitter(1160239439718653952){theme:light}
> 2019年08月07日09時50分の登録： ＼弁護士　戸舘圭之　@todateyoshiyuki＼返信先: \n@TGN54\nさん\nそういう噂が立つのはある意味勲章だと思いますよ。全件準抗告ねらっていても実際にはいろ https://t.co/qIIBkDtJVO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:20／2019-08-05 17:40 URL： https://twitter.com/kk_hirono/status/1160239530894487552 https://twitter.com/hirono_hideki/status/1158296678857728001
&twitter(1160239530894487552){theme:light}
> 2019年08月05日17時08分の登録： ＼弁護士　戸舘圭之　@todateyoshiyuki＼「人間は他の生物種と比べると、外界や自分の状態の認識において誤ることが圧倒的に多い生物種です。」一川誠「ヒューマンエ https://t.co/jm6ML5D6VV
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:21／2019-07-23 06:33 URL： https://twitter.com/kk_hirono/status/1160239743918981126 https://twitter.com/hirono_hideki/status/1153417847315431424
&twitter(1160239743918981126){theme:light}
> 弁護士　戸舘圭之（@todateyoshiyuki）さん / Twitter https://t.co/ECGbD5RXej
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:21／2019-07-23 06:46 URL： https://twitter.com/kk_hirono/status/1160239760314519552 https://twitter.com/hirono_hideki/status/1153421042750115841
&twitter(1160239760314519552){theme:light}
> 戸舘 圭之弁護士（戸舘圭之法律事務所） - 東京都千代田区 - 弁護士ドットコム https://t.co/HJr0CravLK
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:21／2019-07-23 06:47 URL： https://twitter.com/kk_hirono/status/1160239780220686336 https://twitter.com/hirono_hideki/status/1153421438964998144
&twitter(1160239780220686336){theme:light}
> 弁護士 戸舘圭之のぶろぐ - Yahoo!ブログ https://t.co/6RwHUPnFWE
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:21／2019-07-23 06:53 URL： https://twitter.com/kk_hirono/status/1160239799803863040 https://twitter.com/hirono_hideki/status/1153422968157900801
&twitter(1160239799803863040){theme:light}
> 戸舘圭之法律事務所 | 東京都千代田区麹町 半蔵門 https://t.co/qDpjY0Z00i
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:21／2019-07-23 19:53 URL： https://twitter.com/kk_hirono/status/1160239832435531776 https://twitter.com/hirono_hideki/status/1153619185366233091
&twitter(1160239832435531776){theme:light}
> 2019年07月23日19時26分の登録： ＼弁護士　戸舘圭之　@todateyoshiyuki＼鴨志田先生の講演はじまりました！！ https://t.co/suc4Jb1ciQ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:21／2019-07-21 01:35 URL： https://twitter.com/kk_hirono/status/1160239862764593152 https://twitter.com/hirono_hideki/status/1152617924122697728
&twitter(1160239862764593152){theme:light}
> 2019年07月21日01時30分の登録： ＃弁護士　戸舘圭之　@todateyoshiyuki＃のツイート／2019-07-07_1819〜2019-07-20_1936／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2… https://t.co/NR15P2Rvzl
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:22／2019-07-20 09:25 URL： https://twitter.com/kk_hirono/status/1160239909497524224 https://twitter.com/hirono_hideki/status/1152373865974095874
&twitter(1160239909497524224){theme:light}
> 2019年07月20日01時33分の登録： ＼弁護士　戸舘圭之　@todateyoshiyuki＼そのむかし八王子支部がまだあったころ、勾留決定に対して手元のレポート用紙に手書きで準抗告申立書起案して放り込んだこと https://t.co/ptxArpz4Be
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:22／2019-07-18 21:20 URL： https://twitter.com/kk_hirono/status/1160239942557003777 https://twitter.com/hirono_hideki/status/1151828998827024385
&twitter(1160239942557003777){theme:light}
> 2019年07月18日21時02分の登録： ＼弁護士　戸舘圭之　@todateyoshiyuki＼私もきゅうきょ袴田弁護団を代表して駆けつけます！！ https://t.co/8kSPGnVmh6
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:22／2019-07-15 12:04 URL： https://twitter.com/kk_hirono/status/1160239996156039169 https://twitter.com/hirono_hideki/status/1150602101493383168
&twitter(1160239996156039169){theme:light}
> 2019年07月15日11時57分の登録： ＃弁護士　戸舘圭之　@todateyoshiyuki＃のツイート／2019-07-05_1621〜2019-07-15_0954／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2… https://t.co/kXUlUt24Dh
◁◁◁
<hr />
[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年07月23日 - Twilog https://t.co/uyaSL7dcHW

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:25／2019-07-23 02:49 URL： https://twitter.com/kk_hirono/status/1160240668343599104 https://twitter.com/hirono_hideki/status/1153361462976372736
&twitter(1160240668343599104){theme:light}
> 2019年07月23日02時33分の登録： ％@todateyoshiyuki　弁護士　戸舘圭之％【必見】山本太郎氏の政見放送に称賛の声⇒「感動した」「泣いた」「素晴らしい」（動画17分）#全国から「比例は山本太郎 https://t.co/bvqMqg5Hrw
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-11 02:25／2019-07-23 02:49 URL： https://twitter.com/kk_hirono/status/1160240724643762176 https://twitter.com/hirono_hideki/status/1153361541921529856
&twitter(1160240724643762176){theme:light}
> 2019年07月23日02時39分の登録： ＼弁護士 中村憲昭　@nakanori930＼昨日の山本太郎さんの演説、若い子もたくさん来ていた。もちろん高齢者も。弁護士会の憲法イベントより平均年齢が20歳くらい若い印 https://t.co/8iKRZZh262
◁◁◁
<hr />

　時間を掛けてTwilogのツイートに目を通しましたが、戸舘圭之弁護士について詳しく調べておきたいという動機に繋がった決め手となるようなものは発見に至らず残念でした。やはりこれからは大きく心が動かされたのと同時に、なるべき早い段階で記録化しておく必要を痛感しました。

　遡って捜す手間だけでもまったく馬鹿にならないものがあります。

　長くもありますが、正確な情報の記録として、向原栄大朗弁護士の法律事務所と思われるホームページの「弁護士紹介」という部分を引用しました次になります。

```
弁護士紹介

向原 栄大朗（むこうはら　えいたろう）
略歴
大阪府守口市出身
中央大学法学部法律学科出身
関西大学法務研究科出身
平成19年
弁護士登録（福岡県弁護士会　福岡部会）
同年より鴻和法律事務所にて勤務
平成25年
同事務所を退所し独立、現在の向原総合法律事務所に至る。
プラクティス分野
ほぼすべての法律分野。

民法、会社法を得意専門分野とします。企業法務から個人間の紛争も多数の処理実績があり、比較的大きな倒産・再生案件にも関わっています。
また、労働関係事件や遺言相続も数多く手がけています。
近年では、知的財産権（著作権、商標、不競法が中心。弁理士さんとのコラボレーションも行う）、ITに関する事件（システム開発にまつわる法律問題、情報漏洩に対する対応も含む）の取扱にも力を入れております。
また、刑事事件にも取り組んでおります。ただし裁判員制度には反対の立場です。

法律の分野は、専門性も重要であるものの、法律を扱う上では分野に関係なく普遍的に「事実認定」「論点整理」が何より重要というのが、代表弁護士の考え方です。

著書
弁護士独立のすすめ／弁護士 独立・経営の不安解消Ｑ＆Ａ（第一法令・共著）
講師
社会科等における法律関係授業の実績多数（春日市立春日中学校、春日西中学校、純 真学園短期大学、福岡工業大学付属城東高等学校、福岡県立修猷館高等学校など）
メディア出演実績
KBC「アサデス」、「サワダデース」のコメンテイターとしてのTV番組出演多数（その他、RKBラジオ、FBSにも出演経験あり）
新聞、TV、雑誌におけるコメント・取材協力実績多数

木佐　茂男（きさ　しげお）
略歴
島根県出身
京都大学大学院博士課程単位取得退学
（博士・法学・北海道大学）
昭和57年
北海道大学法学部勤務
（現・名誉教授）
平成12年
九州大学法学研究院勤務
（現・名誉教授）
平成28年
福岡県行政不服審査会会長
主要著書
『人間の尊厳と司法権 ― 西ドイツ司法改革に学ぶ』
日本評論社／1990年
本書が原作となり、記録映画『日独裁判官物語』の監修
『豊かさを生む地方自治 ― ドイツを歩いて考える』
日本評論社／1996年
『わたしたちのまちの憲法 ― ニセコ町の挑戦』（共編）
日本経済評論社／2003年
Internationalisierung von Staat und Verfassung im Spiegel des deutschen und　japanischen Staats- und Verwaltungsrechts
Berlin, Duncker & Humblot／2002（共編）
『国際比較の中の地方自治と法』
日本評論社／2015年
『テキストブック現代司法［第6版］』（共著）
日本評論社／2015年
『司法改革と行政裁判』
日本評論社／2016年
『新版　自治体法務入門［実質・第6版］』（共編）
公人の友社／2016年
『合併をしなかった自治体の実際 －非合併小規模自治体のその後』（監修・著）
（公人の友社、近刊）
『法律学小辞典［第5版］』（有斐閣）77項目担当
新版［第2版］（1994年）以降担当
その他
木佐弁護士のホームページ（http：//tabushi.cafe.coocan.jp/）
木佐弁護士のブログ（http：//tabushi.cocolog-nifty.com/）

牟田 功一（むた　こういち）
略歴
福岡県出身
九州大学法学部出身
西南学院大学法科大学院出身
平成26年
弁護士登録
弁護士登録後，福岡市内の法律事務所に入所し，不動産に関する民事事件，離婚・相続等の家事事件，労働事件（使用者側及び労働者側），債権回収事件等を数多く担当するとともに刑事事件にも積極的に取り組んできました。また，企業法務にも携わり，コンプライアンスに関する助言，契約書のチェックによるリスク回避や損害の軽減を図る法的助言を提供させて頂きました。

これまでに培った経験を活かし，ご相談者様に対し，最適のリーガルサービスを提供させていただきますので，お気軽にご相談ください。

［source：］当事務所について | 福岡で弁護士相談なら「向原総合法律事務所」（知的財産、事業再生、M&A、借金・債務整理など） http://www.mk-law.jp/information/#lawyer
```

　特に代表弁護士というようなものは見当たりませんが、法律事務所名が「向原総合法律事務所」とあり、最初に向原栄大朗弁護士のプロフィールが出てくるので、代表格とみるのが自然でしょう。所長という肩書も私が見た範囲で見当たりませんが、自分の名前を事務所名に冠しています。

　木佐茂男というのが、九州大学名誉教授の弁護士になりますが、経歴に司法修習はみあたりません。大学教授の特例として弁護士になった可能性が考えられますが、だとすればTwitterの弁護士に批判や揶揄が多いテレビの野村修也弁護士とおなじになりそうです。

　この特例というのはすでに廃止となっているのかもしれず、記憶も不確かなので調べておきたいと思います。

[link:] » 特例弁護士 大学教授 - Google 検索 https://t.co/UAhVd8rOQp

<hr />
[link:] » 法務省：弁護士資格認定制度 https://t.co/P7ICPydiIn

<hr />
日本弁護士連合会が実施する指定研修の受講を希望される場合の認定申請期限は，平成３１年５月１７日（金）【郵送の場合は当日必着】　です。平成３１年度指定研修日程：平成３１年８月２０日，２１日及び同年８月２６日から１０月４日まで（８月３… https://t.co/0ppYNjNS9D

<hr />
（＝司法試験に合格した（以下「司法試験合格」といいます。））後に，法５条１号に規定する職（簡易裁判所判事，衆議院議員又は参議院議員，内閣法制局参事官，大学の法律学の教授・准教授等）のいずれかに在った期間が通算して５年以上になること… https://t.co/EgaFYKoU38

<hr />
[link:] » 大学教員、駆け込みで弁護士登録　弁護士法特例廃止前に https://t.co/L5v2WeNlbq

<hr />
[link:] » 法学教授の弁護士資格特例、法改正で廃止へ（読売新聞） https://t.co/IMpKcGMzqO \n 2003年02月05日(水) 03時12分

<hr />

　駆け足で調べたこともあると思いますが、明確でわかりやすい信頼のおける情報が見つかりませんでした。ずっと前に廃止されているという情報もありましたが、平成31年度の情報では、司法試験合格を前提にしていると読めるなど、まあ、わかりやすい情報が見つかりませんでした。

```
資格［編集］
日本では、法科大学院課程を修了し、法務省司法試験委員会が行う司法試験に合格したのちに、司法研修所へ入所して司法修習を修了して弁護士となる者が多くみられる［注 4］。

他に以下の人物に資格がある。

最高裁判所裁判官の職にあった者［注 5］
以下の人物は、日本弁護士連合会の研修を修了して法務大臣がその修了を認定した場合［注 6］に対象となる。

司法試験合格後［注 7］に、国会議員、内閣法制局参事官や、大学で法律学を研究する大学院の置かれているものの法律学を研究する学部、専攻科若しくは大学院における法律学の教授若しくは准教授の職、などに在った期間通算5年以上経験した者
司法試験合格後［注 7］に、公務員や民間人として立法作業や契約書等の作成に従事した期間が通算7年以上経過した者
副検事が特別考査に合格して、検察官（副検事を除く）として5年以上在職した者
経過措置として、司法試験に合格せずとも、2004年4月1日時点で、法律学を研究する学部、専攻科もしくは大学院における、法律学の教授もしくは助教授の職歴を通算5年以上有する者などについては、弁護士資格が与えられた［注 8］。

［source：］弁護士 - Wikipedia https://ja.wikipedia.org/wiki/%E5%BC%81%E8%AD%B7%E5%A3%AB
```

　私はずいぶん前から、司法試験に合格していない大学教授が弁護士になれる道があることをしっていたつもりですが、「経過措置として、司法試験に合格せずとも、2004年4月1日時点で」というのは初めてみかけたと思います。経過措置というのがまず理解に苦しみます。

[link:] » 九州大学（KYUSHU UNIVERSITY） https://t.co/VAXfe7OQIu

<hr />

　Twitterで深澤諭史弁護士に同調するツイートをしている向原栄大朗弁護士の、部下か使用人のような立場で弁護士をする九州大学名誉教授がいたというのは、重ね重ね衝撃の事実でした。社会人としてまともな最低限度の判断が出来るのか、それさえも疑問に思い、社会不安を掻き立てられます。

　そもそも第二東京弁護士会が深澤諭史弁護士のツイートに異常や危機感を感じず、放置するばかりか役職のようなものまで任せているのが、不思議でたまりませんでしたし、これが積年の刑事司法不信の宿痾の一つになっていました。常軌を逸した言動は、悪性の社会的危険性を感じるものです。

　それと同時に、弁護士界という得体の知れない異様な世界を探求するには、いちはやく異変を察知できるカナリア的な存在でもありました。その代表格が、モトケンこと矢部善朗弁護士（京都弁護士会）、小倉秀夫弁護士と並ぶ深澤諭史弁護士です。見方を変えれば救世主的な使者にも見えなくはありません。

　小倉秀夫弁護士は早稲田大学の出身で、中央大学、明治大学、首都大学に講師として働きもしくは働いているという事実があります。深澤諭史弁護士は東京大学大学院の卒業とのことですが、製造物責任法に類似したものとして、これら大学の責任と誇りというのも私はずっと意識して記録をしてきました。

　きわめつけの一つは、ストーカーに関する深澤諭史弁護士のtwitterで、これは弁護士と警察との関係性にも深く根ざす問題であり、法務検察としても深刻に受け止めていただく資料として、私は「奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中」の記録を続けて来ました。

　狂った欲望、というのも深澤諭史弁護士やそれに違和感を感じない弁護士らに共通して感じてきたものです。弁護士の最終進化形が深澤諭史弁護士であるとも指摘してきましたし、深澤諭史弁護士本人も放射能生物質の異変から進化したゴジラ、神を加えたシン・ゴジラを模したアイコンを使っています。

　Twitterのアイコンの形状が正方形ではなくなったので、一部文字が消えた部分もあるようですが、深澤諭史弁護士のシン・ゴジラを模したアイコンには、「ベン・ゴシラ」と書いてあるように読めます。弁護士業界の破滅を告げる鶏の怪物のようにも私には見えます。

　このあとの深澤諭史弁護士のTwitterの動向にさらに注目ですが、そのあたりも踏まえた上で、よくよく観察しながらあるべき刑事司法の未来のために対処をしていただきたいところです。

＜＜＜2019-08-11（日曜日）03：41＿［これまでの記述範囲の終了時刻］＜＜＜

