#+TITLE: "弁護士が金目当て、そういう事件に限って、という深澤諭史弁護士のツイートと向原栄大朗弁護士の現象に名前という返信"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-10 14:07:23 +0900
FILE_NAME: 2019-08-10-140723_弁護士が金目当て、そういう事件に限って、という深澤諭史弁護士のツイートと向原栄大朗弁護士の現象に名前という返信.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 向原栄大朗弁護士（福岡県弁護士会）  深澤諭史弁護士（第二東京弁護士会） 福岡県弁護士会
記事タイトル名の文字数：55　保存ファイル名の文字数：77

* 弁護士が金目当て、そういう事件に限って、という深澤諭史弁護士のツイートと向原栄大朗弁護士の現象に名前という返信
  :LOGBOOK:
  CLOCK: [2019-08-10 土 14:09]--[2019-08-10 土 17:42] =>  3:33
  :END:

＞＞＞2019-08-10（土曜日）14：09＿［これからの記述範囲の開始時刻］＞＞＞

5678： 再審制度の制度趣旨を没却する最高裁判所の大崎事件第三次再審請求棄却決定に対し抗議する会長声明（福岡県弁護士会） http://bit.ly/2yO6zgZ

　上記の投稿済み記事の作成中になりますが、香川県観音寺市の中野俊徳弁護士が鹿児島修習だったというプロフィール情報を見て、向原栄大朗弁護士のことを思い出し、Twitterのページを開いたように思います。

　向原栄大朗弁護士のタイムラインを遡ることで見つけたのが、標題に据え記録とする深澤諭史弁護士のツイートに対する向原栄大朗弁護士の返信ツイートになります。深澤諭史弁護士のツイートは昨日に見かけていたように思いますが、毎度のこととして特に重視はしていませんでした。

　まずスクリーンショットの記録として、経過を記録しておきたいと思います。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 14:17／2019-08-10 14:10 URL： https://twitter.com/kk_hirono/status/1160057502404243456 https://twitter.com/s_hirono/status/1160055714896678912
&twitter(1160057502404243456){theme:light}
> 2019-08-10-140249_深澤諭史さんはTwitterを使っています：　「自分の気にくわない裁判を扱う弁護士を、食えない、底辺の弁護士が金目当てで、ってよく聞くけれども、　そういう.jpg https://t.co/E9Kx4YxBmm
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 14:17／2019-08-10 13:27 URL： https://twitter.com/kk_hirono/status/1160057521492463619 https://twitter.com/s_hirono/status/1160045037838667777
&twitter(1160057521492463619){theme:light}
> 2019-08-10-132338_向原総合法律事務所　弁護士向原さんはTwitterを使っています：　「@fukazawas　そういう現象に名前をつけたいです（＾＾）」　／　Twitter.jpg https://t.co/7F45qZGWPO
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 14:18／2019-08-08 22:20 URL： https://twitter.com/kk_hirono/status/1160057847209549824 https://twitter.com/s_hirono/status/1159454412030402562
&twitter(1160057847209549824){theme:light}
> 2019-08-08-221844_深澤諭史さんはTwitterを使っています：　「自分の気にくわない裁判を扱う弁護士を、食えない、底辺の弁護士が金目当てで、ってよく聞くけれども、　そういう.jpg https://t.co/DJy6DKZ7ei
◁◁◁
<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-10 14:21／2019-08-08 19:47 URL： https://twitter.com/kk_hirono/status/1160058505593647104 https://twitter.com/fukazawas/status/1159415854947155968
&twitter(1160058505593647104){theme:light}
> 自分の気にくわない裁判を扱う弁護士を、食えない、底辺の弁護士が金目当てで、ってよく聞くけれども、 \n  そういう事件に限って、実は経済的に全然ペイしないことが多い。 \n  セクハラ、パワハラ、性犯罪、労働、医療、家事とか。 \n  （・∀・；）
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜wata_nabekyo_ko（なべきょう＠過眠症） 日時：2019-08-10 14:21／2019-08-08 19:48 URL： https://twitter.com/kk_hirono/status/1160058542503542790 https://twitter.com/wata_nabekyo_ko/status/1159416098518732802
&twitter(1160058542503542790){theme:light}
> @fukazawas 生活保護申請援助も入れてくださいな
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜harrier0516osk（向原総合法律事務所　弁護士向原） 日時：2019-08-10 14:21／2019-08-08 23:00 URL： https://twitter.com/kk_hirono/status/1160058563856723968 https://twitter.com/harrier0516osk/status/1159464372491583488
&twitter(1160058563856723968){theme:light}
> @fukazawas そういう現象に名前をつけたいです(^^)
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜nekonikoban5656（にゃるる） 日時：2019-08-10 14:21／2019-08-09 05:40 URL： https://twitter.com/kk_hirono/status/1160058621008367616 https://twitter.com/nekonikoban5656/status/1159565062425571328
&twitter(1160058621008367616){theme:light}
> @harrier0516osk @fukazawas いや店本当に凄いみたいな弁護士も居まして友人が交通事故の裁判(判決まで4回)だけで5000万支払う事になり手元からガッツリ引かれたり、借金の返済を相手がしないので裁判するのに3… https://t.co/WMDtWutlv6
◁◁◁
<hr />

　上記４件は、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)でログインした状態でのリツイートになります。当然、ブロックされていれば出来ないことです。

　メインの深澤諭史弁護士のツイートですが、面白い日本語の文章になっていると思います。（自分の気に食わない裁判を扱う弁護士　＝　底辺の弁護士が金目当て）　＝　（経済的にペイしない）　＝　（セクハラ、パワハラ、性犯罪、労働、医療、家事とか）ってな構造です。

　聞くという日本語は、新聞もそうですが見るとか読むという意味もあろうかと思います。「よく」という事柄を強調する言葉も深澤諭史弁護士のツイートではとてもよく見かけてきたものです。

　「セクハラ、パワハラ、性犯罪、労働、医療、家事とか」と列挙するのが、不採算で割の合わない弁護士の仕事のようですが、これに含まれない弁護士の仕事というのが何かと考えます。家事とあるのは家庭裁判所に継続する案件と考えられるので、離婚や相続もそうかと思われます。

　明らかに含まれていないと思われるのは、過払い金に代表される借金問題ぐらいでしょうか。契約書の作成なども弁護士の業務になるとは思いますが、最近は見かけなくなった渉外弁護士は高収入だという話は見かけていました。しかし、それも１０年近く前のことかと思います。

　よくみると深澤諭史弁護士の列挙に名誉毀損は含まれていないようです。２，３日前になりますが、その名誉毀損に関して深澤諭史弁護士の気になるツイートとリツイートを見かけていました。

　名誉毀損の場合、弁護士が不採算かどうかという前に、依頼者にとって負担が大きく実入りの乏しい裁判だとは聞きます。今でもIPアドレスの特定に、ずいぶんと手間と負担がかかるようですが、サーバーでログを見てきたこともあり、このからくりは何なのかとずっと不思議に思ってきました。

　向原栄大朗弁護士の深澤諭史弁護士に肯定的で同調的なツイートというのは、これまでにもちょいちょいと見かけてきました。重箱の隅をつつくような感覚もあったので、いちいちは取り上げてこなかったですが、今日は福岡県弁護士会の大崎事件の批判声明から見方が変わりました。

　深澤諭史弁護士は、弁護士として成功をおさめ順風満帆で躍進を続けているという印象があります。私にはそれが不思議でならず、まるで自作自演の漫画の主人公をみるような気分でした。とりわけ強いイメージが東大一直線という昭和５０年代の漫画で、その舞台も九州の福岡でした。

　弁護士らの生態を観察していると、不思議や奇異に感じるのは深澤諭史弁護士に限ったことではありません。向原栄大朗弁護士のツイートからは深澤諭史弁護士に対し同志のような親近感も感じてきましたが、その向原栄大朗弁護士その人にも、目を疑う事実が存在したのです。

　弁護士会に対する不満も多い向原栄大朗弁護士のツイートでしたが、それも心労を重ねてあえぐ愚痴のようなものではと、距離をおいて見るところがありました。一種の現実逃避であり、希望的観測であるという要素です。それで深澤諭史弁護士が頼もしく見えるのかとも考えてきました。

　今日は久しぶりに向原栄大朗弁護士の法律事務所のホームページを閲覧しました。あらためて事務所名を見ると向原総合法律事務所とあったので、多少違和感を感じました。

　前に向原栄大朗弁護士のホームページをみたのは思い出せないぐらい前のことです。もとは福岡の家電弁護士などというブログがあって、それはまだ羽咋市に住んでいた２００９年３月より前に見かけていたように思います。Twitterのアカウントを知るより前のことです。

```
2010-03-16 19：15：37
テーマ：ブログ
ブログをはじめることにしました。

テーマなど細かいことは何も決めていません。

日常のこと、役に立ちそうなこと、いろいろと試行錯誤しながら

書くことになると思いますが、よろしくお願い致します。

［source：］はじまりはじまり | 向原総合法律事務所／福岡の家電弁護士のブログ https://ameblo.jp/mukoyan-harrier-law/entry-10483435363.html
```

　アメブロ（アメーバブログ）という記憶はあったのですが、Googleで調べるとブログは存在していました。デザインはいくらか印象が違っています。上記の２０１０年３月１６日の記事が初投稿のようなので、２００９年３月以前というのは私の記憶違いだったようです。

```
2016-10-19 14：34：07
テーマ：ブログ
長年に渡って書き貯めてまいりましたのこのブログですが、この度、リニュアールにより、引っ越すことにしました。

新しいブログのアドレスは以下のとおりです。

http：//www.mk-law.jp/

の下部にある「福岡の家電弁護士のブログ」欄からリンク

 

なお直リンは以下

http：//www.mk-law.jp/blog/

 

ぜひ今後ともご愛顧のほどをよろしくお願い申しあげます。

［source：］ブログをお引越しさせていただきます | 向原総合法律事務所／福岡の家電弁護士のブログ https://ameblo.jp/mukoyan-harrier-law/entry-12211181751.html
```

　上記がアメブロで最後の投稿記事となっており、日付が２０１６年１０月１９日とあります。これも見覚えのある記事でした。「福岡の家電弁護士のブログ」という名称もホームページで引き継いでいるようですが、家電製品に関する記事やツイートは見かけた憶えがなく、不思議に感じていました。

　Twitterのプロフィールにも「天神駅から最も近い法律事務所」とありますが、天神は福岡市内で一番大きな町だと聞いたことがありました。長距離トラック運転手の仕事で長浜の魚市場に行っていた頃のことです。３０年ほど前にはなります。

　テレビで福岡市の天神という地名を見ることはあまりないと思いますが、中心部で最も活気のある若者の街というイメージがあり、現地でそのように話を聞いていました。特に調べるなどして確認はしていません。繁華街の知名度としては中洲の方が知られているかとは思います。

```
百貨店やファッションビルなどの商業施設が高度に集積した九州最大の繁華街である。福岡市の中心業務地区でもある。博多駅周辺から福岡市地下鉄で数分の距離にあり、博多との間には全国的にも有名な歓楽街の中洲・南新地がある。

［source：］天神 (福岡市) - Wikipedia https://ja.wikipedia.org/wiki/%E5%A4%A9%E7%A5%9E_(%E7%A6%8F%E5%B2%A1%E5%B8%82)
```

　調べると、上記の引用のとおり、九州最大の繁華街とありました。福岡の裁判所は長浜の魚市場の近くにあると後に知りましたが、数年前に他の場所に移転したという話です。Googleマップで場所を確認しましたが、あまりピンとくるような場所ではなかったと思います。

　もう２年ほど前になりますか、たしか福岡高検の幹部のような人が、若い女性の車にはねられて死亡するという事故のニュースがありました。その頃は、まだ魚市場の近くだったように思います。

　その長浜の魚市場の周辺というのもGoogleマップのストリートビューで見たことがありますが、まるっきり印象が変わっていました。私が行っていたのは昭和の終わりから平成の初め、正門前にはカモメ会館というパチンコ店があり、通っている頃いつの間にかセブンイレブンの店が出来ていました。

　向原栄大朗弁護士ですが、大阪府の出身で、司法修習生として鹿児島修習のあと、福岡市で弁護士をするようになったという情報を読んだと記憶にあります。それも九州最大の繁華街ともいわれる天神の駅から一番近い法律事務所とあるのですから、サクセスストーリーにも思えました。

　記憶があやふやになっていますが、他の人数の多い法律事務所から独立するかたちで開業したという情報も見かけたような記憶が残っていて、詳しくは思い出せないですが、記事を読んだ時の印象としていわゆる一匹狼のような存在感がありました。

　次に向原栄大朗弁護士について情報を見たのは、佐藤大和弁護士に賛同して芸能人の権利を守る団体に参加表明したというような話でした。調べればみつかると思いますが、向原栄大朗弁護士本人がなぜか積極的にその情報を出していないという印象もありました。

[link:] » 向原栄大朗弁護士 佐藤大和弁護士 - Google 検索 https://t.co/jmgvo6B90q

<hr />

[link:] » 向原栄大朗と弁護士法人ALAW&amp;GOODLOOP [無断転載禁止]©https://t.co/o2XXIep9cb https://t.co/35qG65WbRq

<hr />

　無断転載禁止と大書きしてあるので引用は控えましたが、向原・川上総合法律事務所は2016年10月に向原弁護士一人の向原総合法律事務所とALAW&GOODLOOPに分かれ、元のメンバーは全員後者に移籍したとあります。２０１５年よりずっと前のことかと思っていました。

```
会見には、同協会の共同代表理事を務める弁護士の望月宣武氏、向原栄大朗氏、安井飛鳥氏、河西邦剛氏、佐藤大和氏が出席。

［source：］芸能人の駆け込み寺「日本エンターテイナーライツ協会」発足 「対立でなく、芸能人と事務所の架け橋になりたい」 | ザ・リバティweb https://the-liberty.com/article.php?item_id=13110
```

　上記の引用は２０１７年６月１０日付の記事となっています。望月宜武弁護士は設立当初のメンバーとして私の記憶になかったのですが、愛媛の農業アイドルの自殺問題では中心的な存在となっていたので、なるほどと思いました。以外に感じたのは安井飛鳥弁護士が参加していたことです。

　確認する必要がありますが、安井飛鳥弁護士はTwitterアカウントとして見かけてきましたが、何というのか児童支援や心理学的サポートを中心としている印象で、他の弁護士とは一線を画し、独自の道を進んでいるという印象でした。バイク好きを表明しているはずかと思います。

```
飛鳥＠1/18,19 ラブライブフェス現地（願望）
@kiwi250r
ブロックされています
@kiwi250rさんのフォローやツイートの表示はできません。詳細はこちら

［source：］(3) 飛鳥＠1/18,19 ラブライブフェス現地（願望）（@kiwi250r）さん / Twitter https://twitter.com/kiwi250r?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
```

　告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)にログインした状態ですが、ブロックされています、と出てきました。安井飛鳥という名前は見当たらないですが、Googleの検索結果にあったので、本人の可能性が高そうです。

```
飛鳥＠1/18,19 ラブライブフェス現地（願望）
@kiwi250r
千葉県民。ライダーだったり、フォトグラファーだったり、ソーシャルワーカーだったり、ロイヤーだったり、エンターテイナーだったり、クリエイターだったり、旅人だったり、アニメオタクだったり。子ども・若者に関わる分野がライフワーク。 はざまのひと。弁護士法人ソーシャルワーカーズ副代表。ERA共同代表理事。永遠のワグナー。
swrs.jp2010年6月からTwitterを利用しています
3,262 フォロー中
3,816 フォロワー

［source：］飛鳥＠1/18,19 ラブライブフェス現地（願望）（@kiwi250r）さん / Twitter https://twitter.com/kiwi250r?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
```

　上記のTwitterのプロフィールを引用しました。「弁護士法人ソーシャルワーカーズ副代表」とあります。前にも見ていたと思いますが、どうもこれが所属する法律事務所の弁護士法人名のようです。数年前に見たプロフィールの内容とは違いがあるのかも知れません。

```
■福祉分野の専門家■ 福祉職の技術と経験を活かして福祉的な配慮が必要なDV事件や子ども、障がい者、高齢者の問題に注力しています。法律と福祉の両面から真の意味で皆さまに寄り添います。
　私は、学童保育の指導員経験を有し、現在も弁護士の他に社会福祉士・精神保健福祉士の資格を活かして子ども、障がい者、高齢者といった福祉的な支援が必要な方の事件を中心に取り扱っています。

　法律により解決可能な事柄には限りがあり、法律によって権利が守られたとしても、その方の生活上の悩みや問題までは解決ができません。しかし、本当にその人の悩みや問題について解決を目指すのであれば法律面のみならずこうした生活面の課題についても寄り添っていかなければいけないと考えています。
　私は、福祉職としての経験や技術を活かして相談者に寄り添い、福祉的な生活上の悩みや問題の解決についてもお手伝いします。

　・お子さんの養育や非行で不安をお持ちの方
　・障がい等の関係でコミュニケーションが苦手な方
　・高齢の家族の介護にお悩みの方

　皆さんの『良き隣人』として皆さんが抱える問題や悩み事のより良い解決のお手伝いをします。普通の弁護士事務所とは一風変わったカフェのような事務所ですが、お困りのことがあればお気軽にご相談ください。

※児童相談所での勤務も行っている関係で、児童相談所を相手方とする相談・依頼（保護された子どもの引渡交渉等）についてはお受けすることができません。

［source：］安井 飛鳥弁護士（弁護士法人ソーシャルワーカーズ千葉支所法律事務所くらふと） - 千葉県千葉市 - 弁護士ドットコム https://www.bengo4.com/chiba/a_12100/g_12101/l_197879/
```

　より適切な言葉が思い出せなかったのですが、「福祉分野の専門家」と紹介されているようです。「福祉職の技術と経験を活かして」ともあります。「現在も弁護士の他に社会福祉士・精神保健福祉士の資格を活かして」とより具体的なことも記載がありました。

　なにか心理学的なイメージが頭に残っていたのですが、「精神保健福祉士」というのは余り見かけなかったようにも思います。そういえば、昨夜、久しぶりの小木港のアジ釣りから戻ると、テレビで四国中央市の病院での刺傷事件の報道がありました。

　たしか内科もありましたが、精神科などという看板も一緒にクローズアップされていました。横浜の方でも通り魔的な刺傷事件があって、犯人が確保されてないとも出ていたと思いますが、午前中に見ていたテレビでは、どちらもニュースや報道を見ていなかったように思います。

　時計をみると１６時０７分でしたが、１１時前にテレビを消してから一度もつけていません。刺傷事件のことは、ネットでも情報を見ていないように思います。昨夜はテレビに森友学園の捜査終結というニュースもありましたが、Twitterのトレンドでも森友は見ませんでした。

　逆にTwitterのトレンドで知り、ネットでしか情報を見ていないニュースがあって、それが児童福祉に関する事件でした。それも本当なのかと思うような創作の漫画のような内容の事件です。

[link:] » 四国中央市 病院 事件 - Google 検索 https://t.co/gWD6XDHT1G

<hr />
[link:] » 四国中央市土居町の松風病院で殺人未遂事件 刃物男が男性3人を刺傷 | ニュース速報Japan https://t.co/miedq5A7wE

<hr />
[link:] » 横浜　通り魔　事件 - Google 検索 https://t.co/nxztBzvnMm

<hr />
[link:] » 横浜の通り魔事件で、近くに住む容疑者逮捕　県警（カナロコ by 神奈川新聞） - Yahoo!ニュース https://t.co/hN8mA9eRFq

<hr />
[link:] » 水戸　事件 - Google 検索 https://t.co/RNW9ddCN4T

<hr />
[link:] » 水戸署員の拳銃抜き取る　児相でトラブルの家族５人逮捕 - 産経ニュース https://t.co/Rp6TGfTum8

<hr />
[link:] » 警察官が拳銃一時奪われる　児相トラブル対応中　公務執行妨害容疑で逮捕　水戸 - 毎日新聞 https://t.co/6GI0Py7j4D

<hr />

　児相というのは児童相談所のことだと思いますが、これも深澤諭史弁護士の分類では家事事件に入るのかと考えました。記事には「児童の保護に納得しない親や関係者が暴れている」とありますが、親権や連れ去りに関してどうかと考えさせられる深澤諭史弁護士のツイートやリツイートも見かけてきました。

　現在データベースに登録済みの範囲で、深澤諭史弁護士のツイートのまとめ記事を２つ作成しました。キーワードは「親権」と「連れ去り」です。どちらも思っていたよりは該当の少ない結果でした。

[link:] 2019年08月10日16時22分の登録： REGEXP：”親権”／深澤諭史（@fukazawas）の検索（2016-03-23〜2019-06-19／2019年08月10日16時22分の記録27件） http://hirono2014sk.blogspot.com/2019/08/regexpfukazawas2016-03-232019-06.html

[link:] 2019年08月10日16時23分の登録： REGEXP：”連れ去り”／深澤諭史（@fukazawas）の検索（2016-05-11〜2019-06-07／2019年08月10日16時22分の記録15件） http://hirono2014sk.blogspot.com/2019/08/regexpfukazawas2016-05-112019-06.html

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-10 16:29／2018-10-10 09:26 URL： https://twitter.com/kk_hirono/status/1160090663381135360 https://twitter.com/fukazawas/status/1049818418256343040
&twitter(1160090663381135360){theme:light}
> 婚姻関係の継続，子の親権や監護権を巡る争いは，弁護士法７２条にいう法律事件ですし，これについて，自ら代理し，あるいは書面を作成しなくても，執るべき法的措置について，最適なものを選んで指南する行為は，法律事務である「鑑定」に該当するので，非弁行為に該当します。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-10 16:30／2019-06-11 13:21 URL： https://twitter.com/kk_hirono/status/1160090946152759296 https://twitter.com/fukazawas/status/1138300273460310016
&twitter(1160090946152759296){theme:light}
> @ryouheitakaki 共同親権って、私的には理論的だと思うんですよ。夫婦はやめても親子はやめないわけですから。 \n  でも、賛同者の言動に鑑みるに、これを認める弊害が大きすぎると思います。 \n  共同親権という制度は、反対者の言動より… https://t.co/DgIczklPkz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-10 16:30／2019-06-19 18:07 URL： https://twitter.com/kk_hirono/status/1160091040503586818 https://twitter.com/fukazawas/status/1141271182999580674
&twitter(1160091040503586818){theme:light}
> 共同親権制度を主張する方々は、なんであんなに攻撃的、恫喝的なんだろう・・・。 \n  ひょっとして、反対者のネガティブキャンペーン？自作自演かも？っておもってしまうほど。 \n  （・∀・；l）
◁◁◁
<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜fukazawas（深澤諭史） 日時：2019-08-10 16:32／2017-09-03 12:56 URL： https://twitter.com/kk_hirono/status/1160091430175432705 https://twitter.com/fukazawas/status/904191274118291458
&twitter(1160091430175432705){theme:light}
> そこから \n  「信頼関係に基づいて殴ってた！暴力はしていない！」 \n  「それなのにＤＶをでっち上げられた！」 \n  「子どもとも信頼関係があったから，一生懸命殴っていたのに，連れ去られたー！」 \n  「司法は連れ去り肯定だー！ネットで運動するぞー！」 \n  につながるんですよね。分かります。 \n  ＲＴ
◁◁◁
<hr />

　弁護士が入ることでこじれるという話は、近年ちょいちょいと見かけていますが、侮蔑的であったり挑発的と感じる弁護士のツイートはよくみかけるものです。その代表的なワードに「モラ夫」があります。一月より前だったと思いますが、モトケンこと矢部善朗弁護士（京都弁護士会）も使っていました。

[link:] 2019年08月10日16時36分の登録： REGEXP：”モラ夫”／深澤諭史（@fukazawas）の検索（2017-04-14〜2019-06-06／2019年08月10日16時36分の記録15件） http://hirono2014sk.blogspot.com/2019/08/regexpfukazawas2017-04-142019-06.html

[link:] 2019年08月10日16時37分の登録： REGEXP：”モラ夫”／モトケン（@motoken_tw）の検索（2017-09-28〜2019-06-28／2019年08月10日16時37分の記録27件） http://hirono2014sk.blogspot.com/2019/08/regexpmotokentw2017-09-282019-06.html

　何かの対戦ゲームではないですが、深澤諭史弁護士よりモトケンこと矢部善朗弁護士（京都弁護士会）の方が２７対１５で多いとは意外な結果でした。あくまでデータベースに登録した数であり、Twitterの検索の精度も低いので、あくまで参考までのデータです。

▷ リツイート→fukazawas（深澤諭史）＞Miyako_Koji（弁護士 都  行志）｜2017/09/20 09:23／2017/09/20 07:09｜https://twitter.com/fukazawas/status/910298323218657280 ／ https://twitter.com/Miyako_Koji/status/910264587215282176
&twitter(910298323218657280){theme:light}
> RT @Miyako_Koji: ツイッターでモラ夫とか言って、夫婦の関係を煽るツイートを繰り返す弁護士がいるが、違和感しか感じない。夫婦関係は一様ではなく、それぞれ何かしらの問題を抱えて弁護士のところに相談に来られる。徒らに関係を煽ると解決する事件も解決しないのではないか。紛…  

　こういうリツイートも深澤諭史弁護士のタイムラインにあったのかと思いました。元のツイートもリツイートも２０１７年９月２０日となっています。

▶ ツイート％motoken_tw（モトケン）％2019/06/21 12:36％ https://twitter.com/motoken_tw/status/1141912703121776641
&twitter(1141912703121776641){theme:light}
> モラ夫氏は、自分が絶対的に正しいと思っているから弁護士に相談したりしない。
> モラ夫氏の妻は、何かを起こすときには弁護士に相談する。
> 妻側弁護士は使える法的手段は全て使う。
> モラ夫氏は自分が絶対的に正しいと思ってるから、裁判所が妻側… https://t.co/uq5pmpgrlz  
▶

　繰り返しデータベースに登録済みの範囲ですが、モトケンこと矢部善朗弁護士（京都弁護士会）本人のツイートで「モラ夫」を含むものは、上記が初出となります。今年の６月２１日のツイートです。このあと短期集中していたとも思います。近い時期には「安全ピン」もありました。

▶ ツイート％motoken_tw（モトケン）％2019/06/28 16:09％ https://twitter.com/motoken_tw/status/1144503110326292480
&twitter(1144503110326292480){theme:light}
> @gjP0WHxoicHgrtO 何の根拠もなく特定の個人を公の場で「モラ夫」と呼べば侮辱だろうな。
> なお、私は何の根拠もなく特定の個人を「モラ夫」と呼んだことはない。  
▶

　上記が最後に出てきたモトケンこと矢部善朗弁護士（京都弁護士会）のモラ夫をキーワードに含むツイートになります。２０１９年６月２８日１６時０９分です。初出のものが６月２１日だったので、１０日ほどの間に嵐のように集中していたようです。挑発を超え暴虐な攻撃性を感じる内容です。

　ついでに「安全ピン」もやっておきましょう。痴漢を撲滅するのが目的とも打ち上げを行っていたかと思います。それが弁護士の仕事なのかという疑問もありました。

[link:] 2019年08月10日16時54分の登録： REGEXP：”安全ピン”／モトケン（@motoken_tw）の検索（2019-05-23〜2019-06-12／2019年08月10日16時54分の記録47件） http://hirono2014sk.blogspot.com/2019/08/regexpmotokentw2019-05-232019-06.html

　リツイートが多いのかと想像していたのですが、まとめ記事を見ると、私の見落としがない限り全てがモトケンこと矢部善朗弁護士（京都弁護士会）本人のツイートでした。次が最後のものとなります。言い換えれば２０１９年５月２３日に始まり６月１２日に終わっています。

▶ ツイート％motoken_tw（モトケン）％2019/06/12 19:16％ https://twitter.com/motoken_tw/status/1138751899635601410
&twitter(1138751899635601410){theme:light}
> @ki84type4 安全ピンのない痴漢冤罪事件の方がはるかに多いんだから、今まで提案されている自己防衛手段をお勧めする。  
▶

　ちょっと忘れていたように思いましたが、弁護士ドットコムのニュース記事にもなっていたようです。

▶ ツイート％motoken_tw（モトケン）％2019/06/10 10:20％ https://twitter.com/motoken_tw/status/1137892317010964480
&twitter(1137892317010964480){theme:light}
> 痴漢に安全ピンで抵抗した被害者を無償で弁護、 Twitterきっかけに弁護団結成|弁護士ドットコムニュース https://t.co/4B8rN9v0Z4 @bengo4topicsさんから  
▶

　記事には見出しに弁護団結成とありますが、一人として依頼者があったという話は見ていなかったように思います。

　どうも弁護団の活動として、呼びかけは現在も継続中のようです。トラブルを誘発させるリスクのようなものも当初より感じてはいましたが、安全ピンというワードも全く見かけなくなっていたので、終わったものと思っていました。

```
このサイトについて
 投稿日： 2019年6月6日 2019年6月8日  投稿者： anzenpin
安全ピントラブル対策弁護団の設立趣旨
当弁護団は、痴漢の被害に遭われた方（以下「被害者」といいます）が、ご自分に対する痴漢行為を停止・終了させるために安全ピンを用いて反撃し、それがもととなって法的トラブルに巻き込まれた場合に、そのトラブルに対し弁護団員が適切な弁護を行うことによって、今後の痴漢行為を未然に防止し、もって被害を撲滅するために設立したものです。

［source：］安全ピントラブル対策弁護団 – 痴漢撲滅 https://anzenpin.jtwla.com/
```

```
管理者の紹介
 投稿日： 2019年6月7日 2019年6月7日  投稿者： anzenpin
発起人
大阪名物パチパチ弁護士 @obpmb3fN93mQI9i

ツイッターの匿名アカウントですが、下記実名弁護士が弁護士であることを確認しております。

弁護団代表
高木良平　（第二東京弁護士会　所属）

ウェブサイト管理者
矢部善朗　（京都弁護士会　所属）

［source：］管理者の紹介 – 安全ピントラブル対策弁護団 https://anzenpin.jtwla.com/%e7%ae%a1%e7%90%86%e4%ba%ba/
```

　すっかり忘れていたように思ったのですが、ウェブサイト管理者にモトケンこと矢部善朗弁護士（京都弁護士会）の名前があります。

　ずいぶん前になりますが、BINDでネームサーバーをやっていたときのことを思い出し、ドメインの前の方を削除してみたところ、次のページが出現しました。アソシエーションが何か思い出せないですが、日本Twitter法律家アソシエーションという意味があるようです。

```
JTWLA
Japan Twitter Lawyers Association
サンプルページ
公開準備中
 motoken2019年6月4日7件のコメント
関連サイト
 motoken2019年6月4日
架空請求詐欺撲滅

［source：］JTWLA – Japan Twitter Lawyers Association https://jtwla.com/
```

　リンクをたどると一つ次の記事がありました。他は試験運用中途でもいった感じでした。

```
 投稿日： 2019年6月4日 2019年6月4日  投稿者： motoken
訴訟通告を装った請求文書が送られて来ることがありますが、身に覚えのない請求は架空請求と思って間違いありません。

裁判所から送られてきた書面は無視してはいけませんが、裁判所から送られてきたように装って架空請求をしてくる詐欺行為は無視するに限ります。

しかし、架空請求か本当に裁判所から来たものかわからない場合は、無料相談でもいいですから弁護士に確認しましょう。

無料相談を受けることが困難な場合は、ツイッターで質問してみましょう。

弁護士がすぐに判断してくれます。

決して早まって書面に書いてある電話番号に電話をしてはいけません。

架空請求書の例をグーグルで検索してみました。

［source：］架空請求に騙されない。 – その訴訟通告は嘘です！ http://kakuseikyu.jtwla.com/2019/06/04/%e6%9e%b6%e7%a9%ba%e8%ab%8b%e6%b1%82%e3%81%ab%e9%a8%99%e3%81%95%e3%82%8c%e3%81%aa%e3%81%84%e3%80%82/
```

　架空請求というのはモトケンこと矢部善朗弁護士（京都弁護士会）のTwitterのタイムラインで余りみてこない気がしました。少なくとももう２件ぐらいはモトケンこと矢部善朗弁護士（京都弁護士会）と深澤諭史弁護士と小倉秀夫弁護士のツイートを全てデータベースに登録するようにしています。

[link:] 2019年08月10日17時21分の登録： REGEXP：”架空請求”／モトケン（@motoken_tw）の検索（2016-08-26〜2019-06-05／2019年08月10日17時21分の記録8件） http://hirono2014sk.blogspot.com/2019/08/regexpmotokentw2016-08-262019-06.html

　架空請求の被害者が相談するのは警察であり、弁護士に相談してどんな解決がのぞめるのか想像が及ばないと思いました。当然に相談料なり報酬も発生することでしょう。

　つぎが本項目でメインとした深澤諭史弁護士のツイートの内容になります。

▶ ツイート％fukazawas（深澤諭史）％2019/08/08 19:47％ https://twitter.com/fukazawas/status/1159415854947155968
&twitter(1159415854947155968){theme:light}
> 自分の気にくわない裁判を扱う弁護士を、食えない、底辺の弁護士が金目当てで、ってよく聞くけれども、
> そういう事件に限って、実は経済的に全然ペイしないことが多い。
> セクハラ、パワハラ、性犯罪、労働、医療、家事とか。
> （・∀・；）  
▶

[link:] » pay（ペイ）の意味 - goo国語辞書 https://t.co/yAY6NL836Q

<hr />

　深澤諭史弁護士のツイートで重みを感じたペイという言葉について調べてみました。やはり採算や引き合うという意味があるようです。事務所や事務用品の経費というのは、弁護士以外の自営業者にも共通するものかと思いますが、仕入れや在庫というマイナス要因は余りないように思えます。

　弁護士資格をとるまでにかけた時間や出費を投資と考える向きも弁護士には根強く感じておりますが、それは人それぞれの事情や考えもあることなのでしょう。ほかに深澤諭史弁護士で特徴的なのは「消費者被害」になりますが、これを非弁という枠の中でのみ捉えているように見えます。

＜＜＜2019-08-10（土曜日）17：42＿［これまでの記述範囲の終了時刻］＜＜＜

