#+TITLE: "弁護士会は、会員を外部脅威から守る対策を考えてほしいなと思います（業務妨害とか病気とか）←　深澤諭史弁護士のリツイートとして"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-08-10 20:50:15 +0900
FILE_NAME: 2019-08-10-205015_弁護士会は、会員を外部脅威から守る対策を考えてほしいなと思います（業務妨害とか病気とか）←　深澤諭史弁護士のリツイートとして.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags: 向原栄大朗弁護士（福岡県弁護士会）  深澤諭史弁護士 弁護士会
記事タイトル名の文字数：62　保存ファイル名の文字数：84

* 弁護士会は、会員を外部脅威から守る対策を考えてほしいなと思います（業務妨害とか病気とか）←　深澤諭史弁護士のリツイートとして
  :LOGBOOK:
  CLOCK: [2019-08-10 土 20:51]--[2019-08-11 日 00:31] =>  3:40
  :END:

＞＞＞2019-08-10（土曜日）20：51＿［これからの記述範囲の開始時刻］＞＞＞

＞＞＞2019-08-10（土曜日）20：51＿［これからの記述範囲の開始時刻］＞＞＞

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 20:52／2019-08-10 20:43 URL： https://twitter.com/kk_hirono/status/1160156960286629888 https://twitter.com/s_hirono/status/1160154702736003073
&twitter(1160156960286629888){theme:light}
> 2019-08-10-182528_向原総合法律事務所　弁護士向原さんはTwitterを使っています：　「@sokudokubengosi　弁護士会は、会員を外部脅威から守る対策を考えてほし.jpg https://t.co/eBoCyP5SOD
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 20:52／2019-08-10 20:43 URL： https://twitter.com/kk_hirono/status/1160157062149447685 https://twitter.com/s_hirono/status/1160154629574782976
&twitter(1160157062149447685){theme:light}
> 2019-08-10-182358_深澤諭史さんがリツイート向原総合法律事務所　弁護士向原@harrier0516osk·2h返信先：@sokudokubengosiさん弁護士会は、会員を外.jpg https://t.co/p9OoChyCIh
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 20:53／2019-08-10 20:42 URL： https://twitter.com/kk_hirono/status/1160157143963619330 https://twitter.com/s_hirono/status/1160154556342292480
&twitter(1160157143963619330){theme:light}
> 2019-08-10-175331_ローの弁解「きょきょ教育効果はごっご5年で消える」（笑）　｜　向原総合法律事務所／福岡の家電弁護士のブログ.jpg https://t.co/uXSVe1fksm
◁◁◁
<hr />

　スクリーンショットの記録は１８時２３分となっていました。深澤諭史弁護士のタイムラインでリツイートとして見た向原栄大朗弁護士のツイートですが、相乗効果で衝撃的なものを受けました。

　「病気」や「病院」をキーワードにした深澤諭史弁護士のツイートというのもこれまでに何度かまとめ記事を作成し、記録化の作業を行ってきたと思います。

```
[5283]  % dp -p|grep fukazawas |grep -E '(病気|病院)'
[link:] 2017年10月06日22時27分の登録： ％@fukazawas　深澤諭史％病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど， http://hirono2014sk.blogspot.com/2017/10/fukazawas_6.html
[link:] 2017年10月07日20時33分の登録： ％@fukazawas　深澤諭史％病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど http://hirono2014sk.blogspot.com/2017/10/fukazawas_63.html
[link:] 2017年10月08日09時06分の登録： ％@fukazawas　深澤諭史％手術中に病院が倒産。 異変に気が付いた患者家族が病院に駆けつけると，手術台には放置された患者が http://hirono2014sk.blogspot.com/2017/10/fukazawas_25.html
[link:] 2017年11月06日19時51分の登録： ＼深澤諭史　@fukazawas　RT：　@Isseki3＼病んでいる人に必要なのは相談に乗ることではなくてちゃんとした病院に連れて行くこと http://hirono2014sk.blogspot.com/2017/11/fukazawasrtisseki3.html
[link:] 2017年11月09日14時38分の登録： ％@fukazawas　深澤諭史％夫婦別姓の件にしろ，同性婚の件にしろ，日本人には，\n「他人が自由にするのが許せない病」\nという，病気が蔓延している気がする。 http://hirono2014sk.blogspot.com/2017/11/fukazawasnn.html
[link:] 2018年01月15日20時20分の登録： REGEXP：”病気”／深澤諭史（@fukazawas）の検索（2017-01-11〜2017-11-16／2018年01月15日20時20分の記録48件） http://hirono2014sk.blogspot.com/2018/01/regexpfukazawas2017-01-112017-11.html
[link:] 2018年01月15日20時26分の登録： ％@fukazawas　深澤諭史％ローカス先生のツイートって、\n「病気は神様の罰だから、祈祷だけすべき！治療をすすめる医者は悪魔の使いだ！」\nという人達を説得して予防接種や治療の普及を目指す医師の姿に重なりますね。 http://hirono2014sk.blogspot.com/2018/01/fukazawasnn.html
[link:] 2018年04月16日17時00分の登録： ％@fukazawas　深澤諭史％病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下 http://hirono2014sk.blogspot.com/2018/04/fukazawas_80.html
[link:] 2019年01月31日19時05分の登録： ＼深澤諭史　@fukazawas＼これの類例で、いろんな病院に片っ端から電話をかけながら、自分のお腹を切り始める人も結構いますね。\n（・∀・；） http://hirono2014sk.blogspot.com/2019/01/fukazawas_31.html
[link:] 2019年03月20日20時47分の登録： ＼深澤諭史　@fukazawas＼20日午後３時半前、東京 霞が関にある東京家庭裁判所の玄関付近で31歳の女性がいきなり男に刃物で刺され、搬送先の病院で死… http://hirono2014sk.blogspot.com/2019/03/fukazawas20-31.html
[link:] 2019年05月26日10時55分の登録： ＼深澤諭史　@fukazawas　RT：　@fukazawas＼病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど http://hirono2014sk.blogspot.com/2019/05/fukazawasrtfukazawas_26.html
[link:] 2019年06月24日22時39分の登録： REGEXP：TEXT　”病院”／深澤諭史（@fukazawas）の検索（2013-03-04　17：24〜2019-06-22　11：36／2019年06月24日22時39分の記録127件） http://hirono2014sk.blogspot.com/2019/06/regexptextfukazawas2013-03-0417242019_24.html
[link:] 2019年06月25日21時34分の登録： ＼浜ちゃん　@lawer_hamachan　RT：　@fukazawas＼病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみた http://hirono2014sk.blogspot.com/2019/06/lawerhamachanrtfukazawas.html
[link:] 2019年07月25日09時51分の登録： REGEXP：”病院”／深澤諭史（@fukazawas）の検索（2013-02-22〜2019-06-30／2019年07月25日09時51分の記録135件） http://hirono2014sk.blogspot.com/2019/07/regexpfukazawas2013-02-222019-06.html
```

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sokudokubengosi（ワーキングプア弁護士） 日時：2019-08-10 21:02／2019-08-09 22:24 URL： https://twitter.com/kk_hirono/status/1160159515586596865 https://twitter.com/sokudokubengosi/status/1159817821955579904
&twitter(1160159515586596865){theme:light}
> 弁護士が餓死しようが犯罪者になろうが誰も悲しまない。むしろどういう訳か好奇と嘲笑にさらされる。驚くことに同業者ほど身内に手厳しい。どんなに下手を打ってもあそこまではおちないだろう(おちたくない)という内心の表れなのかもしれない。… https://t.co/ny6w6h1OAi
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜harrier0516osk（向原総合法律事務所　弁護士向原） 日時：2019-08-10 21:02／2019-08-10 16:05 URL： https://twitter.com/kk_hirono/status/1160159533374664705 https://twitter.com/harrier0516osk/status/1160084759931867138
&twitter(1160159533374664705){theme:light}
> @sokudokubengosi 弁護士会は、会員を外部脅威から守る対策を考えてほしいなと思います（業務妨害とか病気とか）。要らないことに使う会費分を減らし、その分、自分で保険に入りたいですね。これだけの高い会費を、公益だから、の一言で済まされちゃ納得行かないですね。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜cultamnistagoem（cultamnistagoem*KyoAniStrong!*） 日時：2019-08-10 21:02／2019-08-10 08:55 URL： https://twitter.com/kk_hirono/status/1160159594359824384 https://twitter.com/cultamnistagoem/status/1159976562046853126
&twitter(1160159594359824384){theme:light}
> @sokudokubengosi @popohito 一般論で、しかも釈迦に説法で大変恐縮ですが、弱い立場の人、弱い組織団体であればあるほど、これらに必要なのは、理解、共感、連帯です。被告人、被疑者、中小社長、労働者などの権利を擁… https://t.co/8n2UvRxtOF
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜sokudokubengosi（ワーキングプア弁護士） 日時：2019-08-10 21:03／2019-08-10 19:46 URL： https://twitter.com/kk_hirono/status/1160159649275895811 https://twitter.com/sokudokubengosi/status/1160140264716898305
&twitter(1160159649275895811){theme:light}
> @cultamnistagoem それじゃあこの私が共感や連帯できる人間かと言ったらね、全く協調性が無いんですね。団体行動嫌いな奴が一匹狼でも生きていける資格取っちゃったから、厄介なんですね。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜ifujimoto（藤本一郎 Fujimoto Ichiro） 日時：2019-08-10 21:03／2019-08-10 14:22 URL： https://twitter.com/kk_hirono/status/1160159669618237441 https://twitter.com/ifujimoto/status/1160058696530927616
&twitter(1160159669618237441){theme:light}
> @sokudokubengosi そう感じますね。。
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜masa_shigemo（重本雅美） 日時：2019-08-10 21:03／2019-08-10 18:39 URL： https://twitter.com/kk_hirono/status/1160159706414895104 https://twitter.com/masa_shigemo/status/1160123485777096704
&twitter(1160159706414895104){theme:light}
> @sokudokubengosi 事務員女性と肉体関係になって、旦那さんに竿をちょん切られた弁護士もいましたね。
◁◁◁
<hr />

　これまで向原栄大朗弁護士のツイートとしてみてきた弁護士会に対する不満は、犯罪被害者の見舞金反対と死刑反対でした。見舞金反対のことは今日ひさしぶりに思い出したのですが、横領する弁護士のことを泥棒と断罪していたかと思います。

```
[5284]  % dp -p|grep 向原 |grep -E '(泥棒|死刑)'
[link:] 2017年10月31日14時49分の登録： ＼向原総合法律事務所　弁護士向原　@harrier0516osk＼\nこういうのこそ弁護士会長声明だせばいいのにと思うのは私だけか？死刑廃止とかで声明出すくらいなら http://hirono2014sk.blogspot.com/2017/10/harrier0516osk_22.html
[link:] 2018年05月13日21時54分の登録： ＼奉納＼さらば弁護士鉄道・泥棒神社の物語　@hirono_hideki＼\n\n.深澤諭史弁護士や小倉秀夫弁護士、モトケンこと矢部善朗弁護士（京都弁護士会）、向原栄大朗弁護士 http://hirono2014sk.blogspot.com/2018/05/hironohideki_13.html
[link:] 2018年05月25日21時07分の登録： REGEXP：”泥棒”／向原総合法律事務所　弁護士向原（@harrier0516osk）の検索（2011-04-22〜2017-12-03／2018年05月25日21時07分の記録28件） http://hirono2014sk.blogspot.com/2018/05/regexpharrier0516osk2011-04-222017-12.html
[link:] 2018年06月25日21時00分の登録： ＼向原総合法律事務所　弁護士向原　@harrier0516osk＼こんなことしてるから弁護士は社会から受け入れられないとも思える。その結実が死刑廃止とかだとなおさらですわ http://hirono2014sk.blogspot.com/2018/06/harrier0516osk_41.html
[link:] 2018年07月10日21時46分の登録： ＼向原総合法律事務所　弁護士向原　@harrier0516osk＼司法改革真理教、法科大学院真理教、裁判員制度真理教、死刑廃止真理教、公益活動真理教、弁護士自治真理教、護 http://hirono2014sk.blogspot.com/2018/07/harrier0516osk_10.html
[link:] 2019年08月08日00時02分の登録： ＼向原総合法律事務所　弁護士向原　@harrier0516osk＼死刑には金出すが非弁には出さないというよくわからない序列がなくなるといいのですが、頑張ってみますが、なか http://hirono2014sk.blogspot.com/2019/08/harrier0516osk_8.html
```

```
[5285]  % dp -p|grep 向原 |grep -E '犯罪.*被害者'
[link:] 2017年10月13日19時42分の登録： ＼向原総合法律事務所　弁護士向原　@harrier0516osk＼\n以前、ある弁護士が人権大会で犯罪被害者側弁護士の発言が「時間の浪費」といって物議を醸したけどさ、常議員会とか総会で http://hirono2014sk.blogspot.com/2017/10/harrier0516osk_13.html
```

```
▶（02／28） TW harrier0516osk（弁護士法人向原・川上総合法律事務所　向原） 日時：2016-07-28 19：43 URL： <https：//twitter.com/harrier0516osk/status/758477958562533380>
{% tweet 758477958562533380 %}
> ていうか、なんで日弁連は、俺たちまっとうにやっている弁護士の業務円滑化や福利厚生には殆ど投資しないのに、泥棒弁護士の尻拭いに私らの会費をつぎ込むのか、全然理解できない。 \n #被害弁償基金　#日弁連

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”泥棒”／向原総合法律事務所　弁護士向原（@harrier0516osk）の検索（2011-04-22〜2017-12-03／2018年05月25日21時07分の記録28件） http://hirono2014sk.blogspot.com/2018/05/regexpharrier0516osk2011-04-222017-12.html
```

　久しぶりに見た向原栄大朗弁護士のツイートですが、２０１７年７月２８日となっていました。これまでに何度か取り上げてきたと思いますが、福岡県弁護士会では弁護士による多額の横領、詐欺事件がありました。弁護士会の責任も追求されていたかと思います。

　本日、向原栄大朗弁護士の過去のツイートを調べていると、弁護士会の会費が年間で６０万円とありました。この弁護士会の会費というのは単位会によって大きなばらつきがあるとも聞きます。以前に見た情報の記憶も薄れているので、６０万円が相場でどうなのか判断はつきませんでした。

　この弁護士会の会費というのは、弁護士自治が大前提にあると聞きます。弁護士の懲戒が弁護士会によってしか行えないのもその弁護士自治のためだと聞きます。公権力からの独立性という話も聞きますが、個人的にまったく信頼のおけるものではなく、甚だしい時代錯誤の悪弊だと見ています。

　その弁護士業界の実態を裏付ける向原栄大朗弁護士のツイートだと私はみていました。向原栄大朗弁護士ご本人は、まっとうな弁護士業務で市民に迷惑をかけるつもりなど毛頭ないという確信や信念があるのかもしれません。しかし、岡山と福岡の弁護士の事件を見ただけでも、空恐ろしものを感じます。

[link:] » 福岡弁護士会　横領 - Google 検索 https://t.co/T174kWTIze

<hr />
[link:] » 福岡県で続発する弁護士不祥事＠恵比寿の弁護士のブログ|渋谷・恵比寿の弁護士への相談は田瀬英敏法律事務所へ https://t.co/qQpVnPf3ec

<hr />
[link:] » 弁護士 小松亀一法律事務所_弁護士等_岡山元弁護士巨額横領事件刑事事件第２回公判等報道記事掲載 https://t.co/Df6dRVi2Uc

<hr />
[link:] » 福岡県弁護士会　横領 - Google 検索 https://t.co/aKTtCA57TQ

<hr />
[link:] » 高橋浩文元弁護士の横領事件について所属弁護士会の指導監督責任を認めない判決 弁護士自治を野放しにする司法では、ますます弁護士不祥事は増加するでしょう。 – 鎌倉九郎 https://t.co/LUE6HHBMIq \n 福岡県弁護士… https://t.co/rMAGDqBdMT

<hr />
弁護士会が指導監督を怠ったためだとして、県内企業２社と男性１人が県弁護士会を相手取り総額約２億３０００万円の損害賠償を求めた訴訟の判決が２７日、福岡地裁であった。倉沢守春裁判長は「弁護士会の指導監督が必要といえる具体的事情はなかっ… https://t.co/c7KbmxUsP1

<hr />
倉沢裁判長は「弁護士の職務の独立性や守秘義務などがあり、弁護士会が指導監督できるのは明らかに違法な弁護活動などの場合に限られる」と指摘。その上で「預かり金が返還されないなど高橋元弁護士への苦情は弁護士会に多数寄せられていたが、当時… https://t.co/B4wsg8FO0C

<hr />
法曹倫理に詳しい早稲田大大学院の石田京子准教授は「『弁護士自治』を掲げる以上、金銭の処理に問題ありと認められる場合には、積極的に口座開示を求めるなど、さらに内部規律を強めて再発防止に取り組むべきだ」と話している。 https://t.co/LUE6HHBMIq

<hr />
高橋元弁護士氏は依頼者から、２００８～１２年、「保全命令の申し立てに保証金が必要」などとうそを言い、計約４億３９００万円を詐取。預かった和解金３０００万円を着服したのだ、これは明らかに違法な弁護活動ではないのではないのであろうか？ https://t.co/LUE6HHBMIq

<hr />
こんな犯罪行為も所属弁護士会は「弁護士の職務の独立」を理由に放置しておいて良いという裁判所の判断は一般常識からかけ離れている事は間違いないだろう。 https://t.co/LUE6HHBMIq

<hr />
金に関する苦情が寄せられていたにも関わらず「当時の状況では預り金の流用や詐欺を疑う事はできない」と判断しているが全く意味が分からない。市民窓口などに寄せられる苦情などクレーマーのたわごとだから、何を言っているのか分からないという司… https://t.co/sF3RTYmcu7

<hr />
裁判所が「弁護士の弁護士による弁護士の為の弁護士自治」を認めたのであれば、さらに弁護士不祥事は増え続けるだろう。弁護士の「職務の独立」とは国家権力などに介入されないために必要なのであって、欠陥弁護士の犯罪行為の隠れ蓑に使われるもの… https://t.co/qkf0HxQUjg

<hr />
弁護士自治において弁護士への懲戒権を独占している各単位弁護士会が、一般市民の苦情に対してまともに応対せず、国民の弁護士による被害が増加しても構わないと裁判所が判断したのだから、画期的な判決である。ますます国民への司法への不信が高ま… https://t.co/F4A55Rzx9I

<hr />

　そういえば長い間見かけていなかったと気がついたのですが、「高橋浩文元弁護士（福岡）懲役14年の判決・巨額詐欺事件 ( 事件 ) – 弁護士自治を考える会」というサイトがリンク切れとなっていました。運営者の実名も思い出せません。

　「弁護士自治を考える会」というサイト名ですが、以前は「弁護士と闘う」となっていたように思います。弁護士の不祥事や事件、懲戒処分については唯一に近い情報源でした。ちょっと調べてみたいと思います。なにか情報がみつかるかもしれません。

[link:] » 弁護士自治を考える会 - Google 検索 https://t.co/o5Bl7bhIZh

<hr />
[link:] » 弁護士自治を考える会 – 共に考えましょう　弁護士自治・法曹倫理 https://t.co/E8RbrexKPr

<hr />

　そういえば先ほどリンク切れとなっていたのはYahooのブログだったかもしれません。Yahooのブログは、半年から一年ほど前に、サービス終了のアナウンスを見かけていたことを思い出しました。そのあと話題も見かけてはいなかったですが、すでに終了済みのサービスなのかも知れません。

```
【法人準備室】京都市右京区常盤出口町１２の６
【　メール　】for_fairly@yahoo.co.jp
【ファックス】０３（４３３０）６１７１　※　東京事務所

弁護士自治を考える会は現在、法人団体化に向けて準備を進めています。
弁護士自治を考える会　法人化に向けて　2016年 10月24日公表記事：https：//jlfmt.com/2016/10/24/30955/

［source：］弁護士自治を考える会 – 共に考えましょう　弁護士自治・法曹倫理 https://jlfmt.com/
```

　掲載されたメールアドレスがYahooのドメインとなっています。もうずいぶん長い間、見かけることもなく忘れきっていたので、消滅したか、運営者が逮捕服役した可能性まで想像したのですが、法人団体化に向けて準備を進めているとの近況です。

　代表者の名前は見当たらないですが、住所が京都市右京区と番地まで掲載されています。代表者が京都市在住というような情報は、ずっと前に見かけていましたが、京都弁護士会は伏魔殿や魔境のような存在感と思いながら、弁護士の不正を公にするこのサイトのことはすっかり忘れていました。

[link:] » 弁護士自治を考える会（@bengoshijichi）さん / Twitter https://t.co/BLSKHVwMaX

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bengoshijichi（弁護士自治を考える会） 日時：2019-08-10 21:50／2019-07-17 11:00 URL： https://twitter.com/kk_hirono/status/1160171607182069761 https://twitter.com/bengoshijichi/status/1151310650204811266
&twitter(1160171607182069761){theme:light}
> 判決文偽造弁護士に懲役1年6月執行猶予3年　大阪地裁 \n  離婚事件で良い結果が出なかったからと、鈴木健介弁護士（大阪） \n  https://t.co/xkJ5SHKCOE
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bengoshijichi（弁護士自治を考える会） 日時：2019-08-10 21:50／2019-07-17 09:42 URL： https://twitter.com/kk_hirono/status/1160171627423813632 https://twitter.com/bengoshijichi/status/1151291037429559296
&twitter(1160171627423813632){theme:light}
> 依頼人の預り金を流用した弁護士に退会命令・神奈川県弁護士会 \n  以前にも預り金を流用し処分を受けていた。甘い処分で被害が拡大 \n  https://t.co/jjYrYBYlUY
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bengoshijichi（弁護士自治を考える会） 日時：2019-08-10 21:50／2019-07-15 13:19 URL： https://twitter.com/kk_hirono/status/1160171681832267776 https://twitter.com/bengoshijichi/status/1150620910530916352
&twitter(1160171681832267776){theme:light}
> 二弁の弁護士を住居侵入容疑で逮捕、山形署　さくらんぼテレビ \n  住所不詳だか西村あさひ法律事務所に勤務 \n  https://t.co/2CNs7aqa2q
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bengoshijichi（弁護士自治を考える会） 日時：2019-08-10 21:51／2019-07-12 12:59 URL： https://twitter.com/kk_hirono/status/1160171716645019648 https://twitter.com/bengoshijichi/status/1149528617744867328
&twitter(1160171716645019648){theme:light}
> 新たに北海道の弁護士3人が大量懲戒の懲戒請求者52人に1650万円賠償請求訴訟提起・・・・ \n  まだまだ続くのかな \n  https://t.co/aHaYoNPdqb
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜bengoshijichi（弁護士自治を考える会） 日時：2019-08-10 21:51／2019-06-07 09:19 URL： https://twitter.com/kk_hirono/status/1160171873872650240 https://twitter.com/bengoshijichi/status/1136789770233716736
&twitter(1160171873872650240){theme:light}
> 弁護士自治を考える会　　　ヤフーブログサービス終了のため引越しをしました。 \n  https://t.co/T0IAVHmCKU　　「弁護士自治を考える会」引き続きよろしくお願い致します
◁◁◁
<hr />

　Twitterアカウントの存在も初めて知ったように思いましたが、ざっとライムラインをみたところ、リツイートの数もほとんどが０から３で、一番多いので６となっていました。これだとリツイートとして見かけなかったのも不思議はないと思いましたが、検索結果に出てこなかったのが不思議です。

　プロフィール欄をみると、２０１０年８月からのTwitter利用とありました。９年間になるので一度もツイートを見かけなかったことはないように思えてきました。Twilogで確認をしてみたいと思います。

　一月ほど前の７月１６日にリツイートが１件ありました。すっかり忘れていましたが、これ１件のみというのがかえって不思議です。

▷ リツイート→hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞bengoshijichi（弁護士自治を考える会）｜2019/07/16 14:16／2019/07/15 13:19｜https://twitter.com/hirono_hideki/status/1150997594471981056 ／ https://twitter.com/bengoshijichi/status/1150620910530916352
&twitter(1150997594471981056){theme:light}
> RT @bengoshijichi: 二弁の弁護士を住居侵入容疑で逮捕、山形署　さくらんぼテレビ
> 住所不詳だか西村あさひ法律事務所に勤務
> https://t.co/2CNs7aqa2q  

　山形で弁護士が住居侵入で逮捕されたという事件。これもすっかり忘れていましたが、親族間のトラブルでそれも子供の親権を巡るものであったように思います。西村あさひ法律事務所はトップ３かトップ４に数えられる大手法律事務所として有名ですが、住所不詳が話題となっていました。

[link:] » 弁護士　住居侵入　山形 - Google 検索 https://t.co/gi81Ms8F3G

<hr />

　7月15日の逮捕とあるので、勾留期限も終わっていそうですが、起訴されたとも釈放されたとも続報は見当たりません。思い出したのですが、音楽著作権協会の潜入調査が同じ頃ニュースとなっていて、刑事処分を相当とするような弁護士のツイートも見かけていました。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「潜入調査」の検索結果 - Twilog https://t.co/ycjbj6TT5i

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-10 22:07／2019-07-10 01:59 URL： https://twitter.com/kk_hirono/status/1160175870809649152 https://twitter.com/hirono_hideki/status/1148637696069263362
&twitter(1160175870809649152){theme:light}
> 2019年07月10日01時58分の登録： REGEXP：”潜入調査”／データベース登録済みツイート：2019年07月10日01時57分の記録：ユーザ・投稿：29／40件 https://t.co/hd7iJsjKEF
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-10 22:07／2019-07-10 01:56 URL： https://twitter.com/kk_hirono/status/1160175895379709953 https://twitter.com/hirono_hideki/status/1148637048577781760
&twitter(1160175895379709953){theme:light}
> 2019年07月10日01時56分の実行記録 \n  APIのリミットに達するので8500で処理と中断しました。 \n  twitterAPI-search-lawList-mydql-add.rb "潜入調査" \n  ツイート数：12/1399 リツ… https://t.co/WJAT93CzND
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-10 22:07／2019-07-09 06:32 URL： https://twitter.com/kk_hirono/status/1160175915332063235 https://twitter.com/hirono_hideki/status/1148344174044835840
&twitter(1160175915332063235){theme:light}
> 全文表示 | 「JASRAC職員、音楽教室に潜入調査」報道　証拠になる？合法性は？有識者の見解を聞く : J-CASTニュース https://t.co/s8JBFePTWl
◁◁◁
<hr />

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 22:11／2019-07-09 07:28 URL： https://twitter.com/kk_hirono/status/1160176774224855040 https://twitter.com/s_hirono/status/1148358247134322689
&twitter(1160176774224855040){theme:light}
> 2019-07-09-065413_深澤諭史さんのツイート：　”「JASRAC職員、音楽教室に潜入調査」報道　証拠になる？合法性は？有識者の見解を聞く　　@jcast_newsより”.jpg https://t.co/6R21Ldw0e3
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 22:11／2019-07-09 07:28 URL： https://twitter.com/kk_hirono/status/1160176789253025794 https://twitter.com/s_hirono/status/1148358173662666752
&twitter(1160176789253025794){theme:light}
> 2019-07-09-065342_深澤諭史さんのツイート：　”コメントしましたお（＾ω＾）…　”.jpg https://t.co/7umcs1tCpd
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 22:11／2019-07-09 07:28 URL： https://twitter.com/kk_hirono/status/1160176811327684608 https://twitter.com/s_hirono/status/1148358099574542336
&twitter(1160176811327684608){theme:light}
> 2019-07-09-065054_JASRAC手法の合法性について、著作権に詳しい深澤諭史弁護士は7月8日、J-CASTニュースの取材に次のような見方を示した。.jpg https://t.co/zxQyE7aJgu
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 22:11／2019-07-09 07:27 URL： https://twitter.com/kk_hirono/status/1160176833335181314 https://twitter.com/s_hirono/status/1148358026375512064
&twitter(1160176833335181314){theme:light}
> 2019-07-09-063220_全文表示　｜　「JASRAC職員、音楽教室に潜入調査」報道　証拠になる？合法性は？有識者の見解を聞く　：　J-CASTニュース.jpg https://t.co/NvGFPTMThX
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 22:11／2019-07-09 07:27 URL： https://twitter.com/kk_hirono/status/1160176852805156865 https://twitter.com/s_hirono/status/1148357953679794176
&twitter(1160176852805156865){theme:light}
> 2019-07-09-063034_全文表示　｜　「JASRAC職員、音楽教室に潜入調査」報道　証拠になる？合法性は？有識者の見解を聞く　：　J-CASTニュース.jpg https://t.co/goq8bv5kM3
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2019-08-10 22:11／2019-07-09 07:27 URL： https://twitter.com/kk_hirono/status/1160176875672485891 https://twitter.com/s_hirono/status/1148357879969173504
&twitter(1160176875672485891){theme:light}
> 2019-07-09-062700_ですから、詐欺罪などに問われる可能性は、ゼロではないものの低いと思います」.jpg https://t.co/hBKn7j6M5F
◁◁◁
<hr />

　深澤諭史弁護士の記事のコメントのことも思い出しました。改めて見ると「詐欺罪などに問われる可能性は、ゼロではないものの低いと思います」となっていました。など、という含みもありますが、詐欺罪であれば二項詐欺の可能性を指摘したかと思います。ずいぶん厳し目の見立てです。

　財産上不法の利益を得たというのが二項詐欺の構成要件ではなかったかと思います。職員が潜入調査で会社から給与を得ていたことが、不法の利益だとすると、ずいぶんゆるやかな犯罪の認定であり、深澤諭史弁護士らしい極論の一つかとは考えいました。

```
（詐欺）

第二百四十六条 　人を欺いて財物を交付させた者は、十年以下の懲役に処する。

２ 　前項の方法により、財産上不法の利益を得、又は他人にこれを得させた者も、同項と同様とする。

引用元：刑法246条

［source：］詐欺罪の法定刑は10年以下の懲役｜詐欺罪の基礎知識と逮捕要件まとめ｜あなたの弁護士 https://yourbengo.jp/keiji/436/
```

　上記は引用部分の引用になります。「又は他人にこれを得させた者も、同項と同様とする。」という部分は私の記録と知識にありませんでした。これだと潜入調査を行った職員が、JASRACに財産上不法の利益を得させた、という理屈もありえないのではないのかもしれません。

　薬物使用者の女性の性器を舐め回したため、薬物反応が出たという主張を受け容れ無罪判決を出したという事例は、弁護士らのツイートのおもしろネタ扱いで見かけたことがあります。

　確認のためGoogleで検索しているのですが、それらしい情報が見つかりません。女性器を舐め回したではなく、薬物使用者の女性の尿を浴びるほど飲んだが、正しかったような気もしてきました。

▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜doshinweb（北海道新聞） 日時：2019-08-10 22:35／2017-02-03 16:10 URL： https://twitter.com/kk_hirono/status/1160182768862580736 https://twitter.com/doshinweb/status/827414051936296961
&twitter(1160182768862580736){theme:light}
> 「覚醒剤反応は使用者の尿を飲んだため」　男に無罪判決　地裁浦河支部 https://t.co/ZZ31rQlJ4K
◁◁◁
<hr />

　かろうじて情報を見つけましたが、記事はリンク切れでした。ほかに一般のツイートがもう1件、検索結果にあり、そちらには札幌地裁とありました。浦河というのは北海道の地名のようですが、聞き覚えもなくどのあたりか見当もつきません。

[link:] » 浦河支部 - Google マップ https://t.co/LAHbpRS1KX

<hr />

　札幌地裁浦河支部とあるので日本海側を想像したのですが、襟裳岬の近くに出てきたので驚きました。少なくとも北海道には他に、旭川地裁や釧路地裁がありそうな気がします。北海道の裁判所の管轄が４つに分かれているのを見たような気もします。

[link:] » 北海道の裁判所一覧。北海道地方裁判所、北海道簡易裁判所、家庭裁判所/特定調停・自己破産など債務整理の無料相談 https://t.co/2c65K17SK5

<hr />

　余り聞かないと思ったのですが、もう一つは函館地裁でした。函館地検は森友学園問題の大阪地検特捜部の女性特捜部長が検事正として栄転したことで話題となっていたことがありました。

　調べたところ札幌地裁には苫小牧支部や室蘭支部があるようですが、恵庭市は札幌地裁の本庁が管轄となるようです。恵庭OL殺害事件のことを思い出しました。

　室蘭といえば、警察がビルを買い取り解体までしたものの立件が出来なかったという事件のことを思い出します。それも向原栄大朗弁護士の気になったツイートで、調べたところ、知ることになった事件であったように記憶しています。

[link:] » (1) "室蘭" (from:harrier0516osk) - Twitter検索 / Twitter https://t.co/uWMO3qWVq3

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜harrier0516osk（向原総合法律事務所　弁護士向原） 日時：2019-08-10 22:56／2018-01-09 23:47 URL： https://twitter.com/kk_hirono/status/1160188223378739201 https://twitter.com/harrier0516osk/status/950740870269083648
&twitter(1160188223378739201){theme:light}
> 深澤先生と自分のフリートーク的な感じの時間も設けますが、ネタ満載になりそう。technical termの応酬にならんよう注意。室蘭事件とか富山事件とか
◁◁◁
<hr />

　深澤先生とは深澤諭史弁護士の可能性が高そうですが、他に深澤諭史弁護士とは別に深澤弁護士と呼ばれる弁護士がいることも情報としては見かけています。ツイートの内容は記憶になかったですが、富山事件とあるのは富山氷見強姦冤罪事件の可能性がありそうです。

　2018年1月9日のツイートというのも比較的最近のツイートでした。前後のツイートの流れが気になるところです。

　向原栄大朗弁護士も深澤諭史弁護士もTwilogの登録はありませんでした。深澤諭史弁護士はずっと前から登録がありませんが、確認したのは2,3ヶ月ほどぶりになるかもしれません。

[link:] » (1) (from:harrier0516osk) until:2018-01-10 since:2018-01-08 - Twitter検索 / Twitter https://t.co/V59oqSLrdx

<hr />

[link:] » (from:fukazawas) until:2018-01-10 since:2018-01-08 - Twitter検索 / Twitter https://t.co/o0vjAzCeQv

<hr />

　同じ期間の指定ですが、深澤諭史弁護士のツイートはわずかに6件のみの検索結果です。時刻をいれないと0時00分だけの指定になるのかもしれないですが、3日間の範囲となっているので、6件というのは納得がいきません。たまたま投稿が少なかった可能性はあるのかもしれないですが。

```
[5286]  % dp -p|grep fukazawas |grep -E '2018年01月09日'
[link:] 2018年01月09日21時56分の登録： ＼深澤諭史　@fukazawas＼「ネットに強い」ではしょっちゅうある。事件でも遭遇しないし，判例ＤＢにはいないし，著作も論文も，なにかで解説を書いたこともないのに「ネッ http://hirono2014sk.blogspot.com/2018/01/fukazawas_9.html
[link:] 2018年01月14日12時25分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2018年01月09日”：19件 http://hirono2014sk.blogspot.com/2018/01/fukazawas2018010919.html
```

　一日分だけでも19件あるので、やはりこれはおかしいと思いましたが、ほとんどがリツイートとなっていたので、いくらか納得しました。ただ、向原栄大朗弁護士のツイートと会話が成立するような内容のツイートは、どこにも見当たりませんでした。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2018年01月10日 - Twilog https://t.co/MyQ9t5yILI

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-10 23:20／2018-01-10 13:29 URL： https://twitter.com/kk_hirono/status/1160194229173252096 https://twitter.com/hirono_hideki/status/950947646872702976
&twitter(1160194229173252096){theme:light}
> 室蘭女子高生失踪事件 (千田麻未さん行方不明事件) https://t.co/tZNdfQdHyJ
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-10 23:20／2018-01-10 13:50 URL： https://twitter.com/kk_hirono/status/1160194249230446594 https://twitter.com/hirono_hideki/status/950952911407845376
&twitter(1160194249230446594){theme:light}
> 室蘭女子高生失踪事件　何かが抜け落ちている https://t.co/bXKIH1v02C
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-08-10 23:20／2018-01-10 16:20 URL： https://twitter.com/kk_hirono/status/1160194267043598337 https://twitter.com/hirono_hideki/status/950990715676487680
&twitter(1160194267043598337){theme:light}
> 【未解決事件】室蘭市で行方不明になった千田麻未さん(当時高校１年) の現在【バイト先のパン屋は今】 : 木になるニュースまとめ https://t.co/H9yBRUl1ns
◁◁◁
<hr />

　私が室蘭の事件について調べたのは、向原栄大朗弁護士のツイートの翌日の1月10日だったようです。

[link:] » 室蘭女子高生失踪事件 - zawazawa https://t.co/2RZ01y46ME \n 最終更新: 2019/04/05 (金) 23:39:16

<hr />

　あらためて調べてみると、2001年3月の失踪事件とのことです。平成13年というのはずいぶん前ですが、今年の4月5日にも情報提供を呼びかけるページは更新されているようです。

```
「パン屋のオーナーは店を閉めて、他の土地に移っていったのですが、その際に住んでいた家を取り壊したんです。警察は、更地になった土地にわざわざ重機を入れて、基礎からすべて掘り起こしているんです。彼女の遺体が埋まっているのではと疑っていたんです。警察からしてみれば、パン屋のオーナーが犯人に間違いないということだったんでしょう。しかし、千田さんに関連するものは何も出てきませんでした」

［source：］警察が重要人物の自宅跡を重機で掘り返すも未だ出てこない行方不明の女子高生｜八木澤高明 - 記事詳細｜Infoseekニュース https://news.infoseek.co.jp/article/knuckles_4139/
```

　記憶が劣化していることもあり、確認のため調べたのですが、簡単に情報は見つかりませんでした。上記の引用部分がようやく探し出せた記憶に近い情報ですが、警察が建物を解体したのではなく、解体で更地になった土地に重機を入れて掘り起こしたというのが実際のようです。

　更地となる前の建物で、痕跡を残さず遺体を地面に埋めるという作業が実現可能だったのか疑問ですが、更地に重機を入れて起訴から掘り起こしたことに警察の執念と決め手にかけたがとても怪しい犯人に違いないという印象操作があったとも考えられます。

```
ひたすら店主を容疑者として疑っているため、パトカーが事件発生後常にベーカリー店の前に駐車していて、それが気になって何度も店主が外に顔を出したのです。その様子が地元地域に伝わり、それによりあの店主は犯人という噂が広まっていきました。

当然そのような事が事実ではなくても噂としてたちまち広まってしまったら、そのベーカリー店に足を運ぶ買い物客が激減するのはあたりまえで、この後実際に閉店を余儀なくされてしまうのです。その後店主は遠い地に引越しをしたそうです。



［source：］室蘭女子高生失踪事件は現在も未解決！事件の概要や真相を徹底検証 | Leisurego | 3ページ目 | Leisurego - Part 3 https://leisurego.jp/archives/241091/3
```

```
北海道室蘭警察署のホームぺージにて行方不明者である彼女の関連ページ、関連コラムが存在していたのですが、去年の秋ごろにそのリンクが無くなってしまっています。2019年今年3月には、北海道新聞にて捜索情報が記載されたチラシが配布されたそうです。警察が現在捜査を行っているかは定かではありません。

［source：］室蘭女子高生失踪事件は現在も未解決！事件の概要や真相を徹底検証 | Leisurego | 4ページ目 | Leisurego - Part 4 https://leisurego.jp/archives/241091/4
```

　この室蘭の事件については、弁護士に関する情報を一切目にすることがなく、同じ頃に調べていた恵庭OL殺害事件については、非常に熱心な弁護士の活動がきわだち、対蹠的でした。

　警察が逮捕までしなかったので、弁護士が出てこなかったのもあるいは当然なのかもしれません。上記のページには、疑われた店主は、室蘭に戻り珈琲店を切り盛りしている、ともあるので、もともとそれほど強い嫌疑ではなかったような気もします。

　警察が見込み捜査で初動を誤ったという見方も多いようですが、そのあたりも気になる事件ではあります。

　なお、向原栄大朗弁護士のツイートの「室蘭事件」が、この未可決の女子高生失踪事件を指すものかどうかも不明です。

　今一度、Googleで「室蘭事件」と「富山事件」の検索を行ってみました。室蘭はほとんどが女子高生の失踪事件に関するものでした。富山事件もトップが氷見の冤罪事件でしたが、昨年あたりの警察官の拳銃を奪った殺傷事件もそれに次ぐ結果となっていました。

　室蘭と富山で向原栄大朗弁護士のツイートを検索してみましたが、検索結果は2,3件で、えん罪や失踪未解決事件に関するものはありませんでした。ますます、深澤先生も一緒に出てきたネタ満載ともいう向原栄大朗弁護士のツイートのミステリー性がきわだつ締めくくりです。

＜＜＜2019-08-11（日曜日）00：31＿［これまでの記述範囲の終了時刻］＜＜＜

