#+TITLE: "参考資料／冤罪／柳原病院事件／4代目という弁護士アカウントから発見→柳原病院事件乳腺外科医の控訴に反対する声明　｜　東京保険医協会"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2019-02-25 09:55:18 +0900
FILE_NAME: 2019-02-25-095518_4代目という弁護士アカウントから発見→柳原病院事件乳腺外科医の控訴に反対する声明　｜　東京保険医協会.org
CATEGORY: 石川県警察御中,金沢地方検察庁御中
tags:  柳原病院事件 冤罪 報道 ジャーナリストの江川紹子氏 高野隆弁護士 趙誠峰弁護士
記事タイトル名の文字数：65　保存ファイル名の文字数：72

#contents

* 4代目という弁護士アカウントのTwitterタイムラインで発見→柳原病院乳腺外科医師裁判の無罪判決を受けて、東京保険医協会は鶴田会長名で声明
  :LOGBOOK:
  CLOCK: [2019-02-25 月 10:02]--[2019-02-25 月 11:04] =>  1:02
  :END:

　弁護士会の会長声明というのは、これまでちょくちょく見てきたのですが、医療関係の協会会長が冤罪ともされる刑事事件について声明を出されています。これは4代目という弁護士アカウントという匿名弁護士アカウントのタイムラインでリツイートとして今朝、発見しました。

　この4代目という弁護士アカウントというアカウントについては、いわゆる法クラのTwitterアカウントでは比較的最近に知ったものだという認識ですが、ブロックをされていたようにも思います。イノシシにこだわりを持つ弁護士アカウントとしても印象的な存在感でした。

　ブロックについてはあとで確認をしておきたいと思いますし、弁護士業界とイノシシの関係についても記録をしておきたいと考えます。イノシシは豚が家畜化される前の自然界の動物と聞きますが、神秘的なところや人間と自然界との関わり方についても考えさせられる存在です。

▷ リツイート→4thlawyer（4代目）＞tokyohokeni（東京保険医協会）｜2019/02/21 18:02／2019/02/20 14:35｜https://twitter.com/4thlawyer/status/1098508309504524288 ／ https://twitter.com/tokyohokeni/status/1098093720593870848
&twitter(1098508309504524288){theme:light}
> RT @tokyohokeni: 柳原病院乳腺外科医師裁判の無罪判決を受けて、東京保険医協会は鶴田会長名で声明を発表しました。ホームページにアップしましたので、ご覧ください。＃乳腺外科医　＃裁判　https://t.co/0uViyBnD3K  

　紹介されているホームページの記事のタイトルは、「柳原病院事件乳腺外科医の控訴に反対する声明 | 東京保険医協会」です。このタイトルというのはHTMLのHEADダグでTITLEタグの中に記述された文字情報だと思いますが、取得は知識や経験がないと難しい場合があるかと思います。

　今は、TwitterやFacebookで記事を共有する、されると取得されたページタイトルが、ブログカードなどとも呼ばれるサムネイル画像付きで、見やすいデザインとして表示されることが多いので、普通に接しているものですが、いざ取得となると容易でない場合もあります。

　なかにはページ内リンクのクリックでページの内容が変わったのに、ページのタイトルが変わらないということも多々ありますが、情報の提供者が明示する情報になるので、あえてそうする場合もあるのかもしれないですが、不十分、不完全に感じる場合もあります。

　もっとも特徴的と思えるのが、Twitterの個別のツイートのタイトルなので、これをご紹介したいと思います。

渡辺輝人さんのツイート: "昨日の乳腺外科医の無罪判決について弁護団の一員の趙誠峰弁護士の所感。患者さんを悪く言わない態度は立派。 https://t.co/JWu4aKSI9k"

　これは東京保険医協会のTwitterアカウントのタイムラインでリツイートとして目にした渡辺輝人弁護士のツイートです。無罪判決が出た早い段階で見かけていたツイートでした。渡辺輝人弁護士についてもご紹介したことがあると思いますが、京都の弁護士です。

　どうも東京や関東方面というイメージが強い渡辺輝人弁護士ですが、京都市内の法律事務所で活動しているので、モトケンこと矢部善朗弁護士（京都弁護士会）と同じ京都弁護士会所属ということになるはずかと思います。

　「276件のリツイート 410件のいいね」というのが上記の渡辺輝人弁護士のツイートの反応です。この渡辺輝人弁護士と山口貴士弁護士のツイートは、弁護士アカウントのツイートでも突出してリツイート数が多いと感じてきました。

　渡辺輝人弁護士については、東京で活動していると考えている佐々木亮弁護士と似ていると感じてきました。ちょうど将棋の飛車角の関係性で、三浦義隆弁護士と刑裁サイ太についても長い間、よく似た関係性を感じてきました。類似点があるのだと思います。

▷ リツイート→tokyohokeni（東京保険医協会）＞nabeteru1Q78（渡辺輝人）｜2019/02/21 09:39／2019/02/21 09:35｜https://twitter.com/tokyohokeni/status/1098381750252654592 ／ https://twitter.com/nabeteru1Q78/status/1098380549473763333
&twitter(1098381750252654592){theme:light}
> RT @nabeteru1Q78: 昨日の乳腺外科医の無罪判決について弁護団の一員の趙誠峰弁護士の所感。患者さんを悪く言わない態度は立派。
> https://t.co/JWu4aKSI9k  

　渡辺輝人弁護士のTwitterタイムラインは、最近あまり見ていないのですが、こちらも労働問題を専門のように披瀝していたように思います。なにかの団体の理事か幹事だったように思います。

＜＜＜2019-02-25（月曜日）11：04＿［これまでの記述範囲の終了時刻］＜＜＜

* 東京保険医協会のTwitterアカウントにリツイートされていた京都第一法律事務所の渡辺輝人弁護士から考える、被害者のせん妄による冤罪とされた柳原病院事件
  :LOGBOOK:
  CLOCK: [2019-02-25 月 11:11]--[2019-02-25 月 16:05] =>  4:54
  :END:

＞＞＞2019-02-25（月曜日）11：11＿［これからの記述範囲の開始時刻］＞＞＞

　渡辺輝人弁護士が京都弁護士会所属であることを確認しようと思ったのですが、確認できる情報はすぐに見つかりませんでした。おそらくは京都弁護士会のホームページで確認するすべはあるかと思います。

　まず、次に掲載するのは渡辺輝人弁護士のTwitterアカウントのプロフィール情報です。

```
渡辺輝人
@nabeteru1Q78
弁護士／日本労働弁護団常任幹事、自由法曹団常任幹事、京都脱原発弁護団事務局長／京都第一法律事務所所属／残業代計算用エクセル「給与第一」開発者／労働者側の労働事件・労災・過労死事件などを手がけています。ツイッターみて来られた労働者の方の労働相談は無料。

京都市／府下
nabeteru.seesaa.net
2010年1月に登録

［source：］渡辺輝人(@nabeteru1Q78)さん | Twitter https://twitter.com/nabeteru1Q78
```

　上記の引用をするためブラウザの渡辺輝人弁護士のTwitterページをフォーカスすると、ツイートの更新が1件あり、読み込むと次のツイートになりますが、1分前と表示されました。内容とあわせ妙なタイミングだと少し思いました。

▶ ツイート％nabeteru1Q78（渡辺輝人）％2019/02/25 11:13％ https://twitter.com/nabeteru1Q78/status/1099854829877248000
&twitter(1099854829877248000){theme:light}
> こ、これは・・・。消防署の方から来ました、みたいな。 / 2件のコメント https://t.co/7rCZSJFAVg “2月22日「行テラス」相談事業がスタートします！ | 日本行政書士会連合会のプレスリリース” https://t.co/O90UilAP1i  
▶

　「行テラス」というのは、Twitterの弁護士アカウントの間で、ここ一週間のことだと思いますが、何度か見かけていました。他に意識が向いていたこともあり、深くは考えず、調べることもしていなかったのですが、渡辺輝人弁護士のツイートを見ると、実在するもののようです。

　まだ何も調べていないので確かなことはわかりませんが、「行テラス」は、弁護士らが「クソテラス」や「法寺」などと揶揄してきた不満満載の「法テラス」の、行政書士版ではと考えられます。この行政書士というのも非弁問題で、弁護士らの敵視を見ることがあります。

　渡辺輝人弁護士のツイートにある「消防署の方から来ました」ですが、これは実際、体験した言葉であり、昭和58年9月ころのこと、場所は福井県内で当時の武生市の辺りでした。被告発人安田敏が消火器販売を始めた頃の話です。ネットで書くのは初かもしれません。

　その訪問消火器販売ですが、私と被告発人安田敏が経験し、被告発人安田敏がその後も続けた昭和58年の前年ぐらいが、儲けのピークで業者の数が増え、競争が激しくなっていると聞いていました。その翌年ぐらいには社会問題として認識と警戒が広まり、下火になったようです。

　少なくとも被告発人安田敏が金沢市場輸送で市内配達の運転手として働いたという昭和60年の夏、その時点では被告発人安田敏も訪問の消火器販売をやめており、それ以降、金沢市や石川県で訪問消火器販売の問題を耳にすることはなかったと思います。

　ついでなので、これからネットで訪問の消火器販売について調べてみたいと思いますが、昭和の時代に終わったものとばかり思っていました。そのちょっと前に、京都第一法律事務所のホームページで、渡辺輝人弁護士が昭和53年生まれと見ていたので、なおさら不思議です。

　あるいは、弁護士として勉強した過去の資料として本などで得た知識なのかもしれません。また、私の方がその後、情報に接しなかっただけで、消火器の訪問販売は、その後も続いていたのかもしれません。

　なお、私の知る範囲で、消火器の訪問販売は明らかに違法とされるものではなかったので、現在の振り込め詐欺などとは違いも大きいと思います。被告発人安田敏自身が私に、新潟市内の警察署で事情聴取を受けたなどと話していましたが、逮捕勾留とは言ってなかったと思います。

　今考えると、かっこうが悪いので逮捕された事実を伏せていた可能性はありそうな気はします。新潟市内のことは私に記憶の混同があるのですが、そこでIらと3人ぐらいでシンナー遊びをして具合が悪くなり、金沢に戻ってから松原病院に行って、再入院になったなどとも聞いています。

```
平成31年1月11日	佐賀県	住宅用火災警報器	点検	住宅	20,000
概要：
平成31年1月11日（金）12時50分頃、私服姿の男性が被害者宅を訪問し、住宅用火災警報器の点検と称して料金を請求し、現金を持ち去ったもの。
被害にあった住人の記憶は曖昧であるが「煙の感知器の点検で来ました」ということで男性が訪問。住人が「消防署の依頼ですか」と尋ねると「そうです」と答えた。
部屋に上げると住宅用火災警報器を確認し、外観点検のみ行い（動作確認等はなし）点検料として18,000円程度の料金を請求された。
その後「65歳以上であれば後日返金される」などと言葉を掛け、お釣を取りに屋外に出て行ったまま帰って来なかったもの。

［source：］消防関係製品の悪質な訪問販売・詐欺等について 平成31年　：：　総務省消防庁 http://www.fdma.go.jp/html/life/accident/attention/index.html
```

```
平成29年12月26日	滋賀県	消火器	訪問販売	住宅	16,000
概要：
業者が一般住宅に、「消防署は忙しいので、業務委託を受けて消火器の販売を行っています。」と訪ねてきた。自宅の消火器を見てもらうと、「この消火器は古いので交換する必要がある。」との説明を受け、購入に応じると業務用消火器（10型）1本の購入費及び引取料として16,000円を請求され、その場で支払った。

［source：］消防関係製品の悪質な訪問販売・詐欺等について 平成29年　：：　総務省消防庁 http://www.fdma.go.jp/html/life/accident/attention/list29.html
```

　今でも消火器の訪問販売はあるようですが、組織的で大きな問題というのは聞いたことがありません。被告発人安田敏がやっていたのは、「中央防災」でした。社名だったのだと思いますが、事務所は金沢の旧赤線地帯「石坂（いっさか）」の近く、野田専光寺線に面したビルでした。

　その消火器の訪問販売の仕事は、私の方が少し先にやっていて、被告発人安田敏を紹介で入社させたというかたちでした。このあたりは羽咋市出身のIという暴力団関係者の存在が意味を持つのですが、前に観音堂のアパートについて書いたときも、Iのことは強く意識にのぼりませんでした。

　そのIと昭和58年当時、27歳か28歳と聞いていた紹介訪問販売の社長のその後が、被告発人安田敏から聞いた話で気になるものでした。その後も付き合いがあったとは被告発人安田敏の口から聞くことはなかったですが、付き合いがあった可能性はあり、私が知るより幅広いものかと思います。

　幅の広い人間関係、交際関係というのは一つ一つの付き合いが薄くなる傾向があることも私は経験しているので、過去に接点や付き合いがあったという以上のことはなにもわかりません。ただ、手掛かりとなったり、核心に迫るきっかけになる可能性はあると考えています。

　なかでも重要なのが、平成3年の春、被告発人安田敏が輪島屋鮮冷で4t車の長距離トラック運転手をしていたという事実です。被告発人安田敏は、珠洲市三崎出身のHMの紹介で入社したようなことを話していましたが、両者の接点も私の記録にあったのは昭和58年のことです。

　ついでに少しだけ書いておきますが、その訪問消火器販売では、HとOという男と一緒になりました。Oは岡山県に住んでいたといい岡山弁でしたが、その弟というのは、私が小林運送で長距離助手をしていたとき一緒でした。部屋に遊びに行ったことも少し記憶に残っています。

　弟の方は私と同級生だったと思います。兄の話も聞いていたので、その兄と出会ったのは不思議に思えることでした。被告発人安田敏と4人で、河北郡津幡町に消火器の訪問販売に行き、山の中で車が動かなくなったのですが、前後のことは記憶にありません。

　車の故障ではなく、海の砂浜でタイヤがはまり動けなくなった状況に似ていました。そういえば、夜中に砂浜でタイヤがはまり助けに来て欲しい、と長距離トラック運転手の運行から戻った時に妻から伝言を受けたことがありました。かなり長い間忘れていたように思います。

　詳しく具体的なことは、記憶が鮮明だった時期に書面化してきていると思います。プライバシーの問題もあるので、ここでは詳細を省いてもいます。私の記憶が曖昧になっている部分もありますが、HとOの二人は、金沢市の兼六元町の辺りの施設にいたと聞いたように思います。

　同じ兼六元町の辺りの施設の話は、昭和58年の夏に知り合った被告発人大網健二との共通の友人からも聞いていました。兼六元町というのは、便宜的に金沢市内の特定の場所を指していますが、はっきり裁判所の近くと聞いていた可能性もあります。

　前にも説明を書いたことがあると思いますが、金沢地方裁判所の前には大きな交差点があって、確認していないですが、その交差点の名称は兼六園下交差点となっていたように思います。

　時刻は13時33分です。4代目という弁護士アカウントですが、告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中(@kk_hirono)のアカウントはブロックされていませんでした。現時点の確認です。

　昼食はスパゲティを作って食べました。よくあるレトルトのミートソースでしたが、フライパンで炒めて食べるとけっこう美味かったです。スパゲティは3,4ヶ月ぶりに食べたと思いますが、これまでのところ食べるのは年に3,4回もあったのかという感じです。

　ここ1年以内だと思いますがスパゲティは他の麺類やお米に比較して太りにくいというような情報を見かけました。食べるとそこそこ美味しいとは思い、手軽に作れるということもあったのですが、実際に作って食べることは余りありませんでした。これまでの習慣の1つです。

　裁判所の近くの施設のことについては、金沢市森本の幼稚園のことと同じぐらい重要性か考えてきた事実関係ですが、これまで記述はのびのびとなっています。今日にも取り掛かりたいと思いますが、その前に渡辺輝人弁護士のことに区切りをつけておきます。

　渡辺輝人弁護士について京都弁護士会の所属として確認しておきたいとGoogleで検索してところ、出てきたのはツイートのアカウントと次の京都第一法律事務所のホームページです。そのホームページの情報は相当の分量となっています。つぶさに目は通していません。

［link：］ 渡辺 輝人 ｜ 京都第一法律事務所 https://www.daiichi.gr.jp/lawyer/watanabeteruhito/

　そういえば午前中、ブラウザでページタイトルの取得を実行したところ、この処理をキーボードのｔというキーに割り当てているのですが、リツイートの確認が表示されたので困りました。Twitterの設定でキーボード動作を無効に出来ないものか調べてみました。

　そのときメニューに「新しいTwitterを試す」というのがあったので、実行してみたところ、個別のツイートがタイムラインのように表示されていました。これまではタイムラインの中でポップアップのようにツイートが表示されていたのと、同じ操作だったと思います。

　ポップアップのウィンドウではなく、ページ全体が置き換わるので、レスポンスが悪く感じ元に戻したのですが、もう一度新しいTwitterに変更すると、レスポンスの違いは感じられませんでした。それでも前に見ていたタイムラインに戻るには、戻るボタンをクリックする必要があります。

　これを機会にブラウザの戻るをｂ，進むをｆとキーボードの割付を行いました。アドオンを使っています。戻るボタンまでマウスポインタを移動させクリックするというのも、けっこう馬鹿にならない手間の動作で、ツイートの詳細を開くことは多かったので、強くそれを感じました。

　時刻は16時03分です。このあと現在テレビで放送中の「記憶」というドラマについて、いくらか取り上げておきたいと思います。弁護士と法律事務所がドラマの舞台となっていますが、さきほど「病人が法曹界にいる資格はない」などという台詞がありました。

＜＜＜2019-02-25（月曜日）16：05＿［これまでの記述範囲の終了時刻］＜＜＜

* ごご☆プレ・記憶　【葬られた真実】＃11　2019年2月25日（月）　　15時53分～16時50分　　の放送内容

　この「記憶」というドラマは、先週の木曜と金曜日もテレビで放送をつけていましたが、集中して視聴はしていませんでした。新井という登場人物の名前が出てきたのも気になっていたのですが、今日の番組表の番組内容を見たところ、それらしい名前は見当たりません。

　直人というのが先週も気になったドラマの登場人物名でした。それが真犯人でもあるようなのですが、それらしい若い男をドラマで見たものの、筋が読めておらず、理解が出来ていません。

```
番組内容
逃げずに罪を償おうと警察に出頭する直人(三浦貴大)。だが、そこにいたのは三上(大西武志)だった。片桐(石丸謙二郎)と結託している三上は真面目に取り合おうとはせず、絶望した直人は行方を眩ませる。 一方、本庄(中井貴一)は片桐に「必ず罪を暴く」と宣戦布告をして事務所を去る。本庄を慕って付いて行く二宮(泉澤祐希)と初花(今田美桜)。片桐について調べる本庄たちは、当時御厨(水橋研二)の事件を管轄していた検事局に片桐が勤めていたことに気づく。同じ事件同じ事故に関わった本庄と片桐が、同じ事務所で働いていたことは偶然の一致ではないはず──そこに何かあると予感した本庄は、冤罪を訴え続けている御厨にもう一度弁護をさせて欲しいと頭を下げに行く。 再審請求を通すために、軽井沢の事件現場まで赴いて詳細に調べ直す二宮と初花。そうした動きを警戒する片桐は、本庄がアルツハイマーだとネットに噂を流す。世間は大騒ぎとなり、遥香(優香)や和也(宮澤秀羽)やひなた(落井実結子)といった家族にまで報道陣が殺到する。 窮地に追い込まれた本庄は──!

［source：］記憶 - Yahoo!テレビ.Gガイド［テレビ番組表］ https://tv.yahoo.co.jp/program/55249095/
```

　16時台という夕方の時間帯の再放送のドラマについては、昭和60年ころの「スクールウォーズ」と「スチュワーデス物語」が特に強く印象に残っています。最近では「HERO」を見ましたが、少し見ただけで、いつのまにか終わっていました。

＞＞＞2019-02-25（月曜日）16：37＿［これからの記述範囲の開始時刻］＞＞＞

　本当は16時07分からこの項目の記述を開始していたのですが、Mozcが日本語変換で固まるようになり、パソコンを再起動したのですが、時刻の記録をしないままEmacsを終了させていたので範囲の記録が出来ずにいました。

　この作業時間の記録というのは「CLOCK： [2019-02-25 月 16:37」などという書式となっています。今回は書式を一部変更しています。Emacsでテキスト属性が有効となっていて、なにか動作に支障が起こる可能性を回避しました。

　時刻は16時46分です。「記憶」の番組のエンディングロールが始まりました。再審開始の決定があって、そのあとの法廷の場面でなにかアクシデントがあったようです。次回が最終回とのことです。

　今回が11回目の放送なので、月曜日から金曜日まで週5回とすると、今日が3週目に入ったところになるようです。この「記憶」というドラマは、中井貴一が弁護士役ということで注目したのですが、ドラマの内容については当初関心がありませんでした。

　時刻は16時52分です。16時50分からプライムニュースが始まったのだと思いますが、22歳の男が児童養護施設の施設長を刺殺するという事件の報道がありました。容疑は殺人未遂となっていましたが、被害者はすでに死亡しているとのことです。

　被疑者は児童養護施設の元入所者で、恨みを抱き施設の関係者なら誰でも良かったなどと供述しているようです。被害者の年齢は46歳となっていたように思います。あるいは47歳ですが、昭和39年生まれの私よりだいぶん若く、昭和46年あたりの生まれになるものと思います。

　私より学年も６つ年下の被害者安藤文さんは昭和45年生まれなので、そこから計算をしましたが、その年齢で児童養護施設の所長あるいは施設長になると知り、時の経過の感慨深さがあります。事件は午後1時半ころとなっていたように思いますが、午前中に施設のことを書いていました。

　台所で昼食の支度をしているとき、施設のことを児童養護施設と書くべきかと考えていたのですが、昭和50年代以前は、単に「施設」というだけで、児童養護施設を指していたような気がします。強姦を暴行と読み替えるのが普通の時代でもあったので、配慮が一般化していたのかもしれません。

　また、施設で最初に思い出すのはテレビアニメの「タイガーマスク」です。辺田の浜に住んでいた小学校の低学年の放送と記憶にあるのですが、幼稚園のときであったような気もします。これが被告発人大網健二との最初の出会い、思い出として記憶にあることも書いていると思います。

```
放送期間	1969年10月2日 - 1971年9月30日
話数	全105話

［source：］タイガーマスク - Wikipedia https://ja.wikipedia.org/wiki/%E3%82%BF%E3%82%A4%E3%82%AC%E3%83%BC%E3%83%9E%E3%82%B9%E3%82%AF
```

　昭和44年10月2日から昭和46年9月30日の放送だったようです。少年マガジンに連載があったとも情報がありますが、漫画の雑誌というのは、ほとんど記憶がありません。そういわれればあった気もするという程度です。

　この手の計算が苦手なので自信は持てないですが、昭和46年4月というのが私が宇出津小学校に入学した年だったと思われます。幼稚園は宇出津小学校の旧校舎の裏側にありました。それは記憶にあります。

　宇出津の保育所は持木病院の斜め前にありましたが、部屋に入って何していたという記憶はないものの、大勢ですごく浅いプールで遊んでいたという場面だけが記憶にあります。小学生の頃は、そのプールがあった場所で遊ぶことがあり、隣に映画館がありました。

　その保育所は宇出津の大橋組という町内で、被告発人大網健二兄弟の町内であり、家からも近くでした。いわば縄張りのような感じでそこでよく遊んでいたと考えられますが、そこで兄弟を見たという記憶は残っていません。

　時刻は17時25分です。Twitterのトレンドですが、新しいTwitterの画面では、さらに表示を2回クリックすると、ページで一覧され、数えると22項目ありました。アカデミー賞関係のワードが多いですが、さきほどテレビで見た児童養護施設の刺殺事件は見当たりません。

［link：］ 児童養護施設で刺され死亡　元入所者「施設に恨み」：朝日新聞デジタル https://www.asahi.com/articles/ASM2T5283M2TUTIL022.html

　上記のニュース記事には午後1時50分ごろとあります。テレビでは見なかったと思う情報として、「施設を出てから4年がたっている」と逮捕直後に説明をしているようです。刃物で刺され死亡した施設長の年齢は46歳となっています。

　このあとテレビの情報番組でどのようにどの程度、報道されるのか気になるところですが、このような児童養護施設での施設関係者の殺傷事件というのは、余り見た記憶がなく、殺人事件というのは個人的に文字通り、前代未聞というところかと思います。

　この施設については、平成11年8月12日の午後8時ぐらい、金沢中警察署の取調室に入った直後のことについても書いておかなければならないことがあります。どの程度、どのようなかたちで書いておくかという迷いもずっとありました。

　モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士を許してはおけないという強い理由、動機のことでもあります。警察不信を安易に煽る弁護士の無責任、異常体質にも関わる問題です。見境知らずの弁護士脳です。

＜＜＜2019-02-25（月曜日）17：39＿［これまでの記述範囲の終了時刻］＜＜＜

＞＞＞2019-02-25（月曜日）20：30＿［これからの記述範囲の開始時刻］＞＞＞

　夕方は銭湯に行き、Aコープ能都店で買い物をしてきました。いったん家に戻って、炊飯のスイッチを入れてから牛乳を買い忘れていたこともあり、シメノドラッグにも買い物に行ってきました。外はまだ寒いですが、だいぶんましになってきたとは感じています。

　出かける前、テレビで松本清張の「砂の器」がドラマ化されるらしい情報を見かけていたので、落ち着いてからネットで調べてみました。これもこの前見た「疑惑」と同じで、現代に時代背景が変更されているようでした。さらになぜか犯人役の名前まで変わっているようでした。

　この項目ではテレビドラマの「記憶」について書いています。弁護士のアルツハイマーと再審が一緒になるドラマというのは想像もしなかったですが、アルツハイマーという脳の病気のことが知られるようになったのも平成に入ってからではなかったかと思います。

　その後だいぶん経ってから若年性アルツハイマーという症例も聞くようになりましたが、「記憶」のドラマはそちらの若年性になるのだと思います。ドラマの設定年齢が気になってきましたが、ネットで調べた情報によると、韓国ドラマのリメイク版とのことです。

　あまりよく理解できていないのですが、1年ほど前に地上波ではない有料の放送で人気を博したテレビドラマだったようです。私はそのような有料のテレビ放送を見たことがないので、そのあたりもよくわかっていません。

　夕方の16時台に過去のドラマが再放送されることは、たぶん昭和60年に見た「スクールウォーズ」か「スチュワーデス物語」が私にとって最初だったと思いますが、その最初にみた夕方のドラマの再放送のことは、いくらか不思議なぐらい印象的に記憶に残っています。

　時刻は20時50分です。つい今しがた、テレビのNHKで、金沢市で警察官2人にきりつけたという刑事裁判の報道がありました。被告は正当防衛として無罪を主張し、弁護人は心神喪失などを主張しているようです。

　その事件のことは少し記憶があって思い出したのですが、警察官は顔に重傷を負っていたとのことです。法廷の様子が映像か写真となっていましたが、裁判官に向かって左側が先に紹介され弁護人の説明がありました。その後は検察側の説明でしたが、どちらも机に2人が座っていました。

　いつ頃の事件だったかも思い出せないですが、半年以内ではないかと思います。全国ニュースになるようなことはなかったとも思いますし、事件が起こった金沢市内の場所というのも憶えてはいません。

　毎日20時45分からのNHKの番組ですが、土日は全国ニュースを交えて番組名が変わることもある感じですが、平日はほとんど「ニュースいしかわ８４５」という番組名になっていると思います。

　同じ番組だったと思いますが、2,3日前も気になるニュースがありました。金沢市大野町で別居中の妻にガソリンのような液体をかけライターで着火させ死亡させたという事件ですが、検察は殺意の立証が困難として傷害致死で起訴したとのことです。

　北陸中日新聞を購読していますが、いまだに中を開いて読むことが少なく、それもあって石川県内のニュースがわかっていないこともあるのですが、能登町の死体遺棄事件もその後どうなったのか情報がわかっていません。殺人罪として起訴されたというのが最後の認識かもしれませんが、不確かです。

[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「記憶」の検索結果 - Twilog https://t.co/RgI5ewoTv5

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 21:52／2019-01-17 22:03 URL： https://twitter.com/kk_hirono/status/1100015772720455681 https://twitter.com/hirono_hideki/status/1085885394879561728
&twitter(1100015772720455681){theme:light}
> スキャンダル専門弁護士 QUEEN - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/mP3mDIjXlR \n  　「あんころ餅」が食べたいという。斉藤由貴と思われる声。「あんころ餅」は昭和40年代の金沢名物と… https://t.co/jQht8ExTEs
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 21:52／2019-02-20 16:48 URL： https://twitter.com/kk_hirono/status/1100015794434367488 https://twitter.com/hirono_hideki/status/1098127254989598721
&twitter(1100015794434367488){theme:light}
> ごご☆プレ・記憶　【家族の絆】#8 \n   \n  2019年2月20日（水）  15時53分～16時50分  の放送内容 https://t.co/SnmtWBY215
◁◁◁
<hr />
[link:] » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年02月20日 - Twilog https://t.co/k6QtGiMRw2

<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 22:04／2019-02-20 20:04 URL： https://twitter.com/kk_hirono/status/1100018631306502144 https://twitter.com/hirono_hideki/status/1098176643569340416
&twitter(1100018631306502144){theme:light}
> » 「どの場面でも救えたのに」　逆転勝訴に笑顔なく　弁護士刺殺控訴審判決（毎日新聞） - Yahoo!ニュース https://t.co/Y4ULJ5FB6x
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 22:04／2019-02-20 20:02 URL： https://twitter.com/kk_hirono/status/1100018687648526337 https://twitter.com/hirono_hideki/status/1098176142643589120
&twitter(1100018687648526337){theme:light}
> » 何だコレ×林修ドリル 日本のナゾ大調査SP - Yahoo!テレビ.Gガイド[テレビ番組表] https://t.co/oAgtMKjrcE \n  ▽8時から林修ドリル縁結びで?箱根の神社に朝から大行列!芦ノ湖に竜の化身?
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜Toshimitsu_Dan（だんどじみつ） 日時：2019-02-25 22:11／2019-02-13 23:38 URL： https://twitter.com/kk_hirono/status/1100020461436428289 https://twitter.com/Toshimitsu_Dan/status/1095693736699297792
&twitter(1100020461436428289){theme:light}
> 秋田の弁護士刺殺、県も賠償責任 https://t.co/NDox1RtVNT
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 22:14／2019-02-20 18:15 URL： https://twitter.com/kk_hirono/status/1100021311600943104 https://twitter.com/hirono_hideki/status/1098149160061001728
&twitter(1100021311600943104){theme:light}
> » 乳腺外科医裁判で無罪判決、わいせつ行為否定（2月20日17時追記）｜医療維新 - https://t.co/yHOlg6m9YTの医療コラム https://t.co/W967sPLaOz
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 22:15／2019-02-20 17:44 URL： https://twitter.com/kk_hirono/status/1100021385827479554 https://twitter.com/hirono_hideki/status/1098141290024169472
&twitter(1100021385827479554){theme:light}
> » 巣鴨地蔵通り商店街 https://t.co/9sSU1ClYaG
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 22:15／2019-02-20 17:32 URL： https://twitter.com/kk_hirono/status/1100021408057290757 https://twitter.com/hirono_hideki/status/1098138213414187008
&twitter(1100021408057290757){theme:light}
> » 蒲田行進曲 /松坂慶子 - Bing video https://t.co/NVLsT8Jmm8
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 22:15／2019-02-20 11:30 URL： https://twitter.com/kk_hirono/status/1100021522129813516 https://twitter.com/hirono_hideki/status/1098047189937401856
&twitter(1100021522129813516){theme:light}
> » 祖父母を書類送検＝飼い犬にかまれ乳児死亡－警視庁｜ニフティニュース https://t.co/JRaJjiocOX
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 22:15／2019-02-20 11:28 URL： https://twitter.com/kk_hirono/status/1100021567025643524 https://twitter.com/hirono_hideki/status/1098046695969968128
&twitter(1100021567025643524){theme:light}
> » 安藤優子、体調不良のため「直撃ＬＩＶＥグッディ！」欠席　先月も2日連続で欠席｜ニフティニュース https://t.co/1ThHBf2VTL
◁◁◁
<hr />
▷▷▷リツイート▷▷▷
RT kk_hirono（告発＼市場急配センター殺人未遂事件＼金沢地方検察庁・石川県警察御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2019-02-25 22:16／2019-02-20 11:10 URL： https://twitter.com/kk_hirono/status/1100021596750721025 https://twitter.com/hirono_hideki/status/1098042062354604033
&twitter(1100021596750721025){theme:light}
> » 田畑議員に「乱暴された」、元交際女性が告訴 - 社会 : 日刊スポーツ https://t.co/ekSkgXBSTx
◁◁◁
<hr />
[link:] » 出征兵士を送る歌 - YouTube https://t.co/XZIBceEKXE

<hr />
[link:] » あゝ紅の血は燃ゆる - YouTube https://t.co/Z60qSSbWPE

<hr />
[link:] » ラバウル小唄 - YouTube https://t.co/2mubHfV4sS

<hr />
[link:] » 月月火水木金金 - YouTube https://t.co/ICdQdNnrto

<hr />
[link:] » 勇敢なる水兵【明治海軍軍歌･文部省唱歌】 - YouTube https://t.co/uaLRwxKpza

<hr />
[link:] » 月月火水木金金(艦隊勤務)【海軍軍歌･戦時歌謡】 - YouTube https://t.co/9Yf1H17uCS

<hr />
[link:] » 能登麦屋節2018最優秀賞者 - YouTube https://t.co/mPUFjonhu3

<hr />
[link:] » 星めぐりの歌　映画「あなたへ」より - YouTube https://t.co/e8QQFPbIa3

<hr />
[link:] » 星めぐりの歌　高畑充希 - YouTube https://t.co/ik3uU3twLV

<hr />
[link:] » 星めぐりの歌 - YouTube https://t.co/DTRnXX1zeq

<hr />
[link:] » 能登の祭り 小木とも旗祭り 2016 - YouTube https://t.co/AAGLc2WLgY

<hr />
[link:] » お小夜節(越中五箇山民謡保存会) - YouTube https://t.co/UAOwj9HOmi

<hr />
[link:] » 伊藤さやか【素敵にジングルベル】 - YouTube https://t.co/1IRJRuB6tq

<hr />
[link:] » 素敵にジングルベル～'Cause It's Christmas　伊藤さやか - YouTube https://t.co/rPt4bV0Tg2

<hr />

＜＜＜2019-02-26（火曜日）04：49＿［これまでの記述範囲の終了時刻］＜＜＜

＞＞＞2019-02-28（木曜日）10：02＿［これからの記述範囲の開始時刻］＞＞＞

　2月26日から中断していたことを確認しました。この日は昼過ぎから小木港にアジ釣りに行き、夜、遅めの時間に家に戻り、日付が変わった頃に、録画していた当日のテレビドラマ「記憶」の最終回を視聴しました。26日は火曜日だったことも記憶にあります。

　柳原病院事件ですが、その後、情報は一切見ていません。控訴されたという情報も見ていないですが、控訴の申し立て期限というのも14日間ではなかったかと思います。

＜＜＜2019-02-28（木曜日）10：09＿［これまでの記述範囲の終了時刻］＜＜＜

